/**
 * 날짜 낱장의 화면 문구 — 열 언어.
 *
 * 요일 이름은 `Intl.DateTimeFormat`이 언어마다 내주므로 여기 적지 않는다 —
 * 열 언어 × 일곱 요일을 손으로 적으면 70줄이고 곧 어긋난다.
 */
import type { AnyLocale10 } from '../locales.ts';

export interface DayUI {
  h1: (date: string) => string;
  metaTitle: (date: string) => string;
  metaDesc: (date: string, doy: string) => string;
  dateLabel: (m: number, d: number) => string;
  weekdayTitle: string;
  weekdayNote: (most: string) => string;
  weekTitle: string;
  weekRow: (year: string, week: string) => string;
  factsTitle: string;
  doy: (n: string) => string;
  quarter: (q: string) => string;
  leapNote: string;
  holidayTitle: string;
  publicHoliday: string;
  observance: string;
  nearbyTitle: string;
  note: string;
}

const MONTHS_EN = ['January','February','March','April','May','June','July','August','September','October','November','December'];

export const DAY_UI: Record<AnyLocale10, DayUI> = {
  ko: {
    h1: d => `${d}은 무슨 요일일까`,
    metaTitle: d => `${d} 요일·주차 — 연도별 요일표`,
    metaDesc: (d, n) => `${d}이 해마다 무슨 요일인지, 몇 주차인지 한 표로 봅니다. 그 해의 ${n}번째 날이고 분기와 기념일도 함께 적었습니다.`,
    dateLabel: (m, d) => `${m}월 ${d}일`,
    weekdayTitle: '연도별 요일',
    weekdayNote: most => `이 기간에는 ${most}이 가장 자주 걸립니다.`,
    weekTitle: 'ISO 주차',
    weekRow: (y, w) => `${y}년 · ${w}주차`,
    factsTitle: '날짜 정보',
    doy: n => `그 해의 ${n}번째 날입니다.`,
    quarter: q => `${q}분기에 속합니다.`,
    leapNote: '2월 29일은 윤년에만 있습니다 — 4년마다 한 번, 100으로 나뉘면 건너뛰고 400으로 나뉘면 다시 윤년입니다.',
    holidayTitle: '이 날의 기념일',
    publicHoliday: '법정공휴일',
    observance: '기념일',
    nearbyTitle: '가까운 날짜',
    note: '음력 명절(설날·추석)은 해마다 양력 날짜가 달라 여기 적지 않았습니다. ISO 주차는 그 주의 목요일이 속한 해를 따릅니다.',
  },
  en: {
    h1: d => `What day of the week is ${d}?`,
    metaTitle: d => `${d} — weekday by year and ISO week`,
    metaDesc: (d, n) => `Which weekday ${d} falls on in each year, plus its ISO week number. It is day ${n} of the year, with the quarter and any fixed observance.`,
    dateLabel: (m, d) => `${MONTHS_EN[m - 1]} ${d}`,
    weekdayTitle: 'Weekday by year',
    weekdayNote: most => `Over this span it lands on ${most} most often.`,
    weekTitle: 'ISO week number',
    weekRow: (y, w) => `${y} · week ${w}`,
    factsTitle: 'About this date',
    doy: n => `It is day ${n} of the year.`,
    quarter: q => `It falls in Q${q}.`,
    leapNote: 'February 29 exists only in leap years — every four years, skipped on centuries unless divisible by 400.',
    holidayTitle: 'Observances on this date',
    publicHoliday: 'Public holiday',
    observance: 'Observance',
    nearbyTitle: 'Nearby dates',
    note: 'Lunar holidays are not listed because their Gregorian date changes each year. ISO weeks follow the year of that week’s Thursday.',
  },
  es: {
    h1: d => `¿Qué día de la semana es el ${d}?`,
    metaTitle: d => `${d} — día de la semana por año y semana ISO`,
    metaDesc: (d, n) => `En qué día cae el ${d} cada año y su número de semana ISO. Es el día ${n} del año, con el trimestre y las efemérides fijas.`,
    dateLabel: (m, d) => `${d}/${m}`,
    weekdayTitle: 'Día de la semana por año',
    weekdayNote: most => `En este periodo cae en ${most} con más frecuencia.`,
    weekTitle: 'Semana ISO',
    weekRow: (y, w) => `${y} · semana ${w}`,
    factsTitle: 'Sobre esta fecha',
    doy: n => `Es el día ${n} del año.`,
    quarter: q => `Pertenece al ${q}.º trimestre.`,
    leapNote: 'El 29 de febrero solo existe en años bisiestos: cada cuatro años, salvo los seculares no divisibles entre 400.',
    holidayTitle: 'Efemérides de esta fecha',
    publicHoliday: 'Festivo oficial',
    observance: 'Efeméride',
    nearbyTitle: 'Fechas cercanas',
    note: 'No se incluyen las fiestas lunares porque su fecha cambia cada año. Las semanas ISO siguen el año del jueves de esa semana.',
  },
  'pt-br': {
    h1: d => `Que dia da semana é ${d}?`,
    metaTitle: d => `${d} — dia da semana por ano e semana ISO`,
    metaDesc: (d, n) => `Em que dia da semana ${d} cai a cada ano e o número da semana ISO. É o dia ${n} do ano, com o trimestre e as datas comemorativas fixas.`,
    dateLabel: (m, d) => `${d}/${m}`,
    weekdayTitle: 'Dia da semana por ano',
    weekdayNote: most => `Neste período cai mais vezes em ${most}.`,
    weekTitle: 'Semana ISO',
    weekRow: (y, w) => `${y} · semana ${w}`,
    factsTitle: 'Sobre esta data',
    doy: n => `É o dia ${n} do ano.`,
    quarter: q => `Está no ${q}.º trimestre.`,
    leapNote: '29 de fevereiro só existe em anos bissextos: a cada quatro anos, exceto séculos não divisíveis por 400.',
    holidayTitle: 'Datas comemorativas',
    publicHoliday: 'Feriado',
    observance: 'Data comemorativa',
    nearbyTitle: 'Datas próximas',
    note: 'Feriados lunares não entram porque a data no calendário muda a cada ano. Semanas ISO seguem o ano da quinta-feira daquela semana.',
  },
  ja: {
    h1: d => `${d}は何曜日？`,
    metaTitle: d => `${d} — 年ごとの曜日とISO週番号`,
    metaDesc: (d, n) => `${d}が年ごとに何曜日になるか、ISO週番号はいくつかを一覧で確認できます。その年の${n}日目で、四半期と記念日も載せています。`,
    dateLabel: (m, d) => `${m}月${d}日`,
    weekdayTitle: '年ごとの曜日',
    weekdayNote: most => `この期間では${most}になることが最も多いです。`,
    weekTitle: 'ISO週番号',
    weekRow: (y, w) => `${y}年 · 第${w}週`,
    factsTitle: 'この日について',
    doy: n => `その年の${n}日目です。`,
    quarter: q => `第${q}四半期です。`,
    leapNote: '2月29日は閏年にだけあります — 4年に一度、100で割れる年は除き、400で割れる年は閏年です。',
    holidayTitle: 'この日の記念日',
    publicHoliday: '祝日',
    observance: '記念日',
    nearbyTitle: '近い日付',
    note: '旧暦の祝日は毎年日付が変わるため載せていません。ISO週はその週の木曜日が属する年に従います。',
  },
  de: {
    h1: d => `Welcher Wochentag ist der ${d}?`,
    metaTitle: d => `${d} — Wochentag nach Jahr und ISO-Woche`,
    metaDesc: (d, n) => `Auf welchen Wochentag der ${d} in jedem Jahr fällt und welche ISO-Woche es ist. Es ist der ${n}. Tag des Jahres, mit Quartal und festen Gedenktagen.`,
    dateLabel: (m, d) => `${d}.${m}.`,
    weekdayTitle: 'Wochentag nach Jahr',
    weekdayNote: most => `In diesem Zeitraum fällt er am häufigsten auf ${most}.`,
    weekTitle: 'ISO-Kalenderwoche',
    weekRow: (y, w) => `${y} · KW ${w}`,
    factsTitle: 'Zu diesem Datum',
    doy: n => `Es ist der ${n}. Tag des Jahres.`,
    quarter: q => `Er liegt im ${q}. Quartal.`,
    leapNote: 'Den 29. Februar gibt es nur in Schaltjahren — alle vier Jahre, außer in Jahrhundertjahren, die nicht durch 400 teilbar sind.',
    holidayTitle: 'Gedenktage an diesem Datum',
    publicHoliday: 'Gesetzlicher Feiertag',
    observance: 'Gedenktag',
    nearbyTitle: 'Nahe Daten',
    note: 'Mondkalender-Feiertage fehlen, weil ihr Datum jedes Jahr wechselt. ISO-Wochen richten sich nach dem Jahr des Donnerstags jener Woche.',
  },
  fr: {
    h1: d => `Quel jour de la semaine est le ${d} ?`,
    metaTitle: d => `${d} — jour de la semaine par année et semaine ISO`,
    metaDesc: (d, n) => `Le jour de la semaine du ${d} selon l'année et son numéro de semaine ISO. C'est le ${n}e jour de l'année, avec le trimestre et les commémorations fixes.`,
    dateLabel: (m, d) => `${d}/${m}`,
    weekdayTitle: 'Jour de la semaine par année',
    weekdayNote: most => `Sur cette période, il tombe le plus souvent un ${most}.`,
    weekTitle: 'Semaine ISO',
    weekRow: (y, w) => `${y} · semaine ${w}`,
    factsTitle: 'À propos de cette date',
    doy: n => `C'est le ${n}e jour de l'année.`,
    quarter: q => `Elle se situe au ${q}e trimestre.`,
    leapNote: "Le 29 février n'existe que les années bissextiles : tous les quatre ans, sauf les années séculaires non divisibles par 400.",
    holidayTitle: 'Commémorations à cette date',
    publicHoliday: 'Jour férié',
    observance: 'Commémoration',
    nearbyTitle: 'Dates voisines',
    note: "Les fêtes lunaires ne figurent pas car leur date change chaque année. Les semaines ISO suivent l'année du jeudi de la semaine.",
  },
  hi: {
    h1: d => `${d} को कौन-सा दिन होता है?`,
    metaTitle: d => `${d} — वर्ष के अनुसार दिन और ISO सप्ताह`,
    metaDesc: (d, n) => `${d} हर वर्ष किस दिन पड़ता है और उसका ISO सप्ताह क्या है। यह वर्ष का ${n}वाँ दिन है, तिमाही और निश्चित तिथियों के साथ।`,
    dateLabel: (m, d) => `${d}/${m}`,
    weekdayTitle: 'वर्ष के अनुसार दिन',
    weekdayNote: most => `इस अवधि में यह सबसे अधिक ${most} को पड़ता है।`,
    weekTitle: 'ISO सप्ताह',
    weekRow: (y, w) => `${y} · सप्ताह ${w}`,
    factsTitle: 'इस तारीख़ के बारे में',
    doy: n => `यह वर्ष का ${n}वाँ दिन है।`,
    quarter: q => `यह ${q}वीं तिमाही में आता है।`,
    leapNote: '29 फ़रवरी केवल लीप वर्ष में आता है — हर चार साल में, पर शताब्दी वर्ष तभी जब 400 से विभाज्य हो।',
    holidayTitle: 'इस तारीख़ के अवसर',
    publicHoliday: 'सार्वजनिक अवकाश',
    observance: 'स्मृति दिवस',
    nearbyTitle: 'आस-पास की तारीख़ें',
    note: 'चंद्र कैलेंडर के त्योहार शामिल नहीं हैं क्योंकि उनकी तारीख़ हर साल बदलती है। ISO सप्ताह उस सप्ताह के गुरुवार के वर्ष के अनुसार चलता है।',
  },
  'zh-hans': {
    h1: d => `${d}是星期几？`,
    metaTitle: d => `${d} — 各年份星期几与ISO周数`,
    metaDesc: (d, n) => `${d}在各年份是星期几、ISO周数是多少，一表看清。它是当年的第${n}天，并附季度与固定纪念日。`,
    dateLabel: (m, d) => `${m}月${d}日`,
    weekdayTitle: '各年份的星期',
    weekdayNote: most => `这段期间里最常落在${most}。`,
    weekTitle: 'ISO周数',
    weekRow: (y, w) => `${y}年 · 第${w}周`,
    factsTitle: '关于这一天',
    doy: n => `是当年的第${n}天。`,
    quarter: q => `属于第${q}季度。`,
    leapNote: '2月29日只在闰年出现——每四年一次，逢百不闰，逢四百又闰。',
    holidayTitle: '这一天的纪念日',
    publicHoliday: '法定假日',
    observance: '纪念日',
    nearbyTitle: '相近的日期',
    note: '农历节日的公历日期每年不同，因此未列入。ISO周以该周星期四所在的年份为准。',
  },
  'zh-hant': {
    h1: d => `${d}是星期幾？`,
    metaTitle: d => `${d} — 各年份星期幾與ISO週數`,
    metaDesc: (d, n) => `${d}在各年份是星期幾、ISO週數是多少，一表看清。它是當年的第${n}天，並附季度與固定紀念日。`,
    dateLabel: (m, d) => `${m}月${d}日`,
    weekdayTitle: '各年份的星期',
    weekdayNote: most => `這段期間裡最常落在${most}。`,
    weekTitle: 'ISO週數',
    weekRow: (y, w) => `${y}年 · 第${w}週`,
    factsTitle: '關於這一天',
    doy: n => `是當年的第${n}天。`,
    quarter: q => `屬於第${q}季。`,
    leapNote: '2月29日只在閏年出現——每四年一次，逢百不閏，逢四百又閏。',
    holidayTitle: '這一天的紀念日',
    publicHoliday: '法定假日',
    observance: '紀念日',
    nearbyTitle: '相近的日期',
    note: '農曆節日的西曆日期每年不同，因此未列入。ISO週以該週星期四所在的年份為準。',
  },
};
