/**
 * 기호 이모지 30개의 뜻 — 열 언어. 화살표·재생·종교·카드·돈이 여기 있다.
 *
 * 이 갈래는 대부분 **U+FE0F가 붙어야 컬러로 나오는 글자**다. ➡️·▶️·♠️·✝️·☮️가
 * 모두 그렇고, 그 선택자가 빠지면 흑백 글자로 떨어진다. 복사해 붙일 때 잘리는
 * 자리가 여기여서, 그것이 실제로 문제 되는 항목에는 그 말을 적어 뒀다.
 *
 * 재생 단추(▶️⏸️⏹️⏭️⏮️)는 유니코드가 기기 화면에 쓰라고 넣은 기호이지 이모지로
 * 만든 것이 아니다. 그래서 회사마다 그림 차이가 크고, 흑백으로 나오는 자리도
 * 많다 — 원래 자리가 그림이 아니라 조작 단추였기 때문이다.
 *
 * 종교 기호는 무엇의 표시이고 누가 쓰는지만 사실로 적는다. 평가하지 않는다.
 *
 * 열 칸을 배열로 적는다 — 순서는 ko·en·es·pt·ja·de·fr·hi·zh·tw.
 */
import type { Ten } from './types.ts';

export const EM_DESC_MORE: Record<string, Ten> = {
  /* ───────── 화살표 ───────── */
  'right-arrow': ["오른쪽 화살표입니다. 다음 단계나 결과를 가리키는 데 쓰이고, 아랍어·히브리어처럼 오른쪽에서 왼쪽으로 읽는 화면에서는 흐름과 방향이 어긋나 보입니다.", "A right arrow. Used to point at the next step or the result, and on right-to-left screens in Arabic or Hebrew the direction runs against the reading flow.", "Una flecha derecha. Señala el paso siguiente o el resultado, y en pantallas de derecha a izquierda en árabe o hebreo la dirección va contra la lectura.", "Uma seta para a direita. Aponta o próximo passo ou o resultado, e em telas da direita para a esquerda em árabe ou hebraico a direção vai contra a leitura.", "右向きの矢印です。次の段階や結果を指すのに使い、アラビア語やヘブライ語のように右から左へ読む画面では流れと向きが合わなくなります。", "Ein Rechtspfeil. Er zeigt auf den nächsten Schritt oder das Ergebnis; auf rechts-nach-links laufenden Bildschirmen in Arabisch oder Hebräisch läuft er gegen die Leserichtung.", "Une flèche droite. Elle désigne l’étape suivante ou le résultat ; sur des écrans de droite à gauche en arabe ou en hébreu, elle contredit le sens de lecture.", "दाईं ओर का तीर। अगले चरण या नतीजे की ओर, और अरबी-हिब्रू जैसी दाएँ-से-बाएँ स्क्रीनों पर दिशा पढ़ने के प्रवाह के उलट पड़ जाती है।", "向右的箭头。用来指下一步或结果；在阿拉伯语、希伯来语这类从右往左的界面里，方向与阅读走向相反。", "向右的箭頭。用來指下一步或結果；在阿拉伯語、希伯來語這類從右往左的介面裡，方向與閱讀走向相反。"],
  'left-arrow': ["왼쪽 화살표입니다. 되돌아간다·앞으로 되짚는다는 뜻으로 쓰이고, 뒤에 U+FE0F가 붙어야 컬러로 나옵니다.", "A left arrow. Used for going back or referring to what came before, and it needs a trailing U+FE0F to come out in colour.", "Una flecha izquierda. Para volver atrás o remitir a lo anterior, y necesita un U+FE0F al final para verse en color.", "Uma seta para a esquerda. Para voltar atrás ou remeter ao anterior, e precisa de um U+FE0F no fim para sair em cor.", "左向きの矢印です。戻る・前に述べたものを指すという意味で使い、後ろに U+FE0F が付いて初めて色で出ます。", "Ein Linkspfeil. Für Zurückgehen oder den Verweis auf Vorheriges; er braucht ein angehängtes U+FE0F für Farbe.", "Une flèche gauche. Pour revenir ou renvoyer à ce qui précède, et il lui faut un U+FE0F final pour la couleur.", "बाईं ओर का तीर। लौटने या पहले कही बात की ओर इशारा करने के लिए, और रंग के लिए अंत में U+FE0F चाहिए।", "向左的箭头。用于返回或指向前面的内容；末尾要带 U+FE0F 才是彩色。", "向左的箭頭。用於返回或指向前面的內容；末尾要帶 U+FE0F 才是彩色。"],
  'up-arrow': ["위쪽 화살표입니다. 오른다·늘어난다는 뜻으로 쓰이고, 값이 오른 것을 말할 때 📈 대신 이것을 쓰는 사람도 많습니다.", "An up arrow. It means rising or increasing, and plenty of people reach for it instead of 📈 when a number goes up.", "Una flecha arriba. Significa subir o aumentar, y mucha gente la usa en lugar de 📈 cuando una cifra sube.", "Uma seta para cima. Significa subir ou aumentar, e muita gente a usa em vez de 📈 quando um número sobe.", "上向きの矢印です。上がる・増えるという意味で使い、数が上がったことを言うのに 📈 の代わりにこれを使う人も多いです。", "Ein Aufwärtspfeil. Er meint steigen oder zunehmen, und viele greifen dafür statt zu 📈 zu ihm.", "Une flèche haut. Elle dit monter ou augmenter, et beaucoup l’emploient à la place de 📈 quand un chiffre grimpe.", "ऊपर का तीर। बढ़ने या चढ़ने के अर्थ में, और आँकड़ा बढ़ने पर बहुत लोग 📈 की जगह इसे उठाते हैं।", "向上的箭头。表示上涨、增加；数字变高时，不少人用它而不用 📈。", "向上的箭頭。表示上漲、增加；數字變高時，不少人用它而不用 📈。"],
  'down-arrow': ["아래쪽 화살표입니다. 내린다·줄어든다는 뜻이자 아래를 보라는 표시로 쓰여, 한 글자가 두 일을 합니다.", "A down arrow. It means falling or decreasing and it also says “see below”, so one character does two jobs.", "Una flecha abajo. Significa bajar o disminuir y también «mira abajo», así que un carácter hace dos trabajos.", "Uma seta para baixo. Significa cair ou diminuir e também “veja abaixo”, então um caractere faz dois trabalhos.", "下向きの矢印です。下がる・減るという意味と、下を見よという印の両方に使われ、一つの字が二つの働きをします。", "Ein Abwärtspfeil. Er meint fallen oder abnehmen und sagt zugleich „siehe unten“ — ein Zeichen, zwei Aufgaben.", "Une flèche bas. Elle dit baisser ou diminuer et aussi « voir ci-dessous » : un caractère, deux emplois.", "नीचे का तीर। गिरने या घटने का अर्थ, और “नीचे देखो” का निशान भी — एक अक्षर, दो काम।", "向下的箭头。既表示下降、减少，也表示「见下方」，一个字符担两件事。", "向下的箭頭。既表示下降、減少，也表示「見下方」，一個字元擔兩件事。"],
  'refresh': ["시계 반대 방향으로 도는 두 화살표입니다. 새로 고침·다시 불러오기를 뜻하고, 되풀이를 뜻하는 🔁과 달리 한 번 다시 한다는 쪽입니다.", "Two arrows turning anticlockwise. It means refresh or reload, and unlike the looping 🔁 it is a single fresh attempt rather than repetition.", "Dos flechas girando en sentido contrario al reloj. Significa refrescar o recargar, y a diferencia del bucle 🔁 es un nuevo intento, no una repetición.", "Duas setas girando no sentido anti-horário. Significa atualizar ou recarregar, e diferente do laço 🔁 é uma nova tentativa, não repetição.", "反時計回りに回る二本の矢印です。更新・読み込み直しを意味し、繰り返しの 🔁 と違って一度やり直すという側です。", "Zwei gegen den Uhrzeigersinn drehende Pfeile. Es heißt aktualisieren oder neu laden — anders als die Schleife 🔁 ein einmaliger neuer Versuch.", "Deux flèches tournant dans le sens antihoraire. Cela dit rafraîchir ou recharger et, contrairement à la boucle 🔁, un seul nouvel essai.", "घड़ी की उलटी दिशा में घूमते दो तीर। मतलब ताज़ा करना या फिर लोड करना, और लूप वाले 🔁 से अलग यह एक बार दोबारा करने का पक्ष है।", "两支逆时针旋转的箭头。表示刷新、重新加载；和表示循环的 🔁 不同，它是重来一次而非反复。", "兩支逆時針旋轉的箭頭。表示重新整理、重新載入；和表示循環的 🔁 不同，它是重來一次而非反覆。"],
  'repeat': ["되풀이 단추입니다. 목록 전체를 다시 돈다는 뜻이고, 한 곡만 되풀이하는 🔂과는 안에 숫자 1이 있는지로 갈립니다.", "The repeat button. It loops the whole list, and the difference from the single-track 🔂 is the little numeral one inside it.", "El botón de repetir. Repite toda la lista, y lo que lo distingue del 🔂 de una sola pista es el uno pequeño dentro.", "O botão de repetir. Repete a lista inteira, e o que o distingue do 🔂 de uma faixa só é o pequeno número um dentro.", "繰り返しの単ボタンです。一覧全体をもう一度回すという意味で、一曲だけ繰り返す 🔂 とは中に 1 があるかで分かれます。", "Die Wiederholen-Taste. Sie spielt die ganze Liste erneut; vom Einzeltitel-🔂 unterscheidet sie die kleine Eins darin.", "Le bouton répéter. Il reprend toute la liste ; ce qui le distingue du 🔂 d’une seule piste, c’est le petit un à l’intérieur.", "दोहराव का बटन। यह पूरी सूची फिर चलाता है, और एक ही गाने वाले 🔂 से फ़र्क़ अंदर लिखे छोटे 1 का है।", "循环按钮。重播整个列表；和单曲循环 🔂 的区别就是里面那个小小的 1。", "循環按鈕。重播整個列表；和單曲循環 🔂 的區別就是裡面那個小小的 1。"],
  'repeat-one': ["한 곡만 되풀이하는 단추입니다. 안에 1이 들어 있어 목록 전체를 도는 🔁과 갈리는데, 작게 보이면 구별이 어렵습니다.", "The repeat-one button. The numeral one inside is what separates it from the whole-list 🔁, and at small sizes the two are hard to tell apart.", "El botón de repetir una. El uno dentro es lo que lo separa del 🔁 de toda la lista, y en tamaño pequeño cuesta distinguirlos.", "O botão de repetir uma. O número um dentro é o que o separa do 🔁 da lista inteira, e em tamanho pequeno é difícil distinguir.", "一曲だけ繰り返す単ボタンです。中に 1 が入っているのが一覧全体を回す 🔁 との違いですが、小さく表示されると見分けにくいです。", "Die Einzeltitel-Wiederholung. Die Eins darin trennt sie vom Listen-🔁, und in kleiner Darstellung sind beide kaum unterscheidbar.", "Le bouton répéter une piste. Le un à l’intérieur le distingue du 🔁 de la liste entière ; en petit, on les confond.", "एक ही गाना दोहराने का बटन। अंदर का 1 इसे पूरी सूची वाले 🔁 से अलग करता है, और छोटे आकार में दोनों में फ़र्क़ करना मुश्किल है।", "单曲循环按钮。里面的 1 是它和整列表循环 🔁 的区别，字号一小就分不清。", "單曲循環按鈕。裡面的 1 是它和整列表循環 🔁 的區別，字級一小就分不清。"],
  'shuffle': ["서로 엇갈린 두 화살표입니다. 순서를 섞는다는 뜻으로, 음악 이야기 밖에서는 계획이 뒤죽박죽이라는 비유로도 씁니다.", "Two arrows crossing. It means shuffling the order, and outside music talk it also stands for plans in disarray.", "Dos flechas que se cruzan. Significa mezclar el orden, y fuera de la música vale también por planes hechos un desbarajuste.", "Duas setas que se cruzam. Significa embaralhar a ordem, e fora da música vale também por planos em desordem.", "互い違いに交わる二本の矢印です。順序を混ぜるという意味で、音楽の話の外では計画がめちゃくちゃという喩えにも使います。", "Zwei sich kreuzende Pfeile. Es heißt die Reihenfolge mischen und steht außerhalb von Musik auch für zerfahrene Pläne.", "Deux flèches qui se croisent. Cela dit mélanger l’ordre et, hors musique, des plans sens dessus dessous.", "आपस में कटते दो तीर। मतलब क्रम मिला देना, और संगीत के बाहर यह अस्त-व्यस्त योजनाओं का रूपक भी है।", "两支交叉的箭头。表示打乱顺序；在音乐之外，也用作计划乱成一团的比喻。", "兩支交叉的箭頭。表示打亂順序；在音樂之外，也用作計畫亂成一團的比喻。"],

  /* ───────── 재생 단추 ───────── */
  'play': ["재생 단추입니다. 유니코드가 기기 화면에 쓰라고 넣은 조작 기호라 이모지로 만든 것이 아니고, 그래서 뒤에 U+FE0F가 붙지 않으면 흑백 삼각형으로 떨어집니다.", "The play button. Unicode added it as a device control symbol rather than as an emoji, which is why without a trailing U+FE0F it falls back to a black-and-white triangle.", "El botón de reproducir. Unicode lo añadió como símbolo de control de aparatos, no como emoji, y por eso sin un U+FE0F al final cae a un triángulo en blanco y negro.", "O botão de reproduzir. A Unicode o acrescentou como símbolo de controle de aparelhos, não como emoji, e por isso sem um U+FE0F no fim cai para um triângulo preto e branco.", "再生の単ボタンです。ユニコードが機器の画面に使う操作記号として入れた字で、絵文字として作られたものではないため、後ろに U+FE0F が付かないと白黒の三角に落ちます。", "Die Wiedergabe-Taste. Unicode nahm sie als Gerätesteuerzeichen auf, nicht als Emoji — ohne angehängtes U+FE0F bleibt ein schwarzweißes Dreieck.", "Le bouton lecture. Unicode l’a ajouté comme symbole de commande d’appareil, non comme emoji : sans U+FE0F final, il retombe en triangle noir et blanc.", "प्ले बटन। यूनिकोड ने इसे उपकरणों के नियंत्रण-चिह्न के तौर पर जोड़ा, इमोजी के तौर पर नहीं — इसलिए अंत में U+FE0F न हो तो यह काले-सफ़ेद त्रिकोण में गिर जाता है।", "播放按钮。Unicode 是把它当设备控制符号收录的，而不是表情，所以末尾没有 U+FE0F 时会退成黑白三角。", "播放按鈕。Unicode 是把它當裝置控制符號收錄的，而不是表情，所以末尾沒有 U+FE0F 時會退成黑白三角。"],
  'pause': ["멈춤 단추입니다. 잠깐 쉰다·보류한다는 뜻으로도 쓰이고, 완전히 그친다는 뜻의 ⏹️와는 다릅니다.", "The pause button. It also means taking a break or putting something on hold, and it is not the same as the full stop ⏹️.", "El botón de pausa. También significa tomarse un rato o dejar algo en espera, y no es lo mismo que la parada total ⏹️.", "O botão de pausa. Também significa dar um tempo ou deixar algo em espera, e não é o mesmo que a parada total ⏹️.", "一時停止の単ボタンです。少し休む・保留にするという意味でも使い、完全に止める ⏹️ とは別です。", "Die Pause-Taste. Sie meint auch eine Auszeit oder ein Aufschieben und ist nicht dasselbe wie das vollständige Stopp ⏹️.", "Le bouton pause. Il dit aussi faire une halte ou mettre en attente, et n’est pas l’arrêt complet ⏹️.", "पॉज़ बटन। इसका मतलब थोड़ा रुकना या किसी बात को टाल रखना भी है, और यह पूरी तरह रोकने वाले ⏹️ जैसा नहीं है।", "暂停按钮。也用来表示先歇一下或暂时搁置，和彻底停止的 ⏹️ 不是一回事。", "暫停按鈕。也用來表示先歇一下或暫時擱置，和徹底停止的 ⏹️ 不是一回事。"],
  'stop': ["정지 단추입니다. 그만한다는 뜻이고, 멈춤 ⏸️과 달리 다시 이어 갈 여지가 없다는 쪽으로 읽힙니다.", "The stop button. It means done, and unlike pause ⏸️ it reads as leaving no room to resume.", "El botón de parar. Significa acabar, y a diferencia de la pausa ⏸️ se lee como no dejar sitio para continuar.", "O botão de parar. Significa acabar, e diferente da pausa ⏸️ é lido como não deixar espaço para retomar.", "停止の単ボタンです。やめるという意味で、一時停止 ⏸️ と違って続ける余地がない側に読まれます。", "Die Stopp-Taste. Sie heißt Schluss und liest sich anders als die Pause ⏸️ als endgültig.", "Le bouton arrêt. Il dit terminé et, contrairement à la pause ⏸️, ne laisse pas de place à la reprise.", "स्टॉप बटन। मतलब बस, ख़त्म — और पॉज़ ⏸️ से अलग इसमें आगे बढ़ाने की गुंजाइश नहीं पढ़ी जाती।", "停止按钮。表示到此为止；和暂停 ⏸️ 不同，它读起来没有再续的余地。", "停止按鈕。表示到此為止；和暫停 ⏸️ 不同，它讀起來沒有再續的餘地。"],
  'next-track': ["다음 곡 단추입니다. 건너뛴다는 뜻으로 쓰이고, 이야기를 넘기고 싶을 때 보내는 비유로도 씁니다.", "The next-track button. It means skip, and it doubles as a way of saying you want to move past a topic.", "El botón de siguiente pista. Significa saltar, y también sirve para decir que quieres pasar de tema.", "O botão de próxima faixa. Significa pular, e também serve para dizer que você quer passar do assunto.", "次の曲の単ボタンです。飛ばすという意味で使い、話を先へ進めたいときの喩えにも使います。", "Die Nächster-Titel-Taste. Sie heißt überspringen und dient auch dazu, ein Thema hinter sich lassen zu wollen.", "Le bouton piste suivante. Il dit passer, et sert aussi à signifier qu’on veut changer de sujet.", "अगला ट्रैक बटन। मतलब छोड़कर आगे, और यह किसी बात से आगे बढ़ने की इच्छा कहने में भी चलता है।", "下一曲按钮。表示跳过，也用来表示想把这个话题带过去。", "下一曲按鈕。表示跳過，也用來表示想把這個話題帶過去。"],
  'previous-track': ["이전 곡 단추입니다. 처음부터 다시·앞으로 돌아간다는 뜻이고, 뒤에 U+FE0F가 붙어야 컬러로 나옵니다.", "The previous-track button. It means back to the start or back one step, and it needs a trailing U+FE0F for colour.", "El botón de pista anterior. Significa volver al inicio o un paso atrás, y necesita un U+FE0F al final para el color.", "O botão de faixa anterior. Significa voltar ao início ou um passo atrás, e precisa de um U+FE0F no fim para a cor.", "前の曲の単ボタンです。最初からもう一度・前へ戻るという意味で、後ろに U+FE0F が付いて初めて色で出ます。", "Die Vorheriger-Titel-Taste. Sie heißt zurück zum Anfang oder einen Schritt zurück und braucht ein angehängtes U+FE0F für Farbe.", "Le bouton piste précédente. Il dit revenir au début ou reculer d’un pas, et il lui faut un U+FE0F final.", "पिछला ट्रैक बटन। मतलब शुरू से फिर या एक कदम पीछे, और रंग के लिए अंत में U+FE0F चाहिए।", "上一曲按钮。表示从头再来或退一步；末尾要带 U+FE0F 才是彩色。", "上一曲按鈕。表示從頭再來或退一步；末尾要帶 U+FE0F 才是彩色。"],

  /* ───────── 종교와 신앙의 기호 ───────── */
  'peace-symbol': ["평화 기호입니다. 1958년 영국의 핵무기 반대 운동에서 나온 표시이고, 손으로 만드는 ✌️와는 다른 글자입니다.", "The peace symbol. It came out of the British anti-nuclear movement in 1958, and it is a different character from the hand sign ✌️.", "El símbolo de la paz. Nació del movimiento antinuclear británico en 1958, y es un carácter distinto del gesto con la mano ✌️.", "O símbolo da paz. Surgiu do movimento antinuclear britânico em 1958, e é um caractere diferente do gesto com a mão ✌️.", "平和の記号です。1958 年のイギリスの核兵器反対運動から出た印で、手で作る ✌️ とは別の字です。", "Das Friedenszeichen. Es entstand 1958 in der britischen Anti-Atom-Bewegung und ist ein anderes Zeichen als die Handgebärde ✌️.", "Le symbole de la paix. Né du mouvement antinucléaire britannique en 1958, c’est un autre caractère que le geste ✌️.", "शांति चिह्न। यह 1958 में ब्रिटेन के परमाणु-विरोधी आंदोलन से निकला, और हाथ से बनाए ✌️ से अलग अक्षर है।", "和平符号。它出自 1958 年英国的反核运动，和用手比出的 ✌️ 是不同的字符。", "和平符號。它出自 1958 年英國的反核運動，和用手比出的 ✌️ 是不同的字元。"],
  'latin-cross': ["라틴 십자가입니다. 기독교의 표시이며, 뒤에 U+FE0F가 붙지 않으면 흑백 글자로 떨어집니다.", "The Latin cross, the symbol of Christianity. Without a trailing U+FE0F it falls back to a black-and-white glyph.", "La cruz latina, símbolo del cristianismo. Sin un U+FE0F al final cae a un glifo en blanco y negro.", "A cruz latina, símbolo do cristianismo. Sem um U+FE0F no fim cai para um glifo preto e branco.", "ラテン十字です。キリスト教の印で、後ろに U+FE0F が付かないと白黒の字に落ちます。", "Das lateinische Kreuz, Symbol des Christentums. Ohne angehängtes U+FE0F bleibt ein schwarzweißes Zeichen.", "La croix latine, symbole du christianisme. Sans U+FE0F final, elle retombe en glyphe noir et blanc.", "लैटिन क्रॉस — ईसाई धर्म का चिह्न। अंत में U+FE0F न हो तो यह काले-सफ़ेद अक्षर में गिर जाता है।", "拉丁十字，基督教的标志。末尾没有 U+FE0F 时会退成黑白字形。", "拉丁十字，基督教的標誌。末尾沒有 U+FE0F 時會退成黑白字形。"],
  'star-and-crescent': ["별과 초승달입니다. 이슬람을 나타내는 표시로 널리 쓰이며, 여러 나라의 국기에도 들어 있는 도형입니다.", "The star and crescent. Widely used to represent Islam, and it is also the device on several national flags.", "La estrella y la media luna. Muy usada para representar el islam, y figura además en varias banderas nacionales.", "A estrela e o crescente. Muito usada para representar o islã, e figura também em várias bandeiras nacionais.", "星と三日月です。イスラムを表す印として広く使われ、いくつもの国旗にも入っている図形です。", "Stern und Halbmond. Weit verbreitet als Zeichen des Islam und zugleich Motiv mehrerer Nationalflaggen.", "L’étoile et le croissant. Largement employés pour représenter l’islam, et figurant aussi sur plusieurs drapeaux nationaux.", "तारा और अर्धचंद्र। इस्लाम को दर्शाने के लिए व्यापक, और यह कई देशों के झंडों पर भी है।", "星月符号。广泛用来代表伊斯兰教，也出现在若干国家的国旗上。", "星月符號。廣泛用來代表伊斯蘭教，也出現在若干國家的國旗上。"],
  'om': ["옴 기호입니다. 힌두교의 신성한 음절을 데바나가리로 적은 것이고, 자이나교와 불교에서도 쓰입니다.", "The om. It writes Hinduism's sacred syllable in Devanagari, and it is used in Jainism and Buddhism as well.", "El om. Escribe en devanágari la sílaba sagrada del hinduismo, y se usa también en el jainismo y el budismo.", "O om. Escreve em devanágari a sílaba sagrada do hinduísmo, e é usado também no jainismo e no budismo.", "オーム記号です。ヒンドゥー教の神聖な音節をデーヴァナーガリーで記したもので、ジャイナ教や仏教でも用いられます。", "Das Om. Es schreibt die heilige Silbe des Hinduismus in Devanagari und wird auch im Jainismus und Buddhismus verwendet.", "L’om. Il écrit en devanagari la syllabe sacrée de l’hindouisme, et sert aussi dans le jaïnisme et le bouddhisme.", "ॐ चिह्न। यह हिंदू धर्म के पवित्र अक्षर को देवनागरी में लिखता है, और जैन तथा बौद्ध परंपराओं में भी बरता जाता है।", "唵（Om）符号。它用天城文写出印度教的圣音节，耆那教和佛教也在使用。", "唵（Om）符號。它用天城文寫出印度教的聖音節，耆那教和佛教也在使用。"],
  'star-of-david': ["다윗의 별입니다. 유대교와 유대 민족을 나타내는 표시이며, 이스라엘 국기에도 들어 있습니다.", "The Star of David. It represents Judaism and the Jewish people, and it also appears on the flag of Israel.", "La Estrella de David. Representa el judaísmo y al pueblo judío, y aparece también en la bandera de Israel.", "A Estrela de Davi. Representa o judaísmo e o povo judeu, e aparece também na bandeira de Israel.", "ダビデの星です。ユダヤ教とユダヤ民族を表す印で、イスラエルの国旗にも入っています。", "Der Davidstern. Er steht für das Judentum und das jüdische Volk und erscheint auch auf der Flagge Israels.", "L’étoile de David. Elle représente le judaïsme et le peuple juif, et figure aussi sur le drapeau d’Israël.", "डेविड का तारा। यह यहूदी धर्म और यहूदी जन का चिह्न है, और इसराइल के झंडे पर भी है।", "大卫星。代表犹太教和犹太民族，也出现在以色列国旗上。", "大衛星。代表猶太教和猶太民族，也出現在以色列國旗上。"],
  'dharma-wheel': ["법륜입니다. 불교의 가르침을 나타내는 여덟 살 바퀴이고, 인도 국기 가운데의 바퀴와 같은 계통의 도형입니다.", "The dharma wheel. An eight-spoked wheel standing for the Buddha's teaching, of the same lineage as the wheel at the centre of India's flag.", "La rueda del dharma. Una rueda de ocho radios que representa la enseñanza budista, del mismo linaje que la rueda del centro de la bandera de la India.", "A roda do dharma. Uma roda de oito raios que representa o ensinamento budista, da mesma linhagem da roda no centro da bandeira da Índia.", "法輪です。仏の教えを表す八本の輻の車輪で、インド国旗中央の車輪と同じ系統の図形です。", "Das Dharmarad. Ein achtspeichiges Rad für die Lehre des Buddha, verwandt mit dem Rad in der Mitte der indischen Flagge.", "La roue du dharma. Une roue à huit rayons représentant l’enseignement du Bouddha, de la même lignée que celle au centre du drapeau indien.", "धर्मचक्र। आठ तीलियों वाला यह चक्र बुद्ध की शिक्षा दर्शाता है, और भारत के झंडे के बीच वाले चक्र की उसी परंपरा का है।", "法轮。八根辐的轮子，代表佛陀的教法，与印度国旗中央那个轮同出一脉。", "法輪。八根輻的輪子，代表佛陀的教法，與印度國旗中央那個輪同出一脈。"],
  'six-pointed-star': ["가운데 점이 있는 여섯 모 별입니다. 다윗의 별 ✡️과는 다른 글자로, 유니코드가 일본 점술의 기호에서 가져왔습니다.", "A six-pointed star with a dot in the middle. It is a different character from the Star of David ✡️; Unicode took it from a Japanese fortune-telling symbol.", "Una estrella de seis puntas con un punto en el centro. Es un carácter distinto de la Estrella de David ✡️; Unicode lo tomó de un símbolo de la adivinación japonesa.", "Uma estrela de seis pontas com um ponto no meio. É um caractere diferente da Estrela de Davi ✡️; a Unicode o tirou de um símbolo da adivinhação japonesa.", "中に点がある六芒星です。ダビデの星 ✡️ とは別の字で、ユニコードは日本の占いの記号から取りました。", "Ein sechszackiger Stern mit Punkt in der Mitte. Ein anderes Zeichen als der Davidstern ✡️; Unicode übernahm es aus einem japanischen Wahrsagesymbol.", "Une étoile à six branches avec un point au centre. Autre caractère que l’étoile de David ✡️ : Unicode l’a prise à un symbole de divination japonais.", "बीच में बिंदु लिए छह-कोने वाला तारा। यह डेविड के तारे ✡️ से अलग अक्षर है; यूनिकोड ने इसे जापानी भविष्यकथन के चिह्न से लिया।", "中间带点的六角星。它和大卫星 ✡️ 是不同的字符；Unicode 取自日本占卜的符号。", "中間帶點的六角星。它和大衛星 ✡️ 是不同的字元；Unicode 取自日本占卜的符號。"],
  'menorah': ["메노라입니다. 유대교의 촛대이며, 하누카에 켜는 촛대는 가지가 아홉인 하누키아로 따로 구별합니다.", "A menorah. The Jewish lampstand; the one lit at Hanukkah has nine branches and is distinguished as a hanukkiah.", "Una menorá. El candelabro judío; el que se enciende en Janucá tiene nueve brazos y se distingue como januquiá.", "Uma menorá. O candelabro judaico; o que se acende no Chanucá tem nove braços e se distingue como chanukiá.", "メノラーです。ユダヤ教の燭台で、ハヌカーにともす燭台は枝が九本のハヌキヤーとして区別されます。", "Eine Menora. Der jüdische Leuchter; der zu Chanukka entzündete hat neun Arme und heißt Chanukkia.", "Une menorah. Le chandelier juif ; celui que l’on allume à Hanoucca compte neuf branches et se nomme hanoukkia.", "मेनोरा। यहूदी दीपाधार; हनुक्का पर जलाया जाने वाला नौ शाखाओं वाला होता है और उसे हनुकिया कहकर अलग किया जाता है।", "梅诺拉。犹太教的灯台；光明节点的那种有九枝，另称哈努基亚。", "梅諾拉。猶太教的燈臺；光明節點的那種有九枝，另稱哈努基亞。"],
  'yin-yang': ["음양 도형입니다. 도교에서 나온 표시로, 서로 맞선 두 힘이 하나를 이룬다는 뜻으로 널리 쓰입니다.", "The yin-yang. A Taoist symbol, widely used for two opposing forces making one whole.", "El yin-yang. Símbolo taoísta, muy usado para dos fuerzas opuestas que forman un todo.", "O yin-yang. Símbolo taoísta, muito usado para duas forças opostas que formam um todo.", "陰陽の図形です。道教から出た印で、相対する二つの力が一つを成すという意味で広く使われます。", "Das Yin-Yang. Ein taoistisches Zeichen, verbreitet für zwei gegensätzliche Kräfte, die ein Ganzes bilden.", "Le yin-yang. Symbole taoïste, largement employé pour deux forces opposées formant un tout.", "यिन-यांग। ताओ परंपरा से आया चिह्न, जो दो विपरीत शक्तियों के मिलकर एक होने के अर्थ में व्यापक है।", "阴阳图。出自道家的符号，广泛用来表示相对的两股力量合成一体。", "陰陽圖。出自道家的符號，廣泛用來表示相對的兩股力量合成一體。"],

  /* ───────── 카드와 놀이 ───────── */
  'spade': ["스페이드입니다. 트럼프 네 무늬 가운데 하나이고, 뒤에 U+FE0F가 붙어야 컬러로 나옵니다.", "The spade suit. One of the four card suits, and it needs a trailing U+FE0F to come out in colour.", "El palo de picas. Uno de los cuatro palos de la baraja, y necesita un U+FE0F al final para verse en color.", "O naipe de espadas. Um dos quatro naipes, e precisa de um U+FE0F no fim para sair em cor.", "スペードです。トランプの四つの絵柄の一つで、後ろに U+FE0F が付いて初めて色で出ます。", "Die Pik-Farbe. Eine der vier Kartenfarben; sie braucht ein angehängtes U+FE0F für Farbe.", "Le pique. L’une des quatre couleurs du jeu de cartes, et il lui faut un U+FE0F final pour la couleur.", "हुकुम का रंग। ताश के चार रंगों में से एक, और रंगीन दिखने को अंत में U+FE0F चाहिए।", "黑桃。扑克四种花色之一；末尾要带 U+FE0F 才是彩色。", "黑桃。撲克四種花色之一；末尾要帶 U+FE0F 才是彩色。"],
  'heart-suit': ["하트 무늬입니다. 트럼프의 무늬여서 사랑을 뜻하는 ❤️와는 다른 글자이고, 그림도 더 작고 각이 집니다.", "The heart card suit. Being a card mark it is a different character from the love heart ❤️, and it is drawn smaller and more angular.", "El palo de corazones. Al ser una marca de naipe es un carácter distinto del corazón de amor ❤️, y se dibuja más pequeño y anguloso.", "O naipe de copas. Sendo marca de carta é um caractere diferente do coração de amor ❤️, e é desenhado menor e mais anguloso.", "ハートの絵柄です。トランプの印なので愛を表す ❤️ とは別の字で、絵も小さく角が立っています。", "Die Herz-Farbe. Als Kartenzeichen ein anderes Zeichen als das Liebesherz ❤️ und kleiner sowie kantiger gezeichnet.", "Le cœur du jeu de cartes. Marque de carte, c’est un autre caractère que le cœur d’amour ❤️, dessiné plus petit et plus anguleux.", "पान का रंग। ताश का निशान होने से यह प्रेम वाले दिल ❤️ से अलग अक्षर है, और बना भी छोटा तथा कोनेदार है।", "红桃。作为牌面花色，它和表示爱的 ❤️ 是不同的字符，画得更小、棱角更明。", "紅桃。作為牌面花色，它和表示愛的 ❤️ 是不同的字元，畫得更小、稜角更明。"],
  'diamond-suit': ["다이아몬드 무늬입니다. 트럼프의 무늬여서 보석 💎이나 도형 🔶와는 다른 글자입니다.", "The diamond card suit. Being a card mark it is a different character from the gem 💎 and from the geometric 🔶.", "El palo de diamantes. Al ser una marca de naipe es un carácter distinto de la gema 💎 y del rombo 🔶.", "O naipe de ouros. Sendo marca de carta é um caractere diferente da gema 💎 e do losango 🔶.", "ダイヤの絵柄です。トランプの印なので宝石 💎 や図形 🔶 とは別の字です。", "Die Karo-Farbe. Als Kartenzeichen ein anderes Zeichen als der Edelstein 💎 und die geometrische Raute 🔶.", "Le carreau du jeu de cartes. Marque de carte, c’est un autre caractère que la gemme 💎 et le losange 🔶.", "ईंट का रंग। ताश का निशान होने से यह रत्न 💎 और ज्यामितीय 🔶 से अलग अक्षर है।", "方块。作为牌面花色，它和宝石 💎、几何图形 🔶 都是不同的字符。", "方塊。作為牌面花色，它和寶石 💎、幾何圖形 🔶 都是不同的字元。"],
  'club': ["클로버 무늬입니다. 트럼프의 무늬여서 잎이 넷인 행운의 네잎클로버 🍀와는 다른 글자입니다.", "The club card suit. Being a card mark it is a different character from the lucky four-leaf clover 🍀.", "El palo de tréboles. Al ser una marca de naipe es un carácter distinto del trébol de cuatro hojas de la suerte 🍀.", "O naipe de paus. Sendo marca de carta é um caractere diferente do trevo de quatro folhas da sorte 🍀.", "クラブの絵柄です。トランプの印なので、葉が四枚の幸運のクローバー 🍀 とは別の字です。", "Die Kreuz-Farbe. Als Kartenzeichen ein anderes Zeichen als das Glücks-Kleeblatt 🍀.", "Le trèfle du jeu de cartes. Marque de carte, c’est un autre caractère que le trèfle à quatre feuilles 🍀.", "चिड़ी का रंग। ताश का निशान होने से यह भाग्य वाले चार-पत्ती क्लोवर 🍀 से अलग अक्षर है।", "梅花。作为牌面花色，它和代表幸运的四叶草 🍀 是不同的字符。", "梅花。作為牌面花色，它和代表幸運的四葉草 🍀 是不同的字元。"],
  'mahjong': ["마작의 홍중 패입니다. 유니코드는 마작 패 전체를 담고 있는데 이모지로 자란 것은 이 한 장뿐이라, 마작 이야기 전체를 이것 하나가 맡습니다.", "The red dragon mahjong tile. Unicode encodes the whole tile set but only this one grew into an emoji, so it stands in for mahjong as a whole.", "La ficha del dragón rojo del mahjong. Unicode codifica todo el juego de fichas pero solo esta creció como emoji, así que representa el mahjong entero.", "A peça do dragão vermelho do mahjong. A Unicode codifica o conjunto todo mas só esta virou emoji, então ela representa o mahjong inteiro.", "麻雀の紅中の牌です。ユニコードは麻雀牌の全てを収めていますが、絵文字として育ったのはこの一枚だけなので、麻雀の話全体をこれが担います。", "Der Mahjong-Stein „roter Drache“. Unicode kodiert das ganze Set, doch nur dieser wurde zum Emoji — er steht daher für Mahjong überhaupt.", "La tuile du dragon rouge au mahjong. Unicode encode tout le jeu, mais seule celle-ci est devenue un emoji : elle représente donc le mahjong entier.", "माहजोंग का लाल ड्रैगन पत्ता। यूनिकोड में पूरा सेट है, पर इमोजी सिर्फ़ यही बना, इसलिए माहजोंग की सारी बात यही एक उठाता है।", "麻将的红中。Unicode 收录了整副麻将牌，但只有这一张长成了表情，于是它代表整个麻将。", "麻將的紅中。Unicode 收錄了整副麻將牌，但只有這一張長成了表情，於是它代表整個麻將。"],
  'hanafuda': ["화투 패입니다. 일본의 화투 가운데 흑싸리 껍데기에 해당하는 한 장이고, 한국에서도 같은 놀이패를 씁니다.", "A hanafuda card. It is one card from the Japanese flower-card deck, and the same deck is played in Korea under its own name.", "Una carta de hanafuda. Es una carta del mazo japonés de cartas florales, y la misma baraja se juega en Corea con su propio nombre.", "Uma carta de hanafuda. É uma carta do baralho japonês de cartas florais, e o mesmo baralho é jogado na Coreia com nome próprio.", "花札です。日本の花札の一枚で、韓国でも同じ札で遊びます。", "Eine Hanafuda-Karte. Ein Blatt aus dem japanischen Blumenkartenspiel; dasselbe Deck wird in Korea unter eigenem Namen gespielt.", "Une carte de hanafuda. Une carte du jeu japonais de cartes fleuries ; le même jeu se pratique en Corée sous un autre nom.", "हानाफ़ुदा का एक पत्ता। यह जापानी फूल-पत्तों की गड्डी का एक पत्ता है, और वही गड्डी कोरिया में अपने नाम से खेली जाती है।", "花札的一张牌。它是日本花牌里的一张，同样的牌在韩国也以自己的名字流行。", "花札的一張牌。它是日本花牌裡的一張，同樣的牌在韓國也以自己的名字流行。"],

  /* ───────── 돈 ───────── */
  'dollar-sign': ["굵은 달러 기호입니다. 돈이나 값을 가리키는 데 쓰이고, 지폐 💵와 달리 특정 나라 돈을 그린 것이 아닙니다.", "A heavy dollar sign. Used to point at money or a price, and unlike the banknote 💵 it does not depict any one country's currency.", "Un signo de dólar grueso. Señala dinero o un precio, y a diferencia del billete 💵 no dibuja la moneda de un país concreto.", "Um sinal de dólar grosso. Aponta dinheiro ou um preço, e diferente da nota 💵 não desenha a moeda de um país específico.", "太い ドル記号です。お金や値段を指すのに使い、紙幣 💵 と違って特定の国のお金を描いたものではありません。", "Ein fettes Dollarzeichen. Es verweist auf Geld oder einen Preis und zeigt anders als die Banknote 💵 keine bestimmte Landeswährung.", "Un signe dollar épais. Il désigne l’argent ou un prix et, contrairement au billet 💵, ne représente la monnaie d’aucun pays précis.", "मोटा डॉलर चिह्न। पैसे या दाम की ओर इशारा करने के लिए, और नोट 💵 से अलग यह किसी एक देश की मुद्रा नहीं बनाता।", "粗体美元符号。用来指钱或价格；和纸币 💵 不同，它并不画某个国家的货币。", "粗體美元符號。用來指錢或價格；和紙幣 💵 不同，它並不畫某個國家的貨幣。"],
  'currency-exchange': ["환전 기호입니다. 화살표가 도는 그림으로 돈을 바꾼다는 뜻이며, 공항과 은행 안내판에서 온 표시입니다.", "The currency exchange symbol. Arrows turning around the marks mean money changing hands, and the sign comes from airport and bank wayfinding.", "El símbolo de cambio de divisa. Las flechas girando alrededor significan cambiar dinero, y el signo viene de la señalización de aeropuertos y bancos.", "O símbolo de câmbio. As setas girando em volta significam trocar dinheiro, e o sinal vem da sinalização de aeroportos e bancos.", "両替の記号です。矢印が回る絵でお金を替えるという意味で、空港や銀行の案内板から来た印です。", "Das Zeichen für Geldwechsel. Die kreisenden Pfeile bedeuten Umtausch; das Zeichen stammt aus der Beschilderung von Flughäfen und Banken.", "Le symbole de change. Les flèches qui tournent disent l’échange d’argent, et le signe vient de la signalétique des aéroports et des banques.", "मुद्रा विनिमय का चिह्न। घूमते तीरों का मतलब है पैसा बदलना, और यह चिह्न हवाई अड्डों तथा बैंकों के साइनबोर्ड से आया है।", "货币兑换符号。绕着转的箭头表示换钱，这个标志来自机场和银行的指示牌。", "貨幣兌換符號。繞著轉的箭頭表示換錢，這個標誌來自機場和銀行的指示牌。"],
};
