/**
 * 지하철 노선 - 수도가 아닌 도시 (9)
 *
 * 지하철은 수도에만 있는 것이 아니다. 부산·오사카·시카고·리옹·뮌헨·바르셀로나·
 * 상파울루·리우데자네이루·뭄바이는 각자의 노선을 갖고 있고, 그 도시 사람에게는
 * 수도의 노선보다 이 노선이 자기 노선이다.
 *
 * 역 이름은 그 도시의 표기를 그대로 쓰고, 한글·한자·가나·데바나가리 노선에는
 * 로마자를 함께 정답으로 둔다.
 */
import { T, s, sa } from './copy.ts';
import type { MetroLine } from './types.ts';

export const SECOND_CITY_LINES: MetroLine[] = [
  {
    slug: 'busan-line-1', city: 'busan', num: '1', color: '#f06a00',
    shape: ['E', 'E', 'NE', 'NE', 'NE', 'N', 'N', 'NE', 'NE', 'NE', 'E', 'E', 'NE', 'NE', 'NE', 'E', 'E', 'E', 'NE', 'NE', 'NE', 'N', 'N', 'N', 'NE', 'NE', 'NE', 'N', 'N', 'N', 'N', 'N', 'NE', 'NE', 'N', 'N', 'N', 'N', 'N'],
    stations: [
      s('다대포해수욕장', 'Dadaepo Beach', 'terminus'), s('다대포항', 'Dadaepohang'), s('낫개', 'Natgae'),
      s('신장림', 'Sinjangnim'), s('장림', 'Jangnim'), s('동매', 'Dongmae'), s('신평', 'Sinpyeong'),
      s('하단', 'Hadan', 'transfer'), s('당리', 'Dangni'), s('사하', 'Saha'), s('괴정', 'Goejeong'),
      s('대티', 'Daeti'), s('서대신', 'Seodaesin'), s('동대신', 'Dongdaesin'), s('토성', 'Toseong'),
      s('자갈치', 'Jagalchi'), s('남포', 'Nampo'), s('중앙', 'Jungang'), s('부산역', 'Busan Station', 'transfer'),
      s('초량', 'Choryang'), s('부산진', 'Busanjin'), s('좌천', 'Jwacheon'), s('범일', 'Beomil'),
      s('범내골', 'Beomnaegol'), s('서면', 'Seomyeon', 'transfer'), s('부전', 'Bujeon'),
      s('양정', 'Yangjeong'), s('시청', 'City Hall'), s('연산', 'Yeonsan', 'transfer'),
      s('교대', 'Busan Nat’l Univ. of Education'), s('동래', 'Dongnae', 'transfer'), s('명륜', 'Myeongnyun'),
      s('온천장', 'Oncheonjang'), s('부산대', 'Pusan Nat’l Univ.'), s('장전', 'Jangjeon'),
      s('구서', 'Guseo'), s('두실', 'Dusil'), s('남산', 'Namsan'), s('범어사', 'Beomeosa'),
      s('노포', 'Nopo', 'terminus'),
    ],
    text: T(
      ['서울 밖에서 가장 먼저 개통한 지하철로 다대포 바닷가에서 노포까지 부산을 남북으로 관통합니다. 서면과 연산에서 다른 노선과 갈아탑니다.',
       '남쪽 사하 구간은 장림·동매처럼 짧은 이름이 이어지고, 북쪽은 온천장·범어사처럼 절과 온천 이름이 남아 있습니다.'],
      ['The first subway to open outside Seoul, running the length of Busan from the beach at Dadaepo up to Nopo. Seomyeon and Yeonsan are the interchanges.',
       'The southern Saha stretch is a run of short names — Jangnim, Dongmae — while the north keeps temple and hot-spring names like Oncheonjang and Beomeosa.'],
      ['El primer metro que se abrió fuera de Seúl; recorre Busan de punta a punta, desde la playa de Dadaepo hasta Nopo. Seomyeon y Yeonsan son los transbordos.',
       'El tramo sur de Saha encadena nombres cortos — Jangnim, Dongmae —, mientras el norte conserva nombres de templos y termas: Oncheonjang, Beomeosa.'],
      ['O primeiro metrô a abrir fora de Seul; percorre Busan de ponta a ponta, da praia de Dadaepo até Nopo. Seomyeon e Yeonsan são as baldeações.',
       'O trecho sul de Saha enfileira nomes curtos — Jangnim, Dongmae —, enquanto o norte guarda nomes de templos e termas: Oncheonjang, Beomeosa.'],
      ['ソウル以外で最初に開通した地下鉄で、多大浦の海辺から老圃まで釜山を南北に貫きます。西面と蓮山で他線に乗り換えられます。',
       '南の沙下区間は長林・東梅のように短い駅名が続き、北は温泉場・梵魚寺のように寺と温泉の名が残っています。'],
      ['Die erste U-Bahn außerhalb Seouls; sie durchzieht Busan vom Strand in Dadaepo bis Nopo. Umgestiegen wird in Seomyeon und Yeonsan.',
       'Im Süden bei Saha reihen sich kurze Namen — Jangnim, Dongmae —, im Norden halten sich Tempel- und Thermennamen wie Oncheonjang und Beomeosa.'],
      ['Le premier métro ouvert hors de Séoul ; il traverse Busan de la plage de Dadaepo jusqu’à Nopo. Les correspondances sont à Seomyeon et Yeonsan.',
       'Le tronçon sud de Saha enchaîne les noms courts — Jangnim, Dongmae — tandis que le nord garde des noms de temples et de thermes : Oncheonjang, Beomeosa.'],
      ['सिओल के बाहर सबसे पहले खुली मेट्रो; Dadaepo के समुद्र तट से Nopo तक बुसान को उत्तर-दक्षिण पार करती है। Seomyeon और Yeonsan पर इंटरचेंज हैं।',
       'दक्षिण का Saha हिस्सा छोटे नामों की कतार है — Jangnim, Dongmae — और उत्तर में Oncheonjang, Beomeosa जैसे मंदिर-गर्म चश्मे के नाम बचे हैं।'],
    ),
  },
  {
    slug: 'osaka-midosuji', city: 'osaka', color: '#e5171f',
    label: { ko: '미도스지선', en: 'Midosuji Line', es: 'Línea Midosuji', pt: 'Linha Midosuji', ja: '御堂筋線', de: 'Midosuji-Linie', fr: 'Ligne Midosuji', hi: 'मिदोसुजी लाइन' },
    shape: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'SE', 'SE', 'S', 'S', 'S', 'S'],
    stations: [
      s('江坂', 'Esaka', 'terminus'), s('東三国', 'Higashi-Mikuni'), s('新大阪', 'Shin-Osaka', 'transfer'),
      s('西中島南方', 'Nishinakajima-Minamigata'), s('中津', 'Nakatsu'), s('梅田', 'Umeda', 'transfer'),
      s('淀屋橋', 'Yodoyabashi', 'transfer'), s('本町', 'Hommachi', 'transfer'),
      s('心斎橋', 'Shinsaibashi', 'transfer'), s('難波', 'Namba', 'transfer'), s('大国町', 'Daikokucho'),
      s('動物園前', 'Dobutsuen-mae'), s('天王寺', 'Tennoji', 'transfer'), s('昭和町', 'Showacho'),
      s('西田辺', 'Nishitanabe'), s('長居', 'Nagai'), s('あびこ', 'Abiko'), s('北花田', 'Kitahanada'),
      s('新金岡', 'Shin-Kanaoka'), s('なかもず', 'Nakamozu', 'terminus'),
    ],
    text: T(
      ['오사카 지하철에서 가장 많은 사람이 타는 노선으로 우메다·신사이바시·난바를 한 줄로 잇습니다. 노선색인 빨강은 붐비는 대동맥을 뜻해 골랐다고 합니다.',
       '역명이 한자와 가나로 섞여 있어 로마자로 쳐도 정답입니다. 梅田·難波·天王寺를 먼저 놓고 사이를 채워 보세요.'],
      ['The busiest line on the Osaka network, stringing Umeda, Shinsaibashi and Namba together. Its red was chosen to say “main artery”.',
       'Names mix kanji and kana, so romanised spellings count. Place Umeda, Namba and Tennoji first, then fill the gaps.'],
      ['La línea más concurrida de la red de Osaka; enhebra Umeda, Shinsaibashi y Namba. Su rojo se eligió para decir «arteria principal».',
       'Los nombres mezclan kanji y kana, así que la grafía romanizada vale. Coloca primero Umeda, Namba y Tennoji.'],
      ['A linha mais movimentada da rede de Osaka; enfileira Umeda, Shinsaibashi e Namba. O vermelho foi escolhido para dizer “artéria principal”.',
       'Os nomes misturam kanji e kana, então a grafia romanizada vale. Coloque primeiro Umeda, Namba e Tennoji.'],
      ['大阪メトロで最も利用者が多い路線で、梅田・心斎橋・難波を一本で結びます。路線色の赤は大動脈を表して選ばれたといわれます。',
       '駅名は漢字とかなが混じるため、ローマ字入力でも正解です。梅田・難波・天王寺を先に置いて間を埋めましょう。'],
      ['Die am stärksten genutzte Linie im Osaka-Netz; sie reiht Umeda, Shinsaibashi und Namba auf. Das Rot wurde gewählt, weil sie die Hauptschlagader ist.',
       'Die Namen mischen Kanji und Kana, romanisierte Schreibweisen zählen also. Setze erst Umeda, Namba und Tennoji.'],
      ['La ligne la plus fréquentée du réseau d’Osaka ; elle enfile Umeda, Shinsaibashi et Namba. Son rouge a été choisi pour dire « artère principale ».',
       'Les noms mêlent kanji et kana : la graphie romanisée compte. Posez d’abord Umeda, Namba et Tennoji.'],
      ['ओसाका नेटवर्क की सबसे व्यस्त लाइन; यह Umeda, Shinsaibashi और Namba को एक ही धागे में बाँधती है। लाल रंग “मुख्य धमनी” कहने के लिए चुना गया।',
       'नामों में कांजी और काना मिले हैं, इसलिए रोमन लिपि भी चलती है। पहले Umeda, Namba और Tennoji रखें।'],
    ),
  },
  {
    slug: 'chicago-brown', city: 'chicago', color: '#62361b',
    label: { ko: '브라운 라인', en: 'Brown Line', es: 'Línea Marrón', pt: 'Linha Marrom', ja: 'ブラウンライン', de: 'Brown Line', fr: 'Ligne brune', hi: 'ब्राउन लाइन' },
    shape: ['E', 'E', 'E', 'E', 'SE', 'SE', 'E', 'E', 'SE', 'SE', 'SE', 'S', 'S', 'S', 'SE', 'SE', 'SE', 'S', 'S', 'S', 'SW', 'SW', 'SW', 'W', 'W'],
    stations: [
      s('Kimball', undefined, 'terminus'), s('Kedzie'), s('Francisco'), s('Rockwell'),
      s('Western'), s('Damen'), s('Montrose'), s('Irving Park'), s('Addison'),
      s('Paulina'), s('Southport'), s('Belmont', undefined, 'transfer'), s('Wellington'),
      s('Diversey'), s('Fullerton', undefined, 'transfer'), s('Armitage'),
      s('Sedgwick'), s('Chicago'), s('Merchandise Mart'), s('Washington/Wells', 'Washington Wells'),
      s('Quincy'), s('LaSalle/Van Buren', 'LaSalle Van Buren'), s('Harold Washington Library'),
      s('Adams/Wabash', 'Adams Wabash'), s('State/Lake', 'State Lake'),
      s('Clark/Lake', 'Clark Lake', 'terminus'),
    ],
    text: T(
      ['시카고 북쪽 주택가에서 도심으로 들어와 루프 고가를 한 바퀴 도는 노선입니다. 대부분 고가로 달려 창밖으로 건물 사이가 그대로 보입니다.',
       '슬래시가 들어간 역은 두 거리 이름을 붙인 것입니다. Clark/Lake처럼 슬래시 없이 쳐도 정답으로 받습니다.'],
      ['It comes in from the residential north side and rides the elevated Loop once round. Most of the trip is above the street, right between the buildings.',
       'Stations with a slash are named after two streets. Typing Clark/Lake without the slash counts too.'],
      ['Llega desde los barrios residenciales del norte y da una vuelta al Loop elevado. Casi todo el trayecto va por encima de la calle, entre los edificios.',
       'Las estaciones con barra llevan el nombre de dos calles. Escribir Clark/Lake sin la barra también vale.'],
      ['Vem dos bairros residenciais do norte e dá uma volta no Loop elevado. Quase todo o trajeto corre acima da rua, entre os edifícios.',
       'As estações com barra levam o nome de duas ruas. Digitar Clark/Lake sem a barra também vale.'],
      ['シカゴ北側の住宅地から都心に入り、高架のループを一周する路線です。ほとんどが高架で、ビルのあいだを走る眺めが続きます。',
       'スラッシュの入った駅名は二つの通りの名を並べたものです。Clark/Lake のようにスラッシュなしで打っても正解です。'],
      ['Sie kommt aus den Wohnvierteln im Norden und fährt den Hochbahn-Loop einmal herum. Fast die ganze Fahrt liegt über der Straße, mitten zwischen den Häusern.',
       'Stationen mit Schrägstrich tragen zwei Straßennamen. Clark/Lake ohne Schrägstrich zählt ebenfalls.'],
      ['Elle arrive des quartiers résidentiels du nord et fait un tour du Loop aérien. Presque tout le trajet passe au-dessus de la rue, entre les immeubles.',
       'Les stations avec une barre oblique portent deux noms de rues. Taper Clark/Lake sans la barre compte aussi.'],
      ['यह उत्तर के रिहायशी इलाकों से शहर के केंद्र में आती है और ऊपर बने Loop का एक चक्कर लगाती है। ज़्यादातर सफ़र सड़क के ऊपर, इमारतों के बीच से होता है।',
       'स्लैश वाले स्टेशन दो सड़कों के नाम जोड़कर बने हैं। Clark/Lake को स्लैश के बिना लिखने पर भी सही माना जाता है।'],
    ),
  },
  {
    slug: 'lyon-a', city: 'lyon', color: '#e2231a',
    label: { ko: 'A선', en: 'Line A', es: 'Línea A', pt: 'Linha A', ja: 'A線', de: 'Linie A', fr: 'Ligne A', hi: 'लाइन A' },
    shape: ['NE', 'NE', 'NE', 'N', 'N', 'NE', 'NE', 'E', 'E', 'E', 'E', 'E', 'E'],
    stations: [
      s('Perrache', undefined, 'terminus'), s('Ampère – Victor Hugo', 'Ampere Victor Hugo'),
      s('Bellecour', undefined, 'transfer'), s('Cordeliers'),
      s('Hôtel de Ville – Louis Pradel', 'Hotel de Ville Louis Pradel', 'transfer'),
      s('Foch'), s('Masséna', 'Massena'), s('Charpennes – Charles Hernu', 'Charpennes Charles Hernu', 'transfer'),
      s('République – Villeurbanne', 'Republique Villeurbanne'), s('Gratte-Ciel', 'Gratte Ciel'),
      s('Flachet'), s('Cusset'), s('Laurent Bonnevay – Astroballe', 'Laurent Bonnevay Astroballe'),
      s('Vaulx-en-Velin – La Soie', 'Vaulx en Velin La Soie', 'terminus'),
    ],
    text: T(
      ['1978년에 개통한 리옹 지하철의 첫 노선입니다. 페라슈에서 두 강 사이 도심을 지나 뷔르반과 볼앙벨랭까지 이어집니다.',
       '악상과 붙임표가 없어도 정답으로 받습니다. Bellecour·Cordeliers·Charpennes를 뼈대로 잡아 보세요.'],
      ['The first line of the Lyon metro, opened in 1978. From Perrache it crosses the centre between the two rivers and runs out to Villeurbanne and Vaulx-en-Velin.',
       'Accents and hyphens can be left out. Anchor on Bellecour, Cordeliers and Charpennes.'],
      ['La primera línea del metro de Lyon, inaugurada en 1978. Desde Perrache cruza el centro entre los dos ríos y llega a Villeurbanne y Vaulx-en-Velin.',
       'Puedes omitir acentos y guiones. Fija Bellecour, Cordeliers y Charpennes como puntos de apoyo.'],
      ['A primeira linha do metrô de Lyon, inaugurada em 1978. De Perrache atravessa o centro entre os dois rios e segue até Villeurbanne e Vaulx-en-Velin.',
       'Pode omitir acentos e hifens. Fixe Bellecour, Cordeliers e Charpennes como pontos de apoio.'],
      ['1978年に開通したリヨン地下鉄の最初の路線です。ペラシュから二つの川に挟まれた中心部を通り、ヴィルールバンヌとヴォー・アン・ヴランまで延びます。',
       'アクサンやハイフンは省いても正解です。Bellecour・Cordeliers・Charpennes を骨組みにしましょう。'],
      ['Die erste Linie der Lyoner Metro, 1978 eröffnet. Von Perrache queert sie das Zentrum zwischen den beiden Flüssen und fährt hinaus nach Villeurbanne und Vaulx-en-Velin.',
       'Akzente und Bindestriche darf man weglassen. Nimm Bellecour, Cordeliers und Charpennes als Anker.'],
      ['La première ligne du métro de Lyon, ouverte en 1978. Depuis Perrache, elle traverse le centre entre les deux fleuves et rejoint Villeurbanne et Vaulx-en-Velin.',
       'On peut omettre accents et traits d’union. Prenez Bellecour, Cordeliers et Charpennes comme repères.'],
      ['1978 में खुली ल्योन मेट्रो की पहली लाइन। Perrache से यह दो नदियों के बीच के केंद्र को पार करती है और Villeurbanne तथा Vaulx-en-Velin तक जाती है।',
       'उच्चारण-चिह्न और हाइफ़न छोड़ सकते हैं। Bellecour, Cordeliers और Charpennes को ढाँचा बनाएँ।'],
    ),
  },
  {
    slug: 'munich-u6', city: 'munich', label: 'U6', color: '#0065ae',
    shape: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'SW', 'SW', 'S', 'S', 'S', 'S', 'SW', 'SW', 'SW', 'W', 'W', 'W', 'SW'],
    stations: [
      s('Garching-Forschungszentrum', 'Garching Forschungszentrum', 'terminus'), s('Garching'),
      s('Garching-Hochbrück', 'Garching Hochbrueck'), s('Fröttmaning', 'Froettmaning'),
      s('Kieferngarten'), s('Freimann'), s('Studentenstadt'), s('Alte Heide'),
      s('Nordfriedhof'), s('Dietlindenstraße', 'Dietlindenstrasse'),
      s('Münchner Freiheit', 'Muenchner Freiheit', 'transfer'), s('Giselastraße', 'Giselastrasse'),
      s('Universität', 'Universitaet'), s('Odeonsplatz', undefined, 'transfer'),
      s('Marienplatz', undefined, 'transfer'), s('Sendlinger Tor', undefined, 'transfer'),
      s('Goetheplatz'), s('Poccistraße', 'Poccistrasse'), s('Implerstraße', 'Implerstrasse', 'transfer'),
      s('Harras'), s('Partnachplatz'), s('Westpark'), s('Holzapfelkreuth'),
      s('Haderner Stern'), s('Großhadern', 'Grosshadern'),
      s('Klinikum Großhadern', 'Klinikum Grosshadern', 'terminus'),
    ],
    text: T(
      ['뮌헨 U반에서 가장 긴 노선으로 북쪽 가르힝 연구단지에서 남서쪽 대학병원까지 이어집니다. 축구장이 있는 프뢰트마닝과 마리엔플라츠를 한 노선에서 지납니다.',
       'ß는 ss로, 움라우트는 ue·oe로 쳐도 정답입니다. Marienplatz·Odeonsplatz·Universität를 뼈대로 잡으세요.'],
      ['The longest line on the Munich U-Bahn, from the Garching research campus in the north to the university hospital in the south-west. Fröttmaning, by the stadium, and Marienplatz sit on the same line.',
       'Type ss for ß and ue or oe for the umlauts. Anchor on Marienplatz, Odeonsplatz and Universität.'],
      ['La línea más larga del metro de Múnich, del campus de investigación de Garching, al norte, al hospital universitario, al suroeste. Fröttmaning, junto al estadio, y Marienplatz están en la misma línea.',
       'Escribe ss por ß y ue u oe por las diéresis. Fija Marienplatz, Odeonsplatz y Universität.'],
      ['A linha mais longa do metrô de Munique, do campus de pesquisa de Garching, ao norte, até o hospital universitário, a sudoeste. Fröttmaning, junto ao estádio, e Marienplatz ficam na mesma linha.',
       'Digite ss no lugar de ß e ue ou oe no lugar dos tremas. Fixe Marienplatz, Odeonsplatz e Universität.'],
      ['ミュンヘンUバーンで最も長い路線で、北のガルヒング研究キャンパスから南西の大学病院まで結びます。スタジアムのあるフレットマニングとマリエンプラッツが同じ線上にあります。',
       'ß は ss、ウムラウトは ue・oe と打っても正解です。Marienplatz・Odeonsplatz・Universität を骨組みにしましょう。'],
      ['Die längste Linie der Münchner U-Bahn, vom Forschungscampus Garching im Norden bis zum Klinikum im Südwesten. Fröttmaning am Stadion und Marienplatz liegen auf derselben Linie.',
       'Für ß darf man ss tippen, für Umlaute ue oder oe. Nimm Marienplatz, Odeonsplatz und Universität als Anker.'],
      ['La plus longue ligne du métro de Munich, du campus de recherche de Garching au nord jusqu’à l’hôpital universitaire au sud-ouest. Fröttmaning, près du stade, et Marienplatz sont sur la même ligne.',
       'On peut taper ss pour ß et ue ou oe pour les trémas. Prenez Marienplatz, Odeonsplatz et Universität comme repères.'],
      ['म्यूनिक यू-बान की सबसे लंबी लाइन — उत्तर में Garching के शोध परिसर से दक्षिण-पश्चिम में विश्वविद्यालय अस्पताल तक। स्टेडियम वाला Fröttmaning और Marienplatz एक ही लाइन पर हैं।',
       'ß के लिए ss और उमलाउट के लिए ue या oe लिख सकते हैं। Marienplatz, Odeonsplatz और Universität को ढाँचा बनाएँ।'],
    ),
  },
  {
    slug: 'barcelona-l3', city: 'barcelona', label: 'L3', color: '#00a94f',
    shape: ['E', 'E', 'E', 'SE', 'SE', 'SE', 'E', 'E', 'SE', 'SE', 'E', 'E', 'NE', 'NE', 'NE', 'N', 'N', 'N', 'NE', 'NE', 'NE', 'N', 'N', 'NW', 'NW'],
    stations: [
      s('Zona Universitària', 'Zona Universitaria', 'terminus'), s('Palau Reial'),
      s('Maria Cristina'), s('Les Corts'), s('Plaça del Centre', 'Placa del Centre'),
      s('Sants Estació', 'Sants Estacio', 'transfer'), s('Tarragona'),
      s('Espanya', undefined, 'transfer'), s('Poble Sec'), s('Paral·lel', 'Parallel', 'transfer'),
      s('Drassanes'), s('Liceu'), s('Catalunya', undefined, 'transfer'),
      s('Passeig de Gràcia', 'Passeig de Gracia', 'transfer'), s('Diagonal', undefined, 'transfer'),
      s('Fontana'), s('Lesseps'), s('Vallcarca'), s('Penitents'),
      s('Vall d’Hebron', 'Vall d Hebron', 'transfer'), s('Montbau'), s('Mundet'),
      s('Valldaura'), s('Canyelles'), s('Roquetes'), s('Trinitat Nova', undefined, 'terminus'),
    ],
    text: T(
      ['바르셀로나에서 가장 먼저 개통한 노선으로 람블라스 거리 아래를 지납니다. 카탈루냐 광장과 파세이그 데 그라시아를 지나 북쪽 언덕으로 올라갑니다.',
       '카탈루냐어 표기라 Plaça·Gràcia처럼 특수 문자가 있지만 없이 쳐도 정답입니다. Liceu·Catalunya·Diagonal이 뼈대입니다.'],
      ['The oldest line in Barcelona, running beneath La Rambla. It passes Plaça de Catalunya and Passeig de Gràcia before climbing to the hills in the north.',
       'The names are Catalan, so Plaça and Gràcia carry marks — typing them plain counts. Liceu, Catalunya and Diagonal are the anchors.'],
      ['La línea más antigua de Barcelona; pasa por debajo de La Rambla. Recorre Plaça de Catalunya y Passeig de Gràcia antes de subir a los cerros del norte.',
       'Los nombres son catalanes, así que Plaça y Gràcia llevan signos; escribirlos sin ellos también vale. Liceu, Catalunya y Diagonal son los apoyos.'],
      ['A linha mais antiga de Barcelona; passa por baixo de La Rambla. Atravessa a Plaça de Catalunya e o Passeig de Gràcia antes de subir aos morros do norte.',
       'Os nomes são catalães, então Plaça e Gràcia levam sinais; escrevê-los sem eles também vale. Liceu, Catalunya e Diagonal são os apoios.'],
      ['バルセロナで最初に開通した路線で、ランブラス通りの下を通ります。カタルーニャ広場とパセイジ・デ・グラシアを経て北の丘へ上がります。',
       '駅名はカタルーニャ語で Plaça・Gràcia のような記号が付きますが、なしで打っても正解です。Liceu・Catalunya・Diagonal が骨組みです。'],
      ['Die älteste Linie Barcelonas; sie verläuft unter La Rambla. Über Plaça de Catalunya und Passeig de Gràcia steigt sie zu den Hügeln im Norden.',
       'Die Namen sind katalanisch, Plaça und Gràcia tragen Zeichen — schlicht getippt zählt auch. Liceu, Catalunya und Diagonal sind die Anker.'],
      ['La plus ancienne ligne de Barcelone ; elle passe sous La Rambla. Elle desservit la Plaça de Catalunya et le Passeig de Gràcia avant de monter vers les collines du nord.',
       'Les noms sont catalans : Plaça et Gràcia portent des signes, mais la forme simple compte. Liceu, Catalunya et Diagonal servent de repères.'],
      ['बार्सिलोना की सबसे पुरानी लाइन; यह La Rambla के नीचे से जाती है। Plaça de Catalunya और Passeig de Gràcia से गुज़रकर उत्तर की पहाड़ियों पर चढ़ती है।',
       'नाम कातालान में हैं, इसलिए Plaça और Gràcia पर चिह्न हैं — बिना चिह्न लिखने पर भी सही है। Liceu, Catalunya और Diagonal ढाँचा हैं।'],
    ),
  },
  {
    slug: 'saopaulo-linha-1', city: 'saopaulo', num: '1', color: '#0d4f9e',
    shape: ['S', 'S', 'S', 'S', 'S', 'S', 'SW', 'SW', 'S', 'S', 'S', 'S', 'S', 'SE', 'SE', 'S', 'S', 'S', 'S', 'S', 'S', 'S'],
    stations: [
      s('Tucuruvi', undefined, 'terminus'), s('Parada Inglesa'),
      s('Jardim São Paulo–Ayrton Senna', 'Jardim Sao Paulo Ayrton Senna'), s('Santana'),
      s('Carandiru'), s('Portuguesa-Tietê', 'Portuguesa Tiete'), s('Armênia', 'Armenia'),
      s('Tiradentes'), s('Luz', undefined, 'transfer'), s('São Bento', 'Sao Bento'),
      s('Sé', 'Se', 'transfer'), s('Liberdade'), s('São Joaquim', 'Sao Joaquim'),
      s('Vergueiro'), s('Paraíso', 'Paraiso', 'transfer'), s('Ana Rosa', undefined, 'transfer'),
      s('Vila Mariana'), s('Santa Cruz', undefined, 'transfer'), s('Praça da Árvore', 'Praca da Arvore'),
      s('Saúde', 'Saude'), s('São Judas', 'Sao Judas'), s('Conceição', 'Conceicao'),
      s('Jabaquara', undefined, 'terminus'),
    ],
    text: T(
      ['남아메리카에서 처음 개통한 지하철 노선으로 상파울루를 남북으로 관통합니다. 세와 루스에서 다른 노선과 갈아탑니다.',
       '악센트가 없어도 정답으로 받습니다. Sé·Luz·Paraíso 같은 짧은 이름을 먼저 놓아 보세요.'],
      ['The first metro line in South America, running north to south through São Paulo. Sé and Luz are the main interchanges.',
       'Spellings without accents count. Start from the short names — Sé, Luz, Paraíso.'],
      ['La primera línea de metro de América del Sur; recorre São Paulo de norte a sur. Sé y Luz son los transbordos principales.',
       'Las grafías sin acentos valen. Empieza por los nombres cortos: Sé, Luz, Paraíso.'],
      ['A primeira linha de metrô da América do Sul; atravessa São Paulo de norte a sul. Sé e Luz são as principais baldeações.',
       'As grafias sem acento valem. Comece pelos nomes curtos: Sé, Luz, Paraíso.'],
      ['南アメリカで最初に開通した地下鉄路線で、サンパウロを南北に貫きます。セーとルースで他線に乗り換えられます。',
       'アクセント記号なしでも正解です。Sé・Luz・Paraíso のような短い駅名から置いてみましょう。'],
      ['Die erste Metrolinie Südamerikas; sie durchquert São Paulo von Nord nach Süd. Sé und Luz sind die wichtigsten Umsteigepunkte.',
       'Schreibweisen ohne Akzente zählen. Fang mit den kurzen Namen an — Sé, Luz, Paraíso.'],
      ['La première ligne de métro d’Amérique du Sud ; elle traverse São Paulo du nord au sud. Sé et Luz sont les principales correspondances.',
       'Les graphies sans accents comptent. Commencez par les noms courts : Sé, Luz, Paraíso.'],
      ['दक्षिण अमेरिका की सबसे पहली मेट्रो लाइन; यह साओ पाउलो को उत्तर से दक्षिण पार करती है। Sé और Luz मुख्य इंटरचेंज हैं।',
       'बिना उच्चारण-चिह्न वाली वर्तनी भी चलती है। छोटे नामों से शुरू करें — Sé, Luz, Paraíso।'],
    ),
  },
  {
    slug: 'rio-linha-1', city: 'rio', num: '1', color: '#f58220',
    shape: ['SE', 'SE', 'SE', 'SE', 'SE', 'S', 'S', 'SE', 'SE', 'SE', 'S', 'S', 'SW', 'SW', 'SW', 'W', 'W', 'W', 'SW', 'SW'],
    stations: [
      s('Uruguai', undefined, 'terminus'), s('Sáenz Peña', 'Saens Pena'), s('Afonso Pena'),
      s('São Francisco Xavier', 'Sao Francisco Xavier'), s('Maracanã', 'Maracana'),
      s('Estácio', 'Estacio', 'transfer'), s('Praça Onze', 'Praca Onze'),
      s('Central', undefined, 'transfer'), s('Presidente Vargas'), s('Uruguaiana'),
      s('Carioca', undefined, 'transfer'), s('Cinelândia', 'Cinelandia'),
      s('Glória', 'Gloria'), s('Catete'), s('Largo do Machado'), s('Flamengo'),
      s('Botafogo', undefined, 'transfer'), s('Cardeal Arcoverde'), s('Siqueira Campos'),
      s('Cantagalo'), s('General Osório', 'General Osorio', 'terminus'),
    ],
    text: T(
      ['리우데자네이루 지하철의 첫 노선으로 마라카낭 경기장에서 코파카바나와 이파네마까지 이어집니다. 해변 가까이까지 지하철로 갈 수 있습니다.',
       '악센트가 없어도 정답으로 받습니다. Maracanã·Botafogo·Copacabana 쪽 이름을 먼저 떠올려 보세요.'],
      ['The first line of the Rio metro, linking the Maracanã stadium with Copacabana and Ipanema. It puts the beach within a short walk of a station.',
       'Spellings without accents count. Start from the names you know — Maracanã, Botafogo, and the Copacabana end.'],
      ['La primera línea del metro de Río; une el estadio de Maracaná con Copacabana e Ipanema. Deja la playa a un paso de la estación.',
       'Las grafías sin acentos valen. Empieza por los nombres conocidos: Maracanã, Botafogo y el extremo de Copacabana.'],
      ['A primeira linha do metrô do Rio; liga o Maracanã a Copacabana e Ipanema. Deixa a praia a poucos passos da estação.',
       'As grafias sem acento valem. Comece pelos nomes conhecidos: Maracanã, Botafogo e a ponta de Copacabana.'],
      ['リオデジャネイロ地下鉄の最初の路線で、マラカナン競技場からコパカバーナ・イパネマまで結びます。駅から海辺まで歩いてすぐです。',
       'アクセント記号なしでも正解です。Maracanã・Botafogo やコパカバーナ側の駅名から思い出しましょう。'],
      ['Die erste Linie der Metro von Rio; sie verbindet das Maracanã-Stadion mit Copacabana und Ipanema. Vom Bahnsteig bis zum Strand sind es nur ein paar Schritte.',
       'Schreibweisen ohne Akzente zählen. Fang mit den bekannten Namen an — Maracanã, Botafogo und das Ende bei Copacabana.'],
      ['La première ligne du métro de Rio ; elle relie le stade Maracanã à Copacabana et Ipanema. La plage est à deux pas d’une station.',
       'Les graphies sans accents comptent. Partez des noms connus : Maracanã, Botafogo et le bout côté Copacabana.'],
      ['रियो मेट्रो की पहली लाइन; यह Maracanã स्टेडियम को Copacabana और Ipanema से जोड़ती है। स्टेशन से समुद्र तट कुछ ही क़दम दूर रह जाता है।',
       'बिना उच्चारण-चिह्न वाली वर्तनी भी चलती है। जाने-पहचाने नामों से शुरू करें — Maracanã, Botafogo और Copacabana वाला सिरा।'],
    ),
  },
  {
    slug: 'mumbai-line-1', city: 'mumbai', num: '1', color: '#0072bc',
    shape: ['E', 'E', 'E', 'SE', 'SE', 'E', 'E', 'SE', 'SE', 'E', 'E'],
    stations: [
      sa('Versova', 'वर्सोवा', 'terminus'), sa('D N Nagar', 'डी एन नगर'), sa('Azad Nagar', 'आज़ाद नगर'),
      sa('Andheri', 'अंधेरी', 'transfer'), sa('Western Express Highway', 'वेस्टर्न एक्सप्रेस हाईवे'),
      sa('Chakala', 'चकाला'), sa('Airport Road', 'एयरपोर्ट रोड'), sa('Marol Naka', 'मरोल नाका', 'transfer'),
      sa('Saki Naka', 'साकी नाका'), sa('Asalpha', 'असल्फा'), sa('Jagruti Nagar', 'जागृति नगर'),
      sa('Ghatkopar', 'घाटकोपर', 'terminus'),
    ],
    text: T(
      ['뭄바이에서 가장 먼저 개통한 지하철로 서쪽 베르소바에서 동쪽 가트코파르까지 도시를 가로지릅니다. 열두 개 역뿐이지만 두 시간 걸리던 길을 이십 분으로 줄였습니다.',
       '영문 표기와 데바나가리 표기를 모두 정답으로 받습니다. Andheri와 Ghatkopar가 양쪽 환승 거점입니다.'],
      ['Mumbai’s first metro line, crossing the city from Versova in the west to Ghatkopar in the east. Only twelve stations, but it turned a two-hour trip into twenty minutes.',
       'Both the English and the Devanagari spelling count. Andheri and Ghatkopar are the interchanges at either end.'],
      ['La primera línea de metro de Bombay; cruza la ciudad de Versova, al oeste, a Ghatkopar, al este. Solo doce estaciones, pero convirtió un viaje de dos horas en veinte minutos.',
       'Valen tanto la grafía inglesa como la devanagari. Andheri y Ghatkopar son los transbordos de cada extremo.'],
      ['A primeira linha de metrô de Mumbai; cruza a cidade de Versova, a oeste, até Ghatkopar, a leste. São só doze estações, mas ela transformou duas horas de viagem em vinte minutos.',
       'Valem tanto a grafia inglesa como a devanágari. Andheri e Ghatkopar são as baldeações de cada ponta.'],
      ['ムンバイで最初に開通した地下鉄で、西のヴェルソヴァから東のガートコーパルまで市内を横切ります。十二駅しかありませんが、二時間かかった道を二十分に縮めました。',
       '英字表記とデーヴァナーガリー表記のどちらも正解です。Andheri と Ghatkopar が両端の乗り換え駅です。'],
      ['Mumbais erste Metrolinie; sie querte die Stadt von Versova im Westen bis Ghatkopar im Osten. Nur zwölf Stationen, doch aus zwei Stunden Fahrt wurden zwanzig Minuten.',
       'Sowohl die englische als auch die Devanagari-Schreibweise zählt. Andheri und Ghatkopar sind die Umstiege an den Enden.'],
      ['La première ligne de métro de Mumbai ; elle traverse la ville de Versova, à l’ouest, à Ghatkopar, à l’est. Douze stations seulement, mais deux heures de trajet réduites à vingt minutes.',
       'La graphie anglaise comme la devanagari comptent. Andheri et Ghatkopar sont les correspondances aux deux bouts.'],
      ['मुंबई की सबसे पहली मेट्रो लाइन; यह पश्चिम के वर्सोवा से पूर्व के घाटकोपर तक शहर को पार करती है। सिर्फ़ बारह स्टेशन, पर दो घंटे का रास्ता बीस मिनट का हो गया।',
       'अंग्रेज़ी और देवनागरी दोनों वर्तनी सही मानी जाती हैं। अंधेरी और घाटकोपर दोनों सिरों के इंटरचेंज हैं।'],
    ),
  },
];
