/**
 * 지하철 노선 - 서울 (9)
 *
 * 역 이름은 현재 안내 표기를 따른다. 병기역명(잠실새내처럼 개명된 것)은 개명 뒤
 * 이름을 정답으로 두고 옛 이름은 로마자 칸이 아니라 힌트 문구에서 다룬다.
 *
 * 도시·나라 이름과 "n호선"은 여기 적지 않는다 — cities.ts와 lang.ts에서 여덟 언어가
 * 기계적으로 나온다. 여기 적는 것은 노선마다 다른 소개와 힌트뿐이다.
 */
import { T, s } from './copy.ts';
import type { MetroLine } from './types.ts';

export const SEOUL_LINES: MetroLine[] = [
  {
    slug: 'seoul-line-1', city: 'seoul', num: '1', color: '#0052a4',
    shape: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'SW', 'SW', 'SW', 'S', 'S', 'S', 'SW', 'SW', 'SW', 'W', 'W', 'W', 'SW', 'SW', 'SW', 'SW', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S'],
    stations: [
      s('소요산', 'Soyosan', 'terminus'), s('동두천', 'Dongducheon'), s('보산', 'Bosan'),
      s('동두천중앙', 'Dongducheon Jungang'), s('지행', 'Jihaeng'), s('덕정', 'Deokjeong'),
      s('덕계', 'Deokgye'), s('양주', 'Yangju'), s('녹양', 'Nogyang'), s('가능', 'Ganeung'),
      s('의정부', 'Uijeongbu', 'transfer'), s('회룡', 'Hoeryong', 'transfer'), s('망월사', 'Mangwolsa'),
      s('도봉산', 'Dobongsan', 'transfer'), s('도봉', 'Dobong'), s('방학', 'Banghak'),
      s('창동', 'Changdong', 'transfer'), s('녹천', 'Nokcheon'), s('월계', 'Wolgye'),
      s('광운대', 'Kwangwoon Univ.'), s('석계', 'Seokgye', 'transfer'), s('신이문', 'Sinimun'),
      s('외대앞', 'Hankuk Univ. of Foreign Studies'), s('회기', 'Hoegi', 'transfer'),
      s('청량리', 'Cheongnyangni', 'transfer'), s('제기동', 'Jegi-dong'), s('신설동', 'Sinseol-dong', 'transfer'),
      s('동묘앞', 'Dongmyo', 'transfer'), s('동대문', 'Dongdaemun', 'transfer'), s('종로5가', 'Jongno 5-ga'),
      s('종로3가', 'Jongno 3-ga', 'transfer'), s('종각', 'Jonggak'), s('시청', 'City Hall', 'transfer'),
      s('서울역', 'Seoul Station', 'transfer'), s('남영', 'Namyeong'), s('용산', 'Yongsan', 'transfer'),
      s('노량진', 'Noryangjin', 'transfer'), s('대방', 'Daebang'), s('신길', 'Singil', 'transfer'),
      s('영등포', 'Yeongdeungpo'), s('신도림', 'Sindorim', 'transfer'), s('구로', 'Guro', 'transfer'),
    ],
    text: T(
      ['한국에서 가장 먼저 개통한 지하철이고 지금은 소요산에서 구로까지 이어집니다. 구로 남쪽에서 경인선과 경부선으로 갈라집니다.',
       '종로 구간은 3가·5가처럼 숫자가 붙어 순서를 기억하기 쉽습니다. 북쪽 경기 구간은 동두천·양주 이름이 이어집니다.'],
      ['Korea’s first subway line, now running from Soyosan down to Guro, where it splits towards Incheon and Suwon.',
       'The Jongno stretch is numbered — 3-ga, 5-ga — which makes the order easy. North of Seoul the names come from Dongducheon and Yangju.'],
      ['La primera línea de metro de Corea; hoy va desde Soyosan hasta Guro, donde se bifurca hacia Incheon y Suwon.',
       'El tramo de Jongno va numerado — 3-ga, 5-ga —, así que el orden es fácil. Al norte de Seúl los nombres vienen de Dongducheon y Yangju.'],
      ['A primeira linha de metrô da Coreia; hoje vai de Soyosan até Guro, onde se divide em direção a Incheon e Suwon.',
       'O trecho de Jongno é numerado — 3-ga, 5-ga —, o que facilita a ordem. Ao norte de Seul os nomes vêm de Dongducheon e Yangju.'],
      ['韓国で最初に開通した地下鉄で、いまは逍遥山から九老まで伸びています。九老の南で仁川方面と水原方面に分かれます。',
       '鍾路の区間は3街・5街と番号がついていて順番を覚えやすいです。ソウルより北は東豆川・楊州あたりの地名が続きます。'],
      ['Koreas erste U-Bahn-Linie, die heute von Soyosan bis Guro führt und sich südlich von Guro nach Incheon und Suwon teilt.',
       'Der Abschnitt Jongno ist durchnummeriert — 3-ga, 5-ga —, das macht die Reihenfolge leicht. Nördlich von Seoul stammen die Namen aus Dongducheon und Yangju.'],
      ['La première ligne de métro de Corée ; elle va aujourd’hui de Soyosan à Guro, où elle se divise vers Incheon et Suwon.',
       'Le tronçon de Jongno est numéroté — 3-ga, 5-ga —, ce qui aide pour l’ordre. Au nord de Séoul, les noms viennent de Dongducheon et Yangju.'],
      ['कोरिया की सबसे पहली मेट्रो लाइन, जो अब Soyosan से Guro तक चलती है और Guro के दक्षिण में Incheon तथा Suwon की ओर बँट जाती है।',
       'Jongno वाला हिस्सा 3-ga, 5-ga जैसे नंबरों में है, इसलिए क्रम याद रखना आसान है। सिओल के उत्तर में नाम Dongducheon और Yangju इलाके के हैं।'],
      ['韩国最早通车的地铁线路，如今从逍遥山一路通到九老。过了九老往南，分成开往仁川和水原的两支。',
       '钟路那一段带着 3 街、5 街这样的编号，顺序好记。首尔以北则是东豆川、杨州一带的地名接连出现。'],
      ['韓國最早通車的地鐵路線，如今從逍遙山一路通到九老。過了九老往南，分成開往仁川和水原的兩支。',
       '鐘路那一段帶著 3 街、5 街這樣的編號，順序好記。首爾以北則是東豆川、楊州一帶的地名接連出現。'],
    ),
  },
  {
    slug: 'seoul-line-2', city: 'seoul', num: '2', color: '#00a84d', loop: true,
    shape: ['E', 'E', 'E', 'SE', 'SE', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE', 'S', 'S', 'SW', 'SW', 'SW', 'W', 'W', 'W', 'W', 'W', 'NW', 'NW', 'W', 'W', 'W', 'NW', 'NW', 'N', 'N', 'NE', 'NE', 'NE', 'E', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE'],
    stations: [
      s('시청', 'City Hall', 'transfer'), s('을지로입구', 'Euljiro 1-ga'), s('을지로3가', 'Euljiro 3-ga', 'transfer'),
      s('을지로4가', 'Euljiro 4-ga'), s('동대문역사문화공원', 'Dongdaemun History & Culture Park', 'transfer'),
      s('신당', 'Sindang'), s('상왕십리', 'Sangwangsimni'), s('왕십리', 'Wangsimni', 'transfer'),
      s('한양대', 'Hanyang Univ.'), s('뚝섬', 'Ttukseom'), s('성수', 'Seongsu'),
      s('건대입구', 'Konkuk Univ.', 'transfer'), s('구의', 'Guui'), s('강변', 'Gangbyeon'),
      s('잠실나루', 'Jamsillaru'), s('잠실', 'Jamsil', 'transfer'), s('잠실새내', 'Jamsilsaenae'),
      s('종합운동장', 'Sports Complex', 'transfer'), s('삼성', 'Samseong'), s('선릉', 'Seolleung', 'transfer'),
      s('역삼', 'Yeoksam'), s('강남', 'Gangnam', 'transfer'), s('교대', 'Seoul Nat’l Univ. of Education', 'transfer'),
      s('서초', 'Seocho'), s('방배', 'Bangbae'), s('사당', 'Sadang', 'transfer'),
      s('낙성대', 'Nakseongdae'), s('서울대입구', 'Seoul Nat’l Univ.'), s('봉천', 'Bongcheon'),
      s('신림', 'Sillim'), s('신대방', 'Sindaebang'), s('구로디지털단지', 'Guro Digital Complex'),
      s('대림', 'Daerim', 'transfer'), s('신도림', 'Sindorim', 'transfer'), s('문래', 'Mullae'),
      s('영등포구청', 'Yeongdeungpo-gu Office', 'transfer'), s('당산', 'Dangsan', 'transfer'),
      s('합정', 'Hapjeong', 'transfer'), s('홍대입구', 'Hongik Univ.', 'transfer'), s('신촌', 'Sinchon'),
      s('이대', 'Ewha Womans Univ.'), s('아현', 'Ahyeon'), s('충정로', 'Chungjeongno', 'transfer'),
    ],
    text: T(
      ['서울 도심을 한 바퀴 도는 순환선으로 세계에서 가장 긴 순환 지하철 가운데 하나입니다. 시청에서 출발해 강남을 지나 다시 시청으로 돌아옵니다.',
       '순환선이라 시작과 끝이 같습니다. 강남·잠실·홍대입구 같은 큰 역을 먼저 떠올리고 그 사이를 채우면 수월합니다.'],
      ['A loop around central Seoul and one of the longest circular metro lines in the world. It leaves City Hall, runs through Gangnam and comes back to City Hall.',
       'Being a loop, it starts and ends at the same place. Pin down the big interchanges — Gangnam, Jamsil, Hongik Univ. — then fill the gaps.'],
      ['Un anillo alrededor del centro de Seúl y una de las líneas circulares más largas del mundo. Sale de City Hall, pasa por Gangnam y vuelve a City Hall.',
       'Al ser circular, empieza y acaba en el mismo punto. Fija primero los grandes intercambiadores — Gangnam, Jamsil, Hongik Univ. — y rellena los huecos.'],
      ['Um anel em volta do centro de Seul e uma das linhas circulares mais longas do mundo. Sai de City Hall, passa por Gangnam e volta a City Hall.',
       'Sendo circular, começa e termina no mesmo ponto. Fixe primeiro as grandes baldeações — Gangnam, Jamsil, Hongik Univ. — e depois preencha os vãos.'],
      ['ソウル都心を一周する環状線で、世界でも最長級の環状地下鉄です。市庁を出て江南を回り、また市庁に戻ります。',
       '環状線なので始まりと終わりが同じです。江南・蚕室・弘大入口といった大きな駅を先に置き、その間を埋めると楽です。'],
      ['Eine Ringlinie um die Innenstadt von Seoul und einer der längsten U-Bahn-Ringe der Welt. Sie verlässt City Hall, führt durch Gangnam und kehrt nach City Hall zurück.',
       'Als Ring beginnt und endet sie am gleichen Ort. Setze zuerst die großen Umsteigepunkte — Gangnam, Jamsil, Hongik Univ. — und füll dann die Lücken.'],
      ['Une boucle autour du centre de Séoul, et l’une des plus longues lignes circulaires du monde. Elle quitte City Hall, traverse Gangnam et revient à City Hall.',
       'Comme c’est une boucle, le départ et l’arrivée se confondent. Posez d’abord les grands échangeurs — Gangnam, Jamsil, Hongik Univ. — puis comblez les trous.'],
      ['सिओल के मध्य भाग का चक्कर लगाने वाली रिंग लाइन, दुनिया की सबसे लंबी सर्कुलर मेट्रो लाइनों में एक। City Hall से चलकर Gangnam होकर फिर City Hall लौट आती है।',
       'रिंग लाइन होने से शुरुआत और अंत एक ही जगह है। पहले बड़े जंक्शन — Gangnam, Jamsil, Hongik Univ. — तय कर लें, फिर बीच की जगहें भरें।'],
      ['绕首尔市中心跑一整圈的环线，是世界上最长的环状地铁之一。从市厅出发经过江南，再绕回市厅。',
       '既然是环线，起点和终点就是同一站。先想起江南、蚕室、弘大入口这些大站，再把中间填上，会轻松很多。'],
      ['繞首爾市中心跑一整圈的環線，是世界上最長的環狀地鐵之一。從市廳出發經過江南，再繞回市廳。',
       '既然是環線，起點和終點就是同一站。先想起江南、蠶室、弘大入口這些大站，再把中間填上，會輕鬆很多。'],
    ),
  },
  {
    slug: 'seoul-line-3', city: 'seoul', num: '3', color: '#ef7c1c',
    shape: ['SE', 'SE', 'SE', 'S', 'S', 'SE', 'SE', 'E', 'E', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE', 'SE', 'S', 'SE', 'SE', 'E', 'E', 'SE', 'SE', 'SE', 'E', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE'],
    stations: [
      s('대화', 'Daehwa', 'terminus'), s('주엽', 'Juyeop'), s('정발산', 'Jeongbalsan'), s('마두', 'Madu'),
      s('백석', 'Baekseok'), s('대곡', 'Daegok', 'transfer'), s('화정', 'Hwajeong'), s('원당', 'Wondang'),
      s('원흥', 'Wonheung'), s('삼송', 'Samsong'), s('지축', 'Jichuk'), s('구파발', 'Gupabal'),
      s('연신내', 'Yeonsinnae', 'transfer'), s('불광', 'Bulgwang', 'transfer'), s('녹번', 'Nokbeon'),
      s('홍제', 'Hongje'), s('무악재', 'Muakjae'), s('독립문', 'Dongnimmun'), s('경복궁', 'Gyeongbokgung'),
      s('안국', 'Anguk'), s('종로3가', 'Jongno 3-ga', 'transfer'), s('을지로3가', 'Euljiro 3-ga', 'transfer'),
      s('충무로', 'Chungmuro', 'transfer'), s('동대입구', 'Dongguk Univ.'), s('약수', 'Yaksu', 'transfer'),
      s('금호', 'Geumho'), s('옥수', 'Oksu'), s('압구정', 'Apgujeong'), s('신사', 'Sinsa'),
      s('잠원', 'Jamwon'), s('고속터미널', 'Express Bus Terminal', 'transfer'), s('교대', 'Seoul Nat’l Univ. of Education', 'transfer'),
      s('남부터미널', 'Nambu Bus Terminal'), s('양재', 'Yangjae', 'transfer'), s('매봉', 'Maebong'),
      s('도곡', 'Dogok'), s('대치', 'Daechi'), s('학여울', 'Hangnyeoul'), s('대청', 'Daecheong'),
      s('일원', 'Irwon'), s('수서', 'Suseo', 'transfer'), s('가락시장', 'Garak Market', 'transfer'),
      s('경찰병원', 'Police Hospital'), s('오금', 'Ogeum', 'terminus'),
    ],
    text: T(
      ['고양 대화에서 송파 오금까지 서울을 북서에서 남동으로 가로지릅니다. 경복궁·안국처럼 고궁 근처를 지나고 압구정·고속터미널을 거칩니다.',
       '북서쪽 고양 구간은 일산 신도시 이름이 많고, 남동쪽은 강남 학원가 이름이 이어집니다. 두 덩이로 나눠 떠올리면 쉽습니다.'],
      ['From Daehwa in Goyang to Ogeum in Songpa, cutting north-west to south-east across Seoul. It passes the palaces at Gyeongbokgung and Anguk before reaching Apgujeong.',
       'The north-west stretch is Ilsan new-town names; the south-east is the Gangnam study district. Recall it in two blocks.'],
      ['De Daehwa, en Goyang, a Ogeum, en Songpa, cruzando Seúl de noroeste a sureste. Pasa junto a los palacios de Gyeongbokgung y Anguk antes de llegar a Apgujeong.',
       'El tramo noroeste son nombres de la ciudad nueva de Ilsan; el sureste, el barrio de academias de Gangnam. Recuérdalo en dos bloques.'],
      ['De Daehwa, em Goyang, até Ogeum, em Songpa, cortando Seul do noroeste ao sudeste. Passa pelos palácios de Gyeongbokgung e Anguk antes de chegar a Apgujeong.',
       'O trecho noroeste traz nomes da cidade nova de Ilsan; o sudeste, o bairro dos cursinhos de Gangnam. Lembre em dois blocos.'],
      ['高陽の大化から松坡の梧琴まで、ソウルを北西から南東へ横切ります。景福宮・安国など宮殿のそばを通り、狎鴎亭と高速ターミナルを経ます。',
       '北西の高陽区間は一山ニュータウンの地名が多く、南東は江南の塾街の地名が続きます。二つに分けて思い出すと楽です。'],
      ['Von Daehwa in Goyang bis Ogeum in Songpa, quer durch Seoul von Nordwest nach Südost. Sie führt an den Palästen bei Gyeongbokgung und Anguk vorbei und weiter nach Apgujeong.',
       'Der Nordwesten trägt Namen der Neustadt Ilsan, der Südosten die des Gangnam-Lernviertels. Merke sie in zwei Blöcken.'],
      ['De Daehwa à Goyang jusqu’à Ogeum à Songpa, en traversant Séoul du nord-ouest au sud-est. Elle longe les palais de Gyeongbokgung et Anguk avant Apgujeong.',
       'Le nord-ouest reprend les noms de la ville nouvelle d’Ilsan ; le sud-est, le quartier des écoles de Gangnam. Retenez-la en deux blocs.'],
      ['Goyang के Daehwa से Songpa के Ogeum तक, सिओल को उत्तर-पश्चिम से दक्षिण-पूर्व तक काटती है। Gyeongbokgung और Anguk के महलों के पास से गुज़रकर Apgujeong पहुँचती है।',
       'उत्तर-पश्चिम वाला हिस्सा Ilsan न्यू टाउन के नामों का है, दक्षिण-पूर्व Gangnam के कोचिंग इलाके का। दो हिस्सों में याद करना आसान रहता है।'],
      ['从高阳大化到松坡梧琴，自西北向东南斜穿首尔。会经过景福宫、安国这些古宫附近，也停靠狎鸥亭和高速巴士客运站。',
       '西北边的高阳段多是一山新城的地名，东南边则接连出现江南补习街一带的名字。分成两块来记就容易了。'],
      ['從高陽大化到松坡梧琴，自西北向東南斜穿首爾。會經過景福宮、安國這些古宮附近，也停靠狎鷗亭和高速巴士客運站。',
       '西北邊的高陽段多是一山新城的地名，東南邊則接連出現江南補習街一帶的名字。分成兩塊來記就容易了。'],
    ),
  },
  {
    slug: 'seoul-line-4', city: 'seoul', num: '4', color: '#00a5de',
    shape: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'SW', 'SW', 'SW', 'S', 'S', 'S', 'SW', 'SW', 'SW', 'SW', 'S', 'S', 'SW', 'SW', 'SW', 'S', 'S', 'S', 'SW', 'SW', 'SW', 'W', 'W', 'W', 'SW', 'SW', 'SW', 'W', 'W', 'W', 'SW', 'SW', 'W', 'W', 'W', 'W', 'W', 'SW', 'SW', 'SW'],
    stations: [
      s('당고개', 'Danggogae', 'terminus'), s('상계', 'Sanggye'), s('노원', 'Nowon', 'transfer'),
      s('창동', 'Changdong', 'transfer'), s('쌍문', 'Ssangmun'), s('수유', 'Suyu'), s('미아', 'Mia'),
      s('미아사거리', 'Miasageori'), s('길음', 'Gireum'), s('성신여대입구', 'Sungshin Women’s Univ.'),
      s('한성대입구', 'Hansung Univ.'), s('혜화', 'Hyehwa'), s('동대문', 'Dongdaemun', 'transfer'),
      s('동대문역사문화공원', 'Dongdaemun History & Culture Park', 'transfer'), s('충무로', 'Chungmuro', 'transfer'),
      s('명동', 'Myeongdong'), s('회현', 'Hoehyeon'), s('서울역', 'Seoul Station', 'transfer'),
      s('숙대입구', 'Sookmyung Women’s Univ.'), s('삼각지', 'Samgakji', 'transfer'), s('신용산', 'Sinyongsan'),
      s('이촌', 'Ichon'), s('동작', 'Dongjak', 'transfer'), s('총신대입구(이수)', 'Isu'),
      s('사당', 'Sadang', 'transfer'), s('남태령', 'Namtaeryeong'), s('선바위', 'Seonbawi'),
      s('경마공원', 'Seoul Racecourse Park'), s('대공원', 'Seoul Grand Park'), s('과천', 'Gwacheon'),
      s('정부과천청사', 'Government Complex Gwacheon'), s('인덕원', 'Indeogwon'), s('평촌', 'Pyeongchon'),
      s('범계', 'Beomgye'), s('금정', 'Geumjeong', 'transfer'), s('산본', 'Sanbon'), s('수리산', 'Surisan'),
      s('대야미', 'Daeyami'), s('반월', 'Banwol'), s('상록수', 'Sangnoksu'), s('한대앞', 'Handaeap', 'transfer'),
      s('중앙', 'Jungang'), s('고잔', 'Gojan'), s('초지', 'Choji', 'transfer'), s('안산', 'Ansan'),
      s('신길온천', 'Singiloncheon'), s('정왕', 'Jeongwang'), s('오이도', 'Oido', 'terminus'),
    ],
    text: T(
      ['노원 당고개에서 시흥 오이도까지 이어지며 서울역과 명동, 동대문을 한 번에 지납니다. 남쪽 구간은 안산선과 이어져 서해까지 내려갑니다.',
       '서울 안에서는 대학 이름이 붙은 역이 잇달아 나옵니다. 성신여대입구·한성대입구·숙대입구를 순서대로 떠올려 보세요.'],
      ['From Danggogae in Nowon down to Oido in Siheung, taking in Seoul Station, Myeongdong and Dongdaemun on one ride. The southern half continues onto the Ansan line and reaches the west coast.',
       'Inside Seoul the line strings together university stations — Sungshin, Hansung and Sookmyung come in order.'],
      ['De Danggogae, en Nowon, hasta Oido, en Siheung, con Seoul Station, Myeongdong y Dongdaemun en un solo viaje. La mitad sur sigue por la línea de Ansan hasta la costa oeste.',
       'Dentro de Seúl se encadenan estaciones universitarias: Sungshin, Hansung y Sookmyung salen en ese orden.'],
      ['De Danggogae, em Nowon, até Oido, em Siheung, com Seoul Station, Myeongdong e Dongdaemun na mesma viagem. A metade sul segue pela linha de Ansan até o litoral oeste.',
       'Dentro de Seul a linha enfileira estações de universidades — Sungshin, Hansung e Sookmyung vêm nessa ordem.'],
      ['蘆原の堂皋崖から始興の梧耳島まで伸び、ソウル駅・明洞・東大門を一度に通ります。南側は安山線につながり西海岸まで下ります。',
       'ソウル市内では大学名の駅が続けて現れます。誠信女大入口・漢城大入口・淑明女大入口の順に思い出してみてください。'],
      ['Von Danggogae in Nowon bis Oido in Siheung, mit Seoul Station, Myeongdong und Dongdaemun auf einer Fahrt. Die Südhälfte geht in die Ansan-Linie über und erreicht die Westküste.',
       'Innerhalb Seouls reihen sich Universitätsstationen: Sungshin, Hansung und Sookmyung kommen in dieser Folge.'],
      ['De Danggogae à Nowon jusqu’à Oido à Siheung, avec Seoul Station, Myeongdong et Dongdaemun sur un seul trajet. La moitié sud se prolonge par la ligne d’Ansan jusqu’à la côte ouest.',
       'Dans Séoul, les stations universitaires s’enchaînent : Sungshin, Hansung puis Sookmyung, dans cet ordre.'],
      ['Nowon के Danggogae से Siheung के Oido तक चलती है और एक ही सफ़र में Seoul Station, Myeongdong तथा Dongdaemun पड़ते हैं। दक्षिणी हिस्सा Ansan लाइन से जुड़कर पश्चिमी तट तक जाता है।',
       'सिओल के अंदर विश्वविद्यालयों के नाम वाले स्टेशन एक के बाद एक आते हैं — Sungshin, Hansung और Sookmyung इसी क्रम में।'],
      ['从芦原堂岭一直通到始兴乌耳岛，一条线就串起首尔站、明洞和东大门。南段接上安山线，一路下到西海边。',
       '在首尔市内，带大学名字的站接连出现。试着按顺序想一遍诚信女大入口、汉城大入口、淑大入口。'],
      ['從蘆原堂嶺一直通到始興烏耳島，一條線就串起首爾站、明洞和東大門。南段接上安山線，一路下到西海邊。',
       '在首爾市內，帶大學名字的站接連出現。試著按順序想一遍誠信女大入口、漢城大入口、淑大入口。'],
    ),
  },
  {
    slug: 'seoul-line-5', city: 'seoul', num: '5', color: '#996cac',
    shape: ['E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'NE', 'NE', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'SE', 'SE', 'E', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE', 'E', 'E', 'E', 'E', 'E', 'NE', 'NE', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E'],
    stations: [
      s('방화', 'Banghwa', 'terminus'), s('개화산', 'Gaehwasan'), s('김포공항', 'Gimpo Int’l Airport', 'transfer'),
      s('송정', 'Songjeong'), s('마곡', 'Magok'), s('발산', 'Balsan'), s('우장산', 'Ujangsan'),
      s('화곡', 'Hwagok'), s('까치산', 'Kkachisan', 'transfer'), s('신정', 'Sinjeong'), s('목동', 'Mokdong'),
      s('오목교', 'Omokgyo'), s('양평', 'Yangpyeong'), s('영등포구청', 'Yeongdeungpo-gu Office', 'transfer'),
      s('영등포시장', 'Yeongdeungpo Market'), s('신길', 'Singil', 'transfer'), s('여의도', 'Yeouido', 'transfer'),
      s('여의나루', 'Yeouinaru'), s('마포', 'Mapo'), s('공덕', 'Gongdeok', 'transfer'), s('애오개', 'Aeogae'),
      s('충정로', 'Chungjeongno', 'transfer'), s('서대문', 'Seodaemun'), s('광화문', 'Gwanghwamun'),
      s('종로3가', 'Jongno 3-ga', 'transfer'), s('을지로4가', 'Euljiro 4-ga', 'transfer'),
      s('동대문역사문화공원', 'Dongdaemun History & Culture Park', 'transfer'), s('청구', 'Cheonggu', 'transfer'),
      s('신금호', 'Singeumho'), s('행당', 'Haengdang'), s('왕십리', 'Wangsimni', 'transfer'),
      s('마장', 'Majang'), s('답십리', 'Dapsimni'), s('장한평', 'Janghanpyeong'), s('군자', 'Gunja', 'transfer'),
      s('아차산', 'Achasan'), s('광나루', 'Gwangnaru'), s('천호', 'Cheonho', 'transfer'), s('강동', 'Gangdong'),
      s('길동', 'Gildong'), s('굽은다리', 'Gubeundari'), s('명일', 'Myeongil'), s('고덕', 'Godeok'),
      s('상일동', 'Sangil-dong'), s('강일', 'Gangil'), s('미사', 'Misa'), s('하남풍산', 'Hanam Pungsan'),
      s('하남시청', 'Hanam City Hall'), s('하남검단산', 'Hanam Geomdansan', 'terminus'),
    ],
    text: T(
      ['김포공항에서 하남까지 서울을 동서로 가장 길게 관통합니다. 여의도와 광화문, 왕십리를 한 노선에서 지납니다.',
       '한강을 두 번 건너고 여의도 구간에서 강 아래를 지납니다. 서쪽은 목동·화곡, 동쪽은 하남 이름이 붙습니다.'],
      ['The longest east–west run across Seoul, from Gimpo Airport out to Hanam. Yeouido, Gwanghwamun and Wangsimni all sit on this one line.',
       'It crosses the Han twice and tunnels beneath it around Yeouido. The west end carries Mokdong and Hwagok names, the east end Hanam ones.'],
      ['El recorrido este–oeste más largo de Seúl, del aeropuerto de Gimpo hasta Hanam. Yeouido, Gwanghwamun y Wangsimni están todos en esta línea.',
       'Cruza el río Han dos veces y pasa por debajo a la altura de Yeouido. El extremo oeste lleva nombres de Mokdong y Hwagok; el este, de Hanam.'],
      ['O percurso leste–oeste mais longo de Seul, do aeroporto de Gimpo até Hanam. Yeouido, Gwanghwamun e Wangsimni ficam todos nesta linha.',
       'Ela cruza o rio Han duas vezes e passa por baixo dele na altura de Yeouido. A ponta oeste traz nomes de Mokdong e Hwagok; a leste, de Hanam.'],
      ['金浦空港から河南まで、ソウルを東西に最も長く貫きます。汝矣島・光化門・往十里が一本の線に並びます。',
       '漢江を二度渡り、汝矣島付近では川の下を通ります。西側は木洞・禾谷、東側は河南の地名が付きます。'],
      ['Die längste Ost-West-Strecke durch Seoul, vom Flughafen Gimpo bis Hanam. Yeouido, Gwanghwamun und Wangsimni liegen alle auf dieser Linie.',
       'Sie überquert den Han zweimal und unterquert ihn bei Yeouido. Das Westende trägt Namen aus Mokdong und Hwagok, das Ostende aus Hanam.'],
      ['Le plus long trajet est–ouest de Séoul, de l’aéroport de Gimpo jusqu’à Hanam. Yeouido, Gwanghwamun et Wangsimni sont tous sur cette ligne.',
       'Elle franchit deux fois le Han et passe dessous vers Yeouido. L’extrémité ouest porte les noms de Mokdong et Hwagok, l’est ceux de Hanam.'],
      ['Gimpo एयरपोर्ट से Hanam तक, सिओल को पूर्व-पश्चिम में सबसे लंबा पार करने वाली लाइन। Yeouido, Gwanghwamun और Wangsimni सब इसी एक लाइन पर हैं।',
       'यह Han नदी को दो बार पार करती है और Yeouido के पास नदी के नीचे से जाती है। पश्चिमी सिरे पर Mokdong-Hwagok और पूर्वी सिरे पर Hanam के नाम आते हैं।'],
      ['从金浦机场到河南，是东西向穿过首尔最长的一条。汝矣岛、光化门和往十里都在这一条线上。',
       '它两次跨过汉江，其中汝矣岛那一段是从江底下钻过去的。西边是木洞、禾谷，东边则挂着河南的地名。'],
      ['從金浦機場到河南，是東西向穿過首爾最長的一條。汝矣島、光化門和往十里都在這一條線上。',
       '它兩次跨過漢江，其中汝矣島那一段是從江底下鑽過去的。西邊是木洞、禾谷，東邊則掛著河南的地名。'],
    ),
  },
  {
    slug: 'seoul-line-6', city: 'seoul', num: '6', color: '#cd7c2f',
    shape: ['SE', 'SE', 'E', 'E', 'E', 'E', 'E', 'NE', 'NE', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE', 'E', 'E', 'E', 'E', 'NE', 'NE', 'E', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE', 'E', 'E', 'E', 'E', 'E', 'E', 'E'],
    stations: [
      s('응암', 'Eungam', 'terminus'), s('역촌', 'Yeokchon'), s('불광', 'Bulgwang', 'transfer'),
      s('독바위', 'Dokbawi'), s('연신내', 'Yeonsinnae', 'transfer'), s('구산', 'Gusan'),
      s('새절', 'Saejeol'), s('증산', 'Jeungsan'), s('디지털미디어시티', 'Digital Media City', 'transfer'),
      s('월드컵경기장', 'World Cup Stadium'), s('마포구청', 'Mapo-gu Office'), s('망원', 'Mangwon'),
      s('합정', 'Hapjeong', 'transfer'), s('상수', 'Sangsu'), s('광흥창', 'Gwangheungchang'),
      s('대흥', 'Daeheung'), s('공덕', 'Gongdeok', 'transfer'), s('효창공원앞', 'Hyochang Park'),
      s('삼각지', 'Samgakji', 'transfer'), s('녹사평', 'Noksapyeong'), s('이태원', 'Itaewon'),
      s('한강진', 'Hangangjin'), s('버티고개', 'Beotigogae'), s('약수', 'Yaksu', 'transfer'),
      s('청구', 'Cheonggu', 'transfer'), s('신당', 'Sindang', 'transfer'), s('동묘앞', 'Dongmyo'),
      s('창신', 'Changsin'), s('보문', 'Bomun'), s('안암', 'Anam'), s('고려대', 'Korea Univ.'),
      s('월곡', 'Wolgok'), s('상월곡', 'Sangwolgok'), s('돌곶이', 'Dolgoji'), s('석계', 'Seokgye', 'transfer'),
      s('태릉입구', 'Taereung', 'transfer'), s('화랑대', 'Hwarangdae'), s('봉화산', 'Bonghwasan'),
      s('신내', 'Sinnae', 'terminus'),
    ],
    text: T(
      ['은평 응암에서 중랑 신내까지 서울 북쪽을 크게 휘돌아 갑니다. 이태원과 상수·합정처럼 걷기 좋은 동네가 이 노선에 몰려 있습니다.',
       '응암 쪽은 순환 지선이라 상행과 하행 경로가 다릅니다. 이태원·한강진 구간은 언덕 이름(버티고개)이 그대로 역명입니다.'],
      ['A long arc across northern Seoul from Eungam to Sinnae. The walkable neighbourhoods — Itaewon, Sangsu, Hapjeong — cluster on this line.',
       'The Eungam end runs as a one-way loop, so up and down trains differ. Around Itaewon the hills give their names to the stations.'],
      ['Un gran arco por el norte de Seúl, de Eungam a Sinnae. Los barrios que se recorren a pie — Itaewon, Sangsu, Hapjeong — se agrupan en esta línea.',
       'El extremo de Eungam es un bucle de un solo sentido, así que la ida y la vuelta no coinciden. Cerca de Itaewon las colinas dan nombre a las estaciones.'],
      ['Um arco longo pelo norte de Seul, de Eungam a Sinnae. Os bairros que se andam a pé — Itaewon, Sangsu, Hapjeong — se concentram nesta linha.',
       'A ponta de Eungam funciona como um laço de sentido único, então ida e volta diferem. Perto de Itaewon as colinas dão nome às estações.'],
      ['恩平の鷹岩から中浪の新内まで、ソウル北部を大きく回り込みます。梨泰院・上水・合井といった歩いて楽しい街がこの線に集まっています。',
       '鷹岩側は片方向の環状支線で、上りと下りの経路が違います。梨泰院あたりは坂の名がそのまま駅名になっています。'],
      ['Ein weiter Bogen durch den Norden Seouls, von Eungam nach Sinnae. Die Viertel, die man zu Fuß erkundet — Itaewon, Sangsu, Hapjeong — liegen alle an dieser Linie.',
       'Das Ende bei Eungam ist eine Einbahn-Schleife, Hin- und Rückweg unterscheiden sich also. Um Itaewon geben die Hügel den Stationen ihre Namen.'],
      ['Un long arc à travers le nord de Séoul, d’Eungam à Sinnae. Les quartiers qui se visitent à pied — Itaewon, Sangsu, Hapjeong — se concentrent sur cette ligne.',
       'Le bout d’Eungam forme une boucle à sens unique : l’aller et le retour diffèrent. Vers Itaewon, les collines donnent leur nom aux stations.'],
      ['Eunpyeong के Eungam से Jungnang के Sinnae तक, उत्तरी सिओल का बड़ा चक्करदार रास्ता। पैदल घूमने लायक इलाके — Itaewon, Sangsu, Hapjeong — इसी लाइन पर हैं।',
       'Eungam वाला सिरा एकतरफ़ा लूप है, इसलिए आने और जाने का रास्ता अलग है। Itaewon के आसपास पहाड़ी ढलानों के नाम ही स्टेशन के नाम बने हैं।'],
      ['从恩平鹰岩到中浪新内，沿首尔北侧兜一个大弯。梨泰院、上水、合井这些适合走路逛的街区，都聚在这条线上。',
       '鹰岩那一头是环形支线，所以上行和下行走的不是同一条路。梨泰院到汉江镇那一段，山坡的名字（缓坡岭）就直接成了站名。'],
      ['從恩平鷹岩到中浪新內，沿首爾北側兜一個大彎。梨泰院、上水、合井這些適合走路逛的街區，都聚在這條線上。',
       '鷹岩那一頭是環形支線，所以上行和下行走的不是同一條路。梨泰院到漢江鎮那一段，山坡的名字（緩坡嶺）就直接成了站名。'],
    ),
  },
  {
    slug: 'seoul-line-7', city: 'seoul', num: '7', color: '#747f00',
    shape: ['SE', 'SE', 'E', 'E', 'SE', 'SE', 'SE', 'S', 'S', 'S', 'SE', 'SE', 'SE', 'S', 'S', 'SW', 'SW', 'SW', 'SW', 'W', 'W', 'W', 'SW', 'SW', 'SW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'NW', 'NW', 'W', 'W', 'W', 'W', 'SW', 'SW', 'SW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'],
    stations: [
      s('장암', 'Jangam', 'terminus'), s('도봉산', 'Dobongsan', 'transfer'), s('수락산', 'Suraksan'),
      s('마들', 'Madeul'), s('노원', 'Nowon', 'transfer'), s('중계', 'Junggye'), s('하계', 'Hagye'),
      s('공릉', 'Gongneung'), s('태릉입구', 'Taereung', 'transfer'), s('먹골', 'Meokgol'),
      s('중화', 'Junghwa'), s('상봉', 'Sangbong', 'transfer'), s('면목', 'Myeonmok'),
      s('사가정', 'Sagajeong'), s('용마산', 'Yongmasan'), s('중곡', 'Junggok'), s('군자', 'Gunja', 'transfer'),
      s('어린이대공원', 'Children’s Grand Park'), s('건대입구', 'Konkuk Univ.', 'transfer'),
      s('뚝섬유원지', 'Ttukseom Resort'), s('청담', 'Cheongdam'), s('강남구청', 'Gangnam-gu Office', 'transfer'),
      s('학동', 'Hak-dong'), s('논현', 'Nonhyeon'), s('반포', 'Banpo'), s('고속터미널', 'Express Bus Terminal', 'transfer'),
      s('내방', 'Naebang'), s('이수', 'Isu', 'transfer'), s('남성', 'Namseong'), s('숭실대입구', 'Soongsil Univ.'),
      s('상도', 'Sangdo'), s('장승배기', 'Jangseungbaegi'), s('신대방삼거리', 'Sindaebangsamgeori'),
      s('보라매', 'Boramae'), s('신풍', 'Sinpung'), s('대림', 'Daerim', 'transfer'),
      s('남구로', 'Namguro'), s('가산디지털단지', 'Gasan Digital Complex', 'transfer'),
      s('철산', 'Cheolsan'), s('광명사거리', 'Gwangmyeongsageori'), s('천왕', 'Cheonwang'),
      s('온수', 'Onsu', 'transfer'), s('까치울', 'Kkachiul'), s('부천종합운동장', 'Bucheon Stadium'),
      s('춘의', 'Chunui'), s('신중동', 'Sinjung-dong'), s('부천시청', 'Bucheon City Hall'),
      s('상동', 'Sang-dong'), s('삼산체육관', 'Samsan Gymnasium'), s('굴포천', 'Gulpocheon'),
      s('부평구청', 'Bupyeong-gu Office', 'terminus'),
    ],
    text: T(
      ['의정부 장암에서 인천 부평구청까지 서울을 대각선으로 가로지릅니다. 강남구청과 고속터미널을 지나 광명·부천으로 이어집니다.',
       '노원 근처는 계(溪)로 끝나는 역이 잇달아 나오고, 서남쪽은 부천·인천 이름이 붙습니다.'],
      ['A diagonal sweep from Jangam in Uijeongbu to Bupyeong-gu Office in Incheon, taking in Gangnam-gu Office and the Express Bus Terminal on the way.',
       'Near Nowon several stations end in “-gye”; the south-western end carries Bucheon and Incheon names.'],
      ['Una diagonal desde Jangam, en Uijeongbu, hasta Bupyeong-gu Office, en Incheon, pasando por Gangnam-gu Office y la Terminal de Autobuses Exprés.',
       'Cerca de Nowon varias estaciones acaban en «-gye»; el extremo suroeste lleva nombres de Bucheon e Incheon.'],
      ['Uma diagonal de Jangam, em Uijeongbu, até Bupyeong-gu Office, em Incheon, passando por Gangnam-gu Office e o Terminal Rodoviário Expresso.',
       'Perto de Nowon várias estações terminam em “-gye”; a ponta sudoeste traz nomes de Bucheon e Incheon.'],
      ['議政府の長岩から仁川の富平区庁まで、ソウルを斜めに横切ります。江南区庁と高速ターミナルを経て光明・富川へ延びます。',
       '蘆原の近くでは「渓」で終わる駅が続き、南西側は富川・仁川の地名が付きます。'],
      ['Eine Diagonale von Jangam in Uijeongbu bis Bupyeong-gu Office in Incheon, über Gangnam-gu Office und den Express-Busbahnhof.',
       'Bei Nowon enden mehrere Stationen auf „-gye“; das südwestliche Ende trägt Namen aus Bucheon und Incheon.'],
      ['Une diagonale de Jangam, à Uijeongbu, jusqu’à Bupyeong-gu Office, à Incheon, en passant par Gangnam-gu Office et le terminal de bus express.',
       'Près de Nowon, plusieurs stations finissent en « -gye » ; l’extrémité sud-ouest porte des noms de Bucheon et d’Incheon.'],
      ['Uijeongbu के Jangam से Incheon के Bupyeong-gu Office तक, सिओल को तिरछे काटती है। रास्ते में Gangnam-gu Office और एक्सप्रेस बस टर्मिनल पड़ते हैं।',
       'Nowon के पास कई स्टेशन “-gye” पर ख़त्म होते हैं; दक्षिण-पश्चिमी सिरे पर Bucheon और Incheon के नाम आते हैं।'],
      ['从议政府长岩到仁川富平区厅，斜着穿过整个首尔。经过江南区厅和高速巴士客运站，再往光明、富川去。',
       '芦原一带接连出现以「溪」字结尾的站名，西南边则换成富川、仁川的地名。'],
      ['從議政府長岩到仁川富平區廳，斜著穿過整個首爾。經過江南區廳和高速巴士客運站，再往光明、富川去。',
       '蘆原一帶接連出現以「溪」字結尾的站名，西南邊則換成富川、仁川的地名。'],
    ),
  },
  {
    slug: 'seoul-line-8', city: 'seoul', num: '8', color: '#e6186c',
    shape: ['S', 'S', 'S', 'SE', 'SE', 'S', 'S', 'SW', 'SW', 'S', 'S', 'S', 'S', 'S', 'S', 'S'],
    stations: [
      s('별내', 'Byeollae', 'terminus'), s('다산', 'Dasan'), s('동구릉', 'Donggureung'),
      s('구리', 'Guri', 'transfer'), s('장자호수공원', 'Jangja Lake Park'), s('암사역사공원', 'Amsa History Park'),
      s('암사', 'Amsa'), s('천호', 'Cheonho', 'transfer'), s('강동구청', 'Gangdong-gu Office'),
      s('몽촌토성', 'Mongchontoseong'), s('잠실', 'Jamsil', 'transfer'), s('석촌', 'Seokchon'),
      s('송파', 'Songpa'), s('가락시장', 'Garak Market', 'transfer'), s('문정', 'Munjeong'),
      s('장지', 'Jangji'), s('복정', 'Bokjeong', 'transfer'), s('남위례', 'Namwirye'),
      s('산성', 'Sanseong'), s('남한산성입구', 'Namhansanseong'), s('단대오거리', 'Dandaeogeori'),
      s('신흥', 'Sinheung'), s('수진', 'Sujin'), s('모란', 'Moran', 'terminus'),
    ],
    text: T(
      ['서울 지하철에서 가장 짧은 노선이었지만 별내 연장으로 남북이 길어졌습니다. 잠실에서 성남 모란까지 이어집니다.',
       '성남 구간은 역 이름에 오거리·삼거리처럼 교차로 이름이 남아 있습니다.'],
      ['Once the shortest line on the Seoul network, extended northward to Byeollae. It links Jamsil down to Moran in Seongnam.',
       'In the Seongnam stretch several station names still carry old junction names like “ogeori” — a five-way crossing.'],
      ['Fue la línea más corta de la red de Seúl y la extensión a Byeollae la alargó de norte a sur. Une Jamsil con Moran, en Seongnam.',
       'En el tramo de Seongnam varios nombres conservan antiguos cruces, como «ogeori» — encrucijada de cinco calles.'],
      ['Já foi a linha mais curta da rede de Seul; a extensão até Byeollae a alongou de norte a sul. Liga Jamsil a Moran, em Seongnam.',
       'No trecho de Seongnam vários nomes guardam antigos cruzamentos, como “ogeori” — encruzilhada de cinco vias.'],
      ['ソウルの地下鉄で最も短い路線でしたが、別内への延伸で南北に長くなりました。蚕室から城南の牡丹までを結びます。',
       '城南区間の駅名には五叉路・三叉路といった昔の交差点の名が残っています。'],
      ['Einst die kürzeste Linie des Seouler Netzes, durch die Verlängerung nach Byeollae in Nord-Süd-Richtung gewachsen. Sie verbindet Jamsil mit Moran in Seongnam.',
       'Im Abschnitt Seongnam bewahren mehrere Namen alte Kreuzungen, etwa „ogeori“ — eine Kreuzung mit fünf Armen.'],
      ['Longtemps la ligne la plus courte du réseau de Séoul, allongée vers le nord jusqu’à Byeollae. Elle relie Jamsil à Moran, à Seongnam.',
       'Dans le tronçon de Seongnam, plusieurs noms gardent d’anciens carrefours, comme « ogeori » — un croisement à cinq branches.'],
      ['एक समय सिओल की सबसे छोटी लाइन थी, Byeollae तक बढ़ने से उत्तर-दक्षिण में लंबी हो गई। यह Jamsil को Seongnam के Moran से जोड़ती है।',
       'Seongnam वाले हिस्से में कई स्टेशन नामों में पुराने चौराहे बचे हैं, जैसे “ogeori” — पाँच रास्तों का चौराहा।'],
      ['本来是首尔地铁里最短的一条，延伸到别内之后南北向拉长了不少。从蚕室一直通到城南牡丹。',
       '城南那一段的站名里，还留着五岔路、三岔路这样的路口名。'],
      ['本來是首爾地鐵裡最短的一條，延伸到別內之後南北向拉長了不少。從蠶室一直通到城南牡丹。',
       '城南那一段的站名裡，還留著五岔路、三岔路這樣的路口名。'],
    ),
  },
  {
    slug: 'seoul-line-9', city: 'seoul', num: '9', color: '#bdb092',
    shape: ['E', 'E', 'E', 'E', 'E', 'SE', 'SE', 'E', 'E', 'E', 'E', 'SE', 'SE', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'NE', 'NE'],
    stations: [
      s('개화', 'Gaehwa', 'terminus'), s('김포공항', 'Gimpo Int’l Airport', 'transfer'), s('공항시장', 'Airport Market'),
      s('신방화', 'Sinbanghwa'), s('마곡나루', 'Magongnaru', 'transfer'), s('양천향교', 'Yangcheon Hyanggyo'),
      s('가양', 'Gayang'), s('증미', 'Jeungmi'), s('등촌', 'Deungchon'), s('염창', 'Yeomchang'),
      s('신목동', 'Sinmokdong'), s('선유도', 'Seonyudo'), s('당산', 'Dangsan', 'transfer'),
      s('국회의사당', 'Nat’l Assembly'), s('여의도', 'Yeouido', 'transfer'), s('샛강', 'Saetgang'),
      s('노량진', 'Noryangjin', 'transfer'), s('노들', 'Nodeul'), s('흑석', 'Heukseok'),
      s('구반포', 'Gubanpo'), s('신반포', 'Sinbanpo'), s('사평', 'Sapyeong'),
      s('신논현', 'Sinnonhyeon', 'transfer'), s('언주', 'Eonju'), s('선정릉', 'Seonjeongneung', 'transfer'),
      s('삼성중앙', 'Samseong Jungang'), s('봉은사', 'Bongeunsa'), s('종합운동장', 'Sports Complex', 'transfer'),
      s('삼전', 'Samjeon'), s('석촌고분', 'Seokchon Ancient Tombs'), s('석촌', 'Seokchon', 'transfer'),
      s('송파나루', 'Songpanaru'), s('한성백제', 'Hanseong Baekje'), s('올림픽공원', 'Olympic Park', 'transfer'),
      s('둔촌오륜', 'Dunchon Oryun'), s('중앙보훈병원', 'VHS Medical Center', 'terminus'),
    ],
    text: T(
      ['한강 남쪽을 동서로 달리며 급행 열차를 운행하는 노선입니다. 김포공항에서 강남을 지나 강동까지 이어집니다.',
       '급행이 서는 역이 정해져 있어 노선도에 두 종류로 표시됩니다. 강남 구간의 언주·사평처럼 짧은 이름이 많습니다.'],
      ['Running east–west south of the Han, this is the line with express services. It links Gimpo Airport through Gangnam to Gangdong.',
       'Express trains call at only some stations, which is why the map shows two service types. Several Gangnam-area names are short — Eonju, Sapyeong.'],
      ['Va de este a oeste al sur del río Han y es la línea con servicios exprés. Une el aeropuerto de Gimpo con Gangdong pasando por Gangnam.',
       'Los trenes exprés solo paran en algunas estaciones, por eso el plano marca dos tipos de servicio. En Gangnam abundan los nombres cortos: Eonju, Sapyeong.'],
      ['Corre de leste a oeste ao sul do rio Han e é a linha com serviços expressos. Liga o aeroporto de Gimpo a Gangdong passando por Gangnam.',
       'Os trens expressos param só em algumas estações, por isso o mapa marca dois tipos de serviço. Em Gangnam há vários nomes curtos: Eonju, Sapyeong.'],
      ['漢江の南を東西に走り、急行列車を運行する路線です。金浦空港から江南を経て江東まで結びます。',
       '急行が停まる駅が決まっているため、路線図には二種類の運行が示されます。江南区間は彦州・沙坪のように短い駅名が多いです。'],
      ['Sie verläuft südlich des Han von Ost nach West und ist die Linie mit Express-Zügen. Sie verbindet den Flughafen Gimpo über Gangnam mit Gangdong.',
       'Express-Züge halten nur an einigen Stationen, darum zeigt der Plan zwei Betriebsarten. In Gangnam sind viele Namen kurz — Eonju, Sapyeong.'],
      ['Elle file d’est en ouest au sud du Han et c’est la ligne à trains express. Elle relie l’aéroport de Gimpo à Gangdong via Gangnam.',
       'Les express ne desservent qu’une partie des stations, d’où deux types de service sur le plan. Autour de Gangnam, beaucoup de noms sont courts : Eonju, Sapyeong.'],
      ['Han नदी के दक्षिण में पूर्व-पश्चिम चलने वाली और एक्सप्रेस ट्रेन वाली लाइन। Gimpo एयरपोर्ट से Gangnam होकर Gangdong तक जाती है।',
       'एक्सप्रेस ट्रेनें कुछ ही स्टेशनों पर रुकती हैं, इसलिए नक्शे पर दो तरह की सेवा दिखती है। Gangnam इलाके में Eonju, Sapyeong जैसे छोटे नाम बहुत हैं।'],
      ['沿汉江以南东西向奔驰，是设有快车的线路。从金浦机场经江南一直通到江东。',
       '快车只停固定的几站，所以路线图上会标成两种。江南那一段有不少像彦州、沙坪这样的短名字。'],
      ['沿漢江以南東西向奔馳，是設有快車的路線。從金浦機場經江南一直通到江東。',
       '快車只停固定的幾站，所以路線圖上會標成兩種。江南那一段有不少像彥州、沙坪這樣的短名字。'],
    ),
  },
];
