/**
 * 지하철 노선 - 서울 (9)
 *
 * 역 이름은 현재 안내 표기를 따른다. 병기역명(잠실새내처럼 개명된 것)은 개명 뒤
 * 이름을 정답으로 두고 옛 이름은 로마자 칸이 아니라 힌트 문구에서 다룬다.
 */
import type { MetroLine } from './types.ts';

const s = (name: string, roman: string, mark?: 'terminus' | 'transfer') => ({ name, roman, mark });

export const SEOUL_LINES: MetroLine[] = [
  {
    slug: 'seoul-line-1', city: 'seoul', icon: '🇰🇷', color: '#0052a4',
    shape: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'SW', 'SW', 'SW', 'S', 'S', 'S', 'SW', 'SW', 'SW', 'W', 'W', 'W', 'SW', 'SW', 'SW', 'SW', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S'],
    stations: [
      s('소요산', 'Soyosan', 'terminus'), s('동두천', 'Dongducheon'), s('보산', 'Bosan'),
      s('동두천중앙', 'Dongducheon Jungang'), s('지행', 'Jihaeng'), s('덕정', 'Deokjeong'),
      s('덕계', 'Deokgye'), s('양주', 'Yangju'), s('녹양', 'Nogyang'), s('가능', 'Ganeung'),
      s('의정부', 'Uijeongbu', 'transfer'), s('회룡', 'Hoeryong', 'transfer'), s('망월사', 'Mangwolsa'),
      s('도봉산', 'Dobongsan', 'transfer'), s('도봉', 'Dobong'), s('방학', 'Banghak'),
      s('창동', 'Changdong', 'transfer'), s('녹천', 'Nokcheon'), s('월계', 'Wolgye'),
      s('광운대', 'Kwangwoon Univ.'), s('석계', 'Seokgye', 'transfer'), s('신이문', 'Sinimun'),
      s('외대앞', 'Hankuk Univ. of Foreign Studies'), s('회기', 'Hoegi', 'transfer'),
      s('청량리', 'Cheongnyangni', 'transfer'), s('제기동', 'Jegi-dong'), s('신설동', 'Sinseol-dong', 'transfer'),
      s('동묘앞', 'Dongmyo', 'transfer'), s('동대문', 'Dongdaemun', 'transfer'), s('종로5가', 'Jongno 5-ga'),
      s('종로3가', 'Jongno 3-ga', 'transfer'), s('종각', 'Jonggak'), s('시청', 'City Hall', 'transfer'),
      s('서울역', 'Seoul Station', 'transfer'), s('남영', 'Namyeong'), s('용산', 'Yongsan', 'transfer'),
      s('노량진', 'Noryangjin', 'transfer'), s('대방', 'Daebang'), s('신길', 'Singil', 'transfer'),
      s('영등포', 'Yeongdeungpo'), s('신도림', 'Sindorim', 'transfer'), s('구로', 'Guro', 'transfer'),
    ],
    ko: { city: '서울', line: '1호선', country: '한국',
      intro: '한국에서 가장 먼저 개통한 지하철이고 지금은 소요산에서 구로까지 이어집니다. 구로 남쪽에서 경인선과 경부선으로 갈라집니다.',
      hint: '종로 구간은 3가·5가처럼 숫자가 붙어 순서를 기억하기 쉽습니다. 북쪽 경기 구간은 동두천·양주 이름이 이어집니다.' },
    en: { city: 'Seoul', line: 'Line 1', country: 'South Korea',
      intro: 'Korea’s first subway line, now running from Soyosan down to Guro, where it splits towards Incheon and Suwon.',
      hint: 'The Jongno stretch is numbered — 3-ga, 5-ga — which makes the order easy. North of Seoul the names come from Dongducheon and Yangju.' },
  },
  {
    slug: 'seoul-line-2', city: 'seoul', icon: '🇰🇷', color: '#00a84d', loop: true,
    shape: ['E', 'E', 'E', 'SE', 'SE', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE', 'S', 'S', 'SW', 'SW', 'SW', 'W', 'W', 'W', 'W', 'W', 'NW', 'NW', 'W', 'W', 'W', 'NW', 'NW', 'N', 'N', 'NE', 'NE', 'NE', 'E', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE'],
    stations: [
      s('시청', 'City Hall', 'transfer'), s('을지로입구', 'Euljiro 1-ga'), s('을지로3가', 'Euljiro 3-ga', 'transfer'),
      s('을지로4가', 'Euljiro 4-ga'), s('동대문역사문화공원', 'Dongdaemun History & Culture Park', 'transfer'),
      s('신당', 'Sindang'), s('상왕십리', 'Sangwangsimni'), s('왕십리', 'Wangsimni', 'transfer'),
      s('한양대', 'Hanyang Univ.'), s('뚝섬', 'Ttukseom'), s('성수', 'Seongsu'),
      s('건대입구', 'Konkuk Univ.', 'transfer'), s('구의', 'Guui'), s('강변', 'Gangbyeon'),
      s('잠실나루', 'Jamsillaru'), s('잠실', 'Jamsil', 'transfer'), s('잠실새내', 'Jamsilsaenae'),
      s('종합운동장', 'Sports Complex', 'transfer'), s('삼성', 'Samseong'), s('선릉', 'Seolleung', 'transfer'),
      s('역삼', 'Yeoksam'), s('강남', 'Gangnam', 'transfer'), s('교대', 'Seoul Nat’l Univ. of Education', 'transfer'),
      s('서초', 'Seocho'), s('방배', 'Bangbae'), s('사당', 'Sadang', 'transfer'),
      s('낙성대', 'Nakseongdae'), s('서울대입구', 'Seoul Nat’l Univ.'), s('봉천', 'Bongcheon'),
      s('신림', 'Sillim'), s('신대방', 'Sindaebang'), s('구로디지털단지', 'Guro Digital Complex'),
      s('대림', 'Daerim', 'transfer'), s('신도림', 'Sindorim', 'transfer'), s('문래', 'Mullae'),
      s('영등포구청', 'Yeongdeungpo-gu Office', 'transfer'), s('당산', 'Dangsan', 'transfer'),
      s('합정', 'Hapjeong', 'transfer'), s('홍대입구', 'Hongik Univ.', 'transfer'), s('신촌', 'Sinchon'),
      s('이대', 'Ewha Womans Univ.'), s('아현', 'Ahyeon'), s('충정로', 'Chungjeongno', 'transfer'),
    ],
    ko: { city: '서울', line: '2호선', country: '한국',
      intro: '서울 도심을 한 바퀴 도는 순환선으로 세계에서 가장 긴 순환 지하철 가운데 하나입니다. 시청에서 출발해 강남을 지나 다시 시청으로 돌아옵니다.',
      hint: '순환선이라 시작과 끝이 같습니다. 강남·잠실·홍대입구 같은 큰 역을 먼저 떠올리고 그 사이를 채우면 수월합니다.' },
    en: { city: 'Seoul', line: 'Line 2', country: 'South Korea',
      intro: 'A loop around central Seoul and one of the longest circular metro lines in the world. It leaves City Hall, runs through Gangnam and comes back to City Hall.',
      hint: 'Being a loop, it starts and ends at the same place. Pin down the big interchanges — Gangnam, Jamsil, Hongik Univ. — then fill the gaps.' },
  },
  {
    slug: 'seoul-line-3', city: 'seoul', icon: '🇰🇷', color: '#ef7c1c',
    shape: ['SE', 'SE', 'SE', 'S', 'S', 'SE', 'SE', 'E', 'E', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE', 'SE', 'S', 'SE', 'SE', 'E', 'E', 'SE', 'SE', 'SE', 'E', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE'],
    stations: [
      s('대화', 'Daehwa', 'terminus'), s('주엽', 'Juyeop'), s('정발산', 'Jeongbalsan'), s('마두', 'Madu'),
      s('백석', 'Baekseok'), s('대곡', 'Daegok', 'transfer'), s('화정', 'Hwajeong'), s('원당', 'Wondang'),
      s('원흥', 'Wonheung'), s('삼송', 'Samsong'), s('지축', 'Jichuk'), s('구파발', 'Gupabal'),
      s('연신내', 'Yeonsinnae', 'transfer'), s('불광', 'Bulgwang', 'transfer'), s('녹번', 'Nokbeon'),
      s('홍제', 'Hongje'), s('무악재', 'Muakjae'), s('독립문', 'Dongnimmun'), s('경복궁', 'Gyeongbokgung'),
      s('안국', 'Anguk'), s('종로3가', 'Jongno 3-ga', 'transfer'), s('을지로3가', 'Euljiro 3-ga', 'transfer'),
      s('충무로', 'Chungmuro', 'transfer'), s('동대입구', 'Dongguk Univ.'), s('약수', 'Yaksu', 'transfer'),
      s('금호', 'Geumho'), s('옥수', 'Oksu'), s('압구정', 'Apgujeong'), s('신사', 'Sinsa'),
      s('잠원', 'Jamwon'), s('고속터미널', 'Express Bus Terminal', 'transfer'), s('교대', 'Seoul Nat’l Univ. of Education', 'transfer'),
      s('남부터미널', 'Nambu Bus Terminal'), s('양재', 'Yangjae', 'transfer'), s('매봉', 'Maebong'),
      s('도곡', 'Dogok'), s('대치', 'Daechi'), s('학여울', 'Hangnyeoul'), s('대청', 'Daecheong'),
      s('일원', 'Irwon'), s('수서', 'Suseo', 'transfer'), s('가락시장', 'Garak Market', 'transfer'),
      s('경찰병원', 'Police Hospital'), s('오금', 'Ogeum', 'terminus'),
    ],
    ko: { city: '서울', line: '3호선', country: '한국',
      intro: '고양 대화에서 송파 오금까지 서울을 북서에서 남동으로 가로지릅니다. 경복궁·안국처럼 고궁 근처를 지나고 압구정·고속터미널을 거칩니다.',
      hint: '북서쪽 고양 구간은 일산 신도시 이름이 많고, 남동쪽은 강남 학원가 이름이 이어집니다. 두 덩이로 나눠 떠올리면 쉽습니다.' },
    en: { city: 'Seoul', line: 'Line 3', country: 'South Korea',
      intro: 'From Daehwa in Goyang to Ogeum in Songpa, cutting north-west to south-east across Seoul. It passes the palaces at Gyeongbokgung and Anguk before reaching Apgujeong.',
      hint: 'The north-west stretch is Ilsan new-town names; the south-east is the Gangnam study district. Recall it in two blocks.' },
  },
  {
    slug: 'seoul-line-4', city: 'seoul', icon: '🇰🇷', color: '#00a5de',
    shape: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'SW', 'SW', 'SW', 'S', 'S', 'S', 'SW', 'SW', 'SW', 'SW', 'S', 'S', 'SW', 'SW', 'SW', 'S', 'S', 'S', 'SW', 'SW', 'SW', 'W', 'W', 'W', 'SW', 'SW', 'SW', 'W', 'W', 'W', 'SW', 'SW', 'W', 'W', 'W', 'W', 'W', 'SW', 'SW', 'SW'],
    stations: [
      s('당고개', 'Danggogae', 'terminus'), s('상계', 'Sanggye'), s('노원', 'Nowon', 'transfer'),
      s('창동', 'Changdong', 'transfer'), s('쌍문', 'Ssangmun'), s('수유', 'Suyu'), s('미아', 'Mia'),
      s('미아사거리', 'Miasageori'), s('길음', 'Gireum'), s('성신여대입구', 'Sungshin Women’s Univ.'),
      s('한성대입구', 'Hansung Univ.'), s('혜화', 'Hyehwa'), s('동대문', 'Dongdaemun', 'transfer'),
      s('동대문역사문화공원', 'Dongdaemun History & Culture Park', 'transfer'), s('충무로', 'Chungmuro', 'transfer'),
      s('명동', 'Myeongdong'), s('회현', 'Hoehyeon'), s('서울역', 'Seoul Station', 'transfer'),
      s('숙대입구', 'Sookmyung Women’s Univ.'), s('삼각지', 'Samgakji', 'transfer'), s('신용산', 'Sinyongsan'),
      s('이촌', 'Ichon'), s('동작', 'Dongjak', 'transfer'), s('총신대입구(이수)', 'Isu'),
      s('사당', 'Sadang', 'transfer'), s('남태령', 'Namtaeryeong'), s('선바위', 'Seonbawi'),
      s('경마공원', 'Seoul Racecourse Park'), s('대공원', 'Seoul Grand Park'), s('과천', 'Gwacheon'),
      s('정부과천청사', 'Government Complex Gwacheon'), s('인덕원', 'Indeogwon'), s('평촌', 'Pyeongchon'),
      s('범계', 'Beomgye'), s('금정', 'Geumjeong', 'transfer'), s('산본', 'Sanbon'), s('수리산', 'Surisan'),
      s('대야미', 'Daeyami'), s('반월', 'Banwol'), s('상록수', 'Sangnoksu'), s('한대앞', 'Handaeap', 'transfer'),
      s('중앙', 'Jungang'), s('고잔', 'Gojan'), s('초지', 'Choji', 'transfer'), s('안산', 'Ansan'),
      s('신길온천', 'Singiloncheon'), s('정왕', 'Jeongwang'), s('오이도', 'Oido', 'terminus'),
    ],
    ko: { city: '서울', line: '4호선', country: '한국',
      intro: '노원 당고개에서 시흥 오이도까지 이어지며 서울역과 명동, 동대문을 한 번에 지납니다. 남쪽 구간은 안산선과 이어져 서해까지 내려갑니다.',
      hint: '서울 안에서는 대학 이름이 붙은 역이 잇달아 나옵니다. 성신여대입구·한성대입구·숙대입구를 순서대로 떠올려 보세요.' },
    en: { city: 'Seoul', line: 'Line 4', country: 'South Korea',
      intro: 'From Danggogae in Nowon down to Oido in Siheung, taking in Seoul Station, Myeongdong and Dongdaemun on one ride. The southern half continues onto the Ansan line and reaches the west coast.',
      hint: 'Inside Seoul the line strings together university stations — Sungshin, Hansung and Sookmyung come in order.' },
  },
  {
    slug: 'seoul-line-5', city: 'seoul', icon: '🇰🇷', color: '#996cac',
    shape: ['E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'NE', 'NE', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'SE', 'SE', 'E', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE', 'E', 'E', 'E', 'E', 'E', 'NE', 'NE', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E'],
    stations: [
      s('방화', 'Banghwa', 'terminus'), s('개화산', 'Gaehwasan'), s('김포공항', 'Gimpo Int’l Airport', 'transfer'),
      s('송정', 'Songjeong'), s('마곡', 'Magok'), s('발산', 'Balsan'), s('우장산', 'Ujangsan'),
      s('화곡', 'Hwagok'), s('까치산', 'Kkachisan', 'transfer'), s('신정', 'Sinjeong'), s('목동', 'Mokdong'),
      s('오목교', 'Omokgyo'), s('양평', 'Yangpyeong'), s('영등포구청', 'Yeongdeungpo-gu Office', 'transfer'),
      s('영등포시장', 'Yeongdeungpo Market'), s('신길', 'Singil', 'transfer'), s('여의도', 'Yeouido', 'transfer'),
      s('여의나루', 'Yeouinaru'), s('마포', 'Mapo'), s('공덕', 'Gongdeok', 'transfer'), s('애오개', 'Aeogae'),
      s('충정로', 'Chungjeongno', 'transfer'), s('서대문', 'Seodaemun'), s('광화문', 'Gwanghwamun'),
      s('종로3가', 'Jongno 3-ga', 'transfer'), s('을지로4가', 'Euljiro 4-ga', 'transfer'),
      s('동대문역사문화공원', 'Dongdaemun History & Culture Park', 'transfer'), s('청구', 'Cheonggu', 'transfer'),
      s('신금호', 'Singeumho'), s('행당', 'Haengdang'), s('왕십리', 'Wangsimni', 'transfer'),
      s('마장', 'Majang'), s('답십리', 'Dapsimni'), s('장한평', 'Janghanpyeong'), s('군자', 'Gunja', 'transfer'),
      s('아차산', 'Achasan'), s('광나루', 'Gwangnaru'), s('천호', 'Cheonho', 'transfer'), s('강동', 'Gangdong'),
      s('길동', 'Gildong'), s('굽은다리', 'Gubeundari'), s('명일', 'Myeongil'), s('고덕', 'Godeok'),
      s('상일동', 'Sangil-dong'), s('강일', 'Gangil'), s('미사', 'Misa'), s('하남풍산', 'Hanam Pungsan'),
      s('하남시청', 'Hanam City Hall'), s('하남검단산', 'Hanam Geomdansan', 'terminus'),
    ],
    ko: { city: '서울', line: '5호선', country: '한국',
      intro: '김포공항에서 하남까지 서울을 동서로 가장 길게 관통합니다. 여의도와 광화문, 왕십리를 한 노선에서 지납니다.',
      hint: '한강을 두 번 건너고 여의도 구간에서 강 아래를 지납니다. 서쪽은 목동·화곡, 동쪽은 하남 이름이 붙습니다.' },
    en: { city: 'Seoul', line: 'Line 5', country: 'South Korea',
      intro: 'The longest east–west run across Seoul, from Gimpo Airport out to Hanam. Yeouido, Gwanghwamun and Wangsimni all sit on this one line.',
      hint: 'It crosses the Han twice and tunnels beneath it around Yeouido. The west end carries Mokdong and Hwagok names, the east end Hanam ones.' },
  },
  {
    slug: 'seoul-line-6', city: 'seoul', icon: '🇰🇷', color: '#cd7c2f',
    shape: ['SE', 'SE', 'E', 'E', 'E', 'E', 'E', 'NE', 'NE', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE', 'E', 'E', 'E', 'E', 'NE', 'NE', 'E', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE', 'E', 'E', 'E', 'E', 'E', 'E', 'E'],
    stations: [
      s('응암', 'Eungam', 'terminus'), s('역촌', 'Yeokchon'), s('불광', 'Bulgwang', 'transfer'),
      s('독바위', 'Dokbawi'), s('연신내', 'Yeonsinnae', 'transfer'), s('구산', 'Gusan'),
      s('새절', 'Saejeol'), s('증산', 'Jeungsan'), s('디지털미디어시티', 'Digital Media City', 'transfer'),
      s('월드컵경기장', 'World Cup Stadium'), s('마포구청', 'Mapo-gu Office'), s('망원', 'Mangwon'),
      s('합정', 'Hapjeong', 'transfer'), s('상수', 'Sangsu'), s('광흥창', 'Gwangheungchang'),
      s('대흥', 'Daeheung'), s('공덕', 'Gongdeok', 'transfer'), s('효창공원앞', 'Hyochang Park'),
      s('삼각지', 'Samgakji', 'transfer'), s('녹사평', 'Noksapyeong'), s('이태원', 'Itaewon'),
      s('한강진', 'Hangangjin'), s('버티고개', 'Beotigogae'), s('약수', 'Yaksu', 'transfer'),
      s('청구', 'Cheonggu', 'transfer'), s('신당', 'Sindang', 'transfer'), s('동묘앞', 'Dongmyo'),
      s('창신', 'Changsin'), s('보문', 'Bomun'), s('안암', 'Anam'), s('고려대', 'Korea Univ.'),
      s('월곡', 'Wolgok'), s('상월곡', 'Sangwolgok'), s('돌곶이', 'Dolgoji'), s('석계', 'Seokgye', 'transfer'),
      s('태릉입구', 'Taereung', 'transfer'), s('화랑대', 'Hwarangdae'), s('봉화산', 'Bonghwasan'),
      s('신내', 'Sinnae', 'terminus'),
    ],
    ko: { city: '서울', line: '6호선', country: '한국',
      intro: '은평 응암에서 중랑 신내까지 서울 북쪽을 크게 휘돌아 갑니다. 이태원과 상수·합정처럼 걷기 좋은 동네가 이 노선에 몰려 있습니다.',
      hint: '응암 쪽은 순환 지선이라 상행과 하행 경로가 다릅니다. 이태원·한강진 구간은 언덕 이름(버티고개)이 그대로 역명입니다.' },
    en: { city: 'Seoul', line: 'Line 6', country: 'South Korea',
      intro: 'A long arc across northern Seoul from Eungam to Sinnae. The walkable neighbourhoods — Itaewon, Sangsu, Hapjeong — cluster on this line.',
      hint: 'The Eungam end runs as a one-way loop, so up and down trains differ. Around Itaewon the hills give their names to the stations.' },
  },
  {
    slug: 'seoul-line-7', city: 'seoul', icon: '🇰🇷', color: '#747f00',
    shape: ['SE', 'SE', 'E', 'E', 'SE', 'SE', 'SE', 'S', 'S', 'S', 'SE', 'SE', 'SE', 'S', 'S', 'SW', 'SW', 'SW', 'SW', 'W', 'W', 'W', 'SW', 'SW', 'SW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'NW', 'NW', 'W', 'W', 'W', 'W', 'SW', 'SW', 'SW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'],
    stations: [
      s('장암', 'Jangam', 'terminus'), s('도봉산', 'Dobongsan', 'transfer'), s('수락산', 'Suraksan'),
      s('마들', 'Madeul'), s('노원', 'Nowon', 'transfer'), s('중계', 'Junggye'), s('하계', 'Hagye'),
      s('공릉', 'Gongneung'), s('태릉입구', 'Taereung', 'transfer'), s('먹골', 'Meokgol'),
      s('중화', 'Junghwa'), s('상봉', 'Sangbong', 'transfer'), s('면목', 'Myeonmok'),
      s('사가정', 'Sagajeong'), s('용마산', 'Yongmasan'), s('중곡', 'Junggok'), s('군자', 'Gunja', 'transfer'),
      s('어린이대공원', 'Children’s Grand Park'), s('건대입구', 'Konkuk Univ.', 'transfer'),
      s('뚝섬유원지', 'Ttukseom Resort'), s('청담', 'Cheongdam'), s('강남구청', 'Gangnam-gu Office', 'transfer'),
      s('학동', 'Hak-dong'), s('논현', 'Nonhyeon'), s('반포', 'Banpo'), s('고속터미널', 'Express Bus Terminal', 'transfer'),
      s('내방', 'Naebang'), s('이수', 'Isu', 'transfer'), s('남성', 'Namseong'), s('숭실대입구', 'Soongsil Univ.'),
      s('상도', 'Sangdo'), s('장승배기', 'Jangseungbaegi'), s('신대방삼거리', 'Sindaebangsamgeori'),
      s('보라매', 'Boramae'), s('신풍', 'Sinpung'), s('대림', 'Daerim', 'transfer'),
      s('남구로', 'Namguro'), s('가산디지털단지', 'Gasan Digital Complex', 'transfer'),
      s('철산', 'Cheolsan'), s('광명사거리', 'Gwangmyeongsageori'), s('천왕', 'Cheonwang'),
      s('온수', 'Onsu', 'transfer'), s('까치울', 'Kkachiul'), s('부천종합운동장', 'Bucheon Stadium'),
      s('춘의', 'Chunui'), s('신중동', 'Sinjung-dong'), s('부천시청', 'Bucheon City Hall'),
      s('상동', 'Sang-dong'), s('삼산체육관', 'Samsan Gymnasium'), s('굴포천', 'Gulpocheon'),
      s('부평구청', 'Bupyeong-gu Office', 'terminus'),
    ],
    ko: { city: '서울', line: '7호선', country: '한국',
      intro: '의정부 장암에서 인천 부평구청까지 서울을 대각선으로 가로지릅니다. 강남구청과 고속터미널을 지나 광명·부천으로 이어집니다.',
      hint: '노원 근처는 계(溪)로 끝나는 역이 잇달아 나오고, 서남쪽은 부천·인천 이름이 붙습니다.' },
    en: { city: 'Seoul', line: 'Line 7', country: 'South Korea',
      intro: 'A diagonal sweep from Jangam in Uijeongbu to Bupyeong-gu Office in Incheon, taking in Gangnam-gu Office and the Express Bus Terminal on the way.',
      hint: 'Near Nowon several stations end in “-gye”; the south-western end carries Bucheon and Incheon names.' },
  },
  {
    slug: 'seoul-line-8', city: 'seoul', icon: '🇰🇷', color: '#e6186c',
    shape: ['S', 'S', 'S', 'SE', 'SE', 'S', 'S', 'SW', 'SW', 'S', 'S', 'S', 'S', 'S', 'S', 'S'],
    stations: [
      s('별내', 'Byeollae', 'terminus'), s('다산', 'Dasan'), s('동구릉', 'Donggureung'),
      s('구리', 'Guri', 'transfer'), s('장자호수공원', 'Jangja Lake Park'), s('암사역사공원', 'Amsa History Park'),
      s('암사', 'Amsa'), s('천호', 'Cheonho', 'transfer'), s('강동구청', 'Gangdong-gu Office'),
      s('몽촌토성', 'Mongchontoseong'), s('잠실', 'Jamsil', 'transfer'), s('석촌', 'Seokchon'),
      s('송파', 'Songpa'), s('가락시장', 'Garak Market', 'transfer'), s('문정', 'Munjeong'),
      s('장지', 'Jangji'), s('복정', 'Bokjeong', 'transfer'), s('남위례', 'Namwirye'),
      s('산성', 'Sanseong'), s('남한산성입구', 'Namhansanseong'), s('단대오거리', 'Dandaeogeori'),
      s('신흥', 'Sinheung'), s('수진', 'Sujin'), s('모란', 'Moran', 'terminus'),
    ],
    ko: { city: '서울', line: '8호선', country: '한국',
      intro: '서울 지하철에서 가장 짧은 노선이었지만 별내 연장으로 남북이 길어졌습니다. 잠실에서 성남 모란까지 이어집니다.',
      hint: '성남 구간은 역 이름에 오거리·삼거리처럼 교차로 이름이 남아 있습니다.' },
    en: { city: 'Seoul', line: 'Line 8', country: 'South Korea',
      intro: 'Once the shortest line on the Seoul network, extended northward to Byeollae. It links Jamsil down to Moran in Seongnam.',
      hint: 'In the Seongnam stretch several station names still carry old junction names like “ogeori” — five-way crossing.' },
  },
  {
    slug: 'seoul-line-9', city: 'seoul', icon: '🇰🇷', color: '#bdb092',
    shape: ['E', 'E', 'E', 'E', 'E', 'SE', 'SE', 'E', 'E', 'E', 'E', 'SE', 'SE', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'NE', 'NE'],
    stations: [
      s('개화', 'Gaehwa', 'terminus'), s('김포공항', 'Gimpo Int’l Airport', 'transfer'), s('공항시장', 'Airport Market'),
      s('신방화', 'Sinbanghwa'), s('마곡나루', 'Magongnaru', 'transfer'), s('양천향교', 'Yangcheon Hyanggyo'),
      s('가양', 'Gayang'), s('증미', 'Jeungmi'), s('등촌', 'Deungchon'), s('염창', 'Yeomchang'),
      s('신목동', 'Sinmokdong'), s('선유도', 'Seonyudo'), s('당산', 'Dangsan', 'transfer'),
      s('국회의사당', 'Nat’l Assembly'), s('여의도', 'Yeouido', 'transfer'), s('샛강', 'Saetgang'),
      s('노량진', 'Noryangjin', 'transfer'), s('노들', 'Nodeul'), s('흑석', 'Heukseok'),
      s('구반포', 'Gubanpo'), s('신반포', 'Sinbanpo'), s('사평', 'Sapyeong'),
      s('신논현', 'Sinnonhyeon', 'transfer'), s('언주', 'Eonju'), s('선정릉', 'Seonjeongneung', 'transfer'),
      s('삼성중앙', 'Samseong Jungang'), s('봉은사', 'Bongeunsa'), s('종합운동장', 'Sports Complex', 'transfer'),
      s('삼전', 'Samjeon'), s('석촌고분', 'Seokchon Ancient Tombs'), s('석촌', 'Seokchon', 'transfer'),
      s('송파나루', 'Songpanaru'), s('한성백제', 'Hanseong Baekje'), s('올림픽공원', 'Olympic Park', 'transfer'),
      s('둔촌오륜', 'Dunchon Oryun'), s('중앙보훈병원', 'VHS Medical Center', 'terminus'),
    ],
    ko: { city: '서울', line: '9호선', country: '한국',
      intro: '한강 남쪽을 동서로 달리며 급행 열차를 운행하는 노선입니다. 김포공항에서 강남을 지나 강동까지 이어집니다.',
      hint: '급행이 서는 역이 정해져 있어 노선도에 두 종류로 표시됩니다. 강남 구간의 언주·사평처럼 짧은 이름이 많습니다.' },
    en: { city: 'Seoul', line: 'Line 9', country: 'South Korea',
      intro: 'Running east–west south of the Han, this is the line with express services. It links Gimpo Airport through Gangnam to Gangdong.',
      hint: 'Express trains call at only some stations, which is why the map shows two service types. Several Gangnam-area names are short — Eonju, Sapyeong.' },
  },
];
