/**
 * 지하철 노선 — 이미 있는 도시에 노선을 하나씩 더 넣는다 (10개).
 *
 * world2.ts와 같은 이유로 도시를 늘리지 않았다. cities.ts를 안 건드리면 나라
 * 이름 열 벌을 새로 안 적어도 되고, "관련 노선"이 다른 나라로 튀지 않는다.
 *
 * 역 이름은 전부 위키백과의 노선 문서에서 확인해 옮겼다. 받아 온 목록도 한 번은
 * 의심해야 한다 — 파리 2호선 목록에는 La Chapelle과 Stalingrad 사이에 Magenta가
 * 끼어 있었는데, 그것은 RER E의 역이고 2호선은 25역이다.
 *
 * shape는 E·NE·SE만 쓴다. x가 계속 커지므로 두 역이 같은 격자점에 겹칠 수 없다 —
 * N이나 S를 섞으면 왔다 갔다 하다 한 점에서 만나 노선도에서 역 하나가 사라진다.
 */
import { T, s, sa } from './copy.ts';
import type { MetroLine } from './types.ts';

export const WORLD3_LINES: MetroLine[] = [
  {
    slug: 'tokyo-hibiya', city: 'tokyo', color: '#b5b5ac',
    label: {
      ko: '히비야선', en: 'Hibiya Line', es: 'Línea Hibiya', pt: 'Linha Hibiya', ja: '日比谷線',
      de: 'Hibiya-Linie', fr: 'Ligne Hibiya', hi: 'हिबिया लाइन', zh: '日比谷线', tw: '日比谷線',
    },
    shape: ['E', 'NE', 'NE', 'E', 'E', 'NE', 'E', 'SE', 'E', 'SE', 'E', 'NE', 'E', 'NE',
      'NE', 'E', 'NE', 'E', 'NE', 'NE', 'E'],
    stations: [
      s('中目黒', 'Naka-Meguro', 'terminus'), s('恵比寿', 'Ebisu', 'transfer'),
      s('広尾', 'Hiroo'), s('六本木', 'Roppongi', 'transfer'), s('神谷町', 'Kamiyacho'),
      s('虎ノ門ヒルズ', 'Toranomon Hills'), s('霞ケ関', 'Kasumigaseki', 'transfer'),
      s('日比谷', 'Hibiya', 'transfer'), s('銀座', 'Ginza', 'transfer'),
      s('東銀座', 'Higashi-ginza', 'transfer'), s('築地', 'Tsukiji'),
      s('八丁堀', 'Hatchobori'), s('茅場町', 'Kayabacho', 'transfer'),
      s('人形町', 'Ningyocho', 'transfer'), s('小伝馬町', 'Kodemmacho'),
      s('秋葉原', 'Akihabara', 'transfer'), s('仲御徒町', 'Naka-okachimachi'),
      s('上野', 'Ueno', 'transfer'), s('入谷', 'Iriya'), s('三ノ輪', 'Minowa'),
      s('南千住', 'Minami-senju', 'transfer'), s('北千住', 'Kita-senju', 'terminus'),
    ],
    text: T(
      ['도쿄 남서쪽 나카메구로에서 북동쪽 기타센주까지 도심을 가로지릅니다. 롯폰기·긴자·아키하바라·우에노를 한 줄로 꿰어, 관광객이 가장 많이 타게 되는 노선입니다.',
       '역 이름에 銀座가 들어간 역이 둘입니다. 긴자와 히가시긴자로 한 정거장 차이입니다.'],
      ['Cuts across central Tokyo from Naka-Meguro in the south-west to Kita-Senju in the north-east. It strings together Roppongi, Ginza, Akihabara and Ueno, so visitors end up on it more than any other line.',
       'Two stations carry the name Ginza — Ginza and Higashi-ginza, one stop apart.'],
      ['Cruza el centro de Tokio desde Naka-Meguro, al suroeste, hasta Kita-Senju, al noreste. Enlaza Roppongi, Ginza, Akihabara y Ueno, así que los visitantes acaban usándola más que ninguna otra.',
       'Dos estaciones llevan el nombre Ginza: Ginza y Higashi-ginza, separadas por una parada.'],
      ['Atravessa o centro de Tóquio de Naka-Meguro, a sudoeste, até Kita-Senju, a nordeste. Costura Roppongi, Ginza, Akihabara e Ueno, e por isso os visitantes acabam pegando essa linha mais que qualquer outra.',
       'Duas estações levam o nome Ginza: Ginza e Higashi-ginza, a uma parada de distância.'],
      ['南西の中目黒から北東の北千住まで、東京の都心を斜めに貫きます。六本木・銀座・秋葉原・上野を一本で結ぶため、旅行者がいちばん乗ることになる路線です。',
       '「銀座」が付く駅が二つあります。銀座と東銀座で、隣どうしです。'],
      ['Durchquert das Zentrum Tokios von Naka-Meguro im Südwesten bis Kita-Senju im Nordosten. Sie reiht Roppongi, Ginza, Akihabara und Ueno auf, weshalb Besucher auf keiner Linie öfter landen.',
       'Zwei Stationen tragen den Namen Ginza — Ginza und Higashi-ginza, eine Station auseinander.'],
      ['Traverse le centre de Tokyo de Naka-Meguro, au sud-ouest, à Kita-Senju, au nord-est. Elle enfile Roppongi, Ginza, Akihabara et Ueno : les visiteurs y montent plus que sur toute autre ligne.',
       'Deux stations portent le nom de Ginza : Ginza et Higashi-ginza, à un arrêt l’une de l’autre.'],
      ['दक्षिण-पश्चिम के नाका-मेगुरो से उत्तर-पूर्व के किता-सेंजू तक टोक्यो के केंद्र को तिरछे काटती है। रोप्पोंगी, गिंज़ा, अकिहाबारा और उएनो को एक ही रेखा पर पिरोती है, इसलिए पर्यटक सबसे अधिक इसी में चढ़ते हैं।',
       'दो स्टेशनों के नाम में गिंज़ा आता है — गिंज़ा और हिगाशी-गिंज़ा, बस एक स्टॉप की दूरी पर।'],
      ['从西南的中目黑一直斜穿到东北的北千住，纵贯东京市中心。六本木、银座、秋叶原、上野都串在这一条线上，游客坐得最多。',
       '有两个站名里带「银座」——银座和东银座，只隔一站。'],
      ['從西南的中目黑一直斜穿到東北的北千住，縱貫東京市中心。六本木、銀座、秋葉原、上野都串在這一條線上，遊客坐得最多。',
       '有兩個站名裡帶「銀座」——銀座和東銀座，只隔一站。'],
    ),
  },
  {
    slug: 'hongkong-kwun-tong', city: 'hongkong', color: '#00a040',
    label: {
      ko: '쿤통선', en: 'Kwun Tong line', es: 'Línea Kwun Tong', pt: 'Linha Kwun Tong',
      ja: '観塘線', de: 'Kwun-Tong-Linie', fr: 'Ligne Kwun Tong', hi: 'क्वुन टोंग लाइन',
      zh: '观塘线', tw: '觀塘綫',
    },
    shape: ['SE', 'SE', 'NE', 'NE', 'NE', 'E', 'E', 'SE', 'SE', 'E', 'SE', 'SE', 'E', 'SE', 'E', 'NE'],
    stations: [
      sa('Whampoa', '黃埔', 'terminus'), sa('Ho Man Tin', '何文田', 'transfer'),
      sa('Yau Ma Tei', '油麻地', 'transfer'), sa('Mong Kok', '旺角', 'transfer'),
      sa('Prince Edward', '太子', 'transfer'), sa('Shek Kip Mei', '石硤尾'),
      sa('Kowloon Tong', '九龍塘', 'transfer'), sa('Lok Fu', '樂富'),
      sa('Wong Tai Sin', '黃大仙'), sa('Diamond Hill', '鑽石山', 'transfer'),
      sa('Choi Hung', '彩虹'), sa('Kowloon Bay', '九龍灣'), sa('Ngau Tau Kok', '牛頭角'),
      sa('Kwun Tong', '觀塘'), sa('Lam Tin', '藍田'), sa('Yau Tong', '油塘', 'transfer'),
      sa('Tiu Keng Leng', '調景嶺', 'terminus'),
    ],
    text: T(
      ['구룡반도를 서쪽 웜포아에서 동쪽 티우켕렝까지 훑고 지나는 노선입니다. 몽콕과 프린스에드워드에서 췬완선과 나란히 달려, 두 노선이 같은 승강장을 씁니다.',
       '가운데 네 역은 색·산·언덕 같은 자연에서 이름을 얻었습니다. 초이헝은 무지개라는 뜻입니다.'],
      ['Runs the length of the Kowloon peninsula, from Whampoa in the west to Tiu Keng Leng in the east. Between Mong Kok and Prince Edward it shares platforms with the Tsuen Wan line.',
       'Several stations are named after colours and hills — Choi Hung means rainbow, Wong Tai Sin is a temple.'],
      ['Recorre la península de Kowloon de punta a punta, de Whampoa al oeste hasta Tiu Keng Leng al este. Entre Mong Kok y Prince Edward comparte andén con la línea Tsuen Wan.',
       'Varias estaciones toman su nombre de colores y colinas: Choi Hung significa arcoíris.'],
      ['Percorre a península de Kowloon de ponta a ponta, de Whampoa a oeste até Tiu Keng Leng a leste. Entre Mong Kok e Prince Edward divide plataforma com a linha Tsuen Wan.',
       'Várias estações têm nome de cores e colinas: Choi Hung quer dizer arco-íris.'],
      ['九龍半島を西の黄埔から東の調景嶺まで、端から端まで走る路線です。旺角と太子では荃湾線と同じホームを使います。',
       '色や丘に由来する駅名が多く、彩虹は「虹」という意味です。'],
      ['Fährt die Halbinsel Kowloon von Whampoa im Westen bis Tiu Keng Leng im Osten ab. Zwischen Mong Kok und Prince Edward teilt sie sich den Bahnsteig mit der Tsuen-Wan-Linie.',
       'Etliche Stationen sind nach Farben und Hügeln benannt — Choi Hung heißt Regenbogen.'],
      ['Parcourt la péninsule de Kowloon d’ouest en est, de Whampoa à Tiu Keng Leng. Entre Mong Kok et Prince Edward, elle partage les quais avec la ligne Tsuen Wan.',
       'Plusieurs stations tirent leur nom de couleurs et de collines : Choi Hung veut dire arc-en-ciel.'],
      ['कॉव्लून प्रायद्वीप को पश्चिम के व्हामपोआ से पूर्व के टिउ केंग लेंग तक पूरा नापती है। मोंग कोक और प्रिंस एडवर्ड के बीच यह त्सुएन वान लाइन के साथ एक ही प्लेटफ़ॉर्म साझा करती है।',
       'कई स्टेशनों के नाम रंगों और पहाड़ियों पर हैं — चोई हुंग का अर्थ इंद्रधनुष है।'],
      ['从西边的黄埔一路走到东边的调景岭，把九龙半岛从头贯到尾。在旺角和太子两站与荃湾线共用同一个站台。',
       '不少站名取自颜色和山丘——彩虹就是「虹」的意思。'],
      ['從西邊的黃埔一路走到東邊的調景嶺，把九龍半島從頭貫到尾。在旺角和太子兩站與荃灣綫共用同一個月台。',
       '不少站名取自顏色和山丘——彩虹就是「虹」的意思。'],
    ),
  },
  {
    slug: 'osaka-chuo', city: 'osaka', color: '#019a66',
    label: {
      ko: '주오선', en: 'Chuo Line', es: 'Línea Chūō', pt: 'Linha Chūō', ja: '中央線',
      de: 'Chūō-Linie', fr: 'Ligne Chūō', hi: 'चूओ लाइन', zh: '中央线', tw: '中央線',
    },
    shape: ['E', 'E', 'NE', 'E', 'E', 'E', 'E', 'SE', 'E', 'NE', 'E', 'E', 'E', 'SE'],
    stations: [
      s('夢洲', 'Yumeshima', 'terminus'), s('コスモスクエア', 'Cosmosquare', 'transfer'),
      s('大阪港', 'Osakako'), s('朝潮橋', 'Asashiobashi'), s('弁天町', 'Bentencho', 'transfer'),
      s('九条', 'Kujo', 'transfer'), s('阿波座', 'Awaza', 'transfer'),
      s('本町', 'Hommachi', 'transfer'), s('堺筋本町', 'Sakaisuji-Hommachi', 'transfer'),
      s('谷町四丁目', 'Tanimachi 4-chome', 'transfer'), s('森ノ宮', 'Morinomiya', 'transfer'),
      s('緑橋', 'Midoribashi', 'transfer'), s('深江橋', 'Fukaebashi'),
      s('高井田', 'Takaida', 'transfer'), s('長田', 'Nagata', 'terminus'),
    ],
    text: T(
      ['오사카를 동서로 곧게 가로지르는 노선입니다. 서쪽 끝이 매립지인 유메시마라, 2025년 만국박람회에 맞춰 한 역이 새로 늘었습니다.',
       '이름에 다리 교(橋)가 붙은 역이 셋입니다. 아사시오바시·미도리바시·후카에바시입니다.'],
      ['Runs dead straight east to west across Osaka. Its western end sits on the reclaimed island of Yumeshima, where a station was added for the 2025 World Expo.',
       'Three stations end in -bashi, meaning bridge: Asashiobashi, Midoribashi and Fukaebashi.'],
      ['Atraviesa Osaka en línea recta de este a oeste. Su extremo occidental está en la isla ganada al mar de Yumeshima, donde se añadió una estación para la Expo de 2025.',
       'Tres estaciones acaban en -bashi, que significa puente: Asashiobashi, Midoribashi y Fukaebashi.'],
      ['Corta Osaka em linha reta de leste a oeste. Sua ponta ocidental fica na ilha aterrada de Yumeshima, onde uma estação foi acrescentada para a Expo de 2025.',
       'Três estações terminam em -bashi, que quer dizer ponte: Asashiobashi, Midoribashi e Fukaebashi.'],
      ['大阪を東西にまっすぐ横切る路線です。西の端は埋め立て地の夢洲で、2025年の万博に合わせて一駅が新しく増えました。',
       '「橋」が付く駅が三つあります。朝潮橋・緑橋・深江橋です。'],
      ['Durchquert Osaka schnurgerade von Ost nach West. Ihr westliches Ende liegt auf der aufgeschütteten Insel Yumeshima, wo für die Expo 2025 eine Station dazukam.',
       'Drei Stationen enden auf -bashi, also Brücke: Asashiobashi, Midoribashi und Fukaebashi.'],
      ['Traverse Osaka en ligne droite d’est en ouest. Son extrémité ouest se trouve sur l’île artificielle de Yumeshima, où une station a été ajoutée pour l’Expo 2025.',
       'Trois stations finissent en -bashi, qui veut dire pont : Asashiobashi, Midoribashi et Fukaebashi.'],
      ['ओसाका को पूर्व से पश्चिम तक सीधी रेखा में काटती है। इसका पश्चिमी छोर समुद्र से बनाई गई युमेशिमा द्वीप पर है, जहाँ 2025 के विश्व मेले के लिए एक स्टेशन जोड़ा गया।',
       'तीन स्टेशन -बाशी पर ख़त्म होते हैं, जिसका अर्थ है पुल: आसाशिओबाशी, मिदोरिबाशी और फुकाएबाशी।'],
      ['笔直地把大阪从东到西横穿一遍。西端设在填海造出的梦洲，为 2025 年世博会新增了一站。',
       '有三个站名带「桥」字：朝潮桥、绿桥、深江桥。'],
      ['筆直地把大阪從東到西橫穿一遍。西端設在填海造出的夢洲，為 2025 年世博會新增了一站。',
       '有三個站名帶「橋」字：朝潮橋、綠橋、深江橋。'],
    ),
  },
  {
    slug: 'busan-line-4', city: 'busan', color: '#217dcb', num: '4',
    shape: ['E', 'SE', 'E', 'E', 'NE', 'E', 'NE', 'E', 'NE', 'E', 'NE', 'E', 'NE'],
    stations: [
      s('미남', 'Minam', 'terminus'), s('동래', 'Dongnae', 'transfer'), s('수안', 'Suan'),
      s('낙민', 'Nakmin'), s('충렬사', 'Chungnyeolsa'), s('명장', 'Myeongjang'),
      s('서동', 'Seo-dong'), s('금사', 'Geumsa'), s('반여농산물시장', 'Banyeo Nongsanmul Market'),
      s('석대', 'Seokdae'), s('영산대', 'Youngsan University'), s('윗반송', 'Witbansong'),
      s('고촌', 'Gochon'), s('안평', 'Anpyeong', 'terminus'),
    ],
    text: T(
      ['부산 동래에서 동북쪽 안평까지 올라가는 경전철입니다. 열네 역으로 짧고, 바퀴가 고무라 소리가 조용하며 운전실이 없습니다.',
       '역 이름이 가장 긴 것은 반여농산물시장입니다. 나머지는 대부분 두 글자입니다.'],
      ['A light metro climbing north-east from Dongnae to Anpyeong in Busan. Fourteen stations long, it runs on rubber tyres and has no driver’s cab.',
       'The longest station name by far is Banyeo Nongsanmul Market. Most of the others are two syllables.'],
      ['Un metro ligero que sube hacia el noreste desde Dongnae hasta Anpyeong, en Busan. Tiene catorce estaciones, rueda sobre neumáticos y circula sin conductor.',
       'El nombre más largo con diferencia es Banyeo Nongsanmul Market. Casi todos los demás tienen dos sílabas.'],
      ['Um metrô leve que sobe para nordeste de Dongnae até Anpyeong, em Busan. São catorze estações, rodas de borracha e nenhuma cabine de condutor.',
       'O nome mais comprido de longe é Banyeo Nongsanmul Market. Quase todos os outros têm duas sílabas.'],
      ['釜山の東莱から北東の安平まで上る新交通システムです。十四駅と短く、ゴムタイヤで静かに走り、運転室がありません。',
       '駅名がいちばん長いのは盤如農産物市場です。ほかはほとんど二文字です。'],
      ['Eine Stadtbahn, die in Busan von Dongnae nach Nordosten bis Anpyeong steigt. Vierzehn Stationen lang, auf Gummireifen und ohne Fahrerkabine.',
       'Der mit Abstand längste Name ist Banyeo Nongsanmul Market. Fast alle anderen haben zwei Silben.'],
      ['Un métro léger qui monte vers le nord-est de Dongnae à Anpyeong, à Busan. Quatorze stations, des pneus en caoutchouc et pas de cabine de conduite.',
       'Le nom le plus long est de loin Banyeo Nongsanmul Market. Presque tous les autres font deux syllabes.'],
      ['बुसान में डोंगने से उत्तर-पूर्व की ओर अनप्योंग तक चढ़ती हुई एक हल्की मेट्रो। चौदह स्टेशनों की यह लाइन रबर के पहियों पर चलती है और इसमें चालक कक्ष नहीं है।',
       'सबसे लंबा नाम बिना शक बान्यो नोंगसानमुल मार्केट है। बाकी लगभग सभी दो अक्षरों के हैं।'],
      ['釜山从东莱一路向东北爬升到安平的轻轨。全线仅十四站，采用橡胶轮胎，安静无人驾驶。',
       '站名最长的是盘如农产品市场，其余大多只有两个字。'],
      ['釜山從東萊一路向東北爬升到安平的輕軌。全線僅十四站，採用橡膠輪胎，安靜無人駕駛。',
       '站名最長的是盤如農產品市場，其餘大多只有兩個字。'],
    ),
  },
  {
    slug: 'lyon-b', city: 'lyon', color: '#0072bc',
    label: {
      ko: 'B선', en: 'Line B', es: 'Línea B', pt: 'Linha B', ja: 'B線',
      de: 'Linie B', fr: 'Ligne B', hi: 'लाइन B', zh: 'B线', tw: 'B線',
    },
    shape: ['SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE'],
    stations: [
      s('Charpennes–Charles Hernu', undefined, 'transfer'), s('Brotteaux'),
      s('Gare Part-Dieu–Vivier Merle', undefined, 'transfer'),
      s('Place Guichard–Bourse du Travail'), s('Saxe–Gambetta', undefined, 'transfer'),
      s('Jean Macé', undefined, 'transfer'), s('Place Jean Jaurès'), s('Debourg'),
      s('Stade de Gerland–Le LOU'), s('Gare d’Oullins', undefined, 'transfer'),
      s('Oullins Centre'), s('Saint-Genis-Laval–Hôpital Lyon Sud', undefined, 'terminus'),
    ],
    text: T(
      ['리옹을 북동에서 남서로 잇는 노선입니다. 2023년에 남쪽으로 두 역이 늘어 병원 앞까지 닿았고, 그 구간은 무인 운전입니다.',
       '역 이름에 사람 이름이 붙은 것이 넷입니다. 장 조레스와 장 마세가 그 가운데 둘입니다.'],
      ['Links the north-east of Lyon to the south-west. A 2023 extension added two stations and took the line as far as a hospital, and that stretch runs driverless.',
       'Four stations are named after people. Jean Jaurès and Jean Macé are two of them.'],
      ['Une el noreste de Lyon con el suroeste. Una ampliación de 2023 sumó dos estaciones y llevó la línea hasta un hospital; ese tramo circula sin conductor.',
       'Cuatro estaciones llevan nombre de persona. Jean Jaurès y Jean Macé son dos de ellas.'],
      ['Liga o nordeste de Lyon ao sudoeste. Uma extensão de 2023 acrescentou duas estações e levou a linha até um hospital; esse trecho anda sem condutor.',
       'Quatro estações têm nome de pessoa. Jean Jaurès e Jean Macé são duas delas.'],
      ['リヨンの北東と南西を結ぶ路線です。2023年に南へ二駅延びて病院前まで届き、その区間は無人運転です。',
       '人名が付いた駅が四つあります。ジャン・ジョレスとジャン・マセがそのうちの二つです。'],
      ['Verbindet den Nordosten Lyons mit dem Südwesten. Eine Verlängerung von 2023 brachte zwei Stationen dazu und führte die Linie bis an ein Krankenhaus; dieser Abschnitt fährt fahrerlos.',
       'Vier Stationen tragen Personennamen. Jean Jaurès und Jean Macé sind zwei davon.'],
      ['Relie le nord-est de Lyon au sud-ouest. Un prolongement de 2023 a ajouté deux stations et mené la ligne jusqu’à un hôpital ; ce tronçon roule sans conducteur.',
       'Quatre stations portent des noms de personnes. Jean Jaurès et Jean Macé en font partie.'],
      ['ल्यों के उत्तर-पूर्व को दक्षिण-पश्चिम से जोड़ती है। 2023 के विस्तार में दो स्टेशन जुड़े और लाइन एक अस्पताल तक पहुँच गई; वह हिस्सा बिना चालक के चलता है।',
       'चार स्टेशनों के नाम व्यक्तियों पर हैं। ज़ां जोरेस और ज़ां मासे उनमें से दो हैं।'],
      ['把里昂的东北与西南连起来。2023 年向南延长两站，直抵一家医院，这一段是无人驾驶。',
       '有四个站以人名命名，让·饶勒斯和让·马塞是其中两个。'],
      ['把里昂的東北與西南連起來。2023 年向南延長兩站，直抵一家醫院，這一段是無人駕駛。',
       '有四個站以人名命名，讓·饒勒斯和讓·馬塞是其中兩個。'],
    ),
  },
  {
    slug: 'nyc-g', city: 'newyork', color: '#6cbe45',
    label: {
      ko: 'G 트레인', en: 'G train', es: 'Línea G', pt: 'Linha G', ja: 'G系統',
      de: 'Linie G', fr: 'Ligne G', hi: 'लाइन G', zh: 'G线', tw: 'G線',
    },
    shape: ['SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE',
      'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE'],
    stations: [
      s('Court Square', undefined, 'terminus'), s('21st Street'), s('Greenpoint Avenue'),
      s('Nassau Avenue'), s('Metropolitan Avenue', undefined, 'transfer'), s('Broadway'),
      s('Flushing Avenue'), s('Myrtle–Willoughby Avenues'), s('Bedford–Nostrand Avenues'),
      s('Classon Avenue'), s('Clinton–Washington Avenues'), s('Fulton Street', undefined, 'transfer'),
      s('Hoyt–Schermerhorn Streets', undefined, 'transfer'), s('Bergen Street'),
      s('Carroll Street'), s('Smith–Ninth Streets'), s('Fourth Avenue', undefined, 'transfer'),
      s('Seventh Avenue'), s('15th Street–Prospect Park'), s('Fort Hamilton Parkway'),
      s('Church Avenue', undefined, 'terminus'),
    ],
    text: T(
      ['맨해튼에 한 번도 들어가지 않는 유일한 뉴욕 지하철 노선입니다. 퀸스의 코트스퀘어에서 브루클린 남쪽 처치애비뉴까지, 두 자치구만 잇습니다.',
       '역 이름이 애비뉴로 끝나는 것이 열입니다. 스트리트로 끝나는 것보다 훨씬 많습니다.'],
      ['The only New York subway service that never enters Manhattan. It links Queens and Brooklyn alone, from Court Square down to Church Avenue.',
       'Ten stations end in Avenue — far more than end in Street.'],
      ['El único servicio del metro de Nueva York que nunca entra en Manhattan. Enlaza solo Queens y Brooklyn, desde Court Square hasta Church Avenue.',
       'Diez estaciones acaban en Avenue, muchas más que las que acaban en Street.'],
      ['O único serviço do metrô de Nova York que nunca entra em Manhattan. Liga apenas o Queens e o Brooklyn, de Court Square até Church Avenue.',
       'Dez estações terminam em Avenue, bem mais do que as que terminam em Street.'],
      ['マンハッタンに一度も入らない唯一のニューヨーク地下鉄です。クイーンズのコートスクエアからブルックリン南部のチャーチアベニューまで、二つの区だけを結びます。',
       '駅名がAvenueで終わるものが十あります。Streetで終わるものよりずっと多いです。'],
      ['Die einzige New Yorker U-Bahn-Linie, die Manhattan nie berührt. Sie verbindet allein Queens und Brooklyn, von Court Square bis Church Avenue.',
       'Zehn Stationen enden auf Avenue — weit mehr als auf Street.'],
      ['Le seul service du métro de New York qui n’entre jamais dans Manhattan. Il relie uniquement le Queens et Brooklyn, de Court Square à Church Avenue.',
       'Dix stations se terminent par Avenue, bien plus que par Street.'],
      ['न्यूयॉर्क सबवे की एकमात्र सेवा जो कभी मैनहट्टन में नहीं घुसती। यह सिर्फ़ क्वींस और ब्रुकलिन को जोड़ती है, कोर्ट स्क्वायर से चर्च एवेन्यू तक।',
       'दस स्टेशन Avenue पर ख़त्म होते हैं — Street पर ख़त्म होने वालों से कहीं ज़्यादा।'],
      ['纽约地铁里唯一一条从不进入曼哈顿的线路。它只连接皇后区和布鲁克林，从法院广场一直到教堂大道。',
       '有十个站名以 Avenue 结尾，比以 Street 结尾的多得多。'],
      ['紐約地鐵裡唯一一條從不進入曼哈頓的線路。它只連接皇后區和布魯克林，從法院廣場一直到教堂大道。',
       '有十個站名以 Avenue 結尾，比以 Street 結尾的多得多。'],
    ),
  },
  {
    slug: 'paris-2', city: 'paris', color: '#216eb4', num: '2',
    shape: ['E', 'NE', 'E', 'E', 'E', 'NE', 'E', 'NE', 'E', 'E', 'E', 'E', 'NE', 'E',
      'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE'],
    stations: [
      s('Porte Dauphine', undefined, 'terminus'), s('Victor Hugo'),
      s('Charles de Gaulle–Étoile', undefined, 'transfer'), s('Ternes'), s('Courcelles'),
      s('Monceau'), s('Villiers', undefined, 'transfer'), s('Rome'),
      s('Place de Clichy', undefined, 'transfer'), s('Blanche'), s('Pigalle', undefined, 'transfer'),
      s('Anvers'), s('Barbès–Rochechouart', undefined, 'transfer'), s('La Chapelle', undefined, 'transfer'),
      s('Stalingrad', undefined, 'transfer'), s('Jaurès', undefined, 'transfer'),
      s('Colonel Fabien'), s('Belleville', undefined, 'transfer'), s('Couronnes'),
      s('Ménilmontant'), s('Père Lachaise', undefined, 'transfer'), s('Philippe Auguste'),
      s('Alexandre Dumas'), s('Avron'), s('Nation', undefined, 'terminus'),
    ],
    text: T(
      ['파리 북쪽을 반달처럼 감아 도는 노선입니다. 개선문에서 나시옹까지 스물다섯 역이고, 바르베스에서 자레스까지는 고가로 지상을 달립니다.',
       '역 이름에 사람 이름이 붙은 것이 다섯입니다. 빅토르 위고와 알렉상드르 뒤마가 그 가운데 둘입니다.'],
      ['Curves across the north of Paris like a crescent, twenty-five stations from the Arc de Triomphe to Nation. Between Barbès and Jaurès it runs above ground on a viaduct.',
       'Five stations are named after people — Victor Hugo and Alexandre Dumas among them.'],
      ['Dibuja una media luna por el norte de París, veinticinco estaciones desde el Arco del Triunfo hasta Nation. Entre Barbès y Jaurès circula en superficie sobre un viaducto.',
       'Cinco estaciones llevan nombre de persona; Victor Hugo y Alexandre Dumas están entre ellas.'],
      ['Descreve uma meia-lua pelo norte de Paris, vinte e cinco estações do Arco do Triunfo até Nation. Entre Barbès e Jaurès corre em viaduto, à superfície.',
       'Cinco estações têm nome de pessoa; Victor Hugo e Alexandre Dumas estão entre elas.'],
      ['パリの北側を三日月のように回る路線です。凱旋門からナシオンまで二十五駅で、バルベスからジョレスまでは高架を地上で走ります。',
       '人名が付いた駅が五つあります。ヴィクトル・ユゴーとアレクサンドル・デュマがその二つです。'],
      ['Zieht als Sichel über den Norden von Paris, fünfundzwanzig Stationen vom Arc de Triomphe bis Nation. Zwischen Barbès und Jaurès fährt sie oberirdisch auf einem Viadukt.',
       'Fünf Stationen tragen Personennamen — darunter Victor Hugo und Alexandre Dumas.'],
      ['Décrit un croissant sur le nord de Paris, vingt-cinq stations de l’Arc de Triomphe à Nation. Entre Barbès et Jaurès, elle roule en surface sur un viaduc.',
       'Cinq stations portent des noms de personnes, dont Victor Hugo et Alexandre Dumas.'],
      ['पेरिस के उत्तर में अर्धचंद्र की तरह घूमती है — आर्क द ट्रायम्फ से नास्योन तक पच्चीस स्टेशन। बार्बेस से जोरेस के बीच यह वायाडक्ट पर ज़मीन के ऊपर चलती है।',
       'पाँच स्टेशनों के नाम व्यक्तियों पर हैं, जिनमें विक्टर ह्यूगो और अलेक्जांद्र दुमास शामिल हैं।'],
      ['像一弯新月绕过巴黎北部，从凯旋门到民族广场共二十五站。巴尔贝斯到饶勒斯一段架在高架桥上，走的是地面。',
       '有五个站以人名命名，维克多·雨果和大仲马就在其中。'],
      ['像一彎新月繞過巴黎北部，從凱旋門到民族廣場共二十五站。巴爾貝斯到饒勒斯一段架在高架橋上，走的是地面。',
       '有五個站以人名命名，維克多·雨果和大仲馬就在其中。'],
    ),
  },
  {
    slug: 'beijing-13', city: 'beijing', color: '#f3d03e', num: '13',
    shape: ['NE', 'NE', 'NE', 'NE', 'NE', 'E', 'E', 'E', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE'],
    stations: [
      s('西直门', 'Xizhimen', 'terminus'), s('大钟寺', 'Dazhongsi'),
      s('知春路', 'Zhichunlu', 'transfer'), s('五道口', 'Wudaokou'), s('上地', 'Shangdi'),
      s('清河站', 'Qinghe Railway Station', 'transfer'), s('西二旗', 'Xi\'erqi', 'transfer'),
      s('龙泽', 'Longze'), s('回龙观', 'Huilongguan'), s('霍营', 'Huoying', 'transfer'),
      s('立水桥', 'Lishuiqiao', 'transfer'), s('北苑', 'Beiyuan'),
      s('望京西', 'Wangjing West', 'transfer'), s('芍药居', 'Shaoyaoju', 'transfer'),
      s('光熙门', 'Guangximen'), s('柳芳', 'Liufang'), s('东直门', 'Dongzhimen', 'terminus'),
    ],
    text: T(
      ['베이징 북쪽을 크게 감아 도는 U자 노선입니다. 양쪽 끝이 모두 2호선 순환선에 붙어 있고, 대부분 구간이 지상 고가라 창밖이 보입니다.',
       '이름에 문(門)이 붙은 역이 하나뿐입니다. 광시먼입니다.'],
      ['A wide U across the north of Beijing. Both ends meet the Line 2 loop, and most of the route runs on elevated track, so there is a view from the window.',
       'Only one station ends in -men, meaning gate: Guangximen.'],
      ['Una amplia U por el norte de Pekín. Ambos extremos enlazan con el anillo de la línea 2 y casi todo el trazado va en viaducto, así que hay vistas desde la ventanilla.',
       'Solo una estación acaba en -men, que significa puerta: Guangximen.'],
      ['Um U largo pelo norte de Pequim. As duas pontas encostam no anel da linha 2 e quase todo o traçado é elevado, então há vista pela janela.',
       'Só uma estação termina em -men, que quer dizer portão: Guangximen.'],
      ['北京の北側を大きくU字に回る路線です。両端とも2号線の環状線に接し、区間の大半が高架なので車窓が開けています。',
       '「門」が付く駅は一つだけです。光熙門です。'],
      ['Ein weites U über den Norden Pekings. Beide Enden treffen auf den Ring der Linie 2, und der Großteil verläuft aufgeständert, es gibt also Aussicht.',
       'Nur eine Station endet auf -men, also Tor: Guangximen.'],
      ['Un large U au nord de Pékin. Les deux extrémités rejoignent la boucle de la ligne 2 et l’essentiel du parcours est en viaduc : on voit dehors.',
       'Une seule station se termine par -men, qui signifie porte : Guangximen.'],
      ['बीजिंग के उत्तर में एक चौड़ा U बनाती है। इसके दोनों सिरे लाइन 2 की रिंग से मिलते हैं और अधिकांश हिस्सा ऊपर उठा हुआ है, इसलिए खिड़की से नज़ारा दिखता है।',
       'केवल एक स्टेशन -men पर ख़त्म होता है, जिसका अर्थ है दरवाज़ा: गुआंगशीमेन।'],
      ['在北京北部画出一个大大的 U 字。两端都接上 2 号线环线，大部分路段是高架，车窗外看得见风景。',
       '带「门」字的站只有一个，就是光熙门，其余的站名都不带门字。'],
      ['在北京北部畫出一個大大的 U 字。兩端都接上 2 號線環線，大部分路段是高架，車窗外看得見風景。',
       '帶「門」字的站只有一個，就是光熙門，其餘的站名都不帶門字。'],
    ),
  },
  {
    slug: 'berlin-u8', city: 'berlin', color: '#0067b3', label: 'U8',
    shape: ['SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE',
      'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE'],
    stations: [
      s('Wittenau', undefined, 'terminus'), s('Rathaus Reinickendorf'),
      s('Karl-Bonhoeffer-Nervenklinik', undefined, 'transfer'), s('Lindauer Allee'),
      s('Paracelsus-Bad'), s('Residenzstraße'), s('Franz-Neumann-Platz'),
      s('Osloer Straße', undefined, 'transfer'), s('Pankstraße'),
      s('Gesundbrunnen', undefined, 'transfer'), s('Voltastraße'), s('Bernauer Straße'),
      s('Rosenthaler Platz'), s('Weinmeisterstraße'), s('Alexanderplatz', undefined, 'transfer'),
      s('Jannowitzbrücke', undefined, 'transfer'), s('Heinrich-Heine-Straße'),
      s('Moritzplatz'), s('Kottbusser Tor', undefined, 'transfer'), s('Schönleinstraße'),
      s('Hermannplatz', undefined, 'transfer'), s('Boddinstraße'), s('Leinestraße'),
      s('Hermannstraße', undefined, 'terminus'),
    ],
    text: T(
      ['베를린을 북서에서 남동으로 가로지르는 노선입니다. 분단 시절에는 서베를린 노선이 동베를린 밑을 지나가, 가운데 역들이 문을 닫은 채 열차만 통과했습니다.',
       '역 이름에 슈트라세(Straße)가 붙은 것이 일곱입니다. 가장 많은 꼴입니다.'],
      ['Crosses Berlin from north-west to south-east. During the division it was a West Berlin line running under East Berlin, and the middle stations sat sealed while trains rolled through.',
       'Seven stations end in Straße — the most common ending on the line.'],
      ['Cruza Berlín de noroeste a sureste. Durante la división era una línea del oeste que pasaba por debajo del Berlín oriental, y las estaciones centrales quedaban selladas mientras los trenes las atravesaban.',
       'Siete estaciones acaban en Straße, la terminación más frecuente de la línea.'],
      ['Corta Berlim de noroeste a sudeste. Durante a divisão era uma linha do lado ocidental que passava por baixo de Berlim Oriental, e as estações do meio ficavam lacradas enquanto os trens atravessavam.',
       'Sete estações terminam em Straße, a terminação mais comum da linha.'],
      ['ベルリンを北西から南東へ横切る路線です。分断時代は西ベルリンの路線が東ベルリンの地下を通り、途中の駅は封鎖されたまま列車だけが通過しました。',
       '駅名がStraßeで終わるものが七つあります。この路線でいちばん多い形です。'],
      ['Durchquert Berlin von Nordwesten nach Südosten. Zur Zeit der Teilung fuhr die Westlinie unter Ost-Berlin hindurch, und die mittleren Bahnhöfe blieben verschlossen, während die Züge durchrollten.',
       'Sieben Stationen enden auf Straße — die häufigste Endung der Linie.'],
      ['Traverse Berlin du nord-ouest au sud-est. Du temps de la division, cette ligne de l’Ouest passait sous Berlin-Est et les stations du milieu restaient murées pendant que les trains les franchissaient.',
       'Sept stations se terminent par Straße, la terminaison la plus fréquente de la ligne.'],
      ['बर्लिन को उत्तर-पश्चिम से दक्षिण-पूर्व तक काटती है। विभाजन के दौर में यह पश्चिम बर्लिन की लाइन पूर्वी बर्लिन के नीचे से गुज़रती थी, और बीच के स्टेशन बंद रहते थे जबकि गाड़ियाँ निकलती रहती थीं।',
       'सात स्टेशन Straße पर ख़त्म होते हैं — इस लाइन का सबसे आम अंत।'],
      ['自西北向东南横穿柏林。分裂时期，这条西柏林线路从东柏林地下穿过，中间各站被封死，列车只是驶过而不停。',
       '有七个站名以 Straße 结尾，是这条线上最常见的词尾。'],
      ['自西北向東南橫穿柏林。分裂時期，這條西柏林線路從東柏林地下穿過，中間各站被封死，列車只是駛過而不停。',
       '有七個站名以 Straße 結尾，是這條線上最常見的詞尾。'],
    ),
  },
  {
    slug: 'singapore-ns', city: 'singapore', color: '#d42e12',
    label: {
      ko: '남북선', en: 'North South line', es: 'Línea Norte-Sur', pt: 'Linha Norte-Sul',
      ja: '南北線', de: 'Nord-Süd-Linie', fr: 'Ligne Nord-Sud', hi: 'नॉर्थ साउथ लाइन',
      zh: '南北线', tw: '南北綫',
    },
    shape: ['NE', 'NE', 'NE', 'NE', 'NE', 'E', 'E', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE',
      'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE'],
    stations: [
      s('Jurong East', undefined, 'terminus'), s('Bukit Batok'), s('Bukit Gombak'),
      s('Choa Chu Kang', undefined, 'transfer'), s('Yew Tee'), s('Kranji'), s('Marsiling'),
      s('Woodlands', undefined, 'transfer'), s('Admiralty'), s('Sembawang'), s('Canberra'),
      s('Yishun'), s('Khatib'), s('Yio Chu Kang'), s('Ang Mo Kio'),
      s('Bishan', undefined, 'transfer'), s('Braddell'), s('Toa Payoh'), s('Novena'),
      s('Newton', undefined, 'transfer'), s('Orchard', undefined, 'transfer'), s('Somerset'),
      s('Dhoby Ghaut', undefined, 'transfer'), s('City Hall', undefined, 'transfer'),
      s('Raffles Place', undefined, 'transfer'), s('Marina Bay', undefined, 'transfer'),
      s('Marina South Pier', undefined, 'terminus'),
    ],
    text: T(
      ['싱가포르에서 가장 먼저 열린 노선으로, 서쪽 주롱이스트에서 섬을 한 바퀴 돌 듯 북쪽을 지나 남쪽 바닷가까지 갑니다. 북쪽 절반은 지상 고가라 창밖으로 말레이시아가 보이는 구간도 있습니다.',
       '이름이 부킷으로 시작하는 역이 둘입니다. 말레이어로 언덕이라는 뜻입니다.'],
      ['Singapore’s first line, running from Jurong East in the west up around the north of the island and down to the waterfront. The northern half is elevated, and from part of it you can see Malaysia.',
       'Two stations begin with Bukit, the Malay word for hill.'],
      ['La primera línea de Singapur: sale de Jurong East al oeste, rodea el norte de la isla y baja hasta el paseo marítimo. La mitad norte va en viaducto y desde un tramo se ve Malasia.',
       'Dos estaciones empiezan por Bukit, que en malayo significa colina.'],
      ['A primeira linha de Singapura: parte de Jurong East, a oeste, contorna o norte da ilha e desce até a orla. A metade norte é elevada e de um trecho dá para ver a Malásia.',
       'Duas estações começam com Bukit, palavra malaia para colina.'],
      ['シンガポール最初の路線で、西のジュロン・イーストから島の北側を回って南の海辺まで下ります。北半分は高架で、車窓からマレーシアが見える区間もあります。',
       'ブキッで始まる駅が二つあります。マレー語で「丘」という意味です。'],
      ['Singapurs erste Linie: von Jurong East im Westen um den Norden der Insel herum bis ans Wasser im Süden. Die nördliche Hälfte fährt aufgeständert, und von einem Stück aus sieht man Malaysia.',
       'Zwei Stationen beginnen mit Bukit, dem malaiischen Wort für Hügel.'],
      ['La première ligne de Singapour : de Jurong East à l’ouest, elle contourne le nord de l’île et descend jusqu’au bord de mer. La moitié nord est en viaduc et l’on aperçoit la Malaisie par endroits.',
       'Deux stations commencent par Bukit, qui veut dire colline en malais.'],
      ['सिंगापुर की पहली लाइन — पश्चिम के जुरोंग ईस्ट से निकलकर द्वीप के उत्तर का चक्कर काटती हुई दक्षिण के समुद्र तट तक जाती है। उत्तरी आधा हिस्सा ऊपर उठा हुआ है और एक जगह से मलेशिया दिखता है।',
       'दो स्टेशन Bukit से शुरू होते हैं, जो मलय में पहाड़ी को कहते हैं।'],
      ['新加坡最早开通的线路，从西边的裕廊东出发，绕过岛的北部再南下到海边。北半段是高架，有一段甚至能望见马来西亚。',
       '有两个站以 Bukit 开头，马来语里是「山丘」的意思。'],
      ['新加坡最早開通的線路，從西邊的裕廊東出發，繞過島的北部再南下到海邊。北半段是高架，有一段甚至能望見馬來西亞。',
       '有兩個站以 Bukit 開頭，馬來語裡是「山丘」的意思。'],
    ),
  },
];
