/**
 * 지하철 노선 - 서울 밖 (9)
 *
 * 역 이름은 그 도시에서 부르는 표기를 그대로 쓴다. 도쿄는 한자, 베이징은 간체,
 * 런던·뉴욕·파리는 현지 철자다. 한자·가나 노선에는 로마자를 함께 두어 그 문자를
 * 못 넣는 환경에서도 풀 수 있게 한다.
 */
import type { MetroLine } from './types.ts';

const s = (name: string, roman?: string, mark?: 'terminus' | 'transfer') => ({ name, roman, mark });
/** 영문명이 정답이고 한자명도 함께 받는 곳 — 홍콩 */
const hk = (name: string, alt: string, mark?: 'terminus' | 'transfer') => ({ name, alt, mark });

export const WORLD_LINES: MetroLine[] = [
  {
    slug: 'tokyo-yamanote', city: 'tokyo', icon: '🇯🇵', color: '#9acd32', loop: true,
    shape: ['S', 'S', 'SW', 'SW', 'SW', 'W', 'W', 'NW', 'NW', 'NW', 'N', 'N', 'N', 'NE', 'NE', 'NE', 'E', 'E', 'E', 'SE', 'SE', 'SE', 'S', 'S', 'S', 'SW', 'SW', 'SW'],
    stations: [
      s('東京', 'Tokyo', 'transfer'), s('有楽町', 'Yurakucho'), s('新橋', 'Shimbashi', 'transfer'),
      s('浜松町', 'Hamamatsucho'), s('田町', 'Tamachi'), s('高輪ゲートウェイ', 'Takanawa Gateway'),
      s('品川', 'Shinagawa', 'transfer'), s('大崎', 'Osaki'), s('五反田', 'Gotanda'),
      s('目黒', 'Meguro'), s('恵比寿', 'Ebisu'), s('渋谷', 'Shibuya', 'transfer'),
      s('原宿', 'Harajuku'), s('代々木', 'Yoyogi'), s('新宿', 'Shinjuku', 'transfer'),
      s('新大久保', 'Shin-Okubo'), s('高田馬場', 'Takadanobaba'), s('目白', 'Mejiro'),
      s('池袋', 'Ikebukuro', 'transfer'), s('大塚', 'Otsuka'), s('巣鴨', 'Sugamo'),
      s('駒込', 'Komagome'), s('田端', 'Tabata'), s('西日暮里', 'Nishi-Nippori'),
      s('日暮里', 'Nippori'), s('鶯谷', 'Uguisudani'), s('上野', 'Ueno', 'transfer'),
      s('御徒町', 'Okachimachi'), s('秋葉原', 'Akihabara', 'transfer'), s('神田', 'Kanda'),
    ],
    ko: { city: '도쿄', line: '야마노테선', country: '일본',
      intro: '도쿄 도심을 한 바퀴 도는 순환선으로 한 바퀴에 약 한 시간 걸립니다. 도쿄역·신주쿠·시부야·이케부쿠로 같은 큰 역이 모두 이 선에 있습니다.',
      hint: '역명이 한자라 로마자로 적어도 정답으로 받습니다. 신주쿠·시부야·이케부쿠로를 먼저 놓고 그 사이를 채우면 수월합니다.' },
    en: { city: 'Tokyo', line: 'Yamanote Line', country: 'Japan',
      intro: 'A loop around central Tokyo that takes about an hour to complete. Tokyo Station, Shinjuku, Shibuya and Ikebukuro all sit on it.',
      hint: 'Station names are in kanji, but romanised spellings count. Place Shinjuku, Shibuya and Ikebukuro first, then fill the gaps.' },
    zh: { city: '东京', line: '山手线', country: '日本',
      intro: '环绕东京市中心的环线，绕一圈约需一小时。东京站、新宿、涉谷、池袋等大站都在这条线上。',
      hint: '站名为日文汉字，用罗马字拼写也算对。先定下新宿、涉谷、池袋，再填中间会更顺。' },
  },
  {
    slug: 'tokyo-ginza', city: 'tokyo', icon: '🇯🇵', color: '#f39700',
    shape: ['E', 'E', 'NE', 'NE', 'E', 'E', 'SE', 'SE', 'SE', 'SE', 'SE', 'S', 'S', 'SW', 'SW', 'SW', 'W', 'W'],
    stations: [
      s('渋谷', 'Shibuya', 'terminus'), s('表参道', 'Omotesando', 'transfer'), s('外苑前', 'Gaiemmae'),
      s('青山一丁目', 'Aoyama-itchome'), s('赤坂見附', 'Akasaka-mitsuke'), s('溜池山王', 'Tameike-sanno'),
      s('新橋', 'Shimbashi', 'transfer'), s('銀座', 'Ginza', 'transfer'), s('京橋', 'Kyobashi'),
      s('日本橋', 'Nihombashi'), s('三越前', 'Mitsukoshimae'), s('神田', 'Kanda'),
      s('末広町', 'Suehirocho'), s('上野広小路', 'Ueno-hirokoji'), s('上野', 'Ueno', 'transfer'),
      s('稲荷町', 'Inaricho'), s('田原町', 'Tawaramachi'), s('浅草', 'Asakusa', 'terminus'),
    ],
    ko: { city: '도쿄', line: '긴자선', country: '일본',
      intro: '1927년에 개통한 아시아 최초의 지하철입니다. 시부야에서 아사쿠사까지 도심을 대각선으로 지납니다.',
      hint: '아시아에서 가장 오래된 지하철이라 역이 열여덟 개뿐입니다. 긴자·우에노·아사쿠사가 뼈대입니다.' },
    en: { city: 'Tokyo', line: 'Ginza Line', country: 'Japan',
      intro: 'Opened in 1927, this was Asia’s first subway line. It runs diagonally through the centre from Shibuya to Asakusa.',
      hint: 'Being the oldest, it has only eighteen stations. Ginza, Ueno and Asakusa are the anchors.' },
    zh: { city: '东京', line: '银座线', country: '日本',
      intro: '1927年通车，是亚洲最早的地铁线。从涉谷斜穿市中心直到浅草。',
      hint: '作为亚洲最老的地铁，全线只有十八站。银座、上野、浅草是骨架。' },
  },
  {
    slug: 'london-victoria', city: 'london', icon: '🇬🇧', color: '#0098d4',
    shape: ['N', 'N', 'NE', 'NE', 'N', 'N', 'NE', 'NE', 'N', 'N', 'NE', 'NE', 'N', 'N', 'NE'],
    stations: [
      s('Brixton', undefined, 'terminus'), s('Stockwell'), s('Vauxhall'), s('Pimlico'),
      s('Victoria', undefined, 'transfer'), s('Green Park', undefined, 'transfer'),
      s('Oxford Circus', undefined, 'transfer'), s('Warren Street'), s('Euston', undefined, 'transfer'),
      s('King’s Cross St Pancras', 'Kings Cross St Pancras', 'transfer'),
      s('Highbury & Islington', 'Highbury and Islington'), s('Finsbury Park', undefined, 'transfer'),
      s('Seven Sisters'), s('Tottenham Hale'), s('Blackhorse Road'),
      s('Walthamstow Central', undefined, 'terminus'),
    ],
    ko: { city: '런던', line: 'Victoria line', country: '영국',
      intro: '런던 지하철에서 전 구간이 지하인 노선이고 열여섯 개 역이 모두 다른 노선과 이어집니다. 브릭스턴에서 월섬스토까지 남북으로 지납니다.',
      hint: '열여섯 개뿐이라 짧습니다. 빅토리아·옥스퍼드서커스·킹스크로스가 뼈대입니다.' },
    en: { city: 'London', line: 'Victoria line', country: 'United Kingdom',
      intro: 'Entirely underground, and every one of its sixteen stations offers an interchange. It runs north–south from Brixton to Walthamstow.',
      hint: 'Only sixteen stations, so it is a short one. Victoria, Oxford Circus and King’s Cross are the anchors.' },
    zh: { city: '伦敦', line: 'Victoria line', country: '英国',
      intro: '全线均在地下，十六座车站每一站都能换乘其他线路。自布里克斯顿向北通往沃尔瑟姆斯托。',
      hint: '仅十六站，属于短线。维多利亚、牛津圆环、国王十字是骨架。' },
  },
  {
    slug: 'london-jubilee', city: 'london', icon: '🇬🇧', color: '#a0a5a9',
    shape: ['SE', 'SE', 'SE', 'SE', 'SE', 'E', 'E', 'E', 'SE', 'SE', 'E', 'E', 'E', 'E', 'E', 'NE', 'NE', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E'],
    stations: [
      s('Stanmore', undefined, 'terminus'), s('Canons Park'), s('Queensbury'), s('Kingsbury'),
      s('Wembley Park', undefined, 'transfer'), s('Neasden'), s('Dollis Hill'), s('Willesden Green'),
      s('Kilburn'), s('West Hampstead'), s('Finchley Road', undefined, 'transfer'),
      s('Swiss Cottage'), s('St John’s Wood', 'St Johns Wood'), s('Baker Street', undefined, 'transfer'),
      s('Bond Street', undefined, 'transfer'), s('Green Park', undefined, 'transfer'),
      s('Westminster', undefined, 'transfer'), s('Waterloo', undefined, 'transfer'), s('Southwark'),
      s('London Bridge', undefined, 'transfer'), s('Bermondsey'), s('Canada Water'),
      s('Canary Wharf', undefined, 'transfer'), s('North Greenwich'), s('Canning Town', undefined, 'transfer'),
      s('West Ham'), s('Stratford', undefined, 'terminus'),
    ],
    ko: { city: '런던', line: 'Jubilee line', country: '영국',
      intro: '스탠모어에서 스트랫퍼드까지 이어지며 카나리워프와 그리니치 같은 템스강 동쪽을 지납니다. 남동 구간은 1999년에 새로 지어 역이 크고 넓습니다.',
      hint: '서쪽 절반은 주택가 이름, 동쪽 절반은 강가 재개발 지역 이름입니다.' },
    en: { city: 'London', line: 'Jubilee line', country: 'United Kingdom',
      intro: 'From Stanmore to Stratford, taking in Canary Wharf and Greenwich east of the Thames. The south-eastern extension opened in 1999 with notably large stations.',
      hint: 'The western half is suburban names; the eastern half is riverside redevelopment.' },
    zh: { city: '伦敦', line: 'Jubilee line', country: '英国',
      intro: '从斯坦莫尔通往斯特拉特福，途经泰晤士河东岸的金丝雀码头与格林尼治。东南段于1999年新建，车站格外宽大。',
      hint: '西半段多为住宅区地名，东半段则是河畔再开发区。' },
  },
  {
    slug: 'nyc-7', city: 'newyork', icon: '🇺🇸', color: '#b933ad',
    shape: ['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'SW', 'SW', 'W', 'W', 'W', 'W', 'SW', 'SW', 'SW', 'W', 'W', 'W', 'W'],
    stations: [
      s('Flushing–Main St', 'Flushing Main St', 'terminus'), s('Mets–Willets Point', 'Mets Willets Point'),
      s('111 St'), s('103 St–Corona Plaza', '103 St Corona Plaza'), s('Junction Blvd'),
      s('90 St–Elmhurst Av', '90 St Elmhurst Av'), s('82 St–Jackson Hts', '82 St Jackson Hts'),
      s('74 St–Broadway', '74 St Broadway', 'transfer'), s('69 St'), s('Woodside–61 St', 'Woodside 61 St'),
      s('52 St'), s('46 St–Bliss St', '46 St Bliss St'), s('40 St–Lowery St', '40 St Lowery St'),
      s('33 St–Rawson St', '33 St Rawson St'), s('Queensboro Plaza', undefined, 'transfer'),
      s('Court Sq', undefined, 'transfer'), s('Hunters Point Av'), s('Vernon Blvd–Jackson Av', 'Vernon Blvd Jackson Av'),
      s('Grand Central–42 St', 'Grand Central 42 St', 'transfer'), s('5 Av'),
      s('Times Sq–42 St', 'Times Sq 42 St', 'transfer'), s('34 St–Hudson Yards', '34 St Hudson Yards', 'terminus'),
    ],
    ko: { city: '뉴욕', line: '7 train', country: '미국',
      intro: '플러싱에서 맨해튼 허드슨야드까지 퀸스를 동서로 지납니다. 여러 이민 사회를 잇달아 통과해 국제 익스프레스라는 별칭이 붙었습니다.',
      hint: '숫자로 시작하는 역이 많습니다. 111 St, 103 St처럼 스트리트 번호가 서쪽으로 갈수록 줄어듭니다.' },
    en: { city: 'New York', line: '7 train', country: 'United States',
      intro: 'Running east–west across Queens from Flushing to Hudson Yards in Manhattan. It threads so many immigrant neighbourhoods that it earned the nickname International Express.',
      hint: 'Many stops are numbered streets, and the numbers fall as you head west — 111 St, 103 St, and so on.' },
    zh: { city: '纽约', line: '7号线', country: '美国',
      intro: '自法拉盛横穿皇后区，直到曼哈顿的哈德逊广场。沿线串起众多移民社区，因而被称为“国际快线”。',
      hint: '许多站名以街道编号开头，向西编号依次减小：111街、103街等。' },
  },
  {
    slug: 'paris-1', city: 'paris', icon: '🇫🇷', color: '#ffcd00',
    shape: ['E', 'E', 'E', 'E', 'E', 'E', 'SE', 'SE', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'SE', 'SE', 'E', 'E', 'E', 'E', 'E', 'E', 'E'],
    stations: [
      s('La Défense', 'La Defense', 'terminus'), s('Esplanade de la Défense', 'Esplanade de la Defense'),
      s('Pont de Neuilly'), s('Les Sablons'), s('Porte Maillot'), s('Argentine'),
      s('Charles de Gaulle–Étoile', 'Charles de Gaulle Etoile', 'transfer'), s('George V'),
      s('Franklin D. Roosevelt', 'Franklin D Roosevelt'), s('Champs-Élysées–Clemenceau', 'Champs Elysees Clemenceau'),
      s('Concorde', undefined, 'transfer'), s('Tuileries'),
      s('Palais Royal–Musée du Louvre', 'Palais Royal Musee du Louvre'), s('Louvre–Rivoli', 'Louvre Rivoli'),
      s('Châtelet', 'Chatelet', 'transfer'), s('Hôtel de Ville', 'Hotel de Ville'), s('Saint-Paul', 'Saint Paul'),
      s('Bastille', undefined, 'transfer'), s('Gare de Lyon', undefined, 'transfer'),
      s('Reuilly–Diderot', 'Reuilly Diderot'), s('Nation', undefined, 'transfer'),
      s('Porte de Vincennes'), s('Saint-Mandé', 'Saint Mande'), s('Bérault', 'Berault'),
      s('Château de Vincennes', 'Chateau de Vincennes', 'terminus'),
    ],
    ko: { city: '파리', line: 'Ligne 1', country: '프랑스',
      intro: '1900년에 개통한 파리 최초의 노선으로 지금은 무인 운전으로 바뀌었습니다. 루브르와 샹젤리제, 바스티유를 한 줄로 잇습니다.',
      hint: '악상(é, â)이 없어도 정답으로 받습니다. Concorde·Châtelet·Bastille를 뼈대로 잡으세요.' },
    en: { city: 'Paris', line: 'Ligne 1', country: 'France',
      intro: 'Opened in 1900 as the city’s first line and now fully automated. It strings the Louvre, the Champs-Élysées and Bastille onto one route.',
      hint: 'Spellings without accents count. Use Concorde, Châtelet and Bastille as anchors.' },
    zh: { city: '巴黎', line: 'Ligne 1', country: '法国',
      intro: '1900年通车，是巴黎最早的一条线，如今已实现无人驾驶。它把卢浮宫、香榭丽舍与巴士底连成一线。',
      hint: '不带法语音符的拼写也算对。可以用协和广场、夏特雷、巴士底作为骨架。' },
  },
  {
    slug: 'beijing-2', city: 'beijing', icon: '🇨🇳', color: '#0000d1', loop: true,
    shape: ['S', 'S', 'S', 'SE', 'SE', 'E', 'E', 'E', 'NE', 'NE', 'N', 'N', 'N', 'NW', 'NW', 'W', 'W'],
    stations: [
      s('西直门', 'Xizhimen', 'transfer'), s('车公庄', 'Chegongzhuang'), s('阜成门', 'Fuchengmen'),
      s('复兴门', 'Fuxingmen', 'transfer'), s('长椿街', 'Changchunjie'), s('宣武门', 'Xuanwumen'),
      s('和平门', 'Hepingmen'), s('前门', 'Qianmen'), s('崇文门', 'Chongwenmen'),
      s('北京站', 'Beijing Railway Station', 'transfer'), s('建国门', 'Jianguomen', 'transfer'),
      s('朝阳门', 'Chaoyangmen'), s('东四十条', 'Dongsi Shitiao'), s('东直门', 'Dongzhimen', 'transfer'),
      s('雍和宫', 'Yonghegong'), s('安定门', 'Andingmen'), s('鼓楼大街', 'Guloudajie'),
      s('积水潭', 'Jishuitan'),
    ],
    ko: { city: '베이징', line: '2호선', country: '중국',
      intro: '옛 성벽이 있던 자리를 따라 도는 순환선입니다. 그래서 역 이름에 문(門)이 붙은 것이 많습니다.',
      hint: '이름 끝이 門으로 끝나는 역이 여덟 개입니다. 성문 이름을 시계 방향으로 떠올려 보세요.' },
    en: { city: 'Beijing', line: 'Line 2', country: 'China',
      intro: 'A loop that follows the line of the old city wall, which is why so many stations end in “men” — gate.',
      hint: 'Eight stations end in “-men”. Work round the old city gates in order.' },
    zh: { city: '北京', line: '2号线', country: '中国',
      intro: '沿旧城墙位置环行的环线，因此站名中带“门”字的特别多。',
      hint: '以“门”结尾的车站有八个，可按顺时针顺序回忆各座城门。' },
  },
  {
    slug: 'hongkong-island', city: 'hongkong', icon: '🇭🇰', color: '#0075c2',
    shape: ['E', 'E', 'E', 'E', 'E', 'E', 'E', 'NE', 'NE', 'E', 'E', 'E', 'E', 'SE', 'SE', 'E'],
    stations: [
      hk('Kennedy Town', '堅尼地城', 'terminus'), hk('HKU', '香港大學'), hk('Sai Ying Pun', '西營盤'),
      hk('Sheung Wan', '上環'), hk('Central', '中環', 'transfer'), hk('Admiralty', '金鐘', 'transfer'),
      hk('Wan Chai', '灣仔'), hk('Causeway Bay', '銅鑼灣'), hk('Tin Hau', '天后'),
      hk('Fortress Hill', '炮台山'), hk('North Point', '北角', 'transfer'), hk('Quarry Bay', '鰂魚涌', 'transfer'),
      hk('Tai Koo', '太古'), hk('Sai Wan Ho', '西灣河'), hk('Shau Kei Wan', '筲箕灣'),
      hk('Heng Fa Chuen', '杏花邨'), hk('Chai Wan', '柴灣', 'terminus'),
    ],
    ko: { city: '홍콩', line: 'Island line', country: '홍콩',
      intro: '홍콩섬 북쪽 해안을 따라 서에서 동으로 지납니다. 센트럴과 애드미럴티에서 다른 노선과 갈아탑니다.',
      hint: '영어 이름과 한자 이름을 모두 정답으로 받습니다. Central은 中環, Admiralty는 金鐘입니다.' },
    en: { city: 'Hong Kong', line: 'Island line', country: 'Hong Kong',
      intro: 'Running west to east along the northern shore of Hong Kong Island, with interchanges at Central and Admiralty.',
      hint: 'Both English and Chinese names count. Central is 中環 and Admiralty is 金鐘.' },
    zh: { city: '香港', line: '港岛线', country: '香港',
      intro: '沿香港岛北岸自西向东行驶，在中环与金钟可换乘其他线路。',
      hint: '英文名与中文名都算对。Central即中环，Admiralty即金钟。' },
  },
  {
    slug: 'singapore-ne', city: 'singapore', icon: '🇸🇬', color: '#9e28b5',
    shape: ['NE', 'NE', 'NE', 'NE', 'N', 'N', 'NE', 'NE', 'NE', 'NE', 'NE', 'NE', 'N', 'N', 'NE'],
    stations: [
      s('HarbourFront', undefined, 'terminus'), s('Outram Park', undefined, 'transfer'), s('Chinatown', undefined, 'transfer'),
      s('Clarke Quay'), s('Dhoby Ghaut', undefined, 'transfer'), s('Little India', undefined, 'transfer'),
      s('Farrer Park'), s('Boon Keng'), s('Potong Pasir'), s('Woodleigh'),
      s('Serangoon', undefined, 'transfer'), s('Kovan'), s('Hougang'), s('Buangkok'),
      s('Sengkang', undefined, 'transfer'), s('Punggol', undefined, 'terminus'),
    ],
    ko: { city: '싱가포르', line: 'North East line', country: '싱가포르',
      intro: '개통 당시 세계에서 처음으로 전 구간을 무인으로 운행한 지하 노선입니다. 하버프론트에서 북동쪽 풍골까지 이어집니다.',
      hint: '말레이어에서 온 이름이 많습니다. Boon Keng·Hougang·Buangkok처럼 두 음절씩 끊어 읽으면 떠올리기 쉽습니다.' },
    en: { city: 'Singapore', line: 'North East line', country: 'Singapore',
      intro: 'On opening it was the world’s first fully automated underground line. It runs from HarbourFront north-east to Punggol.',
      hint: 'Many names come from Malay. Reading them in two syllables — Boon Keng, Hougang, Buangkok — helps recall.' },
    zh: { city: '新加坡', line: '东北线', country: '新加坡',
      intro: '通车时是世界上第一条全线无人驾驶的地下线路，从港湾一直通往东北部的榜鹅。',
      hint: '许多站名源自马来语，按两个音节来读会更容易想起：Boon Keng、Hougang、Buangkok。' },
  },
];
