/**
 * 지하철 노선 — 이미 있는 도시에 두 번째 노선을 넣는다 (10개).
 *
 * 도시를 늘리지 않고 노선을 늘린 이유: 한 도시에 노선이 하나뿐이면 "관련 노선"이
 * 언제나 다른 나라로 튄다. 서울처럼 여러 노선이 있는 도시라야 한 도시를 파고들 수
 * 있고, cities.ts를 건드리지 않아 나라 이름 열 벌을 새로 적지 않아도 된다.
 *
 * 역 이름은 모두 위키백과의 노선 문서에서 확인해 옮겼다 — 기억으로 적으면
 * 한두 역이 조용히 틀리는데, 이 게임에서는 그 한 역이 영원히 안 풀린다.
 * 베를린 U2의 Anton-Wilhelm-Amo-Straße처럼 최근에 이름이 바뀐 역도 있다.
 *
 * label에 zh·tw를 함께 적는다. 여덟 언어만 적으면 lineName이 영어로 떨어져
 * 중국어 화면에 영어 노선 이름이 나오는데, 검사는 그것을 잡지 못한다.
 */
import { T, s, sa } from './copy.ts';
import type { MetroLine } from './types.ts';

export const WORLD2_LINES: MetroLine[] = [
  {
    slug: 'seoul-ui-sinseol', city: 'seoul', color: '#b7c450',
    label: {
      ko: '우이신설선', en: 'Ui LRT', es: 'Línea Ui', pt: 'Linha Ui', ja: '牛耳新設線',
      de: 'Ui-Linie', fr: 'Ligne Ui', hi: 'ऊई लाइन', zh: '牛耳新设线', tw: '牛耳新設線',
    },
    shape: ['S', 'S', 'S', 'S', 'SE', 'SE', 'SE', 'SE', 'S', 'S', 'SE', 'SE'],
    stations: [
      s('북한산우이', 'Bukhansan Ui', 'terminus'), s('솔밭공원', 'Solbat Park'),
      s('4·19민주묘지', '4.19 Democracy Cemetery'), s('가오리', 'Gaori'),
      s('화계', 'Hwagye'), s('삼양', 'Samyang'), s('삼양사거리', 'Samyang Sageori'),
      s('솔샘', 'Solsaem'), s('북한산보국문', 'Bukhansan Bogungmun'),
      s('정릉', 'Jeongneung'), s('성신여대입구', 'Sungshin Womens University', 'transfer'),
      s('보문', 'Bomun', 'transfer'), s('신설동', 'Sinseol-dong', 'terminus'),
    ],
    text: T(
      ['서울 북동쪽 우이동에서 신설동까지 이어지는 경전철입니다. 열세 역으로 서울에서 가장 짧은 축에 들고, 차량이 두 칸뿐이라 지하철보다 작습니다.',
       '북한산이 들어간 역이 둘입니다. 북한산우이와 북한산보국문, 둘 다 등산로 들머리입니다.'],
      ['A light rail line running from Ui-dong in north-east Seoul down to Sinseol-dong. With thirteen stations it is one of the shortest lines in the city, and the trains are only two cars long.',
       'Two stations start with Bukhansan — Bukhansan Ui and Bukhansan Bogungmun. Both sit at trailheads for the mountain.'],
      ['Un tren ligero que baja desde Ui-dong, al noreste de Seúl, hasta Sinseol-dong. Con trece estaciones es de las líneas más cortas de la ciudad y los trenes sólo tienen dos coches.',
       'Dos estaciones empiezan por Bukhansan: Bukhansan Ui y Bukhansan Bogungmun. Las dos están al pie de la montaña.'],
      ['Um veículo leve sobre trilhos que desce de Ui-dong, no nordeste de Seul, até Sinseol-dong. Com treze estações é uma das linhas mais curtas da cidade e os trens têm apenas dois carros.',
       'Duas estações começam com Bukhansan: Bukhansan Ui e Bukhansan Bogungmun. As duas ficam no pé da montanha.'],
      ['ソウル北東部の牛耳洞から新設洞まで下るライトレールです。十三駅と市内で最も短い部類で、車両も二両しかありません。',
       '北漢山で始まる駅が二つあります。北漢山牛耳と北漢山普国門、どちらも登山口です。'],
      ['Eine Stadtbahn, die vom Stadtteil Ui-dong im Nordosten Seouls hinunter nach Sinseol-dong führt. Mit dreizehn Stationen ist sie eine der kürzesten Linien der Stadt, die Züge haben nur zwei Wagen.',
       'Zwei Stationen beginnen mit Bukhansan — Bukhansan Ui und Bukhansan Bogungmun. Beide liegen an Wanderwegen.'],
      ['Un tramway léger qui descend d’Ui-dong, au nord-est de Séoul, jusqu’à Sinseol-dong. Avec treize stations, c’est l’une des lignes les plus courtes de la ville, et les rames ne font que deux voitures.',
       'Deux stations commencent par Bukhansan : Bukhansan Ui et Bukhansan Bogungmun. Toutes deux sont au départ de sentiers.'],
      ['सियोल के उत्तर-पूर्व में Ui-dong से Sinseol-dong तक जाने वाली लाइट रेल। तेरह स्टेशनों के साथ यह शहर की सबसे छोटी लाइनों में है और गाड़ियाँ सिर्फ़ दो डिब्बों की हैं।',
       'दो स्टेशन Bukhansan से शुरू होते हैं — Bukhansan Ui और Bukhansan Bogungmun। दोनों पहाड़ी रास्तों के मुहाने पर हैं।'],
      ['从首尔东北的牛耳洞通往新设洞的轻轨。全线十三站，是市内最短的线路之一，列车也只有两节。',
       '有两个站以北汉山开头：北汉山牛耳和北汉山普国门，都在登山口。'],
      ['從首爾東北的牛耳洞通往新設洞的輕軌。全線十三站，是市內最短的路線之一，列車也只有兩節。',
       '有兩個站以北漢山開頭：北漢山牛耳和北漢山普國門，都在登山口。'],
    ),
  },
  {
    slug: 'busan-line-3', city: 'busan', num: '3', color: '#bb8c00',
    shape: ['W', 'W', 'W', 'W', 'NW', 'NW', 'NW', 'NW', 'N', 'N', 'N', 'NW', 'NW', 'NW', 'W', 'W'],
    stations: [
      s('수영', 'Suyeong', 'terminus'), s('망미', 'Mangmi'), s('배산', 'Baesan'),
      s('물만골', 'Mulmangol'), s('연산', 'Yeonsan', 'transfer'), s('거제', 'Geoje'),
      s('종합운동장', 'Sports Complex'), s('사직', 'Sajik'), s('미남', 'Minam', 'transfer'),
      s('만덕', 'Mandeok'), s('남산정', 'Namsanjeong'), s('숙등', 'Sukdeung'),
      s('덕천', 'Deokcheon', 'transfer'), s('구포', 'Gupo'),
      s('강서구청', 'Gangseo-gu Office'), s('체육공원', 'Sports Park'),
      s('대저', 'Daejeo', 'terminus'),
    ],
    text: T(
      ['부산 수영에서 낙동강 건너 대저까지 이어지는 열일곱 역짜리 노선입니다. 연산·미남·덕천 세 곳에서 다른 노선과 만납니다.',
       '사직야구장이 있는 사직역과 종합운동장역이 나란히 붙어 있습니다. 두 역 다 야구 보러 가는 길입니다.'],
      ['Seventeen stations from Suyeong across the Nakdong River to Daejeo. It meets the other Busan lines at Yeonsan, Minam and Deokcheon.',
       'Sajik and Sports Complex sit next to each other — both serve the baseball stadium.'],
      ['Diecisiete estaciones desde Suyeong hasta Daejeo, cruzando el río Nakdong. Enlaza con las otras líneas de Busan en Yeonsan, Minam y Deokcheon.',
       'Sajik y Sports Complex están una al lado de la otra: las dos sirven al estadio de béisbol.'],
      ['Dezessete estações de Suyeong até Daejeo, atravessando o rio Nakdong. Liga-se às outras linhas de Busan em Yeonsan, Minam e Deokcheon.',
       'Sajik e Sports Complex ficam lado a lado: as duas servem o estádio de beisebol.'],
      ['釜山の水営から洛東江を渡って大渚まで、十七駅の路線です。蓮山・美南・徳川の三駅で他の路線と接続します。',
       '社稷駅と総合運動場駅が隣り合っています。どちらも野球場への駅です。'],
      ['Siebzehn Stationen von Suyeong über den Nakdong bis Daejeo. Umstiege zu den anderen Linien Busans gibt es in Yeonsan, Minam und Deokcheon.',
       'Sajik und Sports Complex liegen nebeneinander — beide bedienen das Baseballstadion.'],
      ['Dix-sept stations de Suyeong à Daejeo, en franchissant le Nakdong. Elle rejoint les autres lignes de Busan à Yeonsan, Minam et Deokcheon.',
       'Sajik et Sports Complex se suivent : les deux desservent le stade de baseball.'],
      ['Suyeong से Nakdong नदी पार करके Daejeo तक सत्रह स्टेशन। Yeonsan, Minam और Deokcheon पर बुसान की दूसरी लाइनों से जुड़ती है।',
       'Sajik और Sports Complex अगल-बगल हैं — दोनों बेसबॉल स्टेडियम के लिए हैं।'],
      ['从釜山水营越过洛东江到大渚，全线十七站。在莲山、美南、德川三站与其他线路换乘。',
       '社稷站和综合运动场站紧挨着，两站都是去棒球场的。'],
      ['從釜山水營越過洛東江到大渚，全線十七站。在蓮山、美南、德川三站與其他路線換乘。',
       '社稷站和綜合運動場站緊挨著，兩站都是去棒球場的。'],
    ),
  },
  {
    slug: 'tokyo-marunouchi', city: 'tokyo', color: '#f62e36',
    label: {
      ko: '마루노우치선', en: 'Marunouchi Line', es: 'Línea Marunouchi', pt: 'Linha Marunouchi',
      ja: '丸ノ内線', de: 'Marunouchi-Linie', fr: 'Ligne Marunouchi', hi: 'मारुनोउचि लाइन',
      zh: '丸之内线', tw: '丸之內線',
    },
    shape: ['E', 'E', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE', 'SE', 'E', 'E', 'E', 'E', 'NE', 'NE', 'NE', 'NE', 'N', 'N', 'N', 'NW', 'NW', 'NW'],
    stations: [
      s('荻窪', 'Ogikubo', 'terminus'), s('南阿佐ケ谷', 'Minami-asagaya'),
      s('新高円寺', 'Shin-koenji'), s('東高円寺', 'Higashi-koenji'), s('新中野', 'Shin-nakano'),
      s('中野坂上', 'Nakano-sakaue', 'transfer'), s('西新宿', 'Nishi-shinjuku'),
      s('新宿', 'Shinjuku', 'transfer'), s('新宿三丁目', 'Shinjuku-sanchome', 'transfer'),
      s('新宿御苑前', 'Shinjuku-gyoemmae'), s('四谷三丁目', 'Yotsuya-sanchome'),
      s('四ツ谷', 'Yotsuya', 'transfer'), s('赤坂見附', 'Akasaka-mitsuke', 'transfer'),
      s('国会議事堂前', 'Kokkai-gijidomae', 'transfer'), s('霞ケ関', 'Kasumigaseki', 'transfer'),
      s('銀座', 'Ginza', 'transfer'), s('東京', 'Tokyo', 'transfer'),
      s('大手町', 'Otemachi', 'transfer'), s('淡路町', 'Awajicho'), s('御茶ノ水', 'Ochanomizu'),
      s('本郷三丁目', 'Hongo-sanchome'), s('後楽園', 'Korakuen', 'transfer'),
      s('茗荷谷', 'Myogadani'), s('新大塚', 'Shin-otsuka'), s('池袋', 'Ikebukuro', 'terminus'),
    ],
    text: T(
      ['오기쿠보에서 이케부쿠로까지 크게 휘어 도는 도쿄메트로의 붉은 노선입니다. 신주쿠·긴자·도쿄·이케부쿠로를 한 줄로 꿰어 갈아탈 일이 가장 많은 노선 가운데 하나입니다.',
       '한자와 로마자를 모두 정답으로 받습니다. 신주쿠가 셋(新宿·新宿三丁目·新宿御苑前), 요쓰야가 둘(四谷三丁目·四ツ谷)입니다.'],
      ['Tokyo Metro’s red line, curving from Ogikubo round to Ikebukuro. It strings together Shinjuku, Ginza, Tokyo and Ikebukuro, which makes it one of the busiest interchanges in the network.',
       'Kanji and romaji both count. There are three Shinjuku stations and two Yotsuya ones.'],
      ['La línea roja del metro de Tokio, que describe una curva de Ogikubo a Ikebukuro. Enhebra Shinjuku, Ginza, Tokio e Ikebukuro, así que es de las más transitadas.',
       'Valen los kanji y la transcripción latina. Hay tres estaciones Shinjuku y dos Yotsuya.'],
      ['A linha vermelha do metrô de Tóquio, que descreve uma curva de Ogikubo até Ikebukuro. Enfia Shinjuku, Ginza, Tóquio e Ikebukuro numa linha só, e por isso é das mais movimentadas.',
       'Valem os kanji e a transcrição latina. Há três estações Shinjuku e duas Yotsuya.'],
      ['荻窪から池袋まで大きく弧を描く東京メトロの赤い路線です。新宿・銀座・東京・池袋を一本でつなぎ、乗り換えの多さでも屈指です。',
       '漢字でもローマ字でも正解になります。新宿が三つ、四谷が二つあります。'],
      ['Die rote Linie der Tokyo Metro, die in einem Bogen von Ogikubo nach Ikebukuro führt. Sie reiht Shinjuku, Ginza, Tokio und Ikebukuro auf und ist damit eine der am stärksten genutzten.',
       'Kanji und Umschrift zählen beide. Es gibt drei Shinjuku-Stationen und zwei Yotsuya.'],
      ['La ligne rouge du métro de Tokyo, en arc d’Ogikubo jusqu’à Ikebukuro. Elle enfile Shinjuku, Ginza, Tokyo et Ikebukuro : c’est l’une des plus fréquentées.',
       'Les kanji comme la transcription latine comptent. Il y a trois stations Shinjuku et deux Yotsuya.'],
      ['टोक्यो मेट्रो की लाल लाइन, जो Ogikubo से घूमकर Ikebukuro तक जाती है। यह Shinjuku, Ginza, Tokyo और Ikebukuro को एक ही धागे में पिरोती है।',
       'कांजी और रोमन दोनों चलते हैं। Shinjuku नाम के तीन स्टेशन हैं और Yotsuya के दो।'],
      ['东京地铁的红色线路，从荻洼绕一个大弯到池袋。它把新宿、银座、东京、池袋串在一条线上，换乘量数一数二。',
       '汉字和罗马字都算对。新宿有三个站，四谷有两个。'],
      ['東京地鐵的紅色路線，從荻窪繞一個大彎到池袋。它把新宿、銀座、東京、池袋串在一條線上，換乘量數一數二。',
       '漢字和羅馬字都算對。新宿有三個站，四谷有兩個。'],
    ),
  },
  {
    slug: 'london-bakerloo', city: 'london', color: '#b36305',
    label: {
      ko: '베이컬루선', en: 'Bakerloo line', es: 'Línea Bakerloo', pt: 'Linha Bakerloo',
      ja: 'ベーカールー線', de: 'Bakerloo Line', fr: 'Bakerloo line', hi: 'बेकरलू लाइन',
      zh: '贝克卢线', tw: '貝克盧線',
    },
    shape: ['SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'S', 'S', 'S', 'S', 'SE', 'SE', 'SE', 'SE', 'S', 'S', 'S', 'S', 'SE', 'SE', 'SE', 'SE'],
    stations: [
      s('Harrow & Wealdstone', 'Harrow and Wealdstone', 'terminus'), s('Kenton'),
      s('South Kenton'), s('North Wembley'), s('Wembley Central'), s('Stonebridge Park'),
      s('Harlesden'), s('Willesden Junction', undefined, 'transfer'), s('Kensal Green'),
      s('Queen’s Park', 'Queens Park', 'transfer'), s('Kilburn Park'), s('Maida Vale'),
      s('Warwick Avenue'), s('Paddington', undefined, 'transfer'),
      s('Edgware Road', undefined, 'transfer'), s('Marylebone', undefined, 'transfer'),
      s('Baker Street', undefined, 'transfer'), s('Regent’s Park', 'Regents Park'),
      s('Oxford Circus', undefined, 'transfer'), s('Piccadilly Circus', undefined, 'transfer'),
      s('Charing Cross', undefined, 'transfer'), s('Embankment', undefined, 'transfer'),
      s('Waterloo', undefined, 'transfer'), s('Lambeth North'),
      s('Elephant & Castle', 'Elephant and Castle', 'terminus'),
    ],
    text: T(
      ['이름이 두 역을 붙여 만든 것입니다 — 베이커 스트리트와 워털루. 1906년에 그 둘 사이를 잇는 노선으로 열렸고, 지도에서는 갈색으로 그립니다.',
       '&를 and로 써도 정답입니다. 워털루와 채링크로스를 먼저 놓고 북서쪽 웸블리 쪽으로 거슬러 올라가 보세요.'],
      ['The name is two stations glued together — Baker Street and Waterloo. It opened in 1906 as the link between them, and it is the brown line on the map.',
       'Typing “and” for & counts. Anchor on Waterloo and Charing Cross, then work back north-west towards Wembley.'],
      ['El nombre son dos estaciones pegadas: Baker Street y Waterloo. Se abrió en 1906 para unirlas y es la línea marrón del plano.',
       'Puedes escribir “and” en lugar de &. Fija Waterloo y Charing Cross y sube hacia Wembley, al noroeste.'],
      ['O nome são duas estações coladas: Baker Street e Waterloo. Abriu em 1906 para ligá-las e é a linha marrom do mapa.',
       'Pode escrever “and” em vez de &. Fixe Waterloo e Charing Cross e siga para noroeste, rumo a Wembley.'],
      ['路線名は二つの駅をつないだものです——ベーカー・ストリートとウォータールー。1906年にその間を結ぶ路線として開業し、路線図では茶色で描かれます。',
       '& は and と打っても正解です。ウォータールーとチャリング・クロスを先に置き、北西のウェンブリー方面へ遡りましょう。'],
      ['Der Name ist aus zwei Stationen zusammengesetzt — Baker Street und Waterloo. 1906 als Verbindung zwischen beiden eröffnet, im Plan ist sie braun.',
       'Statt & darf man „and“ tippen. Setze Waterloo und Charing Cross und arbeite dich nach Nordwesten Richtung Wembley vor.'],
      ['Le nom est fait de deux stations collées : Baker Street et Waterloo. Ouverte en 1906 pour les relier, c’est la ligne brune du plan.',
       'On peut taper « and » à la place de &. Posez Waterloo et Charing Cross, puis remontez vers Wembley au nord-ouest.'],
      ['नाम दो स्टेशनों को जोड़कर बना है — Baker Street और Waterloo। 1906 में इन्हें जोड़ने के लिए खुली, नक़्शे पर यह भूरी लाइन है।',
       '& की जगह “and” लिखना भी चलता है। Waterloo और Charing Cross से शुरू करके उत्तर-पश्चिम Wembley की ओर बढ़ें।'],
      ['线名是把两个站名拼起来的——Baker Street 和 Waterloo。1906 年作为连接两者的线路通车，在线路图上是棕色。',
       '& 打成 and 也算对。先定住 Waterloo 和 Charing Cross，再往西北的温布利方向倒推。'],
      ['線名是把兩個站名拼起來的——Baker Street 和 Waterloo。1906 年作為連接兩者的路線通車，在路線圖上是棕色。',
       '& 打成 and 也算對。先定住 Waterloo 和 Charing Cross，再往西北的溫布利方向倒推。'],
    ),
  },
  {
    slug: 'paris-6', city: 'paris', num: '6', color: '#6eca97',
    shape: ['SE', 'SE', 'SE', 'SE', 'S', 'S', 'S', 'S', 'SE', 'SE', 'SE', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'NE', 'NE', 'NE', 'NE', 'N', 'N', 'NE', 'NE'],
    stations: [
      s('Charles de Gaulle–Étoile', 'Charles de Gaulle Etoile', 'terminus'), s('Kléber', 'Kleber'),
      s('Boissière', 'Boissiere'), s('Trocadéro', 'Trocadero', 'transfer'), s('Passy'),
      s('Bir-Hakeim', 'Bir Hakeim'), s('Dupleix'),
      s('La Motte-Picquet–Grenelle', 'La Motte Picquet Grenelle', 'transfer'), s('Cambronne'),
      s('Sèvres–Lecourbe', 'Sevres Lecourbe'), s('Pasteur'),
      s('Montparnasse–Bienvenüe', 'Montparnasse Bienvenue', 'transfer'), s('Edgar Quinet'),
      s('Raspail', undefined, 'transfer'), s('Denfert-Rochereau', 'Denfert Rochereau', 'transfer'),
      s('Saint-Jacques', 'Saint Jacques'), s('Glacière', 'Glaciere'), s('Corvisart'),
      s('Place d’Italie', 'Place d Italie', 'transfer'), s('Nationale'), s('Chevaleret'),
      s('Quai de la Gare'), s('Bercy', undefined, 'transfer'), s('Dugommier'),
      s('Daumesnil', undefined, 'transfer'), s('Bel-Air', 'Bel Air'), s('Picpus'),
      s('Nation', undefined, 'transfer', ),
    ],
    text: T(
      ['파리 남쪽을 크게 감아 도는 노선으로, 절반 가까이가 고가입니다. 비르아켐 다리 위에서 에펠탑이 정면으로 보여 파리에서 경치가 가장 좋은 지하철로 꼽힙니다.',
       '악센트 없이 써도 정답입니다. Bir-Hakeim·Montparnasse·Place d’Italie를 뼈대로 잡아 보세요.'],
      ['A wide arc across southern Paris, almost half of it on viaduct. Crossing the Bir-Hakeim bridge it faces the Eiffel Tower head-on, which makes it the best view from any Paris métro.',
       'Spellings without accents count. Anchor on Bir-Hakeim, Montparnasse and Place d’Italie.'],
      ['Un arco amplio por el sur de París, casi la mitad en viaducto. Al cruzar el puente de Bir-Hakeim queda la Torre Eiffel de frente: la mejor vista del metro parisino.',
       'Las grafías sin acentos valen. Fija Bir-Hakeim, Montparnasse y Place d’Italie.'],
      ['Um arco largo pelo sul de Paris, quase metade em viaduto. Ao cruzar a ponte de Bir-Hakeim a Torre Eiffel fica de frente: a melhor vista do metrô parisiense.',
       'As grafias sem acento valem. Fixe Bir-Hakeim, Montparnasse e Place d’Italie.'],
      ['パリ南部を大きく回る路線で、半分近くが高架です。ビル・アケム橋の上ではエッフェル塔が正面に見え、パリの地下鉄でいちばん眺めのよい区間とされます。',
       'アクセント記号なしでも正解です。Bir-Hakeim・Montparnasse・Place d’Italie を骨組みにしましょう。'],
      ['Ein weiter Bogen durch den Süden von Paris, fast zur Hälfte auf Viadukt. Auf der Brücke von Bir-Hakeim liegt der Eiffelturm direkt voraus — die schönste Aussicht der Pariser Métro.',
       'Schreibweisen ohne Akzente zählen. Setze Bir-Hakeim, Montparnasse und Place d’Italie.'],
      ['Un large arc à travers le sud de Paris, presque moitié en viaduc. Sur le pont de Bir-Hakeim, la tour Eiffel est droit devant : la plus belle vue du métro parisien.',
       'Les graphies sans accents comptent. Posez Bir-Hakeim, Montparnasse et Place d’Italie.'],
      ['दक्षिणी पेरिस पर एक चौड़ा चाप, लगभग आधा वायाडक्ट पर। Bir-Hakeim पुल पर एफ़िल टॉवर बिलकुल सामने पड़ता है — पेरिस मेट्रो का सबसे अच्छा नज़ारा।',
       'बिना उच्चारण-चिह्न वाली वर्तनी चलती है। Bir-Hakeim, Montparnasse और Place d’Italie को ढाँचा बनाएँ।'],
      ['绕巴黎南部画出一道大弧，近一半是高架。过比尔阿坎桥时埃菲尔铁塔正对着车窗，被认为是巴黎地铁风景最好的一段。',
       '不打重音符号也算对。先立住 Bir-Hakeim、Montparnasse、Place d’Italie。'],
      ['繞巴黎南部畫出一道大弧，近一半是高架。過比爾阿坎橋時艾菲爾鐵塔正對著車窗，被認為是巴黎地鐵風景最好的一段。',
       '不打重音符號也算對。先立住 Bir-Hakeim、Montparnasse、Place d’Italie。'],
    ),
  },
  {
    slug: 'berlin-u2', city: 'berlin', label: 'U2', color: '#da421e',
    shape: ['SW', 'SW', 'S', 'S', 'S', 'SW', 'SW', 'SW', 'W', 'W', 'SW', 'SW', 'W', 'W', 'SW', 'SW', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W'],
    stations: [
      s('Pankow', undefined, 'terminus'), s('Vinetastraße', 'Vinetastrasse'),
      s('Schönhauser Allee', 'Schoenhauser Allee', 'transfer'),
      s('Eberswalder Straße', 'Eberswalder Strasse'), s('Senefelderplatz'),
      s('Rosa-Luxemburg-Platz', 'Rosa Luxemburg Platz'),
      s('Alexanderplatz', undefined, 'transfer'), s('Klosterstraße', 'Klosterstrasse'),
      s('Märkisches Museum', 'Maerkisches Museum'), s('Spittelmarkt'), s('Hausvogteiplatz'),
      s('Stadtmitte', undefined, 'transfer'),
      s('Anton-Wilhelm-Amo-Straße', 'Anton Wilhelm Amo Strasse'),
      s('Potsdamer Platz', undefined, 'transfer'), s('Mendelssohn-Bartholdy-Park', 'Mendelssohn Bartholdy Park'),
      s('Gleisdreieck', undefined, 'transfer'), s('Bülowstraße', 'Buelowstrasse'),
      s('Nollendorfplatz', undefined, 'transfer'), s('Wittenbergplatz', undefined, 'transfer'),
      s('Zoologischer Garten', undefined, 'transfer'), s('Ernst-Reuter-Platz', 'Ernst Reuter Platz'),
      s('Deutsche Oper'), s('Bismarckstraße', 'Bismarckstrasse', 'transfer'),
      s('Sophie-Charlotte-Platz', 'Sophie Charlotte Platz'), s('Kaiserdamm'),
      s('Theodor-Heuss-Platz', 'Theodor Heuss Platz'), s('Neu-Westend', 'Neu Westend'),
      s('Olympia-Stadion', 'Olympia Stadion'), s('Ruhleben', undefined, 'terminus'),
    ],
    text: T(
      ['판코에서 루레벤까지 베를린을 북동에서 서로 가로지릅니다. 알렉산더플라츠·포츠다머플라츠·초오까지 도심을 잇고, 서쪽 끝에는 1936년 올림픽 경기장이 있습니다.',
       'ß는 ss로 쳐도 됩니다. 2025년에 Mohrenstraße가 Anton-Wilhelm-Amo-Straße로 바뀌었습니다.'],
      ['From Pankow to Ruhleben, cutting across Berlin from north-east to west. It links Alexanderplatz, Potsdamer Platz and Zoo, and ends at the 1936 Olympic stadium.',
       'Type ss for ß. Mohrenstraße was renamed Anton-Wilhelm-Amo-Straße in 2025.'],
      ['De Pankow a Ruhleben, cruzando Berlín del noreste al oeste. Une Alexanderplatz, Potsdamer Platz y el Zoo, y acaba en el estadio olímpico de 1936.',
       'Puedes escribir ss en lugar de ß. Mohrenstraße pasó a llamarse Anton-Wilhelm-Amo-Straße en 2025.'],
      ['De Pankow a Ruhleben, cortando Berlim do nordeste ao oeste. Liga Alexanderplatz, Potsdamer Platz e o Zoo, e termina no estádio olímpico de 1936.',
       'Pode digitar ss em vez de ß. Mohrenstraße passou a chamar-se Anton-Wilhelm-Amo-Straße em 2025.'],
      ['パンコウからルーレーベンまで、ベルリンを北東から西へ横断します。アレクサンダー広場・ポツダム広場・動物園駅を結び、西端は1936年のオリンピック競技場です。',
       'ß は ss で構いません。Mohrenstraße は2025年に Anton-Wilhelm-Amo-Straße へ改称されました。'],
      ['Von Pankow nach Ruhleben, quer durch Berlin von Nordost nach West. Sie verbindet Alexanderplatz, Potsdamer Platz und den Zoo und endet am Olympiastadion von 1936.',
       'Für ß darf man ss tippen. Die Mohrenstraße heißt seit 2025 Anton-Wilhelm-Amo-Straße.'],
      ['De Pankow à Ruhleben, elle traverse Berlin du nord-est à l’ouest. Elle relie Alexanderplatz, Potsdamer Platz et le Zoo, et se termine au stade olympique de 1936.',
       'On peut taper ss pour ß. Mohrenstraße a été rebaptisée Anton-Wilhelm-Amo-Straße en 2025.'],
      ['Pankow से Ruhleben तक, बर्लिन को उत्तर-पूर्व से पश्चिम काटती है। यह Alexanderplatz, Potsdamer Platz और Zoo को जोड़ती है और 1936 के ओलंपिक स्टेडियम पर ख़त्म होती है।',
       'ß की जगह ss टाइप करें। Mohrenstraße का नाम 2025 में Anton-Wilhelm-Amo-Straße हो गया।'],
      ['从潘科到鲁勒本，自东北向西横穿柏林。沿线串起亚历山大广场、波茨坦广场和动物园站，西端是 1936 年的奥林匹克体育场。',
       'ß 打成 ss 也行。Mohrenstraße 已于 2025 年改名为 Anton-Wilhelm-Amo-Straße。'],
      ['從潘科到魯勒本，自東北向西橫穿柏林。沿線串起亞歷山大廣場、波茨坦廣場和動物園站，西端是 1936 年的奧林匹克體育場。',
       'ß 打成 ss 也行。Mohrenstraße 已於 2025 年改名為 Anton-Wilhelm-Amo-Straße。'],
    ),
  },
  {
    slug: 'madrid-line-6', city: 'madrid', num: '6', color: '#999999', loop: true,
    shape: ['E', 'E', 'NE', 'NE', 'N', 'N', 'NW', 'NW', 'W', 'W', 'SW', 'SW', 'S', 'S', 'SE', 'SE'],
    stations: [
      s('Laguna'), s('Carpetana'), s('Oporto', undefined, 'transfer'), s('Opañel', 'Opanel'),
      s('Plaza Elíptica', 'Plaza Eliptica', 'transfer'), s('Usera'),
      s('Legazpi', undefined, 'transfer'), s('Arganzuela-Planetario', 'Arganzuela Planetario'),
      s('Méndez Álvaro', 'Mendez Alvaro', 'transfer'), s('Pacífico', 'Pacifico', 'transfer'),
      s('Conde de Casal'), s('Sainz de Baranda', undefined, 'transfer'),
      s('O’Donnell', 'O Donnell'), s('Manuel Becerra', undefined, 'transfer'),
      s('Diego de León', 'Diego de Leon', 'transfer'),
      s('Avenida de América', 'Avenida de America', 'transfer'),
      s('República Argentina', 'Republica Argentina'),
      s('Nuevos Ministerios', undefined, 'transfer'), s('Cuatro Caminos', undefined, 'transfer'),
      s('Guzmán el Bueno', 'Guzman el Bueno', 'transfer'), s('Vicente Aleixandre'),
      s('Ciudad Universitaria'), s('Moncloa', undefined, 'transfer'),
      s('Argüelles', 'Arguelles', 'transfer'), s('Príncipe Pío', 'Principe Pio', 'transfer'),
      s('Puerta del Ángel', 'Puerta del Angel'), s('Alto de Extremadura'), s('Lucero'),
    ],
    text: T(
      ['마드리드를 한 바퀴 도는 순환선입니다. 스물여덟 역 가운데 절반 넘게가 다른 노선과 만나는 환승역이라, 도심을 가로지르지 않고 돌아가는 데 씁니다.',
       '순환선이라 어디서 시작해도 됩니다. Moncloa·Nuevos Ministerios·Príncipe Pío 같은 큰 환승역부터 채워 보세요.'],
      ['The circle line of Madrid. More than half of its twenty-eight stations are interchanges, so it is the line you take to go round the centre rather than through it.',
       'It is a loop, so any starting point works. Begin with the big interchanges — Moncloa, Nuevos Ministerios, Príncipe Pío.'],
      ['La línea circular de Madrid. Más de la mitad de sus veintiocho estaciones son de correspondencia, así que sirve para rodear el centro en vez de atravesarlo.',
       'Es circular: da igual por dónde empieces. Ve a por los intercambiadores grandes: Moncloa, Nuevos Ministerios, Príncipe Pío.'],
      ['A linha circular de Madri. Mais de metade das suas vinte e oito estações são de baldeação, por isso serve para contornar o centro em vez de atravessá-lo.',
       'É circular: tanto faz por onde começar. Vá pelos grandes intercambiadores: Moncloa, Nuevos Ministerios, Príncipe Pío.'],
      ['マドリードを一周する環状線です。二十八駅の半分以上が乗換駅で、中心部を突っ切らずに回り込むために使われます。',
       '環状線なのでどこから始めても構いません。Moncloa・Nuevos Ministerios・Príncipe Pío といった大きな乗換駅から埋めましょう。'],
      ['Die Ringlinie von Madrid. Mehr als die Hälfte ihrer achtundzwanzig Stationen sind Umsteigebahnhöfe — man nimmt sie, um das Zentrum zu umfahren statt zu durchqueren.',
       'Es ist ein Ring, der Startpunkt ist egal. Fang mit den großen Umsteigepunkten an: Moncloa, Nuevos Ministerios, Príncipe Pío.'],
      ['La ligne circulaire de Madrid. Plus de la moitié de ses vingt-huit stations sont des correspondances : on la prend pour contourner le centre plutôt que le traverser.',
       'C’est une boucle, le point de départ importe peu. Commencez par les grands pôles : Moncloa, Nuevos Ministerios, Príncipe Pío.'],
      ['मैड्रिड की गोलाकार लाइन। इसके अट्ठाईस में से आधे से ज़्यादा स्टेशन इंटरचेंज हैं, इसलिए यह केंद्र को पार करने के बजाय उसके चारों ओर घूमने के काम आती है।',
       'यह लूप है, कहीं से भी शुरू करें। बड़े इंटरचेंज से शुरू करें — Moncloa, Nuevos Ministerios, Príncipe Pío।'],
      ['马德里的环线。二十八个站里有一半以上是换乘站，所以人们用它绕开市中心，而不是穿过去。',
       '既然是环线，从哪儿开始都行。先填 Moncloa、Nuevos Ministerios、Príncipe Pío 这些大换乘站。'],
      ['馬德里的環線。二十八個站裡有一半以上是換乘站，所以人們用它繞開市中心，而不是穿過去。',
       '既然是環線，從哪兒開始都行。先填 Moncloa、Nuevos Ministerios、Príncipe Pío 這些大換乘站。'],
    ),
  },
  {
    slug: 'hongkong-tsuen-wan', city: 'hongkong', color: '#e2231a',
    label: {
      ko: '췬완선', en: 'Tsuen Wan line', es: 'Línea Tsuen Wan', pt: 'Linha Tsuen Wan',
      ja: '荃湾線', de: 'Tsuen Wan Line', fr: 'Tsuen Wan line', hi: 'ट्सुएन वान लाइन',
      zh: '荃湾线', tw: '荃灣綫',
    },
    shape: ['SE', 'SE', 'SE', 'S', 'S', 'SE', 'SE', 'SE', 'S', 'S', 'SE', 'SE', 'S', 'S', 'SE'],
    stations: [
      sa('Tsuen Wan', '荃灣', 'terminus'), sa('Tai Wo Hau', '大窩口'), sa('Kwai Hing', '葵興'),
      sa('Kwai Fong', '葵芳'), sa('Lai King', '荔景', 'transfer'), sa('Mei Foo', '美孚', 'transfer'),
      sa('Lai Chi Kok', '荔枝角'), sa('Cheung Sha Wan', '長沙灣'), sa('Sham Shui Po', '深水埗'),
      sa('Prince Edward', '太子', 'transfer'), sa('Mong Kok', '旺角', 'transfer'),
      sa('Yau Ma Tei', '油麻地', 'transfer'), sa('Jordan', '佐敦'),
      sa('Tsim Sha Tsui', '尖沙咀', 'transfer'), sa('Admiralty', '金鐘', 'transfer'),
      sa('Central', '中環', 'terminus'),
    ],
    text: T(
      ['홍콩 신계의 췬완에서 카오룽을 지나 홍콩섬 센트럴까지 이어지는 열여섯 역짜리 노선입니다. 1979년에 개통한 홍콩 지하철의 첫 노선이 이 줄기입니다.',
       '영어와 한자를 모두 받습니다. 침사추이는 尖沙咀, 몽콕은 旺角입니다.'],
      ['Sixteen stations from Tsuen Wan in the New Territories, through Kowloon, to Central on Hong Kong Island. This alignment was the MTR’s first line when it opened in 1979.',
       'English and Chinese both count. Tsim Sha Tsui is 尖沙咀 and Mong Kok is 旺角.'],
      ['Dieciséis estaciones desde Tsuen Wan, en los Nuevos Territorios, cruzando Kowloon hasta Central, en la isla de Hong Kong. Este trazado fue la primera línea del MTR, en 1979.',
       'Valen el inglés y el chino. Tsim Sha Tsui es 尖沙咀 y Mong Kok es 旺角.'],
      ['Dezesseis estações desde Tsuen Wan, nos Novos Territórios, atravessando Kowloon até Central, na ilha de Hong Kong. Este traçado foi a primeira linha do MTR, em 1979.',
       'Valem o inglês e o chinês. Tsim Sha Tsui é 尖沙咀 e Mong Kok é 旺角.'],
      ['新界の荃湾から九龍を抜け、香港島の中環まで十六駅の路線です。1979年に開業した香港地下鉄の最初の路線がこの区間です。',
       '英語名と漢字名のどちらも正解です。尖沙咀は Tsim Sha Tsui、旺角は Mong Kok です。'],
      ['Sechzehn Stationen von Tsuen Wan in den New Territories durch Kowloon bis Central auf Hong Kong Island. Diese Strecke war 1979 die erste Linie der MTR.',
       'Englisch und Chinesisch zählen beide. Tsim Sha Tsui ist 尖沙咀, Mong Kok ist 旺角.'],
      ['Seize stations depuis Tsuen Wan, dans les Nouveaux Territoires, à travers Kowloon jusqu’à Central, sur l’île de Hong Kong. Ce tracé fut la première ligne du MTR, en 1979.',
       'L’anglais comme le chinois comptent. Tsim Sha Tsui s’écrit 尖沙咀 et Mong Kok 旺角.'],
      ['New Territories के Tsuen Wan से Kowloon होते हुए Hong Kong Island के Central तक सोलह स्टेशन। 1979 में खुला यही मार्ग MTR की पहली लाइन था।',
       'अंग्रेज़ी और चीनी दोनों चलते हैं। Tsim Sha Tsui यानी 尖沙咀 और Mong Kok यानी 旺角।'],
      ['从新界荃湾穿过九龙，到香港岛中环，共十六站。1979 年通车的这一段就是香港地铁的第一条线。',
       '英文名和中文名都算对。尖沙咀是 Tsim Sha Tsui，旺角是 Mong Kok。'],
      ['從新界荃灣穿過九龍，到香港島中環，共十六站。1979 年通車的這一段就是香港地鐵的第一條線。',
       '英文名和中文名都算對。尖沙咀是 Tsim Sha Tsui，旺角是 Mong Kok。'],
    ),
  },
  {
    slug: 'nyc-l', city: 'newyork', color: '#a7a9ac',
    label: {
      ko: 'L 트레인', en: 'L train', es: 'Línea L', pt: 'Linha L', ja: 'L系統',
      de: 'Linie L', fr: 'Ligne L', hi: 'लाइन L', zh: 'L线', tw: 'L線', 
    },
    shape: ['E', 'E', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE', 'SE', 'SE', 'SE', 'E', 'E', 'E', 'E', 'SE', 'SE', 'SE', 'SE', 'S', 'S', 'S'],
    stations: [
      s('Eighth Avenue', undefined, 'terminus'), s('Sixth Avenue', undefined, 'transfer'),
      s('Union Square', undefined, 'transfer'), s('Third Avenue'), s('First Avenue'),
      s('Bedford Avenue'), s('Lorimer Street', undefined, 'transfer'), s('Graham Avenue'),
      s('Grand Street'), s('Montrose Avenue'), s('Morgan Avenue'), s('Jefferson Street'),
      s('DeKalb Avenue'), s('Myrtle–Wyckoff Avenues', 'Myrtle Wyckoff Avenues', 'transfer'),
      s('Halsey Street'), s('Wilson Avenue'),
      s('Bushwick Avenue–Aberdeen Street', 'Bushwick Avenue Aberdeen Street'),
      s('Broadway Junction', undefined, 'transfer'), s('Atlantic Avenue'), s('Sutter Avenue'),
      s('Livonia Avenue'), s('New Lots Avenue'), s('East 105th Street'),
      s('Canarsie–Rockaway Parkway', 'Canarsie Rockaway Parkway', 'terminus'),
    ],
    text: T(
      ['맨해튼 14번가를 가로질러 브루클린 카나시까지 가는 노선입니다. 뉴욕 지하철에서 드물게 다른 노선과 선로를 하나도 나눠 쓰지 않아, 일찍부터 자동운전 신호를 넣을 수 있었습니다.',
       '이스트강 밑을 지나면 브루클린입니다. Bedford Avenue가 강 건너 첫 역입니다.'],
      ['Across 14th Street in Manhattan and out to Canarsie in Brooklyn. It is one of the few New York routes that shares no track with any other service, which is why it got automatic train signalling early.',
       'Bedford Avenue is the first stop after the East River tunnel — everything past it is Brooklyn.'],
      ['Cruza la calle 14 de Manhattan y sigue hasta Canarsie, en Brooklyn. Es de las pocas líneas de Nueva York que no comparte vía con ninguna otra, y por eso fue de las primeras en señalización automática.',
       'Bedford Avenue es la primera parada tras el túnel del East River: de ahí en adelante es Brooklyn.'],
      ['Atravessa a rua 14 em Manhattan e segue até Canarsie, no Brooklyn. É das poucas linhas de Nova York que não divide via com nenhuma outra, e por isso teve sinalização automática cedo.',
       'Bedford Avenue é a primeira parada depois do túnel do East River: dali em diante é Brooklyn.'],
      ['マンハッタンの14丁目を横断し、ブルックリンのカナーシーまで走ります。他系統と線路を一切共有しない数少ない路線で、そのため早くから自動運転信号が入りました。',
       'イーストリバーのトンネルを抜けた最初の駅が Bedford Avenue です。そこから先はブルックリンです。'],
      ['Quer über die 14th Street in Manhattan und weiter bis Canarsie in Brooklyn. Sie teilt sich mit keiner anderen Linie ein Gleis — deshalb bekam sie früh automatische Zugsicherung.',
       'Bedford Avenue ist die erste Station nach dem East-River-Tunnel; alles danach liegt in Brooklyn.'],
      ['Elle traverse la 14e rue à Manhattan et file jusqu’à Canarsie, à Brooklyn. C’est l’une des rares lignes new-yorkaises à ne partager aucune voie, d’où sa signalisation automatique précoce.',
       'Bedford Avenue est le premier arrêt après le tunnel de l’East River : au-delà, on est à Brooklyn.'],
      ['मैनहट्टन की 14th Street को पार करके ब्रुकलिन के Canarsie तक। यह न्यूयॉर्क की उन गिनी-चुनी लाइनों में है जो किसी और सेवा से पटरी साझा नहीं करती, इसलिए यहाँ स्वचालित सिग्नल जल्दी आए।',
       'East River सुरंग के बाद पहला स्टॉप Bedford Avenue है — उसके आगे सब ब्रुकलिन है।'],
      ['横穿曼哈顿 14 街，一直开到布鲁克林的卡纳西。它是纽约地铁少数不与其他线路共用轨道的线，因此很早就装上了自动信号。',
       '过了东河隧道的第一站是 Bedford Avenue，往后都是布鲁克林。'],
      ['橫穿曼哈頓 14 街，一直開到布魯克林的卡納西。它是紐約地鐵少數不與其他路線共用軌道的線，因此很早就裝上了自動號誌。',
       '過了東河隧道的第一站是 Bedford Avenue，往後都是布魯克林。'],
    ),
  },
  {
    slug: 'chicago-orange', city: 'chicago', color: '#f9461c',
    label: {
      ko: '오렌지 라인', en: 'Orange Line', es: 'Línea Naranja', pt: 'Linha Laranja',
      ja: 'オレンジライン', de: 'Orange Line', fr: 'Ligne orange', hi: 'ऑरेंज लाइन',
      zh: '橙线', tw: '橘線',
    },
    shape: ['NE', 'NE', 'NE', 'NE', 'NE', 'NE', 'NE', 'NE', 'NE', 'N', 'N', 'E', 'E'],
    stations: [
      s('Midway', undefined, 'terminus'), s('Pulaski'), s('Kedzie'), s('Western'),
      s('35th/Archer', '35th Archer'), s('Ashland'), s('Halsted'),
      s('Roosevelt', undefined, 'transfer'), s('Harold Washington Library', undefined, 'transfer'),
      s('LaSalle/Van Buren', 'LaSalle Van Buren'), s('Quincy'),
      s('Washington/Wells', 'Washington Wells', 'transfer'),
      s('Clark/Lake', 'Clark Lake', 'transfer'),
      s('Washington/Wabash', 'Washington Wabash', 'terminus'),
    ],
    text: T(
      ['미드웨이 공항과 시내 루프를 잇는 노선입니다. 루프에 들어가면 고가를 따라 시계 방향으로 한 바퀴 돌고 다시 공항으로 돌아갑니다.',
       '빗금은 없는 셈 치고 붙여 써도 됩니다. Clark/Lake는 Clark Lake로도 정답입니다.'],
      ['The line between Midway airport and the downtown Loop. Once it reaches the Loop it runs clockwise round the elevated tracks and heads back to the airport.',
       'Slashes can be dropped. Clark/Lake also counts as Clark Lake.'],
      ['La línea entre el aeropuerto de Midway y el Loop del centro. Al llegar al Loop da una vuelta en sentido horario por el elevado y vuelve al aeropuerto.',
       'Puedes omitir las barras: Clark/Lake vale también como Clark Lake.'],
      ['A linha entre o aeroporto de Midway e o Loop do centro. Ao chegar ao Loop dá uma volta no sentido horário pelo elevado e volta ao aeroporto.',
       'Pode omitir as barras: Clark/Lake vale também como Clark Lake.'],
      ['ミッドウェー空港と都心のループを結ぶ路線です。ループに入ると高架を時計回りに一周し、また空港へ戻ります。',
       'スラッシュは省いても構いません。Clark/Lake は Clark Lake でも正解です。'],
      ['Die Linie zwischen dem Flughafen Midway und dem Loop in der Innenstadt. Im Loop fährt sie im Uhrzeigersinn einmal über die Hochbahn und dann zurück zum Flughafen.',
       'Schrägstriche darf man weglassen. Clark/Lake zählt auch als Clark Lake.'],
      ['La ligne entre l’aéroport de Midway et le Loop, au centre-ville. Arrivée au Loop, elle en fait le tour dans le sens horaire sur l’aérien puis repart vers l’aéroport.',
       'Les barres obliques peuvent sauter : Clark/Lake compte aussi comme Clark Lake.'],
      ['Midway हवाई अड्डे और डाउनटाउन Loop के बीच की लाइन। Loop पहुँचकर यह एलिवेटेड पटरी पर दक्षिणावर्त एक चक्कर लगाती है और फिर हवाई अड्डे लौट जाती है।',
       'स्लैश छोड़ सकते हैं। Clark/Lake को Clark Lake लिखना भी चलता है।'],
      ['连接中途机场和市中心环线的线路。进了环线之后沿高架顺时针绕一圈，再开回机场。',
       '斜杠可以不打。Clark/Lake 写成 Clark Lake 也算对。'],
      ['連接中途機場和市中心環線的路線。進了環線之後沿高架順時針繞一圈，再開回機場。',
       '斜線可以不打。Clark/Lake 寫成 Clark Lake 也算對。'],
    ),
  },
];
