/* 생성됨(gen.mjs) — 접힌 국제 라우트의 **메타 전용** 등록부.
 *
 * registry.ts(뷰)와 갈라 놓는 것이 요점이다. 서버 모듈 그래프가 pages/*.tsx에
 * 닿기만 하면 — 그리지 않아도 — Turbopack이 그 라우트의 클라이언트 청크를 도로
 * 하나로 합친다. 그래서 서버는 여기(*.meta)만 보고, 뷰는 components/FoldView.tsx가
 * 클라이언트에서 부른다.
 *
 * 두 등록부가 어긋나면 그 갈래가 조용히 죽는다 — tests/fold-routes.test.ts가 대조한다.
 */
import type { Metadata } from 'next';
import type { FoldLang } from './lang';

export type HubMeta = () => Promise<{ buildMeta: (lang: FoldLang) => { metadata: Metadata } }>;
type SlugBuilt = {
  generateMetadata: (a: { params: Promise<never> }) => Promise<Metadata>;
  generateStaticParams: () => Record<string, string>[];
};
export type SlugMeta = () => Promise<{ buildMeta: (lang: FoldLang) => SlugBuilt }>;

export const STATIC_META: Record<string, HubMeta> = {
  '': () => import('./pages/home.meta'),
  'ascii': () => import('./pages/ascii.meta'),
  'body': () => import('./pages/body.meta'),
  'calculator': () => import('./pages/calculator.meta'),
  'checklist': () => import('./pages/checklist.meta'),
  'chmod': () => import('./pages/chmod.meta'),
  'cidr': () => import('./pages/cidr.meta'),
  'cmd': () => import('./pages/cmd.meta'),
  'code': () => import('./pages/code.meta'),
  'color': () => import('./pages/color.meta'),
  'color/colorblind': () => import('./pages/color__colorblind.meta'),
  'color/contrast': () => import('./pages/color__contrast.meta'),
  'color/gradient': () => import('./pages/color__gradient.meta'),
  'color/mixer': () => import('./pages/color__mixer.meta'),
  'color/name': () => import('./pages/color__name.meta'),
  'color/palette': () => import('./pages/color__palette.meta'),
  'color/random': () => import('./pages/color__random.meta'),
  'color/shades': () => import('./pages/color__shades.meta'),
  'color/shadow': () => import('./pages/color__shadow.meta'),
  'color/temperature': () => import('./pages/color__temperature.meta'),
  'convert': () => import('./pages/convert.meta'),
  'craft': () => import('./pages/craft.meta'),
  'device': () => import('./pages/device.meta'),
  'device/gamepad': () => import('./pages/device__gamepad.meta'),
  'device/info': () => import('./pages/device__info.meta'),
  'device/keyboard': () => import('./pages/device__keyboard.meta'),
  'device/mic': () => import('./pages/device__mic.meta'),
  'device/monitor': () => import('./pages/device__monitor.meta'),
  'device/mouse': () => import('./pages/device__mouse.meta'),
  'device/refresh-rate': () => import('./pages/device__refresh-rate.meta'),
  'device/screen': () => import('./pages/device__screen.meta'),
  'device/speaker': () => import('./pages/device__speaker.meta'),
  'device/touch': () => import('./pages/device__touch.meta'),
  'device/webcam': () => import('./pages/device__webcam.meta'),
  'emoji': () => import('./pages/emoji.meta'),
  'ext': () => import('./pages/ext.meta'),
  'food': () => import('./pages/food.meta'),
  'food/baking-pan': () => import('./pages/food__baking-pan.meta'),
  'food/coffee': () => import('./pages/food__coffee.meta'),
  'food/measure': () => import('./pages/food__measure.meta'),
  'food/oven': () => import('./pages/food__oven.meta'),
  'food/pasta': () => import('./pages/food__pasta.meta'),
  'food/recipe-scale': () => import('./pages/food__recipe-scale.meta'),
  'food/rice': () => import('./pages/food__rice.meta'),
  'food/salt': () => import('./pages/food__salt.meta'),
  'food/steak': () => import('./pages/food__steak.meta'),
  'food/storage': () => import('./pages/food__storage.meta'),
  'fortune': () => import('./pages/fortune.meta'),
  'fortune/animal': () => import('./pages/fortune__animal.meta'),
  'fortune/biorhythm': () => import('./pages/fortune__biorhythm.meta'),
  'fortune/birth-stone': () => import('./pages/fortune__birth-stone.meta'),
  'fortune/blood-match': () => import('./pages/fortune__blood-match.meta'),
  'fortune/blood-type': () => import('./pages/fortune__blood-type.meta'),
  'fortune/card': () => import('./pages/fortune__card.meta'),
  'fortune/daily': () => import('./pages/fortune__daily.meta'),
  'fortune/daily-tarot': () => import('./pages/fortune__daily-tarot.meta'),
  'fortune/dream': () => import('./pages/fortune__dream.meta'),
  'fortune/lucky-numbers': () => import('./pages/fortune__lucky-numbers.meta'),
  'fortune/mbti': () => import('./pages/fortune__mbti.meta'),
  'fortune/mbti-match': () => import('./pages/fortune__mbti-match.meta'),
  'fortune/saju': () => import('./pages/fortune__saju.meta'),
  'fortune/star-match': () => import('./pages/fortune__star-match.meta'),
  'fortune/tarot': () => import('./pages/fortune__tarot.meta'),
  'fortune/tarot-yesno': () => import('./pages/fortune__tarot-yesno.meta'),
  'fortune/today-color': () => import('./pages/fortune__today-color.meta'),
  'fortune/zodiac': () => import('./pages/fortune__zodiac.meta'),
  'fortune/zodiac-match': () => import('./pages/fortune__zodiac-match.meta'),
  'fraction': () => import('./pages/fraction.meta'),
  'game': () => import('./pages/game.meta'),
  'game/2048': () => import('./pages/game__2048.meta'),
  'game/aim': () => import('./pages/game__aim.meta'),
  'game/beat': () => import('./pages/game__beat.meta'),
  'game/chess': () => import('./pages/game__chess.meta'),
  'game/color-blind': () => import('./pages/game__color-blind.meta'),
  'game/cps': () => import('./pages/game__cps.meta'),
  'game/cube': () => import('./pages/game__cube.meta'),
  'game/dot-count': () => import('./pages/game__dot-count.meta'),
  'game/hearing': () => import('./pages/game__hearing.meta'),
  'game/math': () => import('./pages/game__math.meta'),
  'game/memory': () => import('./pages/game__memory.meta'),
  'game/minesweeper': () => import('./pages/game__minesweeper.meta'),
  'game/nback': () => import('./pages/game__nback.meta'),
  'game/number-memory': () => import('./pages/game__number-memory.meta'),
  'game/peripheral': () => import('./pages/game__peripheral.meta'),
  'game/poker': () => import('./pages/game__poker.meta'),
  'game/reaction': () => import('./pages/game__reaction.meta'),
  'game/rotation': () => import('./pages/game__rotation.meta'),
  'game/sequence': () => import('./pages/game__sequence.meta'),
  'game/sliding': () => import('./pages/game__sliding.meta'),
  'game/stroop': () => import('./pages/game__stroop.meta'),
  'game/sudoku': () => import('./pages/game__sudoku.meta'),
  'game/typing': () => import('./pages/game__typing.meta'),
  'generator': () => import('./pages/generator.meta'),
  'geometry': () => import('./pages/geometry.meta'),
  'hanja': () => import('./pages/hanja.meta'),
  'holidays': () => import('./pages/holidays.meta'),
  'http': () => import('./pages/http.meta'),
  'image': () => import('./pages/image.meta'),
  'image/adjust': () => import('./pages/image__adjust.meta'),
  'image/compress': () => import('./pages/image__compress.meta'),
  'image/convert': () => import('./pages/image__convert.meta'),
  'image/crop': () => import('./pages/image__crop.meta'),
  'image/favicon': () => import('./pages/image__favicon.meta'),
  'image/frame': () => import('./pages/image__frame.meta'),
  'image/merge': () => import('./pages/image__merge.meta'),
  'image/mosaic': () => import('./pages/image__mosaic.meta'),
  'image/palette': () => import('./pages/image__palette.meta'),
  'image/resize': () => import('./pages/image__resize.meta'),
  'image/rotate': () => import('./pages/image__rotate.meta'),
  'image/round': () => import('./pages/image__round.meta'),
  'image/size': () => import('./pages/image__size.meta'),
  'image/split': () => import('./pages/image__split.meta'),
  'image/watermark': () => import('./pages/image__watermark.meta'),
  'keycode': () => import('./pages/keycode.meta'),
  'number': () => import('./pages/number.meta'),
  'password': () => import('./pages/password.meta'),
  'percent': () => import('./pages/percent.meta'),
  'port': () => import('./pages/port.meta'),
  'quiz': () => import('./pages/quiz.meta'),
  'random': () => import('./pages/random.meta'),
  'random/dice': () => import('./pages/random__dice.meta'),
  'rate': () => import('./pages/rate.meta'),
  'rem': () => import('./pages/rem.meta'),
  'roman': () => import('./pages/roman.meta'),
  'search': () => import('./pages/search.meta'),
  'shortcut': () => import('./pages/shortcut.meta'),
  'snap': () => import('./pages/snap.meta'),
  'snap/animal-face': () => import('./pages/snap__animal-face.meta'),
  'snap/backdrop': () => import('./pages/snap__backdrop.meta'),
  'snap/brows': () => import('./pages/snap__brows.meta'),
  'snap/contrast': () => import('./pages/snap__contrast.meta'),
  'snap/couple-match': () => import('./pages/snap__couple-match.meta'),
  'snap/distance': () => import('./pages/snap__distance.meta'),
  'snap/expression': () => import('./pages/snap__expression.meta'),
  'snap/eye-open': () => import('./pages/snap__eye-open.meta'),
  'snap/eye-spacing': () => import('./pages/snap__eye-spacing.meta'),
  'snap/face-reading': () => import('./pages/snap__face-reading.meta'),
  'snap/face-shape': () => import('./pages/snap__face-shape.meta'),
  'snap/face-symmetry': () => import('./pages/snap__face-symmetry.meta'),
  'snap/face-thirds': () => import('./pages/snap__face-thirds.meta'),
  'snap/first-impression': () => import('./pages/snap__first-impression.meta'),
  'snap/framing': () => import('./pages/snap__framing.meta'),
  'snap/golden-ratio': () => import('./pages/snap__golden-ratio.meta'),
  'snap/handwriting': () => import('./pages/snap__handwriting.meta'),
  'snap/head-pose': () => import('./pages/snap__head-pose.meta'),
  'snap/id-photo': () => import('./pages/snap__id-photo.meta'),
  'snap/lens': () => import('./pages/snap__lens.meta'),
  'snap/lighting': () => import('./pages/snap__lighting.meta'),
  'snap/lips': () => import('./pages/snap__lips.meta'),
  'snap/mirror': () => import('./pages/snap__mirror.meta'),
  'snap/personal-color': () => import('./pages/snap__personal-color.meta'),
  'snap/photo-mood': () => import('./pages/snap__photo-mood.meta'),
  'snap/real-smile': () => import('./pages/snap__real-smile.meta'),
  'snap/sharpness': () => import('./pages/snap__sharpness.meta'),
  'snap/smile-score': () => import('./pages/snap__smile-score.meta'),
  'snap/white-balance': () => import('./pages/snap__white-balance.meta'),
  'sound': () => import('./pages/sound.meta'),
  'sound/binaural': () => import('./pages/sound__binaural.meta'),
  'sound/bpm-tap': () => import('./pages/sound__bpm-tap.meta'),
  'sound/decibel': () => import('./pages/sound__decibel.meta'),
  'sound/hz': () => import('./pages/sound__hz.meta'),
  'sound/metronome': () => import('./pages/sound__metronome.meta'),
  'sound/mosquito': () => import('./pages/sound__mosquito.meta'),
  'sound/noise': () => import('./pages/sound__noise.meta'),
  'sound/pitch': () => import('./pages/sound__pitch.meta'),
  'sound/recorder': () => import('./pages/sound__recorder.meta'),
  'sound/tone': () => import('./pages/sound__tone.meta'),
  'sound/tuner': () => import('./pages/sound__tuner.meta'),
  'sqrt': () => import('./pages/sqrt.meta'),
  'test': () => import('./pages/test.meta'),
  'text': () => import('./pages/text.meta'),
  'text/char': () => import('./pages/text__char.meta'),
  'text/case': () => import('./pages/text__case.meta'),
  'text/clean': () => import('./pages/text__clean.meta'),
  'text/dedupe': () => import('./pages/text__dedupe.meta'),
  'text/emoticon': () => import('./pages/text__emoticon.meta'),
  'text/lorem': () => import('./pages/text__lorem.meta'),
  'text/manuscript': () => import('./pages/text__manuscript.meta'),
  'text/mask': () => import('./pages/text__mask.meta'),
  'text/qr': () => import('./pages/text__qr.meta'),
  'text/regex': () => import('./pages/text__regex.meta'),
  'text/replace': () => import('./pages/text__replace.meta'),
  'text/reverse': () => import('./pages/text__reverse.meta'),
  'text/slug': () => import('./pages/text__slug.meta'),
  'text/special-char': () => import('./pages/text__special-char.meta'),
  'text/table': () => import('./pages/text__table.meta'),
  'text/vertical': () => import('./pages/text__vertical.meta'),
  'text/wrap': () => import('./pages/text__wrap.meta'),
  'time': () => import('./pages/time.meta'),
  'time/alarm': () => import('./pages/time__alarm.meta'),
  'time/date-add': () => import('./pages/time__date-add.meta'),
  'time/lived': () => import('./pages/time__lived.meta'),
  'time/pomodoro': () => import('./pages/time__pomodoro.meta'),
  'time/stopwatch': () => import('./pages/time__stopwatch.meta'),
  'time/timer': () => import('./pages/time__timer.meta'),
  'time/timezone': () => import('./pages/time__timezone.meta'),
  'time/weeknumber': () => import('./pages/time__weeknumber.meta'),
  'time/workdays': () => import('./pages/time__workdays.meta'),
  'time/worldclock': () => import('./pages/time__worldclock.meta'),
  'times': () => import('./pages/times.meta'),
  'year': () => import('./pages/year.meta'),
};

export const EN_STATIC_META: Record<string, HubMeta> = {
  'generator': () => import('./pages/generator__en.meta'),
};

/* 세 칸 낱장 — [a]/[b]/[slug]가 받는다 */
export const DEEP_META: Record<string, SlugMeta> = {
  'body/exercise': () => import('./pages/body__exercise__slug.meta'),
  'device/screen': () => import('./pages/device__screen__slug.meta'),
  'fortune/card': () => import('./pages/fortune__card__slug.meta'),
  'fortune/saju': () => import('./pages/fortune__saju__slug.meta'),
  'game/chess': () => import('./pages/game__chess__slug.meta'),
  'game/cube': () => import('./pages/game__cube__slug.meta'),
  'game/poker': () => import('./pages/game__poker__slug.meta'),
  'image/size': () => import('./pages/image__size__slug.meta'),
  'snap/lens': () => import('./pages/snap__lens__slug.meta'),
  'sound/hz': () => import('./pages/sound__hz__slug.meta'),
  'text/regex': () => import('./pages/text__regex__slug.meta'),
};

/* 뷰 디스패처에 넘길 이름표 — 문자열뿐이라 모듈 그래프를 안 끈다 */
export const STATIC_MODULE: Record<string, string> = {
  '': 'home',
  'ascii': 'ascii',
  'body': 'body',
  'calculator': 'calculator',
  'checklist': 'checklist',
  'chmod': 'chmod',
  'cidr': 'cidr',
  'cmd': 'cmd',
  'code': 'code',
  'color': 'color',
  'color/colorblind': 'color__colorblind',
  'color/contrast': 'color__contrast',
  'color/gradient': 'color__gradient',
  'color/mixer': 'color__mixer',
  'color/name': 'color__name',
  'color/palette': 'color__palette',
  'color/random': 'color__random',
  'color/shades': 'color__shades',
  'color/shadow': 'color__shadow',
  'color/temperature': 'color__temperature',
  'convert': 'convert',
  'craft': 'craft',
  'device': 'device',
  'device/gamepad': 'device__gamepad',
  'device/info': 'device__info',
  'device/keyboard': 'device__keyboard',
  'device/mic': 'device__mic',
  'device/monitor': 'device__monitor',
  'device/mouse': 'device__mouse',
  'device/refresh-rate': 'device__refresh-rate',
  'device/screen': 'device__screen',
  'device/speaker': 'device__speaker',
  'device/touch': 'device__touch',
  'device/webcam': 'device__webcam',
  'emoji': 'emoji',
  'ext': 'ext',
  'food': 'food',
  'food/baking-pan': 'food__baking-pan',
  'food/coffee': 'food__coffee',
  'food/measure': 'food__measure',
  'food/oven': 'food__oven',
  'food/pasta': 'food__pasta',
  'food/recipe-scale': 'food__recipe-scale',
  'food/rice': 'food__rice',
  'food/salt': 'food__salt',
  'food/steak': 'food__steak',
  'food/storage': 'food__storage',
  'fortune': 'fortune',
  'fortune/animal': 'fortune__animal',
  'fortune/biorhythm': 'fortune__biorhythm',
  'fortune/birth-stone': 'fortune__birth-stone',
  'fortune/blood-match': 'fortune__blood-match',
  'fortune/blood-type': 'fortune__blood-type',
  'fortune/card': 'fortune__card',
  'fortune/daily': 'fortune__daily',
  'fortune/daily-tarot': 'fortune__daily-tarot',
  'fortune/dream': 'fortune__dream',
  'fortune/lucky-numbers': 'fortune__lucky-numbers',
  'fortune/mbti': 'fortune__mbti',
  'fortune/mbti-match': 'fortune__mbti-match',
  'fortune/saju': 'fortune__saju',
  'fortune/star-match': 'fortune__star-match',
  'fortune/tarot': 'fortune__tarot',
  'fortune/tarot-yesno': 'fortune__tarot-yesno',
  'fortune/today-color': 'fortune__today-color',
  'fortune/zodiac': 'fortune__zodiac',
  'fortune/zodiac-match': 'fortune__zodiac-match',
  'fraction': 'fraction',
  'game': 'game',
  'game/2048': 'game__2048',
  'game/aim': 'game__aim',
  'game/beat': 'game__beat',
  'game/chess': 'game__chess',
  'game/color-blind': 'game__color-blind',
  'game/cps': 'game__cps',
  'game/cube': 'game__cube',
  'game/dot-count': 'game__dot-count',
  'game/hearing': 'game__hearing',
  'game/math': 'game__math',
  'game/memory': 'game__memory',
  'game/minesweeper': 'game__minesweeper',
  'game/nback': 'game__nback',
  'game/number-memory': 'game__number-memory',
  'game/peripheral': 'game__peripheral',
  'game/poker': 'game__poker',
  'game/reaction': 'game__reaction',
  'game/rotation': 'game__rotation',
  'game/sequence': 'game__sequence',
  'game/sliding': 'game__sliding',
  'game/stroop': 'game__stroop',
  'game/sudoku': 'game__sudoku',
  'game/typing': 'game__typing',
  'generator': 'generator',
  'geometry': 'geometry',
  'hanja': 'hanja',
  'holidays': 'holidays',
  'http': 'http',
  'image': 'image',
  'image/adjust': 'image__adjust',
  'image/compress': 'image__compress',
  'image/convert': 'image__convert',
  'image/crop': 'image__crop',
  'image/favicon': 'image__favicon',
  'image/frame': 'image__frame',
  'image/merge': 'image__merge',
  'image/mosaic': 'image__mosaic',
  'image/palette': 'image__palette',
  'image/resize': 'image__resize',
  'image/rotate': 'image__rotate',
  'image/round': 'image__round',
  'image/size': 'image__size',
  'image/split': 'image__split',
  'image/watermark': 'image__watermark',
  'keycode': 'keycode',
  'number': 'number',
  'password': 'password',
  'percent': 'percent',
  'port': 'port',
  'quiz': 'quiz',
  'random': 'random',
  'random/dice': 'random__dice',
  'rate': 'rate',
  'rem': 'rem',
  'roman': 'roman',
  'search': 'search',
  'shortcut': 'shortcut',
  'snap': 'snap',
  'snap/animal-face': 'snap__animal-face',
  'snap/backdrop': 'snap__backdrop',
  'snap/brows': 'snap__brows',
  'snap/contrast': 'snap__contrast',
  'snap/couple-match': 'snap__couple-match',
  'snap/distance': 'snap__distance',
  'snap/expression': 'snap__expression',
  'snap/eye-open': 'snap__eye-open',
  'snap/eye-spacing': 'snap__eye-spacing',
  'snap/face-reading': 'snap__face-reading',
  'snap/face-shape': 'snap__face-shape',
  'snap/face-symmetry': 'snap__face-symmetry',
  'snap/face-thirds': 'snap__face-thirds',
  'snap/first-impression': 'snap__first-impression',
  'snap/framing': 'snap__framing',
  'snap/golden-ratio': 'snap__golden-ratio',
  'snap/handwriting': 'snap__handwriting',
  'snap/head-pose': 'snap__head-pose',
  'snap/id-photo': 'snap__id-photo',
  'snap/lens': 'snap__lens',
  'snap/lighting': 'snap__lighting',
  'snap/lips': 'snap__lips',
  'snap/mirror': 'snap__mirror',
  'snap/personal-color': 'snap__personal-color',
  'snap/photo-mood': 'snap__photo-mood',
  'snap/real-smile': 'snap__real-smile',
  'snap/sharpness': 'snap__sharpness',
  'snap/smile-score': 'snap__smile-score',
  'snap/white-balance': 'snap__white-balance',
  'sound': 'sound',
  'sound/binaural': 'sound__binaural',
  'sound/bpm-tap': 'sound__bpm-tap',
  'sound/decibel': 'sound__decibel',
  'sound/hz': 'sound__hz',
  'sound/metronome': 'sound__metronome',
  'sound/mosquito': 'sound__mosquito',
  'sound/noise': 'sound__noise',
  'sound/pitch': 'sound__pitch',
  'sound/recorder': 'sound__recorder',
  'sound/tone': 'sound__tone',
  'sound/tuner': 'sound__tuner',
  'sqrt': 'sqrt',
  'test': 'test',
  'text': 'text',
  'text/char': 'text__char',
  'text/case': 'text__case',
  'text/clean': 'text__clean',
  'text/dedupe': 'text__dedupe',
  'text/emoticon': 'text__emoticon',
  'text/lorem': 'text__lorem',
  'text/manuscript': 'text__manuscript',
  'text/mask': 'text__mask',
  'text/qr': 'text__qr',
  'text/regex': 'text__regex',
  'text/replace': 'text__replace',
  'text/reverse': 'text__reverse',
  'text/slug': 'text__slug',
  'text/special-char': 'text__special-char',
  'text/table': 'text__table',
  'text/vertical': 'text__vertical',
  'text/wrap': 'text__wrap',
  'time': 'time',
  'time/alarm': 'time__alarm',
  'time/date-add': 'time__date-add',
  'time/lived': 'time__lived',
  'time/pomodoro': 'time__pomodoro',
  'time/stopwatch': 'time__stopwatch',
  'time/timer': 'time__timer',
  'time/timezone': 'time__timezone',
  'time/weeknumber': 'time__weeknumber',
  'time/workdays': 'time__workdays',
  'time/worldclock': 'time__worldclock',
  'times': 'times',
  'year': 'year',
};

export const EN_STATIC_MODULE: Record<string, string> = {
  'generator': 'generator__en',
};

export const DEEP_MODULE: Record<string, string> = {
  'body/exercise': 'body__exercise__slug',
  'device/screen': 'device__screen__slug',
  'fortune/card': 'fortune__card__slug',
  'fortune/saju': 'fortune__saju__slug',
  'game/chess': 'game__chess__slug',
  'game/cube': 'game__cube__slug',
  'game/poker': 'game__poker__slug',
  'image/size': 'image__size__slug',
  'snap/lens': 'snap__lens__slug',
  'sound/hz': 'sound__hz__slug',
  'text/regex': 'text__regex__slug',
};

export const STATIC_KEYS: string[] = Object.keys(STATIC_META);
