/**
 * 원소 이름 118개 — 열 언어.
 *
 * 기호(H, Fe, Au)는 어느 나라에서나 같지만 이름은 다르다. 독일어는 산소를
 * Sauerstoff, 일본어는 酸素, 한국어는 산소라 부른다. 라틴어 뿌리를 그대로
 * 옮긴 언어(스페인어·포르투갈어·프랑스어)도 어미가 제각각이라 규칙으로
 * 만들 수 없어, 한 줄씩 적는다.
 *
 * 중국어는 원소마다 글자를 하나씩 새로 만들어 쓴다 — 금속에는 쇠 금 변, 기체에는
 * 기운 기 몸이 붙는다. 그래서 간체와 번체가 갈리는 자리가 많다(铁/鐵, 钠/鈉).
 * 규소만은 낱말 자체가 달라 대륙은 硅, 대만은 矽라고 한다.
 *
 * 104번부터는 두 벌이 같다. 초중원소의 이름은 2017년 이후에 정해져 간체·번체를
 * 나누기 전에 한 글자로 확정됐고, 확장 한자 영역이라 글꼴에 따라 네모로 보일 수 있다.
 */
import { type Lang } from '../i18n/lang.ts';

/** ko·en·es·pt·ja·de·fr·hi·zh·tw 열 칸 */
export type Ten = [string, string, string, string, string, string, string, string, string, string];

export const NAMES: Record<number, Ten> = {
  1: ['수소', 'Hydrogen', 'Hidrógeno', 'Hidrogênio', '水素', 'Wasserstoff', 'Hydrogène', 'हाइड्रोजन', '氢', '氫'],
  2: ['헬륨', 'Helium', 'Helio', 'Hélio', 'ヘリウム', 'Helium', 'Hélium', 'हीलियम', '氦', '氦'],
  3: ['리튬', 'Lithium', 'Litio', 'Lítio', 'リチウム', 'Lithium', 'Lithium', 'लिथियम', '锂', '鋰'],
  4: ['베릴륨', 'Beryllium', 'Berilio', 'Berílio', 'ベリリウム', 'Beryllium', 'Béryllium', 'बेरिलियम', '铍', '鈹'],
  5: ['붕소', 'Boron', 'Boro', 'Boro', 'ホウ素', 'Bor', 'Bore', 'बोरॉन', '硼', '硼'],
  6: ['탄소', 'Carbon', 'Carbono', 'Carbono', '炭素', 'Kohlenstoff', 'Carbone', 'कार्बन', '碳', '碳'],
  7: ['질소', 'Nitrogen', 'Nitrógeno', 'Nitrogênio', '窒素', 'Stickstoff', 'Azote', 'नाइट्रोजन', '氮', '氮'],
  8: ['산소', 'Oxygen', 'Oxígeno', 'Oxigênio', '酸素', 'Sauerstoff', 'Oxygène', 'ऑक्सीजन', '氧', '氧'],
  9: ['플루오린', 'Fluorine', 'Flúor', 'Flúor', 'フッ素', 'Fluor', 'Fluor', 'फ़्लोरीन', '氟', '氟'],
  10: ['네온', 'Neon', 'Neón', 'Neônio', 'ネオン', 'Neon', 'Néon', 'नियॉन', '氖', '氖'],
  11: ['소듐', 'Sodium', 'Sodio', 'Sódio', 'ナトリウム', 'Natrium', 'Sodium', 'सोडियम', '钠', '鈉'],
  12: ['마그네슘', 'Magnesium', 'Magnesio', 'Magnésio', 'マグネシウム', 'Magnesium', 'Magnésium', 'मैग्नीशियम', '镁', '鎂'],
  13: ['알루미늄', 'Aluminium', 'Aluminio', 'Alumínio', 'アルミニウム', 'Aluminium', 'Aluminium', 'ऐलुमिनियम', '铝', '鋁'],
  14: ['규소', 'Silicon', 'Silicio', 'Silício', 'ケイ素', 'Silicium', 'Silicium', 'सिलिकॉन', '硅', '矽'],
  15: ['인', 'Phosphorus', 'Fósforo', 'Fósforo', 'リン', 'Phosphor', 'Phosphore', 'फ़ॉस्फ़ोरस', '磷', '磷'],
  16: ['황', 'Sulfur', 'Azufre', 'Enxofre', '硫黄', 'Schwefel', 'Soufre', 'सल्फ़र', '硫', '硫'],
  17: ['염소', 'Chlorine', 'Cloro', 'Cloro', '塩素', 'Chlor', 'Chlore', 'क्लोरीन', '氯', '氯'],
  18: ['아르곤', 'Argon', 'Argón', 'Argônio', 'アルゴン', 'Argon', 'Argon', 'आर्गन', '氩', '氬'],
  19: ['포타슘', 'Potassium', 'Potasio', 'Potássio', 'カリウム', 'Kalium', 'Potassium', 'पोटैशियम', '钾', '鉀'],
  20: ['칼슘', 'Calcium', 'Calcio', 'Cálcio', 'カルシウム', 'Calcium', 'Calcium', 'कैल्शियम', '钙', '鈣'],
  21: ['스칸듐', 'Scandium', 'Escandio', 'Escândio', 'スカンジウム', 'Scandium', 'Scandium', 'स्कैंडियम', '钪', '鈧'],
  22: ['타이타늄', 'Titanium', 'Titanio', 'Titânio', 'チタン', 'Titan', 'Titane', 'टाइटेनियम', '钛', '鈦'],
  23: ['바나듐', 'Vanadium', 'Vanadio', 'Vanádio', 'バナジウム', 'Vanadium', 'Vanadium', 'वैनेडियम', '钒', '釩'],
  24: ['크로뮴', 'Chromium', 'Cromo', 'Cromo', 'クロム', 'Chrom', 'Chrome', 'क्रोमियम', '铬', '鉻'],
  25: ['망가니즈', 'Manganese', 'Manganeso', 'Manganês', 'マンガン', 'Mangan', 'Manganèse', 'मैंगनीज़', '锰', '錳'],
  26: ['철', 'Iron', 'Hierro', 'Ferro', '鉄', 'Eisen', 'Fer', 'लोहा', '铁', '鐵'],
  27: ['코발트', 'Cobalt', 'Cobalto', 'Cobalto', 'コバルト', 'Cobalt', 'Cobalt', 'कोबाल्ट', '钴', '鈷'],
  28: ['니켈', 'Nickel', 'Níquel', 'Níquel', 'ニッケル', 'Nickel', 'Nickel', 'निकेल', '镍', '鎳'],
  29: ['구리', 'Copper', 'Cobre', 'Cobre', '銅', 'Kupfer', 'Cuivre', 'ताँबा', '铜', '銅'],
  30: ['아연', 'Zinc', 'Zinc', 'Zinco', '亜鉛', 'Zink', 'Zinc', 'जस्ता', '锌', '鋅'],
  31: ['갈륨', 'Gallium', 'Galio', 'Gálio', 'ガリウム', 'Gallium', 'Gallium', 'गैलियम', '镓', '鎵'],
  32: ['저마늄', 'Germanium', 'Germanio', 'Germânio', 'ゲルマニウム', 'Germanium', 'Germanium', 'जर्मेनियम', '锗', '鍺'],
  33: ['비소', 'Arsenic', 'Arsénico', 'Arsênio', 'ヒ素', 'Arsen', 'Arsenic', 'आर्सेनिक', '砷', '砷'],
  34: ['셀레늄', 'Selenium', 'Selenio', 'Selênio', 'セレン', 'Selen', 'Sélénium', 'सेलेनियम', '硒', '硒'],
  35: ['브로민', 'Bromine', 'Bromo', 'Bromo', '臭素', 'Brom', 'Brome', 'ब्रोमीन', '溴', '溴'],
  36: ['크립톤', 'Krypton', 'Kriptón', 'Criptônio', 'クリプトン', 'Krypton', 'Krypton', 'क्रिप्टॉन', '氪', '氪'],
  37: ['루비듐', 'Rubidium', 'Rubidio', 'Rubídio', 'ルビジウム', 'Rubidium', 'Rubidium', 'रुबिडियम', '铷', '銣'],
  38: ['스트론튬', 'Strontium', 'Estroncio', 'Estrôncio', 'ストロンチウム', 'Strontium', 'Strontium', 'स्ट्रॉन्शियम', '锶', '鍶'],
  39: ['이트륨', 'Yttrium', 'Itrio', 'Ítrio', 'イットリウム', 'Yttrium', 'Yttrium', 'यत्रियम', '钇', '釔'],
  40: ['지르코늄', 'Zirconium', 'Circonio', 'Zircônio', 'ジルコニウム', 'Zirconium', 'Zirconium', 'ज़र्कोनियम', '锆', '鋯'],
  41: ['나이오븀', 'Niobium', 'Niobio', 'Nióbio', 'ニオブ', 'Niob', 'Niobium', 'नाइओबियम', '铌', '鈮'],
  42: ['몰리브데넘', 'Molybdenum', 'Molibdeno', 'Molibdênio', 'モリブデン', 'Molybdän', 'Molybdène', 'मॉलिब्डेनम', '钼', '鉬'],
  43: ['테크네튬', 'Technetium', 'Tecnecio', 'Tecnécio', 'テクネチウム', 'Technetium', 'Technétium', 'टेक्नीशियम', '锝', '鎝'],
  44: ['루테늄', 'Ruthenium', 'Rutenio', 'Rutênio', 'ルテニウム', 'Ruthenium', 'Ruthénium', 'रुथेनियम', '钌', '釕'],
  45: ['로듐', 'Rhodium', 'Rodio', 'Ródio', 'ロジウム', 'Rhodium', 'Rhodium', 'रोडियम', '铑', '銠'],
  46: ['팔라듐', 'Palladium', 'Paladio', 'Paládio', 'パラジウム', 'Palladium', 'Palladium', 'पैलेडियम', '钯', '鈀'],
  47: ['은', 'Silver', 'Plata', 'Prata', '銀', 'Silber', 'Argent', 'चाँदी', '银', '銀'],
  48: ['카드뮴', 'Cadmium', 'Cadmio', 'Cádmio', 'カドミウム', 'Cadmium', 'Cadmium', 'कैडमियम', '镉', '鎘'],
  49: ['인듐', 'Indium', 'Indio', 'Índio', 'インジウム', 'Indium', 'Indium', 'इंडियम', '铟', '銦'],
  50: ['주석', 'Tin', 'Estaño', 'Estanho', 'スズ', 'Zinn', 'Étain', 'टिन', '锡', '錫'],
  51: ['안티모니', 'Antimony', 'Antimonio', 'Antimônio', 'アンチモン', 'Antimon', 'Antimoine', 'ऐंटिमनी', '锑', '銻'],
  52: ['텔루륨', 'Tellurium', 'Telurio', 'Telúrio', 'テルル', 'Tellur', 'Tellure', 'टेल्यूरियम', '碲', '碲'],
  53: ['아이오딘', 'Iodine', 'Yodo', 'Iodo', 'ヨウ素', 'Iod', 'Iode', 'आयोडीन', '碘', '碘'],
  54: ['제논', 'Xenon', 'Xenón', 'Xenônio', 'キセノン', 'Xenon', 'Xénon', 'ज़ेनॉन', '氙', '氙'],
  55: ['세슘', 'Caesium', 'Cesio', 'Césio', 'セシウム', 'Caesium', 'Césium', 'सीज़ियम', '铯', '銫'],
  56: ['바륨', 'Barium', 'Bario', 'Bário', 'バリウム', 'Barium', 'Baryum', 'बेरियम', '钡', '鋇'],
  57: ['란타넘', 'Lanthanum', 'Lantano', 'Lantânio', 'ランタン', 'Lanthan', 'Lanthane', 'लैंथेनम', '镧', '鑭'],
  58: ['세륨', 'Cerium', 'Cerio', 'Cério', 'セリウム', 'Cer', 'Cérium', 'सीरियम', '铈', '鈰'],
  59: ['프라세오디뮴', 'Praseodymium', 'Praseodimio', 'Praseodímio', 'プラセオジム', 'Praseodym', 'Praséodyme', 'प्रेसियोडाइमियम', '镨', '鐠'],
  60: ['네오디뮴', 'Neodymium', 'Neodimio', 'Neodímio', 'ネオジム', 'Neodym', 'Néodyme', 'नियोडाइमियम', '钕', '釹'],
  61: ['프로메튬', 'Promethium', 'Prometio', 'Promécio', 'プロメチウム', 'Promethium', 'Prométhium', 'प्रोमेथियम', '钷', '鉕'],
  62: ['사마륨', 'Samarium', 'Samario', 'Samário', 'サマリウム', 'Samarium', 'Samarium', 'सैमेरियम', '钐', '釤'],
  63: ['유로퓸', 'Europium', 'Europio', 'Európio', 'ユウロピウム', 'Europium', 'Europium', 'यूरोपियम', '铕', '銪'],
  64: ['가돌리늄', 'Gadolinium', 'Gadolinio', 'Gadolínio', 'ガドリニウム', 'Gadolinium', 'Gadolinium', 'गैडोलिनियम', '钆', '釓'],
  65: ['터븀', 'Terbium', 'Terbio', 'Térbio', 'テルビウム', 'Terbium', 'Terbium', 'टर्बियम', '铽', '鋱'],
  66: ['디스프로슘', 'Dysprosium', 'Disprosio', 'Disprósio', 'ジスプロシウム', 'Dysprosium', 'Dysprosium', 'डिस्प्रोसियम', '镝', '鏑'],
  67: ['홀뮴', 'Holmium', 'Holmio', 'Hólmio', 'ホルミウム', 'Holmium', 'Holmium', 'होल्मियम', '钬', '鈥'],
  68: ['어븀', 'Erbium', 'Erbio', 'Érbio', 'エルビウム', 'Erbium', 'Erbium', 'अर्बियम', '铒', '鉺'],
  69: ['툴륨', 'Thulium', 'Tulio', 'Túlio', 'ツリウム', 'Thulium', 'Thulium', 'थुलियम', '铥', '銩'],
  70: ['이터븀', 'Ytterbium', 'Iterbio', 'Itérbio', 'イッテルビウム', 'Ytterbium', 'Ytterbium', 'इटर्बियम', '镱', '鐿'],
  71: ['루테튬', 'Lutetium', 'Lutecio', 'Lutécio', 'ルテチウム', 'Lutetium', 'Lutécium', 'ल्यूटीशियम', '镥', '鎦'],
  72: ['하프늄', 'Hafnium', 'Hafnio', 'Háfnio', 'ハフニウム', 'Hafnium', 'Hafnium', 'हैफ़नियम', '铪', '鉿'],
  73: ['탄탈럼', 'Tantalum', 'Tántalo', 'Tântalo', 'タンタル', 'Tantal', 'Tantale', 'टैंटलम', '钽', '鉭'],
  74: ['텅스텐', 'Tungsten', 'Wolframio', 'Tungstênio', 'タングステン', 'Wolfram', 'Tungstène', 'टंगस्टन', '钨', '鎢'],
  75: ['레늄', 'Rhenium', 'Renio', 'Rênio', 'レニウム', 'Rhenium', 'Rhénium', 'रीनियम', '铼', '錸'],
  76: ['오스뮴', 'Osmium', 'Osmio', 'Ósmio', 'オスミウム', 'Osmium', 'Osmium', 'ऑस्मियम', '锇', '鋨'],
  77: ['이리듐', 'Iridium', 'Iridio', 'Irídio', 'イリジウム', 'Iridium', 'Iridium', 'इरिडियम', '铱', '銥'],
  78: ['백금', 'Platinum', 'Platino', 'Platina', '白金', 'Platin', 'Platine', 'प्लैटिनम', '铂', '鉑'],
  79: ['금', 'Gold', 'Oro', 'Ouro', '金', 'Gold', 'Or', 'सोना', '金', '金'],
  80: ['수은', 'Mercury', 'Mercurio', 'Mercúrio', '水銀', 'Quecksilber', 'Mercure', 'पारा', '汞', '汞'],
  81: ['탈륨', 'Thallium', 'Talio', 'Tálio', 'タリウム', 'Thallium', 'Thallium', 'थैलियम', '铊', '鉈'],
  82: ['납', 'Lead', 'Plomo', 'Chumbo', '鉛', 'Blei', 'Plomb', 'सीसा', '铅', '鉛'],
  83: ['비스무트', 'Bismuth', 'Bismuto', 'Bismuto', 'ビスマス', 'Bismut', 'Bismuth', 'बिस्मथ', '铋', '鉍'],
  84: ['폴로늄', 'Polonium', 'Polonio', 'Polônio', 'ポロニウム', 'Polonium', 'Polonium', 'पोलोनियम', '钋', '釙'],
  85: ['아스타틴', 'Astatine', 'Astato', 'Astato', 'アスタチン', 'Astat', 'Astate', 'एस्टैटीन', '砹', '砈'],
  86: ['라돈', 'Radon', 'Radón', 'Radônio', 'ラドン', 'Radon', 'Radon', 'रेडॉन', '氡', '氡'],
  87: ['프랑슘', 'Francium', 'Francio', 'Frâncio', 'フランシウム', 'Francium', 'Francium', 'फ़्रैंशियम', '钫', '鍅'],
  88: ['라듐', 'Radium', 'Radio', 'Rádio', 'ラジウム', 'Radium', 'Radium', 'रेडियम', '镭', '鐳'],
  89: ['악티늄', 'Actinium', 'Actinio', 'Actínio', 'アクチニウム', 'Actinium', 'Actinium', 'ऐक्टिनियम', '锕', '錒'],
  90: ['토륨', 'Thorium', 'Torio', 'Tório', 'トリウム', 'Thorium', 'Thorium', 'थोरियम', '钍', '釷'],
  91: ['프로트악티늄', 'Protactinium', 'Protactinio', 'Protactínio', 'プロトアクチニウム', 'Protactinium', 'Protactinium', 'प्रोटैक्टिनियम', '镤', '鏷'],
  92: ['우라늄', 'Uranium', 'Uranio', 'Urânio', 'ウラン', 'Uran', 'Uranium', 'यूरेनियम', '铀', '鈾'],
  93: ['넵투늄', 'Neptunium', 'Neptunio', 'Netúnio', 'ネプツニウム', 'Neptunium', 'Neptunium', 'नेप्ट्यूनियम', '镎', '錼'],
  94: ['플루토늄', 'Plutonium', 'Plutonio', 'Plutônio', 'プルトニウム', 'Plutonium', 'Plutonium', 'प्लूटोनियम', '钚', '鈽'],
  95: ['아메리슘', 'Americium', 'Americio', 'Amerício', 'アメリシウム', 'Americium', 'Américium', 'अमेरिशियम', '镅', '鋂'],
  96: ['퀴륨', 'Curium', 'Curio', 'Cúrio', 'キュリウム', 'Curium', 'Curium', 'क्यूरियम', '锔', '鋦'],
  97: ['버클륨', 'Berkelium', 'Berkelio', 'Berquélio', 'バークリウム', 'Berkelium', 'Berkélium', 'बर्केलियम', '锫', '鉳'],
  98: ['캘리포늄', 'Californium', 'Californio', 'Califórnio', 'カリホルニウム', 'Californium', 'Californium', 'कैलिफ़ोर्नियम', '锎', '鉲'],
  99: ['아인슈타이늄', 'Einsteinium', 'Einstenio', 'Einstênio', 'アインスタイニウム', 'Einsteinium', 'Einsteinium', 'आइंस्टीनियम', '锿', '鑀'],
  100: ['페르뮴', 'Fermium', 'Fermio', 'Férmio', 'フェルミウム', 'Fermium', 'Fermium', 'फ़र्मियम', '镄', '鐨'],
  101: ['멘델레븀', 'Mendelevium', 'Mendelevio', 'Mendelévio', 'メンデレビウム', 'Mendelevium', 'Mendélévium', 'मेंडेलीवियम', '钔', '鍆'],
  102: ['노벨륨', 'Nobelium', 'Nobelio', 'Nobélio', 'ノーベリウム', 'Nobelium', 'Nobélium', 'नोबेलियम', '锘', '鍩'],
  103: ['로렌슘', 'Lawrencium', 'Lawrencio', 'Laurêncio', 'ローレンシウム', 'Lawrencium', 'Lawrencium', 'लॉरेंसियम', '铹', '鐒'],
  104: ['러더포듐', 'Rutherfordium', 'Rutherfordio', 'Rutherfórdio', 'ラザホージウム', 'Rutherfordium', 'Rutherfordium', 'रदरफ़ोर्डियम', '鑪', '鑪'],
  105: ['더브늄', 'Dubnium', 'Dubnio', 'Dúbnio', 'ドブニウム', 'Dubnium', 'Dubnium', 'डब्नियम', '𨧀', '𨧀'],
  106: ['시보귬', 'Seaborgium', 'Seaborgio', 'Seabórgio', 'シーボーギウム', 'Seaborgium', 'Seaborgium', 'सीबोर्गियम', '𨭎', '𨭎'],
  107: ['보륨', 'Bohrium', 'Bohrio', 'Bóhrio', 'ボーリウム', 'Bohrium', 'Bohrium', 'बोहरियम', '𨨏', '𨨏'],
  108: ['하슘', 'Hassium', 'Hasio', 'Hássio', 'ハッシウム', 'Hassium', 'Hassium', 'हैसियम', '𨭆', '𨭆'],
  109: ['마이트너륨', 'Meitnerium', 'Meitnerio', 'Meitnério', 'マイトネリウム', 'Meitnerium', 'Meitnérium', 'माइटनेरियम', '䥑', '䥑'],
  110: ['다름슈타튬', 'Darmstadtium', 'Darmstadtio', 'Darmstácio', 'ダームスタチウム', 'Darmstadtium', 'Darmstadtium', 'डार्मस्टेडियम', '鐽', '鐽'],
  111: ['뢴트게늄', 'Roentgenium', 'Roentgenio', 'Roentgênio', 'レントゲニウム', 'Roentgenium', 'Roentgenium', 'रॉन्टजेनियम', '錀', '錀'],
  112: ['코페르니슘', 'Copernicium', 'Copernicio', 'Copernício', 'コペルニシウム', 'Copernicium', 'Copernicium', 'कोपरनिशियम', '鎶', '鎶'],
  113: ['니호늄', 'Nihonium', 'Nihonio', 'Nihônio', 'ニホニウム', 'Nihonium', 'Nihonium', 'निहोनियम', '鉨', '鉨'],
  114: ['플레로븀', 'Flerovium', 'Flerovio', 'Fleróvio', 'フレロビウム', 'Flerovium', 'Flérovium', 'फ़्लेरोवियम', '鈇', '鈇'],
  115: ['모스코븀', 'Moscovium', 'Moscovio', 'Moscóvio', 'モスコビウム', 'Moscovium', 'Moscovium', 'मॉस्कोवियम', '鏌', '鏌'],
  116: ['리버모륨', 'Livermorium', 'Livermorio', 'Livermório', 'リバモリウム', 'Livermorium', 'Livermorium', 'लिवरमोरियम', '鉝', '鉝'],
  117: ['테네신', 'Tennessine', 'Teneso', 'Tenessino', 'テネシン', 'Tenness', 'Tennesse', 'टेनेसीन', '鿬', '鿬'],
  118: ['오가네손', 'Oganesson', 'Oganesón', 'Oganessônio', 'オガネソン', 'Oganesson', 'Oganesson', 'ओगेनेसन', '鿫', '鿫'],
};

const INDEX: Record<Lang, number> = { ko: 0, en: 1, es: 2, pt: 3, ja: 4, de: 5, fr: 6, hi: 7, zh: 8, tw: 9 };

export const nameOf = (z: number, lang: Lang): string => NAMES[z]?.[INDEX[lang]] ?? '';
