/** 사자성어 - 처세·태도 (9) */
import type { Idiom } from './types.ts';

export const ATTITUDE_IDIOMS: Idiom[] = [
  {
    slug: 'yubimuhwan', hanja: '有備無患', simplified: '有备无患', reading: '유비무환',
    pinyin: 'yǒu bèi wú huàn', chars: ['있을 유', '갖출 비', '없을 무', '근심 환'],
    category: '처세·태도', icon: '🛡️',
    ko: { title: '유비무환', meaning: '미리 준비해 두면 걱정할 일이 없다는 뜻입니다.',
      origin: '《서경》에 나오는 말로, 은나라 재상 부열이 왕에게 올린 조언에서 비롯됐습니다.',
      usage: '재난 대비 훈련이나 보험 가입을 권할 때 가장 흔히 쓰이는 표현입니다.' },
    en: { title: 'Yu-bi-mu-hwan', meaning: 'If you prepare in advance, there is nothing to worry about.',
      origin: 'From the Book of Documents, in advice the Shang minister Fu Yue gave his king.',
      usage: 'The standard phrase in Korea for urging disaster drills or buying insurance.' },
  },
  {
    slug: 'yeokjisaji', hanja: '易地思之', simplified: '易地思之', reading: '역지사지',
    pinyin: 'yì dì sī zhī', chars: ['바꿀 역', '땅 지', '생각할 사', '갈 지'],
    category: '처세·태도', icon: '🤝',
    ko: { title: '역지사지', meaning: '처지를 바꿔서 생각해 본다는 뜻입니다.',
      origin: '《맹자》의 "역지즉개연(易地則皆然, 처지를 바꾸면 모두 그러하다)"에서 나온 한국식 표현입니다.',
      usage: '갈등을 조정할 때 상대의 입장에서 보라고 권하는 말로 쓰입니다.' },
    en: { title: 'Yeok-ji-sa-ji', meaning: 'Think about it after swapping places with the other person.',
      origin: 'A Korean coinage drawn from Mencius’ line that "swapping positions, all would act the same".',
      usage: 'Used in mediating conflict, to ask someone to see it from the other side.' },
  },
  {
    slug: 'chojiilgwan', hanja: '初志一貫', simplified: '初志一贯', reading: '초지일관',
    pinyin: 'chū zhì yī guàn', chars: ['처음 초', '뜻 지', '한 일', '꿸 관'],
    category: '처세·태도', icon: '🎯',
    ko: { title: '초지일관', meaning: '처음 세운 뜻을 끝까지 한결같이 밀고 나간다는 뜻입니다.',
      origin: '한국에서 널리 쓰이는 사자성어로, 고전 출전이 특정되지 않은 근대 이후의 표현입니다.',
      usage: '오래 한 일을 흔들림 없이 이어온 사람을 평가할 때 씁니다.' },
    en: { title: 'Cho-ji-il-gwan', meaning: 'Carry the resolve you started with all the way through, unchanged.',
      origin: 'Widely used in Korea, without a pinned classical source — a modern formation.',
      usage: 'Said of someone who has held to one path for years without wavering.' },
  },
  {
    slug: 'myeongbulheojeon', hanja: '名不虛傳', simplified: '名不虚传', reading: '명불허전',
    pinyin: 'míng bù xū chuán', chars: ['이름 명', '아닐 불', '빌 허', '전할 전'],
    category: '처세·태도', icon: '⭐',
    ko: { title: '명불허전', meaning: '이름이 헛되이 전해진 것이 아니라는 뜻으로, 명성에 걸맞다는 말입니다.',
      origin: '《사기》 등 중국 고전에서 쓰인 표현으로, 소문난 실력을 직접 확인했을 때 씁니다.',
      usage: '기대하고 간 맛집이나 실제로 만나 본 실력자에게 하는 칭찬입니다.' },
    en: { title: 'Myeong-bul-heo-jeon', meaning: 'The reputation was not passed on in vain — it lives up to the name.',
      origin: 'Used in Chinese classics including the Records of the Grand Historian, said when a famed skill proves real.',
      usage: 'The compliment you pay a much-hyped restaurant or an expert who turns out to deserve the praise.' },
  },
  {
    slug: 'cheongchuleoram', hanja: '靑出於藍', simplified: '青出于蓝', reading: '청출어람',
    pinyin: 'qīng chū yú lán', chars: ['푸를 청', '날 출', '어조사 어', '쪽 람'],
    category: '처세·태도', icon: '🌱',
    ko: { title: '청출어람', meaning: '쪽에서 뽑아낸 푸른 물감이 쪽보다 더 푸르다는 뜻으로, 제자가 스승을 뛰어넘는 것을 말합니다.',
      origin: '《순자》 권학편의 "청취지어람이청어람(靑取之於藍而靑於藍)"에서 왔습니다.',
      usage: '가르친 사람이 자기보다 잘하게 된 제자를 자랑스럽게 이를 때 씁니다.' },
    en: { title: 'Cheong-chul-eo-ram', meaning: 'The blue drawn from the indigo plant is bluer than the plant — the student surpasses the teacher.',
      origin: 'From the "Encouraging Learning" chapter of the Xunzi.',
      usage: 'Said with pride by a teacher whose student has outgrown them.' },
  },
  {
    slug: 'daegimanseong', hanja: '大器晩成', simplified: '大器晚成', reading: '대기만성',
    pinyin: 'dà qì wǎn chéng', chars: ['큰 대', '그릇 기', '늦을 만', '이룰 성'],
    category: '처세·태도', icon: '⏳',
    ko: { title: '대기만성', meaning: '큰 그릇은 늦게 이루어진다는 뜻으로, 크게 될 사람은 늦게 성공한다는 말입니다.',
      origin: '《노자》 41장에 나오는 말로, 본래는 큰 그릇일수록 완성에 오래 걸린다는 뜻이었습니다.',
      usage: '늦게 빛을 본 사람이나 아직 결과가 나오지 않은 사람을 격려할 때 씁니다.' },
    en: { title: 'Dae-gi-man-seong', meaning: 'A great vessel takes long to finish — those destined for greatness succeed late.',
      origin: 'From chapter 41 of the Laozi, originally meaning the larger the vessel, the longer it takes to complete.',
      usage: 'Encouragement for a late bloomer, or for someone whose results have not arrived yet.' },
  },
  {
    slug: 'ongojisin', hanja: '溫故知新', simplified: '温故知新', reading: '온고지신',
    pinyin: 'wēn gù zhī xīn', chars: ['익힐 온', '옛 고', '알 지', '새 신'],
    category: '처세·태도', icon: '📖',
    ko: { title: '온고지신', meaning: '옛것을 익혀 새것을 안다는 뜻입니다.',
      origin: '《논어》 위정편의 "온고이지신(溫故而知新)"에서 왔습니다.',
      usage: '전통을 공부해 현재의 문제를 푸는 태도를 가리킬 때 씁니다.' },
    en: { title: 'On-go-ji-sin', meaning: 'Study the old to understand the new.',
      origin: 'From the Analects, book two: "reviewing the old, one knows the new".',
      usage: 'Describes solving present problems by studying tradition.' },
  },
  {
    slug: 'susinjega', hanja: '修身齊家', simplified: '修身齐家', reading: '수신제가',
    pinyin: 'xiū shēn qí jiā', chars: ['닦을 수', '몸 신', '가지런할 제', '집 가'],
    category: '처세·태도', icon: '🏔️',
    ko: { title: '수신제가', meaning: '자기를 닦고 집안을 바로 세운다는 뜻입니다.',
      origin: '《대학》의 "수신제가치국평천하(修身齊家治國平天下)"에서 앞 네 자를 떼어 쓴 것입니다.',
      usage: '남을 다스리기 전에 자기부터 바로 하라는 뜻으로 인용합니다.' },
    en: { title: 'Su-sin-je-ga', meaning: 'Cultivate yourself and put your household in order.',
      origin: 'The first four characters of the Great Learning’s sequence: cultivate the self, order the family, govern the state, bring peace to the world.',
      usage: 'Quoted to say that governing others must begin with governing oneself.' },
  },
  {
    slug: 'anbunjijok', hanja: '安分知足', simplified: '安分知足', reading: '안분지족',
    pinyin: 'ān fèn zhī zú', chars: ['편안할 안', '나눌 분', '알 지', '넉넉할 족'],
    category: '처세·태도', icon: '🍀',
    ko: { title: '안분지족', meaning: '자기 분수를 지키며 만족할 줄 안다는 뜻입니다.',
      origin: '유가와 도가 문헌에 모두 비슷한 표현이 나오며, 한국에서는 조선 시대 문집에서 널리 쓰였습니다.',
      usage: '욕심을 줄이고 지금에 만족하는 삶의 태도를 이를 때 씁니다.' },
    en: { title: 'An-bun-ji-jok', meaning: 'Keep to your station and know contentment.',
      origin: 'Similar phrasing appears in both Confucian and Daoist texts; it was common in Joseon-era Korean writing.',
      usage: 'Describes a life of reduced wants and satisfaction with what one has.' },
  },
];
