/** 사자성어 - 노력·인내 (9) */
import type { Idiom } from './types.ts';

export const EFFORT_IDIOMS: Idiom[] = [
  {
    slug: 'ugongisan', hanja: '愚公移山', simplified: '愚公移山', reading: '우공이산',
    pinyin: 'yú gōng yí shān', chars: ['어리석을 우', '공변될 공', '옮길 이', '산 산'],
    category: '노력·인내', icon: '🏔️',
    ko: { title: '우공이산', meaning: '우공이 산을 옮긴다는 뜻으로, 꾸준히 하면 못 이룰 일이 없다는 말입니다.',
      origin: '《열자》 탕문편에서 아흔 살 우공이 대대로 흙을 나르겠다고 하자 하늘이 산을 옮겨 주었다는 이야기입니다.',
      usage: '결과가 멀어 보이는 일을 오래 밀고 나갈 때 자신을 다잡는 말로 씁니다.' },
    en: { title: 'U-gong-i-san', meaning: 'Old Man Yu moves the mountain — persistence accomplishes anything.',
      origin: 'From the Liezi: a ninety-year-old vowed his descendants would keep carrying the soil, and heaven moved the mountain for him.',
      usage: 'A reminder to yourself when the goal is far off but the work continues.' },
  },
  {
    slug: 'maburakchim', hanja: '磨斧作針', simplified: '磨斧作针', reading: '마부작침',
    pinyin: 'mó fǔ zuò zhēn', chars: ['갈 마', '도끼 부', '지을 작', '바늘 침'],
    category: '노력·인내', icon: '🔨',
    ko: { title: '마부작침', meaning: '도끼를 갈아 바늘을 만든다는 뜻으로, 끈질기게 노력하면 어려운 일도 이룬다는 말입니다.',
      origin: '이백이 공부를 중도에 그만두고 내려오다 도끼를 갈아 바늘을 만들려는 노파를 보고 마음을 돌렸다는 고사에서 왔습니다.',
      usage: '더디지만 멈추지 않는 노력을 격려할 때 씁니다.' },
    en: { title: 'Ma-bu-jak-chim', meaning: 'Grind an axe into a needle — dogged effort achieves even the impossible.',
      origin: 'The poet Li Bai, quitting his studies, met an old woman grinding an axe to make a needle and turned back.',
      usage: 'Encouragement for effort that is slow but never stops.' },
  },
  {
    slug: 'hyeongseoljigong', hanja: '螢雪之功', simplified: '萤雪之功', reading: '형설지공',
    pinyin: 'yíng xuě zhī gōng', chars: ['반딧불 형', '눈 설', '갈 지', '공 공'],
    category: '노력·인내', icon: '❄️',
    ko: { title: '형설지공', meaning: '반딧불과 눈빛으로 글을 읽어 이룬 공이라는 뜻으로, 어려운 형편에서 애써 공부한 보람을 말합니다.',
      origin: '진나라 차윤이 반딧불을 모아, 손강이 눈빛에 비추어 책을 읽었다는 고사에서 왔습니다.',
      usage: '가난한 환경에서 학업을 이룬 사람을 이를 때 씁니다.' },
    en: { title: 'Hyeong-seol-ji-gong', meaning: 'Merit earned reading by fireflies and snow-light — study achieved in hardship.',
      origin: 'Che Yin of Jin gathered fireflies for light, and Sun Kang read by the glare off snow.',
      usage: 'Said of someone who completed their education in poverty.' },
  },
  {
    slug: 'jeolchibusim', hanja: '切齒腐心', simplified: '切齿腐心', reading: '절치부심',
    pinyin: 'qiè chǐ fǔ xīn', chars: ['끊을 절', '이 치', '썩을 부', '마음 심'],
    category: '노력·인내', icon: '🔥',
    ko: { title: '절치부심', meaning: '이를 갈고 마음을 썩이며 원한을 되새긴다는 뜻입니다.',
      origin: '《사기》에 나오는 표현으로, 복수를 다짐하며 참고 견디는 상태를 가리킵니다.',
      usage: '패배를 되새기며 다음을 준비하는 상황에 씁니다.' },
    en: { title: 'Jeol-chi-bu-sim', meaning: 'Grinding your teeth and letting your heart rot — nursing a grievance.',
      origin: 'From the Records of the Grand Historian, describing someone enduring while vowing revenge.',
      usage: 'Used of preparing for the next attempt while chewing over a defeat.' },
  },
  {
    slug: 'wasinsangdam', hanja: '臥薪嘗膽', simplified: '卧薪尝胆', reading: '와신상담',
    pinyin: 'wò xīn cháng dǎn', chars: ['누울 와', '섶 신', '맛볼 상', '쓸개 담'],
    category: '노력·인내', icon: '⚔️',
    ko: { title: '와신상담', meaning: '땔나무 위에 눕고 쓸개를 맛본다는 뜻으로, 원수를 갚기 위해 온갖 고생을 참는다는 말입니다.',
      origin: '월왕 구천이 오나라에 패한 뒤 장작 위에 누워 자고 쓸개를 맛보며 복수를 준비했다는 고사입니다.',
      usage: '큰 실패 뒤 몇 년을 준비해 재기하는 상황을 이를 때 씁니다.' },
    en: { title: 'Wa-sin-sang-dam', meaning: 'Sleep on firewood and taste gall — endure any hardship to settle a score.',
      origin: 'King Goujian of Yue, defeated by Wu, slept on brushwood and tasted gall while preparing his revenge.',
      usage: 'Describes years of preparation for a comeback after a heavy defeat.' },
  },
  {
    slug: 'baekjeolbulgul', hanja: '百折不屈', simplified: '百折不屈', reading: '백절불굴',
    pinyin: 'bǎi zhé bù qū', chars: ['일백 백', '꺾을 절', '아닐 불', '굽을 굴'],
    category: '노력·인내', icon: '🌿',
    ko: { title: '백절불굴', meaning: '백 번 꺾여도 굽히지 않는다는 뜻입니다.',
      origin: '한나라 시대 문헌에서 유래한 표현으로, 중국에서는 백절불요(百折不撓)를 더 많이 씁니다.',
      usage: '거듭 실패해도 뜻을 꺾지 않는 사람을 이를 때 씁니다.' },
    en: { title: 'Baek-jeol-bul-gul', meaning: 'Broken a hundred times and still unbent.',
      origin: 'Traced to Han-dynasty texts; in Chinese the more common form is bǎi zhé bù náo.',
      usage: 'Said of someone whose resolve survives repeated failure.' },
  },
  {
    slug: 'chiljeonpalgi', hanja: '七顚八起', simplified: '七颠八起', reading: '칠전팔기',
    pinyin: 'qī diān bā qǐ', chars: ['일곱 칠', '넘어질 전', '여덟 팔', '일어날 기'],
    category: '노력·인내', icon: '⚡',
    ko: { title: '칠전팔기', meaning: '일곱 번 넘어져도 여덟 번 일어난다는 뜻입니다.',
      origin: '한국에서 널리 쓰이는 표현으로, 일본어 "칠전팔기(七転八起)"와 형태가 같습니다.',
      usage: '실패를 반복하고도 다시 도전하는 사람에게 쓰는 대표적인 격려입니다.' },
    en: { title: 'Chil-jeon-pal-gi', meaning: 'Fall seven times, rise eight.',
      origin: 'Widely used in Korea and identical in form to the Japanese phrase nana-korobi ya-oki.',
      usage: 'The go-to encouragement for someone who keeps trying after repeated failure.' },
  },
  {
    slug: 'jugyeongyadok', hanja: '晝耕夜讀', simplified: '昼耕夜读', reading: '주경야독',
    pinyin: 'zhòu gēng yè dú', chars: ['낮 주', '밭갈 경', '밤 야', '읽을 독'],
    category: '노력·인내', icon: '🌙',
    ko: { title: '주경야독', meaning: '낮에는 밭을 갈고 밤에는 책을 읽는다는 뜻으로, 어려운 형편에서도 공부를 이어가는 것을 말합니다.',
      origin: '《위서》 등에 비슷한 표현이 보이며, 한국에서는 일하며 공부하는 삶을 가리키는 말로 굳었습니다.',
      usage: '직장에 다니며 학업을 이어가는 사람을 이를 때 씁니다.' },
    en: { title: 'Ju-gyeong-ya-dok', meaning: 'Plough by day and read by night — studying on despite hardship.',
      origin: 'Similar phrasing appears in the Book of Wei; in Korea it settled into meaning working while studying.',
      usage: 'Said of someone holding a job while continuing their education.' },
  },
  {
    slug: 'ilchwiwoljang', hanja: '日就月將', simplified: '日就月将', reading: '일취월장',
    pinyin: 'rì jiù yuè jiāng', chars: ['날 일', '나아갈 취', '달 월', '장차 장'],
    category: '노력·인내', icon: '⭐',
    ko: { title: '일취월장', meaning: '날로 나아가고 달로 자란다는 뜻으로, 실력이 빠르게 향상되는 것을 말합니다.',
      origin: '《시경》 주송에 나오는 "일취월장(日就月將)"에서 왔습니다.',
      usage: '배우기 시작한 사람의 실력이 눈에 띄게 좋아질 때 씁니다.' },
    en: { title: 'Il-chwi-wol-jang', meaning: 'Advancing by the day and growing by the month — improving fast.',
      origin: 'From the Book of Odes, in the Zhou hymns.',
      usage: 'Used when a beginner’s skill is visibly improving.' },
  },
];
