/** 사자성어 - 노력·인내 둘째 묶음 (8) */
import type { Idiom } from './types.ts';

export const EFFORT2_IDIOMS: Idiom[] = [
  {
    slug: 'sipbeoljimok', hanja: '十伐之木', simplified: '十伐之木', reading: '십벌지목',
    pinyin: 'shí fá zhī mù', chars: ['열 십', '칠 벌', '갈 지', '나무 목'],
    category: '노력·인내', icon: '🪓',
    ko: { title: '십벌지목', meaning: '열 번 찍어 안 넘어가는 나무가 없다는 뜻입니다.',
      origin: '한국 속담 "열 번 찍어 안 넘어가는 나무 없다"를 네 자로 옮긴 표현입니다.',
      usage: '거절당해도 다시 시도하라고 권할 때 씁니다.' },
    en: { title: 'Sip-beol-ji-mok', meaning: 'No tree stands after ten swings of the axe.',
      origin: 'A four-character rendering of the Korean proverb about the tenth swing.',
      usage: 'Encouragement to try again after being turned down.' },
    zh: { title: '十伐之木', meaning: '砍十次没有不倒的树。',
      origin: '将韩国谚语「砍十次没有不倒的树」压缩成的四字语。',
      usage: '在韩国用于劝人被拒后再试；中文近似「锲而不舍」。' },
  },
  {
    slug: 'jeoktoseongsan', hanja: '積土成山', simplified: '积土成山', reading: '적토성산',
    pinyin: 'jī tǔ chéng shān', chars: ['쌓을 적', '흙 토', '이룰 성', '메 산'],
    category: '노력·인내', icon: '⛰️',
    ko: { title: '적토성산', meaning: '흙을 쌓아 산을 이룬다, 곧 작은 노력이 모여 큰 결과가 된다는 뜻입니다.',
      origin: '《순자》 권학편의 "적토성산 풍우흥언"에서 나왔습니다.',
      usage: '하루치 공부나 저축의 힘을 말할 때 씁니다.' },
    en: { title: 'Jeok-to-seong-san', meaning: 'Pile up earth and you make a mountain.',
      origin: 'From Xunzi’s chapter on learning: pile earth into a mountain and wind and rain arise from it.',
      usage: 'Used to describe the power of a day’s study or a day’s saving.' },
    zh: { title: '积土成山', meaning: '把土堆积起来就能成山。',
      origin: '出自《荀子·劝学》「积土成山，风雨兴焉」。',
      usage: '用于说明每日学习或储蓄的累积之力，中韩通用。' },
  },
  {
    slug: 'jumagapyeon', hanja: '走馬加鞭', simplified: '走马加鞭', reading: '주마가편',
    pinyin: 'zǒu mǎ jiā biān', chars: ['달릴 주', '말 마', '더할 가', '채찍 편'],
    category: '노력·인내', icon: '🐎',
    ko: { title: '주마가편', meaning: '달리는 말에 채찍을 더한다, 곧 잘하는 사람을 더 몰아붙인다는 뜻입니다.',
      origin: '중국 고전에서 온 표현으로 잘 나가는 기세를 더 밀어준다는 뜻으로 쓰였습니다.',
      usage: '잘하고 있는 사람에게 한 번 더 힘을 내라고 할 때 씁니다. 지나치면 부담이 됩니다.' },
    en: { title: 'Ju-ma-ga-pyeon', meaning: 'Whip the horse that is already running — push the one already doing well.',
      origin: 'A classical phrase for adding momentum to something already going strongly.',
      usage: 'Said to urge one more effort from someone performing well; overdone, it becomes pressure.' },
    zh: { title: '走马加鞭', meaning: '给正在奔跑的马再加一鞭。',
      origin: '源自古籍，指为势头正好的事再添助力。',
      usage: '用于催促本已表现良好的人再努力一分，中文多说「快马加鞭」。' },
  },
  {
    slug: 'subulseokgwon', hanja: '手不釋卷', simplified: '手不释卷', reading: '수불석권',
    pinyin: 'shǒu bù shì juàn', chars: ['손 수', '아닐 불', '풀 석', '책 권'],
    category: '노력·인내', icon: '📚',
    ko: { title: '수불석권', meaning: '손에서 책을 놓지 않는다, 곧 늘 부지런히 읽는다는 뜻입니다.',
      origin: '《삼국지》에서 오나라 여몽이 손권의 권유로 학문에 힘쓴 일을 두고 쓴 말입니다.',
      usage: '독서 습관이 몸에 붙은 사람을 칭찬할 때 씁니다.' },
    en: { title: 'Su-bul-seok-gwon', meaning: 'Never letting the book leave your hand.',
      origin: 'From the Records of the Three Kingdoms, describing Lü Meng of Wu after Sun Quan urged him to study.',
      usage: 'Praise for someone whose reading habit has become second nature.' },
    zh: { title: '手不释卷', meaning: '手中的书从不放下，形容勤读不倦。',
      origin: '出自《三国志》，写吴国吕蒙受孙权劝勉而勤学之事。',
      usage: '用于称赞已把读书变成习惯的人，中韩通用。' },
  },
  {
    slug: 'gakgomyeollyeo', hanja: '刻苦勉勵', simplified: '刻苦勉励', reading: '각고면려',
    pinyin: 'kè kǔ miǎn lì', chars: ['새길 각', '쓸 고', '힘쓸 면', '힘쓸 려'],
    category: '노력·인내', icon: '💪',
    ko: { title: '각고면려', meaning: '고생을 새기며 스스로 힘써 노력한다는 뜻입니다.',
      origin: '각고(刻苦)와 면려(勉勵)를 붙인 말로, 중국 고전에서 각각 쓰이던 표현입니다.',
      usage: '오랜 준비를 마친 사람의 노력을 압축해 말할 때 씁니다.' },
    en: { title: 'Gak-go-myeol-lyeo', meaning: 'Bear the hardship and drive yourself on.',
      origin: 'A compound of two classical terms — enduring hardship and urging oneself forward.',
      usage: 'A compact way to describe someone’s long stretch of preparation.' },
    zh: { title: '刻苦勉励', meaning: '忍受艰苦并自我勉励。',
      origin: '由古籍中各自使用的「刻苦」与「勉励」合成。',
      usage: '用于概括某人长期准备的付出，中韩通用。' },
  },
  {
    slug: 'jagangbulsik', hanja: '自强不息', simplified: '自强不息', reading: '자강불식',
    pinyin: 'zì qiáng bù xī', chars: ['스스로 자', '강할 강', '아닐 불', '쉴 식'],
    category: '노력·인내', icon: '🔁',
    ko: { title: '자강불식', meaning: '스스로 힘써 쉬지 않는다는 뜻입니다.',
      origin: '《주역》 건괘의 "천행건 군자이자강불식"에서 나왔습니다.',
      usage: '남이 보지 않을 때도 꾸준한 사람을 두고 씁니다.' },
    en: { title: 'Ja-gang-bul-sik', meaning: 'Strengthen yourself and never rest.',
      origin: 'From the Book of Changes: heaven moves with vigour, so the noble person strengthens himself without cease.',
      usage: 'Applied to someone who keeps at it even when nobody is watching.' },
    zh: { title: '自强不息', meaning: '自我奋发而不停歇。',
      origin: '出自《周易·乾卦》「天行健，君子以自强不息」。',
      usage: '形容无人看时也持之以恒的人，中韩通用。' },
  },
  {
    slug: 'yujigyeongseong', hanja: '有志竟成', simplified: '有志竟成', reading: '유지경성',
    pinyin: 'yǒu zhì jìng chéng', chars: ['있을 유', '뜻 지', '마침내 경', '이룰 성'],
    category: '노력·인내', icon: '🏁',
    ko: { title: '유지경성', meaning: '뜻이 있으면 마침내 이룬다는 뜻입니다.',
      origin: '《후한서》에서 광무제가 경엄을 칭찬하며 한 말에서 나왔습니다.',
      usage: '오래 붙잡고 있는 목표를 두고 격려할 때 씁니다.' },
    en: { title: 'Yu-ji-gyeong-seong', meaning: 'Where there is will, it is accomplished in the end.',
      origin: 'From the Book of the Later Han, in Emperor Guangwu’s praise of the general Geng Yan.',
      usage: 'Encouragement for a goal someone has held onto for a long time.' },
    zh: { title: '有志竟成', meaning: '有志向终能成事。',
      origin: '出自《后汉书》，光武帝赞将军耿弇时所言。',
      usage: '用于鼓励长期坚守目标的人，中韩通用。' },
  },
  {
    slug: 'jeolchatakma', hanja: '切磋琢磨', simplified: '切磋琢磨', reading: '절차탁마',
    pinyin: 'qiē cuō zhuó mó', chars: ['끊을 절', '갈 차', '다듬을 탁', '갈 마'],
    category: '노력·인내', icon: '💎',
    ko: { title: '절차탁마', meaning: '옥을 자르고 갈고 다듬듯 학문과 인격을 끊임없이 닦는다는 뜻입니다.',
      origin: '《시경》 위풍 기욱편의 옥 다듬는 네 공정에서 나왔습니다.',
      usage: '기술이나 학문을 오래 갈고닦는 과정을 두고 씁니다.' },
    en: { title: 'Jeol-cha-tak-ma', meaning: 'Cut, file, chisel and polish — refine learning and character without cease.',
      origin: 'From the Book of Songs, naming the four stages of working a piece of jade.',
      usage: 'Used for the long refinement of a craft or a body of learning.' },
    zh: { title: '切磋琢磨', meaning: '如治玉般不断切、磋、琢、磨，精进学问与品行。',
      origin: '出自《诗经·卫风·淇奥》，本指治玉的四道工序。',
      usage: '用于形容长期锤炼技艺或学问，中韩通用。' },
  },
];
