/** 사자성어 — 뒤에 더한 열두 개 (셋째 묶음) */
import type { Idiom } from './types.ts';

/**
 * 출전을 확인해 적었고, 하나로 못박을 수 없는 것은 그렇다고 적었다.
 *
 * 불철주야는 《논어》의 "不舍晝夜"에서 왔지만 한국에서는 舍가 撤로 굳었다.
 * 허심탄회와 불면불휴는 중국 고전에 이 네 글자 그대로는 나오지 않는다.
 * 그런 것을 "《장자》에 나온다"고 적으면 그 자체로 틀린 정보가 되므로,
 * 어디까지가 확인된 것인지를 유래 칸에 그대로 밝혔다.
 */
export const EXTRA2_IDIOMS: Idiom[] = [
  {
    slug: 'gyeonggeomangdong', hanja: '輕擧妄動', simplified: '轻举妄动', reading: '경거망동',
    pinyin: 'qīng jǔ wàng dòng', chars: ['가벼울 경', '들 거', '망령될 망', '움직일 동'],
    category: '처세·태도', icon: '⚠️',
    ko: { title: '경거망동', meaning: '가볍게 들고 함부로 움직인다는 뜻으로, 앞뒤를 재지 않고 나선다는 말입니다.',
      origin: '《한비자》 해로편에 사람들이 도리를 가벼이 버리고 함부로 행동한다는 대목이 있고, 이 말이 거기서 왔다고 봅니다.',
      usage: '아직 판이 정리되지 않았을 때 나서지 말라고 이를 때 씁니다.' },
    en: { title: 'Gyeong-geo-mang-dong', meaning: 'To lift lightly and move rashly — acting before weighing what follows.',
      origin: 'Traced to the Han Feizi, which warns of those who cast aside principle lightly and act on impulse.',
      usage: 'Said to hold someone back while a situation is still unsettled.' },
  },
  {
    slug: 'heosimtanhoe', hanja: '虛心坦懷', simplified: '虚心坦怀', reading: '허심탄회',
    pinyin: 'xū xīn tǎn huái', chars: ['빌 허', '마음 심', '평탄할 탄', '품을 회'],
    category: '처세·태도', icon: '🪞',
    ko: { title: '허심탄회', meaning: '마음을 비우고 품은 것을 펴 놓는다는 뜻으로, 숨김없이 이야기한다는 말입니다.',
      origin: '중국 고전에 이 네 글자가 그대로 나오지는 않습니다. 虛心은 《장자》에서 온 오랜 말이고, 지금의 네 글자 꼴은 한국과 일본에서 굳었습니다.',
      usage: '서로 재지 말고 터놓고 이야기하자고 할 때 씁니다.' },
    en: { title: 'Heo-sim-tan-hoe', meaning: 'An emptied mind and an open breast — speaking with nothing held back.',
      origin: 'The four characters together are not found in the Chinese classics; the first two are old, and this set phrase settled in Korea and Japan.',
      usage: 'Used to propose that both sides drop their guard and talk openly.' },
  },
  {
    slug: 'bulcheoljuya', hanja: '不撤晝夜', simplified: '不撤昼夜', reading: '불철주야',
    pinyin: 'bù chè zhòu yè', chars: ['아닐 불', '거둘 철', '낮 주', '밤 야'],
    category: '노력·인내', icon: '🕯️',
    ko: { title: '불철주야', meaning: '밤낮을 가리지 않는다는 뜻으로, 쉬지 않고 매달린다는 말입니다.',
      origin: '《논어》 자한편에서 공자가 냇가에 서서 "가는 것이 이와 같구나, 밤낮을 그치지 않는다(不舍晝夜)"고 한 데서 왔습니다. 한국에서는 舍가 撤로 굳었습니다.',
      usage: '기한에 쫓겨 밤낮없이 일한 사람을 두고 씁니다.' },
    en: { title: 'Bul-cheol-ju-ya', meaning: 'Neither day nor night set aside — working straight through without pause.',
      origin: 'From the Analects, where Confucius watches a river and says the current never stops, day or night. Korean usage swapped one character.',
      usage: 'Said of someone who worked round the clock against a deadline.' },
  },
  {
    slug: 'bulmyeonbulhyu', hanja: '不眠不休', simplified: '不眠不休', reading: '불면불휴',
    pinyin: 'bù mián bù xiū', chars: ['아닐 불', '잘 면', '아닐 불', '쉴 휴'],
    category: '노력·인내', icon: '🛑',
    ko: { title: '불면불휴', meaning: '자지도 쉬지도 않는다는 뜻으로, 한 가지 일에 온 힘을 쏟는다는 말입니다.',
      origin: '고전에 정해진 출전이 없이 한국·중국·일본에서 두루 쓰입니다. 네 글자가 그대로 뜻이 되는 꼴이라 출전 없이 굳었습니다.',
      usage: '구조 현장이나 마감 앞의 며칠처럼, 잠을 미룬 기간을 두고 씁니다.' },
    en: { title: 'Bul-myeon-bul-hyu', meaning: 'Neither sleeping nor resting — pouring everything into one task.',
      origin: 'No fixed classical source; the phrase is used across Korea, China and Japan and means exactly what its four characters say.',
      usage: 'Used of a rescue effort or the last days before a deadline, when sleep was set aside.' },
  },
  {
    slug: 'baegajeolhyeon', hanja: '伯牙絶絃', simplified: '伯牙绝弦', reading: '백아절현',
    pinyin: 'bó yá jué xián', chars: ['맏 백', '어금니 아', '끊을 절', '줄 현'],
    category: '관계·사람', icon: '🎻',
    ko: { title: '백아절현', meaning: '백아가 거문고 줄을 끊었다는 뜻으로, 자기를 알아주던 벗을 잃었다는 말입니다.',
      origin: '《열자》 탕문편에 나옵니다. 백아의 연주를 종자기만이 알아들었는데, 종자기가 죽자 백아는 줄을 끊고 다시는 타지 않았습니다.',
      usage: '나를 가장 잘 알던 사람을 잃었을 때 씁니다.' },
    en: { title: 'Baek-a-jeol-hyeon', meaning: 'Bo Ya cut his strings — losing the one person who truly understood you.',
      origin: 'From the Liezi. Only Zhong Ziqi heard what Bo Ya meant when he played; when Ziqi died, Bo Ya cut the strings and never played again.',
      usage: 'Said on losing the person who understood you best.' },
  },
  {
    slug: 'tasanjiseok', hanja: '他山之石', simplified: '他山之石', reading: '타산지석',
    pinyin: 'tā shān zhī shí', chars: ['다를 타', '뫼 산', '갈 지', '돌 석'],
    category: '관계·사람', icon: '🪨',
    ko: { title: '타산지석', meaning: '다른 산의 거친 돌로도 옥을 갈 수 있다는 뜻으로, 남의 허물에서도 배울 것이 있다는 말입니다.',
      origin: '《시경》 소아 학명에 "다른 산의 돌로 옥을 갈 수 있다(他山之石 可以攻玉)"는 구절이 있습니다.',
      usage: '남의 실패를 흉보는 대신 내 쪽으로 옮겨 볼 때 씁니다.' },
    en: { title: 'Ta-san-ji-seok', meaning: 'A stone from another hill — even a rough one can polish your own jade.',
      origin: 'From the Book of Songs: “stones from other hills can be used to work jade.”',
      usage: 'Used to turn someone else’s failure into a lesson for yourself rather than a joke.' },
  },
  {
    slug: 'gorimuwon', hanja: '孤立無援', simplified: '孤立无援', reading: '고립무원',
    pinyin: 'gū lì wú yuán', chars: ['외로울 고', '설 립', '없을 무', '도울 원'],
    category: '상황·형세', icon: '🏝️',
    ko: { title: '고립무원', meaning: '홀로 서서 도울 이가 없다는 뜻으로, 사방이 막혀 기댈 데가 없다는 말입니다.',
      origin: '한 고전에 못박히지 않고 병법서와 역사서에 두루 나오는 표현입니다. 사면초가와 뜻이 가깝지만 그쪽은 《사기》의 한 장면에서 왔습니다.',
      usage: '조직에서 편이 하나도 남지 않은 처지를 이를 때 씁니다.' },
    en: { title: 'Go-rip-mu-won', meaning: 'Standing alone with no one to help — cut off on every side.',
      origin: 'Not tied to a single classic; it appears across military treatises and histories. Its close cousin, “songs of Chu on four sides”, does come from one scene in the Shiji.',
      usage: 'Used of someone left without a single ally inside an organisation.' },
  },
  {
    slug: 'yeonmokguueo', hanja: '緣木求魚', simplified: '缘木求鱼', reading: '연목구어',
    pinyin: 'yuán mù qiú yú', chars: ['인연 연', '나무 목', '구할 구', '물고기 어'],
    category: '상황·형세', icon: '🐟',
    ko: { title: '연목구어', meaning: '나무에 올라가 물고기를 찾는다는 뜻으로, 방법이 아예 틀렸다는 말입니다.',
      origin: '《맹자》 양혜왕 상편에서 맹자가 제 선왕에게, 무력으로 천하를 얻으려는 것은 나무에 올라 물고기를 구하는 것과 같다고 했습니다.',
      usage: '더 애쓸 것이 아니라 방법을 바꿔야 한다고 말할 때 씁니다.' },
    en: { title: 'Yeon-mok-gu-eo', meaning: 'Climbing a tree to look for fish — the method itself is wrong.',
      origin: 'From the Mencius, where Mencius tells King Xuan that winning the realm by force is like climbing a tree after fish.',
      usage: 'Used to say the answer is not more effort but a different approach.' },
  },
  {
    slug: 'nangjungjichu', hanja: '囊中之錐', simplified: '囊中之锥', reading: '낭중지추',
    pinyin: 'náng zhōng zhī zhuī', chars: ['주머니 낭', '가운데 중', '갈 지', '송곳 추'],
    category: '배움·지혜', icon: '🪡',
    ko: { title: '낭중지추', meaning: '주머니 속의 송곳이라는 뜻으로, 재주 있는 사람은 숨어 있어도 드러난다는 말입니다.',
      origin: '《사기》 평원군열전에 나옵니다. 평원군이 "송곳은 주머니에 넣어도 끝이 뚫고 나온다"고 하자, 모수가 자기를 주머니에 넣어 준 적이 없다고 답했습니다.',
      usage: '아직 알려지지 않았지만 곧 드러날 사람을 두고 씁니다.' },
    en: { title: 'Nang-jung-ji-chu', meaning: 'An awl in a sack — real ability pushes through however it is hidden.',
      origin: 'From the Shiji. Told that an awl always pierces the bag, Mao Sui replied that no one had ever put him in the bag.',
      usage: 'Said of someone still unknown whose ability is about to show.' },
  },
  {
    slug: 'husaenggaoe', hanja: '後生可畏', simplified: '后生可畏', reading: '후생가외',
    pinyin: 'hòu shēng kě wèi', chars: ['뒤 후', '날 생', '옳을 가', '두려워할 외'],
    category: '배움·지혜', icon: '🌱',
    ko: { title: '후생가외', meaning: '뒤에 난 사람이 두렵다는 뜻으로, 젊은 사람의 앞날을 함부로 얕볼 수 없다는 말입니다.',
      origin: '《논어》 자한편에서 공자가 "뒤에 난 사람이 두렵다. 뒷사람이 지금만 못하리라고 어찌 알겠는가"라고 했습니다.',
      usage: '나이 어린 사람의 실력을 인정할 때 씁니다.' },
    en: { title: 'Hu-saeng-ga-oe', meaning: 'Those born later are to be feared — never write off what the young will become.',
      origin: 'From the Analects: “The young are to be held in awe. How do we know they will not equal what we are today?”',
      usage: 'Used to acknowledge that someone much younger is already good.' },
  },
  {
    slug: 'yumyeongmusil', hanja: '有名無實', simplified: '有名无实', reading: '유명무실',
    pinyin: 'yǒu míng wú shí', chars: ['있을 유', '이름 명', '없을 무', '열매 실'],
    category: '말·글', icon: '📜',
    ko: { title: '유명무실', meaning: '이름만 있고 알맹이가 없다는 뜻으로, 간판뿐이라는 말입니다.',
      origin: '《국어》 진어와 《후한서》에 이름과 실제가 어긋나는 것을 두고 쓴 대목이 있습니다.',
      usage: '규정이나 기구가 있기는 한데 아무 일도 하지 않을 때 씁니다.' },
    en: { title: 'Yu-myeong-mu-sil', meaning: 'A name without substance — the sign is up but nothing is behind it.',
      origin: 'Found in the Guoyu and the Book of the Later Han, both used of a name that no longer matches the thing.',
      usage: 'Said of a rule or a body that exists on paper and does nothing.' },
  },
  {
    slug: 'geumgwaokjo', hanja: '金科玉條', simplified: '金科玉条', reading: '금과옥조',
    pinyin: 'jīn kē yù tiáo', chars: ['쇠 금', '과목 과', '구슬 옥', '가지 조'],
    category: '말·글', icon: '📖',
    ko: { title: '금과옥조', meaning: '금과 옥으로 된 조문이라는 뜻으로, 반드시 지켜야 할 규칙이라는 말입니다.',
      origin: '한나라 양웅의 〈극진미신〉에 금과 옥에 새긴 법조문이라는 뜻으로 나옵니다.',
      usage: '어떤 원칙을 흔들림 없이 지킬 때, 또는 지나치게 떠받든다고 나무랄 때 씁니다.' },
    en: { title: 'Geum-gwa-ok-jo', meaning: 'Articles of gold and jade — a rule to be kept without exception.',
      origin: 'From Yang Xiong of the Han dynasty, describing statutes worthy of being cut into gold and jade.',
      usage: 'Used both of a principle held firmly and of one held far too reverently.' },
  },
];
