/** 사자성어 - 뒤에 더한 열두 개 */
import type { Idiom } from './types.ts';

/**
 * 出典을 적을 때 어디서 온 말인지를 함께 밝힌다.
 *
 * 한국에서 쓰는 사자성어에는 중국 고전에서 온 것뿐 아니라 일본과 한국에서
 * 만들어진 것도 섞여 있다. 일석이조는 영어 속담을 옮기며 일본에서 만든 말이고,
 * 견문발검은 한국에서 만들어져 쓰이는 말이다. 이것을 중국 고전인 것처럼 적으면
 * 그 자체로 틀린 정보가 되므로 origin에 사실대로 적었다.
 */
export const EXTRA_IDIOMS: Idiom[] = [
  {
    slug: 'dangnanggeocheol', hanja: '螳螂拒轍', simplified: '螳螂拒辙', reading: '당랑거철',
    pinyin: 'táng láng jù zhé', chars: ['사마귀 당', '사마귀 랑', '막을 거', '바퀴자국 철'],
    category: '처세·태도', icon: '🍃',
    ko: { title: '당랑거철', meaning: '사마귀가 수레바퀴를 막아선다는 뜻으로, 제 힘을 모르고 덤빈다는 말입니다.',
      origin: '《장자》 인간세와 《한시외전》에 사마귀가 앞발을 들어 수레를 막으려 했다는 이야기가 나옵니다.',
      usage: '이길 수 없는 상대에게 무모하게 맞설 때 씁니다.' },
    en: { title: 'Dang-nang-geo-cheol', meaning: 'The mantis blocks the cart — taking on what you cannot possibly stop.',
      origin: 'From the Zhuangzi and the Hanshi Waizhuan, where a mantis raises its forelegs against an oncoming chariot.',
      usage: 'Used of standing up to an opponent far out of your weight.' },
  },
  {
    slug: 'gojangnanmyeong', hanja: '孤掌難鳴', simplified: '孤掌难鸣', reading: '고장난명',
    pinyin: 'gū zhǎng nán míng', chars: ['외로울 고', '손바닥 장', '어려울 난', '울 명'],
    category: '관계·사람', icon: '👏',
    ko: { title: '고장난명', meaning: '손바닥 하나로는 소리가 나지 않는다는 뜻으로, 혼자서는 일을 이루기 어렵다는 말입니다.',
      origin: '《한비자》에 한 손으로는 아무리 빨리 쳐도 소리가 나지 않는다는 구절이 있습니다.',
      usage: '함께할 사람이 있어야 한다고 말할 때, 또는 싸움은 양쪽 다 책임이 있다고 할 때 씁니다.' },
    en: { title: 'Go-jang-nan-myeong', meaning: 'One palm makes no sound — nothing gets done alone.',
      origin: 'The Han Feizi observes that a single hand, however fast it moves, produces no clap.',
      usage: 'Used to say a task needs a partner, or that a quarrel takes two.' },
  },
  {
    slug: 'samgochoryeo', hanja: '三顧草廬', simplified: '三顾草庐', reading: '삼고초려',
    pinyin: 'sān gù cǎo lú', chars: ['석 삼', '돌아볼 고', '풀 초', '오두막 려'],
    category: '관계·사람', icon: '🏚️',
    ko: { title: '삼고초려', meaning: '초가집을 세 번 찾아간다는 뜻으로, 인재를 얻으려 정성을 다한다는 말입니다.',
      origin: '제갈량이 《출사표》에서 유비가 자신을 세 번 찾아왔다고 적은 데서 나왔습니다.',
      usage: '사람을 모실 때 공을 들이는 태도를 가리킬 때 씁니다.' },
    en: { title: 'Sam-go-cho-ryeo', meaning: 'Three visits to the thatched hut — courting talent with real effort.',
      origin: 'From Zhuge Liang\'s memorial, where he records that Liu Bei came to his cottage three times.',
      usage: 'Used of the trouble one takes to bring the right person on board.' },
  },
  {
    slug: 'cheonjaeilu', hanja: '千載一遇', simplified: '千载一遇', reading: '천재일우',
    pinyin: 'qiān zǎi yī yù', chars: ['일천 천', '실을 재', '한 일', '만날 우'],
    category: '상황·형세', icon: '🌠',
    ko: { title: '천재일우', meaning: '천 년에 한 번 만난다는 뜻으로, 좀처럼 오지 않는 기회를 이르는 말입니다.',
      origin: '동진의 원굉이 《삼국명신서찬》에서 뛰어난 임금과 신하가 만나는 일을 이렇게 적었습니다.',
      usage: '다시 오기 어려운 기회 앞에서 씁니다.' },
    en: { title: 'Cheon-jae-il-u', meaning: 'One meeting in a thousand years — a chance that scarcely comes.',
      origin: 'Yuan Hong of the Eastern Jin used the phrase for the rare meeting of a fine ruler and a fine minister.',
      usage: 'Said of an opening unlikely to appear again.' },
  },
  {
    slug: 'yongdusami', hanja: '龍頭蛇尾', simplified: '龙头蛇尾', reading: '용두사미',
    pinyin: 'lóng tóu shé wěi', chars: ['용 룡', '머리 두', '뱀 사', '꼬리 미'],
    category: '처세·태도', icon: '🐉',
    ko: { title: '용두사미', meaning: '용의 머리에 뱀의 꼬리라는 뜻으로, 시작은 거창하나 끝이 흐지부지하다는 말입니다.',
      origin: '선종의 어록에 보이는 표현으로, 기세만 좋고 마무리가 없는 것을 가리켰습니다.',
      usage: '요란하게 시작해 조용히 사라진 일을 두고 씁니다.' },
    en: { title: 'Yong-du-sa-mi', meaning: 'A dragon\'s head on a snake\'s tail — a grand start that peters out.',
      origin: 'The phrase appears in Chan Buddhist records, aimed at bluster without follow-through.',
      usage: 'Used of something launched loudly and quietly abandoned.' },
  },
  {
    slug: 'eupchammasok', hanja: '泣斬馬謖', simplified: '泣斩马谡', reading: '읍참마속',
    pinyin: 'qì zhǎn mǎ sù', chars: ['울 읍', '벨 참', '말 마', '일어날 속'],
    category: '처세·태도', icon: '⚖️',
    ko: { title: '읍참마속', meaning: '울면서 마속의 목을 벤다는 뜻으로, 사사로운 정을 누르고 원칙을 지킨다는 말입니다.',
      origin: '《삼국지》 촉서에서 제갈량이 군령을 어긴 마속을 아끼면서도 처형한 일에서 나왔습니다.',
      usage: '가까운 사람에게도 원칙을 적용해야 할 때 씁니다.' },
    en: { title: 'Eup-cham-ma-sok', meaning: 'Beheading Ma Su in tears — holding to the rule despite personal feeling.',
      origin: 'From the Records of the Three Kingdoms: Zhuge Liang executed Ma Su for disobeying orders, though he valued him.',
      usage: 'Used when the rule has to apply to someone close as well.' },
  },
  {
    slug: 'gakjugugeom', hanja: '刻舟求劍', simplified: '刻舟求剑', reading: '각주구검',
    pinyin: 'kè zhōu qiú jiàn', chars: ['새길 각', '배 주', '구할 구', '칼 검'],
    category: '배움·지혜', icon: '🗡️',
    ko: { title: '각주구검', meaning: '뱃전에 표시하고 칼을 찾는다는 뜻으로, 달라진 형편을 모르고 옛 방법에 매달린다는 말입니다.',
      origin: '《여씨춘추》 찰금편에서 강에 칼을 빠뜨린 사람이 뱃전에 자국을 내고 배가 멈춘 뒤 그 아래를 뒤졌다는 이야기입니다.',
      usage: '상황이 바뀌었는데 예전 방식만 고집할 때 씁니다.' },
    en: { title: 'Gak-ju-gu-geom', meaning: 'Notching the boat to find the sword — clinging to an old method after things have moved on.',
      origin: 'From the Lüshi Chunqiu: a man dropped his sword in the river, cut a mark on the gunwale, and searched below it once the boat had stopped.',
      usage: 'Used when the situation has changed but the old approach is kept.' },
  },
  {
    slug: 'pajukjise', hanja: '破竹之勢', simplified: '破竹之势', reading: '파죽지세',
    pinyin: 'pò zhú zhī shì', chars: ['깨뜨릴 파', '대 죽', '갈 지', '형세 세'],
    category: '상황·형세', icon: '🪵',
    ko: { title: '파죽지세', meaning: '대나무를 쪼개는 기세라는 뜻으로, 거침없이 밀고 나가는 형세를 이르는 말입니다.',
      origin: '《진서》 두예전에서 두예가 오나라를 칠 때 첫 마디만 쪼개면 나머지는 저절로 갈라진다고 한 데서 나왔습니다.',
      usage: '연승이나 거침없는 진행을 말할 때 씁니다.' },
    en: { title: 'Pa-juk-ji-se', meaning: 'The force of splitting bamboo — advancing without anything to check it.',
      origin: 'From the Book of Jin: Du Yu said that once the first joints give way, the rest of the stalk splits on its own.',
      usage: 'Used of a winning streak or an advance nothing slows.' },
  },
  {
    slug: 'hwangoltaltae', hanja: '換骨奪胎', simplified: '换骨夺胎', reading: '환골탈태',
    pinyin: 'huàn gǔ duó tāi', chars: ['바꿀 환', '뼈 골', '빼앗을 탈', '아이 밸 태'],
    category: '배움·지혜', icon: '🌸',
    ko: { title: '환골탈태', meaning: '뼈를 바꾸고 태를 벗는다는 뜻으로, 사람이나 글이 몰라보게 좋아진다는 말입니다.',
      origin: '본디 도교에서 신선이 되는 과정을 이르던 말인데, 송나라 황정견이 옛 시를 새롭게 고쳐 쓰는 방법을 가리키며 널리 퍼졌습니다.',
      usage: '사람이 달라졌거나 글을 크게 손봤을 때 씁니다.' },
    en: { title: 'Hwan-gol-tal-tae', meaning: 'New bones, a new womb — a transformation past recognition.',
      origin: 'Originally a Daoist term for becoming an immortal; the Song poet Huang Tingjian used it for reworking older verse into something new.',
      usage: 'Said of a person who has changed, or writing that has been thoroughly rebuilt.' },
  },
  {
    slug: 'gyeonmunbalgeom', hanja: '見蚊拔劍', simplified: '见蚊拔剑', reading: '견문발검',
    pinyin: 'jiàn wén bá jiàn', chars: ['볼 견', '모기 문', '뺄 발', '칼 검'],
    category: '처세·태도', icon: '🦟',
    ko: { title: '견문발검', meaning: '모기를 보고 칼을 뺀다는 뜻으로, 사소한 일에 지나치게 크게 대응한다는 말입니다.',
      origin: '중국 고전이 아니라 한국에서 만들어져 쓰이는 성어로 알려져 있습니다. 조선 시대 문헌에 같은 뜻의 표현이 보입니다.',
      usage: '작은 일에 화를 크게 낼 때 나무라듯 씁니다.' },
    en: { title: 'Gyeon-mun-bal-geom', meaning: 'Drawing a sword at a mosquito — an answer far larger than the problem.',
      origin: 'Not from a Chinese classic; it is understood as a Korean coinage, with the same sense appearing in Joseon-era writing.',
      usage: 'Used, half in reproach, of someone who blows a small thing up.' },
  },
  {
    slug: 'suseoyangdan', hanja: '首鼠兩端', simplified: '首鼠两端', reading: '수서양단',
    pinyin: 'shǒu shǔ liǎng duān', chars: ['머리 수', '쥐 서', '두 량', '끝 단'],
    category: '처세·태도', icon: '👀',
    ko: { title: '수서양단', meaning: '쥐가 구멍에서 머리만 내밀고 양쪽을 살핀다는 뜻으로, 결정을 못 내리고 눈치만 본다는 말입니다.',
      origin: '《사기》 위기무안후열전에서 한무제 앞에서 어느 편도 들지 못하고 망설이던 신하를 두고 한 말입니다.',
      usage: '어느 쪽으로도 정하지 못하고 미루는 태도를 꼬집을 때 씁니다.' },
    en: { title: 'Su-seo-yang-dan', meaning: 'A rat poking its head out and eyeing both ways — hesitating instead of deciding.',
      origin: 'From the Records of the Grand Historian, describing a minister who would not take either side before Emperor Wu.',
      usage: 'Used to needle someone who keeps putting the choice off.' },
  },
  {
    slug: 'balbonsaegwon', hanja: '拔本塞源', simplified: '拔本塞源', reading: '발본색원',
    pinyin: 'bá běn sè yuán', chars: ['뺄 발', '근본 본', '막을 색', '근원 원'],
    category: '상황·형세', icon: '🌿',
    ko: { title: '발본색원', meaning: '뿌리를 뽑고 근원을 막는다는 뜻으로, 문제의 바탕까지 없앤다는 말입니다.',
      origin: '《춘추좌씨전》 소공 9년의 구절에서 나왔습니다. 본디 뿌리를 뽑으면 나무가 죽는다는 경고에 가까웠습니다.',
      usage: '겉만 손보지 않고 원인을 끝까지 없앨 때 씁니다.' },
    en: { title: 'Bal-bon-saeg-won', meaning: 'Pull the root, block the spring — removing a problem at its source.',
      origin: 'From the Zuo Commentary, ninth year of Duke Zhao, where it read closer to a warning that a tree dies once its root is pulled.',
      usage: 'Used of dealing with the cause rather than tidying the surface.' },
  },
];
