/**
 * 글자별 새김의 영어판.
 *
 * 한국어 새김("넉 사")은 훈과 음을 붙여 읽는 우리 방식이라 영어 화면에서는
 * 읽히지 않는다. 영어는 글자의 뜻만 짧게 적고, 중국어 화면은 글자를 이미
 * 알므로 그 글자의 한국어 음을 대신 보여준다(독음을 네 자로 쪼개 쓴다).
 */
export const GLOSS_EN: Record<string, [string, string, string, string]> = {
  yubimuhwan: ['have', 'prepare', 'without', 'worry'],
  yeokjisaji: ['swap', 'place', 'think', 'of it'],
  chojiilgwan: ['first', 'resolve', 'one', 'run through'],
  myeongbulheojeon: ['name', 'not', 'empty', 'passed on'],
  cheongchuleoram: ['blue', 'come out', 'from', 'indigo'],
  daegimanseong: ['great', 'vessel', 'late', 'completed'],
  ongojisin: ['review', 'the old', 'know', 'the new'],
  susinjega: ['cultivate', 'self', 'order', 'household'],
  anbunjijok: ['at ease', 'one’s lot', 'know', 'enough'],

  ugongisan: ['foolish', 'old man', 'move', 'mountain'],
  maburakchim: ['grind', 'axe', 'make', 'needle'],
  hyeongseoljigong: ['firefly', 'snow', 'of', 'merit'],
  jeolchibusim: ['grind', 'teeth', 'rot', 'heart'],
  wasinsangdam: ['lie on', 'firewood', 'taste', 'gall'],
  baekjeolbulgul: ['hundred', 'break', 'not', 'bend'],
  chiljeonpalgi: ['seven', 'fall', 'eight', 'rise'],
  jugyeongyadok: ['day', 'plough', 'night', 'read'],
  ilchwiwoljang: ['day', 'advance', 'month', 'grow'],

  gwanpojigyo: ['Guan', 'Bao', 'of', 'friendship'],
  jukmagou: ['bamboo', 'horse', 'old', 'friend'],
  baengnyeonhaero: ['hundred', 'years', 'together', 'grow old'],
  donggodongnak: ['same', 'hardship', 'same', 'joy'],
  injisangjeong: ['human', 'of', 'ordinary', 'feeling'],
  yuyusangjong: ['kind', 'kind', 'each other', 'follow'],
  gyeolchoboeun: ['tie', 'grass', 'repay', 'kindness'],
  baeeunmangdeok: ['turn back on', 'kindness', 'forget', 'virtue'],
  jogangjicheo: ['lees', 'chaff', 'of', 'wife'],

  samyeonchoga: ['four', 'sides', 'Chu', 'song'],
  jintoeyangnan: ['advance', 'retreat', 'both', 'hard'],
  nuranjiwi: ['piled', 'eggs', 'of', 'peril'],
  pungjeondeunghwa: ['wind', 'before', 'lamp', 'flame'],
  orimujung: ['five', 'li', 'fog', 'within'],
  seolsanggasang: ['snow', 'upon', 'add', 'frost'],
  jeonhwawibok: ['turn', 'disaster', 'into', 'fortune'],
  saeongjima: ['frontier', 'old man', 'of', 'horse'],
  ilchokjeukbal: ['one', 'touch', 'at once', 'goes off'],

  gwalmoksangdae: ['rub', 'eyes', 'each other', 'face'],
  gyohaksangjang: ['teach', 'learn', 'each other', 'grow'],
  dadaikseon: ['many', 'many', 'the more', 'the better'],
  muniljisip: ['hear', 'one', 'know', 'ten'],
  gyeongmulchiji: ['investigate', 'things', 'reach', 'knowing'],
  hagisiseup: ['learn', 'and', 'in season', 'practise'],
  bulchihamun: ['not', 'ashamed', 'below', 'to ask'],
  simsasukgo: ['deep', 'thought', 'ripe', 'weighing'],

  eonjungyugol: ['words', 'within', 'there is', 'bone'],
  choncheolsarin: ['inch', 'of steel', 'kill', 'a person'],
  isimjeonsim: ['by', 'mind', 'transmit', 'mind'],
  gamaniseol: ['sweet', 'words', 'profitable', 'talk'],
  yugumueon: ['have', 'mouth', 'without', 'words'],
  ileonjiha: ['one', 'word', 'of', 'under'],
  guayubulgeup: ['exceed', 'rather', 'not', 'reach'],
  myeonggyeongjisu: ['bright', 'mirror', 'still', 'water'],
  taeyeonjajak: ['great', 'so', 'self', 'same'],
  gojingamnae: ['bitter', 'end', 'sweet', 'come'],
  ilseogijo: ['one', 'stone', 'two', 'birds'],
  eonhaengilchi: ['word', 'deed', 'one', 'reach'],
  jeoksoseongdae: ['pile', 'small', 'become', 'large'],
  gyeonmulsaengsim: ['see', 'thing', 'arise', 'mind'],
  myeongcheolbosin: ['bright', 'wise', 'keep', 'body'],
  sipbeoljimok: ['ten', 'strike', 'of', 'tree'],
  jeoktoseongsan: ['pile', 'earth', 'become', 'mountain'],
  jumagapyeon: ['running', 'horse', 'add', 'whip'],
  subulseokgwon: ['hand', 'not', 'release', 'book'],
  gakgomyeollyeo: ['carve', 'hardship', 'strive', 'urge'],
  jagangbulsik: ['self', 'strong', 'not', 'rest'],
  yujigyeongseong: ['have', 'will', 'at last', 'achieve'],
  jeolchatakma: ['cut', 'file', 'chisel', 'polish'],
  maksangmakha: ['no', 'above', 'no', 'below'],
  nanhyeongnanje: ['hard', 'elder', 'hard', 'younger'],
  taesanbukdu: ['great', 'mountain', 'north', 'dipper'],
  gungyeilhak: ['flock', 'chicken', 'one', 'crane'],
  owoldongju: ['Wu', 'Yue', 'same', 'boat'],
  dongsangimong: ['same', 'bed', 'different', 'dream'],
  gandamsangjo: ['liver', 'gall', 'each other', 'shine'],
  sueojigyo: ['water', 'fish', 'of', 'bond'],
  chomijigeup: ['scorch', 'eyebrow', 'of', 'urgent'],
  baekcheokgandu: ['hundred', 'foot', 'pole', 'top'],
  myeongjaegyeonggak: ['life', 'rests', 'instant', 'moment'],
  soksumuchaek: ['bind', 'hand', 'no', 'plan'],
  gihojise: ['ride', 'tiger', 'of', 'momentum'],
  geumsangcheomhwa: ['brocade', 'on', 'add', 'flower'],
  eobujiri: ['fishing', 'father', 'of', 'gain'],
  gyeranyugol: ['chicken', 'egg', 'have', 'bone'],
  jumagansan: ['running', 'horse', 'view', 'mountain'],
  dokseosammae: ['read', 'book', 'three', 'absorption'],
  gaegwonyuik: ['open', 'book', 'have', 'gain'],
  bakhakdasik: ['broad', 'learn', 'much', 'know'],
  iigwanji: ['one', 'by', 'thread', 'it'],
  jihaenghabil: ['know', 'act', 'join', 'one'],
  dokseobaekpyeon: ['read', 'book', 'hundred', 'times'],
  baramgangi: ['broad', 'view', 'strong', 'remember'],
  cheongunjiji: ['blue', 'cloud', 'of', 'ambition'],
  eobulseongseol: ['word', 'not', 'form', 'statement'],
  gapronulbak: ['first', 'argue', 'second', 'refute'],
  hoengseolsuseol: ['across', 'speak', 'upright', 'speak'],
  ileonbangu: ['one', 'word', 'half', 'phrase'],
  gyoeonyeongsaek: ['crafted', 'word', 'pleasing', 'look'],
  myeongsilsangbu: ['name', 'substance', 'mutually', 'match'],
  buhwanoedong: ['attach', 'echo', 'thunder', 'same'],
  eoneododan: ['word', 'speech', 'path', 'cut'],
  dangnanggeocheol: ['mantis', 'mantis', 'block', 'wheel track'],
  gojangnanmyeong: ['alone', 'palm', 'hard', 'to sound'],
  samgochoryeo: ['three', 'visits', 'thatched', 'hut'],
  cheonjaeilu: ['thousand', 'years', 'one', 'meeting'],
  yongdusami: ['dragon', 'head', 'snake', 'tail'],
  eupchammasok: ['weeping', 'behead', 'Ma', 'Su'],
  gakjugugeom: ['carve', 'boat', 'seek', 'sword'],
  pajukjise: ['split', 'bamboo', 'of', 'momentum'],
  hwangoltaltae: ['change', 'bone', 'seize', 'womb'],
  gyeonmunbalgeom: ['see', 'mosquito', 'draw', 'sword'],
  suseoyangdan: ['head', 'rat', 'two', 'ends'],
  balbonsaegwon: ['pull out', 'root', 'block', 'source'],
  gyeonggeomangdong: ['light', 'lift', 'reckless', 'move'],
  heosimtanhoe: ['empty', 'heart', 'open', 'bosom'],
  bulcheoljuya: ['not', 'set aside', 'day', 'night'],
  bulmyeonbulhyu: ['not', 'sleep', 'not', 'rest'],
  baegajeolhyeon: ['Bo', 'Ya', 'sever', 'strings'],
  tasanjiseok: ['other', 'mountain', 'of', 'stone'],
  gorimuwon: ['alone', 'stand', 'without', 'help'],
  yeonmokguueo: ['climb', 'tree', 'seek', 'fish'],
  nangjungjichu: ['sack', 'inside', 'of', 'awl'],
  husaenggaoe: ['later', 'born', 'worth', 'fearing'],
  yumyeongmusil: ['have', 'name', 'without', 'substance'],
  geumgwaokjo: ['gold', 'article', 'jade', 'clause'],
};
