/** 사자성어 - 배움·지혜 (8) */
import type { Idiom } from './types.ts';

export const LEARNING_IDIOMS: Idiom[] = [
  {
    slug: 'gwalmoksangdae', hanja: '刮目相對', simplified: '刮目相对', reading: '괄목상대',
    pinyin: 'guā mù xiāng duì', chars: ['긁을 괄', '눈 목', '서로 상', '대할 대'],
    category: '배움·지혜', icon: '🔍',
    ko: { title: '괄목상대', meaning: '눈을 비비고 다시 본다는 뜻으로, 상대의 실력이 놀랍게 늘었다는 말입니다.',
      origin: '《삼국지》에서 여몽의 학문이 크게 늘자 노숙이 "눈을 비비고 다시 볼 만하다"고 한 데서 왔습니다.',
      usage: '짧은 사이에 부쩍 성장한 사람을 칭찬할 때 씁니다.' },
    en: { title: 'Gwal-mok-sang-dae', meaning: 'Rub your eyes and look again — someone’s ability has grown astonishingly.',
      origin: 'From the Records of the Three Kingdoms: Lu Su said Lü Meng’s learning deserved a second, eye-rubbing look.',
      usage: 'A compliment for someone who improved sharply in a short time.' },
  },
  {
    slug: 'gyohaksangjang', hanja: '敎學相長', simplified: '教学相长', reading: '교학상장',
    pinyin: 'jiào xué xiāng zhǎng', chars: ['가르칠 교', '배울 학', '서로 상', '자랄 장'],
    category: '배움·지혜', icon: '🎓',
    ko: { title: '교학상장', meaning: '가르치는 일과 배우는 일이 서로를 자라게 한다는 뜻입니다.',
      origin: '《예기》 학기편에 나오는 말로, 배우는 쪽만 자란다고 보지 않은 것이 특징입니다.',
      usage: '가르치면서 오히려 더 배운다는 경험을 말할 때 씁니다.' },
    en: { title: 'Gyo-hak-sang-jang', meaning: 'Teaching and learning grow each other.',
      origin: 'From the "Records of Learning" chapter of the Book of Rites.',
      usage: 'Used to describe learning more by teaching than by studying alone.' },
  },
  {
    slug: 'dadaikseon', hanja: '多多益善', simplified: '多多益善', reading: '다다익선',
    pinyin: 'duō duō yì shàn', chars: ['많을 다', '많을 다', '더할 익', '착할 선'],
    category: '배움·지혜', icon: '📚',
    ko: { title: '다다익선', meaning: '많으면 많을수록 더 좋다는 뜻입니다.',
      origin: '《사기》 회음후열전에서 한신이 병사는 많을수록 좋다고 한 말에서 왔습니다.',
      usage: '자료나 연습량처럼 많을수록 유리한 것을 말할 때 씁니다.' },
    en: { title: 'Da-da-ik-seon', meaning: 'The more, the better.',
      origin: 'From the Records of the Grand Historian, where Han Xin said the more troops the better.',
      usage: 'Used of things like reference material or practice, where quantity helps.' },
  },
  {
    slug: 'muniljisip', hanja: '聞一知十', simplified: '闻一知十', reading: '문일지십',
    pinyin: 'wén yī zhī shí', chars: ['들을 문', '한 일', '알 지', '열 십'],
    category: '배움·지혜', icon: '💡',
    ko: { title: '문일지십', meaning: '하나를 들으면 열을 안다는 뜻으로, 매우 총명함을 말합니다.',
      origin: '《논어》 공야장편에서 자공이 안회를 두고 한 말입니다.',
      usage: '설명 한 번에 전체를 이해하는 사람을 이를 때 씁니다.' },
    en: { title: 'Mun-il-ji-sip', meaning: 'Hear one thing and know ten — exceptional quickness of mind.',
      origin: 'From the Analects, where Zigong says this of Yan Hui.',
      usage: 'Said of someone who grasps the whole from a single explanation.' },
  },
  {
    slug: 'gyeongmulchiji', hanja: '格物致知', simplified: '格物致知', reading: '격물치지',
    pinyin: 'gé wù zhì zhī', chars: ['이를 격', '만물 물', '이를 치', '알 지'],
    category: '배움·지혜', icon: '🧠',
    ko: { title: '격물치지', meaning: '사물을 깊이 따져 앎에 이른다는 뜻입니다.',
      origin: '《대학》에 나오는 말로, 주자학의 핵심 공부법으로 자리 잡았습니다.',
      usage: '현상을 직접 파고들어 원리를 얻는 태도를 이를 때 씁니다.' },
    en: { title: 'Gyeong-mul-chi-ji', meaning: 'Investigate things to reach knowledge.',
      origin: 'From the Great Learning; it became the central method of Neo-Confucian study.',
      usage: 'Describes getting at principles by digging into the phenomena themselves.' },
  },
  {
    slug: 'hagisiseup', hanja: '學而時習', simplified: '学而时习', reading: '학이시습',
    pinyin: 'xué ér shí xí', chars: ['배울 학', '말이을 이', '때 시', '익힐 습'],
    category: '배움·지혜', icon: '📖',
    ko: { title: '학이시습', meaning: '배우고 때맞춰 익힌다는 뜻입니다.',
      origin: '《논어》의 첫 문장 "학이시습지 불역열호(學而時習之 不亦說乎)"에서 왔습니다.',
      usage: '배운 것을 복습하는 습관의 중요함을 말할 때 인용합니다.' },
    en: { title: 'Hak-i-si-seup', meaning: 'Learn, and practise it in due time.',
      origin: 'The opening line of the Analects: "To learn and practise in season — is that not a joy?"',
      usage: 'Quoted on the importance of reviewing what you have learned.' },
  },
  {
    slug: 'bulchihamun', hanja: '不恥下問', simplified: '不耻下问', reading: '불치하문',
    pinyin: 'bù chǐ xià wèn', chars: ['아닐 불', '부끄러울 치', '아래 하', '물을 문'],
    category: '배움·지혜', icon: '🙏',
    ko: { title: '불치하문', meaning: '아랫사람에게 묻는 것을 부끄러워하지 않는다는 뜻입니다.',
      origin: '《논어》 공야장편에서 공자가 공문자를 평한 말에서 왔습니다.',
      usage: '경력이 적은 사람에게도 배우려는 태도를 이를 때 씁니다.' },
    en: { title: 'Bul-chi-ha-mun', meaning: 'Not ashamed to ask those below you.',
      origin: 'From the Analects, in Confucius’ assessment of Kong Wenzi.',
      usage: 'Describes a willingness to learn even from someone junior to you.' },
  },
  {
    slug: 'simsasukgo', hanja: '深思熟考', simplified: '深思熟考', reading: '심사숙고',
    pinyin: 'shēn sī shú kǎo', chars: ['깊을 심', '생각 사', '익을 숙', '생각할 고'],
    category: '배움·지혜', icon: '⏳',
    ko: { title: '심사숙고', meaning: '깊이 생각하고 곰곰이 헤아린다는 뜻입니다.',
      origin: '한국에서 널리 쓰이는 표현으로, 중국에서는 심사숙려(深思熟慮)를 더 많이 씁니다.',
      usage: '중요한 결정을 서둘러 내리지 말라고 할 때 씁니다.' },
    en: { title: 'Sim-sa-suk-go', meaning: 'Think deeply and weigh it thoroughly.',
      origin: 'Common in Korea; Chinese more often uses the form ending in 熟慮.',
      usage: 'Said when urging someone not to rush an important decision.' },
  },
];
