/** 사자성어 - 배움·지혜 둘째 묶음 (8) */
import type { Idiom } from './types.ts';

export const LEARNING2_IDIOMS: Idiom[] = [
  {
    slug: 'dokseosammae', hanja: '讀書三昧', simplified: '读书三昧', reading: '독서삼매',
    pinyin: 'dú shū sān mèi', chars: ['읽을 독', '글 서', '석 삼', '어두울 매'],
    category: '배움·지혜', icon: '📖',
    ko: { title: '독서삼매', meaning: '책 읽기에 푹 빠져 다른 것을 잊은 상태를 뜻합니다.',
      origin: '삼매(三昧)는 산스크리트 사마디를 음으로 옮긴 불교 용어로 한곳에 집중한 상태를 뜻합니다.',
      usage: '몰입해서 읽는 모습을 두고 씁니다.' },
    en: { title: 'Dok-seo-sam-mae', meaning: 'So absorbed in a book that everything else falls away.',
      origin: 'Sammae transliterates the Sanskrit samadhi, the Buddhist term for one-pointed absorption.',
      usage: 'Used to describe someone deep in a book.' },
    zh: { title: '读书三昧', meaning: '沉浸于读书而忘却其他。',
      origin: '「三昧」为梵语samadhi的音译，佛教中指专注一境的状态。',
      usage: '用于形容全神贯注地阅读，中韩通用。' },
  },
  {
    slug: 'gaegwonyuik', hanja: '開卷有益', simplified: '开卷有益', reading: '개권유익',
    pinyin: 'kāi juàn yǒu yì', chars: ['열 개', '책 권', '있을 유', '더할 익'],
    category: '배움·지혜', icon: '📗',
    ko: { title: '개권유익', meaning: '책을 펴면 이로움이 있다, 곧 읽는 것 자체가 남는다는 뜻입니다.',
      origin: '송 태종이 매일 《태평어람》을 읽으며 한 말로 전해집니다.',
      usage: '무엇을 읽을지 고민하는 사람에게 우선 펴 보라고 권할 때 씁니다.' },
    en: { title: 'Gae-gwon-yu-ik', meaning: 'Open a book and there is gain in it.',
      origin: 'Attributed to Emperor Taizong of Song, who read the Taiping Yulan daily.',
      usage: 'Said to someone agonising over what to read — just open one.' },
    zh: { title: '开卷有益', meaning: '打开书就有收获。',
      origin: '相传为宋太宗日读《太平御览》时所言。',
      usage: '用于劝仍在挑书的人先翻开看看，中韩通用。' },
  },
  {
    slug: 'bakhakdasik', hanja: '博學多識', simplified: '博学多识', reading: '박학다식',
    pinyin: 'bó xué duō shí', chars: ['넓을 박', '배울 학', '많을 다', '알 식'],
    category: '배움·지혜', icon: '🎓',
    ko: { title: '박학다식', meaning: '널리 배워 아는 것이 많다는 뜻입니다.',
      origin: '박학(博學)은 《중용》의 학문하는 다섯 단계 가운데 첫째로 나옵니다.',
      usage: '분야를 가리지 않고 아는 사람을 칭찬할 때 씁니다.' },
    en: { title: 'Bak-hak-da-sik', meaning: 'Widely learned and knowing much.',
      origin: 'Bak-hak — broad learning — appears as the first of the five stages of study in the Doctrine of the Mean.',
      usage: 'Praise for someone knowledgeable across fields.' },
    zh: { title: '博学多识', meaning: '学识广博，见闻丰富。',
      origin: '「博学」见于《中庸》，为治学五阶之首。',
      usage: '用于称赞跨领域皆有见识的人，中韩通用。' },
  },
  {
    slug: 'iigwanji', hanja: '一以貫之', simplified: '一以贯之', reading: '일이관지',
    pinyin: 'yī yǐ guàn zhī', chars: ['한 일', '써 이', '꿸 관', '갈 지'],
    category: '배움·지혜', icon: '🧵',
    ko: { title: '일이관지', meaning: '하나의 이치로 전체를 꿰뚫는다는 뜻입니다.',
      origin: '《논어》 위령공편에서 공자가 자기 학문을 두고 한 말입니다.',
      usage: '흩어진 사실을 하나의 원리로 설명해 낼 때 씁니다.' },
    en: { title: 'I-i-gwan-ji', meaning: 'Threading the whole through with a single principle.',
      origin: 'From the Analects, where Confucius describes his own learning this way.',
      usage: 'Used when scattered facts are explained by one underlying rule.' },
    zh: { title: '一以贯之', meaning: '用一个道理贯通全部。',
      origin: '出自《论语·卫灵公》，孔子自述其学。',
      usage: '用于以一条原理解释纷杂事实时，中韩通用。' },
  },
  {
    slug: 'jihaenghabil', hanja: '知行合一', simplified: '知行合一', reading: '지행합일',
    pinyin: 'zhī xíng hé yī', chars: ['알 지', '다닐 행', '합할 합', '한 일'],
    category: '배움·지혜', icon: '🔗',
    ko: { title: '지행합일', meaning: '아는 것과 행하는 것이 하나여야 한다는 뜻입니다.',
      origin: '명나라 왕수인(왕양명)이 세운 명제로, 앎이 행동으로 드러나지 않으면 참된 앎이 아니라고 봤습니다.',
      usage: '이론만 아는 상태를 지적하거나, 배운 것을 실천하라고 권할 때 씁니다.' },
    en: { title: 'Ji-haeng-hab-il', meaning: 'Knowing and doing are one.',
      origin: 'The thesis of Wang Yangming of Ming China: knowledge that does not show in action is not knowledge.',
      usage: 'Used to criticise theory without practice, or to urge acting on what one has learned.' },
    zh: { title: '知行合一', meaning: '知与行本为一体。',
      origin: '明代王阳明所立命题：不见于行的知，并非真知。',
      usage: '用于批评只懂理论，或劝人把所学付诸实践，中韩通用。' },
  },
  {
    slug: 'dokseobaekpyeon', hanja: '讀書百遍', simplified: '读书百遍', reading: '독서백편',
    pinyin: 'dú shū bǎi biàn', chars: ['읽을 독', '글 서', '일백 백', '두루 편'],
    category: '배움·지혜', icon: '🔂',
    ko: { title: '독서백편', meaning: '백 번 읽으면 뜻이 저절로 드러난다는 뜻입니다.',
      origin: '《삼국지》 위서에서 동우가 제자에게 "백 번 읽으면 뜻이 스스로 통한다"고 한 말에서 나왔습니다.',
      usage: '어려운 글을 붙잡고 있는 사람에게 반복해 읽으라고 권할 때 씁니다.' },
    en: { title: 'Dok-seo-baek-pyeon', meaning: 'Read it a hundred times and the meaning reveals itself.',
      origin: 'From the Wei records in the Three Kingdoms, where Dong Yu told his students the sense comes of itself after a hundred readings.',
      usage: 'Advice to someone stuck on a difficult text: read it again.' },
    zh: { title: '读书百遍', meaning: '读上百遍，其义自见。',
      origin: '出自《三国志·魏书》，董遇谓「读书百遍，其义自见」。',
      usage: '用于劝人反复研读难解的文章，中韩通用。' },
  },
  {
    slug: 'baramgangi', hanja: '博覽强記', simplified: '博览强记', reading: '박람강기',
    pinyin: 'bó lǎn qiáng jì', chars: ['넓을 박', '볼 람', '강할 강', '기록할 기'],
    category: '배움·지혜', icon: '🧠',
    ko: { title: '박람강기', meaning: '널리 읽고 잘 기억한다는 뜻입니다.',
      origin: '중국 역사서에서 학식이 넓고 기억력이 뛰어난 인물을 평할 때 쓰던 표현입니다.',
      usage: '읽은 것을 잘 꺼내 쓰는 사람을 칭찬할 때 씁니다.' },
    en: { title: 'Ba-ram-gang-gi', meaning: 'Reads widely and remembers well.',
      origin: 'A standing phrase in Chinese histories for someone of broad learning and strong memory.',
      usage: 'Praise for someone who can pull up what they have read.' },
    zh: { title: '博览强记', meaning: '博览群书而记忆力强。',
      origin: '中国史书中评价学识广博、记性极佳者的惯用语。',
      usage: '用于称赞能随时调用所读内容的人，中韩通用。' },
  },
  {
    slug: 'cheongunjiji', hanja: '靑雲之志', simplified: '青云之志', reading: '청운지지',
    pinyin: 'qīng yún zhī zhì', chars: ['푸를 청', '구름 운', '갈 지', '뜻 지'],
    category: '배움·지혜', icon: '☁️',
    ko: { title: '청운지지', meaning: '푸른 구름에 오르려는 뜻, 곧 높은 이상과 큰 포부를 뜻합니다.',
      origin: '왕발의 〈등왕각서〉에 나오는 "궁차익견 불추청운지지"에서 널리 알려졌습니다.',
      usage: '큰 뜻을 품고 공부나 일을 시작하는 사람에게 씁니다.' },
    en: { title: 'Cheong-un-ji-ji', meaning: 'The ambition to rise to the blue clouds — high aspiration.',
      origin: 'Widely known from Wang Bo’s Preface to the Pavilion of Prince Teng, on not letting hardship lower one’s aim.',
      usage: 'Used of someone starting study or work with a large ambition.' },
    zh: { title: '青云之志', meaning: '直上青云的志向，指远大的抱负。',
      origin: '因王勃《滕王阁序》「穷且益坚，不坠青云之志」而广为人知。',
      usage: '用于怀抱远志开始学业或事业的人，中韩通用。' },
  },
];
