/** 사자성어 - 관계·사람 (9) */
import type { Idiom } from './types.ts';

export const PEOPLE_IDIOMS: Idiom[] = [
  {
    slug: 'gwanpojigyo', hanja: '管鮑之交', simplified: '管鲍之交', reading: '관포지교',
    pinyin: 'guǎn bào zhī jiāo', chars: ['대롱 관', '절인어물 포', '갈 지', '사귈 교'],
    category: '관계·사람', icon: '🤝',
    ko: { title: '관포지교', meaning: '관중과 포숙아의 사귐이라는 뜻으로, 서로를 깊이 알아주는 우정을 말합니다.',
      origin: '《사기》 관안열전에서 포숙아가 관중의 재능을 알아보고 자기 자리를 양보한 이야기입니다.',
      usage: '이해를 따지지 않는 오랜 친구 사이를 이를 때 씁니다.' },
    en: { title: 'Gwan-po-ji-gyo', meaning: 'The friendship of Guan Zhong and Bao Shuya — friends who truly know each other.',
      origin: 'From the Records of the Grand Historian: Bao Shuya recognised Guan Zhong’s talent and yielded his own position to him.',
      usage: 'Describes a long friendship that does not keep accounts.' },
    zh: { title: '管鲍之交', meaning: '管仲与鲍叔牙的交情，比喻彼此深知的挚友。',
      origin: '出自《史记·管晏列传》，鲍叔牙识管仲之才而让位于他。',
      usage: '形容不计得失的多年挚友之情，中韩通用。' },
  },
  {
    slug: 'jukmagou', hanja: '竹馬故友', simplified: '竹马故友', reading: '죽마고우',
    pinyin: 'zhú mǎ gù yǒu', chars: ['대 죽', '말 마', '옛 고', '벗 우'],
    category: '관계·사람', icon: '👥',
    ko: { title: '죽마고우', meaning: '대나무 말을 타고 놀던 옛 친구라는 뜻으로, 어릴 때부터 함께 자란 벗을 말합니다.',
      origin: '《세설신어》에서 유래했으며, 어린 시절 죽마를 타고 놀던 사이를 가리킵니다.',
      usage: '초등학교 때부터 알고 지낸 친구를 소개할 때 씁니다.' },
    en: { title: 'Juk-ma-go-u', meaning: 'An old friend from bamboo-horse days — someone you grew up with.',
      origin: 'From the Shishuo Xinyu, referring to children who played together on bamboo hobby-horses.',
      usage: 'How you introduce a friend you have known since primary school.' },
    zh: { title: '竹马故友', meaning: '骑竹马一起玩过的老朋友，指从小一起长大的伙伴。',
      origin: '出自《世说新语》；中文更常说「青梅竹马」或「总角之交」。',
      usage: '介绍从小学起就相识的朋友时使用。' },
  },
  {
    slug: 'baengnyeonhaero', hanja: '百年偕老', simplified: '百年偕老', reading: '백년해로',
    pinyin: 'bǎi nián xié lǎo', chars: ['일백 백', '해 년', '함께 해', '늙을 로'],
    category: '관계·사람', icon: '💕',
    ko: { title: '백년해로', meaning: '부부가 백 년을 함께 늙어간다는 뜻입니다.',
      origin: '《시경》의 "여자해로(與子偕老)"에서 비롯된 표현입니다.',
      usage: '결혼식 축사와 청첩장에서 가장 흔히 쓰이는 말입니다.' },
    en: { title: 'Baeng-nyeon-hae-ro', meaning: 'Growing old together for a hundred years.',
      origin: 'Derived from the Book of Odes line about growing old alongside one another.',
      usage: 'The most common phrase in Korean wedding toasts and invitations.' },
    zh: { title: '百年偕老', meaning: '夫妻相伴到老，共度百年。',
      origin: '源自《诗经》「与子偕老」。',
      usage: '韩国婚礼致辞和请帖中最常见的祝词；中文多说「白头偕老」。' },
  },
  {
    slug: 'donggodongnak', hanja: '同苦同樂', simplified: '同苦同乐', reading: '동고동락',
    pinyin: 'tóng kǔ tóng lè', chars: ['한가지 동', '쓸 고', '한가지 동', '즐길 락'],
    category: '관계·사람', icon: '🫂',
    ko: { title: '동고동락', meaning: '괴로움과 즐거움을 함께한다는 뜻입니다.',
      origin: '한국에서 널리 쓰이는 표현으로, 중국 고전의 "여민동락(與民同樂)" 계열 어법과 통합니다.',
      usage: '오래 함께 일한 동료나 전우를 이를 때 씁니다.' },
    en: { title: 'Dong-go-dong-nak', meaning: 'Sharing the hardship and the joy alike.',
      origin: 'Widely used in Korea, in the same idiom family as the classical phrase about sharing joy with the people.',
      usage: 'Said of colleagues or comrades who have been through a lot together.' },
    zh: { title: '同苦同乐', meaning: '苦与乐都一同承担、一同享受。',
      origin: '在韩国广泛使用，与古典「与民同乐」的语法同源；中文多说「同甘共苦」。',
      usage: '用于共事多年的同事或战友。' },
  },
  {
    slug: 'injisangjeong', hanja: '人之常情', simplified: '人之常情', reading: '인지상정',
    pinyin: 'rén zhī cháng qíng', chars: ['사람 인', '갈 지', '항상 상', '뜻 정'],
    category: '관계·사람', icon: '❤️',
    ko: { title: '인지상정', meaning: '사람이면 누구나 가지는 보통의 마음이라는 뜻입니다.',
      origin: '중국 고전에서 널리 쓰인 표현으로, 인간의 자연스러운 감정을 가리킵니다.',
      usage: '누군가의 서운함이나 욕심을 이해할 만하다고 감쌀 때 씁니다.' },
    en: { title: 'In-ji-sang-jeong', meaning: 'The ordinary feeling any human being would have.',
      origin: 'A phrase common in Chinese classics, referring to natural human emotion.',
      usage: 'Used to say that someone’s disappointment or wanting is understandable.' },
    zh: { title: '人之常情', meaning: '人人都会有的寻常心情。',
      origin: '古籍中常见，指人自然而然的情感。',
      usage: '用于表示某人的失落或欲望情有可原，中韩通用。' },
  },
  {
    slug: 'yuyusangjong', hanja: '類類相從', simplified: '类类相从', reading: '유유상종',
    pinyin: 'lèi lèi xiāng cóng', chars: ['무리 류', '무리 류', '서로 상', '좇을 종'],
    category: '관계·사람', icon: '👫',
    ko: { title: '유유상종', meaning: '같은 무리끼리 서로 따른다는 뜻으로, 비슷한 사람끼리 모인다는 말입니다.',
      origin: '《주역》 계사전의 "방이유취 물이군분(方以類聚 物以群分)"에서 온 어법입니다.',
      usage: '좋은 뜻으로도 쓰지만, 나쁜 무리를 가리킬 때 더 자주 씁니다.' },
    en: { title: 'Yu-yu-sang-jong', meaning: 'Like follows like — similar people gather together.',
      origin: 'From the Book of Changes: things group by kind and divide by category.',
      usage: 'Sometimes neutral, but more often said of a bad crowd.' },
    zh: { title: '类类相从', meaning: '同类互相追随，比喻相似的人聚在一起。',
      origin: '语出《易经·系辞》「方以类聚，物以群分」；中文多说「物以类聚」。',
      usage: '可中性使用，但在韩国更常带贬义。' },
  },
  {
    slug: 'gyeolchoboeun', hanja: '結草報恩', simplified: '结草报恩', reading: '결초보은',
    pinyin: 'jié cǎo bào ēn', chars: ['맺을 결', '풀 초', '갚을 보', '은혜 은'],
    category: '관계·사람', icon: '🙏',
    ko: { title: '결초보은', meaning: '풀을 묶어 은혜를 갚는다는 뜻으로, 죽어서도 은혜를 잊지 않는다는 말입니다.',
      origin: '《춘추좌전》에서 은혜를 입은 이의 망령이 풀을 묶어 적의 말을 넘어뜨려 은인을 살렸다는 고사입니다.',
      usage: '큰 도움을 받았을 때 감사를 다짐하며 쓰는 표현입니다.' },
    en: { title: 'Gyeol-cho-bo-eun', meaning: 'Tie the grass to repay a kindness — gratitude that outlasts death.',
      origin: 'From the Zuo Commentary: the spirit of a man who had been shown mercy knotted grass to trip an enemy’s horse and save his benefactor.',
      usage: 'Said when vowing to repay a great favour.' },
    zh: { title: '结草报恩', meaning: '打结草茎以报恩，形容至死不忘恩情。',
      origin: '出自《左传》，受恩者的魂灵结草绊倒敌马，救了恩人。',
      usage: '受到大恩时表达报答之心；中文多说「结草衔环」。' },
  },
  {
    slug: 'baeeunmangdeok', hanja: '背恩忘德', simplified: '背恩忘德', reading: '배은망덕',
    pinyin: 'bèi ēn wàng dé', chars: ['등 배', '은혜 은', '잊을 망', '덕 덕'],
    category: '관계·사람', icon: '⚖️',
    ko: { title: '배은망덕', meaning: '은혜를 등지고 덕을 잊는다는 뜻입니다.',
      origin: '중국 고전 어법에서 온 표현으로, 한국에서는 은혜를 저버린 행위를 강하게 비난할 때 굳어졌습니다.',
      usage: '도와준 사람에게 해를 끼친 경우를 꾸짖을 때 씁니다.' },
    en: { title: 'Bae-eun-mang-deok', meaning: 'Turning your back on kindness and forgetting the good done to you.',
      origin: 'From classical Chinese phrasing; in Korean it hardened into a strong rebuke for ingratitude.',
      usage: 'Used to condemn someone who harmed the person who helped them.' },
    zh: { title: '背恩忘德', meaning: '背弃恩情、忘掉他人的好处。',
      origin: '源自古汉语表述；在韩国固定为对忘恩行为的严厉指责。',
      usage: '用于谴责恩将仇报者；中文多说「忘恩负义」。' },
  },
  {
    slug: 'jogangjicheo', hanja: '糟糠之妻', simplified: '糟糠之妻', reading: '조강지처',
    pinyin: 'zāo kāng zhī qī', chars: ['술지게미 조', '겨 강', '갈 지', '아내 처'],
    category: '관계·사람', icon: '🍚',
    ko: { title: '조강지처', meaning: '술지게미와 쌀겨를 함께 먹으며 고생한 아내라는 뜻입니다.',
      origin: '《후한서》 송홍전에서 송홍이 부유해진 뒤에도 가난할 때의 아내를 버리지 않겠다고 한 말에서 왔습니다.',
      usage: '어려운 시절을 함께 견딘 배우자를 이를 때 씁니다.' },
    en: { title: 'Jo-gang-ji-cheo', meaning: 'The wife who shared the dregs and chaff — a spouse who endured poverty with you.',
      origin: 'From the Book of the Later Han: Song Hong refused to set aside the wife who had been with him when he was poor.',
      usage: 'Said of a partner who came through the hard years with you.' },
    zh: { title: '糟糠之妻', meaning: '共食酒糟米糠、一同受苦的妻子。',
      origin: '出自《后汉书·宋弘传》，宋弘富贵后仍不弃贫贱时的妻子。',
      usage: '指共渡艰难岁月的伴侣，中韩通用。' },
  },
];
