/** 사자성어 - 관계·사람 둘째 묶음 (8) */
import type { Idiom } from './types.ts';

export const PEOPLE2_IDIOMS: Idiom[] = [
  {
    slug: 'maksangmakha', hanja: '莫上莫下', simplified: '莫上莫下', reading: '막상막하',
    pinyin: 'mò shàng mò xià', chars: ['없을 막', '위 상', '없을 막', '아래 하'],
    category: '관계·사람', icon: '⚖️',
    ko: { title: '막상막하', meaning: '위도 아래도 없다, 곧 실력이 서로 엇비슷하다는 뜻입니다.',
      origin: '중국 고전에 그대로 나오지 않는 한국식 성어로, 우열을 가릴 수 없다는 뜻으로 굳어졌습니다.',
      usage: '경기나 경쟁에서 승부를 예측하기 어려울 때 씁니다.' },
    en: { title: 'Mak-sang-mak-ha', meaning: 'Neither above nor below — evenly matched.',
      origin: 'A Korean coinage rather than a Chinese classic, settled into meaning that neither side can be ranked higher.',
      usage: 'Used when a match or a contest is too close to call.' },
  },
  {
    slug: 'nanhyeongnanje', hanja: '難兄難弟', simplified: '难兄难弟', reading: '난형난제',
    pinyin: 'nán xiōng nán dì', chars: ['어려울 난', '형 형', '어려울 난', '아우 제'],
    category: '관계·사람', icon: '👬',
    ko: { title: '난형난제', meaning: '누구를 형이라 하고 누구를 아우라 하기 어렵다, 곧 둘이 다 뛰어나다는 뜻입니다.',
      origin: '《세설신어》에서 진식의 두 아들을 두고 우열을 가릴 수 없다고 한 데서 나왔습니다.',
      usage: '두 후보나 두 작품이 모두 훌륭할 때 씁니다.' },
    en: { title: 'Nan-hyeong-nan-je', meaning: 'Hard to say which is the elder brother — both are outstanding.',
      origin: 'From the Shishuo Xinyu, on the two sons of Chen Shi, neither of whom could be ranked above the other.',
      usage: 'Used when two candidates or two works are both excellent.' },
  },
  {
    slug: 'taesanbukdu', hanja: '泰山北斗', simplified: '泰山北斗', reading: '태산북두',
    pinyin: 'tài shān běi dǒu', chars: ['클 태', '메 산', '북쪽 북', '말 두'],
    category: '관계·사람', icon: '⭐',
    ko: { title: '태산북두', meaning: '태산과 북두칠성처럼 그 분야에서 우러러보는 큰 인물을 뜻합니다.',
      origin: '《신당서》에서 한유를 두고 학자들이 태산과 북두처럼 우러렀다고 한 데서 나왔습니다.',
      usage: '학계나 예술계의 원로를 높여 부를 때 씁니다.' },
    en: { title: 'Tae-san-buk-du', meaning: 'Mount Tai and the Northern Dipper — a towering figure in a field.',
      origin: 'From the New History of Tang, where scholars looked up to Han Yu as to Mount Tai and the Dipper.',
      usage: 'An honorific for an elder statesman of a discipline or an art.' },
  },
  {
    slug: 'gungyeilhak', hanja: '群鷄一鶴', simplified: '群鸡一鹤', reading: '군계일학',
    pinyin: 'qún jī yī hè', chars: ['무리 군', '닭 계', '한 일', '학 학'],
    category: '관계·사람', icon: '🦢',
    ko: { title: '군계일학', meaning: '닭 무리 속의 학 한 마리, 곧 여럿 가운데 유난히 뛰어난 사람을 뜻합니다.',
      origin: '《진서》 혜소전에서 혜소를 두고 닭 무리 속의 학 같다고 한 데서 나왔습니다.',
      usage: '한 사람의 실력이 주위와 확연히 다를 때 씁니다.' },
    en: { title: 'Gun-gye-il-hak', meaning: 'One crane among the chickens — the standout in a crowd.',
      origin: 'From the Book of Jin, where Xi Shao was likened to a crane among fowl.',
      usage: 'Used when one person’s ability is plainly a level above the rest.' },
  },
  {
    slug: 'owoldongju', hanja: '呉越同舟', simplified: '吴越同舟', reading: '오월동주',
    pinyin: 'wú yuè tóng zhōu', chars: ['나라 오', '나라 월', '같을 동', '배 주'],
    category: '관계·사람', icon: '⛵',
    ko: { title: '오월동주', meaning: '원수인 오나라와 월나라 사람이 한 배를 탄다, 곧 사이가 나쁜 사람이 어쩔 수 없이 함께한다는 뜻입니다.',
      origin: '《손자》 구지편에서 배가 뒤집힐 위기에는 원수도 서로 돕는다고 한 데서 나왔습니다.',
      usage: '경쟁 관계인 두 회사가 한 사업에 손을 잡을 때 씁니다.' },
    en: { title: 'O-wol-dong-ju', meaning: 'Wu and Yue in the same boat — enemies forced to share a situation.',
      origin: 'From Sun Tzu, on how even enemies help each other when the boat is about to capsize.',
      usage: 'Used when rival companies join on a single project.' },
  },
  {
    slug: 'dongsangimong', hanja: '同床異夢', simplified: '同床异梦', reading: '동상이몽',
    pinyin: 'tóng chuáng yì mèng', chars: ['같을 동', '평상 상', '다를 이', '꿈 몽'],
    category: '관계·사람', icon: '💭',
    ko: { title: '동상이몽', meaning: '같은 자리에 누워 다른 꿈을 꾼다, 곧 함께 있어도 생각이 다르다는 뜻입니다.',
      origin: '송나라 진량의 글에서 나온 표현으로 겉으로만 뜻이 맞는 상태를 가리킵니다.',
      usage: '합의문에는 서명했지만 속셈이 다른 상황을 두고 씁니다.' },
    en: { title: 'Dong-sang-i-mong', meaning: 'Same bed, different dreams — together in place but not in intent.',
      origin: 'From a Song-era text by Chen Liang, describing agreement that is only on the surface.',
      usage: 'Used when two sides sign the same document with different intentions.' },
  },
  {
    slug: 'gandamsangjo', hanja: '肝膽相照', simplified: '肝胆相照', reading: '간담상조',
    pinyin: 'gān dǎn xiāng zhào', chars: ['간 간', '쓸개 담', '서로 상', '비칠 조'],
    category: '관계·사람', icon: '🫂',
    ko: { title: '간담상조', meaning: '간과 쓸개를 서로 비추듯 속마음까지 터놓고 지낸다는 뜻입니다.',
      origin: '한유가 유종원을 기리는 글에서 벗의 사귐을 두고 쓴 말입니다.',
      usage: '오래된 친구 사이의 깊은 신뢰를 말할 때 씁니다.' },
    en: { title: 'Gan-dam-sang-jo', meaning: 'Liver and gall lit up to each other — friendship with nothing held back.',
      origin: 'From Han Yu’s memorial for Liu Zongyuan, on the nature of true friendship.',
      usage: 'Used for the deep trust between long-standing friends.' },
  },
  {
    slug: 'sueojigyo', hanja: '水魚之交', simplified: '水鱼之交', reading: '수어지교',
    pinyin: 'shuǐ yú zhī jiāo', chars: ['물 수', '고기 어', '갈 지', '사귈 교'],
    category: '관계·사람', icon: '🐟',
    ko: { title: '수어지교', meaning: '물과 고기의 사귐, 곧 떼려야 뗄 수 없는 사이를 뜻합니다.',
      origin: '《삼국지》에서 유비가 제갈량과의 관계를 물과 고기에 비유한 데서 나왔습니다.',
      usage: '서로 없으면 안 되는 동료나 부부 사이를 두고 씁니다.' },
    en: { title: 'Su-eo-ji-gyo', meaning: 'The bond of water and fish — a tie that cannot be undone.',
      origin: 'From the Records of the Three Kingdoms, where Liu Bei likened his bond with Zhuge Liang to water and fish.',
      usage: 'Used for colleagues or partners who cannot function without each other.' },
  },
];
