/** 사자성어 - 상황·형세 (9) */
import type { Idiom } from './types.ts';

export const SITUATION_IDIOMS: Idiom[] = [
  {
    slug: 'samyeonchoga', hanja: '四面楚歌', simplified: '四面楚歌', reading: '사면초가',
    pinyin: 'sì miàn chǔ gē', chars: ['넉 사', '낯 면', '초나라 초', '노래 가'],
    category: '상황·형세', icon: '⚔️',
    ko: { title: '사면초가', meaning: '사방에서 초나라 노래가 들린다는 뜻으로, 어디에도 도움을 구할 수 없는 처지를 말합니다.',
      origin: '《사기》 항우본기에서 한나라 군에 포위된 항우가 사방에서 초나라 노래를 듣고 병사들이 흩어진 고사입니다.',
      usage: '빠져나갈 길이 없는 곤경을 이를 때 씁니다.' },
    en: { title: 'Sa-myeon-cho-ga', meaning: 'Chu songs on all four sides — surrounded with nowhere to turn.',
      origin: 'From the Records of the Grand Historian: encircled by Han troops, Xiang Yu heard Chu songs from every direction and his soldiers melted away.',
      usage: 'Used of a predicament with no way out.' },
    zh: { title: '四面楚歌', meaning: '四面都传来楚歌，比喻孤立无援、走投无路。',
      origin: '出自《史记·项羽本纪》，项羽被汉军围困，闻四面楚歌而军心尽散。',
      usage: '形容毫无退路的困境，中韩通用。' },
  },
  {
    slug: 'jintoeyangnan', hanja: '進退兩難', simplified: '进退两难', reading: '진퇴양난',
    pinyin: 'jìn tuì liǎng nán', chars: ['나아갈 진', '물러날 퇴', '두 양', '어려울 난'],
    category: '상황·형세', icon: '🧩',
    ko: { title: '진퇴양난', meaning: '나아가기도 물러나기도 어렵다는 뜻입니다.',
      origin: '중국 고전에서 널리 쓰인 표현으로, 어느 쪽을 택해도 손해인 상황을 가리킵니다.',
      usage: '두 선택지가 모두 나쁠 때 씁니다.' },
    en: { title: 'Jin-toe-yang-nan', meaning: 'Hard to advance and hard to retreat.',
      origin: 'Common in Chinese classics, describing a situation where either choice costs you.',
      usage: 'Used when both options are bad.' },
    zh: { title: '进退两难', meaning: '前进和后退都很困难。',
      origin: '古籍常见，指无论选哪一边都要吃亏的处境。',
      usage: '用于两个选择都不好的情形，中韩通用。' },
  },
  {
    slug: 'nuranjiwi', hanja: '累卵之危', simplified: '累卵之危', reading: '누란지위',
    pinyin: 'lěi luǎn zhī wēi', chars: ['쌓을 루', '알 란', '갈 지', '위태할 위'],
    category: '상황·형세', icon: '🥚',
    ko: { title: '누란지위', meaning: '알을 쌓아 놓은 것처럼 위태롭다는 뜻입니다.',
      origin: '《사기》 범저열전에서 진나라의 형세를 "누란보다 위태롭다"고 표현한 데서 왔습니다.',
      usage: '조금만 건드려도 무너질 상황을 이를 때 씁니다.' },
    en: { title: 'Nu-ran-ji-wi', meaning: 'As precarious as a stack of eggs.',
      origin: 'From the Records of the Grand Historian, where Qin’s position is called more perilous than piled eggs.',
      usage: 'Describes a situation that will collapse at the slightest touch.' },
    zh: { title: '累卵之危', meaning: '像堆叠的蛋一样危险。',
      origin: '出自《史记·范雎列传》，形容秦国形势「危于累卵」。',
      usage: '形容一碰即塌的局面，中韩通用。' },
  },
  {
    slug: 'pungjeondeunghwa', hanja: '風前燈火', simplified: '风前灯火', reading: '풍전등화',
    pinyin: 'fēng qián dēng huǒ', chars: ['바람 풍', '앞 전', '등 등', '불 화'],
    category: '상황·형세', icon: '🕯️',
    ko: { title: '풍전등화', meaning: '바람 앞의 등불이라는 뜻으로, 매우 위태로운 처지를 말합니다.',
      origin: '불교 문헌과 한시에서 쓰인 비유로, 목숨이나 운명이 위태로운 상태를 가리킵니다.',
      usage: '존폐가 걸린 위기 상황을 이를 때 씁니다.' },
    en: { title: 'Pung-jeon-deung-hwa', meaning: 'A lamp flame before the wind — an extremely precarious state.',
      origin: 'A simile used in Buddhist texts and classical poetry for a life or fate hanging by a thread.',
      usage: 'Used for a crisis where survival itself is at stake.' },
    zh: { title: '风前灯火', meaning: '风中的灯火，比喻极其危险的处境。',
      origin: '佛典与古诗中的比喻，形容性命或命运危如悬丝。',
      usage: '用于存亡攸关的危机；中文多说「风中残烛」。' },
  },
  {
    slug: 'orimujung', hanja: '五里霧中', simplified: '五里雾中', reading: '오리무중',
    pinyin: 'wǔ lǐ wù zhōng', chars: ['다섯 오', '마을 리', '안개 무', '가운데 중'],
    category: '상황·형세', icon: '🌫️',
    ko: { title: '오리무중', meaning: '오 리에 걸친 안개 속이라는 뜻으로, 갈피를 잡을 수 없다는 말입니다.',
      origin: '《후한서》 장해전에서 장해가 오 리에 걸친 안개를 일으켰다는 이야기에서 왔습니다.',
      usage: '수사나 상황 파악이 전혀 진전되지 않을 때 씁니다.' },
    en: { title: 'O-ri-mu-jung', meaning: 'Inside a fog five li deep — completely unable to make sense of things.',
      origin: 'From the Book of the Later Han, where Zhang Kai could conjure a fog five li across.',
      usage: 'Used when an investigation or situation is going nowhere.' },
    zh: { title: '五里雾中', meaning: '身处五里之雾，比喻茫无头绪。',
      origin: '出自《后汉书·张楷传》，张楷能作五里雾。',
      usage: '形容调查或状况毫无进展；中文多说「一头雾水」。' },
  },
  {
    slug: 'seolsanggasang', hanja: '雪上加霜', simplified: '雪上加霜', reading: '설상가상',
    pinyin: 'xuě shàng jiā shuāng', chars: ['눈 설', '위 상', '더할 가', '서리 상'],
    category: '상황·형세', icon: '❄️',
    ko: { title: '설상가상', meaning: '눈 위에 서리가 덮인다는 뜻으로, 어려운 일이 겹친다는 말입니다.',
      origin: '선종 어록 《벽암록》 등에 보이는 표현입니다.',
      usage: '나쁜 일이 연달아 생겼을 때 씁니다.' },
    en: { title: 'Seol-sang-ga-sang', meaning: 'Frost on top of snow — one misfortune stacked on another.',
      origin: 'Found in Chan Buddhist records such as the Blue Cliff Record.',
      usage: 'Said when bad things happen back to back.' },
    zh: { title: '雪上加霜', meaning: '雪上又结霜，比喻灾祸接连而来。',
      origin: '见于《碧岩录》等禅宗语录。',
      usage: '用于坏事接连发生时，中韩通用。' },
  },
  {
    slug: 'jeonhwawibok', hanja: '轉禍爲福', simplified: '转祸为福', reading: '전화위복',
    pinyin: 'zhuǎn huò wéi fú', chars: ['구를 전', '재앙 화', '할 위', '복 복'],
    category: '상황·형세', icon: '🍀',
    ko: { title: '전화위복', meaning: '재앙이 바뀌어 복이 된다는 뜻입니다.',
      origin: '《전국책》과 《사기》에 나오는 표현으로, 위기를 기회로 돌린 사례에 쓰였습니다.',
      usage: '손해가 결과적으로 이익이 됐을 때 씁니다.' },
    en: { title: 'Jeon-hwa-wi-bok', meaning: 'Disaster turned into good fortune.',
      origin: 'From the Strategies of the Warring States and the Records of the Grand Historian, of crises turned into openings.',
      usage: 'Used when a loss ended up working out in your favour.' },
    zh: { title: '转祸为福', meaning: '把灾祸转变为福气。',
      origin: '见于《战国策》与《史记》，用于化危机为契机之事。',
      usage: '用于损失最终变成好事时，中韩通用。' },
  },
  {
    slug: 'saeongjima', hanja: '塞翁之馬', simplified: '塞翁之马', reading: '새옹지마',
    pinyin: 'sài wēng zhī mǎ', chars: ['변방 새', '늙은이 옹', '갈 지', '말 마'],
    category: '상황·형세', icon: '🎲',
    ko: { title: '새옹지마', meaning: '변방 노인의 말이라는 뜻으로, 복과 화는 예측할 수 없다는 말입니다.',
      origin: '《회남자》에서 말을 잃고 얻고 아들이 다치는 일이 번갈아 일어나며 화복이 뒤바뀐 이야기입니다.',
      usage: '좋은 일에도 나쁜 일에도 일희일비하지 말라고 할 때 씁니다.' },
    en: { title: 'Sae-ong-ji-ma', meaning: 'The old frontiersman’s horse — fortune and misfortune cannot be predicted.',
      origin: 'From the Huainanzi: a horse lost, a horse gained, a son injured — each turn reversing what looked like luck.',
      usage: 'Said to counsel against reacting too strongly to either good news or bad.' },
    zh: { title: '塞翁之马', meaning: '塞翁的马，比喻福祸难以预料。',
      origin: '出自《淮南子》，失马、得马、子伤等事接连反转吉凶。',
      usage: '劝人不要因一时好坏而大喜大悲；中文多说「塞翁失马」。' },
  },
  {
    slug: 'ilchokjeukbal', hanja: '一觸卽發', simplified: '一触即发', reading: '일촉즉발',
    pinyin: 'yī chù jí fā', chars: ['한 일', '닿을 촉', '곧 즉', '쏠 발'],
    category: '상황·형세', icon: '⚡',
    ko: { title: '일촉즉발', meaning: '한 번 닿으면 곧 터진다는 뜻으로, 아주 위급한 상태를 말합니다.',
      origin: '근대 이후 널리 쓰인 표현으로, 팽팽하게 맞선 긴장 상태를 가리킵니다.',
      usage: '충돌 직전의 대치 상황을 보도할 때 자주 쓰입니다.' },
    en: { title: 'Il-chok-jeuk-bal', meaning: 'One touch and it goes off — an extremely volatile state.',
      origin: 'Widely used since the modern era for a standoff stretched taut.',
      usage: 'Common in reporting on confrontations on the brink of breaking out.' },
    zh: { title: '一触即发', meaning: '一碰就会爆发，形容形势极其危急。',
      origin: '近代以来广泛使用，指绷紧的对峙状态。',
      usage: '常用于报道濒临冲突的对峙，中韩通用。' },
  },
];
