/** 사자성어 - 말·글 (6) */
import type { Idiom } from './types.ts';

export const WORDS_IDIOMS: Idiom[] = [
  {
    slug: 'eonjungyugol', hanja: '言中有骨', simplified: '言中有骨', reading: '언중유골',
    pinyin: 'yán zhōng yǒu gǔ', chars: ['말씀 언', '가운데 중', '있을 유', '뼈 골'],
    category: '말·글', icon: '📝',
    ko: { title: '언중유골', meaning: '말 속에 뼈가 있다는 뜻으로, 예사로운 말에 단단한 속뜻이 있다는 말입니다.',
      origin: '한국에서 굳어진 표현으로, 부드러운 말투에 담긴 날카로운 의도를 가리킵니다.',
      usage: '겉으로 웃으며 한 말에 비판이 담겼을 때 씁니다.' },
    en: { title: 'Eon-jung-yu-gol', meaning: 'There is bone inside the words — a hard meaning hidden in an ordinary remark.',
      origin: 'A phrase settled in Korean usage, for a sharp intent wrapped in a soft tone.',
      usage: 'Used when a smiling comment carried a criticism.' },
  },
  {
    slug: 'choncheolsarin', hanja: '寸鐵殺人', simplified: '寸铁杀人', reading: '촌철살인',
    pinyin: 'cùn tiě shā rén', chars: ['마디 촌', '쇠 철', '죽일 살', '사람 인'],
    category: '말·글', icon: '🗡️',
    ko: { title: '촌철살인', meaning: '한 치의 쇠붙이로 사람을 죽인다는 뜻으로, 짧은 말로 급소를 찌른다는 말입니다.',
      origin: '《학림옥로》에 실린 선종의 비유에서 왔으며, 한국에서는 촌평의 날카로움을 이르는 말로 굳었습니다.',
      usage: '한 문장으로 핵심을 정확히 짚은 논평을 이를 때 씁니다.' },
    en: { title: 'Chon-cheol-sa-rin', meaning: 'Kill with an inch of steel — pierce the vital point with a few words.',
      origin: 'From a Chan Buddhist simile recorded in the Helin Yulu; in Korea it came to mean a devastatingly apt remark.',
      usage: 'Said of a one-sentence comment that nails the heart of the matter.' },
  },
  {
    slug: 'isimjeonsim', hanja: '以心傳心', simplified: '以心传心', reading: '이심전심',
    pinyin: 'yǐ xīn chuán xīn', chars: ['써 이', '마음 심', '전할 전', '마음 심'],
    category: '말·글', icon: '❤️',
    ko: { title: '이심전심', meaning: '마음으로 마음을 전한다는 뜻으로, 말 없이도 서로 뜻이 통한다는 말입니다.',
      origin: '선종에서 문자를 거치지 않고 깨달음을 전한다는 뜻으로 쓴 말입니다.',
      usage: '오래된 사이에서 말하지 않아도 통할 때 씁니다.' },
    en: { title: 'I-sim-jeon-sim', meaning: 'Mind transmits to mind — understanding without a word spoken.',
      origin: 'A Chan Buddhist term for passing on awakening without relying on written words.',
      usage: 'Used when long-standing companions understand each other without speaking.' },
  },
  {
    slug: 'gamaniseol', hanja: '甘言利說', simplified: '甘言利说', reading: '감언이설',
    pinyin: 'gān yán lì shuō', chars: ['달 감', '말씀 언', '이로울 리', '말씀 설'],
    category: '말·글', icon: '🍯',
    ko: { title: '감언이설', meaning: '달콤한 말과 이로운 듯한 말이라는 뜻으로, 남을 꾀는 말을 가리킵니다.',
      origin: '한국에서 널리 쓰이는 표현으로, 사기나 회유의 말을 경계할 때 씁니다.',
      usage: '고수익을 약속하는 투자 권유를 경계할 때 자주 쓰입니다.' },
    en: { title: 'Gam-eon-i-seol', meaning: 'Sweet words and seemingly advantageous talk — the language of enticement.',
      origin: 'Common in Korean usage as a warning against deceit or coaxing.',
      usage: 'Frequently used when warning about investment pitches promising high returns.' },
  },
  {
    slug: 'yugumueon', hanja: '有口無言', simplified: '有口无言', reading: '유구무언',
    pinyin: 'yǒu kǒu wú yán', chars: ['있을 유', '입 구', '없을 무', '말씀 언'],
    category: '말·글', icon: '🤐',
    ko: { title: '유구무언', meaning: '입은 있으나 할 말이 없다는 뜻입니다.',
      origin: '한국에서 굳어진 표현으로, 변명할 여지가 없는 상태를 가리킵니다.',
      usage: '잘못이 분명해 아무 말도 못 할 때 씁니다.' },
    en: { title: 'Yu-gu-mu-eon', meaning: 'You have a mouth but nothing to say.',
      origin: 'Settled in Korean usage for a state with no room left to excuse yourself.',
      usage: 'Used when the fault is so clear that nothing can be said.' },
  },
  {
    slug: 'ileonjiha', hanja: '一言之下', simplified: '一言之下', reading: '일언지하',
    pinyin: 'yī yán zhī xià', chars: ['한 일', '말씀 언', '갈 지', '아래 하'],
    category: '말·글', icon: '⚖️',
    ko: { title: '일언지하', meaning: '한마디 말로 끝낸다는 뜻으로, 두말없이 딱 잘라 대응하는 것을 말합니다.',
      origin: '한국에서 널리 쓰이는 표현으로, 주로 "일언지하에 거절했다"처럼 씁니다.',
      usage: '제안을 즉시 단호하게 거절한 상황에 씁니다.' },
    en: { title: 'Il-eon-ji-ha', meaning: 'Settled in a single word — a flat, immediate response.',
      origin: 'Common in Korean, typically in the form "refused in a single word".',
      usage: 'Used when a proposal was turned down instantly and firmly.' },
  },
];
