/** 사자성어 - 말·글 둘째 묶음 (8) */
import type { Idiom } from './types.ts';

export const WORDS2_IDIOMS: Idiom[] = [
  {
    slug: 'eobulseongseol', hanja: '語不成說', simplified: '语不成说', reading: '어불성설',
    pinyin: 'yǔ bù chéng shuō', chars: ['말씀 어', '아닐 불', '이룰 성', '말씀 설'],
    category: '말·글', icon: '❌',
    ko: { title: '어불성설', meaning: '말이 말을 이루지 못한다, 곧 앞뒤가 맞지 않는다는 뜻입니다.',
      origin: '중국 고전에 그대로 나오지 않는 한국식 성어로, 조선 시대 상소문에서 널리 쓰였습니다.',
      usage: '주장의 논리가 무너졌을 때 단호하게 지적하는 말입니다.' },
    en: { title: 'Eo-bul-seong-seol', meaning: 'The words do not add up to a statement — it makes no sense.',
      origin: 'A Korean coinage rather than a Chinese classic, common in Joseon-era petitions.',
      usage: 'A blunt way to say an argument has collapsed on its own logic.' },
    zh: { title: '语不成说', meaning: '话说不通，前后矛盾。',
      origin: '并非出自中国古籍，是朝鲜时代奏疏中常用的韩式四字语。',
      usage: '在韩国用于直指论点不成立；中文多说「不成体统」或「说不通」。' },
  },
  {
    slug: 'gapronulbak', hanja: '甲論乙駁', simplified: '甲论乙驳', reading: '갑론을박',
    pinyin: 'jiǎ lùn yǐ bó', chars: ['첫째 갑', '논할 론', '둘째 을', '논박할 박'],
    category: '말·글', icon: '💬',
    ko: { title: '갑론을박', meaning: '갑이 주장하면 을이 반박하듯 서로 논쟁이 오간다는 뜻입니다.',
      origin: '갑·을을 당사자 이름 대신 쓰는 관례에서 나온 한국식 표현입니다.',
      usage: '회의에서 의견이 팽팽하게 갈릴 때 씁니다.' },
    en: { title: 'Gap-ron-eul-bak', meaning: 'A argues, B refutes — a back-and-forth dispute.',
      origin: 'A Korean coinage using gap and eul, the conventional stand-ins for the first and second party.',
      usage: 'Used when a meeting splits into evenly matched positions.' },
    zh: { title: '甲论乙驳', meaning: '甲方主张、乙方反驳，来回争论。',
      origin: '取自以甲、乙代指当事双方的惯例，为韩式四字语。',
      usage: '在韩国用于会议上意见僵持不下时；中文多说「各执一词」。' },
  },
  {
    slug: 'hoengseolsuseol', hanja: '橫說竪說', simplified: '横说竖说', reading: '횡설수설',
    pinyin: 'héng shuō shù shuō', chars: ['가로 횡', '말씀 설', '세로 수', '말씀 설'],
    category: '말·글', icon: '🌀',
    ko: { title: '횡설수설', meaning: '가로로 세로로 말한다, 곧 갈피 없이 늘어놓는다는 뜻입니다.',
      origin: '본래는 이리저리 능숙하게 설명한다는 뜻이었으나 지금은 조리 없는 말을 가리킵니다.',
      usage: '취했거나 당황해서 말이 흐트러진 상태를 두고 씁니다.' },
    en: { title: 'Hoeng-seol-su-seol', meaning: 'Talking across and up and down — rambling without thread.',
      origin: 'Once meant explaining deftly from every angle; it now means incoherence.',
      usage: 'Used of speech that falls apart from drink or panic.' },
    zh: { title: '横说竖说', meaning: '横七竖八地说，指言语没有条理。',
      origin: '本指从各角度娴熟阐述，今在韩国专指语无伦次。',
      usage: '用于形容因醉酒或慌乱而语无伦次；中文多说「胡言乱语」。' },
  },
  {
    slug: 'ileonbangu', hanja: '一言半句', simplified: '一言半句', reading: '일언반구',
    pinyin: 'yī yán bàn jù', chars: ['한 일', '말씀 언', '반 반', '글귀 구'],
    category: '말·글', icon: '🤏',
    ko: { title: '일언반구', meaning: '한 마디 말과 반 구절, 곧 아주 짧은 말조차를 뜻합니다.',
      origin: '아주 적은 말을 강조하는 관용 표현으로 굳어졌습니다.',
      usage: '"일언반구도 없었다"처럼 대개 부정문과 함께 씁니다.' },
    en: { title: 'Il-eon-ban-gu', meaning: 'A word and half a phrase — even the smallest utterance.',
      origin: 'A set phrase that emphasises the barest minimum of speech.',
      usage: 'Almost always used with a negative: "not a word of it was said".' },
    zh: { title: '一言半句', meaning: '一句话半个词，指极少的言语。',
      origin: '强调言语极少的固定说法。',
      usage: '多与否定连用，如「一言半句也没提」；中文常说「一言半语」。' },
  },
  {
    slug: 'gyoeonyeongsaek', hanja: '巧言令色', simplified: '巧言令色', reading: '교언영색',
    pinyin: 'qiǎo yán lìng sè', chars: ['공교할 교', '말씀 언', '아름다울 령', '빛 색'],
    category: '말·글', icon: '🎭',
    ko: { title: '교언영색', meaning: '꾸민 말과 지어낸 표정으로 남의 마음을 사려 한다는 뜻입니다.',
      origin: '《논어》 학이편의 "교언영색 선의인"에서 나왔습니다. 공자는 그런 사람에게 어짊이 드물다고 했습니다.',
      usage: '말만 번드르르한 사람을 경계할 때 씁니다.' },
    en: { title: 'Gyo-eon-yeong-saek', meaning: 'Polished words and an arranged face, put on to win favour.',
      origin: 'From the Analects: Confucius said such people rarely have real benevolence in them.',
      usage: 'Used to warn against someone whose talk is all surface.' },
    zh: { title: '巧言令色', meaning: '用花言巧语与讨好的神色博取好感。',
      origin: '出自《论语·学而》「巧言令色，鲜矣仁」。',
      usage: '用于警惕只会说漂亮话的人，中韩通用。' },
  },
  {
    slug: 'myeongsilsangbu', hanja: '名實相符', simplified: '名实相符', reading: '명실상부',
    pinyin: 'míng shí xiāng fú', chars: ['이름 명', '열매 실', '서로 상', '맞을 부'],
    category: '말·글', icon: '✅',
    ko: { title: '명실상부', meaning: '이름과 실제가 서로 맞는다는 뜻입니다.',
      origin: '명(名)과 실(實)의 관계를 따지던 선진 시대 명실론에서 온 표현입니다.',
      usage: '직함이나 평판이 실제 실력과 맞을 때 씁니다.' },
    en: { title: 'Myeong-sil-sang-bu', meaning: 'Name and reality matching each other.',
      origin: 'From pre-Qin debates on the relation between names and the things they denote.',
      usage: 'Used when a title or reputation is matched by actual ability.' },
    zh: { title: '名实相符', meaning: '名称与实际相一致。',
      origin: '源自先秦关于名与实关系的名实之辩。',
      usage: '用于头衔或声誉与真实能力相称时；中文常说「名副其实」。' },
  },
  {
    slug: 'buhwanoedong', hanja: '附和雷同', simplified: '附和雷同', reading: '부화뇌동',
    pinyin: 'fù hè léi tóng', chars: ['붙을 부', '화할 화', '우레 뢰', '같을 동'],
    category: '말·글', icon: '🐑',
    ko: { title: '부화뇌동', meaning: '줄곧 남의 말에 붙어 우레처럼 한꺼번에 같이 움직인다는 뜻입니다.',
      origin: '뇌동(雷同)은 《예기》에서 우레가 울리면 만물이 한꺼번에 응하는 것을 가리킨 말입니다.',
      usage: '자기 판단 없이 여론에 휩쓸리는 태도를 지적할 때 씁니다.' },
    en: { title: 'Bu-hwa-noe-dong', meaning: 'Falling in with others and echoing them like thunder.',
      origin: 'Noe-dong comes from the Book of Rites, on how all things answer at once when thunder sounds.',
      usage: 'Used to criticise going along with opinion without judging for oneself.' },
    zh: { title: '附和雷同', meaning: '附和他人，如雷响时万物齐应般盲从。',
      origin: '「雷同」出自《礼记》，指雷鸣时万物同时相应。',
      usage: '用于批评没有主见、随波逐流；中文多说「随声附和」。' },
  },
  {
    slug: 'eoneododan', hanja: '言語道斷', simplified: '言语道断', reading: '언어도단',
    pinyin: 'yán yǔ dào duàn', chars: ['말씀 언', '말씀 어', '길 도', '끊을 단'],
    category: '말·글', icon: '🚫',
    ko: { title: '언어도단', meaning: '말로는 길이 끊긴다, 곧 말이 안 되는 소리라는 뜻입니다.',
      origin: '본래 불교에서 진리는 말로 다 담을 수 없다는 뜻이었는데, 한국에서는 터무니없다는 뜻으로 굳었습니다.',
      usage: '상대의 주장을 강하게 부정할 때 씁니다.' },
    en: { title: 'Eon-eo-do-dan', meaning: 'Where words run out — in Korean use, utterly unreasonable.',
      origin: 'Originally Buddhist, meaning truth cannot be exhausted in words; Korean usage shifted it to "absurd".',
      usage: 'A strong rejection of what someone has just claimed.' },
    zh: { title: '言语道断', meaning: '在韩语中指荒谬到不成话的程度。',
      origin: '本为佛教用语，谓真理非言语所能尽；韩语中转为「荒唐无理」之意。',
      usage: '用于强烈否定对方主张；中文仍多取佛教本义，需注意差异。' },
  },
];
