/**
 * 상태 코드와 헤더 132개의 한 줄 설명 — 여덟 언어.
 *
 * 번호와 헤더 이름은 표준이 정한 것이라 옮기지 않는다. 404는 어디서나 404이고
 * Content-Type은 Content-Type이다. 옮기는 것은 "이것이 무슨 뜻인가" 한 문장뿐이다.
 *
 * 여덟 칸을 배열로 적는다 — 순서는 ko·en·es·pt·ja·de·fr·hi.
 */
export type Eight = [string, string, string, string, string, string, string, string];

const LANG_ORDER = ['ko', 'en', 'es', 'pt', 'ja', 'de', 'fr', 'hi'] as const;

export const HTTP_DESC: Record<string, Eight> = {
  /* ───────── 1xx ───────── */
  '100': ['요청의 앞부분을 받았으니 나머지를 계속 보내라는 뜻입니다.', 'The first part of the request arrived; go ahead and send the rest.', 'Ha llegado la primera parte de la petición: continúa enviando el resto.', 'A primeira parte do pedido chegou: continue enviando o resto.', '要求の前半を受け取ったので、残りを送ってよいという意味です。', 'Der erste Teil der Anfrage ist da — senden Sie den Rest.', "La première partie de la requête est reçue : envoyez la suite.", 'अनुरोध का पहला हिस्सा मिल गया — बाक़ी भेजते रहें।'],
  '101': ['같은 연결로 다른 프로토콜로 갈아탄다는 뜻입니다. 웹소켓이 이렇게 시작합니다.', 'The connection is switching protocol — this is how a WebSocket begins.', 'La conexión cambia de protocolo: así empieza un WebSocket.', 'A conexão está trocando de protocolo: é assim que um WebSocket começa.', '同じ接続で別のプロトコルに切り替えます。WebSocketはこうして始まります。', 'Die Verbindung wechselt das Protokoll — so beginnt ein WebSocket.', "La connexion change de protocole : c'est ainsi que débute un WebSocket.", 'कनेक्शन प्रोटोकॉल बदल रहा है — WebSocket ऐसे ही शुरू होता है।'],
  '102': ['처리 중이니 기다리라는 뜻입니다. 시간이 오래 걸리는 작업에 쓰입니다.', 'Still working — please wait. Used for operations that take a long time.', 'Sigue procesando: espera. Se usa en operaciones largas.', 'Ainda processando: aguarde. Usado em operações demoradas.', '処理中なので待つように、という意味です。時間のかかる作業に使われます。', 'Wird noch bearbeitet — bitte warten. Für langlaufende Vorgänge.', "Traitement en cours : patientez. Pour les opérations longues.", 'अभी काम चल रहा है — प्रतीक्षा करें। लंबे कामों में इस्तेमाल होता है।'],
  '103': ['본문보다 먼저 힌트를 보내 브라우저가 자원을 미리 받게 합니다.', 'Sends hints ahead of the body so the browser can start fetching resources early.', 'Envía pistas antes del cuerpo para que el navegador precargue recursos.', 'Envia dicas antes do corpo para o navegador pré-carregar recursos.', '本文より先にヒントを送り、ブラウザーが資源を先に取得できるようにします。', 'Sendet Hinweise vor dem Body, damit der Browser Ressourcen früher lädt.', "Envoie des indices avant le corps pour que le navigateur précharge.", 'मुख्य भाग से पहले संकेत भेजता है ताकि ब्राउज़र संसाधन पहले लाना शुरू करे।'],

  /* ───────── 2xx ───────── */
  '200': ['요청이 제대로 처리됐다는 가장 흔한 응답입니다.', 'The request succeeded — the most common response of all.', 'La petición fue correcta: la respuesta más común de todas.', 'O pedido deu certo: a resposta mais comum de todas.', '要求が正しく処理されたという、いちばん多い応答です。', 'Die Anfrage war erfolgreich — die häufigste Antwort überhaupt.', "La requête a réussi : la réponse la plus courante.", 'अनुरोध सफल रहा — सबसे आम प्रतिक्रिया।'],
  '201': ['새 자원이 만들어졌다는 뜻입니다. Location 헤더에 그 주소가 담깁니다.', 'A new resource was created; the Location header carries its address.', 'Se creó un recurso nuevo; la cabecera Location trae su dirección.', 'Um recurso novo foi criado; o cabeçalho Location traz o endereço.', '新しい資源が作られたという意味です。Locationヘッダーにその場所が入ります。', 'Eine neue Ressource wurde erstellt; die Location-Kopfzeile nennt ihre Adresse.', "Une ressource a été créée ; l'en-tête Location en donne l'adresse.", 'नया संसाधन बना; Location हेडर में उसका पता होता है।'],
  '202': ['요청을 받아 두었지만 아직 처리하지 않았다는 뜻입니다.', 'The request was accepted but has not been carried out yet.', 'La petición se aceptó pero aún no se ha ejecutado.', 'O pedido foi aceito, mas ainda não foi executado.', '要求は受け付けたが、まだ処理していないという意味です。', 'Die Anfrage wurde angenommen, aber noch nicht ausgeführt.', "La requête est acceptée mais pas encore traitée.", 'अनुरोध स्वीकार हुआ, पर अभी पूरा नहीं हुआ।'],
  '203': ['원본이 아니라 중간 서버가 손댄 응답이라는 뜻입니다.', 'The answer was modified by a proxy rather than coming straight from the origin.', 'La respuesta fue alterada por un intermediario, no viene del origen.', 'A resposta foi alterada por um intermediário, não veio da origem.', '元のサーバーではなく中間のサーバーが手を加えた応答という意味です。', 'Die Antwort wurde von einem Proxy verändert, statt direkt vom Ursprung zu kommen.', "La réponse a été modifiée par un intermédiaire, non par l'origine.", 'उत्तर मूल सर्वर से नहीं, बीच के प्रॉक्सी से बदला हुआ आया है।'],
  '204': ['성공했지만 보낼 내용이 없다는 뜻입니다. 저장 후 화면을 그대로 둘 때 씁니다.', 'Success, but there is nothing to send back — handy after a save when the page should not change.', 'Éxito, pero sin contenido que devolver: útil tras guardar sin recargar.', 'Sucesso, mas sem conteúdo a devolver: útil após salvar sem recarregar.', '成功したが返す内容がないという意味です。保存後に画面をそのままにしたいときに使います。', 'Erfolg, aber nichts zurückzusenden — praktisch nach dem Speichern.', "Réussite, mais rien à renvoyer : pratique après un enregistrement.", 'सफल, पर लौटाने को कुछ नहीं — सहेजने के बाद पन्ना वैसा ही रखने में उपयोगी।'],
  '205': ['성공했으니 입력 폼을 비우라는 뜻입니다.', 'Success — and the client should clear the form it sent.', 'Éxito: el cliente debe vaciar el formulario enviado.', 'Sucesso: o cliente deve limpar o formulário enviado.', '成功したので入力フォームを空にするように、という意味です。', 'Erfolg — das Formular sollte geleert werden.', "Réussite : le client doit vider le formulaire envoyé.", 'सफल — भेजा गया फ़ॉर्म ख़ाली कर देना चाहिए।'],
  '206': ['요청한 일부만 보냈다는 뜻입니다. 이어받기와 영상 탐색이 이 응답으로 됩니다.', 'Only the requested slice was sent — this is what makes resumable downloads and video seeking work.', 'Solo se envió el trozo pedido: así funcionan las descargas reanudables y el salto en vídeo.', 'Só o trecho pedido foi enviado: é assim que downloads retomáveis e busca em vídeo funcionam.', '要求された一部だけを送ったという意味です。ダウンロードの再開や動画のシークがこれで動きます。', 'Nur der angeforderte Ausschnitt wurde gesendet — so funktionieren fortsetzbare Downloads und Videosprünge.', "Seule la portion demandée est envoyée : c'est ce qui permet la reprise de téléchargement et le déplacement dans une vidéo.", 'सिर्फ़ माँगा गया हिस्सा भेजा गया — इसी से डाउनलोड फिर से शुरू होना और वीडियो में आगे-पीछे जाना चलता है।'],
  '207': ['여러 자원의 결과를 한 번에 담아 보낸다는 뜻입니다.', 'Carries the results for several resources in one response.', 'Contiene el resultado de varios recursos en una sola respuesta.', 'Traz o resultado de vários recursos em uma só resposta.', '複数の資源の結果をまとめて返すという意味です。', 'Enthält die Ergebnisse mehrerer Ressourcen in einer Antwort.', "Contient les résultats de plusieurs ressources en une réponse.", 'एक ही उत्तर में कई संसाधनों के परिणाम।'],
  '208': ['앞서 이미 보고한 것이라 다시 적지 않는다는 뜻입니다.', 'Already reported earlier in the response, so it is not repeated.', 'Ya se informó antes en la respuesta, así que no se repite.', 'Já foi informado antes na resposta, então não se repete.', '先に報告済みなので繰り返さないという意味です。', 'Bereits zuvor gemeldet, wird daher nicht wiederholt.', "Déjà signalé plus haut, donc non répété.", 'पहले ही बताया जा चुका है, इसलिए दोहराया नहीं गया।'],
  '226': ['요청한 자원의 변경분만 보냈다는 뜻입니다.', 'Only the differences from the requested resource were sent.', 'Solo se enviaron las diferencias del recurso pedido.', 'Só as diferenças do recurso pedido foram enviadas.', '要求された資源の変更分だけを送ったという意味です。', 'Nur die Änderungen an der Ressource wurden gesendet.', "Seules les différences de la ressource ont été envoyées.", 'माँगे गए संसाधन का सिर्फ़ बदला हुआ हिस्सा भेजा गया।'],

  /* ───────── 3xx ───────── */
  '300': ['고를 수 있는 자원이 여럿이라는 뜻입니다.', 'There is more than one possible resource to choose from.', 'Hay más de un recurso posible entre los que elegir.', 'Há mais de um recurso possível para escolher.', '選べる資源が複数あるという意味です。', 'Es gibt mehrere mögliche Ressourcen zur Auswahl.', "Plusieurs ressources sont possibles.", 'चुनने के लिए एक से ज़्यादा संसाधन हैं।'],
  '301': ['주소가 영구히 바뀌었다는 뜻입니다. 검색 순위도 새 주소로 넘어갑니다.', 'The address moved for good; search ranking follows to the new URL.', 'La dirección cambió para siempre; el posicionamiento pasa a la nueva URL.', 'O endereço mudou de vez; o ranking de busca vai para a nova URL.', '住所が恒久的に変わったという意味です。検索順位も新しいURLへ引き継がれます。', 'Die Adresse hat sich dauerhaft geändert; auch das Ranking wandert mit.', "L'adresse a changé définitivement ; le référencement suit la nouvelle URL.", 'पता स्थायी रूप से बदल गया; खोज रैंकिंग भी नए URL पर चली जाती है।'],
  '302': ['잠시 다른 주소로 가라는 뜻입니다. 원래 주소는 그대로 남습니다.', 'Go elsewhere for now; the original address stays valid.', 'Ve a otra dirección por ahora; la original sigue siendo válida.', 'Vá a outro endereço por ora; o original continua válido.', '今だけ別の住所へ行くように、という意味です。元の住所はそのまま残ります。', 'Vorübergehend woanders — die ursprüngliche Adresse bleibt gültig.', "Allez ailleurs pour l'instant ; l'adresse d'origine reste valable.", 'फ़िलहाल दूसरे पते पर जाएँ; मूल पता बना रहता है।'],
  '303': ['결과는 다른 주소에서 GET으로 받으라는 뜻입니다. 폼 제출 뒤에 씁니다.', 'Fetch the result from another URL with GET — the usual answer after a form submission.', 'Recoge el resultado en otra URL con GET: lo habitual tras enviar un formulario.', 'Busque o resultado em outra URL com GET: o usual após enviar um formulário.', '結果は別の住所からGETで受け取るように、という意味です。フォーム送信後に使います。', 'Das Ergebnis per GET von einer anderen URL holen — üblich nach dem Absenden eines Formulars.', "Récupérez le résultat via GET à une autre URL : la réponse habituelle après un formulaire.", 'परिणाम दूसरे URL से GET द्वारा लें — फ़ॉर्म भेजने के बाद का सामान्य उत्तर।'],
  '304': ['가진 것이 아직 최신이니 그대로 쓰라는 뜻입니다. 본문을 보내지 않아 빠릅니다.', 'What you have is still current — reuse it. No body is sent, which is what makes caching fast.', 'Lo que tienes sigue vigente: reutilízalo. No se envía cuerpo, y por eso la caché es rápida.', 'O que você tem ainda vale: reutilize. Não vai corpo, e é isso que torna o cache rápido.', '持っているものがまだ最新なのでそのまま使うように、という意味です。本文を送らないので速くなります。', 'Ihr Stand ist noch aktuell — weiterverwenden. Es wird kein Body gesendet, das macht Caching schnell.', "Ce que vous avez est encore à jour : réutilisez-le. Aucun corps n'est envoyé, d'où la rapidité du cache.", 'आपके पास जो है वह अब भी ताज़ा है — उसी का प्रयोग करें। कोई मुख्य भाग नहीं जाता, इसी से कैश तेज़ रहता है।'],
  '307': ['잠시 다른 주소로 가되 방식은 그대로 두라는 뜻입니다.', 'A temporary move that keeps the original method — a POST stays a POST.', 'Traslado temporal que conserva el método: un POST sigue siendo POST.', 'Mudança temporária que mantém o método: um POST continua POST.', '一時的に別の住所へ移るが、方式はそのままという意味です。', 'Vorübergehender Umzug unter Beibehaltung der Methode — ein POST bleibt ein POST.', "Déplacement temporaire en conservant la méthode : un POST reste un POST.", 'अस्थायी बदलाव जिसमें विधि वही रहती है — POST, POST ही रहता है।'],
  '308': ['영구히 옮기되 방식은 그대로 두라는 뜻입니다.', 'A permanent move that keeps the original method.', 'Traslado permanente que conserva el método.', 'Mudança permanente que mantém o método.', '恒久的に移すが、方式はそのままという意味です。', 'Dauerhafter Umzug unter Beibehaltung der Methode.', "Déplacement permanent en conservant la méthode.", 'स्थायी बदलाव जिसमें विधि वही रहती है।'],

  /* ───────── 4xx ───────── */
  '400': ['요청 자체가 잘못돼 읽을 수 없다는 뜻입니다.', 'The request itself is malformed and cannot be read.', 'La petición está mal formada y no se puede leer.', 'O pedido está malformado e não pode ser lido.', '要求そのものが壊れていて読めないという意味です。', 'Die Anfrage ist fehlerhaft und nicht lesbar.', "La requête est mal formée et illisible.", 'अनुरोध ही ग़लत है और पढ़ा नहीं जा सकता।'],
  '401': ['누구인지 밝히지 않았다는 뜻입니다. 로그인하면 풀립니다.', 'You have not said who you are; signing in usually resolves it.', 'No has dicho quién eres; iniciar sesión suele resolverlo.', 'Você não disse quem é; entrar na conta costuma resolver.', '誰であるかを示していないという意味です。ログインすれば解けます。', 'Sie haben sich nicht ausgewiesen; Anmelden hilft meist.', "Vous ne vous êtes pas identifié ; se connecter règle en général le problème.", 'आपने बताया नहीं कि आप कौन हैं; लॉगिन करने पर आमतौर पर हल हो जाता है।'],
  '402': ['결제가 필요하다는 뜻입니다. 표준에는 있지만 실제로는 드물게 쓰입니다.', 'Payment is required — reserved in the standard but rarely used in practice.', 'Se requiere pago: está en el estándar, pero apenas se usa.', 'É preciso pagar: está no padrão, mas quase não se usa.', '支払いが必要という意味です。標準にはありますが実際にはあまり使われません。', 'Zahlung erforderlich — im Standard vorgesehen, in der Praxis selten.', "Paiement requis : prévu par la norme mais rarement utilisé.", 'भुगतान चाहिए — मानक में है, पर व्यवहार में कम ही दिखता है।'],
  '403': ['누구인지는 알지만 권한이 없다는 뜻입니다. 로그인해도 그대로일 수 있습니다.', 'The server knows who you are and still says no; signing in may not change it.', 'El servidor sabe quién eres y aun así lo niega; iniciar sesión puede no cambiarlo.', 'O servidor sabe quem você é e mesmo assim nega; entrar na conta pode não mudar.', '誰であるかは分かっているが権限がないという意味です。ログインしても変わらないことがあります。', 'Der Server kennt Sie und verweigert trotzdem; Anmelden ändert daran oft nichts.', "Le serveur sait qui vous êtes et refuse quand même ; se connecter n'y changera peut-être rien.", 'सर्वर जानता है कि आप कौन हैं, फिर भी अनुमति नहीं है; लॉगिन करने से शायद कुछ न बदले।'],
  '404': ['그 주소에 아무것도 없다는 뜻입니다. 주소가 틀렸거나 이미 지워진 것입니다.', 'Nothing lives at that address — the URL is wrong or the page is gone.', 'No hay nada en esa dirección: la URL está mal o la página ya no existe.', 'Não há nada nesse endereço: a URL está errada ou a página sumiu.', 'その住所には何もないという意味です。URLが違うか、すでに消えています。', 'Unter dieser Adresse liegt nichts — die URL ist falsch oder die Seite ist weg.', "Rien à cette adresse : l'URL est fausse ou la page a disparu.", 'उस पते पर कुछ नहीं है — URL ग़लत है या पन्ना हट चुका है।'],
  '405': ['그 주소는 있지만 그 방식은 받지 않는다는 뜻입니다.', 'The address exists but does not accept that method.', 'La dirección existe pero no admite ese método.', 'O endereço existe, mas não aceita esse método.', 'その住所はあるが、その方式は受け付けないという意味です。', 'Die Adresse existiert, akzeptiert aber diese Methode nicht.', "L'adresse existe mais n'accepte pas cette méthode.", 'पता है, पर वह विधि स्वीकार नहीं करता।'],
  '406': ['요청한 형식으로는 줄 수 없다는 뜻입니다.', 'The server cannot produce the format you asked for.', 'El servidor no puede dar el formato solicitado.', 'O servidor não consegue entregar o formato pedido.', '要求された形式では返せないという意味です。', 'Der Server kann das gewünschte Format nicht liefern.', "Le serveur ne peut pas fournir le format demandé.", 'सर्वर माँगा गया प्रारूप नहीं दे सकता।'],
  '407': ['중간 서버가 먼저 인증을 요구한다는 뜻입니다.', 'A proxy in between wants authentication first.', 'Un proxy intermedio exige autenticación antes.', 'Um proxy no meio exige autenticação antes.', '中間のサーバーが先に認証を求めるという意味です。', 'Ein zwischengeschalteter Proxy verlangt zuerst eine Anmeldung.', "Un proxy intermédiaire exige d'abord une authentification.", 'बीच का प्रॉक्सी पहले प्रमाणीकरण माँगता है।'],
  '408': ['기다렸는데 요청이 끝까지 오지 않았다는 뜻입니다.', 'The server waited and the request never finished arriving.', 'El servidor esperó y la petición nunca llegó entera.', 'O servidor esperou e o pedido nunca chegou por inteiro.', '待ったが要求が最後まで届かなかったという意味です。', 'Der Server hat gewartet, die Anfrage kam nie vollständig an.', "Le serveur a attendu, la requête n'est jamais arrivée entièrement.", 'सर्वर ने प्रतीक्षा की, पर अनुरोध पूरा नहीं पहुँचा।'],
  '409': ['지금 상태와 부딪혀 처리할 수 없다는 뜻입니다. 동시에 고칠 때 납니다.', 'The request clashes with the current state — typical of two edits at once.', 'La petición choca con el estado actual: típico de dos ediciones simultáneas.', 'O pedido conflita com o estado atual: típico de duas edições ao mesmo tempo.', '今の状態とぶつかって処理できないという意味です。同時に編集したときに出ます。', 'Die Anfrage kollidiert mit dem aktuellen Zustand — typisch bei gleichzeitigen Änderungen.', "La requête entre en conflit avec l'état actuel : typique de deux modifications simultanées.", 'अनुरोध मौजूदा स्थिति से टकराता है — दो लोग साथ बदलें तो यही आता है।'],
  '410': ['일부러 지웠고 다시 오지 않는다는 뜻입니다. 404보다 분명한 작별입니다.', 'Deliberately removed and not coming back — a clearer goodbye than 404.', 'Eliminado a propósito y sin vuelta: una despedida más clara que un 404.', 'Removido de propósito e não volta: uma despedida mais clara que 404.', '意図的に消され、戻らないという意味です。404よりはっきりした別れです。', 'Absichtlich entfernt und kehrt nicht zurück — ein klareres Lebewohl als 404.', "Supprimé volontairement et sans retour : un adieu plus net qu'un 404.", 'जानबूझकर हटाया गया और लौटेगा नहीं — 404 से साफ़ विदाई।'],
  '411': ['본문 길이를 밝히지 않았다는 뜻입니다.', 'The request must state its body length and did not.', 'La petición debe indicar la longitud del cuerpo y no lo hizo.', 'O pedido precisa informar o tamanho do corpo e não informou.', '本文の長さを示していないという意味です。', 'Die Anfrage muss ihre Body-Länge nennen, tat es aber nicht.', "La requête doit indiquer la longueur du corps, ce qu'elle n'a pas fait.", 'अनुरोध ने मुख्य भाग की लंबाई नहीं बताई।'],
  '412': ['붙여 보낸 조건이 맞지 않았다는 뜻입니다.', 'A condition attached to the request did not hold.', 'No se cumplió una condición adjunta a la petición.', 'Uma condição enviada com o pedido não se confirmou.', '添えて送った条件が合わなかったという意味です。', 'Eine mitgeschickte Bedingung traf nicht zu.', "Une condition jointe à la requête n'était pas remplie.", 'अनुरोध के साथ भेजी शर्त पूरी नहीं हुई।'],
  '413': ['보낸 본문이 서버가 받는 크기를 넘었다는 뜻입니다.', 'The body you sent is larger than the server accepts.', 'El cuerpo enviado supera el tamaño que admite el servidor.', 'O corpo enviado passa do tamanho que o servidor aceita.', '送った本文がサーバーの受け入れる大きさを超えたという意味です。', 'Der gesendete Body überschreitet das Serverlimit.', "Le corps envoyé dépasse la taille acceptée par le serveur.", 'भेजा गया मुख्य भाग सर्वर की सीमा से बड़ा है।'],
  '414': ['주소가 너무 길다는 뜻입니다. 쿼리를 지나치게 붙였을 때 납니다.', 'The URL is too long — usually the result of piling on query parameters.', 'La URL es demasiado larga: suele pasar al acumular parámetros.', 'A URL é longa demais: costuma acontecer ao empilhar parâmetros.', '住所が長すぎるという意味です。クエリを付けすぎたときに出ます。', 'Die URL ist zu lang — meist durch zu viele Query-Parameter.', "L'URL est trop longue : souvent trop de paramètres accumulés.", 'URL बहुत लंबा है — आमतौर पर बहुत सारे क्वेरी पैरामीटर से।'],
  '415': ['보낸 본문의 형식을 다룰 수 없다는 뜻입니다.', 'The server cannot handle the media type you sent.', 'El servidor no puede manejar el tipo de contenido enviado.', 'O servidor não lida com o tipo de conteúdo enviado.', '送った本文の形式を扱えないという意味です。', 'Der Server kann den gesendeten Medientyp nicht verarbeiten.', "Le serveur ne gère pas le type de contenu envoyé.", 'सर्वर भेजे गए मीडिया प्रकार को नहीं संभाल सकता।'],
  '416': ['요청한 범위가 파일 밖이라는 뜻입니다.', 'The requested byte range lies outside the file.', 'El rango solicitado queda fuera del archivo.', 'O intervalo pedido está fora do arquivo.', '要求された範囲がファイルの外だという意味です。', 'Der angeforderte Bereich liegt außerhalb der Datei.', "La plage demandée se situe hors du fichier.", 'माँगा गया परिसर फ़ाइल के बाहर है।'],
  '417': ['Expect 헤더에 적은 기대를 맞출 수 없다는 뜻입니다.', 'The expectation given in the Expect header cannot be met.', 'No se puede cumplir lo indicado en la cabecera Expect.', 'Não dá para cumprir o que o cabeçalho Expect pediu.', 'Expectヘッダーに書いた期待に応えられないという意味です。', 'Die im Expect-Header genannte Erwartung ist nicht erfüllbar.', "L'attente exprimée dans l'en-tête Expect ne peut être satisfaite.", 'Expect हेडर में बताई अपेक्षा पूरी नहीं की जा सकती।'],
  '418': ['커피를 끓여 달라는 요청을 찻주전자가 거절한다는 농담 코드입니다.', 'A joke code: the teapot refuses to brew coffee. It began as an April Fools RFC.', 'Un código en broma: la tetera se niega a hacer café. Nació de un RFC del día de los inocentes.', 'Um código de brincadeira: o bule se recusa a fazer café. Veio de um RFC de primeiro de abril.', 'コーヒーを淹れてという要求をティーポットが断る、という冗談のコードです。', 'Ein Scherzcode: Die Teekanne weigert sich, Kaffee zu kochen.', "Un code humoristique : la théière refuse de faire du café.", 'मज़ाक़ का कोड: चायदानी कॉफ़ी बनाने से मना करती है।'],
  '421': ['이 서버가 받을 요청이 아니라는 뜻입니다.', 'This server is not the right one to answer that request.', 'Este servidor no es el indicado para esa petición.', 'Este servidor não é o certo para esse pedido.', 'このサーバーが受けるべき要求ではないという意味です。', 'Dieser Server ist für die Anfrage nicht zuständig.', "Ce serveur n'est pas celui qui doit répondre.", 'यह अनुरोध इस सर्वर के लिए नहीं है।'],
  '422': ['형식은 맞지만 내용이 규칙에 어긋나 처리할 수 없다는 뜻입니다.', 'The syntax is fine but the content breaks the rules, so it cannot be processed.', 'La sintaxis es correcta, pero el contenido incumple las reglas.', 'A sintaxe está certa, mas o conteúdo quebra as regras.', '形式は正しいが内容が規則に反していて処理できないという意味です。', 'Die Syntax stimmt, doch der Inhalt verletzt die Regeln.', "La syntaxe est correcte mais le contenu enfreint les règles.", 'वाक्य-रचना ठीक है पर सामग्री नियम तोड़ती है, इसलिए काम नहीं हो सकता।'],
  '423': ['그 자원이 잠겨 있다는 뜻입니다.', 'The resource is locked.', 'El recurso está bloqueado.', 'O recurso está bloqueado.', 'その資源が施錠されているという意味です。', 'Die Ressource ist gesperrt.', 'La ressource est verrouillée.', 'संसाधन लॉक है।'],
  '424': ['앞선 요청이 실패해 이 요청도 못 한다는 뜻입니다.', 'An earlier request failed, so this one cannot go ahead either.', 'Falló una petición anterior, así que esta tampoco puede seguir.', 'Um pedido anterior falhou, então este também não segue.', '先の要求が失敗したので、この要求もできないという意味です。', 'Eine frühere Anfrage schlug fehl, daher scheitert auch diese.', "Une requête précédente a échoué, celle-ci ne peut donc aboutir.", 'पिछला अनुरोध विफल रहा, इसलिए यह भी नहीं हो सकता।'],
  '425': ['다시 보낼 위험이 있어 아직 처리하지 않는다는 뜻입니다.', 'The server will not risk processing a request that might be a replay.', 'El servidor no arriesga procesar algo que podría ser una repetición.', 'O servidor não arrisca processar algo que pode ser repetição.', '再送の危険があるのでまだ処理しないという意味です。', 'Der Server verarbeitet die möglicherweise wiederholte Anfrage noch nicht.', "Le serveur refuse de traiter une requête peut-être rejouée.", 'दोबारा भेजे जाने का ख़तरा है, इसलिए अभी काम नहीं किया गया।'],
  '426': ['다른 프로토콜로 올려야 이어갈 수 있다는 뜻입니다.', 'You must switch to a different protocol to continue.', 'Hay que cambiar de protocolo para continuar.', 'É preciso mudar de protocolo para continuar.', '別のプロトコルへ切り替えないと続けられないという意味です。', 'Zum Fortfahren muss auf ein anderes Protokoll gewechselt werden.', "Il faut passer à un autre protocole pour continuer.", 'आगे बढ़ने के लिए दूसरे प्रोटोकॉल पर जाना होगा।'],
  '428': ['조건을 붙여 보내야 한다는 뜻입니다. 덮어쓰기 사고를 막으려는 것입니다.', 'The request must carry a condition — this is how lost updates are prevented.', 'La petición debe llevar una condición: así se evitan sobrescrituras.', 'O pedido precisa levar uma condição: assim se evitam sobrescritas.', '条件を付けて送る必要があるという意味です。上書き事故を防ぐためです。', 'Die Anfrage muss eine Bedingung mitbringen — so werden verlorene Änderungen verhindert.', "La requête doit porter une condition : c'est ainsi qu'on évite les écrasements.", 'अनुरोध के साथ शर्त भेजनी होगी — इसी से ऊपर लिख जाने की दुर्घटना रुकती है।'],
  '429': ['너무 자주 요청했다는 뜻입니다. Retry-After에 다시 시도할 시간이 담깁니다.', 'You sent too many requests; Retry-After says when to try again.', 'Has hecho demasiadas peticiones; Retry-After indica cuándo reintentar.', 'Você fez pedidos demais; Retry-After diz quando tentar de novo.', '要求が多すぎるという意味です。Retry-Afterに再試行の時間が入ります。', 'Zu viele Anfragen; Retry-After nennt den nächsten Versuch.', "Trop de requêtes ; Retry-After indique quand réessayer.", 'बहुत ज़्यादा अनुरोध भेजे गए; Retry-After बताता है कब दोबारा कोशिश करें।'],
  '431': ['헤더가 너무 크다는 뜻입니다. 쿠키가 쌓였을 때 납니다.', 'The headers are too large — often the result of accumulated cookies.', 'Las cabeceras son demasiado grandes: suele deberse a cookies acumuladas.', 'Os cabeçalhos são grandes demais: costuma ser cookie acumulado.', 'ヘッダーが大きすぎるという意味です。クッキーがたまったときに出ます。', 'Die Header sind zu groß — oft durch angesammelte Cookies.', "Les en-têtes sont trop volumineux : souvent des cookies accumulés.", 'हेडर बहुत बड़े हैं — अक्सर जमा हुई कुकीज़ से।'],
  '451': ['법적인 이유로 막혔다는 뜻입니다. 번호는 소설 화씨 451도에서 왔습니다.', 'Blocked for legal reasons; the number nods to the novel Fahrenheit 451.', 'Bloqueado por motivos legales; el número alude a la novela Fahrenheit 451.', 'Bloqueado por motivos legais; o número alude ao romance Fahrenheit 451.', '法的な理由で遮断されたという意味です。番号は小説『華氏451度』に由来します。', 'Aus rechtlichen Gründen gesperrt; die Zahl spielt auf den Roman Fahrenheit 451 an.', "Bloqué pour raisons légales ; le nombre renvoie au roman Fahrenheit 451.", 'क़ानूनी कारणों से रोका गया; संख्या उपन्यास फ़ारेनहाइट 451 की ओर इशारा करती है।'],

  /* ───────── 5xx ───────── */
  '500': ['서버 안에서 문제가 났다는 뜻입니다. 요청은 잘못이 없습니다.', 'Something broke inside the server; the request itself was fine.', 'Algo falló dentro del servidor; la petición estaba bien.', 'Algo quebrou dentro do servidor; o pedido estava certo.', 'サーバーの中で問題が起きたという意味です。要求に落ち度はありません。', 'Im Server ist etwas schiefgegangen; die Anfrage war in Ordnung.', "Quelque chose a cassé côté serveur ; la requête était correcte.", 'सर्वर के भीतर कुछ बिगड़ा; अनुरोध में कोई ख़ामी नहीं थी।'],
  '501': ['그 기능을 서버가 아직 만들지 않았다는 뜻입니다.', 'The server does not implement that capability yet.', 'El servidor aún no implementa esa función.', 'O servidor ainda não implementa esse recurso.', 'その機能をサーバーがまだ実装していないという意味です。', 'Der Server unterstützt diese Funktion noch nicht.', "Le serveur n'implémente pas encore cette fonction.", 'सर्वर ने वह क्षमता अभी बनाई नहीं है।'],
  '502': ['앞 서버가 뒤 서버에게서 이상한 답을 받았다는 뜻입니다.', 'A gateway got a bad answer from the server behind it.', 'Una pasarela recibió una respuesta inválida del servidor de detrás.', 'Um gateway recebeu resposta inválida do servidor atrás dele.', '前のサーバーが後ろのサーバーからおかしな応答を受け取ったという意味です。', 'Ein Gateway erhielt vom dahinterliegenden Server eine ungültige Antwort.', "Une passerelle a reçu une réponse invalide du serveur situé derrière.", 'गेटवे को पीछे के सर्वर से ग़लत उत्तर मिला।'],
  '503': ['지금은 서버가 요청을 받을 수 없다는 뜻입니다. 점검이나 과부하 때 납니다.', 'The server cannot take requests right now — maintenance or overload.', 'El servidor no puede atender ahora: mantenimiento o sobrecarga.', 'O servidor não pode atender agora: manutenção ou sobrecarga.', '今はサーバーが要求を受けられないという意味です。点検や過負荷のときに出ます。', 'Der Server nimmt gerade keine Anfragen an — Wartung oder Überlast.', "Le serveur ne peut pas répondre pour l'instant : maintenance ou surcharge.", 'सर्वर अभी अनुरोध नहीं ले सकता — रखरखाव या अधिक भार।'],
  '504': ['앞 서버가 뒤 서버를 기다리다 시간이 다 됐다는 뜻입니다.', 'A gateway waited for the server behind it and ran out of time.', 'Una pasarela esperó al servidor de detrás y se agotó el tiempo.', 'Um gateway esperou o servidor atrás dele e o tempo acabou.', '前のサーバーが後ろのサーバーを待ちきれなかったという意味です。', 'Ein Gateway wartete zu lange auf den dahinterliegenden Server.', "Une passerelle a attendu le serveur situé derrière jusqu'à expiration.", 'गेटवे पीछे के सर्वर की प्रतीक्षा करते-करते समय पार कर गया।'],
  '505': ['그 HTTP 판을 지원하지 않는다는 뜻입니다.', 'That HTTP version is not supported.', 'No se admite esa versión de HTTP.', 'Essa versão do HTTP não é suportada.', 'そのHTTPの版に対応していないという意味です。', 'Diese HTTP-Version wird nicht unterstützt.', "Cette version de HTTP n'est pas prise en charge.", 'वह HTTP संस्करण समर्थित नहीं है।'],
  '506': ['서버 설정이 잘못 얽혀 스스로 순환한다는 뜻입니다.', 'A server configuration error makes content negotiation loop on itself.', 'Un error de configuración hace que la negociación de contenido entre en bucle.', 'Um erro de configuração faz a negociação de conteúdo entrar em laço.', 'サーバー設定の誤りで内容の選択が堂々巡りになるという意味です。', 'Ein Konfigurationsfehler lässt die Aushandlung im Kreis laufen.', "Une erreur de configuration fait boucler la négociation de contenu.", 'सर्वर सेटिंग की ग़लती से सामग्री-चयन अपने ही चक्कर में फँस जाता है।'],
  '507': ['저장할 자리가 모자란다는 뜻입니다.', 'There is not enough storage left to finish.', 'No queda espacio suficiente para completar.', 'Não há espaço suficiente para concluir.', '保存する場所が足りないという意味です。', 'Es ist nicht genug Speicherplatz vorhanden.', "Il ne reste pas assez d'espace pour aboutir.", 'पूरा करने के लिए पर्याप्त जगह नहीं बची।'],
  '508': ['처리하다 같은 자리를 맴돌았다는 뜻입니다.', 'The server detected an infinite loop while processing.', 'El servidor detectó un bucle infinito al procesar.', 'O servidor detectou um laço infinito ao processar.', '処理中に同じところを堂々巡りしたという意味です。', 'Der Server erkannte beim Verarbeiten eine Endlosschleife.', "Le serveur a détecté une boucle infinie pendant le traitement.", 'सर्वर ने काम करते समय अनंत लूप पकड़ा।'],
  '510': ['요청에 확장이 더 필요하다는 뜻입니다.', 'The request needs a further extension to be fulfilled.', 'La petición necesita una extensión adicional.', 'O pedido precisa de uma extensão adicional.', '要求にさらに拡張が必要という意味です。', 'Die Anfrage benötigt eine weitere Erweiterung.', "La requête nécessite une extension supplémentaire.", 'अनुरोध को और विस्तार चाहिए।'],
  '511': ['네트워크에 먼저 로그인해야 한다는 뜻입니다. 공용 와이파이에서 자주 만납니다.', 'You must sign in to the network first — the usual sight on public Wi-Fi.', 'Hay que iniciar sesión en la red primero: lo habitual en wifi público.', 'É preciso entrar na rede primeiro: comum em wi-fi público.', 'まずネットワークにログインする必要があるという意味です。公衆Wi-Fiでよく見かけます。', 'Zuerst im Netzwerk anmelden — der übliche Anblick in öffentlichem WLAN.', "Il faut d'abord se connecter au réseau : classique sur un Wi-Fi public.", 'पहले नेटवर्क में लॉगिन करना होगा — सार्वजनिक वाई-फ़ाई पर आम।'],

  /* ───────── 요청 헤더 ───────── */
  accept: ['어떤 형식으로 받고 싶은지 알립니다.', 'Tells the server which formats the client can accept.', 'Indica qué formatos acepta el cliente.', 'Informa quais formatos o cliente aceita.', 'どの形式で受け取りたいかを伝えます。', 'Nennt die Formate, die der Client annehmen kann.', "Indique les formats acceptés par le client.", 'बताता है कि क्लाइंट कौन-से प्रारूप स्वीकार करता है।'],
  'accept-encoding': ['압축 방식을 알립니다. gzip이나 br을 쓰면 전송량이 크게 줄어듭니다.', 'Lists the compressions the client understands; gzip or br cut transfer size a lot.', 'Lista las compresiones que entiende el cliente; gzip o br reducen mucho el tamaño.', 'Lista as compressões que o cliente entende; gzip ou br reduzem muito o tamanho.', '圧縮方式を伝えます。gzipやbrを使うと転送量が大きく減ります。', 'Nennt die verstandenen Kompressionen; gzip oder br sparen viel Übertragung.', "Indique les compressions comprises ; gzip ou br réduisent beaucoup le transfert.", 'बताता है कि क्लाइंट कौन-सा संपीड़न समझता है; gzip या br से आकार काफ़ी घटता है।'],
  'accept-language': ['원하는 언어를 알립니다. 여러 언어 사이트가 이 값을 보고 고릅니다.', 'States the preferred languages; multilingual sites pick a version from it.', 'Declara los idiomas preferidos; los sitios multilingües eligen con esto.', 'Declara os idiomas preferidos; sites multilíngues escolhem por aqui.', '希望する言語を伝えます。多言語サイトはこの値を見て選びます。', 'Nennt die bevorzugten Sprachen; mehrsprachige Seiten wählen danach.', "Déclare les langues préférées ; les sites multilingues s'en servent.", 'पसंदीदा भाषाएँ बताता है; बहुभाषी साइटें इसी से चुनती हैं।'],
  authorization: ['신원을 증명하는 값입니다. 토큰이나 아이디·비밀번호가 담깁니다.', 'Carries the credentials that prove who you are — a token or a username and password.', 'Lleva las credenciales que prueban quién eres: un token o usuario y contraseña.', 'Leva as credenciais que provam quem você é: um token ou usuário e senha.', '身元を証明する値です。トークンやIDとパスワードが入ります。', 'Trägt die Zugangsdaten — ein Token oder Benutzername und Passwort.', "Porte les identifiants prouvant qui vous êtes : jeton ou identifiant et mot de passe.", 'पहचान साबित करने वाले क्रेडेंशियल — टोकन या उपयोगकर्ता नाम और पासवर्ड।'],
  cookie: ['앞서 서버가 심어 둔 쿠키를 도로 보냅니다.', 'Sends back the cookies the server set earlier.', 'Devuelve las cookies que el servidor guardó antes.', 'Devolve os cookies que o servidor guardou antes.', '先にサーバーが置いたクッキーを送り返します。', 'Sendet die zuvor gesetzten Cookies zurück.', "Renvoie les cookies posés précédemment par le serveur.", 'सर्वर द्वारा पहले रखी कुकीज़ वापस भेजता है।'],
  host: ['어느 도메인에 보내는 요청인지 밝힙니다. 한 서버가 여러 사이트를 담을 수 있게 합니다.', 'Names the domain being addressed — what lets one server host many sites.', 'Indica el dominio solicitado: permite que un servidor aloje muchos sitios.', 'Indica o domínio solicitado: permite que um servidor hospede vários sites.', 'どのドメイン宛ての要求かを示します。一台のサーバーが複数サイトを持てるのはこのためです。', 'Nennt die angesprochene Domain — deshalb kann ein Server viele Sites bedienen.', "Nomme le domaine visé : c'est ce qui permet à un serveur d'héberger plusieurs sites.", 'बताता है कि अनुरोध किस डोमेन के लिए है — इसी से एक सर्वर कई साइटें रख पाता है।'],
  'if-modified-since': ['그 시각 이후에 바뀌었을 때만 달라는 뜻입니다.', 'Asks for the resource only if it changed after that time.', 'Pide el recurso solo si cambió después de esa hora.', 'Pede o recurso só se mudou depois daquele horário.', 'その時刻より後に変わっていたときだけ送るように求めます。', 'Fordert die Ressource nur an, wenn sie sich seither geändert hat.', "Ne demande la ressource que si elle a changé depuis.", 'संसाधन तभी माँगता है जब वह उस समय के बाद बदला हो।'],
  'if-none-match': ['가진 ETag와 다를 때만 달라는 뜻입니다. 캐시가 이렇게 확인합니다.', 'Asks for the resource only if its ETag differs — this is how a cache revalidates.', 'Pide el recurso solo si su ETag difiere: así revalida la caché.', 'Pede o recurso só se o ETag for diferente: é assim que o cache revalida.', '持っているETagと違うときだけ送るように求めます。キャッシュはこうして確かめます。', 'Fordert die Ressource nur bei abweichendem ETag — so prüft ein Cache nach.', "Ne demande la ressource que si son ETag diffère : ainsi le cache se revalide.", 'संसाधन तभी माँगता है जब उसका ETag अलग हो — कैश ऐसे ही पुनः जाँचता है।'],
  origin: ['요청을 보낸 출처를 알립니다. 브라우저가 붙이며 CORS 판단의 기준이 됩니다.', 'States where the request came from; the browser adds it and CORS decisions rest on it.', 'Indica el origen de la petición; lo añade el navegador y CORS se basa en él.', 'Informa a origem do pedido; o navegador adiciona e o CORS se baseia nele.', '要求の出どころを伝えます。ブラウザーが付け、CORSの判断の基準になります。', 'Nennt die Herkunft der Anfrage; der Browser setzt ihn, CORS entscheidet danach.', "Indique l'origine de la requête ; ajouté par le navigateur, il fonde les décisions CORS.", 'अनुरोध का स्रोत बताता है; ब्राउज़र जोड़ता है और CORS इसी पर निर्णय लेता है।'],
  range: ['파일의 일부만 달라는 뜻입니다. 이어받기와 영상 탐색이 이걸로 됩니다.', 'Requests only part of a file — the basis of resumable downloads and video seeking.', 'Pide solo una parte del archivo: la base de la reanudación y del salto en vídeo.', 'Pede só parte do arquivo: a base da retomada e da busca em vídeo.', 'ファイルの一部だけを求めます。再開やシークはこれで実現します。', 'Fordert nur einen Teil der Datei — Grundlage für Fortsetzen und Videosprünge.', "Ne demande qu'une partie du fichier : base de la reprise et du déplacement vidéo.", 'फ़ाइल का सिर्फ़ एक हिस्सा माँगता है — डाउनलोड फिर से शुरू करने और वीडियो सीक का आधार।'],
  referer: ['어느 페이지에서 눌러 왔는지 알립니다. 철자가 틀린 채로 표준이 됐습니다.', 'Names the page you came from; the misspelling was baked into the standard long ago.', 'Indica la página de procedencia; el error ortográfico quedó fijado en el estándar.', 'Indica a página de origem; o erro de grafia ficou fixado no padrão.', 'どのページから来たかを伝えます。綴りの誤りのまま標準になりました。', 'Nennt die Herkunftsseite; der Tippfehler wurde Teil des Standards.', "Indique la page d'où l'on vient ; la faute d'orthographe est passée dans la norme.", 'बताता है कि किस पन्ने से आए; वर्तनी की ग़लती मानक में ही रह गई।'],
  'user-agent': ['어떤 브라우저와 기기인지 알립니다. 지금은 대부분 비슷하게 위장돼 있습니다.', 'Describes the browser and device; these strings are mostly camouflage nowadays.', 'Describe el navegador y el dispositivo; hoy casi todo es camuflaje.', 'Descreve o navegador e o aparelho; hoje quase tudo é camuflagem.', 'どのブラウザーと機器かを伝えます。今はほとんどが似たように偽装されています。', 'Beschreibt Browser und Gerät; heute sind diese Angaben meist Tarnung.', "Décrit le navigateur et l'appareil ; ces chaînes relèvent surtout du camouflage.", 'ब्राउज़र और डिवाइस बताता है; आजकल ये अधिकतर छद्म ही होते हैं।'],
  'sec-fetch-dest': ['그 요청이 무엇에 쓰일지 알립니다. 그림인지 스크립트인지 같은 것입니다.', 'Says what the request is for — an image, a script, a document.', 'Dice para qué es la petición: imagen, script, documento.', 'Diz para que serve o pedido: imagem, script, documento.', 'その要求が何に使われるか（画像かスクリプトか）を伝えます。', 'Sagt, wofür die Anfrage ist — Bild, Skript, Dokument.', "Précise l'usage de la requête : image, script, document.", 'बताता है कि अनुरोध किस काम का है — चित्र, स्क्रिप्ट या दस्तावेज़।'],
  'sec-fetch-mode': ['요청 방식이 같은 출처인지 CORS인지 알립니다.', 'States whether the request is same-origin, CORS or a navigation.', 'Indica si la petición es del mismo origen, CORS o navegación.', 'Indica se o pedido é de mesma origem, CORS ou navegação.', '要求が同一出所かCORSかを伝えます。', 'Gibt an, ob die Anfrage gleiche Herkunft, CORS oder Navigation ist.', "Indique si la requête est de même origine, CORS ou navigation.", 'बताता है कि अनुरोध समान-मूल है, CORS है या नेविगेशन।'],
  'sec-fetch-site': ['요청이 같은 사이트에서 왔는지 다른 사이트에서 왔는지 알립니다.', 'Says whether the request came from the same site or a different one.', 'Dice si la petición viene del mismo sitio o de otro.', 'Diz se o pedido veio do mesmo site ou de outro.', '要求が同じサイトからか別のサイトからかを伝えます。', 'Sagt, ob die Anfrage von derselben oder einer anderen Site kam.', "Dit si la requête vient du même site ou d'un autre.", 'बताता है कि अनुरोध उसी साइट से आया या किसी और से।'],
  dnt: ['추적하지 말라는 요청입니다. 강제력이 없어 대부분 무시됩니다.', 'Asks not to be tracked; it carries no force and is largely ignored.', 'Pide no ser rastreado; no obliga a nada y suele ignorarse.', 'Pede para não ser rastreado; não obriga nada e costuma ser ignorado.', '追跡しないでほしいという要求です。強制力がなくほとんど無視されます。', 'Bittet, nicht verfolgt zu werden; unverbindlich und meist ignoriert.', "Demande à ne pas être suivi ; sans force contraignante, souvent ignoré.", 'ट्रैक न करने का अनुरोध; बाध्यकारी नहीं है, इसलिए अक्सर अनदेखा होता है।'],
  expect: ['본문을 보내기 전에 서버가 받을지 먼저 묻습니다.', 'Checks with the server before sending a large body.', 'Consulta al servidor antes de enviar un cuerpo grande.', 'Consulta o servidor antes de enviar um corpo grande.', '本文を送る前に、サーバーが受け取るかを先に尋ねます。', 'Fragt beim Server nach, bevor ein großer Body gesendet wird.', "Interroge le serveur avant d'envoyer un corps volumineux.", 'बड़ा मुख्य भाग भेजने से पहले सर्वर से पूछता है।'],
  forwarded: ['중간을 거친 요청의 원래 정보를 담습니다.', 'Records the original client details of a request that passed through proxies.', 'Guarda los datos originales del cliente tras pasar por proxies.', 'Guarda os dados originais do cliente após passar por proxies.', '中継を経た要求の元の情報を記録します。', 'Hält die ursprünglichen Client-Angaben nach Proxys fest.', "Conserve les informations d'origine après passage par des proxys.", 'प्रॉक्सी से गुज़रे अनुरोध की मूल जानकारी रखता है।'],
  from: ['요청을 보낸 사람의 이메일을 담습니다. 크롤러가 연락처로 씁니다.', 'Carries an email address for whoever sent the request; crawlers use it as contact.', 'Lleva el correo de quien hace la petición; los rastreadores lo usan de contacto.', 'Leva o e-mail de quem faz o pedido; rastreadores usam como contato.', '要求した人のメールアドレスを入れます。クローラーが連絡先として使います。', 'Enthält eine E-Mail-Adresse des Anfragenden; Crawler nutzen sie als Kontakt.', "Contient l'e-mail de l'auteur de la requête ; les robots s'en servent comme contact.", 'अनुरोध भेजने वाले का ईमेल; क्रॉलर इसे संपर्क के रूप में देते हैं।'],
  'if-match': ['가진 ETag와 같을 때만 처리하라는 뜻입니다. 덮어쓰기 사고를 막습니다.', 'Proceed only if the ETag matches — this prevents overwriting someone else’s change.', 'Solo procede si el ETag coincide: evita sobrescribir cambios ajenos.', 'Só prossegue se o ETag bater: evita sobrescrever mudanças alheias.', '持っているETagと同じときだけ処理するように求めます。上書き事故を防ぎます。', 'Nur fortfahren, wenn der ETag übereinstimmt — verhindert Überschreiben.', "N'agir que si l'ETag correspond : évite d'écraser le travail d'autrui.", 'तभी आगे बढ़ें जब ETag मेल खाए — दूसरों का बदलाव मिटने से बचता है।'],
  'if-range': ['조건이 맞으면 이어받고, 아니면 처음부터 받겠다는 뜻입니다.', 'Resume the download if the file is unchanged; otherwise start over.', 'Reanuda si el archivo no cambió; si no, empieza de cero.', 'Retoma se o arquivo não mudou; caso contrário, começa do zero.', '条件が合えば続きから、合わなければ最初から受け取ります。', 'Fortsetzen, wenn die Datei unverändert ist; sonst neu beginnen.', "Reprendre si le fichier n'a pas changé, sinon tout recommencer.", 'फ़ाइल न बदली हो तो आगे से, वरना शुरू से।'],
  'max-forwards': ['중간 서버를 몇 번까지 거칠지 정합니다.', 'Limits how many proxies a request may pass through.', 'Limita por cuántos proxies puede pasar la petición.', 'Limita por quantos proxies o pedido pode passar.', '中間サーバーを何回まで経由してよいかを決めます。', 'Begrenzt, über wie viele Proxys eine Anfrage laufen darf.', "Limite le nombre de proxys traversés.", 'सीमित करता है कि अनुरोध कितने प्रॉक्सी से गुज़रे।'],
  'proxy-authorization': ['중간 서버에 내는 인증 정보입니다.', 'Credentials presented to a proxy rather than the origin server.', 'Credenciales para el proxy, no para el servidor de origen.', 'Credenciais para o proxy, não para o servidor de origem.', '中間サーバーに示す認証情報です。', 'Zugangsdaten für den Proxy statt für den Ursprungsserver.', "Identifiants destinés au proxy, non au serveur d'origine.", 'प्रॉक्सी को दिए जाने वाले क्रेडेंशियल, मूल सर्वर को नहीं।'],
  te: ['전송 중에 어떤 인코딩을 받아들일지 알립니다.', 'Lists the transfer encodings the client will accept.', 'Lista las codificaciones de transferencia aceptadas.', 'Lista as codificações de transferência aceitas.', '転送中にどの符号化を受け入れるかを伝えます。', 'Nennt die akzeptierten Transfer-Codierungen.', "Indique les encodages de transfert acceptés.", 'बताता है कि कौन-सी ट्रांसफ़र एन्कोडिंग स्वीकार्य है।'],
  'upgrade-insecure-requests': ['http로 걸린 링크도 https로 바꿔 달라는 요청입니다.', 'Asks the server to upgrade any plain http links to https.', 'Pide al servidor que convierta los enlaces http en https.', 'Pede ao servidor que troque links http por https.', 'httpのリンクもhttpsに変えてほしいという要求です。', 'Bittet den Server, http-Links auf https zu heben.', "Demande au serveur de passer les liens http en https.", 'सर्वर से कहता है कि http लिंक भी https कर दे।'],
  'x-forwarded-for': ['중간을 거친 요청의 원래 IP를 담습니다. 표준은 아니지만 널리 쓰입니다.', 'Carries the original client IP through proxies; not standard but used everywhere.', 'Lleva la IP original del cliente a través de proxies; no es estándar pero se usa mucho.', 'Leva o IP original do cliente através de proxies; não é padrão, mas é muito usado.', '中継を経た要求の元のIPを入れます。標準ではありませんが広く使われます。', 'Trägt die ursprüngliche Client-IP durch Proxys; kein Standard, aber verbreitet.', "Transporte l'IP d'origine à travers les proxys ; non normalisé mais très répandu.", 'प्रॉक्सी के पार मूल क्लाइंट IP ले जाता है; मानक नहीं, पर हर जगह प्रचलित।'],
  'x-forwarded-proto': ['원래 요청이 http였는지 https였는지 알립니다.', 'Says whether the original request arrived over http or https.', 'Indica si la petición original llegó por http o https.', 'Diz se o pedido original chegou por http ou https.', '元の要求がhttpだったかhttpsだったかを伝えます。', 'Gibt an, ob die ursprüngliche Anfrage über http oder https kam.', "Indique si la requête initiale est arrivée en http ou https.", 'बताता है कि मूल अनुरोध http से आया या https से।'],
  'x-requested-with': ['자바스크립트가 보낸 요청임을 알리던 옛 관행입니다.', 'An old convention marking a request as coming from JavaScript.', 'Una convención antigua para marcar peticiones hechas por JavaScript.', 'Uma convenção antiga para marcar pedidos feitos por JavaScript.', 'JavaScriptからの要求であることを示していた古い慣習です。', 'Eine alte Konvention, die JavaScript-Anfragen kennzeichnete.', "Une vieille convention marquant les requêtes issues de JavaScript.", 'जावास्क्रिप्ट से आए अनुरोध को चिह्नित करने की पुरानी परिपाटी।'],

  /* ───────── 응답 헤더 ───────── */
  'access-control-allow-origin': ['어느 출처에서 이 응답을 읽어도 되는지 정합니다. CORS의 핵심입니다.', 'Names which origins may read this response — the heart of CORS.', 'Indica qué orígenes pueden leer esta respuesta: el núcleo de CORS.', 'Indica quais origens podem ler esta resposta: o coração do CORS.', 'どの出所がこの応答を読んでよいかを決めます。CORSの中心です。', 'Nennt die Ursprünge, die diese Antwort lesen dürfen — der Kern von CORS.', "Nomme les origines autorisées à lire la réponse : le cœur de CORS.", 'बताता है कि कौन-से मूल यह उत्तर पढ़ सकते हैं — CORS का केंद्र।'],
  'access-control-allow-methods': ['교차 출처 요청에 허용하는 방식들을 적습니다.', 'Lists the methods allowed for cross-origin requests.', 'Lista los métodos permitidos en peticiones de otro origen.', 'Lista os métodos permitidos em pedidos de outra origem.', '別出所からの要求に許す方式を並べます。', 'Listet die für ursprungsübergreifende Anfragen erlaubten Methoden.', "Liste les méthodes autorisées en requête cross-origine.", 'क्रॉस-ऑरिजिन अनुरोधों के लिए अनुमत विधियाँ बताता है।'],
  'access-control-allow-headers': ['교차 출처 요청에 허용하는 헤더들을 적습니다.', 'Lists the headers allowed on cross-origin requests.', 'Lista las cabeceras permitidas en peticiones de otro origen.', 'Lista os cabeçalhos permitidos em pedidos de outra origem.', '別出所からの要求に許すヘッダーを並べます。', 'Listet die bei ursprungsübergreifenden Anfragen erlaubten Header.', "Liste les en-têtes autorisés en requête cross-origine.", 'क्रॉस-ऑरिजिन अनुरोधों में अनुमत हेडर बताता है।'],
  'access-control-allow-credentials': ['쿠키를 실어 보내는 교차 출처 요청을 허용할지 정합니다.', 'Decides whether cross-origin requests may carry cookies.', 'Decide si las peticiones de otro origen pueden llevar cookies.', 'Decide se pedidos de outra origem podem levar cookies.', 'クッキーを載せた別出所の要求を許すかを決めます。', 'Legt fest, ob ursprungsübergreifende Anfragen Cookies mitführen dürfen.', "Détermine si les requêtes cross-origine peuvent porter des cookies.", 'तय करता है कि क्रॉस-ऑरिजिन अनुरोध कुकीज़ ले जा सकें या नहीं।'],
  'access-control-max-age': ['사전 요청 결과를 얼마나 오래 재사용할지 정합니다.', 'Says how long the preflight result may be cached.', 'Indica cuánto se puede cachear el resultado del preflight.', 'Diz por quanto tempo o resultado do preflight pode ser cacheado.', '事前要求の結果をどれだけ再利用してよいかを決めます。', 'Gibt an, wie lange das Preflight-Ergebnis gilt.', "Indique la durée de mise en cache du préflight.", 'बताता है कि प्रीफ़्लाइट परिणाम कितनी देर कैश रहे।'],
  age: ['이 응답이 캐시에 머문 시간입니다.', 'How long the response has been sitting in a cache.', 'Cuánto lleva la respuesta en la caché.', 'Há quanto tempo a resposta está no cache.', 'この応答がキャッシュにとどまっていた時間です。', 'Wie lange die Antwort schon im Cache liegt.', "Depuis combien de temps la réponse est en cache.", 'यह उत्तर कैश में कितनी देर से पड़ा है।'],
  allow: ['그 주소가 받아들이는 방식들을 알립니다. 405와 함께 옵니다.', 'Lists the methods the address accepts; it accompanies a 405.', 'Lista los métodos que admite la dirección; acompaña a un 405.', 'Lista os métodos que o endereço aceita; acompanha um 405.', 'その住所が受け付ける方式を伝えます。405と一緒に来ます。', 'Nennt die akzeptierten Methoden; begleitet einen 405.', "Liste les méthodes acceptées ; accompagne un 405.", 'बताता है कि पता कौन-सी विधियाँ स्वीकारता है; 405 के साथ आता है।'],
  'content-disposition': ['화면에 열지 내려받을지 정합니다. 파일 이름도 여기에 담깁니다.', 'Decides whether to display inline or download, and carries the file name.', 'Decide si se muestra o se descarga, y lleva el nombre del archivo.', 'Decide se exibe ou baixa, e leva o nome do arquivo.', '画面で開くか保存するかを決めます。ファイル名もここに入ります。', 'Bestimmt Anzeigen oder Herunterladen und trägt den Dateinamen.', "Décide de l'affichage ou du téléchargement et porte le nom du fichier.", 'तय करता है कि दिखे या डाउनलोड हो, और फ़ाइल नाम भी रखता है।'],
  'content-security-policy': ['어디서 온 스크립트와 이미지를 실행·표시할지 정합니다. XSS를 막는 울타리입니다.', 'Controls where scripts and images may come from — the fence that blunts XSS.', 'Controla de dónde pueden venir scripts e imágenes: la valla contra XSS.', 'Controla de onde scripts e imagens podem vir: a cerca contra XSS.', 'どこから来たスクリプトや画像を実行・表示してよいかを決めます。XSSを防ぐ柵です。', 'Steuert, woher Skripte und Bilder stammen dürfen — der Zaun gegen XSS.', "Contrôle l'origine autorisée des scripts et images : la barrière contre le XSS.", 'तय करता है कि स्क्रिप्ट और चित्र कहाँ से आ सकते हैं — XSS रोकने की बाड़।'],
  etag: ['그 판의 지문입니다. 바뀌면 값이 달라져 캐시가 알아챕니다.', 'A fingerprint of this version; change the content and the tag changes, so caches notice.', 'Una huella de esta versión: si cambia el contenido, cambia la etiqueta y la caché lo nota.', 'Uma impressão digital desta versão: muda o conteúdo, muda a etiqueta, e o cache percebe.', 'その版の指紋です。中身が変わると値も変わり、キャッシュが気づきます。', 'Ein Fingerabdruck dieser Fassung; ändert sich der Inhalt, ändert sich das Tag.', "Une empreinte de cette version : le contenu change, l'étiquette aussi, et le cache le voit.", 'इस संस्करण की छाप; सामग्री बदले तो टैग बदलता है और कैश भाँप लेता है।'],
  expires: ['이 시각이 지나면 낡은 것으로 보라는 뜻입니다.', 'Marks the moment after which the response is considered stale.', 'Marca el momento tras el cual la respuesta se considera vieja.', 'Marca o momento após o qual a resposta é considerada velha.', 'この時刻を過ぎたら古いものとして扱うように、という意味です。', 'Nennt den Zeitpunkt, ab dem die Antwort als veraltet gilt.', "Indique l'instant après lequel la réponse est périmée.", 'बताता है कि इस समय के बाद उत्तर बासी माना जाए।'],
  'last-modified': ['마지막으로 바뀐 시각입니다. 조건부 요청의 기준이 됩니다.', 'When the resource last changed; conditional requests compare against it.', 'Cuándo cambió por última vez; las peticiones condicionales lo comparan.', 'Quando mudou pela última vez; pedidos condicionais comparam com isso.', '最後に変わった時刻です。条件付き要求の基準になります。', 'Wann sich die Ressource zuletzt geändert hat; Basis bedingter Anfragen.', "Date de dernière modification ; référence des requêtes conditionnelles.", 'अंतिम बार कब बदला; सशर्त अनुरोध इसी से तुलना करते हैं।'],
  location: ['다음에 갈 주소입니다. 넘김 응답과 201에 함께 옵니다.', 'The address to go to next; it accompanies redirects and a 201.', 'La dirección a la que ir; acompaña a las redirecciones y al 201.', 'O endereço para onde ir; acompanha redirecionamentos e o 201.', '次に行く住所です。転送応答や201と一緒に来ます。', 'Die nächste Adresse; begleitet Weiterleitungen und 201.', "L'adresse suivante ; accompagne les redirections et le 201.", 'अगला पता; रीडायरेक्ट और 201 के साथ आता है।'],
  'permissions-policy': ['카메라·마이크·위치 같은 기능을 어느 문서가 쓸 수 있는지 정합니다.', 'Controls which documents may use features such as camera, microphone and location.', 'Controla qué documentos pueden usar cámara, micrófono o ubicación.', 'Controla quais documentos podem usar câmera, microfone ou localização.', 'カメラ・マイク・位置などの機能をどの文書が使えるかを決めます。', 'Regelt, welche Dokumente Kamera, Mikrofon oder Standort nutzen dürfen.', "Contrôle quels documents peuvent utiliser caméra, micro ou position.", 'तय करता है कि कैमरा, माइक और स्थान जैसे फ़ीचर कौन इस्तेमाल करे।'],
  'referrer-policy': ['출처 정보를 얼마나 실어 보낼지 정합니다.', 'Decides how much referrer information is passed along.', 'Decide cuánta información de procedencia se envía.', 'Decide quanta informação de origem é enviada.', '出所の情報をどこまで送るかを決めます。', 'Bestimmt, wie viel Referrer-Information mitgeht.', "Détermine la quantité d'information de provenance transmise.", 'तय करता है कि रेफ़रर की कितनी जानकारी भेजी जाए।'],
  'retry-after': ['언제 다시 시도하면 되는지 알립니다. 429·503과 함께 옵니다.', 'Says when to try again; it accompanies a 429 or a 503.', 'Indica cuándo reintentar; acompaña a un 429 o un 503.', 'Diz quando tentar de novo; acompanha um 429 ou 503.', 'いつ再試行すればよいかを伝えます。429や503と一緒に来ます。', 'Nennt den nächsten Versuch; begleitet 429 oder 503.', "Indique quand réessayer ; accompagne un 429 ou un 503.", 'बताता है कब दोबारा कोशिश करें; 429 या 503 के साथ आता है।'],
  server: ['응답한 서버 소프트웨어를 알립니다. 자세히 적으면 공격에 힌트가 됩니다.', 'Names the server software; too much detail hands attackers a hint.', 'Nombra el software del servidor; demasiado detalle da pistas a los atacantes.', 'Diz o software do servidor; detalhe demais dá pista a atacantes.', '応答したサーバーのソフトウェアを伝えます。詳しく書くと攻撃の手がかりになります。', 'Nennt die Serversoftware; zu viele Details helfen Angreifern.', "Indique le logiciel serveur ; trop de détails renseigne les attaquants.", 'सर्वर सॉफ़्टवेयर बताता है; ज़्यादा ब्योरा हमलावरों को संकेत देता है।'],
  'set-cookie': ['브라우저에 쿠키를 심습니다. HttpOnly와 Secure를 붙이는 것이 안전합니다.', 'Plants a cookie in the browser; add HttpOnly and Secure to keep it safe.', 'Coloca una cookie en el navegador; añade HttpOnly y Secure para protegerla.', 'Coloca um cookie no navegador; use HttpOnly e Secure para protegê-lo.', 'ブラウザーにクッキーを置きます。HttpOnlyとSecureを付けるのが安全です。', 'Setzt ein Cookie im Browser; mit HttpOnly und Secure ist es sicherer.', "Dépose un cookie dans le navigateur ; HttpOnly et Secure le sécurisent.", 'ब्राउज़र में कुकी रखता है; HttpOnly और Secure लगाना सुरक्षित रहता है।'],
  'strict-transport-security': ['앞으로 이 사이트는 https로만 오라고 브라우저에 새깁니다.', 'Tells the browser to reach this site over https from now on.', 'Indica al navegador que use solo https en este sitio a partir de ahora.', 'Diz ao navegador para usar só https neste site daqui em diante.', 'これ以降このサイトへはhttpsだけで来るようブラウザーに刻みます。', 'Weist den Browser an, diese Site künftig nur über https zu laden.', "Impose au navigateur d'accéder désormais au site en https.", 'ब्राउज़र से कहता है कि अब से यह साइट सिर्फ़ https पर खोले।'],
  'timing-allow-origin': ['다른 출처가 성능 측정값을 읽어도 되는지 정합니다.', 'Allows another origin to read detailed timing measurements.', 'Permite que otro origen lea las mediciones de rendimiento.', 'Permite que outra origem leia as medições de desempenho.', '別の出所が性能の計測値を読んでよいかを決めます。', 'Erlaubt einer anderen Herkunft, Timing-Messwerte zu lesen.', "Autorise une autre origine à lire les mesures de performance.", 'तय करता है कि दूसरा मूल समय-मापन पढ़ सके या नहीं।'],
  vary: ['같은 주소라도 어떤 헤더에 따라 응답이 달라지는지 알립니다. 캐시가 이걸 보고 나눕니다.', 'Names the headers that change the response; caches key on it.', 'Indica qué cabeceras cambian la respuesta; la caché se guía por ella.', 'Indica quais cabeçalhos mudam a resposta; o cache se guia por ela.', '同じ住所でもどのヘッダー次第で応答が変わるかを伝えます。キャッシュはこれを見て分けます。', 'Nennt die Header, die die Antwort verändern; Caches schlüsseln danach.', "Nomme les en-têtes qui font varier la réponse ; les caches s'y fient.", 'बताता है कि कौन-से हेडर उत्तर बदलते हैं; कैश इसी से बाँटता है।'],
  'www-authenticate': ['어떤 방식으로 인증하라고 알려 줍니다. 401과 함께 옵니다.', 'States which authentication scheme to use; it accompanies a 401.', 'Indica el esquema de autenticación; acompaña a un 401.', 'Indica o esquema de autenticação; acompanha um 401.', 'どの方式で認証するかを知らせます。401と一緒に来ます。', 'Nennt das Authentifizierungsverfahren; begleitet einen 401.', "Indique le schéma d'authentification ; accompagne un 401.", 'बताता है कि किस विधि से प्रमाणीकरण हो; 401 के साथ आता है।'],
  'x-content-type-options': ['형식을 브라우저가 멋대로 짐작하지 못하게 막습니다.', 'Stops the browser guessing a different content type than declared.', 'Impide que el navegador adivine otro tipo de contenido.', 'Impede o navegador de adivinhar outro tipo de conteúdo.', '形式をブラウザーが勝手に推測しないようにします。', 'Verhindert, dass der Browser einen anderen Inhaltstyp errät.', "Empêche le navigateur de deviner un autre type de contenu.", 'ब्राउज़र को घोषित प्रकार से अलग अनुमान लगाने से रोकता है।'],
  'x-frame-options': ['다른 사이트가 이 페이지를 프레임에 넣지 못하게 막습니다.', 'Stops other sites embedding this page in a frame.', 'Impide que otros sitios inserten esta página en un marco.', 'Impede que outros sites coloquem esta página num quadro.', '他のサイトがこのページを枠に入れられないようにします。', 'Verhindert, dass andere Seiten diese Seite einbetten.', "Empêche d'autres sites d'intégrer cette page dans un cadre.", 'दूसरी साइटों को इस पन्ने को फ़्रेम में डालने से रोकता है।'],
  'x-xss-protection': ['옛 브라우저의 XSS 필터를 켜던 헤더입니다. 지금은 CSP가 대신합니다.', 'Switched on an old browser XSS filter; CSP replaces it today.', 'Activaba un antiguo filtro XSS del navegador; hoy lo sustituye CSP.', 'Ligava um antigo filtro XSS do navegador; hoje o CSP o substitui.', '古いブラウザーのXSSフィルターを有効にしていたヘッダーです。今はCSPが代わります。', 'Aktivierte einen alten XSS-Filter; heute übernimmt das CSP.', "Activait un ancien filtre XSS ; le CSP l'a remplacé.", 'पुराने ब्राउज़र का XSS फ़िल्टर चालू करता था; अब CSP उसकी जगह है।'],
  'cross-origin-opener-policy': ['다른 출처가 창을 붙들지 못하게 떼어 놓습니다.', 'Isolates the browsing context so other origins cannot hold a handle to the window.', 'Aísla el contexto para que otros orígenes no retengan la ventana.', 'Isola o contexto para que outras origens não segurem a janela.', '別の出所が窓を握れないよう切り離します。', 'Isoliert den Kontext, damit andere Ursprünge kein Fenster-Handle halten.', "Isole le contexte pour que d'autres origines ne gardent pas la fenêtre.", 'संदर्भ को अलग करता है ताकि अन्य मूल खिड़की पर पकड़ न रखें।'],
  'cross-origin-resource-policy': ['이 자원을 어느 출처가 가져갈 수 있는지 정합니다.', 'Says which origins may fetch this resource at all.', 'Indica qué orígenes pueden siquiera cargar este recurso.', 'Indica quais origens podem sequer buscar este recurso.', 'この資源をどの出所が取得できるかを決めます。', 'Legt fest, welche Ursprünge diese Ressource überhaupt laden dürfen.', "Précise quelles origines peuvent charger cette ressource.", 'तय करता है कि कौन-से मूल यह संसाधन ला सकते हैं।'],
  'cross-origin-embedder-policy': ['출처가 다른 자원을 함부로 끌어오지 못하게 합니다.', 'Requires embedded cross-origin resources to opt in explicitly.', 'Exige que los recursos de otro origen den permiso explícito.', 'Exige que recursos de outra origem deem permissão explícita.', '出所の違う資源を無断で取り込めないようにします。', 'Verlangt, dass eingebettete fremde Ressourcen ausdrücklich zustimmen.', "Exige que les ressources tierces intégrées donnent leur accord.", 'दूसरे मूल के संसाधनों से स्पष्ट अनुमति माँगता है।'],
  'content-range': ['보낸 조각이 전체 어디에 해당하는지 알립니다. 206과 함께 옵니다.', 'States which slice of the whole was sent; it accompanies a 206.', 'Indica qué parte del total se envió; acompaña a un 206.', 'Indica qual parte do total foi enviada; acompanha um 206.', '送った断片が全体のどこに当たるかを伝えます。206と一緒に来ます。', 'Nennt den gesendeten Ausschnitt des Ganzen; begleitet einen 206.', "Indique la portion envoyée du tout ; accompagne un 206.", 'बताता है कि भेजा गया टुकड़ा पूरे में कहाँ का है; 206 के साथ आता है।'],
  'accept-ranges': ['부분 요청을 받는지 알립니다. bytes면 이어받기가 됩니다.', 'Says whether range requests are supported; bytes means resuming works.', 'Indica si admite peticiones por rango; bytes significa que se puede reanudar.', 'Indica se aceita pedidos por intervalo; bytes significa que dá para retomar.', '部分要求を受け付けるかを伝えます。bytesなら再開できます。', 'Gibt an, ob Bereichsanfragen möglich sind; bytes heißt: Fortsetzen geht.', "Indique si les requêtes par plage sont acceptées ; bytes permet la reprise.", 'बताता है कि रेंज अनुरोध चलते हैं या नहीं; bytes का अर्थ है फिर से शुरू करना संभव।'],

  /* ───────── 양쪽 헤더 ───────── */
  'cache-control': ['얼마나 오래, 어디까지 캐시해도 되는지 정합니다. 성능의 절반이 여기서 갈립니다.', 'Sets how long and where the response may be cached — half of web performance lives here.', 'Define cuánto y dónde se puede cachear: aquí se decide media performance.', 'Define quanto e onde se pode cachear: metade do desempenho está aqui.', 'どれだけ長く、どこまでキャッシュしてよいかを決めます。性能の半分はここで決まります。', 'Legt Dauer und Ort des Cachings fest — die halbe Web-Performance hängt daran.', "Définit la durée et le lieu de mise en cache : la moitié de la performance s'y joue.", 'तय करता है कि कितनी देर और कहाँ कैश हो — आधा प्रदर्शन यहीं तय होता है।'],
  connection: ['연결을 이어 쓸지 끊을지 알립니다. HTTP/2부터는 쓰이지 않습니다.', 'Says whether to keep the connection open; HTTP/2 no longer uses it.', 'Indica si mantener la conexión; HTTP/2 ya no lo usa.', 'Indica se mantém a conexão; HTTP/2 já não usa.', '接続を続けるか切るかを伝えます。HTTP/2以降は使いません。', 'Sagt, ob die Verbindung offen bleibt; ab HTTP/2 entfällt er.', "Indique si la connexion reste ouverte ; HTTP/2 ne l'utilise plus.", 'बताता है कि कनेक्शन खुला रहे या नहीं; HTTP/2 में इसका उपयोग नहीं।'],
  'content-encoding': ['본문을 어떤 방식으로 압축했는지 알립니다.', 'Names the compression applied to the body.', 'Indica la compresión aplicada al cuerpo.', 'Indica a compressão aplicada ao corpo.', '本文をどの方式で圧縮したかを伝えます。', 'Nennt die auf den Body angewandte Kompression.', "Indique la compression appliquée au corps.", 'बताता है कि मुख्य भाग पर कौन-सा संपीड़न लगा है।'],
  'content-language': ['본문이 어떤 언어로 쓰였는지 알립니다.', 'States the language the body is written in.', 'Indica el idioma en que está escrito el cuerpo.', 'Indica o idioma em que o corpo está escrito.', '本文がどの言語で書かれているかを伝えます。', 'Nennt die Sprache des Bodys.', "Indique la langue du corps du message.", 'बताता है कि मुख्य भाग किस भाषा में है।'],
  'content-length': ['본문이 몇 바이트인지 알립니다.', 'States the size of the body in bytes.', 'Indica el tamaño del cuerpo en bytes.', 'Indica o tamanho do corpo em bytes.', '本文が何バイトかを伝えます。', 'Nennt die Größe des Bodys in Bytes.', "Indique la taille du corps en octets.", 'बताता है कि मुख्य भाग कितने बाइट का है।'],
  'content-type': ['본문의 형식과 인코딩을 알립니다. 이 값이 틀리면 이미지가 글자로 보입니다.', 'Declares the media type and charset; get it wrong and an image shows up as text.', 'Declara el tipo de contenido y la codificación; si falla, una imagen sale como texto.', 'Declara o tipo de conteúdo e a codificação; se errar, a imagem vira texto.', '本文の形式と文字符号化を伝えます。これが誤ると画像が文字として表示されます。', 'Deklariert Medientyp und Zeichensatz; falsch gesetzt erscheint ein Bild als Text.', "Déclare le type de média et l'encodage ; mal réglé, une image s'affiche en texte.", 'मुख्य भाग का प्रकार और एन्कोडिंग बताता है; ग़लत हो तो चित्र अक्षरों में दिखता है।'],
  date: ['메시지를 만든 시각입니다.', 'The moment the message was generated.', 'El momento en que se generó el mensaje.', 'O momento em que a mensagem foi gerada.', 'メッセージを作った時刻です。', 'Der Zeitpunkt, zu dem die Nachricht entstand.', "L'instant où le message a été produit.", 'संदेश बनने का समय।'],
  pragma: ['옛 캐시 제어 헤더입니다. 지금은 Cache-Control이 대신합니다.', 'An old caching header; Cache-Control replaces it today.', 'Una cabecera de caché antigua; hoy la sustituye Cache-Control.', 'Um cabeçalho de cache antigo; hoje o Cache-Control o substitui.', '古いキャッシュ制御のヘッダーです。今はCache-Controlが代わります。', 'Ein alter Cache-Header; heute übernimmt Cache-Control.', "Un ancien en-tête de cache ; Cache-Control l'a remplacé.", 'पुराना कैश हेडर; अब Cache-Control उसकी जगह है।'],
  trailer: ['본문 뒤에 이어 붙일 헤더 이름을 미리 알립니다.', 'Announces which headers will follow after the body.', 'Anuncia qué cabeceras vendrán después del cuerpo.', 'Anuncia quais cabeçalhos virão depois do corpo.', '本文の後に続くヘッダー名を先に伝えます。', 'Kündigt an, welche Header nach dem Body folgen.', "Annonce les en-têtes qui suivront le corps.", 'बताता है कि मुख्य भाग के बाद कौन-से हेडर आएँगे।'],
  'transfer-encoding': ['본문을 어떤 방식으로 나눠 보내는지 알립니다. chunked면 길이를 미리 몰라도 됩니다.', 'Describes how the body is chunked for transfer; chunked means the length need not be known upfront.', 'Describe cómo se trocea el cuerpo; con chunked no hace falta saber el tamaño de antemano.', 'Descreve como o corpo é fatiado; com chunked não é preciso saber o tamanho antes.', '本文をどう分けて送るかを伝えます。chunkedなら長さを先に知らなくてもよくなります。', 'Beschreibt die Übertragungsaufteilung; chunked erlaubt unbekannte Länge.', "Décrit le découpage du corps ; chunked dispense de connaître la taille à l'avance.", 'बताता है कि मुख्य भाग कैसे टुकड़ों में भेजा जाता है; chunked में लंबाई पहले जानना ज़रूरी नहीं।'],
  upgrade: ['다른 프로토콜로 갈아타자고 제안합니다. 101과 짝을 이룹니다.', 'Proposes switching to another protocol; it pairs with a 101.', 'Propone cambiar de protocolo; forma pareja con un 101.', 'Propõe trocar de protocolo; faz par com um 101.', '別のプロトコルへ切り替えようと提案します。101と対になります。', 'Schlägt einen Protokollwechsel vor; gehört zum 101.', "Propose de changer de protocole ; va de pair avec un 101.", 'दूसरे प्रोटोकॉल पर जाने का प्रस्ताव; 101 के साथ जोड़ा बनाता है।'],
  via: ['거쳐 온 중간 서버들을 기록합니다.', 'Records the proxies the message passed through.', 'Registra los proxies por los que pasó el mensaje.', 'Registra os proxies por onde a mensagem passou.', '経由した中間サーバーを記録します。', 'Verzeichnet die durchlaufenen Proxys.', "Consigne les proxys traversés.", 'बताता है कि संदेश किन प्रॉक्सी से गुज़रा।'],
  warning: ['캐시나 변환에 관한 주의를 적던 헤더입니다. 지금은 쓰지 않습니다.', 'Carried caveats about caching or transformation; it is no longer used.', 'Llevaba avisos sobre caché o transformación; ya no se usa.', 'Trazia avisos sobre cache ou transformação; já não se usa.', 'キャッシュや変換に関する注意を書いていたヘッダーです。現在は使いません。', 'Trug Hinweise zu Caching oder Umwandlung; heute nicht mehr in Gebrauch.', "Portait des avertissements sur le cache ou la transformation ; n'est plus utilisé.", 'कैश या रूपांतरण की चेतावनी रखता था; अब प्रयोग में नहीं।'],
};

/** 열쇠와 언어로 한 줄 설명을 꺼낸다 */
export function httpDesc(slug: string, lang: string): string {
  const row = HTTP_DESC[slug];
  if (!row) return '';
  const i = LANG_ORDER.indexOf(lang as (typeof LANG_ORDER)[number]);
  return row[i >= 0 ? i : 1];
}
