// node에서 직접 로드할 수 있게 확장자를 명시한다 (allowImportingTsExtensions)
import type { AnyLocale10 } from './locales.ts';

/**
 * 기기 점검 화면 문구의 여덟 언어 사전.
 *
 * 측정 로직·이벤트 처리는 한국어 구현을 그대로 쓴다. Hz·ms·좌표는 언어와
 * 무관하므로 프리셋 배열에서는 숫자만 남기고 이름은 여기서 인덱스로 참조한다.
 *
 * 브라우저·OS 이름은 예외다 — 사용자가 "설정에서 본 이름"과 같아야 쓸모가
 * 있으므로 언어별로 그 언어권에서 통하는 표기를 쓴다.
 */
export type DeviceLang = AnyLocale10;

export const DEVICE_COMMON: Record<DeviceLang, {
  reset: string; clearRecord: string; stop: string;
  allowPrompt: string; noDevice: string; cannotOpen: string;
}> = {
  ko: {
    reset: '처음부터 다시', clearRecord: '기록 지우기', stop: '■ 정지',
    allowPrompt: '버튼을 누르면 브라우저가 권한을 물어봅니다.',
    noDevice: '연결된 장치를 찾지 못했습니다.',
    cannotOpen: '장치를 열 수 없습니다. 다른 앱이 쓰고 있는지 확인해 주세요.',
  },
  en: {
    reset: 'Start over', clearRecord: 'Clear the record', stop: '■ Stop',
    allowPrompt: 'Press the button and the browser will ask for permission.',
    noDevice: 'No connected device found.',
    cannotOpen: 'Could not open the device. Check whether another app is using it.',
  },
  es: {
    reset: 'Empezar de cero', clearRecord: 'Borrar el registro', stop: '■ Parar',
    allowPrompt: 'Al pulsar el botón, el navegador pedirá permiso.',
    noDevice: 'No se ha encontrado ningún aparato conectado.',
    cannotOpen: 'No se pudo abrir el aparato. Comprueba si otra aplicación lo está usando.',
  },
  'pt-br': {
    reset: 'Começar do zero', clearRecord: 'Apagar o registro', stop: '■ Parar',
    allowPrompt: 'Ao apertar o botão, o navegador vai pedir permissão.',
    noDevice: 'Nenhum aparelho conectado encontrado.',
    cannotOpen: 'Não foi possível abrir o aparelho. Veja se outro aplicativo está usando.',
  },
  ja: {
    reset: 'はじめからやり直す', clearRecord: '記録を消す', stop: '■ 停止',
    allowPrompt: 'ボタンを押すとブラウザが許可を尋ねます。',
    noDevice: '接続されている機器が見つかりませんでした。',
    cannotOpen: '機器を開けませんでした。ほかのアプリが使っていないか確認してください。',
  },
  de: {
    reset: 'Von vorn beginnen', clearRecord: 'Aufzeichnung löschen', stop: '■ Stopp',
    allowPrompt: 'Wenn du auf die Taste drückst, fragt der Browser nach der Erlaubnis.',
    noDevice: 'Kein angeschlossenes Gerät gefunden.',
    cannotOpen: 'Das Gerät konnte nicht geöffnet werden. Prüfe, ob eine andere App es benutzt.',
  },
  fr: {
    reset: 'Reprendre à zéro', clearRecord: 'Effacer le relevé', stop: '■ Arrêt',
    allowPrompt: 'En appuyant sur le bouton, le navigateur demandera l’autorisation.',
    noDevice: 'Aucun appareil connecté trouvé.',
    cannotOpen: 'Impossible d’ouvrir l’appareil. Vérifie si une autre application l’utilise.',
  },
  hi: {
    reset: 'शुरू से फिर', clearRecord: 'रिकॉर्ड मिटाएँ', stop: '■ रोकें',
    allowPrompt: 'बटन दबाने पर ब्राउज़र अनुमति माँगेगा।',
    noDevice: 'कोई जुड़ा उपकरण नहीं मिला।',
    cannotOpen: 'उपकरण खुल नहीं सका। देखें कि कोई दूसरा ऐप उसे इस्तेमाल नहीं कर रहा।',
  },
  'zh-hans': {
    reset: '重新开始',
    clearRecord: '清除记录',
    stop: '■ 停止',
    allowPrompt: '按下按钮后，浏览器会问你要权限。',
    noDevice: '没找到已连接的设备。',
    cannotOpen: '打不开这个设备。看看是不是别的程序正在用。',
  },
  'zh-hant': {
    reset: '重新開始',
    clearRecord: '清除記錄',
    stop: '■ 停止',
    allowPrompt: '按下按鈕後，瀏覽器會問你要權限。',
    noDevice: '沒找到已連接的裝置。',
    cannotOpen: '打不開這個裝置。看看是不是別的程式正在用。',
  },
};

export const KEYBOARD_UI: Record<DeviceLang, {
  langKey: string; how: string;
  recognised: string; maxSimul: string; nowDown: string; countSuffix: (n: number) => string;
  recentInput: string; noInput: string;
  untested: (n: number) => string; allGood: string;
}> = {
  ko: {
    langKey: '한/영',
    how: '키를 눌러보세요. 파란색은 지금 눌린 키, 연한 파란색은 한 번이라도 인식된 키입니다.',
    recognised: '인식된 키', maxSimul: '동시입력 최대', nowDown: '지금 눌린 키', countSuffix: n => `${n}개`,
    recentInput: '최근 입력', noInput: '아직 입력이 없습니다.',
    untested: n => `아직 안 눌러본 키 ${n}개`, allGood: '🎉 배열의 모든 키가 정상 인식됐습니다.',
  },
  en: {
    langKey: 'Lang',
    how: 'Press any key. Blue means held right now; pale blue means it registered at least once.',
    recognised: 'Keys registered', maxSimul: 'Max simultaneous', nowDown: 'Held now', countSuffix: n => `${n}`,
    recentInput: 'Recent input', noInput: 'Nothing pressed yet.',
    untested: n => `${n} keys not tried yet`, allGood: '🎉 Every key on this layout registered correctly.',
  },
  es: {
    langKey: 'Idioma',
    how: 'Pulsa cualquier tecla. El azul es la que tienes pulsada ahora; el azul claro, la que se registró al menos una vez.',
    recognised: 'Teclas registradas', maxSimul: 'Máximo simultáneo', nowDown: 'Pulsada ahora', countSuffix: n => `${n}`,
    recentInput: 'Última entrada', noInput: 'Todavía no has pulsado nada.',
    untested: n => `${n} teclas sin probar`, allGood: '🎉 Todas las teclas de esta distribución se registraron bien.',
  },
  'pt-br': {
    langKey: 'Idioma',
    how: 'Aperte qualquer tecla. Azul é a que está pressionada agora; azul claro, a que registrou pelo menos uma vez.',
    recognised: 'Teclas registradas', maxSimul: 'Máximo simultâneo', nowDown: 'Pressionada agora', countSuffix: n => `${n}`,
    recentInput: 'Última entrada', noInput: 'Você ainda não apertou nada.',
    untested: n => `${n} teclas não testadas`, allGood: '🎉 Todas as teclas deste layout registraram direito.',
  },
  ja: {
    langKey: '英数',
    how: 'キーを押してみてください。青はいま押しているキー、薄い青は一度でも認識されたキーです。',
    recognised: '認識されたキー', maxSimul: '同時入力の最大', nowDown: 'いま押しているキー', countSuffix: n => `${n}個`,
    recentInput: '直近の入力', noInput: 'まだ入力がありません。',
    untested: n => `まだ押していないキー ${n}個`, allGood: '🎉 この配列のすべてのキーが正しく認識されました。',
  },
  de: {
    langKey: 'Sprache',
    how: 'Drück irgendeine Taste. Blau heißt gerade gehalten, blassblau heißt mindestens einmal erkannt.',
    recognised: 'Erkannte Tasten', maxSimul: 'Max. gleichzeitig', nowDown: 'Jetzt gehalten', countSuffix: n => `${n}`,
    recentInput: 'Letzte Eingabe', noInput: 'Noch nichts gedrückt.',
    untested: n => `${n} Tasten noch nicht probiert`, allGood: '🎉 Jede Taste dieses Layouts wurde korrekt erkannt.',
  },
  fr: {
    langKey: 'Langue',
    how: 'Appuie sur n’importe quelle touche. Bleu = maintenue en ce moment ; bleu pâle = enregistrée au moins une fois.',
    recognised: 'Touches enregistrées', maxSimul: 'Max simultané', nowDown: 'Maintenue', countSuffix: n => `${n}`,
    recentInput: 'Dernière entrée', noInput: 'Rien de pressé pour l’instant.',
    untested: n => `${n} touches non essayées`, allGood: '🎉 Toutes les touches de cette disposition ont bien répondu.',
  },
  hi: {
    langKey: 'भाषा',
    how: 'कोई भी कुंजी दबाइए। नीला वह है जो अभी दबी है; हल्का नीला वह जो कम से कम एक बार दर्ज हुई।',
    recognised: 'दर्ज हुई कुंजियाँ', maxSimul: 'एक साथ अधिकतम', nowDown: 'अभी दबी', countSuffix: n => `${n}`,
    recentInput: 'हाल की इनपुट', noInput: 'अभी तक कुछ नहीं दबाया।',
    untested: n => `${n} कुंजियाँ अभी नहीं आज़माईं`, allGood: '🎉 इस लेआउट की सभी कुंजियाँ ठीक से दर्ज हुईं।',
  },
  'zh-hans': {
    langKey: '切换',
    how: '随便按一个键。蓝色是现在按着的，浅蓝是至少按到过一次的。',
    recognised: '已识别的键',
    maxSimul: '最多同时',
    nowDown: '现在按着',
    countSuffix: n => `${n}个`,
    recentInput: '最近输入',
    noInput: '还没按任何键。',
    untested: n => `还有${n}个键没试过`,
    allGood: '🎉 这个布局上的每个键都正常。',
  },
  'zh-hant': {
    langKey: '切換',
    how: '隨便按一個鍵。藍色是現在按著的，淺藍是至少按到過一次的。',
    recognised: '已識別的鍵',
    maxSimul: '最多同時',
    nowDown: '現在按著',
    countSuffix: n => `${n}個`,
    recentInput: '最近輸入',
    noInput: '還沒按任何鍵。',
    untested: n => `還有${n}個鍵沒試過`,
    allGood: '🎉 這個配置上的每個鍵都正常。',
  },
};

export const MOUSE_UI: Record<DeviceLang, {
  buttons: string[];
  wheelDirs: { up: string; down: string; left: string; right: string };
  pressed: (label: string) => string; buttonN: (n: number) => string; hint: string;
  cursorAt: (x: number, y: number) => string; contextNote: string;
  moveEvents: (rate: number) => string; timesSuffix: (n: number) => string;
  lastGap: (ms: number) => string; noInputYet: string; chatterSuspect: (n: number) => string;
  totalClicks: string; chatterTotal: string; wheelWord: string; scrollWord: string;
  chatterNote: (ms: number, n: number) => string;
}> = {
  ko: {
    buttons: ['왼쪽 클릭', '휠 클릭', '오른쪽 클릭', '뒤로 (사이드)', '앞으로 (사이드)'],
    wheelDirs: { up: '위로', down: '아래로', left: '왼쪽', right: '오른쪽' },
    pressed: label => `${label} 눌림`, buttonN: n => `버튼 ${n}`, hint: '이 영역에서 클릭·스크롤해 보세요',
    cursorAt: (x, y) => `커서 ${x}, ${y}`, contextNote: '오른쪽 클릭 메뉴는 이 영역에서만 잠시 꺼둡니다',
    moveEvents: rate => `이동 이벤트 ${rate}/초`, timesSuffix: n => `${n}회`,
    lastGap: ms => `직전 클릭과 간격 ${ms}ms`, noInputYet: '아직 입력 없음',
    chatterSuspect: n => ` · 채터링 의심 ${n}회`,
    totalClicks: '전체 클릭', chatterTotal: '채터링 의심', wheelWord: '휠', scrollWord: '스크롤',
    chatterNote: (ms, n) => `같은 버튼이 ${ms}ms 안에 다시 눌린 적이 ${n}번 있습니다. 일부러 빠르게 두 번 누른 게 아니라면 스위치 채터링일 수 있어요. 천천히 한 번씩만 눌러 다시 확인해 보세요.`,
  },
  en: {
    buttons: ['Left click', 'Wheel click', 'Right click', 'Back (side)', 'Forward (side)'],
    wheelDirs: { up: 'up', down: 'down', left: 'left', right: 'right' },
    pressed: label => `${label} pressed`, buttonN: n => `Button ${n}`, hint: 'Click and scroll inside this area',
    cursorAt: (x, y) => `Cursor ${x}, ${y}`, contextNote: 'The right-click menu is suppressed inside this area only',
    moveEvents: rate => `${rate} move events/sec`, timesSuffix: n => `${n}×`,
    lastGap: ms => `${ms}ms since the last click`, noInputYet: 'nothing yet',
    chatterSuspect: n => ` · ${n} suspected chatter`,
    totalClicks: 'Total clicks', chatterTotal: 'Suspected chatter', wheelWord: 'Wheel', scrollWord: 'scroll',
    chatterNote: (ms, n) => `The same button registered again within ${ms}ms, ${n} times. Unless you were deliberately double-clicking fast, that could be switch chatter. Try again with slow single clicks to confirm.`,
  },
  es: {
    buttons: ['Clic izquierdo', 'Clic de rueda', 'Clic derecho', 'Atrás (lateral)', 'Adelante (lateral)'],
    wheelDirs: { up: 'arriba', down: 'abajo', left: 'izquierda', right: 'derecha' },
    pressed: label => `${label} pulsado`, buttonN: n => `Botón ${n}`, hint: 'Haz clic y desplázate dentro de esta zona',
    cursorAt: (x, y) => `Cursor ${x}, ${y}`, contextNote: 'El menú del clic derecho se desactiva solo dentro de esta zona',
    moveEvents: rate => `${rate} eventos de movimiento/s`, timesSuffix: n => `${n}×`,
    lastGap: ms => `${ms}ms desde el clic anterior`, noInputYet: 'nada aún',
    chatterSuspect: n => ` · ${n} con sospecha de chatter`,
    totalClicks: 'Clics totales', chatterTotal: 'Sospecha de chatter', wheelWord: 'Rueda', scrollWord: 'desplazamiento',
    chatterNote: (ms, n) => `El mismo botón se registró otra vez en menos de ${ms}ms, ${n} veces. Si no estabas haciendo doble clic a propósito, puede ser chatter del interruptor. Vuelve a probar con clics sueltos y lentos para confirmarlo.`,
  },
  'pt-br': {
    buttons: ['Clique esquerdo', 'Clique da rodinha', 'Clique direito', 'Voltar (lateral)', 'Avançar (lateral)'],
    wheelDirs: { up: 'cima', down: 'baixo', left: 'esquerda', right: 'direita' },
    pressed: label => `${label} pressionado`, buttonN: n => `Botão ${n}`, hint: 'Clique e role dentro desta área',
    cursorAt: (x, y) => `Cursor ${x}, ${y}`, contextNote: 'O menu do clique direito fica desativado só dentro desta área',
    moveEvents: rate => `${rate} eventos de movimento/s`, timesSuffix: n => `${n}×`,
    lastGap: ms => `${ms}ms desde o clique anterior`, noInputYet: 'nada ainda',
    chatterSuspect: n => ` · ${n} com suspeita de chatter`,
    totalClicks: 'Cliques no total', chatterTotal: 'Suspeita de chatter', wheelWord: 'Rodinha', scrollWord: 'rolagem',
    chatterNote: (ms, n) => `O mesmo botão registrou de novo em menos de ${ms}ms, ${n} vezes. Se você não estava clicando duas vezes de propósito, pode ser chatter do switch. Tente de novo com cliques únicos e devagar para confirmar.`,
  },
  ja: {
    buttons: ['左クリック', 'ホイールクリック', '右クリック', '戻る（サイド）', '進む（サイド）'],
    wheelDirs: { up: '上へ', down: '下へ', left: '左', right: '右' },
    pressed: label => `${label} 押下`, buttonN: n => `ボタン ${n}`, hint: 'この範囲でクリック・スクロールしてみてください',
    cursorAt: (x, y) => `カーソル ${x}, ${y}`, contextNote: '右クリックメニューはこの範囲だけ一時的に無効にしています',
    moveEvents: rate => `移動イベント ${rate}/秒`, timesSuffix: n => `${n}回`,
    lastGap: ms => `直前のクリックとの間隔 ${ms}ms`, noInputYet: 'まだ入力なし',
    chatterSuspect: n => ` · チャタリング疑い ${n}回`,
    totalClicks: '全クリック数', chatterTotal: 'チャタリング疑い', wheelWord: 'ホイール', scrollWord: 'スクロール',
    chatterNote: (ms, n) => `同じボタンが${ms}ms以内に再度押された回数が${n}回あります。わざと速く二回押したのでなければ、スイッチのチャタリングかもしれません。ゆっくり一回ずつ押して確かめてみてください。`,
  },
  de: {
    buttons: ['Linksklick', 'Radklick', 'Rechtsklick', 'Zurück (Seite)', 'Vorwärts (Seite)'],
    wheelDirs: { up: 'nach oben', down: 'nach unten', left: 'links', right: 'rechts' },
    pressed: label => `${label} gedrückt`, buttonN: n => `Taste ${n}`, hint: 'Klick und scroll innerhalb dieses Bereichs',
    cursorAt: (x, y) => `Cursor ${x}, ${y}`, contextNote: 'Das Rechtsklick-Menü ist nur in diesem Bereich abgeschaltet',
    moveEvents: rate => `${rate} Bewegungsereignisse/s`, timesSuffix: n => `${n}×`,
    lastGap: ms => `${ms}ms seit dem letzten Klick`, noInputYet: 'noch nichts',
    chatterSuspect: n => ` · ${n} mit Chatter-Verdacht`,
    totalClicks: 'Klicks gesamt', chatterTotal: 'Chatter-Verdacht', wheelWord: 'Rad', scrollWord: 'Scrollen',
    chatterNote: (ms, n) => `Dieselbe Taste hat innerhalb von ${ms}ms erneut ausgelöst, ${n} Mal. Wenn du nicht absichtlich schnell doppelt geklickt hast, kann das Schalter-Chatter sein. Prüf es mit langsamen Einzelklicks nach.`,
  },
  fr: {
    buttons: ['Clic gauche', 'Clic molette', 'Clic droit', 'Retour (latéral)', 'Suivant (latéral)'],
    wheelDirs: { up: 'vers le haut', down: 'vers le bas', left: 'gauche', right: 'droite' },
    pressed: label => `${label} appuyé`, buttonN: n => `Bouton ${n}`, hint: 'Clique et fais défiler dans cette zone',
    cursorAt: (x, y) => `Curseur ${x}, ${y}`, contextNote: 'Le menu du clic droit est désactivé dans cette zone seulement',
    moveEvents: rate => `${rate} événements de déplacement/s`, timesSuffix: n => `${n}×`,
    lastGap: ms => `${ms}ms depuis le clic précédent`, noInputYet: 'rien pour l’instant',
    chatterSuspect: n => ` · ${n} suspectés de chatter`,
    totalClicks: 'Clics au total', chatterTotal: 'Chatter suspecté', wheelWord: 'Molette', scrollWord: 'défilement',
    chatterNote: (ms, n) => `Le même bouton s’est réenregistré en moins de ${ms}ms, ${n} fois. Si tu ne double-cliquais pas exprès, cela peut être du chatter de switch. Refais l’essai avec des clics uniques et lents pour confirmer.`,
  },
  hi: {
    buttons: ['बायाँ क्लिक', 'व्हील क्लिक', 'दायाँ क्लिक', 'पीछे (साइड)', 'आगे (साइड)'],
    wheelDirs: { up: 'ऊपर', down: 'नीचे', left: 'बाएँ', right: 'दाएँ' },
    pressed: label => `${label} दबा`, buttonN: n => `बटन ${n}`, hint: 'इस हिस्से में क्लिक और स्क्रॉल कीजिए',
    cursorAt: (x, y) => `कर्सर ${x}, ${y}`, contextNote: 'दायाँ क्लिक मेनू सिर्फ़ इस हिस्से में बंद रखा गया है',
    moveEvents: rate => `गति घटनाएँ ${rate}/सेकंड`, timesSuffix: n => `${n} बार`,
    lastGap: ms => `पिछले क्लिक से ${ms}ms का अंतर`, noInputYet: 'अभी कुछ नहीं',
    chatterSuspect: n => ` · चैटर के संदेह में ${n} बार`,
    totalClicks: 'कुल क्लिक', chatterTotal: 'चैटर का संदेह', wheelWord: 'व्हील', scrollWord: 'स्क्रॉल',
    chatterNote: (ms, n) => `वही बटन ${ms}ms के भीतर दोबारा दर्ज हुआ, ${n} बार। अगर आपने जानबूझकर तेज़ दो बार नहीं दबाया, तो यह स्विच का चैटर हो सकता है। धीरे-धीरे एक-एक बार दबाकर फिर जाँच लीजिए।`,
  },
  'zh-hans': {
    buttons: ['左键', '滚轮键', '右键', '后退（侧键）', '前进（侧键）'],
    wheelDirs: { up: '上', down: '下', left: '左', right: '右' },
    pressed: label => `按下了${label}`,
    buttonN: n => `按键${n}`,
    hint: '在这块区域里点击和滚动',
    cursorAt: (x, y) => `指针 ${x}, ${y}`,
    contextNote: '只在这块区域里屏蔽了右键菜单',
    moveEvents: rate => `每秒${rate}次移动事件`,
    timesSuffix: n => `${n}次`,
    lastGap: ms => `距上次点击${ms}毫秒`,
    noInputYet: '还没有',
    chatterSuspect: n => ` · 疑似连击${n}次`,
    totalClicks: '总点击数',
    chatterTotal: '疑似连击',
    wheelWord: '滚轮',
    scrollWord: '滚动',
    chatterNote: (ms, n) => `同一个按键在${ms}毫秒内又被记了一次，共${n}次。如果你不是故意快速双击，那可能是微动开关连击。用慢速单击再试一遍来确认。`,
  },
  'zh-hant': {
    buttons: ['左鍵', '滾輪鍵', '右鍵', '上一頁（側鍵）', '下一頁（側鍵）'],
    wheelDirs: { up: '上', down: '下', left: '左', right: '右' },
    pressed: label => `按下了${label}`,
    buttonN: n => `按鍵${n}`,
    hint: '在這塊區域裡點擊和捲動',
    cursorAt: (x, y) => `指標 ${x}, ${y}`,
    contextNote: '只在這塊區域裡遮蔽了右鍵選單',
    moveEvents: rate => `每秒${rate}次移動事件`,
    timesSuffix: n => `${n}次`,
    lastGap: ms => `距上次點擊${ms}毫秒`,
    noInputYet: '還沒有',
    chatterSuspect: n => ` · 疑似連擊${n}次`,
    totalClicks: '總點擊數',
    chatterTotal: '疑似連擊',
    wheelWord: '滾輪',
    scrollWord: '捲動',
    chatterNote: (ms, n) => `同一個按鍵在${ms}毫秒內又被記了一次，共${n}次。如果你不是故意快速雙擊，那可能是微動開關連擊。用慢速單擊再試一遍來確認。`,
  },
};

export const TOUCH_UI: Record<DeviceLang, {
  pressHere: string; multiOk: string;
  nowTouching: string; maxSimul: string; deviceSupports: string;
  detailTitle: string; detailLine: (id: number, type: string, pressure: string, size: string) => string;
  rubNote: string; noTouchNote: string; clearWith: (n: number) => string;
}> = {
  ko: {
    pressHere: '이 영역을 손가락으로 눌러 보세요', multiOk: '여러 손가락을 동시에 올려도 됩니다',
    nowTouching: '지금 닿은 점', maxSimul: '동시 인식 최대', deviceSupports: '기기 지원 점수',
    detailTitle: '터치 상세',
    detailLine: (id, type, pressure, size) => `#${id} · ${type} · 압력 ${pressure} · 크기 ${size}`,
    rubNote: '영역 전체를 손가락으로 꼼꼼히 문질러 보세요. 색이 안 칠해지는 구멍이 있다면 그 자리가 터치를 못 받는 겁니다.',
    noTouchNote: ' (이 기기는 터치를 지원하지 않아 마우스로 표시됩니다.)',
    clearWith: n => `지우고 다시 (총 ${n}번 눌림)`,
  },
  en: {
    pressHere: 'Press this area with a finger', multiOk: 'Several fingers at once is fine',
    nowTouching: 'Touching now', maxSimul: 'Max simultaneous', deviceSupports: 'Device supports',
    detailTitle: 'Touch detail',
    detailLine: (id, type, pressure, size) => `#${id} · ${type} · pressure ${pressure} · size ${size}`,
    rubNote: 'Rub a finger carefully over the whole area. Any gap that does not get coloured in is a spot that is not receiving touch.',
    noTouchNote: ' (This device has no touch support, so the mouse is shown instead.)',
    clearWith: n => `Clear and retry (${n} touches so far)`,
  },
  es: {
    pressHere: 'Pulsa esta zona con un dedo', multiOk: 'Varios dedos a la vez está bien',
    nowTouching: 'Tocando ahora', maxSimul: 'Máximo simultáneo', deviceSupports: 'El aparato admite',
    detailTitle: 'Detalle del toque',
    detailLine: (id, type, pressure, size) => `#${id} · ${type} · presión ${pressure} · tamaño ${size}`,
    rubNote: 'Pasa el dedo con cuidado por toda la zona. Cualquier hueco que no se coloree es un punto que no recibe el toque.',
    noTouchNote: ' (Este aparato no admite toque, así que se muestra el ratón.)',
    clearWith: n => `Borrar y reintentar (${n} toques hasta ahora)`,
  },
  'pt-br': {
    pressHere: 'Toque esta área com o dedo', multiOk: 'Vários dedos ao mesmo tempo pode',
    nowTouching: 'Tocando agora', maxSimul: 'Máximo simultâneo', deviceSupports: 'O aparelho aceita',
    detailTitle: 'Detalhe do toque',
    detailLine: (id, type, pressure, size) => `#${id} · ${type} · pressão ${pressure} · tamanho ${size}`,
    rubNote: 'Passe o dedo com atenção por toda a área. Qualquer falha que não fique colorida é um ponto que não recebe o toque.',
    noTouchNote: ' (Este aparelho não tem suporte a toque, então o mouse é mostrado no lugar.)',
    clearWith: n => `Apagar e tentar de novo (${n} toques até agora)`,
  },
  ja: {
    pressHere: 'この範囲を指で押してみてください', multiOk: '指を何本か同時に置いても大丈夫です',
    nowTouching: 'いま触れている点', maxSimul: '同時認識の最大', deviceSupports: '機器が対応する点数',
    detailTitle: 'タッチの詳細',
    detailLine: (id, type, pressure, size) => `#${id} · ${type} · 圧力 ${pressure} · 大きさ ${size}`,
    rubNote: '範囲全体を指でていねいになぞってみてください。色が付かない穴があれば、その場所がタッチを受け取れていません。',
    noTouchNote: '（この機器はタッチに対応していないため、マウスで表示しています。）',
    clearWith: n => `消してやり直す（これまで${n}回タッチ）`,
  },
  de: {
    pressHere: 'Berühre diesen Bereich mit einem Finger', multiOk: 'Mehrere Finger gleichzeitig sind in Ordnung',
    nowTouching: 'Berührt gerade', maxSimul: 'Max. gleichzeitig', deviceSupports: 'Das Gerät unterstützt',
    detailTitle: 'Berührungsdetails',
    detailLine: (id, type, pressure, size) => `#${id} · ${type} · Druck ${pressure} · Größe ${size}`,
    rubNote: 'Streich mit einem Finger sorgfältig über den ganzen Bereich. Jede Lücke, die nicht eingefärbt wird, ist eine Stelle, die keine Berührung empfängt.',
    noTouchNote: ' (Dieses Gerät hat keine Touch-Unterstützung, deshalb wird die Maus gezeigt.)',
    clearWith: n => `Löschen und neu versuchen (bisher ${n} Berührungen)`,
  },
  fr: {
    pressHere: 'Touche cette zone avec un doigt', multiOk: 'Plusieurs doigts à la fois, pas de problème',
    nowTouching: 'Touché en ce moment', maxSimul: 'Max simultané', deviceSupports: 'L’appareil prend en charge',
    detailTitle: 'Détail du toucher',
    detailLine: (id, type, pressure, size) => `#${id} · ${type} · pression ${pressure} · taille ${size}`,
    rubNote: 'Passe un doigt soigneusement sur toute la zone. Tout trou qui ne se colore pas est un endroit qui ne reçoit pas le toucher.',
    noTouchNote: ' (Cet appareil n’a pas de tactile, la souris est donc affichée à la place.)',
    clearWith: n => `Effacer et réessayer (${n} touchers jusqu’ici)`,
  },
  hi: {
    pressHere: 'इस हिस्से को उँगली से दबाइए', multiOk: 'एक साथ कई उँगलियाँ रखना भी ठीक है',
    nowTouching: 'अभी छू रहे बिंदु', maxSimul: 'एक साथ अधिकतम', deviceSupports: 'उपकरण जितने बिंदु सहेजता है',
    detailTitle: 'स्पर्श का विवरण',
    detailLine: (id, type, pressure, size) => `#${id} · ${type} · दबाव ${pressure} · आकार ${size}`,
    rubNote: 'पूरे हिस्से पर उँगली ध्यान से घुमाइए। जहाँ रंग नहीं भरता, वही जगह स्पर्श नहीं पकड़ रही।',
    noTouchNote: ' (यह उपकरण स्पर्श नहीं सहेजता, इसलिए माउस दिखाया जा रहा है।)',
    clearWith: n => `मिटाकर फिर करें (अब तक ${n} स्पर्श)`,
  },
  'zh-hans': {
    pressHere: '用手指按这块区域',
    multiOk: '好几根手指一起按也没问题',
    nowTouching: '现在触摸',
    maxSimul: '最多同时',
    deviceSupports: '设备支持',
    detailTitle: '触点详情',
    detailLine: (id, type, pressure, size) => `#${id} · ${type} · 压力 ${pressure} · 大小 ${size}`,
    rubNote: '用手指仔细擦过整块区域。没被涂上颜色的地方，就是收不到触摸的位置。',
    noTouchNote: '（这台设备不支持触摸，所以改用鼠标显示。）',
    clearWith: n => `清除重试（已记录${n}个触点）`,
  },
  'zh-hant': {
    pressHere: '用手指按這塊區域',
    multiOk: '好幾根手指一起按也沒問題',
    nowTouching: '現在觸摸',
    maxSimul: '最多同時',
    deviceSupports: '裝置支援',
    detailTitle: '觸點詳情',
    detailLine: (id, type, pressure, size) => `#${id} · ${type} · 壓力 ${pressure} · 大小 ${size}`,
    rubNote: '用手指仔細擦過整塊區域。沒被塗上顏色的地方，就是收不到觸摸的位置。',
    noTouchNote: '（這台裝置不支援觸控，所以改用滑鼠顯示。）',
    clearWith: n => `清除重試（已記錄${n}個觸點）`,
  },
};

export const GAMEPAD_UI: Record<DeviceLang, {
  buttonNames: string[];
  unsupported: string; waiting: string; connectHint: string; connectHintBold: string; needsInput: string;
  padInfo: (i: number, buttons: number, axes: number) => string; standardMapping: string;
  vibrate: string; leftStick: string; rightStick: string;
  driftNote: string; buttonNote: string;
}> = {
  ko: {
    buttonNames: ['L스틱', 'R스틱', '↑', '↓', '←', '→', 'Home'],
    unsupported: '이 브라우저는 게임패드 API를 지원하지 않습니다. 크롬·엣지·파이어폭스에서 열어 주세요.',
    waiting: '컨트롤러를 기다리는 중…',
    connectHint: 'USB로 꽂거나 블루투스로 연결한 뒤, ', connectHintBold: '아무 버튼이나 한 번 눌러 주세요.',
    needsInput: '브라우저는 입력이 한 번 있어야 패드를 인식합니다.',
    padInfo: (i, buttons, axes) => `${i}번 · 버튼 ${buttons}개 · 축 ${axes}개`, standardMapping: ' · 표준 배열',
    vibrate: '진동 테스트', leftStick: '왼쪽 스틱', rightStick: '오른쪽 스틱',
    driftNote: '스틱에서 손을 뗐는데도 값이 0에서 벗어나 있다면 스틱 드리프트입니다. 손을 완전히 뗀 상태에서 위 숫자가 0.00에 가까운지 확인하세요.',
    buttonNote: '모든 버튼을 한 번씩 눌러 보세요. 색이 안 바뀌는 버튼이 인식되지 않는 버튼입니다.',
  },
  en: {
    buttonNames: ['L stick', 'R stick', '↑', '↓', '←', '→', 'Home'],
    unsupported: 'This browser does not support the Gamepad API. Try Chrome, Edge or Firefox.',
    waiting: 'Waiting for a controller…',
    connectHint: 'Plug it in by USB or pair it over Bluetooth, then ', connectHintBold: 'press any button once.',
    needsInput: 'The browser only sees the pad after it receives one input.',
    padInfo: (i, buttons, axes) => `#${i} · ${buttons} buttons · ${axes} axes`, standardMapping: ' · standard mapping',
    vibrate: 'Test vibration', leftStick: 'Left stick', rightStick: 'Right stick',
    driftNote: 'If the values sit away from 0 with your hands off the sticks, that is stick drift. Let go completely and check whether the numbers above stay near 0.00.',
    buttonNote: 'Press every button once. Any button whose colour does not change is not being registered.',
  },
  es: {
    buttonNames: ['Palanca L', 'Palanca R', '↑', '↓', '←', '→', 'Home'],
    unsupported: 'Este navegador no admite la API de mandos. Ábrelo en Chrome, Edge o Firefox.',
    waiting: 'Esperando un mando…',
    connectHint: 'Conéctalo por USB o empareja por Bluetooth y luego ', connectHintBold: 'pulsa cualquier botón una vez.',
    needsInput: 'El navegador solo ve el mando después de recibir una entrada.',
    padInfo: (i, buttons, axes) => `#${i} · ${buttons} botones · ${axes} ejes`, standardMapping: ' · mapeo estándar',
    vibrate: 'Probar la vibración', leftStick: 'Palanca izquierda', rightStick: 'Palanca derecha',
    driftNote: 'Si los valores se alejan de 0 con las manos fuera de las palancas, eso es deriva de palanca. Suelta del todo y comprueba si los números de arriba se quedan cerca de 0,00.',
    buttonNote: 'Pulsa todos los botones una vez. Cualquier botón cuyo color no cambie no se está registrando.',
  },
  'pt-br': {
    buttonNames: ['Analógico L', 'Analógico R', '↑', '↓', '←', '→', 'Home'],
    unsupported: 'Este navegador não tem suporte à API de controles. Abra no Chrome, Edge ou Firefox.',
    waiting: 'Esperando um controle…',
    connectHint: 'Conecte por USB ou emparelhe por Bluetooth, e depois ', connectHintBold: 'aperte qualquer botão uma vez.',
    needsInput: 'O navegador só enxerga o controle depois de receber uma entrada.',
    padInfo: (i, buttons, axes) => `#${i} · ${buttons} botões · ${axes} eixos`, standardMapping: ' · mapeamento padrão',
    vibrate: 'Testar a vibração', leftStick: 'Analógico esquerdo', rightStick: 'Analógico direito',
    driftNote: 'Se os valores ficam longe de 0 com as mãos fora dos analógicos, isso é stick drift. Solte por completo e veja se os números acima ficam perto de 0,00.',
    buttonNote: 'Aperte todos os botões uma vez. Qualquer botão cuja cor não mude não está sendo registrado.',
  },
  ja: {
    buttonNames: ['Lスティック', 'Rスティック', '↑', '↓', '←', '→', 'Home'],
    unsupported: 'このブラウザはゲームパッドAPIに対応していません。Chrome・Edge・Firefoxで開いてください。',
    waiting: 'コントローラーを待っています…',
    connectHint: 'USBでつなぐかBluetoothで接続したあと、', connectHintBold: 'どれかのボタンを一度押してください。',
    needsInput: 'ブラウザは入力が一度ないとパッドを認識しません。',
    padInfo: (i, buttons, axes) => `${i}番 · ボタン${buttons}個 · 軸${axes}個`, standardMapping: ' · 標準配列',
    vibrate: '振動テスト', leftStick: '左スティック', rightStick: '右スティック',
    driftNote: 'スティックから手を離しているのに値が0から離れているなら、スティックドリフトです。完全に手を離した状態で、上の数字が0.00に近いか確認してください。',
    buttonNote: 'すべてのボタンを一度ずつ押してみてください。色が変わらないボタンは認識されていません。',
  },
  de: {
    buttonNames: ['L-Stick', 'R-Stick', '↑', '↓', '←', '→', 'Home'],
    unsupported: 'Dieser Browser unterstützt die Gamepad-API nicht. Öffne die Seite in Chrome, Edge oder Firefox.',
    waiting: 'Warte auf einen Controller…',
    connectHint: 'Schließ ihn per USB an oder koppel ihn über Bluetooth, dann ', connectHintBold: 'drück einmal eine beliebige Taste.',
    needsInput: 'Der Browser erkennt das Pad erst, nachdem er eine Eingabe erhalten hat.',
    padInfo: (i, buttons, axes) => `#${i} · ${buttons} Tasten · ${axes} Achsen`, standardMapping: ' · Standard-Mapping',
    vibrate: 'Vibration testen', leftStick: 'Linker Stick', rightStick: 'Rechter Stick',
    driftNote: 'Weichen die Werte von 0 ab, während du die Sticks nicht anfasst, ist das Stick-Drift. Lass ganz los und prüfe, ob die Zahlen oben nahe 0,00 bleiben.',
    buttonNote: 'Drück jede Taste einmal. Jede Taste, deren Farbe sich nicht ändert, wird nicht erkannt.',
  },
  fr: {
    buttonNames: ['Stick L', 'Stick R', '↑', '↓', '←', '→', 'Home'],
    unsupported: 'Ce navigateur ne prend pas en charge l’API Gamepad. Ouvre la page dans Chrome, Edge ou Firefox.',
    waiting: 'En attente d’une manette…',
    connectHint: 'Branche-la en USB ou appaire-la en Bluetooth, puis ', connectHintBold: 'appuie une fois sur n’importe quel bouton.',
    needsInput: 'Le navigateur ne voit la manette qu’après avoir reçu une entrée.',
    padInfo: (i, buttons, axes) => `#${i} · ${buttons} boutons · ${axes} axes`, standardMapping: ' · mappage standard',
    vibrate: 'Tester la vibration', leftStick: 'Stick gauche', rightStick: 'Stick droit',
    driftNote: 'Si les valeurs restent éloignées de 0 alors que tu ne touches pas les sticks, c’est de la dérive. Lâche complètement et vérifie que les nombres ci-dessus restent proches de 0,00.',
    buttonNote: 'Appuie une fois sur chaque bouton. Tout bouton dont la couleur ne change pas n’est pas enregistré.',
  },
  hi: {
    buttonNames: ['L स्टिक', 'R स्टिक', '↑', '↓', '←', '→', 'Home'],
    unsupported: 'यह ब्राउज़र गेमपैड API नहीं सहेजता। Chrome, Edge या Firefox में खोलें।',
    waiting: 'कंट्रोलर का इंतज़ार…',
    connectHint: 'USB से जोड़ें या ब्लूटूथ से जोड़ें, फिर ', connectHintBold: 'कोई भी बटन एक बार दबाएँ।',
    needsInput: 'एक इनपुट मिलने के बाद ही ब्राउज़र पैड को पहचानता है।',
    padInfo: (i, buttons, axes) => `#${i} · ${buttons} बटन · ${axes} अक्ष`, standardMapping: ' · मानक मैपिंग',
    vibrate: 'कंपन जाँच', leftStick: 'बायाँ स्टिक', rightStick: 'दायाँ स्टिक',
    driftNote: 'स्टिक से हाथ हटा लेने पर भी मान 0 से दूर रहे तो यह स्टिक ड्रिफ़्ट है। पूरी तरह हाथ हटाकर देखें कि ऊपर के अंक 0.00 के पास रहते हैं या नहीं।',
    buttonNote: 'हर बटन एक बार दबाकर देखें। जिस बटन का रंग नहीं बदले, वह दर्ज नहीं हो रहा।',
  },
  'zh-hans': {
    buttonNames: ['左摇杆', '右摇杆', '↑', '↓', '←', '→', 'Home'],
    unsupported: '这个浏览器不支持Gamepad API。试试Chrome、Edge或Firefox。',
    waiting: '等待手柄连接…',
    connectHint: '用USB插上或者用蓝牙配对，然后',
    connectHintBold: '随便按一个键。',
    needsInput: '浏览器要收到一次输入之后才看得见手柄。',
    padInfo: (i, buttons, axes) => `#${i} · ${buttons}个按键 · ${axes}个轴`,
    standardMapping: ' · 标准映射',
    vibrate: '测试震动',
    leftStick: '左摇杆',
    rightStick: '右摇杆',
    driftNote: '手离开摇杆时数值还偏离0，那就是摇杆漂移。完全松手，看看上面的数字是不是稳在0.00附近。',
    buttonNote: '每个键都按一次。颜色没变的那个键就是没被识别到。',
  },
  'zh-hant': {
    buttonNames: ['左搖桿', '右搖桿', '↑', '↓', '←', '→', 'Home'],
    unsupported: '這個瀏覽器不支援Gamepad API。試試Chrome、Edge或Firefox。',
    waiting: '等待手把連接…',
    connectHint: '用USB插上或者用藍牙配對，然後',
    connectHintBold: '隨便按一個鍵。',
    needsInput: '瀏覽器要收到一次輸入之後才看得見手把。',
    padInfo: (i, buttons, axes) => `#${i} · ${buttons}個按鍵 · ${axes}個軸`,
    standardMapping: ' · 標準對應',
    vibrate: '測試震動',
    leftStick: '左搖桿',
    rightStick: '右搖桿',
    driftNote: '手離開搖桿時數值還偏離0，那就是搖桿漂移。完全鬆手，看看上面的數字是不是穩在0.00附近。',
    buttonNote: '每個鍵都按一次。顏色沒變的那個鍵就是沒被識別到。',
  },
};

export const MIC_TEST_UI: Record<DeviceLang, {
  denied: string; notFound: string; cannotOpen: string;
  prompt1: string; prompt2: string; opening: string; startTest: string;
  inputLevel: string; levelPeak: (l: number, p: number) => string;
  saySomething: string; tooQuiet: string; tooLoud: string; working: string;
  deviceLabel: string; deviceN: (n: number) => string;
  recording: string; recordAndListen: string; turnOff: string; resultTitle: string;
}> = {
  ko: {
    denied: '마이크 권한이 거부됐습니다. 주소창의 자물쇠 아이콘에서 마이크를 허용으로 바꿔 주세요.',
    notFound: '연결된 마이크를 찾지 못했습니다. 장치가 꽂혀 있는지 확인해 주세요.',
    cannotOpen: '마이크를 열 수 없습니다. 다른 앱이 마이크를 쓰고 있는지 확인해 주세요.',
    prompt1: '버튼을 누르면 브라우저가 마이크 권한을 물어봅니다.', prompt2: '허용하면 바로 입력 레벨이 보입니다.',
    opening: '마이크 여는 중…', startTest: '마이크 테스트 시작',
    inputLevel: '입력 레벨', levelPeak: (l, p) => `${l}% · 최고 ${p}%`,
    saySomething: '말을 해보세요…',
    tooQuiet: '소리가 거의 안 잡힙니다 — 음소거나 입력 볼륨을 확인하세요',
    tooLoud: '너무 큽니다 — 소리가 깨질 수 있어요',
    working: '✅ 마이크가 정상 동작합니다',
    deviceLabel: '마이크 장치', deviceN: n => `마이크 ${n}`,
    recording: '● 녹음 중… (6초)', recordAndListen: '6초 녹음해서 들어보기', turnOff: '마이크 끄기',
    resultTitle: '녹음 결과 — 재생해서 확인하세요',
  },
  en: {
    denied: 'Microphone access was denied. Allow the microphone from the lock icon in the address bar.',
    notFound: 'No microphone found. Check that the device is plugged in.',
    cannotOpen: 'Could not open the microphone. Check whether another app is using it.',
    prompt1: 'Press the button and the browser will ask for microphone permission.', prompt2: 'Allow it and the input level appears straight away.',
    opening: 'Opening the microphone…', startTest: 'Start the microphone test',
    inputLevel: 'Input level', levelPeak: (l, p) => `${l}% · peak ${p}%`,
    saySomething: 'Say something…',
    tooQuiet: 'Barely picking anything up — check the mute switch and input volume',
    tooLoud: 'Too loud — this will clip',
    working: '✅ The microphone is working',
    deviceLabel: 'Microphone', deviceN: n => `Microphone ${n}`,
    recording: '● Recording… (6s)', recordAndListen: 'Record 6 seconds and listen back', turnOff: 'Turn the mic off',
    resultTitle: 'Your recording — play it back to check',
  },
  es: {
    denied: 'Se denegó el acceso al micrófono. Permite el micrófono desde el icono del candado en la barra de direcciones.',
    notFound: 'No se ha encontrado ningún micrófono. Comprueba que el aparato esté conectado.',
    cannotOpen: 'No se pudo abrir el micrófono. Comprueba si otra aplicación lo está usando.',
    prompt1: 'Al pulsar el botón, el navegador pedirá permiso para el micrófono.', prompt2: 'Si lo permites, el nivel de entrada aparece al momento.',
    opening: 'Abriendo el micrófono…', startTest: 'Empezar el test de micrófono',
    inputLevel: 'Nivel de entrada', levelPeak: (l, p) => `${l}% · máximo ${p}%`,
    saySomething: 'Di algo…',
    tooQuiet: 'Casi no capta nada — comprueba el silencio y el volumen de entrada',
    tooLoud: 'Demasiado alto — el sonido va a saturar',
    working: '✅ El micrófono funciona bien',
    deviceLabel: 'Micrófono', deviceN: n => `Micrófono ${n}`,
    recording: '● Grabando… (6s)', recordAndListen: 'Grabar 6 segundos y escucharlo', turnOff: 'Apagar el micrófono',
    resultTitle: 'Tu grabación — reprodúcela para comprobarla',
  },
  'pt-br': {
    denied: 'O acesso ao microfone foi negado. Libere o microfone pelo ícone do cadeado na barra de endereços.',
    notFound: 'Nenhum microfone encontrado. Confira se o aparelho está conectado.',
    cannotOpen: 'Não foi possível abrir o microfone. Veja se outro aplicativo está usando.',
    prompt1: 'Ao apertar o botão, o navegador vai pedir permissão para o microfone.', prompt2: 'Se você liberar, o nível de entrada aparece na hora.',
    opening: 'Abrindo o microfone…', startTest: 'Começar o teste de microfone',
    inputLevel: 'Nível de entrada', levelPeak: (l, p) => `${l}% · pico ${p}%`,
    saySomething: 'Fale alguma coisa…',
    tooQuiet: 'Quase não capta nada — confira o mudo e o volume de entrada',
    tooLoud: 'Alto demais — o som vai distorcer',
    working: '✅ O microfone está funcionando',
    deviceLabel: 'Microfone', deviceN: n => `Microfone ${n}`,
    recording: '● Gravando… (6s)', recordAndListen: 'Gravar 6 segundos e ouvir', turnOff: 'Desligar o microfone',
    resultTitle: 'Sua gravação — toque para conferir',
  },
  ja: {
    denied: 'マイクの使用が拒否されました。アドレスバーの鍵アイコンからマイクを許可に変えてください。',
    notFound: '接続されているマイクが見つかりませんでした。機器が挿さっているか確認してください。',
    cannotOpen: 'マイクを開けませんでした。ほかのアプリがマイクを使っていないか確認してください。',
    prompt1: 'ボタンを押すとブラウザがマイクの許可を尋ねます。', prompt2: '許可すればすぐに入力レベルが見えます。',
    opening: 'マイクを開いています…', startTest: 'マイクテストを始める',
    inputLevel: '入力レベル', levelPeak: (l, p) => `${l}% · 最大 ${p}%`,
    saySomething: '何か話してみてください…',
    tooQuiet: 'ほとんど音を拾えていません — ミュートと入力音量を確認してください',
    tooLoud: '大きすぎます — 音が割れる可能性があります',
    working: '✅ マイクは正常に動いています',
    deviceLabel: 'マイクの機器', deviceN: n => `マイク ${n}`,
    recording: '● 録音中…（6秒）', recordAndListen: '6秒録音して聴いてみる', turnOff: 'マイクを切る',
    resultTitle: '録音結果 — 再生して確認してください',
  },
  de: {
    denied: 'Der Zugriff aufs Mikrofon wurde verweigert. Erlaube das Mikrofon über das Schloss-Symbol in der Adressleiste.',
    notFound: 'Kein Mikrofon gefunden. Prüfe, ob das Gerät angeschlossen ist.',
    cannotOpen: 'Das Mikrofon konnte nicht geöffnet werden. Prüfe, ob eine andere App es benutzt.',
    prompt1: 'Wenn du auf die Taste drückst, fragt der Browser nach der Mikrofonerlaubnis.', prompt2: 'Erlaubst du es, erscheint der Eingangspegel sofort.',
    opening: 'Mikrofon wird geöffnet…', startTest: 'Mikrofontest starten',
    inputLevel: 'Eingangspegel', levelPeak: (l, p) => `${l}% · Spitze ${p}%`,
    saySomething: 'Sag etwas…',
    tooQuiet: 'Es kommt kaum etwas an — prüfe Stummschaltung und Eingangslautstärke',
    tooLoud: 'Zu laut — das übersteuert',
    working: '✅ Das Mikrofon funktioniert',
    deviceLabel: 'Mikrofon', deviceN: n => `Mikrofon ${n}`,
    recording: '● Aufnahme läuft… (6s)', recordAndListen: '6 Sekunden aufnehmen und abhören', turnOff: 'Mikrofon ausschalten',
    resultTitle: 'Deine Aufnahme — spiel sie zur Prüfung ab',
  },
  fr: {
    denied: 'L’accès au micro a été refusé. Autorise le micro depuis l’icône de cadenas dans la barre d’adresse.',
    notFound: 'Aucun micro trouvé. Vérifie que l’appareil est branché.',
    cannotOpen: 'Impossible d’ouvrir le micro. Vérifie si une autre application l’utilise.',
    prompt1: 'En appuyant sur le bouton, le navigateur demandera l’autorisation du micro.', prompt2: 'Si tu l’autorises, le niveau d’entrée apparaît aussitôt.',
    opening: 'Ouverture du micro…', startTest: 'Lancer le test de micro',
    inputLevel: 'Niveau d’entrée', levelPeak: (l, p) => `${l}% · crête ${p}%`,
    saySomething: 'Dis quelque chose…',
    tooQuiet: 'Il ne capte presque rien — vérifie la coupure du son et le volume d’entrée',
    tooLoud: 'Trop fort — ça va saturer',
    working: '✅ Le micro fonctionne',
    deviceLabel: 'Micro', deviceN: n => `Micro ${n}`,
    recording: '● Enregistrement… (6s)', recordAndListen: 'Enregistrer 6 secondes et réécouter', turnOff: 'Éteindre le micro',
    resultTitle: 'Ton enregistrement — écoute-le pour vérifier',
  },
  hi: {
    denied: 'माइक की अनुमति नहीं मिली। पता-पट्टी के ताले के चिह्न से माइक को अनुमति दें।',
    notFound: 'कोई जुड़ा माइक नहीं मिला। देखें कि उपकरण लगा हुआ है।',
    cannotOpen: 'माइक खुल नहीं सका। देखें कि कोई दूसरा ऐप माइक इस्तेमाल नहीं कर रहा।',
    prompt1: 'बटन दबाने पर ब्राउज़र माइक की अनुमति माँगेगा।', prompt2: 'अनुमति देते ही इनपुट स्तर दिखने लगेगा।',
    opening: 'माइक खोला जा रहा है…', startTest: 'माइक्रोफ़ोन जाँच शुरू करें',
    inputLevel: 'इनपुट स्तर', levelPeak: (l, p) => `${l}% · सर्वोच्च ${p}%`,
    saySomething: 'कुछ बोलिए…',
    tooQuiet: 'आवाज़ लगभग पकड़ में नहीं आ रही — म्यूट और इनपुट आवाज़ जाँचें',
    tooLoud: 'बहुत तेज़ है — आवाज़ फट सकती है',
    working: '✅ माइक ठीक काम कर रहा है',
    deviceLabel: 'माइक उपकरण', deviceN: n => `माइक ${n}`,
    recording: '● रिकॉर्डिंग… (6 सेकंड)', recordAndListen: '6 सेकंड रिकॉर्ड कर सुनें', turnOff: 'माइक बंद करें',
    resultTitle: 'आपकी रिकॉर्डिंग — बजाकर जाँच लें',
  },
  'zh-hans': {
    denied: '麦克风权限被拒了。从地址栏的锁图标里允许麦克风。',
    notFound: '没找到麦克风。确认设备已经插上。',
    cannotOpen: '打不开麦克风。看看是不是别的程序正在用。',
    prompt1: '按下按钮后，浏览器会问你要麦克风权限。',
    prompt2: '允许之后，音量条马上就出来。',
    opening: '正在打开麦克风…',
    startTest: '开始麦克风测试',
    inputLevel: '输入音量',
    levelPeak: (l, p) => `${l}% · 峰值 ${p}%`,
    saySomething: '说点什么…',
    tooQuiet: '几乎收不到声音 — 看看静音开关和输入音量',
    tooLoud: '太大声了 — 这样会破音',
    working: '✅ 麦克风正常',
    deviceLabel: '麦克风',
    deviceN: n => `麦克风${n}`,
    recording: '● 录音中…（6秒）',
    recordAndListen: '录6秒再放来听',
    turnOff: '关掉麦克风',
    resultTitle: '你的录音 — 放出来听听看',
  },
  'zh-hant': {
    denied: '麥克風權限被拒了。從網址列的鎖圖示裡允許麥克風。',
    notFound: '沒找到麥克風。確認裝置已經插上。',
    cannotOpen: '打不開麥克風。看看是不是別的程式正在用。',
    prompt1: '按下按鈕後，瀏覽器會問你要麥克風權限。',
    prompt2: '允許之後，音量條馬上就出來。',
    opening: '正在打開麥克風…',
    startTest: '開始麥克風測試',
    inputLevel: '輸入音量',
    levelPeak: (l, p) => `${l}% · 峰值 ${p}%`,
    saySomething: '說點什麼…',
    tooQuiet: '幾乎收不到聲音 — 看看靜音開關和輸入音量',
    tooLoud: '太大聲了 — 這樣會破音',
    working: '✅ 麥克風正常',
    deviceLabel: '麥克風',
    deviceN: n => `麥克風${n}`,
    recording: '● 錄音中…（6秒）',
    recordAndListen: '錄6秒再放來聽',
    turnOff: '關掉麥克風',
    resultTitle: '你的錄音 — 放出來聽聽看',
  },
};

export const WEBCAM_UI: Record<DeviceLang, {
  cameraWord: string; denied: string; notFound: string; cannotOpen: string;
  prompt: string; opening: string; startTest: string;
  resolution: string; measuredFps: string; setFps: string;
  deviceLabel: string; deviceN: (n: number) => string;
  snapshot: string; mirrorOn: string; mirrorOff: string; turnOff: string;
  snapshotTitle: string; saveImage: string; snapshotAlt: string;
}> = {
  ko: {
    cameraWord: '카메라',
    denied: '카메라 권한이 거부됐습니다. 주소창의 자물쇠 아이콘에서 카메라를 허용으로 바꿔 주세요.',
    notFound: '연결된 카메라를 찾지 못했습니다.',
    cannotOpen: '카메라를 열 수 없습니다. 화상회의 앱 등 다른 프로그램이 쓰고 있는지 확인해 주세요.',
    prompt: '버튼을 누르면 브라우저가 카메라 권한을 물어봅니다.',
    opening: '카메라 여는 중…', startTest: '웹캠 테스트 시작',
    resolution: '해상도', measuredFps: '실측 fps', setFps: '설정 fps',
    deviceLabel: '카메라 장치', deviceN: n => `카메라 ${n}`,
    snapshot: '📸 스냅샷', mirrorOn: '거울모드 끄기', mirrorOff: '거울모드 켜기', turnOff: '카메라 끄기',
    snapshotTitle: '스냅샷', saveImage: '이미지 저장', snapshotAlt: '웹캠 스냅샷',
  },
  en: {
    cameraWord: 'Camera',
    denied: 'Camera access was denied. Allow the camera from the lock icon in the address bar.',
    notFound: 'No camera found.',
    cannotOpen: 'Could not open the camera. Check whether a video call app or another program is using it.',
    prompt: 'Press the button and the browser will ask for camera permission.',
    opening: 'Opening the camera…', startTest: 'Start the webcam test',
    resolution: 'Resolution', measuredFps: 'Measured fps', setFps: 'Reported fps',
    deviceLabel: 'Camera', deviceN: n => `Camera ${n}`,
    snapshot: '📸 Snapshot', mirrorOn: 'Turn mirror off', mirrorOff: 'Turn mirror on', turnOff: 'Turn the camera off',
    snapshotTitle: 'Snapshot', saveImage: 'Save the image', snapshotAlt: 'Webcam snapshot',
  },
  es: {
    cameraWord: 'Cámara',
    denied: 'Se denegó el acceso a la cámara. Permite la cámara desde el icono del candado en la barra de direcciones.',
    notFound: 'No se ha encontrado ninguna cámara.',
    cannotOpen: 'No se pudo abrir la cámara. Comprueba si una aplicación de videollamada u otro programa la está usando.',
    prompt: 'Al pulsar el botón, el navegador pedirá permiso para la cámara.',
    opening: 'Abriendo la cámara…', startTest: 'Empezar el test de webcam',
    resolution: 'Resolución', measuredFps: 'fps medidos', setFps: 'fps declarados',
    deviceLabel: 'Cámara', deviceN: n => `Cámara ${n}`,
    snapshot: '📸 Captura', mirrorOn: 'Desactivar el espejo', mirrorOff: 'Activar el espejo', turnOff: 'Apagar la cámara',
    snapshotTitle: 'Captura', saveImage: 'Guardar la imagen', snapshotAlt: 'Captura de la webcam',
  },
  'pt-br': {
    cameraWord: 'Câmera',
    denied: 'O acesso à câmera foi negado. Libere a câmera pelo ícone do cadeado na barra de endereços.',
    notFound: 'Nenhuma câmera encontrada.',
    cannotOpen: 'Não foi possível abrir a câmera. Veja se um aplicativo de chamada de vídeo ou outro programa está usando.',
    prompt: 'Ao apertar o botão, o navegador vai pedir permissão para a câmera.',
    opening: 'Abrindo a câmera…', startTest: 'Começar o teste de webcam',
    resolution: 'Resolução', measuredFps: 'fps medidos', setFps: 'fps declarados',
    deviceLabel: 'Câmera', deviceN: n => `Câmera ${n}`,
    snapshot: '📸 Captura', mirrorOn: 'Desligar o espelho', mirrorOff: 'Ligar o espelho', turnOff: 'Desligar a câmera',
    snapshotTitle: 'Captura', saveImage: 'Salvar a imagem', snapshotAlt: 'Captura da webcam',
  },
  ja: {
    cameraWord: 'カメラ',
    denied: 'カメラの使用が拒否されました。アドレスバーの鍵アイコンからカメラを許可に変えてください。',
    notFound: '接続されているカメラが見つかりませんでした。',
    cannotOpen: 'カメラを開けませんでした。ビデオ会議アプリなど、ほかのプログラムが使っていないか確認してください。',
    prompt: 'ボタンを押すとブラウザがカメラの許可を尋ねます。',
    opening: 'カメラを開いています…', startTest: 'ウェブカメラテストを始める',
    resolution: '解像度', measuredFps: '実測fps', setFps: '申告fps',
    deviceLabel: 'カメラの機器', deviceN: n => `カメラ ${n}`,
    snapshot: '📸 スナップショット', mirrorOn: '鏡モードを切る', mirrorOff: '鏡モードを入れる', turnOff: 'カメラを切る',
    snapshotTitle: 'スナップショット', saveImage: '画像を保存', snapshotAlt: 'ウェブカメラのスナップショット',
  },
  de: {
    cameraWord: 'Kamera',
    denied: 'Der Zugriff auf die Kamera wurde verweigert. Erlaube die Kamera über das Schloss-Symbol in der Adressleiste.',
    notFound: 'Keine Kamera gefunden.',
    cannotOpen: 'Die Kamera konnte nicht geöffnet werden. Prüfe, ob eine Videokonferenz-App oder ein anderes Programm sie benutzt.',
    prompt: 'Wenn du auf die Taste drückst, fragt der Browser nach der Kameraerlaubnis.',
    opening: 'Kamera wird geöffnet…', startTest: 'Webcam-Test starten',
    resolution: 'Auflösung', measuredFps: 'Gemessene fps', setFps: 'Angegebene fps',
    deviceLabel: 'Kamera', deviceN: n => `Kamera ${n}`,
    snapshot: '📸 Schnappschuss', mirrorOn: 'Spiegel ausschalten', mirrorOff: 'Spiegel einschalten', turnOff: 'Kamera ausschalten',
    snapshotTitle: 'Schnappschuss', saveImage: 'Bild speichern', snapshotAlt: 'Webcam-Schnappschuss',
  },
  fr: {
    cameraWord: 'Caméra',
    denied: 'L’accès à la caméra a été refusé. Autorise la caméra depuis l’icône de cadenas dans la barre d’adresse.',
    notFound: 'Aucune caméra trouvée.',
    cannotOpen: 'Impossible d’ouvrir la caméra. Vérifie si une appli de visio ou un autre programme l’utilise.',
    prompt: 'En appuyant sur le bouton, le navigateur demandera l’autorisation de la caméra.',
    opening: 'Ouverture de la caméra…', startTest: 'Lancer le test de webcam',
    resolution: 'Résolution', measuredFps: 'ips mesurées', setFps: 'ips annoncées',
    deviceLabel: 'Caméra', deviceN: n => `Caméra ${n}`,
    snapshot: '📸 Capture', mirrorOn: 'Désactiver le miroir', mirrorOff: 'Activer le miroir', turnOff: 'Éteindre la caméra',
    snapshotTitle: 'Capture', saveImage: 'Enregistrer l’image', snapshotAlt: 'Capture de la webcam',
  },
  hi: {
    cameraWord: 'कैमरा',
    denied: 'कैमरे की अनुमति नहीं मिली। पता-पट्टी के ताले के चिह्न से कैमरे को अनुमति दें।',
    notFound: 'कोई जुड़ा कैमरा नहीं मिला।',
    cannotOpen: 'कैमरा खुल नहीं सका। देखें कि वीडियो कॉल का ऐप या कोई और प्रोग्राम उसे इस्तेमाल नहीं कर रहा।',
    prompt: 'बटन दबाने पर ब्राउज़र कैमरे की अनुमति माँगेगा।',
    opening: 'कैमरा खोला जा रहा है…', startTest: 'वेबकैम जाँच शुरू करें',
    resolution: 'रिज़ॉल्यूशन', measuredFps: 'मापे गए fps', setFps: 'बताए गए fps',
    deviceLabel: 'कैमरा उपकरण', deviceN: n => `कैमरा ${n}`,
    snapshot: '📸 स्नैपशॉट', mirrorOn: 'मिरर मोड बंद करें', mirrorOff: 'मिरर मोड चालू करें', turnOff: 'कैमरा बंद करें',
    snapshotTitle: 'स्नैपशॉट', saveImage: 'तस्वीर सेव करें', snapshotAlt: 'वेबकैम स्नैपशॉट',
  },
  'zh-hans': {
    cameraWord: '相机',
    denied: '相机权限被拒了。从地址栏的锁图标里允许相机。',
    notFound: '没找到相机。',
    cannotOpen: '打不开相机。看看是不是视频通话软件或别的程序正在用。',
    prompt: '按下按钮后，浏览器会问你要相机权限。',
    opening: '正在打开相机…',
    startTest: '开始摄像头测试',
    resolution: '分辨率',
    measuredFps: '实测帧率',
    setFps: '标称帧率',
    deviceLabel: '相机',
    deviceN: n => `相机${n}`,
    snapshot: '📸 拍一张',
    mirrorOn: '关掉镜像',
    mirrorOff: '打开镜像',
    turnOff: '关掉相机',
    snapshotTitle: '快照',
    saveImage: '保存图片',
    snapshotAlt: '摄像头快照',
  },
  'zh-hant': {
    cameraWord: '相機',
    denied: '相機權限被拒了。從網址列的鎖圖示裡允許相機。',
    notFound: '沒找到相機。',
    cannotOpen: '打不開相機。看看是不是視訊通話軟體或別的程式正在用。',
    prompt: '按下按鈕後，瀏覽器會問你要相機權限。',
    opening: '正在打開相機…',
    startTest: '開始網路攝影機測試',
    resolution: '解析度',
    measuredFps: '實測影格率',
    setFps: '標稱影格率',
    deviceLabel: '相機',
    deviceN: n => `相機${n}`,
    snapshot: '📸 拍一張',
    mirrorOn: '關掉鏡像',
    mirrorOff: '打開鏡像',
    turnOff: '關掉相機',
    snapshotTitle: '快照',
    saveImage: '儲存圖片',
    snapshotAlt: '網路攝影機快照',
  },
};

export const SPEAKER_UI: Record<DeviceLang, {
  bandDescs: string[];
  leftSide: string; rightSide: string;
  playingNote: string; idleNote: string;
  modes: string[]; freq: string; volume: string; hearingWarn: string;
  checkTitle: string; checkItems: string[]; allGood: string;
}> = {
  ko: {
    bandDescs: ['저음 (진동)', '중저음', '기준음', '고음', '초고음', '들리면 좋은 귀'],
    leftSide: 'LEFT · 왼쪽', rightSide: 'RIGHT · 오른쪽',
    playingNote: '소리가 나는 쪽과 화면에 켜진 쪽이 같은지 확인하세요. 반대라면 좌우가 바뀐 겁니다.',
    idleNote: '아래 버튼으로 한쪽씩 울려 보세요. 볼륨은 30%에서 시작합니다.',
    modes: ['왼쪽만', '오른쪽만', '양쪽 함께', '좌 ↔ 우 반복'],
    freq: '주파수', volume: '볼륨',
    hearingWarn: '고주파를 큰 볼륨으로 오래 듣지 마세요. 청력에 좋지 않습니다.',
    checkTitle: '직접 확인하고 체크하세요',
    checkItems: [
      '왼쪽만 눌렀을 때 왼쪽에서만 소리가 난다',
      '오른쪽만 눌렀을 때 오른쪽에서만 소리가 난다',
      '양쪽 소리 크기가 비슷하다',
      '지직거리거나 끊기는 잡음이 없다',
    ],
    allGood: '✅ 스피커·이어폰이 정상입니다.',
  },
  en: {
    bandDescs: ['Bass (you feel it)', 'Low mid', 'Reference tone', 'Treble', 'High treble', 'Good ears if you hear it'],
    leftSide: 'LEFT', rightSide: 'RIGHT',
    playingNote: 'Check that the side you hear matches the side lit up on screen. If they are opposite, your channels are swapped.',
    idleNote: 'Use the buttons below to sound one side at a time. Volume starts at 30%.',
    modes: ['Left only', 'Right only', 'Both together', 'Left ↔ right'],
    freq: 'Frequency', volume: 'Volume',
    hearingWarn: 'Do not listen to high frequencies loudly for long. It is not good for your hearing.',
    checkTitle: 'Check these yourself and tick them off',
    checkItems: [
      'With left only, sound comes from the left only',
      'With right only, sound comes from the right only',
      'Both sides are about the same loudness',
      'No crackling or cutting out',
    ],
    allGood: '✅ Your speakers or headphones are fine.',
  },
  es: {
    bandDescs: ['Graves (se notan)', 'Medios-graves', 'Tono de referencia', 'Agudos', 'Agudos altos', 'Buen oído si lo oyes'],
    leftSide: 'IZQUIERDA', rightSide: 'DERECHA',
    playingNote: 'Comprueba que el lado que oyes coincide con el lado iluminado en pantalla. Si están al contrario, tienes los canales invertidos.',
    idleNote: 'Usa los botones de abajo para sonar un lado a la vez. El volumen empieza al 30%.',
    modes: ['Solo izquierda', 'Solo derecha', 'Ambos juntos', 'Izquierda ↔ derecha'],
    freq: 'Frecuencia', volume: 'Volumen',
    hearingWarn: 'No escuches frecuencias altas a mucho volumen durante mucho tiempo. No le hace bien a tu oído.',
    checkTitle: 'Compruébalo tú y ve marcando',
    checkItems: [
      'Con solo la izquierda, el sonido viene solo de la izquierda',
      'Con solo la derecha, el sonido viene solo de la derecha',
      'Los dos lados suenan más o menos igual de fuerte',
      'No hay chasquidos ni cortes',
    ],
    allGood: '✅ Tus altavoces o auriculares están bien.',
  },
  'pt-br': {
    bandDescs: ['Graves (você sente)', 'Médios-graves', 'Tom de referência', 'Agudos', 'Agudos altos', 'Bom ouvido se você escuta'],
    leftSide: 'ESQUERDA', rightSide: 'DIREITA',
    playingNote: 'Confira se o lado que você ouve é o mesmo que aparece aceso na tela. Se estiverem trocados, seus canais estão invertidos.',
    idleNote: 'Use os botões abaixo para tocar um lado por vez. O volume começa em 30%.',
    modes: ['Só esquerda', 'Só direita', 'Os dois juntos', 'Esquerda ↔ direita'],
    freq: 'Frequência', volume: 'Volume',
    hearingWarn: 'Não escute frequências altas em volume alto por muito tempo. Isso não faz bem à audição.',
    checkTitle: 'Confira você mesmo e vá marcando',
    checkItems: [
      'Com só a esquerda, o som vem só da esquerda',
      'Com só a direita, o som vem só da direita',
      'Os dois lados têm mais ou menos o mesmo volume',
      'Não há estalos nem cortes',
    ],
    allGood: '✅ Suas caixas ou fones estão bem.',
  },
  ja: {
    bandDescs: ['低音（振動で感じる）', '中低音', '基準音', '高音', '超高音', '聞こえたら良い耳'],
    leftSide: 'LEFT · 左', rightSide: 'RIGHT · 右',
    playingNote: '音が出ている側と画面で光っている側が同じか確認してください。逆なら左右が入れ替わっています。',
    idleNote: '下のボタンで片側ずつ鳴らしてみてください。音量は30%から始まります。',
    modes: ['左だけ', '右だけ', '両方いっしょに', '左 ↔ 右をくり返す'],
    freq: '周波数', volume: '音量',
    hearingWarn: '高い周波数を大きな音量で長く聴かないでください。聴力によくありません。',
    checkTitle: '自分で確かめてチェックしてください',
    checkItems: [
      '左だけを押したとき、左からだけ音が出る',
      '右だけを押したとき、右からだけ音が出る',
      '両側の音の大きさがだいたい同じ',
      'ジリジリしたり途切れたりする雑音がない',
    ],
    allGood: '✅ スピーカー・イヤホンは正常です。',
  },
  de: {
    bandDescs: ['Bass (spürbar)', 'Untere Mitten', 'Referenzton', 'Höhen', 'Obere Höhen', 'Gute Ohren, wenn du das hörst'],
    leftSide: 'LINKS', rightSide: 'RECHTS',
    playingNote: 'Prüfe, ob die Seite, die du hörst, zur auf dem Bildschirm leuchtenden passt. Sind sie vertauscht, sind deine Kanäle verdreht.',
    idleNote: 'Nimm die Tasten unten, um jeweils eine Seite klingen zu lassen. Die Lautstärke startet bei 30%.',
    modes: ['Nur links', 'Nur rechts', 'Beide zusammen', 'Links ↔ rechts'],
    freq: 'Frequenz', volume: 'Lautstärke',
    hearingWarn: 'Hör hohe Frequenzen nicht lange bei großer Lautstärke. Das tut dem Gehör nicht gut.',
    checkTitle: 'Prüf das selbst und hak es ab',
    checkItems: [
      'Bei „nur links“ kommt der Ton nur von links',
      'Bei „nur rechts“ kommt der Ton nur von rechts',
      'Beide Seiten sind etwa gleich laut',
      'Kein Knistern und keine Aussetzer',
    ],
    allGood: '✅ Deine Lautsprecher oder Kopfhörer sind in Ordnung.',
  },
  fr: {
    bandDescs: ['Graves (on les sent)', 'Bas-médium', 'Ton de référence', 'Aigus', 'Aigus élevés', 'Bonne oreille si tu l’entends'],
    leftSide: 'GAUCHE', rightSide: 'DROITE',
    playingNote: 'Vérifie que le côté que tu entends correspond au côté allumé à l’écran. S’ils sont inversés, tes canaux sont permutés.',
    idleNote: 'Sers-toi des boutons ci-dessous pour faire sonner un côté à la fois. Le volume démarre à 30%.',
    modes: ['Gauche seulement', 'Droite seulement', 'Les deux ensemble', 'Gauche ↔ droite'],
    freq: 'Fréquence', volume: 'Volume',
    hearingWarn: 'N’écoute pas les fréquences aiguës à fort volume longtemps. Ce n’est pas bon pour l’audition.',
    checkTitle: 'Vérifie par toi-même et coche',
    checkItems: [
      'Avec « gauche seulement », le son ne vient que de gauche',
      'Avec « droite seulement », le son ne vient que de droite',
      'Les deux côtés sont à peu près au même niveau',
      'Aucun grésillement ni coupure',
    ],
    allGood: '✅ Tes enceintes ou ton casque vont bien.',
  },
  hi: {
    bandDescs: ['निचली आवृत्ति (कंपन में महसूस)', 'मध्य-निचली', 'आधार सुर', 'ऊँची', 'बहुत ऊँची', 'सुनाई दे तो अच्छे कान'],
    leftSide: 'बायाँ', rightSide: 'दायाँ',
    playingNote: 'देखें कि जिस तरफ़ से आवाज़ आ रही है और स्क्रीन पर जो तरफ़ जली है, वे एक ही हैं। उलटा हो तो चैनल आपस में बदले हुए हैं।',
    idleNote: 'नीचे के बटनों से एक-एक तरफ़ बजाकर देखें। आवाज़ 30% से शुरू होती है।',
    modes: ['सिर्फ़ बायाँ', 'सिर्फ़ दायाँ', 'दोनों साथ', 'बायाँ ↔ दायाँ'],
    freq: 'आवृत्ति', volume: 'आवाज़',
    hearingWarn: 'ऊँची आवृत्तियाँ तेज़ आवाज़ में देर तक न सुनें। यह सुनने की क्षमता के लिए ठीक नहीं।',
    checkTitle: 'खुद जाँचकर निशान लगाइए',
    checkItems: [
      'सिर्फ़ बायाँ दबाने पर आवाज़ सिर्फ़ बाईं तरफ़ से आती है',
      'सिर्फ़ दायाँ दबाने पर आवाज़ सिर्फ़ दाईं तरफ़ से आती है',
      'दोनों तरफ़ की आवाज़ लगभग बराबर है',
      'कोई खरखराहट या कटने वाली आवाज़ नहीं',
    ],
    allGood: '✅ आपके स्पीकर या हेडफ़ोन ठीक हैं।',
  },
  'zh-hans': {
    bandDescs: ['低音（能感觉到）', '中低音', '参考音', '高音', '极高音', '听得见就是好耳朵'],
    leftSide: '左',
    rightSide: '右',
    playingNote: '确认你听到的那一边和屏幕上亮起来的那一边一致。要是反的，就是声道接反了。',
    idleNote: '用下面的按钮一次响一边。音量从30%开始。',
    modes: ['只有左', '只有右', '两边一起', '左 ↔ 右'],
    freq: '频率',
    volume: '音量',
    hearingWarn: '别把高频开大声听太久。对听力不好。',
    checkTitle: '这几项自己确认一下',
    checkItems: ['只有左的时候，声音只从左边来', '只有右的时候，声音只从右边来', '两边响度差不多', '没有杂音也没有断断续续'],
    allGood: '✅ 你的音箱或耳机没问题。',
  },
  'zh-hant': {
    bandDescs: ['低音（能感覺到）', '中低音', '參考音', '高音', '極高音', '聽得見就是好耳朵'],
    leftSide: '左',
    rightSide: '右',
    playingNote: '確認你聽到的那一邊和螢幕上亮起來的那一邊一致。要是反的，就是聲道接反了。',
    idleNote: '用下面的按鈕一次響一邊。音量從30%開始。',
    modes: ['只有左', '只有右', '兩邊一起', '左 ↔ 右'],
    freq: '頻率',
    volume: '音量',
    hearingWarn: '別把高頻開大聲聽太久。對聽力不好。',
    checkTitle: '這幾項自己確認一下',
    checkItems: ['只有左的時候，聲音只從左邊來', '只有右的時候，聲音只從右邊來', '兩邊響度差不多', '沒有雜音也沒有斷斷續續'],
    allGood: '✅ 你的喇叭或耳機沒問題。',
  },
};

export const MONITOR_UI: Record<DeviceLang, {
  colors: string[]; tips: string[];
  screenAria: (label: string) => string; fullscreenHint: string; exit: string;
  how: string; keysHint: string; autoCycle: string;
  judgeTitle: string;
  deadTerm: string; deadNote: string;
  stuckTerm: string; stuckNote: string;
  bleedTerm: string; bleedNote: string;
  patchTerm: string; patchNote: string;
  warrantyNote: string;
}> = {
  ko: {
    colors: ['빨강', '초록', '파랑', '흰색', '검정', '회색', '그라디언트', 'RGB 3분할'],
    tips: [
      '빨간 화면에서 검은 점 = 죽은 픽셀',
      '초록에서 안 보이면 초록 서브픽셀 문제',
      '파랑에서 얼룩지면 백라이트 불균일',
      '흰 화면의 검은 점·먼지 확인',
      '가장자리 빛샘과 밝은 점 확인',
      '얼룩(멍)과 색 치우침 확인',
      '계단처럼 끊기면 색 밴딩',
      '세 색의 경계가 또렷한지',
    ],
    screenAria: label => `${label} 화면 — 누르면 다음 색으로`,
    fullscreenHint: '클릭 · → 다음 색  |  Esc 나가기', exit: '✕ 나가기 (Esc)',
    how: '색을 하나 고르면 화면 전체가 그 색으로 덮입니다. 화면에 코를 가까이 대고 다른 색의 점이 있는지 훑어보세요.',
    keysHint: '클릭 또는 → 키로 다음 색, Esc로 나가기. 밝기는 최대로 올리고 보는 편이 잘 보입니다.',
    autoCycle: '▶ 2.5초마다 자동으로 전부 순환',
    judgeTitle: '이렇게 판단하세요',
    deadTerm: '데드 픽셀', deadNote: ' — 모든 색에서 계속 까맣다면 그 픽셀이 죽은 겁니다.',
    stuckTerm: '스턱 픽셀', stuckNote: ' — 검정 화면인데 빨강·초록·파랑 점 하나가 켜져 있다면 서브픽셀이 굳은 겁니다. 며칠 쓰면 풀리기도 합니다.',
    bleedTerm: '빛샘', bleedNote: ' — 검정 화면의 가장자리가 희끄무레하면 백라이트가 새는 것으로, LCD에서는 어느 정도 정상 범위입니다.',
    patchTerm: '얼룩(멍)', patchNote: ' — 회색 화면에서 넓게 어두운 부분이 보이면 패널 눌림일 수 있습니다.',
    warrantyNote: '제조사마다 교환 기준(불량화소 개수)이 다릅니다. 개통·구매 직후에 확인하고 사진을 남겨 두세요.',
  },
  en: {
    colors: ['Red', 'Green', 'Blue', 'White', 'Black', 'Grey', 'Gradient', 'RGB thirds'],
    tips: [
      'A black dot on red = a dead pixel',
      'Missing on green means a green subpixel fault',
      'Patchiness on blue means uneven backlight',
      'Look for black dots and dust on white',
      'Look for edge bleed and bright dots',
      'Look for patches and colour cast',
      'Visible steps mean colour banding',
      'Check the boundaries between the three colours are crisp',
    ],
    screenAria: label => `${label} screen — click for the next colour`,
    fullscreenHint: 'Click · → next colour  |  Esc to exit', exit: '✕ Exit (Esc)',
    how: 'Pick a colour and the whole screen fills with it. Get your nose close to the screen and scan for dots of any other colour.',
    keysHint: 'Click or press → for the next colour, Esc to exit. Turn your brightness all the way up — it shows more.',
    autoCycle: '▶ Cycle through all of them every 2.5 seconds',
    judgeTitle: 'How to read what you see',
    deadTerm: 'Dead pixel', deadNote: ' — stays black on every colour. That pixel is gone.',
    stuckTerm: 'Stuck pixel', stuckNote: ' — a red, green or blue dot lit up on a black screen means a subpixel is stuck. These sometimes free themselves after a few days of use.',
    bleedTerm: 'Backlight bleed', bleedNote: ' — a whitish glow at the edges of a black screen is light leaking past the panel. On an LCD, some of this is normal.',
    patchTerm: 'Patches', patchNote: ' — a broad dark area on the grey screen can mean the panel has been pressed.',
    warrantyNote: 'Manufacturers set different thresholds for a replacement (how many bad pixels). Check on the day it arrives and take photos.',
  },
  es: {
    colors: ['Rojo', 'Verde', 'Azul', 'Blanco', 'Negro', 'Gris', 'Degradado', 'RGB en tercios'],
    tips: [
      'Un punto negro sobre rojo = píxel muerto',
      'Si falta sobre verde, es el subpíxel verde',
      'Si sale a manchas sobre azul, la retroiluminación es irregular',
      'Busca puntos negros y polvo sobre blanco',
      'Busca fugas en los bordes y puntos brillantes',
      'Busca manchas y desviación de color',
      'Si se ven escalones, hay banding de color',
      'Comprueba que los límites entre los tres colores son nítidos',
    ],
    screenAria: label => `Pantalla ${label} — pulsa para el siguiente color`,
    fullscreenHint: 'Clic · → siguiente color  |  Esc para salir', exit: '✕ Salir (Esc)',
    how: 'Elige un color y toda la pantalla se llena de él. Acerca la nariz a la pantalla y repásala buscando puntos de cualquier otro color.',
    keysHint: 'Clic o tecla → para el siguiente color, Esc para salir. Sube el brillo al máximo — se ve mucho más.',
    autoCycle: '▶ Recorrer todos cada 2,5 segundos',
    judgeTitle: 'Cómo interpretar lo que ves',
    deadTerm: 'Píxel muerto', deadNote: ' — se queda negro con todos los colores. Ese píxel ya no está.',
    stuckTerm: 'Píxel atascado', stuckNote: ' — un punto rojo, verde o azul encendido sobre pantalla negra significa que un subpíxel está atascado. A veces se liberan solos tras unos días de uso.',
    bleedTerm: 'Fuga de retroiluminación', bleedNote: ' — un resplandor blanquecino en los bordes de la pantalla negra es luz escapándose del panel. En un LCD, algo de esto es normal.',
    patchTerm: 'Manchas', patchNote: ' — una zona oscura amplia en la pantalla gris puede significar que el panel ha recibido presión.',
    warrantyNote: 'Cada fabricante fija un umbral distinto para el cambio (cuántos píxeles defectuosos). Compruébalo el mismo día que llega y haz fotos.',
  },
  'pt-br': {
    colors: ['Vermelho', 'Verde', 'Azul', 'Branco', 'Preto', 'Cinza', 'Degradê', 'RGB em terços'],
    tips: [
      'Um ponto preto no vermelho = pixel morto',
      'Se falta no verde, é o subpixel verde',
      'Se fica manchado no azul, a luz de fundo está irregular',
      'Procure pontos preto e poeira no branco',
      'Procure vazamento nas bordas e pontos claros',
      'Procure manchas e desvio de cor',
      'Se aparecem degraus, há banding de cor',
      'Confira se as bordas entre as três cores estão nítidas',
    ],
    screenAria: label => `Tela ${label} — toque para a próxima cor`,
    fullscreenHint: 'Clique · → próxima cor  |  Esc para sair', exit: '✕ Sair (Esc)',
    how: 'Escolha uma cor e a tela inteira se enche dela. Chegue bem perto da tela e passe os olhos procurando pontos de qualquer outra cor.',
    keysHint: 'Clique ou tecla → para a próxima cor, Esc para sair. Deixe o brilho no máximo — aparece muito mais.',
    autoCycle: '▶ Percorrer todas a cada 2,5 segundos',
    judgeTitle: 'Como ler o que você vê',
    deadTerm: 'Pixel morto', deadNote: ' — fica preto em todas as cores. Aquele pixel se foi.',
    stuckTerm: 'Pixel travado', stuckNote: ' — um ponto vermelho, verde ou azul aceso na tela preta significa que um subpixel travou. Às vezes eles se soltam sozinhos depois de alguns dias de uso.',
    bleedTerm: 'Vazamento de luz', bleedNote: ' — um brilho esbranquiçado nas bordas da tela preta é luz escapando do painel. Num LCD, um pouco disso é normal.',
    patchTerm: 'Manchas', patchNote: ' — uma área escura larga na tela cinza pode significar que o painel sofreu pressão.',
    warrantyNote: 'Cada fabricante define um limite diferente para troca (quantos pixels defeituosos). Confira no dia em que chega e tire fotos.',
  },
  ja: {
    colors: ['赤', '緑', '青', '白', '黒', 'グレー', 'グラデーション', 'RGB三分割'],
    tips: [
      '赤い画面の黒い点＝ドット抜け',
      '緑で見えないなら緑サブピクセルの問題',
      '青でむらが出るならバックライトの不均一',
      '白い画面の黒い点・ほこりを確認',
      '端の光漏れと明るい点を確認',
      'むら（しみ）と色の偏りを確認',
      '段のように途切れるなら色のバンディング',
      '三色の境界がはっきりしているか',
    ],
    screenAria: label => `${label}の画面 — 押すと次の色へ`,
    fullscreenHint: 'クリック · → 次の色  |  Esc で終了', exit: '✕ 終了（Esc）',
    how: '色を一つ選ぶと画面全体がその色で覆われます。画面に顔を近づけて、ほかの色の点がないか見渡してください。',
    keysHint: 'クリックまたは→キーで次の色、Escで終了。明るさを最大にして見るとよく分かります。',
    autoCycle: '▶ 2.5秒ごとに自動で全部めぐる',
    judgeTitle: 'こう判断してください',
    deadTerm: 'ドット抜け', deadNote: ' — どの色でも黒いままなら、その画素が死んでいます。',
    stuckTerm: '常時点灯', stuckNote: ' — 黒い画面なのに赤・緑・青の点が一つ光っているなら、サブピクセルが固まっています。数日使うと直ることもあります。',
    bleedTerm: '光漏れ', bleedNote: ' — 黒い画面の端が白っぽいのはバックライトが漏れているもので、LCDではある程度は正常の範囲です。',
    patchTerm: 'むら（しみ）', patchNote: ' — グレーの画面で広く暗い部分が見えるなら、パネルが押された跡かもしれません。',
    warrantyNote: 'メーカーごとに交換の基準（不良画素の数）が違います。開通・購入した直後に確認して写真を残しておいてください。',
  },
  de: {
    colors: ['Rot', 'Grün', 'Blau', 'Weiß', 'Schwarz', 'Grau', 'Verlauf', 'RGB-Drittel'],
    tips: [
      'Ein schwarzer Punkt auf Rot = toter Pixel',
      'Fehlt er auf Grün, liegt es am grünen Subpixel',
      'Fleckigkeit auf Blau heißt ungleichmäßige Hintergrundbeleuchtung',
      'Auf Weiß nach schwarzen Punkten und Staub sehen',
      'Auf Randbeleuchtung und helle Punkte achten',
      'Auf Flecken und Farbstich achten',
      'Sichtbare Stufen bedeuten Farbbanding',
      'Prüfen, ob die Grenzen zwischen den drei Farben scharf sind',
    ],
    screenAria: label => `${label}-Bildschirm — klicken für die nächste Farbe`,
    fullscreenHint: 'Klick · → nächste Farbe  |  Esc zum Beenden', exit: '✕ Beenden (Esc)',
    how: 'Wähl eine Farbe und der ganze Bildschirm füllt sich damit. Geh mit der Nase nah heran und such nach Punkten in irgendeiner anderen Farbe.',
    keysHint: 'Klick oder → für die nächste Farbe, Esc zum Beenden. Dreh die Helligkeit ganz hoch — dann sieht man mehr.',
    autoCycle: '▶ Alle 2,5 Sekunden automatisch durchgehen',
    judgeTitle: 'So liest du, was du siehst',
    deadTerm: 'Toter Pixel', deadNote: ' — bleibt bei jeder Farbe schwarz. Dieser Pixel ist hin.',
    stuckTerm: 'Hängender Pixel', stuckNote: ' — ein roter, grüner oder blauer Punkt, der auf schwarzem Bild leuchtet, heißt, ein Subpixel hängt. Manchmal lösen sie sich nach einigen Tagen Nutzung von selbst.',
    bleedTerm: 'Backlight-Bleeding', bleedNote: ' — ein weißlicher Schein an den Rändern eines schwarzen Bildes ist Licht, das am Panel vorbeikommt. Bei einem LCD ist etwas davon normal.',
    patchTerm: 'Flecken', patchNote: ' — eine breite dunkle Stelle auf dem grauen Bild kann bedeuten, dass auf das Panel gedrückt wurde.',
    warrantyNote: 'Hersteller setzen unterschiedliche Schwellen für einen Umtausch (wie viele defekte Pixel). Prüf es am Tag der Lieferung und mach Fotos.',
  },
  fr: {
    colors: ['Rouge', 'Vert', 'Bleu', 'Blanc', 'Noir', 'Gris', 'Dégradé', 'RVB en tiers'],
    tips: [
      'Un point noir sur le rouge = pixel mort',
      'S’il manque sur le vert, c’est le sous-pixel vert',
      'Des taches sur le bleu veulent dire un rétroéclairage inégal',
      'Cherche points noirs et poussière sur le blanc',
      'Cherche les fuites de bord et les points brillants',
      'Cherche les taches et la dominante de couleur',
      'Des marches visibles signifient du banding',
      'Vérifie que les limites entre les trois couleurs sont nettes',
    ],
    screenAria: label => `Écran ${label} — clique pour la couleur suivante`,
    fullscreenHint: 'Clic · → couleur suivante  |  Esc pour sortir', exit: '✕ Sortir (Esc)',
    how: 'Choisis une couleur et tout l’écran s’en remplit. Approche le nez de l’écran et balaie-le à la recherche de points d’une autre couleur.',
    keysHint: 'Clic ou touche → pour la couleur suivante, Esc pour sortir. Monte la luminosité à fond — on voit bien plus.',
    autoCycle: '▶ Tout parcourir toutes les 2,5 secondes',
    judgeTitle: 'Comment lire ce que tu vois',
    deadTerm: 'Pixel mort', deadNote: ' — reste noir sur toutes les couleurs. Ce pixel est perdu.',
    stuckTerm: 'Pixel bloqué', stuckNote: ' — un point rouge, vert ou bleu allumé sur écran noir signifie qu’un sous-pixel est bloqué. Ils se libèrent parfois d’eux-mêmes après quelques jours d’usage.',
    bleedTerm: 'Fuite de rétroéclairage', bleedNote: ' — une lueur blanchâtre sur les bords d’un écran noir, c’est de la lumière qui passe à côté de la dalle. Sur un LCD, un peu de cela est normal.',
    patchTerm: 'Taches', patchNote: ' — une large zone sombre sur l’écran gris peut signifier que la dalle a été pressée.',
    warrantyNote: 'Chaque fabricant fixe un seuil différent pour l’échange (combien de pixels défectueux). Vérifie le jour de la réception et prends des photos.',
  },
  hi: {
    colors: ['लाल', 'हरा', 'नीला', 'सफ़ेद', 'काला', 'सलेटी', 'ग्रेडिएंट', 'RGB तीन हिस्से'],
    tips: [
      'लाल पर काला बिंदु = डेड पिक्सेल',
      'हरे पर न दिखे तो हरे सब-पिक्सेल की गड़बड़',
      'नीले पर धब्बे हों तो बैकलाइट असमान है',
      'सफ़ेद पर काले बिंदु और धूल देखें',
      'किनारों का रिसाव और चमकीले बिंदु देखें',
      'धब्बे और रंग का झुकाव देखें',
      'सीढ़ियाँ दिखें तो रंग बैंडिंग है',
      'तीन रंगों की सीमाएँ साफ़ हैं या नहीं देखें',
    ],
    screenAria: label => `${label} स्क्रीन — दबाएँ तो अगला रंग`,
    fullscreenHint: 'क्लिक · → अगला रंग  |  Esc से बाहर', exit: '✕ बाहर (Esc)',
    how: 'कोई एक रंग चुनें और पूरी स्क्रीन उसी से भर जाती है। स्क्रीन के पास जाकर देखिए कि किसी और रंग का बिंदु दिख रहा है या नहीं।',
    keysHint: 'क्लिक या → कुंजी से अगला रंग, Esc से बाहर। चमक पूरी बढ़ाकर देखने पर ज़्यादा साफ़ दिखता है।',
    autoCycle: '▶ हर 2.5 सेकंड में अपने आप सब घुमाएँ',
    judgeTitle: 'ऐसे समझिए',
    deadTerm: 'डेड पिक्सेल', deadNote: ' — हर रंग पर काला ही रहे तो वह पिक्सेल मर चुका है।',
    stuckTerm: 'अटका पिक्सेल', stuckNote: ' — काली स्क्रीन पर एक लाल, हरा या नीला बिंदु जला रहे तो सब-पिक्सेल अटक गया है। कुछ दिन इस्तेमाल में कभी अपने आप ठीक भी हो जाता है।',
    bleedTerm: 'बैकलाइट रिसाव', bleedNote: ' — काली स्क्रीन के किनारे सफ़ेदी लिए दिखें तो बैकलाइट रिस रही है; LCD में कुछ हद तक यह सामान्य है।',
    patchTerm: 'धब्बे', patchNote: ' — सलेटी स्क्रीन पर चौड़ा गहरा हिस्सा दिखे तो पैनल दबा हुआ हो सकता है।',
    warrantyNote: 'हर कंपनी बदलने की शर्त (कितने ख़राब पिक्सेल) अलग रखती है। मिलने के दिन ही जाँच लें और तस्वीरें रख लें।',
  },
  'zh-hans': {
    colors: ['红', '绿', '蓝', '白', '黑', '灰', '渐变', 'RGB三分'],
    tips: ['红色上的黑点 = 坏点', '绿色上缺失表示绿子像素坏了', '蓝色上不均匀表示背光不匀', '白色上找黑点和灰尘', '找边缘漏光和亮点', '找斑块和偏色', '看得出台阶就是色带', '看三色交界处清不清晰'],
    screenAria: label => `${label}画面 — 点一下换下一个颜色`,
    fullscreenHint: '点击 · → 下一个颜色  |  Esc 退出',
    exit: '✕ 退出（Esc）',
    how: '挑一个颜色，整个屏幕就铺满它。把脸凑近屏幕，扫一遍有没有别的颜色的点。',
    keysHint: '点击或按 → 换下一个颜色，Esc 退出。亮度开到最大 — 看得更清楚。',
    autoCycle: '▶ 每2.5秒自动换一个',
    judgeTitle: '看到的东西怎么读',
    deadTerm: '坏点',
    deadNote: '  — 在任何颜色下都是黑的。那个像素已经死了。',
    stuckTerm: '亮点',
    stuckNote: '  — 黑屏上有红、绿或蓝的点，说明某个子像素卡住了。用上几天有时会自己恢复。',
    bleedTerm: '背光漏光',
    bleedNote: '  — 黑屏边缘泛白，是光从面板旁边漏出来。LCD上有一点是正常的。',
    patchTerm: '斑块',
    patchNote: '  — 灰屏上有一大片发暗，可能是面板被压过。',
    warrantyNote: '各家厂商换货的门槛（坏点几个）不一样。到手当天就检查，并且拍照留证。',
  },
  'zh-hant': {
    colors: ['紅', '綠', '藍', '白', '黑', '灰', '漸層', 'RGB三分'],
    tips: ['紅色上的黑點 = 壞點', '綠色上缺失表示綠子像素壞了', '藍色上不均勻表示背光不勻', '白色上找黑點和灰塵', '找邊緣漏光和亮點', '找斑塊和偏色', '看得出階梯就是色帶', '看三色交界處清不清晰'],
    screenAria: label => `${label}畫面 — 點一下換下一個顏色`,
    fullscreenHint: '點擊 · → 下一個顏色  |  Esc 離開',
    exit: '✕ 離開（Esc）',
    how: '挑一個顏色，整個螢幕就鋪滿它。把臉湊近螢幕，掃一遍有沒有別的顏色的點。',
    keysHint: '點擊或按 → 換下一個顏色，Esc 離開。亮度開到最大 — 看得更清楚。',
    autoCycle: '▶ 每2.5秒自動換一個',
    judgeTitle: '看到的東西怎麼讀',
    deadTerm: '壞點',
    deadNote: '  — 在任何顏色下都是黑的。那個像素已經死了。',
    stuckTerm: '亮點',
    stuckNote: '  — 黑畫面上有紅、綠或藍的點，說明某個子像素卡住了。用上幾天有時會自己恢復。',
    bleedTerm: '背光漏光',
    bleedNote: '  — 黑畫面邊緣泛白，是光從面板旁邊漏出來。LCD上有一點是正常的。',
    patchTerm: '斑塊',
    patchNote: '  — 灰畫面上有一大片發暗，可能是面板被壓過。',
    warrantyNote: '各家廠商換貨的門檻（壞點幾個）不一樣。到手當天就檢查，並且拍照留證。',
  },
};

export const REFRESH_UI: Record<DeviceLang, {
  measuring: string; resultLabel: string; ready: string;
  measuringBtn: string; again: string; startBtn: string; stayHere: string;
  frameInterval: string; fastestFrame: string; slowestFrame: string; jitter: string;
  oddNote: (hz: number, nearest: number) => string;
  normalNote: (nearest: number) => string; sixtyHint: string;
  droppedNote: (n: number) => string;
  motionTitle: string; move: string; stopMove: string; motionNote: string;
}> = {
  ko: {
    measuring: '측정 중', resultLabel: '측정 결과', ready: '준비됨',
    measuringBtn: '측정 중…', again: '다시 측정', startBtn: '주사율 측정 시작 (약 2초)',
    stayHere: '측정하는 동안 이 탭을 보고 계셔야 합니다. 다른 창으로 옮기면 브라우저가 프레임을 늦춥니다.',
    frameInterval: '프레임 간격', fastestFrame: '가장 빠른 프레임', slowestFrame: '가장 느린 프레임', jitter: '흔들림(편차)',
    oddNote: (hz, nearest) => `${hz}Hz는 흔한 규격(${nearest}Hz)과 차이가 있습니다. 측정 중 다른 작업이 끼어들었을 수 있으니 한 번 더 재보세요.`,
    normalNote: nearest => `이 화면은 약 ${nearest}Hz로 동작하고 있습니다.`,
    sixtyHint: ' 고주사율 모니터를 쓰고 있다면 디스플레이 설정에서 주사율이 60Hz로 잡혀 있는지 확인해 보세요.',
    droppedNote: n => `측정 중 ${n}프레임이 평소보다 크게 늦었습니다. 백그라운드 프로그램이 많을 때 나타납니다.`,
    motionTitle: '움직임 부드러움 확인', move: '움직이기', stopMove: '멈추기',
    motionNote: '네모가 뚝뚝 끊겨 보이면 주사율이 낮거나 다른 프로그램이 그래픽을 물고 있는 상태입니다.',
  },
  en: {
    measuring: 'Measuring', resultLabel: 'Result', ready: 'Ready',
    measuringBtn: 'Measuring…', again: 'Measure again', startBtn: 'Measure the refresh rate (about 2s)',
    stayHere: 'Keep this tab in view while it measures. Switch windows and the browser throttles the frames.',
    frameInterval: 'Frame interval', fastestFrame: 'Fastest frame', slowestFrame: 'Slowest frame', jitter: 'Jitter (variance)',
    oddNote: (hz, nearest) => `${hz}Hz does not match a common rate (${nearest}Hz). Something may have interrupted the measurement — try once more.`,
    normalNote: nearest => `This screen is running at about ${nearest}Hz.`,
    sixtyHint: ' If you own a high-refresh monitor, check whether your display settings have it pinned at 60Hz.',
    droppedNote: n => `${n} frames arrived much later than the rest. That shows up when a lot is running in the background.`,
    motionTitle: 'Check motion smoothness', move: 'Start moving', stopMove: 'Stop',
    motionNote: 'If the square looks like it is stepping rather than gliding, either the refresh rate is low or something else has hold of the graphics.',
  },
  es: {
    measuring: 'Midiendo', resultLabel: 'Resultado', ready: 'Listo',
    measuringBtn: 'Midiendo…', again: 'Medir otra vez', startBtn: 'Medir la frecuencia de refresco (unos 2s)',
    stayHere: 'Mantén esta pestaña a la vista mientras mide. Si cambias de ventana, el navegador frena los fotogramas.',
    frameInterval: 'Intervalo entre fotogramas', fastestFrame: 'Fotograma más rápido', slowestFrame: 'Fotograma más lento', jitter: 'Irregularidad (varianza)',
    oddNote: (hz, nearest) => `${hz}Hz no coincide con una frecuencia habitual (${nearest}Hz). Puede que algo haya interrumpido la medición — prueba una vez más.`,
    normalNote: nearest => `Esta pantalla está funcionando a unos ${nearest}Hz.`,
    sixtyHint: ' Si tienes un monitor de alta frecuencia, comprueba si tus ajustes de pantalla lo tienen fijado a 60Hz.',
    droppedNote: n => `${n} fotogramas llegaron mucho más tarde que el resto. Eso aparece cuando hay muchas cosas corriendo de fondo.`,
    motionTitle: 'Comprobar la fluidez del movimiento', move: 'Mover', stopMove: 'Parar',
    motionNote: 'Si el cuadrado parece ir a saltos en vez de deslizarse, o la frecuencia es baja o algo más está ocupando la gráfica.',
  },
  'pt-br': {
    measuring: 'Medindo', resultLabel: 'Resultado', ready: 'Pronto',
    measuringBtn: 'Medindo…', again: 'Medir de novo', startBtn: 'Medir a taxa de atualização (uns 2s)',
    stayHere: 'Mantenha esta aba à vista enquanto mede. Se trocar de janela, o navegador segura os quadros.',
    frameInterval: 'Intervalo entre quadros', fastestFrame: 'Quadro mais rápido', slowestFrame: 'Quadro mais lento', jitter: 'Irregularidade (variância)',
    oddNote: (hz, nearest) => `${hz}Hz não bate com uma taxa comum (${nearest}Hz). Algo pode ter interrompido a medição — tente mais uma vez.`,
    normalNote: nearest => `Esta tela está rodando a cerca de ${nearest}Hz.`,
    sixtyHint: ' Se você tem um monitor de alta taxa, veja se as configurações de tela não o deixaram preso em 60Hz.',
    droppedNote: n => `${n} quadros chegaram bem mais tarde que os outros. Isso aparece quando há muita coisa rodando em segundo plano.`,
    motionTitle: 'Conferir a fluidez do movimento', move: 'Mover', stopMove: 'Parar',
    motionNote: 'Se o quadrado parece andar aos saltos em vez de deslizar, ou a taxa está baixa ou outra coisa está ocupando a placa de vídeo.',
  },
  ja: {
    measuring: '測定中', resultLabel: '測定結果', ready: '準備完了',
    measuringBtn: '測定中…', again: 'もう一度測る', startBtn: 'リフレッシュレートを測る（約2秒）',
    stayHere: '測っているあいだはこのタブを見ていてください。別のウィンドウに移るとブラウザがフレームを落とします。',
    frameInterval: 'フレーム間隔', fastestFrame: 'もっとも速いフレーム', slowestFrame: 'もっとも遅いフレーム', jitter: 'ばらつき（偏差）',
    oddNote: (hz, nearest) => `${hz}Hzはよくある規格（${nearest}Hz）とずれています。測定中にほかの処理が割り込んだ可能性があるので、もう一度測ってみてください。`,
    normalNote: nearest => `この画面は約${nearest}Hzで動いています。`,
    sixtyHint: ' 高リフレッシュレートのモニターを使っているなら、ディスプレイ設定で60Hzになっていないか確認してみてください。',
    droppedNote: n => `測定中に${n}フレームがふだんより大きく遅れました。バックグラウンドのプログラムが多いときに出ます。`,
    motionTitle: '動きのなめらかさを確認', move: '動かす', stopMove: '止める',
    motionNote: '四角がなめらかに動かず段々に見えるなら、リフレッシュレートが低いか、ほかのプログラムがグラフィックを掴んでいる状態です。',
  },
  de: {
    measuring: 'Wird gemessen', resultLabel: 'Ergebnis', ready: 'Bereit',
    measuringBtn: 'Wird gemessen…', again: 'Nochmal messen', startBtn: 'Bildwiederholrate messen (etwa 2s)',
    stayHere: 'Lass diesen Tab während der Messung im Blick. Wechselst du das Fenster, bremst der Browser die Bilder.',
    frameInterval: 'Bildabstand', fastestFrame: 'Schnellstes Bild', slowestFrame: 'Langsamstes Bild', jitter: 'Schwankung (Streuung)',
    oddNote: (hz, nearest) => `${hz}Hz passt zu keiner gängigen Rate (${nearest}Hz). Vielleicht ist etwas in die Messung geplatzt — mess noch einmal.`,
    normalNote: nearest => `Dieser Bildschirm läuft mit etwa ${nearest}Hz.`,
    sixtyHint: ' Wenn du einen Monitor mit hoher Wiederholrate hast, prüfe, ob die Anzeigeeinstellungen ihn bei 60Hz festhalten.',
    droppedNote: n => `${n} Bilder kamen deutlich später als die übrigen. Das zeigt sich, wenn im Hintergrund viel läuft.`,
    motionTitle: 'Laufruhe prüfen', move: 'Bewegen', stopMove: 'Anhalten',
    motionNote: 'Wenn das Quadrat zu springen scheint statt zu gleiten, ist entweder die Wiederholrate niedrig oder etwas anderes hält die Grafik besetzt.',
  },
  fr: {
    measuring: 'Mesure en cours', resultLabel: 'Résultat', ready: 'Prêt',
    measuringBtn: 'Mesure en cours…', again: 'Mesurer à nouveau', startBtn: 'Mesurer la fréquence de rafraîchissement (environ 2s)',
    stayHere: 'Garde cet onglet visible pendant la mesure. Si tu changes de fenêtre, le navigateur bride les images.',
    frameInterval: 'Intervalle entre images', fastestFrame: 'Image la plus rapide', slowestFrame: 'Image la plus lente', jitter: 'Irrégularité (variance)',
    oddNote: (hz, nearest) => `${hz}Hz ne correspond pas à une fréquence courante (${nearest}Hz). Quelque chose a peut-être interrompu la mesure — refais un essai.`,
    normalNote: nearest => `Cet écran tourne à environ ${nearest}Hz.`,
    sixtyHint: ' Si tu as un écran à haute fréquence, vérifie si tes réglages d’affichage ne le bloquent pas à 60Hz.',
    droppedNote: n => `${n} images sont arrivées bien plus tard que les autres. Cela se produit quand beaucoup de choses tournent en arrière-plan.`,
    motionTitle: 'Vérifier la fluidité du mouvement', move: 'Faire bouger', stopMove: 'Arrêter',
    motionNote: 'Si le carré semble avancer par à-coups au lieu de glisser, soit la fréquence est basse, soit autre chose occupe la carte graphique.',
  },
  hi: {
    measuring: 'मापा जा रहा है', resultLabel: 'नतीजा', ready: 'तैयार',
    measuringBtn: 'मापा जा रहा है…', again: 'फिर मापें', startBtn: 'रिफ़्रेश दर मापें (लगभग 2 सेकंड)',
    stayHere: 'मापने के दौरान यही टैब खुला रखें। दूसरी खिड़की पर जाने से ब्राउज़र फ़्रेम धीमे कर देता है।',
    frameInterval: 'फ़्रेम अंतराल', fastestFrame: 'सबसे तेज़ फ़्रेम', slowestFrame: 'सबसे धीमा फ़्रेम', jitter: 'डोलाव (विचलन)',
    oddNote: (hz, nearest) => `${hz}Hz आम मानकों (${nearest}Hz) से मेल नहीं खाता। मापने के बीच कोई और काम आ गया होगा — एक बार फिर मापें।`,
    normalNote: nearest => `यह स्क्रीन लगभग ${nearest}Hz पर चल रही है।`,
    sixtyHint: ' अगर आपके पास ऊँची रिफ़्रेश दर वाला मॉनिटर है, तो देखें कि डिस्प्ले सेटिंग में वह 60Hz पर अटका नहीं है।',
    droppedNote: n => `मापने के दौरान ${n} फ़्रेम बाकियों से बहुत देर से आए। पीछे कई प्रोग्राम चल रहे हों तो ऐसा होता है।`,
    motionTitle: 'गति की चिकनाई जाँचें', move: 'चलाएँ', stopMove: 'रोकें',
    motionNote: 'चौकोर फिसलने की जगह झटकों में बढ़ता दिखे तो या रिफ़्रेश दर कम है, या कोई और प्रोग्राम ग्राफ़िक्स पकड़े बैठा है।',
  },
  'zh-hans': {
    measuring: '测量中',
    resultLabel: '结果',
    ready: '就绪',
    measuringBtn: '测量中…',
    again: '再测一次',
    startBtn: '测量刷新率（约2秒）',
    stayHere: '测量时让这个标签页保持在前台。切走的话浏览器会限制帧数。',
    frameInterval: '帧间隔',
    fastestFrame: '最快一帧',
    slowestFrame: '最慢一帧',
    jitter: '抖动（方差）',
    oddNote: (hz, nearest) => `${hz}Hz和常见的刷新率对不上（最接近${nearest}Hz）。可能是测量被打断了 — 再测一次看看。`,
    normalNote: nearest => `这块屏幕大约跑在${nearest}Hz。`,
    sixtyHint: '  如果你的显示器是高刷新率的，去显示设置里看看是不是被锁在60Hz了。',
    droppedNote: n => `有${n}帧比其余的晚到很多。后台跑着很多东西时会这样。`,
    motionTitle: '检查动态流畅度',
    move: '开始移动',
    stopMove: '停止',
    motionNote: '方块看起来是一格一格跳而不是滑过去的话，要么刷新率低，要么显卡被别的东西占着。',
  },
  'zh-hant': {
    measuring: '測量中',
    resultLabel: '結果',
    ready: '就緒',
    measuringBtn: '測量中…',
    again: '再測一次',
    startBtn: '測量更新率（約2秒）',
    stayHere: '測量時讓這個分頁保持在前台。切走的話瀏覽器會限制影格數。',
    frameInterval: '影格間隔',
    fastestFrame: '最快一格',
    slowestFrame: '最慢一格',
    jitter: '抖動（變異）',
    oddNote: (hz, nearest) => `${hz}Hz和常見的更新率對不上（最接近${nearest}Hz）。可能是測量被打斷了 — 再測一次看看。`,
    normalNote: nearest => `這塊螢幕大約跑在${nearest}Hz。`,
    sixtyHint: '  如果你的螢幕是高更新率的，去顯示設定裡看看是不是被鎖在60Hz了。',
    droppedNote: n => `有${n}格比其餘的晚到很多。背景跑著很多東西時會這樣。`,
    motionTitle: '檢查動態流暢度',
    move: '開始移動',
    stopMove: '停止',
    motionNote: '方塊看起來是一格一格跳而不是滑過去的話，要麼更新率低，要麼顯示卡被別的東西占著。',
  },
};

export const DEVICE_INFO_UI: Record<DeviceLang, {
  browsers: Record<string, string>; unknown: string; windows10or11: string;
  screenTitle: string; browserTitle: string; hardwareTitle: string;
  monitorRes: string; monitorResHint: string; windowSize: string;
  workArea: string; workAreaHint: string; dpr: string; dprHint: string;
  realPixels: string; colorDepth: string; bitSuffix: (n: number) => string;
  orientation: string;
  browser: string; os: string; language: string;
  cookies: string; cookiesOn: string; cookiesOff: string;
  network: string; online: string; offline: string; timezone: string;
  cores: string; coresHint: string; countSuffix: (n: number | string) => string;
  memory: string; memoryValue: (gb: number) => string; memoryUnknown: string; memoryHint: string;
  touchPoints: string; touchHint: string;
  loading: string; copy: string; copied: string;
  privacy1: string; privacy2: string;
}> = {
  ko: {
    browsers: { edge: '엣지', opera: '오페라', samsung: '삼성 인터넷', whale: '웨일', firefox: '파이어폭스', chrome: '크롬', safari: '사파리' },
    unknown: '알 수 없음', windows10or11: 'Windows 10 또는 11',
    screenTitle: '화면', browserTitle: '브라우저', hardwareTitle: '하드웨어',
    monitorRes: '모니터 해상도', monitorResHint: '운영체제가 보고하는 논리 해상도', windowSize: '브라우저 창 크기',
    workArea: '작업 영역', workAreaHint: '작업표시줄 등을 뺀 크기', dpr: '픽셀 배율(DPR)', dprHint: '2 이상이면 고해상도(레티나) 화면',
    realPixels: '실제 픽셀 추정', colorDepth: '색 심도', bitSuffix: n => `${n}비트`,
    orientation: '화면 방향',
    browser: '브라우저', os: '운영체제', language: '언어',
    cookies: '쿠키 사용', cookiesOn: '허용됨', cookiesOff: '차단됨',
    network: '네트워크 상태', online: '온라인', offline: '오프라인', timezone: '시간대',
    cores: 'CPU 논리 코어', coresHint: '브라우저가 쓸 수 있는 스레드 수', countSuffix: n => `${n}개`,
    memory: '메모리(대략)', memoryValue: gb => `${gb}GB 이상`, memoryUnknown: '브라우저가 알려주지 않음',
    memoryHint: '크롬 계열만 제공하며 값이 반올림돼 있다',
    touchPoints: '동시 터치 점수', touchHint: '0이면 터치 지원 없음',
    loading: '기기 정보를 읽는 중…', copy: '📋 전체 정보 복사하기', copied: '✅ 복사했습니다',
    privacy1: '여기 있는 값은 브라우저가 알려주는 것뿐이며 어디로도 전송되지 않습니다.',
    privacy2: '개인정보(IP·위치·계정)는 수집하지도, 표시하지도 않습니다.',
  },
  en: {
    browsers: { edge: 'Edge', opera: 'Opera', samsung: 'Samsung Internet', whale: 'Whale', firefox: 'Firefox', chrome: 'Chrome', safari: 'Safari' },
    unknown: 'Unknown', windows10or11: 'Windows 10 or 11',
    screenTitle: 'Display', browserTitle: 'Browser', hardwareTitle: 'Hardware',
    monitorRes: 'Screen resolution', monitorResHint: 'The logical resolution the OS reports', windowSize: 'Browser window size',
    workArea: 'Work area', workAreaHint: 'With the taskbar and similar subtracted', dpr: 'Pixel ratio (DPR)', dprHint: '2 or more means a high-density (Retina) screen',
    realPixels: 'Estimated real pixels', colorDepth: 'Colour depth', bitSuffix: n => `${n}-bit`,
    orientation: 'Orientation',
    browser: 'Browser', os: 'Operating system', language: 'Language',
    cookies: 'Cookies', cookiesOn: 'allowed', cookiesOff: 'blocked',
    network: 'Network', online: 'online', offline: 'offline', timezone: 'Time zone',
    cores: 'CPU logical cores', coresHint: 'Threads the browser can use', countSuffix: n => `${n}`,
    memory: 'Memory (approx)', memoryValue: gb => `${gb}GB or more`, memoryUnknown: 'the browser does not report it',
    memoryHint: 'Only Chromium browsers provide this, and the value is rounded',
    touchPoints: 'Simultaneous touch points', touchHint: '0 means no touch support',
    loading: 'Reading device info…', copy: '📋 Copy all of this', copied: '✅ Copied',
    privacy1: 'Everything here comes from what the browser reports, and none of it is sent anywhere.',
    privacy2: 'Personal data — IP, location, accounts — is neither collected nor shown.',
  },
  es: {
    browsers: { edge: 'Edge', opera: 'Opera', samsung: 'Samsung Internet', whale: 'Whale', firefox: 'Firefox', chrome: 'Chrome', safari: 'Safari' },
    unknown: 'Desconocido', windows10or11: 'Windows 10 u 11',
    screenTitle: 'Pantalla', browserTitle: 'Navegador', hardwareTitle: 'Hardware',
    monitorRes: 'Resolución de pantalla', monitorResHint: 'La resolución lógica que informa el sistema', windowSize: 'Tamaño de la ventana del navegador',
    workArea: 'Área de trabajo', workAreaHint: 'Restando la barra de tareas y similares', dpr: 'Relación de píxeles (DPR)', dprHint: '2 o más significa pantalla de alta densidad (Retina)',
    realPixels: 'Píxeles reales estimados', colorDepth: 'Profundidad de color', bitSuffix: n => `${n} bits`,
    orientation: 'Orientación',
    browser: 'Navegador', os: 'Sistema operativo', language: 'Idioma',
    cookies: 'Cookies', cookiesOn: 'permitidas', cookiesOff: 'bloqueadas',
    network: 'Red', online: 'en línea', offline: 'sin conexión', timezone: 'Zona horaria',
    cores: 'Núcleos lógicos de CPU', coresHint: 'Hilos que el navegador puede usar', countSuffix: n => `${n}`,
    memory: 'Memoria (aprox)', memoryValue: gb => `${gb}GB o más`, memoryUnknown: 'el navegador no lo informa',
    memoryHint: 'Solo lo dan los navegadores Chromium, y el valor está redondeado',
    touchPoints: 'Puntos táctiles simultáneos', touchHint: '0 significa sin soporte táctil',
    loading: 'Leyendo la información del aparato…', copy: '📋 Copiar todo esto', copied: '✅ Copiado',
    privacy1: 'Todo lo que hay aquí viene de lo que informa el navegador, y nada se envía a ningún sitio.',
    privacy2: 'Los datos personales — IP, ubicación, cuentas — no se recogen ni se muestran.',
  },
  'pt-br': {
    browsers: { edge: 'Edge', opera: 'Opera', samsung: 'Samsung Internet', whale: 'Whale', firefox: 'Firefox', chrome: 'Chrome', safari: 'Safari' },
    unknown: 'Desconhecido', windows10or11: 'Windows 10 ou 11',
    screenTitle: 'Tela', browserTitle: 'Navegador', hardwareTitle: 'Hardware',
    monitorRes: 'Resolução de tela', monitorResHint: 'A resolução lógica que o sistema informa', windowSize: 'Tamanho da janela do navegador',
    workArea: 'Área de trabalho', workAreaHint: 'Descontando a barra de tarefas e afins', dpr: 'Proporção de pixels (DPR)', dprHint: '2 ou mais significa tela de alta densidade (Retina)',
    realPixels: 'Pixels reais estimados', colorDepth: 'Profundidade de cor', bitSuffix: n => `${n} bits`,
    orientation: 'Orientação',
    browser: 'Navegador', os: 'Sistema operacional', language: 'Idioma',
    cookies: 'Cookies', cookiesOn: 'permitidos', cookiesOff: 'bloqueados',
    network: 'Rede', online: 'on-line', offline: 'off-line', timezone: 'Fuso horário',
    cores: 'Núcleos lógicos da CPU', coresHint: 'Threads que o navegador pode usar', countSuffix: n => `${n}`,
    memory: 'Memória (aprox)', memoryValue: gb => `${gb}GB ou mais`, memoryUnknown: 'o navegador não informa',
    memoryHint: 'Só os navegadores Chromium fornecem, e o valor vem arredondado',
    touchPoints: 'Pontos de toque simultâneos', touchHint: '0 significa sem suporte a toque',
    loading: 'Lendo as informações do aparelho…', copy: '📋 Copiar tudo isso', copied: '✅ Copiado',
    privacy1: 'Tudo aqui vem do que o navegador informa, e nada é enviado a lugar nenhum.',
    privacy2: 'Dados pessoais — IP, localização, contas — não são coletados nem exibidos.',
  },
  ja: {
    browsers: { edge: 'Edge', opera: 'Opera', samsung: 'Samsung Internet', whale: 'Whale', firefox: 'Firefox', chrome: 'Chrome', safari: 'Safari' },
    unknown: '不明', windows10or11: 'Windows 10 または 11',
    screenTitle: '画面', browserTitle: 'ブラウザ', hardwareTitle: 'ハードウェア',
    monitorRes: 'モニターの解像度', monitorResHint: 'OSが報告する論理解像度', windowSize: 'ブラウザウィンドウの大きさ',
    workArea: '作業領域', workAreaHint: 'タスクバーなどを除いた大きさ', dpr: 'ピクセル比（DPR）', dprHint: '2以上なら高精細（Retina）画面',
    realPixels: '実ピクセルの推定', colorDepth: '色深度', bitSuffix: n => `${n}ビット`,
    orientation: '画面の向き',
    browser: 'ブラウザ', os: 'OS', language: '言語',
    cookies: 'クッキー', cookiesOn: '許可', cookiesOff: 'ブロック',
    network: 'ネットワーク', online: 'オンライン', offline: 'オフライン', timezone: 'タイムゾーン',
    cores: 'CPU論理コア', coresHint: 'ブラウザが使えるスレッド数', countSuffix: n => `${n}個`,
    memory: 'メモリ（おおよそ）', memoryValue: gb => `${gb}GB以上`, memoryUnknown: 'ブラウザが教えてくれません',
    memoryHint: 'Chromium系だけが提供し、値は丸められています',
    touchPoints: '同時タッチ点数', touchHint: '0ならタッチ非対応',
    loading: '端末情報を読み込んでいます…', copy: '📋 すべてコピーする', copied: '✅ コピーしました',
    privacy1: 'ここにある値はブラウザが教えてくれるものだけで、どこにも送信されません。',
    privacy2: '個人情報（IP・位置・アカウント）は収集も表示もしていません。',
  },
  de: {
    browsers: { edge: 'Edge', opera: 'Opera', samsung: 'Samsung Internet', whale: 'Whale', firefox: 'Firefox', chrome: 'Chrome', safari: 'Safari' },
    unknown: 'Unbekannt', windows10or11: 'Windows 10 oder 11',
    screenTitle: 'Bildschirm', browserTitle: 'Browser', hardwareTitle: 'Hardware',
    monitorRes: 'Bildschirmauflösung', monitorResHint: 'Die logische Auflösung, die das System meldet', windowSize: 'Größe des Browserfensters',
    workArea: 'Arbeitsbereich', workAreaHint: 'Taskleiste und Ähnliches abgezogen', dpr: 'Pixelverhältnis (DPR)', dprHint: '2 oder mehr heißt hochauflösender (Retina-)Bildschirm',
    realPixels: 'Geschätzte echte Pixel', colorDepth: 'Farbtiefe', bitSuffix: n => `${n} Bit`,
    orientation: 'Ausrichtung',
    browser: 'Browser', os: 'Betriebssystem', language: 'Sprache',
    cookies: 'Cookies', cookiesOn: 'erlaubt', cookiesOff: 'blockiert',
    network: 'Netzwerk', online: 'online', offline: 'offline', timezone: 'Zeitzone',
    cores: 'Logische CPU-Kerne', coresHint: 'Threads, die der Browser nutzen kann', countSuffix: n => `${n}`,
    memory: 'Speicher (ungefähr)', memoryValue: gb => `${gb}GB oder mehr`, memoryUnknown: 'der Browser meldet es nicht',
    memoryHint: 'Nur Chromium-Browser liefern das, und der Wert ist gerundet',
    touchPoints: 'Gleichzeitige Berührungspunkte', touchHint: '0 heißt keine Touch-Unterstützung',
    loading: 'Geräteinfos werden gelesen…', copy: '📋 Alles kopieren', copied: '✅ Kopiert',
    privacy1: 'Alles hier stammt aus dem, was der Browser meldet, und nichts davon wird irgendwohin gesendet.',
    privacy2: 'Persönliche Daten — IP, Standort, Konten — werden weder erhoben noch angezeigt.',
  },
  fr: {
    browsers: { edge: 'Edge', opera: 'Opera', samsung: 'Samsung Internet', whale: 'Whale', firefox: 'Firefox', chrome: 'Chrome', safari: 'Safari' },
    unknown: 'Inconnu', windows10or11: 'Windows 10 ou 11',
    screenTitle: 'Écran', browserTitle: 'Navigateur', hardwareTitle: 'Matériel',
    monitorRes: 'Résolution d’écran', monitorResHint: 'La résolution logique rapportée par le système', windowSize: 'Taille de la fenêtre du navigateur',
    workArea: 'Zone de travail', workAreaHint: 'Barre des tâches et compagnie déduites', dpr: 'Ratio de pixels (DPR)', dprHint: '2 ou plus signifie un écran haute densité (Retina)',
    realPixels: 'Pixels réels estimés', colorDepth: 'Profondeur de couleur', bitSuffix: n => `${n} bits`,
    orientation: 'Orientation',
    browser: 'Navigateur', os: 'Système d’exploitation', language: 'Langue',
    cookies: 'Cookies', cookiesOn: 'autorisés', cookiesOff: 'bloqués',
    network: 'Réseau', online: 'en ligne', offline: 'hors ligne', timezone: 'Fuseau horaire',
    cores: 'Cœurs logiques du processeur', coresHint: 'Threads que le navigateur peut utiliser', countSuffix: n => `${n}`,
    memory: 'Mémoire (approx)', memoryValue: gb => `${gb}GB ou plus`, memoryUnknown: 'le navigateur ne le rapporte pas',
    memoryHint: 'Seuls les navigateurs Chromium le fournissent, et la valeur est arrondie',
    touchPoints: 'Points de contact simultanés', touchHint: '0 signifie aucune prise en charge du tactile',
    loading: 'Lecture des infos de l’appareil…', copy: '📋 Copier tout ceci', copied: '✅ Copié',
    privacy1: 'Tout ce qui est ici vient de ce que le navigateur rapporte, et rien n’est envoyé où que ce soit.',
    privacy2: 'Les données personnelles — IP, position, comptes — ne sont ni collectées ni affichées.',
  },
  hi: {
    browsers: { edge: 'Edge', opera: 'Opera', samsung: 'Samsung Internet', whale: 'Whale', firefox: 'Firefox', chrome: 'Chrome', safari: 'Safari' },
    unknown: 'पता नहीं', windows10or11: 'Windows 10 या 11',
    screenTitle: 'स्क्रीन', browserTitle: 'ब्राउज़र', hardwareTitle: 'हार्डवेयर',
    monitorRes: 'मॉनिटर रिज़ॉल्यूशन', monitorResHint: 'ऑपरेटिंग सिस्टम बताने वाला तार्किक रिज़ॉल्यूशन', windowSize: 'ब्राउज़र खिड़की का नाप',
    workArea: 'कार्य क्षेत्र', workAreaHint: 'टास्कबार आदि घटाकर', dpr: 'पिक्सेल अनुपात (DPR)', dprHint: '2 या ज़्यादा हो तो उच्च घनत्व (रेटिना) स्क्रीन',
    realPixels: 'असली पिक्सेल का अनुमान', colorDepth: 'रंग गहराई', bitSuffix: n => `${n} बिट`,
    orientation: 'स्क्रीन की दिशा',
    browser: 'ब्राउज़र', os: 'ऑपरेटिंग सिस्टम', language: 'भाषा',
    cookies: 'कुकी', cookiesOn: 'अनुमति है', cookiesOff: 'रोकी गई',
    network: 'नेटवर्क', online: 'ऑनलाइन', offline: 'ऑफ़लाइन', timezone: 'समय क्षेत्र',
    cores: 'CPU तार्किक कोर', coresHint: 'ब्राउज़र जितने थ्रेड इस्तेमाल कर सकता है', countSuffix: n => `${n}`,
    memory: 'मेमोरी (लगभग)', memoryValue: gb => `${gb}GB या ज़्यादा`, memoryUnknown: 'ब्राउज़र नहीं बताता',
    memoryHint: 'सिर्फ़ Chromium ब्राउज़र देते हैं, और मान गोल किया हुआ होता है',
    touchPoints: 'एक साथ स्पर्श बिंदु', touchHint: '0 का मतलब स्पर्श समर्थन नहीं',
    loading: 'उपकरण की जानकारी पढ़ी जा रही है…', copy: '📋 सारी जानकारी कॉपी करें', copied: '✅ कॉपी हो गया',
    privacy1: 'यहाँ जो भी है वह ब्राउज़र की बताई जानकारी है, और कुछ भी कहीं नहीं भेजा जाता।',
    privacy2: 'निजी जानकारी — IP, स्थान, खाते — न जमा की जाती है न दिखाई जाती है।',
  },
  'zh-hans': {
    browsers: { edge: 'Edge', opera: 'Opera', samsung: '三星浏览器', whale: 'Whale', firefox: 'Firefox', chrome: 'Chrome', safari: 'Safari' },
    unknown: '未知',
    windows10or11: 'Windows 10 或 11',
    screenTitle: '显示',
    browserTitle: '浏览器',
    hardwareTitle: '硬件',
    monitorRes: '屏幕分辨率',
    monitorResHint: '系统报出来的逻辑分辨率',
    windowSize: '浏览器窗口大小',
    workArea: '工作区',
    workAreaHint: '扣掉任务栏之类的部分',
    dpr: '像素比（DPR）',
    dprHint: '2以上就是高密度（Retina）屏幕',
    realPixels: '估算的实际像素',
    colorDepth: '色深',
    bitSuffix: n => `${n}位`,
    orientation: '方向',
    browser: '浏览器',
    os: '操作系统',
    language: '语言',
    cookies: 'Cookie',
    cookiesOn: '允许',
    cookiesOff: '已阻止',
    network: '网络',
    online: '在线',
    offline: '离线',
    timezone: '时区',
    cores: 'CPU逻辑核心',
    coresHint: '浏览器能用的线程数',
    countSuffix: n => `${n}个`,
    memory: '内存（约）',
    memoryValue: gb => `${gb}GB 以上`,
    memoryUnknown: '浏览器不提供这一项',
    memoryHint: '只有Chromium系的浏览器给这个值，而且是取整过的',
    touchPoints: '同时触摸点数',
    touchHint: '0表示不支持触摸',
    loading: '正在读取设备信息…',
    copy: '📋 全部复制',
    copied: '✅ 已复制',
    privacy1: '这里的一切都来自浏览器自己报出来的值，不会送到任何地方。',
    privacy2: '个人资料 — IP、位置、账号 — 既不收集也不显示。',
  },
  'zh-hant': {
    browsers: { edge: 'Edge', opera: 'Opera', samsung: '三星瀏覽器', whale: 'Whale', firefox: 'Firefox', chrome: 'Chrome', safari: 'Safari' },
    unknown: '未知',
    windows10or11: 'Windows 10 或 11',
    screenTitle: '顯示',
    browserTitle: '瀏覽器',
    hardwareTitle: '硬體',
    monitorRes: '螢幕解析度',
    monitorResHint: '系統報出來的邏輯解析度',
    windowSize: '瀏覽器視窗大小',
    workArea: '工作區',
    workAreaHint: '扣掉工作列之類的部分',
    dpr: '像素比（DPR）',
    dprHint: '2以上就是高密度（Retina）螢幕',
    realPixels: '估算的實際像素',
    colorDepth: '色深',
    bitSuffix: n => `${n}位元`,
    orientation: '方向',
    browser: '瀏覽器',
    os: '作業系統',
    language: '語言',
    cookies: 'Cookie',
    cookiesOn: '允許',
    cookiesOff: '已封鎖',
    network: '網路',
    online: '線上',
    offline: '離線',
    timezone: '時區',
    cores: 'CPU邏輯核心',
    coresHint: '瀏覽器能用的執行緒數',
    countSuffix: n => `${n}個`,
    memory: '記憶體（約）',
    memoryValue: gb => `${gb}GB 以上`,
    memoryUnknown: '瀏覽器不提供這一項',
    memoryHint: '只有Chromium系的瀏覽器給這個值，而且是取整過的',
    touchPoints: '同時觸摸點數',
    touchHint: '0表示不支援觸控',
    loading: '正在讀取裝置資訊…',
    copy: '📋 全部複製',
    copied: '✅ 已複製',
    privacy1: '這裡的一切都來自瀏覽器自己報出來的值，不會送到任何地方。',
    privacy2: '個人資料 — IP、位置、帳號 — 既不收集也不顯示。',
  },
};
