import type { DreamEntry } from './dream-data';

/**
 * 중국어 꿈해몽.
 *
 * 한국어 57종 중 돼지꿈=재물처럼 한국 특유의 상징은 옮겨봐야 통하지 않는다.
 * 낙하·치아·추격처럼 문화를 넘어 널리 보고되는 상징 20종만 골라 새로 썼다.
 *
 * 해석에 단정적인 예언을 담지 않는다 — 어느 쪽으로도 근거가 없고,
 * "이런 꿈은 이런 시기에 자주 보고된다"는 서술이 사실에 가깝다.
 */
export const DREAM_DATA_ZH: DreamEntry[] = [
  {
    id: 'falling',
    keyword: '坠落',
    emoji: '🪂',
    category: '动作' as DreamEntry['category'],
    luck: -1 as DreamEntry['luck'],
    summary: '象征生活中失去掌控感',
    detail: [
      '坠落的梦通常出现在有什么脱离掌控的时候 —— 工作、关系，或者一个不再由你决定的选择。',
      '关键细节是下坠过程中发生了什么。安全落地，或在落地前醒来，通常被解读为「这件事熬得过去」。',
      '这是最常见的梦之一，多出现在变动期，而不是在预示什么。',
    ],
  },
  {
    id: 'teeth',
    keyword: '掉牙',
    emoji: '🦷',
    category: '身体' as DreamEntry['category'],
    luck: -1 as DreamEntry['luck'],
    summary: '对外在形象的焦虑',
    detail: [
      '掉牙是全世界报告最多的梦之一，通常与外貌、衰老或「别人怎么看我」的担忧有关。',
      '它常出现在要被评价的事情之前 —— 演讲、面试、见新的人。',
      '也有传统把它读作家人的消息。焦虑这一解读更常见，通常也更贴切。',
    ],
  },
  {
    id: 'flying',
    keyword: '飞翔',
    emoji: '🕊️',
    category: '动作' as DreamEntry['category'],
    luck: 2 as DreamEntry['luck'],
    summary: '自由，或者对自由的渴望',
    detail: [
      '飞翔的梦被解读为一种释放感 —— 从某种束缚、角色，或一段沉重的时期里脱身。',
      '轻松地高飞是正面的形态。飞不高、或者根本离不了地，则指向还有什么在拉着你。',
      '人们常在难熬的时期结束时或刚结束后做这种梦。',
    ],
  },
  {
    id: 'chased',
    keyword: '被追赶',
    emoji: '🏃',
    category: '动作' as DreamEntry['category'],
    luck: -1 as DreamEntry['luck'],
    summary: '你正在回避的某件事',
    detail: [
      '被追赶通常被解读为回避 —— 一场对话、一个决定，或一种你一直在躲的情绪。',
      '追你的是什么，不如「你在跑」这件事本身重要。梦里转身面对它，常被说成是转折的那一刻。',
      '只要被回避的事没解决，这种梦就会反复出现，处理掉之后往往就停了。',
    ],
  },
  {
    id: 'water',
    keyword: '水',
    emoji: '🌊',
    category: '自然' as DreamEntry['category'],
    luck: 1 as DreamEntry['luck'],
    summary: '你情绪的状态',
    detail: [
      '水被解读为情绪，而水的状态就是解读本身。清澈平静的水意味着事情安定；浑浊或汹涌则相反。',
      '深水常与你还没完全正视的东西相连。在深水里觉得自在，是好兆头。',
      '洪水尤其容易出现在情绪积累得比消化速度更快的时候。',
    ],
  },
  {
    id: 'snake',
    keyword: '蛇',
    emoji: '🐍',
    category: '动物' as DreamEntry['category'],
    luck: 1 as DreamEntry['luck'],
    summary: '蜕变，或潜藏的担忧',
    detail: [
      '蛇同时带着两种解读：因为蜕皮而象征更新，也因为是蛇而象征威胁。适用哪一种，取决于梦里的感受。',
      '平静的蛇通常被读作正在进行的转变。有攻击性的蛇则指向你已经察觉、却还没说出口的东西。',
      '在不少传统里颜色很重要 —— 金蛇、白蛇的解读比暗色的蛇正面得多。',
    ],
  },
  {
    id: 'house',
    keyword: '房子',
    emoji: '🏠',
    category: '场所' as DreamEntry['category'],
    luck: 1 as DreamEntry['luck'],
    summary: '以建筑形式出现的你自己',
    detail: [
      '梦里的房子常被读作自己，每个房间对应生活的不同部分。',
      '发现一个自己不知道存在的房间，是被报告最多的变体之一，解读为发现了尚未使用的能力。',
      '房子失修通常指向有什么被忽略了，而不是关于房子本身。',
    ],
  },
  {
    id: 'death',
    keyword: '死亡',
    emoji: '⚰️',
    category: '人物' as DreamEntry['category'],
    luck: 0 as DreamEntry['luck'],
    summary: '一个结束，而不是预言',
    detail: [
      '关于死亡的梦，几乎在所有传统里都被读作结束与过渡，而不是字面上的警告。',
      '梦见自己死亡，通常被读作某个阶段的收尾 —— 一份工作、一段关系，或过去的某个自己。',
      '这类梦多出现在真实的人生转变期，所以感觉很重要，但字面解读并不是有用的那一种。',
    ],
  },
  {
    id: 'baby',
    keyword: '婴儿',
    emoji: '👶',
    category: '人物' as DreamEntry['category'],
    luck: 2 as DreamEntry['luck'],
    summary: '有什么新的正在开始',
    detail: [
      '婴儿被读作开始 —— 一个项目、一段关系，或刚刚起步的某种生活。',
      '轻松照顾婴儿是正面的形态。弄丢或忘记它，则指向某件新的事你没给够注意力。',
      '这种梦常见于真正承担新责任的时期，与是否有孩子无关。',
    ],
  },
  {
    id: 'money',
    keyword: '钱',
    emoji: '💰',
    category: '物品' as DreamEntry['category'],
    luck: 1 as DreamEntry['luck'],
    summary: '价值感与自我评价',
    detail: [
      '梦里的钱，更多关于你觉得自己值多少，而不是字面的财务。',
      '捡到钱与「意识到自己本来就有的东西」相连。丢钱则指向感到不被重视。',
      '各种传统在这里分歧很大，所以梦里的感受比任何固定含义都更值得参考。',
    ],
  },
  {
    id: 'exam',
    keyword: '考试',
    emoji: '📝',
    category: '情境' as DreamEntry['category'],
    luck: -1 as DreamEntry['luck'],
    summary: '觉得被检验或没准备好',
    detail: [
      '考试的梦 —— 没准备、迟到、走错考场 —— 是最常见的焦虑梦之一，往往毕业几十年后还会做。',
      '它们通常出现在要被评判的事情之前，而不是真的要考试之前。',
      '反复出现的版本，通常对应某个你觉得正在被评估的具体处境。',
    ],
  },
  {
    id: 'naked',
    keyword: '当众赤身',
    emoji: '🙈',
    category: '情境' as DreamEntry['category'],
    luck: -1 as DreamEntry['luck'],
    summary: '害怕被看见真实的自己',
    detail: [
      '当众赤身被解读为脆弱感 —— 担心自己身上的某些东西，会在你准备好之前被看见。',
      '梦里没人有反应是个常见细节，通常被读作「恐惧大于现实」。',
      '这类梦常出现在真正需要暴露自己的事情之前：新工作、公开演讲、一段变认真的关系。',
    ],
  },
  {
    id: 'fire',
    keyword: '火',
    emoji: '🔥',
    category: '自然' as DreamEntry['category'],
    luck: 0 as DreamEntry['luck'],
    summary: '强烈的能量 —— 或创造或毁灭',
    detail: [
      '火同时带着两种解读：一边是热情与驱动力，另一边是毁灭与愤怒。',
      '受控的火是正面的 —— 能量被用起来了。失控的火则指向有什么正在脱离你的掌握。',
      '在不少传统里，火尤其与财运和急速的变化相连。',
    ],
  },
  {
    id: 'lost',
    keyword: '迷路',
    emoji: '🧭',
    category: '情境' as DreamEntry['category'],
    luck: -1 as DreamEntry['luck'],
    summary: '对方向的不确定',
    detail: [
      '迷路被解读为对方向的不确定 —— 可能是工作上的，也可能是更广义的人生方向。',
      '熟悉的地方变得陌生是常见变体，通常指向某个在你脚下已经变了的处境。',
      '在梦里找到路，被报告为转折点的比例相当高。',
    ],
  },
  {
    id: 'cat',
    keyword: '猫',
    emoji: '🐱',
    category: '动物' as DreamEntry['category'],
    luck: 0 as DreamEntry['luck'],
    summary: '独立，以及你保留的私人空间',
    detail: [
      '猫通常被读作独立与直觉，有时也代表你留给自己的那部分。',
      '亲人的猫是正面的解读。有攻击性的猫，则常与某段有话没说开的关系相连。',
      '关于猫，各种传统的说法差异之大，几乎超过其他任何动物。',
    ],
  },
  {
    id: 'bird',
    keyword: '鸟',
    emoji: '🐦',
    category: '动物' as DreamEntry['category'],
    luck: 1 as DreamEntry['luck'],
    summary: '消息，或想去别处的心情',
    detail: [
      '鸟被广泛读作消息与自由，取决于它是飞来还是飞走。',
      '笼中鸟在各种传统里都是很强且一致的意象 —— 你身上有什么没被放出来。',
      '鸟群常与消息的到来相连，有时是来自远方的消息。',
    ],
  },
  {
    id: 'mountain',
    keyword: '山',
    emoji: '⛰️',
    category: '自然' as DreamEntry['category'],
    luck: 1 as DreamEntry['luck'],
    summary: '障碍，或者志向',
    detail: [
      '山被读作横在你面前的大东西 —— 可能是障碍，也可能是目标，往往两者都是。',
      '往上爬是正面的形态。站在山脚下动不了，则指向某件事让你觉得遥不可及。',
      '登顶是各种传统里解读最一致地正面的梦境意象之一。',
    ],
  },
  {
    id: 'mirror',
    keyword: '镜子',
    emoji: '🪞',
    category: '物品' as DreamEntry['category'],
    luck: 0 as DreamEntry['luck'],
    summary: '你如何看待自己',
    detail: [
      '镜子被读作自我认知 —— 你怎么看自己，而不是别人怎么看你。',
      '变形或看不清的倒影，通常与身份或方向上的不确定相连。',
      '打碎镜子在迷信里代表霉运，但在解梦里更多指向破碎的自我形象，而非厄运。',
    ],
  },
  {
    id: 'rain',
    keyword: '雨',
    emoji: '🌧️',
    category: '自然' as DreamEntry['category'],
    luck: 1 as DreamEntry['luck'],
    summary: '释放，以及之后到来的东西',
    detail: [
      '雨被读作释放与洗涤 —— 常出现在情绪沉重的时期之后，而不是之前。',
      '细雨是正面的解读。暴风雨则指向还没解决的东西。',
      '躲在屋檐下，还是站在雨里，是多数解读的关键细节。',
    ],
  },
  {
    id: 'road',
    keyword: '道路',
    emoji: '🛣️',
    category: '场所' as DreamEntry['category'],
    luck: 0 as DreamEntry['luck'],
    summary: '你正走的那条路',
    detail: [
      '道路被读作人生方向，岔路口代表你已经意识到、却可能在拖延的决定。',
      '前方清晰的路是直接的正面解读。被堵住或到头的路，则指向某个需要重新想的计划。',
      '和你同行的是谁，往往是信息量更大的细节。',
    ],
  },
];

export const DREAM_CATEGORIES_ZH = ['人物', '动作', '动物', '场所', '情境', '物品', '自然', '身体'];
