/**
 * 요리 도구 화면 문구의 세 언어 사전.
 *
 * 데이터 이름표는 lib/food-intl.ts, 계산은 lib/food.ts에 있다. 여기에는
 * 라벨·버튼·설명 문단만 둔다.
 */
import type { FoodLang } from './food-intl.ts';
export type { FoodLang };

export const MEASURE_UI: Record<FoodLang, {
  ingredient: string; modes: string[];
  cup: string; cupUnit: string; tbsp: string; tsp: string; weight: string;
  basedOn: (name: string, ml: number) => string;
  cupStandard: string; standards: string[];
  whyTitle: string; why: string; standardNote: (cupMl: number) => string;
}> = {
  ko: {
    ingredient: '재료', modes: ['계량도구 → 그램', '그램 → 계량도구'],
    cup: '컵', cupUnit: '컵', tbsp: '큰술', tsp: '작은술', weight: '무게',
    basedOn: (name, ml) => `${name} 기준 · 부피 ${ml}ml`,
    cupStandard: '컵 기준', standards: ['한국·유럽 200ml', '미국 240ml'],
    whyTitle: '왜 재료를 골라야 하나요',
    why: '같은 1컵이라도 밀가루는 120g, 설탕은 200g, 꿀은 284g입니다. 부피가 같아도 밀도가 다르기 때문입니다. ‘1컵 = 200g’으로 퉁치면 베이킹은 거의 실패합니다.',
    standardNote: cupMl => `지금은 1컵 ${cupMl}ml, 1큰술 15ml, 1작은술 5ml 기준입니다. 레시피 출처의 컵 기준과 맞는지 확인하세요.`,
  },
  en: {
    ingredient: 'Ingredient', modes: ['Measures → grams', 'Grams → measures'],
    cup: 'Cups', cupUnit: 'cup', tbsp: 'Tbsp', tsp: 'tsp', weight: 'Weight',
    basedOn: (name, ml) => `${name} · volume ${ml}ml`,
    cupStandard: 'Cup standard', standards: ['Metric 200ml', 'US 240ml'],
    whyTitle: 'Why the ingredient matters',
    why: 'A cup of flour is 120g, a cup of sugar is 200g, a cup of honey is 284g. Same volume, different density. Treat every cup as the same weight and your baking will almost certainly fail.',
    standardNote: cupMl => `Currently using a ${cupMl}ml cup, 15ml tablespoon and 5ml teaspoon. Check which cup your recipe was written with — the two differ by 20%.`,
  },
  es: {
    ingredient: 'Ingrediente', modes: ['Medidas → gramos', 'Gramos → medidas'],
    cup: 'Tazas', cupUnit: 'taza', tbsp: 'cda', tsp: 'cdta', weight: 'Peso',
    basedOn: (name, ml) => `${name} · volumen ${ml}ml`,
    cupStandard: 'Tipo de taza', standards: ['Métrica 200ml', 'Estadounidense 240ml'],
    whyTitle: 'Por qué importa el ingrediente',
    why: 'Una taza de harina son 120g, una de azúcar 200g, una de miel 284g. Mismo volumen, densidad distinta. Si tratas todas las tazas como el mismo peso, la repostería te va a fallar casi seguro.',
    standardNote: cupMl => `Ahora mismo se usa una taza de ${cupMl}ml, cucharada de 15ml y cucharadita de 5ml. Comprueba con qué taza se escribió tu receta — entre las dos hay un 20% de diferencia.`,
  },
  'pt-br': {
    ingredient: 'Ingrediente', modes: ['Medidas → gramas', 'Gramas → medidas'],
    cup: 'Xícaras', cupUnit: 'xícara', tbsp: 'c. sopa', tsp: 'c. chá', weight: 'Peso',
    basedOn: (name, ml) => `${name} · volume ${ml}ml`,
    cupStandard: 'Tipo de xícara', standards: ['Métrica 200ml', 'Americana 240ml'],
    whyTitle: 'Por que o ingrediente importa',
    why: 'Uma xícara de farinha dá 120g, uma de açúcar 200g, uma de mel 284g. Mesmo volume, densidade diferente. Se tratar toda xícara como o mesmo peso, a confeitaria vai dar errado quase sempre.',
    standardNote: cupMl => `Agora está usando xícara de ${cupMl}ml, colher de sopa de 15ml e de chá de 5ml. Veja com qual xícara sua receita foi escrita — entre as duas há 20% de diferença.`,
  },
  ja: {
    ingredient: '材料', modes: ['計量器具 → グラム', 'グラム → 計量器具'],
    cup: 'カップ', cupUnit: 'カップ', tbsp: '大さじ', tsp: '小さじ', weight: '重さ',
    basedOn: (name, ml) => `${name} · 体積 ${ml}ml`,
    cupStandard: 'カップの基準', standards: ['日本・欧州 200ml', '米国 240ml'],
    whyTitle: 'なぜ材料を選ぶ必要があるのか',
    why: '同じ1カップでも小麦粉は120g、砂糖は200g、はちみつは284gです。体積が同じでも比重が違うからです。「1カップ＝200g」で片づけると、お菓子作りはほぼ失敗します。',
    standardNote: cupMl => `いまは1カップ${cupMl}ml、大さじ15ml、小さじ5ml で計算しています。レシピがどのカップで書かれているか確認してください — 二つは20%違います。`,
  },
  de: {
    ingredient: 'Zutat', modes: ['Maße → Gramm', 'Gramm → Maße'],
    cup: 'Cups', cupUnit: 'Cup', tbsp: 'EL', tsp: 'TL', weight: 'Gewicht',
    basedOn: (name, ml) => `${name} · Volumen ${ml}ml`,
    cupStandard: 'Cup-Standard', standards: ['Metrisch 200ml', 'US 240ml'],
    whyTitle: 'Warum die Zutat entscheidet',
    why: 'Ein Cup Mehl sind 120g, ein Cup Zucker 200g, ein Cup Honig 284g. Gleiches Volumen, andere Dichte. Wenn du jeden Cup als gleiches Gewicht behandelst, geht das Backen fast sicher schief.',
    standardNote: cupMl => `Gerechnet wird derzeit mit einem Cup von ${cupMl}ml, 15ml Esslöffel und 5ml Teelöffel. Prüfe, mit welchem Cup dein Rezept geschrieben wurde — zwischen beiden liegen 20%.`,
  },
  fr: {
    ingredient: 'Ingrédient', modes: ['Mesures → grammes', 'Grammes → mesures'],
    cup: 'Tasses', cupUnit: 'tasse', tbsp: 'c. à s.', tsp: 'c. à c.', weight: 'Poids',
    basedOn: (name, ml) => `${name} · volume ${ml}ml`,
    cupStandard: 'Type de tasse', standards: ['Métrique 200ml', 'Américaine 240ml'],
    whyTitle: 'Pourquoi l’ingrédient compte',
    why: 'Une tasse de farine fait 120g, une de sucre 200g, une de miel 284g. Même volume, densité différente. Traite toutes les tasses comme le même poids et ta pâtisserie va presque sûrement rater.',
    standardNote: cupMl => `Le calcul utilise actuellement une tasse de ${cupMl}ml, une cuillère à soupe de 15ml et une cuillère à café de 5ml. Vérifie avec quelle tasse ta recette a été écrite — les deux diffèrent de 20%.`,
  },
  hi: {
    ingredient: 'सामग्री', modes: ['नाप → ग्राम', 'ग्राम → नाप'],
    cup: 'कप', cupUnit: 'कप', tbsp: 'बड़ा चम्मच', tsp: 'छोटा चम्मच', weight: 'वज़न',
    basedOn: (name, ml) => `${name} · मात्रा ${ml}ml`,
    cupStandard: 'कप का मानक', standards: ['मीट्रिक 200ml', 'अमेरिकी 240ml'],
    whyTitle: 'सामग्री चुनना क्यों ज़रूरी है',
    why: 'एक ही कप में आटा 120g, चीनी 200g और शहद 284g आता है। मात्रा वही, घनत्व अलग। हर कप को एक ही वज़न मानकर चलें तो बेकिंग लगभग तय रूप से बिगड़ती है।',
    standardNote: cupMl => `अभी ${cupMl}ml का कप, 15ml का बड़ा चम्मच और 5ml का छोटा चम्मच माना गया है। देख लें कि आपकी रेसिपी किस कप से लिखी गई है — दोनों में 20% का अंतर है।`,
  },
};

export const RECIPE_SCALE_UI: Record<FoodLang, {
  /** 곱하지 않고 그대로 둘 단위 — 온도·시간·인분 */
  keepUnits: RegExp;
  fromLabel: string; toLabel: string; servingUnit: string;
  scaleUp: (f: number) => string; scaleDown: (f: number) => string;
  pasteLabel: string; placeholder: string;
  resultLabel: (n: number) => string; copy: string; copied: string; empty: string;
  noteTitle: string; note: string;
}> = {
  ko: {
    keepUnits: /^(도|℃|°C|분|초|시간|인분|%|번|회|cm|mm)/,
    fromLabel: '원래 레시피', toLabel: '만들 양', servingUnit: '인분',
    scaleUp: f => `${f}배로 늘립니다`, scaleDown: f => `${f}배로 줄입니다`,
    pasteLabel: '레시피 붙여넣기',
    placeholder: '돼지고기 300g\n양파 1개\n간장 2큰술\n설탕 1/2큰술\n180도로 20분',
    resultLabel: n => `${n}인분 재료`, copy: '복사하기', copied: '✅ 복사했습니다',
    empty: '위에 레시피를 붙여 넣으세요',
    noteTitle: '온도와 시간은 바꾸지 않습니다',
    note: '‘180도로 20분’의 숫자까지 곱하면 오븐이 360도가 됩니다. 도·분·초·인분이 붙은 숫자는 그대로 둡니다. 다만 양이 두 배가 되면 익는 데 시간이 더 걸리므로, 오븐 요리는 시간을 조금 늘리고 중간에 확인하세요. 소금·향신료는 배율대로 넣으면 짜질 수 있어 조금 적게 시작하는 편이 안전합니다.',
  },
  en: {
    keepUnits: /^(°C|°F|℃|C\b|F\b|min|minute|minutes|sec|second|seconds|hour|hours|hr|serving|servings|%|cm|mm|inch|in\b)/i,
    fromLabel: 'Original recipe', toLabel: 'Making', servingUnit: 'servings',
    scaleUp: f => `scaling everything up ${f}×`, scaleDown: f => `scaling everything down to ${f}×`,
    pasteLabel: 'Paste the recipe',
    placeholder: '300g pork\n1 onion\n2 tbsp soy sauce\n1/2 tbsp sugar\n20 minutes at 180°C',
    resultLabel: n => `Ingredients for ${n}`, copy: 'Copy', copied: '✅ Copied',
    empty: 'Paste a recipe above',
    noteTitle: 'Temperatures and times are left alone',
    note: 'Multiply the numbers in ‘20 minutes at 180°C’ and you end up with a 360°C oven. Anything attached to a degree, a minute, a second or a serving count stays as it is. Do bear in mind that double the quantity takes longer to cook, so add a little time for anything in the oven and check partway. Salt and spices scaled exactly can come out too strong — start slightly under.',
  },
  es: {
    keepUnits: /^(°C|°F|℃|grados|grado|min|minuto|minutos|seg|segundo|segundos|hora|horas|h\b|ración|raciones|porción|porciones|%|cm|mm)/i,
    fromLabel: 'Receta original', toLabel: 'Vas a hacer', servingUnit: 'raciones',
    scaleUp: f => `se multiplica todo por ${f}`, scaleDown: f => `se reduce todo a ${f}×`,
    pasteLabel: 'Pega la receta',
    placeholder: '300g de cerdo\n1 cebolla\n2 cdas de salsa de soja\n1/2 cda de azúcar\n20 minutos a 180°C',
    resultLabel: n => `Ingredientes para ${n}`, copy: 'Copiar', copied: '✅ Copiado',
    empty: 'Pega una receta arriba',
    noteTitle: 'La temperatura y el tiempo no se tocan',
    note: 'Si multiplicas los números de ‘20 minutos a 180°C’ acabas con un horno a 360°C. Todo lo que va pegado a grados, minutos, segundos o número de raciones se queda igual. Ten en cuenta que el doble de cantidad tarda más en hacerse: añade algo de tiempo a lo que vaya al horno y comprueba a mitad. La sal y las especias escaladas al milímetro salen demasiado fuertes — empieza por debajo.',
  },
  'pt-br': {
    keepUnits: /^(°C|°F|℃|graus|grau|min|minuto|minutos|seg|segundo|segundos|hora|horas|h\b|porção|porções|%|cm|mm)/i,
    fromLabel: 'Receita original', toLabel: 'Você vai fazer', servingUnit: 'porções',
    scaleUp: f => `tudo multiplicado por ${f}`, scaleDown: f => `tudo reduzido para ${f}×`,
    pasteLabel: 'Cole a receita',
    placeholder: '300g de carne de porco\n1 cebola\n2 c. sopa de shoyu\n1/2 c. sopa de açúcar\n20 minutos a 180°C',
    resultLabel: n => `Ingredientes para ${n}`, copy: 'Copiar', copied: '✅ Copiado',
    empty: 'Cole uma receita acima',
    noteTitle: 'Temperatura e tempo não são mexidos',
    note: 'Se multiplicar os números de ‘20 minutos a 180°C’ você termina com um forno a 360°C. Tudo que vem junto de graus, minutos, segundos ou número de porções fica como está. Lembre que o dobro da quantidade leva mais tempo para assar: acrescente um pouco de tempo ao que for ao forno e confira no meio. Sal e temperos multiplicados na régua saem fortes demais — comece abaixo.',
  },
  ja: {
    keepUnits: /^(度|℃|°C|°F|分|秒|時間|人分|人前|%|cm|mm)/,
    fromLabel: '元のレシピ', toLabel: '作る量', servingUnit: '人分',
    scaleUp: f => `${f}倍に増やします`, scaleDown: f => `${f}倍に減らします`,
    pasteLabel: 'レシピを貼り付け',
    placeholder: '豚肉 300g\n玉ねぎ 1個\nしょうゆ 大さじ2\n砂糖 大さじ1/2\n180度で20分',
    resultLabel: n => `${n}人分の材料`, copy: 'コピー', copied: '✅ コピーしました',
    empty: '上にレシピを貼り付けてください',
    noteTitle: '温度と時間は変えません',
    note: '「180度で20分」の数字まで掛けると、オーブンが360度になってしまいます。度・分・秒・人分が付いた数字はそのままにします。ただし量が倍になると火が通るのに時間がかかるので、オーブン料理は時間を少し延ばして途中で確認してください。塩や香辛料は倍率どおりに入れると塩辛くなることがあるので、少なめから始めるほうが安全です。',
  },
  de: {
    keepUnits: /^(°C|°F|℃|Grad|Min|Minute|Minuten|Sek|Sekunde|Sekunden|Std|Stunde|Stunden|Portion|Portionen|%|cm|mm)/i,
    fromLabel: 'Originalrezept', toLabel: 'Du machst', servingUnit: 'Portionen',
    scaleUp: f => `alles um ${f}× erhöht`, scaleDown: f => `alles auf ${f}× verringert`,
    pasteLabel: 'Rezept einfügen',
    placeholder: '300g Schweinefleisch\n1 Zwiebel\n2 EL Sojasoße\n1/2 EL Zucker\n20 Minuten bei 180°C',
    resultLabel: n => `Zutaten für ${n}`, copy: 'Kopieren', copied: '✅ Kopiert',
    empty: 'Füge oben ein Rezept ein',
    noteTitle: 'Temperatur und Zeit bleiben unverändert',
    note: 'Multiplizierst du die Zahlen in ‘20 Minuten bei 180°C’, landest du bei einem 360°C-Ofen. Alles, was an Grad, Minuten, Sekunden oder Portionen hängt, bleibt stehen. Denk daran: die doppelte Menge braucht länger — gib bei allem im Ofen etwas Zeit dazu und schau zwischendurch nach. Salz und Gewürze exakt mitskaliert werden leicht zu kräftig; fang eher darunter an.',
  },
  fr: {
    keepUnits: /^(°C|°F|℃|degrés|degré|min|minute|minutes|sec|seconde|secondes|heure|heures|h\b|portion|portions|part|parts|%|cm|mm)/i,
    fromLabel: 'Recette d’origine', toLabel: 'Tu prépares', servingUnit: 'parts',
    scaleUp: f => `tout multiplié par ${f}`, scaleDown: f => `tout réduit à ${f}×`,
    pasteLabel: 'Colle la recette',
    placeholder: '300g de porc\n1 oignon\n2 c. à s. de sauce soja\n1/2 c. à s. de sucre\n20 minutes à 180°C',
    resultLabel: n => `Ingrédients pour ${n}`, copy: 'Copier', copied: '✅ Copié',
    empty: 'Colle une recette ci-dessus',
    noteTitle: 'Températures et temps ne sont pas touchés',
    note: 'Multiplie les nombres de ‘20 minutes à 180°C’ et tu obtiens un four à 360°C. Tout ce qui est rattaché à des degrés, des minutes, des secondes ou un nombre de parts reste tel quel. Garde en tête que le double de quantité met plus longtemps à cuire : ajoute un peu de temps pour tout ce qui va au four et vérifie à mi-cuisson. Le sel et les épices multipliés à l’identique ressortent trop forts — commence en dessous.',
  },
  hi: {
    keepUnits: /^(°C|°F|℃|डिग्री|मिनट|सेकंड|घंटा|घंटे|लोग|लोगों|व्यक्ति|%|cm|mm|min|sec|hour)/i,
    fromLabel: 'मूल रेसिपी', toLabel: 'आप बनाएँगे', servingUnit: 'लोगों के लिए',
    scaleUp: f => `सब कुछ ${f} गुना बढ़ाया जाएगा`, scaleDown: f => `सब कुछ ${f} गुना घटाया जाएगा`,
    pasteLabel: 'रेसिपी चिपकाएँ',
    placeholder: 'सूअर का मांस 300g\nप्याज़ 1\nसोया सॉस 2 बड़े चम्मच\nचीनी 1/2 बड़ा चम्मच\n180 डिग्री पर 20 मिनट',
    resultLabel: n => `${n} लोगों की सामग्री`, copy: 'कॉपी करें', copied: '✅ कॉपी हो गया',
    empty: 'ऊपर रेसिपी चिपकाएँ',
    noteTitle: 'तापमान और समय नहीं बदले जाते',
    note: '‘180 डिग्री पर 20 मिनट’ के अंक भी गुणा कर दें तो ओवन 360 डिग्री का हो जाएगा। डिग्री, मिनट, सेकंड या लोगों की संख्या से जुड़े अंक वैसे ही रहते हैं। ध्यान रखें कि मात्रा दोगुनी होने पर पकने में समय ज़्यादा लगता है, इसलिए ओवन वाली चीज़ों में समय थोड़ा बढ़ाइए और बीच में देख लीजिए। नमक और मसाले पूरे गुणक में डालने पर तेज़ हो जाते हैं — कम से शुरू करना सुरक्षित है।',
  },
};

export const SALT_UI: Record<FoodLang, {
  presets: string[]; presetNotes: string[];
  modes: string[]; water: string; targetPct: string; saltAdded: string;
  subSalt: string; subPct: string; saltWord: string;
  byTotalExact: (pct: number, g: number) => string; byTotalPct: (p: number) => string;
  presetTitle: string; note: string;
}> = {
  ko: {
    presets: ['겉절이·즉석', '배추 절이기', '장아찌', '염장'],
    presetNotes: ['살짝만 절일 때', '김장 기본', '오래 두고 먹을 때', '아주 오래 보관'],
    modes: ['소금량 구하기', '염도 구하기'],
    water: '물', targetPct: '원하는 염도', saltAdded: '넣은 소금',
    subSalt: '물 무게 기준 · 총량 기준으로는 아래 참고', subPct: '물 대비 / 총량 대비',
    saltWord: '소금',
    byTotalExact: (pct, g) => `총량(물+소금) 기준으로 정확히 ${pct}%를 맞추려면 ${g}g`,
    byTotalPct: p => `총량(물+소금) 기준으로는 ${p}%`,
    presetTitle: '용도별 권장 염도',
    note: '소금 종류에 따라 같은 부피라도 무게가 다릅니다. 굵은 소금은 알갱이 사이 공간이 많아 같은 컵에 담아도 가볍고, 맛소금은 첨가물이 있어 더 짜게 느껴집니다. 저울로 무게를 재는 편이 확실합니다.',
  },
  en: {
    presets: ['Quick pickle', 'Salting cabbage', 'Long pickle', 'Curing'],
    presetNotes: ['A light salting only', 'The kimchi standard', 'To keep for a while', 'For very long storage'],
    modes: ['Find the salt', 'Find the salinity'],
    water: 'Water', targetPct: 'Target salinity', saltAdded: 'Salt added',
    subSalt: 'By weight of water · see below for by total weight', subPct: 'Of water / of total',
    saltWord: 'Salt',
    byTotalExact: (pct, g) => `For exactly ${pct}% of the total (water + salt), use ${g}g`,
    byTotalPct: p => `${p}% of the total weight (water + salt)`,
    presetTitle: 'Suggested salinity by purpose',
    note: 'The same volume of different salts weighs a different amount. Coarse salt has air between the grains, so a cup of it weighs less, and table salt with additives tastes saltier. Weighing on a scale is the reliable way.',
  },
  es: {
    presets: ['Encurtido rápido', 'Salar col', 'Encurtido largo', 'Salazón'],
    presetNotes: ['Solo un salado ligero', 'El estándar del kimchi', 'Para guardar un tiempo', 'Para conservar mucho tiempo'],
    modes: ['Hallar la sal', 'Hallar la salinidad'],
    water: 'Agua', targetPct: 'Salinidad buscada', saltAdded: 'Sal añadida',
    subSalt: 'Sobre el peso del agua · más abajo, sobre el peso total', subPct: 'Del agua / del total',
    saltWord: 'Sal',
    byTotalExact: (pct, g) => `Para exactamente el ${pct}% del total (agua + sal), usa ${g}g`,
    byTotalPct: p => `${p}% del peso total (agua + sal)`,
    presetTitle: 'Salinidad recomendada según el uso',
    note: 'El mismo volumen de sales distintas pesa distinto. La sal gruesa tiene aire entre los granos, así que una taza pesa menos, y la sal de mesa con aditivos sabe más salada. Pesar en una balanza es lo fiable.',
  },
  'pt-br': {
    presets: ['Conserva rápida', 'Salgar repolho', 'Conserva longa', 'Salga'],
    presetNotes: ['Só uma salga leve', 'O padrão do kimchi', 'Para guardar um tempo', 'Para conservar por muito tempo'],
    modes: ['Achar o sal', 'Achar a salinidade'],
    water: 'Água', targetPct: 'Salinidade desejada', saltAdded: 'Sal colocado',
    subSalt: 'Sobre o peso da água · mais abaixo, sobre o peso total', subPct: 'Da água / do total',
    saltWord: 'Sal',
    byTotalExact: (pct, g) => `Para exatamente ${pct}% do total (água + sal), use ${g}g`,
    byTotalPct: p => `${p}% do peso total (água + sal)`,
    presetTitle: 'Salinidade sugerida por finalidade',
    note: 'O mesmo volume de sais diferentes pesa diferente. O sal grosso tem ar entre os grãos, então uma xícara pesa menos, e o sal refinado com aditivos parece mais salgado. Pesar na balança é o jeito confiável.',
  },
  ja: {
    presets: ['浅漬け・即席', '白菜の塩漬け', '漬けもの', '塩蔵'],
    presetNotes: ['軽く漬けるとき', 'キムチの基本', '長めに置いて食べるとき', 'かなり長く保存する'],
    modes: ['塩の量を求める', '塩分濃度を求める'],
    water: '水', targetPct: '目指す塩分濃度', saltAdded: '入れた塩',
    subSalt: '水の重さ基準 · 総量基準は下を参照', subPct: '水に対して / 総量に対して',
    saltWord: '塩',
    byTotalExact: (pct, g) => `総量（水＋塩）基準でちょうど${pct}%にするには ${g}g`,
    byTotalPct: p => `総量（水＋塩）基準では ${p}%`,
    presetTitle: '用途ごとのおすすめ濃度',
    note: '塩の種類によって、同じ体積でも重さが違います。粗塩は粒のあいだに空間が多いので同じカップでも軽く、食卓塩は添加物があってより塩辛く感じます。はかりで重さを量るほうが確実です。',
  },
  de: {
    presets: ['Schnell einlegen', 'Kohl salzen', 'Lange einlegen', 'Einsalzen'],
    presetNotes: ['Nur leicht salzen', 'Der Kimchi-Standard', 'Um es eine Weile zu halten', 'Für sehr lange Lagerung'],
    modes: ['Salzmenge finden', 'Salzgehalt finden'],
    water: 'Wasser', targetPct: 'Zielsalzgehalt', saltAdded: 'Zugegebenes Salz',
    subSalt: 'Bezogen auf das Wassergewicht · unten bezogen aufs Gesamtgewicht', subPct: 'Vom Wasser / vom Gesamten',
    saltWord: 'Salz',
    byTotalExact: (pct, g) => `Für genau ${pct}% vom Gesamten (Wasser + Salz) nimm ${g}g`,
    byTotalPct: p => `${p}% vom Gesamtgewicht (Wasser + Salz)`,
    presetTitle: 'Empfohlener Salzgehalt je Zweck',
    note: 'Dasselbe Volumen verschiedener Salze wiegt unterschiedlich. Grobes Salz hat Luft zwischen den Körnern, ein Cup davon wiegt also weniger, und Tafelsalz mit Zusätzen schmeckt salziger. Auf der Waage abzuwiegen ist der verlässliche Weg.',
  },
  fr: {
    presets: ['Conserve rapide', 'Saler du chou', 'Conserve longue', 'Salaison'],
    presetNotes: ['Un salage léger seulement', 'Le standard du kimchi', 'Pour garder un moment', 'Pour une très longue conservation'],
    modes: ['Trouver le sel', 'Trouver la salinité'],
    water: 'Eau', targetPct: 'Salinité visée', saltAdded: 'Sel ajouté',
    subSalt: 'Sur le poids de l’eau · plus bas, sur le poids total', subPct: 'De l’eau / du total',
    saltWord: 'Sel',
    byTotalExact: (pct, g) => `Pour exactement ${pct}% du total (eau + sel), utilise ${g}g`,
    byTotalPct: p => `${p}% du poids total (eau + sel)`,
    presetTitle: 'Salinité conseillée selon l’usage',
    note: 'Le même volume de sels différents ne pèse pas pareil. Le gros sel a de l’air entre les grains, donc une tasse pèse moins, et le sel de table avec additifs paraît plus salé. Peser sur une balance reste la méthode sûre.',
  },
  hi: {
    presets: ['झटपट अचार', 'पत्तागोभी नमकाना', 'लंबा अचार', 'नमक में रखना'],
    presetNotes: ['बस हल्का नमकाना हो तो', 'किमची का मानक', 'कुछ समय रखकर खाना हो तो', 'बहुत लंबे भंडारण के लिए'],
    modes: ['नमक की मात्रा निकालें', 'नमक का प्रतिशत निकालें'],
    water: 'पानी', targetPct: 'चाहा गया प्रतिशत', saltAdded: 'डाला गया नमक',
    subSalt: 'पानी के वज़न पर · कुल वज़न पर नीचे देखें', subPct: 'पानी पर / कुल पर',
    saltWord: 'नमक',
    byTotalExact: (pct, g) => `कुल वज़न (पानी + नमक) पर ठीक ${pct}% के लिए ${g}g`,
    byTotalPct: p => `कुल वज़न (पानी + नमक) पर ${p}%`,
    presetTitle: 'काम के हिसाब से सुझाया प्रतिशत',
    note: 'अलग-अलग नमक की एक ही मात्रा का वज़न अलग होता है। मोटे नमक के दानों के बीच हवा रहती है, इसलिए एक कप हल्का पड़ता है, और मिलावट वाला बारीक नमक ज़्यादा नमकीन लगता है। तराज़ू से वज़न करना ही पक्का तरीका है।',
  },
};

export const OVEN_UI: Record<FoodLang, {
  modes: string[]; temp: string; time: string; minUnit: string;
  gasMarkSub: (mark: string, min: number) => string;
  celsius: string; fahrenheit: string; gasMark: string;
  airTitle: string; airValue: (c: number, m: number) => string; airNote: string;
  presetTitle: string; note: string;
}> = {
  ko: {
    modes: ['섭씨(℃)로 입력', '화씨(°F)로 입력'],
    temp: '오븐 온도', time: '굽는 시간', minUnit: '분',
    gasMarkSub: (mark, min) => `가스마크 ${mark} · ${min}분`,
    celsius: '섭씨', fahrenheit: '화씨', gasMark: '가스마크',
    airTitle: '에어프라이어로 만든다면', airValue: (c, m) => `${c}℃ · ${m}분`,
    airNote: '온도를 20도 낮추고 시간을 20% 줄인 값입니다. 뜨거운 바람이 재료에 직접 닿아 같은 온도라도 훨씬 빨리 익기 때문입니다. 중간에 한 번 열어 확인하는 편이 안전합니다.',
    presetTitle: '자주 쓰는 온도',
    note: '가정용 오븐은 표시 온도와 실제 온도가 20도까지 차이 나기도 합니다. 자주 쓰는 오븐이라면 오븐 온도계를 하나 두고 실제 온도를 확인해 보세요. 예열은 표시등이 꺼진 뒤에도 5분쯤 더 기다리는 편이 확실합니다.',
  },
  en: {
    modes: ['Enter °C', 'Enter °F'],
    temp: 'Oven temperature', time: 'Bake time', minUnit: 'min',
    gasMarkSub: (mark, min) => `Gas mark ${mark} · ${min} min`,
    celsius: 'Celsius', fahrenheit: 'Fahrenheit', gasMark: 'Gas mark',
    airTitle: 'If you are using an air fryer', airValue: (c, m) => `${c}°C · ${m} min`,
    airNote: 'That is 20°C lower and 20% less time. Hot air hits the food directly, so it cooks much faster at the same temperature. Open it once partway to check.',
    presetTitle: 'Common temperatures',
    note: 'A home oven can be up to 20°C away from what the dial says. If it is an oven you use often, put a thermometer in it and find out. For preheating, waiting another five minutes after the light goes out is the safer bet.',
  },
  es: {
    modes: ['Introducir °C', 'Introducir °F'],
    temp: 'Temperatura del horno', time: 'Tiempo de horno', minUnit: 'min',
    gasMarkSub: (mark, min) => `Número de gas ${mark} · ${min} min`,
    celsius: 'Centígrados', fahrenheit: 'Fahrenheit', gasMark: 'Número de gas',
    airTitle: 'Si lo haces en la freidora de aire', airValue: (c, m) => `${c}°C · ${m} min`,
    airNote: 'Son 20°C menos y un 20% menos de tiempo. El aire caliente da directamente en la comida, así que a la misma temperatura se hace mucho antes. Ábrela una vez a mitad para comprobar.',
    presetTitle: 'Temperaturas más usadas',
    note: 'Un horno doméstico puede estar hasta 20°C lejos de lo que marca el mando. Si es un horno que usas a menudo, mete un termómetro y averígualo. Para el precalentado, esperar cinco minutos más después de que se apague la luz es la apuesta segura.',
  },
  'pt-br': {
    modes: ['Digitar °C', 'Digitar °F'],
    temp: 'Temperatura do forno', time: 'Tempo de forno', minUnit: 'min',
    gasMarkSub: (mark, min) => `Número do gás ${mark} · ${min} min`,
    celsius: 'Celsius', fahrenheit: 'Fahrenheit', gasMark: 'Número do gás',
    airTitle: 'Se for fazer na air fryer', airValue: (c, m) => `${c}°C · ${m} min`,
    airNote: 'São 20°C menos e 20% menos tempo. O ar quente bate direto na comida, então na mesma temperatura ela assa muito mais rápido. Abra uma vez no meio para conferir.',
    presetTitle: 'Temperaturas mais usadas',
    note: 'Um forno doméstico pode estar até 20°C longe do que o botão indica. Se for um forno que você usa muito, coloque um termômetro e descubra. No preaquecimento, esperar mais cinco minutos depois que a luz apaga é a aposta segura.',
  },
  ja: {
    modes: ['摂氏（℃）で入力', '華氏（°F）で入力'],
    temp: 'オーブンの温度', time: '焼く時間', minUnit: '分',
    gasMarkSub: (mark, min) => `ガスマーク ${mark} · ${min}分`,
    celsius: '摂氏', fahrenheit: '華氏', gasMark: 'ガスマーク',
    airTitle: 'エアフライヤーで作るなら', airValue: (c, m) => `${c}℃ · ${m}分`,
    airNote: '温度を20度下げ、時間を20%減らした値です。熱い風が食材に直接当たるので、同じ温度でもずっと早く火が通ります。途中で一度開けて確認するほうが安全です。',
    presetTitle: 'よく使う温度',
    note: '家庭用オーブンは表示温度と実際の温度が20度ずれることもあります。よく使うオーブンなら温度計を一つ入れて実際の温度を確かめてみてください。予熱は表示ランプが消えたあと5分ほど待つほうが確実です。',
  },
  de: {
    modes: ['°C eingeben', '°F eingeben'],
    temp: 'Ofentemperatur', time: 'Backzeit', minUnit: 'Min.',
    gasMarkSub: (mark, min) => `Gasstufe ${mark} · ${min} Min.`,
    celsius: 'Celsius', fahrenheit: 'Fahrenheit', gasMark: 'Gasstufe',
    airTitle: 'Wenn du die Heißluftfritteuse nimmst', airValue: (c, m) => `${c}°C · ${m} Min.`,
    airNote: 'Das sind 20°C weniger und 20% weniger Zeit. Die heiße Luft trifft das Essen direkt, deshalb gart es bei gleicher Temperatur viel schneller. Öffne einmal zwischendurch zum Nachsehen.',
    presetTitle: 'Gängige Temperaturen',
    note: 'Ein Haushaltsofen kann bis zu 20°C von der Anzeige abweichen. Wenn du diesen Ofen oft benutzt, leg ein Thermometer hinein und finde es heraus. Beim Vorheizen ist es sicherer, nach dem Ausgehen der Lampe noch fünf Minuten zu warten.',
  },
  fr: {
    modes: ['Saisir en °C', 'Saisir en °F'],
    temp: 'Température du four', time: 'Temps de cuisson', minUnit: 'min',
    gasMarkSub: (mark, min) => `Thermostat ${mark} · ${min} min`,
    celsius: 'Celsius', fahrenheit: 'Fahrenheit', gasMark: 'Thermostat',
    airTitle: 'Si tu passes à l’airfryer', airValue: (c, m) => `${c}°C · ${m} min`,
    airNote: 'C’est 20°C de moins et 20% de temps en moins. L’air chaud frappe directement les aliments, donc à température égale ça cuit bien plus vite. Ouvre une fois à mi-cuisson pour vérifier.',
    presetTitle: 'Températures courantes',
    note: 'Un four domestique peut s’écarter de 20°C de ce qu’affiche le bouton. Si c’est un four que tu utilises souvent, mets-y un thermomètre et vois ce qu’il en est. Pour le préchauffage, attendre cinq minutes de plus après l’extinction du voyant est le choix sûr.',
  },
  hi: {
    modes: ['°C में लिखें', '°F में लिखें'],
    temp: 'ओवन का तापमान', time: 'बेक करने का समय', minUnit: 'मिनट',
    gasMarkSub: (mark, min) => `गैस मार्क ${mark} · ${min} मिनट`,
    celsius: 'सेल्सियस', fahrenheit: 'फ़ारेनहाइट', gasMark: 'गैस मार्क',
    airTitle: 'एयर फ़्रायर में बनाना हो तो', airValue: (c, m) => `${c}°C · ${m} मिनट`,
    airNote: 'यह तापमान 20°C कम और समय 20% कम किया हुआ मान है। गरम हवा सीधे खाने पर पड़ती है, इसलिए उसी तापमान पर बहुत जल्दी पक जाता है। बीच में एक बार खोलकर देख लेना सुरक्षित है।',
    presetTitle: 'आम तापमान',
    note: 'घरेलू ओवन में दिखाया और असली तापमान 20°C तक अलग हो सकता है। जो ओवन रोज़ चलाते हैं उसमें एक थर्मामीटर रखकर असली तापमान देख लें। प्री-हीट में बत्ती बुझने के बाद भी पाँच मिनट और रुकना पक्का रहता है।',
  },
};

export const STEAK_UI: Record<FoodLang, {
  finalCenter: string; pullAt: (name: string) => string; afterRest: (t: number) => string;
  thickness: string; perSide: string; aboutMin: (m: number) => string;
  restTime: string; minSuffix: (m: number) => string; pullTemp: string;
  whyTitle: string; why: string; note: string;
}> = {
  ko: {
    finalCenter: '최종 중심', pullAt: name => `${name} — 불에서 꺼낼 때`,
    afterRest: t => `휴지 후 ${t}℃가 됩니다`,
    thickness: '고기 두께', perSide: '한 면 굽기', aboutMin: m => `약 ${m}분`,
    restTime: '휴지 시간', minSuffix: m => `${m}분`, pullTemp: '꺼내는 온도',
    whyTitle: '왜 목표보다 낮게 꺼내나요',
    why: '불에서 내린 뒤에도 겉의 열이 안으로 퍼지며 중심 온도가 3~5도 더 오릅니다. 목표 온도에서 꺼내면 한 단계 더 익은 고기가 됩니다. 꺼낸 뒤 두께의 두 배쯤 되는 시간만큼 쉬게 두면 육즙이 고기 전체로 퍼져 썰었을 때 흐르지 않습니다.',
    note: '굽는 시간은 팬 온도·고기 온도·기름 양에 따라 크게 달라지는 어림값입니다. 정확히 하려면 심부 온도계를 쓰세요. 다진 고기와 가금류는 식중독 위험 때문에 속까지 완전히 익혀야 합니다.',
  },
  en: {
    finalCenter: 'Final centre', pullAt: name => `${name} — pull it off the heat at`,
    afterRest: t => `It reaches ${t}°C after resting`,
    thickness: 'Thickness', perSide: 'Per side', aboutMin: m => `about ${m} min`,
    restTime: 'Rest', minSuffix: m => `${m} min`, pullTemp: 'Pull temperature',
    whyTitle: 'Why pull it below the target',
    why: 'Heat from the surface keeps moving inward after it leaves the pan, and the centre climbs another 3–5°C. Pull it at the target and you get meat one level more done than you wanted. Rest it for roughly twice the thickness in minutes and the juices redistribute, so they do not run out when you cut.',
    note: 'Cooking times are rough — pan temperature, meat temperature and the amount of oil all change them a lot. Use a probe thermometer if you want it exact. Minced meat and poultry must be cooked all the way through because of the food poisoning risk.',
  },
  es: {
    finalCenter: 'Centro final', pullAt: name => `${name} — sácalo del fuego a`,
    afterRest: t => `Llega a ${t}°C tras el reposo`,
    thickness: 'Grosor', perSide: 'Por cada lado', aboutMin: m => `unos ${m} min`,
    restTime: 'Reposo', minSuffix: m => `${m} min`, pullTemp: 'Temperatura de retirada',
    whyTitle: 'Por qué sacarlo antes de la temperatura objetivo',
    why: 'El calor de la superficie sigue avanzando hacia dentro después de salir de la sartén, y el centro sube otros 3–5°C. Si lo sacas al objetivo, te queda un punto más hecho de lo que querías. Déjalo reposar aproximadamente el doble de minutos que centímetros de grosor y los jugos se reparten, así no se escapan al cortar.',
    note: 'Los tiempos son aproximados: la temperatura de la sartén, la de la carne y la cantidad de aceite los cambian mucho. Usa un termómetro de sonda si lo quieres exacto. La carne picada y las aves hay que hacerlas del todo por el riesgo de intoxicación.',
  },
  'pt-br': {
    finalCenter: 'Centro final', pullAt: name => `${name} — tire do fogo a`,
    afterRest: t => `Chega a ${t}°C depois do descanso`,
    thickness: 'Espessura', perSide: 'De cada lado', aboutMin: m => `cerca de ${m} min`,
    restTime: 'Descanso', minSuffix: m => `${m} min`, pullTemp: 'Temperatura de retirada',
    whyTitle: 'Por que tirar antes da temperatura-alvo',
    why: 'O calor da superfície continua avançando para dentro depois de sair da frigideira, e o centro sobe outros 3–5°C. Se tirar no alvo, você acaba com um ponto além do que queria. Deixe descansar mais ou menos o dobro de minutos em relação aos centímetros de espessura e os sucos se distribuem, então não escorrem ao cortar.',
    note: 'Os tempos são aproximados: temperatura da frigideira, da carne e quantidade de óleo mudam tudo bastante. Use um termômetro de sonda se quiser exato. Carne moída e aves precisam ser cozidas por completo pelo risco de intoxicação.',
  },
  ja: {
    finalCenter: '最終の中心温度', pullAt: name => `${name} — 火から下ろすとき`,
    afterRest: t => `休ませたあと ${t}℃ になります`,
    thickness: '肉の厚み', perSide: '片面を焼く時間', aboutMin: m => `約${m}分`,
    restTime: '休ませる時間', minSuffix: m => `${m}分`, pullTemp: '下ろす温度',
    whyTitle: 'なぜ目標より低い温度で下ろすのか',
    why: '火から下ろしたあとも表面の熱が中へ伝わり、中心温度が3〜5度さらに上がります。目標温度で下ろすと、一段上の焼き加減になってしまいます。下ろしてから厚み（cm）の倍くらいの分数だけ休ませると、肉汁が全体に広がって切ったときに流れ出しません。',
    note: '焼き時間はフライパンの温度・肉の温度・油の量で大きく変わる目安です。正確にしたいなら中心温度計を使ってください。ひき肉と鶏肉は食中毒の危険があるので、中まで完全に火を通す必要があります。',
  },
  de: {
    finalCenter: 'Endgültige Kerntemperatur', pullAt: name => `${name} — vom Feuer nehmen bei`,
    afterRest: t => `Nach dem Ruhen erreicht es ${t}°C`,
    thickness: 'Dicke', perSide: 'Pro Seite', aboutMin: m => `etwa ${m} Min.`,
    restTime: 'Ruhen', minSuffix: m => `${m} Min.`, pullTemp: 'Entnahmetemperatur',
    whyTitle: 'Warum unter der Zieltemperatur herausnehmen',
    why: 'Die Hitze von der Oberfläche wandert nach der Pfanne weiter nach innen, und die Kerntemperatur steigt noch um 3–5°C. Nimmst du es bei der Zieltemperatur heraus, bekommst du eine Garstufe mehr als gewollt. Lass es etwa doppelt so viele Minuten ruhen, wie es Zentimeter dick ist — dann verteilt sich der Saft und läuft beim Schneiden nicht aus.',
    note: 'Die Garzeiten sind Näherungswerte: Pfannentemperatur, Fleischtemperatur und Ölmenge verändern sie erheblich. Nimm ein Einstichthermometer, wenn du es genau willst. Hackfleisch und Geflügel müssen wegen der Vergiftungsgefahr vollständig durchgegart werden.',
  },
  fr: {
    finalCenter: 'Température à cœur finale', pullAt: name => `${name} — sors-la du feu à`,
    afterRest: t => `Elle atteint ${t}°C après le repos`,
    thickness: 'Épaisseur', perSide: 'Par face', aboutMin: m => `environ ${m} min`,
    restTime: 'Repos', minSuffix: m => `${m} min`, pullTemp: 'Température de sortie',
    whyTitle: 'Pourquoi la sortir sous la température visée',
    why: 'La chaleur de la surface continue de progresser vers l’intérieur après la poêle, et le cœur grimpe encore de 3 à 5°C. Si tu la sors à la température visée, tu obtiens une cuisson de plus que voulue. Laisse-la reposer environ deux fois plus de minutes qu’elle a de centimètres d’épaisseur : les jus se répartissent et ne s’échappent pas à la découpe.',
    note: 'Les temps sont approximatifs : température de la poêle, de la viande et quantité d’huile les changent beaucoup. Utilise une sonde si tu veux du précis. La viande hachée et les volailles doivent être cuites à cœur à cause du risque d’intoxication.',
  },
  hi: {
    finalCenter: 'अंतिम भीतरी तापमान', pullAt: name => `${name} — आँच से उतारते समय`,
    afterRest: t => `आराम देने के बाद ${t}°C हो जाएगा`,
    thickness: 'मांस की मोटाई', perSide: 'हर तरफ़', aboutMin: m => `लगभग ${m} मिनट`,
    restTime: 'आराम का समय', minSuffix: m => `${m} मिनट`, pullTemp: 'उतारने का तापमान',
    whyTitle: 'लक्ष्य से कम पर क्यों उतारें',
    why: 'आँच से उतारने के बाद भी बाहरी गर्मी भीतर फैलती रहती है और भीतरी तापमान 3–5 डिग्री और चढ़ जाता है। लक्ष्य तापमान पर उतारें तो एक स्तर ज़्यादा पका मांस मिलता है। उतारने के बाद मोटाई (सेंटीमीटर) के दोगुने मिनट आराम देने से रस पूरे मांस में फैल जाता है और काटते समय बहता नहीं।',
    note: 'पकाने का समय तवे के तापमान, मांस के तापमान और तेल की मात्रा से बहुत बदलता है — यह मोटा अंदाज़ा है। ठीक-ठीक चाहिए तो भीतरी तापमान मापने वाला थर्मामीटर लें। कीमा और मुर्गी को खाद्य विषाक्तता के जोखिम के कारण भीतर तक पूरा पकाना ज़रूरी है।',
  },
};

export const RICE_UI: Record<FoodLang, {
  grains: string[]; grainNotes: string[]; soaks: string[];
  textures: string[]; riceCups: string; cupUnit: string;
  grainTitle: string; textureTitle: string;
  ratioSub: (ratio: number, cups: number) => string; waterWord: string;
  riceLabel: string; waterLabel: string; soakLabel: string;
  tipTitle: (grain: string) => string; knuckle: string; rinseNote: string;
  waterTimes: (r: number) => string;
}> = {
  ko: {
    grains: ['백미', '현미', '잡곡'],
    grainNotes: ['햅쌀은 1.1, 묵은쌀은 1.3', '겨층이 물을 잘 안 먹습니다', '콩은 따로 더 불리세요'],
    soaks: ['30분', '2시간 이상', '1시간'],
    textures: ['고슬', '보통', '진밥'],
    riceCups: '쌀 (계량컵)', cupUnit: '컵',
    grainTitle: '쌀 종류', textureTitle: '밥의 질기',
    ratioSub: (ratio, cups) => `쌀 : 물 = 1 : ${ratio} · 물 ${cups}컵`, waterWord: '물',
    riceLabel: '쌀', waterLabel: '물', soakLabel: '불리는 시간',
    tipTitle: grain => `${grain} 요령`,
    knuckle: '손등 기준으로는 쌀을 평평하게 고른 뒤 손등이 잠길 정도(약 1.5cm)가 백미 보통입니다. 다만 냄비 지름에 따라 크게 달라지므로, 같은 냄비를 쓸 때만 믿을 만한 기준입니다.',
    rinseNote: '쌀을 씻은 뒤 체에 밭쳐 물기를 빼고 재야 정확합니다. 젖은 쌀은 이미 물을 먹은 상태입니다.',
    waterTimes: r => `물 ${r}배`,
  },
  en: {
    grains: ['White rice', 'Brown rice', 'Mixed grain'],
    grainNotes: ['1.1 for new-crop rice, 1.3 for older rice', 'The bran layer resists water', 'Soak any beans separately, for longer'],
    soaks: ['30 min', '2 hours or more', '1 hour'],
    textures: ['Firm', 'Normal', 'Soft'],
    riceCups: 'Rice (cups)', cupUnit: 'cups',
    grainTitle: 'Type of rice', textureTitle: 'How soft you want it',
    ratioSub: (ratio, cups) => `rice : water = 1 : ${ratio} · ${cups} cups of water`, waterWord: 'Water',
    riceLabel: 'Rice', waterLabel: 'Water', soakLabel: 'Soak',
    tipTitle: grain => `${grain} — how to get it right`,
    knuckle: 'By the knuckle method, level the rice out and add water until it just covers your knuckle, about 1.5cm — that is normal white rice. It depends heavily on the diameter of the pot, so it is only reliable when you always use the same one.',
    rinseNote: 'Rinse the rice, drain it in a sieve, then measure — wet rice has already taken on water.',
    waterTimes: r => `${r}× water`,
  },
  es: {
    grains: ['Arroz blanco', 'Arroz integral', 'Mezcla de cereales'],
    grainNotes: ['1,1 para arroz nuevo, 1,3 para arroz viejo', 'La capa de salvado repele el agua', 'Las legumbres se ponen a remojo aparte, más tiempo'],
    soaks: ['30 min', '2 horas o más', '1 hora'],
    textures: ['Suelto', 'Normal', 'Blando'],
    riceCups: 'Arroz (tazas)', cupUnit: 'tazas',
    grainTitle: 'Tipo de arroz', textureTitle: 'Cómo lo quieres',
    ratioSub: (ratio, cups) => `arroz : agua = 1 : ${ratio} · ${cups} tazas de agua`, waterWord: 'Agua',
    riceLabel: 'Arroz', waterLabel: 'Agua', soakLabel: 'Remojo',
    tipTitle: grain => `${grain} — cómo acertar`,
    knuckle: 'Con el método del nudillo, alisa el arroz y añade agua hasta que cubra justo el nudillo, unos 1,5cm — ese es el arroz blanco normal. Depende mucho del diámetro de la olla, así que solo es fiable si siempre usas la misma.',
    rinseNote: 'Lava el arroz, escúrrelo en un colador y luego mídelo — el arroz mojado ya ha absorbido agua.',
    waterTimes: r => `agua ×${r}`,
  },
  'pt-br': {
    grains: ['Arroz branco', 'Arroz integral', 'Mistura de grãos'],
    grainNotes: ['1,1 para arroz novo, 1,3 para arroz velho', 'A camada de farelo resiste à água', 'Deixe os grãos duros de molho à parte, por mais tempo'],
    soaks: ['30 min', '2 horas ou mais', '1 hora'],
    textures: ['Soltinho', 'Normal', 'Macio'],
    riceCups: 'Arroz (xícaras)', cupUnit: 'xícaras',
    grainTitle: 'Tipo de arroz', textureTitle: 'Como você quer',
    ratioSub: (ratio, cups) => `arroz : água = 1 : ${ratio} · ${cups} xícaras de água`, waterWord: 'Água',
    riceLabel: 'Arroz', waterLabel: 'Água', soakLabel: 'De molho',
    tipTitle: grain => `${grain} — como acertar`,
    knuckle: 'Pelo método do dedo, nivele o arroz e coloque água até cobrir a primeira junta, mais ou menos 1,5cm — esse é o arroz branco normal. Depende muito do diâmetro da panela, então só é confiável se você sempre usar a mesma.',
    rinseNote: 'Lave o arroz, escorra na peneira e só então meça — arroz molhado já absorveu água.',
    waterTimes: r => `água ×${r}`,
  },
  ja: {
    grains: ['白米', '玄米', '雑穀米'],
    grainNotes: ['新米は1.1、古米は1.3', 'ぬか層が水を吸いにくいです', '豆は別に長めに浸してください'],
    soaks: ['30分', '2時間以上', '1時間'],
    textures: ['かため', 'ふつう', 'やわらかめ'],
    riceCups: '米（計量カップ）', cupUnit: 'カップ',
    grainTitle: '米の種類', textureTitle: 'ご飯のかたさ',
    ratioSub: (ratio, cups) => `米 : 水 = 1 : ${ratio} · 水 ${cups}カップ`, waterWord: '水',
    riceLabel: '米', waterLabel: '水', soakLabel: '浸水時間',
    tipTitle: grain => `${grain}のこつ`,
    knuckle: '指の関節で測るなら、米を平らにならしてから手の甲がちょうど浸かるくらい（約1.5cm）が白米のふつうです。ただし鍋の直径で大きく変わるので、同じ鍋を使うときだけ信頼できる目安です。',
    rinseNote: '米を洗ったらざるに上げて水を切ってから量ると正確です。濡れた米はすでに水を吸っています。',
    waterTimes: r => `水 ${r}倍`,
  },
  de: {
    grains: ['Weißer Reis', 'Vollkornreis', 'Mischgetreide'],
    grainNotes: ['1,1 bei frischem, 1,3 bei älterem Reis', 'Die Kleieschicht nimmt Wasser schlecht auf', 'Hülsenfrüchte separat und länger einweichen'],
    soaks: ['30 Min.', '2 Stunden oder mehr', '1 Stunde'],
    textures: ['Körnig', 'Normal', 'Weich'],
    riceCups: 'Reis (Cups)', cupUnit: 'Cups',
    grainTitle: 'Reissorte', textureTitle: 'Wie du ihn magst',
    ratioSub: (ratio, cups) => `Reis : Wasser = 1 : ${ratio} · ${cups} Cups Wasser`, waterWord: 'Wasser',
    riceLabel: 'Reis', waterLabel: 'Wasser', soakLabel: 'Einweichen',
    tipTitle: grain => `${grain} — so gelingt er`,
    knuckle: 'Beim Fingerglied-Trick streichst du den Reis glatt und gibst Wasser dazu, bis es gerade das Glied bedeckt, etwa 1,5cm — das ist normaler weißer Reis. Das hängt stark vom Topfdurchmesser ab und ist nur zuverlässig, wenn du immer denselben Topf nimmst.',
    rinseNote: 'Reis waschen, in einem Sieb abtropfen lassen und dann abmessen — nasser Reis hat schon Wasser aufgenommen.',
    waterTimes: r => `Wasser ×${r}`,
  },
  fr: {
    grains: ['Riz blanc', 'Riz complet', 'Mélange de céréales'],
    grainNotes: ['1,1 pour du riz récent, 1,3 pour du riz plus vieux', 'La couche de son laisse mal passer l’eau', 'Fais tremper les légumineuses à part, plus longtemps'],
    soaks: ['30 min', '2 heures ou plus', '1 heure'],
    textures: ['Ferme', 'Normal', 'Moelleux'],
    riceCups: 'Riz (tasses)', cupUnit: 'tasses',
    grainTitle: 'Type de riz', textureTitle: 'La tenue que tu veux',
    ratioSub: (ratio, cups) => `riz : eau = 1 : ${ratio} · ${cups} tasses d’eau`, waterWord: 'Eau',
    riceLabel: 'Riz', waterLabel: 'Eau', soakLabel: 'Trempage',
    tipTitle: grain => `${grain} — comment le réussir`,
    knuckle: 'Avec la méthode de la phalange, égalise le riz et ajoute de l’eau jusqu’à ce qu’elle recouvre tout juste la phalange, environ 1,5cm — c’est du riz blanc normal. Cela dépend beaucoup du diamètre de la casserole, donc ce n’est fiable qu’avec toujours la même.',
    rinseNote: 'Rince le riz, égoutte-le dans une passoire puis mesure — un riz mouillé a déjà pris de l’eau.',
    waterTimes: r => `eau ×${r}`,
  },
  hi: {
    grains: ['सफ़ेद चावल', 'भूरे चावल', 'मिले-जुले अनाज'],
    grainNotes: ['नए चावल के लिए 1.1, पुराने के लिए 1.3', 'चोकर की परत पानी कम सोखती है', 'दालों को अलग से और ज़्यादा देर भिगोएँ'],
    soaks: ['30 मिनट', '2 घंटे या ज़्यादा', '1 घंटा'],
    textures: ['खिला-खिला', 'सामान्य', 'नरम'],
    riceCups: 'चावल (कप)', cupUnit: 'कप',
    grainTitle: 'चावल का प्रकार', textureTitle: 'कितना नरम चाहिए',
    ratioSub: (ratio, cups) => `चावल : पानी = 1 : ${ratio} · ${cups} कप पानी`, waterWord: 'पानी',
    riceLabel: 'चावल', waterLabel: 'पानी', soakLabel: 'भिगोने का समय',
    tipTitle: grain => `${grain} — कैसे ठीक बने`,
    knuckle: 'उँगली की गाँठ वाले तरीके में चावल को बराबर कर लें और पानी इतना डालें कि गाँठ बस डूब जाए, लगभग 1.5cm — यह सामान्य सफ़ेद चावल है। यह बर्तन के व्यास पर बहुत निर्भर करता है, इसलिए एक ही बर्तन इस्तेमाल करने पर ही भरोसेमंद है।',
    rinseNote: 'चावल धोकर छन्नी में पानी निकाल लें, फिर नापें — गीले चावल पहले ही पानी सोख चुके होते हैं।',
    waterTimes: r => `पानी ${r} गुना`,
  },
};

export const PASTA_UI: Record<FoodLang, {
  shapes: string[]; noodle: string; servingNote: string;
  ratioSub: string; waterWord: string; saltWord: string;
  waterLabel: string; saltLabel: string; timeLabel: string; minSuffix: (m: number) => string;
  shapeTitle: string; alDente: string; alDenteNote: string;
  saltTitle: string; saltNote: string; waterNote: string;
}> = {
  ko: {
    shapes: ['스파게티', '링귀네', '펜네', '푸실리', '파르팔레', '페투치네'],
    noodle: '면', servingNote: '1인분은 보통 80~100g입니다 (많이 먹으면 120g)',
    ratioSub: '면 100g당 물 1L · 소금 10g 기준', waterWord: '물', saltWord: '소금',
    waterLabel: '물', saltLabel: '소금', timeLabel: '삶는 시간', minSuffix: m => `${m}분`,
    shapeTitle: '면 종류',
    alDente: '알덴테로 (1분 덜 삶기)', alDenteNote: '소스와 볶을 예정이라면 켜세요',
    saltTitle: '소금을 왜 이렇게 많이 넣나요',
    saltNote: '면에 간이 배는 유일한 기회이기 때문입니다. 대부분은 물과 함께 버려지고 면에 남는 양은 적습니다. 물이 팔팔 끓은 뒤에 소금을 넣고, 면을 넣기 전에 한 번 저어 녹이세요.',
    waterNote: '면수는 버리지 말고 한 국자 남겨 두세요. 전분이 녹아 있어 소스와 면이 겉돌지 않게 잡아 줍니다.',
  },
  en: {
    shapes: ['Spaghetti', 'Linguine', 'Penne', 'Fusilli', 'Farfalle', 'Fettuccine'],
    noodle: 'Pasta', servingNote: 'A serving is usually 80–100g (120g if you are hungry)',
    ratioSub: '1L water and 10g salt per 100g of pasta', waterWord: 'Water', saltWord: 'Salt',
    waterLabel: 'Water', saltLabel: 'Salt', timeLabel: 'Cooking time', minSuffix: m => `${m} min`,
    shapeTitle: 'Pasta shape',
    alDente: 'Al dente (one minute less)', alDenteNote: 'Turn this on if it is going into a pan with sauce',
    saltTitle: 'Why so much salt',
    saltNote: 'This is the only chance the pasta itself gets seasoned. Most of the salt goes down the drain with the water and only a little stays in the pasta. Add it once the water is at a full boil, and stir before the pasta goes in.',
    waterNote: 'Do not throw all the pasta water away — keep a ladle of it. The starch in it keeps the sauce clinging to the pasta instead of sliding off.',
  },
  es: {
    shapes: ['Espaguetis', 'Linguine', 'Penne', 'Fusilli', 'Farfalle', 'Fettuccine'],
    noodle: 'Pasta', servingNote: 'Una ración suele ser de 80–100g (120g si tienes hambre)',
    ratioSub: '1L de agua y 10g de sal por cada 100g de pasta', waterWord: 'Agua', saltWord: 'Sal',
    waterLabel: 'Agua', saltLabel: 'Sal', timeLabel: 'Tiempo de cocción', minSuffix: m => `${m} min`,
    shapeTitle: 'Forma de la pasta',
    alDente: 'Al dente (un minuto menos)', alDenteNote: 'Actívalo si va a pasar por la sartén con la salsa',
    saltTitle: 'Por qué tanta sal',
    saltNote: 'Es la única ocasión en que la pasta se sazona por dentro. La mayor parte de la sal se va por el desagüe con el agua y en la pasta queda poca. Échala cuando el agua esté hirviendo a borbotones y remueve antes de meter la pasta.',
    waterNote: 'No tires toda el agua de la pasta — guarda un cazo. El almidón que lleva mantiene la salsa agarrada a la pasta en vez de resbalar.',
  },
  'pt-br': {
    shapes: ['Espaguete', 'Linguine', 'Penne', 'Fusilli', 'Farfalle', 'Fettuccine'],
    noodle: 'Massa', servingNote: 'Uma porção geralmente é 80–100g (120g se estiver com fome)',
    ratioSub: '1L de água e 10g de sal para cada 100g de massa', waterWord: 'Água', saltWord: 'Sal',
    waterLabel: 'Água', saltLabel: 'Sal', timeLabel: 'Tempo de cozimento', minSuffix: m => `${m} min`,
    shapeTitle: 'Formato da massa',
    alDente: 'Al dente (um minuto menos)', alDenteNote: 'Ligue se ela vai para a frigideira com o molho',
    saltTitle: 'Por que tanto sal',
    saltNote: 'É a única chance de a massa ganhar tempero por dentro. A maior parte do sal vai pelo ralo com a água e na massa fica pouco. Coloque quando a água estiver em fervura forte e mexa antes de pôr a massa.',
    waterNote: 'Não jogue toda a água do cozimento fora — guarde uma concha. O amido dela mantém o molho agarrado na massa em vez de escorregar.',
  },
  ja: {
    shapes: ['スパゲッティ', 'リングイネ', 'ペンネ', 'フジッリ', 'ファルファッレ', 'フェットチーネ'],
    noodle: '麺', servingNote: '1人分はふつう80〜100gです（よく食べるなら120g）',
    ratioSub: '麺100gあたり水1L・塩10gが基準', waterWord: '水', saltWord: '塩',
    waterLabel: '水', saltLabel: '塩', timeLabel: 'ゆで時間', minSuffix: m => `${m}分`,
    shapeTitle: '麺の種類',
    alDente: 'アルデンテに（1分短く）', alDenteNote: 'ソースと炒める予定ならオンに',
    saltTitle: 'なぜこんなに塩を入れるのか',
    saltNote: '麺そのものに味が入る唯一の機会だからです。ほとんどはゆで汁と一緒に捨てられ、麺に残る量はわずかです。湯がしっかり沸いてから塩を入れ、麺を入れる前に一度混ぜて溶かしてください。',
    waterNote: 'ゆで汁は全部捨てず、お玉一杯分を取っておいてください。でんぷんが溶けているので、ソースと麺がなじんで離れなくなります。',
  },
  de: {
    shapes: ['Spaghetti', 'Linguine', 'Penne', 'Fusilli', 'Farfalle', 'Fettuccine'],
    noodle: 'Pasta', servingNote: 'Eine Portion sind meist 80–100g (120g, wenn du Hunger hast)',
    ratioSub: '1L Wasser und 10g Salz auf 100g Pasta', waterWord: 'Wasser', saltWord: 'Salz',
    waterLabel: 'Wasser', saltLabel: 'Salz', timeLabel: 'Kochzeit', minSuffix: m => `${m} Min.`,
    shapeTitle: 'Pastaform',
    alDente: 'Al dente (eine Minute weniger)', alDenteNote: 'Schalte das ein, wenn sie noch in die Pfanne zur Soße kommt',
    saltTitle: 'Warum so viel Salz',
    saltNote: 'Das ist die einzige Gelegenheit, bei der die Pasta selbst Geschmack bekommt. Der größte Teil des Salzes geht mit dem Wasser den Abfluss hinunter, in der Pasta bleibt nur wenig. Gib es zu, wenn das Wasser richtig kocht, und rühr einmal um, bevor die Pasta hineinkommt.',
    waterNote: 'Schütte nicht alles Nudelwasser weg — behalte eine Kelle. Die Stärke darin hält die Soße an der Pasta, statt dass sie abrutscht.',
  },
  fr: {
    shapes: ['Spaghetti', 'Linguine', 'Penne', 'Fusilli', 'Farfalle', 'Fettuccine'],
    noodle: 'Pâtes', servingNote: 'Une part fait généralement 80–100g (120g si tu as faim)',
    ratioSub: '1L d’eau et 10g de sel pour 100g de pâtes', waterWord: 'Eau', saltWord: 'Sel',
    waterLabel: 'Eau', saltLabel: 'Sel', timeLabel: 'Temps de cuisson', minSuffix: m => `${m} min`,
    shapeTitle: 'Forme des pâtes',
    alDente: 'Al dente (une minute de moins)', alDenteNote: 'Active-le si elles passent ensuite à la poêle avec la sauce',
    saltTitle: 'Pourquoi autant de sel',
    saltNote: 'C’est la seule occasion où les pâtes elles-mêmes sont assaisonnées. La majeure partie du sel part à l’évier avec l’eau et il n’en reste que peu dans les pâtes. Ajoute-le quand l’eau bout à gros bouillons, et remue avant de mettre les pâtes.',
    waterNote: 'Ne jette pas toute l’eau de cuisson — garde une louche. L’amidon qu’elle contient fait tenir la sauce aux pâtes au lieu de glisser.',
  },
  hi: {
    shapes: ['स्पैगेटी', 'लिंगुइने', 'पेने', 'फ़ुज़ीली', 'फ़ारफ़ाले', 'फ़ेटुचिने'],
    noodle: 'पास्ता', servingNote: 'एक व्यक्ति के लिए आम तौर पर 80–100g (भूख ज़्यादा हो तो 120g)',
    ratioSub: 'हर 100g पास्ता पर 1L पानी और 10g नमक', waterWord: 'पानी', saltWord: 'नमक',
    waterLabel: 'पानी', saltLabel: 'नमक', timeLabel: 'पकाने का समय', minSuffix: m => `${m} मिनट`,
    shapeTitle: 'पास्ता का आकार',
    alDente: 'अल दांते (एक मिनट कम)', alDenteNote: 'सॉस के साथ कड़ाही में जाना हो तो चालू करें',
    saltTitle: 'इतना नमक क्यों',
    saltNote: 'पास्ता के भीतर स्वाद जाने का यही एक मौका होता है। ज़्यादातर नमक पानी के साथ बह जाता है और पास्ता में थोड़ा ही रह जाता है। पानी अच्छी तरह उबलने पर नमक डालें, और पास्ता डालने से पहले एक बार चला दें।',
    waterNote: 'पास्ता का सारा पानी न फेंकें — एक कलछी बचा लें। उसमें घुला स्टार्च सॉस को पास्ता से चिपका रखता है, फिसलने नहीं देता।',
  },
};

export const COFFEE_UI: Record<FoodLang, {
  modes: string[]; drinkWater: string; yieldLabel: string; beanLabel: string;
  beanWord: string; waterWord: string;
  beanStat: string; waterStat: string; ratioStat: string;
  note: string;
}> = {
  ko: {
    modes: ['물 양으로 계산', '원두 양으로 계산'],
    drinkWater: '마실 물', yieldLabel: '추출할 양', beanLabel: '원두',
    beanWord: '원두', waterWord: '물',
    beanStat: '원두', waterStat: '물', ratioStat: '비율',
    note: '비율은 시작점일 뿐입니다. 같은 비율이라도 물 온도(90~95℃)와 분쇄도에 따라 맛이 크게 달라집니다. 쓰고 텁텁하면 굵게 갈거나 물 온도를 낮추고, 싱겁고 신맛만 나면 곱게 갈거나 시간을 늘리세요.',
  },
  en: {
    modes: ['Start from the water', 'Start from the coffee'],
    drinkWater: 'Water to drink', yieldLabel: 'Shot yield', beanLabel: 'Coffee',
    beanWord: 'Coffee', waterWord: 'Water',
    beanStat: 'Coffee', waterStat: 'Water', ratioStat: 'Ratio',
    note: 'The ratio is only a starting point. At the same ratio, water temperature (90–95°C) and grind size still change the taste a lot. Bitter and muddy means grind coarser or drop the temperature; thin and sour means grind finer or brew longer.',
  },
  es: {
    modes: ['Partir del agua', 'Partir del café'],
    drinkWater: 'Agua a beber', yieldLabel: 'Cantidad de salida', beanLabel: 'Café',
    beanWord: 'Café', waterWord: 'Agua',
    beanStat: 'Café', waterStat: 'Agua', ratioStat: 'Proporción',
    note: 'La proporción es solo un punto de partida. Con la misma proporción, la temperatura del agua (90–95°C) y la molienda cambian mucho el sabor. Si sale amargo y pastoso, muele más grueso o baja la temperatura; si sale aguado y ácido, muele más fino o alarga la extracción.',
  },
  'pt-br': {
    modes: ['Partir da água', 'Partir do café'],
    drinkWater: 'Água para beber', yieldLabel: 'Quantidade de saída', beanLabel: 'Café',
    beanWord: 'Café', waterWord: 'Água',
    beanStat: 'Café', waterStat: 'Água', ratioStat: 'Proporção',
    note: 'A proporção é só um ponto de partida. Na mesma proporção, a temperatura da água (90–95°C) e a moagem mudam muito o sabor. Se sair amargo e pastoso, moa mais grosso ou abaixe a temperatura; se sair aguado e ácido, moa mais fino ou estenda a extração.',
  },
  ja: {
    modes: ['湯の量から計算', '豆の量から計算'],
    drinkWater: '飲む湯の量', yieldLabel: '抽出量', beanLabel: '豆',
    beanWord: '豆', waterWord: '湯',
    beanStat: '豆', waterStat: '湯', ratioStat: '比率',
    note: '比率は出発点にすぎません。同じ比率でも湯の温度（90〜95℃）と挽き方で味は大きく変わります。苦くて重たいなら粗く挽くか湯の温度を下げ、薄くて酸味だけが立つなら細かく挽くか時間を延ばしてください。',
  },
  de: {
    modes: ['Vom Wasser ausgehen', 'Vom Kaffee ausgehen'],
    drinkWater: 'Wasser zum Trinken', yieldLabel: 'Auslaufmenge', beanLabel: 'Kaffee',
    beanWord: 'Kaffee', waterWord: 'Wasser',
    beanStat: 'Kaffee', waterStat: 'Wasser', ratioStat: 'Verhältnis',
    note: 'Das Verhältnis ist nur ein Ausgangspunkt. Beim gleichen Verhältnis verändern Wassertemperatur (90–95°C) und Mahlgrad den Geschmack immer noch stark. Bitter und schwer heißt grober mahlen oder Temperatur senken; dünn und nur sauer heißt feiner mahlen oder länger brühen.',
  },
  fr: {
    modes: ['Partir de l’eau', 'Partir du café'],
    drinkWater: 'Eau à boire', yieldLabel: 'Quantité en sortie', beanLabel: 'Café',
    beanWord: 'Café', waterWord: 'Eau',
    beanStat: 'Café', waterStat: 'Eau', ratioStat: 'Ratio',
    note: 'Le ratio n’est qu’un point de départ. À ratio égal, la température de l’eau (90–95°C) et la mouture changent beaucoup le goût. Amer et lourd : mouds plus grossier ou baisse la température ; léger et seulement acide : mouds plus fin ou allonge l’extraction.',
  },
  hi: {
    modes: ['पानी से शुरू करें', 'कॉफ़ी से शुरू करें'],
    drinkWater: 'पीने का पानी', yieldLabel: 'निकास की मात्रा', beanLabel: 'कॉफ़ी',
    beanWord: 'कॉफ़ी', waterWord: 'पानी',
    beanStat: 'कॉफ़ी', waterStat: 'पानी', ratioStat: 'अनुपात',
    note: 'अनुपात सिर्फ़ शुरुआत है। एक ही अनुपात पर भी पानी का तापमान (90–95°C) और पीसने की बारीकी स्वाद को बहुत बदल देते हैं। कड़वा और भारी लगे तो मोटा पीसें या तापमान घटाएँ; पतला और सिर्फ़ खट्टा लगे तो बारीक पीसें या समय बढ़ाएँ।',
  },
};

export const PAN_UI: Record<FoodLang, {
  shapes: string[]; diameter: string; width: string; height: string;
  fromTitle: string; toTitle: string;
  areaSub: (from: number, to: number) => string; batter: string; timesUnit: string;
  fromArea: string; toArea: string; scaleStat: string; timesSuffix: (n: number) => string;
  timeTitle: string; timeBigger: string; timeSmaller: string; timeSame: string;
  note: string;
}> = {
  ko: {
    shapes: ['원형', '사각'], diameter: '지름', width: '가로', height: '세로',
    fromTitle: '레시피의 틀', toTitle: '내가 쓸 틀',
    areaSub: (from, to) => `넓이 ${from}cm² → ${to}cm²`, batter: '반죽', timesUnit: '배',
    fromArea: '레시피 틀 넓이', toArea: '내 틀 넓이', scaleStat: '반죽 배율', timesSuffix: n => `${n}배`,
    timeTitle: '굽는 시간도 조정하세요',
    timeBigger: '틀이 커져 반죽이 얇게 퍼지면 더 빨리 익습니다. 원래 시간의 80% 지점에서 확인해 보세요.',
    timeSmaller: '틀이 작아 반죽이 두꺼워지면 속이 덜 익기 쉽습니다. 온도를 10도 낮추고 시간을 늘리세요.',
    timeSame: '넓이가 비슷해 시간은 거의 그대로 두면 됩니다.',
    note: '넓이 비율로 계산하므로 틀 높이가 비슷할 때 맞습니다. 깊이가 크게 다르면 반죽 두께가 달라져 굽는 시간이 많이 바뀝니다. 반죽은 틀의 60~70%까지만 채우세요.',
  },
  en: {
    shapes: ['Round', 'Square'], diameter: 'Diameter', width: 'Width', height: 'Length',
    fromTitle: 'The recipe’s tin', toTitle: 'The tin you have',
    areaSub: (from, to) => `area ${from}cm² → ${to}cm²`, batter: 'Batter', timesUnit: '×',
    fromArea: 'Recipe tin area', toArea: 'Your tin area', scaleStat: 'Batter scale', timesSuffix: n => `${n}×`,
    timeTitle: 'Adjust the bake time too',
    timeBigger: 'A bigger tin spreads the batter thinner, so it bakes faster. Start checking at 80% of the original time.',
    timeSmaller: 'A smaller tin makes the batter deeper, which easily leaves the middle underdone. Drop the temperature 10°C and bake longer.',
    timeSame: 'The areas are close enough that you can leave the time roughly as it is.',
    note: 'This compares by area, so it is right when the tins are a similar depth. If the depths differ a lot the batter thickness changes and the bake time shifts considerably. Fill a tin only 60–70% of the way.',
  },
  es: {
    shapes: ['Redondo', 'Cuadrado'], diameter: 'Diámetro', width: 'Ancho', height: 'Largo',
    fromTitle: 'El molde de la receta', toTitle: 'El molde que tienes',
    areaSub: (from, to) => `superficie ${from}cm² → ${to}cm²`, batter: 'Masa', timesUnit: '×',
    fromArea: 'Superficie del molde de la receta', toArea: 'Superficie de tu molde', scaleStat: 'Escala de la masa', timesSuffix: n => `${n}×`,
    timeTitle: 'Ajusta también el tiempo de horno',
    timeBigger: 'Un molde más grande reparte la masa más fina, así que se hace antes. Empieza a comprobar al 80% del tiempo original.',
    timeSmaller: 'Un molde más pequeño deja la masa más gruesa, y el centro se queda crudo con facilidad. Baja la temperatura 10°C y alarga el tiempo.',
    timeSame: 'Las superficies son parecidas, así que puedes dejar el tiempo casi igual.',
    note: 'Esto compara por superficie, así que acierta cuando los moldes tienen una altura parecida. Si las alturas cambian mucho, el grosor de la masa cambia y el tiempo de horno se mueve bastante. Llena el molde solo al 60–70%.',
  },
  'pt-br': {
    shapes: ['Redonda', 'Quadrada'], diameter: 'Diâmetro', width: 'Largura', height: 'Comprimento',
    fromTitle: 'A forma da receita', toTitle: 'A forma que você tem',
    areaSub: (from, to) => `área ${from}cm² → ${to}cm²`, batter: 'Massa', timesUnit: '×',
    fromArea: 'Área da forma da receita', toArea: 'Área da sua forma', scaleStat: 'Ajuste da massa', timesSuffix: n => `${n}×`,
    timeTitle: 'Ajuste também o tempo de forno',
    timeBigger: 'Uma forma maior espalha a massa mais fina, então assa mais rápido. Comece a conferir aos 80% do tempo original.',
    timeSmaller: 'Uma forma menor deixa a massa mais alta, e o meio fica cru com facilidade. Abaixe a temperatura 10°C e asse por mais tempo.',
    timeSame: 'As áreas são parecidas, então você pode deixar o tempo quase igual.',
    note: 'Isto compara por área, então acerta quando as formas têm altura parecida. Se as alturas mudam muito, a espessura da massa muda e o tempo de forno se altera bastante. Encha a forma só até 60–70%.',
  },
  ja: {
    shapes: ['丸型', '角型'], diameter: '直径', width: '横', height: '縦',
    fromTitle: 'レシピの型', toTitle: '使う型',
    areaSub: (from, to) => `面積 ${from}cm² → ${to}cm²`, batter: '生地', timesUnit: '倍',
    fromArea: 'レシピの型の面積', toArea: '使う型の面積', scaleStat: '生地の倍率', timesSuffix: n => `${n}倍`,
    timeTitle: '焼く時間も調整してください',
    timeBigger: '型が大きくなって生地が薄く広がると早く焼けます。もとの時間の80%の時点で確認してみてください。',
    timeSmaller: '型が小さく生地が厚くなると中が生焼けになりやすいです。温度を10度下げて時間を延ばしてください。',
    timeSame: '面積が近いので、時間はほぼそのままで大丈夫です。',
    note: '面積の比で計算するので、型の高さが近いときに合います。深さが大きく違うと生地の厚みが変わり、焼き時間もかなり変わります。生地は型の60〜70%までにしてください。',
  },
  de: {
    shapes: ['Rund', 'Eckig'], diameter: 'Durchmesser', width: 'Breite', height: 'Länge',
    fromTitle: 'Die Form aus dem Rezept', toTitle: 'Die Form, die du hast',
    areaSub: (from, to) => `Fläche ${from}cm² → ${to}cm²`, batter: 'Teig', timesUnit: '×',
    fromArea: 'Fläche der Rezeptform', toArea: 'Fläche deiner Form', scaleStat: 'Teigfaktor', timesSuffix: n => `${n}×`,
    timeTitle: 'Passe auch die Backzeit an',
    timeBigger: 'Eine größere Form verteilt den Teig dünner, er backt also schneller. Fang bei 80% der ursprünglichen Zeit an nachzusehen.',
    timeSmaller: 'Eine kleinere Form macht den Teig höher, dann bleibt die Mitte leicht roh. Senke die Temperatur um 10°C und backe länger.',
    timeSame: 'Die Flächen liegen nah beieinander, du kannst die Zeit also fast so lassen.',
    note: 'Verglichen wird über die Fläche, das passt also bei ähnlicher Formhöhe. Weichen die Tiefen stark ab, ändert sich die Teigdicke und die Backzeit verschiebt sich erheblich. Füll eine Form nur zu 60–70%.',
  },
  fr: {
    shapes: ['Rond', 'Carré'], diameter: 'Diamètre', width: 'Largeur', height: 'Longueur',
    fromTitle: 'Le moule de la recette', toTitle: 'Le moule que tu as',
    areaSub: (from, to) => `surface ${from}cm² → ${to}cm²`, batter: 'Pâte', timesUnit: '×',
    fromArea: 'Surface du moule de la recette', toArea: 'Surface de ton moule', scaleStat: 'Facteur de pâte', timesSuffix: n => `${n}×`,
    timeTitle: 'Ajuste aussi le temps de cuisson',
    timeBigger: 'Un moule plus grand étale la pâte plus fin, donc ça cuit plus vite. Commence à vérifier à 80% du temps d’origine.',
    timeSmaller: 'Un moule plus petit épaissit la pâte, et le centre reste facilement cru. Baisse la température de 10°C et allonge le temps.',
    timeSame: 'Les surfaces sont proches, tu peux donc laisser le temps quasiment tel quel.',
    note: 'La comparaison se fait par surface : c’est juste quand les moules ont une hauteur proche. Si les profondeurs diffèrent beaucoup, l’épaisseur de la pâte change et le temps de cuisson bouge nettement. Ne remplis un moule qu’à 60–70%.',
  },
  hi: {
    shapes: ['गोल', 'चौकोर'], diameter: 'व्यास', width: 'चौड़ाई', height: 'लंबाई',
    fromTitle: 'रेसिपी का टिन', toTitle: 'आपके पास का टिन',
    areaSub: (from, to) => `क्षेत्रफल ${from}cm² → ${to}cm²`, batter: 'घोल', timesUnit: 'गुना',
    fromArea: 'रेसिपी के टिन का क्षेत्रफल', toArea: 'आपके टिन का क्षेत्रफल', scaleStat: 'घोल का गुणक', timesSuffix: n => `${n} गुना`,
    timeTitle: 'बेक करने का समय भी बदलें',
    timeBigger: 'टिन बड़ा होने से घोल पतला फैलता है और जल्दी पक जाता है। मूल समय के 80% पर देखना शुरू कर दें।',
    timeSmaller: 'टिन छोटा होने से घोल मोटा हो जाता है और बीच कच्चा रह जाना आसान है। तापमान 10°C घटाकर समय बढ़ाएँ।',
    timeSame: 'क्षेत्रफल मिलता-जुलता है, इसलिए समय लगभग वही रख सकते हैं।',
    note: 'गणना क्षेत्रफल के अनुपात से होती है, इसलिए टिन की गहराई मिलती-जुलती होने पर सही बैठती है। गहराई बहुत अलग हो तो घोल की मोटाई बदल जाती है और बेक का समय काफ़ी बदलता है। घोल टिन के 60–70% तक ही भरें।',
  },
};

export const STORAGE_UI: Record<FoodLang, {
  searchPlaceholder: string; fridge: string; freezer: string; notFound: string;
  noteTitle: string; note: string; noteBold: string; refreeze: string;
}> = {
  ko: {
    searchPlaceholder: '재료 이름으로 찾기 — 닭, 우유, 두부…',
    fridge: '냉장', freezer: '냉동', notFound: '찾는 재료가 목록에 없습니다',
    noteTitle: '기간은 품질 기준입니다',
    note: '여기 적힌 기간은 ‘맛과 질감이 유지되는’ 기준입니다. 냉동은 그 뒤에도 상하지는 않지만 맛이 떨어집니다. 반대로 냉장은 기간 안이라도 온도가 높거나 여러 번 열었다면 더 빨리 상할 수 있으니,',
    noteBold: ' 냄새와 색을 먼저 확인하세요.',
    refreeze: '해동한 식품을 다시 얼리지 마세요. 녹는 동안 늘어난 세균이 그대로 남습니다.',
  },
  en: {
    searchPlaceholder: 'Search by name — chicken, milk, tofu…',
    fridge: 'Fridge', freezer: 'Freezer', notFound: 'That ingredient is not in the list',
    noteTitle: 'These are quality times, not safety limits',
    note: 'The times here are how long the taste and texture hold up. Frozen food does not become unsafe after that, it just gets worse. In the fridge, the opposite applies — even inside the window, a warm fridge or a door opened often can spoil things sooner, so',
    noteBold: ' check the smell and the colour first.',
    refreeze: 'Do not refreeze food you have thawed. The bacteria that multiplied while it thawed are still there.',
  },
  es: {
    searchPlaceholder: 'Busca por nombre — pollo, leche, tofu…',
    fridge: 'Nevera', freezer: 'Congelador', notFound: 'Ese ingrediente no está en la lista',
    noteTitle: 'Son plazos de calidad, no límites de seguridad',
    note: 'Los plazos de aquí indican cuánto se mantienen el sabor y la textura. La comida congelada no se vuelve peligrosa después, solo empeora. En la nevera es al contrario: incluso dentro del plazo, una nevera templada o una puerta que se abre mucho pueden echar a perder las cosas antes, así que',
    noteBold: ' comprueba primero el olor y el color.',
    refreeze: 'No vuelvas a congelar lo que has descongelado. Las bacterias que se multiplicaron mientras se descongelaba siguen ahí.',
  },
  'pt-br': {
    searchPlaceholder: 'Busque pelo nome — frango, leite, tofu…',
    fridge: 'Geladeira', freezer: 'Freezer', notFound: 'Esse ingrediente não está na lista',
    noteTitle: 'São prazos de qualidade, não limites de segurança',
    note: 'Os prazos daqui dizem quanto tempo sabor e textura se mantêm. Comida congelada não fica perigosa depois disso, só piora. Na geladeira é o contrário: mesmo dentro do prazo, uma geladeira mais quente ou uma porta aberta muitas vezes podem estragar antes, então',
    noteBold: ' confira primeiro o cheiro e a cor.',
    refreeze: 'Não congele de novo o que você descongelou. As bactérias que se multiplicaram durante o descongelamento continuam ali.',
  },
  ja: {
    searchPlaceholder: '食材の名前で探す — 鶏肉、牛乳、豆腐…',
    fridge: '冷蔵', freezer: '冷凍', notFound: '探している食材が一覧にありません',
    noteTitle: 'この期間は品質の目安です',
    note: 'ここに書いた期間は「味と食感が保たれる」目安です。冷凍はそのあとも傷むわけではありませんが、味は落ちます。逆に冷蔵は期間内でも温度が高かったり何度も開けたりすれば早く傷むことがあるので、',
    noteBold: 'まず匂いと色を確かめてください。',
    refreeze: '解凍した食品を再び凍らせないでください。解けているあいだに増えた細菌はそのまま残っています。',
  },
  de: {
    searchPlaceholder: 'Nach Namen suchen — Hähnchen, Milch, Tofu…',
    fridge: 'Kühlschrank', freezer: 'Gefrierschrank', notFound: 'Diese Zutat steht nicht in der Liste',
    noteTitle: 'Das sind Qualitätszeiten, keine Sicherheitsgrenzen',
    note: 'Die Zeiten hier sagen, wie lange Geschmack und Konsistenz halten. Gefrorenes wird danach nicht unsicher, es wird nur schlechter. Im Kühlschrank gilt das Umgekehrte — selbst innerhalb der Frist kann ein zu warmer Kühlschrank oder eine häufig geöffnete Tür Dinge früher verderben, also',
    noteBold: ' prüfe zuerst Geruch und Farbe.',
    refreeze: 'Friere Aufgetautes nicht wieder ein. Die Bakterien, die sich beim Auftauen vermehrt haben, sind noch da.',
  },
  fr: {
    searchPlaceholder: 'Cherche par nom — poulet, lait, tofu…',
    fridge: 'Frigo', freezer: 'Congélateur', notFound: 'Cet ingrédient n’est pas dans la liste',
    noteTitle: 'Ce sont des durées de qualité, pas des limites de sécurité',
    note: 'Les durées indiquées disent combien de temps le goût et la texture tiennent. Un aliment congelé ne devient pas dangereux ensuite, il se dégrade seulement. Au frigo, c’est l’inverse — même dans le délai, un frigo trop chaud ou une porte souvent ouverte peuvent gâter les choses plus tôt, donc',
    noteBold: ' vérifie d’abord l’odeur et la couleur.',
    refreeze: 'Ne recongèle pas ce que tu as décongelé. Les bactéries qui se sont multipliées pendant la décongélation sont toujours là.',
  },
  hi: {
    searchPlaceholder: 'नाम से खोजें — चिकन, दूध, टोफ़ू…',
    fridge: 'फ़्रिज', freezer: 'फ़्रीज़र', notFound: 'यह सामग्री सूची में नहीं है',
    noteTitle: 'ये अवधि गुणवत्ता की है, सुरक्षा की सीमा नहीं',
    note: 'यहाँ दी गई अवधि बताती है कि स्वाद और बनावट कितने दिन बनी रहती है। जमा हुआ खाना उसके बाद असुरक्षित नहीं हो जाता, बस बिगड़ जाता है। फ़्रिज में उलटा है — अवधि के भीतर भी तापमान ज़्यादा हो या दरवाज़ा बार-बार खुले तो पहले ही ख़राब हो सकता है, इसलिए',
    noteBold: ' पहले गंध और रंग जाँच लें।',
    refreeze: 'पिघलाए हुए खाने को दोबारा न जमाएँ। पिघलने के दौरान बढ़े जीवाणु उसी में बने रहते हैं।',
  },
};
