// node에서 직접 로드할 수 있게 확장자를 명시한다 (allowImportingTsExtensions)
import type { AnyLocale } from './locales.ts';

/**
 * 요리 도구가 쓰는 데이터의 여덟 언어 이름표.
 *
 * lib/food.ts의 밀도·온도·비율은 언어와 무관한 숫자다. 그래서 그쪽은 건드리지
 * 않고, id(또는 배열 순서)를 열쇠로 이름과 설명만 여기서 갈아 끼운다.
 *
 * 재료 이름은 번역이 아니라 그 언어의 부엌에서 쓰는 말로 적는다 — 고추장을
 * 'red pepper paste'로 풀어 쓰는 대신 gochujang으로 두는 것이 실제로 찾기 쉽다.
 */
export type FoodLang = AnyLocale;

/** INGREDIENTS의 id → 이름·주의 */
export const INGREDIENT_INTL: Record<FoodLang, Record<string, { name: string; note?: string }>> = {
  ko: {
    water: { name: '물·우유' },
    flour: { name: '밀가루(박력·중력)', note: '체에 쳐서 수북이 담지 말고 깎아 재세요' },
    sugar: { name: '설탕(백설탕)' },
    'brown-sugar': { name: '황설탕(눌러 담기)' },
    salt: { name: '소금(꽃소금)' },
    rice: { name: '쌀(생쌀)' },
    oil: { name: '식용유·올리브유' },
    butter: { name: '버터(녹인 것)' },
    honey: { name: '꿀·물엿' },
    soy: { name: '간장' },
    gochujang: { name: '고추장' },
    cocoa: { name: '코코아 가루' },
    oat: { name: '오트밀' },
    breadcrumb: { name: '빵가루' },
  },
  en: {
    water: { name: 'Water or milk' },
    flour: { name: 'Flour (plain, cake)', note: 'Sift it and level the cup off — do not heap or pack it' },
    sugar: { name: 'Sugar (white, granulated)' },
    'brown-sugar': { name: 'Brown sugar (packed)' },
    salt: { name: 'Salt (fine)' },
    rice: { name: 'Rice (uncooked)' },
    oil: { name: 'Cooking or olive oil' },
    butter: { name: 'Butter (melted)' },
    honey: { name: 'Honey or syrup' },
    soy: { name: 'Soy sauce' },
    gochujang: { name: 'Gochujang (Korean chilli paste)' },
    cocoa: { name: 'Cocoa powder' },
    oat: { name: 'Rolled oats' },
    breadcrumb: { name: 'Breadcrumbs' },
  },
  es: {
    water: { name: 'Agua o leche' },
    flour: { name: 'Harina (floja, de repostería)', note: 'Tamízala y rasa la taza — no la colmes ni la aprietes' },
    sugar: { name: 'Azúcar (blanco, granulado)' },
    'brown-sugar': { name: 'Azúcar moreno (apretado)' },
    salt: { name: 'Sal (fina)' },
    rice: { name: 'Arroz (crudo)' },
    oil: { name: 'Aceite de girasol u oliva' },
    butter: { name: 'Mantequilla (derretida)' },
    honey: { name: 'Miel o sirope' },
    soy: { name: 'Salsa de soja' },
    gochujang: { name: 'Gochujang (pasta de chile coreana)' },
    cocoa: { name: 'Cacao en polvo' },
    oat: { name: 'Copos de avena' },
    breadcrumb: { name: 'Pan rallado' },
  },
  'pt-br': {
    water: { name: 'Água ou leite' },
    flour: { name: 'Farinha de trigo', note: 'Peneire e nivele a xícara — não encha por cima nem aperte' },
    sugar: { name: 'Açúcar (refinado)' },
    'brown-sugar': { name: 'Açúcar mascavo (apertado)' },
    salt: { name: 'Sal (fino)' },
    rice: { name: 'Arroz (cru)' },
    oil: { name: 'Óleo ou azeite' },
    butter: { name: 'Manteiga (derretida)' },
    honey: { name: 'Mel ou melado' },
    soy: { name: 'Shoyu' },
    gochujang: { name: 'Gochujang (pasta de pimenta coreana)' },
    cocoa: { name: 'Cacau em pó' },
    oat: { name: 'Aveia em flocos' },
    breadcrumb: { name: 'Farinha de rosca' },
  },
  ja: {
    water: { name: '水・牛乳' },
    flour: { name: '小麦粉（薄力・中力）', note: 'ふるってから、山盛りにせずすり切りで量ってください' },
    sugar: { name: '砂糖（上白糖・グラニュー糖）' },
    'brown-sugar': { name: 'ブラウンシュガー（押し込んで）' },
    salt: { name: '塩（食塩）' },
    rice: { name: '米（生米）' },
    oil: { name: 'サラダ油・オリーブ油' },
    butter: { name: 'バター（溶かしたもの）' },
    honey: { name: 'はちみつ・水あめ' },
    soy: { name: 'しょうゆ' },
    gochujang: { name: 'コチュジャン' },
    cocoa: { name: 'ココアパウダー' },
    oat: { name: 'オートミール' },
    breadcrumb: { name: 'パン粉' },
  },
  de: {
    water: { name: 'Wasser oder Milch' },
    flour: { name: 'Mehl (Type 405, 550)', note: 'Sieben und glatt abstreichen — nicht häufen, nicht festdrücken' },
    sugar: { name: 'Zucker (weiß, Kristall)' },
    'brown-sugar': { name: 'Brauner Zucker (festgedrückt)' },
    salt: { name: 'Salz (feines)' },
    rice: { name: 'Reis (ungekocht)' },
    oil: { name: 'Speise- oder Olivenöl' },
    butter: { name: 'Butter (geschmolzen)' },
    honey: { name: 'Honig oder Sirup' },
    soy: { name: 'Sojasoße' },
    gochujang: { name: 'Gochujang (koreanische Chilipaste)' },
    cocoa: { name: 'Kakaopulver' },
    oat: { name: 'Haferflocken' },
    breadcrumb: { name: 'Semmelbrösel' },
  },
  fr: {
    water: { name: 'Eau ou lait' },
    flour: { name: 'Farine (T45, T55)', note: 'Tamise-la et rase la tasse — ne la tasse pas et ne la remplis pas en dôme' },
    sugar: { name: 'Sucre (blanc, semoule)' },
    'brown-sugar': { name: 'Cassonade (tassée)' },
    salt: { name: 'Sel (fin)' },
    rice: { name: 'Riz (cru)' },
    oil: { name: 'Huile de tournesol ou d’olive' },
    butter: { name: 'Beurre (fondu)' },
    honey: { name: 'Miel ou sirop' },
    soy: { name: 'Sauce soja' },
    gochujang: { name: 'Gochujang (pâte de piment coréenne)' },
    cocoa: { name: 'Cacao en poudre' },
    oat: { name: 'Flocons d’avoine' },
    breadcrumb: { name: 'Chapelure' },
  },
  hi: {
    water: { name: 'पानी या दूध' },
    flour: { name: 'मैदा', note: 'छानकर कप को सीधा कर लें — ढेर लगाकर या दबाकर न भरें' },
    sugar: { name: 'चीनी (सफ़ेद)' },
    'brown-sugar': { name: 'भूरी चीनी (दबाकर)' },
    salt: { name: 'नमक (बारीक)' },
    rice: { name: 'चावल (कच्चे)' },
    oil: { name: 'तेल या जैतून का तेल' },
    butter: { name: 'मक्खन (पिघला)' },
    honey: { name: 'शहद या चाशनी' },
    soy: { name: 'सोया सॉस' },
    gochujang: { name: 'गोचुजांग (कोरियाई मिर्च की चटनी)' },
    cocoa: { name: 'कोको पाउडर' },
    oat: { name: 'ओट्स' },
    breadcrumb: { name: 'ब्रेडक्रम्ब' },
  },
};

/** DONENESS의 id → 이름·설명 */
export const DONENESS_INTL: Record<FoodLang, Record<string, { name: string; desc: string }>> = {
  ko: {
    rare: { name: '레어', desc: '가운데가 붉고 차갑습니다' },
    'medium-rare': { name: '미디엄 레어', desc: '가장 많이 권하는 굽기입니다' },
    medium: { name: '미디엄', desc: '분홍빛이 남고 육즙이 있습니다' },
    'medium-well': { name: '미디엄 웰던', desc: '분홍빛이 거의 사라집니다' },
    well: { name: '웰던', desc: '속까지 완전히 익습니다' },
  },
  en: {
    rare: { name: 'Rare', desc: 'Red and cool in the middle' },
    'medium-rare': { name: 'Medium rare', desc: 'The most commonly recommended' },
    medium: { name: 'Medium', desc: 'Still pink, still juicy' },
    'medium-well': { name: 'Medium well', desc: 'Almost no pink left' },
    well: { name: 'Well done', desc: 'Cooked through' },
  },
  es: {
    rare: { name: 'Poco hecho', desc: 'Rojo y frío en el centro' },
    'medium-rare': { name: 'Al punto poco hecho', desc: 'El punto que más se recomienda' },
    medium: { name: 'Al punto', desc: 'Aún rosado, aún jugoso' },
    'medium-well': { name: 'Al punto pasado', desc: 'Casi no queda rosa' },
    well: { name: 'Muy hecho', desc: 'Hecho por completo' },
  },
  'pt-br': {
    rare: { name: 'Mal passado', desc: 'Vermelho e frio no centro' },
    'medium-rare': { name: 'Ao ponto para mal', desc: 'O ponto mais recomendado' },
    medium: { name: 'Ao ponto', desc: 'Ainda rosado, ainda suculento' },
    'medium-well': { name: 'Ao ponto para bem', desc: 'Quase não sobra rosa' },
    well: { name: 'Bem passado', desc: 'Cozido por inteiro' },
  },
  ja: {
    rare: { name: 'レア', desc: '中心が赤く、冷たいままです' },
    'medium-rare': { name: 'ミディアムレア', desc: 'もっともよく勧められる焼き加減です' },
    medium: { name: 'ミディアム', desc: 'ピンク色が残り、肉汁があります' },
    'medium-well': { name: 'ミディアムウェル', desc: 'ピンク色がほぼなくなります' },
    well: { name: 'ウェルダン', desc: '中まで完全に火が通ります' },
  },
  de: {
    rare: { name: 'Rare', desc: 'In der Mitte rot und kühl' },
    'medium-rare': { name: 'Medium rare', desc: 'Die am häufigsten empfohlene Stufe' },
    medium: { name: 'Medium', desc: 'Noch rosa, noch saftig' },
    'medium-well': { name: 'Medium well', desc: 'Fast kein Rosa mehr' },
    well: { name: 'Well done', desc: 'Durchgegart' },
  },
  fr: {
    rare: { name: 'Bleu', desc: 'Rouge et froid au centre' },
    'medium-rare': { name: 'Saignant', desc: 'La cuisson la plus souvent conseillée' },
    medium: { name: 'À point', desc: 'Encore rosé, encore juteux' },
    'medium-well': { name: 'Cuit', desc: 'Presque plus de rose' },
    well: { name: 'Bien cuit', desc: 'Cuit de part en part' },
  },
  hi: {
    rare: { name: 'रेयर', desc: 'बीच में लाल और ठंडा' },
    'medium-rare': { name: 'मीडियम रेयर', desc: 'सबसे ज़्यादा सुझाया जाने वाला स्तर' },
    medium: { name: 'मीडियम', desc: 'गुलाबी रंग बचा हुआ, रसीला' },
    'medium-well': { name: 'मीडियम वेल', desc: 'गुलाबी रंग लगभग ख़त्म' },
    well: { name: 'वेल डन', desc: 'भीतर तक पूरा पका' },
  },
};

/** BREW_RATIOS의 id → 이름·설명 */
export const BREW_INTL: Record<FoodLang, Record<string, { name: string; note: string }>> = {
  ko: {
    'filter-light': { name: '핸드드립 (연하게)', note: '물 17 : 원두 1' },
    filter: { name: '핸드드립 (보통)', note: '가장 무난한 비율입니다' },
    'filter-strong': { name: '핸드드립 (진하게)', note: '산미가 줄고 바디가 올라갑니다' },
    french: { name: '프렌치프레스', note: '굵게 갈아 4분 담급니다' },
    coldbrew: { name: '콜드브루 원액', note: '희석해서 마십니다' },
    espresso: { name: '에스프레소', note: '원두 1 : 추출량 2' },
  },
  en: {
    'filter-light': { name: 'Pour over (light)', note: '17 parts water to 1 coffee' },
    filter: { name: 'Pour over (standard)', note: 'The safest ratio to start from' },
    'filter-strong': { name: 'Pour over (strong)', note: 'Less acidity, more body' },
    french: { name: 'French press', note: 'Coarse grind, steeped four minutes' },
    coldbrew: { name: 'Cold brew concentrate', note: 'Dilute before drinking' },
    espresso: { name: 'Espresso', note: '1 part coffee to 2 out' },
  },
  es: {
    'filter-light': { name: 'Filtrado (suave)', note: '17 partes de agua por 1 de café' },
    filter: { name: 'Filtrado (normal)', note: 'La proporción más segura para empezar' },
    'filter-strong': { name: 'Filtrado (intenso)', note: 'Menos acidez, más cuerpo' },
    french: { name: 'Prensa francesa', note: 'Molienda gruesa, cuatro minutos en reposo' },
    coldbrew: { name: 'Concentrado de cold brew', note: 'Dilúyelo antes de beberlo' },
    espresso: { name: 'Espresso', note: '1 parte de café por 2 de salida' },
  },
  'pt-br': {
    'filter-light': { name: 'Coado (suave)', note: '17 partes de água para 1 de café' },
    filter: { name: 'Coado (normal)', note: 'A proporção mais segura para começar' },
    'filter-strong': { name: 'Coado (forte)', note: 'Menos acidez, mais corpo' },
    french: { name: 'Prensa francesa', note: 'Moagem grossa, quatro minutos de infusão' },
    coldbrew: { name: 'Concentrado de cold brew', note: 'Dilua antes de beber' },
    espresso: { name: 'Espresso', note: '1 parte de café para 2 de saída' },
  },
  ja: {
    'filter-light': { name: 'ハンドドリップ（薄め）', note: '湯17 : 豆1' },
    filter: { name: 'ハンドドリップ（ふつう）', note: 'いちばん無難な比率です' },
    'filter-strong': { name: 'ハンドドリップ（濃いめ）', note: '酸味が減り、ボディが増します' },
    french: { name: 'フレンチプレス', note: '粗く挽いて4分浸します' },
    coldbrew: { name: 'コールドブリュー原液', note: '薄めて飲みます' },
    espresso: { name: 'エスプレッソ', note: '豆1 : 抽出量2' },
  },
  de: {
    'filter-light': { name: 'Handfilter (mild)', note: '17 Teile Wasser auf 1 Kaffee' },
    filter: { name: 'Handfilter (normal)', note: 'Das sicherste Verhältnis zum Anfangen' },
    'filter-strong': { name: 'Handfilter (stark)', note: 'Weniger Säure, mehr Körper' },
    french: { name: 'French Press', note: 'Grob gemahlen, vier Minuten ziehen lassen' },
    coldbrew: { name: 'Cold-Brew-Konzentrat', note: 'Vor dem Trinken verdünnen' },
    espresso: { name: 'Espresso', note: '1 Teil Kaffee auf 2 Teile Auslauf' },
  },
  fr: {
    'filter-light': { name: 'Filtre (léger)', note: '17 parts d’eau pour 1 de café' },
    filter: { name: 'Filtre (standard)', note: 'Le ratio le plus sûr pour débuter' },
    'filter-strong': { name: 'Filtre (corsé)', note: 'Moins d’acidité, plus de corps' },
    french: { name: 'Presse française', note: 'Mouture grossière, quatre minutes d’infusion' },
    coldbrew: { name: 'Concentré de cold brew', note: 'À diluer avant de boire' },
    espresso: { name: 'Espresso', note: '1 part de café pour 2 en sortie' },
  },
  hi: {
    'filter-light': { name: 'पोर ओवर (हल्का)', note: '17 भाग पानी : 1 भाग कॉफ़ी' },
    filter: { name: 'पोर ओवर (सामान्य)', note: 'शुरू करने के लिए सबसे सुरक्षित अनुपात' },
    'filter-strong': { name: 'पोर ओवर (गाढ़ा)', note: 'खट्टापन कम, बॉडी ज़्यादा' },
    french: { name: 'फ़्रेंच प्रेस', note: 'मोटा पीसकर चार मिनट भिगोएँ' },
    coldbrew: { name: 'कोल्ड ब्रू सत', note: 'पतला करके पीजिए' },
    espresso: { name: 'एस्प्रेसो', note: '1 भाग कॉफ़ी : 2 भाग निकास' },
  },
};

/** 원두 분쇄도·시간 안내 (커피 도구) */
export const GRIND_INTL: Record<FoodLang, Record<string, string>> = {
  ko: {
    'filter-light': '중간 굵기 · 2분 30초~3분',
    filter: '중간 굵기 · 2분 30초~3분',
    'filter-strong': '중간보다 조금 곱게 · 3분',
    french: '아주 굵게 · 4분 담근 뒤 눌러 내리기',
    coldbrew: '굵게 · 냉장 12~16시간',
    espresso: '아주 곱게 · 25~30초 추출',
  },
  en: {
    'filter-light': 'Medium grind · 2:30–3:00',
    filter: 'Medium grind · 2:30–3:00',
    'filter-strong': 'Slightly finer than medium · 3:00',
    french: 'Very coarse · steep 4 minutes, then press',
    coldbrew: 'Coarse · 12–16 hours in the fridge',
    espresso: 'Very fine · 25–30 second shot',
  },
  es: {
    'filter-light': 'Molienda media · 2:30–3:00',
    filter: 'Molienda media · 2:30–3:00',
    'filter-strong': 'Algo más fina que media · 3:00',
    french: 'Muy gruesa · deja reposar 4 minutos y presiona',
    coldbrew: 'Gruesa · 12–16 horas en la nevera',
    espresso: 'Muy fina · extracción de 25–30 segundos',
  },
  'pt-br': {
    'filter-light': 'Moagem média · 2:30–3:00',
    filter: 'Moagem média · 2:30–3:00',
    'filter-strong': 'Um pouco mais fina que média · 3:00',
    french: 'Bem grossa · quatro minutos de infusão e depois pressione',
    coldbrew: 'Grossa · 12–16 horas na geladeira',
    espresso: 'Bem fina · extração de 25–30 segundos',
  },
  ja: {
    'filter-light': '中挽き · 2分30秒〜3分',
    filter: '中挽き · 2分30秒〜3分',
    'filter-strong': '中挽きより少し細かく · 3分',
    french: 'かなり粗挽き · 4分浸してから押し下げる',
    coldbrew: '粗挽き · 冷蔵で12〜16時間',
    espresso: '極細挽き · 25〜30秒で抽出',
  },
  de: {
    'filter-light': 'Mittlerer Mahlgrad · 2:30–3:00',
    filter: 'Mittlerer Mahlgrad · 2:30–3:00',
    'filter-strong': 'Etwas feiner als mittel · 3:00',
    french: 'Sehr grob · 4 Minuten ziehen lassen, dann pressen',
    coldbrew: 'Grob · 12–16 Stunden im Kühlschrank',
    espresso: 'Sehr fein · 25–30 Sekunden Bezug',
  },
  fr: {
    'filter-light': 'Mouture moyenne · 2:30–3:00',
    filter: 'Mouture moyenne · 2:30–3:00',
    'filter-strong': 'Un peu plus fine que moyenne · 3:00',
    french: 'Très grossière · laisse infuser 4 minutes puis presse',
    coldbrew: 'Grossière · 12–16 heures au frigo',
    espresso: 'Très fine · extraction de 25–30 secondes',
  },
  hi: {
    'filter-light': 'मध्यम पीस · 2:30–3:00',
    filter: 'मध्यम पीस · 2:30–3:00',
    'filter-strong': 'मध्यम से ज़रा बारीक · 3:00',
    french: 'बहुत मोटा · 4 मिनट भिगोकर दबाएँ',
    coldbrew: 'मोटा · फ़्रिज में 12–16 घंटे',
    espresso: 'बहुत बारीक · 25–30 सेकंड में निकास',
  },
};

/** STORAGE 배열 순서 → 이름·분류·기간·요령 */
export const STORAGE_INTL: Record<FoodLang, { name: string; category: string; fridge: string; freezer: string; tip: string }[]> = {
  ko: [
    { name: '생닭', category: '육류', fridge: '1~2일', freezer: '9개월', tip: '핏물을 닦아 밀폐해 두면 냄새가 덜합니다' },
    { name: '다진 고기', category: '육류', fridge: '1~2일', freezer: '3~4개월', tip: '표면적이 넓어 가장 빨리 상합니다' },
    { name: '소·돼지 덩어리', category: '육류', fridge: '3~5일', freezer: '6~12개월', tip: '한 번 쓸 만큼 나눠 얼리세요' },
    { name: '생선(흰살)', category: '수산물', fridge: '1~2일', freezer: '6개월', tip: '내장을 빼고 물기를 없앤 뒤 보관하세요' },
    { name: '새우·조개', category: '수산물', fridge: '1~2일', freezer: '3~6개월', tip: '해동 후 재냉동하지 마세요' },
    { name: '우유', category: '유제품', fridge: '개봉 후 2~3일', freezer: '권장하지 않음', tip: '문쪽은 온도가 높아 안쪽에 두세요' },
    { name: '치즈(경성)', category: '유제품', fridge: '3~4주', freezer: '6개월', tip: '얼리면 부스러지므로 요리용으로만' },
    { name: '달걀', category: '유제품', fridge: '3~5주', freezer: '푼 것만 1년', tip: '씻지 말고 뾰족한 쪽을 아래로 두세요' },
    { name: '밥(지은 것)', category: '조리식품', fridge: '1일', freezer: '1개월', tip: '따뜻할 때 바로 얼려야 맛이 남습니다' },
    { name: '국·찌개', category: '조리식품', fridge: '2~3일', freezer: '2~3개월', tip: '식힌 뒤 넣고, 다시 데울 때 팔팔 끓이세요' },
    { name: '두부(개봉)', category: '조리식품', fridge: '2~3일', freezer: '3개월', tip: '물에 담가 매일 물을 갈아 주세요' },
    { name: '잎채소', category: '채소·과일', fridge: '3~7일', freezer: '데쳐서 8개월', tip: '물기를 없애고 키친타월과 함께 넣으세요' },
    { name: '감자·양파', category: '채소·과일', fridge: '넣지 마세요', freezer: '조리 후 3개월', tip: '서늘하고 어두운 곳에 따로 보관하세요' },
    { name: '바나나·토마토', category: '채소·과일', fridge: '익은 뒤 2~3일', freezer: '으깨서 3개월', tip: '덜 익었으면 실온에 두세요' },
  ],
  en: [
    { name: 'Raw chicken', category: 'Meat', fridge: '1–2 days', freezer: '9 months', tip: 'Pat off the blood and seal it — it smells far less' },
    { name: 'Minced meat', category: 'Meat', fridge: '1–2 days', freezer: '3–4 months', tip: 'All that surface area makes it spoil the fastest' },
    { name: 'Beef or pork joint', category: 'Meat', fridge: '3–5 days', freezer: '6–12 months', tip: 'Freeze it in portions you will use at once' },
    { name: 'White fish', category: 'Seafood', fridge: '1–2 days', freezer: '6 months', tip: 'Gut it and dry it off before storing' },
    { name: 'Prawns and shellfish', category: 'Seafood', fridge: '1–2 days', freezer: '3–6 months', tip: 'Never refreeze after thawing' },
    { name: 'Milk', category: 'Dairy', fridge: '2–3 days once open', freezer: 'Not recommended', tip: 'The door is the warmest spot — keep it further in' },
    { name: 'Hard cheese', category: 'Dairy', fridge: '3–4 weeks', freezer: '6 months', tip: 'Freezing makes it crumbly, so use it for cooking' },
    { name: 'Eggs', category: 'Dairy', fridge: '3–5 weeks', freezer: '1 year, beaten only', tip: 'Do not wash them, and store pointed end down' },
    { name: 'Cooked rice', category: 'Cooked food', fridge: '1 day', freezer: '1 month', tip: 'Freeze it while still warm to keep the texture' },
    { name: 'Soups and stews', category: 'Cooked food', fridge: '2–3 days', freezer: '2–3 months', tip: 'Cool it before it goes in, and boil it hard when reheating' },
    { name: 'Tofu (opened)', category: 'Cooked food', fridge: '2–3 days', freezer: '3 months', tip: 'Keep it under water and change the water daily' },
    { name: 'Leafy greens', category: 'Produce', fridge: '3–7 days', freezer: '8 months blanched', tip: 'Dry them off and store with a paper towel' },
    { name: 'Potatoes and onions', category: 'Produce', fridge: 'Do not refrigerate', freezer: '3 months once cooked', tip: 'Store them apart, somewhere cool and dark' },
    { name: 'Bananas and tomatoes', category: 'Produce', fridge: '2–3 days once ripe', freezer: '3 months mashed', tip: 'Leave them at room temperature until ripe' },
  ],
  es: [
    { name: 'Pollo crudo', category: 'Carne', fridge: '1–2 días', freezer: '9 meses', tip: 'Sécalo de la sangre y ciérralo bien — huele mucho menos' },
    { name: 'Carne picada', category: 'Carne', fridge: '1–2 días', freezer: '3–4 meses', tip: 'Tanta superficie expuesta la echa a perder antes que nada' },
    { name: 'Pieza de vacuno o cerdo', category: 'Carne', fridge: '3–5 días', freezer: '6–12 meses', tip: 'Congélala en raciones que vayas a usar de una vez' },
    { name: 'Pescado blanco', category: 'Pescado', fridge: '1–2 días', freezer: '6 meses', tip: 'Destrípalo y sécalo antes de guardarlo' },
    { name: 'Gambas y moluscos', category: 'Pescado', fridge: '1–2 días', freezer: '3–6 meses', tip: 'Nunca vuelvas a congelarlos después de descongelar' },
    { name: 'Leche', category: 'Lácteos', fridge: '2–3 días una vez abierta', freezer: 'No se recomienda', tip: 'La puerta es la zona más cálida — déjala más al fondo' },
    { name: 'Queso curado', category: 'Lácteos', fridge: '3–4 semanas', freezer: '6 meses', tip: 'Al congelarlo se desmiga, así que úsalo para cocinar' },
    { name: 'Huevos', category: 'Lácteos', fridge: '3–5 semanas', freezer: '1 año, solo batidos', tip: 'No los laves y guárdalos con la punta hacia abajo' },
    { name: 'Arroz cocido', category: 'Comida cocinada', fridge: '1 día', freezer: '1 mes', tip: 'Congélalo aún caliente para que no pierda textura' },
    { name: 'Sopas y guisos', category: 'Comida cocinada', fridge: '2–3 días', freezer: '2–3 meses', tip: 'Enfríalos antes de guardarlos y hiérvelos bien al recalentar' },
    { name: 'Tofu (abierto)', category: 'Comida cocinada', fridge: '2–3 días', freezer: '3 meses', tip: 'Mantenlo cubierto de agua y cámbiala a diario' },
    { name: 'Verduras de hoja', category: 'Frutas y verduras', fridge: '3–7 días', freezer: '8 meses escaldadas', tip: 'Sécalas y guárdalas con papel de cocina' },
    { name: 'Patatas y cebollas', category: 'Frutas y verduras', fridge: 'No las metas en la nevera', freezer: '3 meses una vez cocinadas', tip: 'Guárdalas separadas, en un sitio fresco y oscuro' },
    { name: 'Plátanos y tomates', category: 'Frutas y verduras', fridge: '2–3 días ya maduros', freezer: '3 meses en puré', tip: 'Déjalos a temperatura ambiente hasta que maduren' },
  ],
  'pt-br': [
    { name: 'Frango cru', category: 'Carne', fridge: '1–2 dias', freezer: '9 meses', tip: 'Seque o sangue e feche bem — cheira muito menos' },
    { name: 'Carne moída', category: 'Carne', fridge: '1–2 dias', freezer: '3–4 meses', tip: 'Tanta superfície exposta faz estragar mais rápido que tudo' },
    { name: 'Peça de boi ou porco', category: 'Carne', fridge: '3–5 dias', freezer: '6–12 meses', tip: 'Congele em porções que você vá usar de uma vez' },
    { name: 'Peixe branco', category: 'Peixes', fridge: '1–2 dias', freezer: '6 meses', tip: 'Limpe as tripas e seque antes de guardar' },
    { name: 'Camarão e mariscos', category: 'Peixes', fridge: '1–2 dias', freezer: '3–6 meses', tip: 'Nunca congele de novo depois de descongelar' },
    { name: 'Leite', category: 'Lácteos', fridge: '2–3 dias depois de aberto', freezer: 'Não recomendado', tip: 'A porta é a parte mais quente — deixe mais para dentro' },
    { name: 'Queijo duro', category: 'Lácteos', fridge: '3–4 semanas', freezer: '6 meses', tip: 'Congelado ele esfarela, então use para cozinhar' },
    { name: 'Ovos', category: 'Lácteos', fridge: '3–5 semanas', freezer: '1 ano, só batidos', tip: 'Não lave e guarde com a ponta para baixo' },
    { name: 'Arroz cozido', category: 'Comida pronta', fridge: '1 dia', freezer: '1 mês', tip: 'Congele ainda quente para não perder a textura' },
    { name: 'Sopas e ensopados', category: 'Comida pronta', fridge: '2–3 dias', freezer: '2–3 meses', tip: 'Esfrie antes de guardar e ferva bem ao reaquecer' },
    { name: 'Tofu (aberto)', category: 'Comida pronta', fridge: '2–3 dias', freezer: '3 meses', tip: 'Deixe coberto de água e troque a água todo dia' },
    { name: 'Folhas verdes', category: 'Frutas e verduras', fridge: '3–7 dias', freezer: '8 meses branqueadas', tip: 'Seque e guarde com papel toalha' },
    { name: 'Batata e cebola', category: 'Frutas e verduras', fridge: 'Não coloque na geladeira', freezer: '3 meses depois de cozidas', tip: 'Guarde separadas, em lugar fresco e escuro' },
    { name: 'Banana e tomate', category: 'Frutas e verduras', fridge: '2–3 dias já maduros', freezer: '3 meses amassados', tip: 'Deixe em temperatura ambiente até amadurecer' },
  ],
  ja: [
    { name: '生の鶏肉', category: '肉類', fridge: '1〜2日', freezer: '9か月', tip: '血をふき取って密閉すると匂いがぐっと減ります' },
    { name: 'ひき肉', category: '肉類', fridge: '1〜2日', freezer: '3〜4か月', tip: '表面積が広いのでいちばん早く傷みます' },
    { name: '牛・豚のかたまり肉', category: '肉類', fridge: '3〜5日', freezer: '6〜12か月', tip: '一度に使う分に分けて凍らせてください' },
    { name: '白身魚', category: '魚介', fridge: '1〜2日', freezer: '6か月', tip: '内臓を取り、水気をふいてから保存してください' },
    { name: 'えび・貝', category: '魚介', fridge: '1〜2日', freezer: '3〜6か月', tip: '解凍したものを再冷凍しないでください' },
    { name: '牛乳', category: '乳製品', fridge: '開封後2〜3日', freezer: 'おすすめしません', tip: 'ドアポケットは温度が高いので奥に置いてください' },
    { name: 'ハードチーズ', category: '乳製品', fridge: '3〜4週間', freezer: '6か月', tip: '凍らせるとぼろぼろになるので料理用に' },
    { name: '卵', category: '乳製品', fridge: '3〜5週間', freezer: 'ときほぐしたものだけ1年', tip: '洗わずに、とがったほうを下にして置いてください' },
    { name: '炊いたご飯', category: '調理済み', fridge: '1日', freezer: '1か月', tip: '温かいうちに凍らせると食感が残ります' },
    { name: 'スープ・煮もの', category: '調理済み', fridge: '2〜3日', freezer: '2〜3か月', tip: '冷ましてから入れ、温め直すときはしっかり煮立ててください' },
    { name: '豆腐（開封後）', category: '調理済み', fridge: '2〜3日', freezer: '3か月', tip: '水に浸して毎日水を替えてください' },
    { name: '葉物野菜', category: '野菜・果物', fridge: '3〜7日', freezer: '下ゆでして8か月', tip: '水気をふき、キッチンペーパーと一緒に入れてください' },
    { name: 'じゃがいも・玉ねぎ', category: '野菜・果物', fridge: '入れないでください', freezer: '調理後3か月', tip: '涼しく暗い場所に、別々に置いてください' },
    { name: 'バナナ・トマト', category: '野菜・果物', fridge: '熟してから2〜3日', freezer: 'つぶして3か月', tip: '熟していなければ常温に置いてください' },
  ],
  de: [
    { name: 'Rohes Hähnchen', category: 'Fleisch', fridge: '1–2 Tage', freezer: '9 Monate', tip: 'Blut abtupfen und luftdicht verpacken — riecht deutlich weniger' },
    { name: 'Hackfleisch', category: 'Fleisch', fridge: '1–2 Tage', freezer: '3–4 Monate', tip: 'Die große Oberfläche lässt es am schnellsten verderben' },
    { name: 'Rind- oder Schweinebraten', category: 'Fleisch', fridge: '3–5 Tage', freezer: '6–12 Monate', tip: 'In Portionen einfrieren, die du auf einmal verbrauchst' },
    { name: 'Weißfisch', category: 'Fisch', fridge: '1–2 Tage', freezer: '6 Monate', tip: 'Ausnehmen und trocken tupfen, bevor er in den Kühlschrank geht' },
    { name: 'Garnelen und Muscheln', category: 'Fisch', fridge: '1–2 Tage', freezer: '3–6 Monate', tip: 'Nach dem Auftauen nie wieder einfrieren' },
    { name: 'Milch', category: 'Milchprodukte', fridge: '2–3 Tage nach dem Öffnen', freezer: 'Nicht empfohlen', tip: 'Die Tür ist die wärmste Stelle — stell sie weiter nach hinten' },
    { name: 'Hartkäse', category: 'Milchprodukte', fridge: '3–4 Wochen', freezer: '6 Monate', tip: 'Nach dem Einfrieren krümelig — dann zum Kochen verwenden' },
    { name: 'Eier', category: 'Milchprodukte', fridge: '3–5 Wochen', freezer: '1 Jahr, nur verquirlt', tip: 'Nicht waschen und mit der Spitze nach unten lagern' },
    { name: 'Gekochter Reis', category: 'Gekochtes', fridge: '1 Tag', freezer: '1 Monat', tip: 'Noch warm einfrieren, dann bleibt die Konsistenz' },
    { name: 'Suppen und Eintöpfe', category: 'Gekochtes', fridge: '2–3 Tage', freezer: '2–3 Monate', tip: 'Vor dem Einstellen abkühlen lassen und beim Aufwärmen richtig aufkochen' },
    { name: 'Tofu (geöffnet)', category: 'Gekochtes', fridge: '2–3 Tage', freezer: '3 Monate', tip: 'Unter Wasser aufbewahren und das Wasser täglich wechseln' },
    { name: 'Blattgemüse', category: 'Obst und Gemüse', fridge: '3–7 Tage', freezer: '8 Monate blanchiert', tip: 'Trocken tupfen und mit einem Küchentuch lagern' },
    { name: 'Kartoffeln und Zwiebeln', category: 'Obst und Gemüse', fridge: 'Nicht in den Kühlschrank', freezer: '3 Monate nach dem Garen', tip: 'Getrennt lagern, kühl und dunkel' },
    { name: 'Bananen und Tomaten', category: 'Obst und Gemüse', fridge: '2–3 Tage, wenn reif', freezer: '3 Monate püriert', tip: 'Bis zur Reife bei Zimmertemperatur liegen lassen' },
  ],
  fr: [
    { name: 'Poulet cru', category: 'Viande', fridge: '1–2 jours', freezer: '9 mois', tip: 'Essuie le sang et referme bien — ça sent beaucoup moins' },
    { name: 'Viande hachée', category: 'Viande', fridge: '1–2 jours', freezer: '3–4 mois', tip: 'Toute cette surface exposée la fait tourner plus vite que le reste' },
    { name: 'Rôti de bœuf ou de porc', category: 'Viande', fridge: '3–5 jours', freezer: '6–12 mois', tip: 'Congèle en portions que tu utiliseras d’un coup' },
    { name: 'Poisson blanc', category: 'Poisson', fridge: '1–2 jours', freezer: '6 mois', tip: 'Vide-le et essuie-le avant de le ranger' },
    { name: 'Crevettes et coquillages', category: 'Poisson', fridge: '1–2 jours', freezer: '3–6 mois', tip: 'Ne les recongèle jamais après décongélation' },
    { name: 'Lait', category: 'Produits laitiers', fridge: '2–3 jours après ouverture', freezer: 'Déconseillé', tip: 'La porte est l’endroit le plus chaud — mets-le plus au fond' },
    { name: 'Fromage à pâte dure', category: 'Produits laitiers', fridge: '3–4 semaines', freezer: '6 mois', tip: 'Congelé il s’effrite, réserve-le à la cuisine' },
    { name: 'Œufs', category: 'Produits laitiers', fridge: '3–5 semaines', freezer: '1 an, battus seulement', tip: 'Ne les lave pas et range-les pointe vers le bas' },
    { name: 'Riz cuit', category: 'Plats cuisinés', fridge: '1 jour', freezer: '1 mois', tip: 'Congèle-le encore chaud pour garder la texture' },
    { name: 'Soupes et ragoûts', category: 'Plats cuisinés', fridge: '2–3 jours', freezer: '2–3 mois', tip: 'Laisse refroidir avant de ranger, et fais bien bouillir au réchauffage' },
    { name: 'Tofu (ouvert)', category: 'Plats cuisinés', fridge: '2–3 jours', freezer: '3 mois', tip: 'Garde-le immergé et change l’eau chaque jour' },
    { name: 'Légumes-feuilles', category: 'Fruits et légumes', fridge: '3–7 jours', freezer: '8 mois blanchis', tip: 'Essuie-les et range-les avec du papier absorbant' },
    { name: 'Pommes de terre et oignons', category: 'Fruits et légumes', fridge: 'Pas au réfrigérateur', freezer: '3 mois une fois cuits', tip: 'Range-les séparément, au frais et à l’abri de la lumière' },
    { name: 'Bananes et tomates', category: 'Fruits et légumes', fridge: '2–3 jours une fois mûres', freezer: '3 mois en purée', tip: 'Laisse-les à température ambiante jusqu’à maturité' },
  ],
  hi: [
    { name: 'कच्चा चिकन', category: 'मांस', fridge: '1–2 दिन', freezer: '9 महीने', tip: 'खून पोंछकर बंद डिब्बे में रखें — गंध बहुत कम आती है' },
    { name: 'कीमा', category: 'मांस', fridge: '1–2 दिन', freezer: '3–4 महीने', tip: 'सतह ज़्यादा खुली होने से यह सबसे पहले ख़राब होता है' },
    { name: 'गोमांस या सूअर का टुकड़ा', category: 'मांस', fridge: '3–5 दिन', freezer: '6–12 महीने', tip: 'एक बार में इस्तेमाल होने जितना बाँटकर जमाएँ' },
    { name: 'सफ़ेद मछली', category: 'मछली', fridge: '1–2 दिन', freezer: '6 महीने', tip: 'अंतड़ियाँ निकालकर और पानी सुखाकर रखें' },
    { name: 'झींगा और सीपी', category: 'मछली', fridge: '1–2 दिन', freezer: '3–6 महीने', tip: 'पिघलाने के बाद दोबारा कभी न जमाएँ' },
    { name: 'दूध', category: 'दुग्ध उत्पाद', fridge: 'खोलने के बाद 2–3 दिन', freezer: 'सलाह नहीं दी जाती', tip: 'दरवाज़े की तरफ़ तापमान ज़्यादा रहता है — भीतर रखें' },
    { name: 'सख़्त पनीर', category: 'दुग्ध उत्पाद', fridge: '3–4 हफ़्ते', freezer: '6 महीने', tip: 'जमाने पर भुरभुरा हो जाता है, इसलिए पकाने में इस्तेमाल करें' },
    { name: 'अंडे', category: 'दुग्ध उत्पाद', fridge: '3–5 हफ़्ते', freezer: 'फेंटे हुए ही 1 साल', tip: 'धोइए नहीं और नुकीला सिरा नीचे रखिए' },
    { name: 'पके चावल', category: 'पका खाना', fridge: '1 दिन', freezer: '1 महीना', tip: 'गरम रहते ही जमाएँ तो बनावट बची रहती है' },
    { name: 'सूप और सालन', category: 'पका खाना', fridge: '2–3 दिन', freezer: '2–3 महीने', tip: 'ठंडा करके रखें, और दोबारा गरम करते समय अच्छी तरह उबालें' },
    { name: 'टोफ़ू (खुला)', category: 'पका खाना', fridge: '2–3 दिन', freezer: '3 महीने', tip: 'पानी में डुबोकर रखें और हर दिन पानी बदलें' },
    { name: 'पत्तेदार सब्ज़ियाँ', category: 'फल और सब्ज़ी', fridge: '3–7 दिन', freezer: 'उबालकर 8 महीने', tip: 'पानी सुखाकर किचन पेपर के साथ रखें' },
    { name: 'आलू और प्याज़', category: 'फल और सब्ज़ी', fridge: 'फ़्रिज में न रखें', freezer: 'पकाने के बाद 3 महीने', tip: 'ठंडी अँधेरी जगह पर अलग-अलग रखें' },
    { name: 'केला और टमाटर', category: 'फल और सब्ज़ी', fridge: 'पकने के बाद 2–3 दिन', freezer: 'मसलकर 3 महीने', tip: 'कच्चे हों तो कमरे के तापमान पर रखें' },
  ],
};

/**
 * 보관 도구의 분류 탭 — 첫 항목은 '전체'.
 *
 * 두 번째부터는 위 STORAGE_INTL의 category와 글자까지 같아야 한다. 한 글자라도
 * 다르면 그 탭을 눌렀을 때 목록이 빈다.
 */
export const STORAGE_CATEGORIES: Record<FoodLang, string[]> = {
  ko: ['전체', '육류', '수산물', '유제품', '조리식품', '채소·과일'],
  en: ['All', 'Meat', 'Seafood', 'Dairy', 'Cooked food', 'Produce'],
  es: ['Todo', 'Carne', 'Pescado', 'Lácteos', 'Comida cocinada', 'Frutas y verduras'],
  'pt-br': ['Tudo', 'Carne', 'Peixes', 'Lácteos', 'Comida pronta', 'Frutas e verduras'],
  ja: ['すべて', '肉類', '魚介', '乳製品', '調理済み', '野菜・果物'],
  de: ['Alle', 'Fleisch', 'Fisch', 'Milchprodukte', 'Gekochtes', 'Obst und Gemüse'],
  fr: ['Tout', 'Viande', 'Poisson', 'Produits laitiers', 'Plats cuisinés', 'Fruits et légumes'],
  hi: ['सभी', 'मांस', 'मछली', 'दुग्ध उत्पाद', 'पका खाना', 'फल और सब्ज़ी'],
};
