import type { Metadata } from 'next';
import { alternateLanguages10, localeHref, openGraphFor, type AnyLocale10 } from './locales.ts';
import type { Lang } from './fortune-intl.ts';

/**
 * 운세(/fortune) 섹션의 라우트 메타데이터·허브 카드·공유 카드 문구.
 *
 * 결과 문장은 lib/fortune-l10n·match-l10n·dream-l10n·saju-l10n에, 화면 안의 UI는
 * components/fortune/*에 있다. 여기 모은 것은 페이지 밖에서 쓰이는 문구다 —
 * 검색 결과 제목, 허브 카드, 공유 카드. [[lib/snap-tools-intl.ts]]와 같은 구조다.
 *
 * slug·아이콘·색은 언어와 무관하니 FORTUNE_TOOLS에 한 번만 적고, 언어별로는
 * 사람이 읽는 네 문장만 갈아 끼운다.
 *
 * /fortune/card(타로 78장 사전)는 여기 없다 — 그쪽은 lib/tarot/route.ts가
 * 이미 열 언어를 갖고 있다.
 */
export type FortuneIntlLang = Exclude<Lang, 'ko'>;

export const FORTUNE_TOOLS = [
  { slug: 'daily', icon: '🔮', color: 'from-purple-500 to-pink-600', eyebrow: 'Daily Fortune', from: '#a855f7', to: '#db2777' },
  { slug: 'zodiac', icon: '⭐', color: 'from-violet-500 to-purple-700', eyebrow: 'Star Signs', from: '#8b5cf6', to: '#6d28d9' },
  { slug: 'animal', icon: '🐉', color: 'from-rose-500 to-pink-600', eyebrow: 'Chinese Zodiac', from: '#f43f5e', to: '#db2777' },
  { slug: 'blood-type', icon: '🩸', color: 'from-rose-500 to-red-600', eyebrow: 'Blood Type', from: '#f43f5e', to: '#dc2626' },
  { slug: 'biorhythm', icon: '📈', color: 'from-emerald-500 to-teal-600', eyebrow: 'Biorhythm', from: '#10b981', to: '#0d9488' },
  { slug: 'birth-stone', icon: '💎', color: 'from-fuchsia-500 to-violet-600', eyebrow: 'Birthstone', from: '#d946ef', to: '#7c3aed' },
  { slug: 'today-color', icon: '🎨', color: 'from-pink-500 to-violet-600', eyebrow: 'Lucky Colour', from: '#ec4899', to: '#7c3aed' },
  { slug: 'lucky-numbers', icon: '🍀', color: 'from-emerald-500 to-teal-600', eyebrow: 'Lucky Numbers', from: '#10b981', to: '#0d9488' },
  { slug: 'star-match', icon: '💞', color: 'from-violet-500 to-fuchsia-600', eyebrow: 'Star Match', from: '#8b5cf6', to: '#c026d3' },
  { slug: 'zodiac-match', icon: '🐲', color: 'from-rose-500 to-red-600', eyebrow: 'Zodiac Match', from: '#f43f5e', to: '#dc2626' },
  { slug: 'mbti-match', icon: '🧠', color: 'from-violet-500 to-indigo-600', eyebrow: 'MBTI Match', from: '#8b5cf6', to: '#4f46e5' },
  { slug: 'blood-match', icon: '🩸', color: 'from-rose-500 to-orange-600', eyebrow: 'Blood Match', from: '#f43f5e', to: '#ea580c' },
  { slug: 'mbti', icon: '🧠', color: 'from-sky-500 to-blue-600', eyebrow: 'MBTI', from: '#0ea5e9', to: '#2563eb' },
  { slug: 'daily-tarot', icon: '🃏', color: 'from-amber-500 to-orange-600', eyebrow: 'Daily Tarot', from: '#f59e0b', to: '#ea580c' },
  { slug: 'tarot-yesno', icon: '🔮', color: 'from-indigo-500 to-violet-700', eyebrow: 'Tarot Yes/No', from: '#6366f1', to: '#6d28d9' },
  { slug: 'tarot', icon: '🎴', color: 'from-violet-500 to-purple-700', eyebrow: 'Tarot Spread', from: '#8b5cf6', to: '#6d28d9' },
  { slug: 'dream', icon: '🌙', color: 'from-slate-700 to-indigo-800', eyebrow: 'Dream', from: '#334155', to: '#3730a3' },
  { slug: 'saju', icon: '🔯', color: 'from-indigo-500 to-violet-700', eyebrow: 'Saju', from: '#6366f1', to: '#6d28d9' },
] as const;

export type FortuneToolSlug = typeof FORTUNE_TOOLS[number]['slug'];

interface ToolCopy {
  /** 허브 카드·공유 카드에 쓰는 짧은 이름 */
  title: string;
  /** 허브 카드·공유 카드에 쓰는 한 줄 설명 */
  desc: string;
  /** 카드 오른쪽 끝의 작은 배지 — "12별자리"처럼 규모를 알린다 */
  badge: string;
  metaTitle: string;
  metaDesc: string;
}

interface HubCopy {
  title: string; lead: string; kicker: string;
  metaTitle: string; metaDesc: string;
  footer: string;
}

const HUB: Record<FortuneIntlLang, HubCopy> = {
  en: {
    title: 'Horoscopes', lead: 'Free daily readings — star signs, Chinese zodiac, tarot and more', kicker: 'Horoscopes',
    metaTitle: 'Free Daily Horoscope — Star Signs, Chinese Zodiac & Blood Type',
    metaDesc: 'Free daily horoscopes: read today’s reading by star sign, Chinese zodiac animal or blood type. Love, money, work and health, updated every day.',
    footer: 'Free daily horoscopes',
  },
  es: {
    title: 'Horóscopos', lead: 'Lecturas diarias gratis — signos, horóscopo chino, tarot y más', kicker: 'Horóscopos',
    metaTitle: 'Horóscopo diario gratis — Signos, horóscopo chino y grupo sanguíneo',
    metaDesc: 'Horóscopos diarios gratis: lee la lectura de hoy por signo del zodiaco, animal del horóscopo chino o grupo sanguíneo. Amor, dinero, trabajo y salud, actualizado cada día.',
    footer: 'Horóscopos diarios gratis',
  },
  'pt-br': {
    title: 'Horóscopos', lead: 'Leituras diárias grátis — signos, horóscopo chinês, tarô e mais', kicker: 'Horóscopos',
    metaTitle: 'Horóscopo diário grátis — Signos, horóscopo chinês e tipo sanguíneo',
    metaDesc: 'Horóscopos diários grátis: leia a leitura de hoje por signo, animal do horóscopo chinês ou tipo sanguíneo. Amor, dinheiro, trabalho e saúde, atualizado todo dia.',
    footer: 'Horóscopos diários grátis',
  },
  ja: {
    title: '占い', lead: '無料の毎日の運勢 — 星座、干支、タロットなど', kicker: '占い',
    metaTitle: '無料の今日の運勢 — 星座・干支・血液型',
    metaDesc: '無料の毎日の占い。星座、干支、血液型から今日の運勢を読めます。恋愛・金運・仕事・健康、毎日更新。',
    footer: '無料の毎日の占い',
  },
  de: {
    title: 'Horoskope', lead: 'Kostenlose Tageshoroskope — Sternzeichen, chinesischer Tierkreis, Tarot und mehr', kicker: 'Horoskope',
    metaTitle: 'Kostenloses Tageshoroskop — Sternzeichen, chinesischer Tierkreis & Blutgruppe',
    metaDesc: 'Kostenlose Tageshoroskope: lies die Lesung von heute nach Sternzeichen, chinesischem Tierkreiszeichen oder Blutgruppe. Liebe, Geld, Beruf und Gesundheit, täglich aktualisiert.',
    footer: 'Kostenlose Tageshoroskope',
  },
  fr: {
    title: 'Horoscopes', lead: 'Lectures quotidiennes gratuites — signes, horoscope chinois, tarot et plus', kicker: 'Horoscopes',
    metaTitle: 'Horoscope du jour gratuit — Signes, horoscope chinois et groupe sanguin',
    metaDesc: 'Horoscopes quotidiens gratuits : lisez la lecture du jour par signe du zodiaque, animal de l’horoscope chinois ou groupe sanguin. Amour, argent, travail et santé, mis à jour chaque jour.',
    footer: 'Horoscopes quotidiens gratuits',
  },
  hi: {
    title: 'राशिफल', lead: 'मुफ़्त दैनिक राशिफल — राशियाँ, चीनी राशिचक्र, टैरो और बहुत कुछ', kicker: 'राशिफल',
    metaTitle: 'मुफ़्त दैनिक राशिफल — राशियाँ, चीनी राशिचक्र और ब्लड ग्रुप',
    metaDesc: 'मुफ़्त दैनिक राशिफल: राशि, चीनी राशि-पशु या ब्लड ग्रुप से आज का हाल पढ़िए। प्रेम, धन, काम और सेहत, हर दिन अपडेट।',
    footer: 'मुफ़्त दैनिक राशिफल',
  },
  'zh-hans': {
    title: '运势', lead: '免费的每日运势——星座、生肖、塔罗等等', kicker: '运势',
    metaTitle: '免费每日运势 — 星座、生肖与血型',
    metaDesc: '免费的每日运势：按星座、生肖或血型看今天的运势。爱情、财运、事业和健康，每天更新。',
    footer: '免费的每日运势',
  },
  'zh-hant': {
    title: '運勢', lead: '免費的每日運勢——星座、生肖、塔羅等等', kicker: '運勢',
    metaTitle: '免費每日運勢 — 星座、生肖與血型',
    metaDesc: '免費的每日運勢：按星座、生肖或血型看今天的運勢。愛情、財運、事業和健康，每天更新。',
    footer: '免費的每日運勢',
  },
};

const TOOLS: Record<FortuneIntlLang, Record<FortuneToolSlug, ToolCopy>> = {
  en: {
    daily: { title: 'Today’s Horoscope', desc: 'Your reading from your birth date', badge: 'Daily',
      metaTitle: 'Today’s Horoscope by Birth Date — Free Daily Reading',
      metaDesc: 'Enter your date of birth for today’s free reading: overall, love, money, work and health, plus a lucky colour, number, direction and item. Updated daily.' },
    zodiac: { title: 'Daily Horoscope', desc: 'Today’s reading for all 12 star signs', badge: '12 signs',
      metaTitle: 'Daily Horoscope — All 12 Star Signs, Free',
      metaDesc: 'Read today’s free horoscope for all 12 star signs: love, money, work and health, with a lucky colour, number and item. Updated every day.' },
    animal: { title: 'Chinese Zodiac', desc: 'Today’s reading for all 12 animals', badge: '12 animals',
      metaTitle: 'Chinese Zodiac Horoscope — Today’s Reading for All 12 Animals',
      metaDesc: 'Today’s free Chinese zodiac horoscope for Rat, Ox, Tiger, Rabbit, Dragon, Snake, Horse, Goat, Monkey, Rooster, Dog and Pig — love, money, work and health.' },
    'blood-type': { title: 'Blood Type Horoscope', desc: 'Today’s reading for A, B, O and AB', badge: '4 types',
      metaTitle: 'Blood Type Horoscope — A, B, O and AB Today',
      metaDesc: 'Today’s free blood type horoscope for A, B, O and AB — love, money, work and health, plus a lucky colour, number and item. Updated daily.' },
    biorhythm: { title: 'Biorhythm Calculator', desc: 'Chart your physical, emotional and intellectual cycles', badge: 'Chart',
      metaTitle: 'Biorhythm Calculator — Physical, Emotional & Intellectual',
      metaDesc: 'Free biorhythm calculator: enter your date of birth to chart your 23-day physical, 28-day emotional and 33-day intellectual cycles, with critical days marked.' },
    'birth-stone': { title: 'Birthstone & Flower', desc: 'The gem and flower of your birth month', badge: '12 months',
      metaTitle: 'Birthstone & Birth Flower by Month — Meanings',
      metaDesc: 'Find your birthstone and birth flower by birth month, from garnet in January to turquoise in December, with what each one traditionally stands for.' },
    'today-color': { title: 'Today’s Lucky Colour', desc: 'Your colour for today — and the one to skip', badge: 'Daily',
      metaTitle: 'Today’s Lucky Colour — Free Daily Colour Reading',
      metaDesc: 'Find today’s lucky colour and the colour to skip, with what each one means and a tip for the day. Free, instant, updated daily.' },
    'lucky-numbers': { title: 'Lucky Numbers', desc: 'Six numbers from your birth date', badge: 'Daily',
      metaTitle: 'Today’s Lucky Numbers — Six Numbers From Your Birth Date',
      metaDesc: 'Get six lucky numbers from 1–45 generated from your date of birth and today’s date, plus a lucky direction, day and time. Free and for fun.' },
    'star-match': { title: 'Star Sign Compatibility', desc: 'How two signs match by element', badge: '12 signs',
      metaTitle: 'Star Sign Compatibility — All 12 Zodiac Pairings',
      metaDesc: 'Check star sign compatibility for any two signs based on their elements — fire, earth, air and water — with a score, what it means and advice.' },
    'zodiac-match': { title: 'Chinese Zodiac Compatibility', desc: 'Six Harmonies, Three Harmonies and clashes', badge: '12 animals',
      metaTitle: 'Chinese Zodiac Compatibility — All 12 Animal Pairings',
      metaDesc: 'Check Chinese zodiac compatibility for any two animals using the traditional Six Harmonies, Three Harmonies and clash relationships, with a score and advice.' },
    'mbti-match': { title: 'MBTI Compatibility', desc: 'How two of the 16 types line up', badge: '16 types',
      metaTitle: 'MBTI Compatibility — Match Any Two of the 16 Types',
      metaDesc: 'Check MBTI compatibility between any two of the 16 types. See how the E/I, N/S, T/F and J/P axes line up, with a score and practical advice.' },
    'blood-match': { title: 'Blood Type Compatibility', desc: 'How A, B, O and AB pair up', badge: '4 types',
      metaTitle: 'Blood Type Compatibility — A, B, O and AB Pairings',
      metaDesc: 'Check blood type compatibility for any two of A, B, O and AB, with a score, what drives the pairing, how it plays out in a relationship and advice.' },
    mbti: { title: 'MBTI Daily Horoscope', desc: 'Today’s reading for all 16 types', badge: '16 types',
      metaTitle: 'MBTI Daily Horoscope — All 16 Personality Types',
      metaDesc: 'Today’s free horoscope for all 16 MBTI types: love, money, work and health, plus a lucky colour, number and item. Updated every day.' },
    'daily-tarot': { title: 'Today’s Tarot', desc: 'One card from the major arcana', badge: 'Daily',
      metaTitle: 'Today’s Tarot Card — One Card, Free, Daily',
      metaDesc: 'Draw today’s tarot card from the 22 major arcana. Chosen from the date, so it stays the same all day. Free, with upright and reversed readings.' },
    'tarot-yesno': { title: 'Tarot Yes or No', desc: 'Draw one card for an answer', badge: 'Draw',
      metaTitle: 'Tarot Yes or No — Draw One Card',
      metaDesc: 'Hold a question in mind and draw a single tarot card for a yes, no or not-yet answer. Free, with the full card reading.' },
    tarot: { title: 'Tarot Reading', desc: 'Full 78-card deck, four spreads', badge: 'Spread',
      metaTitle: 'Tarot Reading Online — Free 78-Card Spreads',
      metaDesc: 'Draw a free tarot reading from the full 78-card deck: one card, past-present-future, a relationship spread or the full Celtic cross. Upright and reversed meanings for every card.' },
    dream: { title: 'Dream Dictionary', desc: '20 common dream symbols', badge: '20',
      metaTitle: 'Dream Dictionary — 20 Common Dream Symbols Explained',
      metaDesc: 'What falling, losing teeth, flying, being chased and 16 other common dream symbols are traditionally read as, and which situations they tend to be reported in.' },
    saju: { title: 'Saju — Korean Four Pillars', desc: 'Your four-pillar chart from birth date', badge: 'Chart',
      metaTitle: 'Saju — Korean Four Pillars Reading, Free',
      metaDesc: 'Read your saju — the Korean four-pillar chart — from your date and time of birth: heavenly stems, earthly branches, five-element balance, ten gods and luck pillars. Also known as BaZi. Free, calculated in your browser.' },
  },
  es: {
    daily: { title: 'Horóscopo de hoy', desc: 'Tu lectura a partir de tu fecha de nacimiento', badge: 'Diario',
      metaTitle: 'Horóscopo de hoy por fecha de nacimiento — Lectura diaria gratis',
      metaDesc: 'Escribe tu fecha de nacimiento para la lectura gratis de hoy: general, amor, dinero, trabajo y salud, más un color, número, dirección y objeto de la suerte. Actualizado a diario.' },
    zodiac: { title: 'Horóscopo diario', desc: 'La lectura de hoy para los 12 signos', badge: '12 signos',
      metaTitle: 'Horóscopo diario — Los 12 signos del zodiaco, gratis',
      metaDesc: 'Lee el horóscopo gratis de hoy para los 12 signos: amor, dinero, trabajo y salud, con un color, número y objeto de la suerte. Actualizado cada día.' },
    animal: { title: 'Horóscopo chino', desc: 'La lectura de hoy para los 12 animales', badge: '12 animales',
      metaTitle: 'Horóscopo chino — La lectura de hoy para los 12 animales',
      metaDesc: 'Horóscopo chino gratis de hoy para Rata, Buey, Tigre, Conejo, Dragón, Serpiente, Caballo, Cabra, Mono, Gallo, Perro y Cerdo: amor, dinero, trabajo y salud.' },
    'blood-type': { title: 'Horóscopo por grupo sanguíneo', desc: 'La lectura de hoy para A, B, O y AB', badge: '4 grupos',
      metaTitle: 'Horóscopo por grupo sanguíneo — A, B, O y AB hoy',
      metaDesc: 'Horóscopo gratis de hoy por grupo sanguíneo para A, B, O y AB: amor, dinero, trabajo y salud, más color, número y objeto de la suerte. Actualizado a diario.' },
    biorhythm: { title: 'Calculadora de biorritmo', desc: 'Traza tus ciclos físico, emocional e intelectual', badge: 'Gráfico',
      metaTitle: 'Calculadora de biorritmo — Físico, emocional e intelectual',
      metaDesc: 'Calculadora de biorritmo gratis: escribe tu fecha de nacimiento para trazar los ciclos de 23 días (físico), 28 (emocional) y 33 (intelectual), con los días críticos marcados.' },
    'birth-stone': { title: 'Piedra y flor de nacimiento', desc: 'La gema y la flor de tu mes de nacimiento', badge: '12 meses',
      metaTitle: 'Piedra y flor de nacimiento por mes — Significados',
      metaDesc: 'Encuentra tu piedra y tu flor de nacimiento según el mes, del granate en enero a la turquesa en diciembre, con lo que cada una representa por tradición.' },
    'today-color': { title: 'Color de la suerte de hoy', desc: 'Tu color de hoy y el que conviene evitar', badge: 'Diario',
      metaTitle: 'El color de la suerte de hoy — Lectura diaria gratis',
      metaDesc: 'Descubre el color de la suerte de hoy y el que conviene saltarse, con lo que significa cada uno y un consejo para el día. Gratis, al momento, actualizado a diario.' },
    'lucky-numbers': { title: 'Números de la suerte', desc: 'Seis números desde tu fecha de nacimiento', badge: 'Diario',
      metaTitle: 'Números de la suerte de hoy — Seis números desde tu fecha de nacimiento',
      metaDesc: 'Consigue seis números de la suerte del 1 al 45 generados con tu fecha de nacimiento y la de hoy, más una dirección, un día y una hora de suerte. Gratis y para divertirse.' },
    'star-match': { title: 'Compatibilidad de signos', desc: 'Cómo encajan dos signos por su elemento', badge: '12 signos',
      metaTitle: 'Compatibilidad de signos — Todas las parejas del zodiaco',
      metaDesc: 'Comprueba la compatibilidad de dos signos cualesquiera según sus elementos —fuego, tierra, aire y agua— con una puntuación, lo que significa y consejos.' },
    'zodiac-match': { title: 'Compatibilidad del horóscopo chino', desc: 'Seis Armonías, Tres Armonías y choques', badge: '12 animales',
      metaTitle: 'Compatibilidad del horóscopo chino — Las 12 parejas de animales',
      metaDesc: 'Comprueba la compatibilidad de dos animales del horóscopo chino con las relaciones tradicionales de Seis Armonías, Tres Armonías y choque, con puntuación y consejos.' },
    'mbti-match': { title: 'Compatibilidad MBTI', desc: 'Cómo se alinean dos de los 16 tipos', badge: '16 tipos',
      metaTitle: 'Compatibilidad MBTI — Empareja dos de los 16 tipos',
      metaDesc: 'Comprueba la compatibilidad MBTI entre dos de los 16 tipos. Mira cómo se alinean los ejes E/I, N/S, T/F y J/P, con una puntuación y consejos prácticos.' },
    'blood-match': { title: 'Compatibilidad por grupo sanguíneo', desc: 'Cómo se emparejan A, B, O y AB', badge: '4 grupos',
      metaTitle: 'Compatibilidad por grupo sanguíneo — Parejas de A, B, O y AB',
      metaDesc: 'Comprueba la compatibilidad de dos grupos sanguíneos cualesquiera de A, B, O y AB, con puntuación, qué mueve la pareja, cómo se vive en una relación y consejos.' },
    mbti: { title: 'Horóscopo MBTI', desc: 'La lectura de hoy para los 16 tipos', badge: '16 tipos',
      metaTitle: 'Horóscopo diario MBTI — Los 16 tipos de personalidad',
      metaDesc: 'Horóscopo gratis de hoy para los 16 tipos MBTI: amor, dinero, trabajo y salud, más un color, número y objeto de la suerte. Actualizado cada día.' },
    'daily-tarot': { title: 'Tarot de hoy', desc: 'Una carta de los arcanos mayores', badge: 'Diario',
      metaTitle: 'La carta de tarot de hoy — Una carta, gratis, a diario',
      metaDesc: 'Saca la carta de tarot de hoy de los 22 arcanos mayores. Se elige a partir de la fecha, así que no cambia en todo el día. Gratis, con lecturas del derecho y del revés.' },
    'tarot-yesno': { title: 'Tarot sí o no', desc: 'Saca una carta para tener respuesta', badge: 'Tirada',
      metaTitle: 'Tarot sí o no — Saca una carta',
      metaDesc: 'Ten una pregunta en mente y saca una sola carta de tarot para un sí, un no o un todavía no. Gratis, con la lectura completa de la carta.' },
    tarot: { title: 'Tirada de tarot', desc: 'Baraja completa de 78, cuatro tiradas', badge: 'Tiradas',
      metaTitle: 'Tirada de tarot online — 78 cartas gratis',
      metaDesc: 'Haz una tirada de tarot gratis con la baraja completa de 78 cartas: una carta, pasado-presente-futuro, tirada de relación o la cruz celta entera. Significados del derecho e invertidos para cada carta.' },
    dream: { title: 'Diccionario de sueños', desc: '20 símbolos oníricos comunes', badge: '20',
      metaTitle: 'Diccionario de sueños — 20 símbolos comunes explicados',
      metaDesc: 'Cómo se leen tradicionalmente caer, perder los dientes, volar, ser perseguido y otros 16 símbolos oníricos comunes, y en qué situaciones se suelen reportar.' },
    saju: { title: 'Saju — Cuatro Pilares coreanos', desc: 'Tu carta de cuatro pilares por fecha de nacimiento', badge: 'Carta',
      metaTitle: 'Saju — Lectura de los Cuatro Pilares coreanos, gratis',
      metaDesc: 'Lee tu saju —la carta coreana de cuatro pilares— a partir de tu fecha y hora de nacimiento: troncos celestes, ramas terrestres, equilibrio de los cinco elementos, diez dioses y pilares de fortuna. También conocido como BaZi. Gratis, calculado en tu navegador.' },
  },
  'pt-br': {
    daily: { title: 'Horóscopo de hoje', desc: 'Sua leitura a partir da data de nascimento', badge: 'Diário',
      metaTitle: 'Horóscopo de hoje pela data de nascimento — Leitura diária grátis',
      metaDesc: 'Digite sua data de nascimento para a leitura grátis de hoje: geral, amor, dinheiro, trabalho e saúde, mais cor, número, direção e item da sorte. Atualizado todo dia.' },
    zodiac: { title: 'Horóscopo diário', desc: 'A leitura de hoje para os 12 signos', badge: '12 signos',
      metaTitle: 'Horóscopo diário — Os 12 signos, grátis',
      metaDesc: 'Leia o horóscopo grátis de hoje para os 12 signos: amor, dinheiro, trabalho e saúde, com cor, número e item da sorte. Atualizado todo dia.' },
    animal: { title: 'Horóscopo chinês', desc: 'A leitura de hoje para os 12 animais', badge: '12 animais',
      metaTitle: 'Horóscopo chinês — A leitura de hoje para os 12 animais',
      metaDesc: 'Horóscopo chinês grátis de hoje para Rato, Boi, Tigre, Coelho, Dragão, Serpente, Cavalo, Cabra, Macaco, Galo, Cachorro e Porco: amor, dinheiro, trabalho e saúde.' },
    'blood-type': { title: 'Horóscopo por tipo sanguíneo', desc: 'A leitura de hoje para A, B, O e AB', badge: '4 tipos',
      metaTitle: 'Horóscopo por tipo sanguíneo — A, B, O e AB hoje',
      metaDesc: 'Horóscopo grátis de hoje por tipo sanguíneo para A, B, O e AB: amor, dinheiro, trabalho e saúde, mais cor, número e item da sorte. Atualizado todo dia.' },
    biorhythm: { title: 'Calculadora de biorritmo', desc: 'Trace seus ciclos físico, emocional e intelectual', badge: 'Gráfico',
      metaTitle: 'Calculadora de biorritmo — Físico, emocional e intelectual',
      metaDesc: 'Calculadora de biorritmo grátis: digite sua data de nascimento para traçar os ciclos de 23 dias (físico), 28 (emocional) e 33 (intelectual), com os dias críticos marcados.' },
    'birth-stone': { title: 'Pedra e flor de nascimento', desc: 'A gema e a flor do seu mês de nascimento', badge: '12 meses',
      metaTitle: 'Pedra e flor de nascimento por mês — Significados',
      metaDesc: 'Descubra sua pedra e sua flor de nascimento pelo mês, da granada em janeiro à turquesa em dezembro, com o que cada uma representa pela tradição.' },
    'today-color': { title: 'A cor da sorte de hoje', desc: 'Sua cor de hoje — e a que é melhor evitar', badge: 'Diário',
      metaTitle: 'A cor da sorte de hoje — Leitura diária grátis',
      metaDesc: 'Descubra a cor da sorte de hoje e a que é melhor evitar, com o significado de cada uma e uma dica para o dia. Grátis, na hora, atualizado todo dia.' },
    'lucky-numbers': { title: 'Números da sorte', desc: 'Seis números da sua data de nascimento', badge: 'Diário',
      metaTitle: 'Números da sorte de hoje — Seis números da sua data de nascimento',
      metaDesc: 'Receba seis números da sorte de 1 a 45 gerados pela sua data de nascimento e pela data de hoje, mais uma direção, um dia e um horário de sorte. Grátis e por diversão.' },
    'star-match': { title: 'Compatibilidade de signos', desc: 'Como dois signos combinam pelo elemento', badge: '12 signos',
      metaTitle: 'Compatibilidade de signos — Todas as duplas do zodíaco',
      metaDesc: 'Confira a compatibilidade de dois signos quaisquer pelos seus elementos — fogo, terra, ar e água — com pontuação, o que significa e conselhos.' },
    'zodiac-match': { title: 'Compatibilidade do horóscopo chinês', desc: 'Seis Harmonias, Três Harmonias e choques', badge: '12 animais',
      metaTitle: 'Compatibilidade do horóscopo chinês — As 12 duplas de animais',
      metaDesc: 'Confira a compatibilidade de dois animais do horóscopo chinês pelas relações tradicionais de Seis Harmonias, Três Harmonias e choque, com pontuação e conselhos.' },
    'mbti-match': { title: 'Compatibilidade MBTI', desc: 'Como dois dos 16 tipos se alinham', badge: '16 tipos',
      metaTitle: 'Compatibilidade MBTI — Combine dois dos 16 tipos',
      metaDesc: 'Confira a compatibilidade MBTI entre dois dos 16 tipos. Veja como os eixos E/I, N/S, T/F e J/P se alinham, com pontuação e conselhos práticos.' },
    'blood-match': { title: 'Compatibilidade por tipo sanguíneo', desc: 'Como A, B, O e AB combinam', badge: '4 tipos',
      metaTitle: 'Compatibilidade por tipo sanguíneo — Duplas de A, B, O e AB',
      metaDesc: 'Confira a compatibilidade de dois tipos sanguíneos quaisquer entre A, B, O e AB, com pontuação, o que move a dupla, como isso aparece num relacionamento e conselhos.' },
    mbti: { title: 'Horóscopo MBTI', desc: 'A leitura de hoje para os 16 tipos', badge: '16 tipos',
      metaTitle: 'Horóscopo diário MBTI — Os 16 tipos de personalidade',
      metaDesc: 'Horóscopo grátis de hoje para os 16 tipos MBTI: amor, dinheiro, trabalho e saúde, mais cor, número e item da sorte. Atualizado todo dia.' },
    'daily-tarot': { title: 'Tarô de hoje', desc: 'Uma carta dos arcanos maiores', badge: 'Diário',
      metaTitle: 'A carta de tarô de hoje — Uma carta, grátis, todo dia',
      metaDesc: 'Tire a carta de tarô de hoje dos 22 arcanos maiores. Ela é escolhida pela data, então não muda o dia inteiro. Grátis, com leituras em pé e invertidas.' },
    'tarot-yesno': { title: 'Tarô sim ou não', desc: 'Tire uma carta para ter resposta', badge: 'Tiragem',
      metaTitle: 'Tarô sim ou não — Tire uma carta',
      metaDesc: 'Tenha uma pergunta em mente e tire uma única carta de tarô para um sim, um não ou um ainda não. Grátis, com a leitura completa da carta.' },
    tarot: { title: 'Tiragem de tarô', desc: 'Baralho completo de 78, quatro tiragens', badge: 'Tiragens',
      metaTitle: 'Tiragem de tarô online — 78 cartas grátis',
      metaDesc: 'Faça uma tiragem de tarô grátis com o baralho completo de 78 cartas: uma carta, passado-presente-futuro, tiragem de relacionamento ou a cruz celta inteira. Significados em pé e invertidos para cada carta.' },
    dream: { title: 'Dicionário dos sonhos', desc: '20 símbolos de sonho comuns', badge: '20',
      metaTitle: 'Dicionário dos sonhos — 20 símbolos comuns explicados',
      metaDesc: 'Como cair, perder os dentes, voar, ser perseguido e outros 16 símbolos de sonho comuns são lidos pela tradição, e em que situações costumam ser relatados.' },
    saju: { title: 'Saju — Quatro Pilares coreanos', desc: 'Seu mapa de quatro pilares pela data de nascimento', badge: 'Mapa',
      metaTitle: 'Saju — Leitura dos Quatro Pilares coreanos, grátis',
      metaDesc: 'Leia seu saju — o mapa coreano de quatro pilares — a partir da data e hora de nascimento: troncos celestes, ramos terrestres, equilíbrio dos cinco elementos, dez deuses e pilares de sorte. Também conhecido como BaZi. Grátis, calculado no seu navegador.' },
  },
  ja: {
    daily: { title: '今日の運勢', desc: '生年月日から読む今日の運勢', badge: '毎日',
      metaTitle: '生年月日でみる今日の運勢 — 無料の毎日占い',
      metaDesc: '生年月日を入れると今日の運勢が無料で出ます。総合・恋愛・金運・仕事・健康に、ラッキーカラー、ナンバー、方位、アイテムつき。毎日更新。' },
    zodiac: { title: '星座占い', desc: '12星座それぞれの今日の運勢', badge: '12星座',
      metaTitle: '星座占い — 12星座の今日の運勢、無料',
      metaDesc: '12星座すべての今日の運勢を無料で。恋愛・金運・仕事・健康に、ラッキーカラー、ナンバー、アイテムつき。毎日更新。' },
    animal: { title: '干支占い', desc: '十二支それぞれの今日の運勢', badge: '十二支',
      metaTitle: '干支占い — 十二支すべての今日の運勢',
      metaDesc: '子・丑・寅・卯・辰・巳・午・未・申・酉・戌・亥の今日の運勢を無料で。恋愛・金運・仕事・健康。' },
    'blood-type': { title: '血液型占い', desc: 'A・B・O・ABの今日の運勢', badge: '4型',
      metaTitle: '血液型占い — A・B・O・ABの今日',
      metaDesc: 'A型・B型・O型・AB型の今日の運勢を無料で。恋愛・金運・仕事・健康に、ラッキーカラー、ナンバー、アイテムつき。毎日更新。' },
    biorhythm: { title: 'バイオリズム計算', desc: '身体・感情・知性の三つのリズムをグラフで', badge: 'グラフ',
      metaTitle: 'バイオリズム計算 — 身体・感情・知性',
      metaDesc: '無料のバイオリズム計算。生年月日を入れると、身体23日・感情28日・知性33日の周期をグラフにし、要注意日も示します。' },
    'birth-stone': { title: '誕生石と誕生花', desc: '生まれ月の宝石と花', badge: '12か月',
      metaTitle: '月別の誕生石と誕生花 — その意味',
      metaDesc: '生まれ月の誕生石と誕生花を調べられます。1月のガーネットから12月のターコイズまで、それぞれが伝統的に何を表すかつき。' },
    'today-color': { title: '今日のラッキーカラー', desc: '今日の色と、避けたい色', badge: '毎日',
      metaTitle: '今日のラッキーカラー — 無料の毎日診断',
      metaDesc: '今日のラッキーカラーと控えたい色がわかります。それぞれの意味と今日のひとことつき。無料、その場で、毎日更新。' },
    'lucky-numbers': { title: 'ラッキーナンバー', desc: '生年月日から作る六つの数字', badge: '毎日',
      metaTitle: '今日のラッキーナンバー — 生年月日から六つ',
      metaDesc: '生年月日と今日の日付から1〜45の六つの数字を作ります。ラッキー方位・曜日・時間帯つき。無料、遊びとして。' },
    'star-match': { title: '星座の相性', desc: 'エレメントでみる二つの星座の噛み合い', badge: '12星座',
      metaTitle: '星座の相性 — 12星座すべての組み合わせ',
      metaDesc: '好きな二つの星座の相性を、火・地・風・水のエレメントからみます。点数と、その意味、アドバイスつき。' },
    'zodiac-match': { title: '干支の相性', desc: '六合・三合・相冲でみる', badge: '十二支',
      metaTitle: '干支の相性 — 十二支すべての組み合わせ',
      metaDesc: '好きな二つの干支の相性を、伝統的な六合・三合・相冲の関係からみます。点数とアドバイスつき。' },
    'mbti-match': { title: 'MBTIの相性', desc: '16タイプのうち二つの噛み合い', badge: '16タイプ',
      metaTitle: 'MBTIの相性 — 16タイプの好きな二つを',
      metaDesc: '16タイプのうち好きな二つのMBTI相性をみます。E/I・N/S・T/F・J/Pの四つの指標の並び方を、点数と実用的なアドバイスつきで。' },
    'blood-match': { title: '血液型の相性', desc: 'A・B・O・ABの組み合わせ', badge: '4型',
      metaTitle: '血液型の相性 — A・B・O・ABの組み合わせ',
      metaDesc: 'A・B・O・ABのうち好きな二つの相性をみます。点数、その組み合わせを動かしているもの、恋愛での出方、アドバイスつき。' },
    mbti: { title: 'MBTI占い', desc: '16タイプそれぞれの今日の運勢', badge: '16タイプ',
      metaTitle: 'MBTI占い — 16タイプすべての今日',
      metaDesc: 'MBTI16タイプすべての今日の運勢を無料で。恋愛・金運・仕事・健康に、ラッキーカラー、ナンバー、アイテムつき。毎日更新。' },
    'daily-tarot': { title: '今日のタロット', desc: '大アルカナから1枚', badge: '毎日',
      metaTitle: '今日のタロット — 1枚引き、無料、毎日',
      metaDesc: '大アルカナ22枚から今日の1枚を引きます。日付から選ばれるので一日中同じです。無料、正位置と逆位置の読みつき。' },
    'tarot-yesno': { title: 'タロット イエス／ノー', desc: '1枚引いて答えをみる', badge: '1枚引き',
      metaTitle: 'タロット イエス／ノー — 1枚引く',
      metaDesc: '質問を思い浮かべてタロットを1枚引き、はい・いいえ・まだ、のどれかで答えをみます。無料、カードの読みも全文。' },
    tarot: { title: 'タロット占い', desc: '78枚フルデッキ、四つのスプレッド', badge: 'スプレッド',
      metaTitle: 'タロット占い — 78枚フルデッキの無料スプレッド',
      metaDesc: '78枚のフルデッキで無料のタロット占い。1枚引き、過去・現在・未来、相手との関係、ケルト十字。全カードに正位置と逆位置の意味つき。' },
    dream: { title: '夢占い辞典', desc: 'よく見る夢の象徴20種', badge: '20',
      metaTitle: '夢占い辞典 — よく見る夢の象徴20種',
      metaDesc: '落ちる、歯が抜ける、飛ぶ、追いかけられる、ほか16種のよく見る夢が伝統的にどう読まれてきたか、どんな時期に報告されやすいか。' },
    saju: { title: '四柱推命（사주）', desc: '生年月日から出す四つの柱', badge: '命式',
      metaTitle: '四柱推命（사주） — 韓国式の四柱、無料',
      metaDesc: '生年月日と時刻から韓国式の四柱（사주）をみます。天干、地支、五行のバランス、十神、大運。中国では八字と呼ばれます。無料、ブラウザ内で計算。' },
  },
  de: {
    daily: { title: 'Tageshoroskop', desc: 'Deine Lesung aus dem Geburtsdatum', badge: 'Täglich',
      metaTitle: 'Tageshoroskop nach Geburtsdatum — Kostenlose Lesung',
      metaDesc: 'Gib dein Geburtsdatum ein für die kostenlose Lesung von heute: allgemein, Liebe, Geld, Beruf und Gesundheit, dazu Glücksfarbe, -zahl, -richtung und -bringer. Täglich aktualisiert.' },
    zodiac: { title: 'Tageshoroskop nach Sternzeichen', desc: 'Die Lesung von heute für alle 12 Sternzeichen', badge: '12 Zeichen',
      metaTitle: 'Tageshoroskop — Alle 12 Sternzeichen, kostenlos',
      metaDesc: 'Lies das kostenlose Horoskop von heute für alle 12 Sternzeichen: Liebe, Geld, Beruf und Gesundheit, mit Glücksfarbe, -zahl und -bringer. Täglich aktualisiert.' },
    animal: { title: 'Chinesisches Horoskop', desc: 'Die Lesung von heute für alle 12 Tiere', badge: '12 Tiere',
      metaTitle: 'Chinesisches Horoskop — Die Lesung von heute für alle 12 Tiere',
      metaDesc: 'Kostenloses chinesisches Horoskop von heute für Ratte, Büffel, Tiger, Hase, Drache, Schlange, Pferd, Ziege, Affe, Hahn, Hund und Schwein: Liebe, Geld, Beruf und Gesundheit.' },
    'blood-type': { title: 'Blutgruppen-Horoskop', desc: 'Die Lesung von heute für A, B, 0 und AB', badge: '4 Gruppen',
      metaTitle: 'Blutgruppen-Horoskop — A, B, 0 und AB heute',
      metaDesc: 'Kostenloses Blutgruppen-Horoskop von heute für A, B, 0 und AB: Liebe, Geld, Beruf und Gesundheit, dazu Glücksfarbe, -zahl und -bringer. Täglich aktualisiert.' },
    biorhythm: { title: 'Biorhythmus-Rechner', desc: 'Zeichne deinen körperlichen, emotionalen und geistigen Rhythmus', badge: 'Diagramm',
      metaTitle: 'Biorhythmus-Rechner — Körperlich, emotional & geistig',
      metaDesc: 'Kostenloser Biorhythmus-Rechner: Gib dein Geburtsdatum ein, um die Zyklen von 23 Tagen (körperlich), 28 (emotional) und 33 (geistig) zu zeichnen — mit markierten kritischen Tagen.' },
    'birth-stone': { title: 'Geburtsstein & Blume', desc: 'Edelstein und Blume deines Geburtsmonats', badge: '12 Monate',
      metaTitle: 'Geburtsstein und Geburtsblume nach Monat — Bedeutungen',
      metaDesc: 'Finde Geburtsstein und Geburtsblume nach Geburtsmonat, vom Granat im Januar bis zum Türkis im Dezember, mit dem, wofür sie überliefert stehen.' },
    'today-color': { title: 'Glücksfarbe für heute', desc: 'Deine Farbe für heute — und die, die du auslassen solltest', badge: 'Täglich',
      metaTitle: 'Glücksfarbe für heute — Kostenlose Tagesdeutung',
      metaDesc: 'Finde die Glücksfarbe für heute und die Farbe, die du auslassen solltest, mit der Bedeutung beider und einem Tipp für den Tag. Kostenlos, sofort, täglich aktualisiert.' },
    'lucky-numbers': { title: 'Glückszahlen', desc: 'Sechs Zahlen aus deinem Geburtsdatum', badge: 'Täglich',
      metaTitle: 'Glückszahlen für heute — Sechs Zahlen aus deinem Geburtsdatum',
      metaDesc: 'Erhalte sechs Glückszahlen von 1 bis 45, erzeugt aus deinem Geburtsdatum und dem heutigen Datum, dazu Glücksrichtung, -tag und -stunde. Kostenlos und zum Spaß.' },
    'star-match': { title: 'Sternzeichen-Kompatibilität', desc: 'Wie zwei Zeichen über ihre Elemente zusammenpassen', badge: '12 Zeichen',
      metaTitle: 'Sternzeichen-Kompatibilität — Alle 12 Tierkreis-Paarungen',
      metaDesc: 'Prüf die Kompatibilität zweier Sternzeichen anhand ihrer Elemente — Feuer, Erde, Luft und Wasser — mit Punktzahl, Bedeutung und Rat.' },
    'zodiac-match': { title: 'Chinesische Tierkreis-Kompatibilität', desc: 'Sechs Harmonien, Drei Harmonien und Kollisionen', badge: '12 Tiere',
      metaTitle: 'Chinesische Tierkreis-Kompatibilität — Alle 12 Tier-Paarungen',
      metaDesc: 'Prüf die Kompatibilität zweier chinesischer Tierkreiszeichen über die überlieferten Beziehungen der Sechs Harmonien, Drei Harmonien und Kollision, mit Punktzahl und Rat.' },
    'mbti-match': { title: 'MBTI-Kompatibilität', desc: 'Wie zwei der 16 Typen zusammenlaufen', badge: '16 Typen',
      metaTitle: 'MBTI-Kompatibilität — Zwei beliebige der 16 Typen',
      metaDesc: 'Prüf die MBTI-Kompatibilität zwischen zwei beliebigen der 16 Typen. Sieh, wie die Achsen E/I, N/S, T/F und J/P zusammenlaufen — mit Punktzahl und praktischem Rat.' },
    'blood-match': { title: 'Blutgruppen-Kompatibilität', desc: 'Wie A, B, 0 und AB zusammenpassen', badge: '4 Gruppen',
      metaTitle: 'Blutgruppen-Kompatibilität — Paarungen von A, B, 0 und AB',
      metaDesc: 'Prüf die Kompatibilität zweier beliebiger Blutgruppen aus A, B, 0 und AB, mit Punktzahl, was die Paarung trägt, wie sie sich in einer Beziehung zeigt, und Rat.' },
    mbti: { title: 'MBTI-Tageshoroskop', desc: 'Die Lesung von heute für alle 16 Typen', badge: '16 Typen',
      metaTitle: 'MBTI-Tageshoroskop — Alle 16 Persönlichkeitstypen',
      metaDesc: 'Kostenloses Horoskop von heute für alle 16 MBTI-Typen: Liebe, Geld, Beruf und Gesundheit, dazu Glücksfarbe, -zahl und -bringer. Täglich aktualisiert.' },
    'daily-tarot': { title: 'Tarot des Tages', desc: 'Eine Karte aus den großen Arkana', badge: 'Täglich',
      metaTitle: 'Die Tarotkarte des Tages — Eine Karte, kostenlos, täglich',
      metaDesc: 'Zieh die Tarotkarte des Tages aus den 22 großen Arkana. Sie wird aus dem Datum gewählt und bleibt den ganzen Tag gleich. Kostenlos, mit aufrechter und umgekehrter Deutung.' },
    'tarot-yesno': { title: 'Tarot Ja oder Nein', desc: 'Zieh eine Karte für eine Antwort', badge: 'Ziehen',
      metaTitle: 'Tarot Ja oder Nein — Eine Karte ziehen',
      metaDesc: 'Halt eine Frage im Kopf und zieh eine einzelne Tarotkarte für ein Ja, ein Nein oder ein Noch-nicht. Kostenlos, mit der vollständigen Kartendeutung.' },
    tarot: { title: 'Tarot legen', desc: 'Volles 78-Karten-Deck, vier Legungen', badge: 'Legungen',
      metaTitle: 'Tarot online legen — 78 Karten kostenlos',
      metaDesc: 'Leg dir kostenlos Tarot mit dem vollen 78-Karten-Deck: eine Karte, Vergangenheit-Gegenwart-Zukunft, eine Beziehungslegung oder das ganze keltische Kreuz. Bedeutungen aufrecht und umgekehrt für jede Karte.' },
    dream: { title: 'Traumdeutungs-Lexikon', desc: '20 häufige Traumsymbole', badge: '20',
      metaTitle: 'Traumdeutungs-Lexikon — 20 häufige Traumsymbole erklärt',
      metaDesc: 'Wie Fallen, Zahnverlust, Fliegen, Verfolgtwerden und 16 weitere häufige Traumsymbole überliefert gelesen werden, und in welchen Situationen sie berichtet werden.' },
    saju: { title: 'Saju — koreanische Vier Säulen', desc: 'Dein Vier-Säulen-Chart aus dem Geburtsdatum', badge: 'Chart',
      metaTitle: 'Saju — koreanische Vier-Säulen-Deutung, kostenlos',
      metaDesc: 'Lies dein Saju — das koreanische Vier-Säulen-Chart — aus Geburtsdatum und -zeit: Himmelsstämme, Erdzweige, Balance der fünf Elemente, Zehn Götter und Glückssäulen. Auch als BaZi bekannt. Kostenlos, im Browser berechnet.' },
  },
  fr: {
    daily: { title: 'Horoscope du jour', desc: 'Votre lecture d’après votre date de naissance', badge: 'Quotidien',
      metaTitle: 'Horoscope du jour selon la date de naissance — Lecture quotidienne gratuite',
      metaDesc: 'Saisissez votre date de naissance pour la lecture gratuite du jour : général, amour, argent, travail et santé, plus une couleur, un chiffre, une direction et un objet porte-bonheur. Mis à jour chaque jour.' },
    zodiac: { title: 'Horoscope quotidien', desc: 'La lecture du jour pour les 12 signes', badge: '12 signes',
      metaTitle: 'Horoscope quotidien — Les 12 signes du zodiaque, gratuit',
      metaDesc: 'Lisez l’horoscope gratuit du jour pour les 12 signes : amour, argent, travail et santé, avec une couleur, un chiffre et un objet porte-bonheur. Mis à jour chaque jour.' },
    animal: { title: 'Horoscope chinois', desc: 'La lecture du jour pour les 12 animaux', badge: '12 animaux',
      metaTitle: 'Horoscope chinois — La lecture du jour pour les 12 animaux',
      metaDesc: 'Horoscope chinois gratuit du jour pour Rat, Bœuf, Tigre, Lapin, Dragon, Serpent, Cheval, Chèvre, Singe, Coq, Chien et Cochon : amour, argent, travail et santé.' },
    'blood-type': { title: 'Horoscope par groupe sanguin', desc: 'La lecture du jour pour A, B, O et AB', badge: '4 groupes',
      metaTitle: 'Horoscope par groupe sanguin — A, B, O et AB aujourd’hui',
      metaDesc: 'Horoscope gratuit du jour par groupe sanguin pour A, B, O et AB : amour, argent, travail et santé, plus une couleur, un chiffre et un objet porte-bonheur. Mis à jour chaque jour.' },
    biorhythm: { title: 'Calculateur de biorythme', desc: 'Tracez vos rythmes physique, émotionnel et intellectuel', badge: 'Graphique',
      metaTitle: 'Calculateur de biorythme — Physique, émotionnel et intellectuel',
      metaDesc: 'Calculateur de biorythme gratuit : saisissez votre date de naissance pour tracer les cycles de 23 jours (physique), 28 (émotionnel) et 33 (intellectuel), jours critiques marqués.' },
    'birth-stone': { title: 'Pierre et fleur de naissance', desc: 'La gemme et la fleur de votre mois de naissance', badge: '12 mois',
      metaTitle: 'Pierre et fleur de naissance par mois — Significations',
      metaDesc: 'Trouvez votre pierre et votre fleur de naissance selon le mois, du grenat en janvier à la turquoise en décembre, avec ce que chacune représente par tradition.' },
    'today-color': { title: 'La couleur porte-bonheur du jour', desc: 'Votre couleur du jour — et celle à éviter', badge: 'Quotidien',
      metaTitle: 'La couleur porte-bonheur du jour — Lecture quotidienne gratuite',
      metaDesc: 'Découvrez la couleur porte-bonheur du jour et celle à éviter, avec ce que chacune signifie et un conseil pour la journée. Gratuit, immédiat, mis à jour chaque jour.' },
    'lucky-numbers': { title: 'Numéros porte-bonheur', desc: 'Six numéros d’après votre date de naissance', badge: 'Quotidien',
      metaTitle: 'Numéros porte-bonheur du jour — Six numéros d’après votre date de naissance',
      metaDesc: 'Obtenez six numéros porte-bonheur de 1 à 45 générés à partir de votre date de naissance et de la date du jour, plus une direction, un jour et une heure de chance. Gratuit et pour le plaisir.' },
    'star-match': { title: 'Compatibilité des signes', desc: 'Comment deux signes s’accordent par leur élément', badge: '12 signes',
      metaTitle: 'Compatibilité des signes — Toutes les paires du zodiaque',
      metaDesc: 'Vérifiez la compatibilité de deux signes selon leurs éléments — feu, terre, air et eau — avec un score, ce que cela signifie et des conseils.' },
    'zodiac-match': { title: 'Compatibilité de l’horoscope chinois', desc: 'Six Harmonies, Trois Harmonies et chocs', badge: '12 animaux',
      metaTitle: 'Compatibilité de l’horoscope chinois — Les 12 paires d’animaux',
      metaDesc: 'Vérifiez la compatibilité de deux animaux de l’horoscope chinois via les relations traditionnelles de Six Harmonies, Trois Harmonies et choc, avec un score et des conseils.' },
    'mbti-match': { title: 'Compatibilité MBTI', desc: 'Comment deux des 16 types s’alignent', badge: '16 types',
      metaTitle: 'Compatibilité MBTI — Associez deux des 16 types',
      metaDesc: 'Vérifiez la compatibilité MBTI entre deux des 16 types. Voyez comment les axes E/I, N/S, T/F et J/P s’alignent, avec un score et des conseils pratiques.' },
    'blood-match': { title: 'Compatibilité des groupes sanguins', desc: 'Comment A, B, O et AB s’associent', badge: '4 groupes',
      metaTitle: 'Compatibilité des groupes sanguins — Paires de A, B, O et AB',
      metaDesc: 'Vérifiez la compatibilité de deux groupes sanguins parmi A, B, O et AB, avec un score, ce qui porte la paire, comment cela se joue en couple, et des conseils.' },
    mbti: { title: 'Horoscope MBTI', desc: 'La lecture du jour pour les 16 types', badge: '16 types',
      metaTitle: 'Horoscope quotidien MBTI — Les 16 types de personnalité',
      metaDesc: 'Horoscope gratuit du jour pour les 16 types MBTI : amour, argent, travail et santé, plus une couleur, un chiffre et un objet porte-bonheur. Mis à jour chaque jour.' },
    'daily-tarot': { title: 'Tarot du jour', desc: 'Une carte des arcanes majeurs', badge: 'Quotidien',
      metaTitle: 'La carte de tarot du jour — Une carte, gratuit, chaque jour',
      metaDesc: 'Tirez la carte de tarot du jour parmi les 22 arcanes majeurs. Elle est choisie d’après la date et reste la même toute la journée. Gratuit, avec les lectures à l’endroit et à l’envers.' },
    'tarot-yesno': { title: 'Tarot oui ou non', desc: 'Tirez une carte pour avoir une réponse', badge: 'Tirage',
      metaTitle: 'Tarot oui ou non — Tirez une carte',
      metaDesc: 'Gardez une question en tête et tirez une seule carte de tarot pour un oui, un non ou un pas encore. Gratuit, avec la lecture complète de la carte.' },
    tarot: { title: 'Tirage de tarot', desc: 'Jeu complet de 78 cartes, quatre tirages', badge: 'Tirages',
      metaTitle: 'Tirage de tarot en ligne — 78 cartes gratuit',
      metaDesc: 'Faites un tirage de tarot gratuit avec le jeu complet de 78 cartes : une carte, passé-présent-futur, tirage de relation ou la croix celtique entière. Sens à l’endroit et à l’envers pour chaque carte.' },
    dream: { title: 'Dictionnaire des rêves', desc: '20 symboles oniriques courants', badge: '20',
      metaTitle: 'Dictionnaire des rêves — 20 symboles courants expliqués',
      metaDesc: 'Comment tomber, perdre ses dents, voler, être poursuivi et 16 autres symboles oniriques courants se lisent par tradition, et dans quelles situations on les rapporte.' },
    saju: { title: 'Saju — Quatre Piliers coréens', desc: 'Votre thème des quatre piliers d’après la date de naissance', badge: 'Thème',
      metaTitle: 'Saju — Lecture des Quatre Piliers coréens, gratuit',
      metaDesc: 'Lisez votre saju — le thème coréen des quatre piliers — d’après votre date et heure de naissance : troncs célestes, branches terrestres, équilibre des cinq éléments, dix dieux et piliers de chance. Aussi connu sous le nom de BaZi. Gratuit, calculé dans votre navigateur.' },
  },
  hi: {
    daily: { title: 'आज का राशिफल', desc: 'जन्म तिथि से आज का हाल', badge: 'रोज़',
      metaTitle: 'जन्म तिथि से आज का राशिफल — मुफ़्त दैनिक पढ़त',
      metaDesc: 'आज की मुफ़्त पढ़त के लिए जन्म तिथि भरिए: कुल, प्रेम, धन, काम और सेहत, साथ में भाग्यशाली रंग, अंक, दिशा और चीज़। हर दिन अपडेट।' },
    zodiac: { title: 'दैनिक राशिफल', desc: 'बारहों राशियों का आज का हाल', badge: '12 राशियाँ',
      metaTitle: 'दैनिक राशिफल — बारहों राशियाँ, मुफ़्त',
      metaDesc: 'बारहों राशियों का आज का मुफ़्त राशिफल पढ़िए: प्रेम, धन, काम और सेहत, साथ में भाग्यशाली रंग, अंक और चीज़। हर दिन अपडेट।' },
    animal: { title: 'चीनी राशिफल', desc: 'बारहों राशि-पशुओं का आज का हाल', badge: '12 पशु',
      metaTitle: 'चीनी राशिफल — बारहों पशुओं का आज का हाल',
      metaDesc: 'चूहा, बैल, बाघ, खरगोश, ड्रैगन, साँप, घोड़ा, बकरी, बंदर, मुर्गा, कुत्ता और सूअर का आज का मुफ़्त चीनी राशिफल: प्रेम, धन, काम और सेहत।' },
    'blood-type': { title: 'ब्लड ग्रुप राशिफल', desc: 'A, B, O और AB का आज का हाल', badge: '4 ग्रुप',
      metaTitle: 'ब्लड ग्रुप राशिफल — A, B, O और AB आज',
      metaDesc: 'A, B, O और AB का आज का मुफ़्त ब्लड ग्रुप राशिफल: प्रेम, धन, काम और सेहत, साथ में भाग्यशाली रंग, अंक और चीज़। हर दिन अपडेट।' },
    biorhythm: { title: 'बायोरिदम कैलकुलेटर', desc: 'अपनी शारीरिक, भावनात्मक और बौद्धिक लय बनाइए', badge: 'चार्ट',
      metaTitle: 'बायोरिदम कैलकुलेटर — शारीरिक, भावनात्मक और बौद्धिक',
      metaDesc: 'मुफ़्त बायोरिदम कैलकुलेटर: जन्म तिथि भरकर 23 दिन (शारीरिक), 28 (भावनात्मक) और 33 (बौद्धिक) के चक्र बनाइए, नाज़ुक दिन चिह्नित।' },
    'birth-stone': { title: 'जन्म रत्न और पुष्प', desc: 'आपके जन्म महीने का रत्न और फूल', badge: '12 महीने',
      metaTitle: 'महीने के हिसाब से जन्म रत्न और जन्म पुष्प — अर्थ',
      metaDesc: 'जन्म महीने के हिसाब से अपना रत्न और फूल जानिए, जनवरी के गार्नेट से दिसंबर के फ़िरोज़ा तक, और परंपरा में हर एक किसका प्रतीक है।' },
    'today-color': { title: 'आज का भाग्यशाली रंग', desc: 'आज का रंग — और जिससे बचना है', badge: 'रोज़',
      metaTitle: 'आज का भाग्यशाली रंग — मुफ़्त दैनिक पढ़त',
      metaDesc: 'आज का भाग्यशाली रंग और जिससे बचना बेहतर है, दोनों जानिए — हर एक का अर्थ और दिन के लिए एक सुझाव के साथ। मुफ़्त, तुरंत, हर दिन अपडेट।' },
    'lucky-numbers': { title: 'भाग्यशाली अंक', desc: 'जन्म तिथि से छह अंक', badge: 'रोज़',
      metaTitle: 'आज के भाग्यशाली अंक — जन्म तिथि से छह अंक',
      metaDesc: 'अपनी जन्म तिथि और आज की तारीख़ से 1 से 45 तक छह भाग्यशाली अंक पाइए, साथ में भाग्यशाली दिशा, दिन और समय। मुफ़्त और मज़े के लिए।' },
    'star-match': { title: 'राशियों की जोड़ी', desc: 'तत्व के हिसाब से दो राशियों का मेल', badge: '12 राशियाँ',
      metaTitle: 'राशियों की जोड़ी — बारहों राशियों के सभी मेल',
      metaDesc: 'किन्हीं दो राशियों का मेल उनके तत्वों — अग्नि, पृथ्वी, वायु और जल — के आधार पर देखिए, अंक, अर्थ और सलाह के साथ।' },
    'zodiac-match': { title: 'चीनी राशि की जोड़ी', desc: 'छह मेल, तीन मेल और टकराव', badge: '12 पशु',
      metaTitle: 'चीनी राशि की जोड़ी — बारहों पशुओं के सभी मेल',
      metaDesc: 'किन्हीं दो चीनी राशि-पशुओं का मेल परंपरागत छह मेल, तीन मेल और टकराव के रिश्तों से देखिए, अंक और सलाह के साथ।' },
    'mbti-match': { title: 'MBTI जोड़ी', desc: '16 में से दो टाइप कैसे मिलते हैं', badge: '16 टाइप',
      metaTitle: 'MBTI जोड़ी — 16 में से कोई दो टाइप मिलाइए',
      metaDesc: '16 में से किन्हीं दो MBTI टाइप का मेल देखिए। E/I, N/S, T/F और J/P अक्ष कैसे मिलते हैं, अंक और व्यावहारिक सलाह के साथ।' },
    'blood-match': { title: 'ब्लड ग्रुप जोड़ी', desc: 'A, B, O और AB कैसे मिलते हैं', badge: '4 ग्रुप',
      metaTitle: 'ब्लड ग्रुप जोड़ी — A, B, O और AB के मेल',
      metaDesc: 'A, B, O और AB में से किन्हीं दो का मेल देखिए, अंक, जोड़ी को क्या चलाता है, रिश्ते में यह कैसा रहता है, और सलाह के साथ।' },
    mbti: { title: 'MBTI राशिफल', desc: 'सोलहों टाइप का आज का हाल', badge: '16 टाइप',
      metaTitle: 'MBTI दैनिक राशिफल — सोलहों व्यक्तित्व टाइप',
      metaDesc: 'सोलहों MBTI टाइप का आज का मुफ़्त राशिफल: प्रेम, धन, काम और सेहत, साथ में भाग्यशाली रंग, अंक और चीज़। हर दिन अपडेट।' },
    'daily-tarot': { title: 'आज का टैरो', desc: 'मेजर अर्काना से एक कार्ड', badge: 'रोज़',
      metaTitle: 'आज का टैरो कार्ड — एक कार्ड, मुफ़्त, रोज़',
      metaDesc: '22 मेजर अर्काना में से आज का कार्ड निकालिए। यह तारीख़ से चुना जाता है, इसलिए पूरे दिन वही रहता है। मुफ़्त, सीधे और उल्टे अर्थ के साथ।' },
    'tarot-yesno': { title: 'टैरो हाँ या ना', desc: 'जवाब के लिए एक कार्ड निकालिए', badge: 'एक कार्ड',
      metaTitle: 'टैरो हाँ या ना — एक कार्ड निकालिए',
      metaDesc: 'मन में एक सवाल रखिए और हाँ, ना या अभी नहीं — के जवाब के लिए एक टैरो कार्ड निकालिए। मुफ़्त, कार्ड की पूरी पढ़त के साथ।' },
    tarot: { title: 'टैरो रीडिंग', desc: 'पूरा 78 कार्ड डेक, चार प्रसार', badge: 'प्रसार',
      metaTitle: 'ऑनलाइन टैरो रीडिंग — 78 कार्ड के मुफ़्त प्रसार',
      metaDesc: 'पूरे 78 कार्ड के डेक से मुफ़्त टैरो रीडिंग: एक कार्ड, अतीत-वर्तमान-भविष्य, रिश्ते का प्रसार या पूरा सेल्टिक क्रॉस। हर कार्ड के सीधे और उल्टे अर्थ के साथ।' },
    dream: { title: 'स्वप्न कोश', desc: 'बीस आम स्वप्न-प्रतीक', badge: '20',
      metaTitle: 'स्वप्न कोश — बीस आम स्वप्न-प्रतीक समझाए गए',
      metaDesc: 'गिरना, दाँत गिरना, उड़ना, पीछा किया जाना और सोलह अन्य आम स्वप्न-प्रतीक परंपरा में कैसे पढ़े जाते हैं, और किन हालात में इनकी चर्चा होती है।' },
    saju: { title: 'साजू — कोरियाई चार स्तंभ', desc: 'जन्म तिथि से आपकी चार-स्तंभ कुंडली', badge: 'कुंडली',
      metaTitle: 'साजू — कोरियाई चार स्तंभ पढ़त, मुफ़्त',
      metaDesc: 'जन्म तिथि और समय से अपना साजू — कोरियाई चार-स्तंभ कुंडली — पढ़िए: आकाशीय तने, पार्थिव शाखाएँ, पंच तत्वों का संतुलन, दस देव और भाग्य-स्तंभ। इसे बाज़ी भी कहते हैं। मुफ़्त, आपके ब्राउज़र में गणना।' },
  },
  'zh-hans': {
    daily: { title: '今日运势', desc: '按出生日期看今天的运势', badge: '每日',
      metaTitle: '按出生日期看今天的运势 — 免费每日运势',
      metaDesc: '填入出生日期就能看今天的免费运势：综合、爱情、财运、事业和健康，还有幸运色、数字、方位和物件。每天更新。' },
    zodiac: { title: '星座运势', desc: '十二星座各自今天的运势', badge: '12星座',
      metaTitle: '星座运势 — 十二星座今天的运势，免费',
      metaDesc: '免费看十二星座今天的运势：爱情、财运、事业和健康，附幸运色、数字和物件。每天更新。' },
    animal: { title: '生肖运势', desc: '十二生肖各自今天的运势', badge: '12生肖',
      metaTitle: '生肖运势 — 十二生肖今天的运势',
      metaDesc: '鼠、牛、虎、兔、龙、蛇、马、羊、猴、鸡、狗、猪今天的免费生肖运势：爱情、财运、事业和健康。' },
    'blood-type': { title: '血型运势', desc: 'A、B、O、AB 今天的运势', badge: '4种血型',
      metaTitle: '血型运势 — A、B、O、AB 的今天',
      metaDesc: 'A、B、O、AB 今天的免费血型运势：爱情、财运、事业和健康，附幸运色、数字和物件。每天更新。' },
    biorhythm: { title: '生物节律计算', desc: '画出体力、情绪和智力三条曲线', badge: '曲线图',
      metaTitle: '生物节律计算 — 体力、情绪与智力',
      metaDesc: '免费的生物节律计算：填入出生日期，画出体力23天、情绪28天、智力33天的周期，并标出临界日。' },
    'birth-stone': { title: '诞生石与诞生花', desc: '你出生月份的宝石和花', badge: '12个月',
      metaTitle: '按月份看诞生石与诞生花 — 含义',
      metaDesc: '按出生月份查你的诞生石和诞生花，从一月的石榴石到十二月的绿松石，附每一种在传统里代表什么。' },
    'today-color': { title: '今天的幸运色', desc: '今天的颜色和最好避开的颜色', badge: '每日',
      metaTitle: '今天的幸运色 — 免费每日解读',
      metaDesc: '看今天的幸运色和最好避开的颜色，附每一种的含义和一句今日提示。免费、即时、每天更新。' },
    'lucky-numbers': { title: '幸运数字', desc: '由出生日期生成的六个数字', badge: '每日',
      metaTitle: '今天的幸运数字 — 由出生日期生成的六个数字',
      metaDesc: '用你的出生日期和今天的日期生成六个 1–45 的幸运数字，附幸运方位、幸运日和幸运时段。免费，图个乐。' },
    'star-match': { title: '星座配对', desc: '按元素看两个星座合不合', badge: '12星座',
      metaTitle: '星座配对 — 十二星座所有组合',
      metaDesc: '按火、土、风、水四元素看任意两个星座的配对，附分数、含义和建议。' },
    'zodiac-match': { title: '生肖配对', desc: '六合、三合与相冲', badge: '12生肖',
      metaTitle: '生肖配对 — 十二生肖所有组合',
      metaDesc: '用传统的六合、三合和相冲关系看任意两个生肖的配对，附分数和建议。' },
    'mbti-match': { title: 'MBTI 配对', desc: '16型里两个类型怎么对上', badge: '16型',
      metaTitle: 'MBTI 配对 — 16型里任选两个',
      metaDesc: '看16型里任意两个 MBTI 的配对。E/I、N/S、T/F、J/P 四个维度怎么对上，附分数和实用建议。' },
    'blood-match': { title: '血型配对', desc: 'A、B、O、AB 怎么配', badge: '4种血型',
      metaTitle: '血型配对 — A、B、O、AB 的组合',
      metaDesc: '看 A、B、O、AB 里任意两个的配对，附分数、这组配对靠什么撑着、在感情里怎么走，以及建议。' },
    mbti: { title: 'MBTI 运势', desc: '十六型各自今天的运势', badge: '16型',
      metaTitle: 'MBTI 每日运势 — 十六种人格类型',
      metaDesc: '十六种 MBTI 类型今天的免费运势：爱情、财运、事业和健康，附幸运色、数字和物件。每天更新。' },
    'daily-tarot': { title: '今日塔罗', desc: '大阿尔卡纳里的一张牌', badge: '每日',
      metaTitle: '今天的塔罗牌 — 一张牌，免费，每天',
      metaDesc: '从22张大阿尔卡纳里抽今天的一张牌。它按日期选定，所以一整天都一样。免费，附正位和逆位的解读。' },
    'tarot-yesno': { title: '塔罗是或否', desc: '抽一张牌得到答案', badge: '抽牌',
      metaTitle: '塔罗是或否 — 抽一张牌',
      metaDesc: '心里想着一个问题，抽一张塔罗牌得到是、否或还看不清楚的答案。免费，附完整的牌义解读。' },
    tarot: { title: '塔罗占卜', desc: '完整78张牌，四种牌阵', badge: '牌阵',
      metaTitle: '在线塔罗占卜 — 78张全牌免费牌阵',
      metaDesc: '用完整的78张牌做免费塔罗占卜：单张、过去-现在-未来、关系牌阵，或完整的凯尔特十字。每张牌都有正位和逆位的含义。' },
    dream: { title: '解梦词典', desc: '二十个常见梦境符号', badge: '20',
      metaTitle: '解梦词典 — 二十个常见梦境符号解说',
      metaDesc: '坠落、掉牙、飞、被追赶，以及另外十六个常见梦境符号在传统里怎么被解读，通常出现在什么时期。' },
    saju: { title: '八字（사주） — 韩式四柱', desc: '按出生日期排出的四柱命盘', badge: '命盘',
      metaTitle: '八字（사주） — 韩式四柱解读，免费',
      metaDesc: '用出生日期和时辰读你的사주（韩式四柱）：天干、地支、五行平衡、十神和大运。在中国称作八字。免费，在你的浏览器里计算。' },
  },
  'zh-hant': {
    daily: { title: '今日運勢', desc: '按出生日期看今天的運勢', badge: '每日',
      metaTitle: '按出生日期看今天的運勢 — 免費每日運勢',
      metaDesc: '填入出生日期就能看今天的免費運勢：綜合、愛情、財運、事業和健康，還有幸運色、數字、方位和物件。每天更新。' },
    zodiac: { title: '星座運勢', desc: '十二星座各自今天的運勢', badge: '12星座',
      metaTitle: '星座運勢 — 十二星座今天的運勢，免費',
      metaDesc: '免費看十二星座今天的運勢：愛情、財運、事業和健康，附幸運色、數字和物件。每天更新。' },
    animal: { title: '生肖運勢', desc: '十二生肖各自今天的運勢', badge: '12生肖',
      metaTitle: '生肖運勢 — 十二生肖今天的運勢',
      metaDesc: '鼠、牛、虎、兔、龍、蛇、馬、羊、猴、雞、狗、豬今天的免費生肖運勢：愛情、財運、事業和健康。' },
    'blood-type': { title: '血型運勢', desc: 'A、B、O、AB 今天的運勢', badge: '4種血型',
      metaTitle: '血型運勢 — A、B、O、AB 的今天',
      metaDesc: 'A、B、O、AB 今天的免費血型運勢：愛情、財運、事業和健康，附幸運色、數字和物件。每天更新。' },
    biorhythm: { title: '生物節律計算', desc: '畫出體力、情緒和智力三條曲線', badge: '曲線圖',
      metaTitle: '生物節律計算 — 體力、情緒與智力',
      metaDesc: '免費的生物節律計算：填入出生日期，畫出體力23天、情緒28天、智力33天的週期，並標出臨界日。' },
    'birth-stone': { title: '誕生石與誕生花', desc: '你出生月份的寶石和花', badge: '12個月',
      metaTitle: '按月份看誕生石與誕生花 — 含義',
      metaDesc: '按出生月份查你的誕生石和誕生花，從一月的石榴石到十二月的綠松石，附每一種在傳統裡代表什麼。' },
    'today-color': { title: '今天的幸運色', desc: '今天的顏色和最好避開的顏色', badge: '每日',
      metaTitle: '今天的幸運色 — 免費每日解讀',
      metaDesc: '看今天的幸運色和最好避開的顏色，附每一種的含義和一句今日提示。免費、即時、每天更新。' },
    'lucky-numbers': { title: '幸運數字', desc: '由出生日期產生的六個數字', badge: '每日',
      metaTitle: '今天的幸運數字 — 由出生日期產生的六個數字',
      metaDesc: '用你的出生日期和今天的日期產生六個 1–45 的幸運數字，附幸運方位、幸運日和幸運時段。免費，圖個樂。' },
    'star-match': { title: '星座配對', desc: '按元素看兩個星座合不合', badge: '12星座',
      metaTitle: '星座配對 — 十二星座所有組合',
      metaDesc: '按火、土、風、水四元素看任意兩個星座的配對，附分數、含義和建議。' },
    'zodiac-match': { title: '生肖配對', desc: '六合、三合與相沖', badge: '12生肖',
      metaTitle: '生肖配對 — 十二生肖所有組合',
      metaDesc: '用傳統的六合、三合和相沖關係看任意兩個生肖的配對，附分數和建議。' },
    'mbti-match': { title: 'MBTI 配對', desc: '16型裡兩個類型怎麼對上', badge: '16型',
      metaTitle: 'MBTI 配對 — 16型裡任選兩個',
      metaDesc: '看16型裡任意兩個 MBTI 的配對。E/I、N/S、T/F、J/P 四個維度怎麼對上，附分數和實用建議。' },
    'blood-match': { title: '血型配對', desc: 'A、B、O、AB 怎麼配', badge: '4種血型',
      metaTitle: '血型配對 — A、B、O、AB 的組合',
      metaDesc: '看 A、B、O、AB 裡任意兩個的配對，附分數、這組配對靠什麼撐著、在感情裡怎麼走，以及建議。' },
    mbti: { title: 'MBTI 運勢', desc: '十六型各自今天的運勢', badge: '16型',
      metaTitle: 'MBTI 每日運勢 — 十六種人格類型',
      metaDesc: '十六種 MBTI 類型今天的免費運勢：愛情、財運、事業和健康，附幸運色、數字和物件。每天更新。' },
    'daily-tarot': { title: '今日塔羅', desc: '大阿爾克那裡的一張牌', badge: '每日',
      metaTitle: '今天的塔羅牌 — 一張牌，免費，每天',
      metaDesc: '從22張大阿爾克那裡抽今天的一張牌。它按日期選定，所以一整天都一樣。免費，附正位和逆位的解讀。' },
    'tarot-yesno': { title: '塔羅是或否', desc: '抽一張牌得到答案', badge: '抽牌',
      metaTitle: '塔羅是或否 — 抽一張牌',
      metaDesc: '心裡想著一個問題，抽一張塔羅牌得到是、否或還看不清楚的答案。免費，附完整的牌義解讀。' },
    tarot: { title: '塔羅占卜', desc: '完整78張牌，四種牌陣', badge: '牌陣',
      metaTitle: '線上塔羅占卜 — 78張全牌免費牌陣',
      metaDesc: '用完整的78張牌做免費塔羅占卜：單張、過去-現在-未來、關係牌陣，或完整的凱爾特十字。每張牌都有正位和逆位的含義。' },
    dream: { title: '解夢詞典', desc: '二十個常見夢境符號', badge: '20',
      metaTitle: '解夢詞典 — 二十個常見夢境符號解說',
      metaDesc: '墜落、掉牙、飛、被追趕，以及另外十六個常見夢境符號在傳統裡怎麼被解讀，通常出現在什麼時期。' },
    saju: { title: '八字（사주） — 韓式四柱', desc: '按出生日期排出的四柱命盤', badge: '命盤',
      metaTitle: '八字（사주） — 韓式四柱解讀，免費',
      metaDesc: '用出生日期和時辰讀你的사주（韓式四柱）：天干、地支、五行平衡、十神和大運。在中國稱作八字。免費，在你的瀏覽器裡計算。' },
  },
};

export function fortuneHubCopy(lang: FortuneIntlLang): HubCopy {
  return HUB[lang];
}

export function fortuneToolCopy(lang: FortuneIntlLang, slug: FortuneToolSlug): ToolCopy {
  return TOOLS[lang][slug];
}

/** 허브 카드 — 아이콘·색은 언어와 무관하므로 FORTUNE_TOOLS에서 가져온다 */
export function fortuneHubCards(lang: FortuneIntlLang) {
  return FORTUNE_TOOLS.map(t => ({
    href: `/${lang}/fortune/${t.slug}`,
    icon: t.icon,
    color: t.color,
    title: TOOLS[lang][t.slug].title,
    desc: TOOLS[lang][t.slug].desc,
    badge: TOOLS[lang][t.slug].badge,
  }));
}

/** 열 언어를 서로 가리킨다 — 한쪽만 걸면 구글이 짝으로 인정하지 않는다 */
export function fortuneHubMetadata(lang: FortuneIntlLang): Metadata {
  const c = HUB[lang];
  const route = '/fortune';
  return {
    title: c.metaTitle,
    description: c.metaDesc,
    alternates: { canonical: localeHref(lang, route), languages: alternateLanguages10(route) },
    openGraph: { ...openGraphFor(lang as AnyLocale10), title: c.metaTitle, description: c.metaDesc, url: localeHref(lang, route) },
  };
}

/**
 * 슬러그가 언어마다 다른 도구.
 *
 * 행운의 숫자는 한국어가 /fortune/lucky-lotto다 — 한국 로또(6/45) 전용으로
 * 만들었기 때문이다. 다국어는 특정 복권을 지칭하면 나라마다 형식이 달라
 * 틀린 말이 되므로 lucky-numbers로 두었다. 같은 도구이므로 hreflang은 서로를
 * 가리켜야 하고, 주소가 다르니 alternateLanguages10으로는 안 된다.
 */
const KO_SLUG: Partial<Record<FortuneToolSlug, string>> = { 'lucky-numbers': 'lucky-lotto' };

export function fortuneToolMetadata(lang: FortuneIntlLang, slug: FortuneToolSlug): Metadata {
  const c = TOOLS[lang][slug];
  const route = `/fortune/${slug}`;
  const koSlug = KO_SLUG[slug];
  const languages = koSlug
    ? { ...alternateLanguages10(route), ko: `/fortune/${koSlug}` }
    : alternateLanguages10(route);
  return {
    title: c.metaTitle,
    description: c.metaDesc,
    alternates: { canonical: localeHref(lang, route), languages },
    openGraph: { ...openGraphFor(lang as AnyLocale10), title: c.metaTitle, description: c.metaDesc, url: localeHref(lang, route) },
  };
}

/** 공유 카드 조각 — 열쇠는 og-intl과 같은 "fortune[/도구]/언어" 꼴 */
export function fortuneIntlCards(): Record<string, { icon: string; eyebrow: string; title: string; desc: string; from: string; to: string }> {
  const out: Record<string, { icon: string; eyebrow: string; title: string; desc: string; from: string; to: string }> = {};
  for (const lang of Object.keys(TOOLS) as FortuneIntlLang[]) {
    out[`fortune/${lang}`] = {
      icon: '🔮', eyebrow: 'Fortune', title: HUB[lang].title, desc: HUB[lang].lead,
      from: '#7c3aed', to: '#db2777',
    };
    for (const t of FORTUNE_TOOLS) {
      const c = TOOLS[lang][t.slug];
      out[`fortune/${t.slug}/${lang}`] = {
        icon: t.icon, eyebrow: t.eyebrow, title: c.title, desc: c.desc, from: t.from, to: t.to,
      };
    }
  }
  return out;
}
