/**
 * 두뇌 게임 여섯(스트룹·개수 어림·엔백·도형 회전·박자·주변시야)의 화면 문구.
 *
 * lib/game-ui-intl.ts가 이미 커서 새 게임은 여기 따로 둔다 — 계산을
 * lib/game-more.ts로 나눈 것과 같은 이유다.
 */
import type { GameLang } from './game-ui-intl.ts';

export interface GameMoreUi {
  start: string;
  again: string;
  level: string;
  score: string;
  best: string;
  correct: string;
  wrong: string;
  ready: string;
  stroopHow: string;
  red: string;
  blue: string;
  green: string;
  yellow: string;
  purple: string;
  timeLeft: string;
  dotHow: string;
  howMany: string;
  actual: string;
  submit: string;
  nbackHow: string;
  match: string;
  hit: string;
  miss: string;
  falseAlarm: string;
  rotHow: string;
  sameShape: string;
  diffShape: string;
  beatHow: string;
  tapHere: string;
  avgOff: string;
  evenness: string;
  bpm: string;
  periHow: string;
  keepEyes: string;
  missed: string;
}

export const GAME_MORE_UI: Record<GameLang, GameMoreUi> = {
  ko: {
    start: "시작하기",
    again: "다시 하기",
    level: "단계",
    score: "점수",
    best: "최고 기록",
    correct: "맞음",
    wrong: "틀림",
    ready: "준비되면 시작을 누르세요",
    stroopHow: "글자의 뜻이 아니라 **칠해진 색**을 고르세요",
    red: "빨강",
    blue: "파랑",
    green: "초록",
    yellow: "노랑",
    purple: "보라",
    timeLeft: "남은 시간",
    dotHow: "점이 잠깐 보입니다. 몇 개였는지 어림해 보세요.",
    howMany: "몇 개였나요?",
    actual: "실제",
    submit: "확인",
    nbackHow: "{n}칸 앞과 같은 자리에 불이 들어오면 누르세요",
    match: "같아요!",
    hit: "맞힘",
    miss: "놓침",
    falseAlarm: "헛누름",
    rotHow: "두 도형이 돌리면 같아지나요?",
    sameShape: "같아요",
    diffShape: "달라요",
    beatHow: "소리에 맞춰 눌러 보세요. 소리가 멈춘 뒤에도 같은 박자로 이어가세요.",
    tapHere: "여기를 누르세요",
    avgOff: "평균 어긋남",
    evenness: "고름",
    bpm: "빠르기",
    periHow: "가운데 점을 계속 보면서, 가장자리에 뜨는 것을 누르세요",
    keepEyes: "가운데를 보세요",
    missed: "놓쳤습니다",
  },
  en: {
    start: "Start",
    again: "Try again",
    level: "Level",
    score: "Score",
    best: "Best",
    correct: "Correct",
    wrong: "Wrong",
    ready: "Press start when you are ready",
    stroopHow: "Pick the colour it is printed in, not the word",
    red: "Red",
    blue: "Blue",
    green: "Green",
    yellow: "Yellow",
    purple: "Purple",
    timeLeft: "Time left",
    dotHow: "The dots flash for a moment — guess how many there were.",
    howMany: "How many?",
    actual: "Actual",
    submit: "Check",
    nbackHow: "Press when the square matches the one {n} steps back",
    match: "Match!",
    hit: "Hits",
    miss: "Misses",
    falseAlarm: "False presses",
    rotHow: "Are these the same shape, just rotated?",
    sameShape: "Same",
    diffShape: "Different",
    beatHow: "Tap along with the beat, then keep it going after the sound stops.",
    tapHere: "Tap here",
    avgOff: "Average off",
    evenness: "Evenness",
    bpm: "Tempo",
    periHow: "Keep looking at the centre dot and tap what appears at the edge",
    keepEyes: "Look at the centre",
    missed: "Missed it",
  },
  es: {
    start: "Empezar",
    again: "Otra vez",
    level: "Nivel",
    score: "Puntos",
    best: "Mejor",
    correct: "Aciertos",
    wrong: "Fallos",
    ready: "Pulsa empezar cuando estés listo",
    stroopHow: "Elige el color con el que está escrito, no la palabra",
    red: "Rojo",
    blue: "Azul",
    green: "Verde",
    yellow: "Amarillo",
    purple: "Morado",
    timeLeft: "Tiempo",
    dotHow: "Los puntos aparecen un instante: adivina cuántos había.",
    howMany: "¿Cuántos?",
    actual: "Real",
    submit: "Comprobar",
    nbackHow: "Pulsa cuando el cuadro coincida con el de {n} pasos atrás",
    match: "¡Igual!",
    hit: "Aciertos",
    miss: "Perdidos",
    falseAlarm: "Falsos",
    rotHow: "¿Son la misma figura, solo girada?",
    sameShape: "Igual",
    diffShape: "Distinta",
    beatHow: "Toca al ritmo y sigue con el mismo compás cuando el sonido pare.",
    tapHere: "Toca aquí",
    avgOff: "Desvío medio",
    evenness: "Regularidad",
    bpm: "Tempo",
    periHow: "Mira siempre el punto central y toca lo que aparece en el borde",
    keepEyes: "Mira al centro",
    missed: "Fallaste",
  },
  'pt-br': {
    start: "Começar",
    again: "De novo",
    level: "Nível",
    score: "Pontos",
    best: "Melhor",
    correct: "Acertos",
    wrong: "Erros",
    ready: "Toque em começar quando estiver pronto",
    stroopHow: "Escolha a cor em que está escrito, não a palavra",
    red: "Vermelho",
    blue: "Azul",
    green: "Verde",
    yellow: "Amarelo",
    purple: "Roxo",
    timeLeft: "Tempo",
    dotHow: "Os pontos aparecem por um instante: adivinhe quantos eram.",
    howMany: "Quantos?",
    actual: "Real",
    submit: "Conferir",
    nbackHow: "Toque quando o quadrado for igual ao de {n} passos atrás",
    match: "Igual!",
    hit: "Acertos",
    miss: "Perdidos",
    falseAlarm: "Falsos",
    rotHow: "São a mesma forma, apenas girada?",
    sameShape: "Igual",
    diffShape: "Diferente",
    beatHow: "Toque no ritmo e continue no mesmo compasso quando o som parar.",
    tapHere: "Toque aqui",
    avgOff: "Desvio médio",
    evenness: "Regularidade",
    bpm: "Tempo",
    periHow: "Olhe sempre para o ponto central e toque no que aparecer na borda",
    keepEyes: "Olhe para o centro",
    missed: "Você perdeu",
  },
  ja: {
    start: "スタート",
    again: "もう一度",
    level: "レベル",
    score: "スコア",
    best: "ベスト",
    correct: "正解",
    wrong: "不正解",
    ready: "準備ができたらスタートを押してください",
    stroopHow: "言葉の意味ではなく**塗られた色**を選んでください",
    red: "あか",
    blue: "あお",
    green: "みどり",
    yellow: "きいろ",
    purple: "むらさき",
    timeLeft: "残り時間",
    dotHow: "点が一瞬だけ見えます。何個だったか当ててください。",
    howMany: "何個でしたか？",
    actual: "実際",
    submit: "決定",
    nbackHow: "{n}つ前と同じ位置が光ったら押してください",
    match: "同じ！",
    hit: "ヒット",
    miss: "見逃し",
    falseAlarm: "空押し",
    rotHow: "2つの図形は回すと同じになりますか？",
    sameShape: "同じ",
    diffShape: "違う",
    beatHow: "音に合わせて押し、音が止まっても同じ拍で続けてください。",
    tapHere: "ここを押す",
    avgOff: "平均ずれ",
    evenness: "安定度",
    bpm: "テンポ",
    periHow: "中央の点を見たまま、端に出るものを押してください",
    keepEyes: "中央を見て",
    missed: "見逃しました",
  },
  de: {
    start: "Start",
    again: "Nochmal",
    level: "Stufe",
    score: "Punkte",
    best: "Bestwert",
    correct: "Richtig",
    wrong: "Falsch",
    ready: "Drück Start, wenn du bereit bist",
    stroopHow: "Wähle die Farbe, in der es gedruckt ist — nicht das Wort",
    red: "Rot",
    blue: "Blau",
    green: "Grün",
    yellow: "Gelb",
    purple: "Lila",
    timeLeft: "Restzeit",
    dotHow: "Die Punkte blitzen kurz auf — schätze, wie viele es waren.",
    howMany: "Wie viele?",
    actual: "Tatsächlich",
    submit: "Prüfen",
    nbackHow: "Drück, wenn das Feld dem von vor {n} Schritten entspricht",
    match: "Treffer!",
    hit: "Treffer",
    miss: "Verpasst",
    falseAlarm: "Fehldrücke",
    rotHow: "Sind das die gleichen Formen, nur gedreht?",
    sameShape: "Gleich",
    diffShape: "Anders",
    beatHow: "Tippe im Takt mit und halte ihn, wenn der Ton aufhört.",
    tapHere: "Hier tippen",
    avgOff: "Mittlere Abweichung",
    evenness: "Gleichmäßigkeit",
    bpm: "Tempo",
    periHow: "Schau auf den Mittelpunkt und tippe an, was am Rand erscheint",
    keepEyes: "Schau in die Mitte",
    missed: "Verpasst",
  },
  fr: {
    start: "Commencer",
    again: "Recommencer",
    level: "Niveau",
    score: "Score",
    best: "Meilleur",
    correct: "Correct",
    wrong: "Faux",
    ready: "Appuyez sur Commencer quand vous êtes prêt",
    stroopHow: "Choisissez la couleur d’impression, pas le mot",
    red: "Rouge",
    blue: "Bleu",
    green: "Vert",
    yellow: "Jaune",
    purple: "Violet",
    timeLeft: "Temps restant",
    dotHow: "Les points apparaissent un instant : devinez combien il y en avait.",
    howMany: "Combien ?",
    actual: "Réel",
    submit: "Valider",
    nbackHow: "Appuyez quand la case correspond à celle d’il y a {n} coups",
    match: "Identique !",
    hit: "Trouvés",
    miss: "Manqués",
    falseAlarm: "Fausses alertes",
    rotHow: "Est-ce la même forme, simplement tournée ?",
    sameShape: "Identique",
    diffShape: "Différente",
    beatHow: "Tapez en rythme, puis continuez au même tempo une fois le son arrêté.",
    tapHere: "Tapez ici",
    avgOff: "Écart moyen",
    evenness: "Régularité",
    bpm: "Tempo",
    periHow: "Fixez le point central et touchez ce qui apparaît sur le bord",
    keepEyes: "Regardez le centre",
    missed: "Manqué",
  },
  hi: {
    start: "शुरू करें",
    again: "फिर से",
    level: "स्तर",
    score: "अंक",
    best: "सर्वोत्तम",
    correct: "सही",
    wrong: "ग़लत",
    ready: "तैयार हों तो शुरू करें दबाएँ",
    stroopHow: "शब्द नहीं, जिस रंग में लिखा है वह चुनें",
    red: "लाल",
    blue: "नीला",
    green: "हरा",
    yellow: "पीला",
    purple: "बैंगनी",
    timeLeft: "शेष समय",
    dotHow: "बिंदु एक पल के लिए दिखते हैं — अंदाज़ा लगाएँ कि कितने थे।",
    howMany: "कितने थे?",
    actual: "वास्तविक",
    submit: "जाँचें",
    nbackHow: "जब ख़ाना {n} क़दम पीछे वाले से मेल खाए तो दबाएँ",
    match: "मेल!",
    hit: "हिट",
    miss: "चूक",
    falseAlarm: "ग़लत दबाव",
    rotHow: "क्या ये वही आकृति है, बस घुमाई हुई?",
    sameShape: "वही",
    diffShape: "अलग",
    beatHow: "ताल के साथ दबाएँ, और आवाज़ रुकने के बाद भी वही ताल बनाए रखें।",
    tapHere: "यहाँ दबाएँ",
    avgOff: "औसत अंतर",
    evenness: "एकरूपता",
    bpm: "गति",
    periHow: "बीच के बिंदु को देखते रहें और किनारे पर जो दिखे उसे दबाएँ",
    keepEyes: "बीच देखें",
    missed: "चूक गए",
  },
  'zh-hans': {
    start: "开始",
    again: "再来一次",
    level: "关卡",
    score: "分数",
    best: "最佳",
    correct: "正确",
    wrong: "错误",
    ready: "准备好后点开始",
    stroopHow: "选出它被涂成的颜色，不是文字的意思",
    red: "红",
    blue: "蓝",
    green: "绿",
    yellow: "黄",
    purple: "紫",
    timeLeft: "剩余时间",
    dotHow: "圆点会闪一下，猜猜有几个。",
    howMany: "有几个？",
    actual: "实际",
    submit: "确认",
    nbackHow: "当亮起的格子与 {n} 步之前相同时按下",
    match: "相同！",
    hit: "命中",
    miss: "漏掉",
    falseAlarm: "误按",
    rotHow: "这两个图形转一下会一样吗？",
    sameShape: "一样",
    diffShape: "不一样",
    beatHow: "跟着节拍点击，声音停了也保持同样的节奏。",
    tapHere: "点这里",
    avgOff: "平均偏差",
    evenness: "稳定度",
    bpm: "速度",
    periHow: "一直盯着中间的点，点掉边缘出现的东西",
    keepEyes: "看中间",
    missed: "没点到",
  },
  'zh-hant': {
    start: "開始",
    again: "再來一次",
    level: "關卡",
    score: "分數",
    best: "最佳",
    correct: "正確",
    wrong: "錯誤",
    ready: "準備好後點開始",
    stroopHow: "選出它被塗成的顏色，不是文字的意思",
    red: "紅",
    blue: "藍",
    green: "綠",
    yellow: "黃",
    purple: "紫",
    timeLeft: "剩餘時間",
    dotHow: "圓點會閃一下，猜猜有幾個。",
    howMany: "有幾個？",
    actual: "實際",
    submit: "確認",
    nbackHow: "當亮起的格子與 {n} 步之前相同時按下",
    match: "相同！",
    hit: "命中",
    miss: "漏掉",
    falseAlarm: "誤按",
    rotHow: "這兩個圖形轉一下會一樣嗎？",
    sameShape: "一樣",
    diffShape: "不一樣",
    beatHow: "跟著節拍點擊，聲音停了也保持同樣的節奏。",
    tapHere: "點這裡",
    avgOff: "平均偏差",
    evenness: "穩定度",
    bpm: "速度",
    periHow: "一直盯著中間的點，點掉邊緣出現的東西",
    keepEyes: "看中間",
    missed: "沒點到",
  },
};
