// node에서 직접 로드할 수 있게 확장자를 명시한다 (allowImportingTsExtensions)
import type { AnyLocale10 } from './locales.ts';

/**
 * 게임 화면 문구의 여덟 언어 사전.
 *
 * 점수·판정 로직은 한국어 구현을 그대로 쓴다. 등급 문구만 언어별로 갈린다.
 *
 * 타자 게임은 예외적으로 데이터까지 갈린다 — 한국어 문장을 다른 언어 사용자에게
 * 치라고 할 수는 없고, 재는 단위도 다르다(타/분 vs 분당 글자 수).
 */
export type GameLang = AnyLocale10;

/** 열 게임이 공통으로 쓰는 라벨 */
export const GAME_COMMON: Record<GameLang, {
  start: string; retry: string; running: string; again: string; fromStart: string;
  best: string; level: string; accuracy: string; secLeft: (s: string) => string;
}> = {
  ko: {
    start: '시작하기', retry: '다시 도전', running: '진행 중…', again: '다시 하기', fromStart: '처음부터 다시',
    best: '최고 기록', level: '단계', accuracy: '정확도', secLeft: s => `${s}초 남음`,
  },
  en: {
    start: 'Start', retry: 'Try again', running: 'Running…', again: 'Go again', fromStart: 'Start over',
    best: 'Best', level: 'Level', accuracy: 'Accuracy', secLeft: s => `${s}s left`,
  },
  es: {
    start: 'Empezar', retry: 'Volver a intentarlo', running: 'En marcha…', again: 'Otra vez', fromStart: 'Empezar de cero',
    best: 'Mejor', level: 'Nivel', accuracy: 'Precisión', secLeft: s => `quedan ${s}s`,
  },
  'pt-br': {
    start: 'Começar', retry: 'Tentar de novo', running: 'Em andamento…', again: 'De novo', fromStart: 'Começar do zero',
    best: 'Melhor', level: 'Nível', accuracy: 'Precisão', secLeft: s => `faltam ${s}s`,
  },
  ja: {
    start: 'はじめる', retry: 'もう一度挑戦', running: '進行中…', again: 'もう一度', fromStart: 'はじめからやり直す',
    best: '最高記録', level: 'レベル', accuracy: '正確さ', secLeft: s => `残り${s}秒`,
  },
  de: {
    start: 'Starten', retry: 'Nochmal versuchen', running: 'Läuft…', again: 'Noch einmal', fromStart: 'Von vorn beginnen',
    best: 'Bestwert', level: 'Ebene', accuracy: 'Genauigkeit', secLeft: s => `${s}s übrig`,
  },
  fr: {
    start: 'Commencer', retry: 'Réessayer', running: 'En cours…', again: 'Encore', fromStart: 'Reprendre à zéro',
    best: 'Meilleur', level: 'Niveau', accuracy: 'Précision', secLeft: s => `${s}s restantes`,
  },
  hi: {
    start: 'शुरू करें', retry: 'फिर कोशिश करें', running: 'चल रहा है…', again: 'दोबारा', fromStart: 'शुरू से फिर',
    best: 'सबसे अच्छा', level: 'स्तर', accuracy: 'सटीकता', secLeft: s => `${s} सेकंड बचे`,
  },
  'zh-hans': {
    start: '开始',
    retry: '再试一次',
    running: '进行中…',
    again: '再来一次',
    fromStart: '从头开始',
    best: '最好',
    level: '关卡',
    accuracy: '准确率',
    secLeft: s => `还剩${s}秒`,
  },
  'zh-hant': {
    start: '開始',
    retry: '再試一次',
    running: '進行中…',
    again: '再來一次',
    fromStart: '從頭開始',
    best: '最好',
    level: '關卡',
    accuracy: '準確率',
    secLeft: s => `還剩${s}秒`,
  },
};

export const REACTION_UI: Record<GameLang, {
  idleTitle: string; idleSub: string; waitTitle: string; waitSub: string; nowTitle: string;
  resultSub: string; roundSub: (n: number, total: number) => string;
  earlyTitle: string; earlySub: string;
  thisRound: string; avgOf: (n: number) => string; fastest: string;
  gradeTop: (ms: number) => string; gradeFast: (ms: number) => string;
  gradeNormal: (ms: number) => string; gradeSlow: (ms: number) => string;
  noteTitle: string; note: string;
}> = {
  ko: {
    idleTitle: '준비되면 누르세요', idleSub: '초록으로 바뀌는 순간 다시 누르면 됩니다',
    waitTitle: '기다리세요…', waitSub: '초록이 되기 전에 누르면 무효입니다',
    nowTitle: '지금!',
    resultSub: '아래에서 결과를 확인하세요', roundSub: (n, total) => `${n}/${total}회 — 눌러서 계속`,
    earlyTitle: '너무 빨랐습니다', earlySub: '초록이 된 뒤에 누르세요 — 눌러서 다시',
    thisRound: '이번 기록', avgOf: n => `평균 (${n}회)`, fastest: '가장 빠름',
    gradeTop: ms => `평균 ${ms}ms — 상위권입니다`,
    gradeFast: ms => `평균 ${ms}ms — 평균보다 빠릅니다`,
    gradeNormal: ms => `평균 ${ms}ms — 보통입니다`,
    gradeSlow: ms => `평균 ${ms}ms — 조금 느립니다. 화면을 응시하고 다시 해보세요`,
    noteTitle: '사람의 반응속도는',
    note: '빛을 보고 반응하는 데는 보통 200~250ms가 걸립니다. 눈이 신호를 받아 뇌가 판단하고 손가락까지 명령이 가는 시간이라, 아무리 연습해도 100ms 아래로는 내려가기 어렵습니다. 화면 주사율과 마우스 지연도 20~30ms쯤 더해집니다.',
  },
  en: {
    idleTitle: 'Click when you are ready', idleSub: 'Then click again the moment it turns green',
    waitTitle: 'Wait…', waitSub: 'Clicking before green does not count',
    nowTitle: 'Now!',
    resultSub: 'See your results below', roundSub: (n, total) => `${n}/${total} — click to continue`,
    earlyTitle: 'Too early', earlySub: 'Wait for green — click to try again',
    thisRound: 'This round', avgOf: n => `Average (${n})`, fastest: 'Fastest',
    gradeTop: ms => `${ms}ms average — that is up there`,
    gradeFast: ms => `${ms}ms average — faster than most`,
    gradeNormal: ms => `${ms}ms average — about typical`,
    gradeSlow: ms => `${ms}ms average — a little slow. Keep your eyes on the screen and try again`,
    noteTitle: 'About human reaction time',
    note: 'Reacting to light usually takes 200–250ms. That is the eye receiving the signal, the brain deciding, and the command reaching your finger — which is why practice rarely gets anyone below 100ms. Your screen refresh rate and mouse latency add another 20–30ms on top.',
  },
  es: {
    idleTitle: 'Pulsa cuando estés listo', idleSub: 'Y vuelve a pulsar en el momento en que se ponga verde',
    waitTitle: 'Espera…', waitSub: 'Pulsar antes del verde no cuenta',
    nowTitle: '¡Ahora!',
    resultSub: 'Mira tus resultados abajo', roundSub: (n, total) => `${n}/${total} — pulsa para seguir`,
    earlyTitle: 'Demasiado pronto', earlySub: 'Espera al verde — pulsa para reintentar',
    thisRound: 'Esta ronda', avgOf: n => `Media (${n})`, fastest: 'Más rápido',
    gradeTop: ms => `${ms}ms de media — estás arriba`,
    gradeFast: ms => `${ms}ms de media — más rápido que la mayoría`,
    gradeNormal: ms => `${ms}ms de media — dentro de lo normal`,
    gradeSlow: ms => `${ms}ms de media — algo lento. No apartes la vista de la pantalla y vuelve a probar`,
    noteTitle: 'Sobre el tiempo de reacción humano',
    note: 'Reaccionar a la luz suele llevar 200–250ms. Es el ojo recibiendo la señal, el cerebro decidiendo y la orden llegando al dedo — por eso casi nadie baja de 100ms por mucho que practique. La frecuencia de tu pantalla y la latencia del ratón suman otros 20–30ms.',
  },
  'pt-br': {
    idleTitle: 'Clique quando estiver pronto', idleSub: 'E clique de novo no instante em que ficar verde',
    waitTitle: 'Espere…', waitSub: 'Clicar antes do verde não conta',
    nowTitle: 'Agora!',
    resultSub: 'Veja seus resultados abaixo', roundSub: (n, total) => `${n}/${total} — clique para continuar`,
    earlyTitle: 'Cedo demais', earlySub: 'Espere o verde — clique para tentar de novo',
    thisRound: 'Esta rodada', avgOf: n => `Média (${n})`, fastest: 'Mais rápido',
    gradeTop: ms => `${ms}ms de média — você está lá em cima`,
    gradeFast: ms => `${ms}ms de média — mais rápido que a maioria`,
    gradeNormal: ms => `${ms}ms de média — dentro do normal`,
    gradeSlow: ms => `${ms}ms de média — um pouco lento. Fique de olho na tela e tente de novo`,
    noteTitle: 'Sobre o tempo de reação humano',
    note: 'Reagir à luz costuma levar 200–250ms. É o olho recebendo o sinal, o cérebro decidindo e o comando chegando ao dedo — por isso quase ninguém baixa de 100ms, treine quanto treinar. A taxa de atualização da tela e a latência do mouse somam outros 20–30ms.',
  },
  ja: {
    idleTitle: '準備できたら押してください', idleSub: '緑に変わった瞬間にもう一度押します',
    waitTitle: '待ってください…', waitSub: '緑になる前に押すと無効です',
    nowTitle: 'いま！',
    resultSub: '下で結果を確認してください', roundSub: (n, total) => `${n}/${total}回 — 押して続ける`,
    earlyTitle: '早すぎました', earlySub: '緑になってから押してください — 押してやり直す',
    thisRound: '今回の記録', avgOf: n => `平均（${n}回）`, fastest: 'いちばん速い',
    gradeTop: ms => `平均${ms}ms — 上位です`,
    gradeFast: ms => `平均${ms}ms — 平均より速いです`,
    gradeNormal: ms => `平均${ms}ms — ふつうです`,
    gradeSlow: ms => `平均${ms}ms — 少し遅めです。画面をじっと見てもう一度やってみてください`,
    noteTitle: '人の反応速度は',
    note: '光を見て反応するには200〜250msかかります。目が信号を受け、脳が判断し、指まで命令が届く時間なので、いくら練習しても100msを下回るのは難しいです。画面のリフレッシュレートとマウスの遅延で20〜30msほど上乗せされます。',
  },
  de: {
    idleTitle: 'Klick, wenn du bereit bist', idleSub: 'Und klick erneut, sobald es grün wird',
    waitTitle: 'Warte…', waitSub: 'Vor Grün geklickt zählt nicht',
    nowTitle: 'Jetzt!',
    resultSub: 'Deine Ergebnisse stehen unten', roundSub: (n, total) => `${n}/${total} — klicken, um weiterzumachen`,
    earlyTitle: 'Zu früh', earlySub: 'Warte auf Grün — klicken für einen neuen Versuch',
    thisRound: 'Diese Runde', avgOf: n => `Durchschnitt (${n})`, fastest: 'Schnellste',
    gradeTop: ms => `${ms}ms im Schnitt — das ist ganz oben`,
    gradeFast: ms => `${ms}ms im Schnitt — schneller als die meisten`,
    gradeNormal: ms => `${ms}ms im Schnitt — im üblichen Bereich`,
    gradeSlow: ms => `${ms}ms im Schnitt — etwas langsam. Bleib mit den Augen am Bildschirm und versuch es nochmal`,
    noteTitle: 'Zur menschlichen Reaktionszeit',
    note: 'Auf Licht zu reagieren dauert meist 200–250ms. Das ist das Auge, das das Signal empfängt, das Gehirn, das entscheidet, und der Befehl, der den Finger erreicht — darum kommt kaum jemand durch Übung unter 100ms. Bildwiederholrate und Mauslatenz legen weitere 20–30ms drauf.',
  },
  fr: {
    idleTitle: 'Clique quand tu es prêt', idleSub: 'Puis reclique à l’instant où ça passe au vert',
    waitTitle: 'Attends…', waitSub: 'Cliquer avant le vert ne compte pas',
    nowTitle: 'Maintenant !',
    resultSub: 'Tes résultats sont plus bas', roundSub: (n, total) => `${n}/${total} — clique pour continuer`,
    earlyTitle: 'Trop tôt', earlySub: 'Attends le vert — clique pour réessayer',
    thisRound: 'Ce tour', avgOf: n => `Moyenne (${n})`, fastest: 'Le plus rapide',
    gradeTop: ms => `${ms}ms de moyenne — tu es dans le haut du panier`,
    gradeFast: ms => `${ms}ms de moyenne — plus rapide que la plupart`,
    gradeNormal: ms => `${ms}ms de moyenne — dans la norme`,
    gradeSlow: ms => `${ms}ms de moyenne — un peu lent. Garde les yeux sur l’écran et recommence`,
    noteTitle: 'À propos du temps de réaction humain',
    note: 'Réagir à la lumière prend généralement 200–250ms. C’est l’œil qui reçoit le signal, le cerveau qui décide et l’ordre qui atteint le doigt — voilà pourquoi presque personne ne descend sous 100ms, même en s’entraînant. La fréquence de ton écran et la latence de la souris ajoutent 20–30ms de plus.',
  },
  hi: {
    idleTitle: 'तैयार हों तो दबाएँ', idleSub: 'और जिस पल हरा हो, उसी पल फिर दबाएँ',
    waitTitle: 'रुकिए…', waitSub: 'हरा होने से पहले दबाना गिना नहीं जाता',
    nowTitle: 'अब!',
    resultSub: 'नतीजे नीचे देखें', roundSub: (n, total) => `${n}/${total} — जारी रखने के लिए दबाएँ`,
    earlyTitle: 'बहुत जल्दी हो गया', earlySub: 'हरा होने का इंतज़ार करें — दोबारा के लिए दबाएँ',
    thisRound: 'इस बार का समय', avgOf: n => `औसत (${n})`, fastest: 'सबसे तेज़',
    gradeTop: ms => `औसत ${ms}ms — ऊपर की श्रेणी में`,
    gradeFast: ms => `औसत ${ms}ms — ज़्यादातर लोगों से तेज़`,
    gradeNormal: ms => `औसत ${ms}ms — सामान्य दायरे में`,
    gradeSlow: ms => `औसत ${ms}ms — थोड़ा धीमा। स्क्रीन पर नज़र टिकाकर फिर कोशिश करें`,
    noteTitle: 'इंसानी प्रतिक्रिया समय के बारे में',
    note: 'रोशनी देखकर प्रतिक्रिया करने में आम तौर पर 200–250ms लगते हैं। इसमें आँख का संकेत पाना, दिमाग़ का तय करना और उँगली तक आदेश पहुँचना शामिल है — इसलिए कितना भी अभ्यास कर लें, 100ms से नीचे जाना मुश्किल है। स्क्रीन की रिफ़्रेश दर और माउस की देरी 20–30ms और जोड़ देती हैं।',
  },
  'zh-hans': {
    idleTitle: '准备好就点一下',
    idleSub: '然后在变绿的那一刻再点一次',
    waitTitle: '等一下…',
    waitSub: '绿之前点不算数',
    nowTitle: '就是现在！',
    resultSub: '结果看下面',
    roundSub: (n, total) => `${n}/${total} — 点一下继续`,
    earlyTitle: '抢跑了',
    earlySub: '等绿了再点 — 点一下重来',
    thisRound: '这一轮',
    avgOf: n => `平均（${n}次）`,
    fastest: '最快',
    gradeTop: ms => `平均${ms}毫秒 — 相当顶`,
    gradeFast: ms => `平均${ms}毫秒 — 比大多数人快`,
    gradeNormal: ms => `平均${ms}毫秒 — 大概是一般水平`,
    gradeSlow: ms => `平均${ms}毫秒 — 稍慢。眼睛盯着屏幕再试一次`,
    noteTitle: '关于人的反应时间',
    note: '对光做出反应一般要200~250毫秒。那是眼睛收到信号、大脑做决定、指令送到手指的全过程 — 所以怎么练也很难低于100毫秒。屏幕刷新率和鼠标延迟还要再加20~30毫秒。',
  },
  'zh-hant': {
    idleTitle: '準備好就點一下',
    idleSub: '然後在變綠的那一刻再點一次',
    waitTitle: '等一下…',
    waitSub: '綠之前點不算數',
    nowTitle: '就是現在！',
    resultSub: '結果看下面',
    roundSub: (n, total) => `${n}/${total} — 點一下繼續`,
    earlyTitle: '搶跑了',
    earlySub: '等綠了再點 — 點一下重來',
    thisRound: '這一輪',
    avgOf: n => `平均（${n}次）`,
    fastest: '最快',
    gradeTop: ms => `平均${ms}毫秒 — 相當頂`,
    gradeFast: ms => `平均${ms}毫秒 — 比大多數人快`,
    gradeNormal: ms => `平均${ms}毫秒 — 大概是一般水平`,
    gradeSlow: ms => `平均${ms}毫秒 — 稍慢。眼睛盯著螢幕再試一次`,
    noteTitle: '關於人的反應時間',
    note: '對光做出反應一般要200~250毫秒。那是眼睛收到訊號、大腦做決定、指令送到手指的全過程 — 所以怎麼練也很難低於100毫秒。螢幕更新率和滑鼠延遲還要再加20~30毫秒。',
  },
};

export const CPS_UI: Record<GameLang, {
  secSuffix: (n: number) => string; clicksSuffix: (n: number) => string;
  tapHere: string; startsOnFirst: (d: number) => string;
  clicks: string; cps: string; bestOf: (d: number) => string;
  gradeVeryFast: (c: string) => string; gradeFast: (c: string) => string;
  gradeNormal: (c: string) => string; gradeSlow: (c: string) => string;
  note: string;
}> = {
  ko: {
    secSuffix: n => `${n}초`, clicksSuffix: n => `${n}번 클릭`,
    tapHere: '여기를 계속 누르세요', startsOnFirst: d => `첫 클릭과 함께 ${d}초가 시작됩니다`,
    clicks: '클릭 수', cps: '초당 클릭(CPS)', bestOf: d => `최고 기록 (${d}초)`,
    gradeVeryFast: c => `${c} CPS — 아주 빠릅니다`,
    gradeFast: c => `${c} CPS — 빠른 편입니다`,
    gradeNormal: c => `${c} CPS — 보통입니다`,
    gradeSlow: c => `${c} CPS — 손가락 두 개를 번갈아 쓰면 더 나옵니다`,
    note: '보통 한 손가락으로는 6~8 CPS 정도가 한계입니다. 두 손가락을 번갈아 쓰거나(버터플라이) 손목을 떠는 방식으로 10 CPS를 넘기기도 하지만, 마우스와 손목에 무리가 가니 오래 하지 마세요.',
  },
  en: {
    secSuffix: n => `${n}s`, clicksSuffix: n => `${n} clicks`,
    tapHere: 'Keep clicking here', startsOnFirst: d => `The ${d} seconds start on your first click`,
    clicks: 'Clicks', cps: 'Clicks per second', bestOf: d => `Best (${d}s)`,
    gradeVeryFast: c => `${c} CPS — very fast`,
    gradeFast: c => `${c} CPS — on the fast side`,
    gradeNormal: c => `${c} CPS — about average`,
    gradeSlow: c => `${c} CPS — alternating two fingers gets you more`,
    note: 'One finger usually tops out around 6–8 CPS. Alternating two fingers (butterfly clicking) or vibrating your wrist can push past 10 CPS, but it is hard on both the mouse and your wrist — do not keep it up for long.',
  },
  es: {
    secSuffix: n => `${n}s`, clicksSuffix: n => `${n} clics`,
    tapHere: 'Sigue pulsando aquí', startsOnFirst: d => `Los ${d} segundos empiezan con tu primer clic`,
    clicks: 'Clics', cps: 'Clics por segundo', bestOf: d => `Mejor marca (${d}s)`,
    gradeVeryFast: c => `${c} CPS — muy rápido`,
    gradeFast: c => `${c} CPS — del lado rápido`,
    gradeNormal: c => `${c} CPS — dentro de la media`,
    gradeSlow: c => `${c} CPS — alternando dos dedos sacas más`,
    note: 'Con un dedo el tope suele estar en 6–8 CPS. Alternar dos dedos (butterfly clicking) o vibrar la muñeca puede pasar de 10 CPS, pero castiga tanto al ratón como a tu muñeca — no lo mantengas mucho tiempo.',
  },
  'pt-br': {
    secSuffix: n => `${n}s`, clicksSuffix: n => `${n} cliques`,
    tapHere: 'Continue clicando aqui', startsOnFirst: d => `Os ${d} segundos começam no seu primeiro clique`,
    clicks: 'Cliques', cps: 'Cliques por segundo', bestOf: d => `Melhor marca (${d}s)`,
    gradeVeryFast: c => `${c} CPS — muito rápido`,
    gradeFast: c => `${c} CPS — do lado rápido`,
    gradeNormal: c => `${c} CPS — dentro da média`,
    gradeSlow: c => `${c} CPS — alternando dois dedos você tira mais`,
    note: 'Com um dedo o limite costuma ser 6–8 CPS. Alternar dois dedos (butterfly clicking) ou vibrar o pulso pode passar de 10 CPS, mas castiga tanto o mouse quanto o seu pulso — não insista por muito tempo.',
  },
  ja: {
    secSuffix: n => `${n}秒`, clicksSuffix: n => `${n}回クリック`,
    tapHere: 'ここを押し続けてください', startsOnFirst: d => `最初のクリックで${d}秒が始まります`,
    clicks: 'クリック数', cps: '1秒あたりのクリック（CPS）', bestOf: d => `最高記録（${d}秒）`,
    gradeVeryFast: c => `${c} CPS — とても速いです`,
    gradeFast: c => `${c} CPS — 速いほうです`,
    gradeNormal: c => `${c} CPS — ふつうです`,
    gradeSlow: c => `${c} CPS — 指を二本交互に使うともっと出ます`,
    note: '指一本ではだいたい6〜8 CPSが限界です。指を二本交互に使うバタフライや手首を震わせる方法で10 CPSを超えることもありますが、マウスと手首に負担がかかるので長く続けないでください。',
  },
  de: {
    secSuffix: n => `${n}s`, clicksSuffix: n => `${n} Klicks`,
    tapHere: 'Klick hier weiter', startsOnFirst: d => `Die ${d} Sekunden starten mit deinem ersten Klick`,
    clicks: 'Klicks', cps: 'Klicks pro Sekunde', bestOf: d => `Bestwert (${d}s)`,
    gradeVeryFast: c => `${c} CPS — sehr schnell`,
    gradeFast: c => `${c} CPS — eher schnell`,
    gradeNormal: c => `${c} CPS — im Durchschnitt`,
    gradeSlow: c => `${c} CPS — mit zwei Fingern im Wechsel holst du mehr heraus`,
    note: 'Mit einem Finger liegt die Grenze meist bei 6–8 CPS. Zwei Finger im Wechsel (Butterfly-Clicking) oder ein vibrierendes Handgelenk kommen über 10 CPS, belasten aber Maus und Handgelenk — mach das nicht lange.',
  },
  fr: {
    secSuffix: n => `${n}s`, clicksSuffix: n => `${n} clics`,
    tapHere: 'Continue de cliquer ici', startsOnFirst: d => `Les ${d} secondes démarrent à ton premier clic`,
    clicks: 'Clics', cps: 'Clics par seconde', bestOf: d => `Meilleur score (${d}s)`,
    gradeVeryFast: c => `${c} CPS — très rapide`,
    gradeFast: c => `${c} CPS — plutôt rapide`,
    gradeNormal: c => `${c} CPS — dans la moyenne`,
    gradeSlow: c => `${c} CPS — en alternant deux doigts tu en sors davantage`,
    note: 'Avec un doigt, le plafond est généralement de 6–8 CPS. Alterner deux doigts (butterfly clicking) ou faire vibrer le poignet peut dépasser 10 CPS, mais cela fatigue la souris comme le poignet — ne tiens pas longtemps.',
  },
  hi: {
    secSuffix: n => `${n} सेकंड`, clicksSuffix: n => `${n} क्लिक`,
    tapHere: 'यहाँ लगातार दबाते रहें', startsOnFirst: d => `पहले क्लिक के साथ ${d} सेकंड शुरू हो जाते हैं`,
    clicks: 'क्लिक', cps: 'प्रति सेकंड क्लिक (CPS)', bestOf: d => `सबसे अच्छा (${d} सेकंड)`,
    gradeVeryFast: c => `${c} CPS — बहुत तेज़`,
    gradeFast: c => `${c} CPS — तेज़ की ओर`,
    gradeNormal: c => `${c} CPS — औसत के भीतर`,
    gradeSlow: c => `${c} CPS — दो उँगलियाँ बारी-बारी चलाएँ तो ज़्यादा निकलेगा`,
    note: 'एक उँगली से आम तौर पर 6–8 CPS ही ऊपरी सीमा होती है। दो उँगलियाँ बारी-बारी चलाकर (बटरफ़्लाई) या कलाई कँपाकर 10 CPS पार किया जा सकता है, पर इससे माउस और कलाई दोनों पर ज़ोर पड़ता है — देर तक ऐसा न करें।',
  },
  'zh-hans': {
    secSuffix: n => `${n}秒`,
    clicksSuffix: n => `${n}下`,
    tapHere: '在这里一直点',
    startsOnFirst: d => `第一下点下去，${d}秒开始计时`,
    clicks: '点击数',
    cps: '每秒点击',
    bestOf: d => `最好（${d}秒）`,
    gradeVeryFast: c => `${c} CPS — 非常快`,
    gradeFast: c => `${c} CPS — 偏快`,
    gradeNormal: c => `${c} CPS — 大概是平均水平`,
    gradeSlow: c => `${c} CPS — 两根手指交替能点更多`,
    note: '一根手指一般到6~8 CPS就到顶了。两根手指交替（蝴蝶点击）或者抖手腕能过10 CPS，但对鼠标和手腕都很伤 — 别撑太久。',
  },
  'zh-hant': {
    secSuffix: n => `${n}秒`,
    clicksSuffix: n => `${n}下`,
    tapHere: '在這裡一直點',
    startsOnFirst: d => `第一下點下去，${d}秒開始計時`,
    clicks: '點擊數',
    cps: '每秒點擊',
    bestOf: d => `最好（${d}秒）`,
    gradeVeryFast: c => `${c} CPS — 非常快`,
    gradeFast: c => `${c} CPS — 偏快`,
    gradeNormal: c => `${c} CPS — 大概是平均水平`,
    gradeSlow: c => `${c} CPS — 兩根手指交替能點更多`,
    note: '一根手指一般到6~8 CPS就到頂了。兩根手指交替（蝴蝶點擊）或者抖手腕能過10 CPS，但對滑鼠和手腕都很傷 — 別撐太久。',
  },
};

export const AIM_UI: Record<GameLang, {
  sizes: string[]; targetPrefix: string; targetAria: string;
  hitsSub: (acc: number) => string; introTitle: (d: number) => string; introSub: string;
  hits: string; misses: string;
  gradeFast: (h: number) => string; gradeGood: (h: number) => string; gradeSlow: (h: number) => string;
  note: string;
}> = {
  ko: {
    sizes: ['큼', '보통', '작음'], targetPrefix: '과녁', targetAria: '과녁',
    hitsSub: acc => `명중 · 정확도 ${acc}%`,
    introTitle: d => `${d}초 동안 과녁 맞히기`, introSub: '빗나간 클릭도 셉니다 — 마구 누르면 정확도가 떨어집니다',
    hits: '명중', misses: '빗나감',
    gradeFast: h => `${h}개 명중 — 아주 빠릅니다`,
    gradeGood: h => `${h}개 명중 — 좋은 편입니다`,
    gradeSlow: h => `${h}개 명중 — 과녁을 크게 두고 감을 잡아보세요`,
    note: '정확도가 낮다면 마우스 감도(DPI)가 너무 높은 경우가 많습니다. 감도를 낮추고 팔로 크게 움직이면 작은 과녁에서 명중률이 올라갑니다. 휴대폰에서는 손가락 크기 때문에 작은 과녁이 불리합니다.',
  },
  en: {
    sizes: ['Large', 'Medium', 'Small'], targetPrefix: 'Target', targetAria: 'Target',
    hitsSub: acc => `hits · ${acc}% accuracy`,
    introTitle: d => `Hit targets for ${d} seconds`, introSub: 'Misses count too — spamming clicks drops your accuracy',
    hits: 'Hits', misses: 'Misses',
    gradeFast: h => `${h} hits — very fast`,
    gradeGood: h => `${h} hits — good going`,
    gradeSlow: h => `${h} hits — try the large targets first to get a feel for it`,
    note: 'Low accuracy usually means your mouse DPI is too high. Turn the sensitivity down and move from the arm, and your hit rate on small targets goes up. On a phone, small targets are unfair simply because of finger size.',
  },
  es: {
    sizes: ['Grande', 'Mediano', 'Pequeño'], targetPrefix: 'Blanco', targetAria: 'Blanco',
    hitsSub: acc => `aciertos · ${acc}% de precisión`,
    introTitle: d => `Acierta blancos durante ${d} segundos`, introSub: 'Los fallos también cuentan — dar clics a lo loco baja tu precisión',
    hits: 'Aciertos', misses: 'Fallos',
    gradeFast: h => `${h} aciertos — muy rápido`,
    gradeGood: h => `${h} aciertos — bien hecho`,
    gradeSlow: h => `${h} aciertos — prueba primero con los blancos grandes para coger el tacto`,
    note: 'Una precisión baja suele significar que el DPI de tu ratón es demasiado alto. Baja la sensibilidad y mueve desde el brazo, y tu acierto en blancos pequeños sube. En el móvil, los blancos pequeños son injustos solo por el tamaño del dedo.',
  },
  'pt-br': {
    sizes: ['Grande', 'Médio', 'Pequeno'], targetPrefix: 'Alvo', targetAria: 'Alvo',
    hitsSub: acc => `acertos · ${acc}% de precisão`,
    introTitle: d => `Acerte alvos por ${d} segundos`, introSub: 'Os erros também contam — clicar à esmo derruba sua precisão',
    hits: 'Acertos', misses: 'Erros',
    gradeFast: h => `${h} acertos — muito rápido`,
    gradeGood: h => `${h} acertos — muito bem`,
    gradeSlow: h => `${h} acertos — comece pelos alvos grandes para pegar o jeito`,
    note: 'Precisão baixa geralmente quer dizer que o DPI do seu mouse está alto demais. Diminua a sensibilidade e mova a partir do braço: sua taxa de acerto em alvos pequenos sobe. No celular, alvos pequenos são injustos só pelo tamanho do dedo.',
  },
  ja: {
    sizes: ['大きい', 'ふつう', '小さい'], targetPrefix: '標的', targetAria: '標的',
    hitsSub: acc => `命中 · 正確さ ${acc}%`,
    introTitle: d => `${d}秒間、標的を当てる`, introSub: '外したクリックも数えます — 連打すると正確さが下がります',
    hits: '命中', misses: '外し',
    gradeFast: h => `${h}個命中 — とても速いです`,
    gradeGood: h => `${h}個命中 — good です`,
    gradeSlow: h => `${h}個命中 — まず大きい標的で感覚をつかんでみてください`,
    note: '正確さが低いときは、マウスの感度（DPI）が高すぎることが多いです。感度を下げて腕から大きく動かすと、小さい標的でも命中率が上がります。スマートフォンでは指の大きさのせいで小さい標的が不利になります。',
  },
  de: {
    sizes: ['Groß', 'Mittel', 'Klein'], targetPrefix: 'Ziel', targetAria: 'Ziel',
    hitsSub: acc => `Treffer · ${acc}% Genauigkeit`,
    introTitle: d => `${d} Sekunden lang Ziele treffen`, introSub: 'Fehlschüsse zählen auch — wildes Klicken senkt deine Genauigkeit',
    hits: 'Treffer', misses: 'Fehlschüsse',
    gradeFast: h => `${h} Treffer — sehr schnell`,
    gradeGood: h => `${h} Treffer — gut gemacht`,
    gradeSlow: h => `${h} Treffer — fang mit den großen Zielen an, um ein Gefühl dafür zu bekommen`,
    note: 'Niedrige Genauigkeit heißt meist, dass die DPI deiner Maus zu hoch ist. Dreh die Empfindlichkeit herunter und bewege aus dem Arm — dann steigt die Trefferquote auf kleinen Zielen. Auf dem Handy sind kleine Ziele allein wegen der Fingergröße unfair.',
  },
  fr: {
    sizes: ['Grande', 'Moyenne', 'Petite'], targetPrefix: 'Cible', targetAria: 'Cible',
    hitsSub: acc => `touches · ${acc}% de précision`,
    introTitle: d => `Touche des cibles pendant ${d} secondes`, introSub: 'Les ratés comptent aussi — cliquer n’importe comment fait chuter ta précision',
    hits: 'Touches', misses: 'Ratés',
    gradeFast: h => `${h} touches — très rapide`,
    gradeGood: h => `${h} touches — bien joué`,
    gradeSlow: h => `${h} touches — commence par les grandes cibles pour prendre le geste`,
    note: 'Une précision faible signifie souvent que le DPI de ta souris est trop élevé. Baisse la sensibilité et bouge depuis le bras : ton taux de réussite sur les petites cibles remonte. Sur téléphone, les petites cibles sont injustes rien qu’à cause de la taille du doigt.',
  },
  hi: {
    sizes: ['बड़ा', 'सामान्य', 'छोटा'], targetPrefix: 'निशाना', targetAria: 'निशाना',
    hitsSub: acc => `सही निशाने · सटीकता ${acc}%`,
    introTitle: d => `${d} सेकंड तक निशाने लगाएँ`, introSub: 'चूकें भी गिनी जाती हैं — बेतरतीब क्लिक से सटीकता गिरती है',
    hits: 'सही निशाने', misses: 'चूकें',
    gradeFast: h => `${h} सही निशाने — बहुत तेज़`,
    gradeGood: h => `${h} सही निशाने — अच्छा चल रहा है`,
    gradeSlow: h => `${h} सही निशाने — पहले बड़े निशानों से अभ्यास कर लीजिए`,
    note: 'सटीकता कम हो तो अक्सर माउस की संवेदनशीलता (DPI) बहुत ज़्यादा होती है। संवेदनशीलता घटाकर बाँह से चलाएँ, तो छोटे निशानों पर भी सही निशाने बढ़ते हैं। फ़ोन पर उँगली के आकार के कारण छोटे निशाने अपने आप कठिन हो जाते हैं।',
  },
  'zh-hans': {
    sizes: ['大', '中', '小'],
    targetPrefix: '目标',
    targetAria: '目标',
    hitsSub: acc => `命中 · 准确率${acc}%`,
    introTitle: d => `${d}秒内打中目标`,
    introSub: '打空也算 — 乱点会拉低准确率',
    hits: '命中',
    misses: '打空',
    gradeFast: h => `命中${h}个 — 非常快`,
    gradeGood: h => `命中${h}个 — 不错`,
    gradeSlow: h => `命中${h}个 — 先用大目标找找手感`,
    note: '准确率低通常是鼠标DPI太高。把灵敏度调低、用手臂带动，小目标的命中率就上去了。手机上小目标不公平，纯粹是手指太大。',
  },
  'zh-hant': {
    sizes: ['大', '中', '小'],
    targetPrefix: '目標',
    targetAria: '目標',
    hitsSub: acc => `命中 · 準確率${acc}%`,
    introTitle: d => `${d}秒內打中目標`,
    introSub: '打空也算 — 亂點會拉低準確率',
    hits: '命中',
    misses: '打空',
    gradeFast: h => `命中${h}個 — 非常快`,
    gradeGood: h => `命中${h}個 — 不錯`,
    gradeSlow: h => `命中${h}個 — 先用大目標找找手感`,
    note: '準確率低通常是滑鼠DPI太高。把靈敏度調低、用手臂帶動，小目標的命中率就上去了。手機上小目標不公平，純粹是手指太大。',
  },
};

export const TYPING_UI: Record<GameLang, {
  sentences: string[];
  /** 한글은 자판을 누른 횟수, 나머지는 글자 수를 센다 */
  countStrokes: boolean;
  placeholder: string;
  currentSpeed: string; avgOf: (n: number) => string; bestSpeed: string;
  gradeFast: (v: number, acc: number) => string; gradeGood: (v: number, acc: number) => string;
  gradeSlow: (v: number, acc: number) => string;
  note: string;
}> = {
  ko: {
    sentences: [
      '오늘도 좋은 하루 되세요',
      '한글 타자 연습을 시작합니다',
      '천 리 길도 한 걸음부터 시작된다',
      '바람이 불어오는 곳 그곳으로 가네',
      '작은 습관이 큰 변화를 만든다',
      '노력은 배신하지 않는다고 믿는다',
      '가는 말이 고와야 오는 말이 곱다',
      '오늘 할 일을 내일로 미루지 말자',
    ],
    countStrokes: true,
    placeholder: '여기에 위 문장을 그대로 치세요',
    currentSpeed: '현재 타수', avgOf: n => `평균 (${n}문장)`, bestSpeed: '최고 타수',
    gradeFast: (v, acc) => `평균 ${v}타 · 정확도 ${acc}% — 아주 빠릅니다`,
    gradeGood: (v, acc) => `평균 ${v}타 · 정확도 ${acc}% — 평균 이상입니다`,
    gradeSlow: (v, acc) => `평균 ${v}타 · 정확도 ${acc}% — 속도보다 정확도를 먼저 올리세요`,
    note: '한글 타수는 자판을 누른 횟수로 셉니다 — ‘한’은 ㅎ·ㅏ·ㄴ 세 번이라 3타입니다. 성인 평균은 200~300타, 300타를 넘으면 빠른 편입니다. 정확도가 95% 아래라면 속도를 조금 늦추는 편이 결과적으로 더 빠릅니다.',
  },
  en: {
    sentences: [
      'The quick brown fox jumps over the lazy dog',
      'Practice makes the difference over time',
      'A journey of a thousand miles begins with one step',
      'Small habits add up to big changes',
      'Type steadily rather than quickly at first',
      'Accuracy comes before speed in typing',
      'The best time to start is right now',
      'Keep your wrists relaxed while you type',
    ],
    countStrokes: false,
    placeholder: 'Type the sentence above, exactly as it appears',
    currentSpeed: 'Current CPM', avgOf: n => `Average (${n} sentences)`, bestSpeed: 'Best CPM',
    gradeFast: (v, acc) => `${v} CPM · ${acc}% accuracy — very fast`,
    gradeGood: (v, acc) => `${v} CPM · ${acc}% accuracy — above average`,
    gradeSlow: (v, acc) => `${v} CPM · ${acc}% accuracy — get accuracy up before speed`,
    note: 'CPM counts characters per minute; divide by five for the usual WPM figure, so 250 CPM is about 50 WPM. Most adults land between 150 and 300 CPM. If your accuracy is under 95%, slowing down actually finishes the text sooner.',
  },
  es: {
    sentences: [
      'El veloz murciélago hindú comía feliz cardillo y kiwi',
      'La práctica constante marca la diferencia con el tiempo',
      'Un camino de mil kilómetros empieza con un solo paso',
      'Los hábitos pequeños suman cambios grandes',
      'Al principio escribe con calma antes que rápido',
      'En la escritura la precisión va antes que la velocidad',
      'El mejor momento para empezar es ahora mismo',
      'Mantén las muñecas relajadas mientras escribes',
    ],
    countStrokes: false,
    placeholder: 'Escribe la frase de arriba, tal como aparece',
    currentSpeed: 'CPM actual', avgOf: n => `Media (${n} frases)`, bestSpeed: 'Mejor CPM',
    gradeFast: (v, acc) => `${v} CPM · ${acc}% de precisión — muy rápido`,
    gradeGood: (v, acc) => `${v} CPM · ${acc}% de precisión — por encima de la media`,
    gradeSlow: (v, acc) => `${v} CPM · ${acc}% de precisión — sube la precisión antes que la velocidad`,
    note: 'CPM cuenta caracteres por minuto; divide por cinco para la cifra habitual de PPM, así que 250 CPM son unas 50 PPM. La mayoría de los adultos se mueve entre 150 y 300 CPM. Si tu precisión está por debajo del 95%, ir más despacio termina el texto antes.',
  },
  'pt-br': {
    sentences: [
      'Um pequeno jabuti xereta viu dez cegonhas felizes',
      'A prática constante faz diferença com o tempo',
      'Uma jornada de mil quilômetros começa com um passo',
      'Hábitos pequenos somam mudanças grandes',
      'No começo digite com calma em vez de rápido',
      'Na digitação a precisão vem antes da velocidade',
      'A melhor hora para começar é agora mesmo',
      'Mantenha os punhos relaxados enquanto digita',
    ],
    countStrokes: false,
    placeholder: 'Digite a frase acima, exatamente como aparece',
    currentSpeed: 'CPM atual', avgOf: n => `Média (${n} frases)`, bestSpeed: 'Melhor CPM',
    gradeFast: (v, acc) => `${v} CPM · ${acc}% de precisão — muito rápido`,
    gradeGood: (v, acc) => `${v} CPM · ${acc}% de precisão — acima da média`,
    gradeSlow: (v, acc) => `${v} CPM · ${acc}% de precisão — melhore a precisão antes da velocidade`,
    note: 'CPM conta caracteres por minuto; divida por cinco para a cifra habitual de PPM, então 250 CPM são cerca de 50 PPM. A maioria dos adultos fica entre 150 e 300 CPM. Se sua precisão está abaixo de 95%, ir mais devagar termina o texto mais cedo.',
  },
  ja: {
    sentences: [
      'いろはにほへと ちりぬるを',
      '毎日の積み重ねが力になります',
      '千里の道も一歩から始まります',
      '小さな習慣が大きな変化をつくります',
      '最初は速さよりも一定の速度で打ちましょう',
      'タイピングでは正確さが速さより先に来ます',
      '始めるのにいちばんいい時はいまです',
      '打つあいだは手首を楽にしておきましょう',
    ],
    countStrokes: false,
    placeholder: 'ここに上の文章をそのまま打ってください',
    currentSpeed: '現在の文字数', avgOf: n => `平均（${n}文）`, bestSpeed: '最高の文字数',
    gradeFast: (v, acc) => `1分あたり${v}文字 · 正確さ${acc}% — とても速いです`,
    gradeGood: (v, acc) => `1分あたり${v}文字 · 正確さ${acc}% — 平均以上です`,
    gradeSlow: (v, acc) => `1分あたり${v}文字 · 正確さ${acc}% — 速さより先に正確さを上げてください`,
    note: 'ここでは1分あたりの文字数を数えます。ローマ字入力ではキーを押す回数が文字数の倍前後になるので、数字はキー入力数ではなく出力された文字の数です。正確さが95%を下回るなら、少し速度を落とすほうが結果的に早く打ち終わります。',
  },
  de: {
    sentences: [
      'Franz jagt im komplett verwahrlosten Taxi quer durch Bayern',
      'Regelmäßiges Üben macht mit der Zeit den Unterschied',
      'Eine Reise von tausend Kilometern beginnt mit einem Schritt',
      'Kleine Gewohnheiten summieren sich zu großen Veränderungen',
      'Tippe am Anfang lieber gleichmäßig als schnell',
      'Beim Tippen kommt Genauigkeit vor Geschwindigkeit',
      'Der beste Zeitpunkt anzufangen ist genau jetzt',
      'Halte die Handgelenke locker, während du tippst',
    ],
    countStrokes: false,
    placeholder: 'Tippe den Satz oben genau so, wie er dasteht',
    currentSpeed: 'Aktuelle ZPM', avgOf: n => `Durchschnitt (${n} Sätze)`, bestSpeed: 'Beste ZPM',
    gradeFast: (v, acc) => `${v} ZPM · ${acc}% Genauigkeit — sehr schnell`,
    gradeGood: (v, acc) => `${v} ZPM · ${acc}% Genauigkeit — über dem Durchschnitt`,
    gradeSlow: (v, acc) => `${v} ZPM · ${acc}% Genauigkeit — bring die Genauigkeit vor die Geschwindigkeit`,
    note: 'ZPM zählt Zeichen pro Minute; geteilt durch fünf ergibt das die üblichen WPM, 250 ZPM sind also etwa 50 WPM. Die meisten Erwachsenen liegen zwischen 150 und 300 ZPM. Liegt deine Genauigkeit unter 95%, bist du langsamer getippt am Ende früher fertig.',
  },
  fr: {
    sentences: [
      'Portez ce vieux whisky au juge blond qui fume',
      'La pratique régulière fait la différence avec le temps',
      'Un voyage de mille kilomètres commence par un pas',
      'De petites habitudes font de grands changements',
      'Au début, tape régulièrement plutôt que vite',
      'En frappe, la précision passe avant la vitesse',
      'Le meilleur moment pour commencer, c’est maintenant',
      'Garde les poignets détendus pendant que tu tapes',
    ],
    countStrokes: false,
    placeholder: 'Tape la phrase ci-dessus, exactement telle quelle',
    currentSpeed: 'CPM actuels', avgOf: n => `Moyenne (${n} phrases)`, bestSpeed: 'Meilleurs CPM',
    gradeFast: (v, acc) => `${v} CPM · ${acc}% de précision — très rapide`,
    gradeGood: (v, acc) => `${v} CPM · ${acc}% de précision — au-dessus de la moyenne`,
    gradeSlow: (v, acc) => `${v} CPM · ${acc}% de précision — monte la précision avant la vitesse`,
    note: 'Les CPM comptent les caractères par minute ; divise par cinq pour obtenir les MPM habituels, donc 250 CPM font environ 50 MPM. La plupart des adultes se situent entre 150 et 300 CPM. Si ta précision est sous 95%, ralentir termine en fait le texte plus tôt.',
  },
  hi: {
    sentences: [
      'अभ्यास से ही धीरे-धीरे रफ़्तार बनती है',
      'लगातार अभ्यास समय के साथ फ़र्क़ ले आता है',
      'हज़ार किलोमीटर का सफ़र एक कदम से शुरू होता है',
      'छोटी आदतें मिलकर बड़ा बदलाव बनाती हैं',
      'शुरुआत में तेज़ नहीं, एक-सी रफ़्तार से लिखिए',
      'टाइपिंग में सटीकता रफ़्तार से पहले आती है',
      'शुरू करने का सबसे अच्छा समय अभी है',
      'टाइप करते समय कलाइयाँ ढीली रखिए',
    ],
    countStrokes: false,
    placeholder: 'ऊपर लिखा वाक्य जैसा है वैसा ही यहाँ लिखें',
    currentSpeed: 'अभी CPM', avgOf: n => `औसत (${n} वाक्य)`, bestSpeed: 'सबसे अच्छा CPM',
    gradeFast: (v, acc) => `${v} CPM · सटीकता ${acc}% — बहुत तेज़`,
    gradeGood: (v, acc) => `${v} CPM · सटीकता ${acc}% — औसत से ऊपर`,
    gradeSlow: (v, acc) => `${v} CPM · सटीकता ${acc}% — रफ़्तार से पहले सटीकता बढ़ाइए`,
    note: 'CPM प्रति मिनट अक्षर गिनता है; आम WPM पाने के लिए पाँच से भाग दें, तो 250 CPM लगभग 50 WPM हुआ। ज़्यादातर वयस्क 150 से 300 CPM के बीच रहते हैं। सटीकता 95% से नीचे हो तो थोड़ा धीमा चलना असल में जल्दी ख़त्म कराता है।',
  },
  'zh-hans': {
    sentences: ['敏捷的棕色狐狸跳过了懒狗', '日子久了，练习才见得出分别', '千里之行始于足下', '小习惯攒起来就是大变化', '刚开始与其求快，不如求稳', '打字里准确永远排在速度前面', '开始的最好时机就是现在', '打字的时候手腕放松一点'],
    countStrokes: true,
    placeholder: '照着上面的句子打，一模一样',
    currentSpeed: '当前 CPM',
    avgOf: n => `平均（${n}句）`,
    bestSpeed: '最好 CPM',
    gradeFast: (v, acc) => `${v} CPM · 准确率${acc}% — 非常快`,
    gradeGood: (v, acc) => `${v} CPM · 准确率${acc}% — 高于平均`,
    gradeSlow: (v, acc) => `${v} CPM · 准确率${acc}% — 先把准确率提上去再追速度`,
    note: 'CPM是每分钟字符数。中文打字一般按每分钟字数看，60字/分就算入门、100字/分以上算熟练。准确率低于95%的话，慢下来反而更快打完。',
  },
  'zh-hant': {
    sentences: ['敏捷的棕色狐狸跳過了懶狗', '日子久了，練習才見得出分別', '千里之行始於足下', '小習慣攢起來就是大變化', '剛開始與其求快，不如求穩', '打字裡準確永遠排在速度前面', '開始的最好時機就是現在', '打字的時候手腕放鬆一點'],
    countStrokes: true,
    placeholder: '照著上面的句子打，一模一樣',
    currentSpeed: '目前 CPM',
    avgOf: n => `平均（${n}句）`,
    bestSpeed: '最好 CPM',
    gradeFast: (v, acc) => `${v} CPM · 準確率${acc}% — 非常快`,
    gradeGood: (v, acc) => `${v} CPM · 準確率${acc}% — 高於平均`,
    gradeSlow: (v, acc) => `${v} CPM · 準確率${acc}% — 先把準確率提上去再追速度`,
    note: 'CPM是每分鐘字元數。中文打字一般按每分鐘字數看，60字/分就算入門、100字/分以上算熟練。準確率低於95%的話，慢下來反而更快打完。',
  },
};

export const MEMORY_UI: Record<GameLang, {
  buttonAria: (n: number) => string;
  idle: string; show: string; input: (a: number, b: number) => string; over: (l: number) => string;
  currentLevel: string; toRemember: string; bestLevel: string;
  gradeGreat: (l: number) => string; gradeGood: (l: number) => string; gradeSlow: (l: number) => string;
  note: string;
}> = {
  ko: {
    buttonAria: n => `${n}번 단추`,
    idle: '순서를 기억했다가 그대로 누르세요', show: '잘 보세요…',
    input: (a, b) => `따라 누르세요 (${a}/${b})`, over: l => `${l}단계에서 끝났습니다`,
    currentLevel: '현재 단계', toRemember: '기억할 개수', bestLevel: '최고 단계',
    gradeGreat: l => `${l}단계 — 아주 좋은 기억력입니다`,
    gradeGood: l => `${l}단계 — 평균 이상입니다`,
    gradeSlow: l => `${l}단계 — 소리 내어 순서를 읊으면 더 오래 기억됩니다`,
    note: '사람이 한 번에 붙잡아 두는 정보는 보통 다섯에서 아홉 덩어리입니다. 순서를 ‘초록-빨강-파랑’처럼 말로 묶어 외우면 덩어리 수가 줄어 더 길게 갈 수 있습니다.',
  },
  en: {
    buttonAria: n => `Button ${n}`,
    idle: 'Remember the order, then press it back', show: 'Watch closely…',
    input: (a, b) => `Press them back (${a}/${b})`, over: l => `You reached level ${l}`,
    currentLevel: 'Current level', toRemember: 'To remember', bestLevel: 'Best level',
    gradeGreat: l => `Level ${l} — a very good memory`,
    gradeGood: l => `Level ${l} — above average`,
    gradeSlow: l => `Level ${l} — saying the order out loud makes it stick longer`,
    note: 'People hold about five to nine chunks at once. Binding the sequence into words — ‘green-red-blue’ — cuts the number of chunks, which is how you get further.',
  },
  es: {
    buttonAria: n => `Botón ${n}`,
    idle: 'Recuerda el orden y vuelve a pulsarlo', show: 'Fíjate bien…',
    input: (a, b) => `Púlsalos de vuelta (${a}/${b})`, over: l => `Llegaste al nivel ${l}`,
    currentLevel: 'Nivel actual', toRemember: 'Para recordar', bestLevel: 'Mejor nivel',
    gradeGreat: l => `Nivel ${l} — muy buena memoria`,
    gradeGood: l => `Nivel ${l} — por encima de la media`,
    gradeSlow: l => `Nivel ${l} — decir el orden en voz alta lo fija más tiempo`,
    note: 'Las personas retienen entre cinco y nueve bloques a la vez. Atar la secuencia en palabras — ‘verde-rojo-azul’ — reduce el número de bloques, y así se llega más lejos.',
  },
  'pt-br': {
    buttonAria: n => `Botão ${n}`,
    idle: 'Lembre a ordem e aperte de volta', show: 'Observe bem…',
    input: (a, b) => `Aperte de volta (${a}/${b})`, over: l => `Você chegou ao nível ${l}`,
    currentLevel: 'Nível atual', toRemember: 'Para lembrar', bestLevel: 'Melhor nível',
    gradeGreat: l => `Nível ${l} — memória muito boa`,
    gradeGood: l => `Nível ${l} — acima da média`,
    gradeSlow: l => `Nível ${l} — dizer a ordem em voz alta fixa por mais tempo`,
    note: 'As pessoas seguram de cinco a nove blocos de uma vez. Amarrar a sequência em palavras — ‘verde-vermelho-azul’ — reduz o número de blocos, e é assim que se vai mais longe.',
  },
  ja: {
    buttonAria: n => `${n}番のボタン`,
    idle: '順番を覚えて、そのとおりに押してください', show: 'よく見てください…',
    input: (a, b) => `同じ順番で押してください（${a}/${b}）`, over: l => `レベル${l}まで進みました`,
    currentLevel: '現在のレベル', toRemember: '覚える数', bestLevel: '最高レベル',
    gradeGreat: l => `レベル${l} — とても良い記憶力です`,
    gradeGood: l => `レベル${l} — 平均以上です`,
    gradeSlow: l => `レベル${l} — 順番を声に出して唱えると長く覚えていられます`,
    note: '人が一度に保てる情報はふつう5〜9のかたまりです。順番を「緑・赤・青」のように言葉でまとめて覚えると、かたまりの数が減ってもっと先まで進めます。',
  },
  de: {
    buttonAria: n => `Taste ${n}`,
    idle: 'Merke dir die Reihenfolge und drücke sie nach', show: 'Genau hinsehen…',
    input: (a, b) => `Drücke sie nach (${a}/${b})`, over: l => `Du hast Ebene ${l} erreicht`,
    currentLevel: 'Aktuelle Ebene', toRemember: 'Zu merken', bestLevel: 'Beste Ebene',
    gradeGreat: l => `Ebene ${l} — ein sehr gutes Gedächtnis`,
    gradeGood: l => `Ebene ${l} — über dem Durchschnitt`,
    gradeSlow: l => `Ebene ${l} — die Reihenfolge laut mitzusprechen hält länger`,
    note: 'Menschen halten etwa fünf bis neun Blöcke gleichzeitig. Die Folge in Worte zu binden — ‘grün-rot-blau’ — verringert die Zahl der Blöcke, und genau so kommt man weiter.',
  },
  fr: {
    buttonAria: n => `Bouton ${n}`,
    idle: 'Retiens l’ordre, puis rappuie dessus', show: 'Regarde bien…',
    input: (a, b) => `Rappuie dessus (${a}/${b})`, over: l => `Tu as atteint le niveau ${l}`,
    currentLevel: 'Niveau actuel', toRemember: 'À retenir', bestLevel: 'Meilleur niveau',
    gradeGreat: l => `Niveau ${l} — très bonne mémoire`,
    gradeGood: l => `Niveau ${l} — au-dessus de la moyenne`,
    gradeSlow: l => `Niveau ${l} — dire l’ordre à voix haute le fixe plus longtemps`,
    note: 'On retient entre cinq et neuf blocs à la fois. Lier la séquence en mots — ‘vert-rouge-bleu’ — réduit le nombre de blocs, et c’est comme ça qu’on va plus loin.',
  },
  hi: {
    buttonAria: n => `बटन ${n}`,
    idle: 'क्रम याद रखकर उसी तरह दबाएँ', show: 'ध्यान से देखिए…',
    input: (a, b) => `उसी क्रम में दबाएँ (${a}/${b})`, over: l => `आप स्तर ${l} तक पहुँचे`,
    currentLevel: 'अभी का स्तर', toRemember: 'याद रखने हैं', bestLevel: 'सबसे ऊँचा स्तर',
    gradeGreat: l => `स्तर ${l} — बहुत अच्छी स्मृति`,
    gradeGood: l => `स्तर ${l} — औसत से ऊपर`,
    gradeSlow: l => `स्तर ${l} — क्रम को बोलकर दोहराने से वह देर तक टिकता है`,
    note: 'इंसान एक बार में आम तौर पर पाँच से नौ टुकड़े ही थाम पाता है। क्रम को ‘हरा-लाल-नीला’ की तरह शब्दों में बाँध लें तो टुकड़ों की संख्या घट जाती है और आगे तक पहुँचा जा सकता है।',
  },
  'zh-hans': {
    buttonAria: n => `按钮${n}`,
    idle: '记住顺序，然后按回去',
    show: '看仔细…',
    input: (a, b) => `按回去（${a}/${b}）`,
    over: l => `你走到了第${l}关`,
    currentLevel: '当前关卡',
    toRemember: '要记的个数',
    bestLevel: '最高关卡',
    gradeGreat: l => `第${l}关 — 记性非常好`,
    gradeGood: l => `第${l}关 — 高于平均`,
    gradeSlow: l => `第${l}关 — 把顺序念出声，记得更久`,
    note: '人一次大概能装五到九个组块。把序列串成词 — 「绿红蓝」 — 组块数就少了，这就是能走更远的办法。',
  },
  'zh-hant': {
    buttonAria: n => `按鈕${n}`,
    idle: '記住順序，然後按回去',
    show: '看仔細…',
    input: (a, b) => `按回去（${a}/${b}）`,
    over: l => `你走到了第${l}關`,
    currentLevel: '目前關卡',
    toRemember: '要記的個數',
    bestLevel: '最高關卡',
    gradeGreat: l => `第${l}關 — 記性非常好`,
    gradeGood: l => `第${l}關 — 高於平均`,
    gradeSlow: l => `第${l}關 — 把順序唸出聲，記得更久`,
    note: '人一次大概能裝五到九個組塊。把序列串成詞 — 「綠紅藍」 — 組塊數就少了，這就是能走更遠的辦法。',
  },
};

export const NUMBER_MEMORY_UI: Record<GameLang, {
  memorise: string; briefly: string; typeBack: string;
  reached: (d: number) => string; answerVs: (a: string, i: string) => string; nothing: string;
  confirm: string; currentDigits: string; memorised: string;
  note: string;
}> = {
  ko: {
    memorise: '숫자를 외우세요', briefly: '잠깐 보였다가 사라집니다', typeBack: '방금 본 숫자를 입력하세요',
    reached: d => `${d}자리까지 외웠습니다`, answerVs: (a, i) => `정답 ${a} · 입력 ${i}`, nothing: '없음',
    confirm: '확인', currentDigits: '현재 자릿수', memorised: '외운 자릿수',
    note: '사람이 한 번에 외우는 숫자는 보통 일곱 자리 안팎입니다. 전화번호가 그 길이인 것도 우연이 아닙니다. 숫자를 두세 개씩 묶어 ‘삼사-이오’처럼 덩어리로 읽으면 열 자리를 넘기기도 합니다.',
  },
  en: {
    memorise: 'Memorise the number', briefly: 'It shows briefly, then disappears', typeBack: 'Type the number you just saw',
    reached: d => `You held ${d} digits`, answerVs: (a, i) => `Answer ${a} · you typed ${i}`, nothing: 'nothing',
    confirm: 'Check', currentDigits: 'Current digits', memorised: 'Digits held',
    note: 'People usually hold around seven digits at once — it is no coincidence that phone numbers are about that long. Reading them in chunks of two or three, ‘thirty-four, twenty-five’, gets some people past ten.',
  },
  es: {
    memorise: 'Memoriza el número', briefly: 'Se muestra un instante y desaparece', typeBack: 'Escribe el número que acabas de ver',
    reached: d => `Retuviste ${d} dígitos`, answerVs: (a, i) => `Correcto ${a} · escribiste ${i}`, nothing: 'nada',
    confirm: 'Comprobar', currentDigits: 'Dígitos actuales', memorised: 'Dígitos retenidos',
    note: 'La gente suele retener unos siete dígitos a la vez — no es casualidad que los teléfonos midan más o menos eso. Leerlos en bloques de dos o tres, ‘treinta y cuatro, veinticinco’, permite a algunos pasar de diez.',
  },
  'pt-br': {
    memorise: 'Memorize o número', briefly: 'Aparece por um instante e desaparece', typeBack: 'Digite o número que você acabou de ver',
    reached: d => `Você segurou ${d} dígitos`, answerVs: (a, i) => `Certo ${a} · você digitou ${i}`, nothing: 'nada',
    confirm: 'Conferir', currentDigits: 'Dígitos atuais', memorised: 'Dígitos segurados',
    note: 'As pessoas costumam segurar uns sete dígitos de uma vez — não é coincidência que telefones tenham mais ou menos isso. Ler em blocos de dois ou três, ‘trinta e quatro, vinte e cinco’, faz alguns passarem de dez.',
  },
  ja: {
    memorise: '数字を覚えてください', briefly: '一瞬表示されて消えます', typeBack: 'いま見た数字を入力してください',
    reached: d => `${d}桁まで覚えられました`, answerVs: (a, i) => `正解 ${a} · 入力 ${i}`, nothing: 'なし',
    confirm: '確認', currentDigits: '現在の桁数', memorised: '覚えた桁数',
    note: '人が一度に覚えられる数字はふつう7桁前後です。電話番号がその長さなのも偶然ではありません。数字を2〜3個ずつまとめて「さんじゅうよん、にじゅうご」のように読むと、10桁を超える人もいます。',
  },
  de: {
    memorise: 'Merke dir die Zahl', briefly: 'Sie erscheint kurz und verschwindet', typeBack: 'Tippe die Zahl ein, die du gerade gesehen hast',
    reached: d => `Du hast ${d} Ziffern gehalten`, answerVs: (a, i) => `Richtig ${a} · getippt ${i}`, nothing: 'nichts',
    confirm: 'Prüfen', currentDigits: 'Aktuelle Ziffern', memorised: 'Gehaltene Ziffern',
    note: 'Menschen halten meist etwa sieben Ziffern gleichzeitig — dass Telefonnummern ungefähr so lang sind, ist kein Zufall. Sie in Zweier- oder Dreierblöcken zu lesen, ‘vierunddreißig, fünfundzwanzig’, bringt manche über zehn.',
  },
  fr: {
    memorise: 'Retiens le nombre', briefly: 'Il s’affiche un instant puis disparaît', typeBack: 'Retape le nombre que tu viens de voir',
    reached: d => `Tu as retenu ${d} chiffres`, answerVs: (a, i) => `Correct ${a} · tu as tapé ${i}`, nothing: 'rien',
    confirm: 'Vérifier', currentDigits: 'Chiffres actuels', memorised: 'Chiffres retenus',
    note: 'On retient d’ordinaire une septaine de chiffres d’un coup — ce n’est pas un hasard si les numéros de téléphone font à peu près cette longueur. Les lire par blocs de deux ou trois, ‘trente-quatre, vingt-cinq’, en fait dépasser dix à certains.',
  },
  hi: {
    memorise: 'अंक याद कीजिए', briefly: 'एक पल दिखकर गायब हो जाता है', typeBack: 'अभी देखा हुआ अंक लिखिए',
    reached: d => `आपने ${d} अंक याद रखे`, answerVs: (a, i) => `सही ${a} · आपने लिखा ${i}`, nothing: 'कुछ नहीं',
    confirm: 'जाँचें', currentDigits: 'अभी के अंक', memorised: 'याद रखे अंक',
    note: 'इंसान एक बार में आम तौर पर सात अंक के आस-पास याद रख पाता है — फ़ोन नंबर उतने ही लंबे होते हैं, यह संयोग नहीं है। अंकों को दो-तीन के टुकड़ों में ‘चौंतीस, पच्चीस’ की तरह पढ़ने से कुछ लोग दस के पार भी चले जाते हैं।',
  },
  'zh-hans': {
    memorise: '记住这个数字',
    briefly: '它只出现一下，然后就消失',
    typeBack: '把刚看到的数字打出来',
    reached: d => `你记住了${d}位`,
    answerVs: (a, i) => `答案 ${a} · 你打的 ${i}`,
    nothing: '什么都没有',
    confirm: '确认',
    currentDigits: '当前位数',
    memorised: '记住的位数',
    note: '人一次一般记得住七位上下 — 电话号码差不多就是这个长度，不是巧合。按两三位一组读，「三四、二五」，有些人能过十位。',
  },
  'zh-hant': {
    memorise: '記住這個數字',
    briefly: '它只出現一下，然後就消失',
    typeBack: '把剛看到的數字打出來',
    reached: d => `你記住了${d}位`,
    answerVs: (a, i) => `答案 ${a} · 你打的 ${i}`,
    nothing: '什麼都沒有',
    confirm: '確認',
    currentDigits: '目前位數',
    memorised: '記住的位數',
    note: '人一次一般記得住七位上下 — 電話號碼差不多就是這個長度，不是巧合。按兩三位一組讀，「三四、二五」，有些人能過十位。',
  },
};

export const SEQUENCE_UI: Record<GameLang, {
  cellAria: (n: number) => string;
  idle: string; show: string; input: (a: number, b: number) => string; over: (l: number) => string;
  grid: string; bestLevel: string;
  gradeGood: (l: number) => string; gradeSlow: (l: number) => string;
  note: string;
}> = {
  ko: {
    cellAria: n => `${n}번 칸`,
    idle: '켜진 칸의 위치를 기억하세요', show: '잘 보세요…',
    input: (a, b) => `켜졌던 칸을 누르세요 (${a}/${b})`,
    over: l => `${l}단계에서 끝났습니다 — 빨간 칸이 틀린 곳입니다`,
    grid: '격자', bestLevel: '최고 단계',
    gradeGood: l => `${l}단계 — 공간 기억이 좋습니다`,
    gradeSlow: l => `${l}단계 — 모양으로 묶어 외우면 늘어납니다`,
    note: '칸 하나하나를 외우는 대신 켜진 칸들이 이루는 모양(ㄱ자, 대각선)으로 기억하면 훨씬 오래 갑니다. 위치 기억은 순서 기억과 다른 종류라, 한쪽을 잘해도 다른 쪽이 약할 수 있습니다.',
  },
  en: {
    cellAria: n => `Cell ${n}`,
    idle: 'Remember which cells light up', show: 'Watch closely…',
    input: (a, b) => `Press the cells that lit up (${a}/${b})`,
    over: l => `You reached level ${l} — the red cells are the ones you missed`,
    grid: 'Grid', bestLevel: 'Best level',
    gradeGood: l => `Level ${l} — good spatial memory`,
    gradeSlow: l => `Level ${l} — grouping them into a shape gets you further`,
    note: 'Instead of memorising each cell, remember the shape the lit cells make — an L, a diagonal. Spatial memory is a different faculty from sequence memory, so being good at one does not mean you are good at the other.',
  },
  es: {
    cellAria: n => `Casilla ${n}`,
    idle: 'Recuerda qué casillas se iluminan', show: 'Fíjate bien…',
    input: (a, b) => `Pulsa las casillas que se iluminaron (${a}/${b})`,
    over: l => `Llegaste al nivel ${l} — las casillas rojas son las que fallaste`,
    grid: 'Cuadrícula', bestLevel: 'Mejor nivel',
    gradeGood: l => `Nivel ${l} — buena memoria espacial`,
    gradeSlow: l => `Nivel ${l} — agruparlas en una forma te lleva más lejos`,
    note: 'En lugar de memorizar cada casilla, recuerda la forma que dibujan las iluminadas — una L, una diagonal. La memoria espacial es una facultad distinta de la memoria de secuencias, así que ser bueno en una no significa serlo en la otra.',
  },
  'pt-br': {
    cellAria: n => `Quadrado ${n}`,
    idle: 'Lembre quais quadrados acendem', show: 'Observe bem…',
    input: (a, b) => `Aperte os quadrados que acenderam (${a}/${b})`,
    over: l => `Você chegou ao nível ${l} — os quadrados vermelhos são os que você errou`,
    grid: 'Grade', bestLevel: 'Melhor nível',
    gradeGood: l => `Nível ${l} — boa memória espacial`,
    gradeSlow: l => `Nível ${l} — agrupar em uma forma leva você mais longe`,
    note: 'Em vez de memorizar cada quadrado, lembre a forma que os acesos desenham — um L, uma diagonal. A memória espacial é uma faculdade diferente da memória de sequência, então ser bom em uma não quer dizer ser bom na outra.',
  },
  ja: {
    cellAria: n => `${n}番のマス`,
    idle: '光ったマスの位置を覚えてください', show: 'よく見てください…',
    input: (a, b) => `光ったマスを押してください（${a}/${b}）`,
    over: l => `レベル${l}まで進みました — 赤いマスが間違えたところです`,
    grid: 'マス', bestLevel: '最高レベル',
    gradeGood: l => `レベル${l} — 空間の記憶が良いです`,
    gradeSlow: l => `レベル${l} — 形としてまとめて覚えると伸びます`,
    note: 'マスを一つずつ覚えるのではなく、光ったマスがつくる形（L字、対角線）として覚えるとずっと長くもちます。位置の記憶は順番の記憶とは別の種類なので、片方が得意でももう片方は苦手なことがあります。',
  },
  de: {
    cellAria: n => `Feld ${n}`,
    idle: 'Merke dir, welche Felder aufleuchten', show: 'Genau hinsehen…',
    input: (a, b) => `Drücke die Felder, die aufgeleuchtet sind (${a}/${b})`,
    over: l => `Du hast Ebene ${l} erreicht — die roten Felder hast du verpasst`,
    grid: 'Raster', bestLevel: 'Beste Ebene',
    gradeGood: l => `Ebene ${l} — gutes räumliches Gedächtnis`,
    gradeSlow: l => `Ebene ${l} — sie zu einer Form zusammenzufassen bringt dich weiter`,
    note: 'Statt jedes Feld einzeln zu merken, merke dir die Form, die die leuchtenden Felder bilden — ein L, eine Diagonale. Räumliches Gedächtnis ist eine andere Fähigkeit als Reihenfolgegedächtnis; in einem gut zu sein heißt nicht, im anderen gut zu sein.',
  },
  fr: {
    cellAria: n => `Case ${n}`,
    idle: 'Retiens quelles cases s’allument', show: 'Regarde bien…',
    input: (a, b) => `Appuie sur les cases qui se sont allumées (${a}/${b})`,
    over: l => `Tu as atteint le niveau ${l} — les cases rouges sont celles que tu as manquées`,
    grid: 'Grille', bestLevel: 'Meilleur niveau',
    gradeGood: l => `Niveau ${l} — bonne mémoire spatiale`,
    gradeSlow: l => `Niveau ${l} — les regrouper en une forme te mène plus loin`,
    note: 'Plutôt que de mémoriser chaque case, retiens la forme dessinée par les cases allumées — un L, une diagonale. La mémoire spatiale est une faculté distincte de la mémoire de séquence : être bon dans l’une ne veut pas dire l’être dans l’autre.',
  },
  hi: {
    cellAria: n => `खाना ${n}`,
    idle: 'जो खाने जलते हैं उनकी जगह याद रखिए', show: 'ध्यान से देखिए…',
    input: (a, b) => `जो खाने जले थे उन्हें दबाएँ (${a}/${b})`,
    over: l => `आप स्तर ${l} तक पहुँचे — लाल खाने वही हैं जो छूट गए`,
    grid: 'जाल', bestLevel: 'सबसे ऊँचा स्तर',
    gradeGood: l => `स्तर ${l} — स्थान की स्मृति अच्छी है`,
    gradeSlow: l => `स्तर ${l} — आकृति के रूप में जोड़कर याद रखें तो आगे बढ़ेंगे`,
    note: 'हर खाने को अलग-अलग याद करने के बजाय जले खाने जो आकृति बनाते हैं — L, तिरछी रेखा — उसे याद रखें तो बहुत देर टिकता है। स्थान की स्मृति क्रम की स्मृति से अलग तरह की है, इसलिए एक में अच्छे होने का मतलब दूसरे में भी अच्छा होना नहीं।',
  },
  'zh-hans': {
    cellAria: n => `格子${n}`,
    idle: '记住哪几格亮了',
    show: '看仔细…',
    input: (a, b) => `按下亮过的格子（${a}/${b}）`,
    over: l => `你走到了第${l}关 — 红色是漏掉的格子`,
    grid: '格子',
    bestLevel: '最高关卡',
    gradeGood: l => `第${l}关 — 空间记忆不错`,
    gradeSlow: l => `第${l}关 — 把它们看成一个图形能走更远`,
    note: '别一格一格地背，记亮起来的格子拼成什么形状 — 一个L、一条斜线。空间记忆和顺序记忆是两种不同的能力，一个强不代表另一个也强。',
  },
  'zh-hant': {
    cellAria: n => `格子${n}`,
    idle: '記住哪幾格亮了',
    show: '看仔細…',
    input: (a, b) => `按下亮過的格子（${a}/${b}）`,
    over: l => `你走到了第${l}關 — 紅色是漏掉的格子`,
    grid: '格子',
    bestLevel: '最高關卡',
    gradeGood: l => `第${l}關 — 空間記憶不錯`,
    gradeSlow: l => `第${l}關 — 把它們看成一個圖形能走更遠`,
    note: '別一格一格地背，記亮起來的格子拼成什麼形狀 — 一個L、一條斜線。空間記憶和順序記憶是兩種不同的能力，一個強不代表另一個也強。',
  },
};

export const COLOR_BLIND_UI: Record<GameLang, {
  cellAria: (n: number) => string;
  over: (l: number) => string; idle: string;
  colorDiff: string; bestLevel: string;
  gradeSharp: (l: number) => string; gradeGood: (l: number) => string; gradeSlow: (l: number) => string;
  noteTitle: string; note: string;
}> = {
  ko: {
    cellAria: n => `${n}번 색`,
    over: l => `${l}단계에서 끝났습니다 — 정답은 표시된 칸입니다`,
    idle: '색이 다른 칸 하나를 찾아 누르세요',
    colorDiff: '색 차이', bestLevel: '최고 단계',
    gradeSharp: l => `${l}단계 — 아주 예민한 눈입니다`,
    gradeGood: l => `${l}단계 — 평균 이상입니다`,
    gradeSlow: l => `${l}단계 — 화면 밝기를 올리고 다시 해보세요`,
    noteTitle: '색약 검사가 아닙니다',
    note: '이 게임은 명도 차이를 구별하는 능력을 봅니다. 색약·색맹 여부는 이시하라 검사처럼 특정 색 조합을 쓰는 검사로만 알 수 있고, 정확한 판정은 안과에서 받아야 합니다. 결과는 화면 품질과 밝기, 주변 조명에 따라서도 크게 달라집니다.',
  },
  en: {
    cellAria: n => `Colour ${n}`,
    over: l => `You reached level ${l} — the marked square was the answer`,
    idle: 'Find and press the one square that is a different colour',
    colorDiff: 'Colour difference', bestLevel: 'Best level',
    gradeSharp: l => `Level ${l} — a very sharp eye`,
    gradeGood: l => `Level ${l} — above average`,
    gradeSlow: l => `Level ${l} — turn your screen brightness up and try again`,
    noteTitle: 'This is not a colour blindness test',
    note: 'This game measures how well you tell shades apart. Colour blindness can only be identified by a test built on specific colour combinations, like Ishihara plates, and a real diagnosis has to come from an optometrist. Results also swing considerably with screen quality, brightness and the light in the room.',
  },
  es: {
    cellAria: n => `Color ${n}`,
    over: l => `Llegaste al nivel ${l} — la casilla marcada era la respuesta`,
    idle: 'Encuentra y pulsa la única casilla de otro color',
    colorDiff: 'Diferencia de color', bestLevel: 'Mejor nivel',
    gradeSharp: l => `Nivel ${l} — un ojo muy fino`,
    gradeGood: l => `Nivel ${l} — por encima de la media`,
    gradeSlow: l => `Nivel ${l} — sube el brillo de la pantalla y vuelve a probar`,
    noteTitle: 'Esto no es un test de daltonismo',
    note: 'Este juego mide lo bien que distingues tonos. El daltonismo solo se identifica con una prueba construida sobre combinaciones de color concretas, como las láminas de Ishihara, y un diagnóstico real tiene que venir de un oftalmólogo. Los resultados también oscilan bastante según la calidad de la pantalla, el brillo y la luz de la habitación.',
  },
  'pt-br': {
    cellAria: n => `Cor ${n}`,
    over: l => `Você chegou ao nível ${l} — o quadrado marcado era a resposta`,
    idle: 'Ache e aperte o único quadrado de outra cor',
    colorDiff: 'Diferença de cor', bestLevel: 'Melhor nível',
    gradeSharp: l => `Nível ${l} — olho muito afiado`,
    gradeGood: l => `Nível ${l} — acima da média`,
    gradeSlow: l => `Nível ${l} — aumente o brilho da tela e tente de novo`,
    noteTitle: 'Isto não é um teste de daltonismo',
    note: 'Este jogo mede o quanto você distingue tons. O daltonismo só é identificado por um teste montado sobre combinações de cor específicas, como as pranchas de Ishihara, e um diagnóstico de verdade precisa vir de um oftalmologista. Os resultados também variam bastante com a qualidade da tela, o brilho e a luz do ambiente.',
  },
  ja: {
    cellAria: n => `${n}番の色`,
    over: l => `レベル${l}まで進みました — 印の付いたマスが正解です`,
    idle: '色が違うマスを一つ見つけて押してください',
    colorDiff: '色の差', bestLevel: '最高レベル',
    gradeSharp: l => `レベル${l} — とても目が敏感です`,
    gradeGood: l => `レベル${l} — 平均以上です`,
    gradeSlow: l => `レベル${l} — 画面の明るさを上げてもう一度やってみてください`,
    noteTitle: '色覚検査ではありません',
    note: 'このゲームは明るさの差を見分ける力を見ています。色覚の特性は石原式のように特定の色の組み合わせを使う検査でしか分からず、正確な判定は眼科で受ける必要があります。結果は画面の品質や明るさ、部屋の照明によっても大きく変わります。',
  },
  de: {
    cellAria: n => `Farbe ${n}`,
    over: l => `Du hast Ebene ${l} erreicht — das markierte Feld war die Antwort`,
    idle: 'Finde das eine Feld mit anderer Farbe und drücke es',
    colorDiff: 'Farbunterschied', bestLevel: 'Beste Ebene',
    gradeSharp: l => `Ebene ${l} — ein sehr scharfes Auge`,
    gradeGood: l => `Ebene ${l} — über dem Durchschnitt`,
    gradeSlow: l => `Ebene ${l} — dreh die Bildschirmhelligkeit hoch und versuch es nochmal`,
    noteTitle: 'Das ist kein Farbenblindheitstest',
    note: 'Dieses Spiel misst, wie gut du Abstufungen auseinanderhältst. Farbenblindheit lässt sich nur mit einem Test feststellen, der auf bestimmten Farbkombinationen aufbaut, etwa den Ishihara-Tafeln, und eine echte Diagnose muss von einer Augenärztin kommen. Die Ergebnisse schwanken außerdem erheblich mit Bildschirmqualität, Helligkeit und dem Licht im Raum.',
  },
  fr: {
    cellAria: n => `Couleur ${n}`,
    over: l => `Tu as atteint le niveau ${l} — la case marquée était la réponse`,
    idle: 'Trouve et appuie sur la seule case d’une autre couleur',
    colorDiff: 'Écart de couleur', bestLevel: 'Meilleur niveau',
    gradeSharp: l => `Niveau ${l} — un œil très fin`,
    gradeGood: l => `Niveau ${l} — au-dessus de la moyenne`,
    gradeSlow: l => `Niveau ${l} — monte la luminosité de l’écran et recommence`,
    noteTitle: 'Ceci n’est pas un test de daltonisme',
    note: 'Ce jeu mesure ta capacité à distinguer des nuances. Le daltonisme ne s’identifie qu’avec un test bâti sur des combinaisons de couleurs précises, comme les planches d’Ishihara, et un vrai diagnostic doit venir d’un ophtalmologue. Les résultats varient aussi beaucoup selon la qualité de l’écran, la luminosité et l’éclairage de la pièce.',
  },
  hi: {
    cellAria: n => `रंग ${n}`,
    over: l => `आप स्तर ${l} तक पहुँचे — चिह्नित खाना ही सही जवाब था`,
    idle: 'अलग रंग वाला एक खाना खोजकर दबाएँ',
    colorDiff: 'रंग का अंतर', bestLevel: 'सबसे ऊँचा स्तर',
    gradeSharp: l => `स्तर ${l} — बहुत तेज़ नज़र`,
    gradeGood: l => `स्तर ${l} — औसत से ऊपर`,
    gradeSlow: l => `स्तर ${l} — स्क्रीन की चमक बढ़ाकर फिर कोशिश करें`,
    noteTitle: 'यह वर्णांधता की जाँच नहीं है',
    note: 'यह खेल देखता है कि आप रंगों की छायाओं में अंतर कितना पकड़ पाते हैं। वर्णांधता का पता इशिहारा जैसी विशेष रंग-संयोजनों वाली जाँच से ही चलता है, और सही निदान नेत्र चिकित्सक से ही मिलना चाहिए। नतीजे स्क्रीन की गुणवत्ता, चमक और कमरे की रोशनी से भी काफ़ी बदलते हैं।',
  },
  'zh-hans': {
    cellAria: n => `颜色${n}`,
    over: l => `你走到了第${l}关 — 标记的那块是答案`,
    idle: '找出颜色不一样的那一块并按下去',
    colorDiff: '色差',
    bestLevel: '最高关卡',
    gradeSharp: l => `第${l}关 — 眼睛非常尖`,
    gradeGood: l => `第${l}关 — 高于平均`,
    gradeSlow: l => `第${l}关 — 把屏幕亮度调高再试一次`,
    noteTitle: '这不是色盲检查',
    note: '这个游戏量的是你分辨深浅的能力。色盲只能靠石原氏色盘这类按特定配色做的检查来判断，真正的诊断得由验光师来下。结果还会随屏幕素质、亮度和房间的光线大幅摇摆。',
  },
  'zh-hant': {
    cellAria: n => `顏色${n}`,
    over: l => `你走到了第${l}關 — 標記的那塊是答案`,
    idle: '找出顏色不一樣的那一塊並按下去',
    colorDiff: '色差',
    bestLevel: '最高關卡',
    gradeSharp: l => `第${l}關 — 眼睛非常尖`,
    gradeGood: l => `第${l}關 — 高於平均`,
    gradeSlow: l => `第${l}關 — 把螢幕亮度調高再試一次`,
    noteTitle: '這不是色盲檢查',
    note: '這個遊戲量的是你分辨深淺的能力。色盲只能靠石原氏色盤這類按特定配色做的檢查來判斷，真正的診斷得由驗光師來下。結果還會隨螢幕素質、亮度和房間的光線大幅搖擺。',
  },
};

export const HEARING_UI: Record<GameLang, {
  ages: string[];
  nowPlaying: string; stepOf: (i: number, total: number) => string;
  stopSound: string; playThis: string; canHear: string; cannotHear: string;
  limitLabel: string; belowOne: string;
  currentStep: string; currentFreq: string; limitStat: string; measuring: string;
  tipsTitle: string; tips: string[];
}> = {
  ko: {
    ages: ['10대 후반~20대 초반 수준으로 들립니다', '20대 중반 수준입니다', '30대 수준입니다', '40대 수준입니다', '50대 수준입니다', '8kHz 이하만 들린다면 조용한 곳에서 이어폰으로 다시 해보세요'],
    nowPlaying: '지금 재생 중인 주파수', stepOf: (i, total) => `${i} / ${total}단계`,
    stopSound: '■ 소리 멈추기', playThis: '▶ 이 주파수 들어보기',
    canHear: '들려요 → 더 높게', cannotHear: '안 들려요',
    limitLabel: '들리는 한계', belowOne: '1kHz 미만',
    currentStep: '현재 단계', currentFreq: '현재 주파수', limitStat: '들리는 한계', measuring: '측정 중',
    tipsTitle: '정확히 재려면',
    tips: [
      '· 이어폰을 쓰세요. 노트북 스피커는 15kHz 위를 거의 못 냅니다 — 귀가 아니라 스피커의 한계입니다.',
      '· 조용한 곳에서 하세요. 주변 소음이 있으면 높은 소리가 묻힙니다.',
      '· 볼륨은 낮게 두세요. 크게 들어도 한계는 안 올라가고 귀만 상합니다.',
      '· 이 결과는 재미로 보는 값이며 청력 검사가 아닙니다. 한쪽만 안 들린다면 이비인후과에 가세요.',
    ],
  },
  en: {
    ages: ['That is the late-teens to early-twenties range', 'That is the mid-twenties range', 'That is the thirties range', 'That is the forties range', 'That is the fifties range', 'If you only hear below 8kHz, try again somewhere quiet with headphones'],
    nowPlaying: 'Frequency now playing', stepOf: (i, total) => `${i} / ${total}`,
    stopSound: '■ Stop the sound', playThis: '▶ Play this frequency',
    canHear: 'I hear it → go higher', cannotHear: 'I cannot hear it',
    limitLabel: 'Your upper limit', belowOne: 'below 1kHz',
    currentStep: 'Step', currentFreq: 'Frequency', limitStat: 'Upper limit', measuring: 'measuring',
    tipsTitle: 'To measure this properly',
    tips: [
      '· Use headphones. Laptop speakers barely produce anything above 15kHz — that is the speaker’s limit, not your ears.',
      '· Do it somewhere quiet. Background noise buries the high tones.',
      '· Keep the volume low. Turning it up does not raise your limit, it just damages your hearing.',
      '· This is for curiosity, not a hearing test. If one ear cannot hear it, see an audiologist.',
    ],
  },
  es: {
    ages: ['Ese es el rango de finales de la adolescencia a primeros veinte', 'Ese es el rango de mediados de los veinte', 'Ese es el rango de los treinta', 'Ese es el rango de los cuarenta', 'Ese es el rango de los cincuenta', 'Si solo oyes por debajo de 8kHz, vuelve a probarlo en un sitio silencioso y con auriculares'],
    nowPlaying: 'Frecuencia que suena ahora', stepOf: (i, total) => `${i} / ${total}`,
    stopSound: '■ Parar el sonido', playThis: '▶ Escuchar esta frecuencia',
    canHear: 'La oigo → sube más', cannotHear: 'No la oigo',
    limitLabel: 'Tu límite superior', belowOne: 'por debajo de 1kHz',
    currentStep: 'Paso', currentFreq: 'Frecuencia', limitStat: 'Límite superior', measuring: 'midiendo',
    tipsTitle: 'Para medirlo bien',
    tips: [
      '· Usa auriculares. Los altavoces de portátil apenas producen nada por encima de 15kHz — ese es el límite del altavoz, no de tu oído.',
      '· Hazlo en un sitio silencioso. El ruido de fondo entierra los tonos agudos.',
      '· Mantén el volumen bajo. Subirlo no eleva tu límite, solo daña tu audición.',
      '· Esto es por curiosidad, no un examen auditivo. Si un oído no lo oye, acude a un audiólogo.',
    ],
  },
  'pt-br': {
    ages: ['Essa é a faixa do fim da adolescência ao começo dos vinte', 'Essa é a faixa de meados dos vinte', 'Essa é a faixa dos trinta', 'Essa é a faixa dos quarenta', 'Essa é a faixa dos cinquenta', 'Se você só ouve abaixo de 8kHz, tente de novo num lugar silencioso e com fones'],
    nowPlaying: 'Frequência tocando agora', stepOf: (i, total) => `${i} / ${total}`,
    stopSound: '■ Parar o som', playThis: '▶ Ouvir esta frequência',
    canHear: 'Estou ouvindo → suba mais', cannotHear: 'Não estou ouvindo',
    limitLabel: 'Seu limite superior', belowOne: 'abaixo de 1kHz',
    currentStep: 'Passo', currentFreq: 'Frequência', limitStat: 'Limite superior', measuring: 'medindo',
    tipsTitle: 'Para medir direito',
    tips: [
      '· Use fones. Alto-falantes de notebook quase não produzem nada acima de 15kHz — esse é o limite do alto-falante, não do seu ouvido.',
      '· Faça num lugar silencioso. O ruído de fundo enterra os tons agudos.',
      '· Mantenha o volume baixo. Aumentar não eleva seu limite, só prejudica a audição.',
      '· Isto é por curiosidade, não um exame auditivo. Se um ouvido não escuta, procure um audiologista.',
    ],
  },
  ja: {
    ages: ['10代後半〜20代前半くらいの範囲です', '20代半ばくらいの範囲です', '30代くらいの範囲です', '40代くらいの範囲です', '50代くらいの範囲です', '8kHz以下しか聞こえない場合は、静かな場所でイヤホンを使ってもう一度試してください'],
    nowPlaying: 'いま鳴っている周波数', stepOf: (i, total) => `${i} / ${total}段階`,
    stopSound: '■ 音を止める', playThis: '▶ この周波数を聴いてみる',
    canHear: '聞こえる → もっと高く', cannotHear: '聞こえない',
    limitLabel: '聞こえる上限', belowOne: '1kHz未満',
    currentStep: '現在の段階', currentFreq: '現在の周波数', limitStat: '聞こえる上限', measuring: '測定中',
    tipsTitle: '正しく測るには',
    tips: [
      '· イヤホンを使ってください。ノートパソコンのスピーカーは15kHzより上をほとんど出せません — 耳ではなくスピーカーの限界です。',
      '· 静かな場所でやってください。周囲の音があると高い音が埋もれます。',
      '· 音量は低くしてください。大きくしても上限は上がらず、耳を痛めるだけです。',
      '· これは興味で見る値で、聴力検査ではありません。片方だけ聞こえないときは耳鼻科へ行ってください。',
    ],
  },
  de: {
    ages: ['Das ist der Bereich von den späten Teenagerjahren bis Anfang zwanzig', 'Das ist der Bereich Mitte zwanzig', 'Das ist der Bereich der Dreißiger', 'Das ist der Bereich der Vierziger', 'Das ist der Bereich der Fünfziger', 'Wenn du nur unter 8kHz hörst, versuch es nochmal an einem stillen Ort mit Kopfhörern'],
    nowPlaying: 'Gerade gespielte Frequenz', stepOf: (i, total) => `${i} / ${total}`,
    stopSound: '■ Ton stoppen', playThis: '▶ Diese Frequenz hören',
    canHear: 'Ich höre sie → höher', cannotHear: 'Ich höre sie nicht',
    limitLabel: 'Deine obere Grenze', belowOne: 'unter 1kHz',
    currentStep: 'Stufe', currentFreq: 'Frequenz', limitStat: 'Obere Grenze', measuring: 'wird gemessen',
    tipsTitle: 'Damit das sauber gemessen wird',
    tips: [
      '· Nimm Kopfhörer. Laptop-Lautsprecher geben oberhalb von 15kHz kaum etwas her — das ist die Grenze des Lautsprechers, nicht deiner Ohren.',
      '· Mach es an einem stillen Ort. Hintergrundgeräusche verschütten die hohen Töne.',
      '· Halte die Lautstärke niedrig. Lauter zu machen hebt deine Grenze nicht, es schädigt nur das Gehör.',
      '· Das ist Neugier, kein Hörtest. Wenn ein Ohr nichts hört, geh zu einer HNO-Praxis.',
    ],
  },
  fr: {
    ages: ['C’est la plage de la fin de l’adolescence au début de la vingtaine', 'C’est la plage du milieu de la vingtaine', 'C’est la plage de la trentaine', 'C’est la plage de la quarantaine', 'C’est la plage de la cinquantaine', 'Si tu n’entends qu’en dessous de 8kHz, réessaie dans un endroit calme avec un casque'],
    nowPlaying: 'Fréquence en cours', stepOf: (i, total) => `${i} / ${total}`,
    stopSound: '■ Arrêter le son', playThis: '▶ Écouter cette fréquence',
    canHear: 'Je l’entends → plus haut', cannotHear: 'Je ne l’entends pas',
    limitLabel: 'Ta limite haute', belowOne: 'sous 1kHz',
    currentStep: 'Palier', currentFreq: 'Fréquence', limitStat: 'Limite haute', measuring: 'mesure en cours',
    tipsTitle: 'Pour mesurer correctement',
    tips: [
      '· Utilise un casque. Les haut-parleurs de portable ne produisent presque rien au-dessus de 15kHz — c’est la limite du haut-parleur, pas de tes oreilles.',
      '· Fais-le dans un endroit calme. Le bruit de fond enterre les aigus.',
      '· Garde le volume bas. Monter le son ne relève pas ta limite, cela abîme seulement ton audition.',
      '· C’est par curiosité, pas un examen auditif. Si une oreille n’entend rien, consulte un ORL.',
    ],
  },
  hi: {
    ages: ['यह किशोरावस्था के अंत से बीस की शुरुआत तक का दायरा है', 'यह बीस के मध्य का दायरा है', 'यह तीस के दशक का दायरा है', 'यह चालीस के दशक का दायरा है', 'यह पचास के दशक का दायरा है', 'अगर सिर्फ़ 8kHz से नीचे सुनाई देता है, तो शांत जगह पर हेडफ़ोन से फिर आज़माएँ'],
    nowPlaying: 'अभी बज रही आवृत्ति', stepOf: (i, total) => `${i} / ${total} चरण`,
    stopSound: '■ आवाज़ रोकें', playThis: '▶ यह आवृत्ति सुनें',
    canHear: 'सुनाई दे रही है → और ऊपर', cannotHear: 'सुनाई नहीं दे रही',
    limitLabel: 'आपकी ऊपरी सीमा', belowOne: '1kHz से नीचे',
    currentStep: 'अभी का चरण', currentFreq: 'अभी की आवृत्ति', limitStat: 'ऊपरी सीमा', measuring: 'मापा जा रहा है',
    tipsTitle: 'ठीक से मापने के लिए',
    tips: [
      '· हेडफ़ोन इस्तेमाल करें। लैपटॉप के स्पीकर 15kHz से ऊपर लगभग कुछ नहीं निकालते — यह स्पीकर की सीमा है, कान की नहीं।',
      '· शांत जगह पर करें। आस-पास का शोर ऊँची आवाज़ों को दबा देता है।',
      '· आवाज़ धीमी रखें। तेज़ करने से सीमा नहीं बढ़ती, सिर्फ़ कान को नुकसान होता है।',
      '· यह जिज्ञासा के लिए है, श्रवण परीक्षण नहीं। एक कान से सुनाई न दे तो कान के डॉक्टर के पास जाएँ।',
    ],
  },
  'zh-hans': {
    ages: ['这是十几岁末到二十出头的范围', '这是二十五岁上下的范围', '这是三十几岁的范围', '这是四十几岁的范围', '这是五十几岁的范围', '如果只听得到8kHz以下，换个安静的地方戴耳机再试'],
    nowPlaying: '正在播放的频率',
    stepOf: (i, total) => `${i} / ${total}`,
    stopSound: '■ 停止播放',
    playThis: '▶ 播放这个频率',
    canHear: '听得到 → 往上',
    cannotHear: '听不到',
    limitLabel: '你的上限',
    belowOne: '1kHz以下',
    currentStep: '档位',
    currentFreq: '频率',
    limitStat: '上限',
    measuring: '测量中',
    tipsTitle: '要量准的话',
    tips: ['· 用耳机。笔记本音箱几乎发不出15kHz以上 — 那是音箱的极限，不是你耳朵的。', '· 找个安静的地方。背景噪音会把高频盖掉。', '· 音量放小。开大声不会抬高你的上限，只会伤听力。', '· 这是图个好奇，不是听力检查。有一只耳朵听不到的话，去看听力科。'],
  },
  'zh-hant': {
    ages: ['這是十幾歲末到二十出頭的範圍', '這是二十五歲上下的範圍', '這是三十幾歲的範圍', '這是四十幾歲的範圍', '這是五十幾歲的範圍', '如果只聽得到8kHz以下，換個安靜的地方戴耳機再試'],
    nowPlaying: '正在播放的頻率',
    stepOf: (i, total) => `${i} / ${total}`,
    stopSound: '■ 停止播放',
    playThis: '▶ 播放這個頻率',
    canHear: '聽得到 → 往上',
    cannotHear: '聽不到',
    limitLabel: '你的上限',
    belowOne: '1kHz以下',
    currentStep: '檔位',
    currentFreq: '頻率',
    limitStat: '上限',
    measuring: '測量中',
    tipsTitle: '要量準的話',
    tips: ['· 用耳機。筆電喇叭幾乎發不出15kHz以上 — 那是喇叭的極限，不是你耳朵的。', '· 找個安靜的地方。背景噪音會把高頻蓋掉。', '· 音量放小。開大聲不會抬高你的上限，只會傷聽力。', '· 這是圖個好奇，不是聽力檢查。有一隻耳朵聽不到的話，去看聽力科。'],
  },
};

export const MATH_UI: Record<GameLang, {
  levels: string[]; opTitle: string; levelTitle: string;
  timeLeft: (s: string, solved: number) => string; answerPlaceholder: string; skip: string;
  solvedIn: (d: number) => string; startIn: (d: number) => string;
  solved: string; skipped: string; perQuestion: string; secSuffix: (s: string) => string;
  gradeFast: (n: number) => string; gradeGood: (n: number) => string; gradeSlow: (n: number) => string;
  skippedTitle: string;
}> = {
  ko: {
    levels: ['쉬움', '보통', '어려움'], opTitle: '연산 고르기', levelTitle: '난이도',
    timeLeft: (s, solved) => `${s}초 남음 · ${solved}문제`, answerPlaceholder: '답', skip: '모르겠어요 — 넘기기',
    solvedIn: d => `${d}초 동안 푼 문제`, startIn: d => `${d}초 시작`,
    solved: '푼 문제', skipped: '넘긴 문제', perQuestion: '문제당 평균', secSuffix: s => `${s}초`,
    gradeFast: n => `${n}문제 — 암산이 아주 빠릅니다`,
    gradeGood: n => `${n}문제 — 평균 이상입니다`,
    gradeSlow: n => `${n}문제 — 연산을 하나씩 줄여 연습해 보세요`,
    skippedTitle: '넘긴 문제',
  },
  en: {
    levels: ['Easy', 'Normal', 'Hard'], opTitle: 'Operations', levelTitle: 'Difficulty',
    timeLeft: (s, solved) => `${s}s left · ${solved} solved`, answerPlaceholder: 'Answer', skip: 'No idea — skip it',
    solvedIn: d => `solved in ${d} seconds`, startIn: d => `Start ${d} seconds`,
    solved: 'Solved', skipped: 'Skipped', perQuestion: 'Per question', secSuffix: s => `${s}s`,
    gradeFast: n => `${n} solved — very fast mental maths`,
    gradeGood: n => `${n} solved — above average`,
    gradeSlow: n => `${n} solved — try practising with one operation at a time`,
    skippedTitle: 'The ones you skipped',
  },
  es: {
    levels: ['Fácil', 'Normal', 'Difícil'], opTitle: 'Operaciones', levelTitle: 'Dificultad',
    timeLeft: (s, solved) => `quedan ${s}s · ${solved} resueltas`, answerPlaceholder: 'Respuesta', skip: 'No lo sé — pasar',
    solvedIn: d => `resueltas en ${d} segundos`, startIn: d => `Empezar ${d} segundos`,
    solved: 'Resueltas', skipped: 'Pasadas', perQuestion: 'Por operación', secSuffix: s => `${s}s`,
    gradeFast: n => `${n} resueltas — cálculo mental muy rápido`,
    gradeGood: n => `${n} resueltas — por encima de la media`,
    gradeSlow: n => `${n} resueltas — prueba a practicar con una operación a la vez`,
    skippedTitle: 'Las que pasaste',
  },
  'pt-br': {
    levels: ['Fácil', 'Normal', 'Difícil'], opTitle: 'Operações', levelTitle: 'Dificuldade',
    timeLeft: (s, solved) => `faltam ${s}s · ${solved} resolvidas`, answerPlaceholder: 'Resposta', skip: 'Não sei — pular',
    solvedIn: d => `resolvidas em ${d} segundos`, startIn: d => `Começar ${d} segundos`,
    solved: 'Resolvidas', skipped: 'Puladas', perQuestion: 'Por conta', secSuffix: s => `${s}s`,
    gradeFast: n => `${n} resolvidas — cálculo mental muito rápido`,
    gradeGood: n => `${n} resolvidas — acima da média`,
    gradeSlow: n => `${n} resolvidas — tente treinar com uma operação por vez`,
    skippedTitle: 'As que você pulou',
  },
  ja: {
    levels: ['やさしい', 'ふつう', 'むずかしい'], opTitle: '演算を選ぶ', levelTitle: '難易度',
    timeLeft: (s, solved) => `残り${s}秒 · ${solved}問`, answerPlaceholder: '答え', skip: 'わからない — 飛ばす',
    solvedIn: d => `${d}秒で解いた問題`, startIn: d => `${d}秒で開始`,
    solved: '解いた問題', skipped: '飛ばした問題', perQuestion: '1問あたり平均', secSuffix: s => `${s}秒`,
    gradeFast: n => `${n}問 — 暗算がとても速いです`,
    gradeGood: n => `${n}問 — 平均以上です`,
    gradeSlow: n => `${n}問 — 演算を一つずつに絞って練習してみてください`,
    skippedTitle: '飛ばした問題',
  },
  de: {
    levels: ['Leicht', 'Normal', 'Schwer'], opTitle: 'Rechenarten', levelTitle: 'Schwierigkeit',
    timeLeft: (s, solved) => `${s}s übrig · ${solved} gelöst`, answerPlaceholder: 'Antwort', skip: 'Keine Ahnung — überspringen',
    solvedIn: d => `in ${d} Sekunden gelöst`, startIn: d => `${d} Sekunden starten`,
    solved: 'Gelöst', skipped: 'Übersprungen', perQuestion: 'Pro Aufgabe', secSuffix: s => `${s}s`,
    gradeFast: n => `${n} gelöst — sehr schnelles Kopfrechnen`,
    gradeGood: n => `${n} gelöst — über dem Durchschnitt`,
    gradeSlow: n => `${n} gelöst — üb erst mit einer Rechenart auf einmal`,
    skippedTitle: 'Die übersprungenen Aufgaben',
  },
  fr: {
    levels: ['Facile', 'Normal', 'Difficile'], opTitle: 'Opérations', levelTitle: 'Difficulté',
    timeLeft: (s, solved) => `${s}s restantes · ${solved} résolues`, answerPlaceholder: 'Réponse', skip: 'Aucune idée — passer',
    solvedIn: d => `résolues en ${d} secondes`, startIn: d => `Démarrer ${d} secondes`,
    solved: 'Résolues', skipped: 'Passées', perQuestion: 'Par opération', secSuffix: s => `${s}s`,
    gradeFast: n => `${n} résolues — calcul mental très rapide`,
    gradeGood: n => `${n} résolues — au-dessus de la moyenne`,
    gradeSlow: n => `${n} résolues — essaie de t’entraîner sur une opération à la fois`,
    skippedTitle: 'Celles que tu as passées',
  },
  hi: {
    levels: ['आसान', 'सामान्य', 'कठिन'], opTitle: 'गणित चुनें', levelTitle: 'कठिनाई',
    timeLeft: (s, solved) => `${s} सेकंड बचे · ${solved} सवाल`, answerPlaceholder: 'जवाब', skip: 'नहीं पता — छोड़ें',
    solvedIn: d => `${d} सेकंड में हल किए सवाल`, startIn: d => `${d} सेकंड शुरू`,
    solved: 'हल किए', skipped: 'छोड़े', perQuestion: 'हर सवाल पर औसत', secSuffix: s => `${s} सेकंड`,
    gradeFast: n => `${n} सवाल — मानसिक गणित बहुत तेज़`,
    gradeGood: n => `${n} सवाल — औसत से ऊपर`,
    gradeSlow: n => `${n} सवाल — एक बार में एक ही संक्रिया लेकर अभ्यास कीजिए`,
    skippedTitle: 'छोड़े गए सवाल',
  },
  'zh-hans': {
    levels: ['简单', '普通', '困难'],
    opTitle: '运算',
    levelTitle: '难度',
    timeLeft: (s, solved) => `还剩${s}秒 · 做对${solved}道`,
    answerPlaceholder: '答案',
    skip: '不会 — 跳过',
    solvedIn: d => `${d}秒内做对`,
    startIn: d => `开始 ${d}秒`,
    solved: '做对',
    skipped: '跳过',
    perQuestion: '每题',
    secSuffix: s => `${s}秒`,
    gradeFast: n => `做对${n}道 — 心算非常快`,
    gradeGood: n => `做对${n}道 — 高于平均`,
    gradeSlow: n => `做对${n}道 — 试着一次只练一种运算`,
    skippedTitle: '你跳过的题',
  },
  'zh-hant': {
    levels: ['簡單', '普通', '困難'],
    opTitle: '運算',
    levelTitle: '難度',
    timeLeft: (s, solved) => `還剩${s}秒 · 做對${solved}道`,
    answerPlaceholder: '答案',
    skip: '不會 — 跳過',
    solvedIn: d => `${d}秒內做對`,
    startIn: d => `開始 ${d}秒`,
    solved: '做對',
    skipped: '跳過',
    perQuestion: '每題',
    secSuffix: s => `${s}秒`,
    gradeFast: n => `做對${n}道 — 心算非常快`,
    gradeGood: n => `做對${n}道 — 高於平均`,
    gradeSlow: n => `做對${n}道 — 試著一次只練一種運算`,
    skippedTitle: '你跳過的題',
  },
};
