// node에서 직접 로드할 수 있게 확장자를 명시한다 (allowImportingTsExtensions)
import type { AnyLocale10 } from './locales.ts';

/**
 * 이미지 도구 화면에 뜨는 문구의 여덟 언어 사전.
 *
 * 계산·canvas 처리는 한국어 구현을 그대로 쓴다 — 여기서 갈리는 건 문구뿐이다.
 * 도구가 프리셋 배열을 들고 있는 경우(규격, 비율 등) 배열에서 label을 떼어내고
 * 여기 이름 배열을 인덱스로 참조한다. 픽셀·비율은 언어와 무관하기 때문이다.
 *
 * 배열은 언어마다 길이와 순서가 같아야 한다 — 인덱스로 짝지으므로 하나를 빼면
 * 그 뒤가 전부 한 칸씩 밀린다.
 */
export type ImageLang = AnyLocale10;

/** 여덟 도구가 공통으로 쓰는 조각 — 입구, 결과 요약, 저장 버튼 */
export const IMAGE_COMMON: Record<ImageLang, {
  dropOne: string; dropMany: string; dropHow: string; notImage: string;
  original: string; result: string; saved: string; grew: string;
  otherPhoto: string; save: string; working: string;
  quality: string; smaller: string; sharper: string;
  bgFill: string; pickBg: string; bgColor: string;
}> = {
  ko: {
    dropOne: '사진을 올려주세요', dropMany: '사진 여러 장을 올려주세요',
    dropHow: '여기를 누르거나 끌어다 놓으세요',
    notImage: '이미지 파일이 아닙니다. JPG·PNG·WebP·GIF 등을 올려주세요.',
    original: '원본', result: '결과', saved: '절감', grew: '증가',
    otherPhoto: '다른 사진', save: '저장하기', working: '처리 중…',
    quality: '화질', smaller: '작게', sharper: '선명하게',
    bgFill: '투명 배경을 채울 색', pickBg: '배경색 직접 고르기', bgColor: '배경색',
  },
  en: {
    dropOne: 'Drop a photo here', dropMany: 'Drop several photos here',
    dropHow: 'Click here or drag a file in',
    notImage: 'That is not an image file. Try a JPG, PNG, WebP or GIF.',
    original: 'Original', result: 'Result', saved: 'saved', grew: 'larger',
    otherPhoto: 'New photo', save: 'Save', working: 'Working…',
    quality: 'Quality', smaller: 'Smaller', sharper: 'Sharper',
    bgFill: 'Colour to fill transparency', pickBg: 'Pick a background colour', bgColor: 'Background',
  },
  es: {
    dropOne: 'Suelta una foto aquí', dropMany: 'Suelta varias fotos aquí',
    dropHow: 'Pulsa aquí o arrastra un archivo',
    notImage: 'Eso no es un archivo de imagen. Prueba con JPG, PNG, WebP o GIF.',
    original: 'Original', result: 'Resultado', saved: 'ahorrado', grew: 'más grande',
    otherPhoto: 'Otra foto', save: 'Guardar', working: 'Procesando…',
    quality: 'Calidad', smaller: 'Más ligera', sharper: 'Más nítida',
    bgFill: 'Color para rellenar la transparencia', pickBg: 'Elegir color de fondo', bgColor: 'Fondo',
  },
  'pt-br': {
    dropOne: 'Solte uma foto aqui', dropMany: 'Solte várias fotos aqui',
    dropHow: 'Clique aqui ou arraste um arquivo',
    notImage: 'Esse não é um arquivo de imagem. Tente JPG, PNG, WebP ou GIF.',
    original: 'Original', result: 'Resultado', saved: 'de economia', grew: 'maior',
    otherPhoto: 'Outra foto', save: 'Salvar', working: 'Processando…',
    quality: 'Qualidade', smaller: 'Mais leve', sharper: 'Mais nítida',
    bgFill: 'Cor para preencher a transparência', pickBg: 'Escolher cor de fundo', bgColor: 'Fundo',
  },
  ja: {
    dropOne: '写真をここに置いてください', dropMany: '写真を何枚かここに置いてください',
    dropHow: 'ここを押すか、ファイルをドラッグしてください',
    notImage: '画像ファイルではありません。JPG・PNG・WebP・GIFなどを選んでください。',
    original: '元の写真', result: '結果', saved: '削減', grew: '増加',
    otherPhoto: '別の写真', save: '保存', working: '処理中…',
    quality: '画質', smaller: '軽く', sharper: '鮮明に',
    bgFill: '透明部分を埋める色', pickBg: '背景色を選ぶ', bgColor: '背景色',
  },
  de: {
    dropOne: 'Foto hier ablegen', dropMany: 'Mehrere Fotos hier ablegen',
    dropHow: 'Hier klicken oder eine Datei hereinziehen',
    notImage: 'Das ist keine Bilddatei. Versuche JPG, PNG, WebP oder GIF.',
    original: 'Original', result: 'Ergebnis', saved: 'gespart', grew: 'größer',
    otherPhoto: 'Neues Foto', save: 'Speichern', working: 'Wird verarbeitet…',
    quality: 'Qualität', smaller: 'Kleiner', sharper: 'Schärfer',
    bgFill: 'Farbe für die Transparenzfüllung', pickBg: 'Hintergrundfarbe wählen', bgColor: 'Hintergrund',
  },
  fr: {
    dropOne: 'Dépose une photo ici', dropMany: 'Dépose plusieurs photos ici',
    dropHow: 'Clique ici ou fais glisser un fichier',
    notImage: 'Ce n’est pas un fichier image. Essaie un JPG, PNG, WebP ou GIF.',
    original: 'Original', result: 'Résultat', saved: 'gagné', grew: 'plus lourd',
    otherPhoto: 'Autre photo', save: 'Enregistrer', working: 'Traitement…',
    quality: 'Qualité', smaller: 'Plus léger', sharper: 'Plus net',
    bgFill: 'Couleur qui remplit la transparence', pickBg: 'Choisir une couleur de fond', bgColor: 'Fond',
  },
  hi: {
    dropOne: 'फ़ोटो यहाँ डालें', dropMany: 'कई फ़ोटो यहाँ डालें',
    dropHow: 'यहाँ दबाएँ या फ़ाइल खींचकर छोड़ें',
    notImage: 'यह इमेज फ़ाइल नहीं है। JPG, PNG, WebP या GIF आज़माएँ।',
    original: 'मूल', result: 'नतीजा', saved: 'की बचत', grew: 'बढ़ा',
    otherPhoto: 'दूसरी फ़ोटो', save: 'सेव करें', working: 'हो रहा है…',
    quality: 'क्वालिटी', smaller: 'हल्का', sharper: 'साफ़',
    bgFill: 'पारदर्शिता भरने वाला रंग', pickBg: 'बैकग्राउंड रंग चुनें', bgColor: 'बैकग्राउंड',
  },
  'zh-hans': {
    dropOne: '把照片拖到这里',
    dropMany: '把几张照片拖到这里',
    dropHow: '点这里，或者把文件拖进来',
    notImage: '这不是图片文件。试试JPG、PNG、WebP或GIF。',
    original: '原图',
    result: '结果',
    saved: '省下',
    grew: '变大',
    otherPhoto: '换一张',
    save: '保存',
    working: '处理中…',
    quality: '画质',
    smaller: '更小',
    sharper: '更清晰',
    bgFill: '填补透明的颜色',
    pickBg: '挑一个背景色',
    bgColor: '背景',
  },
  'zh-hant': {
    dropOne: '把照片拖到這裡',
    dropMany: '把幾張照片拖到這裡',
    dropHow: '點這裡，或者把檔案拖進來',
    notImage: '這不是圖片檔。試試JPG、PNG、WebP或GIF。',
    original: '原圖',
    result: '結果',
    saved: '省下',
    grew: '變大',
    otherPhoto: '換一張',
    save: '儲存',
    working: '處理中…',
    quality: '畫質',
    smaller: '更小',
    sharper: '更清晰',
    bgFill: '填補透明的顏色',
    pickBg: '挑一個背景色',
    bgColor: '背景',
  },
};

/** 붙여넣기 안내 — kbd 태그가 끼어 있어 앞뒤를 나눈다 */
export const PASTE_HINT: Record<ImageLang, { before: string; after: string }> = {
  ko: { before: ' · ', after: '로 붙여넣기도 됩니다' },
  en: { before: ' · or paste with ', after: '' },
  es: { before: ' · o pega con ', after: '' },
  'pt-br': { before: ' · ou cole com ', after: '' },
  ja: { before: ' · ', after: ' で貼り付けもできます' },
  de: { before: ' · oder einfügen mit ', after: '' },
  fr: { before: ' · ou colle avec ', after: '' },
  hi: { before: ' · या ', after: ' से पेस्ट करें' },
  'zh-hans': {
    before: ' · 或者按 ',
    after: '',
  },
  'zh-hant': {
    before: ' · 或者按 ',
    after: '',
  },
};

export const COMPRESS_UI: Record<ImageLang, {
  hint: string; formats: string[]; formatHints: string[]; saveAs: string;
  altOriginal: string; altResult: string; viewingOriginal: string; tapForOriginal: string;
  note: string; noteLink: string;
}> = {
  ko: {
    hint: 'JPG·PNG·WebP 모두 됩니다',
    formats: ['JPG', 'WebP'], formatHints: ['사진에 가장 무난', '같은 화질에 더 작음'],
    saveAs: '저장 형식',
    altOriginal: '원본 사진', altResult: '압축 결과 미리보기',
    viewingOriginal: '원본 보는 중', tapForOriginal: '누르면 원본',
    note: '크기(픽셀)는 그대로 두고 화질만 낮춥니다. 더 줄이려면 ',
    noteLink: '이미지 크기 조절',
  },
  en: {
    hint: 'JPG, PNG and WebP all work',
    formats: ['JPG', 'WebP'], formatHints: ['Safest for photos', 'Smaller at the same quality'],
    saveAs: 'Save as',
    altOriginal: 'The original photo', altResult: 'Preview of the compressed result',
    viewingOriginal: 'Showing original', tapForOriginal: 'Tap for original',
    note: 'The pixel dimensions stay the same — only quality comes down. To go smaller, also use ',
    noteLink: 'Image Resizer',
  },
  es: {
    hint: 'Sirve con JPG, PNG y WebP',
    formats: ['JPG', 'WebP'], formatHints: ['Lo más seguro para fotos', 'Más ligero a igual calidad'],
    saveAs: 'Guardar como',
    altOriginal: 'La foto original', altResult: 'Vista previa del resultado comprimido',
    viewingOriginal: 'Viendo el original', tapForOriginal: 'Pulsa para el original',
    note: 'Las medidas en píxeles no cambian — solo baja la calidad. Para reducir más, usa también ',
    noteLink: 'Redimensionar imagen',
  },
  'pt-br': {
    hint: 'Funciona com JPG, PNG e WebP',
    formats: ['JPG', 'WebP'], formatHints: ['O mais seguro para fotos', 'Mais leve na mesma qualidade'],
    saveAs: 'Salvar como',
    altOriginal: 'A foto original', altResult: 'Prévia do resultado comprimido',
    viewingOriginal: 'Vendo o original', tapForOriginal: 'Toque para o original',
    note: 'As medidas em pixels não mudam — só a qualidade cai. Para reduzir mais, use também ',
    noteLink: 'Redimensionar imagem',
  },
  ja: {
    hint: 'JPG・PNG・WebPどれでも大丈夫です',
    formats: ['JPG', 'WebP'], formatHints: ['写真にいちばん無難', '同じ画質でより軽い'],
    saveAs: '保存形式',
    altOriginal: '元の写真', altResult: '圧縮結果のプレビュー',
    viewingOriginal: '元の写真を表示中', tapForOriginal: '押すと元の写真',
    note: 'ピクセル数はそのままで画質だけを下げます。もっと小さくするなら',
    noteLink: '画像サイズ変更',
  },
  de: {
    hint: 'JPG, PNG und WebP funktionieren alle',
    formats: ['JPG', 'WebP'], formatHints: ['Am sichersten für Fotos', 'Kleiner bei gleicher Qualität'],
    saveAs: 'Speichern als',
    altOriginal: 'Das Originalfoto', altResult: 'Vorschau des komprimierten Ergebnisses',
    viewingOriginal: 'Original wird gezeigt', tapForOriginal: 'Antippen für das Original',
    note: 'Die Pixelmaße bleiben gleich — nur die Qualität sinkt. Für noch kleinere Dateien nimm zusätzlich ',
    noteLink: 'Bildgröße ändern',
  },
  fr: {
    hint: 'JPG, PNG et WebP fonctionnent tous',
    formats: ['JPG', 'WebP'], formatHints: ['Le plus sûr pour les photos', 'Plus léger à qualité égale'],
    saveAs: 'Enregistrer en',
    altOriginal: 'La photo d’origine', altResult: 'Aperçu du résultat compressé',
    viewingOriginal: 'Original affiché', tapForOriginal: 'Touche pour l’original',
    note: 'Les dimensions en pixels ne changent pas — seule la qualité baisse. Pour aller plus loin, utilise aussi ',
    noteLink: 'Redimensionner une image',
  },
  hi: {
    hint: 'JPG, PNG और WebP सब चलते हैं',
    formats: ['JPG', 'WebP'], formatHints: ['फ़ोटो के लिए सबसे सुरक्षित', 'उसी क्वालिटी में हल्का'],
    saveAs: 'इस रूप में सेव करें',
    altOriginal: 'मूल फ़ोटो', altResult: 'कंप्रेस किए नतीजे की झलक',
    viewingOriginal: 'मूल फ़ोटो दिख रही है', tapForOriginal: 'दबाएँ तो मूल',
    note: 'पिक्सेल नाप वही रहते हैं — सिर्फ़ क्वालिटी घटती है। और छोटा करना हो तो साथ में ',
    noteLink: 'इमेज का आकार बदलें',
  },
  'zh-hans': {
    hint: 'JPG、PNG、WebP都能用',
    formats: ['JPG', 'WebP'],
    formatHints: ['照片用它最稳', '同样画质下更小'],
    saveAs: '保存为',
    altOriginal: '原来的照片',
    altResult: '压缩结果的预览',
    viewingOriginal: '正在看原图',
    tapForOriginal: '点一下看原图',
    note: '像素尺寸不变 — 只有画质降下来。还想更小的话，再用一次',
    noteLink: '图片尺寸调整',
  },
  'zh-hant': {
    hint: 'JPG、PNG、WebP都能用',
    formats: ['JPG', 'WebP'],
    formatHints: ['照片用它最穩', '同樣畫質下更小'],
    saveAs: '儲存為',
    altOriginal: '原來的照片',
    altResult: '壓縮結果的預覽',
    viewingOriginal: '正在看原圖',
    tapForOriginal: '點一下看原圖',
    note: '像素尺寸不變 — 只有畫質降下來。還想更小的話，再用一次',
    noteLink: '圖片尺寸調整',
  },
};

export const RESIZE_UI: Record<ImageLang, {
  hint: string; alt: string; width: string; height: string;
  lockOn: string; lockOff: string; byRatio: string; originalLabel: string;
  presetsTitle: string; presets: string[]; note: string;
}> = {
  ko: {
    hint: '가로·세로를 원하는 픽셀로 맞춥니다', alt: '크기 조절 결과 미리보기',
    width: '가로 (px)', height: '세로 (px)',
    lockOn: '비율 고정을 풉니다', lockOff: '비율을 고정합니다',
    byRatio: '비율로 줄이기', originalLabel: '원본',
    presetsTitle: '자주 쓰는 규격',
    presets: ['인스타 정사각', '유튜브 썸네일', '프로필 512'],
    note: '원본보다 크게 늘리면 화질이 좋아지지는 않고 흐릿해집니다.',
  },
  en: {
    hint: 'Set the width and height in pixels', alt: 'Preview of the resized result',
    width: 'Width (px)', height: 'Height (px)',
    lockOn: 'Unlock the aspect ratio', lockOff: 'Lock the aspect ratio',
    byRatio: 'Scale by percentage', originalLabel: 'Original',
    presetsTitle: 'Common sizes',
    presets: ['Instagram square', 'YouTube thumbnail', 'Profile 512'],
    note: 'Enlarging past the original does not add detail — it just gets blurry.',
  },
  es: {
    hint: 'Fija el ancho y el alto en píxeles', alt: 'Vista previa del resultado redimensionado',
    width: 'Ancho (px)', height: 'Alto (px)',
    lockOn: 'Desbloquear la proporción', lockOff: 'Bloquear la proporción',
    byRatio: 'Reducir por porcentaje', originalLabel: 'Original',
    presetsTitle: 'Tamaños más usados',
    presets: ['Cuadrado de Instagram', 'Miniatura de YouTube', 'Perfil 512'],
    note: 'Agrandar más allá del original no añade detalle — solo sale borroso.',
  },
  'pt-br': {
    hint: 'Defina largura e altura em pixels', alt: 'Prévia do resultado redimensionado',
    width: 'Largura (px)', height: 'Altura (px)',
    lockOn: 'Destravar a proporção', lockOff: 'Travar a proporção',
    byRatio: 'Reduzir por porcentagem', originalLabel: 'Original',
    presetsTitle: 'Tamanhos mais usados',
    presets: ['Quadrado do Instagram', 'Thumbnail do YouTube', 'Perfil 512'],
    note: 'Ampliar além do original não cria detalhe — só fica embaçado.',
  },
  ja: {
    hint: '縦横を好きなピクセル数に合わせます', alt: 'サイズ変更結果のプレビュー',
    width: '幅 (px)', height: '高さ (px)',
    lockOn: '縦横比の固定を外す', lockOff: '縦横比を固定する',
    byRatio: 'パーセントで縮小', originalLabel: '元のサイズ',
    presetsTitle: 'よく使う規格',
    presets: ['Instagram 正方形', 'YouTube サムネイル', 'プロフィール 512'],
    note: '元より大きくしても画質は上がりません。ぼやけるだけです。',
  },
  de: {
    hint: 'Breite und Höhe in Pixeln festlegen', alt: 'Vorschau des skalierten Ergebnisses',
    width: 'Breite (px)', height: 'Höhe (px)',
    lockOn: 'Seitenverhältnis entsperren', lockOff: 'Seitenverhältnis sperren',
    byRatio: 'Prozentual skalieren', originalLabel: 'Original',
    presetsTitle: 'Gängige Maße',
    presets: ['Instagram quadratisch', 'YouTube-Thumbnail', 'Profil 512'],
    note: 'Über das Original hinaus zu vergrößern bringt keine Details — es wird nur unscharf.',
  },
  fr: {
    hint: 'Règle la largeur et la hauteur en pixels', alt: 'Aperçu du résultat redimensionné',
    width: 'Largeur (px)', height: 'Hauteur (px)',
    lockOn: 'Déverrouiller les proportions', lockOff: 'Verrouiller les proportions',
    byRatio: 'Réduire en pourcentage', originalLabel: 'Original',
    presetsTitle: 'Formats courants',
    presets: ['Carré Instagram', 'Vignette YouTube', 'Profil 512'],
    note: 'Agrandir au-delà de l’original n’ajoute pas de détail — ça devient juste flou.',
  },
  hi: {
    hint: 'चौड़ाई और ऊँचाई पिक्सेल में तय करें', alt: 'आकार बदले नतीजे की झलक',
    width: 'चौड़ाई (px)', height: 'ऊँचाई (px)',
    lockOn: 'अनुपात का लॉक हटाएँ', lockOff: 'अनुपात लॉक करें',
    byRatio: 'प्रतिशत में घटाएँ', originalLabel: 'मूल',
    presetsTitle: 'आम नाप',
    presets: ['इंस्टाग्राम वर्ग', 'यूट्यूब थंबनेल', 'प्रोफ़ाइल 512'],
    note: 'मूल से बड़ा करने पर बारीकी नहीं बढ़ती — बस धुँधला हो जाता है।',
  },
  'zh-hans': {
    hint: '按像素填宽和高',
    alt: '调整尺寸后的预览',
    width: '宽（px）',
    height: '高（px）',
    lockOn: '解开长宽比',
    lockOff: '锁住长宽比',
    byRatio: '按百分比缩放',
    originalLabel: '原图',
    presetsTitle: '常用尺寸',
    presets: ['Instagram 方形', 'YouTube 缩略图', '头像 512'],
    note: '放得比原图还大不会多出细节 — 只会变糊。',
  },
  'zh-hant': {
    hint: '按像素填寬和高',
    alt: '調整尺寸後的預覽',
    width: '寬（px）',
    height: '高（px）',
    lockOn: '解開長寬比',
    lockOff: '鎖住長寬比',
    byRatio: '按百分比縮放',
    originalLabel: '原圖',
    presetsTitle: '常用尺寸',
    presets: ['Instagram 方形', 'YouTube 縮圖', '大頭貼 512'],
    note: '放得比原圖還大不會多出細節 — 只會變糊。',
  },
};

export const CONVERT_UI: Record<ImageLang, {
  hint: string; alt: string; targetFormat: string; note: string;
}> = {
  ko: {
    hint: 'GIF·BMP·HEIC 등도 읽어서 변환합니다', alt: '변환 결과 미리보기',
    targetFormat: '바꿀 형식',
    note: 'JPG·WebP(품질 지정)에는 투명이 없어 원래 투명했던 부분이 이 색으로 채워집니다.',
  },
  en: {
    hint: 'GIF, BMP and HEIC can be read and converted too', alt: 'Preview of the converted result',
    targetFormat: 'Convert to',
    note: 'JPG and quality-set WebP have no transparency, so anything that was transparent gets filled with this colour.',
  },
  es: {
    hint: 'También lee y convierte GIF, BMP y HEIC', alt: 'Vista previa del resultado convertido',
    targetFormat: 'Convertir a',
    note: 'JPG y WebP con calidad fijada no tienen transparencia, así que lo que era transparente se rellena con este color.',
  },
  'pt-br': {
    hint: 'Também lê e converte GIF, BMP e HEIC', alt: 'Prévia do resultado convertido',
    targetFormat: 'Converter para',
    note: 'JPG e WebP com qualidade definida não têm transparência, então o que era transparente é preenchido com esta cor.',
  },
  ja: {
    hint: 'GIF・BMP・HEICなども読み込んで変換します', alt: '変換結果のプレビュー',
    targetFormat: '変換先の形式',
    note: 'JPGと画質を指定したWebPには透明がないので、元が透明だった部分はこの色で埋まります。',
  },
  de: {
    hint: 'GIF, BMP und HEIC können auch gelesen und umgewandelt werden', alt: 'Vorschau des umgewandelten Ergebnisses',
    targetFormat: 'Umwandeln in',
    note: 'JPG und WebP mit festgelegter Qualität haben keine Transparenz — was transparent war, wird mit dieser Farbe gefüllt.',
  },
  fr: {
    hint: 'GIF, BMP et HEIC peuvent aussi être lus et convertis', alt: 'Aperçu du résultat converti',
    targetFormat: 'Convertir en',
    note: 'JPG et WebP à qualité fixée n’ont pas de transparence : ce qui était transparent est rempli avec cette couleur.',
  },
  hi: {
    hint: 'GIF, BMP और HEIC भी पढ़कर बदले जाते हैं', alt: 'बदले नतीजे की झलक',
    targetFormat: 'इसमें बदलें',
    note: 'JPG और क्वालिटी तय किए WebP में पारदर्शिता नहीं होती, इसलिए जो पारदर्शी था वह इस रंग से भर जाता है।',
  },
  'zh-hans': {
    hint: 'GIF、BMP、HEIC也读得进来并转换',
    alt: '转换结果的预览',
    targetFormat: '转成',
    note: 'JPG和设了画质的WebP没有透明通道，原本透明的地方会被填上这个颜色。',
  },
  'zh-hant': {
    hint: 'GIF、BMP、HEIC也讀得進來並轉換',
    alt: '轉換結果的預覽',
    targetFormat: '轉成',
    note: 'JPG和設了畫質的WebP沒有透明通道，原本透明的地方會被填上這個顏色。',
  },
};

export const CROP_UI: Record<ImageLang, {
  hint: string; alt: string; ratioTitle: string; ratios: string[];
  how: string; keeps: (ow: number, oh: number, w: number, h: number) => string;
}> = {
  ko: {
    hint: '필요한 부분만 남깁니다', alt: '자를 사진',
    ratioTitle: '비율 고정', ratios: ['자유', '1:1', '4:3', '3:4', '16:9', '9:16'],
    how: '사진 위에서 끌어 영역을 새로 그리거나, 네 모서리를 잡아 크기를 바꾸세요. 가운데를 끌면 위치가 움직입니다.',
    keeps: (ow, oh, w, h) => `원본 ${ow} × ${oh}px에서 ${w} × ${h}px만 남깁니다.`,
  },
  en: {
    hint: 'Keep only the part you need', alt: 'The photo to crop',
    ratioTitle: 'Lock ratio', ratios: ['Free', '1:1', '4:3', '3:4', '16:9', '9:16'],
    how: 'Drag on the photo to draw a new area, or grab a corner to resize. Drag the middle to move it.',
    keeps: (ow, oh, w, h) => `Keeping ${w} × ${h}px out of the original ${ow} × ${oh}px.`,
  },
  es: {
    hint: 'Deja solo la parte que necesitas', alt: 'La foto que vas a recortar',
    ratioTitle: 'Bloquear proporción', ratios: ['Libre', '1:1', '4:3', '3:4', '16:9', '9:16'],
    how: 'Arrastra sobre la foto para dibujar un área nueva, o agarra una esquina para cambiar el tamaño. Arrastra el centro para moverla.',
    keeps: (ow, oh, w, h) => `Se quedan ${w} × ${h}px de los ${ow} × ${oh}px originales.`,
  },
  'pt-br': {
    hint: 'Fica só com a parte que você precisa', alt: 'A foto que você vai recortar',
    ratioTitle: 'Travar proporção', ratios: ['Livre', '1:1', '4:3', '3:4', '16:9', '9:16'],
    how: 'Arraste sobre a foto para desenhar uma área nova, ou pegue um canto para mudar o tamanho. Arraste o meio para mover.',
    keeps: (ow, oh, w, h) => `Ficam ${w} × ${h}px dos ${ow} × ${oh}px originais.`,
  },
  ja: {
    hint: '必要な部分だけを残します', alt: '切り抜く写真',
    ratioTitle: '比率を固定', ratios: ['自由', '1:1', '4:3', '3:4', '16:9', '9:16'],
    how: '写真の上をドラッグして範囲を描き直すか、四隅をつかんで大きさを変えてください。中央をドラッグすると位置が動きます。',
    keeps: (ow, oh, w, h) => `元の ${ow} × ${oh}px から ${w} × ${h}px を残します。`,
  },
  de: {
    hint: 'Nur den Teil behalten, den du brauchst', alt: 'Das Foto zum Zuschneiden',
    ratioTitle: 'Verhältnis sperren', ratios: ['Frei', '1:1', '4:3', '3:4', '16:9', '9:16'],
    how: 'Zieh über das Foto, um einen neuen Bereich zu ziehen, oder greif eine Ecke, um die Größe zu ändern. Zieh die Mitte, um ihn zu verschieben.',
    keeps: (ow, oh, w, h) => `Behält ${w} × ${h}px von den ursprünglichen ${ow} × ${oh}px.`,
  },
  fr: {
    hint: 'Ne garde que la partie utile', alt: 'La photo à recadrer',
    ratioTitle: 'Verrouiller le ratio', ratios: ['Libre', '1:1', '4:3', '3:4', '16:9', '9:16'],
    how: 'Fais glisser sur la photo pour tracer une nouvelle zone, ou attrape un coin pour la redimensionner. Fais glisser le centre pour la déplacer.',
    keeps: (ow, oh, w, h) => `On garde ${w} × ${h}px sur les ${ow} × ${oh}px d’origine.`,
  },
  hi: {
    hint: 'सिर्फ़ ज़रूरी हिस्सा रखें', alt: 'काटी जाने वाली फ़ोटो',
    ratioTitle: 'अनुपात लॉक', ratios: ['खुला', '1:1', '4:3', '3:4', '16:9', '9:16'],
    how: 'फ़ोटो पर खींचकर नया क्षेत्र बनाएँ, या किसी कोने को पकड़कर आकार बदलें। बीच से खींचें तो जगह बदलती है।',
    keeps: (ow, oh, w, h) => `मूल ${ow} × ${oh}px में से ${w} × ${h}px रखे जाएँगे।`,
  },
  'zh-hans': {
    hint: '只留下需要的那一块',
    alt: '要裁的照片',
    ratioTitle: '锁定比例',
    ratios: ['自由', '1:1', '4:3', '3:4', '16:9', '9:16'],
    how: '在照片上拖出新的范围，或者拉角来改大小。拖中间可以移动。',
    keeps: (ow, oh, w, h) => `从原来的 ${ow} × ${oh}px 里留下 ${w} × ${h}px。`,
  },
  'zh-hant': {
    hint: '只留下需要的那一塊',
    alt: '要裁的照片',
    ratioTitle: '鎖定比例',
    ratios: ['自由', '1:1', '4:3', '3:4', '16:9', '9:16'],
    how: '在照片上拖出新的範圍，或者拉角來改大小。拖中間可以移動。',
    keeps: (ow, oh, w, h) => `從原來的 ${ow} × ${oh}px 裡留下 ${w} × ${h}px。`,
  },
};

export const ROTATE_UI: Record<ImageLang, {
  hint: string; alt: string; left: string; right: string; flipH: string; flipV: string;
  fineAngle: string; angleAria: string; toZero: string;
  cornerColor: string; cornerNote: string; dimension: (a: number) => string;
}> = {
  ko: {
    hint: '옆으로 누워 저장된 사진을 바로 세울 때', alt: '회전 결과 미리보기',
    left: '↺ 왼쪽', right: '↻ 오른쪽', flipH: '↔ 좌우', flipV: '↕ 상하',
    fineAngle: '각도 미세 조정', angleAria: '회전 각도', toZero: '0°로',
    cornerColor: '빈 구석을 채울 색',
    cornerNote: '90의 배수가 아닌 각도에서는 모서리에 빈 곳이 생깁니다',
    dimension: a => `${a}° 회전`,
  },
  en: {
    hint: 'For a photo that saved sideways', alt: 'Preview of the rotated result',
    left: '↺ Left', right: '↻ Right', flipH: '↔ Flip', flipV: '↕ Flip',
    fineAngle: 'Fine angle', angleAria: 'Rotation angle', toZero: 'To 0°',
    cornerColor: 'Colour to fill the corners',
    cornerNote: 'Any angle that is not a multiple of 90° leaves gaps at the corners',
    dimension: a => `Rotated ${a}°`,
  },
  es: {
    hint: 'Para una foto que se guardó tumbada', alt: 'Vista previa del resultado girado',
    left: '↺ Izquierda', right: '↻ Derecha', flipH: '↔ Voltear', flipV: '↕ Voltear',
    fineAngle: 'Ángulo fino', angleAria: 'Ángulo de giro', toZero: 'A 0°',
    cornerColor: 'Color para rellenar las esquinas',
    cornerNote: 'Cualquier ángulo que no sea múltiplo de 90° deja huecos en las esquinas',
    dimension: a => `Girada ${a}°`,
  },
  'pt-br': {
    hint: 'Para uma foto que salvou deitada', alt: 'Prévia do resultado girado',
    left: '↺ Esquerda', right: '↻ Direita', flipH: '↔ Espelhar', flipV: '↕ Espelhar',
    fineAngle: 'Ângulo fino', angleAria: 'Ângulo de giro', toZero: 'Para 0°',
    cornerColor: 'Cor para preencher os cantos',
    cornerNote: 'Qualquer ângulo que não seja múltiplo de 90° deixa falhas nos cantos',
    dimension: a => `Girada ${a}°`,
  },
  ja: {
    hint: '横向きに保存された写真を起こすときに', alt: '回転結果のプレビュー',
    left: '↺ 左', right: '↻ 右', flipH: '↔ 左右', flipV: '↕ 上下',
    fineAngle: '角度の微調整', angleAria: '回転角度', toZero: '0°に',
    cornerColor: '空いた角を埋める色',
    cornerNote: '90の倍数でない角度では、角に余白ができます',
    dimension: a => `${a}° 回転`,
  },
  de: {
    hint: 'Für ein Foto, das quer gespeichert wurde', alt: 'Vorschau des gedrehten Ergebnisses',
    left: '↺ Links', right: '↻ Rechts', flipH: '↔ Spiegeln', flipV: '↕ Spiegeln',
    fineAngle: 'Feiner Winkel', angleAria: 'Drehwinkel', toZero: 'Auf 0°',
    cornerColor: 'Farbe für die Ecken',
    cornerNote: 'Jeder Winkel, der kein Vielfaches von 90° ist, lässt Lücken an den Ecken',
    dimension: a => `Um ${a}° gedreht`,
  },
  fr: {
    hint: 'Pour une photo enregistrée de travers', alt: 'Aperçu du résultat pivoté',
    left: '↺ Gauche', right: '↻ Droite', flipH: '↔ Retourner', flipV: '↕ Retourner',
    fineAngle: 'Angle fin', angleAria: 'Angle de rotation', toZero: 'À 0°',
    cornerColor: 'Couleur qui remplit les coins',
    cornerNote: 'Tout angle qui n’est pas un multiple de 90° laisse des vides dans les coins',
    dimension: a => `Pivotée de ${a}°`,
  },
  hi: {
    hint: 'तिरछी सेव हो गई फ़ोटो सीधी करने के लिए', alt: 'घुमाए नतीजे की झलक',
    left: '↺ बाएँ', right: '↻ दाएँ', flipH: '↔ बाएँ-दाएँ', flipV: '↕ ऊपर-नीचे',
    fineAngle: 'कोण की बारीक सेटिंग', angleAria: 'घुमाव का कोण', toZero: '0° पर',
    cornerColor: 'कोनों को भरने वाला रंग',
    cornerNote: '90 के गुणक न होने वाले कोण पर कोनों में खाली जगह बचती है',
    dimension: a => `${a}° घुमाया`,
  },
  'zh-hans': {
    hint: '给存下来变成横躺的照片用',
    alt: '旋转结果的预览',
    left: '↺ 左转',
    right: '↻ 右转',
    flipH: '↔ 翻转',
    flipV: '↕ 翻转',
    fineAngle: '微调角度',
    angleAria: '旋转角度',
    toZero: '回到0°',
    cornerColor: '填补边角的颜色',
    cornerNote: '不是90°倍数的角度，边角会留出空隙',
    dimension: a => `旋转了${a}°`,
  },
  'zh-hant': {
    hint: '給存下來變成橫躺的照片用',
    alt: '旋轉結果的預覽',
    left: '↺ 左轉',
    right: '↻ 右轉',
    flipH: '↔ 翻轉',
    flipV: '↕ 翻轉',
    fineAngle: '微調角度',
    angleAria: '旋轉角度',
    toZero: '回到0°',
    cornerColor: '填補邊角的顏色',
    cornerNote: '不是90°倍數的角度，邊角會留出空隙',
    dimension: a => `旋轉了${a}°`,
  },
};

export const MOSAIC_UI: Record<ImageLang, {
  hint: string; how: string; modes: string[]; modeHints: string[];
  brush: string; cellSize: string; cellNote: string;
  undo: string; clear: string; dimension: (n: number) => string;
}> = {
  ko: {
    hint: '주소·계좌·얼굴이 담긴 캡처도 브라우저 밖으로 나가지 않습니다',
    how: '가리고 싶은 곳을 손가락이나 마우스로 문지르세요',
    modes: ['🔳 모자이크', '⬛ 검게 덮기'], modeHints: ['흐릿하게 뭉갬', '완전히 가림'],
    brush: '붓 굵기', cellSize: '모자이크 칸 크기',
    cellNote: '칸이 클수록 알아보기 어렵습니다. 글자를 가릴 때는 크게 잡으세요.',
    undo: '↩ 방금 지운 것 되돌리기', clear: '전부 지우기',
    dimension: n => `${n}번 칠함`,
  },
  en: {
    hint: 'Screenshots with addresses, account numbers or faces never leave the browser',
    how: 'Brush over anything you want hidden, with a finger or the mouse',
    modes: ['🔳 Pixelate', '⬛ Solid black'], modeHints: ['Blurs it out', 'Hides it completely'],
    brush: 'Brush size', cellSize: 'Pixel block size',
    cellNote: 'Bigger blocks are harder to read back. Go large when covering text.',
    undo: '↩ Undo the last stroke', clear: 'Clear all',
    dimension: n => `${n} strokes`,
  },
  es: {
    hint: 'Las capturas con direcciones, números de cuenta o caras no salen del navegador',
    how: 'Pinta con el dedo o el ratón sobre lo que quieras tapar',
    modes: ['🔳 Pixelar', '⬛ Negro sólido'], modeHints: ['Lo deja borroso', 'Lo tapa del todo'],
    brush: 'Grosor del pincel', cellSize: 'Tamaño del bloque',
    cellNote: 'Los bloques grandes son más difíciles de descifrar. Súbelo cuando tapes texto.',
    undo: '↩ Deshacer el último trazo', clear: 'Borrar todo',
    dimension: n => `${n} trazos`,
  },
  'pt-br': {
    hint: 'Prints com endereços, números de conta ou rostos não saem do navegador',
    how: 'Passe o dedo ou o mouse sobre o que quiser esconder',
    modes: ['🔳 Pixelar', '⬛ Preto sólido'], modeHints: ['Deixa embaçado', 'Esconde por completo'],
    brush: 'Espessura do pincel', cellSize: 'Tamanho do bloco',
    cellNote: 'Blocos maiores são mais difíceis de decifrar. Aumente ao cobrir texto.',
    undo: '↩ Desfazer o último traço', clear: 'Apagar tudo',
    dimension: n => `${n} traços`,
  },
  ja: {
    hint: '住所・口座番号・顔が写ったスクリーンショットもブラウザの外に出ません',
    how: '隠したいところを指やマウスでなぞってください',
    modes: ['🔳 モザイク', '⬛ 黒で塗る'], modeHints: ['ぼかして潰す', '完全に隠す'],
    brush: 'ブラシの太さ', cellSize: 'モザイクの粗さ',
    cellNote: '粗いほど読み取りにくくなります。文字を隠すときは大きめに。',
    undo: '↩ 直前の一筆を取り消す', clear: 'すべて消す',
    dimension: n => `${n}回なぞった`,
  },
  de: {
    hint: 'Screenshots mit Adressen, Kontonummern oder Gesichtern verlassen den Browser nicht',
    how: 'Pinsle mit Finger oder Maus über alles, was verdeckt sein soll',
    modes: ['🔳 Verpixeln', '⬛ Schwarz abdecken'], modeHints: ['Macht es unscharf', 'Verdeckt es vollständig'],
    brush: 'Pinselgröße', cellSize: 'Blockgröße',
    cellNote: 'Größere Blöcke sind schwerer zurückzulesen. Bei Text ruhig groß wählen.',
    undo: '↩ Letzten Strich zurücknehmen', clear: 'Alles löschen',
    dimension: n => `${n} Striche`,
  },
  fr: {
    hint: 'Les captures avec adresses, numéros de compte ou visages ne quittent pas le navigateur',
    how: 'Passe le doigt ou la souris sur ce que tu veux masquer',
    modes: ['🔳 Pixeliser', '⬛ Noir opaque'], modeHints: ['Rend flou', 'Masque complètement'],
    brush: 'Taille du pinceau', cellSize: 'Taille des blocs',
    cellNote: 'De gros blocs sont plus difficiles à relire. Vois large pour masquer du texte.',
    undo: '↩ Annuler le dernier trait', clear: 'Tout effacer',
    dimension: n => `${n} traits`,
  },
  hi: {
    hint: 'पते, खाता नंबर या चेहरे वाले स्क्रीनशॉट भी ब्राउज़र से बाहर नहीं जाते',
    how: 'जो छिपाना है उस पर उँगली या माउस से ब्रश चलाइए',
    modes: ['🔳 पिक्सेल', '⬛ काले से ढकें'], modeHints: ['धुँधला कर देता है', 'पूरी तरह छिपा देता है'],
    brush: 'ब्रश की मोटाई', cellSize: 'खाने का आकार',
    cellNote: 'खाने बड़े हों तो पढ़ना मुश्किल होता है। लिखावट ढकते समय बड़ा रखें।',
    undo: '↩ आख़िरी स्ट्रोक वापस लें', clear: 'सब मिटाएँ',
    dimension: n => `${n} स्ट्रोक`,
  },
  'zh-hans': {
    hint: '带地址、账号或人脸的截图，一步都不会离开浏览器',
    how: '用手指或鼠标在要挡的地方涂一下',
    modes: ['🔳 马赛克', '⬛ 纯黑遮住'],
    modeHints: ['把它糊掉', '完全挡住'],
    brush: '笔刷大小',
    cellSize: '马赛克方块大小',
    cellNote: '方块越大越读不回来。遮文字的时候调大一点。',
    undo: '↩ 撤销上一笔',
    clear: '全部清除',
    dimension: n => `${n}笔`,
  },
  'zh-hant': {
    hint: '帶地址、帳號或人臉的截圖，一步都不會離開瀏覽器',
    how: '用手指或滑鼠在要擋的地方塗一下',
    modes: ['🔳 馬賽克', '⬛ 純黑遮住'],
    modeHints: ['把它糊掉', '完全擋住'],
    brush: '筆刷大小',
    cellSize: '馬賽克方塊大小',
    cellNote: '方塊越大越讀不回來。遮文字的時候調大一點。',
    undo: '↩ 復原上一筆',
    clear: '全部清除',
    dimension: n => `${n}筆`,
  },
};

export const MERGE_UI: Record<ImageLang, {
  hint: string; hintMore: string; alt: string; countLine: (n: number) => string;
  up: string; down: string; remove: string;
  dirs: string[]; matchLabel: (which: string) => string; widthWord: string; heightWord: string;
  matchOff: string; gap: string; gapColor: string; gapColorAria: string; pickGapColor: string;
}> = {
  ko: {
    hint: '여러 장을 한 번에 고를 수 있습니다', hintMore: '이미 올린 사진 뒤에 이어서 붙습니다',
    alt: '이어붙인 결과 미리보기', countLine: n => `붙인 사진 ${n}장 — 순서를 바꿀 수 있어요`,
    up: '위로', down: '아래로', remove: '빼기',
    dirs: ['⬇ 세로로 잇기', '➡ 가로로 잇기'],
    matchLabel: w => `크기가 다른 사진 ${w} 맞추기`, widthWord: '폭', heightWord: '높이',
    matchOff: '끄면 원래 크기 그대로 가운데 정렬합니다',
    gap: '사진 사이 간격', gapColor: '여백 색', gapColorAria: '여백색', pickGapColor: '여백색 직접 고르기',
  },
  en: {
    hint: 'You can select several at once', hintMore: 'These get added after the photos already loaded',
    alt: 'Preview of the combined result', countLine: n => `${n} photos joined — you can reorder them`,
    up: 'Move up', down: 'Move down', remove: 'Remove',
    dirs: ['⬇ Stack vertically', '➡ Join side by side'],
    matchLabel: w => `Match the ${w} of differently sized photos`, widthWord: 'width', heightWord: 'height',
    matchOff: 'Turn this off to keep original sizes, centred',
    gap: 'Gap between photos', gapColor: 'Gap colour', gapColorAria: 'Gap colour', pickGapColor: 'Pick a gap colour',
  },
  es: {
    hint: 'Puedes elegir varias a la vez', hintMore: 'Se añaden detrás de las fotos que ya cargaste',
    alt: 'Vista previa del resultado unido', countLine: n => `${n} fotos unidas — puedes cambiar el orden`,
    up: 'Subir', down: 'Bajar', remove: 'Quitar',
    dirs: ['⬇ Apilar en vertical', '➡ Unir en horizontal'],
    matchLabel: w => `Igualar el ${w} de fotos de distinto tamaño`, widthWord: 'ancho', heightWord: 'alto',
    matchOff: 'Desactívalo para mantener los tamaños originales, centrados',
    gap: 'Espacio entre fotos', gapColor: 'Color del espacio', gapColorAria: 'Color del espacio', pickGapColor: 'Elegir color del espacio',
  },
  'pt-br': {
    hint: 'Você pode escolher várias de uma vez', hintMore: 'Elas entram depois das fotos já carregadas',
    alt: 'Prévia do resultado unido', countLine: n => `${n} fotos unidas — você pode mudar a ordem`,
    up: 'Subir', down: 'Descer', remove: 'Remover',
    dirs: ['⬇ Empilhar na vertical', '➡ Unir lado a lado'],
    matchLabel: w => `Igualar a ${w} de fotos de tamanhos diferentes`, widthWord: 'largura', heightWord: 'altura',
    matchOff: 'Desligue para manter os tamanhos originais, centralizados',
    gap: 'Espaço entre as fotos', gapColor: 'Cor do espaço', gapColorAria: 'Cor do espaço', pickGapColor: 'Escolher cor do espaço',
  },
  ja: {
    hint: '何枚でも一度に選べます', hintMore: 'すでに読み込んだ写真のうしろに追加されます',
    alt: '結合結果のプレビュー', countLine: n => `${n}枚を結合 — 順番を入れ替えられます`,
    up: '上へ', down: '下へ', remove: '外す',
    dirs: ['⬇ 縦に積む', '➡ 横に並べる'],
    matchLabel: w => `大きさの違う写真の${w}を揃える`, widthWord: '幅', heightWord: '高さ',
    matchOff: 'オフにすると元の大きさのまま中央に揃えます',
    gap: '写真の間隔', gapColor: '余白の色', gapColorAria: '余白の色', pickGapColor: '余白の色を選ぶ',
  },
  de: {
    hint: 'Du kannst mehrere auf einmal auswählen', hintMore: 'Diese kommen hinter die schon geladenen Fotos',
    alt: 'Vorschau des zusammengefügten Ergebnisses', countLine: n => `${n} Fotos verbunden — du kannst sie umsortieren`,
    up: 'Nach oben', down: 'Nach unten', remove: 'Entfernen',
    dirs: ['⬇ Senkrecht stapeln', '➡ Nebeneinander setzen'],
    matchLabel: w => `${w} unterschiedlich großer Fotos angleichen`, widthWord: 'Breite', heightWord: 'Höhe',
    matchOff: 'Ausschalten, um die Originalgrößen zentriert zu behalten',
    gap: 'Abstand zwischen den Fotos', gapColor: 'Farbe des Abstands', gapColorAria: 'Farbe des Abstands', pickGapColor: 'Farbe des Abstands wählen',
  },
  fr: {
    hint: 'Tu peux en choisir plusieurs à la fois', hintMore: 'Elles s’ajoutent après les photos déjà chargées',
    alt: 'Aperçu du résultat assemblé', countLine: n => `${n} photos assemblées — tu peux changer l’ordre`,
    up: 'Monter', down: 'Descendre', remove: 'Retirer',
    dirs: ['⬇ Empiler à la verticale', '➡ Mettre côte à côte'],
    matchLabel: w => `Aligner la ${w} des photos de tailles différentes`, widthWord: 'largeur', heightWord: 'hauteur',
    matchOff: 'Désactive pour garder les tailles d’origine, centrées',
    gap: 'Écart entre les photos', gapColor: 'Couleur de l’écart', gapColorAria: 'Couleur de l’écart', pickGapColor: 'Choisir la couleur de l’écart',
  },
  hi: {
    hint: 'एक बार में कई चुन सकते हैं', hintMore: 'ये पहले डाली गई फ़ोटो के पीछे जुड़ेंगी',
    alt: 'जोड़े नतीजे की झलक', countLine: n => `${n} फ़ोटो जुड़ीं — क्रम बदल सकते हैं`,
    up: 'ऊपर', down: 'नीचे', remove: 'हटाएँ',
    dirs: ['⬇ खड़े जोड़ें', '➡ आड़े जोड़ें'],
    matchLabel: w => `अलग-अलग नाप की फ़ोटो की ${w} बराबर करें`, widthWord: 'चौड़ाई', heightWord: 'ऊँचाई',
    matchOff: 'बंद करें तो मूल नाप में बीच में सजाया जाता है',
    gap: 'फ़ोटो के बीच अंतर', gapColor: 'खाली जगह का रंग', gapColorAria: 'खाली जगह का रंग', pickGapColor: 'खाली जगह का रंग चुनें',
  },
  'zh-hans': {
    hint: '可以一次选好几张',
    hintMore: '这些会接在已经加载的照片后面',
    alt: '拼接结果的预览',
    countLine: n => `拼了${n}张 — 顺序可以调`,
    up: '往上移',
    down: '往下移',
    remove: '移除',
    dirs: ['⬇ 竖着拼', '➡ 横着拼'],
    matchLabel: w => `把大小不同的照片按${w}对齐`,
    widthWord: '宽',
    heightWord: '高',
    matchOff: '关掉的话就保持原尺寸、居中摆放',
    gap: '照片之间的间距',
    gapColor: '间距颜色',
    gapColorAria: '间距颜色',
    pickGapColor: '挑一个间距颜色',
  },
  'zh-hant': {
    hint: '可以一次選好幾張',
    hintMore: '這些會接在已經載入的照片後面',
    alt: '拼接結果的預覽',
    countLine: n => `拼了${n}張 — 順序可以調`,
    up: '往上移',
    down: '往下移',
    remove: '移除',
    dirs: ['⬇ 豎著拼', '➡ 橫著拼'],
    matchLabel: w => `把大小不同的照片按${w}對齊`,
    widthWord: '寬',
    heightWord: '高',
    matchOff: '關掉的話就保持原尺寸、置中擺放',
    gap: '照片之間的間距',
    gapColor: '間距顏色',
    gapColorAria: '間距顏色',
    pickGapColor: '挑一個間距顏色',
  },
};

export const IMG_PALETTE_UI: Record<ImageLang, {
  hint: string; alt: string; how: string;
  copy: string; copied: string; copyHex: (hex: string) => string;
  pickedPoint: string; noteBefore: string; noteAfter: string;
  otherPhoto: string; savePalette: string;
}> = {
  ko: {
    hint: '사진·일러스트·스크린샷 아무거나',
    alt: '색을 추출할 사진 — 누르면 그 지점의 색을 읽습니다',
    how: '사진 위를 누르면 그 지점의 색을 정확히 집어냅니다',
    copy: '복사', copied: '복사됨', copyHex: hex => `${hex} 복사`,
    pickedPoint: ' · 찍은 지점',
    noteBefore: '가장 많이 쓰인 색은 ', noteAfter: '입니다 — 배경이나 포인트 색으로 그대로 쓰면 사진과 잘 어울립니다.',
    otherPhoto: '다른 사진', savePalette: '⬇ 팔레트 이미지로 저장',
  },
  en: {
    hint: 'A photo, an illustration, a screenshot — anything',
    alt: 'The photo to pull colours from — tap to read the colour at that point',
    how: 'Tap anywhere on the photo to pick up the exact colour there',
    copy: 'Copy', copied: 'Copied', copyHex: hex => `Copy ${hex}`,
    pickedPoint: ' · picked point',
    noteBefore: 'The most used colour is ', noteAfter: ' — use it as a background or accent and it will sit well with the photo.',
    otherPhoto: 'New photo', savePalette: '⬇ Save palette as an image',
  },
  es: {
    hint: 'Una foto, una ilustración, una captura — lo que sea',
    alt: 'La foto de la que sacar colores — toca para leer el color de ese punto',
    how: 'Toca cualquier punto de la foto para coger el color exacto de ahí',
    copy: 'Copiar', copied: 'Copiado', copyHex: hex => `Copiar ${hex}`,
    pickedPoint: ' · punto elegido',
    noteBefore: 'El color más usado es ', noteAfter: ' — úsalo de fondo o de acento y quedará bien con la foto.',
    otherPhoto: 'Otra foto', savePalette: '⬇ Guardar la paleta como imagen',
  },
  'pt-br': {
    hint: 'Uma foto, uma ilustração, um print — qualquer coisa',
    alt: 'A foto de onde tirar cores — toque para ler a cor daquele ponto',
    how: 'Toque em qualquer ponto da foto para pegar a cor exata dali',
    copy: 'Copiar', copied: 'Copiado', copyHex: hex => `Copiar ${hex}`,
    pickedPoint: ' · ponto escolhido',
    noteBefore: 'A cor mais usada é ', noteAfter: ' — use como fundo ou destaque e vai combinar com a foto.',
    otherPhoto: 'Outra foto', savePalette: '⬇ Salvar a paleta como imagem',
  },
  ja: {
    hint: '写真・イラスト・スクリーンショット、何でも',
    alt: '色を抽出する写真 — 押すとその地点の色を読みます',
    how: '写真の上を押すと、その一点の色を正確に拾えます',
    copy: 'コピー', copied: 'コピーしました', copyHex: hex => `${hex} をコピー`,
    pickedPoint: ' · 選んだ地点',
    noteBefore: 'いちばん多く使われている色は ', noteAfter: ' です — 背景やアクセントにそのまま使うと写真と馴染みます。',
    otherPhoto: '別の写真', savePalette: '⬇ パレットを画像として保存',
  },
  de: {
    hint: 'Ein Foto, eine Illustration, ein Screenshot — was du willst',
    alt: 'Das Foto, aus dem Farben geholt werden — antippen, um die Farbe dort zu lesen',
    how: 'Tippe irgendwo auf das Foto, um genau die Farbe dort aufzunehmen',
    copy: 'Kopieren', copied: 'Kopiert', copyHex: hex => `${hex} kopieren`,
    pickedPoint: ' · gewählter Punkt',
    noteBefore: 'Die häufigste Farbe ist ', noteAfter: ' — als Hintergrund oder Akzent passt sie gut zum Foto.',
    otherPhoto: 'Neues Foto', savePalette: '⬇ Palette als Bild speichern',
  },
  fr: {
    hint: 'Une photo, une illustration, une capture — ce que tu veux',
    alt: 'La photo dont extraire les couleurs — touche pour lire la couleur à cet endroit',
    how: 'Touche n’importe quel point de la photo pour prélever la couleur exacte',
    copy: 'Copier', copied: 'Copié', copyHex: hex => `Copier ${hex}`,
    pickedPoint: ' · point choisi',
    noteBefore: 'La couleur la plus présente est ', noteAfter: ' — en fond ou en accent, elle s’accordera avec la photo.',
    otherPhoto: 'Autre photo', savePalette: '⬇ Enregistrer la palette en image',
  },
  hi: {
    hint: 'फ़ोटो, चित्र, स्क्रीनशॉट — कुछ भी',
    alt: 'जिससे रंग निकालने हैं वह फ़ोटो — दबाएँ तो उस बिंदु का रंग पढ़ा जाता है',
    how: 'फ़ोटो पर कहीं भी दबाएँ और उस बिंदु का ठीक रंग मिल जाएगा',
    copy: 'कॉपी', copied: 'कॉपी हो गया', copyHex: hex => `${hex} कॉपी करें`,
    pickedPoint: ' · चुना बिंदु',
    noteBefore: 'सबसे ज़्यादा इस्तेमाल हुआ रंग ', noteAfter: ' है — बैकग्राउंड या हाइलाइट में यही रखें तो फ़ोटो से मेल खाएगा।',
    otherPhoto: 'दूसरी फ़ोटो', savePalette: '⬇ पैलेट को इमेज में सेव करें',
  },
  'zh-hans': {
    hint: '照片、插画、截图 — 什么都行',
    alt: '要取色的照片 — 点一下读出那一点的颜色',
    how: '在照片上点哪儿，就取到那一点的准确颜色',
    copy: '复制',
    copied: '已复制',
    copyHex: hex => `复制 ${hex}`,
    pickedPoint: ' · 取色点',
    noteBefore: '用得最多的颜色是 ',
    noteAfter: ' — 拿它当背景或点缀色，会和照片很搭。',
    otherPhoto: '换一张',
    savePalette: '⬇ 把色板存成图片',
  },
  'zh-hant': {
    hint: '照片、插畫、截圖 — 什麼都行',
    alt: '要取色的照片 — 點一下讀出那一點的顏色',
    how: '在照片上點哪兒，就取到那一點的準確顏色',
    copy: '複製',
    copied: '已複製',
    copyHex: hex => `複製 ${hex}`,
    pickedPoint: ' · 取色點',
    noteBefore: '用得最多的顏色是 ',
    noteAfter: ' — 拿它當背景或點綴色，會和照片很搭。',
    otherPhoto: '換一張',
    savePalette: '⬇ 把色票存成圖片',
  },
};
