/**
 * 지뢰찾기 화면의 열 언어 문구.
 *
 * lib/game-ui-intl.ts와 lib/game-more-ui.ts가 이미 커서 따로 둔다 — 셈을
 * lib/minesweeper.ts로 가른 것과 같은 이유다.
 *
 * ── 값이 전부 문자열인 이유 ──────────────────────────────────
 * 숫자를 끼우는 자리는 함수로 두는 것이 보통이지만, 이 화면에서 숫자가 들어가는
 * 곳은 시간(0:00)과 남은 지뢰 수뿐이고 둘 다 어느 언어에서도 그대로 읽힌다.
 * 문자열만 두면 검사가 열쇠를 훑어 "비었다·이모지가 섞였다·남의 언어 글자가
 * 섞였다"를 한 번에 볼 수 있다.
 *
 * 이 화면에는 **이모지를 쓰지 않는다.** 깃발과 지뢰는 인라인 SVG로 그린다.
 */
import type { GameLang } from './game-ui-intl.ts';

/** 검사가 훑는 열쇠 목록 — 여기 없는 열쇠는 언어별 빠짐을 아무도 못 본다 */
export const MINESWEEPER_UI_KEYS = [
  'level_beginner', 'level_intermediate', 'level_expert',
  'minesLeft', 'time', 'bestTime', 'clicks',
  'dig', 'flag', 'modeHint',
  'won', 'lost', 'newGame', 'restart',
  'how', 'note', 'wide',
  'cell', 'flagged', 'unknown',
] as const;

export type MinesweeperUiKey = (typeof MINESWEEPER_UI_KEYS)[number];
export type MinesweeperUi = Record<MinesweeperUiKey, string>;

export const MINESWEEPER_UI: Record<GameLang, MinesweeperUi> = {
  ko: {
    level_beginner: '초급 9×9',
    level_intermediate: '중급 16×16',
    level_expert: '고급 30×16',
    minesLeft: '남은 지뢰',
    time: '경과 시간',
    bestTime: '최고 기록',
    clicks: '3BV 최소 클릭',
    dig: '열기',
    flag: '깃발',
    modeHint: '오른쪽 클릭이나 길게 누르기로 깃발을 꽂습니다. 위의 깃발 단추를 켜 두면 그냥 눌러서 꽂을 수 있습니다.',
    won: '지뢰를 모두 피했습니다',
    lost: '지뢰를 밟았습니다',
    newGame: '새 판',
    restart: '다시 하기',
    how: '숫자는 맞닿은 여덟 칸에 든 지뢰 수입니다. 첫 칸은 언제나 안전하고 주변에 지뢰가 없어 넓게 열립니다.',
    note: '3BV는 이 판을 푸는 데 필요한 최소 클릭 수입니다. 같은 30초라도 3BV 150짜리 판과 80짜리 판은 전혀 다른 일이어서, 초만 재면 쉬운 판을 뽑은 사람이 이깁니다.',
    wide: '판이 화면보다 넓으면 좌우로 밀어 보세요',
    cell: '칸',
    flagged: '깃발 꽂힘',
    unknown: '물음표',
  },
  en: {
    level_beginner: 'Beginner 9×9',
    level_intermediate: 'Intermediate 16×16',
    level_expert: 'Expert 30×16',
    minesLeft: 'Mines left',
    time: 'Time',
    bestTime: 'Best time',
    clicks: '3BV min clicks',
    dig: 'Dig',
    flag: 'Flag',
    modeHint: 'Right-click or press and hold to plant a flag. Turn on the flag button above and a plain tap plants one.',
    won: 'You cleared every mine',
    lost: 'You hit a mine',
    newGame: 'New board',
    restart: 'Try again',
    how: 'A number is how many mines touch that square. Your first square is always safe and always has no mines around it, so it opens wide.',
    note: '3BV is the smallest number of clicks that solves the board. The same 30 seconds on a 3BV 150 board and a 3BV 80 board are different jobs, so timing alone rewards whoever drew the easier board.',
    wide: 'Swipe sideways if the board is wider than your screen',
    cell: 'Square',
    flagged: 'Flagged',
    unknown: 'Unsure',
  },
  es: {
    level_beginner: 'Principiante 9×9',
    level_intermediate: 'Intermedio 16×16',
    level_expert: 'Experto 30×16',
    minesLeft: 'Minas restantes',
    time: 'Tiempo',
    bestTime: 'Mejor tiempo',
    clicks: '3BV clics mínimos',
    dig: 'Abrir',
    flag: 'Bandera',
    modeHint: 'Haz clic derecho o mantén pulsado para poner una bandera. Si activas el botón de bandera de arriba, basta con un toque.',
    won: 'Has despejado todas las minas',
    lost: 'Has pisado una mina',
    newGame: 'Tablero nuevo',
    restart: 'Volver a intentarlo',
    how: 'El número dice cuántas minas tocan esa casilla. La primera casilla siempre es segura y nunca tiene minas alrededor, así que se abre en grande.',
    note: '3BV es el mínimo de clics con que se resuelve el tablero. Los mismos 30 segundos en un tablero de 3BV 150 y en uno de 3BV 80 no son lo mismo, así que cronometrar a secas premia a quien le tocó el tablero fácil.',
    wide: 'Desliza a los lados si el tablero es más ancho que tu pantalla',
    cell: 'Casilla',
    flagged: 'Con bandera',
    unknown: 'En duda',
  },
  'pt-br': {
    level_beginner: 'Iniciante 9×9',
    level_intermediate: 'Intermediário 16×16',
    level_expert: 'Especialista 30×16',
    minesLeft: 'Minas restantes',
    time: 'Tempo',
    bestTime: 'Melhor tempo',
    clicks: '3BV cliques mínimos',
    dig: 'Abrir',
    flag: 'Bandeira',
    modeHint: 'Clique com o botão direito ou pressione e segure para colocar uma bandeira. Ligando o botão de bandeira acima, um toque simples já coloca.',
    won: 'Você desviou de todas as minas',
    lost: 'Você pisou numa mina',
    newGame: 'Novo tabuleiro',
    restart: 'Tentar de novo',
    how: 'O número diz quantas minas encostam naquela casa. A primeira casa é sempre segura e nunca tem minas em volta, por isso abre uma área grande.',
    note: '3BV é o menor número de cliques que resolve o tabuleiro. Os mesmos 30 segundos num tabuleiro de 3BV 150 e num de 3BV 80 são tarefas diferentes, então cronometrar só isso premia quem tirou o tabuleiro fácil.',
    wide: 'Arraste para os lados se o tabuleiro for mais largo que a tela',
    cell: 'Casa',
    flagged: 'Com bandeira',
    unknown: 'Em dúvida',
  },
  ja: {
    level_beginner: '初級 9×9',
    level_intermediate: '中級 16×16',
    level_expert: '上級 30×16',
    minesLeft: '残りの地雷',
    time: '経過時間',
    bestTime: '最高記録',
    clicks: '3BV 最小クリック',
    dig: '開く',
    flag: '旗',
    modeHint: '右クリックか長押しで旗を立てます。上の旗ボタンを入れておけば、そのまま押すだけで立てられます。',
    won: '地雷を全部よけました',
    lost: '地雷を踏みました',
    newGame: '新しい盤',
    restart: 'もう一度',
    how: '数字はそのマスに接する八マスの地雷の数です。最初のマスは必ず安全で、周りにも地雷がないので広く開きます。',
    note: '3BVはその盤を解くのに要る最小のクリック数です。同じ30秒でも3BV150の盤と80の盤はまるで別の仕事なので、秒だけを競うと易しい盤を引いた人が勝ちます。',
    wide: '盤が画面より広いときは左右にずらしてください',
    cell: 'マス',
    flagged: '旗あり',
    unknown: 'はてな',
  },
  de: {
    level_beginner: 'Anfänger 9×9',
    level_intermediate: 'Fortgeschritten 16×16',
    level_expert: 'Profi 30×16',
    minesLeft: 'Minen übrig',
    time: 'Zeit',
    bestTime: 'Bestzeit',
    clicks: '3BV Mindestklicks',
    dig: 'Öffnen',
    flag: 'Fahne',
    modeHint: 'Rechtsklick oder langes Drücken setzt eine Fahne. Schaltest du oben den Fahnen-Knopf ein, genügt ein normales Antippen.',
    won: 'Du hast alle Minen umgangen',
    lost: 'Du bist auf eine Mine getreten',
    newGame: 'Neues Feld',
    restart: 'Nochmal versuchen',
    how: 'Die Zahl sagt, wie viele Minen an dieses Feld grenzen. Das erste Feld ist immer sicher und hat nie Minen ringsum, also öffnet es großflächig.',
    note: '3BV ist die kleinste Anzahl Klicks, mit der das Feld gelöst ist. Dieselben 30 Sekunden auf einem 3BV-150-Feld und auf einem 3BV-80-Feld sind zwei verschiedene Aufgaben — reine Zeitmessung belohnt also, wer das leichtere Feld gezogen hat.',
    wide: 'Wisch zur Seite, wenn das Feld breiter als dein Bildschirm ist',
    cell: 'Feld',
    flagged: 'Markiert',
    unknown: 'Unsicher',
  },
  fr: {
    level_beginner: 'Débutant 9×9',
    level_intermediate: 'Intermédiaire 16×16',
    level_expert: 'Expert 30×16',
    minesLeft: 'Mines restantes',
    time: 'Temps',
    bestTime: 'Meilleur temps',
    clicks: '3BV clics mini',
    dig: 'Creuser',
    flag: 'Drapeau',
    modeHint: 'Clic droit ou appui long pour poser un drapeau. Active le bouton drapeau au-dessus et un simple appui suffit.',
    won: 'Tu as évité toutes les mines',
    lost: 'Tu as marché sur une mine',
    newGame: 'Nouvelle grille',
    restart: 'Réessayer',
    how: 'Le chiffre dit combien de mines touchent cette case. La première case est toujours sûre et n’a jamais de mine autour, donc elle ouvre large.',
    note: 'Le 3BV est le nombre minimal de clics qui résout la grille. Les mêmes 30 secondes sur une grille à 3BV 150 et sur une à 3BV 80 sont deux travaux différents : chronométrer seul récompense donc celui qui a tiré la grille facile.',
    wide: 'Fais glisser sur le côté si la grille est plus large que ton écran',
    cell: 'Case',
    flagged: 'Marquée',
    unknown: 'Incertaine',
  },
  hi: {
    level_beginner: 'शुरुआती 9×9',
    level_intermediate: 'मध्यम 16×16',
    level_expert: 'विशेषज्ञ 30×16',
    minesLeft: 'बची माइन',
    time: 'समय',
    bestTime: 'सबसे अच्छा समय',
    clicks: '3BV न्यूनतम क्लिक',
    dig: 'खोलें',
    flag: 'झंडा',
    modeHint: 'झंडा लगाने के लिए दायाँ क्लिक करें या दबाकर रखें। ऊपर का झंडा बटन चालू कर दें तो सादा टैप ही काफ़ी है।',
    won: 'आपने सारी माइन बचा लीं',
    lost: 'आप माइन पर पड़ गए',
    newGame: 'नया बोर्ड',
    restart: 'फिर कोशिश करें',
    how: 'अंक बताता है कि उस खाने से कितनी माइन सटी हैं। पहला खाना हमेशा सुरक्षित रहता है और उसके चारों ओर कोई माइन नहीं होती, इसलिए बड़ा हिस्सा खुल जाता है।',
    note: '3BV वह सबसे कम क्लिक है जिससे बोर्ड हल हो जाता है। 3BV 150 वाले बोर्ड के 30 सेकंड और 3BV 80 वाले बोर्ड के 30 सेकंड एक जैसे काम नहीं हैं, इसलिए सिर्फ़ समय गिनने से आसान बोर्ड पाने वाला जीत जाता है।',
    wide: 'बोर्ड स्क्रीन से चौड़ा हो तो दाएँ-बाएँ खिसकाएँ',
    cell: 'खाना',
    flagged: 'झंडा लगा',
    unknown: 'संदेह',
  },
  'zh-hans': {
    level_beginner: '初级 9×9',
    level_intermediate: '中级 16×16',
    level_expert: '高级 30×16',
    minesLeft: '剩余地雷',
    time: '用时',
    bestTime: '最好成绩',
    clicks: '3BV 最少点击',
    dig: '挖开',
    flag: '旗子',
    modeHint: '右键或长按可以插旗。把上面的旗子按钮打开，轻轻一点就能插旗。',
    won: '全部地雷都躲过了',
    lost: '踩到地雷了',
    newGame: '新一局',
    restart: '再来一次',
    how: '数字是紧挨着这一格的八格里有几颗地雷。第一格一定安全，周围也没有地雷，所以会开出一大片。',
    note: '3BV 是解开这一局最少要点几下。同样是 30 秒，3BV 150 的局和 80 的局根本不是一回事，只比秒数的话，抽到简单局的人就赢了。',
    wide: '棋盘比屏幕宽的时候，左右拖动来看',
    cell: '格',
    flagged: '已插旗',
    unknown: '不确定',
  },
  'zh-hant': {
    level_beginner: '初級 9×9',
    level_intermediate: '中級 16×16',
    level_expert: '高級 30×16',
    minesLeft: '剩餘地雷',
    time: '用時',
    bestTime: '最好成績',
    clicks: '3BV 最少點擊',
    dig: '挖開',
    flag: '旗子',
    modeHint: '右鍵或長按可以插旗。把上面的旗子按鈕打開，輕輕一點就能插旗。',
    won: '全部地雷都躲過了',
    lost: '踩到地雷了',
    newGame: '新一局',
    restart: '再來一次',
    how: '數字是緊挨著這一格的八格裡有幾顆地雷。第一格一定安全，周圍也沒有地雷，所以會開出一大片。',
    note: '3BV 是解開這一局最少要點幾下。同樣是 30 秒，3BV 150 的局和 80 的局根本不是一回事，只比秒數的話，抽到簡單局的人就贏了。',
    wide: '棋盤比螢幕寬的時候，左右拖動來看',
    cell: '格',
    flagged: '已插旗',
    unknown: '不確定',
  },
};
