/**
 * 이모지 → 아이콘 이름 매핑.
 *
 * og-icons.tsx에서 떼어낸 이유는 하나다 — 그쪽은 JSX가 들어 있어서
 * `node --test`가 파싱하지 못한다. 매핑 표만 JSX 없는 파일로 두면
 * 테스트가 직접 불러와 빠진 이모지를 셀 수 있다.
 *
 * 사이트 데이터가 카드마다 이모지를 이미 골라 뒀으니(사람이 고른 값이라
 * 내용을 제일 잘 나타낸다) 제목을 파싱하지 않고 이모지를 열쇠로 쓴다.
 * 뜻이 겹치는 이모지는 한 아이콘에 몰아넣는다 — 📋📝📄가 서로 다른 그림일
 * 필요는 없다.
 */

export const GROUPS: Record<string, string[]> = {
  smile: ['😊', '😄', '😀', '🙂', '😌', '😇', '😆', '😎', '🪞'],
  frown: ['😤', '😰', '😬', '😵', '😭'],
  mask: ['🎭', '🤥', '🙈', '😏', '🤪', '🤫', '🤐'],
  eye: ['👀', '👁️'],
  person: ['👤', '🧒', '🙇', '🧓', '👵', '🙋', '🧍', '🧑‍⚕️'],
  people: ['👥', '👫', '👨‍👩‍👧‍👦', '🫂', '🤲', '🙏', '🫰'],
  baby: ['👶', '🍼', '🧸', '🤰'],
  brain: ['🧠'],

  heart: ['❤️', '🤍', '💚', '💛', '💕', '💘', '🥰', '💜'],
  heartBroken: ['💔'],
  hearts: ['💑', '💞'],
  ring: ['💍', '💒', '👰'],
  pulse: ['🫀', '💹', '👏', '💓'],
  blood: ['🩸'],

  coin: ['💰', '💵', '💴', '💸'],
  card: ['💳'],
  bank: ['🏦'],
  piggy: ['🐷'],
  gem: ['💎', '🔷', '🔶'],
  chartUp: ['📈'],
  chartBar: ['📊'],
  candles: ['🪙'],

  clipboard: ['📋', '✅', '🪣'],
  doc: ['📄', '📜'],
  note: ['📝', '✏️', '🖊️', '✍️'],
  book: ['📚', '📖', '📗', '📔', '📓'],
  folder: ['📁', '🗂️', '💾'],
  receipt: ['🧾'],
  ruler: ['📐', '🪜'],
  letters: ['🔤', '🀄', '🟨', '🔣'],
  hash: ['#️⃣'],
  mail: ['📧', '💌', '📮'],
  megaphone: ['📣', '📢', '🗣️'],
  bubble: ['💬', '🗨️', '💭'],
  question: ['❓', '🤔'],
  bulb: ['💡'],

  clock: ['🕰️', '⏸️'],
  calendar: ['📅', '📆'],

  laptop: ['💻'],
  tv: ['📺'],
  screen: ['🖥️'],
  phone: ['📱', '📲', '🤳'],
  keyboard: ['⌨️'],
  mouse: ['🖱️'],
  plug: ['🔌'],
  wifi: ['📶'],
  cloud: ['☁️', '⛅', '🌫️', '🌤️'],
  robot: ['🤖'],
  atom: ['⚛️', '🧲'],
  triangle: ['▲', '🔺', '🍦'],
  triangleDown: ['🔻'],
  gamepad: ['🎮', '🕹️', '🔫', '♟️'],
  dice: ['🎲', '🎱'],
  ticket: ['🎟️', '🎫'],
  grid: ['🔲', '🔳', '🧱', '🟪', '🟦'],
  numbers: ['🔢'],
  calculator: ['🧮'],
  pie: ['🥧', '🎡', '🍕', '🍩', '💿'],
  arrowUp: ['🔼'],
  arrowDown: ['🔽'],
  equals: ['🟰'],
  thermometer: ['🌡️'],
  boat: ['⚓'],
  drop: ['💧', '🚰', '🐠', '🍯', '💦'],
  compress: ['🗜️'],
  touch: ['👆'],

  camera: ['📸', '📷'],
  video: ['📹', '🎥', '🎬', '🎦'],
  film: ['🎞️', '🍿', '📼'],
  play: ['▶️'],
  headphone: ['🎧'],
  music: ['🎵', '🎻', '🎼'],
  piano: ['🎹'],
  mic: ['🎤', '🎙️'],
  wave: ['〰️', '🎢', '💨'],
  speaker: ['🔊', '🔇', '👂'],

  home: ['🏠', '🏡', '🏘️', '🏚️'],
  building: ['🏢', '🏨', '🏪', '🏫', '🏛️', '🏙️'],
  castle: ['🏰', '🏯', '⛩️', '🗽'],
  door: ['🚪'],
  sofa: ['🛋️', '🛏️'],

  leaf: ['🌿', '🪴', '🍀', '🍃', '🌾', '🪵'],
  flower: ['🌸', '💐', '🍂'],
  globe: ['🌍', '🌎', '🌏', '🌐'],
  mountain: ['🌋', '🏔️', '⛰️', '🧗', '🎿', '🏞️'],
  umbrella: ['🏖️', '🏝️'],
  tent: ['⛺', '🏕️'],
  sunrise: ['🌅', '🌇', '☀️'],
  moon: ['🌙', '🌜', '🌗', '🌕'],
  rainbow: ['🌈'],
  snow: ['❄️', '🧊'],
  fire: ['🔥', '🌶️', '🪔', '🕯️'],
  bolt: ['⚡', '🔋', '🔦'],

  plate: ['🍽️', '🍴', '🍱', '🥩', '🥙', '🥣'],
  noodle: ['🍜', '🍝'],
  pan: ['🍳', '🧑‍🍳'],
  apple: ['🍎', '🥗', '🥦', '👅'],
  cake: ['🎂', '🍰', '🥐', '🥠', '🍬'],
  coffee: ['☕', '🍵', '🥤'],
  beer: ['🍺', '🍻', '🍶'],
  wine: ['🍷', '🍸', '🍹', '🥂'],
  can: ['🥫', '🥄'],

  dumbbell: ['🏋️'],
  run: ['🏃'],
  lotus: ['🧘', '🧘‍♀️'],
  ball: ['⚽', '⚾', '🏀', '🏐', '🥊', '🪁', '⛳', '🤹', '⭕', '🔵', '🥚'],
  stethoscope: ['🩺', '🚑', '🤒', '🤧'],
  pill: ['💊'],
  sleep: ['😴'],
  glasses: ['👓'],

  tie: ['👔'],
  shirt: ['👕', '🎽'],
  briefcase: ['💼', '🧑‍💼', '👷'],
  gradCap: ['🎓'],
  medal: ['🎖️', '🏅', '🥇'],
  trophy: ['🏆'],
  crown: ['👑'],

  tools: ['🔧', '🔨', '🧰', '🏗️', '🛠️', '🔩'],
  gear: ['⚙️'],
  scissors: ['✂️'],
  broom: ['🧹'],
  soap: ['🧼', '🧴', '🫧'],
  trash: ['🗑️'],
  search: ['🔍', '🕵️'],
  lock: ['🔒', '🔐'],
  unlock: ['🔓'],
  key: ['🔑', '🗝️'],
  shield: ['🛡️'],
  scale: ['⚖️'],
  target: ['🎯', '🏹', '🎣'],
  puzzle: ['🧩'],
  flask: ['🧪', '🔬'],
  telescope: ['🔭'],
  palette: ['🎨'],
  frame: ['🖼️'],
  tag: ['🏷️', '🆔', '🛂'],
  gift: ['🎁', '💝'],
  box: ['📦'],
  bag: ['🛍️', '🎒'],
  cart: ['🛒'],
  confetti: ['🎉', '🎊', '🎪', '🎎'],
  balloon: ['🎈'],
  check: ['☑️'],
  plus: ['➕', '➗'],
  refresh: ['🔄', '♻️', '🌀'],

  car: ['🚘', '🚙', '🛵', '🚆'],
  plane: ['✈️'],
  rocket: ['🚀'],
  map: ['🗺️', '🛣️', '📍'],
  compass: ['🧭'],
  /*
   * 국기(🇰🇷 같은 지역표시 두 글자)는 여기 넣지 않는다.
   * 한 장의 일반 깃발 윤곽으로 묶으면 나라 100곳이 전부 같은 그림이 된다 —
   * 실제로 그렇게 되어 /country 목록 100장이 구분되지 않았다. 국기는 그 나라의
   * 정체성이고 흑백 선으로 대체할 수 있는 것이 아니므로 이모지로 그대로 둔다.
   * (ToolIcon·ogGlyph는 매핑이 없으면 이모지를 그린다)
   */
  flag: ['🚩', '🏴‍☠️', '🏁'],
  warning: ['🚨', '🛑', '⚠️', '🚦', '🚸', '🚭', '🚧', '🧯'],

  dog: ['🐕', '🐶'],
  cat: ['🐈', '🐱'],
  paw: ['🐾', '🦊', '🦁', '🐐', '🐙', '🐋', '🦕', '🐸'],
  bird: ['🦅', '🕊️', '🐧'],
  bug: ['🐛'],
  dragon: ['🐉', '🐲'],

  crystalBall: ['🔮'],
  cards: ['🃏', '🎴'],
  hexagram: ['🔯'],
  star: ['⭐', '🌟', '💫', '🌠'],
  sparkles: ['✨', '💄'],
  wizard: ['🧙', '🎩'],
  hero: ['🦸'],
  ghost: ['👻', '😈'],
  sword: ['⚔️', '🗡️'],
  alarmClock: ['⏰'],
  stopwatch: ['⏱️'],
  kitchenTimer: ['⏲️'],
  tomato: ['🍅'],
  calendarWeek: ['🗓️'],
  hourglass: ['⏳'],
  rotate: ['🔃'],
  riceBowl: ['🍚'],
  saltShaker: ['🧂'],
  butter: ['🧈'],
  waterWave: ['🌊'],
  mosquito: ['🦟'],
  guitar: ['🎸'],
  upperLower: ['🔠'],
  fish: ['🐟'],
  needle: ['🪡'],
  gauge: ['🚗'],
  barrel: ['🛢️'],
  tractor: ['🚜'],
  tree: ['🌲'],
  tire: ['🛞'],
  server: ['🗄️'],
  rulerStraight: ['📏'],
  truck: ['🚛', '🚚'],
  raceCar: ['🏎️'],
  fuelPump: ['⛽'],
  seedling: ['🌱'],
  tornado: ['🌪️'],
  motorboat: ['🛥️'],
  dish: ['🧫'],
  retort: ['⚗️'],
  bookmark: ['🔖'],
  arrowUpBold: ['⬆️'],
  chartDown: ['📉'],
  split: ['🤝'],
  shuffle: ['🔀'],
  heartPulse: ['💗'],
  syringe: ['💉'],
  hospital: ['🏥'],
  swim: ['🏊'],
  shoe: ['👟'],
  kettlebell: ['💪'],
  swap: ['💱'],
  chain: ['🔗'],
  undo: ['↩️'],
  loop: ['🔁'],
  steam: ['♨️'],
  luggage: ['🛄', '🧳'],
  bone: ['🦴'],
  drumstick: ['🍗'],
  lungs: ['🫁'],
  bicycle: ['🚲'],
  rowboat: ['🚣'],
  slider: ['🎚️'],
  kidney: ['🫘'],
  cigarette: ['🚬'],
  honeycomb: ['🐝'],
  squareShape: ['🟥'],
  arrowRight: ['➡️'],
  pin: ['📌'],
  yarn: ['🧶'],
  rock: ['🪨'],
  saw: ['🪚'],
  window: ['🪟'],
  parking: ['🅿️'],
  rainCloud: ['🌧️'],
  galaxy: ['🌌'],
  horse: ['🐎', '🐴'],
  chopsticks: ['🥢'],
  shell: ['🦪'],
  ship: ['🚢'],
  glass: ['🥛'],
  corn: ['🌽'],
  stadium: ['🏟️'],
  subway: ['🚇', '🚋'],
  fingersCrossed: ['🤞'],
  axe: ['🪓'],
  twoPeople: ['👬'],
  swan: ['🦢'],
  sailboat: ['⛵'],
  openHands: ['🙌'],
  tiger: ['🐅'],
  jockey: ['🏇'],
  thread: ['🧵'],
  repeatOne: ['🔂'],
  cross: ['❌'],
  pinch: ['🤏'],
  sheep: ['🐑'],
  forbidden: ['🚫'],
};

/** 이모지 → 아이콘 이름 (GROUPS를 뒤집은 것) */
export const ICON_FOR: Record<string, string> = {};
for (const [name, emojis] of Object.entries(GROUPS)) {
  for (const e of emojis) ICON_FOR[e] = name;
}
