import type { Quiz } from './types';

export const QUIZZES: Quiz[] = [
  {
    slug: 'general-knowledge',
    title: '일반상식 퀴즈',
    desc: '기본 상식을 얼마나 알고 있는지 테스트해보세요',
    icon: '🌍',
    category: '상식',
    questions: [
      { q: '대한민국의 수도는?', opts: ['서울', '부산', '인천', '대전'], correct: 0, explanation: '대한민국의 수도는 서울이며, 1394년 조선 태조 이성계가 한양(현재 서울)으로 천도했습니다.' },
      { q: '세계에서 가장 높은 산은?', opts: ['K2', '에베레스트', '킬리만자로', '몽블랑'], correct: 1, explanation: '에베레스트(8,849m)는 세계에서 가장 높은 산으로, 히말라야 산맥에 위치합니다.' },
      { q: '인간의 체온(정상 범위)은 대략 몇 도인가요?', opts: ['35°C', '36.5°C', '38°C', '39°C'], correct: 1, explanation: '정상 체온은 36.1~37.2°C 사이이며, 일반적으로 36.5°C를 기준으로 합니다.' },
      { q: '빛의 속도는 대략 초당 얼마인가요?', opts: ['30만 km', '3만 km', '300만 km', '30억 km'], correct: 0, explanation: '빛의 속도는 진공 상태에서 초당 약 299,792km(약 30만 km)입니다.' },
      { q: '태양계에서 지구는 몇 번째 행성인가요?', opts: ['두 번째', '세 번째', '네 번째', '첫 번째'], correct: 1, explanation: '태양계 행성 순서: 수성, 금성, 지구, 화성, 목성, 토성, 천왕성, 해왕성. 지구는 세 번째입니다.' },
      { q: '물의 화학 기호는?', opts: ['CO2', 'H2O', 'NaCl', 'O2'], correct: 1, explanation: '물(H2O)은 수소 원자 2개와 산소 원자 1개로 이루어진 화합물입니다.' },
      { q: '한국의 국화(나라꽃)는?', opts: ['장미', '무궁화', '벚꽃', '국화'], correct: 1, explanation: '무궁화는 대한민국의 국화로, "끝없이 피고 또 피는 꽃"이라는 의미를 가집니다.' },
      { q: '1 킬로그램(kg)은 몇 그램(g)인가요?', opts: ['100g', '10g', '1,000g', '10,000g'], correct: 2, explanation: '킬로(kilo-)는 1,000을 의미하는 접두사로, 1kg = 1,000g입니다.' },
      { q: '인터넷 주소(URL)에서 "www"는 무엇의 약자인가요?', opts: ['World Wide Web', 'Web World Wide', 'Wide World Web', 'Web Worldwide Wire'], correct: 0, explanation: 'www는 World Wide Web의 약자로, 팀 버너스 리가 1989년에 창안한 인터넷 기반 하이퍼미디어 시스템입니다.' },
      { q: '24시간 365일 영업하는 편의점의 대표 브랜드 "7-Eleven"의 숫자는 원래 무엇을 의미했나요?', opts: ['가게 번호', '영업시간 오전 7시~오후 11시', '창업 연도 1711년', '상품 종류 수'], correct: 1, explanation: '7-Eleven은 원래 오전 7시부터 오후 11시까지 영업하는 시간을 나타낸 이름이었습니다.' },
    ],
  },
  {
    slug: 'korean-history',
    title: '한국사 퀴즈',
    desc: '한국 역사를 얼마나 알고 있나요?',
    icon: '🏯',
    category: '역사',
    questions: [
      { q: '조선을 건국한 왕은 누구인가요?', opts: ['이성계', '왕건', '광개토대왕', '세종대왕'], correct: 0, explanation: '이성계(태조)는 1392년 고려를 무너뜨리고 조선을 건국했습니다.' },
      { q: '한글을 창제한 왕은?', opts: ['태종', '세종대왕', '성종', '중종'], correct: 1, explanation: '세종대왕은 1443년 훈민정음(한글)을 창제했습니다. 이전까지 우리나라는 한자를 사용했습니다.' },
      { q: '임진왜란이 일어난 해는?', opts: ['1492년', '1592년', '1392년', '1692년'], correct: 1, explanation: '임진왜란은 1592년(선조 25년) 일본이 조선을 침략하면서 시작되었습니다.' },
      { q: '3·1 운동이 일어난 해는?', opts: ['1905년', '1919년', '1945년', '1960년'], correct: 1, explanation: '3·1 운동은 1919년 3월 1일 일본 식민 지배에 저항하여 일어난 독립운동입니다.' },
      { q: '6·25 전쟁이 시작된 해는?', opts: ['1945년', '1948년', '1950년', '1953년'], correct: 2, explanation: '6·25 전쟁(한국전쟁)은 1950년 6월 25일 북한의 남침으로 시작되었습니다.' },
      { q: '신라를 세운 나라는?', opts: ['박혁거세', '이성계', '온조', '동명성왕'], correct: 0, explanation: '신라는 기원전 57년 박혁거세가 건국했습니다. 삼국시대의 세 나라 중 하나입니다.' },
      { q: '광개토대왕이 속한 나라는?', opts: ['신라', '백제', '고구려', '가야'], correct: 2, explanation: '광개토대왕은 고구려의 제19대 왕으로, 영토를 크게 확장하여 "광개토"라는 호칭을 얻었습니다.' },
      { q: '고려의 마지막 왕은?', opts: ['공민왕', '우왕', '공양왕', '충정왕'], correct: 2, explanation: '공양왕은 고려의 마지막 왕(34대)으로, 이성계에 의해 폐위되고 조선이 건국되었습니다.' },
      { q: '조선 시대 최초의 실학자로 불리는 사람은?', opts: ['이황', '이이', '유형원', '정약용'], correct: 2, explanation: '유형원(반계)은 조선 중기 실학의 선구자로 "반계수록"을 저술했습니다.' },
      { q: '을사늑약이 체결된 해는?', opts: ['1895년', '1905년', '1910년', '1919년'], correct: 1, explanation: '을사늑약(1905년)은 일제가 강제로 체결한 조약으로, 대한제국의 외교권을 박탈했습니다.' },
    ],
  },
  {
    slug: 'javascript',
    title: '자바스크립트 퀴즈',
    desc: '자바스크립트 기초 지식을 테스트해보세요',
    icon: '🟨',
    category: '기술·IT',
    questions: [
      { q: 'typeof null 의 결과는?', opts: ['"null"', '"object"', '"undefined"', '"boolean"'], correct: 1, explanation: 'typeof null이 "object"를 반환하는 것은 자바스크립트의 역사적 버그입니다. ECMAScript 초기 구현에서의 오류가 그대로 유지되었습니다.' },
      { q: '0.1 + 0.2 === 0.3 의 결과는?', opts: ['true', 'false', 'undefined', 'NaN'], correct: 1, explanation: 'IEEE 754 부동소수점 방식으로 인해 0.1 + 0.2는 0.30000000000000004가 됩니다. 따라서 결과는 false입니다.' },
      { q: 'const, let, var 중 블록 스코프를 갖지 않는 것은?', opts: ['const', 'let', 'var', '모두 블록 스코프'], correct: 2, explanation: 'var는 함수 스코프를 가지며, 블록({ }) 내에서 선언해도 블록 밖에서 접근 가능합니다. const와 let은 블록 스코프입니다.' },
      { q: 'Array.prototype.map() 의 반환값은?', opts: ['undefined', '원본 배열', '새 배열', 'Boolean'], correct: 2, explanation: 'map()은 원본 배열을 변경하지 않고, 콜백 함수의 반환값으로 구성된 새로운 배열을 반환합니다.' },
      { q: '===와 ==의 차이는?', opts: ['차이 없음', '=== 는 타입까지 비교', '== 가 더 엄격', '=== 는 값만 비교'], correct: 1, explanation: '=== (엄격 동등)는 값과 타입을 모두 비교하고, == (동등)는 타입 변환 후 값만 비교합니다.' },
      { q: 'Promise.all()은 언제 reject되나요?', opts: ['모든 Promise가 reject될 때', '하나라도 reject되면', '50% 이상 reject되면', 'reject되지 않음'], correct: 1, explanation: 'Promise.all()은 전달된 Promise 중 하나라도 reject되면 즉시 reject됩니다. (Fast-fail 방식)' },
      { q: 'JSON.stringify()로 변환할 수 없는 값은?', opts: ['null', 'Array', 'undefined', 'Number'], correct: 2, explanation: 'undefined, 함수, Symbol은 JSON.stringify()로 직렬화할 수 없으며, 객체 속성이면 무시되고 배열 요소면 null이 됩니다.' },
      { q: 'event.preventDefault()의 역할은?', opts: ['이벤트 버블링 막기', '기본 동작 막기', '이벤트 삭제', 'DOM 업데이트 막기'], correct: 1, explanation: 'preventDefault()는 링크 클릭 시 페이지 이동, 폼 submit 시 페이지 새로고침 같은 브라우저 기본 동작을 막습니다.' },
      { q: 'async/await에서 에러를 잡는 방법은?', opts: ['try/catch', '.catch()', 'try/finally', 'error 이벤트'], correct: 0, explanation: 'async 함수 내에서는 try/catch를 사용하여 await된 Promise의 rejection을 처리합니다.' },
      { q: 'localStorage와 sessionStorage의 차이는?', opts: ['용량 차이', '도메인 제한 차이', '탭/브라우저 종료 시 삭제 여부', '보안 수준 차이'], correct: 2, explanation: 'sessionStorage는 탭/브라우저가 닫히면 데이터가 삭제되지만, localStorage는 명시적으로 삭제하기 전까지 유지됩니다.' },
    ],
  },
  {
    slug: 'kpop',
    title: 'K-POP 퀴즈',
    desc: 'K-POP 상식을 얼마나 알고 있나요?',
    icon: '🎵',
    category: '엔터테인먼트',
    questions: [
      { q: '2024년 기준 빌보드 HOT 100 1위를 달성한 최초의 한국 그룹은?', opts: ['EXO', 'BTS', 'BLACKPINK', 'TWICE'], correct: 1, explanation: 'BTS는 2020년 "Dynamite"로 빌보드 HOT 100 1위를 달성한 최초의 한국 가수가 되었습니다.' },
      { q: 'BLACKPINK의 소속사는?', opts: ['SM Entertainment', 'JYP Entertainment', 'YG Entertainment', 'HYBE'], correct: 2, explanation: 'BLACKPINK는 YG Entertainment 소속으로, 2016년 데뷔했습니다.' },
      { q: 'aespa 멤버가 아닌 사람은?', opts: ['카리나', '지젤', '윈터', '예나'], correct: 3, explanation: 'aespa는 카리나, 지젤, 윈터, 닝닝으로 구성됩니다. 예나는 IZ*ONE 출신 솔로 아티스트입니다.' },
      { q: '"FIFTY FIFTY"의 데뷔곡은?', opts: ['Cupid', 'Barbie Dreams', 'Lovin Me', 'Tell Me'], correct: 0, explanation: 'FIFTY FIFTY는 2022년 데뷔 후 2023년 "Cupid"로 빌보드 글로벌 차트에 진입하며 큰 인기를 얻었습니다.' },
      { q: '소녀시대 멤버 수는?', opts: ['7명', '8명', '9명', '10명'], correct: 2, explanation: '소녀시대는 처음 9명으로 데뷔했습니다(태연, 제시카, 써니, 티파니, 효연, 유리, 수영, 윤아, 서현).' },
      { q: '"뉴진스(NewJeans)"는 몇 명으로 구성되나요?', opts: ['4명', '5명', '6명', '3명'], correct: 1, explanation: '뉴진스는 민지, 하니, 다니엘, 해린, 혜인 5명으로 구성된 그룹입니다.' },
      { q: 'K-POP에서 "컴백"이 의미하는 것은?', opts: ['은퇴 후 복귀', '새 앨범 발매', '방송 출연 재개', '군대 복귀'], correct: 1, explanation: 'K-POP에서 컴백(comeback)은 새 앨범이나 싱글을 발매하는 것을 의미합니다.' },
      { q: '스트레이 키즈(Stray Kids)의 소속사는?', opts: ['SM', 'YG', 'JYP', 'HYBE'], correct: 2, explanation: '스트레이 키즈는 JYP Entertainment 소속으로, 2018년 데뷔했습니다.' },
      { q: '다음 중 4세대 K-POP 그룹은?', opts: ['소녀시대', '2NE1', 'aespa', 'f(x)'], correct: 2, explanation: 'aespa는 2020년 데뷔한 4세대 걸그룹입니다. 소녀시대, 2NE1, f(x)는 2세대 그룹입니다.' },
      { q: '"Gangnam Style"을 부른 가수는?', opts: ['비', '싸이', '원더걸스', 'G-DRAGON'], correct: 1, explanation: '싸이(PSY)의 "강남스타일"(2012)은 유튜브 최초로 10억 조회수를 달성한 한국 K-POP입니다.' },
    ],
  },
  {
    slug: 'health',
    title: '건강 상식 퀴즈',
    desc: '일상 건강 상식을 얼마나 알고 있나요?',
    icon: '❤️',
    category: '생활·건강',
    questions: [
      { q: '성인 기준 하루 권장 수분 섭취량은?', opts: ['500mL', '1리터', '1.5~2리터', '3리터 이상'], correct: 2, explanation: '성인 기준 하루 1.5~2리터의 수분 섭취를 권장합니다. 운동량과 날씨에 따라 더 필요할 수 있습니다.' },
      { q: 'BMI(체질량지수)로 비만을 판단할 때 기준은?', opts: ['BMI 25 이상', 'BMI 30 이상', 'BMI 22 이상', 'BMI 27 이상'], correct: 0, explanation: '한국 기준으로 BMI 23~24.9는 과체중, 25 이상은 비만으로 분류합니다.' },
      { q: '수면 중 뇌가 하는 일이 아닌 것은?', opts: ['기억 정리', '독소 제거', '소화 촉진', '세포 재생'], correct: 2, explanation: '소화는 주로 깨어있을 때 이루어집니다. 수면 중 뇌는 기억 정리, 독소 제거(글림프 시스템), 세포 재생 등을 합니다.' },
      { q: '비타민 D를 생성하는 데 필요한 것은?', opts: ['채소 섭취', '자외선(햇빛)', '수면', '운동'], correct: 1, explanation: '비타민 D는 피부가 햇빛(UVB)에 노출될 때 체내에서 합성됩니다. 음식으로도 섭취할 수 있습니다.' },
      { q: '심폐소생술(CPR)에서 가슴 압박 속도는?', opts: ['분당 60회', '분당 100~120회', '분당 80회', '분당 150회'], correct: 1, explanation: 'CPR 가슴 압박은 분당 100~120회의 속도로, 5~6cm 깊이로 압박합니다.' },
      { q: '혈당 스파이크를 방지하기 위한 식사 순서는?', opts: ['밥 → 고기 → 채소', '채소 → 단백질 → 탄수화물', '국 → 밥 → 반찬', '탄수화물 → 채소 → 단백질'], correct: 1, explanation: '채소(식이섬유) → 단백질 → 탄수화물 순으로 먹으면 혈당 상승 속도를 늦출 수 있습니다.' },
      { q: '스트레칭을 해야 하는 최적의 시간은?', opts: ['일어나자마자', '운동 전 차가운 근육에', '운동 후 따뜻해진 상태에서', '자기 직전'], correct: 2, explanation: '스트레칭은 운동 후 근육이 충분히 따뜻해졌을 때가 가장 효과적입니다. 차가운 근육을 무리하게 늘리면 부상 위험이 있습니다.' },
      { q: '성인 심장 박동수(안정시 정상 범위)는?', opts: ['40~50회/분', '60~100회/분', '100~120회/분', '50~60회/분'], correct: 1, explanation: '안정시 정상 심박수는 분당 60~100회입니다. 운동선수는 더 낮을 수 있습니다.' },
      { q: '카페인의 반감기는 대략?', opts: ['1~2시간', '3~5시간', '10~12시간', '24시간'], correct: 1, explanation: '카페인의 반감기는 약 3~5시간입니다. 오후 3시에 커피를 마시면 밤 8시에도 절반의 카페인이 남아있습니다.' },
      { q: '알레르기의 원인으로 틀린 것은?', opts: ['꽃가루', '음식', '세균 감염', '동물 털'], correct: 2, explanation: '세균 감염은 면역 반응이지만 알레르기는 아닙니다. 알레르기는 무해한 물질에 대한 과민 면역 반응입니다.' },
    ],
  },
];

// 에이전트가 나머지 95개를 추가합니다
export const QUIZ_MAP: Record<string, Quiz> = Object.fromEntries(QUIZZES.map(q => [q.slug, q]));
