import type { Quiz } from './types';

/**
 * 영어 퀴즈.
 *
 * 한국어 182종은 한국사·K-POP 등 문화 의존이 커서 옮겨봐야 영어권에서 검색되지도,
 * 풀리지도 않는다. 그래서 번역이 아니라 영어권 기준으로 새로 만들었다.
 *
 * 문제는 사실 관계가 분명하고 시간이 지나도 답이 바뀌지 않는 것만 담았다.
 * "가장 큰 회사" 같은 문제는 몇 년 뒤 오답이 되므로 넣지 않는다.
 */
export const QUIZZES_EN: Quiz[] = [
  {
    slug: 'world-capitals',
    title: 'World Capitals Quiz',
    desc: 'Ten capitals that people get wrong more often than they expect',
    icon: '🌍',
    category: 'Geography',
    questions: [
      { q: 'What is the capital of Australia?', opts: ['Canberra', 'Brisbane', 'Sydney', 'Melbourne'], correct: 0,
        explanation: 'Canberra was purpose-built as a compromise between Sydney and Melbourne, which both wanted the title.' },
      { q: 'What is the capital of Turkey?', opts: ['Istanbul', 'Ankara', 'Izmir', 'Antalya'], correct: 1,
        explanation: 'Ankara replaced Istanbul as capital in 1923 with the founding of the republic.' },
      { q: 'What is the capital of Canada?', opts: ['Vancouver', 'Montreal', 'Ottawa', 'Toronto'], correct: 2,
        explanation: 'Ottawa was chosen by Queen Victoria in 1857, partly because it sat on the border of English and French Canada.' },
      { q: 'What is the capital of Brazil?', opts: ['Salvador', 'Rio de Janeiro', 'São Paulo', 'Brasília'], correct: 3,
        explanation: 'Brasília was built from nothing in the interior and became the capital in 1960.' },
      { q: 'What is the capital of Switzerland?', opts: ['Bern', 'Zurich', 'Geneva', 'Basel'], correct: 0,
        explanation: 'Bern is technically the "federal city" — Switzerland has never formally named a capital.' },
      { q: 'What is the capital of New Zealand?', opts: ['Auckland', 'Wellington', 'Christchurch', 'Dunedin'], correct: 1,
        explanation: 'Wellington took over from Auckland in 1865 for being more central to both islands.' },
      { q: 'What is the capital of South Africa?', opts: ['Johannesburg', 'Pretoria', 'It has three', 'Cape Town'], correct: 2,
        explanation: 'Pretoria is administrative, Cape Town legislative and Bloemfontein judicial.' },
      { q: 'What is the capital of Morocco?', opts: ['Fez', 'Casablanca', 'Marrakesh', 'Rabat'], correct: 3,
        explanation: 'Rabat has been the capital since 1912, though Casablanca is the larger city.' },
      { q: 'What is the capital of Vietnam?', opts: ['Hanoi', 'Da Nang', 'Hue', 'Ho Chi Minh City'], correct: 0,
        explanation: 'Hanoi is the capital; Ho Chi Minh City is larger but is not the seat of government.' },
      { q: 'What is the capital of Nigeria?', opts: ['Lagos', 'Abuja', 'Kano', 'Ibadan'], correct: 1,
        explanation: 'Abuja replaced Lagos in 1991, chosen for its central and religiously neutral location.' },
    ],
  },
  {
    slug: 'science-basics',
    title: 'Science Basics Quiz',
    desc: 'Ten questions on the science most people half-remember',
    icon: '🔬',
    category: 'Science',
    questions: [
      { q: 'What is the most abundant gas in Earth’s atmosphere?', opts: ['Nitrogen', 'Argon', 'Oxygen', 'Carbon dioxide'], correct: 0,
        explanation: 'Nitrogen makes up about 78% of the atmosphere; oxygen is around 21%.' },
      { q: 'How many bones are in an adult human body?', opts: ['186', '206', '226', '246'], correct: 1,
        explanation: 'Babies are born with around 270; many fuse together during growth.' },
      { q: 'What is the hardest naturally occurring substance?', opts: ['Quartz', 'Steel', 'Diamond', 'Titanium'], correct: 2,
        explanation: 'Diamond sits at 10 on the Mohs scale. Steel and titanium are alloys, not natural minerals.' },
      { q: 'Which planet has the most moons?', opts: ['Uranus', 'Neptune', 'Jupiter', 'Saturn'], correct: 3,
        explanation: 'Saturn overtook Jupiter after a large batch of confirmations in 2023.' },
      { q: 'What does DNA stand for?', opts: ['Deoxyribonucleic acid', 'Dinucleic acid', 'Deoxyribose nuclear acid', 'Double nucleic acid'], correct: 0,
        explanation: 'Deoxyribonucleic acid — the sugar in its backbone is deoxyribose.' },
      { q: 'At what temperature are Celsius and Fahrenheit equal?', opts: ['0°', '-40°', '-100°', 'They never are'], correct: 1,
        explanation: '−40°C is exactly −40°F. The two scales cross at that single point.' },
      { q: 'What is the speed of light in a vacuum, roughly?', opts: ['30,000 km/s', '3,000,000 km/s', '300,000 km/s', '300,000 km/h'], correct: 2,
        explanation: 'About 299,792 km per second — close enough to 300,000 for most purposes.' },
      { q: 'Which blood type is the universal donor for red cells?', opts: ['B negative', 'A negative', 'AB positive', 'O negative'], correct: 3,
        explanation: 'O negative has no A, B or Rh antigens, so it can go to anyone in an emergency.' },
      { q: 'What causes the seasons on Earth?', opts: ['The tilt of Earth’s axis', 'Solar flare cycles', 'The Moon’s orbit', 'Distance from the Sun'], correct: 0,
        explanation: 'The 23.5° axial tilt does it. Earth is actually closest to the Sun in January.' },
      { q: 'How long does light from the Sun take to reach Earth?', opts: ['8 seconds', '8 minutes', '8 hours', '8 days'], correct: 1,
        explanation: 'About 8 minutes 20 seconds — so you always see the Sun as it was minutes ago.' },
    ],
  },
  {
    slug: 'world-history',
    title: 'World History Quiz',
    desc: 'Ten moments that changed the shape of the world',
    icon: '🏛️',
    category: 'History',
    questions: [
      { q: 'In which year did the Berlin Wall fall?', opts: ['1989', '1991', '1993', '1987'], correct: 0,
        explanation: 'The crossings opened on 9 November 1989 after a mistakenly announced travel rule.' },
      { q: 'Which civilisation built Machu Picchu?', opts: ['Aztec', 'Inca', 'Olmec', 'Maya'], correct: 1,
        explanation: 'The Inca built it in the fifteenth century, probably as an estate for the emperor Pachacuti.' },
      { q: 'How long did the Hundred Years’ War actually last?', opts: ['150 years', '100 years', '116 years', '87 years'], correct: 2,
        explanation: '1337 to 1453 — 116 years, with long pauses in between.' },
      { q: 'Who was the first woman to win a Nobel Prize?', opts: ['Rosalind Franklin', 'Dorothy Hodgkin', 'Ada Lovelace', 'Marie Curie'], correct: 3,
        explanation: 'Marie Curie won Physics in 1903, then Chemistry in 1911 — still the only person to win in two sciences.' },
      { q: 'Which empire was ruled from Constantinople?', opts: ['Both', 'Neither', 'Ottoman', 'Byzantine'], correct: 0,
        explanation: 'The Byzantines until 1453, then the Ottomans after Mehmed II took the city.' },
      { q: 'What ended the Western Roman Empire in 476 CE?', opts: ['A plague', 'The deposing of its last emperor', 'A volcanic eruption', 'Conversion to Christianity'], correct: 1,
        explanation: 'Odoacer deposed Romulus Augustulus. The Eastern empire continued for another thousand years.' },
      { q: 'Which country was never colonised by a European power?', opts: ['Indonesia', 'Vietnam', 'Ethiopia', 'India'], correct: 2,
        explanation: 'Ethiopia repelled Italy at Adwa in 1896, though it was occupied briefly in the 1930s.' },
      { q: 'The printing press was introduced to Europe by whom?', opts: ['William Caxton', 'Martin Luther', 'Leonardo da Vinci', 'Johannes Gutenberg'], correct: 3,
        explanation: 'Gutenberg, around 1440. Movable type had existed in Korea and China considerably earlier.' },
      { q: 'Which two countries fought the Winter War of 1939–40?', opts: ['Soviet Union and Finland', 'Japan and China', 'Italy and Greece', 'Germany and Poland'], correct: 0,
        explanation: 'Finland held off a far larger Soviet force for over three months.' },
      { q: 'Approximately when did the Great Pyramid of Giza get built?', opts: ['1,500 years ago', '4,500 years ago', '2,500 years ago', '7,000 years ago'], correct: 1,
        explanation: 'Around 2560 BCE. Cleopatra lived closer in time to us than to its construction.' },
    ],
  },
  {
    slug: 'internet-tech',
    title: 'Internet & Tech Quiz',
    desc: 'Ten questions on how the thing you are using actually works',
    icon: '💻',
    category: 'Technology',
    questions: [
      { q: 'What does HTTP stand for?', opts: ['HyperText Transfer Protocol', 'High Transfer Text Protocol', 'HyperText Transmission Process', 'Host Transfer Protocol'], correct: 0,
        explanation: 'The S in HTTPS adds a TLS-encrypted layer on top of the same protocol.' },
      { q: 'What does a DNS server actually do?', opts: ['Stores your passwords', 'Turns domain names into IP addresses', 'Encrypts your traffic', 'Blocks advertisements'], correct: 1,
        explanation: 'It is the phone book of the internet — vixutil.com in, an IP address out.' },
      { q: 'Roughly how many bytes are in a kilobyte, as storage is usually sold?', opts: ['100', '10,000', '1,000', '1,024'], correct: 2,
        explanation: 'Drive makers use 1,000; operating systems often count 1,024, which is why a "1 TB" drive shows less.' },
      { q: 'What is a VPN primarily for?', opts: ['Removing viruses', 'Backing up files', 'Making the internet faster', 'Routing your traffic through another server'], correct: 3,
        explanation: 'It tunnels traffic via a server elsewhere. It hides traffic from your local network — not from the VPN itself.' },
      { q: 'What does "open source" mean?', opts: ['The source code is publicly available', 'Made by volunteers only', 'Cannot be sold commercially', 'Always free of charge'], correct: 0,
        explanation: 'Availability of the code is the definition. Plenty of open-source software is sold commercially.' },
      { q: 'What is phishing?', opts: ['Slowing down a network', 'Tricking someone into giving up credentials', 'Encrypting files for ransom', 'Scanning for open ports'], correct: 1,
        explanation: 'It targets the person rather than the system, which is why technical defences alone do not stop it.' },
      { q: 'What does the "cloud" physically consist of?', opts: ['Undersea cables only', 'Satellites', 'Other people’s computers in data centres', 'Radio towers'], correct: 2,
        explanation: 'Data centres full of ordinary servers. "The cloud" is a billing model more than a technology.' },
      { q: 'What is the purpose of two-factor authentication?', opts: ['Logging in twice', 'Two email addresses', 'Two passwords', 'Something you know plus something you have'], correct: 3,
        explanation: 'A stolen password alone is not enough if the second factor is a device you hold.' },
      { q: 'What does RAM do?', opts: ['Holds data the processor is actively using', 'Displays graphics', 'Connects to the internet', 'Stores files permanently'], correct: 0,
        explanation: 'It is fast and volatile — everything in it is lost when the power goes.' },
      { q: 'Who is generally credited with proposing the World Wide Web?', opts: ['Bill Gates', 'Tim Berners-Lee', 'Vint Cerf', 'Alan Turing'], correct: 1,
        explanation: 'Berners-Lee proposed it at CERN in 1989. Vint Cerf co-designed TCP/IP, which the internet itself runs on.' },
    ],
  },
  {
    slug: 'human-body',
    title: 'Human Body Quiz',
    desc: 'Ten questions about the machine you are currently operating',
    icon: '🫀',
    category: 'Science',
    questions: [
      { q: 'Which organ produces insulin?', opts: ['Pancreas', 'Kidney', 'Thyroid', 'Liver'], correct: 0,
        explanation: 'The beta cells of the pancreas. Type 1 diabetes occurs when those cells are destroyed.' },
      { q: 'How many chambers does the human heart have?', opts: ['Three', 'Four', 'Six', 'Two'], correct: 1,
        explanation: 'Two atria and two ventricles, keeping oxygenated and deoxygenated blood separate.' },
      { q: 'What is the largest organ in the human body?', opts: ['Liver', 'Brain', 'Skin', 'Lungs'], correct: 2,
        explanation: 'Skin — roughly two square metres of it on an average adult.' },
      { q: 'Roughly what percentage of the human body is water?', opts: ['About 85%', 'About 95%', 'About 30%', 'About 60%'], correct: 3,
        explanation: 'Around 60% in adults, higher in infants and lower in older adults.' },
      { q: 'Which part of the brain controls balance and coordination?', opts: ['Cerebellum', 'Brainstem', 'Hippocampus', 'Cerebrum'], correct: 0,
        explanation: 'The cerebellum, at the back and underneath. It holds more neurons than the rest of the brain combined.' },
      { q: 'How long does a red blood cell live, roughly?', opts: ['About 12 days', 'About 120 days', 'The whole lifetime', 'About 12 hours'], correct: 1,
        explanation: 'About four months, after which the spleen and liver recycle it.' },
      { q: 'What is the smallest bone in the human body?', opts: ['A wrist bone', 'A toe bone', 'Stapes, in the ear', 'The last finger bone'], correct: 2,
        explanation: 'The stapes, one of three tiny bones that transmit sound in the middle ear.' },
      { q: 'Which vitamin does your skin make from sunlight?', opts: ['Vitamin K', 'Vitamin A', 'Vitamin C', 'Vitamin D'], correct: 3,
        explanation: 'UVB triggers vitamin D synthesis. Glass blocks UVB, so sitting by a window does not count.' },
      { q: 'What is the function of the alveoli in the lungs?', opts: ['Gas exchange with the blood', 'Producing mucus', 'Controlling breathing rate', 'Filtering dust'], correct: 0,
        explanation: 'Oxygen in, carbon dioxide out, across a surface roughly the size of a tennis court.' },
      { q: 'How many pairs of chromosomes does a human normally have?', opts: ['21', '23', '46', '48'], correct: 1,
        explanation: '23 pairs, 46 chromosomes in total, one of each pair from each parent.' },
    ],
  },
  {
    slug: 'movies-general',
    title: 'Film Trivia Quiz',
    desc: 'Ten questions on films that most people have at least heard of',
    icon: '🎬',
    category: 'Entertainment',
    questions: [
      { q: 'Which film won the first Academy Award for Best Picture?', opts: ['Wings', 'The Jazz Singer', 'Metropolis', 'Sunrise'], correct: 0,
        explanation: 'Wings, a silent war film, took the first Best Picture award in 1929.' },
      { q: 'Who directed Jaws, Jurassic Park and Schindler’s List?', opts: ['Martin Scorsese', 'Steven Spielberg', 'Ridley Scott', 'James Cameron'], correct: 1,
        explanation: 'Spielberg directed all three, spanning three different decades.' },
      { q: 'What was the first feature-length animated film?', opts: ['Bambi', 'Pinocchio', 'Snow White and the Seven Dwarfs', 'Fantasia'], correct: 2,
        explanation: 'Snow White, 1937. The industry expected it to fail and called it "Disney’s Folly".' },
      { q: 'In The Wizard of Oz, what colour were the slippers in the original book?', opts: ['Gold', 'Emerald', 'Ruby', 'Silver'], correct: 3,
        explanation: 'Silver in the book. They were changed to ruby to show off Technicolor.' },
      { q: 'Which film features the line "Here’s looking at you, kid"?', opts: ['Casablanca', 'Citizen Kane', 'The Maltese Falcon', 'Gone with the Wind'], correct: 0,
        explanation: 'Casablanca, 1942 — the line was reportedly ad-libbed by Humphrey Bogart.' },
      { q: 'What does the Pixar lamp in the studio logo squash?', opts: ['A ball', 'The letter I', 'A cube', 'The letter O'], correct: 1,
        explanation: 'The lamp flattens the I in PIXAR, a reference to the short film Luxo Jr.' },
      { q: 'Which country produces the most films per year?', opts: ['Nigeria', 'United States', 'India', 'China'], correct: 2,
        explanation: 'India, by volume, across many regional film industries — not just Hindi-language Bollywood.' },
      { q: 'What is a "MacGuffin"?', opts: ['A type of film score', 'A lighting setup', 'A camera technique', 'An object that drives the plot but does not matter itself'], correct: 3,
        explanation: 'Hitchcock’s term. The briefcase, the formula, the falcon — what matters is that characters want it.' },
      { q: 'Roughly how long is a standard feature film reel change interval?', opts: ['20 minutes', '45 minutes', '90 minutes', '5 minutes'], correct: 0,
        explanation: 'About 20 minutes per reel — the "cigarette burn" marks in the corner cued the switch.' },
      { q: 'Which film was the first to be shot entirely on digital video and released widely?', opts: ['The Matrix', 'Star Wars: Episode II', 'Avatar', 'Toy Story'], correct: 1,
        explanation: 'Attack of the Clones, 2002, shot fully on high-definition digital cameras.' },
    ],
  },
];

export const QUIZZES_EN_MAP: Record<string, Quiz> = Object.fromEntries(
  QUIZZES_EN.map(q => [q.slug, q]),
);
