/**
 * 뽑기 도구 여섯(카드·가위바위보·빙고·가중치·당번표·예아니오)의 화면 문구.
 *
 * lib/random-ui-intl.ts의 RandomUi가 이미 커서 새 도구는 여기 따로 둔다 —
 * 계산을 lib/random-more.ts로 나눈 것과 같은 이유다.
 */
import type { RandomLang } from './random-ui-intl.ts';

export interface RandomMoreUi {
  drawCard: string;
  howManyCards: string;
  again: string;
  deckNote: string;
  rock: string;
  paper: string;
  scissors: string;
  youWin: string;
  youLose: string;
  itsDraw: string;
  pickYours: string;
  record: string;
  boardSize: string;
  freeCenter: string;
  newBoard: string;
  bingoCount: string;
  tapToMark: string;
  weightTitle: string;
  weight: string;
  chance: string;
  addItem: string;
  drawWeighted: string;
  weightNote: string;
  turns: string;
  perTurn: string;
  makeRoster: string;
  turnNo: string;
  timesEach: string;
  rosterNote: string;
  askIt: string;
  lean: string;
  yes: string;
  no: string;
  decide: string;
  leanNote: string;
}

export const RANDOM_MORE_UI: Record<RandomLang, RandomMoreUi> = {
  ko: {
    drawCard: "카드 뽑기",
    howManyCards: "몇 장",
    again: "다시 뽑기",
    deckNote: "한 벌에서 뽑으므로 같은 카드가 두 번 나오지 않습니다",
    rock: "바위",
    paper: "보",
    scissors: "가위",
    youWin: "이겼습니다",
    youLose: "졌습니다",
    itsDraw: "비겼습니다",
    pickYours: "내 손을 고르세요",
    record: "전적",
    boardSize: "판 크기",
    freeCenter: "가운데 무료 칸",
    newBoard: "새 판 만들기",
    bingoCount: "완성한 줄",
    tapToMark: "칸을 눌러 지우세요",
    weightTitle: "항목과 가중치",
    weight: "가중치",
    chance: "확률",
    addItem: "+ 항목 추가",
    drawWeighted: "가중치로 뽑기",
    weightNote: "가중치가 클수록 자주 뽑힙니다. 0이면 뽑히지 않습니다.",
    turns: "몇 차례",
    perTurn: "한 차례 인원",
    makeRoster: "당번표 만들기",
    turnNo: "차례",
    timesEach: "사람별 횟수",
    rosterNote: "한 바퀴를 다 돌기 전에는 같은 사람이 두 번 걸리지 않고, 바퀴가 바뀔 때도 연달아 오지 않습니다.",
    askIt: "질문을 적어보세요 (없어도 됩니다)",
    lean: "\"예\"가 나올 확률",
    yes: "예",
    no: "아니오",
    decide: "정해줘",
    leanNote: "답이 나왔을 때 마음이 어떤지 보세요 — 아쉬우면 이미 답을 알고 있는 겁니다.",
  },
  en: {
    drawCard: "Draw",
    howManyCards: "How many",
    again: "Draw again",
    deckNote: "Drawn from one deck, so no card repeats",
    rock: "Rock",
    paper: "Paper",
    scissors: "Scissors",
    youWin: "You win",
    youLose: "You lose",
    itsDraw: "A draw",
    pickYours: "Pick your hand",
    record: "Record",
    boardSize: "Board size",
    freeCenter: "Free centre square",
    newBoard: "New board",
    bingoCount: "Lines completed",
    tapToMark: "Tap a square to mark it",
    weightTitle: "Items and weights",
    weight: "Weight",
    chance: "Chance",
    addItem: "+ Add item",
    drawWeighted: "Draw by weight",
    weightNote: "A bigger weight is drawn more often. Zero is never drawn.",
    turns: "How many turns",
    perTurn: "People per turn",
    makeRoster: "Build the roster",
    turnNo: "Turn",
    timesEach: "Times each",
    rosterNote: "Nobody comes up twice before everyone has had a turn, and nobody lands twice in a row across rounds.",
    askIt: "Type your question (optional)",
    lean: "Chance of yes",
    yes: "Yes",
    no: "No",
    decide: "Decide for me",
    leanNote: "Watch how you feel about the answer — if you are disappointed, you already knew.",
  },
  es: {
    drawCard: "Sacar",
    howManyCards: "Cuántas",
    again: "Sacar otra vez",
    deckNote: "Se saca de una baraja, así que ninguna carta se repite",
    rock: "Piedra",
    paper: "Papel",
    scissors: "Tijera",
    youWin: "Ganaste",
    youLose: "Perdiste",
    itsDraw: "Empate",
    pickYours: "Elige tu jugada",
    record: "Marcador",
    boardSize: "Tamaño del cartón",
    freeCenter: "Casilla libre en el centro",
    newBoard: "Cartón nuevo",
    bingoCount: "Líneas completadas",
    tapToMark: "Toca una casilla para marcarla",
    weightTitle: "Elementos y pesos",
    weight: "Peso",
    chance: "Probabilidad",
    addItem: "+ Añadir elemento",
    drawWeighted: "Sacar por peso",
    weightNote: "Un peso mayor sale más a menudo. Cero nunca sale.",
    turns: "Cuántos turnos",
    perTurn: "Personas por turno",
    makeRoster: "Crear el turno",
    turnNo: "Turno",
    timesEach: "Veces cada uno",
    rosterNote: "Nadie sale dos veces antes de que todos hayan tenido su turno, ni dos veces seguidas entre rondas.",
    askIt: "Escribe tu pregunta (opcional)",
    lean: "Probabilidad de sí",
    yes: "Sí",
    no: "No",
    decide: "Decide por mí",
    leanNote: "Fíjate en cómo te sientes con la respuesta: si te decepciona, ya lo sabías.",
  },
  'pt-br': {
    drawCard: "Sacar",
    howManyCards: "Quantas",
    again: "Sacar de novo",
    deckNote: "Tiradas de um baralho, então nenhuma carta se repete",
    rock: "Pedra",
    paper: "Papel",
    scissors: "Tesoura",
    youWin: "Você venceu",
    youLose: "Você perdeu",
    itsDraw: "Empate",
    pickYours: "Escolha sua jogada",
    record: "Placar",
    boardSize: "Tamanho da cartela",
    freeCenter: "Casa livre no centro",
    newBoard: "Nova cartela",
    bingoCount: "Linhas completas",
    tapToMark: "Toque em uma casa para marcar",
    weightTitle: "Itens e pesos",
    weight: "Peso",
    chance: "Chance",
    addItem: "+ Adicionar item",
    drawWeighted: "Sortear por peso",
    weightNote: "Um peso maior sai mais vezes. Zero nunca sai.",
    turns: "Quantos turnos",
    perTurn: "Pessoas por turno",
    makeRoster: "Montar a escala",
    turnNo: "Turno",
    timesEach: "Vezes cada um",
    rosterNote: "Ninguém sai duas vezes antes de todos terem a vez, nem duas vezes seguidas entre rodadas.",
    askIt: "Escreva sua pergunta (opcional)",
    lean: "Chance de sim",
    yes: "Sim",
    no: "Não",
    decide: "Decida por mim",
    leanNote: "Repare em como você se sente com a resposta — se ficou decepcionado, você já sabia.",
  },
  ja: {
    drawCard: "カードを引く",
    howManyCards: "何枚",
    again: "もう一度引く",
    deckNote: "1組から引くので同じカードは出ません",
    rock: "グー",
    paper: "パー",
    scissors: "チョキ",
    youWin: "勝ちました",
    youLose: "負けました",
    itsDraw: "あいこです",
    pickYours: "自分の手を選んでください",
    record: "戦績",
    boardSize: "盤の大きさ",
    freeCenter: "中央をフリーにする",
    newBoard: "新しい盤",
    bingoCount: "揃った列",
    tapToMark: "マスを押して消します",
    weightTitle: "項目と重み",
    weight: "重み",
    chance: "確率",
    addItem: "+ 項目を追加",
    drawWeighted: "重みで抽選",
    weightNote: "重みが大きいほどよく出ます。0は出ません。",
    turns: "何回分",
    perTurn: "1回の人数",
    makeRoster: "当番表を作る",
    turnNo: "回",
    timesEach: "人ごとの回数",
    rosterNote: "一巡するまで同じ人は二度当たらず、巡が変わるときも連続しません。",
    askIt: "質問を書いてください（任意）",
    lean: "「はい」が出る確率",
    yes: "はい",
    no: "いいえ",
    decide: "決めて",
    leanNote: "答えが出たときの気持ちを見てください — がっかりしたなら、もう答えは分かっています。",
  },
  de: {
    drawCard: "Ziehen",
    howManyCards: "Wie viele",
    again: "Nochmal ziehen",
    deckNote: "Aus einem Deck gezogen — keine Karte wiederholt sich",
    rock: "Stein",
    paper: "Papier",
    scissors: "Schere",
    youWin: "Du gewinnst",
    youLose: "Du verlierst",
    itsDraw: "Unentschieden",
    pickYours: "Wähle deine Hand",
    record: "Bilanz",
    boardSize: "Feldgröße",
    freeCenter: "Freies Feld in der Mitte",
    newBoard: "Neues Feld",
    bingoCount: "Fertige Reihen",
    tapToMark: "Tippe ein Feld an, um es zu markieren",
    weightTitle: "Einträge und Gewichte",
    weight: "Gewicht",
    chance: "Chance",
    addItem: "+ Eintrag hinzufügen",
    drawWeighted: "Nach Gewicht ziehen",
    weightNote: "Ein größeres Gewicht wird öfter gezogen. Null nie.",
    turns: "Wie viele Runden",
    perTurn: "Personen pro Runde",
    makeRoster: "Plan erstellen",
    turnNo: "Runde",
    timesEach: "Mal je Person",
    rosterNote: "Niemand kommt zweimal dran, bevor alle einmal dran waren — auch nicht zweimal hintereinander über Runden hinweg.",
    askIt: "Schreib deine Frage (optional)",
    lean: "Wahrscheinlichkeit für Ja",
    yes: "Ja",
    no: "Nein",
    decide: "Entscheide für mich",
    leanNote: "Achte darauf, wie sich die Antwort anfühlt — wenn du enttäuscht bist, wusstest du es schon.",
  },
  fr: {
    drawCard: "Tirer",
    howManyCards: "Combien",
    again: "Retirer",
    deckNote: "Tirées d’un seul jeu : aucune carte ne se répète",
    rock: "Pierre",
    paper: "Feuille",
    scissors: "Ciseaux",
    youWin: "Vous gagnez",
    youLose: "Vous perdez",
    itsDraw: "Égalité",
    pickYours: "Choisissez votre coup",
    record: "Bilan",
    boardSize: "Taille de la grille",
    freeCenter: "Case libre au centre",
    newBoard: "Nouvelle grille",
    bingoCount: "Lignes complétées",
    tapToMark: "Touchez une case pour la marquer",
    weightTitle: "Éléments et poids",
    weight: "Poids",
    chance: "Chance",
    addItem: "+ Ajouter un élément",
    drawWeighted: "Tirer selon le poids",
    weightNote: "Un poids plus grand sort plus souvent. Zéro ne sort jamais.",
    turns: "Combien de tours",
    perTurn: "Personnes par tour",
    makeRoster: "Créer le planning",
    turnNo: "Tour",
    timesEach: "Fois par personne",
    rosterNote: "Personne ne revient deux fois avant que tout le monde soit passé, ni deux fois de suite entre les tours.",
    askIt: "Écrivez votre question (facultatif)",
    lean: "Chance de oui",
    yes: "Oui",
    no: "Non",
    decide: "Décidez pour moi",
    leanNote: "Regardez ce que vous ressentez face à la réponse : si vous êtes déçu, vous saviez déjà.",
  },
  hi: {
    drawCard: "कार्ड निकालें",
    howManyCards: "कितने",
    again: "फिर निकालें",
    deckNote: "एक ही डेक से निकाले जाते हैं, इसलिए कोई कार्ड दोहराता नहीं",
    rock: "पत्थर",
    paper: "कागज़",
    scissors: "कैंची",
    youWin: "आप जीते",
    youLose: "आप हारे",
    itsDraw: "बराबरी",
    pickYours: "अपना हाथ चुनें",
    record: "रिकॉर्ड",
    boardSize: "बोर्ड का आकार",
    freeCenter: "बीच का ख़ाना मुफ़्त",
    newBoard: "नया बोर्ड",
    bingoCount: "पूरी हुई पंक्तियाँ",
    tapToMark: "चिह्नित करने के लिए ख़ाना दबाएँ",
    weightTitle: "मद और भार",
    weight: "भार",
    chance: "संभावना",
    addItem: "+ मद जोड़ें",
    drawWeighted: "भार से निकालें",
    weightNote: "बड़ा भार अधिक बार निकलता है। शून्य कभी नहीं।",
    turns: "कितनी बारी",
    perTurn: "प्रति बारी लोग",
    makeRoster: "रोस्टर बनाएँ",
    turnNo: "बारी",
    timesEach: "प्रति व्यक्ति बार",
    rosterNote: "सबकी बारी आने से पहले कोई दोबारा नहीं आता, और चक्र बदलने पर भी लगातार दो बार नहीं।",
    askIt: "अपना प्रश्न लिखें (वैकल्पिक)",
    lean: "\"हाँ\" की संभावना",
    yes: "हाँ",
    no: "नहीं",
    decide: "मेरे लिए तय करो",
    leanNote: "देखें कि उत्तर पर आपको कैसा लगा — अगर निराशा हुई, तो आप पहले से जानते थे।",
  },
  'zh-hans': {
    drawCard: "抽牌",
    howManyCards: "几张",
    again: "再抽一次",
    deckNote: "从一副牌里抽，不会出现重复的牌",
    rock: "石头",
    paper: "布",
    scissors: "剪刀",
    youWin: "你赢了",
    youLose: "你输了",
    itsDraw: "平局",
    pickYours: "选出你的手势",
    record: "战绩",
    boardSize: "卡片大小",
    freeCenter: "中间为免费格",
    newBoard: "生成新卡片",
    bingoCount: "完成的行",
    tapToMark: "点格子来标记",
    weightTitle: "项目与权重",
    weight: "权重",
    chance: "概率",
    addItem: "+ 添加项目",
    drawWeighted: "按权重抽取",
    weightNote: "权重越大越常被抽中，0 则不会被抽中。",
    turns: "排几轮",
    perTurn: "每轮人数",
    makeRoster: "生成值日表",
    turnNo: "轮",
    timesEach: "每人次数",
    rosterNote: "在每个人都轮过之前不会有人轮两次，换轮时也不会连着两次。",
    askIt: "写下你的问题（可不填）",
    lean: "出现“是”的概率",
    yes: "是",
    no: "否",
    decide: "帮我决定",
    leanNote: "留意你对答案的反应——如果感到失望，你其实早就知道了。",
  },
  'zh-hant': {
    drawCard: "抽牌",
    howManyCards: "幾張",
    again: "再抽一次",
    deckNote: "從一副牌裡抽，不會出現重複的牌",
    rock: "石頭",
    paper: "布",
    scissors: "剪刀",
    youWin: "你贏了",
    youLose: "你輸了",
    itsDraw: "平局",
    pickYours: "選出你的手勢",
    record: "戰績",
    boardSize: "卡片大小",
    freeCenter: "中間為免費格",
    newBoard: "產生新卡片",
    bingoCount: "完成的行",
    tapToMark: "點格子來標記",
    weightTitle: "項目與權重",
    weight: "權重",
    chance: "機率",
    addItem: "+ 新增項目",
    drawWeighted: "按權重抽取",
    weightNote: "權重越大越常被抽中，0 則不會被抽中。",
    turns: "排幾輪",
    perTurn: "每輪人數",
    makeRoster: "產生值日表",
    turnNo: "輪",
    timesEach: "每人次數",
    rosterNote: "在每個人都輪過之前不會有人輪兩次，換輪時也不會連著兩次。",
    askIt: "寫下你的問題（可不填）",
    lean: "出現「是」的機率",
    yes: "是",
    no: "否",
    decide: "幫我決定",
    leanNote: "留意你對答案的反應——如果感到失望，你其實早就知道了。",
  },
};
