/* ────────────────────────────────────────────────
   사주(四柱) 영어·중국어 데이터.

   사주는 중화권에서 八字로 본토 문화라 zh 수요가 크다. 한자(甲子·乙丑…)는
   세 언어가 공유하므로 그대로 쓰고, 해석 문구만 언어별로 새로 썼다.

   영어권에는 대응 용어가 없어 통용되는 표기를 따랐다 — 天干은 Heavenly Stems,
   地支는 Earthly Branches, 十神은 Ten Gods, 大運은 Luck Pillars.

   계산(간지 산출·십성 판정·대운)은 saju-data.ts를 그대로 쓴다. 여기에는
   문구만 있고 계산은 없다 — 같은 생년월일이면 세 언어가 같은 명식을 낸다.
──────────────────────────────────────────────── */
export type SajuIntlLang = 'en' | 'zh';

/* ── 오행 ── */
export const ELEMENT_INTL: Record<SajuIntlLang, Record<string, { label: string; advice: string; shortage: string }>> = {
  en: {
    목: { label: 'Wood (木)',
      advice: 'Strong creative and growth energy. Favours new starts and challenges, and shows well in teaching and the arts.',
      shortage: 'Keep green plants nearby, or take an early morning walk. Starting something new to learn also feeds Wood.' },
    화: { label: 'Fire (火)',
      advice: 'Abundant warmth and expressiveness. Sociable and charismatic, standing out in leadership and creative work.',
      shortage: 'Wear bright, warm colours and spend more time around people. Activity toward the south lifts Fire.' },
    토: { label: 'Earth (土)',
      advice: 'Strong stability and trustworthiness. Grounded and consistent, excellent at building results that last.',
      shortage: 'Build regular habits and spend time close to the ground — gardening, hiking, anything with soil in it.' },
    금: { label: 'Metal (金)',
      advice: 'Strong resolve and principle. Analytical and determined, pursuing a high standard in whatever you take on.',
      shortage: 'Practise setting a rule and keeping it. White and silver objects help, as does turning toward the west.' },
    수: { label: 'Water (水)',
      advice: 'Outstanding wisdom and adaptability. Deep insight and tolerance that resolve complicated situations smoothly.',
      shortage: 'Reading, meditation and walks by water help. Keep blue close and spend time facing north.' },
  },
  zh: {
    목: { label: '木',
      advice: '创造力与成长能量强。适合新的开始与挑战，在教育、艺术领域尤其出色。',
      shortage: '在身边放些绿色植物，或享受清晨散步。开始学习新东西也能补木气。' },
    화: { label: '火',
      advice: '热情与表现力充沛。善社交、有气场，在领导与创作活动中容易脱颖而出。',
      shortage: '穿明亮温暖色系的衣服，多与人相处。往南方活动能助火气。' },
    토: { label: '土',
      advice: '安定感与可信度强。务实而持久，擅长做出经得起时间的成果。',
      shortage: '建立规律的生活习惯，多做与土地相近的活动 —— 种菜、爬山之类。' },
    금: { label: '金',
      advice: '决断力与原则性强。以分析性思维和坚定意志，在任何领域都追求高完成度。',
      shortage: '练习立下规则并遵守。多用白色、银色的小物，朝西方向也有帮助。' },
    수: { label: '水',
      advice: '智慧与灵活性出众。以深刻的洞察力与包容力，把复杂的局面处理得圆融。',
      shortage: '阅读、冥想、在水边散步都有帮助。多亲近蓝色，朝北方待一待。' },
  },
};

/* ── 천간 10개 ── */
interface StemIntl {
  kor: string; nature: string; personality: string;
  luckyColor: string; luckyDirection: string; aptitude: string;
}

export const STEMS_INTL: Record<SajuIntlLang, Record<string, StemIntl>> = {
  en: {
    甲: { kor: 'Jia', nature: 'Great tree, bamboo', luckyColor: 'Green · blue', luckyDirection: 'East', aptitude: 'Management · education · medicine · sport',
      personality: 'A natural leader with a pioneering streak. Like a tall tree you stand your ground and pull others along, and you are not afraid to take on something untried. The drive toward a goal runs straight and strong; cultivating the flexibility to actually hear other people is what turns that drive into larger success.' },
    乙: { kor: 'Yi', nature: 'Grass, vine', luckyColor: 'Green · yellow', luckyDirection: 'Southeast', aptitude: 'Arts · counselling · fashion · diplomacy',
      personality: 'Flexible and highly adaptable, with a talent for getting what you want through gentle means rather than force. Your relationships are numerous and your consideration for others runs deep, which is why people tend to be fond of you. Like a vine using a trellis, you are clever about making the most of the environment you are in, and you persist.' },
    丙: { kor: 'Bing', nature: 'Sun, great fire', luckyColor: 'Red · orange', luckyDirection: 'South', aptitude: 'Broadcasting · performance · sales · politics',
      personality: 'Bright and warm, the sort of presence that draws attention anywhere. Like the sun you shine openly and light up what is around you. Passion and charisma are strong, though too much certainty in your own view can create friction — considering where the other person stands matters here.' },
    丁: { kor: 'Ding', nature: 'Candle, lamplight', luckyColor: 'Red · purple', luckyDirection: 'South', aptitude: 'Research · design · writing · religion',
      personality: 'A quieter, more focused flame. You warm the people close to you rather than the whole room, and your attention goes deep rather than wide. Sensitive to detail and to atmosphere, with an inner intensity that is easy to miss from the outside.' },
    戊: { kor: 'Wu', nature: 'Mountain, great earth', luckyColor: 'Yellow · brown', luckyDirection: 'Centre', aptitude: 'Property · construction · finance · administration',
      personality: 'Solid and dependable, the person others lean on. You are not easily moved, which is a strength in a crisis and a liability when circumstances genuinely call for change. Trust accumulates around you over time rather than arriving quickly.' },
    己: { kor: 'Ji', nature: 'Field, soft earth', luckyColor: 'Yellow · beige', luckyDirection: 'Centre', aptitude: 'Agriculture · nursing · service · accounting',
      personality: 'Accommodating and nurturing, the kind of ground that lets other things grow. You adapt to what is needed rather than imposing a shape, which makes you easy to work with. Watch that accommodating everyone does not leave your own needs last.' },
    庚: { kor: 'Geng', nature: 'Sword, raw metal', luckyColor: 'White · silver', luckyDirection: 'West', aptitude: 'Military · law · engineering · surgery',
      personality: 'Decisive and direct, with a clean sense of right and wrong. You cut through rather than work around, which is efficient and occasionally sharp. Principle matters more to you than comfort, and people know where they stand with you.' },
    辛: { kor: 'Xin', nature: 'Jewel, refined metal', luckyColor: 'White · gold', luckyDirection: 'West', aptitude: 'Jewellery · beauty · precision work · criticism',
      personality: 'Refined and exacting, with a strong aesthetic sense. You notice what is slightly off in a way most people do not, and you hold a high standard for yourself first. That precision reads as elegance when it is turned outward and as harshness when it is turned inward.' },
    壬: { kor: 'Ren', nature: 'Ocean, great water', luckyColor: 'Black · blue', luckyDirection: 'North', aptitude: 'Trade · logistics · travel · media',
      personality: 'Wide-ranging and hard to contain, with a mind that moves easily across subjects. You take in a great deal and connect things others keep separate. The risk is spreading thin — depth needs deliberate choosing when breadth comes this naturally.' },
    癸: { kor: 'Gui', nature: 'Rain, dew', luckyColor: 'Black · grey', luckyDirection: 'North', aptitude: 'Research · counselling · medicine · the occult',
      personality: 'Quiet, perceptive and patient. You work by seeping in rather than pushing, and you notice what goes unsaid. There is real endurance here that is easy to underestimate, including by yourself.' },
  },
  zh: {
    甲: { kor: '甲', nature: '大树·竹', luckyColor: '绿·蓝', luckyDirection: '东', aptitude: '经营·教育·医疗·体育',
      personality: '天生带着领导力与开拓精神。像大树一样堂堂站住，有带动周围的力量，也不怕挑战新东西。朝目标笔直推进的劲头很足；若能再培养倾听他人意见的柔软，成就会更大。' },
    乙: { kor: '乙', nature: '草·藤', luckyColor: '绿·黄', luckyDirection: '东南', aptitude: '艺术·咨询·时尚·外交',
      personality: '灵活、适应力强，擅长用柔和的方式达成想要的结果。人际丰富、体贴入微，很受周围人喜欢。像藤蔓顺着支架往上长一样，懂得善用环境，也很有韧性。' },
    丙: { kor: '丙', nature: '太阳·大火', luckyColor: '红·橙', luckyDirection: '南', aptitude: '传媒·表演·销售·政治',
      personality: '性格明亮温暖，走到哪里都受注目。像太阳一样堂堂发光，把周围照亮，能量充沛。热情与气场都很强，但过度的自我确信有时会引起摩擦，多体谅对方的立场很重要。' },
    丁: { kor: '丁', nature: '烛火·灯光', luckyColor: '红·紫', luckyDirection: '南', aptitude: '研究·设计·写作·宗教',
      personality: '是更安静、更聚焦的一簇火。温暖的是身边的人而不是整个场子，注意力偏深而不偏广。对细节和氛围敏感，内里有一股从外面不容易看出来的强度。' },
    戊: { kor: '戊', nature: '山·大地', luckyColor: '黄·褐', luckyDirection: '中', aptitude: '房地产·建筑·金融·行政',
      personality: '扎实可靠，是别人可以倚靠的那一个。不容易被撼动 —— 危机时是优点，真正需要改变时则可能成为负担。别人对你的信任是慢慢累积起来的，而不是一下子给的。' },
    己: { kor: '己', nature: '田地·软土', luckyColor: '黄·米', luckyDirection: '中', aptitude: '农业·护理·服务·会计',
      personality: '包容而滋养，像能让别的东西生长的那片土。你会顺着需要去调整，而不是硬要塑形，所以很好相处。要留意的是：照顾所有人，别把自己的需要放到最后。' },
    庚: { kor: '庚', nature: '刀剑·原矿', luckyColor: '白·银', luckyDirection: '西', aptitude: '军警·法律·工程·外科',
      personality: '果断直接，是非分明。你会直接切开，而不是绕过去 —— 效率高，偶尔也锋利。原则对你比舒适更重要，别人很清楚你的立场在哪。' },
    辛: { kor: '辛', nature: '珠宝·精炼金属', luckyColor: '白·金', luckyDirection: '西', aptitude: '珠宝·美妆·精密工艺·评论',
      personality: '精致而讲究，审美感强。你能注意到别人察觉不到的那点不对劲，而且对自己的标准最高。这份精准向外时读作优雅，向内时则容易变成苛刻。' },
    壬: { kor: '壬', nature: '大海·大水', luckyColor: '黑·蓝', luckyDirection: '北', aptitude: '贸易·物流·旅行·媒体',
      personality: '格局开阔、难以被框住，思维在不同题目之间移动得很轻松。你吸收得多，也能把别人分开看的东西连起来。风险是摊得太薄 —— 广度来得这么自然的时候，深度需要刻意去选。' },
    癸: { kor: '癸', nature: '雨·露', luckyColor: '黑·灰', luckyDirection: '北', aptitude: '研究·咨询·医疗·玄学',
      personality: '安静、敏锐、有耐性。你靠渗透而不是推挤来做事，也会注意到没被说出口的东西。这里有一种很容易被低估的耐力 —— 连你自己也常常低估。' },
  },
};

/* ── 지지 12개 ── */
export const BRANCHES_INTL: Record<SajuIntlLang, Record<string, { kor: string; animal: string; season: string }>> = {
  en: {
    子: { kor: 'Zi', animal: 'Rat', season: 'Winter' },
    丑: { kor: 'Chou', animal: 'Ox', season: 'Winter' },
    寅: { kor: 'Yin', animal: 'Tiger', season: 'Spring' },
    卯: { kor: 'Mao', animal: 'Rabbit', season: 'Spring' },
    辰: { kor: 'Chen', animal: 'Dragon', season: 'Spring' },
    巳: { kor: 'Si', animal: 'Snake', season: 'Summer' },
    午: { kor: 'Wu', animal: 'Horse', season: 'Summer' },
    未: { kor: 'Wei', animal: 'Goat', season: 'Summer' },
    申: { kor: 'Shen', animal: 'Monkey', season: 'Autumn' },
    酉: { kor: 'You', animal: 'Rooster', season: 'Autumn' },
    戌: { kor: 'Xu', animal: 'Dog', season: 'Autumn' },
    亥: { kor: 'Hai', animal: 'Pig', season: 'Winter' },
  },
  zh: {
    子: { kor: '子', animal: '鼠', season: '冬' },
    丑: { kor: '丑', animal: '牛', season: '冬' },
    寅: { kor: '寅', animal: '虎', season: '春' },
    卯: { kor: '卯', animal: '兔', season: '春' },
    辰: { kor: '辰', animal: '龙', season: '春' },
    巳: { kor: '巳', animal: '蛇', season: '夏' },
    午: { kor: '午', animal: '马', season: '夏' },
    未: { kor: '未', animal: '羊', season: '夏' },
    申: { kor: '申', animal: '猴', season: '秋' },
    酉: { kor: '酉', animal: '鸡', season: '秋' },
    戌: { kor: '戌', animal: '狗', season: '秋' },
    亥: { kor: '亥', animal: '猪', season: '冬' },
  },
};

/* ── 십성 10개 ── */
interface SipseongIntl {
  name: string; summary: string; category: string;
  male: string; female: string; career: string; wealth: string;
}

export const SIPSEONG_INTL: Record<SajuIntlLang, Record<string, SipseongIntl>> = {
  en: {
    비견: { name: 'Friend (比肩)', summary: 'Independence · competition', category: 'Self',
      male: 'The star of siblings and peers. Strong independence and high self-regard. The instinct to solve everything alone can push people away without meaning to.',
      female: 'The star of sisters, friends and same-sex rivals. Self-reliant, walking your own road. Partnership luck can weaken, but redirecting that energy into a career turns it into a strength.',
      career: 'Favours independent business, freelancing and the professions. You shine where you decide and execute alone.',
      wealth: 'Money comes and goes in swings. Sole operation is safer than partnership or joint investment.' },
    겁재: { name: 'Rob Wealth (劫財)', summary: 'Struggle · breakthrough', category: 'Self',
      male: 'The star of competition. Considerable drive and a willingness to take risk, with a tendency to push through where others would wait.',
      female: 'Strong competitive energy. Effective in contested environments, though it can strain close relationships if left unchecked.',
      career: 'Suits sales, sport, and anywhere performance is measured directly against others.',
      wealth: 'Income can be substantial but is rarely steady. Guard against lending and against decisions made in haste.' },
    식신: { name: 'Eating God (食神)', summary: 'Expression · enjoyment', category: 'Output',
      male: 'The star of ease and appetite. Generous, unhurried, and good at enjoying what is in front of you.',
      female: 'The star of children and of creative output. Warm and nurturing, with a natural talent for making things pleasant.',
      career: 'Favours food, hospitality, the arts, and anything that involves making something people enjoy.',
      wealth: 'Money arrives steadily rather than dramatically. Comfort matters more to you than accumulation.' },
    상관: { name: 'Hurting Officer (傷官)', summary: 'Talent · rebellion', category: 'Output',
      male: 'The star of sharp talent. Quick, articulate and impatient with authority that has not earned it.',
      female: 'Strong self-expression and a low tolerance for constraint. Brilliant in the right setting, restless in the wrong one.',
      career: 'Suits performance, criticism, design and any field where originality outweighs conformity.',
      wealth: 'Earnings track your output directly. The variable to manage is consistency, not capability.' },
    편재: { name: 'Indirect Wealth (偏財)', summary: 'Opportunity · circulation', category: 'Wealth',
      male: 'The star of movable money and of wide social range. Generous with what you have and quick to spot an opening.',
      female: 'Resourceful and outward-facing, with money that moves rather than sits.',
      career: 'Favours trade, investment, sales and anything with a deal in it.',
      wealth: 'Large sums can arrive and leave quickly. Setting aside a fixed portion before spending is the useful discipline.' },
    정재: { name: 'Direct Wealth (正財)', summary: 'Stability · accumulation', category: 'Wealth',
      male: 'The star of steady income and, traditionally, of the spouse. Careful with money and reliable with commitments.',
      female: 'Practical and grounded about resources, building rather than gambling.',
      career: 'Suits accounting, administration, and salaried work with clear structure.',
      wealth: 'Accumulates slowly and holds. Your risk is being too cautious to take a worthwhile opening.' },
    편관: { name: 'Seven Killings (偏官)', summary: 'Pressure · decisiveness', category: 'Authority',
      male: 'The star of challenge and command. Performs under pressure, sometimes seeks it out.',
      female: 'Traditionally read as the star of a demanding partner or of authority. Considerable resilience under strain.',
      career: 'Favours the military, law enforcement, surgery, and crisis-facing roles.',
      wealth: 'Income tied to responsibility taken on. Rises with the weight you are willing to carry.' },
    정관: { name: 'Direct Officer (正官)', summary: 'Order · responsibility', category: 'Authority',
      male: 'The star of position and propriety. Reliable, rule-respecting and trusted with responsibility.',
      female: 'Traditionally the star of the husband and of social standing. Composed and well regarded.',
      career: 'Suits public service, large organisations and any structured hierarchy.',
      wealth: 'Steady and predictable. Growth comes through position rather than through risk.' },
    편인: { name: 'Indirect Resource (偏印)', summary: 'Insight · the unconventional', category: 'Resource',
      male: 'The star of unusual knowledge. Draws on sources others overlook, and thinks sideways.',
      female: 'Intuitive and drawn to the unorthodox, with real depth in specialised subjects.',
      career: 'Favours research, technical specialisation, medicine and the metaphysical.',
      wealth: 'Money follows expertise rather than effort. Narrow and deep pays better than broad here.' },
    정인: { name: 'Direct Resource (正印)', summary: 'Learning · protection', category: 'Resource',
      male: 'The star of study and of the mother. Supported, well-taught and inclined toward knowledge.',
      female: 'Nurturing and studious, with steady support from those above you.',
      career: 'Suits education, publishing, research and the caring professions.',
      wealth: 'Comfortable rather than large. Support tends to arrive when it is needed.' },
  },
  zh: {
    비견: { name: '比肩', summary: '自立·竞争', category: '比劫',
      male: '兄弟朋友之星。独立心强、自尊心高。凡事想自己解决的倾向，有时会无意间把周围的人推开。',
      female: '姐妹、朋友与同性对手之星。自立性强，走自己的路。配偶运可能偏弱，但把这股能量转到事业上就成了长处。',
      career: '适合独立创业、自由职业与专业职。在自己决定、自己执行的环境里最能发光。',
      wealth: '财来财去起伏较大。比起合伙或共同投资，单独经营更稳妥。' },
    겁재: { name: '劫财', summary: '争取·突破', category: '比劫',
      male: '竞争之星。冲劲足、敢冒险，在别人还在观望时就已经推进了。',
      female: '竞争能量强。在需要比拼的环境里很有效，但不加节制会消耗亲近的关系。',
      career: '适合销售、体育，以及任何直接以业绩与他人比较的领域。',
      wealth: '收入可能可观，但少有稳定。留意借贷，也留意仓促之间做的决定。' },
    식신: { name: '食神', summary: '表达·享受', category: '食伤',
      male: '从容与口福之星。大方、不急躁，很会享受眼前的东西。',
      female: '子女与创作产出之星。温暖有滋养力，天生擅长把事情弄得舒服宜人。',
      career: '适合餐饮、款待、艺术，以及一切「做出让人享受的东西」的行业。',
      wealth: '财来得稳而不猛。比起累积，你更在意过得舒服。' },
    상관: { name: '伤官', summary: '才华·叛逆', category: '食伤',
      male: '锋利才华之星。反应快、口才好，对没有实力支撑的权威缺乏耐心。',
      female: '自我表达强烈，对束缚容忍度低。在对的地方光芒四射，在错的地方坐立难安。',
      career: '适合表演、评论、设计，以及任何原创性重于顺从的领域。',
      wealth: '收入与产出直接挂钩。要管理的是稳定性，而不是能力。' },
    편재: { name: '偏财', summary: '机会·流动', category: '财星',
      male: '活钱与广泛人脉之星。对拥有的东西大方，也很快能看出机会在哪。',
      female: '资源灵活、面向外部，钱是流动的而不是沉淀的。',
      career: '适合贸易、投资、销售，以及一切带着「谈成一笔」性质的事。',
      wealth: '大额可能来得快也去得快。花之前先固定拨出一部分，是有用的纪律。' },
    정재: { name: '正财', summary: '安定·积累', category: '财星',
      male: '稳定收入之星，传统上也是配偶之星。用钱谨慎，承诺可靠。',
      female: '对资源务实踏实，是在建造而不是在赌。',
      career: '适合会计、行政，以及结构清晰的受薪工作。',
      wealth: '慢慢积累且守得住。风险在于过于谨慎，错过值得的机会。' },
    편관: { name: '七杀', summary: '压力·果断', category: '官星',
      male: '挑战与统率之星。在压力下表现好，有时甚至主动去找压力。',
      female: '传统上读作要求较高的伴侣之星，或权威之星。承压的韧性相当强。',
      career: '适合军警、执法、外科，以及直面危机的岗位。',
      wealth: '收入与承担的责任绑在一起。你愿意扛多重，它就往上走多少。' },
    정관: { name: '正官', summary: '秩序·责任', category: '官星',
      male: '地位与规矩之星。可靠、守规则，被托付责任。',
      female: '传统上是丈夫之星与社会地位之星。沉稳而受人敬重。',
      career: '适合公职、大型组织，以及层级清晰的体系。',
      wealth: '稳定可预期。增长来自位置，而不是来自冒险。' },
    편인: { name: '偏印', summary: '洞察·非主流', category: '印星',
      male: '偏门学问之星。会去别人忽略的地方取材，思路是横向的。',
      female: '直觉强、被非正统的东西吸引，在专门题目上有真正的深度。',
      career: '适合研究、技术专精、医疗与玄学。',
      wealth: '财随专业而来，而不是随辛苦而来。窄而深比广而浅更划算。' },
    정인: { name: '正印', summary: '学习·庇护', category: '印星',
      male: '学业与母亲之星。得到支持、受过好的教导，倾向于求知。',
      female: '有滋养力且好学，长辈的支持相对稳定。',
      career: '适合教育、出版、研究与照护类职业。',
      wealth: '够用而不至于大富。需要的时候，支援往往会到。' },
  },
};

/* ── UI 문구 ── */
export const SAJU_UI: Record<SajuIntlLang, Record<string, string>> = {
  en: {
    title: 'Saju — Korean Four Pillars',
    lead: 'Your four pillars from date and time of birth, read the way saju is read in Korea',
    birthLabel: 'Date of birth',
    yearPh: 'e.g. 1995', monthPh: 'Month', dayPh: 'Day',
    hourLabel: 'Hour of birth', hourUnknown: 'Not known',
    genderLabel: 'Gender', male: 'Male', female: 'Female',
    submit: 'Read my chart',
    empty: 'Enter your birth details to see your chart',
    chart: 'Four Pillars',
    yearPillar: 'Year', monthPillar: 'Month', dayPillar: 'Day', hourPillar: 'Hour',
    dayMaster: 'Day Master',
    elements: 'Five Elements',
    missing: 'Missing elements',
    tenGods: 'Ten Gods',
    luckPillars: 'Luck Pillars',
    age: 'Age',
    strong: 'Strong Day Master', weak: 'Weak Day Master',
    strongNote: 'Your Day Master has ample support. Elements that drain or control it tend to help.',
    weakNote: 'Your Day Master has limited support. Elements that generate or reinforce it tend to help.',
    inCareer: 'Career', inWealth: 'Wealth',
    hourNote: 'Without the hour, the Hour Pillar is omitted — the rest of the chart is unaffected.',
    errAll: 'Please fill in the full date of birth.',
    errMonth: 'Month must be between 1 and 12.',
    errDay: 'Day must be between 1 and 31.',
    errInvalid: 'That date does not exist.',
    errFuture: 'Your date of birth is in the future.',
    originNote: 'Saju (사주) is how four-pillar astrology is practised in Korea. The system itself came from China, where it is known as BaZi (八字), and the two share the same sexagenary calculation — the reading conventions and vocabulary differ.',
    disclaimer: 'The chart itself is calculated from the traditional sexagenary cycle and is deterministic — the same birth details always give the same pillars. The interpretations attached to it are a traditional practice, not a scientific one. Treat it as reflection rather than prediction.',
  },
  zh: {
    title: '八字排盘',
    lead: '由出生年月日时排出四柱，并看五行分布',
    birthLabel: '出生日期',
    yearPh: '例) 1995', monthPh: '月', dayPh: '日',
    hourLabel: '出生时辰', hourUnknown: '不详',
    genderLabel: '性别', male: '男', female: '女',
    submit: '排盘',
    empty: '填写出生信息即可排盘',
    chart: '四柱',
    yearPillar: '年柱', monthPillar: '月柱', dayPillar: '日柱', hourPillar: '时柱',
    dayMaster: '日主',
    elements: '五行',
    missing: '缺失的五行',
    tenGods: '十神',
    luckPillars: '大运',
    age: '岁',
    strong: '日主偏强', weak: '日主偏弱',
    strongNote: '日主得到的助力充足。泄耗与克制日主的五行通常有帮助。',
    weakNote: '日主得到的助力有限。生扶日主的五行通常有帮助。',
    inCareer: '事业', inWealth: '财运',
    hourNote: '不填时辰则不排时柱 —— 其余部分不受影响。',
    errAll: '请填写完整的出生日期。',
    errMonth: '月份请填 1~12 之间。',
    errDay: '日期请填 1~31 之间。',
    errInvalid: '该日期不存在。',
    errFuture: '出生日期晚于今天。',
    originNote: '八字在韩国称为「四柱（사주）」，用的是同一套干支推算，只是解读的习惯与用语有些不同。',
    disclaimer: '排盘本身按传统干支纪年法计算，是确定的 —— 同样的出生信息永远得到同样的四柱。附在上面的解读属于传统术数，而非科学。请当作自省而不是预言。',
  },
};
