/**
 * 슬라이딩 퍼즐 화면의 열 언어 문구.
 *
 * lib/game-ui-intl.ts는 이미 1,400줄이고 lib/game-more-ui.ts는 게임 여섯이 한
 * 인터페이스를 나눠 쓰고 있다. 거기에 칸을 더하면 열 언어 × 여섯 게임이 함께
 * 흔들리므로, 2048·지뢰찾기처럼 이 게임의 사전도 따로 둔다.
 *
 * 판에는 숫자만 있어 옮길 낱말이 하나도 없다 — 번역할 것은 화면 문구뿐이다.
 * 판 크기(3×3·4×4·5×5)도 어느 언어에서나 그대로 읽히므로 사전에 넣지 않고
 * 컴포넌트가 숫자로 만든다.
 *
 * 값이 전부 문자열이라 검사가 열쇠를 훑어 "비었다·한국어 그대로다·남의 언어
 * 글자가 섞였다"를 한 번에 볼 수 있다. 이 화면에는 **이모지를 쓰지 않는다.**
 */
import type { GameLang } from './game-ui-intl.ts';

/** 검사가 훑는 열쇠 목록 — 여기 없는 열쇠는 언어별 빠짐을 아무도 못 본다 */
export const SLIDING_UI_KEYS = [
  'how', 'pushHint',
  'moves', 'time', 'best', 'left', 'size',
  'shuffle', 'undo', 'solved',
  'boardLabel', 'tile', 'blank',
  'note', 'distanceNote',
] as const;

export type SlidingUiKey = (typeof SLIDING_UI_KEYS)[number];
export type SlidingUi = Record<SlidingUiKey, string>;

export const SLIDING_UI: Record<GameLang, SlidingUi> = {
  ko: {
    how: '빈 칸과 맞닿은 칸을 눌러 옮기세요',
    pushHint: '빈 칸과 같은 줄에 있는 먼 칸을 누르면 사이의 칸이 한꺼번에 밀립니다',
    moves: '움직인 칸',
    time: '경과 시간',
    best: '최고 기록',
    left: '남은 거리',
    size: '판 크기',
    shuffle: '다시 섞기',
    undo: '한 칸 되돌리기',
    solved: '다 맞췄습니다',
    boardLabel: '슬라이딩 퍼즐 판',
    tile: '칸',
    blank: '빈 칸',
    note: '숫자를 왼쪽 위부터 차례로 놓고 빈 칸을 맨 끝에 두면 끝납니다. 이 퍼즐은 늘어놓는 방법의 절반이 아무리 옮겨도 완성되지 않기 때문에, 섞을 때마다 풀 수 있는 판인지 먼저 셈해 보고 아니면 두 칸을 맞바꿔 고칩니다. 그래서 여기서 나오는 판은 언제나 풀립니다.',
    distanceNote: '남은 거리는 칸마다 제자리까지 가야 하는 걸음을 더한 값입니다. 한 번 옮길 때 1만 바뀌므로 그 값보다 적게 옮겨서는 끝낼 수 없습니다 — 최소 움직임의 하한입니다.',
  },
  en: {
    how: 'Tap any tile touching the empty square to slide it',
    pushHint: 'Tap a tile further along the same row or column and the whole run slides at once',
    moves: 'Moves',
    time: 'Time',
    best: 'Best',
    left: 'Distance left',
    size: 'Board size',
    shuffle: 'Shuffle again',
    undo: 'Undo one move',
    solved: 'Solved',
    boardLabel: 'Sliding puzzle board',
    tile: 'Tile',
    blank: 'Empty square',
    note: 'Put the numbers in order from the top left and leave the empty square at the end. Half of all arrangements of this puzzle can never be finished no matter how you slide, so every shuffle here is checked first and repaired by swapping two tiles when it fails. Every board you are given is solvable.',
    distanceNote: 'Distance left adds up how many steps each tile still has to travel to reach its home square. One slide changes it by exactly one, so you can never finish in fewer moves than that number — it is a lower bound.',
  },
  es: {
    how: 'Toca una casilla pegada al hueco para deslizarla',
    pushHint: 'Toca una casilla más lejana de la misma fila o columna y se desliza toda la hilera de golpe',
    moves: 'Movimientos',
    time: 'Tiempo',
    best: 'Mejor',
    left: 'Distancia restante',
    size: 'Tamaño del tablero',
    shuffle: 'Volver a mezclar',
    undo: 'Deshacer un movimiento',
    solved: 'Resuelto',
    boardLabel: 'Tablero del puzle deslizante',
    tile: 'Casilla',
    blank: 'Hueco',
    note: 'Coloca los números en orden desde arriba a la izquierda y deja el hueco al final. La mitad de las posiciones de este puzle no se pueden terminar por mucho que deslices, así que cada mezcla se comprueba antes y, si no vale, se arregla intercambiando dos casillas. El tablero que te sale aquí siempre tiene solución.',
    distanceNote: 'La distancia restante suma los pasos que le faltan a cada casilla para llegar a su sitio. Un deslizamiento la cambia justo en uno, así que nunca podrás acabar con menos movimientos que ese número: es una cota inferior.',
  },
  'pt-br': {
    how: 'Toque em uma peça encostada no espaço vazio para deslizá-la',
    pushHint: 'Toque em uma peça mais longe na mesma linha ou coluna e a fileira inteira desliza de uma vez',
    moves: 'Jogadas',
    time: 'Tempo',
    best: 'Melhor',
    left: 'Distância restante',
    size: 'Tamanho do tabuleiro',
    shuffle: 'Embaralhar de novo',
    undo: 'Desfazer uma jogada',
    solved: 'Resolvido',
    boardLabel: 'Tabuleiro do quebra-cabeça deslizante',
    tile: 'Peça',
    blank: 'Espaço vazio',
    note: 'Coloque os números em ordem a partir do canto superior esquerdo e deixe o espaço vazio no fim. Metade das posições deste quebra-cabeça não pode ser terminada, não importa quanto você deslize, então cada embaralhada é conferida antes e, quando não serve, é corrigida trocando duas peças. O tabuleiro que aparece aqui sempre tem solução.',
    distanceNote: 'A distância restante soma quantos passos cada peça ainda precisa dar até o lugar dela. Uma jogada muda esse número em exatamente um, então não dá para terminar com menos jogadas do que ele — é um limite inferior.',
  },
  ja: {
    how: '空きマスに接しているマスを押して動かします',
    pushHint: '空きマスと同じ列や行の離れたマスを押すと、間のマスがまとめて動きます',
    moves: '手数',
    time: '経過時間',
    best: '最高記録',
    left: '残り距離',
    size: '盤の大きさ',
    shuffle: 'もう一度混ぜる',
    undo: '一手戻す',
    solved: '完成しました',
    boardLabel: 'スライドパズルの盤',
    tile: 'マス',
    blank: '空きマス',
    note: '左上から順に数字を並べ、空きマスを最後に置けば完成です。このパズルは並べ方の半分がどう動かしても完成しないので、混ぜるたびに解けるかを先に確かめ、だめなら二つのマスを入れ替えて直します。ここで出る盤は必ず解けます。',
    distanceNote: '残り距離は、それぞれのマスが本来の位置まで進む歩数の合計です。一手で1しか変わらないので、その数より少ない手数では終われません — 最小手数の下限です。',
  },
  de: {
    how: 'Tippe ein Feld an, das an die Lücke grenzt, um es zu schieben',
    pushHint: 'Tippe ein weiter entferntes Feld in derselben Reihe oder Spalte an, dann rutscht die ganze Reihe auf einmal',
    moves: 'Züge',
    time: 'Zeit',
    best: 'Bestwert',
    left: 'Restdistanz',
    size: 'Brettgröße',
    shuffle: 'Neu mischen',
    undo: 'Einen Zug zurück',
    solved: 'Gelöst',
    boardLabel: 'Schiebepuzzle-Brett',
    tile: 'Feld',
    blank: 'Lücke',
    note: 'Lege die Zahlen von links oben der Reihe nach ab und lass die Lücke am Ende. Bei der Hälfte aller Stellungen dieses Puzzles kommt man durch Schieben nie ans Ziel, deshalb wird jede Mischung vorher geprüft und bei Bedarf durch Tauschen zweier Felder in Ordnung gebracht. Jedes Brett, das du hier bekommst, ist lösbar.',
    distanceNote: 'Die Restdistanz addiert, wie viele Schritte jedes Feld noch bis zu seinem Platz braucht. Ein Zug ändert sie um genau eins, du kannst also nie mit weniger Zügen fertig werden als diese Zahl — sie ist eine untere Grenze.',
  },
  fr: {
    how: 'Touche une case qui touche le trou pour la faire glisser',
    pushHint: 'Touche une case plus loin sur la même ligne ou colonne et toute la rangée glisse d’un coup',
    moves: 'Coups',
    time: 'Temps',
    best: 'Meilleur',
    left: 'Distance restante',
    size: 'Taille du plateau',
    shuffle: 'Mélanger encore',
    undo: 'Annuler un coup',
    solved: 'Résolu',
    boardLabel: 'Plateau du jeu de taquin',
    tile: 'Case',
    blank: 'Trou',
    note: 'Remets les nombres dans l’ordre depuis le coin en haut à gauche et laisse le trou à la fin. La moitié des positions de ce casse-tête ne peut jamais être terminée, quoi que tu fasses glisser : chaque mélange est donc vérifié avant, et corrigé en échangeant deux cases s’il ne convient pas. Le plateau que tu reçois ici a toujours une solution.',
    distanceNote: 'La distance restante additionne les pas qu’il manque à chaque case pour rejoindre sa place. Un coup la change d’exactement un, donc tu ne peux jamais finir en moins de coups que ce nombre : c’est une borne inférieure.',
  },
  hi: {
    how: 'खाली जगह से सटे किसी ख़ाने को दबाकर सरकाएँ',
    pushHint: 'उसी पंक्ति या स्तंभ में दूर वाला ख़ाना दबाएँ तो बीच के सारे ख़ाने एक साथ सरक जाते हैं',
    moves: 'चालें',
    time: 'बीता समय',
    best: 'सर्वोत्तम',
    left: 'बची दूरी',
    size: 'बोर्ड का आकार',
    shuffle: 'फिर से मिलाएँ',
    undo: 'एक चाल पीछे',
    solved: 'हल हो गया',
    boardLabel: 'सरकाने वाली पहेली का बोर्ड',
    tile: 'ख़ाना',
    blank: 'खाली जगह',
    note: 'ऊपर बाएँ से क्रम में अंक जमाएँ और खाली जगह आख़िर में छोड़ें। इस पहेली की आधी सजावटें कितना भी सरकाने पर पूरी नहीं होतीं, इसलिए हर बार मिलाने के बाद पहले जाँचा जाता है और ज़रूरत पड़े तो दो ख़ाने बदलकर सुधार दिया जाता है। यहाँ जो बोर्ड मिलता है वह हमेशा हल हो सकता है।',
    distanceNote: 'बची दूरी हर ख़ाने के अपनी जगह तक पहुँचने के क़दमों का जोड़ है। एक चाल में यह ठीक एक बदलती है, इसलिए इस संख्या से कम चालों में खेल ख़त्म नहीं हो सकता — यही न्यूनतम चालों की निचली सीमा है।',
  },
  'zh-hans': {
    how: '点与空格相邻的方块就能推动',
    pushHint: '点同一行或同一列上更远的方块，中间的几个会一起被推过去',
    moves: '步数',
    time: '用时',
    best: '最好成绩',
    left: '剩余距离',
    size: '盘面大小',
    shuffle: '重新打乱',
    undo: '退回一步',
    solved: '完成了',
    boardLabel: '数字华容道盘面',
    tile: '方块',
    blank: '空格',
    note: '把数字从左上角按顺序排好，空格留在最后就算完成。这个拼图有一半的排法无论怎么推都拼不出来，所以每次打乱都会先算一遍能不能解，不能解就交换两个方块修好。这里给你的盘面一定能解。',
    distanceNote: '剩余距离是把每个方块还要走多少格才回到自己位置全部加起来。推一步只会让它变化 1，所以步数不可能少于这个数 — 它就是最少步数的下限。',
  },
  'zh-hant': {
    how: '點與空格相鄰的方塊就能推動',
    pushHint: '點同一行或同一列上更遠的方塊，中間的幾個會一起被推過去',
    moves: '步數',
    time: '用時',
    best: '最好成績',
    left: '剩餘距離',
    size: '盤面大小',
    shuffle: '重新打亂',
    undo: '退回一步',
    solved: '完成了',
    boardLabel: '數字華容道盤面',
    tile: '方塊',
    blank: '空格',
    note: '把數字從左上角按順序排好，空格留在最後就算完成。這個拼圖有一半的排法無論怎麼推都拼不出來，所以每次打亂都會先算一遍能不能解，不能解就交換兩個方塊修好。這裡給你的盤面一定能解。',
    distanceNote: '剩餘距離是把每個方塊還要走多少格才回到自己位置全部加起來。推一步只會讓它變化 1，所以步數不可能少於這個數 — 它就是最少步數的下限。',
  },
};
