/**
 * 스도쿠 화면 문구의 열 언어 사전.
 *
 * lib/game-ui-intl.ts는 이미 1,400줄이고 lib/game-more-ui.ts는 게임 여섯이 한
 * 인터페이스를 나눠 쓴다 — 거기에 칸을 더하면 열 언어 × 여섯 게임이 함께
 * 흔들린다. 셈을 lib/sudoku.ts로 가른 것과 같은 이유로 사전도 따로 둔다.
 *
 * 스도쿠는 판에 숫자만 있어서 옮길 것이 화면 문구뿐이다. 그래서 사전이 작다.
 *
 * ── 값이 전부 문자열인 이유 ──────────────────────────────
 * 숫자를 끼우는 자리를 함수로 두면 검사가 그 문장을 읽을 수 없다. 여기서는
 * {v}(수)·{r}(행)·{c}(열)·{n}(단위 번호)를 문자열에 박아 두고 화면에서 바꿔
 * 끼운다. 그러면 검사가 열쇠를 훑어 "비었다·영어 그대로다·남의 언어 글자가
 * 섞였다"를 한 번에 볼 수 있다.
 */
import type { GameLang } from './game-ui-intl.ts';

/** 검사가 훑는 열쇠 목록 — 여기 없는 열쇠는 언어별 빠짐을 아무도 못 본다 */
export const SUDOKU_UI_KEYS = [
  'level_easy', 'level_normal', 'level_hard',
  'time', 'bestTime', 'blanks', 'puzzleNo',
  'newGame', 'hint', 'undo', 'notes', 'erase',
  'won', 'newBest',
  'hintNaked', 'hintRow', 'hintCol', 'hintBox', 'hintNone',
  'conflict', 'how', 'note', 'boardLabel', 'cellLabel',
] as const;

export type SudokuUiKey = (typeof SUDOKU_UI_KEYS)[number];
export type SudokuUi = Record<SudokuUiKey, string>;

/** 자리를 바꿔 끼운다 — {v}·{r}·{c}·{n} */
export function fillSlots(text: string, slots: Record<string, string | number>): string {
  return text.replace(/\{(\w+)\}/g, (whole, key) => (key in slots ? String(slots[key]) : whole));
}

export const SUDOKU_UI: Record<GameLang, SudokuUi> = {
  ko: {
    level_easy: '쉬움',
    level_normal: '보통',
    level_hard: '어려움',
    time: '경과 시간',
    bestTime: '최고 기록',
    blanks: '남은 칸',
    puzzleNo: '문제 번호',
    newGame: '새 문제',
    hint: '힌트',
    undo: '되돌리기',
    notes: '메모',
    erase: '지우기',
    won: '다 풀었습니다',
    newBest: '최고 기록입니다',
    hintNaked: '{r}행 {c}열에는 {v}만 들어갑니다 — 나머지 여덟 수가 같은 가로줄·세로줄·상자에 이미 있습니다.',
    hintRow: '{n}행에서 {v}가 들어갈 자리는 {c}열 하나뿐입니다.',
    hintCol: '{n}열에서 {v}가 들어갈 자리는 {r}행 하나뿐입니다.',
    hintBox: '왼쪽 위에서 {n}번째 3×3 상자에서 {v}가 들어갈 자리는 {r}행 {c}열 하나뿐입니다.',
    hintNone: '지금 판에서 확실히 채울 수 있는 칸이 없습니다 — 여기서부터는 두 갈래를 따져 봐야 합니다.',
    conflict: '빨간 칸은 같은 가로줄·세로줄·상자에 같은 수가 또 있는 자리입니다.',
    how: '칸을 누르고 1~9를 고르세요. 키보드는 화살표로 옮기고 숫자로 채우며, 0이나 백스페이스로 지웁니다.',
    note: '문제는 완성판에서 한 칸씩 지우면서 그때마다 답이 하나뿐인지 확인해 만듭니다. 그래서 어느 문제든 답이 정확히 하나입니다. 난이도는 지운 칸 수가 아니라 푸는 데 필요한 기법으로 갈립니다 — 쉬움은 들어갈 수가 하나뿐인 칸만 따라가면 끝까지 풀리고, 보통은 줄이나 상자에서 그 수가 들어갈 자리가 하나뿐인 것을 봐야 하며, 어려움은 그 둘로도 막히는 자리가 있습니다. 문제 번호가 같으면 늘 같은 문제가 나옵니다.',
    boardLabel: '스도쿠 판',
    cellLabel: '{r}행 {c}열',
  },

  en: {
    level_easy: 'Easy',
    level_normal: 'Medium',
    level_hard: 'Hard',
    time: 'Time',
    bestTime: 'Best time',
    blanks: 'Cells left',
    puzzleNo: 'Puzzle no.',
    newGame: 'New puzzle',
    hint: 'Hint',
    undo: 'Undo',
    notes: 'Notes',
    erase: 'Erase',
    won: 'Solved',
    newBest: 'That is your best time',
    hintNaked: 'Row {r}, column {c} can only be {v} — the other eight digits are already in the same row, column or box.',
    hintRow: 'In row {n}, {v} fits in column {c} and nowhere else.',
    hintCol: 'In column {n}, {v} fits in row {r} and nowhere else.',
    hintBox: 'In the {n}th 3×3 box, counting from the top left, {v} fits at row {r}, column {c} and nowhere else.',
    hintNone: 'Nothing on the board is forced right now — from here you have to work through two branches.',
    conflict: 'A red cell means the same digit appears again in its row, column or box.',
    how: 'Tap a cell and pick 1–9. On a keyboard, move with the arrows, type a digit to fill, and press 0 or backspace to clear.',
    note: 'Each puzzle is dug out of a finished grid one cell at a time, checking after every removal that exactly one solution remains — so every puzzle here has exactly one answer. The difficulty is set by the technique the puzzle needs, not by how many cells are blank: easy solves by following cells that have only one possible digit, medium also needs spotting a digit that fits in only one place in a row or box, and hard gets stuck on both. The same puzzle number always gives the same puzzle.',
    boardLabel: 'Sudoku grid',
    cellLabel: 'Row {r}, column {c}',
  },

  es: {
    level_easy: 'Fácil',
    level_normal: 'Medio',
    level_hard: 'Difícil',
    time: 'Tiempo',
    bestTime: 'Mejor tiempo',
    blanks: 'Casillas restantes',
    puzzleNo: 'N.º de puzle',
    newGame: 'Nuevo puzle',
    hint: 'Pista',
    undo: 'Deshacer',
    notes: 'Notas',
    erase: 'Borrar',
    won: 'Resuelto',
    newBest: 'Es tu mejor tiempo',
    hintNaked: 'En la fila {r}, columna {c} solo cabe el {v}: los otros ocho dígitos ya están en la misma fila, columna o caja.',
    hintRow: 'En la fila {n}, el {v} solo cabe en la columna {c}.',
    hintCol: 'En la columna {n}, el {v} solo cabe en la fila {r}.',
    hintBox: 'En la caja 3×3 número {n}, contando desde arriba a la izquierda, el {v} solo cabe en la fila {r}, columna {c}.',
    hintNone: 'Ahora mismo no hay ninguna casilla forzada: a partir de aquí hay que seguir dos ramas.',
    conflict: 'Una casilla en rojo significa que ese mismo número vuelve a aparecer en su fila, columna o caja.',
    how: 'Toca una casilla y elige del 1 al 9. Con teclado, muévete con las flechas, escribe un número para rellenar y pulsa 0 o retroceso para borrar.',
    note: 'Cada puzle se vacía a partir de una cuadrícula completa, casilla a casilla, comprobando tras cada borrado que sigue quedando una sola solución: por eso todos los puzles de aquí tienen exactamente una respuesta. La dificultad la fija la técnica que hace falta, no el número de casillas vacías: en fácil basta seguir las casillas donde solo cabe un número, en medio hay que ver además un número que solo cabe en un sitio de una fila o una caja, y en difícil ninguna de las dos cosas alcanza. El mismo número de puzle da siempre el mismo puzle.',
    boardLabel: 'Cuadrícula de sudoku',
    cellLabel: 'Fila {r}, columna {c}',
  },

  'pt-br': {
    level_easy: 'Fácil',
    level_normal: 'Médio',
    level_hard: 'Difícil',
    time: 'Tempo',
    bestTime: 'Melhor tempo',
    blanks: 'Casas restantes',
    puzzleNo: 'N.º do jogo',
    newGame: 'Novo jogo',
    hint: 'Dica',
    undo: 'Desfazer',
    notes: 'Anotações',
    erase: 'Apagar',
    won: 'Resolvido',
    newBest: 'É o seu melhor tempo',
    hintNaked: 'Na linha {r}, coluna {c} só cabe o {v} — os outros oito algarismos já estão na mesma linha, coluna ou bloco.',
    hintRow: 'Na linha {n}, o {v} só cabe na coluna {c}.',
    hintCol: 'Na coluna {n}, o {v} só cabe na linha {r}.',
    hintBox: 'No bloco 3×3 número {n}, contando do canto superior esquerdo, o {v} só cabe na linha {r}, coluna {c}.',
    hintNone: 'Agora não há nenhuma casa forçada — daqui em diante é preciso testar dois caminhos.',
    conflict: 'Uma casa em vermelho quer dizer que o mesmo número aparece de novo na linha, na coluna ou no bloco.',
    how: 'Toque numa casa e escolha de 1 a 9. No teclado, ande com as setas, digite um número para preencher e use 0 ou backspace para apagar.',
    note: 'Cada jogo é cavado a partir de uma grade completa, uma casa por vez, conferindo depois de cada remoção que ainda sobra uma única solução — por isso todo jogo aqui tem exatamente uma resposta. A dificuldade vem da técnica necessária, não da quantidade de casas vazias: no fácil basta seguir as casas em que só cabe um número, no médio também é preciso notar um número que cabe num só lugar de uma linha ou de um bloco, e no difícil as duas coisas travam. O mesmo número de jogo dá sempre o mesmo jogo.',
    boardLabel: 'Grade de sudoku',
    cellLabel: 'Linha {r}, coluna {c}',
  },

  ja: {
    level_easy: 'やさしい',
    level_normal: 'ふつう',
    level_hard: 'むずかしい',
    time: '経過時間',
    bestTime: '最短記録',
    blanks: '残りのマス',
    puzzleNo: '問題番号',
    newGame: '新しい問題',
    hint: 'ヒント',
    undo: '一手戻す',
    notes: 'メモ',
    erase: '消す',
    won: '解けました',
    newBest: '最短記録です',
    hintNaked: '{r}行{c}列には{v}しか入りません — ほかの八つは同じ行・列・ブロックにすでにあります。',
    hintRow: '{n}行で{v}が入るのは{c}列だけです。',
    hintCol: '{n}列で{v}が入るのは{r}行だけです。',
    hintBox: '左上から{n}番目の3×3ブロックで{v}が入るのは{r}行{c}列だけです。',
    hintNone: 'いま確実に埋まるマスはありません — ここからは二手に分けて試す必要があります。',
    conflict: '赤いマスは、同じ行・列・ブロックに同じ数字がもう一つある場所です。',
    how: 'マスを選んで1〜9を押してください。キーボードでは矢印で動かし、数字で入れ、0かバックスペースで消します。',
    note: '問題は完成した盤から一マスずつ消して作り、消すたびに答えが一つだけ残るかを確かめています。だからどの問題も答えはきっちり一つです。難易度は空きマスの数ではなく、解くのに必要な手筋で決めます — やさしいは入る数字が一つだけのマスをたどれば最後まで解け、ふつうは行やブロックでその数字が入る場所が一つだけなのを見つける必要があり、むずかしいはその二つでも詰まる場所があります。問題番号が同じなら、いつでも同じ問題が出ます。',
    boardLabel: '数独の盤',
    cellLabel: '{r}行{c}列',
  },

  de: {
    level_easy: 'Leicht',
    level_normal: 'Mittel',
    level_hard: 'Schwer',
    time: 'Zeit',
    bestTime: 'Bestzeit',
    blanks: 'Offene Felder',
    puzzleNo: 'Rätsel-Nr.',
    newGame: 'Neues Rätsel',
    hint: 'Tipp',
    undo: 'Zurück',
    notes: 'Notizen',
    erase: 'Löschen',
    won: 'Gelöst',
    newBest: 'Das ist deine Bestzeit',
    hintNaked: 'In Zeile {r}, Spalte {c} passt nur die {v} — die anderen acht Ziffern stehen schon in derselben Zeile, Spalte oder Box.',
    hintRow: 'In Zeile {n} passt die {v} nur in Spalte {c}.',
    hintCol: 'In Spalte {n} passt die {v} nur in Zeile {r}.',
    hintBox: 'In der {n}. 3×3-Box, von links oben gezählt, passt die {v} nur in Zeile {r}, Spalte {c}.',
    hintNone: 'Im Moment ist kein Feld erzwungen — von hier an musst du zwei Zweige durchspielen.',
    conflict: 'Ein rotes Feld heißt: dieselbe Ziffer steht noch einmal in seiner Zeile, Spalte oder Box.',
    how: 'Tippe ein Feld an und wähle 1–9. Auf der Tastatur bewegst du dich mit den Pfeilen, füllst mit einer Ziffer und löschst mit 0 oder Rücktaste.',
    note: 'Jedes Rätsel wird aus einem fertigen Gitter Feld für Feld ausgehöhlt, wobei nach jedem Entfernen geprüft wird, ob genau eine Lösung übrig bleibt — deshalb hat hier jedes Rätsel genau eine Antwort. Die Schwierigkeit ergibt sich aus der nötigen Technik, nicht aus der Zahl der leeren Felder: leicht löst sich, indem man Feldern mit nur einer möglichen Ziffer folgt, mittel verlangt zusätzlich, eine Ziffer zu finden, die in einer Zeile oder Box nur an einer Stelle passt, und schwer bleibt bei beidem stecken. Dieselbe Rätselnummer ergibt immer dasselbe Rätsel.',
    boardLabel: 'Sudoku-Gitter',
    cellLabel: 'Zeile {r}, Spalte {c}',
  },

  fr: {
    level_easy: 'Facile',
    level_normal: 'Moyen',
    level_hard: 'Difficile',
    time: 'Temps',
    bestTime: 'Meilleur temps',
    blanks: 'Cases restantes',
    puzzleNo: 'Grille n°',
    newGame: 'Nouvelle grille',
    hint: 'Indice',
    undo: 'Annuler',
    notes: 'Notes',
    erase: 'Effacer',
    won: 'Résolu',
    newBest: 'C’est ton meilleur temps',
    hintNaked: 'À la ligne {r}, colonne {c}, seul le {v} peut entrer — les huit autres chiffres sont déjà dans la même ligne, colonne ou région.',
    hintRow: 'Dans la ligne {n}, le {v} ne peut aller qu’en colonne {c}.',
    hintCol: 'Dans la colonne {n}, le {v} ne peut aller qu’à la ligne {r}.',
    hintBox: 'Dans la {n}e région 3×3, en comptant depuis le coin haut gauche, le {v} ne peut aller qu’à la ligne {r}, colonne {c}.',
    hintNone: 'Aucune case n’est forcée pour l’instant — à partir d’ici il faut explorer deux branches.',
    conflict: 'Une case en rouge signifie que le même chiffre revient dans sa ligne, sa colonne ou sa région.',
    how: 'Touche une case puis choisis de 1 à 9. Au clavier, déplace-toi avec les flèches, tape un chiffre pour remplir, et appuie sur 0 ou retour arrière pour effacer.',
    note: 'Chaque grille est creusée à partir d’une grille complète, case par case, en vérifiant après chaque retrait qu’il ne reste qu’une seule solution — c’est pourquoi toutes les grilles ici ont exactement une réponse. La difficulté vient de la technique nécessaire, pas du nombre de cases vides : en facile il suffit de suivre les cases où un seul chiffre est possible, en moyen il faut aussi repérer un chiffre qui n’a qu’une place possible dans une ligne ou une région, et en difficile les deux ne suffisent plus. Le même numéro de grille donne toujours la même grille.',
    boardLabel: 'Grille de sudoku',
    cellLabel: 'Ligne {r}, colonne {c}',
  },

  hi: {
    level_easy: 'आसान',
    level_normal: 'मध्यम',
    level_hard: 'कठिन',
    time: 'लगा समय',
    bestTime: 'सबसे कम समय',
    blanks: 'बचे खाने',
    puzzleNo: 'पहेली संख्या',
    newGame: 'नई पहेली',
    hint: 'संकेत',
    undo: 'पिछली चाल हटाएँ',
    notes: 'नोट',
    erase: 'मिटाएँ',
    won: 'हल हो गई',
    newBest: 'यह आपका सबसे कम समय है',
    hintNaked: 'पंक्ति {r}, स्तंभ {c} में केवल {v} आ सकता है — बाकी आठ अंक उसी पंक्ति, स्तंभ या बक्से में पहले से हैं।',
    hintRow: 'पंक्ति {n} में {v} केवल स्तंभ {c} में आ सकता है।',
    hintCol: 'स्तंभ {n} में {v} केवल पंक्ति {r} में आ सकता है।',
    hintBox: 'ऊपर बाएँ से {n}वें 3×3 बक्से में {v} केवल पंक्ति {r}, स्तंभ {c} में आ सकता है।',
    hintNone: 'इस समय कोई खाना पक्का नहीं है — यहाँ से दो रास्ते जाँचने पड़ेंगे।',
    conflict: 'लाल खाने का मतलब है कि वही अंक उसकी पंक्ति, स्तंभ या बक्से में दोबारा आया है।',
    how: 'कोई खाना चुनें और 1–9 दबाएँ। कीबोर्ड पर तीर से चलें, अंक टाइप करके भरें, और 0 या बैकस्पेस से मिटाएँ।',
    note: 'हर पहेली पूरी भरी हुई ग्रिड से एक-एक खाना हटाकर बनाई जाती है, और हर हटाने के बाद जाँचा जाता है कि हल अब भी सिर्फ़ एक बचा है — इसलिए यहाँ हर पहेली का उत्तर ठीक एक ही है। कठिनाई खाली खानों की संख्या से नहीं, हल करने में लगने वाली तरकीब से तय होती है: आसान में जिन खानों में एक ही अंक बैठता है उन्हें पकड़ते जाना काफ़ी है, मध्यम में यह भी देखना पड़ता है कि किसी पंक्ति या बक्से में वह अंक एक ही जगह बैठता है, और कठिन में ये दोनों अटक जाती हैं। पहेली संख्या वही हो तो पहेली भी हमेशा वही आती है।',
    boardLabel: 'सुडोकू ग्रिड',
    cellLabel: 'पंक्ति {r}, स्तंभ {c}',
  },

  'zh-hans': {
    level_easy: '简单',
    level_normal: '普通',
    level_hard: '困难',
    time: '用时',
    bestTime: '最快成绩',
    blanks: '剩余格子',
    puzzleNo: '题号',
    newGame: '换一题',
    hint: '提示',
    undo: '撤销一步',
    notes: '笔记',
    erase: '清除',
    won: '全部填对了',
    newBest: '这是你最快的一次',
    hintNaked: '第{r}行第{c}列只能填{v} — 其余八个数字已经出现在同一行、同一列或同一宫里。',
    hintRow: '第{n}行里，{v}只能填在第{c}列。',
    hintCol: '第{n}列里，{v}只能填在第{r}行。',
    hintBox: '从左上角数第{n}个3×3宫里，{v}只能填在第{r}行第{c}列。',
    hintNone: '眼下没有一格是能直接定下来的 — 从这里开始要分两条路试。',
    conflict: '红色的格子表示同一行、同一列或同一宫里又出现了相同的数字。',
    how: '点一个格子再选1~9。用键盘时，方向键移动，数字键填入，0或退格键清除。',
    note: '题目是从填满的盘面上一格一格挖出来的，每挖一格都要确认答案仍然只剩一个 — 所以这里每道题的答案都正好一个。难度不看空格多少，只看解题要用到的方法：简单的题，顺着只能填一个数字的格子走就能做到底；普通的题还要看出某个数字在一行或一宫里只有一处能放；困难的题这两招都会卡住。题号相同，出的题永远相同。',
    boardLabel: '数独盘面',
    cellLabel: '第{r}行第{c}列',
  },

  'zh-hant': {
    level_easy: '簡單',
    level_normal: '普通',
    level_hard: '困難',
    time: '用時',
    bestTime: '最快成績',
    blanks: '剩餘格子',
    puzzleNo: '題號',
    newGame: '換一題',
    hint: '提示',
    undo: '還原一步',
    notes: '筆記',
    erase: '清除',
    won: '全部填對了',
    newBest: '這是你最快的一次',
    hintNaked: '第{r}列第{c}欄只能填{v} — 其餘八個數字已經出現在同一列、同一欄或同一宮裡。',
    hintRow: '第{n}列裡，{v}只能填在第{c}欄。',
    hintCol: '第{n}欄裡，{v}只能填在第{r}列。',
    hintBox: '從左上角數第{n}個3×3宮裡，{v}只能填在第{r}列第{c}欄。',
    hintNone: '目前沒有哪一格能直接定下來 — 從這裡開始得分兩條路試。',
    conflict: '紅色的格子表示同一列、同一欄或同一宮裡又出現了相同的數字。',
    how: '點一個格子再選1~9。用鍵盤時，方向鍵移動，數字鍵填入，0或退格鍵清除。',
    note: '題目是從填滿的盤面上一格一格挖出來的，每挖一格都要確認答案仍然只剩一個 — 所以這裡每道題的答案都正好一個。難度不看空格多少，只看解題要用到的方法：簡單的題，順著只能填一個數字的格子走就能做到底；普通的題還要看出某個數字在一列或一宮裡只有一處能放；困難的題這兩招都會卡住。題號相同，出的題永遠相同。',
    boardLabel: '數獨盤面',
    cellLabel: '第{r}列第{c}欄',
  },
};
