/**
 * 마이너 아르카나 56장의 영어·중국어 해석.
 *
 * 메이저 22장은 lib/tarot-intl.ts에 있다. 56장을 그쪽에 더하면 파일이 한눈에
 * 안 들어와서 갈라 뒀고, TAROT_READINGS가 두 쪽을 합쳐서 내보낸다.
 *
 * id는 lib/fortune-data.ts의 getFullDeck()이 매기는 22~77을 그대로 쓴다 —
 * 세 언어가 같은 id를 봐야 같은 카드가 나온다. 순서는 완드·컵·소드·펜타클,
 * 각 수트 안에서 에이스→10→시종→기사→여왕→왕이다.
 */
interface Reading { upright: string; reversed: string }

/** 중국어 카드 이름 — 수트는 权杖·圣杯·宝剑·星币로 옮긴다 */
export const MINOR_READINGS_EN: Record<number, Reading> = {
  22: { upright: 'A creative spark is catching light in you. A new venture, a project or a passionate connection is beginning, and the card says start now rather than wait until you feel fully ready.', reversed: 'The spark is there but has nowhere to go — delays, second thoughts, or enthusiasm that fades before anything is built. Pick one small piece and finish it to get the fire moving again.' },
  23: { upright: 'You are standing with the world in your hands, planning what comes next. The groundwork is done; what remains is choosing a direction and accepting that it means leaving something familiar behind.', reversed: 'Planning has become a way of avoiding the decision. Fear of the wrong choice is keeping you at the window instead of out the door.' },
  24: { upright: 'The first ships are on the horizon. Early effort is starting to return something, and this is the moment to think bigger than you originally allowed yourself to.', reversed: 'Progress is slower than the plan promised, or the plan was drawn for a world that has since changed. Adjust the scope rather than abandoning the voyage.' },
  25: { upright: 'A celebration, a homecoming, a milestone reached together. Something you built has become stable enough to enjoy — let yourself mark it before moving on.', reversed: 'The foundation feels less solid than it looks from outside, or tension at home is undercutting what should be a good moment. Address the crack rather than hosting over it.' },
  26: { upright: 'Competition and clashing egos, but the productive kind — everyone here is trying, and the friction is sharpening you. Treat it as sparring rather than war.', reversed: 'The conflict has turned pointless, or you are avoiding it entirely and losing ground by default. Decide which fights are actually yours.' },
  27: { upright: 'Recognition after real effort. Others can see what you accomplished, and accepting the credit is part of the work, not vanity.', reversed: 'Recognition is not coming, or arriving for the wrong thing, or you cannot receive it without deflecting. Confidence built only on applause is fragile.' },
  28: { upright: 'You are defending what you built, alone and outnumbered but holding. Standing your ground is the right call, though it costs energy to keep it up.', reversed: 'You are exhausted from defending a position that may no longer be worth it, or you are fighting everyone instead of the actual problem.' },
  29: { upright: 'Everything is moving fast and in the same direction. Momentum is on your side — news arrives, things unblock, travel and decisions accelerate.', reversed: 'Rushing without direction, or everything stalling at once. Check whether speed is substituting for a plan.' },
  30: { upright: 'Worn out but still standing. You have taken hits and are guarding the last stretch — the resilience you need is already in you, and this is nearly over.', reversed: 'Defensiveness has hardened into paranoia, or you are carrying on past the point where rest would serve you better. Stopping is not the same as failing.' },
  31: { upright: 'Carrying more than you should, close to the finish. The load is real; the question is how much of it was ever yours to carry.', reversed: 'Something has to be put down. Delegate, cut scope or admit the whole burden was self-assigned before it costs you your health.' },
  32: { upright: 'Raw enthusiasm and news of something new. Curiosity is worth following here even if you cannot yet say where it leads.', reversed: 'Enthusiasm without follow-through, or news that turns out to be nothing. Test the idea before you announce it.' },
  33: { upright: 'Charging forward with charm and nerve. Bold action gets results now, though the same energy tends to leave loose ends behind.', reversed: 'Recklessness dressed up as courage, or starting a fourth thing before finishing the first. Slow down enough to land something.' },
  34: { upright: 'Warm, confident, magnetic — sure of yourself without needing to prove it. People are drawn to that, and it works in your favour now.', reversed: 'Confidence tipping into jealousy or a need for attention, or self-belief so shaken that you cannot show up at all.' },
  35: { upright: 'A natural leader with vision and the will to make it real. You can see the whole board and move people with you.', reversed: 'Leading by force rather than vision, or a vision so grand it never becomes a plan. Listening is the missing piece.' },
  36: { upright: 'A cup filling from a source you did not expect. New love, a creative opening, or feeling something clearly for the first time in a while — receive it rather than analysing it.', reversed: 'Feelings blocked, held back or spilling out at the wrong moment. Something needs saying, or needs grieving, before the cup can fill.' },
  37: { upright: 'Two people meeting as equals. Partnership, mutual recognition, a bond where both sides give — in love or in work, this is the real thing.', reversed: 'Imbalance: one side giving far more, or a bond strained by something unspoken. Repair is possible but requires honesty first.' },
  38: { upright: 'Celebration with the people who know you. Friendship, community, shared success — the kind of joy that only exists in company.', reversed: 'Gossip souring a group, or feeling alone in a room full of people. Check whether you belong here or just attend.' },
  39: { upright: 'A cup being offered while you look away. Something is on the table that you are too jaded or too tired to see. Discontent is the signal, not the answer.', reversed: 'Withdrawal is ending — you are ready to look up and take what is offered. Coming out of a low patch.' },
  40: { upright: 'Grief over what spilled. The loss is real, but two cups are still standing behind you and this card exists to point at them.', reversed: 'Beginning to move on. Forgiveness — of someone else or of yourself — is loosening its grip.' },
  41: { upright: 'A warm memory reaching forward. Nostalgia, an old friend, a kindness from long ago that matters again — the past is a resource here, not a trap.', reversed: 'Living in the memory instead of the present, or an idealised past that never quite happened that way. Come back to now.' },
  42: { upright: 'Too many options, most of them imagined. Dreams and fantasies are crowding out the one real choice. Pick what actually exists.', reversed: 'The fog is clearing and you can tell wish from possibility again. A decision becomes obvious.' },
  43: { upright: 'Walking away from something that was fine but not enough. This is not failure — it is choosing meaning over comfort, and it takes nerve.', reversed: 'Circling back to what you already outgrew, or staying past the point of usefulness because leaving feels like waste.' },
  44: { upright: 'Contentment, earned. What you wanted has arrived and you are able to enjoy it — a rare, straightforwardly good card.', reversed: 'Getting what you wanted and feeling nothing, or satisfaction that depends on things staying exactly as they are.' },
  45: { upright: 'Emotional fulfilment shared with others. Family, chosen or given, in a good moment — this is the card of belonging.', reversed: 'A rift at home, or a picture of harmony kept up for show. The gap between how it looks and how it feels is the issue.' },
  46: { upright: 'A gentle, unexpected feeling — a message, an offer, a creative idea arriving sideways. Stay open rather than sensible.', reversed: 'Emotional immaturity, or an intuition ignored because it seemed silly. It was probably right.' },
  47: { upright: 'Following the heart with grace. A romantic gesture, a sincere approach, an artist moving toward what they love.', reversed: 'Feeling led entirely by mood, or promises made in the moment that will not survive it. Charm is not the same as intention.' },
  48: { upright: 'Deep empathy paired with steadiness. You can feel what others feel without drowning in it, and that is a form of strength.', reversed: 'Absorbing everyone else’s emotions until you lose your own outline, or shutting them out entirely. Boundaries, not walls.' },
  49: { upright: 'Emotional mastery — calm in a storm, generous without being consumed. The person others come to when it is hard.', reversed: 'Calm held on the surface over something unaddressed, or emotion used to manage other people.' },
  50: { upright: 'A clean, decisive insight. The truth cuts through the noise, a diagnosis lands, a decision becomes obvious. Say the thing.', reversed: 'Clarity used as a weapon, or too much information and no conclusion. Confusion here is a sign to gather less and think more.' },
  51: { upright: 'A choice made with a blindfold on. You are avoiding a decision because both options cost something. The information you are missing may be information you are declining to look at.', reversed: 'The blindfold is coming off. Stalemate breaks, sometimes uncomfortably.' },
  52: { upright: 'Heartbreak, plainly. Something has been said or lost and it hurts. This card does not pretend otherwise — the way through is feeling it, not routing around it.', reversed: 'The worst of the pain is passing. Recovery is slow and not linear, and that is normal.' },
  53: { upright: 'Rest, deliberately taken. Stepping back is not giving up; recovery is part of the work. Take the pause before it is forced on you.', reversed: 'Burnout from refusing to stop, or restlessness that will not let you rest even when you try.' },
  54: { upright: 'A win that cost more than it was worth. Conflict has left damage on both sides — check whether being right was the goal.', reversed: 'Ready to stop fighting. Reconciliation, or at least the decision to walk away from a fight you cannot win well.' },
  55: { upright: 'Leaving difficulty behind, quietly and with help. The crossing is not comfortable, but you are moving toward calmer water.', reversed: 'Carrying the old trouble with you, or a move that changes the scenery without changing the problem.' },
  56: { upright: 'Something is being taken or hidden. Deception, or a shortcut that only works if nobody looks closely. Verify what you have been told.', reversed: 'What was hidden comes out, or you decide to come clean. Either way the concealment is ending.' },
  57: { upright: 'Trapped, but by beliefs more than by circumstance. The bindings are loose enough to step out of once you notice them.', reversed: 'Beginning to see the way out. What looked like a cage turns out to have a door.' },
  58: { upright: 'Awake at 3am with everything looming. The dread here is larger than the situation warrants — anxiety is the subject of this card, not prophecy.', reversed: 'The worst thoughts are losing their grip. Saying them out loud shrinks them.' },
  59: { upright: 'The end of something, absolute. It is over, and pretending otherwise costs more than accepting it. Something new can only start from here.', reversed: 'Surviving the ending. The bottom has been reached and the only direction left is up.' },
  60: { upright: 'Sharp curiosity and a hunger for information. Ask the questions, read the fine print, learn the thing.', reversed: 'Talking more than thinking, or information gathered to win arguments rather than understand. Watch what you repeat.' },
  61: { upright: 'Acting fast on conviction. Directness cuts through obstruction — just aim before you charge.', reversed: 'Speed without judgement, or bluntness that leaves damage. Being right quickly is not the same as being effective.' },
  62: { upright: 'Clear-eyed and independent, kind without being soft. You can see the situation exactly as it is, which is a gift and occasionally lonely.' , reversed: 'Clarity gone cold, or a hurt turned into a rule about people. Detachment protecting you from more than it needs to.' },
  63: { upright: 'Authority through reason. Fair, principled, able to make the hard call and explain it. Structure serves you here.' , reversed: 'Rules used to control rather than to be fair, or logic that has stopped accounting for people.' },
  64: { upright: 'A tangible opportunity — a job, a deal, a seed of something that could grow real. Small and solid beats large and vague.', reversed: 'An opportunity missed or built on a shaky base. Check the numbers before committing.' },
  65: { upright: 'Juggling, competently. Two demands, both legitimate, and you are managing — but this is a balance you hold, not one that holds itself.', reversed: 'One ball dropped, or all of them. Something has to come off the list.' },
  66: { upright: 'Skilled collaboration. Your work is being recognised by people who understand it, and the thing you are building needs more than one pair of hands.', reversed: 'Mismatched effort, unclear roles, or work that is not being credited. Say who did what.' },
  67: { upright: 'Holding on tight to what you have. Prudence, or fear disguised as prudence — worth knowing which one this is.', reversed: 'Loosening the grip, or losing it. Generosity turns out to cost less than the holding did.' },
  68: { upright: 'Cold outside the lit window. Hardship, and the particular loneliness of thinking you must face it alone. Help is nearer than it looks — the door is right there.', reversed: 'Recovery beginning. Asking for help turns out to be the thing that works.' },
  69: { upright: 'Giving and receiving in fair measure. Generosity that is not a transaction, help that does not create a debt.', reversed: 'Strings attached, or charity that keeps someone dependent. Check what the giving is really for.' },
  70: { upright: 'Waiting for what you planted. The work is done and now the answer is patience, which is harder than more effort.', reversed: 'Impatience pulling up the crop early, or effort poured into ground that will not yield. Reassess before continuing.' },
  71: { upright: 'Craft and repetition. Getting better through practice, not talent — dull to live and unbeatable in results.', reversed: 'Going through the motions, or perfectionism that never releases anything. Ship it and improve it after.' },
  72: { upright: 'Self-sufficiency, earned. Comfortable alone and in what you built — independence that came from work, not luck.', reversed: 'Comfort turned to isolation, or success measured only against others. Check what the independence is protecting.' },
  73: { upright: 'Lasting security, the kind that outlives you. Family, inheritance, an institution built well — long-term thinking pays here.', reversed: 'Money straining a family, or a legacy that has become an obligation. Wealth without warmth is expensive.' },
  74: { upright: 'A studious beginning. A new skill, a course, a first job — humble start, real trajectory.', reversed: 'Distraction, or plans that stay plans. Start smaller than feels satisfying.' },
  75: { upright: 'Slow, reliable progress. Not exciting, entirely trustworthy — the one who finishes what they start.', reversed: 'Stuck in the same groove, or caution so complete that nothing moves. Change one thing.' },
  76: { upright: 'Practical warmth. Someone who provides — for a home, a team, a garden — and does it competently.', reversed: 'Giving until nothing is left for yourself, or worry about security crowding out enjoying it.' },
  77: { upright: 'Material success held wisely. Reliable, practical, generous with what was built — a mature kind of leadership.', reversed: 'Holding on to success too tightly, or using status to control. It stays solid only alongside humility.' },
};

