/**
 * 마이너 아르카나 56장의 영어·중국어 해석.
 *
 * 메이저 22장은 lib/tarot-intl.ts에 있다. 56장을 그쪽에 더하면 파일이 한눈에
 * 안 들어와서 갈라 뒀고, TAROT_READINGS가 두 쪽을 합쳐서 내보낸다.
 *
 * id는 lib/fortune-data.ts의 getFullDeck()이 매기는 22~77을 그대로 쓴다 —
 * 세 언어가 같은 id를 봐야 같은 카드가 나온다. 순서는 완드·컵·소드·펜타클,
 * 각 수트 안에서 에이스→10→시종→기사→여왕→왕이다.
 */
interface Reading { upright: string; reversed: string }

/** 중국어 카드 이름 — 수트는 权杖·圣杯·宝剑·星币로 옮긴다 */
export const MINOR_NAMES_ZH: Record<number, string> = {
  22: '权杖首牌', 23: '权杖二', 24: '权杖三', 25: '权杖四', 26: '权杖五', 27: '权杖六', 28: '权杖七',
  29: '权杖八', 30: '权杖九', 31: '权杖十', 32: '权杖侍者', 33: '权杖骑士', 34: '权杖王后', 35: '权杖国王',
  36: '圣杯首牌', 37: '圣杯二', 38: '圣杯三', 39: '圣杯四', 40: '圣杯五', 41: '圣杯六', 42: '圣杯七',
  43: '圣杯八', 44: '圣杯九', 45: '圣杯十', 46: '圣杯侍者', 47: '圣杯骑士', 48: '圣杯王后', 49: '圣杯国王',
  50: '宝剑首牌', 51: '宝剑二', 52: '宝剑三', 53: '宝剑四', 54: '宝剑五', 55: '宝剑六', 56: '宝剑七',
  57: '宝剑八', 58: '宝剑九', 59: '宝剑十', 60: '宝剑侍者', 61: '宝剑骑士', 62: '宝剑王后', 63: '宝剑国王',
  64: '星币首牌', 65: '星币二', 66: '星币三', 67: '星币四', 68: '星币五', 69: '星币六', 70: '星币七',
  71: '星币八', 72: '星币九', 73: '星币十', 74: '星币侍者', 75: '星币骑士', 76: '星币王后', 77: '星币国王',
};

export const MINOR_READINGS_EN: Record<number, Reading> = {
  22: { upright: 'A creative spark is catching light in you. A new venture, a project or a passionate connection is beginning, and the card says start now rather than wait until you feel fully ready.', reversed: 'The spark is there but has nowhere to go — delays, second thoughts, or enthusiasm that fades before anything is built. Pick one small piece and finish it to get the fire moving again.' },
  23: { upright: 'You are standing with the world in your hands, planning what comes next. The groundwork is done; what remains is choosing a direction and accepting that it means leaving something familiar behind.', reversed: 'Planning has become a way of avoiding the decision. Fear of the wrong choice is keeping you at the window instead of out the door.' },
  24: { upright: 'The first ships are on the horizon. Early effort is starting to return something, and this is the moment to think bigger than you originally allowed yourself to.', reversed: 'Progress is slower than the plan promised, or the plan was drawn for a world that has since changed. Adjust the scope rather than abandoning the voyage.' },
  25: { upright: 'A celebration, a homecoming, a milestone reached together. Something you built has become stable enough to enjoy — let yourself mark it before moving on.', reversed: 'The foundation feels less solid than it looks from outside, or tension at home is undercutting what should be a good moment. Address the crack rather than hosting over it.' },
  26: { upright: 'Competition and clashing egos, but the productive kind — everyone here is trying, and the friction is sharpening you. Treat it as sparring rather than war.', reversed: 'The conflict has turned pointless, or you are avoiding it entirely and losing ground by default. Decide which fights are actually yours.' },
  27: { upright: 'Recognition after real effort. Others can see what you accomplished, and accepting the credit is part of the work, not vanity.', reversed: 'Recognition is not coming, or arriving for the wrong thing, or you cannot receive it without deflecting. Confidence built only on applause is fragile.' },
  28: { upright: 'You are defending what you built, alone and outnumbered but holding. Standing your ground is the right call, though it costs energy to keep it up.', reversed: 'You are exhausted from defending a position that may no longer be worth it, or you are fighting everyone instead of the actual problem.' },
  29: { upright: 'Everything is moving fast and in the same direction. Momentum is on your side — news arrives, things unblock, travel and decisions accelerate.', reversed: 'Rushing without direction, or everything stalling at once. Check whether speed is substituting for a plan.' },
  30: { upright: 'Worn out but still standing. You have taken hits and are guarding the last stretch — the resilience you need is already in you, and this is nearly over.', reversed: 'Defensiveness has hardened into paranoia, or you are carrying on past the point where rest would serve you better. Stopping is not the same as failing.' },
  31: { upright: 'Carrying more than you should, close to the finish. The load is real; the question is how much of it was ever yours to carry.', reversed: 'Something has to be put down. Delegate, cut scope or admit the whole burden was self-assigned before it costs you your health.' },
  32: { upright: 'Raw enthusiasm and news of something new. Curiosity is worth following here even if you cannot yet say where it leads.', reversed: 'Enthusiasm without follow-through, or news that turns out to be nothing. Test the idea before you announce it.' },
  33: { upright: 'Charging forward with charm and nerve. Bold action gets results now, though the same energy tends to leave loose ends behind.', reversed: 'Recklessness dressed up as courage, or starting a fourth thing before finishing the first. Slow down enough to land something.' },
  34: { upright: 'Warm, confident, magnetic — sure of yourself without needing to prove it. People are drawn to that, and it works in your favour now.', reversed: 'Confidence tipping into jealousy or a need for attention, or self-belief so shaken that you cannot show up at all.' },
  35: { upright: 'A natural leader with vision and the will to make it real. You can see the whole board and move people with you.', reversed: 'Leading by force rather than vision, or a vision so grand it never becomes a plan. Listening is the missing piece.' },
  36: { upright: 'A cup filling from a source you did not expect. New love, a creative opening, or feeling something clearly for the first time in a while — receive it rather than analysing it.', reversed: 'Feelings blocked, held back or spilling out at the wrong moment. Something needs saying, or needs grieving, before the cup can fill.' },
  37: { upright: 'Two people meeting as equals. Partnership, mutual recognition, a bond where both sides give — in love or in work, this is the real thing.', reversed: 'Imbalance: one side giving far more, or a bond strained by something unspoken. Repair is possible but requires honesty first.' },
  38: { upright: 'Celebration with the people who know you. Friendship, community, shared success — the kind of joy that only exists in company.', reversed: 'Gossip souring a group, or feeling alone in a room full of people. Check whether you belong here or just attend.' },
  39: { upright: 'A cup being offered while you look away. Something is on the table that you are too jaded or too tired to see. Discontent is the signal, not the answer.', reversed: 'Withdrawal is ending — you are ready to look up and take what is offered. Coming out of a low patch.' },
  40: { upright: 'Grief over what spilled. The loss is real, but two cups are still standing behind you and this card exists to point at them.', reversed: 'Beginning to move on. Forgiveness — of someone else or of yourself — is loosening its grip.' },
  41: { upright: 'A warm memory reaching forward. Nostalgia, an old friend, a kindness from long ago that matters again — the past is a resource here, not a trap.', reversed: 'Living in the memory instead of the present, or an idealised past that never quite happened that way. Come back to now.' },
  42: { upright: 'Too many options, most of them imagined. Dreams and fantasies are crowding out the one real choice. Pick what actually exists.', reversed: 'The fog is clearing and you can tell wish from possibility again. A decision becomes obvious.' },
  43: { upright: 'Walking away from something that was fine but not enough. This is not failure — it is choosing meaning over comfort, and it takes nerve.', reversed: 'Circling back to what you already outgrew, or staying past the point of usefulness because leaving feels like waste.' },
  44: { upright: 'Contentment, earned. What you wanted has arrived and you are able to enjoy it — a rare, straightforwardly good card.', reversed: 'Getting what you wanted and feeling nothing, or satisfaction that depends on things staying exactly as they are.' },
  45: { upright: 'Emotional fulfilment shared with others. Family, chosen or given, in a good moment — this is the card of belonging.', reversed: 'A rift at home, or a picture of harmony kept up for show. The gap between how it looks and how it feels is the issue.' },
  46: { upright: 'A gentle, unexpected feeling — a message, an offer, a creative idea arriving sideways. Stay open rather than sensible.', reversed: 'Emotional immaturity, or an intuition ignored because it seemed silly. It was probably right.' },
  47: { upright: 'Following the heart with grace. A romantic gesture, a sincere approach, an artist moving toward what they love.', reversed: 'Feeling led entirely by mood, or promises made in the moment that will not survive it. Charm is not the same as intention.' },
  48: { upright: 'Deep empathy paired with steadiness. You can feel what others feel without drowning in it, and that is a form of strength.', reversed: 'Absorbing everyone else’s emotions until you lose your own outline, or shutting them out entirely. Boundaries, not walls.' },
  49: { upright: 'Emotional mastery — calm in a storm, generous without being consumed. The person others come to when it is hard.', reversed: 'Calm held on the surface over something unaddressed, or emotion used to manage other people.' },
  50: { upright: 'A clean, decisive insight. The truth cuts through the noise, a diagnosis lands, a decision becomes obvious. Say the thing.', reversed: 'Clarity used as a weapon, or too much information and no conclusion. Confusion here is a sign to gather less and think more.' },
  51: { upright: 'A choice made with a blindfold on. You are avoiding a decision because both options cost something. The information you are missing may be information you are declining to look at.', reversed: 'The blindfold is coming off. Stalemate breaks, sometimes uncomfortably.' },
  52: { upright: 'Heartbreak, plainly. Something has been said or lost and it hurts. This card does not pretend otherwise — the way through is feeling it, not routing around it.', reversed: 'The worst of the pain is passing. Recovery is slow and not linear, and that is normal.' },
  53: { upright: 'Rest, deliberately taken. Stepping back is not giving up; recovery is part of the work. Take the pause before it is forced on you.', reversed: 'Burnout from refusing to stop, or restlessness that will not let you rest even when you try.' },
  54: { upright: 'A win that cost more than it was worth. Conflict has left damage on both sides — check whether being right was the goal.', reversed: 'Ready to stop fighting. Reconciliation, or at least the decision to walk away from a fight you cannot win well.' },
  55: { upright: 'Leaving difficulty behind, quietly and with help. The crossing is not comfortable, but you are moving toward calmer water.', reversed: 'Carrying the old trouble with you, or a move that changes the scenery without changing the problem.' },
  56: { upright: 'Something is being taken or hidden. Deception, or a shortcut that only works if nobody looks closely. Verify what you have been told.', reversed: 'What was hidden comes out, or you decide to come clean. Either way the concealment is ending.' },
  57: { upright: 'Trapped, but by beliefs more than by circumstance. The bindings are loose enough to step out of once you notice them.', reversed: 'Beginning to see the way out. What looked like a cage turns out to have a door.' },
  58: { upright: 'Awake at 3am with everything looming. The dread here is larger than the situation warrants — anxiety is the subject of this card, not prophecy.', reversed: 'The worst thoughts are losing their grip. Saying them out loud shrinks them.' },
  59: { upright: 'The end of something, absolute. It is over, and pretending otherwise costs more than accepting it. Something new can only start from here.', reversed: 'Surviving the ending. The bottom has been reached and the only direction left is up.' },
  60: { upright: 'Sharp curiosity and a hunger for information. Ask the questions, read the fine print, learn the thing.', reversed: 'Talking more than thinking, or information gathered to win arguments rather than understand. Watch what you repeat.' },
  61: { upright: 'Acting fast on conviction. Directness cuts through obstruction — just aim before you charge.', reversed: 'Speed without judgement, or bluntness that leaves damage. Being right quickly is not the same as being effective.' },
  62: { upright: 'Clear-eyed and independent, kind without being soft. You can see the situation exactly as it is, which is a gift and occasionally lonely.' , reversed: 'Clarity gone cold, or a hurt turned into a rule about people. Detachment protecting you from more than it needs to.' },
  63: { upright: 'Authority through reason. Fair, principled, able to make the hard call and explain it. Structure serves you here.' , reversed: 'Rules used to control rather than to be fair, or logic that has stopped accounting for people.' },
  64: { upright: 'A tangible opportunity — a job, a deal, a seed of something that could grow real. Small and solid beats large and vague.', reversed: 'An opportunity missed or built on a shaky base. Check the numbers before committing.' },
  65: { upright: 'Juggling, competently. Two demands, both legitimate, and you are managing — but this is a balance you hold, not one that holds itself.', reversed: 'One ball dropped, or all of them. Something has to come off the list.' },
  66: { upright: 'Skilled collaboration. Your work is being recognised by people who understand it, and the thing you are building needs more than one pair of hands.', reversed: 'Mismatched effort, unclear roles, or work that is not being credited. Say who did what.' },
  67: { upright: 'Holding on tight to what you have. Prudence, or fear disguised as prudence — worth knowing which one this is.', reversed: 'Loosening the grip, or losing it. Generosity turns out to cost less than the holding did.' },
  68: { upright: 'Cold outside the lit window. Hardship, and the particular loneliness of thinking you must face it alone. Help is nearer than it looks — the door is right there.', reversed: 'Recovery beginning. Asking for help turns out to be the thing that works.' },
  69: { upright: 'Giving and receiving in fair measure. Generosity that is not a transaction, help that does not create a debt.', reversed: 'Strings attached, or charity that keeps someone dependent. Check what the giving is really for.' },
  70: { upright: 'Waiting for what you planted. The work is done and now the answer is patience, which is harder than more effort.', reversed: 'Impatience pulling up the crop early, or effort poured into ground that will not yield. Reassess before continuing.' },
  71: { upright: 'Craft and repetition. Getting better through practice, not talent — dull to live and unbeatable in results.', reversed: 'Going through the motions, or perfectionism that never releases anything. Ship it and improve it after.' },
  72: { upright: 'Self-sufficiency, earned. Comfortable alone and in what you built — independence that came from work, not luck.', reversed: 'Comfort turned to isolation, or success measured only against others. Check what the independence is protecting.' },
  73: { upright: 'Lasting security, the kind that outlives you. Family, inheritance, an institution built well — long-term thinking pays here.', reversed: 'Money straining a family, or a legacy that has become an obligation. Wealth without warmth is expensive.' },
  74: { upright: 'A studious beginning. A new skill, a course, a first job — humble start, real trajectory.', reversed: 'Distraction, or plans that stay plans. Start smaller than feels satisfying.' },
  75: { upright: 'Slow, reliable progress. Not exciting, entirely trustworthy — the one who finishes what they start.', reversed: 'Stuck in the same groove, or caution so complete that nothing moves. Change one thing.' },
  76: { upright: 'Practical warmth. Someone who provides — for a home, a team, a garden — and does it competently.', reversed: 'Giving until nothing is left for yourself, or worry about security crowding out enjoying it.' },
  77: { upright: 'Material success held wisely. Reliable, practical, generous with what was built — a mature kind of leadership.', reversed: 'Holding on to success too tightly, or using status to control. It stays solid only alongside humility.' },
};

export const MINOR_READINGS_ZH: Record<number, Reading> = {
  22: { upright: '创造的火花正在你心里点起来。新的事业、项目或一段热烈的关系正要开始，这张牌说的是现在就动手，而不是等到觉得万事俱备。', reversed: '火花有了，却没处去 —— 拖延、反复犹豫，或者热情在做出东西之前就凉了。挑一件最小的事做完，火才会重新烧起来。' },
  23: { upright: '你手里握着整个世界，正在盘算下一步。基础已经打好，剩下的是选一个方向，并接受这意味着要离开某些熟悉的东西。', reversed: '规划变成了逃避决定的方式。怕选错，就一直站在窗边而不出门。' },
  24: { upright: '最早的船已经出现在地平线上。前期的努力开始有回报，现在正是把格局想得比当初更大一点的时候。', reversed: '进展比计划慢，或者计划是为一个已经变了的世界画的。调整范围，而不是放弃这趟航程。' },
  25: { upright: '庆祝、归家、一起达成的里程碑。你造出来的东西已经稳到可以享受了 —— 先好好标记一下再继续往前。', reversed: '地基没有外面看起来那么牢，或者家里的紧张感在削弱这个本该愉快的时刻。修裂缝，而不是在裂缝上办宴。' },
  26: { upright: '竞争与自尊的碰撞，但属于有产出的那种 —— 在场的人都在使劲，摩擦也在磨快你。当成对练，不是战争。', reversed: '冲突已经变得没有意义，或者你完全在回避而白白失去阵地。想清楚哪些仗真的是你的。' },
  27: { upright: '实打实努力之后的被认可。别人看得见你做成了什么，接受这份肯定是工作的一部分，不是虚荣。', reversed: '肯定没有来，或者为了错的事情来了，或者你接不住只会推开。只靠掌声搭起来的自信很脆。' },
  28: { upright: '你在守自己造出来的东西，孤身且寡不敵众，但守住了。坚持是对的，只是撑着很耗力气。', reversed: '你已经累于守一个也许不值得再守的位置，或者你在跟所有人打，而不是跟真正的问题打。' },
  29: { upright: '一切都在快速地往同一个方向走。势头站在你这边 —— 消息来了，堵住的地方通了，行程和决定都在加速。', reversed: '急着走却没有方向，或者所有事情同时停住。看看是不是用速度代替了计划。' },
  30: { upright: '疲惫但还站着。你挨过打，正守着最后一段路 —— 你需要的韧性本来就在你身上，而这快结束了。', reversed: '防卫已经硬化成疑心，或者你撑过了休息更有用的那个点。停下来不等于失败。' },
  31: { upright: '扛得比该扛的多，而且已经快到终点。担子是真的重，问题是这里面有多少本来就不该由你扛。', reversed: '必须放下一些东西。分出去、砍掉范围，或者承认这担子本来是自己给自己加的 —— 在它伤到身体之前。' },
  32: { upright: '未加修饰的热情，以及关于新事物的消息。这里的好奇心值得跟着走，就算你还说不清它通向哪。', reversed: '热情有了没有跟进，或者消息最后什么也不是。先验证想法，再去宣布。' },
  33: { upright: '带着魅力和胆量往前冲。此刻大胆行动确实有效果，只是同一股劲往往会留下没收尾的地方。', reversed: '把莽撞打扮成勇气，或者第一件还没做完就开了第四件。慢到能把一件事落地。' },
  34: { upright: '温暖、自信、有吸引力 —— 对自己有把握，不需要证明。别人会被这一点吸引，而这现在对你有利。', reversed: '自信偏向了嫉妒或对关注的渴求，又或者自我认同动摇到根本站不出来。' },
  35: { upright: '天生的领导者，有远景也有把它做实的意志。你能看清整个棋盘，也能带动别人。', reversed: '靠强压而不是靠远景带人，或者远景太宏大以致从没变成计划。缺的那块是倾听。' },
  36: { upright: '一只杯子正被意想不到的源头注满。新的爱、创作的开口，或者久违地清楚感受到某种情绪 —— 接住它，别急着分析。', reversed: '感情被堵住、被压着，或者在不该的时候溢出来。有些话要说出口，或者有些事要先哀悼，杯子才能满。' },
  37: { upright: '两个人以对等的姿态相遇。伙伴关系、互相认可、双方都在付出的连接 —— 不论在感情还是工作里，这是真的。', reversed: '失衡：一方付出多得多，或者有话没说出来把关系撑得很紧。可以修，但要先诚实。' },
  38: { upright: '和懂你的人一起庆祝。友谊、群体、共享的成果 —— 那种只有在人群里才存在的快乐。', reversed: '闲话把一个群体弄坏了，或者身在人群中却觉得孤单。想想你是属于这里，还是只是在场。' },
  39: { upright: '有人递上杯子，你却看向别处。桌上有东西，但你太倦或太冷淡而看不见。不满是信号，不是答案。', reversed: '退缩正在结束 —— 你准备抬头，接住递过来的东西。从低谷里走出来。' },
  40: { upright: '为洒掉的东西悲伤。损失是真的，但你身后还立着两只杯子，这张牌存在就是为了指向它们。', reversed: '开始往前走。原谅 —— 别人或自己 —— 正在松开它的手。' },
  41: { upright: '一段温暖的记忆伸过来。怀旧、老朋友、很久以前的一点好意此刻又有了意义 —— 这里的过去是资源，不是陷阱。', reversed: '活在记忆里而不是当下，或者美化了一个其实并非如此的过去。回到现在。' },
  42: { upright: '选项太多，而大半是想象出来的。梦和幻想挤掉了唯一真实的那个选择。挑真实存在的那个。', reversed: '雾在散，你又分得清愿望和可能了。某个决定会变得很明显。' },
  43: { upright: '离开一个还不错但不够的东西。这不是失败 —— 是选意义而不选舒服，需要胆量。', reversed: '绕回已经长过去的地方，或者因为觉得离开太浪费而留过了有用的时点。' },
  44: { upright: '满足，而且是挣来的。你想要的到了，你也有能力享受它 —— 这是少见的、直接就是好的牌。', reversed: '拿到了想要的却毫无感觉，或者满足感全靠一切保持原样才成立。' },
  45: { upright: '与人共享的情感圆满。家人 —— 血缘的或自己选的 —— 处在好的时刻，这是归属之牌。', reversed: '家里有裂痕，或者一幅为外人维持的和睦画面。看起来和感受起来之间的差距，就是问题。' },
  46: { upright: '一种温柔而意外的感受 —— 一条消息、一个邀约、一个从侧面冒出来的创作念头。保持敞开，别急着讲道理。', reversed: '情绪上的不成熟，或者因为觉得傻而忽略了直觉。它大概是对的。' },
  47: { upright: '带着风度跟着心走。一个浪漫的举动、一次真诚的靠近、一个正走向所爱之物的创作者。', reversed: '完全被情绪牵着走，或者当下许的诺撑不过当下。魅力不等于意图。' },
  48: { upright: '深切的共情加上稳。你能感到别人的感受而不被淹没，这本身就是一种力量。', reversed: '把所有人的情绪都吸进来，直到自己的轮廓消失；或者干脆全部关在门外。要的是边界，不是墙。' },
  49: { upright: '情感上的成熟 —— 风浪里也稳，慷慨而不被吞掉。是别人难的时候会去找的那个人。', reversed: '表面的平静盖着没处理的东西，或者把情绪当成管住别人的手段。' },
  50: { upright: '一次干净的、决定性的洞察。真相切开噪音，诊断落地，决定变得显然。把那句话说出来。', reversed: '把清晰当成武器，或者信息太多却没有结论。这里的混乱是提示：少收集一点，多想一点。' },
  51: { upright: '蒙着眼做的选择。你在回避决定，因为两个选项都有代价。你缺的那份信息，可能是你不愿意去看的那份。', reversed: '眼罩正在摘下来。僵局会破，有时破得不太舒服。' },
  52: { upright: '心碎，就是字面意思。有话被说出口，或有什么失去了，而它就是痛。这张牌不假装别的 —— 走出去的路是感受它，不是绕开它。', reversed: '最痛的那阵正在过去。恢复很慢，也不是一条直线，这是正常的。' },
  53: { upright: '刻意去休息。退一步不是放弃；恢复也是工作的一部分。在被迫停下之前先自己停。', reversed: '因为不肯停而耗竭，或者一种连想休息都休息不了的焦躁。' },
  54: { upright: '一场代价大于收获的胜利。冲突在双方都留了伤 —— 想想「赢」是不是本来的目标。', reversed: '准备停战了。和解，或者至少决定退出一场赢不好看的仗。' },
  55: { upright: '安静地、有人帮着地把难处留在身后。渡过去并不舒服，但你在往更平的水面走。', reversed: '把旧的麻烦一起带走了，或者搬动只换了风景没换问题。' },
  56: { upright: '有东西正被拿走或藏起来。欺瞒，或者一条只要没人细看就成立的捷径。核实一下你被告知的内容。', reversed: '藏着的事情露出来，或者你决定坦白。不管哪种，隐瞒都在结束。' },
  57: { upright: '被困住，但困住你的更多是想法而不是处境。绑得并不紧，只要你注意到就能走出来。', reversed: '开始看见出口。原以为是笼子的地方，其实有门。' },
  58: { upright: '凌晨三点醒着，什么都显得很大。这里的恐惧大于处境本身 —— 这张牌讲的是焦虑，不是预言。', reversed: '最糟的那些念头正在松手。说出来，它们就会变小。' },
  59: { upright: '某件事彻底结束了。它结束了，装作没结束的代价比接受更高。新的东西只能从这里开始。', reversed: '你活过了这个结束。已经到底，剩下的方向只有往上。' },
  60: { upright: '敏锐的好奇心，以及对信息的饥渴。去问、去读小字、去把那件事学会。', reversed: '说得比想得多，或者收集信息是为了赢辩论而不是为了理解。留意你在转述什么。' },
  61: { upright: '凭信念快速行动。直接能切开阻塞 —— 只是冲之前先瞄一下。', reversed: '快而无判断，或者直白到留下损伤。快速正确，不等于有效。' },
  62: { upright: '看得清楚而且独立，温和但不软。你能把处境看得分明，这是天赋，偶尔也是孤单。', reversed: '清晰变冷，或者把一次受伤变成了关于人的定论。疏离保护你的，超过了它需要保护的。' },
  63: { upright: '靠理性建立的权威。公正、有原则，能做难的决定并且讲得清。规则在这里是帮你的。', reversed: '规则用来控制而不是求公正，或者逻辑已经不把人算进去了。' },
  64: { upright: '一个摸得着的机会 —— 一份工作、一笔生意、一颗真能长起来的种子。小而实胜过大而虚。', reversed: '机会错过了，或者建在不稳的底子上。投入前先看数字。' },
  65: { upright: '有本事的兼顾。两头都合理，你也应付得来 —— 但这个平衡是你在扶着，不是它自己站着。', reversed: '掉了一个球，或者全掉了。清单上必须去掉点东西。' },
  66: { upright: '有技术的协作。你的活被懂它的人看见了，而你在造的东西也不是一双手能造完的。', reversed: '出力不对等、角色不清，或者做的事没人记在你名下。把谁做了什么说清楚。' },
  67: { upright: '把手里的东西紧紧攥住。是谨慎，还是打扮成谨慎的恐惧 —— 值得分清是哪一个。', reversed: '手在松开，或者已经失去。到头来慷慨的成本，比一直攥着更低。' },
  68: { upright: '亮着灯的窗外很冷。困境，以及那种以为只能一个人扛的特有的孤单。帮助比看起来更近 —— 门就在那儿。', reversed: '恢复开始了。到头来，开口求助才是有用的那件事。' },
  69: { upright: '给与受都合乎分寸。不是交易的慷慨，不制造人情债的帮助。', reversed: '给得附带条件，或者一种让人一直依赖下去的施与。想想这份给到底是为了什么。' },
  70: { upright: '等自己种下的东西。活已经干完了，现在的答案是耐心，而这比再多使劲更难。', reversed: '不耐烦而提前把作物拔出来，或者把力气浇在不会长东西的地上。继续之前先重估。' },
  71: { upright: '手艺与重复。靠练而不是靠天赋变好 —— 过程无聊，结果无敌。', reversed: '只是在走流程，或者完美主义让东西永远出不来。先交出去，再往上改。' },
  72: { upright: '挣来的自足。独自待着、待在自己造的东西里都很舒服 —— 这份独立来自劳动，不是运气。', reversed: '舒适变成了孤立，或者成功只拿来和别人比。想想这份独立在保护什么。' },
  73: { upright: '能留下去的安稳，那种比你活得更久的安稳。家庭、传承、造得扎实的机构 —— 这里想得远是有回报的。', reversed: '钱在拉紧一个家，或者传承已经变成了义务。没有温度的财富很贵。' },
  74: { upright: '一个用功的开始。一项新技能、一门课、第一份工作 —— 起点谦卑，路径是真的。', reversed: '分心，或者计划一直停在计划。开始得比「让人满意」再小一点。' },
  75: { upright: '慢而可靠的推进。不刺激，但完全可托付 —— 是会把开始的事做完的那种人。', reversed: '卡在同一道沟里，或者谨慎到什么都不动。改一件事就好。' },
  76: { upright: '务实的温暖。会去张罗的人 —— 一个家、一个团队、一片园子 —— 而且张罗得很在行。', reversed: '给到自己一点不剩，或者对安稳的担心挤掉了享受它的余地。' },
  77: { upright: '把物质上的成功握得有智慧。可靠、务实、对造出来的东西大方 —— 一种成熟的领导。', reversed: '把成功攥得太紧，或者拿地位来控制人。它只有和谦逊在一起才稳。' },
};
