import type { Test } from './types';

/**
 * 중국어 심리테스트.
 *
 * test-en.ts와 같은 5주제·같은 slug·같은 문항 수·같은 점수 구조로 맞췄다.
 * hreflang이 en↔zh를 slug로 짝지어야 하고, 구조가 어긋나면 같은 답을 골라도
 * 언어별로 다른 결과가 나온다.
 */
export const TESTS_ZH: Test[] = [
  {
    slug: 'social-battery',
    title: '社交电量测试',
    desc: '人群消耗你的速度，以及什么才真正让你回血',
    icon: '🔋',
    category: '性格',
    questions: [
      { q: '和人相处一整天之后，你最想要什么？', opts: [{ text: '完全独处', score: 0 }, { text: '安静的陪伴', score: 1 }, { text: '和一个朋友做点轻松的事', score: 2 }, { text: '把夜晚继续下去', score: 3 }] },
      { q: '空着的晚上突然收到临时邀约。', opts: [{ text: '我几乎会条件反射地拒绝', score: 0 }, { text: '我会认真掂量', score: 1 }, { text: '我通常会答应', score: 2 }, { text: '还没看清内容就答应了', score: 3 }] },
      { q: '在群聊场合，你通常：', opts: [{ text: '听着，很少开口', score: 0 }, { text: '主要和旁边的人说话', score: 1 }, { text: '自在地加入', score: 2 }, { text: '最后变成主导的人', score: 3 }] },
      { q: '一个完全没安排的周末让你觉得：', opts: [{ text: '这是最好的结果', score: 0 }, { text: '不错，再加一个小安排', score: 1 }, { text: '有点空', score: 2 }, { text: '像是哪里出了问题', score: 3 }] },
      { q: '在热闹的开放式办公室工作：', opts: [{ text: '我完全没法专注', score: 0 }, { text: '戴耳机还能应付', score: 1 }, { text: '大多数时候没问题', score: 2 }, { text: '反而让我更有劲', score: 3 }] },
      { q: '你到了一个只认识一个人的聚会。', opts: [{ text: '我整晚都待在他旁边', score: 0 }, { text: '通过他认识几个人', score: 1 }, { text: '我会四处走走和几拨人聊', score: 2 }, { text: '结束时半场人我都认识了', score: 3 }] },
      { q: '手机响了，是陌生号码。', opts: [{ text: '我从来不接', score: 0 }, { text: '让它响完，之后再看', score: 1 }, { text: '有空就接', score: 2 }, { text: '立刻接起来', score: 3 }] },
      { q: '对于和一群人的长途旅行，你的感觉是：', opts: [{ text: '我需要自己的房间和自己的节奏', score: 0 }, { text: '还行，但要有独处的间隙', score: 1 }, { text: '我挺享受的', score: 2 }, { text: '人越多越好', score: 3 }] },
      { q: '一个愉快的社交夜晚之后你感觉：', opts: [{ text: '即使很顺利，也很累', score: 0 }, { text: '满足，但可以收工了', score: 1 }, { text: '兴奋劲还在', score: 2 }, { text: '明天还想再来一次', score: 3 }] },
      { q: '成为全场焦点这件事：', opts: [{ text: '真的让我不自在', score: 0 }, { text: '短暂还行', score: 1 }, { text: '在合适的场合挺享受', score: 2 }, { text: '那是我最像自己的时候', score: 3 }] },
    ],
    results: [
      { min: 0, max: 7, emoji: '🕯️', title: '深度回血型', color: 'from-slate-500 to-slate-700',
        desc: '你的电量在人群里消耗得很快，只有独处才补得回来。这不是害羞，而是实实在在的能量成本。越早围绕它来安排，而不是为它道歉，你的每一周就越顺。像安排会议一样，把恢复时间写进日程。',
        traits: ['需要独处', '专注力深', '有选择性', '沉稳'] },
      { min: 8, max: 14, emoji: '🌙', title: '安静蓄电型', color: 'from-indigo-500 to-violet-600',
        desc: '你应付得了社交，但事后要还债。小圈子和熟人几乎不耗你，大型陌生场合则消耗很大。每周守住一个真正空着的晚上，通常就足以维持状态。',
        traits: ['小圈子', '独处恢复', '善思考', '一对一时温暖'] },
      { min: 15, max: 21, emoji: '🌤️', title: '均衡续航型', color: 'from-sky-500 to-blue-600',
        desc: '你在社交与独处之间切换得很顺，这是很实用的特质。风险在于消耗积累到一定程度前你不会察觉 —— 在答应第四个晚上的邀约之前先问问自己，而不是之后。',
        traits: ['适应力强', '善社交', '有自觉', '平稳'] },
      { min: 22, max: 30, emoji: '⚡', title: '人群充电型', color: 'from-amber-400 to-orange-500',
        desc: '你的能量来自别人，所以空白的日程对你像是问题而不是休息。不过值得知道的是，独处仍能给你一些社交给不了的东西 —— 哪怕一小段安静，也常能让其他一切更清晰。',
        traits: ['被人群充电', '快速连接', '有表达力', '随性'] },
    ],
  },
  {
    slug: 'stress-style',
    title: '压力应对方式测试',
    desc: '你在压力下的默认反应，以及可以怎么办',
    icon: '🌊',
    category: '身心',
    questions: [
      { q: '截止日期突然提前一周，你的第一反应是：', opts: [{ text: '僵住，盯着它看一会儿', score: 0 }, { text: '先难受一阵，然后开始列清单', score: 1 }, { text: '立刻重新排计划', score: 2 }, { text: '反而有点被激起劲头', score: 3 }] },
      { q: '有压力时，你的睡眠：', opts: [{ text: '彻底垮掉', score: 0 }, { text: '变短', score: 1 }, { text: '基本正常', score: 2 }, { text: '不受影响', score: 3 }] },
      { q: '压力下你会和别人说吗？', opts: [{ text: '完全不说，我会沉默', score: 0 }, { text: '事情过去之后才说', score: 1 }, { text: '只跟一个信任的人说', score: 2 }, { text: '当下就坦白说', score: 3 }] },
      { q: '压力下你的身体：', opts: [{ text: '头痛、胃痛、紧绷，全都来', score: 0 }, { text: '有一个固定的症状', score: 1 }, { text: '只有轻微紧绷', score: 2 }, { text: '几乎没感觉', score: 3 }] },
      { q: '出了差错之后你通常：', opts: [{ text: '反复回放好几天', score: 0 }, { text: '难受一晚上', score: 1 }, { text: '记下教训然后往前走', score: 2 }, { text: '几乎立刻就翻篇', score: 3 }] },
      { q: '任务堆得太多时，你会：', opts: [{ text: '一件都做不下去', score: 0 }, { text: '先做最容易的', score: 1 }, { text: '排优先级，从最上面开始', score: 2 }, { text: '分派出去或砍掉一些', score: 3 }] },
      { q: '工作上被批评，你的感受是：', opts: [{ text: '很重，而且持续很久', score: 0 }, { text: '当下难受，之后会淡', score: 1 }, { text: '当作信息', score: 2 }, { text: '当作有用的东西', score: 3 }] },
      { q: '你常用的减压方式是：', opts: [{ text: '我没有', score: 0 }, { text: '刷手机或吃东西', score: 1 }, { text: '散步、运动、泡澡', score: 2 }, { text: '有计划、有规律的安排', score: 3 }] },
      { q: '真正的危机当中，你是：', opts: [{ text: '最先慌的那个', score: 0 }, { text: '发抖但还能做事', score: 1 }, { text: '够冷静', score: 2 }, { text: '全场最稳的人', score: 3 }] },
      { q: '回头看你上一个难熬的月份：', opts: [{ text: '我到现在还背着它', score: 0 }, { text: '花了很久才走出来', score: 1 }, { text: '恢复得还算可以', score: 2 }, { text: '我因此变得更好了', score: 3 }] },
    ],
    results: [
      { min: 0, max: 7, emoji: '🫧', title: '全盘吸收型', color: 'from-blue-500 to-indigo-700',
        desc: '压力会直接穿过防线留在你的身体里。这值得认真对待，而不是硬撑过去 —— 压力表现为失眠和身体症状的模式往往会累积。一个具体的出口，加上一个可以说的人，通常比任何意志力都管用。',
        traits: ['高度敏感', '内化压力', '需要恢复期', '共情力强'] },
      { min: 8, max: 14, emoji: '🌧️', title: '缓慢消化型', color: 'from-sky-500 to-blue-600',
        desc: '难熬的时期你都撑得过去，但代价不小，恢复也比你希望的慢。有用的做法是更早察觉 —— 该介入的时机是睡眠刚开始变化的时候，而不是一切都堆起来之后。',
        traits: ['能扛', '恢复慢', '尽责', '安静的韧性'] },
      { min: 15, max: 21, emoji: '⛅', title: '负重稳定型', color: 'from-emerald-500 to-teal-600',
        desc: '压力不会让你脱轨，主要是因为你能一边感受一边继续运转。风险在于：因为还在工作就以为自己没事。在压力下高产，并不等于不受影响。',
        traits: ['务实', '沉着', '恢复良好', '可靠'] },
      { min: 22, max: 30, emoji: '🗿', title: '风暴中的定海针', color: 'from-slate-600 to-slate-800',
        desc: '出事时你依然稳得住，所以危机中别人会转向你。要留意的是：这么稳的人常常低估累积的负荷，而周围的人也会渐渐不再问「你还好吗」。',
        traits: ['临危不乱', '果断', '被信任', '低反应性'] },
    ],
  },
  {
    slug: 'decision-style',
    title: '决策方式测试',
    desc: '凭直觉、讲逻辑，还是在两者之间',
    icon: '🧭',
    category: '性格',
    questions: [
      { q: '和朋友决定去哪吃饭时：', opts: [{ text: '我会先看完所有评价', score: 0 }, { text: '我会看几条', score: 1 }, { text: '我会推荐一家自己喜欢的', score: 2 }, { text: '看着不错就定了', score: 3 }] },
      { q: '一笔大额消费，你会考虑多久？', opts: [{ text: '好几周，还会做表格', score: 0 }, { text: '几天', score: 1 }, { text: '一两天', score: 2 }, { text: '感觉对了就买', score: 3 }] },
      { q: '决定之后，你会回头再想吗？', opts: [{ text: '一直在想', score: 0 }, { text: '有时候会', score: 1 }, { text: '很少', score: 2 }, { text: '不会，定了就定了', score: 3 }] },
      { q: '有人来问你的意见，你会：', opts: [{ text: '先问很多细节', score: 0 }, { text: '把选项摆出来', score: 1 }, { text: '说我会怎么做', score: 2 }, { text: '直接给答案', score: 3 }] },
      { q: '两个都不错、分不出高下时：', opts: [{ text: '我会拖到情况替我决定', score: 0 }, { text: '我会列个清单', score: 1 }, { text: '我会先睡一觉再说', score: 2 }, { text: '我跟着直觉走', score: 3 }] },
      { q: '你多常后悔自己的决定？', opts: [{ text: '经常，而且会想很久', score: 0 }, { text: '有时候', score: 1 }, { text: '很少', score: 2 }, { text: '几乎从不', score: 3 }] },
      { q: '会上没人肯拍板时：', opts: [{ text: '我等别人先说', score: 0 }, { text: '我会问还漏了什么', score: 1 }, { text: '我提一个方案', score: 2 }, { text: '我直接定下来往下走', score: 3 }] },
      { q: '你相信对一个人的第一印象吗？', opts: [{ text: '完全不信', score: 0 }, { text: '有一点', score: 1 }, { text: '通常信', score: 2 }, { text: '基本上完全相信', score: 3 }] },
      { q: '新信息和你的选择相矛盾时：', opts: [{ text: '我会把整个决定推翻重来', score: 0 }, { text: '我会认真重新考虑', score: 1 }, { text: '重要的话就调整', score: 2 }, { text: '我通常还是照原计划', score: 3 }] },
      { q: '你决策上最大的坑是：', opts: [{ text: '根本不做决定', score: 0 }, { text: '决定得太晚', score: 1 }, { text: '少确认了一件事就定了', score: 2 }, { text: '定得太快，来不及改', score: 3 }] },
    ],
    results: [
      { min: 0, max: 7, emoji: '🔍', title: '深思型', color: 'from-slate-500 to-slate-700',
        desc: '你要看到全貌才肯下决定，所以你的决定依据充分但很慢。代价是实实在在的：你在查资料的时候机会就过期了，而悬而未决的焦虑往往比选错一点点更折磨人。给「做决定」这件事本身设一个截止时间，而不只是给结果设。',
        traits: ['周全', '风险意识强', '善分析', '不轻易拍板'] },
      { min: 8, max: 14, emoji: '⚖️', title: '权衡型', color: 'from-sky-500 to-indigo-600',
        desc: '你收集到足够信息、感到有把握后就做决定 —— 这是很好的默认模式。要留意的是：最后 10% 的调研常常花掉 90% 的时间，却什么都没改变。',
        traits: ['均衡', '深思熟虑', '务实', '讲道理'] },
      { min: 15, max: 21, emoji: '🎯', title: '拍板型', color: 'from-emerald-500 to-teal-600',
        desc: '信息够了你就快速行动，而且很少回头，这让你在没人肯拍板的场合特别有用。值得保留的一个习惯是：说清楚你押的是哪个前提，这样万一前提错了你能及时发现。',
        traits: ['果断', '自信', '向前推进', '少后悔'] },
      { min: 22, max: 30, emoji: '⚡', title: '直觉型', color: 'from-amber-400 to-rose-500',
        desc: '你相信直觉、行动很快，在瞬息万变的情况下这确实是优势。但在不可逆的事情上就成了风险 —— 有用的规则是：只对无法撤销的决定慢下来，其余保持速度。',
        traits: ['迅速', '直觉强', '行动优先', '果断'] },
    ],
  },
  {
    slug: 'work-style',
    title: '工作风格测试',
    desc: '你实际是怎么把事做完的，而不是你以为该怎么做',
    icon: '💼',
    category: '职场',
    questions: [
      { q: '你状态最好的工作发生在：', opts: [{ text: '一整段不被打断的时间里', score: 0 }, { text: '几段专注的时段里', score: 1 }, { text: '一天里的多个短时段', score: 2 }, { text: '有什么紧急的时候', score: 3 }] },
      { q: '你的待办清单是：', opts: [{ text: '详细且持续维护的', score: 0 }, { text: '大致列着、基本照做', score: 1 }, { text: '几条备注', score: 2 }, { text: '在脑子里', score: 3 }] },
      { q: '接到一个没有截止日期的大项目：', opts: [{ text: '我自己定一个并严格执行', score: 0 }, { text: '我定一个，基本能守住', score: 1 }, { text: '我准备好了再开始', score: 2 }, { text: '等到有什么逼着我才动', score: 3 }] },
      { q: '卡住的时候你会：', opts: [{ text: '继续硬磕', score: 0 }, { text: '短暂休息后再回来', score: 1 }, { text: '切换到别的任务', score: 2 }, { text: '立刻找人问', score: 3 }] },
      { q: '一周里的会议：', opts: [{ text: '会把我一整天打碎', score: 0 }, { text: '集中安排的话还能忍', score: 1 }, { text: '是正常的一部分', score: 2 }, { text: '是我思考得最好的时候', score: 3 }] },
      { q: '你更喜欢的工作方式是：', opts: [{ text: '深入、独自完成', score: 0 }, { text: '基本独立，定期同步', score: 1 }, { text: '协作式的', score: 2 }, { text: '一直在对话之中', score: 3 }] },
      { q: '你和截止日期的关系：', opts: [{ text: '我会提前很久做完', score: 0 }, { text: '我会从容地完成', score: 1 }, { text: '我会刚好赶上', score: 2 }, { text: '我在最后关头状态最好', score: 3 }] },
      { q: '遇到一个你觉得无聊的任务：', opts: [{ text: '我先做掉它清空', score: 0 }, { text: '我把它排进日程', score: 1 }, { text: '我会拖一阵子', score: 2 }, { text: '它会一直放着', score: 3 }] },
      { q: '对进行中工作的反馈：', opts: [{ text: '我宁愿先做完再说', score: 0 }, { text: '在几个节点上要', score: 1 }, { text: '相当频繁', score: 2 }, { text: '边做边一直要', score: 3 }] },
      { q: '你的工作台面：', opts: [{ text: '得整理干净才开始', score: 0 }, { text: '大致有条理', score: 1 }, { text: '有生活痕迹', score: 2 }, { text: '混乱但我用得顺', score: 3 }] },
    ],
    results: [
      { min: 0, max: 7, emoji: '🎯', title: '深度工作型', color: 'from-indigo-500 to-violet-700',
        desc: '你在长而安静的时段里做出最好的工作，一切都围绕保护这些时段来安排。这确实带来深度，但也让你很怕被打断 —— 值得投入的是：每周绝对守住两三个整块时间，其余一切都可以灵活。',
        traits: ['专注', '有结构', '自我驱动', '怕被打断'] },
      { min: 8, max: 14, emoji: '📋', title: '稳健计划型', color: 'from-sky-500 to-blue-600',
        desc: '你会计划、会控速，事情都在你说的时间点交付。这份可靠比多数人以为的更有价值。偶尔检查一下：计划还在为工作服务，而不是反过来。',
        traits: ['可靠', '有条理', '节奏稳', '一致'] },
      { min: 15, max: 21, emoji: '🔄', title: '灵活推进型', color: 'from-emerald-500 to-teal-600',
        desc: '你分段作业、切换自如，对突发状况反应很快，很适合节奏快的工作。要留意的是：不断切换会让人感觉很高产，却让真正难的问题更难收尾。',
        traits: ['适应力强', '响应快', '善协作', '迅速'] },
      { min: 22, max: 30, emoji: '🔥', title: '压力驱动型', color: 'from-amber-400 to-rose-500',
        desc: '紧迫感才是打开你的开关，你在截止线上产出很好。这套是管用的 —— 直到两个截止日撞在一起。人为制造更早、更小的截止点是标准解法，而且比试图把自己变成另一种人更有效。',
        traits: ['压力下高效', '善临场发挥', '有冲劲', '被截止日驱动'] },
    ],
  },
  {
    slug: 'love-language',
    title: '你表达爱的方式',
    desc: '你如何表达在乎，以及你希望被怎样对待',
    icon: '💝',
    category: '情感',
    questions: [
      { q: '伴侣今天过得很糟，你会：', opts: [{ text: '明确告诉他你欣赏他什么', score: 0 }, { text: '安静地陪着，不多说', score: 1 }, { text: '默默替他分担一件事', score: 2 }, { text: '带一样他喜欢的东西回来', score: 3 }] },
      { q: '什么最让你感到被在乎？', opts: [{ text: '被亲口说出来', score: 0 }, { text: '全心全意的相处时间', score: 1 }, { text: '有人替我处理好某件事', score: 2 }, { text: '一件用心的东西', score: 3 }] },
      { q: '纪念日你的直觉反应是：', opts: [{ text: '写点什么', score: 0 }, { text: '安排一整天在一起', score: 1 }, { text: '做一件他一直需要的实事', score: 2 }, { text: '找到对的那份礼物', score: 3 }] },
      { q: '关系里什么最伤人？', opts: [{ text: '从来听不到「我们挺好的」', score: 0 }, { text: '人在身边心不在', score: 1 }, { text: '什么都留给我一个人扛', score: 2 }, { text: '在重要的那天被忘记', score: 3 }] },
      { q: '朋友正经历难关：', opts: [{ text: '我会告诉他我怎么看他', score: 0 }, { text: '我会空出一个晚上给他', score: 1 }, { text: '我会帮他处理些实际的事', score: 2 }, { text: '我会寄点东西给他', score: 3 }] },
      { q: '你表达想念的方式是：', opts: [{ text: '直接说出来', score: 0 }, { text: '立刻挪出时间', score: 1 }, { text: '为他做点什么', score: 2 }, { text: '带样东西回来给他', score: 3 }] },
      { q: '最打动你的称赞是：', opts: [{ text: '关于我这个人的具体评价', score: 0 }, { text: '「我总想和你多待一会儿」', score: 1 }, { text: '「你总是把事情照顾好」', score: 2 }, { text: '「我看到这个就想到你」', score: 3 }] },
      { q: '争执之后，什么最能修复？', opts: [{ text: '听到他仍然珍视我什么', score: 0 }, { text: '好好坐下来谈一次', score: 1 }, { text: '他用行动表示', score: 2 }, { text: '一个说明他有在想的举动', score: 3 }] },
      { q: '伴侣要离开一个月，你会：', opts: [{ text: '写长长的消息', score: 0 }, { text: '雷打不动地约通话', score: 1 }, { text: '把家里都打理好让他不用操心', score: 2 }, { text: '给他寄东西', score: 3 }] },
      { q: '少了哪一样你会最先察觉？', opts: [{ text: '被告知他的感受', score: 0 }, { text: '真正在一起的时间', score: 1 }, { text: '不用开口就被帮到', score: 2 }, { text: '那些用心的小惊喜', score: 3 }] },
    ],
    results: [
      { min: 0, max: 7, emoji: '💬', title: '言语型', color: 'from-sky-500 to-blue-600',
        desc: '你通过说出来的话给予和接收爱。被明确告知别人欣赏你什么，比任何举动都更打动你；而沉默即使没出事，也会被读成疏远。这值得对伴侣说清楚 —— 表达方式不同的人，往往以为这是不言自明的。',
        traits: ['言语表达', '直接', '有表达力', '给人安心'] },
      { min: 8, max: 14, emoji: '⏳', title: '时间型', color: 'from-violet-500 to-purple-600',
        desc: '注意力是你的货币。一个真正在场、放下手机的人，比他能买或能说的任何东西都重要。反过来说，人在身边却心不在，对你来说等于缺席 —— 这值得说出来，而不是憋成怨气。',
        traits: ['在场', '专注', '有耐心', '重视连接'] },
      { min: 15, max: 21, emoji: '🛠️', title: '行动型', color: 'from-emerald-500 to-teal-600',
        desc: '你用做事来表达在乎，也会注意到有人默默处理掉你一直发怵的事。对那些在等着「听到」的人来说，你的爱可能是隐形的 —— 所以偶尔把话也说出来，而不只是做出来。',
        traits: ['务实', '可靠', '观察入微', '不张扬'] },
      { min: 22, max: 30, emoji: '🎁', title: '礼物型', color: 'from-rose-400 to-pink-600',
        desc: '对你来说，一件东西承载的是背后的心意 ——「我看到这个就想到你」才是重点，而不是价格。这也意味着在重要的日子被忘记，杀伤力会格外大，这值得解释清楚，而不是指望别人自己领会。',
        traits: ['用心', '重象征', '注意细节', '珍藏记忆'] },
    ],
  },
];

export const TESTS_ZH_MAP: Record<string, Test> = Object.fromEntries(
  TESTS_ZH.map(t => [t.slug, t]),
);
