import type { Test } from './types.ts';

/**
 * 심리테스트 열두 가지 — 서른두째 묶음.
 *
 * 주제는 기존 228가지와 겹치지 않는 것만 골랐다. 이미 여행 스타일·정리벽·
 * 인내심이 있어서 여기에는 짐 싸는 방식·이사 방식·걷는 속도처럼 그 옆자리를
 * 넣는다.
 *
 * 문항 열 개에 보기마다 1~4점이므로 총점은 10~40이다. 결과 구간 넷이 그
 * 범위를 빈틈없이 덮어야 어떤 점수에서도 결과가 나온다.
 */
export const TESTS_AF: Test[] = [
  {
    slug: 'cooking-style',
    title: '요리 스타일 테스트',
    desc: '레시피 그대로 vs 눈대중 감으로ㅋㅋ 부엌에서 나오는 성격 알아보자 🍳',
    icon: '🍳',
    category: '취미·라이프스타일',
    questions: [
      { q: '처음 만드는 요리를 할 때 나는?', opts: [
        { text: '레시피 그램 단위까지 재서 함', score: 4 },
        { text: '레시피 보되 대충 눈대중', score: 3 },
        { text: '영상 한 번 보고 기억나는 대로', score: 2 },
        { text: '그냥 감으로 넣음', score: 1 }] },
      { q: '간을 볼 때는?', opts: [
        { text: '중간중간 계속 맛봄', score: 4 },
        { text: '마지막에 한 번 봄', score: 3 },
        { text: '냄새로 대충 앎', score: 2 },
        { text: '안 봄, 먹을 때 알게 됨', score: 1 }] },
      { q: '재료가 하나 없을 때?', opts: [
        { text: '사러 나감', score: 4 },
        { text: '비슷한 걸로 대체함', score: 3 },
        { text: '그냥 빼고 함', score: 2 },
        { text: '다른 요리로 바꿈', score: 1 }] },
      { q: '요리하는 동안 주방 상태는?', opts: [
        { text: '쓴 건 바로바로 치움', score: 4 },
        { text: '중간에 한 번 정리', score: 3 },
        { text: '끝나고 몰아서 함', score: 2 },
        { text: '전쟁터, 나중의 내가 알아서', score: 1 }] },
      { q: '칼질할 때 크기는?', opts: [
        { text: '최대한 똑같이 맞춤', score: 4 },
        { text: '비슷하게는 함', score: 3 },
        { text: '들쭉날쭉해도 익으면 됨', score: 2 },
        { text: '크게 대충 썲', score: 1 }] },
      { q: '새 조리도구를 보면?', opts: [
        { text: '용도 알아보고 필요하면 삼', score: 4 },
        { text: '괜찮아 보이면 사기도 함', score: 3 },
        { text: '있는 걸로 어떻게든 함', score: 2 },
        { text: '냄비 하나로 다 됨', score: 1 }] },
      { q: '요리를 망쳤을 때?', opts: [
        { text: '뭐가 문제였는지 되짚어 봄', score: 4 },
        { text: '아쉬워하고 다음엔 조심', score: 3 },
        { text: '그냥 먹음', score: 2 },
        { text: '배달 시킴', score: 1 }] },
      { q: '냉장고 재료 관리는?', opts: [
        { text: '유통기한 순으로 배치함', score: 4 },
        { text: '대충은 알고 있음', score: 3 },
        { text: '열어봐야 앎', score: 2 },
        { text: '가끔 놀라운 걸 발견함', score: 1 }] },
      { q: '누가 내 요리를 먹을 때 나는?', opts: [
        { text: '반응을 계속 살핌', score: 4 },
        { text: '맛있냐고 한 번 물어봄', score: 3 },
        { text: '알아서 먹겠지', score: 2 },
        { text: '나도 같이 처음 먹어봄', score: 1 }] },
      { q: '주말에 요리하는 시간은?', opts: [
        { text: '두세 시간도 즐거움', score: 4 },
        { text: '한 시간쯤이면 적당', score: 3 },
        { text: '삼십 분 넘으면 지침', score: 2 },
        { text: '안 함, 사 먹는 게 맛있음', score: 1 }] },
    ],
    results: [
      { min: 10, max: 22, title: '주방은 최소한만 쓰는 실용파 🥡',
        desc: '요리에 시간 쏟느니 다른 걸 하겠다는 실용파야ㅋㅋ 배달과 밀키트를 잘 골라 쓰고 부엌은 딱 필요한 만큼만 씀. 이 담백함 덕에 저녁 시간이 통째로 남는 게 강점이지. 그래도 라면 말고 하나쯤 자신 있는 메뉴를 만들어 두면 든든해 🥡',
        emoji: '🥡', color: 'from-slate-400 to-gray-600',
        traits: ['실용적', '시간아낌', '배달마스터', '군더더기없음'] },
      { min: 23, max: 24, title: '감으로 만드는 눈대중 요리사 🥄',
        desc: '레시피는 참고만 하고 손 가는 대로 만드는 눈대중파야ㅋㅋ 간도 냄새로 대충 맞추고 재료 없으면 그냥 빼버림. 이 유연함이 부엌에서 스트레스를 안 받게 해주는 강점이야. 맛있게 된 날엔 뭘 넣었는지 적어두면 다음에도 그 맛이 나와 🥄',
        emoji: '🥄', color: 'from-amber-400 to-orange-500',
        traits: ['눈대중', '유연함', '즉흥적', '스트레스없음'] },
      { min: 25, max: 27, title: '레시피 반 감 반 균형러 🍲',
        desc: '기본은 레시피대로 하되 자기 입맛에 맞게 조절할 줄 아는 균형파야ㅋㅋ 간도 보고 정리도 하면서 너무 완벽하려고는 안 함. 이 적당함이 요리를 오래 즐기게 해주는 비결이지 ㅇㅈ. 잘된 레시피를 따로 모아두면 실력이 눈에 띄게 쌓여 🍲',
        emoji: '🍲', color: 'from-emerald-400 to-teal-600',
        traits: ['균형감', '응용력', '꾸준함', '입맛좋음'] },
      { min: 28, max: 40, title: '계량스푼까지 챙기는 정밀 요리사 ⚖️',
        desc: '그램 단위로 재고 칼질 크기까지 맞추는 정밀파야ㅋㅋ 망친 요리도 원인을 찾아내고 냉장고도 유통기한 순으로 관리함. 이 꼼꼼함이 실패 없는 결과를 만들어 주는 강점이지. 가끔은 재료 하나 빼고 대충 해보는 날도 재미있을 거야 ⚖️',
        emoji: '⚖️', color: 'from-violet-500 to-purple-700',
        traits: ['정밀함', '분석적', '완성도', '관리력'] },
    ],
  },
  {
    slug: 'pet-owner-type',
    title: '반려동물 집사 유형 테스트',
    desc: '껌딱지 집사 vs 쿨한 집사ㅋㅋ 너는 어떤 보호자일까 🐾',
    icon: '🐾',
    category: '취미·라이프스타일',
    questions: [
      { q: '집에 들어왔을 때 첫 행동은?', opts: [
        { text: '이름 부르며 바로 찾아감', score: 4 },
        { text: '반겨주면 쓰다듬어 줌', score: 3 },
        { text: '손 씻고 나서 인사', score: 2 },
        { text: '알아서 오면 놀아줌', score: 1 }] },
      { q: '사료를 고를 때는?', opts: [
        { text: '성분표를 다 읽어봄', score: 4 },
        { text: '후기 보고 정함', score: 3 },
        { text: '먹던 거 계속 삼', score: 2 },
        { text: '마트에서 파는 걸로', score: 1 }] },
      { q: '병원에 가는 주기는?', opts: [
        { text: '정기검진 챙겨서 감', score: 4 },
        { text: '접종 때 맞춰 감', score: 3 },
        { text: '아파 보이면 감', score: 2 },
        { text: '거의 안 감', score: 1 }] },
      { q: '외출할 때 마음은?', opts: [
        { text: '계속 신경 쓰여서 확인함', score: 4 },
        { text: '가끔 생각남', score: 3 },
        { text: '나가면 잊음', score: 2 },
        { text: '잘 있겠지 하고 안 걱정', score: 1 }] },
      { q: '휴대폰 사진첩은?', opts: [
        { text: '거의 다 우리 애 사진', score: 4 },
        { text: '꽤 많이 찍음', score: 3 },
        { text: '가끔 찍음', score: 2 },
        { text: '별로 안 찍음', score: 1 }] },
      { q: '장난감이나 간식을 살 때?', opts: [
        { text: '보이면 자꾸 사게 됨', score: 4 },
        { text: '떨어지면 삼', score: 3 },
        { text: '필요할 때만', score: 2 },
        { text: '있는 걸로 충분', score: 1 }] },
      { q: '털이나 발톱 관리는?', opts: [
        { text: '주기 정해서 꼬박꼬박', score: 4 },
        { text: '길어지면 함', score: 3 },
        { text: '눈에 띄면 함', score: 2 },
        { text: '미용실에 맡김', score: 1 }] },
      { q: '이상한 걸 먹었을 때?', opts: [
        { text: '바로 병원에 전화함', score: 4 },
        { text: '찾아보고 판단함', score: 3 },
        { text: '지켜봄', score: 2 },
        { text: '괜찮겠지 함', score: 1 }] },
      { q: '여행 계획을 세울 때?', opts: [
        { text: '같이 갈 수 있는 곳부터 봄', score: 4 },
        { text: '맡길 곳 먼저 알아봄', score: 3 },
        { text: '가족한테 부탁함', score: 2 },
        { text: '짧게 다녀오면 됨', score: 1 }] },
      { q: '반려동물이 나를 무시할 때?', opts: [
        { text: '서운해서 계속 말 걸어봄', score: 4 },
        { text: '왜 그러지 하고 살펴봄', score: 3 },
        { text: '기분 있나 보다 함', score: 2 },
        { text: '나도 내 할 일 함', score: 1 }] },
    ],
    results: [
      { min: 10, max: 22, title: '적당한 거리의 쿨한 집사 😎',
        desc: '지나치게 매달리지 않고 각자의 시간을 존중하는 쿨한 집사야ㅋㅋ 알아서 잘 지내게 두고 필요할 때만 챙김. 이 여유가 반려동물에게도 편한 공간을 만들어 주는 강점이지. 정기검진 날짜만 달력에 넣어두면 놓칠 게 없어 😎',
        emoji: '😎', color: 'from-sky-400 to-blue-600',
        traits: ['담백함', '독립적', '여유', '존중'] },
      { min: 23, max: 24, title: '할 건 하는 무난한 보호자 🙂',
        desc: '호들갑 떨지는 않지만 챙길 건 챙기는 무난한 보호자야ㅋㅋ 접종도 때 되면 맞히고 아파 보이면 바로 병원 감. 이 균형이 서로 스트레스 없는 사이를 만들어 주지. 사진 좀 더 찍어두면 나중에 보물이 될 거야 🙂',
        emoji: '🙂', color: 'from-emerald-400 to-teal-600',
        traits: ['무난함', '책임감', '균형', '차분함'] },
      { min: 25, max: 27, title: '꼼꼼히 챙기는 다정한 집사 🧡',
        desc: '성분표도 읽고 사진도 많이 찍는 다정한 집사야ㅋㅋ 외출하면 생각나고 이상한 낌새엔 바로 찾아봄. 이 세심함이 아픈 걸 일찍 발견하게 해주는 큰 장점이지 ㅇㅈ. 가끔은 혼자 있는 시간도 필요하다는 걸 기억해 🧡',
        emoji: '🧡', color: 'from-amber-400 to-orange-500',
        traits: ['세심함', '다정함', '관찰력', '정성'] },
      { min: 28, max: 40, title: '온 세상이 우리 애인 껌딱지 집사 💗',
        desc: '사진첩도 대화 주제도 전부 우리 애인 껌딱지 집사야ㅋㅋ 여행지도 같이 갈 수 있는 곳부터 고르고 무시당하면 서운해함. 이 애정이 최고의 돌봄으로 이어지는 건 분명하지. 다만 네 일상도 챙겨야 오래오래 함께할 수 있어 💗',
        emoji: '💗', color: 'from-pink-400 to-rose-600',
        traits: ['찐사랑', '헌신적', '껌딱지', '정성만렙'] },
    ],
  },
  {
    slug: 'photo-style',
    title: '사진 찍는 스타일 테스트',
    desc: '백 장 찍고 고르는 타입 vs 한 장이면 끝ㅋㅋ 네 촬영 스타일 알아보자 📸',
    icon: '📸',
    category: '취미·라이프스타일',
    questions: [
      { q: '풍경을 만났을 때 나는?', opts: [
        { text: '각도 바꿔가며 여러 장', score: 4 },
        { text: '두세 장 찍음', score: 3 },
        { text: '한 장이면 됨', score: 2 },
        { text: '눈으로만 봄', score: 1 }] },
      { q: '음식이 나오면?', opts: [
        { text: '위에서 옆에서 다 찍음', score: 4 },
        { text: '한 장 찍고 먹음', score: 3 },
        { text: '가끔 찍음', score: 2 },
        { text: '바로 먹음', score: 1 }] },
      { q: '보정은 어떻게?', opts: [
        { text: '밝기와 색감을 하나씩 손봄', score: 4 },
        { text: '필터 하나 씌움', score: 3 },
        { text: '자동 보정만', score: 2 },
        { text: '안 함', score: 1 }] },
      { q: '사진첩 정리는?', opts: [
        { text: '앨범 나눠서 관리함', score: 4 },
        { text: '가끔 몰아서 지움', score: 3 },
        { text: '용량 찰 때만', score: 2 },
        { text: '그냥 쌓아둠', score: 1 }] },
      { q: '단체사진을 찍을 때 나는?', opts: [
        { text: '자리 잡아주고 여러 번 찍음', score: 4 },
        { text: '찍어주는 편', score: 3 },
        { text: '찍히는 쪽', score: 2 },
        { text: '뒤에 숨음', score: 1 }] },
      { q: '여행 중 사진 찍는 시간은?', opts: [
        { text: '멈춰서 제대로 찍음', score: 4 },
        { text: '걸으면서 몇 장', score: 3 },
        { text: '기억할 만한 데서만', score: 2 },
        { text: '거의 안 찍음', score: 1 }] },
      { q: '내 사진이 마음에 안 들면?', opts: [
        { text: '다시 찍자고 함', score: 4 },
        { text: '아쉬워하지만 넘어감', score: 3 },
        { text: '그러려니 함', score: 2 },
        { text: '어차피 안 봄', score: 1 }] },
      { q: '카메라 앱 설정은?', opts: [
        { text: '격자와 수동 설정을 켜둠', score: 4 },
        { text: '몇 가지는 바꿔둠', score: 3 },
        { text: '기본 그대로', score: 2 },
        { text: '뭐가 있는지 모름', score: 1 }] },
      { q: '남이 찍어준 사진을 볼 때?', opts: [
        { text: '구도가 먼저 보임', score: 4 },
        { text: '잘 나왔는지 봄', score: 3 },
        { text: '얼굴만 봄', score: 2 },
        { text: '슥 넘김', score: 1 }] },
      { q: '일 년 전 오늘 사진이 뜨면?', opts: [
        { text: '한참 들여다봄', score: 4 },
        { text: '반갑게 봄', score: 3 },
        { text: '잠깐 보고 넘김', score: 2 },
        { text: '알림 꺼둠', score: 1 }] },
    ],
    results: [
      { min: 10, max: 22, title: '눈으로 남기는 무촬영파 👀',
        desc: '카메라 들이대기보다 그냥 보는 걸 택하는 무촬영파야ㅋㅋ 순간에 온전히 있고 사진첩은 늘 가벼움. 이 태도가 여행을 더 진하게 만들어 주는 건 분명하지. 그래도 일 년에 몇 장은 남겨두면 나중에 고마울 거야 👀',
        emoji: '👀', color: 'from-slate-400 to-gray-600',
        traits: ['현재집중', '가벼움', '기억파', '군더더기없음'] },
      { min: 23, max: 24, title: '기억할 만할 때만 누르는 선택파 🙂',
        desc: '아무 데서나 찍지 않고 남길 만한 순간에만 카메라를 드는 선택파야ㅋㅋ 보정도 자동에 맡기고 정리도 가끔 몰아서 함. 이 절제가 사진첩을 볼 만하게 유지해 주지. 앨범만 나눠두면 찾기가 훨씬 쉬워져 🙂',
        emoji: '🙂', color: 'from-emerald-400 to-teal-600',
        traits: ['선택적', '절제', '무난함', '실용적'] },
      { min: 25, max: 27, title: '몇 장은 꼭 남기는 기록파 🗂️',
        desc: '음식도 풍경도 한두 장은 꼭 남기고 필터도 씌우는 기록파야ㅋㅋ 단체사진은 주로 찍어주는 쪽이고 일 년 전 사진도 반갑게 봄. 이 부지런함이 나중에 큰 선물이 되지 ㅇㅈ. 잘 나온 것만 따로 모아두면 더 좋아 🗂️',
        emoji: '🗂️', color: 'from-amber-400 to-orange-500',
        traits: ['기록성', '꾸준함', '다정함', '추억파'] },
      { min: 28, max: 40, title: '백 장 찍고 한 장 고르는 촬영러 📷',
        desc: '각도 바꿔가며 백 장 찍고 보정까지 하나씩 손보는 촬영러야ㅋㅋ 격자도 켜두고 남의 사진에서 구도부터 보임. 이 집요함이 남들은 못 건지는 한 장을 만들어 내지. 가끔은 카메라 내리고 그냥 보는 시간도 챙겨봐 📷',
        emoji: '📷', color: 'from-violet-500 to-purple-700',
        traits: ['집요함', '구도감각', '보정력', '기록광'] },
    ],
  },
  {
    slug: 'packing-style',
    title: '짐 싸는 스타일 테스트',
    desc: '떠나기 일주일 전 vs 나가기 삼십 분 전ㅋㅋ 네 짐 싸는 법 알아보자 🧳',
    icon: '🧳',
    category: '취미·라이프스타일',
    questions: [
      { q: '짐을 싸기 시작하는 시점은?', opts: [
        { text: '며칠 전부터 조금씩', score: 4 },
        { text: '전날 저녁', score: 3 },
        { text: '전날 밤늦게', score: 2 },
        { text: '나가기 직전', score: 1 }] },
      { q: '짐 목록은?', opts: [
        { text: '적어두고 하나씩 지움', score: 4 },
        { text: '머릿속으로 정리함', score: 3 },
        { text: '생각나는 대로', score: 2 },
        { text: '목록이 뭐임', score: 1 }] },
      { q: '가방 안 정리는?', opts: [
        { text: '파우치로 종류별로 나눔', score: 4 },
        { text: '옷과 세면도구만 분리', score: 3 },
        { text: '대충 넣음', score: 2 },
        { text: '눌러서 닫음', score: 1 }] },
      { q: '옷은 며칠치를 챙기나?', opts: [
        { text: '일정에 맞춰 정확히', score: 4 },
        { text: '한 벌 정도 여유', score: 3 },
        { text: '넉넉하게 더', score: 2 },
        { text: '일단 많이', score: 1 }] },
      { q: '충전기와 케이블은?', opts: [
        { text: '전용 파우치에 다 모아둠', score: 4 },
        { text: '한곳에 넣음', score: 3 },
        { text: '생각나면 챙김', score: 2 },
        { text: '자주 두고 옴', score: 1 }] },
      { q: '상비약은?', opts: [
        { text: '종류별로 챙김', score: 4 },
        { text: '기본만 챙김', score: 3 },
        { text: '가끔 챙김', score: 2 },
        { text: '현지에서 사면 됨', score: 1 }] },
      { q: '돌아올 때 가방은?', opts: [
        { text: '갈 때처럼 정리해서 옴', score: 4 },
        { text: '대충 접어서 넣음', score: 3 },
        { text: '쑤셔 넣음', score: 2 },
        { text: '가방이 하나 더 늘어남', score: 1 }] },
      { q: '빠뜨린 걸 알았을 때?', opts: [
        { text: '거의 그런 일이 없음', score: 4 },
        { text: '아쉽지만 대체함', score: 3 },
        { text: '현지에서 삼', score: 2 },
        { text: '없으면 없는 대로', score: 1 }] },
      { q: '기내용과 부치는 짐 나누기는?', opts: [
        { text: '규정 확인하고 정확히 나눔', score: 4 },
        { text: '중요한 건 기내로', score: 3 },
        { text: '대충 나눔', score: 2 },
        { text: '다 한 가방에', score: 1 }] },
      { q: '가방 무게는?', opts: [
        { text: '집에서 저울로 재봄', score: 4 },
        { text: '들어보고 짐작', score: 3 },
        { text: '공항에서 알게 됨', score: 2 },
        { text: '초과하면 빼면 됨', score: 1 }] },
    ],
    results: [
      { min: 10, max: 22, title: '삼십 분 만에 끝내는 즉흥 패커 🏃',
        desc: '나가기 직전에 몰아서 싸고도 어떻게든 되는 즉흥 패커야ㅋㅋ 빠뜨려도 현지에서 사면 그만이라는 배짱이 있음. 이 가벼움이 여행을 부담 없이 만들어 주는 강점이지. 여권과 충전기만 미리 챙겨두면 사고는 안 나 🏃',
        emoji: '🏃', color: 'from-slate-400 to-gray-600',
        traits: ['즉흥적', '배짱', '가벼움', '적응력'] },
      { min: 23, max: 24, title: '전날 저녁에 해치우는 실전파 🌙',
        desc: '전날 저녁쯤 앉아서 한 번에 끝내는 실전파야ㅋㅋ 중요한 건 기내로 넣고 옷은 한 벌 정도 여유 있게 챙김. 이 감각이 시간도 아끼고 빠뜨리지도 않게 해주지. 목록 한 번만 적어두면 더 편해질 거야 🌙',
        emoji: '🌙', color: 'from-emerald-400 to-teal-600',
        traits: ['실전형', '효율', '감각적', '무난함'] },
      { min: 25, max: 27, title: '파우치로 나누는 정돈파 🎒',
        desc: '세면도구와 옷을 나누고 케이블은 한곳에 모아두는 정돈파야ㅋㅋ 상비약도 기본은 챙기고 규정도 확인함. 이 정리 감각이 여행 내내 물건 찾는 시간을 없애 주지 ㅇㅈ. 돌아올 때 순서만 정해두면 완벽해 🎒',
        emoji: '🎒', color: 'from-amber-400 to-orange-500',
        traits: ['정돈', '준비성', '균형', '실용성'] },
      { min: 28, max: 40, title: '목록 적고 저울까지 재는 완벽 패커 📋',
        desc: '며칠 전부터 목록 지워가며 싸고 무게까지 집에서 재보는 완벽 패커야ㅋㅋ 파우치로 종류별로 나누고 빠뜨리는 일이 거의 없음. 이 철저함이 여행에서 변수를 확 줄여주지. 가끔은 한 칸 비워두고 떠나는 것도 재미있어 📋',
        emoji: '📋', color: 'from-violet-500 to-purple-700',
        traits: ['철저함', '계획성', '무결점', '체계적'] },
    ],
  },
  {
    slug: 'note-taking',
    title: '필기 스타일 테스트',
    desc: '형광펜 다섯 자루 vs 그냥 검정 하나ㅋㅋ 네 필기 습관 알아보자 ✏️',
    icon: '✏️',
    category: '자기계발',
    questions: [
      { q: '수업이나 회의 중 나는?', opts: [
        { text: '거의 다 받아 적음', score: 4 },
        { text: '중요한 것만 적음', score: 3 },
        { text: '가끔 적음', score: 2 },
        { text: '듣기만 함', score: 1 }] },
      { q: '필기 도구는?', opts: [
        { text: '색깔별로 여러 자루', score: 4 },
        { text: '두세 색 씀', score: 3 },
        { text: '한 자루면 됨', score: 2 },
        { text: '아무거나 있는 걸로', score: 1 }] },
      { q: '노트를 다시 보는 일은?', opts: [
        { text: '자주 꺼내 봄', score: 4 },
        { text: '시험이나 발표 전에', score: 3 },
        { text: '거의 안 봄', score: 2 },
        { text: '어디 뒀는지 모름', score: 1 }] },
      { q: '들으면서 못 따라갈 때?', opts: [
        { text: '표시해 두고 나중에 채움', score: 4 },
        { text: '핵심만 적고 넘어감', score: 3 },
        { text: '그냥 놓침', score: 2 },
        { text: '적기를 포기함', score: 1 }] },
      { q: '노트 정리 방식은?', opts: [
        { text: '나만의 틀이 정해져 있음', score: 4 },
        { text: '제목과 항목 정도는 나눔', score: 3 },
        { text: '줄줄이 씀', score: 2 },
        { text: '여백에 흩어져 있음', score: 1 }] },
      { q: '종이와 화면 중에?', opts: [
        { text: '용도에 따라 나눠 씀', score: 4 },
        { text: '주로 한쪽을 씀', score: 3 },
        { text: '되는 대로', score: 2 },
        { text: '거의 안 씀', score: 1 }] },
      { q: '그림이나 도표를 그리나?', opts: [
        { text: '관계를 그림으로 정리함', score: 4 },
        { text: '가끔 화살표 정도', score: 3 },
        { text: '거의 글로만', score: 2 },
        { text: '낙서만 함', score: 1 }] },
      { q: '읽은 책에 대해서는?', opts: [
        { text: '요약과 생각을 따로 남김', score: 4 },
        { text: '인상 깊은 문장만 적음', score: 3 },
        { text: '접어만 둠', score: 2 },
        { text: '아무것도 안 남김', score: 1 }] },
      { q: '남이 내 노트를 본다면?', opts: [
        { text: '그대로 봐도 이해될 것', score: 4 },
        { text: '설명 좀 해주면 될 것', score: 3 },
        { text: '나만 알아볼 것', score: 2 },
        { text: '나도 못 알아볼 것', score: 1 }] },
      { q: '한 해가 지난 노트는?', opts: [
        { text: '정리해서 보관함', score: 4 },
        { text: '일단 두고 봄', score: 3 },
        { text: '어딘가 쌓여 있음', score: 2 },
        { text: '버림', score: 1 }] },
    ],
    results: [
      { min: 10, max: 22, title: '머리로 담는 무필기파 🧠',
        desc: '적기보다 듣는 데 집중하는 무필기파야ㅋㅋ 노트가 없어도 흐름은 잡고 있고 손이 자유로움. 이 방식이 대화나 회의에서 반응을 빠르게 해주는 강점이지. 딱 세 줄만 남기는 습관을 들이면 한 달 뒤가 달라져 🧠',
        emoji: '🧠', color: 'from-slate-400 to-gray-600',
        traits: ['집중력', '기억의존', '가벼움', '즉응력'] },
      { min: 23, max: 24, title: '핵심만 골라 적는 요약파 📝',
        desc: '다 받아 적지 않고 중요한 것만 골라 적는 요약파야ㅋㅋ 펜 한두 자루면 충분하고 시험 전엔 꺼내 봄. 이 선별력이 시간을 아껴주는 실속 있는 방식이지. 제목만 붙여두면 나중에 찾기가 쉬워져 📝',
        emoji: '📝', color: 'from-emerald-400 to-teal-600',
        traits: ['선별력', '효율', '실속', '간결함'] },
      { min: 25, max: 27, title: '틀을 갖춘 정리형 필기러 📒',
        desc: '제목과 항목을 나누고 화살표로 관계까지 그리는 정리형이야ㅋㅋ 책도 인상 깊은 문장은 따로 남기고 노트도 다시 봄. 이 체계가 배운 걸 실제로 쓰게 만들어 주지 ㅇㅈ. 한 해 지난 노트만 한 번씩 추리면 더 좋아 📒',
        emoji: '📒', color: 'from-amber-400 to-orange-500',
        traits: ['체계성', '정리력', '복습형', '구조적'] },
      { min: 28, max: 40, title: '남이 봐도 이해되는 필기 장인 🖍️',
        desc: '색깔별로 나누고 도표까지 그려 남이 봐도 이해되는 필기 장인이야ㅋㅋ 못 따라간 자리는 표시해 뒀다 채우고 지난 노트도 정리해 보관함. 이 완성도가 네 노트를 자료로 만들어 주지. 다만 적느라 듣기를 놓치지 않게 균형만 챙겨 🖍️',
        emoji: '🖍️', color: 'from-violet-500 to-purple-700',
        traits: ['완성도', '시각화', '자료화', '꼼꼼함'] },
    ],
  },
  {
    slug: 'silence-comfort',
    title: '침묵 견디기 테스트',
    desc: '조용해지면 못 참는 타입? 아무렇지 않은 타입?ㅋㅋ 정적 앞의 너를 알아보자 🤐',
    icon: '🤐',
    category: '성격',
    questions: [
      { q: '대화가 뚝 끊겼을 때 나는?', opts: [
        { text: '아무렇지 않게 그냥 있음', score: 4 },
        { text: '조금 있다 말 꺼냄', score: 3 },
        { text: '어색해서 얼른 화제 찾음', score: 2 },
        { text: '견디기 힘들어 아무 말이나 함', score: 1 }] },
      { q: '엘리베이터에 아는 사람과 둘이면?', opts: [
        { text: '인사만 하고 그냥 감', score: 4 },
        { text: '가벼운 말 한마디', score: 3 },
        { text: '계속 뭔가 말함', score: 2 },
        { text: '계단으로 갈걸 후회함', score: 1 }] },
      { q: '집에 혼자 있을 때 소리는?', opts: [
        { text: '아무것도 안 틀어둠', score: 4 },
        { text: '가끔 음악 틀어둠', score: 3 },
        { text: '거의 늘 뭔가 틀어둠', score: 2 },
        { text: '조용하면 불안함', score: 1 }] },
      { q: '같이 있는 사람이 말이 없으면?', opts: [
        { text: '편한가 보다 함', score: 4 },
        { text: '별생각 없음', score: 3 },
        { text: '기분 상했나 살핌', score: 2 },
        { text: '내가 뭘 잘못했나 걱정됨', score: 1 }] },
      { q: '회의에서 아무도 말 안 할 때?', opts: [
        { text: '기다림', score: 4 },
        { text: '조금 기다렸다 말함', score: 3 },
        { text: '먼저 입을 뗌', score: 2 },
        { text: '못 견디고 바로 말함', score: 1 }] },
      { q: '차 안에서 대화가 없을 때?', opts: [
        { text: '창밖 보며 편히 감', score: 4 },
        { text: '음악 틀면 됨', score: 3 },
        { text: '자꾸 말을 걸게 됨', score: 2 },
        { text: '분위기가 무거워 힘듦', score: 1 }] },
      { q: '혼자 밥 먹을 때는?', opts: [
        { text: '아무것도 안 봐도 됨', score: 4 },
        { text: '가끔 영상 봄', score: 3 },
        { text: '꼭 뭘 틀어둠', score: 2 },
        { text: '혼밥 자체가 어려움', score: 1 }] },
      { q: '통화 중 잠깐 말이 멈추면?', opts: [
        { text: '기다림', score: 4 },
        { text: '별로 신경 안 씀', score: 3 },
        { text: '여보세요 하고 확인함', score: 2 },
        { text: '끊겼나 싶어 조급해짐', score: 1 }] },
      { q: '명상이나 가만히 앉아 있기는?', opts: [
        { text: '어렵지 않음', score: 4 },
        { text: '몇 분은 됨', score: 3 },
        { text: '금방 좀이 쑤심', score: 2 },
        { text: '거의 못 함', score: 1 }] },
      { q: '침묵이 흐를 때 내 마음은?', opts: [
        { text: '오히려 편안함', score: 4 },
        { text: '아무렇지 않음', score: 3 },
        { text: '살짝 불편함', score: 2 },
        { text: '빨리 깨지길 바람', score: 1 }] },
    ],
    results: [
      { min: 10, max: 22, title: '정적을 못 견디는 분위기 채움러 🗣️',
        desc: '조용해지면 마음이 급해져서 얼른 말을 꺼내는 채움러야ㅋㅋ 덕분에 어색한 자리가 금방 풀리고 사람들이 편해함. 이 순발력이 모임에서 큰 몫을 하는 건 분명하지. 다만 침묵이 늘 나쁜 신호는 아니라는 것도 기억해 두면 편해져 🗣️',
        emoji: '🗣️', color: 'from-pink-400 to-rose-600',
        traits: ['분위기메이커', '순발력', '배려', '활발함'] },
      { min: 23, max: 24, title: '조금 어색하면 말 꺼내는 조율러 🙂',
        desc: '정적이 길어지면 슬쩍 화제를 꺼내는 조율러야ㅋㅋ 못 견딜 정도는 아니지만 상대 눈치는 살피는 편. 이 감각이 대화를 자연스럽게 이어주는 강점이지. 가끔은 그냥 두고 봐도 아무 일 없다는 걸 확인해 봐 🙂',
        emoji: '🙂', color: 'from-amber-400 to-orange-500',
        traits: ['눈치빠름', '조율력', '적당함', '사교적'] },
      { min: 25, max: 27, title: '조용해도 괜찮은 담담파 😌',
        desc: '말이 없어도 딱히 불편해하지 않는 담담파야ㅋㅋ 상대가 조용하면 편한가 보다 하고 넘김. 이 여유가 함께 있는 사람도 편하게 만들어 주지 ㅇㅈ. 가끔 먼저 말을 걸면 관계가 더 가까워질 거야 😌',
        emoji: '😌', color: 'from-emerald-400 to-teal-600',
        traits: ['담담함', '여유', '편안함', '안정적'] },
      { min: 28, max: 40, title: '침묵이 오히려 편한 고요파 🍃',
        desc: '아무 소리 없어도 편안하고 오히려 그 시간을 좋아하는 고요파야ㅋㅋ 혼자 밥 먹을 때도 뭘 틀지 않고 가만히 있는 것도 잘함. 이 고요함이 깊이 생각할 힘을 주는 강점이지. 상대는 어색해할 수 있으니 한마디씩만 건네줘 🍃',
        emoji: '🍃', color: 'from-sky-400 to-blue-600',
        traits: ['고요함', '자립적', '사색형', '안정감'] },
    ],
  },
  {
    slug: 'rule-following',
    title: '규칙 지키기 테스트',
    desc: '아무도 안 봐도 지키는 타입? 융통성 있는 타입?ㅋㅋ 네 기준 알아보자 🚦',
    icon: '🚦',
    category: '성격',
    questions: [
      { q: '새벽에 차 없는 횡단보도 빨간불이면?', opts: [
        { text: '초록 될 때까지 기다림', score: 4 },
        { text: '보통 기다림', score: 3 },
        { text: '주변 보고 건넘', score: 2 },
        { text: '그냥 건넘', score: 1 }] },
      { q: '줄이 길고 새치기할 틈이 보이면?', opts: [
        { text: '생각도 안 함', score: 4 },
        { text: '안 함', score: 3 },
        { text: '가끔 흔들림', score: 2 },
        { text: '상황 봐서 함', score: 1 }] },
      { q: '이용약관은?', opts: [
        { text: '중요한 부분은 읽음', score: 4 },
        { text: '훑어봄', score: 3 },
        { text: '거의 안 봄', score: 2 },
        { text: '바로 동의 누름', score: 1 }] },
      { q: '모임에서 정한 규칙이 불편하면?', opts: [
        { text: '지키면서 바꾸자고 말함', score: 4 },
        { text: '일단 지킴', score: 3 },
        { text: '슬쩍 넘어가기도 함', score: 2 },
        { text: '내 방식대로 함', score: 1 }] },
      { q: '분리배출 규정은?', opts: [
        { text: '라벨 떼고 씻어서 함', score: 4 },
        { text: '기본은 지킴', score: 3 },
        { text: '대충 나눔', score: 2 },
        { text: '한 봉투에 넣음', score: 1 }] },
      { q: '반납 기한이 있는 물건은?', opts: [
        { text: '기한 전에 돌려줌', score: 4 },
        { text: '기한에 맞춰 돌려줌', score: 3 },
        { text: '가끔 늦음', score: 2 },
        { text: '자주 늦음', score: 1 }] },
      { q: '규칙이 이상하다고 느낄 때?', opts: [
        { text: '지키면서 문제 제기함', score: 4 },
        { text: '일단 따름', score: 3 },
        { text: '안 지키기도 함', score: 2 },
        { text: '무시함', score: 1 }] },
      { q: '남이 규칙을 어기는 걸 보면?', opts: [
        { text: '신경 쓰이고 말할 때도 있음', score: 4 },
        { text: '속으로 별로라고 생각함', score: 3 },
        { text: '그러려니 함', score: 2 },
        { text: '아무 생각 없음', score: 1 }] },
      { q: '설명서는?', opts: [
        { text: '읽고 그대로 함', score: 4 },
        { text: '한 번 훑음', score: 3 },
        { text: '막히면 봄', score: 2 },
        { text: '안 봄', score: 1 }] },
      { q: '조용히 해달라는 안내가 있으면?', opts: [
        { text: '휴대폰까지 무음으로', score: 4 },
        { text: '말소리를 줄임', score: 3 },
        { text: '남들 하는 만큼', score: 2 },
        { text: '별로 신경 안 씀', score: 1 }] },
    ],
    results: [
      { min: 10, max: 22, title: '상황 따라 움직이는 자유파 🕊️',
        desc: '규칙보다 상황과 효율을 먼저 보는 자유파야ㅋㅋ 굳이 안 지켜도 되는 자리에서는 힘을 빼고 융통성 있게 움직임. 이 유연함이 막힌 일을 뚫는 힘이 되기도 하지. 다만 남에게 피해가 가는 선만 그어두면 문제없어 🕊️',
        emoji: '🕊️', color: 'from-pink-400 to-rose-600',
        traits: ['유연함', '실리적', '자유로움', '융통성'] },
      { min: 23, max: 24, title: '눈치껏 맞추는 균형러 🙂',
        desc: '기본은 지키되 상황을 보며 조절하는 균형러야ㅋㅋ 크게 어기지도 않고 지나치게 매이지도 않음. 이 감각이 어느 자리에서든 잘 섞이게 해주지. 스스로 정한 선 하나만 있으면 흔들릴 일이 없어 🙂',
        emoji: '🙂', color: 'from-amber-400 to-orange-500',
        traits: ['균형감', '적응력', '무난함', '현실적'] },
      { min: 25, max: 27, title: '지킬 건 지키는 신뢰형 🤝',
        desc: '정해진 건 웬만하면 지키고 기한도 잘 맞추는 신뢰형이야ㅋㅋ 규칙이 이상해도 일단 따르고 나서 얘기하는 편. 이 태도가 같이 일할 때 큰 믿음을 주지 ㅇㅈ. 가끔은 왜 그런 규칙인지 물어보는 것도 좋아 🤝',
        emoji: '🤝', color: 'from-emerald-400 to-teal-600',
        traits: ['신뢰감', '책임감', '성실함', '일관성'] },
      { min: 28, max: 40, title: '아무도 안 봐도 지키는 원칙파 📏',
        desc: '새벽 빈 횡단보도에서도 초록불을 기다리는 원칙파야ㅋㅋ 약관도 읽고 분리배출도 라벨까지 떼서 함. 이 일관성이 주변에 기준이 되어 주는 큰 힘이지. 다만 남에게까지 같은 잣대를 대면 서로 피곤해질 수 있어 📏',
        emoji: '📏', color: 'from-violet-500 to-purple-700',
        traits: ['원칙주의', '일관성', '철저함', '정직함'] },
    ],
  },
  {
    slug: 'secondhand-style',
    title: '중고거래 스타일 테스트',
    desc: '깎는 사람 vs 부르는 대로 사는 사람ㅋㅋ 네 거래 스타일 알아보자 📦',
    icon: '📦',
    category: '금융·재테크',
    questions: [
      { q: '물건을 사기 전에 나는?', opts: [
        { text: '시세를 여러 곳에서 비교함', score: 4 },
        { text: '몇 개 보고 정함', score: 3 },
        { text: '괜찮아 보이면 삼', score: 2 },
        { text: '마음에 들면 바로', score: 1 }] },
      { q: '가격 흥정은?', opts: [
        { text: '근거를 들어 조심스럽게', score: 4 },
        { text: '조금은 물어봄', score: 3 },
        { text: '거의 안 함', score: 2 },
        { text: '부르는 대로 삼', score: 1 }] },
      { q: '팔 때 사진은?', opts: [
        { text: '흠집까지 찍어서 올림', score: 4 },
        { text: '여러 각도로 찍음', score: 3 },
        { text: '한두 장 올림', score: 2 },
        { text: '검색해서 가져다 씀', score: 1 }] },
      { q: '설명글은?', opts: [
        { text: '사용 기간과 상태를 다 적음', score: 4 },
        { text: '기본은 적음', score: 3 },
        { text: '짧게 적음', score: 2 },
        { text: '제목만 씀', score: 1 }] },
      { q: '약속 장소를 정할 때?', opts: [
        { text: '사람 많은 곳으로 정함', score: 4 },
        { text: '중간 지점으로', score: 3 },
        { text: '상대가 정하는 대로', score: 2 },
        { text: '집 앞으로 오라고 함', score: 1 }] },
      { q: '만나서 물건을 받으면?', opts: [
        { text: '그 자리에서 작동까지 확인', score: 4 },
        { text: '겉만 살펴봄', score: 3 },
        { text: '슥 보고 받음', score: 2 },
        { text: '그냥 받아옴', score: 1 }] },
      { q: '거래 후 문제가 생기면?', opts: [
        { text: '기록 보여주고 차분히 요청', score: 4 },
        { text: '연락해서 얘기함', score: 3 },
        { text: '귀찮아서 그냥 둠', score: 2 },
        { text: '속으로만 화남', score: 1 }] },
      { q: '안 쓰는 물건이 생기면?', opts: [
        { text: '바로 정리해서 올림', score: 4 },
        { text: '가끔 몰아서 올림', score: 3 },
        { text: '언젠가 하려고 둠', score: 2 },
        { text: '그냥 쌓아둠', score: 1 }] },
      { q: '택배 거래는?', opts: [
        { text: '송장 찍어두고 안전결제 씀', score: 4 },
        { text: '되도록 안전결제', score: 3 },
        { text: '계좌이체로도 함', score: 2 },
        { text: '별생각 없이 보냄', score: 1 }] },
      { q: '너무 싼 물건을 보면?', opts: [
        { text: '왜 싼지부터 의심함', score: 4 },
        { text: '한 번 더 확인함', score: 3 },
        { text: '운이 좋다고 생각함', score: 2 },
        { text: '놓칠까 봐 바로 연락', score: 1 }] },
    ],
    results: [
      { min: 10, max: 22, title: '마음 가는 대로 사는 즉흥 거래러 💨',
        desc: '마음에 들면 값 안 따지고 바로 사는 즉흥파야ㅋㅋ 흥정도 잘 안 하고 사람을 잘 믿는 편. 이 시원시원함이 거래를 빠르고 기분 좋게 만들어 주지. 다만 지나치게 싼 건 왜 싼지 한 번만 의심해 보면 좋아 💨',
        emoji: '💨', color: 'from-pink-400 to-rose-600',
        traits: ['시원시원', '신뢰형', '즉흥적', '털털함'] },
      { min: 23, max: 24, title: '적당히 챙기는 무난 거래러 🙂',
        desc: '시세도 몇 개 보고 사진도 몇 장 올리는 무난한 거래러야ㅋㅋ 크게 손해 보지도 않고 실랑이도 잘 안 함. 이 균형이 거래를 피곤하지 않게 해주지. 안전결제만 습관으로 만들면 더 든든해 🙂',
        emoji: '🙂', color: 'from-emerald-400 to-teal-600',
        traits: ['무난함', '균형', '적당함', '실용적'] },
      { min: 25, max: 27, title: '기록 남기는 꼼꼼 거래러 🧾',
        desc: '상태를 자세히 적고 만나서 확인까지 하는 꼼꼼 거래러야ㅋㅋ 약속 장소도 사람 많은 곳으로 잡고 문제가 생기면 차분히 얘기함. 이 태도가 분쟁을 미리 막아주지 ㅇㅈ. 안 쓰는 물건만 바로바로 올리면 완벽해 🧾',
        emoji: '🧾', color: 'from-amber-400 to-orange-500',
        traits: ['꼼꼼함', '신중함', '기록성', '안전지향'] },
      { min: 28, max: 40, title: '시세부터 파는 프로 거래러 📈',
        desc: '여러 곳 시세를 비교하고 흠집까지 찍어 올리는 프로급이야ㅋㅋ 근거 있는 흥정을 하고 안전결제와 송장까지 챙김. 이 철저함이 사고도 손해도 막아주는 큰 무기지. 가끔은 조금 손해 봐도 괜찮다는 여유도 챙겨봐 📈',
        emoji: '📈', color: 'from-violet-500 to-purple-700',
        traits: ['정보력', '협상력', '철저함', '안전제일'] },
    ],
  },
  {
    slug: 'moving-style',
    title: '이사 스타일 테스트',
    desc: '한 달 전부터 준비 vs 전날 밤 폭주ㅋㅋ 네 이사 스타일 알아보자 🚚',
    icon: '🚚',
    category: '건강·생활',
    questions: [
      { q: '이사 날짜가 정해지면 나는?', opts: [
        { text: '바로 할 일 목록을 만듦', score: 4 },
        { text: '몇 가지 알아보기 시작', score: 3 },
        { text: '한동안 그냥 둠', score: 2 },
        { text: '닥쳐서 함', score: 1 }] },
      { q: '짐을 싸는 순서는?', opts: [
        { text: '방별로 계획해서', score: 4 },
        { text: '안 쓰는 것부터', score: 3 },
        { text: '눈에 띄는 대로', score: 2 },
        { text: '한꺼번에 몰아서', score: 1 }] },
      { q: '박스에 표시는?', opts: [
        { text: '내용물과 갈 방까지 적음', score: 4 },
        { text: '대충 뭐가 들었는지', score: 3 },
        { text: '중요한 것만', score: 2 },
        { text: '안 적음', score: 1 }] },
      { q: '이사 업체는?', opts: [
        { text: '세 곳 이상 견적 비교', score: 4 },
        { text: '두 곳쯤 비교', score: 3 },
        { text: '검색해서 한 곳', score: 2 },
        { text: '아는 사람 소개로', score: 1 }] },
      { q: '버릴 물건 정리는?', opts: [
        { text: '이사 전에 크게 비움', score: 4 },
        { text: '눈에 띄는 것만 정리', score: 3 },
        { text: '일단 다 가져감', score: 2 },
        { text: '새 집 가서 생각함', score: 1 }] },
      { q: '인터넷이나 가스 신청은?', opts: [
        { text: '일주일 전에 다 해둠', score: 4 },
        { text: '며칠 전에 함', score: 3 },
        { text: '이사 즈음에 함', score: 2 },
        { text: '가서 불편하면 함', score: 1 }] },
      { q: '이사 당일 나는?', opts: [
        { text: '순서대로 지시하고 확인함', score: 4 },
        { text: '옆에서 도움', score: 3 },
        { text: '지켜봄', score: 2 },
        { text: '정신없이 끌려다님', score: 1 }] },
      { q: '새 집 하자 확인은?', opts: [
        { text: '사진 찍으며 꼼꼼히', score: 4 },
        { text: '한 바퀴 둘러봄', score: 3 },
        { text: '눈에 띄면 봄', score: 2 },
        { text: '나중에 알게 됨', score: 1 }] },
      { q: '짐 푸는 속도는?', opts: [
        { text: '며칠 안에 다 끝냄', score: 4 },
        { text: '한두 주 안에', score: 3 },
        { text: '한 달쯤 걸림', score: 2 },
        { text: '안 푼 박스가 남아 있음', score: 1 }] },
      { q: '전입신고는?', opts: [
        { text: '이사 당일이나 다음 날', score: 4 },
        { text: '그 주 안에', score: 3 },
        { text: '생각날 때', score: 2 },
        { text: '한참 뒤에 함', score: 1 }] },
    ],
    results: [
      { min: 10, max: 22, title: '닥쳐서 해치우는 벼락 이사러 ⚡',
        desc: '전날 밤에 몰아서 싸고 새 집에서 천천히 푸는 벼락 이사러야ㅋㅋ 미리 스트레스받지 않고 어떻게든 해내는 뚝심이 있음. 이 배짱이 큰일을 가볍게 넘기게 해주지. 전입신고와 인터넷 신청만 먼저 해두면 고생이 확 줄어 ⚡',
        emoji: '⚡', color: 'from-pink-400 to-rose-600',
        traits: ['벼락치기', '뚝심', '무던함', '적응력'] },
      { min: 23, max: 24, title: '할 만큼은 하는 무난 이사러 🙂',
        desc: '안 쓰는 것부터 싸고 며칠 전에 신청도 해두는 무난한 타입이야ㅋㅋ 지나치게 애쓰지 않으면서 큰 실수도 없음. 이 균형이 이사 스트레스를 적당히 유지해 주지. 박스에 갈 방만 적어두면 푸는 속도가 달라져 🙂',
        emoji: '🙂', color: 'from-emerald-400 to-teal-600',
        traits: ['무난함', '적당함', '실용적', '균형'] },
      { min: 25, max: 27, title: '방별로 챙기는 준비형 📦',
        desc: '방별로 계획해서 싸고 견적도 비교하는 준비형이야ㅋㅋ 하자도 한 바퀴 돌며 확인하고 짐도 금방 풀어냄. 이 준비성이 이사 뒤 며칠을 편하게 만들어 주지 ㅇㅈ. 버릴 것만 미리 크게 비우면 짐이 확 가벼워져 📦',
        emoji: '📦', color: 'from-amber-400 to-orange-500',
        traits: ['준비성', '계획적', '정리력', '실행력'] },
      { min: 28, max: 40, title: '목록부터 만드는 이사 사령관 🗂️',
        desc: '날짜 정해지자마자 목록을 만들고 견적도 세 곳 비교하는 사령관이야ㅋㅋ 박스마다 갈 방을 적고 하자는 사진으로 남기며 며칠 안에 다 풀어냄. 이 통솔력이 이사를 사고 없이 끝내주지. 다만 혼자 다 하려 들면 지치니 나눠 맡겨 🗂️',
        emoji: '🗂️', color: 'from-violet-500 to-purple-700',
        traits: ['통솔력', '체계적', '완벽주의', '추진력'] },
    ],
  },
  {
    slug: 'walking-speed',
    title: '걷는 속도 테스트',
    desc: '앞사람 답답해서 추월하는 타입?ㅋㅋ 네 걸음에서 성격이 보인다 🚶',
    icon: '🚶',
    category: '건강·생활',
    questions: [
      { q: '앞사람이 느리게 걸으면?', opts: [
        { text: '그 속도에 맞춰 감', score: 4 },
        { text: '천천히 따라감', score: 3 },
        { text: '틈나면 앞질러 감', score: 2 },
        { text: '바로 추월함', score: 1 }] },
      { q: '약속 장소까지 가는 길에?', opts: [
        { text: '주변 구경하며 걸음', score: 4 },
        { text: '적당한 속도로', score: 3 },
        { text: '빠르게 걸음', score: 2 },
        { text: '거의 뛰다시피', score: 1 }] },
      { q: '에스컬레이터에서는?', opts: [
        { text: '서서 감', score: 4 },
        { text: '보통 서 있음', score: 3 },
        { text: '급하면 걸어 올라감', score: 2 },
        { text: '늘 걸어 올라감', score: 1 }] },
      { q: '신호가 깜빡일 때?', opts: [
        { text: '다음 신호를 기다림', score: 4 },
        { text: '가까우면 건넘', score: 3 },
        { text: '빠르게 건넘', score: 2 },
        { text: '뛰어서 건넘', score: 1 }] },
      { q: '일행과 걸을 때 나는?', opts: [
        { text: '늘 상대에 맞춤', score: 4 },
        { text: '비슷하게 감', score: 3 },
        { text: '가끔 앞서감', score: 2 },
        { text: '자꾸 앞서서 기다림', score: 1 }] },
      { q: '산책할 때는?', opts: [
        { text: '느긋하게 오래', score: 4 },
        { text: '적당히 걸음', score: 3 },
        { text: '운동 삼아 빠르게', score: 2 },
        { text: '산책보다 목적지가 중요', score: 1 }] },
      { q: '계단과 엘리베이터 중?', opts: [
        { text: '기다렸다 엘리베이터', score: 4 },
        { text: '상황 봐서', score: 3 },
        { text: '두세 층은 계단', score: 2 },
        { text: '거의 계단으로 뛰어감', score: 1 }] },
      { q: '길이 막힐 때 마음은?', opts: [
        { text: '별로 안 급함', score: 4 },
        { text: '조금 답답함', score: 3 },
        { text: '짜증이 남', score: 2 },
        { text: '견디기 힘듦', score: 1 }] },
      { q: '만보 걷기를 한다면?', opts: [
        { text: '천천히 오래 걸어 채움', score: 4 },
        { text: '적당한 속도로', score: 3 },
        { text: '빠르게 걸어 빨리 끝냄', score: 2 },
        { text: '뛰어서 끝냄', score: 1 }] },
      { q: '남들이 내 걸음을 말할 때?', opts: [
        { text: '느리다는 말을 들음', score: 4 },
        { text: '보통이라고 함', score: 3 },
        { text: '빠르다고 함', score: 2 },
        { text: '따라가기 힘들다고 함', score: 1 }] },
    ],
    results: [
      { min: 10, max: 22, title: '늘 앞서 나가는 초고속 워커 🏃‍♂️',
        desc: '앞사람이 답답해서 바로 추월하고 계단도 뛰어오르는 초고속 워커야ㅋㅋ 시간을 아끼는 감각이 몸에 배어 있고 움직임이 시원함. 이 추진력이 하루를 길게 쓰게 해주지. 가끔은 속도를 늦춰야 보이는 것도 있어 🏃‍♂️',
        emoji: '🏃‍♂️', color: 'from-pink-400 to-rose-600',
        traits: ['추진력', '시간효율', '급함', '에너지'] },
      { min: 23, max: 24, title: '필요하면 속도 내는 실속러 👟',
        desc: '평소엔 보통이다가 급하면 확 빨라지는 실속러야ㅋㅋ 계단도 몇 층은 걸어 올라가고 신호도 가까우면 건넘. 이 조절력이 상황마다 알맞게 움직이게 해주지. 일행과 걸을 땐 한 박자만 늦춰주면 좋아 👟',
        emoji: '👟', color: 'from-amber-400 to-orange-500',
        traits: ['조절력', '실속', '상황적응', '균형'] },
      { min: 25, max: 27, title: '나란히 맞춰 걷는 동행형 🚶‍♀️',
        desc: '일행 속도에 맞추고 앞사람도 굳이 앞지르지 않는 동행형이야ㅋㅋ 급할 일이 아니면 적당한 속도를 유지함. 이 배려가 같이 걷는 사람을 편하게 만들어 주지 ㅇㅈ. 혼자일 땐 조금 빨리 걸어보면 기분이 또 달라 🚶‍♀️',
        emoji: '🚶‍♀️', color: 'from-emerald-400 to-teal-600',
        traits: ['배려심', '동행형', '차분함', '안정적'] },
      { min: 28, max: 40, title: '주변을 보며 걷는 산책러 🍃',
        desc: '느긋하게 주변을 보며 걷고 급한 신호는 다음 걸 기다리는 산책러야ㅋㅋ 막혀도 별로 짜증 나지 않고 오래 걷는 걸 좋아함. 이 여유가 하루의 피로를 덜어주는 힘이지. 약속엔 조금 일찍 나서면 서두를 일이 없어 🍃',
        emoji: '🍃', color: 'from-sky-400 to-blue-600',
        traits: ['여유', '관찰력', '느긋함', '평온함'] },
    ],
  },
  {
    slug: 'alarm-style',
    title: '알람 습관 테스트',
    desc: '한 번에 일어남 vs 스누즈 열 번ㅋㅋ 네 아침을 알아보자 ⏰',
    icon: '⏰',
    category: '건강·생활',
    questions: [
      { q: '알람은 몇 개를 맞추나?', opts: [
        { text: '하나면 충분', score: 4 },
        { text: '두 개쯤', score: 3 },
        { text: '서너 개', score: 2 },
        { text: '다섯 개 넘게', score: 1 }] },
      { q: '알람이 울리면?', opts: [
        { text: '바로 일어남', score: 4 },
        { text: '잠깐 누웠다 일어남', score: 3 },
        { text: '한두 번 미룸', score: 2 },
        { text: '몇 번을 미루는지 모름', score: 1 }] },
      { q: '휴대폰은 어디에 두고 자나?', opts: [
        { text: '멀리 두고 잠', score: 4 },
        { text: '책상 위', score: 3 },
        { text: '머리맡', score: 2 },
        { text: '손에 쥐고 잠', score: 1 }] },
      { q: '주말 알람은?', opts: [
        { text: '평일과 비슷하게 맞춤', score: 4 },
        { text: '조금 늦게 맞춤', score: 3 },
        { text: '가끔만 맞춤', score: 2 },
        { text: '안 맞춤', score: 1 }] },
      { q: '일어나야 할 시간보다 일찍 깨면?', opts: [
        { text: '그냥 일어남', score: 4 },
        { text: '조금 뒤척이다 일어남', score: 3 },
        { text: '알람까지 더 잠', score: 2 },
        { text: '다시 깊게 잠듦', score: 1 }] },
      { q: '알람 소리는?', opts: [
        { text: '잔잔한 소리로 충분', score: 4 },
        { text: '보통 소리', score: 3 },
        { text: '크게 해둠', score: 2 },
        { text: '제일 시끄러운 걸로', score: 1 }] },
      { q: '중요한 날 아침에는?', opts: [
        { text: '평소처럼 하나면 됨', score: 4 },
        { text: '하나 더 맞춤', score: 3 },
        { text: '여러 개 맞춤', score: 2 },
        { text: '누구한테 깨워달라고 함', score: 1 }] },
      { q: '일어난 직후 상태는?', opts: [
        { text: '바로 정신이 듦', score: 4 },
        { text: '몇 분이면 괜찮음', score: 3 },
        { text: '한참 멍함', score: 2 },
        { text: '삼십 분은 좀비', score: 1 }] },
      { q: '자는 시간은?', opts: [
        { text: '거의 일정함', score: 4 },
        { text: '비슷한 편', score: 3 },
        { text: '들쭉날쭉', score: 2 },
        { text: '매일 다름', score: 1 }] },
      { q: '지각한 적은?', opts: [
        { text: '거의 없음', score: 4 },
        { text: '아주 가끔', score: 3 },
        { text: '종종 있음', score: 2 },
        { text: '자주 있음', score: 1 }] },
    ],
    results: [
      { min: 10, max: 22, title: '스누즈와 싸우는 좀비 기상러 🧟',
        desc: '알람 다섯 개를 맞추고도 몇 번을 미루는 좀비 기상러야ㅋㅋ 일어나기까지가 전쟁이지만 결국은 해내는 근성이 있음. 이 버티는 힘도 능력이긴 하지. 휴대폰을 침대에서 멀리 두는 것 하나만 바꿔도 아침이 달라져 🧟',
        emoji: '🧟', color: 'from-slate-400 to-gray-600',
        traits: ['스누즈장인', '저혈압', '근성', '아침고전'] },
      { min: 23, max: 24, title: '한두 번 미루고 일어나는 보통러 😪',
        desc: '알람을 한두 번 미루긴 해도 결국 시간 맞춰 일어나는 보통러야ㅋㅋ 중요한 날엔 하나 더 맞춰두는 대비도 함. 이 정도면 무난하게 굴러가는 아침이지. 자는 시간만 조금 일정하게 하면 훨씬 가벼워져 😪',
        emoji: '😪', color: 'from-amber-400 to-orange-500',
        traits: ['무난함', '적당함', '대비형', '평범'] },
      { min: 25, max: 27, title: '알람 두 개면 되는 안정형 🌤️',
        desc: '알람 한두 개로 잠깐 누웠다 일어나는 안정형이야ㅋㅋ 몇 분이면 정신이 들고 지각도 거의 없음. 이 규칙성이 하루를 든든하게 시작하게 해주지 ㅇㅈ. 주말 기상 시간만 크게 흔들지 않으면 완벽해 🌤️',
        emoji: '🌤️', color: 'from-emerald-400 to-teal-600',
        traits: ['안정적', '규칙성', '자기관리', '무리없음'] },
      { min: 28, max: 40, title: '알람보다 먼저 깨는 아침형 🌅',
        desc: '알람 하나면 충분하고 종종 그보다 먼저 눈이 떠지는 아침형이야ㅋㅋ 자는 시간도 일정하고 일어나자마자 정신이 듦. 이 리듬이 하루를 길고 안정적으로 만들어 주지. 다만 잠이 모자란 날은 몸이 보내는 신호를 들어줘 🌅',
        emoji: '🌅', color: 'from-violet-500 to-purple-700',
        traits: ['아침형', '규칙적', '자기관리', '컨디션관리'] },
    ],
  },
  {
    slug: 'phone-call-anxiety',
    title: '전화 통화 부담 테스트',
    desc: '전화 오면 심장 쿵? 문자로 해주지ㅋㅋ 네 통화 부담 알아보자 ☎️',
    icon: '☎️',
    category: '성격',
    questions: [
      { q: '모르는 번호로 전화가 오면?', opts: [
        { text: '그냥 받음', score: 4 },
        { text: '보통 받음', score: 3 },
        { text: '망설이다 받음', score: 2 },
        { text: '안 받고 검색해 봄', score: 1 }] },
      { q: '가게에 문의할 일이 있으면?', opts: [
        { text: '바로 전화함', score: 4 },
        { text: '전화가 빠르면 함', score: 3 },
        { text: '되도록 검색으로 해결', score: 2 },
        { text: '전화 안 되면 포기', score: 1 }] },
      { q: '전화 걸기 전에 나는?', opts: [
        { text: '그냥 걸음', score: 4 },
        { text: '할 말만 생각함', score: 3 },
        { text: '머릿속으로 연습함', score: 2 },
        { text: '적어놓고 걺', score: 1 }] },
      { q: '통화 중 말이 겹치면?', opts: [
        { text: '자연스럽게 넘김', score: 4 },
        { text: '양보하고 이어감', score: 3 },
        { text: '당황함', score: 2 },
        { text: '머리가 하얘짐', score: 1 }] },
      { q: '음성 메시지를 남길 때?', opts: [
        { text: '편하게 남김', score: 4 },
        { text: '짧게 남김', score: 3 },
        { text: '몇 번 고쳐 말함', score: 2 },
        { text: '끊고 문자로 보냄', score: 1 }] },
      { q: '업무 연락은 어떤 쪽이 편한가?', opts: [
        { text: '전화가 훨씬 빠름', score: 4 },
        { text: '경우에 따라', score: 3 },
        { text: '되도록 메신저', score: 2 },
        { text: '무조건 글로', score: 1 }] },
      { q: '전화가 길어질 때?', opts: [
        { text: '얼마든지 괜찮음', score: 4 },
        { text: '보통은 괜찮음', score: 3 },
        { text: '슬슬 끊고 싶음', score: 2 },
        { text: '빨리 끝내고 싶음', score: 1 }] },
      { q: '통화 후 기분은?', opts: [
        { text: '별생각 없음', score: 4 },
        { text: '개운함', score: 3 },
        { text: '잘 말했나 되짚어 봄', score: 2 },
        { text: '한참 곱씹음', score: 1 }] },
      { q: '영상통화는?', opts: [
        { text: '편하게 함', score: 4 },
        { text: '가끔 함', score: 3 },
        { text: '부담스러움', score: 2 },
        { text: '거의 안 함', score: 1 }] },
      { q: '부재중 전화를 봤을 때?', opts: [
        { text: '바로 걸어봄', score: 4 },
        { text: '곧 걸어봄', score: 3 },
        { text: '문자로 먼저 물어봄', score: 2 },
        { text: '미루다 못 걺', score: 1 }] },
    ],
    results: [
      { min: 10, max: 22, title: '전화보다 글이 편한 텍스트파 💬',
        desc: '전화가 오면 긴장되고 되도록 글로 해결하려는 텍스트파야ㅋㅋ 대신 글로는 훨씬 정확하고 차분하게 전달함. 이 강점이 기록이 남는 소통에서 큰 힘이 되지. 짧은 용건 하나만 전화로 해보는 연습부터 시작해 봐 💬',
        emoji: '💬', color: 'from-slate-400 to-gray-600',
        traits: ['글소통', '정확함', '신중함', '기록형'] },
      { min: 23, max: 24, title: '필요하면 하지만 부담은 있는 타입 😅',
        desc: '해야 하면 걸긴 하는데 그 전에 할 말을 정리하는 타입이야ㅋㅋ 통화 뒤에 잘 말했나 되짚어 보기도 함. 이 신중함이 실수를 줄여주는 강점이지. 되짚는 시간만 줄이면 훨씬 가벼워질 거야 😅',
        emoji: '😅', color: 'from-amber-400 to-orange-500',
        traits: ['신중함', '준비형', '책임감', '소심한편'] },
      { min: 25, max: 27, title: '전화든 글이든 괜찮은 무난파 🙂',
        desc: '전화도 글도 상황에 맞게 골라 쓰는 무난파야ㅋㅋ 모르는 번호도 대체로 받고 통화가 길어져도 괜찮음. 이 유연함이 어떤 소통이든 막히지 않게 해주지 ㅇㅈ. 급한 일은 전화가 빠르다는 것도 잘 알고 있어 🙂',
        emoji: '🙂', color: 'from-emerald-400 to-teal-600',
        traits: ['유연함', '무난함', '균형', '적응력'] },
      { min: 28, max: 40, title: '전화가 제일 빠른 통화파 📞',
        desc: '메신저로 열 줄 쓸 바에 전화 한 통이 낫다는 통화파야ㅋㅋ 모르는 번호도 그냥 받고 통화 뒤에 곱씹지도 않음. 이 시원시원함이 일을 빨리 굴러가게 만들지. 상대는 전화가 부담일 수 있으니 한 번씩 물어봐 주면 좋아 📞',
        emoji: '📞', color: 'from-violet-500 to-purple-700',
        traits: ['직진소통', '빠름', '털털함', '추진력'] },
    ],
  },
];
