import type { Test } from './types';

export const TESTS: Test[] = [
  {
    slug: 'mbti',
    title: 'MBTI 간이 테스트',
    desc: '짧은 시간에 나의 MBTI 성향을 파악해보세요',
    icon: '🧠',
    category: '성격',
    questions: [
      { q: '모르는 사람들 사이에서도 먼저 대화를 시작하는 편이다', opts: [{ text: '매우 그렇다', score: 4 }, { text: '그렇다', score: 3 }, { text: '아닌 편이다', score: 2 }, { text: '전혀 아니다', score: 1 }] },
      { q: '주말에는 친구들과 바깥 활동보다 집에서 쉬는 것이 좋다', opts: [{ text: '매우 그렇다', score: 1 }, { text: '그렇다', score: 2 }, { text: '아닌 편이다', score: 3 }, { text: '전혀 아니다', score: 4 }] },
      { q: '계획 없이 즉흥적으로 행동하는 것이 편하다', opts: [{ text: '매우 그렇다', score: 4 }, { text: '그렇다', score: 3 }, { text: '아닌 편이다', score: 2 }, { text: '전혀 아니다', score: 1 }] },
      { q: '결정을 내릴 때 논리보다 감정을 더 중요시한다', opts: [{ text: '매우 그렇다', score: 4 }, { text: '그렇다', score: 3 }, { text: '아닌 편이다', score: 2 }, { text: '전혀 아니다', score: 1 }] },
      { q: '새로운 아이디어보다 검증된 방법을 선호한다', opts: [{ text: '매우 그렇다', score: 1 }, { text: '그렇다', score: 2 }, { text: '아닌 편이다', score: 3 }, { text: '전혀 아니다', score: 4 }] },
      { q: '갈등 상황에서 상대방 감정을 먼저 배려한다', opts: [{ text: '매우 그렇다', score: 4 }, { text: '그렇다', score: 3 }, { text: '아닌 편이다', score: 2 }, { text: '전혀 아니다', score: 1 }] },
      { q: '프로젝트를 마감 전에 미리 완료하는 편이다', opts: [{ text: '매우 그렇다', score: 1 }, { text: '그렇다', score: 2 }, { text: '아닌 편이다', score: 3 }, { text: '전혀 아니다', score: 4 }] },
      { q: '대화할 때 상대방의 숨은 의미를 파악하려 한다', opts: [{ text: '매우 그렇다', score: 4 }, { text: '그렇다', score: 3 }, { text: '아닌 편이다', score: 2 }, { text: '전혀 아니다', score: 1 }] },
      { q: '여럿이 함께하는 자리에서 에너지가 넘친다', opts: [{ text: '매우 그렇다', score: 4 }, { text: '그렇다', score: 3 }, { text: '아닌 편이다', score: 2 }, { text: '전혀 아니다', score: 1 }] },
      { q: '일상의 소소한 루틴이 편안하고 안정감을 준다', opts: [{ text: '매우 그렇다', score: 1 }, { text: '그렇다', score: 2 }, { text: '아닌 편이다', score: 3 }, { text: '전혀 아니다', score: 4 }] },
    ],
    results: [
      { min: 10, max: 22, title: '내향적 사색가 🌙', desc: '혼자만의 시간이 재충전의 원천입니다. 깊은 사고와 신중한 판단력이 강점이며, 소수의 깊은 인간관계를 선호합니다. 계획적이고 체계적인 방식으로 목표를 달성합니다.', emoji: '🌙', color: 'from-indigo-500 to-purple-700', traits: ['신중함', '깊은 사고', '계획적', '1:1 대화 선호'] },
      { min: 23, max: 32, title: '유연한 중간형 ⚡', desc: '상황에 따라 유연하게 적응하는 균형 잡힌 타입입니다. 내향과 외향의 장점을 모두 활용하며, 다양한 환경에서 편안하게 지냅니다.', emoji: '⚡', color: 'from-violet-500 to-pink-600', traits: ['유연성', '균형감', '적응력', '상황 판단력'] },
      { min: 33, max: 40, title: '외향적 행동파 ☀️', desc: '사람들과 함께할 때 에너지가 넘칩니다. 즉흥적이고 도전적이며, 새로운 경험과 만남을 즐깁니다. 타고난 리더십과 소통 능력으로 주변을 이끕니다.', emoji: '☀️', color: 'from-orange-400 to-red-500', traits: ['사교성', '즉흥성', '도전정신', '리더십'] },
    ],
  },
  {
    slug: 'burnout',
    title: '번아웃 테스트',
    desc: '나의 번아웃 위험도를 체크해보세요',
    icon: '🔥',
    category: '직장·커리어',
    questions: [
      { q: '아침에 일어나기가 너무 힘들고 출근이 두렵다', opts: [{ text: '항상 그렇다', score: 4 }, { text: '자주 그렇다', score: 3 }, { text: '가끔 그렇다', score: 2 }, { text: '거의 없다', score: 1 }] },
      { q: '퇴근 후에도 일 생각이 떠나지 않는다', opts: [{ text: '항상 그렇다', score: 4 }, { text: '자주 그렇다', score: 3 }, { text: '가끔 그렇다', score: 2 }, { text: '거의 없다', score: 1 }] },
      { q: '예전에 즐겁던 업무가 이제 재미없고 귀찮다', opts: [{ text: '항상 그렇다', score: 4 }, { text: '자주 그렇다', score: 3 }, { text: '가끔 그렇다', score: 2 }, { text: '거의 없다', score: 1 }] },
      { q: '집중력이 떨어지고 작은 실수가 잦아졌다', opts: [{ text: '항상 그렇다', score: 4 }, { text: '자주 그렇다', score: 3 }, { text: '가끔 그렇다', score: 2 }, { text: '거의 없다', score: 1 }] },
      { q: '주말에도 쉬어도 피로가 풀리지 않는다', opts: [{ text: '항상 그렇다', score: 4 }, { text: '자주 그렇다', score: 3 }, { text: '가끔 그렇다', score: 2 }, { text: '거의 없다', score: 1 }] },
      { q: '동료나 가족에게 짜증을 자주 낸다', opts: [{ text: '항상 그렇다', score: 4 }, { text: '자주 그렇다', score: 3 }, { text: '가끔 그렇다', score: 2 }, { text: '거의 없다', score: 1 }] },
      { q: '내 업무에서 의미나 보람을 찾지 못하고 있다', opts: [{ text: '항상 그렇다', score: 4 }, { text: '자주 그렇다', score: 3 }, { text: '가끔 그렇다', score: 2 }, { text: '거의 없다', score: 1 }] },
      { q: '식욕이 없거나 반대로 폭식을 한다', opts: [{ text: '항상 그렇다', score: 4 }, { text: '자주 그렇다', score: 3 }, { text: '가끔 그렇다', score: 2 }, { text: '거의 없다', score: 1 }] },
      { q: '이직이나 퇴사를 하고 싶다는 생각이 자주 든다', opts: [{ text: '항상 그렇다', score: 4 }, { text: '자주 그렇다', score: 3 }, { text: '가끔 그렇다', score: 2 }, { text: '거의 없다', score: 1 }] },
      { q: '취미나 여가활동도 즐겁지 않고 무기력하다', opts: [{ text: '항상 그렇다', score: 4 }, { text: '자주 그렇다', score: 3 }, { text: '가끔 그렇다', score: 2 }, { text: '거의 없다', score: 1 }] },
    ],
    results: [
      { min: 10, max: 18, title: '번아웃 안전 ✅', desc: '현재 번아웃 위험이 낮습니다. 건강한 워라밸을 유지하고 있어요. 지금처럼 자기 관리를 잘 해주세요!', emoji: '✅', color: 'from-emerald-400 to-teal-500', traits: ['건강한 워라밸', '충분한 회복력', '긍정적 마인드'] },
      { min: 19, max: 27, title: '번아웃 주의 ⚠️', desc: '번아웃 초기 신호가 보입니다. 지금 충분한 휴식을 취하지 않으면 악화될 수 있어요. 하루 30분이라도 나를 위한 시간을 가져보세요.', emoji: '⚠️', color: 'from-yellow-400 to-amber-500', traits: ['피로 누적', '집중력 저하', '휴식 필요'] },
      { min: 28, max: 34, title: '번아웃 위험 🆘', desc: '번아웃 증상이 뚜렷합니다. 지금 당장 휴식이 필요해요. 신뢰할 수 있는 사람과 이야기하고, 필요하다면 전문가의 도움을 받으세요.', emoji: '🆘', color: 'from-orange-500 to-red-600', traits: ['번아웃 진행 중', '즉각적 휴식 필요', '전문가 상담 권장'] },
      { min: 35, max: 40, title: '심각한 번아웃 🚨', desc: '번아웃이 심각한 상태입니다. 혼자 해결하려 하지 마세요. 전문 심리상담을 받고, 가능하다면 의료 전문가와 상담하세요. 당신의 건강이 가장 중요합니다.', emoji: '🚨', color: 'from-red-500 to-rose-700', traits: ['심각한 소진', '전문 치료 필요', '즉각 휴직 고려'] },
    ],
  },
  {
    slug: 'love-style',
    title: '연애 성향 테스트',
    desc: '나의 연애 스타일과 이상형을 알아보세요',
    icon: '💕',
    category: '연애·결혼',
    questions: [
      { q: '연인과 하루에 연락을 얼마나 해야 편한가요?', opts: [{ text: '수시로 연락해야 안심된다', score: 4 }, { text: '하루에 여러 번 정도', score: 3 }, { text: '하루 한두 번이면 충분', score: 2 }, { text: '필요할 때만 연락해도 괜찮다', score: 1 }] },
      { q: '연인이 친구들과 늦게까지 있으면 어떤가요?', opts: [{ text: '많이 신경 쓰이고 불안하다', score: 4 }, { text: '조금 신경 쓰인다', score: 3 }, { text: '이해하지만 연락은 해줬으면 한다', score: 2 }, { text: '전혀 신경 안 쓴다', score: 1 }] },
      { q: '연인의 과거 연애에 대해 어떻게 생각하나요?', opts: [{ text: '많이 신경 쓰인다', score: 4 }, { text: '조금 신경 쓰인다', score: 3 }, { text: '별로 안 궁금하다', score: 2 }, { text: '전혀 상관없다', score: 1 }] },
      { q: '연인과 다투면 어떻게 하나요?', opts: [{ text: '바로 화해하려고 먼저 연락한다', score: 4 }, { text: '시간이 좀 지나면 연락한다', score: 3 }, { text: '상대방이 먼저 연락하길 기다린다', score: 2 }, { text: '각자 시간을 갖고 자연스럽게 해결된다', score: 1 }] },
      { q: '기념일이나 이벤트를 얼마나 중요하게 생각하나요?', opts: [{ text: '매우 중요하다, 꼭 챙겨야 한다', score: 4 }, { text: '중요하다', score: 3 }, { text: '있으면 좋지만 없어도 된다', score: 2 }, { text: '별로 중요하지 않다', score: 1 }] },
      { q: '연인과 함께하는 시간 vs 개인 시간', opts: [{ text: '연인과 최대한 함께 있고 싶다', score: 4 }, { text: '연인과 보내는 시간이 더 많아야 한다', score: 3 }, { text: '비슷하게 있으면 좋겠다', score: 2 }, { text: '개인 시간이 충분히 있어야 한다', score: 1 }] },
      { q: '연인이 나의 친구 모임에 함께하는 것은?', opts: [{ text: '항상 함께했으면 한다', score: 4 }, { text: '자주 함께했으면 한다', score: 3 }, { text: '가끔 함께해도 좋다', score: 2 }, { text: '각자 친구 모임은 따로 하는 게 좋다', score: 1 }] },
      { q: '연인에게 감정 표현을 어느 정도 하나요?', opts: [{ text: '매우 자주, 언제나 표현한다', score: 4 }, { text: '자주 표현한다', score: 3 }, { text: '가끔 표현한다', score: 2 }, { text: '표현이 서툰 편이다', score: 1 }] },
      { q: '연인의 휴대폰을 보고 싶다는 생각이 드나요?', opts: [{ text: '자주 든다', score: 4 }, { text: '가끔 든다', score: 3 }, { text: '거의 안 든다', score: 2 }, { text: '전혀 없다', score: 1 }] },
      { q: '연인과의 미래 계획을 얼마나 자주 이야기하나요?', opts: [{ text: '자주 이야기하고 싶다', score: 4 }, { text: '가끔 이야기한다', score: 3 }, { text: '자연스럽게 흘러가면 된다고 생각한다', score: 2 }, { text: '거의 이야기하지 않는다', score: 1 }] },
    ],
    results: [
      { min: 10, max: 19, title: '자유로운 독립형 🦋', desc: '개인 시간과 자유를 소중히 여기는 타입입니다. 서로의 공간을 존중하는 성숙한 연애를 원해요. 구속은 싫지만 진심 어린 감정은 충분히 전달하는 스타일입니다.', emoji: '🦋', color: 'from-sky-400 to-blue-600', traits: ['독립성 중시', '여유로운 관계', '신뢰 기반', '자유로운 소통'] },
      { min: 20, max: 29, title: '균형 잡힌 안정형 💫', desc: '적당한 스킨십과 연락, 적당한 자유를 모두 추구하는 균형형입니다. 상대방의 감정을 배려하면서도 자신의 페이스도 유지할 줄 압니다.', emoji: '💫', color: 'from-violet-400 to-purple-600', traits: ['균형감', '안정적 애착', '배려심', '실용적 사랑'] },
      { min: 30, max: 40, title: '열정적 밀착형 🔥', desc: '사랑에 올인하는 열정적인 타입입니다. 연인과의 시간을 최우선으로 두며, 강한 감정 표현과 긴밀한 유대를 원합니다. 질투심이 생길 수 있으나 그만큼 깊이 사랑합니다.', emoji: '🔥', color: 'from-rose-500 to-red-600', traits: ['강한 애정표현', '밀착 스타일', '열정적', '헌신적'] },
    ],
  },
  {
    slug: 'stress-index',
    title: '스트레스 지수 테스트',
    desc: '나의 현재 스트레스 수준을 확인해보세요',
    icon: '😤',
    category: '건강·생활',
    questions: [
      { q: '요즘 잠들기가 어렵거나 수면의 질이 나쁘다', opts: [{ text: '매우 그렇다', score: 4 }, { text: '그렇다', score: 3 }, { text: '조금 그렇다', score: 2 }, { text: '아니다', score: 1 }] },
      { q: '사소한 일에도 짜증이 나거나 화가 난다', opts: [{ text: '매우 그렇다', score: 4 }, { text: '그렇다', score: 3 }, { text: '조금 그렇다', score: 2 }, { text: '아니다', score: 1 }] },
      { q: '두통, 어깨 결림 등 신체 증상이 자주 있다', opts: [{ text: '매우 그렇다', score: 4 }, { text: '그렇다', score: 3 }, { text: '조금 그렇다', score: 2 }, { text: '아니다', score: 1 }] },
      { q: '집중력이 떨어지고 멍하니 있을 때가 많다', opts: [{ text: '매우 그렇다', score: 4 }, { text: '그렇다', score: 3 }, { text: '조금 그렇다', score: 2 }, { text: '아니다', score: 1 }] },
      { q: '아무것도 하기 싫고 무기력한 느낌이 든다', opts: [{ text: '매우 그렇다', score: 4 }, { text: '그렇다', score: 3 }, { text: '조금 그렇다', score: 2 }, { text: '아니다', score: 1 }] },
      { q: '먹는 것(과식 또는 식욕 저하)에 변화가 생겼다', opts: [{ text: '매우 그렇다', score: 4 }, { text: '그렇다', score: 3 }, { text: '조금 그렇다', score: 2 }, { text: '아니다', score: 1 }] },
      { q: '하고 싶은 일이나 취미도 즐겁지 않다', opts: [{ text: '매우 그렇다', score: 4 }, { text: '그렇다', score: 3 }, { text: '조금 그렇다', score: 2 }, { text: '아니다', score: 1 }] },
      { q: '미래에 대한 불안감이 크다', opts: [{ text: '매우 그렇다', score: 4 }, { text: '그렇다', score: 3 }, { text: '조금 그렇다', score: 2 }, { text: '아니다', score: 1 }] },
      { q: '주변 사람들과 관계가 피곤하게 느껴진다', opts: [{ text: '매우 그렇다', score: 4 }, { text: '그렇다', score: 3 }, { text: '조금 그렇다', score: 2 }, { text: '아니다', score: 1 }] },
      { q: '혼자 있고 싶은데 동시에 외로운 느낌이 든다', opts: [{ text: '매우 그렇다', score: 4 }, { text: '그렇다', score: 3 }, { text: '조금 그렇다', score: 2 }, { text: '아니다', score: 1 }] },
    ],
    results: [
      { min: 10, max: 18, title: '스트레스 낮음 😊', desc: '현재 스트레스 수준이 양호합니다. 지금의 건강한 생활 습관을 유지하세요. 작은 것에도 감사하는 마음이 스트레스를 낮춰줍니다.', emoji: '😊', color: 'from-emerald-400 to-green-600', traits: ['안정적', '긍정적', '건강한 컨디션'] },
      { min: 19, max: 27, title: '스트레스 보통 😐', desc: '약간의 스트레스가 누적되어 있어요. 규칙적인 운동과 충분한 수면, 좋아하는 취미 활동으로 해소해보세요. 무시하면 쌓일 수 있으니 관리가 필요합니다.', emoji: '😐', color: 'from-yellow-400 to-amber-500', traits: ['스트레스 누적 중', '휴식 권장', '자기 돌봄 필요'] },
      { min: 28, max: 34, title: '스트레스 높음 😰', desc: '스트레스가 꽤 높은 상태입니다. 지금 당장 쉬어가는 시간이 필요해요. 신뢰하는 사람과 대화하거나, 명상과 가벼운 운동을 시도해보세요.', emoji: '😰', color: 'from-orange-400 to-red-500', traits: ['스트레스 과부하', '즉각적 케어 필요', '상담 권장'] },
      { min: 35, max: 40, title: '위험 수준 스트레스 🆘', desc: '스트레스가 매우 심각한 상태입니다. 혼자 감당하지 마세요. 전문 심리 상담을 받거나 가까운 사람에게 도움을 요청하세요. 당신의 정신 건강이 무엇보다 소중합니다.', emoji: '🆘', color: 'from-red-500 to-rose-700', traits: ['위험 수준', '전문가 상담 필요', '즉각 휴식'] },
    ],
  },
  {
    slug: 'spending-habit',
    title: '소비 습관 테스트',
    desc: '나의 소비 패턴과 금융 성향을 파악해보세요',
    icon: '💳',
    category: '금융·재테크',
    questions: [
      { q: '한 달 용돈/급여 중 저축 비율은?', opts: [{ text: '30% 이상 저축한다', score: 1 }, { text: '10~30% 저축한다', score: 2 }, { text: '10% 미만 저축한다', score: 3 }, { text: '저축을 거의 못 한다', score: 4 }] },
      { q: '마음에 드는 물건을 보면?', opts: [{ text: '바로 구매한다', score: 4 }, { text: '일주일 정도 고민 후 산다', score: 3 }, { text: '정말 필요한지 꼼꼼히 따진다', score: 2 }, { text: '웬만하면 안 산다', score: 1 }] },
      { q: '할인/세일 소식을 들으면?', opts: [{ text: '필요 없어도 사게 된다', score: 4 }, { text: '관심 있는 것만 구매한다', score: 3 }, { text: '미리 계획한 것만 산다', score: 2 }, { text: '할인에 크게 반응하지 않는다', score: 1 }] },
      { q: '한 달 후 카드 명세서를 보면?', opts: [{ text: '예상보다 훨씬 많아서 놀란다', score: 4 }, { text: '조금 많은 것 같다', score: 3 }, { text: '예상 범위 내다', score: 2 }, { text: '예상보다 적다', score: 1 }] },
      { q: '가계부 또는 지출 기록을?', opts: [{ text: '전혀 하지 않는다', score: 4 }, { text: '가끔 한다', score: 3 }, { text: '대략적으로 파악한다', score: 2 }, { text: '꼼꼼히 기록한다', score: 1 }] },
      { q: '음식·카페·외식 등에 한 달에 얼마나 쓰나요?', opts: [{ text: '예산 없이 그냥 쓴다', score: 4 }, { text: '신경은 쓰지만 초과가 잦다', score: 3 }, { text: '예산을 정해두고 지킨다', score: 2 }, { text: '아끼는 편이다', score: 1 }] },
      { q: '충동구매 후 후회한 경험이?', opts: [{ text: '매우 자주 있다', score: 4 }, { text: '자주 있다', score: 3 }, { text: '가끔 있다', score: 2 }, { text: '거의 없다', score: 1 }] },
      { q: '비상금(예비금)을 따로 관리하나요?', opts: [{ text: '전혀 없다', score: 4 }, { text: '조금 있다', score: 3 }, { text: '어느 정도 있다', score: 2 }, { text: '충분히 있다', score: 1 }] },
      { q: '친구 모임, 경조사 등 지출을?', opts: [{ text: '아낌없이 쓴다', score: 4 }, { text: '다소 많이 쓰는 편', score: 3 }, { text: '적당히 쓴다', score: 2 }, { text: '최소한으로 관리한다', score: 1 }] },
      { q: '나의 재무 목표(집 구매, 은퇴자금 등)가?', opts: [{ text: '생각해본 적 없다', score: 4 }, { text: '막연하게 있다', score: 3 }, { text: '어느 정도 계획이 있다', score: 2 }, { text: '구체적 계획이 있다', score: 1 }] },
    ],
    results: [
      { min: 10, max: 18, title: '절약왕 💰', desc: '훌륭한 소비 절제력을 가지고 있습니다. 계획적인 소비와 저축 습관으로 재정적으로 안정적입니다. 다만 너무 과도한 절약은 삶의 질을 낮출 수 있으니 가끔은 자신에게 투자하세요!', emoji: '💰', color: 'from-emerald-500 to-teal-600', traits: ['절약 능력', '계획적 소비', '저축 습관', '재정 안정'] },
      { min: 19, max: 27, title: '균형 소비형 ⚖️', desc: '소비와 저축 사이에서 균형을 잡고 있습니다. 즐길 건 즐기면서도 미래를 준비하는 합리적인 타입이에요. 조금 더 체계적인 계획을 세우면 더욱 탄탄해집니다.', emoji: '⚖️', color: 'from-blue-400 to-violet-500', traits: ['균형 잡힌 소비', '합리적 판단', '중간 저축률'] },
      { min: 28, max: 34, title: '충동 소비형 💸', desc: '충동구매나 계획 없는 지출이 잦은 편입니다. 가계부 앱이나 소비 알림 서비스를 활용해 지출을 추적해보세요. 작은 변화가 큰 차이를 만듭니다!', emoji: '💸', color: 'from-amber-400 to-orange-500', traits: ['충동구매 경향', '계획성 부족', '지출 관리 필요'] },
      { min: 35, max: 40, title: '소비 위험형 🚨', desc: '소비 습관 개선이 시급합니다. 당장 가계부를 쓰고, 신용카드 한도를 줄이고, 자동 저축을 설정해보세요. 지금 당장 바꾸지 않으면 나중에 더 힘들어집니다.', emoji: '🚨', color: 'from-red-500 to-rose-600', traits: ['과소비 위험', '저축 부족', '즉각 개선 필요'] },
    ],
  },
];

// 에이전트가 나머지 95개를 추가합니다
export const TEST_MAP: Record<string, Test> = Object.fromEntries(TESTS.map(t => [t.slug, t]));
