/**
 * CSS 속성 154개의 한 줄 설명 — 여덟 언어.
 *
 * 속성 이름과 값은 표준이 정한 영어라 옮기지 않는다. display: flex는 어디서나
 * display: flex이고, 옮기는 것은 "이 속성이 무엇을 하는가" 한 문장뿐이다.
 *
 * 여덟 칸을 배열로 적는다 — 항목마다 열쇠 이름을 여덟 번 쓰면 파일이 세 배가 되고,
 * 빠진 칸도 오히려 눈에 안 띈다. 순서는 ko·en·es·pt·ja·de·fr·hi.
 */
export type Eight = [string, string, string, string, string, string, string, string];

const LANG_ORDER = ['ko', 'en', 'es', 'pt', 'ja', 'de', 'fr', 'hi'] as const;

export const CSS_DESC: Record<string, Eight> = {
  /* ───────── 배치 ───────── */
  display: ['요소를 어떤 상자로 다룰지 정합니다. 배치의 시작점이 되는 속성입니다.', 'Sets what kind of box the element becomes — the starting point of any layout.', 'Define qué tipo de caja es el elemento: el punto de partida de toda maquetación.', 'Define que tipo de caixa o elemento é: o ponto de partida de qualquer layout.', '要素をどんな箱として扱うかを決めます。レイアウトの出発点になる属性です。', 'Legt fest, als welche Box ein Element behandelt wird — der Ausgangspunkt jedes Layouts.', "Définit le type de boîte de l'élément : le point de départ de toute mise en page.", 'तय करता है कि तत्व किस तरह का बॉक्स बने — हर लेआउट का शुरुआती बिंदु।'],
  visibility: ['보이거나 숨깁니다. hidden으로 숨겨도 자리는 그대로 차지합니다.', 'Shows or hides an element; hidden still leaves its space occupied.', 'Muestra u oculta; con hidden el espacio sigue ocupado.', 'Mostra ou esconde; com hidden o espaço continua ocupado.', '見せるか隠すかを決めます。hiddenで隠しても場所はそのまま残ります。', 'Zeigt oder verbirgt ein Element; bei hidden bleibt der Platz erhalten.', "Affiche ou masque ; avec hidden, la place reste occupée.", 'दिखाता या छिपाता है; hidden पर भी जगह घिरी रहती है।'],
  float: ['요소를 한쪽으로 띄워 글이 옆으로 흐르게 합니다. 지금은 flex와 grid가 대신합니다.', 'Floats an element to one side so text flows beside it; flex and grid handle this now.', 'Flota el elemento a un lado para que el texto lo rodee; hoy lo hacen flex y grid.', 'Flutua o elemento para um lado e o texto contorna; hoje flex e grid fazem isso.', '要素を片側に寄せて文章を横に流します。今はflexやgridが担います。', 'Lässt ein Element seitlich schwimmen, sodass Text daneben fließt; heute übernehmen das Flex und Grid.', "Fait flotter un élément sur un côté pour que le texte l'entoure ; flex et grid le remplacent.", 'तत्व को एक ओर तैराता है ताकि पाठ बगल से बहे; अब flex और grid यह काम करते हैं।'],
  clear: ['앞선 float 아래로 내려가게 합니다.', 'Pushes the element below any preceding floats.', 'Empuja el elemento por debajo de los flotantes anteriores.', 'Empurra o elemento para baixo dos flutuantes anteriores.', '先行するfloatの下に回り込ませます。', 'Schiebt das Element unter vorangehende Floats.', "Place l'élément sous les flottants qui précèdent.", 'तत्व को पिछले फ़्लोट के नीचे धकेलता है।'],
  overflow: ['넘치는 내용을 자를지 스크롤할지 정합니다.', 'Decides whether overflowing content is clipped or scrolls.', 'Decide si el contenido que desborda se recorta o se desplaza.', 'Decide se o conteúdo que transborda é cortado ou rola.', 'はみ出した内容を切るかスクロールさせるかを決めます。', 'Bestimmt, ob überlaufender Inhalt beschnitten wird oder scrollt.', "Décide si le contenu qui déborde est rogné ou défile.", 'तय करता है कि उमड़ती सामग्री कटे या स्क्रॉल हो।'],
  'overflow-x': ['가로로 넘칠 때만 따로 정합니다.', 'Controls overflow on the horizontal axis alone.', 'Controla solo el desbordamiento horizontal.', 'Controla apenas o transbordo horizontal.', '横にはみ出したときだけを別に決めます。', 'Steuert nur den waagerechten Überlauf.', "Ne gère que le débordement horizontal.", 'सिर्फ़ क्षैतिज दिशा का ओवरफ़्लो संभालता है।'],
  'overflow-y': ['세로로 넘칠 때만 따로 정합니다.', 'Controls overflow on the vertical axis alone.', 'Controla solo el desbordamiento vertical.', 'Controla apenas o transbordo vertical.', '縦にはみ出したときだけを別に決めます。', 'Steuert nur den senkrechten Überlauf.', "Ne gère que le débordement vertical.", 'सिर्फ़ ऊर्ध्व दिशा का ओवरफ़्लो संभालता है।'],
  'box-sizing': ['너비에 테두리와 안쪽 여백을 포함할지 정합니다. border-box가 계산이 편합니다.', 'Decides whether width includes padding and border; border-box is the easier one to reason about.', 'Decide si el ancho incluye relleno y borde; border-box es más fácil de calcular.', 'Decide se a largura inclui preenchimento e borda; border-box é mais fácil de calcular.', '幅に内側の余白と枠線を含めるかを決めます。border-boxのほうが計算が楽です。', 'Legt fest, ob die Breite Innenabstand und Rahmen einschließt; border-box rechnet sich leichter.', "Détermine si la largeur inclut la marge intérieure et la bordure ; border-box est plus simple.", 'तय करता है कि चौड़ाई में पैडिंग और बॉर्डर शामिल हों; border-box में हिसाब आसान रहता है।'],
  'aspect-ratio': ['가로세로 비를 고정합니다. 한쪽만 정하면 나머지가 따라옵니다.', 'Locks the width-to-height ratio; set one side and the other follows.', 'Fija la relación ancho-alto: defines un lado y el otro se ajusta.', 'Fixa a relação largura-altura: define um lado e o outro acompanha.', '縦横比を固定します。片方を決めればもう片方が追従します。', 'Fixiert das Verhältnis von Breite zu Höhe; eine Seite genügt.', "Verrouille le rapport largeur/hauteur : un côté suffit.", 'चौड़ाई-ऊँचाई अनुपात तय करता है; एक पक्ष देने पर दूसरा अपने आप बनता है।'],
  'container-type': ['화면이 아니라 부모 상자의 크기에 따라 스타일을 바꿀 수 있게 합니다.', 'Lets styles respond to the size of a parent box instead of the viewport.', 'Permite que los estilos respondan al tamaño de la caja padre, no de la pantalla.', 'Permite que estilos respondam ao tamanho da caixa pai, não da tela.', '画面ではなく親の箱の大きさに応じてスタイルを変えられるようにします。', 'Erlaubt Stile, die auf die Größe eines Elternelements reagieren statt auf das Fenster.', "Permet des styles réagissant à la taille d'un conteneur parent plutôt qu'à l'écran.", 'शैलियों को स्क्रीन नहीं, मूल बॉक्स के आकार पर प्रतिक्रिया देने देता है।'],
  isolation: ['블렌드가 바깥으로 새지 않게 층을 따로 만듭니다.', 'Creates a new stacking layer so blending does not leak outside.', 'Crea una capa nueva para que la mezcla no se salga.', 'Cria uma camada nova para que a mesclagem não vaze.', 'ブレンドが外に漏れないよう層を分けます。', 'Erzeugt eine eigene Ebene, damit Blending nicht nach außen wirkt.', "Crée un nouveau plan pour que le mélange ne déborde pas.", 'नई परत बनाता है ताकि ब्लेंडिंग बाहर न फैले।'],

  /* ───────── 플렉스와 그리드 ───────── */
  'flex-direction': ['플렉스 항목을 가로로 놓을지 세로로 놓을지 정합니다.', 'Sets whether flex items run in a row or a column.', 'Define si los elementos flex van en fila o en columna.', 'Define se os itens flex ficam em linha ou coluna.', 'フレックス項目を横に並べるか縦に並べるかを決めます。', 'Legt fest, ob Flex-Elemente in einer Zeile oder Spalte laufen.', "Indique si les éléments flex s'alignent en ligne ou en colonne.", 'तय करता है कि flex आइटम पंक्ति में चलें या स्तंभ में।'],
  'flex-wrap': ['한 줄에 다 못 들어갈 때 줄을 바꿀지 정합니다.', 'Decides whether items wrap onto a new line when they run out of room.', 'Decide si los elementos pasan a otra línea cuando no caben.', 'Decide se os itens passam para outra linha quando não cabem.', '一行に収まらないとき折り返すかを決めます。', 'Bestimmt, ob Elemente in eine neue Zeile umbrechen.', "Décide si les éléments passent à la ligne quand la place manque.", 'तय करता है कि जगह न बचने पर आइटम अगली पंक्ति में जाएँ।'],
  flex: ['남는 자리를 어떻게 나눌지 한 번에 정합니다. flex: 1이면 고르게 나눕니다.', 'Sets how leftover space is shared in one go; flex: 1 splits it evenly.', 'Reparte el espacio sobrante de una vez; flex: 1 lo divide por igual.', 'Distribui o espaço restante de uma vez; flex: 1 divide igualmente.', '余った場所の分け方をまとめて決めます。flex: 1なら均等に分けます。', 'Regelt in einem Schritt, wie freier Platz verteilt wird; flex: 1 teilt gleichmäßig.', "Règle d'un coup le partage de l'espace restant ; flex: 1 le divise également.", 'बची जगह का बँटवारा एक साथ तय करता है; flex: 1 बराबर बाँटता है।'],
  'flex-grow': ['남는 자리를 얼마나 가져갈지 정합니다.', 'How much of the leftover space this item takes.', 'Cuánto del espacio sobrante toma este elemento.', 'Quanto do espaço restante este item toma.', '余った場所をどれだけ取るかを決めます。', 'Wie viel vom freien Platz dieses Element nimmt.', "La part d'espace restant que prend cet élément.", 'यह आइटम बची जगह का कितना हिस्सा ले।'],
  'flex-shrink': ['자리가 모자랄 때 얼마나 줄어들지 정합니다. 0이면 안 줄어듭니다.', 'How much the item shrinks when space runs short; 0 keeps it fixed.', 'Cuánto se encoge cuando falta espacio; con 0 no se encoge.', 'Quanto o item encolhe quando falta espaço; com 0 não encolhe.', '場所が足りないときどれだけ縮むかを決めます。0なら縮みません。', 'Wie stark das Element bei Platzmangel schrumpft; 0 hält es fest.', "De combien l'élément rétrécit quand la place manque ; 0 le fige.", 'जगह कम पड़ने पर आइटम कितना सिकुड़े; 0 पर नहीं सिकुड़ता।'],
  'flex-basis': ['늘거나 줄기 전의 기준 크기입니다.', 'The starting size before growing or shrinking.', 'El tamaño de partida antes de crecer o encoger.', 'O tamanho inicial antes de crescer ou encolher.', '伸び縮みする前の基準の大きさです。', 'Die Ausgangsgröße vor dem Wachsen oder Schrumpfen.', "La taille de départ avant de grandir ou rétrécir.", 'बढ़ने या सिकुड़ने से पहले का आधार आकार।'],
  'justify-content': ['주축 방향으로 항목들을 어떻게 늘어놓을지 정합니다.', 'Distributes items along the main axis.', 'Reparte los elementos a lo largo del eje principal.', 'Distribui os itens ao longo do eixo principal.', '主軸の方向に項目をどう並べるかを決めます。', 'Verteilt die Elemente entlang der Hauptachse.', "Répartit les éléments le long de l'axe principal.", 'मुख्य अक्ष पर आइटम कैसे बँटें, यह तय करता है।'],
  'align-items': ['교차축 방향으로 항목들을 어떻게 맞출지 정합니다. center가 세로 가운데입니다.', 'Aligns items along the cross axis; center is the usual vertical centring.', 'Alinea los elementos en el eje transversal; center es el centrado vertical habitual.', 'Alinha os itens no eixo transversal; center é a centralização vertical usual.', '交差軸の方向に項目をどう揃えるかを決めます。centerが縦の中央です。', 'Richtet Elemente an der Querachse aus; center ist die übliche vertikale Zentrierung.', "Aligne les éléments sur l'axe transversal ; center centre verticalement.", 'क्रॉस अक्ष पर आइटम कैसे संरेखित हों; center ऊर्ध्व केंद्र देता है।'],
  'align-self': ['한 항목만 다르게 맞출 때 씁니다.', 'Overrides the alignment for a single item.', 'Cambia la alineación de un solo elemento.', 'Altera o alinhamento de um único item.', '一つの項目だけ別に揃えたいときに使います。', 'Überschreibt die Ausrichtung für ein einzelnes Element.', "Modifie l'alignement d'un seul élément.", 'सिर्फ़ एक आइटम का संरेखण बदलता है।'],
  'align-content': ['줄이 여러 개일 때 줄 사이를 어떻게 나눌지 정합니다.', 'Spaces the lines themselves when items wrap onto several rows.', 'Distribuye las líneas cuando los elementos ocupan varias filas.', 'Distribui as linhas quando os itens ocupam várias fileiras.', '行が複数あるとき、行同士の間隔を決めます。', 'Verteilt die Zeilen selbst, wenn Elemente mehrzeilig umbrechen.', "Répartit les lignes elles-mêmes quand les éléments passent sur plusieurs rangées.", 'कई पंक्तियाँ होने पर पंक्तियों के बीच की जगह बाँटता है।'],
  gap: ['항목 사이의 간격입니다. 여백과 달리 바깥쪽에는 생기지 않습니다.', 'The space between items — unlike margins, none is added on the outside.', 'El espacio entre elementos; a diferencia del margen, no se añade por fuera.', 'O espaço entre itens; ao contrário da margem, não sobra por fora.', '項目のあいだの間隔です。余白と違って外側にはつきません。', 'Der Abstand zwischen Elementen — anders als Margins nicht außen.', "L'espace entre les éléments ; contrairement aux marges, rien à l'extérieur.", 'आइटम के बीच की जगह — मार्जिन के उलट बाहर कुछ नहीं जुड़ता।'],
  'row-gap': ['줄과 줄 사이의 간격만 정합니다.', 'Sets only the space between rows.', 'Fija solo el espacio entre filas.', 'Define apenas o espaço entre linhas.', '行と行のあいだの間隔だけを決めます。', 'Legt nur den Abstand zwischen Zeilen fest.', "Ne fixe que l'espace entre les rangées.", 'सिर्फ़ पंक्तियों के बीच की जगह तय करता है।'],
  'column-gap': ['칸과 칸 사이의 간격만 정합니다.', 'Sets only the space between columns.', 'Fija solo el espacio entre columnas.', 'Define apenas o espaço entre colunas.', '列と列のあいだの間隔だけを決めます。', 'Legt nur den Abstand zwischen Spalten fest.', "Ne fixe que l'espace entre les colonnes.", 'सिर्फ़ स्तंभों के बीच की जगह तय करता है।'],
  order: ['HTML 순서를 그대로 두고 보이는 차례만 바꿉니다.', 'Changes the visual order without touching the HTML order.', 'Cambia el orden visual sin tocar el del HTML.', 'Muda a ordem visual sem alterar a do HTML.', 'HTMLの順序はそのままに、見える順番だけ変えます。', 'Ändert die sichtbare Reihenfolge, ohne die HTML-Reihenfolge anzutasten.', "Change l'ordre visuel sans toucher à l'ordre HTML.", 'HTML क्रम बदले बिना दिखने का क्रम बदलता है।'],
  'grid-template-columns': ['그리드의 칸을 몇 개, 어떤 너비로 만들지 정합니다.', 'Defines how many columns the grid has and how wide each is.', 'Define cuántas columnas tiene la cuadrícula y su ancho.', 'Define quantas colunas a grade tem e a largura de cada uma.', 'グリッドの列を何本、どんな幅で作るかを決めます。', 'Legt Anzahl und Breite der Grid-Spalten fest.', "Définit le nombre et la largeur des colonnes de la grille.", 'ग्रिड में कितने स्तंभ और कितने चौड़े हों, यह तय करता है।'],
  'grid-template-rows': ['그리드의 줄을 몇 개, 어떤 높이로 만들지 정합니다.', 'Defines how many rows the grid has and how tall each is.', 'Define cuántas filas tiene la cuadrícula y su alto.', 'Define quantas linhas a grade tem e a altura de cada uma.', 'グリッドの行を何本、どんな高さで作るかを決めます。', 'Legt Anzahl und Höhe der Grid-Zeilen fest.', "Définit le nombre et la hauteur des rangées de la grille.", 'ग्रिड में कितनी पंक्तियाँ और कितनी ऊँची हों, यह तय करता है।'],
  'grid-template-areas': ['칸에 이름을 붙여 배치를 그림처럼 적습니다.', 'Names grid areas so the layout can be written out like a picture.', 'Nombra zonas de la cuadrícula para escribir la maquetación como un dibujo.', 'Nomeia áreas da grade para escrever o layout como um desenho.', 'マス目に名前を付けて、配置を絵のように書けます。', 'Benennt Grid-Bereiche, sodass sich das Layout wie ein Bild aufschreiben lässt.', "Nomme des zones pour écrire la mise en page comme un dessin.", 'ग्रिड क्षेत्रों को नाम देता है ताकि लेआउट चित्र की तरह लिखा जा सके।'],
  'grid-column': ['한 항목이 가로로 몇 칸을 차지할지 정합니다.', 'Sets how many columns an item spans.', 'Indica cuántas columnas ocupa un elemento.', 'Indica quantas colunas um item ocupa.', '一つの項目が横に何マス分を占めるかを決めます。', 'Legt fest, über wie viele Spalten ein Element reicht.', "Indique sur combien de colonnes s'étend un élément.", 'तय करता है कि आइटम कितने स्तंभों में फैले।'],
  'grid-row': ['한 항목이 세로로 몇 줄을 차지할지 정합니다.', 'Sets how many rows an item spans.', 'Indica cuántas filas ocupa un elemento.', 'Indica quantas linhas um item ocupa.', '一つの項目が縦に何マス分を占めるかを決めます。', 'Legt fest, über wie viele Zeilen ein Element reicht.', "Indique sur combien de rangées s'étend un élément.", 'तय करता है कि आइटम कितनी पंक्तियों में फैले।'],
  'grid-auto-flow': ['자리를 지정하지 않은 항목을 어느 방향으로 채울지 정합니다.', 'Decides which way unplaced items fill the grid.', 'Decide en qué dirección se colocan los elementos sin posición.', 'Decide em que direção os itens sem posição preenchem a grade.', '位置を指定していない項目をどの向きに詰めるかを決めます。', 'Bestimmt, in welcher Richtung nicht platzierte Elemente einfließen.', "Détermine dans quel sens se placent les éléments non positionnés.", 'बिना स्थान वाले आइटम किस दिशा में भरें, यह तय करता है।'],
  'grid-auto-rows': ['자동으로 생기는 줄의 높이를 정합니다.', 'Sets the height of rows the grid creates automatically.', 'Fija la altura de las filas creadas automáticamente.', 'Define a altura das linhas criadas automaticamente.', '自動でできる行の高さを決めます。', 'Legt die Höhe automatisch erzeugter Zeilen fest.', "Fixe la hauteur des rangées créées automatiquement.", 'स्वतः बनने वाली पंक्तियों की ऊँचाई तय करता है।'],
  'place-items': ['가로와 세로 정렬을 한 번에 정합니다. center 하나로 가운데가 됩니다.', 'Sets both axes of alignment at once; a single center centres everything.', 'Define ambos ejes de alineación a la vez; con center todo queda centrado.', 'Define os dois eixos de alinhamento de uma vez; com center tudo centraliza.', '縦横の揃え方をまとめて決めます。centerひとつで中央になります。', 'Setzt beide Ausrichtungsachsen auf einmal; ein center zentriert alles.', "Règle les deux axes d'alignement d'un coup ; un seul center centre tout.", 'दोनों अक्षों का संरेखण एक साथ तय करता है; अकेला center सब केंद्र में लाता है।'],
  'place-content': ['내용 덩어리 자체를 가로세로로 어디에 놓을지 정합니다.', 'Positions the whole block of content on both axes.', 'Coloca el bloque de contenido en ambos ejes.', 'Posiciona o bloco de conteúdo nos dois eixos.', '内容のかたまり自体を縦横のどこに置くかを決めます。', 'Positioniert den gesamten Inhaltsblock auf beiden Achsen.', "Place le bloc de contenu sur les deux axes.", 'पूरी सामग्री-गुल्ली को दोनों अक्षों पर रखता है।'],
  'justify-items': ['각 칸 안에서 항목을 가로로 어디에 둘지 정합니다.', 'Places items horizontally inside their own cells.', 'Coloca los elementos horizontalmente dentro de su celda.', 'Posiciona os itens horizontalmente dentro da própria célula.', '各マスの中で項目を横のどこに置くかを決めます。', 'Platziert Elemente waagerecht in ihrer Zelle.', "Place les éléments horizontalement dans leur cellule.", 'हर कोशिका के भीतर आइटम को क्षैतिज रूप से रखता है।'],

  /* ───────── 상자 ───────── */
  width: ['가로 크기입니다. 100%는 부모 기준, 100vw는 화면 기준입니다.', 'The horizontal size; 100% follows the parent, 100vw follows the viewport.', 'El tamaño horizontal; 100% sigue al padre y 100vw a la ventana.', 'O tamanho horizontal; 100% segue o pai e 100vw a janela.', '横の大きさです。100%は親を、100vwは画面を基準にします。', 'Die waagerechte Größe; 100 % folgt dem Elternelement, 100vw dem Fenster.', "La taille horizontale ; 100 % suit le parent, 100vw la fenêtre.", 'क्षैतिज आकार; 100% मूल तत्व और 100vw स्क्रीन के अनुसार।'],
  height: ['세로 크기입니다. auto면 내용만큼만 차지합니다.', 'The vertical size; auto takes only as much as the content needs.', 'El tamaño vertical; con auto ocupa solo lo que pide el contenido.', 'O tamanho vertical; com auto ocupa apenas o que o conteúdo pede.', '縦の大きさです。autoなら内容の分だけになります。', 'Die senkrechte Größe; auto nimmt nur so viel, wie der Inhalt braucht.', "La taille verticale ; auto ne prend que ce qu'exige le contenu.", 'ऊर्ध्व आकार; auto पर उतना ही जितना सामग्री माँगे।'],
  'min-width': ['이보다 좁아지지 않게 막습니다. 플렉스에서 0으로 두면 줄어들 수 있습니다.', 'Stops the box getting narrower than this; inside flex, 0 lets it shrink.', 'Impide que la caja sea más estrecha; en flex, 0 le permite encogerse.', 'Impede a caixa de ficar mais estreita; em flex, 0 permite encolher.', 'これより狭くならないようにします。フレックスでは0にすると縮められます。', 'Verhindert, dass die Box schmaler wird; in Flex erlaubt 0 das Schrumpfen.', "Empêche la boîte d'être plus étroite ; dans flex, 0 autorise le rétrécissement.", 'बॉक्स को इससे पतला नहीं होने देता; flex में 0 उसे सिकुड़ने देता है।'],
  'max-width': ['이보다 넓어지지 않게 막습니다. 글줄 길이를 잡을 때 자주 씁니다.', 'Caps the width; the usual way to keep a line of text readable.', 'Limita el ancho; la forma habitual de controlar la longitud de línea.', 'Limita a largura; o jeito usual de controlar o comprimento da linha.', 'これより広くならないようにします。行の長さを抑えるのによく使います。', 'Begrenzt die Breite; so hält man Textzeilen lesbar.', "Plafonne la largeur ; la façon courante de limiter la longueur des lignes.", 'चौड़ाई की ऊपरी सीमा; पंक्ति की लंबाई पठनीय रखने का सामान्य तरीक़ा।'],
  'min-height': ['이보다 낮아지지 않게 막습니다.', 'Stops the box getting shorter than this.', 'Impide que la caja sea más baja.', 'Impede a caixa de ficar mais baixa.', 'これより低くならないようにします。', 'Verhindert, dass die Box niedriger wird.', "Empêche la boîte d'être plus basse.", 'बॉक्स को इससे कम ऊँचा नहीं होने देता।'],
  'max-height': ['이보다 높아지지 않게 막습니다. 넘치면 overflow가 처리합니다.', 'Caps the height; anything past it is handled by overflow.', 'Limita el alto; lo que sobra lo gestiona overflow.', 'Limita a altura; o que passa é tratado por overflow.', 'これより高くならないようにします。あふれた分はoverflowが扱います。', 'Begrenzt die Höhe; alles darüber regelt overflow.', "Plafonne la hauteur ; le surplus relève d'overflow.", 'ऊँचाई की ऊपरी सीमा; बाक़ी overflow संभालता है।'],
  margin: ['바깥 여백입니다. 위아래는 서로 겹쳐 하나로 합쳐집니다.', 'The space outside the box; top and bottom margins collapse into one.', 'El espacio exterior; los márgenes superior e inferior se colapsan en uno.', 'O espaço externo; margens de topo e base se colapsam em uma.', '外側の余白です。上下は互いに重なって一つにまとまります。', 'Der Außenabstand; obere und untere Margins fallen zusammen.', "L'espace extérieur ; les marges haut et bas fusionnent.", 'बाहरी जगह; ऊपर-नीचे के मार्जिन आपस में मिलकर एक हो जाते हैं।'],
  'margin-top': ['위쪽 바깥 여백입니다.', 'The outer space above the box.', 'El espacio exterior por arriba.', 'O espaço externo acima.', '上側の外の余白です。', 'Der Außenabstand oben.', "L'espace extérieur au-dessus.", 'ऊपर की बाहरी जगह।'],
  'margin-right': ['오른쪽 바깥 여백입니다. auto를 주면 왼쪽으로 밀립니다.', 'The outer space on the right; auto pushes the box left.', 'El espacio exterior derecho; con auto la caja se va a la izquierda.', 'O espaço externo à direita; com auto a caixa vai para a esquerda.', '右側の外の余白です。autoにすると左に寄ります。', 'Der Außenabstand rechts; auto schiebt die Box nach links.', "L'espace extérieur à droite ; auto pousse la boîte à gauche.", 'दाईं ओर की बाहरी जगह; auto देने पर बॉक्स बाईं ओर खिसकता है।'],
  'margin-bottom': ['아래쪽 바깥 여백입니다.', 'The outer space below the box.', 'El espacio exterior por abajo.', 'O espaço externo abaixo.', '下側の外の余白です。', 'Der Außenabstand unten.', "L'espace extérieur en dessous.", 'नीचे की बाहरी जगह।'],
  'margin-left': ['왼쪽 바깥 여백입니다. 좌우를 auto로 두면 가운데 정렬이 됩니다.', 'The outer space on the left; auto on both sides centres the box.', 'El espacio exterior izquierdo; auto a ambos lados centra la caja.', 'O espaço externo à esquerda; auto dos dois lados centraliza a caixa.', '左側の外の余白です。左右をautoにすると中央揃えになります。', 'Der Außenabstand links; auto auf beiden Seiten zentriert die Box.', "L'espace extérieur à gauche ; auto des deux côtés centre la boîte.", 'बाईं ओर की बाहरी जगह; दोनों ओर auto देने पर बॉक्स केंद्र में आ जाता है।'],
  padding: ['안쪽 여백입니다. 배경색이 여기까지 칠해집니다.', 'The space inside the box; the background colour extends into it.', 'El espacio interior; el color de fondo llega hasta aquí.', 'O espaço interno; a cor de fundo chega até aqui.', '内側の余白です。背景色はここまで塗られます。', 'Der Innenabstand; die Hintergrundfarbe reicht bis hierhin.', "L'espace intérieur ; la couleur de fond s'y étend.", 'भीतरी जगह; पृष्ठभूमि का रंग यहाँ तक फैलता है।'],
  'padding-top': ['위쪽 안 여백입니다.', 'The inner space above the content.', 'El espacio interior por arriba.', 'O espaço interno acima.', '上側の内の余白です。', 'Der Innenabstand oben.', "L'espace intérieur au-dessus.", 'ऊपर की भीतरी जगह।'],
  'padding-right': ['오른쪽 안 여백입니다.', 'The inner space to the right of the content.', 'El espacio interior derecho.', 'O espaço interno à direita.', '右側の内の余白です。', 'Der Innenabstand rechts.', "L'espace intérieur à droite.", 'दाईं ओर की भीतरी जगह।'],
  'padding-bottom': ['아래쪽 안 여백입니다. 비율로 주면 높이를 만드는 데도 쓰입니다.', 'The inner space below the content; a percentage here can create height.', 'El espacio interior inferior; en porcentaje sirve para generar altura.', 'O espaço interno abaixo; em porcentagem serve para gerar altura.', '下側の内の余白です。割合で指定すると高さを作るのにも使えます。', 'Der Innenabstand unten; als Prozentwert erzeugt er sogar Höhe.', "L'espace intérieur en dessous ; en pourcentage, il crée de la hauteur.", 'नीचे की भीतरी जगह; प्रतिशत में देने पर ऊँचाई भी बनती है।'],
  'padding-left': ['왼쪽 안 여백입니다.', 'The inner space to the left of the content.', 'El espacio interior izquierdo.', 'O espaço interno à esquerda.', '左側の内の余白です。', 'Der Innenabstand links.', "L'espace intérieur à gauche.", 'बाईं ओर की भीतरी जगह।'],

  /* ───────── 글자 ───────── */
  'font-size': ['글자 크기입니다. rem은 뿌리 글자 크기의 배수라 확대 설정을 따라갑니다.', 'The text size; rem multiplies the root size, so it follows the reader’s zoom setting.', 'El tamaño del texto; rem multiplica el tamaño raíz y respeta el zoom del lector.', 'O tamanho do texto; rem multiplica o tamanho raiz e respeita o zoom do leitor.', '文字の大きさです。remはルートの文字サイズの倍数なので、拡大設定に追従します。', 'Die Schriftgröße; rem vervielfacht die Wurzelgröße und folgt der Zoom-Einstellung.', "La taille du texte ; rem multiplie la taille racine et suit le zoom du lecteur.", 'पाठ का आकार; rem मूल आकार का गुणक है और पाठक की ज़ूम सेटिंग का अनुसरण करता है।'],
  'font-family': ['글꼴을 정합니다. 앞의 것이 없으면 뒤로 넘어가므로 마지막에 갈래를 적습니다.', 'Sets the typeface; the browser falls through the list, so end with a generic family.', 'Define la tipografía; el navegador recorre la lista, así que termina con una familia genérica.', 'Define a fonte; o navegador percorre a lista, então termine com uma família genérica.', '書体を決めます。前のものがなければ次に移るので、最後に総称を書きます。', 'Legt die Schriftart fest; der Browser geht die Liste durch, daher am Ende eine generische Familie.', "Définit la police ; le navigateur parcourt la liste, terminez par une famille générique.", 'टाइपफ़ेस तय करता है; ब्राउज़र सूची में आगे बढ़ता है, इसलिए अंत में सामान्य परिवार दें।'],
  'font-weight': ['글자 굵기입니다. 400이 보통, 700이 굵게입니다.', 'The stroke weight; 400 is regular and 700 is bold.', 'El grosor del trazo; 400 es normal y 700 negrita.', 'A espessura do traço; 400 é normal e 700 é negrito.', '文字の太さです。400が標準、700が太字です。', 'Die Strichstärke; 400 ist normal, 700 fett.', "La graisse ; 400 correspond au normal et 700 au gras.", 'अक्षरों की मोटाई; 400 सामान्य और 700 बोल्ड।'],
  'font-style': ['기울임 여부를 정합니다.', 'Turns italics on or off.', 'Activa o desactiva la cursiva.', 'Liga ou desliga o itálico.', '斜体にするかどうかを決めます。', 'Schaltet Kursivschrift ein oder aus.', "Active ou désactive l'italique.", 'तिरछापन चालू या बंद करता है।'],
  font: ['글꼴 관련 값을 한 줄에 몰아 적습니다. 빠뜨린 값은 기본값으로 되돌아갑니다.', 'Sets several font values at once; anything omitted resets to its default.', 'Fija varios valores de fuente a la vez; lo omitido vuelve a su valor inicial.', 'Define vários valores de fonte de uma vez; o omitido volta ao padrão.', '書体まわりの値をまとめて指定します。省いた値は既定に戻ります。', 'Setzt mehrere Schriftwerte auf einmal; Weggelassenes fällt auf den Standard zurück.', "Regroupe plusieurs valeurs de police ; ce qui est omis revient à sa valeur initiale.", 'फ़ॉन्ट के कई मान एक साथ; छोड़े गए मान डिफ़ॉल्ट पर लौट जाते हैं।'],
  'line-height': ['줄 간격입니다. 단위 없이 1.5처럼 적는 편이 물려줄 때 안전합니다.', 'The line spacing; a unitless value such as 1.5 inherits more safely.', 'El interlineado; un valor sin unidad como 1.5 se hereda mejor.', 'A entrelinha; um valor sem unidade como 1.5 se herda melhor.', '行間です。1.5のように単位なしで書くほうが継承時に安全です。', 'Der Zeilenabstand; ein einheitenloser Wert wie 1.5 vererbt sich sicherer.', "L'interligne ; une valeur sans unité comme 1.5 s'hérite mieux.", 'पंक्ति अंतराल; 1.5 जैसा बिना इकाई मान विरासत में सुरक्षित रहता है।'],
  'letter-spacing': ['글자 사이 간격입니다. 큰 제목에서 살짝 좁히면 정돈돼 보입니다.', 'The space between letters; tightening it slightly suits large headings.', 'El espacio entre letras; apretarlo un poco favorece a los títulos grandes.', 'O espaço entre letras; apertar um pouco favorece títulos grandes.', '文字と文字のあいだの間隔です。大きな見出しでは少し詰めると整って見えます。', 'Der Abstand zwischen Buchstaben; leicht enger wirkt bei großen Überschriften ruhiger.', "L'espacement entre lettres ; le resserrer un peu convient aux grands titres.", 'अक्षरों के बीच की जगह; बड़े शीर्षकों में थोड़ा कसने पर सुव्यवस्थित लगता है।'],
  'word-spacing': ['낱말 사이 간격입니다.', 'The space between words.', 'El espacio entre palabras.', 'O espaço entre palavras.', '語と語のあいだの間隔です。', 'Der Abstand zwischen Wörtern.', "L'espacement entre les mots.", 'शब्दों के बीच की जगह।'],
  'text-align': ['글의 좌우 정렬을 정합니다.', 'Aligns text horizontally.', 'Alinea el texto horizontalmente.', 'Alinha o texto horizontalmente.', '文章の左右の揃え方を決めます。', 'Richtet Text waagerecht aus.', 'Aligne le texte horizontalement.', 'पाठ को क्षैतिज रूप से संरेखित करता है।'],
  'text-decoration': ['밑줄이나 취소선을 붙입니다. 링크의 기본 밑줄을 없앨 때도 씁니다.', 'Adds underlines or strike-throughs; also how you remove a link’s default underline.', 'Añade subrayado o tachado; también sirve para quitar el subrayado de los enlaces.', 'Adiciona sublinhado ou riscado; também remove o sublinhado padrão dos links.', '下線や取り消し線を付けます。リンクの既定の下線を消すときにも使います。', 'Fügt Unter- oder Durchstreichungen hinzu; entfernt auch die Standardunterstreichung von Links.', "Ajoute soulignement ou barré ; sert aussi à retirer le soulignement des liens.", 'रेखांकन या काट जोड़ता है; लिंक का डिफ़ॉल्ट रेखांकन हटाने में भी काम आता है।'],
  'text-decoration-line': ['어떤 줄을 그을지만 정합니다.', 'Chooses which decoration line is drawn.', 'Elige qué línea de decoración se dibuja.', 'Escolhe qual linha de decoração é desenhada.', 'どの線を引くかだけを決めます。', 'Bestimmt nur, welche Linie gezeichnet wird.', "Choisit uniquement la ligne tracée.", 'सिर्फ़ यह चुनता है कि कौन-सी रेखा खिंचे।'],
  'text-decoration-color': ['그 줄의 색만 따로 정합니다.', 'Colours that decoration line on its own.', 'Da color a esa línea por separado.', 'Dá cor àquela linha separadamente.', 'その線の色だけを別に決めます。', 'Färbt allein diese Linie.', "Colore uniquement cette ligne.", 'सिर्फ़ उस रेखा का रंग तय करता है।'],
  'text-decoration-style': ['줄의 모양을 정합니다. wavy는 맞춤법 검사처럼 물결선입니다.', 'Sets the line style; wavy gives the squiggle used by spellcheckers.', 'Define el estilo de línea; wavy da la ondulación del corrector.', 'Define o estilo da linha; wavy dá a ondulação do corretor.', '線の形を決めます。wavyは校正記号のような波線です。', 'Legt den Linienstil fest; wavy ergibt die Wellenlinie der Rechtschreibprüfung.', "Définit le style de ligne ; wavy donne l'ondulation du correcteur.", 'रेखा की शैली; wavy वर्तनी-जाँच जैसी लहरदार रेखा देता है।'],
  'text-transform': ['대소문자를 강제로 바꿉니다. 화면만 바뀌고 원래 글자는 그대로입니다.', 'Forces the letter case for display only; the underlying text is untouched.', 'Cambia mayúsculas y minúsculas solo en pantalla; el texto original no cambia.', 'Muda maiúsculas e minúsculas só na exibição; o texto original fica igual.', '大文字小文字を強制的に変えます。表示だけが変わり、元の文字はそのままです。', 'Erzwingt Groß- oder Kleinschreibung nur in der Anzeige; der Text bleibt unverändert.', "Force la casse à l'affichage seulement ; le texte source reste intact.", 'सिर्फ़ प्रदर्शन में अक्षर-रूप बदलता है; मूल पाठ वैसा ही रहता है।'],
  'text-indent': ['첫 줄을 들여씁니다.', 'Indents the first line of a block.', 'Sangra la primera línea del bloque.', 'Recua a primeira linha do bloco.', '最初の行を字下げします。', 'Rückt die erste Zeile eines Blocks ein.', 'Indente la première ligne du bloc.', 'खंड की पहली पंक्ति को अंदर करता है।'],
  'text-overflow': ['넘치는 글을 말줄임표로 잘라 보여 줍니다. overflow와 nowrap이 함께 있어야 합니다.', 'Trims overflowing text with an ellipsis; needs overflow and nowrap alongside it.', 'Corta el texto que desborda con puntos suspensivos; requiere overflow y nowrap.', 'Corta o texto que transborda com reticências; exige overflow e nowrap.', 'あふれた文章を三点リーダーで切って見せます。overflowとnowrapが必要です。', 'Kürzt überlaufenden Text mit Auslassungspunkten; braucht overflow und nowrap dazu.', "Tronque le texte qui déborde par des points de suspension ; exige overflow et nowrap.", 'उमड़ते पाठ को इलिप्सिस से काटता है; साथ में overflow और nowrap चाहिए।'],
  'text-shadow': ['글자에 그림자를 답니다. 밝은 배경 위 흰 글씨를 살릴 때 씁니다.', 'Casts a shadow behind text — useful for white type on a busy photo.', 'Proyecta sombra tras el texto: útil para letras blancas sobre fotos.', 'Lança sombra atrás do texto: útil para letras brancas sobre fotos.', '文字に影を付けます。明るい背景の上の白い文字を読ませたいときに使います。', 'Wirft einen Schatten hinter den Text — hilfreich für weiße Schrift auf Fotos.', "Projette une ombre derrière le texte : utile pour du blanc sur photo.", 'पाठ के पीछे छाया डालता है — तस्वीर पर सफ़ेद अक्षरों के लिए उपयोगी।'],
  'white-space': ['공백과 줄바꿈을 어떻게 다룰지 정합니다. nowrap이면 한 줄로 이어집니다.', 'Controls how spaces and line breaks are handled; nowrap keeps everything on one line.', 'Controla espacios y saltos de línea; con nowrap todo queda en una línea.', 'Controla espaços e quebras de linha; com nowrap tudo fica em uma linha.', '空白と改行の扱いを決めます。nowrapなら一行につながります。', 'Regelt Leerzeichen und Zeilenumbrüche; nowrap hält alles in einer Zeile.', "Gère espaces et retours à la ligne ; nowrap garde tout sur une ligne.", 'स्पेस और लाइन ब्रेक का व्यवहार; nowrap सब एक पंक्ति में रखता है।'],
  'word-break': ['긴 낱말을 어디서 자를지 정합니다. keep-all은 한국어에서 낱말이 쪼개지지 않게 합니다.', 'Decides where long words may break; keep-all stops Korean words splitting mid-word.', 'Decide dónde se parten las palabras largas; keep-all evita partir palabras en coreano.', 'Decide onde palavras longas quebram; keep-all evita quebrar palavras em coreano.', '長い語をどこで切るかを決めます。keep-allは韓国語で語が割れないようにします。', 'Bestimmt, wo lange Wörter brechen; keep-all verhindert Wortbrüche im Koreanischen.', "Détermine où couper les mots longs ; keep-all évite de couper les mots coréens.", 'लंबे शब्द कहाँ टूटें; keep-all कोरियाई शब्दों को बीच से टूटने से रोकता है।'],
  'overflow-wrap': ['줄을 넘기지 못하는 긴 문자열을 강제로 넘깁니다. 긴 주소에 씁니다.', 'Forces very long unbreakable strings to wrap — handy for long URLs.', 'Fuerza el salto de cadenas largas sin espacios: útil para URLs.', 'Força a quebra de sequências longas sem espaço: útil para URLs.', '折り返せない長い文字列を強制的に折り返します。長いURLに使います。', 'Erzwingt den Umbruch sehr langer Zeichenketten — praktisch bei langen URLs.', "Force le retour à la ligne des chaînes très longues : pratique pour les URL.", 'बहुत लंबी अटूट शृंखलाओं को ज़बरन तोड़ता है — लंबे URL के लिए उपयोगी।'],
  'writing-mode': ['글의 흐름 방향을 바꿉니다. 세로쓰기에 씁니다.', 'Changes the direction text flows — this is how vertical writing is done.', 'Cambia la dirección del texto: así se escribe en vertical.', 'Muda a direção do texto: é assim que se escreve na vertical.', '文章の流れる向きを変えます。縦書きに使います。', 'Ändert die Schreibrichtung — so entsteht vertikaler Satz.', "Change le sens d'écoulement du texte : c'est ainsi qu'on écrit à la verticale.", 'पाठ के बहाव की दिशा बदलता है — ऊर्ध्व लेखन इसी से होता है।'],
  'vertical-align': ['한 줄 안에서 위아래로 어디에 맞출지 정합니다. 표 칸에서도 쓰입니다.', 'Aligns an inline box vertically within its line; also works in table cells.', 'Alinea verticalmente dentro de la línea; también sirve en celdas de tabla.', 'Alinha verticalmente dentro da linha; também vale em células de tabela.', '一行の中で上下のどこに揃えるかを決めます。表のセルでも使います。', 'Richtet Inline-Boxen senkrecht in ihrer Zeile aus; gilt auch in Tabellenzellen.', "Aligne verticalement dans la ligne ; fonctionne aussi dans les cellules.", 'पंक्ति के भीतर ऊर्ध्व संरेखण; तालिका कोशिकाओं में भी काम करता है।'],
  'font-variant-numeric': ['숫자 모양을 고릅니다. tabular-nums는 자릿수를 맞춰 표에서 흔들리지 않게 합니다.', 'Picks a numeral style; tabular-nums keeps digits the same width so tables stop jittering.', 'Elige el estilo de las cifras; tabular-nums iguala su ancho y estabiliza las tablas.', 'Escolhe o estilo dos algarismos; tabular-nums iguala a largura e estabiliza tabelas.', '数字の形を選びます。tabular-numsは幅を揃えて表がぶれないようにします。', 'Wählt eine Ziffernform; tabular-nums hält Ziffern gleich breit, damit Tabellen ruhig bleiben.', "Choisit un style de chiffres ; tabular-nums fixe leur largeur et stabilise les tableaux.", 'अंकों की शैली चुनता है; tabular-nums सबकी चौड़ाई बराबर रखकर तालिकाएँ स्थिर करता है।'],
  hyphens: ['줄 끝에서 낱말을 붙임표로 나눌지 정합니다. 언어 설정이 있어야 동작합니다.', 'Allows words to break with a hyphen at line ends; needs the language to be declared.', 'Permite partir palabras con guion al final de línea; requiere declarar el idioma.', 'Permite quebrar palavras com hífen no fim da linha; exige o idioma declarado.', '行末で語をハイフンで分けるかを決めます。言語の指定が必要です。', 'Erlaubt Worttrennung mit Bindestrich am Zeilenende; setzt eine Sprachangabe voraus.', "Autorise la césure en fin de ligne ; nécessite que la langue soit déclarée.", 'पंक्ति के अंत में शब्द हाइफ़न से टूटें या नहीं; भाषा घोषित होनी चाहिए।'],
  'text-wrap': ['줄을 어떻게 나눌지 정합니다. balance는 제목의 줄 길이를 고르게 맞춥니다.', 'Chooses how lines break; balance evens out the line lengths of a heading.', 'Elige cómo se reparten las líneas; balance iguala su longitud en los títulos.', 'Escolhe como as linhas quebram; balance iguala o comprimento em títulos.', '行の分け方を決めます。balanceは見出しの行の長さを揃えます。', 'Bestimmt den Zeilenumbruch; balance gleicht die Zeilenlängen einer Überschrift aus.', "Choisit la coupure des lignes ; balance égalise la longueur des lignes d'un titre.", 'पंक्तियाँ कैसे टूटें; balance शीर्षक की पंक्तियों की लंबाई बराबर करता है।'],

  /* ───────── 색과 배경 ───────── */
  color: ['글자 색입니다. currentColor는 이 값을 그대로 물려받습니다.', 'The text colour; currentColor elsewhere refers back to this value.', 'El color del texto; currentColor remite a este valor.', 'A cor do texto; currentColor remete a este valor.', '文字の色です。currentColorはこの値をそのまま受け継ぎます。', 'Die Textfarbe; currentColor greift anderswo auf diesen Wert zurück.', "La couleur du texte ; currentColor renvoie à cette valeur.", 'पाठ का रंग; currentColor इसी मान को दोहराता है।'],
  'background-color': ['배경색입니다. 안쪽 여백까지 칠해집니다.', 'The background colour; it fills the padding area too.', 'El color de fondo; llena también el relleno.', 'A cor de fundo; preenche também o padding.', '背景色です。内側の余白まで塗られます。', 'Die Hintergrundfarbe; sie füllt auch den Innenabstand.', "La couleur de fond ; elle remplit aussi la marge intérieure.", 'पृष्ठभूमि का रंग; यह पैडिंग तक भरता है।'],
  'background-image': ['배경에 그림이나 그러데이션을 깝니다. 여러 장을 겹칠 수도 있습니다.', 'Lays an image or gradient behind the content; several can be stacked.', 'Coloca una imagen o degradado de fondo; se pueden apilar varios.', 'Coloca uma imagem ou gradiente ao fundo; vários podem ser empilhados.', '背景に画像やグラデーションを敷きます。複数枚を重ねることもできます。', 'Legt ein Bild oder einen Verlauf hinter den Inhalt; mehrere lassen sich stapeln.', "Place une image ou un dégradé en fond ; on peut en superposer plusieurs.", 'पृष्ठभूमि में चित्र या ग्रेडिएंट रखता है; कई परतें भी लग सकती हैं।'],
  'background-size': ['배경 그림의 크기입니다. cover는 빈틈없이 채우고 contain은 다 보이게 넣습니다.', 'Sizes the background image; cover fills without gaps, contain shows all of it.', 'Dimensiona la imagen de fondo; cover llena sin huecos y contain la muestra entera.', 'Dimensiona a imagem de fundo; cover preenche sem falhas e contain mostra tudo.', '背景画像の大きさです。coverは隙間なく埋め、containは全体が見えるように入れます。', 'Skaliert das Hintergrundbild; cover füllt lückenlos, contain zeigt alles.', "Dimensionne l'image de fond ; cover remplit sans vide, contain montre tout.", 'पृष्ठभूमि चित्र का आकार; cover बिना अंतराल भरता है, contain पूरा दिखाता है।'],
  'background-position': ['배경 그림을 어디에 둘지 정합니다.', 'Positions the background image inside the box.', 'Coloca la imagen de fondo dentro de la caja.', 'Posiciona a imagem de fundo dentro da caixa.', '背景画像をどこに置くかを決めます。', 'Positioniert das Hintergrundbild in der Box.', "Positionne l'image de fond dans la boîte.", 'बॉक्स में पृष्ठभूमि चित्र की स्थिति तय करता है।'],
  'background-repeat': ['배경 그림을 반복할지 정합니다.', 'Decides whether the background image tiles.', 'Decide si la imagen de fondo se repite.', 'Decide se a imagem de fundo se repete.', '背景画像を繰り返すかを決めます。', 'Legt fest, ob sich das Hintergrundbild wiederholt.', "Détermine si l'image de fond se répète.", 'तय करता है कि पृष्ठभूमि चित्र दोहराया जाए या नहीं।'],
  'background-attachment': ['배경이 스크롤을 따라갈지 붙어 있을지 정합니다.', 'Decides whether the background scrolls with the page or stays put.', 'Decide si el fondo se desplaza con la página o queda fijo.', 'Decide se o fundo rola com a página ou fica fixo.', '背景がスクロールに追従するか固定されるかを決めます。', 'Bestimmt, ob der Hintergrund mitscrollt oder feststeht.', "Détermine si le fond défile avec la page ou reste fixe.", 'तय करता है कि पृष्ठभूमि स्क्रॉल के साथ चले या टिकी रहे।'],
  background: ['배경 관련 값을 한 줄에 몰아 적습니다. 빠뜨린 값은 기본값으로 되돌아갑니다.', 'Sets all the background values at once; anything omitted resets to its default.', 'Fija todos los valores de fondo a la vez; lo omitido vuelve a su valor inicial.', 'Define todos os valores de fundo de uma vez; o omitido volta ao padrão.', '背景まわりの値をまとめて指定します。省いた値は既定に戻ります。', 'Setzt alle Hintergrundwerte auf einmal; Weggelassenes fällt auf den Standard zurück.', "Regroupe toutes les valeurs de fond ; ce qui est omis revient à l'initial.", 'पृष्ठभूमि के सभी मान एक साथ; छोड़े गए मान डिफ़ॉल्ट पर लौटते हैं।'],
  'background-clip': ['배경을 어디까지 칠할지 정합니다. text로 두면 글자 모양으로 잘립니다.', 'Limits how far the background paints; text clips it to the letterforms.', 'Limita hasta dónde se pinta el fondo; con text se recorta a las letras.', 'Limita até onde o fundo pinta; com text recorta nas letras.', '背景をどこまで塗るかを決めます。textにすると文字の形に切り抜かれます。', 'Begrenzt, wie weit der Hintergrund reicht; text beschneidet ihn auf die Buchstaben.', "Limite l'étendue du fond ; text le découpe selon les lettres.", 'पृष्ठभूमि कहाँ तक रंगे; text इसे अक्षरों के आकार में काटता है।'],
  opacity: ['전체 투명도입니다. 자식까지 함께 흐려집니다.', 'The overall transparency; children fade along with the element.', 'La transparencia global; los hijos también se atenúan.', 'A transparência geral; os filhos também desbotam.', '全体の透明度です。子要素まで一緒に薄くなります。', 'Die Gesamttransparenz; Kindelemente werden mit blass.', "L'opacité globale ; les enfants s'estompent aussi.", 'समग्र पारदर्शिता; बच्चे तत्व भी साथ में धुँधले होते हैं।'],
  'mix-blend-mode': ['아래 요소와 색을 섞는 방식을 정합니다.', 'Sets how the element’s colours blend with what is beneath.', 'Define cómo se mezclan los colores con lo que hay debajo.', 'Define como as cores se mesclam com o que está abaixo.', '下の要素と色を混ぜる方法を決めます。', 'Legt fest, wie sich die Farben mit dem Untergrund mischen.', "Définit le mélange des couleurs avec ce qui est dessous.", 'नीचे की चीज़ों के साथ रंग कैसे मिलें, यह तय करता है।'],
  'accent-color': ['체크박스나 라디오처럼 브라우저가 그리는 부분의 색을 정합니다.', 'Colours browser-drawn controls such as checkboxes and radio buttons.', 'Da color a los controles que dibuja el navegador, como casillas y radios.', 'Colore os controles desenhados pelo navegador, como caixas e rádios.', 'チェックボックスやラジオなど、ブラウザーが描く部分の色を決めます。', 'Färbt vom Browser gezeichnete Bedienelemente wie Kontrollkästchen.', "Colore les contrôles dessinés par le navigateur, cases et boutons radio.", 'चेकबॉक्स और रेडियो जैसे ब्राउज़र-निर्मित नियंत्रणों का रंग।'],
  'color-scheme': ['밝은 화면과 어두운 화면 중 어느 쪽을 지원하는지 알립니다.', 'Declares which of light and dark the page supports.', 'Declara si la página admite modo claro, oscuro o ambos.', 'Declara se a página suporta modo claro, escuro ou ambos.', '明るい画面と暗い画面のどちらに対応するかを伝えます。', 'Gibt an, welche Farbschemata die Seite unterstützt.', "Déclare les schémas clair et sombre pris en charge.", 'बताता है कि पन्ना हल्की या गहरी योजना में से किसे मानता है।'],

  /* ───────── 테두리 ───────── */
  border: ['테두리 굵기·모양·색을 한 줄에 적습니다.', 'Sets border width, style and colour in one line.', 'Define grosor, estilo y color del borde en una línea.', 'Define espessura, estilo e cor da borda em uma linha.', '枠線の太さ・形・色を一行で書きます。', 'Setzt Rahmenbreite, -stil und -farbe in einer Zeile.', "Définit épaisseur, style et couleur de bordure en une ligne.", 'बॉर्डर की मोटाई, शैली और रंग एक पंक्ति में।'],
  'border-width': ['테두리 굵기만 정합니다.', 'Sets only the border thickness.', 'Fija solo el grosor del borde.', 'Define apenas a espessura da borda.', '枠線の太さだけを決めます。', 'Legt nur die Rahmenstärke fest.', "Ne fixe que l'épaisseur de la bordure.", 'सिर्फ़ बॉर्डर की मोटाई तय करता है।'],
  'border-style': ['테두리 모양만 정합니다. 이 값이 없으면 테두리가 안 보입니다.', 'Sets only the border style; without it the border does not show at all.', 'Fija solo el estilo; sin él el borde no se ve.', 'Define apenas o estilo; sem ele a borda não aparece.', '枠線の形だけを決めます。この値がないと枠線は見えません。', 'Legt nur den Rahmenstil fest; ohne ihn erscheint kein Rahmen.', "Ne fixe que le style ; sans lui, la bordure ne s'affiche pas.", 'सिर्फ़ शैली तय करता है; इसके बिना बॉर्डर दिखता ही नहीं।'],
  'border-color': ['테두리 색만 정합니다.', 'Sets only the border colour.', 'Fija solo el color del borde.', 'Define apenas a cor da borda.', '枠線の色だけを決めます。', 'Legt nur die Rahmenfarbe fest.', "Ne fixe que la couleur de la bordure.", 'सिर्फ़ बॉर्डर का रंग तय करता है।'],
  'border-top': ['위쪽 테두리만 정합니다.', 'Sets the top border only.', 'Define solo el borde superior.', 'Define apenas a borda de cima.', '上の枠線だけを決めます。', 'Setzt nur den oberen Rahmen.', 'Ne définit que la bordure du haut.', 'सिर्फ़ ऊपरी बॉर्डर तय करता है।'],
  'border-bottom': ['아래쪽 테두리만 정합니다. 목록 구분선에 자주 씁니다.', 'Sets the bottom border only — the usual divider between list rows.', 'Define solo el borde inferior: el separador habitual entre filas.', 'Define apenas a borda de baixo: o separador usual entre linhas.', '下の枠線だけを決めます。一覧の区切り線によく使います。', 'Setzt nur den unteren Rahmen — die übliche Trennlinie in Listen.', 'Ne définit que la bordure du bas : le séparateur habituel des listes.', 'सिर्फ़ निचला बॉर्डर — सूची पंक्तियों का सामान्य विभाजक।'],
  'border-radius': ['모서리를 둥글게 깎습니다. 50%면 원, 9999px면 알약 모양이 됩니다.', 'Rounds the corners; 50% makes a circle and a huge value makes a pill.', 'Redondea las esquinas; 50% da un círculo y un valor enorme, una píldora.', 'Arredonda os cantos; 50% vira círculo e um valor enorme vira pílula.', '角を丸くします。50%なら円、9999pxなら丸薬のような形になります。', 'Rundet die Ecken; 50 % ergibt einen Kreis, ein sehr großer Wert eine Pille.', "Arrondit les coins ; 50 % donne un cercle, une valeur énorme une pilule.", 'कोने गोल करता है; 50% वृत्त और बहुत बड़ा मान गोली जैसा आकार देता है।'],
  outline: ['테두리 바깥에 그리는 선입니다. 자리를 차지하지 않아 키보드 초점 표시에 씁니다.', 'A line drawn outside the border; it takes no space, which is why focus rings use it.', 'Una línea fuera del borde; no ocupa espacio, por eso sirve para el foco de teclado.', 'Uma linha fora da borda; não ocupa espaço, por isso serve ao foco do teclado.', '枠線の外に描く線です。場所を取らないのでキーボード焦点の表示に使います。', 'Eine Linie außerhalb des Rahmens; sie braucht keinen Platz — ideal für Fokusringe.', "Un trait tracé hors de la bordure ; sans encombrement, idéal pour le focus clavier.", 'बॉर्डर के बाहर खिंची रेखा; जगह नहीं लेती, इसलिए कीबोर्ड फ़ोकस में काम आती है।'],
  'outline-width': ['그 선의 굵기만 정합니다.', 'Sets only the outline thickness.', 'Fija solo el grosor del contorno.', 'Define apenas a espessura do contorno.', 'その線の太さだけを決めます。', 'Legt nur die Stärke der Outline fest.', "Ne fixe que l'épaisseur du contour.", 'सिर्फ़ आउटलाइन की मोटाई तय करता है।'],
  'outline-style': ['그 선의 모양만 정합니다.', 'Sets only the outline style.', 'Fija solo el estilo del contorno.', 'Define apenas o estilo do contorno.', 'その線の形だけを決めます。', 'Legt nur den Stil der Outline fest.', "Ne fixe que le style du contour.", 'सिर्फ़ आउटलाइन की शैली तय करता है।'],
  'outline-color': ['그 선의 색만 정합니다.', 'Sets only the outline colour.', 'Fija solo el color del contorno.', 'Define apenas a cor do contorno.', 'その線の色だけを決めます。', 'Legt nur die Farbe der Outline fest.', "Ne fixe que la couleur du contour.", 'सिर्फ़ आउटलाइन का रंग तय करता है।'],
  'outline-offset': ['그 선을 요소에서 얼마나 띄울지 정합니다.', 'Pushes the outline away from the element.', 'Separa el contorno del elemento.', 'Afasta o contorno do elemento.', 'その線を要素からどれだけ離すかを決めます。', 'Rückt die Outline vom Element ab.', "Éloigne le contour de l'élément.", 'आउटलाइन को तत्व से कितनी दूर रखे, यह तय करता है।'],
  'box-shadow': ['상자에 그림자를 답니다. inset을 붙이면 안쪽으로 들어갑니다.', 'Casts a shadow around the box; inset moves it inside.', 'Proyecta sombra alrededor de la caja; con inset va por dentro.', 'Lança sombra ao redor da caixa; com inset vai por dentro.', '箱に影を付けます。insetを付けると内側に入ります。', 'Wirft einen Schatten um die Box; inset legt ihn nach innen.', "Projette une ombre autour de la boîte ; inset la place à l'intérieur.", 'बॉक्स के चारों ओर छाया; inset लगाने पर वह भीतर चली जाती है।'],
  /* ───────── 효과 ───────── */
  filter: ['흐림·흑백·밝기 같은 효과를 겁니다. 여러 개를 이어 쓸 수 있습니다.', 'Applies blur, greyscale, brightness and the like; several can be chained.', 'Aplica desenfoque, escala de grises o brillo; se pueden encadenar.', 'Aplica desfoque, escala de cinza ou brilho; podem ser encadeados.', 'ぼかし・白黒・明るさなどの効果をかけます。複数つなげられます。', 'Wendet Weichzeichnen, Graustufen, Helligkeit an; mehrere lassen sich verketten.', "Applique flou, niveaux de gris, luminosité ; on peut les enchaîner.", 'धुँधलापन, श्वेत-श्याम, चमक जैसे प्रभाव; कई एक साथ जोड़े जा सकते हैं।'],
  'backdrop-filter': ['요소 뒤쪽 화면에 효과를 겁니다. 반투명 유리 느낌을 만들 때 씁니다.', 'Filters whatever sits behind the element — this is what makes frosted glass.', 'Filtra lo que hay detrás del elemento: así se logra el cristal esmerilado.', 'Filtra o que está atrás do elemento: é assim que se faz o vidro fosco.', '要素の後ろにある画面に効果をかけます。すりガラスの見た目を作るのに使います。', 'Filtert, was hinter dem Element liegt — so entsteht Milchglas.', "Filtre ce qui se trouve derrière l'élément : c'est l'effet verre dépoli.", 'तत्व के पीछे की सामग्री पर प्रभाव डालता है — धुँधले काँच का रूप इसी से।'],
  'clip-path': ['요소를 정해진 모양으로 잘라 냅니다.', 'Cuts the element down to a given shape.', 'Recorta el elemento según una forma dada.', 'Recorta o elemento em uma forma dada.', '要素を決めた形に切り抜きます。', 'Schneidet das Element auf eine gegebene Form zu.', "Découpe l'élément selon une forme donnée.", 'तत्व को दिए गए आकार में काटता है।'],
  'mask-image': ['그림의 밝기에 따라 요소를 가립니다. 가장자리를 부드럽게 사라지게 할 때 씁니다.', 'Hides parts of an element by the brightness of an image — good for fading edges out.', 'Oculta partes según el brillo de una imagen: útil para desvanecer bordes.', 'Esconde partes conforme o brilho de uma imagem: útil para esmaecer bordas.', '画像の明るさに応じて要素を隠します。端をなめらかに消すのに使います。', 'Blendet Teile nach der Helligkeit eines Bildes aus — gut für weiche Kanten.', "Masque selon la luminosité d'une image : pratique pour estomper les bords.", 'चित्र की चमक के अनुसार तत्व छिपाता है — किनारे धीरे-धीरे मिटाने में उपयोगी।'],
  'object-fit': ['그림이나 영상을 상자에 어떻게 채울지 정합니다. cover가 잘라서 채우기입니다.', 'Decides how an image or video fills its box; cover crops to fill.', 'Decide cómo llena la caja una imagen o vídeo; cover recorta para llenar.', 'Decide como imagem ou vídeo preenche a caixa; cover corta para preencher.', '画像や動画を箱にどう収めるかを決めます。coverは切り取って埋めます。', 'Bestimmt, wie Bild oder Video die Box füllt; cover beschneidet zum Füllen.', "Détermine comment une image ou vidéo remplit sa boîte ; cover rogne pour remplir.", 'चित्र या वीडियो बॉक्स को कैसे भरे; cover काटकर भरता है।'],
  'object-position': ['잘릴 때 어느 부분을 남길지 정합니다. 인물 사진에서 얼굴을 살릴 때 씁니다.', 'Chooses which part survives the crop — the way to keep faces in a photo.', 'Elige qué parte se conserva al recortar: así se salvan las caras.', 'Escolhe qual parte sobrevive ao corte: assim se preservam os rostos.', '切り取られるときどこを残すかを決めます。人物写真で顔を残したいときに使います。', 'Wählt, welcher Teil beim Beschnitt bleibt — so retten Sie Gesichter.', "Choisit la partie conservée au rognage : ainsi on garde les visages.", 'कटाई में कौन-सा हिस्सा बचे; तस्वीर में चेहरा बचाने का तरीक़ा।'],
  'image-rendering': ['확대할 때 부드럽게 할지 또렷하게 할지 정합니다. 도트 그림에는 pixelated를 씁니다.', 'Chooses smooth or crisp scaling; pixelated keeps pixel art sharp.', 'Elige escalado suave o nítido; pixelated conserva el pixel art.', 'Escolhe escalonamento suave ou nítido; pixelated preserva pixel art.', '拡大時になめらかにするか輪郭を残すかを決めます。ドット絵にはpixelatedを使います。', 'Wählt weiche oder harte Skalierung; pixelated hält Pixelart scharf.', "Choisit un lissage doux ou net ; pixelated garde le pixel art net.", 'बड़ा करने पर चिकना या स्पष्ट — पिक्सेल आर्ट के लिए pixelated।'],

  /* ───────── 변형과 움직임 ───────── */
  transform: ['옮기고 돌리고 키웁니다. 자리는 그대로 두고 그림만 움직이므로 배치가 흔들리지 않습니다.', 'Moves, rotates and scales; the layout box stays put, so nothing else shifts.', 'Mueve, gira y escala; la caja no se mueve, así que nada más se descoloca.', 'Move, gira e escala; a caixa fica no lugar, então nada mais se desloca.', '移動・回転・拡大をします。占める場所はそのままなので配置がずれません。', 'Verschiebt, dreht und skaliert; die Layout-Box bleibt, nichts verrutscht.', "Déplace, tourne et redimensionne ; la boîte reste en place, rien ne bouge autour.", 'खिसकाता, घुमाता और बड़ा करता है; लेआउट बॉक्स वहीं रहता है, बाक़ी नहीं हिलता।'],
  'transform-origin': ['돌리거나 키울 때의 기준점입니다.', 'The anchor point for rotation and scaling.', 'El punto de anclaje al girar o escalar.', 'O ponto de âncora ao girar ou escalar.', '回転や拡大の基準となる点です。', 'Der Bezugspunkt für Drehung und Skalierung.', "Le point d'ancrage des rotations et mises à l'échelle.", 'घुमाव और स्केलिंग का आधार बिंदु।'],
  transition: ['값이 바뀔 때 부드럽게 이어 줍니다. 무엇을 얼마 동안 어떻게 바꿀지 한 줄에 적습니다.', 'Eases a value from old to new; one line names what changes, for how long and how.', 'Suaviza el cambio de un valor; en una línea se dice qué, cuánto y cómo.', 'Suaviza a mudança de um valor; em uma linha diz o quê, por quanto e como.', '値が変わるときになめらかにつなぎます。何をどれだけどう変えるかを一行で書きます。', 'Überführt Werte weich; eine Zeile nennt was, wie lange und wie.', "Adoucit le passage d'une valeur à l'autre : quoi, combien de temps, comment.", 'मान बदलने पर सहज संक्रमण; एक पंक्ति में क्या, कितनी देर और कैसे।'],
  'transition-property': ['어떤 속성을 부드럽게 바꿀지 정합니다. all은 편하지만 느려질 수 있습니다.', 'Names which properties animate; all is convenient but can cost performance.', 'Indica qué propiedades se animan; all es cómodo pero puede pesar.', 'Indica quais propriedades animam; all é cômodo mas pode pesar.', 'どの属性をなめらかに変えるかを決めます。allは楽ですが重くなることがあります。', 'Nennt die zu animierenden Eigenschaften; all ist bequem, kann aber bremsen.', "Indique les propriétés animées ; all est pratique mais peut coûter cher.", 'कौन-सी विशेषताएँ एनिमेट हों; all सुविधाजनक है पर भारी पड़ सकता है।'],
  'transition-delay': ['시작을 얼마나 미룰지 정합니다.', 'How long to wait before the transition starts.', 'Cuánto se espera antes de empezar.', 'Quanto se espera antes de começar.', '始まりをどれだけ遅らせるかを決めます。', 'Wie lange vor dem Start gewartet wird.', "Le délai avant le début de la transition.", 'शुरू होने से पहले कितनी देर रुके।'],
  'transition-duration': ['바뀌는 데 걸리는 시간입니다. 0.2초 안팎이 자연스럽습니다.', 'How long the change takes; around 0.2 s feels natural.', 'Cuánto dura el cambio; unos 0,2 s resulta natural.', 'Quanto dura a mudança; cerca de 0,2 s parece natural.', '変化にかかる時間です。0.2秒前後が自然に感じられます。', 'Wie lange der Wechsel dauert; rund 0,2 s wirkt natürlich.', "La durée du changement ; environ 0,2 s paraît naturel.", 'बदलाव में लगने वाला समय; लगभग 0.2 सेकंड स्वाभाविक लगता है।'],
  'transition-timing-function': ['빠르기의 흐름을 정합니다. ease는 시작과 끝이 부드럽습니다.', 'Shapes the pacing; ease starts and ends gently.', 'Da forma al ritmo; ease empieza y termina suave.', 'Molda o ritmo; ease começa e termina suave.', '速さの流れを決めます。easeは始まりと終わりがなめらかです。', 'Formt den Ablauf; ease beginnt und endet sanft.', "Façonne le rythme ; ease démarre et finit en douceur.", 'गति का प्रवाह; ease शुरू और अंत में कोमल रहता है।'],
  animation: ['정해 둔 키프레임을 재생합니다. 이름·시간·반복을 한 줄에 적습니다.', 'Plays a set of keyframes; name, duration and repetition go in one line.', 'Reproduce fotogramas clave; nombre, duración y repetición en una línea.', 'Reproduz quadros-chave; nome, duração e repetição em uma linha.', '決めておいたキーフレームを再生します。名前・時間・繰り返しを一行で書きます。', 'Spielt Keyframes ab; Name, Dauer und Wiederholung in einer Zeile.', "Joue des images clés ; nom, durée et répétition en une ligne.", 'तय कीफ़्रेम चलाता है; नाम, अवधि और दोहराव एक पंक्ति में।'],
  'animation-name': ['재생할 키프레임의 이름입니다.', 'The name of the keyframes to play.', 'El nombre de los fotogramas clave.', 'O nome dos quadros-chave.', '再生するキーフレームの名前です。', 'Der Name der abzuspielenden Keyframes.', "Le nom des images clés à jouer.", 'चलाए जाने वाले कीफ़्रेम का नाम।'],
  'animation-timing-function': ['움직임의 빠르기 흐름입니다. steps로 두면 뚝뚝 끊깁니다.', 'The pacing of the motion; steps makes it advance in jumps.', 'El ritmo del movimiento; con steps avanza a saltos.', 'O ritmo do movimento; com steps avança aos saltos.', '動きの速さの流れです。stepsにすると段階的に進みます。', 'Der Ablauf der Bewegung; steps lässt sie springen.', "Le rythme du mouvement ; steps le fait avancer par paliers.", 'गति का प्रवाह; steps देने पर यह चरणों में बढ़ता है।'],
  'animation-duration': ['한 번 도는 데 걸리는 시간입니다.', 'How long one cycle takes.', 'Cuánto dura un ciclo.', 'Quanto dura um ciclo.', '一回りにかかる時間です。', 'Wie lange ein Durchlauf dauert.', "La durée d'un cycle.", 'एक चक्र में लगने वाला समय।'],
  'animation-iteration-count': ['몇 번 반복할지 정합니다. infinite면 멈추지 않습니다.', 'How many times it repeats; infinite never stops.', 'Cuántas veces se repite; con infinite no para.', 'Quantas vezes repete; com infinite não para.', '何回繰り返すかを決めます。infiniteなら止まりません。', 'Wie oft es sich wiederholt; infinite hört nie auf.', "Le nombre de répétitions ; infinite ne s'arrête jamais.", 'कितनी बार दोहराए; infinite पर कभी नहीं रुकता।'],
  'will-change': ['곧 바뀔 속성을 미리 알려 브라우저가 준비하게 합니다. 남발하면 오히려 느려집니다.', 'Warns the browser what will change so it can prepare; overusing it backfires.', 'Avisa al navegador de qué cambiará; abusar de ello es contraproducente.', 'Avisa o navegador do que vai mudar; abusar disso sai pela culatra.', 'まもなく変わる属性を前もって伝え、ブラウザーに備えさせます。使いすぎると逆に重くなります。', 'Kündigt dem Browser Änderungen an; im Übermaß bewirkt es das Gegenteil.', "Prévient le navigateur de ce qui va changer ; en abuser nuit à la performance.", 'ब्राउज़र को आने वाले बदलाव की सूचना; अति करने पर उल्टा असर होता है।'],
  perspective: ['3차원 변형의 원근감을 정합니다. 값이 작을수록 과장됩니다.', 'Sets the depth of 3D transforms; smaller values exaggerate the effect.', 'Fija la profundidad de las transformaciones 3D; valores menores exageran.', 'Define a profundidade das transformações 3D; valores menores exageram.', '三次元変形の遠近感を決めます。値が小さいほど誇張されます。', 'Legt die Tiefe von 3D-Transformationen fest; kleinere Werte übertreiben.', "Définit la profondeur des transformations 3D ; plus la valeur est petite, plus l'effet est marqué.", '3D रूपांतरण की गहराई; छोटा मान प्रभाव को बढ़ा देता है।'],

  /* ───────── 위치 ───────── */
  position: ['위치를 잡는 방식을 정합니다. sticky는 스크롤하다 정해진 자리에서 붙습니다.', 'Chooses the positioning scheme; sticky pins an element once you scroll past it.', 'Elige el esquema de posición; sticky fija el elemento al desplazarse.', 'Escolhe o esquema de posição; sticky fixa o elemento ao rolar.', '位置の取り方を決めます。stickyはスクロールして決めた位置に貼りつきます。', 'Wählt das Positionierungsschema; sticky heftet ein Element beim Scrollen fest.', "Choisit le mode de positionnement ; sticky fixe l'élément au défilement.", 'स्थिति निर्धारण की विधि; sticky स्क्रॉल पर तत्व को तय जगह चिपका देता है।'],
  top: ['기준에서 위로부터 얼마나 떨어질지 정합니다.', 'How far from the top edge the element sits.', 'A qué distancia queda del borde superior.', 'A que distância fica da borda superior.', '基準の上からどれだけ離すかを決めます。', 'Wie weit vom oberen Rand das Element sitzt.', "La distance depuis le bord supérieur.", 'ऊपरी किनारे से कितनी दूरी।'],
  right: ['기준에서 오른쪽으로부터 얼마나 떨어질지 정합니다.', 'How far from the right edge the element sits.', 'A qué distancia queda del borde derecho.', 'A que distância fica da borda direita.', '基準の右からどれだけ離すかを決めます。', 'Wie weit vom rechten Rand das Element sitzt.', "La distance depuis le bord droit.", 'दाएँ किनारे से कितनी दूरी।'],
  bottom: ['기준에서 아래로부터 얼마나 떨어질지 정합니다.', 'How far from the bottom edge the element sits.', 'A qué distancia queda del borde inferior.', 'A que distância fica da borda inferior.', '基準の下からどれだけ離すかを決めます。', 'Wie weit vom unteren Rand das Element sitzt.', "La distance depuis le bord inférieur.", 'निचले किनारे से कितनी दूरी।'],
  left: ['기준에서 왼쪽으로부터 얼마나 떨어질지 정합니다.', 'How far from the left edge the element sits.', 'A qué distancia queda del borde izquierdo.', 'A que distância fica da borda esquerda.', '基準の左からどれだけ離すかを決めます。', 'Wie weit vom linken Rand das Element sitzt.', "La distance depuis le bord gauche.", 'बाएँ किनारे से कितनी दूरी।'],
  inset: ['위·오른쪽·아래·왼쪽을 한 번에 정합니다. 0으로 두면 부모를 꽉 채웁니다.', 'Sets all four offsets at once; 0 stretches the element over its parent.', 'Fija los cuatro lados a la vez; con 0 llena el padre por completo.', 'Define os quatro lados de uma vez; com 0 preenche todo o pai.', '上下左右をまとめて決めます。0にすると親いっぱいに広がります。', 'Setzt alle vier Abstände auf einmal; 0 spannt das Element über das Elternelement.', "Règle les quatre décalages d'un coup ; 0 étire l'élément sur tout son parent.", 'चारों दूरियाँ एक साथ; 0 पर तत्व मूल बॉक्स को पूरा भर देता है।'],
  'z-index': ['겹칠 때 누가 위에 올지 정합니다. 같은 층 안에서만 견줍니다.', 'Decides what stacks on top; the comparison only happens within one stacking context.', 'Decide qué queda encima; solo se compara dentro del mismo contexto de apilamiento.', 'Decide o que fica em cima; compara-se só dentro do mesmo contexto de empilhamento.', '重なったときどちらが上に来るかを決めます。同じ層の中でだけ比べます。', 'Bestimmt, was obenauf liegt; verglichen wird nur im selben Stapelkontext.', "Détermine ce qui passe au-dessus ; la comparaison se fait dans un même contexte d'empilement.", 'ऊपर कौन रहे, यह तय करता है; तुलना एक ही स्टैकिंग संदर्भ में होती है।'],

  /* ───────── 표·목록 ───────── */
  'border-collapse': ['표 칸의 테두리를 하나로 합칠지 정합니다. collapse가 선이 겹치지 않습니다.', 'Merges adjacent cell borders into one; collapse avoids doubled lines.', 'Fusiona los bordes contiguos; collapse evita las líneas dobles.', 'Funde as bordas vizinhas; collapse evita linhas duplicadas.', '表のセルの枠線を一つにまとめるかを決めます。collapseなら線が重なりません。', 'Führt benachbarte Zellenrahmen zusammen; collapse vermeidet doppelte Linien.', "Fusionne les bordures voisines ; collapse évite les traits doublés.", 'सटी कोशिकाओं के बॉर्डर मिलाता है; collapse दोहरी रेखाएँ रोकता है।'],
  'border-spacing': ['칸 사이의 간격입니다. collapse가 아닐 때만 뜻이 있습니다.', 'The gap between cells; only meaningful when borders are not collapsed.', 'El espacio entre celdas; solo cuenta si no se colapsan los bordes.', 'O espaço entre células; só vale quando as bordas não colapsam.', 'セルのあいだの間隔です。collapseでないときにだけ意味があります。', 'Der Abstand zwischen Zellen; nur ohne collapse relevant.', "L'espace entre cellules ; utile seulement sans collapse.", 'कोशिकाओं के बीच की जगह; collapse न होने पर ही अर्थपूर्ण।'],
  'table-layout': ['칸 너비를 내용에 맞출지 미리 정할지 고릅니다. fixed가 훨씬 빠릅니다.', 'Chooses content-driven or fixed column widths; fixed renders much faster.', 'Elige anchos según el contenido o fijos; fixed es mucho más rápido.', 'Escolhe larguras conforme o conteúdo ou fixas; fixed é bem mais rápido.', '列幅を内容に合わせるか先に決めるかを選びます。fixedのほうがずっと速いです。', 'Wählt inhaltsabhängige oder feste Spaltenbreiten; fixed rendert deutlich schneller.', "Choisit des colonnes selon le contenu ou fixes ; fixed est bien plus rapide.", 'स्तंभ चौड़ाई सामग्री से या पहले से तय; fixed कहीं तेज़ है।'],
  'caption-side': ['표 제목을 위에 둘지 아래에 둘지 정합니다.', 'Puts the table caption above or below.', 'Sitúa el título de la tabla arriba o abajo.', 'Põe a legenda da tabela acima ou abaixo.', '表の題名を上に置くか下に置くかを決めます。', 'Stellt die Tabellenbeschriftung nach oben oder unten.', "Place la légende du tableau au-dessus ou en dessous.", 'तालिका का शीर्षक ऊपर रखे या नीचे।'],
  'list-style': ['목록 기호의 모양·위치·그림을 한 줄에 적습니다. none이면 기호가 사라집니다.', 'Sets the marker type, position and image in one line; none removes the marker.', 'Define tipo, posición e imagen del marcador en una línea; none lo quita.', 'Define tipo, posição e imagem do marcador em uma linha; none o remove.', '目印の形・位置・画像を一行で書きます。noneにすると目印が消えます。', 'Setzt Markertyp, -position und -bild in einer Zeile; none entfernt den Marker.', "Définit type, position et image du marqueur en une ligne ; none le supprime.", 'मार्कर का प्रकार, स्थान और चित्र एक पंक्ति में; none मार्कर हटा देता है।'],
  'list-style-type': ['목록 기호의 모양만 정합니다.', 'Sets only the marker shape.', 'Fija solo la forma del marcador.', 'Define apenas a forma do marcador.', '目印の形だけを決めます。', 'Legt nur die Markerform fest.', "Ne fixe que la forme du marqueur.", 'सिर्फ़ मार्कर का आकार तय करता है।'],
  'list-style-image': ['목록 기호로 쓸 그림을 정합니다.', 'Uses an image as the list marker.', 'Usa una imagen como marcador de lista.', 'Usa uma imagem como marcador da lista.', '目印として使う画像を決めます。', 'Verwendet ein Bild als Listenmarker.', "Utilise une image comme marqueur de liste.", 'सूची मार्कर के रूप में चित्र तय करता है।'],
  'list-style-position': ['기호를 글 안쪽에 둘지 바깥에 둘지 정합니다.', 'Places the marker inside or outside the text block.', 'Coloca el marcador dentro o fuera del bloque de texto.', 'Põe o marcador dentro ou fora do bloco de texto.', '目印を文章の内側に置くか外側に置くかを決めます。', 'Setzt den Marker innerhalb oder außerhalb des Textblocks.', "Place le marqueur à l'intérieur ou à l'extérieur du bloc.", 'मार्कर पाठ खंड के भीतर रखे या बाहर।'],

  /* ───────── 조작 ───────── */
  cursor: ['마우스 포인터 모양을 정합니다. 누를 수 있는 것에는 pointer를 씁니다.', 'Sets the mouse pointer shape; pointer signals that something is clickable.', 'Define la forma del puntero; pointer indica que algo se puede pulsar.', 'Define a forma do ponteiro; pointer indica que algo é clicável.', 'マウスポインターの形を決めます。押せるものにはpointerを使います。', 'Legt die Zeigerform fest; pointer signalisiert Klickbarkeit.', "Définit la forme du curseur ; pointer signale un élément cliquable.", 'माउस पॉइंटर का आकार; pointer बताता है कि चीज़ क्लिक-योग्य है।'],
  'pointer-events': ['마우스 입력을 받을지 정합니다. none이면 클릭이 뒤로 통과합니다.', 'Decides whether the element receives pointer input; none lets clicks pass through.', 'Decide si recibe eventos de puntero; con none los clics lo atraviesan.', 'Decide se recebe eventos de ponteiro; com none os cliques atravessam.', 'マウス入力を受けるかを決めます。noneならクリックが後ろへ通り抜けます。', 'Bestimmt, ob das Element Zeigereingaben erhält; none lässt Klicks durch.', "Détermine si l'élément reçoit les événements de pointeur ; none les laisse passer.", 'तय करता है कि तत्व पॉइंटर इनपुट ले या नहीं; none पर क्लिक पार निकल जाते हैं।'],
  'user-select': ['글자를 드래그해 선택할 수 있는지 정합니다.', 'Decides whether text can be selected by dragging.', 'Decide si se puede seleccionar el texto arrastrando.', 'Decide se o texto pode ser selecionado arrastando.', '文字をドラッグして選べるかを決めます。', 'Bestimmt, ob Text per Ziehen markiert werden kann.', "Détermine si le texte peut être sélectionné à la souris.", 'तय करता है कि पाठ खींचकर चुना जा सके या नहीं।'],
  'touch-action': ['터치 제스처를 브라우저가 처리할지 정합니다. manipulation은 더블탭 확대를 없앱니다.', 'Controls which touch gestures the browser handles; manipulation drops double-tap zoom.', 'Controla qué gestos táctiles gestiona el navegador; manipulation quita el zoom por doble toque.', 'Controla quais gestos o navegador trata; manipulation remove o zoom de toque duplo.', 'タッチ操作をブラウザーが処理するかを決めます。manipulationはダブルタップ拡大をなくします。', 'Steuert, welche Gesten der Browser behandelt; manipulation entfernt den Doppeltipp-Zoom.', "Contrôle les gestes gérés par le navigateur ; manipulation supprime le zoom par double tap.", 'ब्राउज़र कौन-से टच जेस्चर संभाले; manipulation डबल-टैप ज़ूम हटा देता है।'],
  'scroll-behavior': ['스크롤을 부드럽게 할지 정합니다.', 'Makes scrolling jump or glide.', 'Hace que el desplazamiento salte o fluya.', 'Faz a rolagem saltar ou deslizar.', 'スクロールをなめらかにするかを決めます。', 'Lässt Scrollen springen oder gleiten.', "Rend le défilement instantané ou fluide.", 'स्क्रॉल तुरंत हो या सहज, यह तय करता है।'],
  'scroll-snap-type': ['스크롤이 정해진 자리에 착 붙게 합니다. 가로 목록에 자주 씁니다.', 'Snaps scrolling to set positions — common in horizontal carousels.', 'Ajusta el desplazamiento a posiciones fijas: habitual en carruseles.', 'Encaixa a rolagem em posições fixas: comum em carrosséis.', 'スクロールを決めた位置にぴたりと止めます。横並びの一覧によく使います。', 'Rastet das Scrollen an festen Punkten ein — üblich in Karussells.', "Cale le défilement sur des positions fixes : courant dans les carrousels.", 'स्क्रॉल को तय बिंदुओं पर टिकाता है — क्षैतिज सूचियों में आम।'],
  'overscroll-behavior': ['끝까지 스크롤했을 때 부모까지 움직일지 정합니다. contain이면 안에서 멈춥니다.', 'Decides whether scrolling past the end moves the parent; contain stops it inside.', 'Decide si al llegar al final se mueve el padre; contain lo detiene dentro.', 'Decide se ao chegar ao fim o pai se move; contain para dentro.', '端まで滑らせたとき親まで動くかを決めます。containなら中で止まります。', 'Bestimmt, ob am Ende der Elternbereich mitscrollt; contain hält es innen.', "Détermine si arriver au bout entraîne le parent ; contain stoppe à l'intérieur.", 'अंत तक स्क्रॉल करने पर मूल तत्व चले या नहीं; contain भीतर ही रोकता है।'],
  resize: ['사용자가 크기를 바꿀 수 있게 할지 정합니다. textarea에서 자주 씁니다.', 'Lets the user resize the box — most often used on a textarea.', 'Permite al usuario cambiar el tamaño; se usa sobre todo en textarea.', 'Permite ao usuário redimensionar; usado sobretudo em textarea.', '利用者が大きさを変えられるかを決めます。textareaでよく使います。', 'Erlaubt Nutzern, die Box zu skalieren — meist bei textarea.', "Permet à l'utilisateur de redimensionner ; surtout sur textarea.", 'उपयोगकर्ता आकार बदल सके या नहीं; अक्सर textarea में।'],
  'caret-color': ['입력 칸의 깜빡이는 커서 색을 정합니다.', 'Colours the blinking text cursor in an input.', 'Da color al cursor parpadeante del campo.', 'Colore o cursor piscante do campo.', '入力欄で点滅するカーソルの色を決めます。', 'Färbt den blinkenden Textcursor im Eingabefeld.', "Colore le curseur clignotant du champ de saisie.", 'इनपुट में टिमटिमाते कर्सर का रंग।'],

  /* ───────── 인쇄와 기타 ───────── */
  'page-break-after': ['인쇄할 때 이 뒤에서 쪽을 넘길지 정합니다.', 'Forces or avoids a page break after the element when printing.', 'Fuerza o evita un salto de página después al imprimir.', 'Força ou evita quebra de página depois, ao imprimir.', '印刷時にこの後ろでページを変えるかを決めます。', 'Erzwingt oder vermeidet beim Druck einen Seitenumbruch danach.', "Force ou évite un saut de page après, à l'impression.", 'छपाई में इसके बाद पृष्ठ बदले या नहीं।'],
  'break-inside': ['인쇄나 다단에서 요소 가운데가 잘리지 않게 막습니다.', 'Stops an element from being split across pages or columns.', 'Impide que el elemento se parta entre páginas o columnas.', 'Impede que o elemento se parta entre páginas ou colunas.', '印刷や段組みで要素の途中が切れないようにします。', 'Verhindert, dass ein Element über Seiten oder Spalten zerrissen wird.', "Empêche un élément d'être coupé entre pages ou colonnes.", 'तत्व पन्नों या स्तंभों के बीच न टूटे, यह रोकता है।'],
  content: ['::before나 ::after로 만들어 넣을 내용입니다. 빈 따옴표만 두는 일도 많습니다.', 'The content generated by ::before or ::after; often just an empty pair of quotes.', 'El contenido que generan ::before o ::after; a menudo solo comillas vacías.', 'O conteúdo gerado por ::before ou ::after; muitas vezes só aspas vazias.', '::beforeや::afterで作って入れる内容です。空の引用符だけ置くこともよくあります。', 'Der von ::before oder ::after erzeugte Inhalt; oft nur ein leeres Anführungspaar.', "Le contenu généré par ::before ou ::after ; souvent de simples guillemets vides.", '::before या ::after से बनने वाली सामग्री; अक्सर सिर्फ़ खाली उद्धरण।'],
  'counter-reset': ['번호 매기기를 시작하거나 되돌립니다.', 'Starts or resets a counter used for numbering.', 'Inicia o reinicia un contador de numeración.', 'Inicia ou reinicia um contador de numeração.', '番号付けを始めるか、元に戻します。', 'Startet oder setzt einen Zähler für Nummerierungen zurück.', "Démarre ou réinitialise un compteur de numérotation.", 'गिनती शुरू करता या रीसेट करता है।'],
  'counter-increment': ['번호를 하나 올립니다. content와 짝을 이뤄 목차 번호를 만듭니다.', 'Steps a counter forward; paired with content it numbers headings automatically.', 'Avanza el contador; junto a content numera títulos automáticamente.', 'Avança o contador; junto de content numera títulos automaticamente.', '番号を一つ進めます。contentと組み合わせて目次番号を作ります。', 'Erhöht einen Zähler; zusammen mit content nummeriert das Überschriften.', "Incrémente un compteur ; avec content, il numérote les titres.", 'गिनती एक बढ़ाता है; content के साथ मिलकर शीर्षकों की संख्या बनाता है।'],
  quotes: ['q 태그가 쓸 따옴표 모양을 언어에 맞게 정합니다.', 'Chooses the quotation marks the q element uses, per language.', 'Elige las comillas que usa el elemento q según el idioma.', 'Escolhe as aspas que o elemento q usa conforme o idioma.', 'qタグが使う引用符の形を言語に合わせて決めます。', 'Wählt die Anführungszeichen für das q-Element je Sprache.', "Choisit les guillemets employés par q selon la langue.", 'q तत्व किन उद्धरण चिह्नों का प्रयोग करे, भाषा के अनुसार।'],
  all: ['그 요소의 모든 속성을 한 번에 되돌립니다. 낯선 스타일을 지울 때 씁니다.', 'Resets every property on the element at once — a blunt way to clear inherited styles.', 'Reinicia todas las propiedades de golpe: útil para borrar estilos heredados.', 'Reinicia todas as propriedades de uma vez: útil para limpar estilos herdados.', 'その要素のすべての属性を一度に戻します。見慣れないスタイルを消すときに使います。', 'Setzt alle Eigenschaften des Elements auf einmal zurück — grob, aber wirksam.', "Réinitialise toutes les propriétés d'un coup : utile pour effacer des styles hérités.", 'तत्व की सारी विशेषताएँ एक साथ रीसेट करता है — विरासती शैलियाँ मिटाने का सीधा तरीक़ा।'],
};


/** 속성 이름과 언어로 한 줄 설명을 꺼낸다 */
export function propDesc(name: string, lang: string): string {
  const row = CSS_DESC[name];
  if (!row) return '';
  const i = LANG_ORDER.indexOf(lang as (typeof LANG_ORDER)[number]);
  return row[i >= 0 ? i : 1];
}
