/**
 * 용어 뜻풀이(3언어) — 입력·결과 표에서 라벨 옆에 한 줄로 붙는다.
 *
 * TERMS는 "이 개념을 세 언어로 뭐라 부르나"만 정한다. 여기는 "그게 무슨
 * 뜻인가"를 적는다. 개념 하나를 한 번만 설명해 두면 그 개념을 쓰는 페이지
 * 전부가 같은 설명을 물려받는다 — 삼백 페이지에 같은 말을 삼백 번 쓰지 않는다.
 *
 * 없는 키는 그냥 설명이 안 붙는다. 새 도구를 만든 사람이 여기 채우기 전에도
 * 표는 정상으로 나와야 한다.
 */
import type { FormulaLang, Term } from './terms.ts';
import { FORMULA_L10N } from './l10n/index.ts';
import { RATE_DESC } from './glossary-rate.ts';
import { BODY2_DESC } from './glossary-body.ts';
import { GEO2_DESC, GEO3_DESC } from './glossary-geo.ts';

const CORE_DESC: Record<string, Term> = {
  /* ───────── 가격·거래 ───────── */
  price: { ko: '지금 매겨진 값. 세금이 붙기 전인지 뒤인지를 먼저 정해야 합니다.', en: 'The amount being charged. Decide first whether it is before or after tax.' },
  cost: { ko: '물건을 들여오거나 만드는 데 든 돈. 판매가에서 이걸 빼면 이익입니다.', en: 'What it cost you to buy or make. Sale price minus this is profit.' },
  listPrice: { ko: '할인 전에 붙어 있던 값. 영수증의 "정상가"입니다.', en: 'The price before any discount — the "was" price on a receipt.' },
  salePrice: { ko: '할인이 적용된 뒤 실제로 결제하는 값.', en: 'What you actually hand over at the till, after the discount.' },
  finalPrice: { ko: '할인·세금을 모두 반영한 뒤 낼 돈.', en: 'What you pay once discounts and tax are applied.' },
  amount: { ko: '계산의 출발점이 되는 금액. 세금 포함 여부를 먼저 정하세요.', en: 'The amount the calculation starts from — settle whether tax is inside it.' },
  discountAmt: { ko: '정가에서 깎인 돈. 아낀 금액입니다.', en: 'How much came off the list price — what you saved.' },
  profit: { ko: '판매가에서 원가를 뺀 값.', en: 'Sale price minus cost.' },
  marginRate: { ko: '이익을 판매가로 나눈 비율. 100%를 넘지 않습니다.', en: 'Profit divided by the sale price. It can never exceed 100%.' },
  markup: { ko: '이익을 원가로 나눈 비율. 100%를 넘을 수 있습니다.', en: 'Profit divided by cost. This one can exceed 100%.' },
  vat: { ko: '판매가에 얹히는 소비세. 나라마다 세율이 다릅니다.', en: 'Consumption tax added on top. The rate differs by country.' },
  supply: { ko: '세금을 빼고 남는 물건 값 자체.', en: 'The goods value itself, with tax stripped out.' },
  total: { ko: '항목을 모두 더한 값. 세금이나 팁이 포함됐는지 확인하세요.', en: 'Every item added together — check whether tax or tip is inside it.' },
  tip: { ko: '봉사료로 더 얹는 돈.', en: 'The gratuity added for service.' },
  perPerson: { ko: '인원수로 나눈 1명분.', en: 'The total split by head count.' },
  taxAmt: { ko: '떼이는 세금의 금액.', en: 'The tax withheld or charged, as money.' },
  netPay: { ko: '세금을 떼고 실제로 손에 들어오는 돈.', en: 'What lands in your account after tax.' },
  grossPay: { ko: '세금을 떼기 전 계약상 금액.', en: 'The contracted amount before any deduction.' },
  feeAmt: { ko: '수수료로 나가는 금액.', en: 'The fee charged, as money.' },

  /* ───────── 비율 ───────── */
  percent: { ko: '전체를 100으로 봤을 때의 몫.', en: 'A share expressed out of 100.' },
  rate: { ko: '적용되는 비율. 보통 연 단위입니다.', en: 'The rate applied — usually per year.' },
  before: { ko: '비교의 출발점이 되는 값. 분모로 들어갑니다.', en: 'The starting value — it goes in the denominator.' },
  after: { ko: '비교의 도착점이 되는 값.', en: 'The value you ended up with.' },
  change: { ko: '이전 값을 기준으로 얼마나 움직였는지.', en: 'How far it moved, measured against the before value.' },
  diff: { ko: '두 값을 뺀 차이. 비율이 아니라 양입니다.', en: 'The gap between two values — a quantity, not a rate.' },
  part: { ko: '전체 중에서 떼어 낸 조각.', en: 'The slice taken out of the whole.' },
  whole: { ko: '기준이 되는 전체. 이걸로 나눕니다.', en: 'The reference total — you divide by this.' },
  target: { ko: '도달하려는 목표 값.', en: 'The value you are aiming for.' },
  achieved: { ko: '지금까지 실제로 채운 값.', en: 'What you have actually reached so far.' },
  remaining: { ko: '목표까지 아직 남은 양. 0이 되면 목표를 채운 것입니다.', en: 'How much is still left to go; zero means the goal is met.' },

  /* ───────── 금융 ───────── */
  principal: { ko: '처음 넣은 돈. 이자가 붙는 밑돈입니다.', en: 'The money you put in — the base that earns interest.' },
  annualRate: { ko: '1년치로 표시한 이자율. 월 이자는 이걸 12로 나눕니다.', en: 'Interest quoted per year; the monthly rate is this over 12.' },
  years: { ko: '돈을 그대로 두는 햇수. 복리는 이 값이 길어질수록 세집니다.', en: 'How many years the money stays put; compounding bites harder as this grows.' },
  months: { ko: '개월로 센 기간. 연 단위 이율은 12로 나눠 씁니다.', en: 'The period counted in months; a yearly rate gets divided by twelve.' },
  interest: { ko: '기간 동안 붙은 이자.', en: 'The interest earned or owed over the period.' },
  maturity: { ko: '원금과 이자를 합쳐 마지막에 받는 돈.', en: 'Principal plus interest — what you get at the end.' },
  monthlyPay: { ko: '매달 갚아야 하는 금액.', en: 'What you owe every month.' },
  invested: { ko: '넣은 돈을 모두 더한 값. 수수료도 넣어야 실제 수익률이 나옵니다.', en: 'Everything you put in; include fees or the return comes out flattering.' },
  returned: { ko: '돌려받은 돈의 합계.', en: 'The total you got back.' },
  roi: { ko: '넣은 돈에 비해 얼마를 벌었는지.', en: 'How much you made relative to what you put in.' },
  doubleYears: { ko: '지금 이율이 유지되면 원금이 2배가 되는 데 걸리는 해.', en: 'Years for the principal to double if the rate holds.' },
  nominalRate: { ko: '표시 이율. 복리 횟수를 반영하지 않은 숫자입니다.', en: 'The quoted rate, before compounding is taken into account.' },
  effRate: { ko: '복리를 반영해 실제로 붙는 이율.', en: 'The rate you actually earn once compounding is counted.' },
  realRate: { ko: '물가 상승을 뺀 이율. 구매력 기준입니다.', en: 'The rate after inflation is removed — purchasing power.' },
  inflation: { ko: '물가가 1년에 오르는 비율.', en: 'How fast prices rise each year.' },
  cagr: { ko: '여러 해의 성장을 1년 평균으로 편 값.', en: 'Multi-year growth flattened into one yearly average.' },

  /* ───────── 농도·배합 ───────── */
  solute: { ko: '녹아 들어가는 쪽. 설탕·소금 같은 것입니다.', en: 'The stuff being dissolved — sugar, salt and the like.' },
  solvent: { ko: '녹이는 쪽. 보통 물입니다.', en: 'What does the dissolving — usually water.' },
  solution: { ko: '용질과 용매를 합친 전체.', en: 'Solute and solvent together.' },
  concentration: { ko: '전체에서 용질이 차지하는 비율.', en: 'How much of the whole is solute.' },
  targetConc: { ko: '맞추려는 농도. 지금 농도보다 낮으면 물을, 높으면 용질을 더합니다.', en: 'The concentration you want; lower means add water, higher means add solute.' },
  addWater: { ko: '목표 농도까지 더 넣어야 하는 물.', en: 'Extra water needed to reach the target.' },
  addSolute: { ko: '목표 농도까지 더 넣어야 하는 용질.', en: 'Extra solute needed to reach the target.' },

  /* ───────── 수량·기타 ───────── */
  count: { ko: '몇 개인지 센 값. 나누기의 분모로 자주 들어갑니다.', en: 'A plain count of items; it often ends up as the denominator.' },
  people: { ko: '나눠 낼 사람 수. 1로 두면 나누지 않은 값이 나옵니다.', en: 'How many people share it; leave it at one to see the undivided figure.' },
  score: { ko: '실제로 받은 점수. 만점과 함께 봐야 뜻이 생깁니다.', en: 'The points actually scored — only meaningful next to the maximum.' },
  maxScore: { ko: '받을 수 있는 최대 점수.', en: 'The most points available.' },
  scaleReal: { ko: '땅에서 실제로 재는 거리.', en: 'The distance measured on the ground.' },
  scaleMap: { ko: '도면·지도 위에서 재는 거리.', en: 'The distance measured on the drawing.' },
  scaleDenom: { ko: '축척 1:n의 n. 클수록 넓게 줄인 지도입니다.', en: 'The n in a 1:n scale — bigger means more shrunk down.' },
  weightKg: { ko: '킬로그램으로 잰 무게.', en: 'Mass in kilograms.' },
  volumeMl: { ko: '밀리리터로 잰 용량.', en: 'Volume in millilitres.' },

  /* ───────── 몸 수치 ───────── */
  heightCm: { ko: '센티미터로 잰 키. 미터로 바꿔 계산에 씁니다.', en: 'Height in centimetres; converted to metres inside the formula.' },
  ageYears: { ko: '만 나이. 생일이 지났는지에 따라 한 살 달라집니다.', en: 'Age in completed years — it shifts by one depending on the birthday.' },
  waistCm: { ko: '배꼽 높이에서 숨을 내쉰 채 잰 허리둘레.', en: 'Waist at navel height, measured after breathing out.' },
  hipCm: { ko: '엉덩이의 가장 굵은 곳 둘레.', en: 'Hip circumference at its widest point.' },
  neckCm: { ko: '목의 가장 얇은 곳 둘레.', en: 'Neck circumference at its narrowest point.' },
  bmi: { ko: '키와 몸무게만으로 낸 체격 지수. 근육과 지방을 구분하지 못합니다.', en: 'A build index from height and weight alone; it cannot tell muscle from fat.' },
  bmr: { ko: '가만히 있어도 하루에 쓰는 최소 열량.', en: 'The calories you burn in a day doing nothing at all.' },
  tdee: { ko: '활동까지 더한 하루 총 소비 열량.', en: 'Daily calories burned once activity is included.' },
  bodyFat: { ko: '몸무게에서 지방이 차지하는 비율.', en: 'The share of body weight that is fat.' },
  leanMass: { ko: '지방을 뺀 나머지 — 근육·뼈·물입니다.', en: 'Everything that is not fat — muscle, bone, water.' },
  maxHr: { ko: '나이로 추정한 최대 심박수. 개인차가 큽니다.', en: 'Maximum heart rate estimated from age; individual variation is large.' },
  restHr: { ko: '아침에 일어나 바로 잰 안정 시 심박수.', en: 'Resting heart rate, taken right after waking.' },
  calories: { ko: '열량. 킬로칼로리 단위입니다.', en: 'Energy, in kilocalories.' },
  systolic: { ko: '심장이 짤 때의 높은 쪽 혈압.', en: 'The higher reading, when the heart squeezes.' },
  diastolic: { ko: '심장이 쉴 때의 낮은 쪽 혈압.', en: 'The lower reading, when the heart relaxes.' },

  /* ───────── 도형 ───────── */
  radius: { ko: '중심에서 테두리까지의 거리. 지름의 절반입니다.', en: 'Centre to edge — half the diameter.' },
  diameter: { ko: '원을 가로지르는 가장 긴 선. 반지름의 2배입니다.', en: 'The longest line across a circle — twice the radius.' },
  circumference: { ko: '원 테두리를 한 바퀴 잰 길이.', en: 'The distance once around a circle.' },
  perimeter: { ko: '도형의 테두리를 모두 더한 길이.', en: 'The total length around the outside of a shape.' },
  area: { ko: '도형이 덮는 넓이. 길이의 제곱 단위입니다.', en: 'The space a shape covers — length squared.' },
  volume: { ko: '입체가 담는 부피. 길이의 세제곱 단위입니다.', en: 'The space a solid holds — length cubed.' },
  surface: { ko: '입체의 껍데기 넓이를 모두 더한 값.', en: 'The total area of a solid’s outer skin.' },
  hypotenuse: { ko: '직각삼각형에서 직각을 마주 보는 가장 긴 변.', en: 'The longest side of a right triangle, facing the right angle.' },
  angleDeg: { ko: '도(°)로 잰 각. 한 바퀴가 360°입니다.', en: 'An angle in degrees; a full turn is 360°.' },
  angleRad: { ko: '라디안으로 잰 각. 한 바퀴가 2π입니다.', en: 'An angle in radians; a full turn is 2π.' },
  slopePct: { ko: '수평으로 100 갔을 때 올라간 높이.', en: 'How far you rise over 100 of horizontal run.' },
  thickness: { ko: '한 겹의 두께. 겹 수를 곱하면 전체 두께가 됩니다.', en: 'How thick one layer is; times the number of layers gives the whole.' },
  pyeong: { ko: '한국에서 쓰는 면적 단위. 1평은 약 3.3058㎡입니다.', en: 'A Korean area unit; 1 pyeong is about 3.3058 m².' },

  /* ───────── 비율 계산에서 더 쓰는 것들 ───────── */
  result: { ko: '공식이 내놓는 값. 이 페이지에서 구하려던 답입니다.', en: 'What the formula gives back — the answer this page is for.' },
  settle: { ko: '주고받을 것을 상계한 뒤 남는 정산 금액.', en: 'What is left to settle once both sides are offset.' },
  base: { ko: '비교의 기준이 되는 값. 분모 자리에 들어갑니다.', en: 'The value everything is measured against — the denominator.' },
  ratioA: { ko: '비의 앞쪽 숫자. 2:3에서 2에 해당합니다.', en: 'The first number of the ratio — the 2 in 2:3.' },
  ratioB: { ko: '비의 뒤쪽 숫자. 2:3에서 3에 해당합니다.', en: 'The second number of the ratio — the 3 in 2:3.' },
  pointDiff: { ko: '두 비율을 뺀 차이. 퍼센트가 아니라 퍼센트포인트로 읽습니다.', en: 'The gap between two percentages, read in points rather than percent.' },
  original: { ko: '변하기 전의 처음 값.', en: 'The value it had before anything changed.' },
  shareA: { ko: '비율대로 나눴을 때 A가 받는 몫.', en: 'The slice A gets once the ratio is applied.' },
  shareB: { ko: '비율대로 나눴을 때 B가 받는 몫.', en: 'The slice B gets once the ratio is applied.' },
  percentA: { ko: '첫 번째 대상의 비율.', en: 'The percentage that applies to the first item.' },
  percentB: { ko: '두 번째 대상의 비율.', en: 'The percentage that applies to the second item.' },
  unknown: { ko: '비례식에서 비워 둔 자리. 이 값을 찾습니다.', en: 'The blank slot in the proportion — the value being solved for.' },
  totalGrowth: { ko: '기간을 통틀어 몇 배가 됐는지 비율로 본 값.', en: 'How much it grew across the whole period, as a percentage.' },
  monthlyDeposit: { ko: '매달 꼬박꼬박 넣는 금액.', en: 'The amount you pay in every month.' },
  totalDeposit: { ko: '기간 동안 넣은 돈을 모두 더한 값. 이자는 빠집니다.', en: 'Everything you paid in over the period, interest not included.' },
  totalPaid: { ko: '다 갚을 때까지 낸 돈의 합계. 원금과 이자를 합친 값입니다.', en: 'Everything handed over by the last payment — principal plus interest.' },
  holdDays: { ko: '사서 팔기까지 들고 있던 날 수.', en: 'How many days you held it before selling.' },
  annualized: { ko: '짧은 기간의 수익을 1년치로 늘려 본 값. 실제로 그만큼 번 건 아닙니다.', en: 'A short-period return stretched to a year — not money actually earned.' },
  lossRate: { ko: '고점에서 떨어진 비율.', en: 'How far it dropped from the high point, as a percentage.' },
  neededRise: { ko: '원래 값으로 돌아가려면 올라야 하는 비율. 떨어진 비율보다 큽니다.', en: 'The rise needed to get back to where you started — always larger than the fall.' },
  netInterest: { ko: '이자소득세를 떼고 손에 남는 이자.', en: 'The interest left once tax on it is taken off.' },
  foldRate: { ko: '원액 1에 대해 전체를 몇 배로 불렸는지.', en: 'How many times the concentrate was expanded — 1 part to how many.' },
  volumeL: { ko: '만들려는 전체 양. 리터로 셉니다.', en: 'How much finished liquid you want, in litres.' },
  stockMl: { ko: '희석하기 전 진한 원액의 양.', en: 'How much undiluted concentrate you start with.' },
  perLiterMl: { ko: '물 1리터마다 넣을 원액의 양.', en: 'Concentrate to add for every litre of water.' },
  ppmValue: { ko: '100만분의 몇인지 나타낸 농도. 1ppm은 0.0001%입니다.', en: 'Parts per million; 1 ppm is 0.0001%.' },
  mgPerL: { ko: '물 1리터에 몇 밀리그램 들었는지. 물에서는 ppm과 거의 같습니다.', en: 'Milligrams in one litre; in water this is nearly the same as ppm.' },
  sessions: { ko: '전체 횟수. 수업이면 총 강의 수입니다.', en: 'The total number of sessions — all the classes, say.' },
  attended: { ko: '실제로 나간 횟수. 지각을 어떻게 셀지는 규정을 보세요.', en: 'How many you actually turned up to; check the rules on late arrivals.' },
  attendRate: { ko: '나간 횟수를 전체로 나눈 비율.', en: 'Sessions attended divided by sessions held.' },
  canMiss: { ko: '기준을 지키면서 더 빠질 수 있는 횟수.', en: 'How many more you can skip and still clear the bar.' },
  actual: { ko: '계획이 아니라 실제로 나온 값.', en: 'What actually happened, as opposed to the plan.' },
  wins: { ko: '이긴 경기 수. 무승부는 따로 셉니다.', en: 'How many games were won; draws are counted separately.' },
  losses: { ko: '진 경기 수. 무승부는 따로 셉니다.', en: 'How many games were lost; draws are counted separately.' },
  winRate: { ko: '이긴 비율. 무승부를 셈에 넣는지 먼저 정하세요.', en: 'The share of games won — decide first whether draws count.' },
  games: { ko: '치른 경기 수의 합계.', en: 'The total number of games played.' },

  /* ───────── 몸 수치 ───────── */
  weightKgB: { ko: '비교하려는 두 번째 체중.', en: 'The second weight you are comparing against.' },
  idealWeight: { ko: '키로 계산한 표준 체중. 목표가 아니라 기준점입니다.', en: 'A reference weight from height alone — a benchmark, not a goal.' },
  sexFactor: { ko: '공식에서 남녀가 갈리는 자리. 남자 1, 여자 0으로 넣습니다.', en: 'Where the formula splits by sex — enter 1 for male, 0 for female.' },
  bmiTarget: { ko: '맞추려는 BMI 값.', en: 'The BMI figure you are aiming at.' },
  targetWeight: { ko: '목표 BMI를 만족하는 체중.', en: 'The weight that lands you on the target BMI.' },
  fatMass: { ko: '몸무게 가운데 지방이 차지하는 무게.', en: 'How much of your weight is fat, in kilograms.' },
  whr: { ko: '허리를 엉덩이로 나눈 값. 지방이 어디 붙었는지를 봅니다.', en: 'Waist over hip — it shows where the fat sits, not how much.' },
  whtr: { ko: '허리를 키로 나눈 값. 0.5를 넘는지가 기준선입니다.', en: 'Waist over height; the line people watch is 0.5.' },
  bsa: { ko: '몸 표면의 넓이. 약 용량과 수액 계산에 씁니다.', en: 'Body surface area — used for drug and fluid dosing.' },
  ponderal: { ko: '키의 세제곱으로 나눈 지수. 아기와 아주 큰 키에서 BMI보다 잘 맞습니다.', en: 'An index divided by height cubed; it fits infants and very tall people better than BMI.' },
  activity: { ko: '하루가 얼마나 활동적인지 곱해 주는 계수. 앉아 지내면 1.2 근처입니다.', en: 'A multiplier for how active your day is; desk-bound sits near 1.2.' },
  deficit: { ko: '먹는 것보다 더 쓰는 하루치 열량 차이.', en: 'How many more calories you burn than you eat each day.' },
  weeksNeeded: { ko: '지금 속도를 유지하면 목표까지 걸리는 주 수.', en: 'Weeks to the goal if you keep this pace.' },
  dosePerKg: { ko: '체중 1kg마다 쓰는 약 용량.', en: 'How much drug is given per kilogram of body weight.' },
  proteinG: { ko: '하루에 먹을 단백질의 양. 1g은 4kcal입니다.', en: 'Grams of protein for the day; each gram is 4 kcal.' },
  perFeed: { ko: '한 번 먹일 때의 양.', en: 'How much goes in at a single feed.' },
  minutes: { ko: '분으로 센 시간. 시간 단위와 섞지 않도록 주의하세요.', en: 'A duration in minutes — take care not to mix it with hours.' },
  waterMl: { ko: '하루에 마실 물의 양. 음식에 든 물은 빠져 있습니다.', en: 'Water to drink in a day; water inside food is not counted.' },
  carbG: { ko: '하루에 먹을 탄수화물의 양. 1g은 4kcal입니다.', en: 'Grams of carbohydrate for the day; each gram is 4 kcal.' },
  fatG: { ko: '하루에 먹을 지방의 양. 1g은 9kcal로 가장 셉니다.', en: 'Grams of fat for the day; at 9 kcal a gram it is the densest.' },
  metValue: { ko: '가만히 있을 때의 몇 배로 힘든 운동인지. 걷기가 3 정도입니다.', en: 'How many times harder than sitting still; walking is about 3.' },
  steps: { ko: '걸은 걸음의 수. 보폭을 곱하면 거리가 됩니다.', en: 'The number of steps taken; times your stride it becomes distance.' },
  strideCm: { ko: '한 걸음의 길이. 키의 0.4배쯤입니다.', en: 'How long one step is — roughly 0.4 times your height.' },
  distanceKm: { ko: '킬로미터로 잰 거리.', en: 'Distance measured in kilometres.' },
  intensity: { ko: '최대 심박수의 몇 %로 뛰는지.', en: 'What share of your maximum heart rate you are working at.' },
  hrLow: { ko: '그 구간의 아래쪽 심박수.', en: 'The bottom of the heart-rate band.' },
  hrHigh: { ko: '그 구간의 위쪽 심박수.', en: 'The top of the heart-rate band.' },
  cooperDist: { ko: '12분 동안 쉬지 않고 달린 거리.', en: 'How far you ran in twelve minutes without stopping.' },
  vo2max: { ko: '1분에 쓸 수 있는 산소의 최대량. 심폐 능력의 지표입니다.', en: 'The most oxygen you can use per minute — the cardio yardstick.' },
  speedKmh: { ko: '시간당 몇 킬로미터로 움직이는지.', en: 'How many kilometres you cover in an hour.' },
  liftWeight: { ko: '실제로 들어 올린 무게.', en: 'The weight you actually lifted.' },
  reps: { ko: '그 무게로 반복한 횟수.', en: 'How many times you lifted it.' },
  oneRm: { ko: '딱 한 번 들 수 있는 최대 무게. 추정값입니다.', en: 'The most you could lift exactly once — an estimate.' },
  timeMin: { ko: '분으로 센 걸린 시간.', en: 'The time it took, in minutes.' },
  paceMin: { ko: '1km를 뛰는 데 걸리는 시간의 분 부분.', en: 'The minutes part of the time per kilometre.' },
  paceSec: { ko: '페이스의 초 부분. 0~59 사이입니다.', en: 'The seconds part of the pace, from 0 to 59.' },
  finishTime: { ko: '그 페이스를 끝까지 지켰을 때의 완주 시간.', en: 'Your finish time if the pace holds all the way.' },
  hours: { ko: '시간 단위로 센 기간.', en: 'A duration counted in hours.' },
  per100m: { ko: '100m를 가는 데 걸리는 시간. 수영에서 씁니다.', en: 'Time to cover 100 m — the swimmer’s pace unit.' },
  fatherCm: { ko: '아버지의 키. 센티미터로 넣습니다.', en: 'The father’s height, entered in centimetres.' },
  motherCm: { ko: '어머니의 키. 센티미터로 넣습니다.', en: 'The mother’s height, entered in centimetres.' },
  childHeight: { ko: '부모 키로 추정한 다 자란 키. 오차가 ±5cm쯤 됩니다.', en: 'Adult height estimated from the parents, give or take about 5 cm.' },
  feeds: { ko: '하루에 먹이는 횟수.', en: 'How many feeds there are in a day.' },
  milkMl: { ko: '하루에 먹이는 전체 양.', en: 'The total amount fed across the day.' },
  birthWeight: { ko: '태어났을 때의 몸무게. 그램으로 넣습니다.', en: 'Weight at birth, entered in grams.' },
  nowWeight: { ko: '지금 재 본 몸무게.', en: 'The weight measured right now.' },
  gainPercent: { ko: '출생 때보다 늘어난 비율.', en: 'How much it has grown since birth, as a percentage.' },
  doseMg: { ko: '한 번에 먹이거나 쓰는 약의 양.', en: 'How much drug goes in at one time.' },
  bloodMl: { ko: '몸속 전체 피의 양. 체중으로 추정합니다.', en: 'Total blood in the body, estimated from weight.' },
  map: { ko: '한 심장 주기 동안의 평균 혈압. 장기로 가는 압력을 봅니다.', en: 'Average pressure over one heartbeat — what the organs actually feel.' },
  pulsePress: { ko: '높은 쪽에서 낮은 쪽을 뺀 값. 혈관이 얼마나 굳었는지 힌트가 됩니다.', en: 'Systolic minus diastolic — a hint at how stiff the arteries are.' },
  totalChol: { ko: '피 속 콜레스테롤을 모두 더한 값.', en: 'All the cholesterol in the blood, added up.' },
  hdl: { ko: '남는 콜레스테롤을 간으로 되돌리는 쪽. 높은 게 좋습니다.', en: 'The kind that carries cholesterol back to the liver — higher is better.' },
  cholRatio: { ko: '총콜레스테롤을 HDL로 나눈 값. 낮을수록 좋습니다.', en: 'Total cholesterol over HDL — lower is better.' },
  nonHdl: { ko: '총콜레스테롤에서 HDL을 뺀 나머지.', en: 'Everything except HDL.' },
  triglyceride: { ko: '피 속 중성지방. 공복에 재야 맞습니다.', en: 'Blood triglycerides — measure after fasting or the number lies.' },
  ldl: { ko: '혈관 벽에 쌓이는 쪽 콜레스테롤. 낮은 게 좋습니다.', en: 'The kind that builds up in artery walls — lower is better.' },
  glucose: { ko: '피 속 포도당 농도. 공복인지 식후인지 함께 봐야 합니다.', en: 'Blood sugar; whether it is fasting or after a meal changes everything.' },
  insulin: { ko: '공복에 잰 인슐린 농도.', en: 'Fasting insulin concentration.' },
  homaIr: { ko: '인슐린이 잘 듣는지 보는 지수. 높으면 저항성이 있다는 뜻입니다.', en: 'An index of how well insulin works; higher means more resistance.' },
  a1c: { ko: '지난 두세 달의 혈당을 평균한 값.', en: 'Blood sugar averaged over the past two to three months.' },
  avgGlucose: { ko: '당화혈색소를 평균 혈당으로 되돌린 값.', en: 'The A1c figure translated back into an average blood sugar.' },
  mmolL: { ko: '유럽에서 쓰는 혈당 단위. mg/dL을 18로 나눈 값입니다.', en: 'The European blood-sugar unit — mg/dL divided by 18.' },
  cycles: { ko: '자는 동안 도는 수면 주기 횟수. 한 주기가 90분쯤입니다.', en: 'How many sleep cycles you go through; one runs about 90 minutes.' },
  sleepHours: { ko: '실제로 자는 시간. 눕는 시간과 다릅니다.', en: 'Time actually asleep — not the same as time in bed.' },
  drinkMl: { ko: '마신 술의 양. 도수와 함께 봐야 순알코올이 나옵니다.', en: 'How much drink went down; with the strength it gives pure alcohol.' },
  abv: { ko: '술에 든 알코올의 부피 비율.', en: 'The share of the drink that is alcohol, by volume.' },
  bac: { ko: '피 100ml에 든 알코올의 무게 비율.', en: 'Alcohol by weight in 100 mL of blood.' },
  clearHours: { ko: '알코올이 다 분해되기까지 걸리는 시간. 사람마다 다릅니다.', en: 'Hours until the alcohol clears; it varies a lot by person.' },
  caffeineMg: { ko: '마신 카페인의 양. 아메리카노 한 잔이 약 120mg입니다.', en: 'Caffeine taken in; a single Americano runs about 120 mg.' },
  hoursLater: { ko: '마시고 나서 지난 시간.', en: 'How long it has been since you drank it.' },
  remainMg: { ko: '지금 몸에 남아 있는 양. 5시간마다 절반으로 줄어듭니다.', en: 'How much is still in you; it halves about every five hours.' },

  /* ───────── 도형·측량 ───────── */
  baseLen: { ko: '넓이를 잴 때 바닥으로 삼는 변.', en: 'The side you treat as the bottom when finding area.' },
  heightGeo: { ko: '밑변에서 수직으로 잰 높이. 비스듬한 변이 아닙니다.', en: 'The perpendicular height from the base — not the slanted side.' },
  sideA: { ko: '첫 번째 변의 길이.', en: 'The length of the first side.' },
  sideB: { ko: '두 번째 변의 길이.', en: 'The length of the second side.' },
  sideC: { ko: '세 번째 변의 길이. 두 변의 합보다 짧아야 삼각형이 됩니다.', en: 'The third side; it must be shorter than the other two combined.' },
  baseTop: { ko: '사다리꼴에서 위쪽의 짧은 변.', en: 'The shorter parallel side of a trapezium.' },
  diagonal1: { ko: '첫 번째 대각선의 길이.', en: 'The length of the first diagonal.' },
  diagonal2: { ko: '두 번째 대각선의 길이.', en: 'The length of the second diagonal.' },
  sideLen: { ko: '정다각형에서 한 변의 길이. 모든 변이 같습니다.', en: 'One side of a regular polygon — they are all the same.' },
  sideCount: { ko: '다각형의 변 수. 3부터 셉니다.', en: 'How many sides the polygon has, counting from three.' },
  innerAngle: { ko: '정다각형 한 모서리의 안쪽 각.', en: 'The interior angle at one corner of a regular polygon.' },
  outerAngle: { ko: '한 모서리에서 방향이 꺾이는 각. 모두 더하면 360°입니다.', en: 'How far you turn at a corner; they always add to 360°.' },
  angleSum: { ko: '다각형 내각을 모두 더한 값. (변수−2)×180°입니다.', en: 'All interior angles added up — (sides − 2) × 180°.' },
  axisA: { ko: '타원의 긴 쪽 반지름.', en: 'The longer radius of an ellipse.' },
  axisB: { ko: '타원의 짧은 쪽 반지름.', en: 'The shorter radius of an ellipse.' },
  arcLen: { ko: '원 테두리 가운데 잘라 낸 곡선의 길이.', en: 'The length of the curved piece cut from a circle’s edge.' },
  chordLen: { ko: '원 위의 두 점을 직선으로 이은 길이.', en: 'The straight line between two points on a circle.' },
  liters: { ko: '리터로 나타낸 담을 수 있는 양. 1L는 1,000㎤입니다.', en: 'Capacity in litres; one litre is 1,000 cm³.' },
  lengthCm: { ko: '가로 방향으로 잰 길이.', en: 'The measurement across, side to side.' },
  widthCm: { ko: '세로 방향으로 잰 길이.', en: 'The measurement front to back.' },
  depthCm: { ko: '깊이 방향으로 잰 길이.', en: 'How deep it goes.' },
  diagonal: { ko: '마주 보는 두 모서리를 잇는 길이.', en: 'Corner to opposite corner.' },
  slant: { ko: '꼭대기에서 바닥 테두리까지 비스듬히 잰 길이. 높이보다 깁니다.', en: 'The sloped length from apex to base edge — longer than the height.' },
  radius2: { ko: '위아래 반지름이 다를 때 작은 쪽.', en: 'The smaller of two radii when the ends differ.' },
  riseLen: { ko: '수직으로 올라간 높이.', en: 'How far it climbs, straight up.' },
  runLen: { ko: '수평으로 나아간 거리.', en: 'How far it travels horizontally.' },
  sinVal: { ko: '각의 사인 값. 마주 보는 변을 빗변으로 나눈 값입니다.', en: 'The sine of the angle — opposite over hypotenuse.' },
  cosVal: { ko: '각의 코사인 값. 붙어 있는 변을 빗변으로 나눈 값입니다.', en: 'The cosine of the angle — adjacent over hypotenuse.' },
  tanVal: { ko: '각의 탄젠트 값. 90°에서는 정의되지 않습니다.', en: 'The tangent of the angle; it is undefined at 90°.' },
  distance: { ko: '두 점 사이를 직선으로 잰 거리.', en: 'The straight-line distance between two points.' },
  x1: { ko: '첫 번째 점의 가로 좌표.', en: 'The horizontal coordinate of the first point.' },
  y1: { ko: '첫 번째 점의 세로 좌표.', en: 'The vertical coordinate of the first point.' },
  x2: { ko: '두 번째 점의 가로 좌표.', en: 'The horizontal coordinate of the second point.' },
  y2: { ko: '두 번째 점의 세로 좌표.', en: 'The vertical coordinate of the second point.' },
  midX: { ko: '두 점 가운데의 가로 좌표.', en: 'The horizontal coordinate halfway between.' },
  midY: { ko: '두 점 가운데의 세로 좌표.', en: 'The vertical coordinate halfway between.' },
  turns: { ko: '몇 바퀴 감거나 돌았는지.', en: 'How many full turns it makes.' },
  coats: { ko: '겹쳐 칠하는 횟수. 두 번 칠하면 페인트가 두 배 듭니다.', en: 'How many coats you paint; two coats means twice the paint.' },
  paintL: { ko: '필요한 페인트의 양. 통 단위로 올려 사야 합니다.', en: 'How much paint you need — buy up to whole tins.' },
  tileSize: { ko: '타일 한 변의 길이.', en: 'One edge of a single tile.' },
  tileCount: { ko: '필요한 타일 개수. 자를 때 나오는 손실이 더 붙습니다.', en: 'Tiles needed; cutting waste comes on top of this.' },
  extraPct: { ko: '깨짐과 재단 손실에 대비해 더 사는 비율. 보통 10%입니다.', en: 'Extra bought for breakage and offcuts — usually 10%.' },
  rollWidth: { ko: '벽지 한 롤의 폭. 보통 53cm나 106cm입니다.', en: 'How wide one roll is — commonly 53 cm or 106 cm.' },
  rollLength: { ko: '벽지 한 롤에 감긴 길이.', en: 'How long one roll of wallpaper runs.' },
  rolls: { ko: '필요한 롤 수. 무늬를 맞추면 더 듭니다.', en: 'Rolls needed; matching a pattern eats more.' },
  cementBags: { ko: '필요한 시멘트 포대 수. 40kg 한 포 기준입니다.', en: 'Bags of cement needed, based on 40 kg a bag.' },
  weightT: { ko: '톤으로 나타낸 무게. 1톤은 1,000kg입니다.', en: 'Weight in tonnes; one tonne is 1,000 kg.' },
  waterKg: { ko: '담긴 물의 무게. 물 1리터가 1kg입니다.', en: 'The weight of the water inside; a litre weighs a kilogram.' },
  pizzaA: { ko: '비교하는 첫 번째 피자의 지름.', en: 'The diameter of the first pizza.' },
  pizzaB: { ko: '비교하는 두 번째 피자의 지름.', en: 'The diameter of the second pizza.' },
  countB: { ko: '작은 쪽을 몇 판 시키는지.', en: 'How many of the smaller ones you order.' },
  inches: { ko: '인치로 잰 대각선 길이. 화면 크기는 대각선으로 부릅니다.', en: 'The diagonal in inches — screens are always named by the diagonal.' },
  aspectW: { ko: '화면 비의 가로 쪽 숫자. 16:9에서 16입니다.', en: 'The width part of the aspect ratio — the 16 in 16:9.' },
  aspectH: { ko: '화면 비의 세로 쪽 숫자. 16:9에서 9입니다.', en: 'The height part of the aspect ratio — the 9 in 16:9.' },
  paperN: { ko: 'A 규격의 번호. A4의 4처럼 커질수록 절반씩 작아집니다.', en: 'The number in an A size; each step up halves the sheet.' },
  stepHeight: { ko: '계단 한 단의 높이.', en: 'The rise of a single stair.' },
  stepCount: { ko: '계단의 단 수. 한 단 높이를 곱하면 전체 높이가 됩니다.', en: 'How many stairs there are; times the rise gives the total climb.' },
  roofArea: { ko: '경사를 반영한 지붕의 실제 넓이. 바닥 넓이보다 큽니다.', en: 'The real roof area once the pitch is counted — bigger than the footprint.' },
};

/* 섹션별 뜻풀이는 파일을 나눠 둔다 — 한 파일에 삼백 줄이면 무엇이 빠졌는지 안 보인다 */
export const TERM_DESC: Record<string, Term> = { ...CORE_DESC, ...RATE_DESC, ...BODY2_DESC, ...GEO2_DESC, ...GEO3_DESC };

/**
 * 라벨 옆에 붙는 한 줄 뜻풀이.
 *
 * 번역이 없으면 null을 돌려준다 — 영어를 끼우면 그 페이지에서 그 줄만 영어가
 * 되므로, 차라리 설명을 안 붙이는 편이 읽기에 낫다.
 */
export const termDesc = (key: string, lang: FormulaLang): string | null => {
  if (lang === 'ko' || lang === 'en') return TERM_DESC[key]?.[lang] ?? null;
  return FORMULA_L10N[lang]?.DESC[key] ?? null;
};
