/**
 * 비율 섹션 용어의 뜻풀이(3언어).
 *
 * glossary.ts가 세 섹션 공통이라면 여기는 비율 100종을 만들며 생긴 용어들이다.
 * 입력 표와 결과 표에서 라벨 아래 한 줄로 붙는다.
 */
import type { Lang, Term } from './terms.ts';

export const RATE_DESC: Record<string, Term> = {
  /* ───────── 할인·가격 ───────── */
  effDiscount: { ko: '겹친 할인을 하나로 합친 실제 할인율. 각 할인율을 더한 값보다 작습니다.', en: 'Stacked discounts boiled down to one number — always less than adding them.' },
  payCount: { ko: '돈을 내고 사는 개수. 덤은 여기 넣지 않습니다.', en: 'How many you pay for; the free ones do not go here.' },
  freeCount: { ko: '덤으로 받는 개수. 1+1이면 1입니다.', en: 'How many come free — one, in a buy-one-get-one.' },
  unitPrice: { ko: '한 개에 얼마인지. 덤을 포함한 전체 개수로 나눈 값입니다.', en: 'What one costs, divided across everything you carry home.' },
  saveAmt: { ko: '이 조건으로 아끼는 금액.', en: 'How much this deal keeps in your pocket.' },
  costPerUse: { ko: '한 번 쓸 때 드는 값. 가격을 쓸 횟수로 나눕니다.', en: 'What one use costs — price divided by the number of uses.' },
  costPerMonth: { ko: '한 달로 환산한 비용. 구독료와 견주기 좋습니다.', en: 'The cost spread over a month — handy against a subscription.' },
  costPerDay: { ko: '하루로 환산한 비용. 커피 한 잔과 견주면 감이 옵니다.', en: 'The cost spread over a day; compare it with a coffee.' },
  freeShipMin: { ko: '배송비가 사라지는 주문 금액 기준선.', en: 'The order value at which delivery becomes free.' },
  shipFee: { ko: '기준을 못 넘겼을 때 붙는 배송비.', en: 'What delivery costs if you stay under the threshold.' },
  addBuy: { ko: '무료배송 기준까지 더 담아야 하는 금액.', en: 'How much more the basket needs to clear the threshold.' },
  annualFee: { ko: '1년에 한 번 내는 회비.', en: 'The fee charged once a year.' },
  memberPrice: { ko: '회원에게만 주는 값. 일반가보다 낮아야 회비를 뽑습니다.', en: 'The price members get; it must beat the normal one for the fee to pay off.' },
  breakEvenCount: { ko: '회비를 뽑는 데 필요한 이용 횟수. 올림해서 셉니다.', en: 'Uses needed before the fee is recovered, rounded up.' },
  baseRate: { ko: '수수료가 붙지 않은 시장 중간 환율.', en: 'The mid-market rate, before anyone adds a margin.' },
  appliedRate: { ko: '창구에서 실제로 적용된 환율.', en: 'The rate the counter actually gave you.' },
  spread: { ko: '기준 환율과 적용 환율의 차이. 숨은 수수료입니다.', en: 'The gap between mid-market and what you got — the hidden fee.' },
  buyPrice: { ko: '살 때 실제로 낸 금액. 수수료를 포함해야 손익이 맞습니다.', en: 'What you actually paid, fees included, or the profit maths breaks.' },
  depreciation: { ko: '해마다 값이 떨어지는 비율. 남은 가치에 붙습니다.', en: 'How much value falls each year, applied to what is left.' },
  nowValue: { ko: '감가를 반영한 지금 가치.', en: 'What it is worth today, after depreciation.' },
  minMargin: { ko: '할인해도 지켜야 하는 최소 이익률.', en: 'The margin you refuse to go below, however deep the discount.' },
  maxDiscount: { ko: '그 이익률을 지키면서 줄 수 있는 가장 큰 할인율.', en: 'The deepest discount that still leaves that margin standing.' },
  installMonths: { ko: '몇 달에 걸쳐 나눠 낼지. 길어질수록 수수료 총액이 커집니다.', en: 'How many months to spread it over; longer means more fee in total.' },

  /* ───────── 세금·정산 ───────── */
  taxRate: { ko: '적용되는 세율. 나라와 품목에 따라 다릅니다.', en: 'The tax rate that applies; it varies by country and item.' },
  taxFreeRate: { ko: '세금을 떼지 않는 상품의 표시 수익률.', en: 'The headline rate on a product whose returns are not taxed.' },
  equivYield: { ko: '세금을 떼고도 비과세와 같아지려면 필요한 과세 수익률.', en: 'The taxable rate that, after tax, matches the tax-free one.' },
  serviceRate: { ko: '음식값에 얹히는 봉사료 비율.', en: 'The service charge added on top of the bill.' },
  feeRateA: { ko: '먼저 떼이는 수수료의 비율.', en: 'The first cut taken, as a percentage.' },
  feeRateB: { ko: '남은 금액에서 다시 떼이는 수수료의 비율.', en: 'The second cut, taken from what is left.' },
  totalDays: { ko: '계약이나 이용권의 전체 기간.', en: 'The full length of the contract or pass.' },
  usedDays: { ko: '이미 쓴 기간. 이 부분은 돌려받지 못합니다.', en: 'The part already used — that share does not come back.' },
  refundAmt: { ko: '남은 기간에 비례해 돌려받는 금액.', en: 'What comes back, in proportion to the days left.' },
  goodsPrice: { ko: '배송비를 뺀 물건 값 자체.', en: 'The item price on its own, before shipping.' },
  dutyRate: { ko: '수입할 때 붙는 관세율. 품목마다 다릅니다.', en: 'The customs duty rate on import; it differs by product.' },
  landedCost: { ko: '물건값·배송비·관세·세금을 모두 더한 실제 지불액.', en: 'Item, shipping, duty and tax added up — what you really pay.' },
  dutyFreeLimit: { ko: '이 금액까지는 세금이 붙지 않는 한도.', en: 'The value up to which nothing is charged.' },
  taxableAmt: { ko: '한도를 넘겨 세금이 매겨지는 부분.', en: 'The slice above the allowance that gets taxed.' },
  workHours: { ko: '한 달에 실제로 일하는 시간. 야근을 포함합니다.', en: 'Hours actually worked in a month, overtime included.' },
  hourlyNet: { ko: '세금을 떼고 한 시간 일해 남는 돈.', en: 'What an hour of work leaves you after tax.' },

  /* ───────── 비율·증감 ───────── */
  outerPct: { ko: '전체에서 먼저 떼어 내는 비율.', en: 'The share carved out of the whole first.' },
  innerPct: { ko: '떼어 낸 그 안에서 다시 세는 비율.', en: 'The share counted inside that slice.' },
  netPercent: { ko: '두 비율을 곱해 전체 기준으로 환산한 값.', en: 'The two shares multiplied, back on the scale of the whole.' },
  changeA: { ko: '먼저 일어난 변화의 비율.', en: 'The first change, as a percentage.' },
  changeB: { ko: '그다음에 일어난 변화의 비율. 커진 값에 적용됩니다.', en: 'The second change; it works off the new, larger value.' },
  trueVal: { ko: '기준으로 삼는 정확한 값. 오차율의 분모입니다.', en: 'The correct figure you measure against — the denominator.' },
  measured: { ko: '실제로 재서 얻은 값.', en: 'The figure your measurement produced.' },
  errorPct: { ko: '참값에서 벗어난 정도를 비율로 나타낸 값.', en: 'How far off the measurement was, as a percentage.' },
  startVal: { ko: '성장을 시작하는 시점의 값.', en: 'Where the growth starts from.' },
  endVal: { ko: '기간이 끝날 때 닿으려는 값.', en: 'Where you want to be when the period ends.' },
  neededRate: { ko: '기간 안에 목표에 닿기 위해 매년 필요한 성장률.', en: 'The yearly growth required to arrive on time.' },
  rankNo: { ko: '위에서 몇 번째인지. 1이 가장 좋습니다.', en: 'Your place counting from the top; one is best.' },
  totalPeople: { ko: '순위를 매긴 전체 인원.', en: 'How many people were ranked in total.' },
  topPercent: { ko: '상위 몇 %인지. 작을수록 좋습니다.', en: 'What top percentage you fall in — smaller is better.' },
  grade: { ko: '아래에 몇 %가 있는지. 클수록 좋습니다.', en: 'What share sits below you — bigger is better.' },
  ratioC: { ko: '비의 세 번째 숫자. 3:2:1에서 1입니다.', en: 'The third number of the ratio — the 1 in 3:2:1.' },
  shareC: { ko: '비율대로 나눴을 때 C가 받는 몫.', en: 'The slice C gets once the ratio is applied.' },
  permille: { ko: '1000분의 몇인지. 퍼센트의 10배 숫자로 나옵니다.', en: 'Parts per thousand — ten times the percentage figure.' },
  workers: { ko: '일에 붙는 사람 수.', en: 'How many people are on the job.' },
  daysNeeded: { ko: '그 인원으로 일을 끝내는 데 걸리는 날 수.', en: 'Days to finish with that many people.' },
  usedAmt: { ko: '전체 가운데 이미 써 버린 양.', en: 'How much of the total is already gone.' },
  indexVal: { ko: '기준을 100으로 놓았을 때의 값. 115면 15% 높습니다.', en: 'The value with the base set to 100; 115 means 15% above.' },

  /* ───────── 금융·이자 ───────── */
  goalAmount: { ko: '기간 안에 모으려는 금액.', en: 'The sum you want to have by the end.' },
  neededMonthly: { ko: '목표에 닿기 위해 매달 넣어야 하는 금액.', en: 'What to pay in each month to land on the goal.' },
  monthsNeeded: { ko: '지금 속도로 목표까지 걸리는 개월 수.', en: 'Months to the goal at the current pace.' },
  futureAmt: { ko: '나중에 받게 될 금액.', en: 'The sum arriving at some point in the future.' },
  discountRate: { ko: '미래 금액을 현재로 끌어올 때 쓰는 연 이율.', en: 'The yearly rate used to pull a future sum back to today.' },
  presentAmt: { ko: '미래 금액을 지금 가치로 바꾼 값.', en: 'That future sum expressed in today’s money.' },
  affordPay: { ko: '매달 무리 없이 갚을 수 있는 금액.', en: 'What you can comfortably hand over each month.' },
  maxLoan: { ko: '그 월 상환액으로 감당할 수 있는 원금.', en: 'The principal that monthly payment can support.' },
  prepayAmt: { ko: '정해진 상환 외에 미리 갚는 원금.', en: 'Principal paid off ahead of the schedule.' },
  savedInterest: { ko: '미리 갚아서 내지 않게 된 이자.', en: 'The interest that never accrues because you paid early.' },
  days: { ko: '이자가 붙는 날 수. 하루치 이자에 이 값을 곱합니다.', en: 'How many days interest runs for; multiply the daily figure by this.' },
  dailyInterest: { ko: '하루에 붙는 이자. 연이율을 365로 나눈 값입니다.', en: 'Interest for a single day — the annual rate over 365.' },
  firstInterest: { ko: '첫 달 상환액 가운데 이자로 가는 부분.', en: 'The part of the first payment that goes to interest.' },
  firstPrincipal: { ko: '첫 달에 실제로 줄어드는 원금.', en: 'How much principal the first payment actually retires.' },
  installFee: { ko: '할부에 붙는 표시 수수료율. 처음 금액 전체에 매겨집니다.', en: 'The quoted instalment fee, charged on the full amount.' },
  apr: { ko: '실제로 부담하는 연 이자율. 표시 수수료율의 두 배에 가깝습니다.', en: 'The rate you really bear — close to double the quoted fee.' },
  futurePrice: { ko: '물가가 오른 뒤의 가격.', en: 'What it will cost once prices have risen.' },
  buyPriceA: { ko: '처음 살 때의 단가.', en: 'The unit price on the first purchase.' },
  buyQtyA: { ko: '처음 살 때의 수량. 평균 단가의 가중치가 됩니다.', en: 'How many you bought first; it weights the average price.' },
  buyPriceB: { ko: '두 번째로 살 때의 단가.', en: 'The unit price on the second purchase.' },
  buyQtyB: { ko: '두 번째로 산 수량.', en: 'How many you bought the second time.' },
  avgPrice: { ko: '수량으로 가중한 평균 단가. 손익분기점이 되는 값입니다.', en: 'The quantity-weighted average price — your break-even.' },
  totalQty: { ko: '두 번에 걸쳐 산 전체 수량.', en: 'Everything bought across both purchases.' },
  feeRate: { ko: '사고팔 때 양쪽에서 떼이는 수수료를 합친 비율.', en: 'Buying and selling fees added together.' },
  needReturn: { ko: '수수료를 물고 본전이 되기 위해 올라야 하는 비율.', en: 'The rise needed just to get back to even after fees.' },
  monthlySpend: { ko: '한 달에 쓰는 돈. 고정비와 변동비를 모두 넣습니다.', en: 'What you spend in a month, fixed and variable together.' },
  fundMonths: { ko: '수입이 끊겨도 버티려는 개월 수.', en: 'How many months you want to survive with no income.' },
  savedSoFar: { ko: '지금까지 모아 둔 금액.', en: 'What you have set aside so far.' },
  fundAmount: { ko: '그 개월을 버티기 위해 필요한 총액.', en: 'The total needed to cover those months.' },
  faceValue: { ko: '채권에 적힌 금액. 만기에 돌려받는 원금입니다.', en: 'The amount printed on the bond — repaid at maturity.' },
  couponRate: { ko: '액면에 대해 해마다 주는 이자 비율. 고정입니다.', en: 'Yearly interest as a share of face value; it is fixed.' },
  currentYield: { ko: '실제 매입가에 대한 이자 수익률.', en: 'The coupon measured against what you actually paid.' },

  /* ───────── 농도·배합 ───────── */
  origAbv: { ko: '희석 전 술의 도수.', en: 'The strength of the drink before you dilute it.' },
  targetAbv: { ko: '맞추려는 도수. 원래 도수보다 낮아야 물로 맞출 수 있습니다.', en: 'The strength you want; water can only take it down, never up.' },
  waterAddMl: { ko: '목표에 닿기 위해 더 넣을 물의 양.', en: 'How much water to pour in to hit the target.' },
  syrupPart: { ko: '비율에서 시럽이 차지하는 몫의 수.', en: 'How many parts of the ratio are syrup.' },
  waterPart: { ko: '비율에서 물이 차지하는 몫의 수.', en: 'How many parts of the ratio are water.' },
  syrupMl: { ko: '실제로 넣을 시럽의 양.', en: 'The amount of syrup to actually pour.' },
  amountA: { ko: '진한 쪽 액체를 넣을 양.', en: 'How much of the stronger liquid to use.' },
  amountB: { ko: '묶은 쪽 액체를 넣을 양.', en: 'How much of the weaker liquid to use.' },
  evapMl: { ko: '목표 농도까지 날려야 하는 물의 양.', en: 'The water that has to boil off to reach the target.' },
  stockPct: { ko: '희석 전 원액에 적힌 농도.', en: 'The concentration printed on the undiluted stock.' },
  targetPpm: { ko: '만들려는 용액의 목표 농도. 100만분의 몇입니다.', en: 'The concentration you are aiming for, in parts per million.' },
  stockNeedMl: { ko: '목표 농도를 만들기 위해 덜어 낼 원액의 양.', en: 'How much stock to draw off to hit that concentration.' },
  mainMl: { ko: '2액형에서 양이 많은 주제 쪽의 양.', en: 'The larger of the two parts — the resin or base.' },
  hardenerMl: { ko: '굳게 만드는 경화제 쪽의 양.', en: 'The hardener that makes it set.' },

  /* ───────── 점수·달성 ───────── */
  currentAvg: { ko: '지금까지 치른 시험의 평균 점수.', en: 'Your average across the tests taken so far.' },
  examsDone: { ko: '이미 치른 시험의 수.', en: 'How many tests are already behind you.' },
  examsLeft: { ko: '아직 남은 시험의 수.', en: 'How many tests are still to come.' },
  targetAvg: { ko: '학기가 끝났을 때 맞추려는 평균.', en: 'The average you want when the term is over.' },
  neededScore: { ko: '남은 시험에서 평균으로 받아야 하는 점수.', en: 'The average you must score on what is left.' },
  gapScore: { ko: '기준까지 모자란 점수.', en: 'How many points short of the line you are.' },
  midScore: { ko: '중간고사에서 받은 점수.', en: 'What you scored on the midterm.' },
  midWeight: { ko: '최종 성적에서 중간고사가 차지하는 비중.', en: 'How much the midterm counts towards the final grade.' },
  finalScoreV: { ko: '기말고사에서 받은 점수.', en: 'What you scored on the final exam.' },
  finalWeight: { ko: '최종 성적에서 기말고사가 차지하는 비중.', en: 'How much the final exam counts towards the grade.' },
  hwScore: { ko: '과제·출석 등으로 받은 점수.', en: 'Marks from coursework and attendance.' },
  weightedScore: { ko: '비중을 반영해 계산한 최종 점수.', en: 'The final mark once every weight is applied.' },
  passScore: { ko: '이 점수를 넘겨야 합격입니다.', en: 'Clear this and you pass.' },
  daysLeft: { ko: '기한까지 남은 날 수.', en: 'How many days remain until the deadline.' },
  perDay: { ko: '기한을 지키려면 하루에 해야 하는 양.', en: 'What you have to get through each day to make the deadline.' },
  /* ───────── 셋째 묶음 ───────── */
  tierQty: { ko: '이 수량부터 싼 단가가 붙습니다. 한 개만 모자라도 안 붙습니다.', en: 'The quantity at which the cheaper rate kicks in; one short and it does not.' },
  tierPrice: { ko: '기준 수량을 넘겼을 때 전부에 적용되는 단가.', en: 'The unit price applied to every item once the threshold is met.' },
  avgUnit: { ko: '총액을 개수로 나눈 값. 실제로 1개에 치른 돈입니다.', en: 'Total over quantity — what one unit really cost you.' },
  otherShare: { ko: '내 몫을 뺀 나머지, 곧 상대가 낼 금액.', en: 'What is left after your share — the other side’s part.' },
  multiple: { ko: '몇 배가 되는지. 2배는 100% 증가입니다.', en: 'How many times over; doubling is a 100% increase.' },
  halfLife: { ko: '지금 값이 절반으로 줄기까지 걸리는 시간.', en: 'How long it takes to fall to half of today’s value.' },
  balanceLeft: { ko: '아직 갚지 않고 남아 있는 원금. 이자는 빠져 있습니다.', en: 'Principal still owed, with interest excluded.' },
  bracketLine: { ko: '세율이 바뀌는 금액. 이 위로만 높은 세율이 붙습니다.', en: 'The amount where the rate changes; only income above it pays more.' },
  beanG: { ko: '갈기 전에 잰 원두 무게.', en: 'The weight of coffee, measured before grinding.' },
  brewRatio: { ko: '원두 1g에 붓는 물의 ml. 작을수록 진합니다.', en: 'Millilitres of water per gram of coffee; smaller means stronger.' },
  brewWater: { ko: '실제로 부을 물의 양. 잔에 남는 양보다 많습니다.', en: 'The water you pour in — more than what ends up in the cup.' },
  totalFold: { ko: '단계마다의 배수를 모두 곱한 값.', en: 'Every step’s factor multiplied together.' },
  curveShift: { ko: '모두에게 똑같이 더하거나 빼는 점수.', en: 'The points added to or taken from everyone alike.' },
};

export const rateDesc = (key: string, lang: Lang): string | null => RATE_DESC[key]?.[lang] ?? null;
