/**
 * 공예 용어의 뜻풀이(ko·en).
 *
 * 이 섹션은 입력을 잘못 넣기 쉽다. 게이지를 5cm에 몇 코로 재 놓고 10cm 칸에
 * 넣거나, 향 비율을 전체 무게 기준으로 잡거나, SAP 값을 오일 무게로 착각하는
 * 식이다. 어느 것을 어떻게 재는 값인지 한 줄로 적어 두면 그 실수가 줄어든다.
 *
 * 재는 자리를 콕 집어 적는다 — "완성 폭"이 시접을 포함하는지, "머리둘레"를
 * 어디서 재는지처럼. 그것이 답을 가르는 자리다.
 */
import type { Term } from './terms.ts';

export const CRAFT_DESC: Record<string, Term> = {
  /* 뜨개 */
  stitchGauge: { ko: '10cm에 들어가는 코 수. 5cm로 재면 두 배로 환산해 넣으세요.', en: 'Stitches in 10 cm. If you measured over 5 cm, double it before entering.' },
  rowGauge: { ko: '10cm에 들어가는 단 수. 폭이 아니라 길이를 정합니다.', en: 'Rows in 10 cm. This sets length, not width.' },
  patternGauge: { ko: '도안에 적힌 게이지. 내 것과 다르면 코 수를 고쳐야 합니다.', en: 'The gauge printed on the pattern; differing from yours means the counts change.' },
  myGauge: { ko: '내가 실제로 뜬 게이지. 세탁·블로킹 뒤에 잰 값입니다.', en: 'The gauge you actually knit, measured after washing and blocking.' },
  targetWidth: { ko: '완성했을 때의 폭. 시접이나 접는 몫은 넣지 않습니다.', en: 'The width when finished, before any seam or fold allowance.' },
  targetLength: { ko: '완성했을 때의 길이.', en: 'The length when finished.' },
  swatchArea: { ko: '시험 뜨기 조각의 면적. 10cm 사방이면 100㎠입니다.', en: 'Area of the swatch — a 10 cm square is 100 cm².' },
  swatchWeight: { ko: '그 조각의 무게. 실을 풀어 재지 말고 뜬 채로 잽니다.', en: 'What that swatch weighs; weigh it knitted, not unravelled.' },
  yarnWeight: { ko: '드는 실의 무게. 볼 개수가 아니라 g입니다.', en: 'The yarn weight in grams, not a number of balls.' },
  yarnLength: { ko: '드는 실의 길이. 라벨의 미터를 기준으로 합니다.', en: 'The yarn length in metres, matching the label.' },
  ballLength: { ko: '한 볼(타래)에 감긴 길이. 라벨에 적혀 있습니다.', en: 'Metres in one ball or skein, as stated on the band.' },
  ballWeight: { ko: '한 볼의 무게. 대개 50g이나 100g입니다.', en: 'Grams in one ball — usually 50 or 100.' },
  balls: { ko: '사야 하는 볼 수. 쪼갤 수 없어 올림입니다.', en: 'Balls to buy; you cannot split one, so it rounds up.' },
  metrePerGram: { ko: '1g에 몇 미터인지. 남은 실 무게로 길이를 되짚을 때 씁니다.', en: 'Metres per gram — how you read length off leftover weight.' },
  spare: { ko: '넉넉히 두는 몫. 마무리와 로트 차이 때문에 남깁니다.', en: 'The margin you keep for finishing and dye-lot mismatch.' },
  wpi: { ko: '자에 실을 나란히 감아 1인치를 채운 감김 수. 당겨 감으면 커집니다.', en: 'Wraps filling one inch on a ruler; winding tight inflates it.' },
  yarnClass: { ko: '실 굵기 번호. 0이 레이스, 6이 슈퍼벌키입니다.', en: 'Yarn weight number — 0 is lace, 6 is super bulky.' },
  stitches: { ko: '코 수. 가로로 세는 수입니다.', en: 'Stitch count, measured across.' },
  rows: { ko: '단 수. 세로로 세는 수입니다.', en: 'Row count, measured up.' },
  castOn: { ko: '처음에 잡는 코 수. 무늬 반복의 배수로 맞추세요.', en: 'Stitches to cast on; round to the pattern repeat.' },
  headCirc: { ko: '머리에서 가장 굵은 곳의 둘레. 귀 위를 지나게 잽니다.', en: 'The head at its widest, taped just above the ears.' },
  negEase: { ko: '머리보다 작게 뜨는 비율. 이것이 있어야 모자가 붙어 있습니다.', en: 'How much smaller than the head you knit — what keeps a hat on.' },
  startSts: { ko: '줄이기 전의 코 수.', en: 'The stitch count before shaping.' },
  endSts: { ko: '다 줄인 뒤의 코 수.', en: 'The stitch count after shaping.' },
  everyRows: { ko: '몇 단마다 한 번 줄이는지.', en: 'Work one decrease every this many rows.' },
  decreases: { ko: '줄임을 몇 번 하는지. 한 번에 두 코가 줄어듭니다.', en: 'How many decrease rounds; each takes two stitches.' },

  /* 재봉 */
  boltWidth: { ko: '원단의 폭. 접힌 채 팔면 펼친 폭으로 넣으세요.', en: 'The fabric width; if it is sold folded, enter the opened width.' },
  fabricLength: { ko: '사야 하는 원단 길이. 폭 방향이 아니라 결 방향입니다.', en: 'Fabric length to buy, along the grain rather than across.' },
  pieceW: { ko: '조각 하나의 폭. 시접을 포함한 재단 치수입니다.', en: 'One piece across, as cut — seam allowance included.' },
  pieceH: { ko: '조각 하나의 길이. 시접을 포함한 재단 치수입니다.', en: 'One piece along, as cut — seam allowance included.' },
  pieceCount: { ko: '필요한 조각 수. 같은 치수로 여러 장을 재단할 때의 장수입니다.', en: 'How many pieces you need at that size.' },
  piecesOut: { ko: '그 원단에서 나오는 조각 수.', en: 'How many pieces that fabric yields.' },
  perRow: { ko: '폭 하나에 나란히 놓이는 조각 수.', en: 'Pieces that sit side by side across the width.' },
  seamAllow: { ko: '한쪽 시접. 양쪽에 붙으므로 두 배가 더해집니다.', en: 'Allowance on one edge; it is added on both, so twice over.' },
  cutW: { ko: '재단할 폭. 완성 치수에 시접을 더한 값입니다.', en: 'The width to cut — finished size plus allowance.' },
  cutH: { ko: '재단할 길이. 완성 길이에 시접을 더한 값입니다.', en: 'The length to cut, finished length plus allowance.' },
  finishedLen: { ko: '완성했을 때의 길이.', en: 'The length when finished.' },
  gatherRatio: { ko: '완성 길이의 몇 배를 잡을지. 2배면 촘촘한 개더입니다.', en: 'How many times the finished length you cut; twice gives a full gather.' },
  elasticLen: { ko: '자를 고무줄 길이. 늘어난 상태가 아니라 편안한 길이입니다.', en: 'Elastic to cut, relaxed rather than stretched.' },
  stretchPct: { ko: '고무줄을 당겨 쓰는 비율.', en: 'How much you rely on the elastic stretching.' },
  beforeWash: { ko: '세탁 전에 잰 치수.', en: 'The measurement before washing.' },
  afterWash: { ko: '세탁 후에 잰 같은 자리 치수.', en: 'The same measurement after washing.' },
  shrinkPct: { ko: '줄어든 비율. 재단 전에 미리 빨아 두면 이만큼 안 놀랍니다.', en: 'How much it shrank; pre-washing spends this before you cut.' },
  extraNeeded: { ko: '수축을 메우려고 더 사야 하는 양.', en: 'The extra to buy so shrinkage does not leave you short.' },
  scalePct: { ko: '도안을 몇 %로 키우거나 줄이는지. 100%가 원본입니다.', en: 'How far to scale a pattern; 100% is the original.' },
  scaledLen: { ko: '배율을 적용한 치수.', en: 'The measurement after scaling.' },

  /* 퀼트·자수 */
  quiltW: { ko: '완성 퀼트의 폭. 바인딩을 두른 뒤의 치수입니다.', en: 'The finished quilt across, once bound.' },
  quiltH: { ko: '완성 퀼트의 길이. 바인딩을 두른 뒤의 치수입니다.', en: 'The finished quilt along, once bound.' },
  bindingLen: { ko: '둘레를 감싸는 데 드는 바인딩 길이. 이음과 코너 몫이 들어 있습니다.', en: 'Binding to go round, including corners and joins.' },
  stripW: { ko: '바인딩 스트립의 재단 폭. 접어 쓰므로 마감 폭의 네 배쯤입니다.', en: 'Cut width of a binding strip — about four times the finished edge.' },
  strips: { ko: '원단 폭에서 잘라 낼 스트립 수.', en: 'Strips to cut across the fabric width.' },
  backingLen: { ko: '뒷천으로 사야 하는 길이. 폭이 모자라면 이어 붙입니다.', en: 'Backing length to buy; too narrow a fabric must be pieced.' },
  overhang: { ko: '한 변에서 밖으로 남기는 여유. 퀼팅 중에 밀리는 몫입니다.', en: 'Extra beyond each edge, absorbing shift while quilting.' },
  battingArea: { ko: '솜의 면적. 퀼트보다 사방으로 조금씩 넓습니다.', en: 'The batting area, a little wider than the quilt on every side.' },
  blockSize: { ko: '블록 하나의 완성 크기. 시접을 뺀 값입니다.', en: 'One block finished, seam allowance excluded.' },
  blocks: { ko: '블록의 총 개수. 가로 수와 세로 수를 곱한 값입니다.', en: 'Total blocks — across times down.' },
  blocksW: { ko: '가로로 놓이는 블록 수.', en: 'Blocks across.' },
  blocksH: { ko: '세로로 놓이는 블록 수.', en: 'Blocks down.' },
  hstFinished: { ko: '완성된 반쪽 삼각 블록의 크기. 시접을 뺀 값입니다.', en: 'The finished half-square triangle, seam allowance excluded.' },
  hstCut: { ko: '시작할 정사각형의 재단 크기.', en: 'The size to cut the starting squares.' },
  aidaCount: { ko: '1인치에 들어가는 코 수. 14카운트가 가장 흔합니다.', en: 'Stitches per inch of fabric; 14-count is the common one.' },
  chartW: { ko: '도안의 가로 코 수.', en: 'Chart stitches across.' },
  chartH: { ko: '도안의 세로 코 수.', en: 'Chart stitches down.' },
  designW: { ko: '수를 놓은 그림의 가로 크기.', en: 'The stitched design across.' },
  designH: { ko: '수를 놓은 그림의 세로 크기.', en: 'The stitched design down.' },
  stitchCount: { ko: '놓을 스티치의 총 수.', en: 'Total stitches to work.' },
  strandCount: { ko: '바늘에 꿰는 가닥 수. 여섯 겹 실에서 몇 겹을 쓰는지입니다.', en: 'Strands in the needle, out of the six in the skein.' },
  flossLen: { ko: '드는 실의 길이. 여섯 겹 타래가 아니라 꿰는 가닥 기준입니다.', en: 'Floss length for the strands in the needle, not whole skeins.' },

  /* 양초 */
  containerVol: { ko: '용기에 담기는 부피. 물을 채워 재는 것이 가장 정확합니다.', en: 'What the vessel holds; filling it with water is the accurate way.' },
  fillPct: { ko: '용기의 몇 %까지 채우는지. 위쪽은 비워 둡니다.', en: 'How far up you fill; the top stays clear.' },
  waxDensity: { ko: '왁스 1㎤의 무게. 소이는 0.9 안팎, 파라핀은 조금 더 무겁습니다.', en: 'Grams per cm³ of wax — soy near 0.9, paraffin a little more.' },
  waxWeight: { ko: '녹여야 하는 왁스 무게.', en: 'The wax to melt, by weight.' },
  candleCount: { ko: '한 번에 만들 개수. 같은 용기라고 보고 계산합니다.', en: 'How many you are pouring in one batch of identical vessels.' },
  fragrancePct: { ko: '왁스 무게 기준의 향 비율. 전체 무게 기준이 아닙니다.', en: 'Fragrance as a share of the wax, not of the finished candle.' },
  fragranceWt: { ko: '넣는 향료의 무게. 부피가 아니라 무게로 재세요.', en: 'Fragrance oil by weight; do not measure it by volume.' },
  totalBatch: { ko: '왁스와 향료를 합친 무게.', en: 'Wax and fragrance together.' },
  burnRate: { ko: '한 시간에 줄어드는 왁스 무게. 심지 굵기가 정합니다.', en: 'Wax lost per hour; the wick size sets it.' },
  burnHours: { ko: '다 타는 데 걸리는 시간.', en: 'Hours until it is spent.' },
  vesselD: { ko: '용기 안쪽 지름. 유리 두께를 빼고 잽니다.', en: 'The inside diameter, excluding the glass wall.' },
  vesselH: { ko: '용기 안쪽 높이. 바닥 두께를 빼고 잽니다.', en: 'The inside height, excluding the thickness of the base.' },
  baseWeight: { ko: '녹일 베이스의 무게.', en: 'The base to melt, by weight.' },
  unitCost: { ko: '한 개에 드는 재료비.', en: 'Materials for one piece.' },

  /* 비누·수지 */
  oilWeight: { ko: '레시피의 오일 총 무게. 물과 가성소다는 뺀 값입니다.', en: 'Total oils in the recipe, excluding water and lye.' },
  sapValue: { ko: '오일 1g을 비누로 만드는 데 드는 KOH의 mg. 오일마다 다릅니다.', en: 'Milligrams of KOH to saponify one gram of that oil; it differs per oil.' },
  superfat: { ko: '비누에 남기는 오일 비율. 가성소다를 그만큼 덜 넣습니다.', en: 'Oil left unsaponified; the lye is cut by this much.' },
  lyeWeight: { ko: '넣어야 하는 가성소다 무게. 적으면 무르고 많으면 caustic입니다.', en: 'Lye needed; too little leaves it soft, too much leaves it caustic.' },
  lyePurity: { ko: '가성소다의 순도. KOH는 대개 90%입니다.', en: 'Purity of the lye — KOH is usually 90%.' },
  waterRatio: { ko: '가성소다 1에 대한 물의 비. 2:1이 흔합니다.', en: 'Water per part lye; 2:1 is the common choice.' },
  waterWeight: { ko: '녹이는 물의 무게. 가성소다를 물에 넣습니다, 반대로는 절대 안 됩니다.', en: 'Water to dissolve in; lye goes into water, never the reverse.' },
  batchTotal: { ko: '오일·물·가성소다를 합친 무게.', en: 'Oils, water and lye together.' },
  recipeScale: { ko: '레시피를 몇 배로 하는지.', en: 'How many times the recipe you are making.' },
  mouldVol: { ko: '몰드가 담는 부피. 물을 채워 재면 정확합니다.', en: 'What the mould holds; measure it with water.' },
  resinDensity: { ko: '재료 1㎤의 무게. 에폭시는 1.1 안팎입니다.', en: 'Grams per cm³ — epoxy sits near 1.1.' },
  resinWeight: { ko: '드는 수지의 무게. A제와 B제를 합친 값입니다.', en: 'Resin needed in total, parts A and B together.' },
  mixRatioA: { ko: '혼합비의 A쪽 숫자.', en: 'The A side of the mix ratio.' },
  mixRatioB: { ko: '혼합비의 B쪽 숫자.', en: 'The B side of the mix ratio.' },
  partA: { ko: '재야 하는 A제의 양.', en: 'How much part A to weigh out.' },
  partB: { ko: '재야 하는 B제의 양. 눈대중은 굳지 않는 원인입니다.', en: 'How much part B; eyeballing this is why resin fails to cure.' },
  pigmentPct: { ko: '수지 무게 기준의 색소 비율. 많이 넣으면 굳지 않습니다.', en: 'Pigment as a share of the resin; too much stops the cure.' },
  pigmentWt: { ko: '넣는 색소의 양. 수지 무게에 비례합니다.', en: 'How much pigment to add, in proportion to the resin.' },
  modelVol: { ko: '몰드를 뜰 원형의 부피.', en: 'The volume of the model you are moulding.' },
  siliconeWt: { ko: '드는 실리콘의 무게. 상자 부피에서 원형 부피를 뺀 몫입니다.', en: 'Silicone needed — the box volume less the model.' },

  /* 구슬·포장 */
  strandLen: { ko: '완성할 줄의 길이. 잠금장치 길이는 빼고 잡으세요.', en: 'The finished strand, excluding the clasp.' },
  beadD: { ko: '구슬 하나의 지름. 구멍이 아니라 겉 지름입니다.', en: 'One bead across the outside, not the hole.' },
  beadCount: { ko: '드는 구슬 개수. 사이 간격을 넣으면 그만큼 줄어듭니다.', en: 'Beads it takes; adding a gap between them lowers it.' },
  beadWt: { ko: '구슬 하나의 무게. 열 개를 재서 나누면 정확합니다.', en: 'One bead\'s weight; weigh ten and divide.' },
  totalBeadWt: { ko: '구슬 전체의 무게. 배송비나 발송 단위를 볼 때 씁니다.', en: 'What all the beads weigh, for postage or ordering by weight.' },
  mandrelD: { ko: '감는 심의 지름. 링의 안지름이 됩니다.', en: 'The mandrel across; it becomes the ring\'s inside diameter.' },
  wireD: { ko: '와이어의 굵기. 링 지름에 두 번 더해집니다.', en: 'Wire thickness; it adds to the ring diameter twice.' },
  wraps: { ko: '감는 횟수. 한 바퀴가 지름의 원주만큼 먹습니다.', en: 'How many turns; each eats one circumference.' },
  wireLen: { ko: '드는 와이어 길이. 자르는 몫과 다듬는 몫은 빠져 있습니다.', en: 'Wire needed, before what you trim and waste.' },
  ringCount: { ko: '만들어지는 링 개수.', en: 'How many rings you get.' },
  knotLen: { ko: '매듭으로 채울 구간의 길이. 완성 길이가 아닙니다.', en: 'The stretch you will fill with knots, not the finished length.' },
  cordMultiple: { ko: '매듭 구간의 몇 배로 코드를 자를지. 사각매듭은 4배쯤입니다.', en: 'How many times the knotted length to cut; square knots take about four.' },
  cordCount: { ko: '쓰는 코드 가닥 수.', en: 'How many cords you use.' },
  cordLen: { ko: '자를 코드 길이. 한 가닥 기준입니다.', en: 'Cord to cut, per single cord.' },
  boxW: { ko: '상자의 폭. 뚜껑을 덮은 상태로 잽니다.', en: 'The box across, measured with the lid on.' },
  boxD: { ko: '상자의 깊이. 앞에서 뒤까지입니다.', en: 'The box front to back.' },
  boxH: { ko: '상자의 높이. 뚜껑까지 포함합니다.', en: 'The box height, lid included.' },
  wrapW: { ko: '필요한 포장지의 폭.', en: 'The paper width needed.' },
  wrapH: { ko: '필요한 포장지의 길이.', en: 'The paper length needed.' },
  ribbonLen: { ko: '드는 리본 길이. 매듭과 고리 몫이 들어 있습니다.', en: 'Ribbon needed, including the knot and bow.' },
  clayDensity: { ko: '점토 1㎤의 무게. 폴리머는 1.7 안팎, 자연건조 점토는 더 가볍습니다.', en: 'Grams per cm³ — polymer near 1.7, air-dry lighter.' },
  clayWeight: { ko: '드는 점토의 무게. 구우면서 줄어드는 몫은 빠져 있습니다.', en: 'Clay needed by weight, before any loss in baking.' },
};
