/**
 * 비율 섹션 용어의 뜻풀이(3언어).
 *
 * glossary.ts가 세 섹션 공통이라면 여기는 비율 100종을 만들며 생긴 용어들이다.
 * 입력 표와 결과 표에서 라벨 아래 한 줄로 붙는다.
 */
import type { Lang, Term } from './terms.ts';

export const RATE_DESC: Record<string, Term> = {
  /* ───────── 할인·가격 ───────── */
  effDiscount: { ko: '겹친 할인을 하나로 합친 실제 할인율. 각 할인율을 더한 값보다 작습니다.', en: 'Stacked discounts boiled down to one number — always less than adding them.', zh: '把叠加折扣合成一个数字的实际折扣率，总是小于各折扣相加。' },
  payCount: { ko: '돈을 내고 사는 개수. 덤은 여기 넣지 않습니다.', en: 'How many you pay for; the free ones do not go here.', zh: '需要付钱购买的数量，赠品不计入此项。' },
  freeCount: { ko: '덤으로 받는 개수. 1+1이면 1입니다.', en: 'How many come free — one, in a buy-one-get-one.', zh: '免费赠送的数量，买一送一时为1。' },
  unitPrice: { ko: '한 개에 얼마인지. 덤을 포함한 전체 개수로 나눈 값입니다.', en: 'What one costs, divided across everything you carry home.', zh: '每个多少钱，按含赠品的总数量摊算。' },
  saveAmt: { ko: '이 조건으로 아끼는 금액.', en: 'How much this deal keeps in your pocket.', zh: '在此条件下节省的金额。' },
  costPerUse: { ko: '한 번 쓸 때 드는 값. 가격을 쓸 횟수로 나눕니다.', en: 'What one use costs — price divided by the number of uses.', zh: '每使用一次的成本，即价格除以使用次数。' },
  costPerMonth: { ko: '한 달로 환산한 비용. 구독료와 견주기 좋습니다.', en: 'The cost spread over a month — handy against a subscription.', zh: '折算到每月的成本，便于与订阅费比较。' },
  costPerDay: { ko: '하루로 환산한 비용. 커피 한 잔과 견주면 감이 옵니다.', en: 'The cost spread over a day; compare it with a coffee.', zh: '折算到每天的成本，与一杯咖啡对比就有概念了。' },
  freeShipMin: { ko: '배송비가 사라지는 주문 금액 기준선.', en: 'The order value at which delivery becomes free.', zh: '达到即可免运费的订单金额门槛。' },
  shipFee: { ko: '기준을 못 넘겼을 때 붙는 배송비.', en: 'What delivery costs if you stay under the threshold.', zh: '未达门槛时需支付的运费。' },
  addBuy: { ko: '무료배송 기준까지 더 담아야 하는 금액.', en: 'How much more the basket needs to clear the threshold.', zh: '为达到免运门槛还需加购的金额。' },
  annualFee: { ko: '1년에 한 번 내는 회비.', en: 'The fee charged once a year.', zh: '每年缴纳一次的会费。' },
  memberPrice: { ko: '회원에게만 주는 값. 일반가보다 낮아야 회비를 뽑습니다.', en: 'The price members get; it must beat the normal one for the fee to pay off.', zh: '仅会员适用的价格，需低于一般价才能回本。' },
  breakEvenCount: { ko: '회비를 뽑는 데 필요한 이용 횟수. 올림해서 셉니다.', en: 'Uses needed before the fee is recovered, rounded up.', zh: '收回会费所需的使用次数，向上取整。' },
  baseRate: { ko: '수수료가 붙지 않은 시장 중간 환율.', en: 'The mid-market rate, before anyone adds a margin.', zh: '未加任何加价的市场中间汇率。' },
  appliedRate: { ko: '창구에서 실제로 적용된 환율.', en: 'The rate the counter actually gave you.', zh: '柜台实际适用的汇率。' },
  spread: { ko: '기준 환율과 적용 환율의 차이. 숨은 수수료입니다.', en: 'The gap between mid-market and what you got — the hidden fee.', zh: '基准汇率与实际汇率之差，即隐藏手续费。' },
  buyPrice: { ko: '살 때 실제로 낸 금액. 수수료를 포함해야 손익이 맞습니다.', en: 'What you actually paid, fees included, or the profit maths breaks.', zh: '购入时实际支付的金额，需含手续费才能算准盈亏。' },
  depreciation: { ko: '해마다 값이 떨어지는 비율. 남은 가치에 붙습니다.', en: 'How much value falls each year, applied to what is left.', zh: '每年贬值的比率，作用于剩余价值。' },
  nowValue: { ko: '감가를 반영한 지금 가치.', en: 'What it is worth today, after depreciation.', zh: '计入折旧后的当前价值。' },
  minMargin: { ko: '할인해도 지켜야 하는 최소 이익률.', en: 'The margin you refuse to go below, however deep the discount.', zh: '即使打折也必须守住的最低利润率。' },
  maxDiscount: { ko: '그 이익률을 지키면서 줄 수 있는 가장 큰 할인율.', en: 'The deepest discount that still leaves that margin standing.', zh: '在守住该利润率下能给出的最大折扣率。' },
  installMonths: { ko: '몇 달에 걸쳐 나눠 낼지. 길어질수록 수수료 총액이 커집니다.', en: 'How many months to spread it over; longer means more fee in total.', zh: '分几个月偿还；月数越长，总费用越多。' },

  /* ───────── 세금·정산 ───────── */
  taxRate: { ko: '적용되는 세율. 나라와 품목에 따라 다릅니다.', en: 'The tax rate that applies; it varies by country and item.', zh: '适用的税率，因国家与品项而异。' },
  taxFreeRate: { ko: '세금을 떼지 않는 상품의 표시 수익률.', en: 'The headline rate on a product whose returns are not taxed.', zh: '免税产品的标示收益率。' },
  equivYield: { ko: '세금을 떼고도 비과세와 같아지려면 필요한 과세 수익률.', en: 'The taxable rate that, after tax, matches the tax-free one.', zh: '扣税后与免税收益相当所需的应税收益率。' },
  serviceRate: { ko: '음식값에 얹히는 봉사료 비율.', en: 'The service charge added on top of the bill.', zh: '在餐费之上加收的服务费比率。' },
  feeRateA: { ko: '먼저 떼이는 수수료의 비율.', en: 'The first cut taken, as a percentage.', zh: '先扣除的那笔手续费比率。' },
  feeRateB: { ko: '남은 금액에서 다시 떼이는 수수료의 비율.', en: 'The second cut, taken from what is left.', zh: '再从剩余金额中扣除的手续费比率。' },
  totalDays: { ko: '계약이나 이용권의 전체 기간.', en: 'The full length of the contract or pass.', zh: '合同或使用权的完整期间。' },
  usedDays: { ko: '이미 쓴 기간. 이 부분은 돌려받지 못합니다.', en: 'The part already used — that share does not come back.', zh: '已经使用的期间，这部分无法退回。' },
  refundAmt: { ko: '남은 기간에 비례해 돌려받는 금액.', en: 'What comes back, in proportion to the days left.', zh: '按剩余期间比例退回的金额。' },
  goodsPrice: { ko: '배송비를 뺀 물건 값 자체.', en: 'The item price on its own, before shipping.', zh: '不含运费的货物本身价格。' },
  dutyRate: { ko: '수입할 때 붙는 관세율. 품목마다 다릅니다.', en: 'The customs duty rate on import; it differs by product.', zh: '进口时征收的关税率，因品类而异。' },
  landedCost: { ko: '물건값·배송비·관세·세금을 모두 더한 실제 지불액.', en: 'Item, shipping, duty and tax added up — what you really pay.', zh: '货价、运费、关税与税款相加后的实际支付额。' },
  dutyFreeLimit: { ko: '이 금액까지는 세금이 붙지 않는 한도.', en: 'The value up to which nothing is charged.', zh: '在此金额以内不征税的额度。' },
  taxableAmt: { ko: '한도를 넘겨 세금이 매겨지는 부분.', en: 'The slice above the allowance that gets taxed.', zh: '超出额度、需要计税的部分。' },
  workHours: { ko: '한 달에 실제로 일하는 시간. 야근을 포함합니다.', en: 'Hours actually worked in a month, overtime included.', zh: '一个月实际工作的小时数，含加班。' },
  hourlyNet: { ko: '세금을 떼고 한 시간 일해 남는 돈.', en: 'What an hour of work leaves you after tax.', zh: '扣税后工作一小时实得的金额。' },

  /* ───────── 비율·증감 ───────── */
  outerPct: { ko: '전체에서 먼저 떼어 내는 비율.', en: 'The share carved out of the whole first.', zh: '先从整体中划出的比例。' },
  innerPct: { ko: '떼어 낸 그 안에서 다시 세는 비율.', en: 'The share counted inside that slice.', zh: '在划出的部分之内再计的比例。' },
  netPercent: { ko: '두 비율을 곱해 전체 기준으로 환산한 값.', en: 'The two shares multiplied, back on the scale of the whole.', zh: '两个比例相乘后换算回整体口径的值。' },
  changeA: { ko: '먼저 일어난 변화의 비율.', en: 'The first change, as a percentage.', zh: '先发生的那次变化比率。' },
  changeB: { ko: '그다음에 일어난 변화의 비율. 커진 값에 적용됩니다.', en: 'The second change; it works off the new, larger value.', zh: '随后发生的变化比率，作用于已变化后的数值。' },
  trueVal: { ko: '기준으로 삼는 정확한 값. 오차율의 분모입니다.', en: 'The correct figure you measure against — the denominator.', zh: '作为基准的正确数值，是误差率的分母。' },
  measured: { ko: '실제로 재서 얻은 값.', en: 'The figure your measurement produced.', zh: '实际测量得到的数值。' },
  errorPct: { ko: '참값에서 벗어난 정도를 비율로 나타낸 값.', en: 'How far off the measurement was, as a percentage.', zh: '偏离真值程度的百分比表示。' },
  startVal: { ko: '성장을 시작하는 시점의 값.', en: 'Where the growth starts from.', zh: '增长起点的数值。' },
  endVal: { ko: '기간이 끝날 때 닿으려는 값.', en: 'Where you want to be when the period ends.', zh: '期末希望达到的数值。' },
  neededRate: { ko: '기간 안에 목표에 닿기 위해 매년 필요한 성장률.', en: 'The yearly growth required to arrive on time.', zh: '按期达成目标所需的年增长率。' },
  rankNo: { ko: '위에서 몇 번째인지. 1이 가장 좋습니다.', en: 'Your place counting from the top; one is best.', zh: '从上数第几名，1为最好。' },
  totalPeople: { ko: '순위를 매긴 전체 인원.', en: 'How many people were ranked in total.', zh: '参与排名的总人数。' },
  topPercent: { ko: '상위 몇 %인지. 작을수록 좋습니다.', en: 'What top percentage you fall in — smaller is better.', zh: '处于前百分之几，越小越好。' },
  grade: { ko: '아래에 몇 %가 있는지. 클수록 좋습니다.', en: 'What share sits below you — bigger is better.', zh: '有百分之几的人在你之下，越大越好。' },
  ratioC: { ko: '비의 세 번째 숫자. 3:2:1에서 1입니다.', en: 'The third number of the ratio — the 1 in 3:2:1.', zh: '比例中的第三项，即3:2:1中的1。' },
  shareC: { ko: '비율대로 나눴을 때 C가 받는 몫.', en: 'The slice C gets once the ratio is applied.', zh: '按比例分配后C所得的份额。' },
  permille: { ko: '1000분의 몇인지. 퍼센트의 10배 숫자로 나옵니다.', en: 'Parts per thousand — ten times the percentage figure.', zh: '千分之几，数值是百分比的10倍。' },
  workers: { ko: '일에 붙는 사람 수.', en: 'How many people are on the job.', zh: '投入工作的人数。' },
  daysNeeded: { ko: '그 인원으로 일을 끝내는 데 걸리는 날 수.', en: 'Days to finish with that many people.', zh: '按该人数完成工作所需的天数。' },
  usedAmt: { ko: '전체 가운데 이미 써 버린 양.', en: 'How much of the total is already gone.', zh: '总量中已经用掉的部分。' },
  indexVal: { ko: '기준을 100으로 놓았을 때의 값. 115면 15% 높습니다.', en: 'The value with the base set to 100; 115 means 15% above.', zh: '以基准为100时的数值，115表示高出15%。' },

  /* ───────── 금융·이자 ───────── */
  goalAmount: { ko: '기간 안에 모으려는 금액.', en: 'The sum you want to have by the end.', zh: '希望在期限内攒到的金额。' },
  neededMonthly: { ko: '목표에 닿기 위해 매달 넣어야 하는 금액.', en: 'What to pay in each month to land on the goal.', zh: '为达成目标每月需存入的金额。' },
  monthsNeeded: { ko: '지금 속도로 목표까지 걸리는 개월 수.', en: 'Months to the goal at the current pace.', zh: '按当前速度到达目标所需的月数。' },
  futureAmt: { ko: '나중에 받게 될 금액.', en: 'The sum arriving at some point in the future.', zh: '未来某时点将收到的金额。' },
  discountRate: { ko: '미래 금액을 현재로 끌어올 때 쓰는 연 이율.', en: 'The yearly rate used to pull a future sum back to today.', zh: '把未来金额折算到今天所用的年利率。' },
  presentAmt: { ko: '미래 금액을 지금 가치로 바꾼 값.', en: 'That future sum expressed in today’s money.', zh: '把未来金额换算成今天价值后的数额。' },
  affordPay: { ko: '매달 무리 없이 갚을 수 있는 금액.', en: 'What you can comfortably hand over each month.', zh: '每月能够从容偿还的金额。' },
  maxLoan: { ko: '그 월 상환액으로 감당할 수 있는 원금.', en: 'The principal that monthly payment can support.', zh: '该月供所能支撑的贷款本金。' },
  prepayAmt: { ko: '정해진 상환 외에 미리 갚는 원금.', en: 'Principal paid off ahead of the schedule.', zh: '在约定还款之外提前偿还的本金。' },
  savedInterest: { ko: '미리 갚아서 내지 않게 된 이자.', en: 'The interest that never accrues because you paid early.', zh: '因提前还款而不再产生的利息。' },
  days: { ko: '이자가 붙는 날 수. 하루치 이자에 이 값을 곱합니다.', en: 'How many days interest runs for; multiply the daily figure by this.', zh: '计息的天数，用每日利息乘以它。' },
  dailyInterest: { ko: '하루에 붙는 이자. 연이율을 365로 나눈 값입니다.', en: 'Interest for a single day — the annual rate over 365.', zh: '每天产生的利息，即年利率除以365。' },
  firstInterest: { ko: '첫 달 상환액 가운데 이자로 가는 부분.', en: 'The part of the first payment that goes to interest.', zh: '首月还款中归入利息的部分。' },
  firstPrincipal: { ko: '첫 달에 실제로 줄어드는 원금.', en: 'How much principal the first payment actually retires.', zh: '首月实际偿还掉的本金。' },
  installFee: { ko: '할부에 붙는 표시 수수료율. 처음 금액 전체에 매겨집니다.', en: 'The quoted instalment fee, charged on the full amount.', zh: '分期标示费率，按初始全额收取。' },
  apr: { ko: '실제로 부담하는 연 이자율. 표시 수수료율의 두 배에 가깝습니다.', en: 'The rate you really bear — close to double the quoted fee.', zh: '实际承担的年利率，接近名义费率的两倍。' },
  futurePrice: { ko: '물가가 오른 뒤의 가격.', en: 'What it will cost once prices have risen.', zh: '物价上涨之后的价格。' },
  buyPriceA: { ko: '처음 살 때의 단가.', en: 'The unit price on the first purchase.', zh: '首次买入的单价。' },
  buyQtyA: { ko: '처음 살 때의 수량. 평균 단가의 가중치가 됩니다.', en: 'How many you bought first; it weights the average price.', zh: '首次买入的数量，是平均成本的权重。' },
  buyPriceB: { ko: '두 번째로 살 때의 단가.', en: 'The unit price on the second purchase.', zh: '第二次买入的单价。' },
  buyQtyB: { ko: '두 번째로 산 수량.', en: 'How many you bought the second time.', zh: '第二次买入的数量。' },
  avgPrice: { ko: '수량으로 가중한 평균 단가. 손익분기점이 되는 값입니다.', en: 'The quantity-weighted average price — your break-even.', zh: '按数量加权的平均单价，也是回本价位。' },
  totalQty: { ko: '두 번에 걸쳐 산 전체 수량.', en: 'Everything bought across both purchases.', zh: '两次买入的总数量。' },
  feeRate: { ko: '사고팔 때 양쪽에서 떼이는 수수료를 합친 비율.', en: 'Buying and selling fees added together.', zh: '买入与卖出手续费合计的比率。' },
  needReturn: { ko: '수수료를 물고 본전이 되기 위해 올라야 하는 비율.', en: 'The rise needed just to get back to even after fees.', zh: '扣除手续费后回到本金所需的涨幅。' },
  monthlySpend: { ko: '한 달에 쓰는 돈. 고정비와 변동비를 모두 넣습니다.', en: 'What you spend in a month, fixed and variable together.', zh: '一个月的支出，含固定与浮动开销。' },
  fundMonths: { ko: '수입이 끊겨도 버티려는 개월 수.', en: 'How many months you want to survive with no income.', zh: '希望在没有收入时能支撑的月数。' },
  savedSoFar: { ko: '지금까지 모아 둔 금액.', en: 'What you have set aside so far.', zh: '目前已经存下的金额。' },
  fundAmount: { ko: '그 개월을 버티기 위해 필요한 총액.', en: 'The total needed to cover those months.', zh: '支撑这些月份所需的总额。' },
  faceValue: { ko: '채권에 적힌 금액. 만기에 돌려받는 원금입니다.', en: 'The amount printed on the bond — repaid at maturity.', zh: '债券上标明的金额，到期时偿还的本金。' },
  couponRate: { ko: '액면에 대해 해마다 주는 이자 비율. 고정입니다.', en: 'Yearly interest as a share of face value; it is fixed.', zh: '相对面值每年支付的利息比率，固定不变。' },
  currentYield: { ko: '실제 매입가에 대한 이자 수익률.', en: 'The coupon measured against what you actually paid.', zh: '按实际买入价计算的利息收益率。' },

  /* ───────── 농도·배합 ───────── */
  origAbv: { ko: '희석 전 술의 도수.', en: 'The strength of the drink before you dilute it.', zh: '稀释之前的酒精度数。' },
  targetAbv: { ko: '맞추려는 도수. 원래 도수보다 낮아야 물로 맞출 수 있습니다.', en: 'The strength you want; water can only take it down, never up.', zh: '希望调到的度数；加水只能降低度数，无法升高。' },
  waterAddMl: { ko: '목표에 닿기 위해 더 넣을 물의 양.', en: 'How much water to pour in to hit the target.', zh: '为达到目标需要加入的水量。' },
  syrupPart: { ko: '비율에서 시럽이 차지하는 몫의 수.', en: 'How many parts of the ratio are syrup.', zh: '比例中糖浆所占的份数。' },
  waterPart: { ko: '비율에서 물이 차지하는 몫의 수.', en: 'How many parts of the ratio are water.', zh: '比例中水所占的份数。' },
  syrupMl: { ko: '실제로 넣을 시럽의 양.', en: 'The amount of syrup to actually pour.', zh: '实际需要加入的糖浆量。' },
  amountA: { ko: '진한 쪽 액체를 넣을 양.', en: 'How much of the stronger liquid to use.', zh: '需要取用的较浓液体的量。' },
  amountB: { ko: '묶은 쪽 액체를 넣을 양.', en: 'How much of the weaker liquid to use.', zh: '需要取用的较稀液体的量。' },
  evapMl: { ko: '목표 농도까지 날려야 하는 물의 양.', en: 'The water that has to boil off to reach the target.', zh: '为达到目标浓度需蒸发掉的水量。' },
  stockPct: { ko: '희석 전 원액에 적힌 농도.', en: 'The concentration printed on the undiluted stock.', zh: '未稀释原液标示的浓度。' },
  targetPpm: { ko: '만들려는 용액의 목표 농도. 100만분의 몇입니다.', en: 'The concentration you are aiming for, in parts per million.', zh: '目标溶液的浓度，以百万分之几表示。' },
  stockNeedMl: { ko: '목표 농도를 만들기 위해 덜어 낼 원액의 양.', en: 'How much stock to draw off to hit that concentration.', zh: '为配出该浓度需要取用的原液量。' },
  mainMl: { ko: '2액형에서 양이 많은 주제 쪽의 양.', en: 'The larger of the two parts — the resin or base.', zh: '双组分中用量较多的主剂量。' },
  hardenerMl: { ko: '굳게 만드는 경화제 쪽의 양.', en: 'The hardener that makes it set.', zh: '使其固化的固化剂用量。' },

  /* ───────── 점수·달성 ───────── */
  currentAvg: { ko: '지금까지 치른 시험의 평균 점수.', en: 'Your average across the tests taken so far.', zh: '已考科目的平均分。' },
  examsDone: { ko: '이미 치른 시험의 수.', en: 'How many tests are already behind you.', zh: '已经考完的科目数。' },
  examsLeft: { ko: '아직 남은 시험의 수.', en: 'How many tests are still to come.', zh: '尚未考的科目数。' },
  targetAvg: { ko: '학기가 끝났을 때 맞추려는 평균.', en: 'The average you want when the term is over.', zh: '学期结束时希望达到的平均分。' },
  neededScore: { ko: '남은 시험에서 평균으로 받아야 하는 점수.', en: 'The average you must score on what is left.', zh: '剩余科目需要达到的平均分。' },
  gapScore: { ko: '기준까지 모자란 점수.', en: 'How many points short of the line you are.', zh: '距标准还差的分数。' },
  midScore: { ko: '중간고사에서 받은 점수.', en: 'What you scored on the midterm.', zh: '期中考试所得分数。' },
  midWeight: { ko: '최종 성적에서 중간고사가 차지하는 비중.', en: 'How much the midterm counts towards the final grade.', zh: '期中考试在最终成绩中的权重。' },
  finalScoreV: { ko: '기말고사에서 받은 점수.', en: 'What you scored on the final exam.', zh: '期末考试所得分数。' },
  finalWeight: { ko: '최종 성적에서 기말고사가 차지하는 비중.', en: 'How much the final exam counts towards the grade.', zh: '期末考试在最终成绩中的权重。' },
  hwScore: { ko: '과제·출석 등으로 받은 점수.', en: 'Marks from coursework and attendance.', zh: '作业与出勤等所得分数。' },
  weightedScore: { ko: '비중을 반영해 계산한 최종 점수.', en: 'The final mark once every weight is applied.', zh: '计入各项权重后的最终分数。' },
  passScore: { ko: '이 점수를 넘겨야 합격입니다.', en: 'Clear this and you pass.', zh: '超过这一分数即为合格。' },
  daysLeft: { ko: '기한까지 남은 날 수.', en: 'How many days remain until the deadline.', zh: '距截止还剩的天数。' },
  perDay: { ko: '기한을 지키려면 하루에 해야 하는 양.', en: 'What you have to get through each day to make the deadline.', zh: '为赶上截止日期每天需完成的量。' },
};

export const rateDesc = (key: string, lang: Lang): string | null => RATE_DESC[key]?.[lang] ?? null;
