/**
 * 도형 둘째 묶음 용어의 뜻풀이(3언어).
 *
 * 도형 용어는 이름이 비슷해서 서로 헷갈린다 — 모선과 높이, 내접원과 외접원,
 * 활 높이와 현. 무엇이 어디를 가리키는지 한 줄로 적어 두면 입력을 잘못 넣지 않는다.
 */
import type { Lang, Term } from './terms.ts';

export const GEO2_DESC: Record<string, Term> = {
  /* 평면 */
  sideSquare: { ko: '정사각형이나 정육면체의 한 모서리 길이.', en: 'One edge of a square or cube.', zh: '正方形或正方体的一条边长。' },
  heightTri: { ko: '밑변에서 수직으로 잰 높이. 비스듬한 변이 아닙니다.', en: 'The perpendicular height from the base, not a slanted side.', zh: '自底边垂直量得的高，不是斜边。' },
  inradius: { ko: '세 변에 모두 닿는 원의 반지름. 도형 안쪽에 있습니다.', en: 'Radius of the circle touching all sides, sitting inside the shape.', zh: '与各边都相切的圆的半径，位于图形内部。' },
  circumradius: { ko: '모든 꼭짓점을 지나는 원의 반지름. 도형 바깥으로 감쌉니다.', en: 'Radius of the circle through every vertex, wrapping the shape.', zh: '经过所有顶点的圆的半径，包住整个图形。' },
  included: { ko: '두 변이 만나서 이루는 각. 다른 각을 넣으면 공식이 틀립니다.', en: 'The angle where the two sides meet; another angle breaks the formula.', zh: '两条边相交所成的角；换成其他角公式便不成立。' },
  scaleFactor: { ko: '길이를 몇 배로 키우거나 줄이는지.', en: 'How many times you scale the lengths up or down.', zh: '把长度放大或缩小的倍数。' },
  areaRatio: { ko: '길이가 k배가 될 때 면적이 늘어나는 배수. k의 제곱입니다.', en: 'How much area grows when length scales by k — k squared.', zh: '长度放大k倍时面积增加的倍数，即k的平方。' },
  volumeRatio: { ko: '길이가 k배가 될 때 부피가 늘어나는 배수. k의 세제곱입니다.', en: 'How much volume grows when length scales by k — k cubed.', zh: '长度放大k倍时体积增加的倍数，即k的立方。' },
  x3: { ko: '세 번째 점의 가로 좌표.', en: 'The horizontal coordinate of the third point.', zh: '第三个点的横坐标。' },
  y3: { ko: '세 번째 점의 세로 좌표.', en: 'The vertical coordinate of the third point.', zh: '第三个点的纵坐标。' },
  centroidX: { ko: '세 꼭짓점 가로 좌표의 평균. 무게중심의 x입니다.', en: 'The average of the three x values — the centroid’s x.', zh: '三个顶点横坐标的平均值，即重心的x。' },
  centroidY: { ko: '세 꼭짓점 세로 좌표의 평균. 무게중심의 y입니다.', en: 'The average of the three y values — the centroid’s y.', zh: '三个顶点纵坐标的平均值，即重心的y。' },
  shapeRatio: { ko: '가로를 세로로 나눈 값. 화면 비율과 같은 뜻입니다.', en: 'Width over height — the same idea as an aspect ratio.', zh: '宽除以高，与画面比例是同一概念。' },

  /* 입체 */
  frustumTop: { ko: '위쪽 원의 반지름. 아래와 다르면 원뿔대가 됩니다.', en: 'The radius of the top circle; differing from the bottom makes a frustum.', zh: '上底圆的半径；与下底不同即构成圆台。' },
  capHeight: { ko: '구 안에 물이 찬 높이. 바닥부터 잽니다.', en: 'How deep the sphere is filled, measured from the bottom.', zh: '球内充填的高度，自底部量起。' },
  capVolume: { ko: '그 높이까지 찬 부분의 부피.', en: 'The volume held up to that depth.', zh: '充到该高度所容纳的体积。' },
  fillPercent: { ko: '전체 부피 가운데 찬 비율.', en: 'The filled share of the total volume.', zh: '已充填部分占总体积的比例。' },
  bodyLen: { ko: '둥근 끝을 뺀 직선 부분의 길이.', en: 'The straight section, excluding the rounded ends.', zh: '不含两端圆头的直段长度。' },
  axisC: { ko: '타원체의 세 번째 반지름. 세 값이 같으면 구가 됩니다.', en: 'The ellipsoid’s third semi-axis; all three equal gives a sphere.', zh: '椭球的第三个半轴；三者相等即为球。' },
  baseArea: { ko: '바닥 한 면의 넓이.', en: 'The area of one base face.', zh: '底面一个面的面积。' },
  lateral: { ko: '바닥을 뺀 옆면만의 넓이. 라벨 크기가 이 값입니다.', en: 'The side surface only, without the bases — the size of a wraparound label.', zh: '不含底面的侧面面积，环绕标签的尺寸即为此值。' },

  /* 삼각비 */
  angleA: { ko: '변 a와 마주 보는 각.', en: 'The angle opposite side a.', zh: '与边a相对的角。' },
  angleB: { ko: '변 b와 마주 보는 각.', en: 'The angle opposite side b.', zh: '与边b相对的角。' },
  angleC: { ko: '변 c와 마주 보는 각. 세 각의 합은 180°입니다.', en: 'The angle opposite side c; the three add to 180°.', zh: '与边c相对的角；三角之和为180°。' },
  eyeHeight: { ko: '땅에서 눈까지의 높이. 마지막에 더해야 실제 높이가 됩니다.', en: 'Ground to eye; add it at the end for the true height.', zh: '地面到眼睛的高度，最后要加上才是实际高度。' },
  targetHeight: { ko: '재려는 대상의 전체 높이.', en: 'The full height of the object you are measuring.', zh: '所测目标物的总高度。' },
  z1: { ko: '첫 번째 점의 높이 좌표.', en: 'The height coordinate of the first point.', zh: '第一个点的高度坐标。' },
  z2: { ko: '두 번째 점의 높이 좌표.', en: 'The height coordinate of the second point.', zh: '第二个点的高度坐标。' },
  vecAx: { ko: '첫 번째 벡터의 가로 성분.', en: 'The horizontal component of the first vector.', zh: '第一个向量的横向分量。' },
  vecAy: { ko: '첫 번째 벡터의 세로 성분.', en: 'The vertical component of the first vector.', zh: '第一个向量的纵向分量。' },
  vecBx: { ko: '두 번째 벡터의 가로 성분.', en: 'The horizontal component of the second vector.', zh: '第二个向量的横向分量。' },
  vecBy: { ko: '두 번째 벡터의 세로 성분.', en: 'The vertical component of the second vector.', zh: '第二个向量的纵向分量。' },
  bearingDeg: { ko: '북쪽을 0°로 놓고 시계 방향으로 잰 각.', en: 'The angle clockwise from north, with north as zero.', zh: '以北为0°、按顺时针测得的角度。' },
  ratioVal: { ko: '각을 되짚을 삼각비 값. −1에서 1 사이입니다.', en: 'The trigonometric ratio to invert, between −1 and 1.', zh: '要反推角度的三角比值，取值在−1到1之间。' },
  ladderLen: { ko: '사다리 전체 길이. 펼친 상태로 잽니다.', en: 'The full length of the ladder, measured extended.', zh: '梯子的总长度，按展开状态量取。' },
  wallHeight: { ko: '사다리 끝이 벽에 닿는 높이.', en: 'How high up the wall the top of the ladder reaches.', zh: '梯顶在墙上搭到的高度。' },
  footDist: { ko: '사다리 발과 벽 사이의 거리.', en: 'The distance from the foot of the ladder to the wall.', zh: '梯脚到墙面的距离。' },
  polarR: { ko: '원점에서 점까지의 거리.', en: 'The distance from the origin to the point.', zh: '原点到该点的距离。' },
  polarTheta: { ko: 'x축 양의 방향에서 반시계로 잰 각.', en: 'The angle from the positive x-axis, counter-clockwise.', zh: '自x轴正方向按逆时针测得的角。' },
  cartX: { ko: '직교좌표로 바꾼 가로 위치.', en: 'The horizontal position in Cartesian form.', zh: '换算成直角坐标后的横向位置。' },
  cartY: { ko: '직교좌표로 바꾼 세로 위치.', en: 'The vertical position in Cartesian form.', zh: '换算成直角坐标后的纵向位置。' },

  /* 원·호 */
  sectorPerimeter: { ko: '호 하나와 반지름 두 개를 더한 부채꼴의 테두리.', en: 'One arc plus two radii — the whole edge of a sector.', zh: '一段弧加两条半径，即扇形的全部边界。' },
  sagitta: { ko: '현의 중간에서 호까지의 높이. 활이 부푼 정도입니다.', en: 'The height from the middle of the chord to the arc — how much it bulges.', zh: '从弦中点到弧的高度，即弓形鼓起的程度。' },
  pulleyA: { ko: '큰 쪽 풀리의 지름.', en: 'The diameter of the larger pulley.', zh: '较大皮带轮的直径。' },
  pulleyB: { ko: '작은 쪽 풀리의 지름.', en: 'The diameter of the smaller pulley.', zh: '较小皮带轮的直径。' },
  centerDist: { ko: '두 축 중심 사이의 거리.', en: 'The distance between the two shaft centres.', zh: '两轴中心之间的距离。' },
  beltLen: { ko: '두 풀리를 감아 도는 벨트의 전체 길이.', en: 'The total length of belt wrapping both pulleys.', zh: '绕过两轮的皮带总长度。' },
  pipeDia: { ko: '파이프 속이 빈 부분의 지름. 바깥지름이 아닙니다.', en: 'The inside diameter of the pipe, not the outside.', zh: '管道内部空腔的直径，不是外径。' },
  flowSpeed: { ko: '물이 파이프 속을 지나는 속도.', en: 'How fast the water moves through the pipe.', zh: '水在管内流动的速度。' },
  flowRate: { ko: '단위 시간에 흐르는 물의 부피.', en: 'The volume of water passing per unit of time.', zh: '单位时间内通过的水体积。' },
  smallDia: { ko: '안에 채워 넣을 작은 원의 지름.', en: 'The diameter of the small circles being packed in.', zh: '要填入的小圆的直径。' },
  fitCount: { ko: '빈틈을 감안해 실제로 들어가는 개수.', en: 'How many actually fit once the gaps are counted.', zh: '计入空隙后实际可容纳的数量。' },

  /* 생활 계산 */
  carpetArea: { ko: '손실을 더해 실제로 사야 하는 면적.', en: 'The area to actually buy, waste included.', zh: '计入损耗后实际需购买的面积。' },
  fenceLen: { ko: '울타리가 지나갈 전체 길이.', en: 'The total run the fence covers.', zh: '围栏所要覆盖的总长度。' },
  postGap: { ko: '기둥과 기둥 사이의 거리.', en: 'The spacing from one post to the next.', zh: '相邻立柱之间的距离。' },
  postCount: { ko: '양쪽 끝을 포함한 기둥의 개수. 칸보다 하나 많습니다.', en: 'Posts including both ends — one more than the spans.', zh: '含两端的立柱数量，比跨距数多一根。' },
  gravelDepth: { ko: '깔아 올릴 층의 두께.', en: 'How thick the layer will be laid.', zh: '铺设层的厚度。' },
  gravelWeight: { ko: '그 부피에 해당하는 무게. 자재는 무게로 팝니다.', en: 'The weight of that volume; materials are sold by weight.', zh: '该体积对应的重量；材料按重量销售。' },
  flowLpm: { ko: '수도에서 1분에 나오는 물의 양.', en: 'How many litres the tap delivers each minute.', zh: '水龙头每分钟出水的升数。' },
  fillHours: { ko: '그 유량으로 다 채우는 데 걸리는 시간.', en: 'How long filling takes at that flow rate.', zh: '按该流量注满所需的时间。' },
  boardWidth: { ko: '판재 한 장의 폭. 규격은 보통 90·120·140mm입니다.', en: 'The width of a single board; 90, 120 and 140 mm are common.', zh: '单块板材的宽度，常见规格为90、120、140毫米。' },
  boardCount: { ko: '깔아야 하는 판재의 줄 수.', en: 'How many runs of board you need to lay.', zh: '需要铺设的板材排数。' },
  windowWidth: { ko: '가릴 창의 폭. 커튼 봉 길이로 재는 편이 낫습니다.', en: 'The width to cover; measuring the pole is usually better.', zh: '需遮挡的窗宽，按窗帘杆长度测量更合适。' },
  pleatRatio: { ko: '창 폭의 몇 배로 원단을 쓰는지. 2가 표준입니다.', en: 'How many times the window width in fabric; 2 is standard.', zh: '用布量为窗宽的几倍，2为标准。' },
  fabricWidth: { ko: '주름을 잡기 위해 필요한 원단 폭.', en: 'The fabric width needed to hang in folds.', zh: '为形成褶皱所需的布幅宽度。' },
  potDia: { ko: '화분 입구의 지름. 화분 호수는 이 값으로 정해집니다.', en: 'The diameter across the pot’s rim, which is what pot sizes refer to.', zh: '花盆盆口的直径，花盆规格即按此标示。' },
  potDepth: { ko: '화분 안쪽 깊이. 겉높이보다 조금 작습니다.', en: 'The internal depth, a little less than the outside height.', zh: '花盆内部深度，略小于外部高度。' },
  soilL: { ko: '화분을 채우는 데 드는 배양토의 양.', en: 'How much compost the pot takes.', zh: '装满花盆所需的营养土量。' },
  brickW: { ko: '벽돌 한 장의 긴 쪽 길이.', en: 'The long side of one brick.', zh: '一块砖的长边长度。' },
  brickH: { ko: '벽돌 한 장의 높이.', en: 'The height of one brick.', zh: '一块砖的高度。' },
  brickCount: { ko: '줄눈과 손실을 감안한 벽돌 개수.', en: 'Bricks needed with mortar joints and waste counted.', zh: '计入灰缝与损耗后所需的砖数。' },
  cordVolume: { ko: '빈틈을 포함해 쌓인 장작의 부피.', en: 'The stacked volume of firewood, air gaps included.', zh: '含空隙在内的柴堆体积。' },
  cords: { ko: '장작 거래 단위. 1코드는 약 3.62㎥입니다.', en: 'The firewood trading unit; one cord is about 3.62 m³.', zh: '柴火交易单位，1 cord约3.62立方米。' },
  lotArea: { ko: '주차장으로 쓸 땅의 전체 면적.', en: 'The total area of land available for parking.', zh: '可用于停车的场地总面积。' },
  perSpace: { ko: '통로까지 포함한 1대당 필요 면적.', en: 'Area needed per car, aisles included.', zh: '含通道在内每辆车所需面积。' },
  spaceCount: { ko: '그 면적에 세울 수 있는 대수.', en: 'How many cars that area holds.', zh: '该面积可停放的车辆数。' },
  panelW: { ko: '패널 한 장의 가로 길이.', en: 'The width of one panel.', zh: '单块组件的宽度。' },
  panelH: { ko: '패널 한 장의 세로 길이.', en: 'The height of one panel.', zh: '单块组件的高度。' },
  panelCount: { ko: '지붕에 실제로 올릴 수 있는 패널 수.', en: 'How many panels the roof can actually take.', zh: '屋顶实际可安装的组件数量。' },
  panelKw: { ko: '패널 수와 출력을 곱한 설치 용량.', en: 'Panels times output — the installed capacity.', zh: '组件数乘功率所得的装机容量。' },
  rainMm: { ko: '내린 비의 깊이. 1mm는 1㎡에 1L입니다.', en: 'The depth of rain that fell; 1 mm is 1 L per square metre.', zh: '降雨的深度；1毫米相当于每平方米1升。' },
  harvestL: { ko: '손실을 뺀 뒤 실제로 받을 수 있는 물의 양.', en: 'The water you can actually collect after losses.', zh: '扣除损失后实际可收集的水量。' },
  pxWidth: { ko: '화면 가로 방향의 픽셀 수.', en: 'How many pixels across the screen.', zh: '屏幕横向的像素数。' },
  pxHeight: { ko: '화면 세로 방향의 픽셀 수.', en: 'How many pixels down the screen.', zh: '屏幕纵向的像素数。' },
  ppi: { ko: '1인치에 들어 있는 픽셀 수. 클수록 선명합니다.', en: 'Pixels packed into one inch; higher is sharper.', zh: '每英寸内的像素数，越大越清晰。' },
  itemW: { ko: '넣을 물건의 가로 길이.', en: 'The width of the item being packed.', zh: '待装物品的长度。' },
  itemH: { ko: '넣을 물건의 세로 길이.', en: 'The depth of the item being packed.', zh: '待装物品的宽度。' },
  itemD: { ko: '넣을 물건의 높이. 눕히면 이 값이 바뀝니다.', en: 'The height of the item; laying it down swaps this figure.', zh: '待装物品的高度；侧放时该数值会改变。' },
  boxCount: { ko: '한 방향으로 쌓았을 때 들어가는 개수.', en: 'How many fit when stacked in one orientation.', zh: '按同一朝向摆放时可装的数量。' },
  roofArea: { ko: '위에서 본 지붕의 수평 투영 면적.', en: 'The roof’s horizontal plan area, seen from above.', zh: '俯视所得屋顶的水平投影面积。' },
  extraPct: { ko: '깨짐과 재단 손실에 대비해 더 사는 비율.', en: 'The extra bought to cover breakage and offcuts.', zh: '为破损与切割损耗而多买的比例。' },
};

export const geo2Desc = (key: string, lang: Lang): string | null => GEO2_DESC[key]?.[lang] ?? null;
