/**
 * 도형 둘째 묶음 용어의 뜻풀이(3언어).
 *
 * 도형 용어는 이름이 비슷해서 서로 헷갈린다 — 모선과 높이, 내접원과 외접원,
 * 활 높이와 현. 무엇이 어디를 가리키는지 한 줄로 적어 두면 입력을 잘못 넣지 않는다.
 */
import type { Lang, Term } from './terms.ts';

export const GEO2_DESC: Record<string, Term> = {
  /* 평면 */
  sideSquare: { ko: '정사각형이나 정육면체의 한 모서리 길이.', en: 'One edge of a square or cube.' },
  heightTri: { ko: '밑변에서 수직으로 잰 높이. 비스듬한 변이 아닙니다.', en: 'The perpendicular height from the base, not a slanted side.' },
  inradius: { ko: '세 변에 모두 닿는 원의 반지름. 도형 안쪽에 있습니다.', en: 'Radius of the circle touching all sides, sitting inside the shape.' },
  circumradius: { ko: '모든 꼭짓점을 지나는 원의 반지름. 도형 바깥으로 감쌉니다.', en: 'Radius of the circle through every vertex, wrapping the shape.' },
  included: { ko: '두 변이 만나서 이루는 각. 다른 각을 넣으면 공식이 틀립니다.', en: 'The angle where the two sides meet; another angle breaks the formula.' },
  scaleFactor: { ko: '길이를 몇 배로 키우거나 줄이는지.', en: 'How many times you scale the lengths up or down.' },
  areaRatio: { ko: '길이가 k배가 될 때 면적이 늘어나는 배수. k의 제곱입니다.', en: 'How much area grows when length scales by k — k squared.' },
  volumeRatio: { ko: '길이가 k배가 될 때 부피가 늘어나는 배수. k의 세제곱입니다.', en: 'How much volume grows when length scales by k — k cubed.' },
  x3: { ko: '세 번째 점의 가로 좌표.', en: 'The horizontal coordinate of the third point.' },
  y3: { ko: '세 번째 점의 세로 좌표.', en: 'The vertical coordinate of the third point.' },
  centroidX: { ko: '세 꼭짓점 가로 좌표의 평균. 무게중심의 x입니다.', en: 'The average of the three x values — the centroid’s x.' },
  centroidY: { ko: '세 꼭짓점 세로 좌표의 평균. 무게중심의 y입니다.', en: 'The average of the three y values — the centroid’s y.' },
  shapeRatio: { ko: '가로를 세로로 나눈 값. 화면 비율과 같은 뜻입니다.', en: 'Width over height — the same idea as an aspect ratio.' },

  /* 입체 */
  frustumTop: { ko: '위쪽 원의 반지름. 아래와 다르면 원뿔대가 됩니다.', en: 'The radius of the top circle; differing from the bottom makes a frustum.' },
  capHeight: { ko: '구 안에 물이 찬 높이. 바닥부터 잽니다.', en: 'How deep the sphere is filled, measured from the bottom.' },
  capVolume: { ko: '그 높이까지 찬 부분의 부피.', en: 'The volume held up to that depth.' },
  fillPercent: { ko: '전체 부피 가운데 찬 비율.', en: 'The filled share of the total volume.' },
  bodyLen: { ko: '둥근 끝을 뺀 직선 부분의 길이.', en: 'The straight section, excluding the rounded ends.' },
  axisC: { ko: '타원체의 세 번째 반지름. 세 값이 같으면 구가 됩니다.', en: 'The ellipsoid’s third semi-axis; all three equal gives a sphere.' },
  baseArea: { ko: '바닥 한 면의 넓이.', en: 'The area of one base face.' },
  lateral: { ko: '바닥을 뺀 옆면만의 넓이. 라벨 크기가 이 값입니다.', en: 'The side surface only, without the bases — the size of a wraparound label.' },

  /* 삼각비 */
  angleA: { ko: '변 a와 마주 보는 각.', en: 'The angle opposite side a.' },
  angleB: { ko: '변 b와 마주 보는 각.', en: 'The angle opposite side b.' },
  angleC: { ko: '변 c와 마주 보는 각. 세 각의 합은 180°입니다.', en: 'The angle opposite side c; the three add to 180°.' },
  eyeHeight: { ko: '땅에서 눈까지의 높이. 마지막에 더해야 실제 높이가 됩니다.', en: 'Ground to eye; add it at the end for the true height.' },
  targetHeight: { ko: '재려는 대상의 전체 높이.', en: 'The full height of the object you are measuring.' },
  z1: { ko: '첫 번째 점의 높이 좌표.', en: 'The height coordinate of the first point.' },
  z2: { ko: '두 번째 점의 높이 좌표.', en: 'The height coordinate of the second point.' },
  vecAx: { ko: '첫 번째 벡터의 가로 성분.', en: 'The horizontal component of the first vector.' },
  vecAy: { ko: '첫 번째 벡터의 세로 성분.', en: 'The vertical component of the first vector.' },
  vecBx: { ko: '두 번째 벡터의 가로 성분.', en: 'The horizontal component of the second vector.' },
  vecBy: { ko: '두 번째 벡터의 세로 성분.', en: 'The vertical component of the second vector.' },
  bearingDeg: { ko: '북쪽을 0°로 놓고 시계 방향으로 잰 각.', en: 'The angle clockwise from north, with north as zero.' },
  ratioVal: { ko: '각을 되짚을 삼각비 값. −1에서 1 사이입니다.', en: 'The trigonometric ratio to invert, between −1 and 1.' },
  ladderLen: { ko: '사다리 전체 길이. 펼친 상태로 잽니다.', en: 'The full length of the ladder, measured extended.' },
  wallHeight: { ko: '사다리 끝이 벽에 닿는 높이.', en: 'How high up the wall the top of the ladder reaches.' },
  footDist: { ko: '사다리 발과 벽 사이의 거리.', en: 'The distance from the foot of the ladder to the wall.' },
  polarR: { ko: '원점에서 점까지의 거리.', en: 'The distance from the origin to the point.' },
  polarTheta: { ko: 'x축 양의 방향에서 반시계로 잰 각.', en: 'The angle from the positive x-axis, counter-clockwise.' },
  cartX: { ko: '직교좌표로 바꾼 가로 위치.', en: 'The horizontal position in Cartesian form.' },
  cartY: { ko: '직교좌표로 바꾼 세로 위치.', en: 'The vertical position in Cartesian form.' },

  /* 원·호 */
  sectorPerimeter: { ko: '호 하나와 반지름 두 개를 더한 부채꼴의 테두리.', en: 'One arc plus two radii — the whole edge of a sector.' },
  sagitta: { ko: '현의 중간에서 호까지의 높이. 활이 부푼 정도입니다.', en: 'The height from the middle of the chord to the arc — how much it bulges.' },
  pulleyA: { ko: '큰 쪽 풀리의 지름.', en: 'The diameter of the larger pulley.' },
  pulleyB: { ko: '작은 쪽 풀리의 지름.', en: 'The diameter of the smaller pulley.' },
  centerDist: { ko: '두 축 중심 사이의 거리.', en: 'The distance between the two shaft centres.' },
  beltLen: { ko: '두 풀리를 감아 도는 벨트의 전체 길이.', en: 'The total length of belt wrapping both pulleys.' },
  pipeDia: { ko: '파이프 속이 빈 부분의 지름. 바깥지름이 아닙니다.', en: 'The inside diameter of the pipe, not the outside.' },
  flowSpeed: { ko: '물이 파이프 속을 지나는 속도.', en: 'How fast the water moves through the pipe.' },
  flowRate: { ko: '단위 시간에 흐르는 물의 부피.', en: 'The volume of water passing per unit of time.' },
  smallDia: { ko: '안에 채워 넣을 작은 원의 지름.', en: 'The diameter of the small circles being packed in.' },
  fitCount: { ko: '빈틈을 감안해 실제로 들어가는 개수.', en: 'How many actually fit once the gaps are counted.' },

  /* 생활 계산 */
  carpetArea: { ko: '손실을 더해 실제로 사야 하는 면적.', en: 'The area to actually buy, waste included.' },
  fenceLen: { ko: '울타리가 지나갈 전체 길이.', en: 'The total run the fence covers.' },
  postGap: { ko: '기둥과 기둥 사이의 거리.', en: 'The spacing from one post to the next.' },
  postCount: { ko: '양쪽 끝을 포함한 기둥의 개수. 칸보다 하나 많습니다.', en: 'Posts including both ends — one more than the spans.' },
  gravelDepth: { ko: '깔아 올릴 층의 두께.', en: 'How thick the layer will be laid.' },
  gravelWeight: { ko: '그 부피에 해당하는 무게. 자재는 무게로 팝니다.', en: 'The weight of that volume; materials are sold by weight.' },
  flowLpm: { ko: '수도에서 1분에 나오는 물의 양.', en: 'How many litres the tap delivers each minute.' },
  fillHours: { ko: '그 유량으로 다 채우는 데 걸리는 시간.', en: 'How long filling takes at that flow rate.' },
  boardWidth: { ko: '판재 한 장의 폭. 규격은 보통 90·120·140mm입니다.', en: 'The width of a single board; 90, 120 and 140 mm are common.' },
  boardCount: { ko: '깔아야 하는 판재의 줄 수.', en: 'How many runs of board you need to lay.' },
  windowWidth: { ko: '가릴 창의 폭. 커튼 봉 길이로 재는 편이 낫습니다.', en: 'The width to cover; measuring the pole is usually better.' },
  pleatRatio: { ko: '창 폭의 몇 배로 원단을 쓰는지. 2가 표준입니다.', en: 'How many times the window width in fabric; 2 is standard.' },
  fabricWidth: { ko: '주름을 잡기 위해 필요한 원단 폭.', en: 'The fabric width needed to hang in folds.' },
  potDia: { ko: '화분 입구의 지름. 화분 호수는 이 값으로 정해집니다.', en: 'The diameter across the pot’s rim, which is what pot sizes refer to.' },
  potDepth: { ko: '화분 안쪽 깊이. 겉높이보다 조금 작습니다.', en: 'The internal depth, a little less than the outside height.' },
  soilL: { ko: '화분을 채우는 데 드는 배양토의 양.', en: 'How much compost the pot takes.' },
  brickW: { ko: '벽돌 한 장의 긴 쪽 길이.', en: 'The long side of one brick.' },
  brickH: { ko: '벽돌 한 장의 높이.', en: 'The height of one brick.' },
  brickCount: { ko: '줄눈과 손실을 감안한 벽돌 개수.', en: 'Bricks needed with mortar joints and waste counted.' },
  cordVolume: { ko: '빈틈을 포함해 쌓인 장작의 부피.', en: 'The stacked volume of firewood, air gaps included.' },
  cords: { ko: '장작 거래 단위. 1코드는 약 3.62㎥입니다.', en: 'The firewood trading unit; one cord is about 3.62 m³.' },
  lotArea: { ko: '주차장으로 쓸 땅의 전체 면적.', en: 'The total area of land available for parking.' },
  perSpace: { ko: '통로까지 포함한 1대당 필요 면적.', en: 'Area needed per car, aisles included.' },
  spaceCount: { ko: '그 면적에 세울 수 있는 대수.', en: 'How many cars that area holds.' },
  panelW: { ko: '패널 한 장의 가로 길이.', en: 'The width of one panel.' },
  panelH: { ko: '패널 한 장의 세로 길이.', en: 'The height of one panel.' },
  panelCount: { ko: '지붕에 실제로 올릴 수 있는 패널 수.', en: 'How many panels the roof can actually take.' },
  panelKw: { ko: '패널 수와 출력을 곱한 설치 용량.', en: 'Panels times output — the installed capacity.' },
  rainMm: { ko: '내린 비의 깊이. 1mm는 1㎡에 1L입니다.', en: 'The depth of rain that fell; 1 mm is 1 L per square metre.' },
  harvestL: { ko: '손실을 뺀 뒤 실제로 받을 수 있는 물의 양.', en: 'The water you can actually collect after losses.' },
  pxWidth: { ko: '화면 가로 방향의 픽셀 수.', en: 'How many pixels across the screen.' },
  pxHeight: { ko: '화면 세로 방향의 픽셀 수.', en: 'How many pixels down the screen.' },
  ppi: { ko: '1인치에 들어 있는 픽셀 수. 클수록 선명합니다.', en: 'Pixels packed into one inch; higher is sharper.' },
  itemW: { ko: '넣을 물건의 가로 길이.', en: 'The width of the item being packed.' },
  itemH: { ko: '넣을 물건의 세로 길이.', en: 'The depth of the item being packed.' },
  itemD: { ko: '넣을 물건의 높이. 눕히면 이 값이 바뀝니다.', en: 'The height of the item; laying it down swaps this figure.' },
  boxCount: { ko: '한 방향으로 쌓았을 때 들어가는 개수.', en: 'How many fit when stacked in one orientation.' },
  roofArea: { ko: '위에서 본 지붕의 수평 투영 면적.', en: 'The roof’s horizontal plan area, seen from above.' },
  extraPct: { ko: '깨짐과 재단 손실에 대비해 더 사는 비율.', en: 'The extra bought to cover breakage and offcuts.' },
};

export const geo2Desc = (key: string, lang: Lang): string | null => GEO2_DESC[key]?.[lang] ?? null;
