/**
 * 비율 섹션에서 더 쓰는 용어(3언어).
 *
 * terms.ts의 CORE_TERMS는 세 섹션이 함께 쓰는 것만 둔다. 비율 100종으로 늘리며
 * 생긴 용어는 여기 모아 둔다 — 한 파일이 삼백 줄을 넘으면 무엇이 어디 쓰이는지
 * 안 보인다.
 */
import type { Term } from './terms.ts';

export const RATE_TERMS: Record<string, Term> = {
  /* 할인·가격 */
  freeCount: { ko: '무료 개수', en: 'Free items', zh: '赠送数量' },
  payCount: { ko: '사는 개수', en: 'Items paid for', zh: '付费数量' },
  effDiscount: { ko: '실질 할인율', en: 'Real discount', zh: '实际折扣率' },
  unitPrice: { ko: '개당 가격', en: 'Price each', zh: '单个价格' },
  costPerUse: { ko: '1회당 비용', en: 'Cost per use', zh: '单次成本' },
  costPerMonth: { ko: '한 달당 비용', en: 'Cost a month', zh: '每月成本' },
  costPerDay: { ko: '하루당 비용', en: 'Cost a day', zh: '每天成本' },
  saveAmt: { ko: '절약액', en: 'Saved', zh: '节省金额' },
  shipFee: { ko: '배송비', en: 'Shipping', zh: '运费' },
  freeShipMin: { ko: '무료배송 기준', en: 'Free-shipping threshold', zh: '免运门槛' },
  addBuy: { ko: '더 담을 금액', en: 'Add to basket', zh: '还需加购' },
  annualFee: { ko: '연회비', en: 'Annual fee', zh: '年费' },
  memberPrice: { ko: '회원가', en: 'Member price', zh: '会员价' },
  breakEvenCount: { ko: '본전 되는 횟수', en: 'Break-even uses', zh: '回本次数' },
  baseRate: { ko: '기준 환율', en: 'Mid-market rate', zh: '基准汇率' },
  appliedRate: { ko: '적용 환율', en: 'Rate you got', zh: '实际汇率' },
  spread: { ko: '환전 스프레드', en: 'Spread', zh: '汇率差' },
  buyPrice: { ko: '구매가', en: 'Purchase price', zh: '购入价' },
  depreciation: { ko: '연 감가율', en: 'Yearly depreciation', zh: '年折旧率' },
  nowValue: { ko: '현재 가치', en: 'Value now', zh: '当前价值' },
  minMargin: { ko: '지킬 이익률', en: 'Margin floor', zh: '保底利润率' },
  maxDiscount: { ko: '최대 할인율', en: 'Discount ceiling', zh: '最大折扣率' },

  /* 세금·정산 */
  taxRate: { ko: '세율', en: 'Tax rate', zh: '税率' },
  taxFreeRate: { ko: '비과세 수익률', en: 'Tax-free rate', zh: '免税收益率' },
  equivYield: { ko: '등가 과세 수익률', en: 'Equivalent taxable rate', zh: '等效应税收益率' },
  serviceRate: { ko: '서비스료', en: 'Service charge', zh: '服务费率' },
  feeRateA: { ko: '수수료 A', en: 'First fee', zh: '手续费A' },
  feeRateB: { ko: '수수료 B', en: 'Second fee', zh: '手续费B' },
  totalDays: { ko: '전체 일수', en: 'Days in term', zh: '总天数' },
  usedDays: { ko: '쓴 일수', en: 'Days used', zh: '已用天数' },
  refundAmt: { ko: '환불액', en: 'Refund', zh: '退款金额' },
  goodsPrice: { ko: '물품 가격', en: 'Item price', zh: '货物价格' },
  dutyRate: { ko: '관세율', en: 'Duty rate', zh: '关税率' },
  landedCost: { ko: '총 수입 비용', en: 'Landed cost', zh: '到岸总成本' },
  dutyFreeLimit: { ko: '면세 한도', en: 'Duty-free allowance', zh: '免税额度' },
  taxableAmt: { ko: '과세 대상액', en: 'Taxable amount', zh: '应税金额' },
  workHours: { ko: '월 근무시간', en: 'Hours a month', zh: '每月工时' },
  hourlyNet: { ko: '세후 시급', en: 'Take-home hourly', zh: '税后时薪' },

  /* 비율·증감 */
  outerPct: { ko: '바깥 비율', en: 'Outer share', zh: '外层比例' },
  innerPct: { ko: '안쪽 비율', en: 'Inner share', zh: '内层比例' },
  netPercent: { ko: '전체 대비', en: 'Of the whole', zh: '占整体比例' },
  changeA: { ko: '1차 변화율', en: 'First change', zh: '第一次变化' },
  changeB: { ko: '2차 변화율', en: 'Second change', zh: '第二次变化' },
  trueVal: { ko: '참값', en: 'True value', zh: '真值' },
  measured: { ko: '측정값', en: 'Measured value', zh: '测量值' },
  errorPct: { ko: '오차율', en: 'Error', zh: '误差率' },
  startVal: { ko: '시작 값', en: 'Starting value', zh: '起始值' },
  endVal: { ko: '목표 값', en: 'Ending value', zh: '目标值' },
  neededRate: { ko: '필요 연 성장률', en: 'Growth needed', zh: '所需年增长率' },
  rankNo: { ko: '내 순위', en: 'Your rank', zh: '名次' },
  totalPeople: { ko: '전체 인원', en: 'Total people', zh: '总人数' },
  topPercent: { ko: '상위 비율', en: 'Top percentage', zh: '前百分之几' },
  ratioC: { ko: 'C', en: 'C', zh: 'C' },
  shareC: { ko: 'C의 몫', en: "C's share", zh: 'C的份额' },
  permille: { ko: '천분율(‰)', en: 'Per mille (‰)', zh: '千分率(‰)' },
  workers: { ko: '사람 수', en: 'Workers', zh: '人数' },
  daysNeeded: { ko: '걸리는 일수', en: 'Days needed', zh: '所需天数' },
  usedAmt: { ko: '쓴 양', en: 'Used', zh: '已用量' },
  remainPct: { ko: '남은 비율', en: 'Left', zh: '剩余比例' },
  relDiff: { ko: '상대 차이', en: 'Relative gap', zh: '相对差异' },
  indexVal: { ko: '지수', en: 'Index', zh: '指数' },

  /* 금융·이자 */
  goalAmount: { ko: '목표 금액', en: 'Goal amount', zh: '目标金额' },
  neededMonthly: { ko: '필요 월 납입', en: 'Monthly needed', zh: '每月需存' },
  monthsNeeded: { ko: '걸리는 개월', en: 'Months needed', zh: '所需月数' },
  futureAmt: { ko: '미래 금액', en: 'Future amount', zh: '未来金额' },
  presentAmt: { ko: '현재 가치', en: 'Present value', zh: '现值' },
  discountRate: { ko: '할인율(연)', en: 'Discount rate', zh: '折现率' },
  affordPay: { ko: '월 상환 여력', en: 'Payment you can manage', zh: '每月可还款额' },
  maxLoan: { ko: '빌릴 수 있는 금액', en: 'Borrowing limit', zh: '可贷金额' },
  prepayAmt: { ko: '중도상환액', en: 'Extra payment', zh: '提前还款额' },
  savedInterest: { ko: '아끼는 이자', en: 'Interest saved', zh: '节省利息' },
  days: { ko: '일수', en: 'Days', zh: '天数' },
  dailyInterest: { ko: '하루 이자', en: 'Interest a day', zh: '每日利息' },
  firstPrincipal: { ko: '첫 달 원금', en: 'Principal in month 1', zh: '首月本金' },
  firstInterest: { ko: '첫 달 이자', en: 'Interest in month 1', zh: '首月利息' },
  installMonths: { ko: '할부 개월', en: 'Instalments', zh: '分期月数' },
  installFee: { ko: '할부 수수료율', en: 'Instalment fee', zh: '分期费率' },
  apr: { ko: '실질 연이율', en: 'Effective APR', zh: '实际年利率' },
  futurePrice: { ko: '미래 가격', en: 'Price later', zh: '未来价格' },
  buyPriceA: { ko: '1차 매수가', en: 'First buy price', zh: '首次买入价' },
  buyQtyA: { ko: '1차 수량', en: 'First quantity', zh: '首次数量' },
  buyPriceB: { ko: '2차 매수가', en: 'Second buy price', zh: '二次买入价' },
  buyQtyB: { ko: '2차 수량', en: 'Second quantity', zh: '二次数量' },
  avgPrice: { ko: '평균 단가', en: 'Average price', zh: '平均成本' },
  totalQty: { ko: '총 수량', en: 'Total quantity', zh: '总数量' },
  feeRate: { ko: '왕복 수수료', en: 'Round-trip fee', zh: '往返手续费' },
  needReturn: { ko: '본전 수익률', en: 'Return to break even', zh: '回本收益率' },
  monthlySpend: { ko: '월 생활비', en: 'Monthly spend', zh: '每月支出' },
  fundMonths: { ko: '버틸 개월', en: 'Months of cover', zh: '可支撑月数' },
  fundAmount: { ko: '필요 비상금', en: 'Fund needed', zh: '所需应急金' },
  savedSoFar: { ko: '지금 모은 금액', en: 'Saved so far', zh: '目前已存' },
  faceValue: { ko: '액면 금액', en: 'Face value', zh: '面值' },
  couponRate: { ko: '표면 금리', en: 'Coupon rate', zh: '票面利率' },
  currentYield: { ko: '현재 수익률', en: 'Current yield', zh: '当期收益率' },

  /* 농도·배합 */
  origAbv: { ko: '원래 도수', en: 'Starting strength', zh: '原始度数' },
  targetAbv: { ko: '목표 도수', en: 'Target strength', zh: '目标度数' },
  waterAddMl: { ko: '넣을 물(ml)', en: 'Water to add (mL)', zh: '需加水(毫升)' },
  syrupPart: { ko: '시럽 몫', en: 'Syrup parts', zh: '糖浆份' },
  waterPart: { ko: '물 몫', en: 'Water parts', zh: '水份' },
  syrupMl: { ko: '시럽(ml)', en: 'Syrup (mL)', zh: '糖浆(毫升)' },
  amountA: { ko: 'A의 양', en: 'Amount of A', zh: 'A的用量' },
  amountB: { ko: 'B의 양', en: 'Amount of B', zh: 'B的用量' },
  evapMl: { ko: '졸일 물', en: 'Water to boil off', zh: '需蒸发的水' },
  stockPct: { ko: '원액 농도', en: 'Stock strength', zh: '原液浓度' },
  targetPpm: { ko: '목표 ppm', en: 'Target ppm', zh: '目标ppm' },
  stockNeedMl: { ko: '필요 원액', en: 'Stock needed', zh: '所需原液' },
  mainMl: { ko: '주제(ml)', en: 'Base (mL)', zh: '主剂(毫升)' },
  hardenerMl: { ko: '경화제(ml)', en: 'Hardener (mL)', zh: '固化剂(毫升)' },

  /* 점수·달성 */
  currentAvg: { ko: '현재 평균', en: 'Average so far', zh: '目前平均' },
  targetAvg: { ko: '목표 평균', en: 'Average wanted', zh: '目标平均' },
  examsDone: { ko: '치른 과목 수', en: 'Tests taken', zh: '已考科目数' },
  examsLeft: { ko: '남은 과목 수', en: 'Tests left', zh: '剩余科目数' },
  neededScore: { ko: '받아야 할 점수', en: 'Score needed', zh: '所需分数' },
  midScore: { ko: '중간 점수', en: 'Midterm score', zh: '期中分数' },
  finalScoreV: { ko: '기말 점수', en: 'Final score', zh: '期末分数' },
  hwScore: { ko: '과제 점수', en: 'Coursework score', zh: '作业分数' },
  midWeight: { ko: '중간 비중', en: 'Midterm weight', zh: '期中权重' },
  finalWeight: { ko: '기말 비중', en: 'Final weight', zh: '期末权重' },
  weightedScore: { ko: '가중 총점', en: 'Weighted total', zh: '加权总分' },
  passScore: { ko: '합격선', en: 'Pass mark', zh: '合格线' },
  gapScore: { ko: '남은 점수', en: 'Points short', zh: '还差分数' },
  daysLeft: { ko: '남은 일수', en: 'Days left', zh: '剩余天数' },
  perDay: { ko: '하루에 할 양', en: 'Per day', zh: '每天需完成' },
};

export const RATE_UNITS: Record<string, Term> = {
  piece: { ko: '개', en: '', zh: '个' },
  day: { ko: '일', en: 'd', zh: '天' },
  hour: { ko: '시간', en: 'h', zh: '小时' },
  point: { ko: '점', en: 'pt', zh: '分' },
  permille: { ko: '‰', en: '‰', zh: '‰' },
};
