/**
 * 도형 100종으로 늘리며 생긴 용어(3언어).
 */
import type { Term } from './terms.ts';

export const GEO2_TERMS: Record<string, Term> = {
  /* 평면 */
  sideSquare: { ko: '한 변', en: 'Side', zh: '边长' },
  inradius: { ko: '내접원 반지름', en: 'Inradius', zh: '内切圆半径' },
  circumradius: { ko: '외접원 반지름', en: 'Circumradius', zh: '外接圆半径' },
  scaleFactor: { ko: '닮음비', en: 'Scale factor', zh: '相似比' },
  areaRatio: { ko: '면적비', en: 'Area ratio', zh: '面积比' },
  volumeRatio: { ko: '부피비', en: 'Volume ratio', zh: '体积比' },
  x3: { ko: 'x₃', en: 'x₃', zh: 'x₃' },
  y3: { ko: 'y₃', en: 'y₃', zh: 'y₃' },
  centroidX: { ko: '무게중심 x', en: 'Centroid x', zh: '重心x' },
  centroidY: { ko: '무게중심 y', en: 'Centroid y', zh: '重心y' },
  included: { ko: '끼인각', en: 'Included angle', zh: '夹角' },
  heightTri: { ko: '높이', en: 'Height', zh: '高' },

  /* 입체 */
  frustumTop: { ko: '위쪽 반지름', en: 'Top radius', zh: '上底半径' },
  capHeight: { ko: '채운 높이', en: 'Fill height', zh: '充填高度' },
  capVolume: { ko: '채운 부피', en: 'Filled volume', zh: '充填体积' },
  fillPercent: { ko: '채운 비율', en: 'Fill share', zh: '充填比例' },
  bodyLen: { ko: '몸통 길이', en: 'Body length', zh: '筒身长度' },
  axisC: { ko: '세 번째 반지름', en: 'Third radius', zh: '第三半轴' },
  baseArea: { ko: '밑면 넓이', en: 'Base area', zh: '底面积' },
  lateral: { ko: '옆면 넓이', en: 'Lateral area', zh: '侧面积' },

  /* 삼각비 */
  angleB: { ko: '각 B', en: 'Angle B', zh: '角B' },
  angleC: { ko: '각 C', en: 'Angle C', zh: '角C' },
  angleA: { ko: '각 A', en: 'Angle A', zh: '角A' },
  eyeHeight: { ko: '눈높이', en: 'Eye height', zh: '视线高度' },
  targetHeight: { ko: '대상 높이', en: 'Object height', zh: '目标高度' },
  z1: { ko: 'z₁', en: 'z₁', zh: 'z₁' },
  z2: { ko: 'z₂', en: 'z₂', zh: 'z₂' },
  vecAx: { ko: 'A의 x', en: 'A.x', zh: 'A的x' },
  vecAy: { ko: 'A의 y', en: 'A.y', zh: 'A的y' },
  vecBx: { ko: 'B의 x', en: 'B.x', zh: 'B的x' },
  vecBy: { ko: 'B의 y', en: 'B.y', zh: 'B的y' },
  bearingDeg: { ko: '방위각', en: 'Bearing', zh: '方位角' },
  ratioVal: { ko: '삼각비 값', en: 'Ratio', zh: '三角比值' },
  ladderLen: { ko: '사다리 길이', en: 'Ladder length', zh: '梯子长度' },
  wallHeight: { ko: '닿는 높이', en: 'Height reached', zh: '搭到的高度' },
  footDist: { ko: '벽에서 거리', en: 'Distance from wall', zh: '距墙距离' },
  polarR: { ko: '반지름 r', en: 'Radius r', zh: '半径r' },
  polarTheta: { ko: '각 θ', en: 'Angle θ', zh: '角θ' },
  cartX: { ko: 'x 좌표', en: 'x', zh: 'x坐标' },
  cartY: { ko: 'y 좌표', en: 'y', zh: 'y坐标' },

  /* 원·호 */
  sectorPerimeter: { ko: '부채꼴 둘레', en: 'Sector perimeter', zh: '扇形周长' },
  sagitta: { ko: '활 높이', en: 'Sagitta', zh: '弓高' },
  pulleyA: { ko: '풀리 A 지름', en: 'Pulley A diameter', zh: '皮带轮A直径' },
  pulleyB: { ko: '풀리 B 지름', en: 'Pulley B diameter', zh: '皮带轮B直径' },
  centerDist: { ko: '축간 거리', en: 'Centre distance', zh: '轴间距' },
  beltLen: { ko: '벨트 길이', en: 'Belt length', zh: '皮带长度' },
  pipeDia: { ko: '파이프 안지름', en: 'Pipe bore', zh: '管内径' },
  flowSpeed: { ko: '유속(m/s)', en: 'Flow speed (m/s)', zh: '流速(米/秒)' },
  flowRate: { ko: '유량', en: 'Flow rate', zh: '流量' },
  smallDia: { ko: '작은 원 지름', en: 'Small circle diameter', zh: '小圆直径' },
  fitCount: { ko: '들어가는 개수', en: 'How many fit', zh: '可容纳数量' },

  /* 생활 계산 */
  carpetArea: { ko: '필요 면적', en: 'Area needed', zh: '所需面积' },
  fenceLen: { ko: '울타리 길이', en: 'Fence length', zh: '围栏长度' },
  postGap: { ko: '기둥 간격', en: 'Post spacing', zh: '立柱间距' },
  postCount: { ko: '기둥 개수', en: 'Posts needed', zh: '立柱数量' },
  gravelDepth: { ko: '깔 두께', en: 'Layer depth', zh: '铺设厚度' },
  gravelWeight: { ko: '자갈 무게', en: 'Gravel weight', zh: '砾石重量' },
  fillHours: { ko: '채우는 시간', en: 'Time to fill', zh: '充满所需时间' },
  flowLpm: { ko: '수압(L/분)', en: 'Flow (L/min)', zh: '水流(升/分)' },
  boardWidth: { ko: '판재 폭', en: 'Board width', zh: '板宽' },
  boardCount: { ko: '판재 개수', en: 'Boards needed', zh: '所需板数' },
  windowWidth: { ko: '창 폭', en: 'Window width', zh: '窗宽' },
  pleatRatio: { ko: '주름 배율', en: 'Fullness ratio', zh: '褶皱倍率' },
  fabricWidth: { ko: '필요 원단 폭', en: 'Fabric width needed', zh: '所需布幅' },
  potDia: { ko: '화분 지름', en: 'Pot diameter', zh: '花盆直径' },
  potDepth: { ko: '화분 깊이', en: 'Pot depth', zh: '花盆深度' },
  soilL: { ko: '필요 흙', en: 'Soil needed', zh: '所需土量' },
  brickW: { ko: '벽돌 길이(cm)', en: 'Brick length (cm)', zh: '砖长(厘米)' },
  brickH: { ko: '벽돌 높이(cm)', en: 'Brick height (cm)', zh: '砖高(厘米)' },
  brickCount: { ko: '벽돌 개수', en: 'Bricks needed', zh: '所需砖数' },
  cordVolume: { ko: '장작 부피', en: 'Firewood volume', zh: '柴堆体积' },
  cords: { ko: '코드 수', en: 'Cords', zh: '柴堆单位' },
  lotArea: { ko: '부지 면적', en: 'Lot area', zh: '场地面积' },
  perSpace: { ko: '1대당 면적', en: 'Area per car', zh: '每车位面积' },
  spaceCount: { ko: '주차 대수', en: 'Parking spaces', zh: '车位数' },
  panelW: { ko: '패널 가로(m)', en: 'Panel width (m)', zh: '组件宽(米)' },
  panelH: { ko: '패널 세로(m)', en: 'Panel height (m)', zh: '组件高(米)' },
  panelCount: { ko: '패널 개수', en: 'Panels', zh: '组件数量' },
  panelKw: { ko: '설치 용량', en: 'Installed capacity', zh: '装机容量' },
  rainMm: { ko: '강수량(mm)', en: 'Rainfall (mm)', zh: '降雨量(毫米)' },
  harvestL: { ko: '모이는 물', en: 'Water collected', zh: '可收集水量' },
  pxWidth: { ko: '가로 픽셀', en: 'Width in pixels', zh: '横向像素' },
  pxHeight: { ko: '세로 픽셀', en: 'Height in pixels', zh: '纵向像素' },
  ppi: { ko: '픽셀 밀도(ppi)', en: 'Pixel density (ppi)', zh: '像素密度(ppi)' },
  itemW: { ko: '물건 가로', en: 'Item width', zh: '物品长' },
  itemH: { ko: '물건 세로', en: 'Item depth', zh: '物品宽' },
  itemD: { ko: '물건 높이', en: 'Item height', zh: '物品高' },
  boxCount: { ko: '들어가는 개수', en: 'Items that fit', zh: '可装数量' },
};

export const GEO2_UNITS: Record<string, Term> = {
  deg: { ko: '°', en: '°', zh: '°' },
  liter: { ko: 'L', en: 'L', zh: '升' },
  ton: { ko: 't', en: 't', zh: '吨' },
  kw: { ko: 'kW', en: 'kW', zh: '千瓦' },
  ppiU: { ko: 'ppi', en: 'ppi', zh: 'ppi' },
  px: { ko: 'px', en: 'px', zh: '像素' },
  m3: { ko: '㎥', en: 'm³', zh: '立方米' },
  lpm: { ko: 'L/분', en: 'L/min', zh: '升/分' },
  mm: { ko: 'mm', en: 'mm', zh: '毫米' },
};
