/** 도형·수학 도구가 쓰는 용어 — 핵심 사전(terms.ts)에 합쳐진다 */
import type { Term } from './terms.ts';

export const GEO_TERMS: Record<string, Term> = {
  radius:       { ko: '반지름',      en: 'Radius' },
  radius2:      { ko: '작은 반지름', en: 'Inner radius' },
  diameter:     { ko: '지름',        en: 'Diameter' },
  circumference:{ ko: '둘레',        en: 'Circumference' },
  area:         { ko: '면적',        en: 'Area' },
  perimeter:    { ko: '둘레',        en: 'Perimeter' },
  baseLen:      { ko: '밑변',        en: 'Base' },
  baseTop:      { ko: '윗변',        en: 'Top edge' },
  heightGeo:    { ko: '높이',        en: 'Height' },
  sideLen:      { ko: '한 변',       en: 'Side length' },
  sideCount:    { ko: '변의 수',     en: 'Number of sides' },
  sideA:        { ko: '변 a',        en: 'Side a' },
  sideB:        { ko: '변 b',        en: 'Side b' },
  sideC:        { ko: '변 c',        en: 'Side c' },
  hypotenuse:   { ko: '빗변',        en: 'Hypotenuse' },
  diagonal1:    { ko: '대각선 1',    en: 'Diagonal 1' },
  diagonal2:    { ko: '대각선 2',    en: 'Diagonal 2' },
  diagonal:     { ko: '대각선',      en: 'Diagonal' },
  axisA:        { ko: '장반경',      en: 'Semi-major axis' },
  axisB:        { ko: '단반경',      en: 'Semi-minor axis' },
  angleDeg:     { ko: '각도(°)',     en: 'Angle (°)' },
  angleRad:     { ko: '라디안',      en: 'Radians' },
  innerAngle:   { ko: '한 내각',     en: 'Interior angle' },
  outerAngle:   { ko: '한 외각',     en: 'Exterior angle' },
  angleSum:     { ko: '내각의 합',   en: 'Sum of angles' },
  arcLen:       { ko: '호의 길이',   en: 'Arc length' },
  chordLen:     { ko: '현의 길이',   en: 'Chord length' },

  volume:       { ko: '부피',        en: 'Volume' },
  surface:      { ko: '표면적',      en: 'Surface area' },
  sideSurface:  { ko: '옆면적',      en: 'Lateral area' },
  slant:        { ko: '모선',        en: 'Slant height' },
  lengthCm:     { ko: '가로',        en: 'Length' },
  widthCm:      { ko: '세로',        en: 'Width' },
  depthCm:      { ko: '깊이',        en: 'Depth' },
  liters:       { ko: '용량(L)',     en: 'Litres' },
  weightT:      { ko: '무게',        en: 'Weight' },

  sinVal:       { ko: 'sin',         en: 'sin' },
  cosVal:       { ko: 'cos',         en: 'cos' },
  tanVal:       { ko: 'tan',         en: 'tan' },
  slopePct:     { ko: '경사도(%)',   en: 'Grade (%)' },
  riseLen:      { ko: '수직 높이',   en: 'Rise' },
  runLen:       { ko: '수평 거리',   en: 'Run' },
  x1: { ko: 'x₁', en: 'x₁' },
  y1: { ko: 'y₁', en: 'y₁' },
  x2: { ko: 'x₂', en: 'x₂' },
  y2: { ko: 'y₂', en: 'y₂' },
  distance:     { ko: '거리',        en: 'Distance' },
  midX:         { ko: '중점 x',      en: 'Midpoint x' },
  midY:         { ko: '중점 y',      en: 'Midpoint y' },

  pyeong:       { ko: '평',          en: 'Pyeong' },
  thickness:    { ko: '두께',        en: 'Thickness' },
  cementBags:   { ko: '시멘트 포대', en: 'Cement bags' },
  stepHeight:   { ko: '한 단 높이', en: 'Riser height' },
  stepCount:    { ko: '단 수',       en: 'Steps' },
  roofArea:     { ko: '지붕 면적',   en: 'Roof area' },
  extraPct:     { ko: '여유율',      en: 'Waste allowance' },
  waterKg:      { ko: '물 무게',     en: 'Water weight' },
  paintL:       { ko: '페인트',      en: 'Paint needed' },
  coats:        { ko: '칠할 횟수',   en: 'Coats' },
  tileSize:     { ko: '타일 한 변',  en: 'Tile side' },
  tileCount:    { ko: '타일 개수',   en: 'Tiles needed' },
  rollWidth:    { ko: '벽지 폭(cm)', en: 'Roll width (cm)' },
  rollLength:   { ko: '벽지 길이(m)', en: 'Roll length (m)' },
  rolls:        { ko: '필요 롤 수',  en: 'Rolls needed' },
  turns:        { ko: '회전 수',     en: 'Turns' },
  inches:       { ko: '인치',        en: 'Inches' },
  aspectW:      { ko: '가로 비',     en: 'Aspect width' },
  aspectH:      { ko: '세로 비',     en: 'Aspect height' },
  paperN:       { ko: 'A 규격 번호', en: 'A-series number' },
  pizzaA:       { ko: '피자 A 지름', en: 'Pizza A diameter' },
  pizzaB:       { ko: '피자 B 지름', en: 'Pizza B diameter' },
  countB:       { ko: 'B 판 수',     en: 'How many B' },
};

export const GEO_UNITS: Record<string, Term> = {
  cm2:  { ko: '㎠',   en: 'cm²' },
  cm3:  { ko: '㎤',   en: 'cm³' },
  m3:   { ko: '㎥',   en: 'm³' },
  mm:   { ko: 'mm',   en: 'mm' },
  deg:  { ko: '°',    en: '°' },
  rad:  { ko: 'rad',  en: 'rad' },
  liter:{ ko: 'L',    en: 'L' },
  kg2:  { ko: 'kg',   en: 'kg' },
  roll: { ko: '롤',   en: 'rolls' },
  ea:   { ko: '개',   en: '' },
  inch: { ko: '인치', en: 'in' },
};
