/**
 * 몸 수치 100종으로 늘리며 생긴 용어(3언어).
 *
 * terms-body.ts는 첫 50종이 쓰던 것들이다. 한 파일이 계속 길어지면 무엇이
 * 어디서 쓰이는지 안 보이므로 나눠 둔다.
 */
import type { Term } from './terms.ts';

export const BODY2_TERMS: Record<string, Term> = {
  /* 체중·체형 */
  bmiPrime: { ko: 'BMI 프라임', en: 'BMI Prime' },
  weightLow: { ko: '정상 최소 체중', en: 'Lower healthy weight' },
  weightHigh: { ko: '정상 최대 체중', en: 'Upper healthy weight' },
  waistTarget: { ko: '목표 허리둘레', en: 'Target waist' },
  ffmi: { ko: '제지방 지수', en: 'FFMI' },
  chestCm: { ko: '가슴둘레(cm)', en: 'Chest (cm)' },
  wristCm: { ko: '손목둘레(cm)', en: 'Wrist (cm)' },
  frameIndex: { ko: '골격 지수', en: 'Frame index' },
  smi: { ko: '사지근육지수', en: 'Muscle mass index' },
  brocaWeight: { ko: '브로카 표준체중', en: 'Broca weight' },
  weightBefore: { ko: '이전 체중(kg)', en: 'Weight before (kg)' },
  weightNow: { ko: '현재 체중(kg)', en: 'Weight now (kg)' },
  shapeRatio: { ko: '허리·가슴 비율', en: 'Waist-to-chest' },

  /* 대사·칼로리 */
  bmrMifflin: { ko: '기초대사량', en: 'BMR' },
  surplus: { ko: '하루 잉여 열량', en: 'Daily surplus' },
  gainPerWeek: { ko: '주당 증가', en: 'Gain a week' },
  lossPerWeek: { ko: '주당 감량 목표', en: 'Loss a week' },
  needDeficit: { ko: '필요 하루 적자', en: 'Deficit needed' },
  foodKcal: { ko: '음식 열량', en: 'Food calories' },
  burnMinutes: { ko: '태우는 시간', en: 'Minutes to burn' },
  kcalPerKg: { ko: '체중 1kg당 열량', en: 'Calories per kg' },
  gPerKg: { ko: '체중 1kg당(g)', en: 'Grams per kg' },
  mgPerKg: { ko: '체중 1kg당(mg)', en: 'Milligrams per kg' },
  fiberPerMeal: { ko: '한 끼 식이섬유', en: 'Fibre a meal' },
  mealsPerDay: { ko: '하루 끼니 수', en: 'Meals a day' },
  proteinPerMeal: { ko: '한 끼 단백질', en: 'Protein a meal' },
  fiberG: { ko: '식이섬유', en: 'Fibre' },
  sugarLimitG: { ko: '당류 상한', en: 'Added-sugar limit' },
  sodiumMg: { ko: '나트륨(mg)', en: 'Sodium (mg)' },
  saltG: { ko: '소금(g)', en: 'Salt (g)' },
  caffeineLimit: { ko: '카페인 상한', en: 'Caffeine ceiling' },
  coffeeCups: { ko: '커피 잔 수', en: 'Cups of coffee' },

  /* 심장·운동 */
  karvonenLow: { ko: '구간 하한', en: 'Zone floor' },
  karvonenHigh: { ko: '구간 상한', en: 'Zone ceiling' },
  peakHr: { ko: '운동 직후 심박', en: 'Heart rate at finish' },
  hr1min: { ko: '1분 후 심박', en: 'Heart rate after 1 min' },
  hrDrop: { ko: '회복 심박수', en: 'Recovery drop' },
  metFromVo2: { ko: 'MET 환산', en: 'METs' },
  wheelCm: { ko: '바퀴 둘레(cm)', en: 'Wheel circumference (cm)' },
  cadence: { ko: '케이던스(rpm)', en: 'Cadence (rpm)' },
  gearRatio: { ko: '기어비', en: 'Gear ratio' },
  rowMeters: { ko: '거리(m)', en: 'Distance (m)' },
  rowSeconds: { ko: '걸린 시간(초)', en: 'Time (s)' },
  split500: { ko: '500m 스플릿', en: '500 m split' },
  sets: { ko: '세트 수', en: 'Sets' },
  volumeKg: { ko: '훈련 볼륨', en: 'Training volume' },
  rpe: { ko: 'RPE(1~10)', en: 'RPE (1–10)' },
  rmPercent: { ko: '1RM 대비', en: 'Share of 1RM' },
  halfMin: { ko: '하프 기록(분)', en: 'Half time (min)' },
  fullPredict: { ko: '풀코스 예상', en: 'Marathon prediction' },

  /* 아이·성장 */
  childWater: { ko: '하루 수분 요구량', en: 'Daily fluid need' },
  fluidPerKg: { ko: '체중 1kg당 수분', en: 'Fluid per kg' },
  fluidPerHour: { ko: '시간당 수분', en: 'Fluid an hour' },
  crclPerKg: { ko: '체중 1kg당 청소율', en: 'Clearance per kg' },
  childKcal: { ko: '하루 열량 요구량', en: 'Daily calorie need' },
  heightBefore: { ko: '지난번 키(cm)', en: 'Height then (cm)' },
  heightNow: { ko: '지금 키(cm)', en: 'Height now (cm)' },
  monthsGap: { ko: '지난 기간(개월)', en: 'Months between' },
  growthVelocity: { ko: '연간 성장 속도', en: 'Growth velocity' },
  formulaPerKg: { ko: '체중 1kg당 분유', en: 'Formula per kg' },
  feverDose: { ko: '1회 해열제 용량', en: 'Dose per go' },
  maxDaily: { ko: '하루 최대량', en: 'Daily ceiling' },
  birthWeeks: { ko: '출생 주수', en: 'Gestation at birth' },
  ageWeeks: { ko: '지금 주수', en: 'Weeks since birth' },
  correctedAge: { ko: '교정 연령(주)', en: 'Corrected age (wk)' },

  /* 건강 지표 */
  creatinine: { ko: '크레아티닌(mg/dL)', en: 'Creatinine (mg/dL)' },
  egfr: { ko: '추정 사구체여과율', en: 'eGFR' },
  crcl: { ko: '크레아티닌 청소율', en: 'Creatinine clearance' },
  tgHdl: { ko: '중성지방·HDL 비율', en: 'TG / HDL' },
  quicki: { ko: 'QUICKI 지수', en: 'QUICKI' },
  tygIndex: { ko: 'TyG 지수', en: 'TyG index' },
  ast: { ko: 'AST', en: 'AST' },
  alt: { ko: 'ALT', en: 'ALT' },
  platelet: { ko: '혈소판(10⁹/L)', en: 'Platelets (10⁹/L)' },
  fib4: { ko: 'FIB-4 지수', en: 'FIB-4' },
  remnantChol: { ko: '잔여 콜레스테롤', en: 'Remnant cholesterol' },
  a1cIfcc: { ko: 'IFCC 단위', en: 'IFCC (mmol/mol)' },

  /* 생활 대사 */
  sleepNeed: { ko: '필요 수면(시간)', en: 'Sleep needed (h)' },
  sleepActual: { ko: '실제 수면(시간)', en: 'Sleep actually got (h)' },
  sleepDebt: { ko: '주간 수면 부채', en: 'Weekly sleep debt' },
  timezoneGap: { ko: '시차(시간)', en: 'Time zones crossed' },
  goEast: { ko: '방향(동1·서0)', en: 'Direction (E1 / W0)' },
  adaptDays: { ko: '적응 일수', en: 'Days to adjust' },
  standardDrinks: { ko: '표준 잔 수', en: 'Standard drinks' },
  pureAlcoholG: { ko: '순알코올(g)', en: 'Pure alcohol (g)' },
  cigsPerDay: { ko: '하루 개비 수', en: 'Cigarettes a day' },
  smokeYears: { ko: '흡연 기간(년)', en: 'Years smoking' },
  packYears: { ko: '갑년', en: 'Pack-years' },
  weightLoss: { ko: '운동 중 체중 감소(kg)', en: 'Weight lost (kg)' },
  drankMl: { ko: '운동 중 마신 물(ml)', en: 'Fluid drunk (mL)' },
  sweatRate: { ko: '시간당 땀 손실', en: 'Sweat rate an hour' },
  alcoholKcal: { ko: '술 열량', en: 'Calories from drink' },
};

export const BODY2_UNITS: Record<string, Term> = {
  mlPerKg: { ko: 'ml/kg', en: 'mL/kg' },
  kcalPerKgU: { ko: 'kcal/kg', en: 'kcal/kg' },
  cmPerYear: { ko: 'cm/년', en: 'cm/yr' },
  rpm: { ko: 'rpm', en: 'rpm' },
  sec: { ko: '초', en: 's' },
  set: { ko: '세트', en: 'sets' },
  glass: { ko: '잔', en: 'drinks' },
  packYear: { ko: '갑년', en: 'pack-yr' },
  mlPerHour: { ko: 'ml/시간', en: 'mL/h' },
  mlmin: { ko: 'ml/분', en: 'mL/min' },
  mmolMol: { ko: 'mmol/mol', en: 'mmol/mol' },
};
