/**
 * 도형 100종으로 늘리며 생긴 용어(3언어).
 */
import type { Term } from './terms.ts';

export const GEO2_TERMS: Record<string, Term> = {
  /* 평면 */
  sideSquare: { ko: '한 변', en: 'Side' },
  inradius: { ko: '내접원 반지름', en: 'Inradius' },
  circumradius: { ko: '외접원 반지름', en: 'Circumradius' },
  scaleFactor: { ko: '닮음비', en: 'Scale factor' },
  areaRatio: { ko: '면적비', en: 'Area ratio' },
  volumeRatio: { ko: '부피비', en: 'Volume ratio' },
  x3: { ko: 'x₃', en: 'x₃' },
  y3: { ko: 'y₃', en: 'y₃' },
  centroidX: { ko: '무게중심 x', en: 'Centroid x' },
  centroidY: { ko: '무게중심 y', en: 'Centroid y' },
  included: { ko: '끼인각', en: 'Included angle' },
  heightTri: { ko: '높이', en: 'Height' },

  /* 입체 */
  frustumTop: { ko: '위쪽 반지름', en: 'Top radius' },
  capHeight: { ko: '채운 높이', en: 'Fill height' },
  capVolume: { ko: '채운 부피', en: 'Filled volume' },
  fillPercent: { ko: '채운 비율', en: 'Fill share' },
  bodyLen: { ko: '몸통 길이', en: 'Body length' },
  axisC: { ko: '세 번째 반지름', en: 'Third radius' },
  baseArea: { ko: '밑면 넓이', en: 'Base area' },
  lateral: { ko: '옆면 넓이', en: 'Lateral area' },

  /* 삼각비 */
  angleB: { ko: '각 B', en: 'Angle B' },
  angleC: { ko: '각 C', en: 'Angle C' },
  angleA: { ko: '각 A', en: 'Angle A' },
  eyeHeight: { ko: '눈높이', en: 'Eye height' },
  targetHeight: { ko: '대상 높이', en: 'Object height' },
  z1: { ko: 'z₁', en: 'z₁' },
  z2: { ko: 'z₂', en: 'z₂' },
  vecAx: { ko: 'A의 x', en: 'A.x' },
  vecAy: { ko: 'A의 y', en: 'A.y' },
  vecBx: { ko: 'B의 x', en: 'B.x' },
  vecBy: { ko: 'B의 y', en: 'B.y' },
  bearingDeg: { ko: '방위각', en: 'Bearing' },
  ratioVal: { ko: '삼각비 값', en: 'Ratio' },
  ladderLen: { ko: '사다리 길이', en: 'Ladder length' },
  wallHeight: { ko: '닿는 높이', en: 'Height reached' },
  footDist: { ko: '벽에서 거리', en: 'Distance from wall' },
  polarR: { ko: '반지름 r', en: 'Radius r' },
  polarTheta: { ko: '각 θ', en: 'Angle θ' },
  cartX: { ko: 'x 좌표', en: 'x' },
  cartY: { ko: 'y 좌표', en: 'y' },

  /* 원·호 */
  sectorPerimeter: { ko: '부채꼴 둘레', en: 'Sector perimeter' },
  sagitta: { ko: '활 높이', en: 'Sagitta' },
  pulleyA: { ko: '풀리 A 지름', en: 'Pulley A diameter' },
  pulleyB: { ko: '풀리 B 지름', en: 'Pulley B diameter' },
  centerDist: { ko: '축간 거리', en: 'Centre distance' },
  beltLen: { ko: '벨트 길이', en: 'Belt length' },
  pipeDia: { ko: '파이프 안지름', en: 'Pipe bore' },
  flowSpeed: { ko: '유속(m/s)', en: 'Flow speed (m/s)' },
  flowRate: { ko: '유량', en: 'Flow rate' },
  smallDia: { ko: '작은 원 지름', en: 'Small circle diameter' },
  fitCount: { ko: '들어가는 개수', en: 'How many fit' },

  /* 생활 계산 */
  carpetArea: { ko: '필요 면적', en: 'Area needed' },
  fenceLen: { ko: '울타리 길이', en: 'Fence length' },
  postGap: { ko: '기둥 간격', en: 'Post spacing' },
  postCount: { ko: '기둥 개수', en: 'Posts needed' },
  gravelDepth: { ko: '깔 두께', en: 'Layer depth' },
  gravelWeight: { ko: '자갈 무게', en: 'Gravel weight' },
  fillHours: { ko: '채우는 시간', en: 'Time to fill' },
  flowLpm: { ko: '수압(L/분)', en: 'Flow (L/min)' },
  boardWidth: { ko: '판재 폭', en: 'Board width' },
  boardCount: { ko: '판재 개수', en: 'Boards needed' },
  windowWidth: { ko: '창 폭', en: 'Window width' },
  pleatRatio: { ko: '주름 배율', en: 'Fullness ratio' },
  fabricWidth: { ko: '필요 원단 폭', en: 'Fabric width needed' },
  potDia: { ko: '화분 지름', en: 'Pot diameter' },
  potDepth: { ko: '화분 깊이', en: 'Pot depth' },
  soilL: { ko: '필요 흙', en: 'Soil needed' },
  brickW: { ko: '벽돌 길이(cm)', en: 'Brick length (cm)' },
  brickH: { ko: '벽돌 높이(cm)', en: 'Brick height (cm)' },
  brickCount: { ko: '벽돌 개수', en: 'Bricks needed' },
  cordVolume: { ko: '장작 부피', en: 'Firewood volume' },
  cords: { ko: '코드 수', en: 'Cords' },
  lotArea: { ko: '부지 면적', en: 'Lot area' },
  perSpace: { ko: '1대당 면적', en: 'Area per car' },
  spaceCount: { ko: '주차 대수', en: 'Parking spaces' },
  panelW: { ko: '패널 가로(m)', en: 'Panel width (m)' },
  panelH: { ko: '패널 세로(m)', en: 'Panel height (m)' },
  panelCount: { ko: '패널 개수', en: 'Panels' },
  panelKw: { ko: '설치 용량', en: 'Installed capacity' },
  rainMm: { ko: '강수량(mm)', en: 'Rainfall (mm)' },
  harvestL: { ko: '모이는 물', en: 'Water collected' },
  pxWidth: { ko: '가로 픽셀', en: 'Width in pixels' },
  pxHeight: { ko: '세로 픽셀', en: 'Height in pixels' },
  ppi: { ko: '픽셀 밀도(ppi)', en: 'Pixel density (ppi)' },
  itemW: { ko: '물건 가로', en: 'Item width' },
  itemH: { ko: '물건 세로', en: 'Item depth' },
  itemD: { ko: '물건 높이', en: 'Item height' },
  boxCount: { ko: '들어가는 개수', en: 'Items that fit' },
};

export const GEO2_UNITS: Record<string, Term> = {
  deg: { ko: '°', en: '°' },
  liter: { ko: 'L', en: 'L' },
  ton: { ko: 't', en: 't' },
  kw: { ko: 'kW', en: 'kW' },
  ppiU: { ko: 'ppi', en: 'ppi' },
  px: { ko: 'px', en: 'px' },
  m3: { ko: '㎥', en: 'm³' },
  lpm: { ko: 'L/분', en: 'L/min' },
  mm: { ko: 'mm', en: 'mm' },
};
