/** 몸 수치 도구가 쓰는 용어 — 핵심 사전(terms.ts)에 합쳐진다 */
import type { Term } from './terms.ts';

export const BODY_TERMS: Record<string, Term> = {
  heightCm:     { ko: '키(cm)',      en: 'Height (cm)',      zh: '身高(厘米)' },
  weightKgB:    { ko: '체중(kg)',    en: 'Weight (kg)',      zh: '体重(公斤)' },
  ageYears:     { ko: '나이',        en: 'Age',              zh: '年龄' },
  sexFactor:    { ko: '성별(남1·여0)', en: 'Sex (M1 / F0)',  zh: '性别(男1女0)' },
  waistCm:      { ko: '허리둘레(cm)', en: 'Waist (cm)',      zh: '腰围(厘米)' },
  hipCm:        { ko: '엉덩이둘레(cm)', en: 'Hip (cm)',      zh: '臀围(厘米)' },
  neckCm:       { ko: '목둘레(cm)',  en: 'Neck (cm)',        zh: '颈围(厘米)' },
  bmi:          { ko: 'BMI',         en: 'BMI',              zh: 'BMI' },
  bmiTarget:    { ko: '목표 BMI',    en: 'Target BMI',       zh: '目标BMI' },
  idealWeight:  { ko: '표준 체중',   en: 'Ideal weight',     zh: '标准体重' },
  bodyFat:      { ko: '체지방률',    en: 'Body fat',         zh: '体脂率' },
  fatMass:      { ko: '체지방량',    en: 'Fat mass',         zh: '脂肪量' },
  leanMass:     { ko: '제지방량',    en: 'Lean mass',        zh: '去脂体重' },
  bsa:          { ko: '체표면적',    en: 'Body surface area', zh: '体表面积' },
  whr:          { ko: '허리·엉덩이 비율', en: 'Waist-hip ratio', zh: '腰臀比' },
  whtr:         { ko: '허리·키 비율', en: 'Waist-height ratio', zh: '腰高比' },
  ponderal:     { ko: '신체충실지수', en: 'Ponderal index',  zh: '体质指数' },

  bmr:          { ko: '기초대사량',  en: 'BMR',              zh: '基础代谢率' },
  tdee:         { ko: '활동대사량',  en: 'TDEE',             zh: '每日总消耗' },
  activity:     { ko: '활동계수',    en: 'Activity factor',  zh: '活动系数' },
  calories:     { ko: '칼로리',      en: 'Calories',         zh: '卡路里' },
  deficit:      { ko: '하루 적자',   en: 'Daily deficit',    zh: '每日热量差' },
  targetWeight: { ko: '목표 체중',   en: 'Target weight',    zh: '目标体重' },
  weeksNeeded:  { ko: '걸리는 기간', en: 'Time needed',      zh: '所需时间' },
  proteinG:     { ko: '단백질',      en: 'Protein',          zh: '蛋白质' },
  carbG:        { ko: '탄수화물',    en: 'Carbs',            zh: '碳水化合物' },
  fatG:         { ko: '지방',        en: 'Fat',              zh: '脂肪' },
  waterMl:      { ko: '권장 수분',   en: 'Water',            zh: '建议饮水量' },
  metValue:     { ko: 'MET(운동 강도)', en: 'MET',           zh: 'MET(运动强度)' },
  minutes:      { ko: '시간(분)',    en: 'Minutes',          zh: '时间(分钟)' },
  steps:        { ko: '걸음 수',     en: 'Steps',            zh: '步数' },
  strideCm:     { ko: '보폭(cm)',    en: 'Stride (cm)',      zh: '步幅(厘米)' },
  distanceKm:   { ko: '거리(km)',    en: 'Distance (km)',    zh: '距离(公里)' },

  maxHr:        { ko: '최대 심박수', en: 'Max heart rate',   zh: '最大心率' },
  restHr:       { ko: '안정 심박수', en: 'Resting HR',       zh: '静息心率' },
  hrLow:        { ko: '구간 하한',   en: 'Zone low',         zh: '区间下限' },
  hrHigh:       { ko: '구간 상한',   en: 'Zone high',        zh: '区间上限' },
  intensity:    { ko: '운동 강도',   en: 'Intensity',        zh: '运动强度' },
  vo2max:       { ko: 'VO2max',      en: 'VO2max',           zh: '最大摄氧量' },
  liftWeight:   { ko: '든 무게(kg)', en: 'Weight lifted (kg)', zh: '举起重量(公斤)' },
  reps:         { ko: '반복 횟수',   en: 'Reps',             zh: '重复次数' },
  oneRm:        { ko: '1RM',         en: '1RM',              zh: '1RM' },
  paceMin:      { ko: '페이스',      en: 'Pace',             zh: '配速' },
  timeMin:      { ko: '시간(분)',    en: 'Time (min)',       zh: '时间(分钟)' },
  speedKmh:     { ko: '속도(km/h)',  en: 'Speed (km/h)',     zh: '速度(公里/时)' },
  finishTime:   { ko: '완주 시간',   en: 'Finish time',      zh: '完成时间' },
  per100m:      { ko: '100m당',      en: 'Per 100 m',        zh: '每100米' },
  paceSec:      { ko: '초 부분',      en: 'Seconds',          zh: '秒数' },
  cooperDist:   { ko: '12분 달린 거리(m)', en: '12-min distance (m)', zh: '12分钟跑距(米)' },
  hours:        { ko: '시간',         en: 'Hours',            zh: '小时' },

  fatherCm:     { ko: '아버지 키(cm)', en: "Father's height", zh: '父亲身高(厘米)' },
  motherCm:     { ko: '어머니 키(cm)', en: "Mother's height", zh: '母亲身高(厘米)' },
  childHeight:  { ko: '예측 키',     en: 'Predicted height', zh: '预测身高' },
  birthWeight:  { ko: '출생 체중(g)', en: 'Birth weight (g)', zh: '出生体重(克)' },
  nowWeight:    { ko: '현재 체중(g)', en: 'Current weight (g)', zh: '当前体重(克)' },
  milkMl:       { ko: '하루 수유량', en: 'Daily milk',       zh: '每日奶量' },
  perFeed:      { ko: '1회 수유량',  en: 'Per feed',         zh: '每次奶量' },
  feeds:        { ko: '수유 횟수',   en: 'Feeds per day',    zh: '每日次数' },
  dosePerKg:    { ko: '용량(mg/kg)', en: 'Dose (mg/kg)',     zh: '剂量(毫克/公斤)' },
  doseMg:       { ko: '1회 용량',    en: 'Dose',             zh: '单次剂量' },
  bloodMl:      { ko: '혈액량',      en: 'Blood volume',     zh: '血容量' },
  gainPercent:  { ko: '증가율',      en: 'Gain',             zh: '增长率' },

  systolic:     { ko: '수축기 혈압', en: 'Systolic',         zh: '收缩压' },
  diastolic:    { ko: '이완기 혈압', en: 'Diastolic',        zh: '舒张压' },
  map:          { ko: '평균 동맥압', en: 'Mean arterial pressure', zh: '平均动脉压' },
  pulsePress:   { ko: '맥압',        en: 'Pulse pressure',   zh: '脉压' },
  totalChol:    { ko: '총콜레스테롤', en: 'Total cholesterol', zh: '总胆固醇' },
  hdl:          { ko: 'HDL',         en: 'HDL',              zh: '高密度脂蛋白' },
  ldl:          { ko: 'LDL',         en: 'LDL',              zh: '低密度脂蛋白' },
  triglyceride: { ko: '중성지방',    en: 'Triglycerides',    zh: '甘油三酯' },
  cholRatio:    { ko: '총/HDL 비율', en: 'Total : HDL',      zh: '总胆固醇/HDL' },
  nonHdl:       { ko: 'non-HDL',     en: 'Non-HDL',          zh: '非HDL胆固醇' },
  glucose:      { ko: '혈당(mg/dL)', en: 'Glucose (mg/dL)',  zh: '血糖(毫克/分升)' },
  insulin:      { ko: '인슐린(μU/ml)', en: 'Insulin (μU/mL)', zh: '胰岛素' },
  homaIr:       { ko: 'HOMA-IR',     en: 'HOMA-IR',          zh: 'HOMA-IR' },
  a1c:          { ko: '당화혈색소(%)', en: 'HbA1c (%)',      zh: '糖化血红蛋白' },
  avgGlucose:   { ko: '평균 혈당',   en: 'Average glucose',  zh: '平均血糖' },
  mmolL:        { ko: 'mmol/L',      en: 'mmol/L',           zh: '毫摩尔/升' },
  mgdl:         { ko: 'mg/dL',       en: 'mg/dL',            zh: '毫克/分升' },

  sleepHours:   { ko: '자는 시간',   en: 'Sleep',            zh: '睡眠时间' },
  cycles:       { ko: '수면 주기',   en: 'Cycles',           zh: '睡眠周期' },
  drinkMl:      { ko: '마신 양(ml)', en: 'Volume (mL)',      zh: '饮用量(毫升)' },
  abv:          { ko: '도수(%)',     en: 'ABV (%)',          zh: '酒精度(%)' },
  bac:          { ko: '혈중 알코올', en: 'BAC',              zh: '血液酒精浓度' },
  clearHours:   { ko: '분해 시간',   en: 'Time to clear',    zh: '分解时间' },
  caffeineMg:   { ko: '카페인(mg)',  en: 'Caffeine (mg)',    zh: '咖啡因(毫克)' },
  hoursLater:   { ko: '경과 시간',   en: 'Hours later',      zh: '经过时间' },
  remainMg:     { ko: '남은 양',     en: 'Remaining',        zh: '残留量' },
};

export const BODY_UNITS: Record<string, Term> = {
  kg:      { ko: 'kg',     en: 'kg',      zh: '公斤' },
  kcal:    { ko: 'kcal',   en: 'kcal',    zh: '千卡' },
  bpm:     { ko: 'bpm',    en: 'bpm',     zh: '次/分' },
  mmHg:    { ko: 'mmHg',   en: 'mmHg',    zh: '毫米汞柱' },
  mg:      { ko: 'mg',     en: 'mg',      zh: '毫克' },
  m2:      { ko: '㎡',     en: 'm²',      zh: '平方米' },
  minPerKm:{ ko: '분/km',  en: 'min/km',  zh: '分/公里' },
  hour:    { ko: '시간',   en: 'h',       zh: '小时' },
  week:    { ko: '주',     en: 'wk',      zh: '周' },
  mgdlU:   { ko: 'mg/dL',  en: 'mg/dL',   zh: '毫克/分升' },
  mmolU:   { ko: 'mmol/L', en: 'mmol/L',  zh: '毫摩尔/升' },
  step:    { ko: '걸음',   en: 'steps',   zh: '步' },
  minute:  { ko: '분',     en: 'min',     zh: '分钟' },
};
