/** 도형·수학 도구가 쓰는 용어 — 핵심 사전(terms.ts)에 합쳐진다 */
import type { Term } from './terms.ts';

export const GEO_TERMS: Record<string, Term> = {
  radius:       { ko: '반지름',      en: 'Radius',           zh: '半径' },
  radius2:      { ko: '작은 반지름', en: 'Inner radius',     zh: '内半径' },
  diameter:     { ko: '지름',        en: 'Diameter',         zh: '直径' },
  circumference:{ ko: '둘레',        en: 'Circumference',    zh: '周长' },
  area:         { ko: '면적',        en: 'Area',             zh: '面积' },
  perimeter:    { ko: '둘레',        en: 'Perimeter',        zh: '周长' },
  baseLen:      { ko: '밑변',        en: 'Base',             zh: '底边' },
  baseTop:      { ko: '윗변',        en: 'Top edge',         zh: '上底' },
  heightGeo:    { ko: '높이',        en: 'Height',           zh: '高' },
  sideLen:      { ko: '한 변',       en: 'Side length',      zh: '边长' },
  sideCount:    { ko: '변의 수',     en: 'Number of sides',  zh: '边数' },
  sideA:        { ko: '변 a',        en: 'Side a',           zh: '边a' },
  sideB:        { ko: '변 b',        en: 'Side b',           zh: '边b' },
  sideC:        { ko: '변 c',        en: 'Side c',           zh: '边c' },
  hypotenuse:   { ko: '빗변',        en: 'Hypotenuse',       zh: '斜边' },
  diagonal1:    { ko: '대각선 1',    en: 'Diagonal 1',       zh: '对角线1' },
  diagonal2:    { ko: '대각선 2',    en: 'Diagonal 2',       zh: '对角线2' },
  diagonal:     { ko: '대각선',      en: 'Diagonal',         zh: '对角线' },
  axisA:        { ko: '장반경',      en: 'Semi-major axis',  zh: '长半轴' },
  axisB:        { ko: '단반경',      en: 'Semi-minor axis',  zh: '短半轴' },
  angleDeg:     { ko: '각도(°)',     en: 'Angle (°)',        zh: '角度(°)' },
  angleRad:     { ko: '라디안',      en: 'Radians',          zh: '弧度' },
  innerAngle:   { ko: '한 내각',     en: 'Interior angle',   zh: '内角' },
  outerAngle:   { ko: '한 외각',     en: 'Exterior angle',   zh: '外角' },
  angleSum:     { ko: '내각의 합',   en: 'Sum of angles',    zh: '内角和' },
  arcLen:       { ko: '호의 길이',   en: 'Arc length',        zh: '弧长' },
  chordLen:     { ko: '현의 길이',   en: 'Chord length',      zh: '弦长' },

  volume:       { ko: '부피',        en: 'Volume',           zh: '体积' },
  surface:      { ko: '표면적',      en: 'Surface area',     zh: '表面积' },
  sideSurface:  { ko: '옆면적',      en: 'Lateral area',     zh: '侧面积' },
  slant:        { ko: '모선',        en: 'Slant height',     zh: '母线' },
  lengthCm:     { ko: '가로',        en: 'Length',           zh: '长' },
  widthCm:      { ko: '세로',        en: 'Width',            zh: '宽' },
  depthCm:      { ko: '깊이',        en: 'Depth',            zh: '深' },
  liters:       { ko: '용량(L)',     en: 'Litres',           zh: '容量(升)' },
  weightT:      { ko: '무게',        en: 'Weight',           zh: '重量' },

  sinVal:       { ko: 'sin',         en: 'sin',              zh: 'sin' },
  cosVal:       { ko: 'cos',         en: 'cos',              zh: 'cos' },
  tanVal:       { ko: 'tan',         en: 'tan',              zh: 'tan' },
  slopePct:     { ko: '경사도(%)',   en: 'Grade (%)',        zh: '坡度(%)' },
  riseLen:      { ko: '수직 높이',   en: 'Rise',             zh: '垂直高度' },
  runLen:       { ko: '수평 거리',   en: 'Run',              zh: '水平距离' },
  x1: { ko: 'x₁', en: 'x₁', zh: 'x₁' },
  y1: { ko: 'y₁', en: 'y₁', zh: 'y₁' },
  x2: { ko: 'x₂', en: 'x₂', zh: 'x₂' },
  y2: { ko: 'y₂', en: 'y₂', zh: 'y₂' },
  distance:     { ko: '거리',        en: 'Distance',         zh: '距离' },
  midX:         { ko: '중점 x',      en: 'Midpoint x',       zh: '中点x' },
  midY:         { ko: '중점 y',      en: 'Midpoint y',       zh: '中点y' },

  pyeong:       { ko: '평',          en: 'Pyeong',           zh: '坪' },
  thickness:    { ko: '두께',        en: 'Thickness',        zh: '厚度' },
  cementBags:   { ko: '시멘트 포대', en: 'Cement bags',      zh: '水泥袋数' },
  stepHeight:   { ko: '한 단 높이', en: 'Riser height',     zh: '单级高度' },
  stepCount:    { ko: '단 수',       en: 'Steps',            zh: '级数' },
  roofArea:     { ko: '지붕 면적',   en: 'Roof area',        zh: '屋顶面积' },
  extraPct:     { ko: '여유율',      en: 'Waste allowance',  zh: '损耗率' },
  waterKg:      { ko: '물 무게',     en: 'Water weight',     zh: '水重' },
  paintL:       { ko: '페인트',      en: 'Paint needed',     zh: '所需涂料' },
  coats:        { ko: '칠할 횟수',   en: 'Coats',            zh: '涂刷遍数' },
  tileSize:     { ko: '타일 한 변',  en: 'Tile side',        zh: '瓷砖边长' },
  tileCount:    { ko: '타일 개수',   en: 'Tiles needed',     zh: '所需瓷砖' },
  rollWidth:    { ko: '벽지 폭(cm)', en: 'Roll width (cm)',  zh: '壁纸幅宽(厘米)' },
  rollLength:   { ko: '벽지 길이(m)', en: 'Roll length (m)', zh: '壁纸长度(米)' },
  rolls:        { ko: '필요 롤 수',  en: 'Rolls needed',     zh: '所需卷数' },
  turns:        { ko: '회전 수',     en: 'Turns',            zh: '转数' },
  inches:       { ko: '인치',        en: 'Inches',           zh: '英寸' },
  aspectW:      { ko: '가로 비',     en: 'Aspect width',     zh: '宽比' },
  aspectH:      { ko: '세로 비',     en: 'Aspect height',    zh: '高比' },
  paperN:       { ko: 'A 규격 번호', en: 'A-series number',  zh: 'A系列编号' },
  pizzaA:       { ko: '피자 A 지름', en: 'Pizza A diameter', zh: '披萨A直径' },
  pizzaB:       { ko: '피자 B 지름', en: 'Pizza B diameter', zh: '披萨B直径' },
  countB:       { ko: 'B 판 수',     en: 'How many B',       zh: 'B的数量' },
};

export const GEO_UNITS: Record<string, Term> = {
  cm2:  { ko: '㎠',   en: 'cm²',  zh: '平方厘米' },
  cm3:  { ko: '㎤',   en: 'cm³',  zh: '立方厘米' },
  m3:   { ko: '㎥',   en: 'm³',   zh: '立方米' },
  mm:   { ko: 'mm',   en: 'mm',   zh: '毫米' },
  deg:  { ko: '°',    en: '°',    zh: '°' },
  rad:  { ko: 'rad',  en: 'rad',  zh: '弧度' },
  liter:{ ko: 'L',    en: 'L',    zh: '升' },
  kg2:  { ko: 'kg',   en: 'kg',   zh: '公斤' },
  roll: { ko: '롤',   en: 'rolls', zh: '卷' },
  ea:   { ko: '개',   en: '',     zh: '个' },
  inch: { ko: '인치', en: 'in',   zh: '英寸' },
};
