/**
 * 몸 수치 100종으로 늘리며 생긴 용어(3언어).
 *
 * terms-body.ts는 첫 50종이 쓰던 것들이다. 한 파일이 계속 길어지면 무엇이
 * 어디서 쓰이는지 안 보이므로 나눠 둔다.
 */
import type { Term } from './terms.ts';

export const BODY2_TERMS: Record<string, Term> = {
  /* 체중·체형 */
  bmiPrime: { ko: 'BMI 프라임', en: 'BMI Prime', zh: 'BMI Prime' },
  weightLow: { ko: '정상 최소 체중', en: 'Lower healthy weight', zh: '正常下限体重' },
  weightHigh: { ko: '정상 최대 체중', en: 'Upper healthy weight', zh: '正常上限体重' },
  waistTarget: { ko: '목표 허리둘레', en: 'Target waist', zh: '目标腰围' },
  ffmi: { ko: '제지방 지수', en: 'FFMI', zh: '去脂体重指数' },
  chestCm: { ko: '가슴둘레(cm)', en: 'Chest (cm)', zh: '胸围(厘米)' },
  wristCm: { ko: '손목둘레(cm)', en: 'Wrist (cm)', zh: '腕围(厘米)' },
  frameIndex: { ko: '골격 지수', en: 'Frame index', zh: '骨架指数' },
  smi: { ko: '사지근육지수', en: 'Muscle mass index', zh: '四肢肌肉指数' },
  brocaWeight: { ko: '브로카 표준체중', en: 'Broca weight', zh: '布罗卡标准体重' },
  weightBefore: { ko: '이전 체중(kg)', en: 'Weight before (kg)', zh: '之前体重(公斤)' },
  weightNow: { ko: '현재 체중(kg)', en: 'Weight now (kg)', zh: '当前体重(公斤)' },
  shapeRatio: { ko: '허리·가슴 비율', en: 'Waist-to-chest', zh: '腰胸比' },

  /* 대사·칼로리 */
  bmrMifflin: { ko: '기초대사량', en: 'BMR', zh: '基础代谢率' },
  surplus: { ko: '하루 잉여 열량', en: 'Daily surplus', zh: '每日热量盈余' },
  gainPerWeek: { ko: '주당 증가', en: 'Gain a week', zh: '每周增重' },
  lossPerWeek: { ko: '주당 감량 목표', en: 'Loss a week', zh: '每周减重目标' },
  needDeficit: { ko: '필요 하루 적자', en: 'Deficit needed', zh: '所需每日热量缺口' },
  foodKcal: { ko: '음식 열량', en: 'Food calories', zh: '食物热量' },
  burnMinutes: { ko: '태우는 시간', en: 'Minutes to burn', zh: '消耗所需时间' },
  kcalPerKg: { ko: '체중 1kg당 열량', en: 'Calories per kg', zh: '每公斤体重热量' },
  gPerKg: { ko: '체중 1kg당(g)', en: 'Grams per kg', zh: '每公斤体重(克)' },
  mgPerKg: { ko: '체중 1kg당(mg)', en: 'Milligrams per kg', zh: '每公斤体重(毫克)' },
  fiberPerMeal: { ko: '한 끼 식이섬유', en: 'Fibre a meal', zh: '每餐膳食纤维' },
  mealsPerDay: { ko: '하루 끼니 수', en: 'Meals a day', zh: '每天餐数' },
  proteinPerMeal: { ko: '한 끼 단백질', en: 'Protein a meal', zh: '每餐蛋白质' },
  fiberG: { ko: '식이섬유', en: 'Fibre', zh: '膳食纤维' },
  sugarLimitG: { ko: '당류 상한', en: 'Added-sugar limit', zh: '添加糖上限' },
  sodiumMg: { ko: '나트륨(mg)', en: 'Sodium (mg)', zh: '钠(毫克)' },
  saltG: { ko: '소금(g)', en: 'Salt (g)', zh: '盐(克)' },
  caffeineLimit: { ko: '카페인 상한', en: 'Caffeine ceiling', zh: '咖啡因上限' },
  coffeeCups: { ko: '커피 잔 수', en: 'Cups of coffee', zh: '咖啡杯数' },

  /* 심장·운동 */
  karvonenLow: { ko: '구간 하한', en: 'Zone floor', zh: '区间下限' },
  karvonenHigh: { ko: '구간 상한', en: 'Zone ceiling', zh: '区间上限' },
  peakHr: { ko: '운동 직후 심박', en: 'Heart rate at finish', zh: '运动结束时心率' },
  hr1min: { ko: '1분 후 심박', en: 'Heart rate after 1 min', zh: '1分钟后心率' },
  hrDrop: { ko: '회복 심박수', en: 'Recovery drop', zh: '心率恢复值' },
  metFromVo2: { ko: 'MET 환산', en: 'METs', zh: 'MET换算' },
  wheelCm: { ko: '바퀴 둘레(cm)', en: 'Wheel circumference (cm)', zh: '轮周(厘米)' },
  cadence: { ko: '케이던스(rpm)', en: 'Cadence (rpm)', zh: '踏频(rpm)' },
  gearRatio: { ko: '기어비', en: 'Gear ratio', zh: '齿比' },
  rowMeters: { ko: '거리(m)', en: 'Distance (m)', zh: '距离(米)' },
  rowSeconds: { ko: '걸린 시간(초)', en: 'Time (s)', zh: '用时(秒)' },
  split500: { ko: '500m 스플릿', en: '500 m split', zh: '500米分段' },
  sets: { ko: '세트 수', en: 'Sets', zh: '组数' },
  volumeKg: { ko: '훈련 볼륨', en: 'Training volume', zh: '训练容量' },
  rpe: { ko: 'RPE(1~10)', en: 'RPE (1–10)', zh: 'RPE(1~10)' },
  rmPercent: { ko: '1RM 대비', en: 'Share of 1RM', zh: '占1RM比例' },
  halfMin: { ko: '하프 기록(분)', en: 'Half time (min)', zh: '半马成绩(分)' },
  fullPredict: { ko: '풀코스 예상', en: 'Marathon prediction', zh: '全马预测' },

  /* 아이·성장 */
  childWater: { ko: '하루 수분 요구량', en: 'Daily fluid need', zh: '每日需水量' },
  fluidPerKg: { ko: '체중 1kg당 수분', en: 'Fluid per kg', zh: '每公斤需水量' },
  fluidPerHour: { ko: '시간당 수분', en: 'Fluid an hour', zh: '每小时水分' },
  crclPerKg: { ko: '체중 1kg당 청소율', en: 'Clearance per kg', zh: '每公斤清除率' },
  childKcal: { ko: '하루 열량 요구량', en: 'Daily calorie need', zh: '每日热量需求' },
  heightBefore: { ko: '지난번 키(cm)', en: 'Height then (cm)', zh: '上次身高(厘米)' },
  heightNow: { ko: '지금 키(cm)', en: 'Height now (cm)', zh: '当前身高(厘米)' },
  monthsGap: { ko: '지난 기간(개월)', en: 'Months between', zh: '间隔月数' },
  growthVelocity: { ko: '연간 성장 속도', en: 'Growth velocity', zh: '年生长速度' },
  formulaPerKg: { ko: '체중 1kg당 분유', en: 'Formula per kg', zh: '每公斤奶量' },
  feverDose: { ko: '1회 해열제 용량', en: 'Dose per go', zh: '单次退热药量' },
  maxDaily: { ko: '하루 최대량', en: 'Daily ceiling', zh: '每日上限' },
  birthWeeks: { ko: '출생 주수', en: 'Gestation at birth', zh: '出生周数' },
  ageWeeks: { ko: '지금 주수', en: 'Weeks since birth', zh: '出生后周数' },
  correctedAge: { ko: '교정 연령(주)', en: 'Corrected age (wk)', zh: '矫正年龄(周)' },

  /* 건강 지표 */
  creatinine: { ko: '크레아티닌(mg/dL)', en: 'Creatinine (mg/dL)', zh: '肌酐(毫克/分升)' },
  egfr: { ko: '추정 사구체여과율', en: 'eGFR', zh: '估算肾小球滤过率' },
  crcl: { ko: '크레아티닌 청소율', en: 'Creatinine clearance', zh: '肌酐清除率' },
  tgHdl: { ko: '중성지방·HDL 비율', en: 'TG / HDL', zh: '甘油三酯与HDL比' },
  quicki: { ko: 'QUICKI 지수', en: 'QUICKI', zh: 'QUICKI指数' },
  tygIndex: { ko: 'TyG 지수', en: 'TyG index', zh: 'TyG指数' },
  ast: { ko: 'AST', en: 'AST', zh: 'AST' },
  alt: { ko: 'ALT', en: 'ALT', zh: 'ALT' },
  platelet: { ko: '혈소판(10⁹/L)', en: 'Platelets (10⁹/L)', zh: '血小板(10⁹/升)' },
  fib4: { ko: 'FIB-4 지수', en: 'FIB-4', zh: 'FIB-4指数' },
  remnantChol: { ko: '잔여 콜레스테롤', en: 'Remnant cholesterol', zh: '残余胆固醇' },
  a1cIfcc: { ko: 'IFCC 단위', en: 'IFCC (mmol/mol)', zh: 'IFCC单位' },

  /* 생활 대사 */
  sleepNeed: { ko: '필요 수면(시간)', en: 'Sleep needed (h)', zh: '所需睡眠(小时)' },
  sleepActual: { ko: '실제 수면(시간)', en: 'Sleep actually got (h)', zh: '实际睡眠(小时)' },
  sleepDebt: { ko: '주간 수면 부채', en: 'Weekly sleep debt', zh: '每周睡眠债' },
  timezoneGap: { ko: '시차(시간)', en: 'Time zones crossed', zh: '时差(小时)' },
  goEast: { ko: '방향(동1·서0)', en: 'Direction (E1 / W0)', zh: '方向(东1西0)' },
  adaptDays: { ko: '적응 일수', en: 'Days to adjust', zh: '适应天数' },
  standardDrinks: { ko: '표준 잔 수', en: 'Standard drinks', zh: '标准杯数' },
  pureAlcoholG: { ko: '순알코올(g)', en: 'Pure alcohol (g)', zh: '纯酒精(克)' },
  cigsPerDay: { ko: '하루 개비 수', en: 'Cigarettes a day', zh: '每天支数' },
  smokeYears: { ko: '흡연 기간(년)', en: 'Years smoking', zh: '吸烟年数' },
  packYears: { ko: '갑년', en: 'Pack-years', zh: '包年' },
  weightLoss: { ko: '운동 중 체중 감소(kg)', en: 'Weight lost (kg)', zh: '运动中体重下降(公斤)' },
  drankMl: { ko: '운동 중 마신 물(ml)', en: 'Fluid drunk (mL)', zh: '运动中饮水(毫升)' },
  sweatRate: { ko: '시간당 땀 손실', en: 'Sweat rate an hour', zh: '每小时汗液流失' },
  alcoholKcal: { ko: '술 열량', en: 'Calories from drink', zh: '酒的热量' },
};

export const BODY2_UNITS: Record<string, Term> = {
  mlPerKg: { ko: 'ml/kg', en: 'mL/kg', zh: '毫升/公斤' },
  kcalPerKgU: { ko: 'kcal/kg', en: 'kcal/kg', zh: '千卡/公斤' },
  cmPerYear: { ko: 'cm/년', en: 'cm/yr', zh: '厘米/年' },
  rpm: { ko: 'rpm', en: 'rpm', zh: 'rpm' },
  sec: { ko: '초', en: 's', zh: '秒' },
  set: { ko: '세트', en: 'sets', zh: '组' },
  glass: { ko: '잔', en: 'drinks', zh: '杯' },
  packYear: { ko: '갑년', en: 'pack-yr', zh: '包年' },
  mlPerHour: { ko: 'ml/시간', en: 'mL/h', zh: '毫升/小时' },
  mlmin: { ko: 'ml/분', en: 'mL/min', zh: '毫升/分' },
  mmolMol: { ko: 'mmol/mol', en: 'mmol/mol', zh: '毫摩尔/摩尔' },
};
