/** 몸 수치 도구가 쓰는 용어 — 핵심 사전(terms.ts)에 합쳐진다 */
import type { Term } from './terms.ts';

export const BODY_TERMS: Record<string, Term> = {
  heightCm:     { ko: '키(cm)',      en: 'Height (cm)' },
  weightKgB:    { ko: '체중(kg)',    en: 'Weight (kg)' },
  ageYears:     { ko: '나이',        en: 'Age' },
  sexFactor:    { ko: '성별(남1·여0)', en: 'Sex (M1 / F0)' },
  waistCm:      { ko: '허리둘레(cm)', en: 'Waist (cm)' },
  hipCm:        { ko: '엉덩이둘레(cm)', en: 'Hip (cm)' },
  neckCm:       { ko: '목둘레(cm)',  en: 'Neck (cm)' },
  bmi:          { ko: 'BMI',         en: 'BMI' },
  bmiTarget:    { ko: '목표 BMI',    en: 'Target BMI' },
  idealWeight:  { ko: '표준 체중',   en: 'Ideal weight' },
  bodyFat:      { ko: '체지방률',    en: 'Body fat' },
  fatMass:      { ko: '체지방량',    en: 'Fat mass' },
  leanMass:     { ko: '제지방량',    en: 'Lean mass' },
  bsa:          { ko: '체표면적',    en: 'Body surface area' },
  whr:          { ko: '허리·엉덩이 비율', en: 'Waist-hip ratio' },
  whtr:         { ko: '허리·키 비율', en: 'Waist-height ratio' },
  ponderal:     { ko: '신체충실지수', en: 'Ponderal index' },

  bmr:          { ko: '기초대사량',  en: 'BMR' },
  tdee:         { ko: '활동대사량',  en: 'TDEE' },
  activity:     { ko: '활동계수',    en: 'Activity factor' },
  calories:     { ko: '칼로리',      en: 'Calories' },
  deficit:      { ko: '하루 적자',   en: 'Daily deficit' },
  targetWeight: { ko: '목표 체중',   en: 'Target weight' },
  weeksNeeded:  { ko: '걸리는 기간', en: 'Time needed' },
  proteinG:     { ko: '단백질',      en: 'Protein' },
  carbG:        { ko: '탄수화물',    en: 'Carbs' },
  fatG:         { ko: '지방',        en: 'Fat' },
  waterMl:      { ko: '권장 수분',   en: 'Water' },
  metValue:     { ko: 'MET(운동 강도)', en: 'MET' },
  minutes:      { ko: '시간(분)',    en: 'Minutes' },
  steps:        { ko: '걸음 수',     en: 'Steps' },
  strideCm:     { ko: '보폭(cm)',    en: 'Stride (cm)' },
  distanceKm:   { ko: '거리(km)',    en: 'Distance (km)' },

  maxHr:        { ko: '최대 심박수', en: 'Max heart rate' },
  restHr:       { ko: '안정 심박수', en: 'Resting HR' },
  hrLow:        { ko: '구간 하한',   en: 'Zone low' },
  hrHigh:       { ko: '구간 상한',   en: 'Zone high' },
  intensity:    { ko: '운동 강도',   en: 'Intensity' },
  vo2max:       { ko: 'VO2max',      en: 'VO2max' },
  liftWeight:   { ko: '든 무게(kg)', en: 'Weight lifted (kg)' },
  reps:         { ko: '반복 횟수',   en: 'Reps' },
  oneRm:        { ko: '1RM',         en: '1RM' },
  paceMin:      { ko: '페이스',      en: 'Pace' },
  timeMin:      { ko: '시간(분)',    en: 'Time (min)' },
  speedKmh:     { ko: '속도(km/h)',  en: 'Speed (km/h)' },
  finishTime:   { ko: '완주 시간',   en: 'Finish time' },
  per100m:      { ko: '100m당',      en: 'Per 100 m' },
  paceSec:      { ko: '초 부분',      en: 'Seconds' },
  cooperDist:   { ko: '12분 달린 거리(m)', en: '12-min distance (m)' },
  hours:        { ko: '시간',         en: 'Hours' },

  fatherCm:     { ko: '아버지 키(cm)', en: "Father's height" },
  motherCm:     { ko: '어머니 키(cm)', en: "Mother's height" },
  childHeight:  { ko: '예측 키',     en: 'Predicted height' },
  birthWeight:  { ko: '출생 체중(g)', en: 'Birth weight (g)' },
  nowWeight:    { ko: '현재 체중(g)', en: 'Current weight (g)' },
  milkMl:       { ko: '하루 수유량', en: 'Daily milk' },
  perFeed:      { ko: '1회 수유량',  en: 'Per feed' },
  feeds:        { ko: '수유 횟수',   en: 'Feeds per day' },
  dosePerKg:    { ko: '용량(mg/kg)', en: 'Dose (mg/kg)' },
  doseMg:       { ko: '1회 용량',    en: 'Dose' },
  bloodMl:      { ko: '혈액량',      en: 'Blood volume' },
  gainPercent:  { ko: '증가율',      en: 'Gain' },

  systolic:     { ko: '수축기 혈압', en: 'Systolic' },
  diastolic:    { ko: '이완기 혈압', en: 'Diastolic' },
  map:          { ko: '평균 동맥압', en: 'Mean arterial pressure' },
  pulsePress:   { ko: '맥압',        en: 'Pulse pressure' },
  totalChol:    { ko: '총콜레스테롤', en: 'Total cholesterol' },
  hdl:          { ko: 'HDL',         en: 'HDL' },
  ldl:          { ko: 'LDL',         en: 'LDL' },
  triglyceride: { ko: '중성지방',    en: 'Triglycerides' },
  cholRatio:    { ko: '총/HDL 비율', en: 'Total : HDL' },
  nonHdl:       { ko: 'non-HDL',     en: 'Non-HDL' },
  glucose:      { ko: '혈당(mg/dL)', en: 'Glucose (mg/dL)' },
  insulin:      { ko: '인슐린(μU/ml)', en: 'Insulin (μU/mL)' },
  homaIr:       { ko: 'HOMA-IR',     en: 'HOMA-IR' },
  a1c:          { ko: '당화혈색소(%)', en: 'HbA1c (%)' },
  avgGlucose:   { ko: '평균 혈당',   en: 'Average glucose' },
  mmolL:        { ko: 'mmol/L',      en: 'mmol/L' },
  mgdl:         { ko: 'mg/dL',       en: 'mg/dL' },

  sleepHours:   { ko: '자는 시간',   en: 'Sleep' },
  cycles:       { ko: '수면 주기',   en: 'Cycles' },
  drinkMl:      { ko: '마신 양(ml)', en: 'Volume (mL)' },
  abv:          { ko: '도수(%)',     en: 'ABV (%)' },
  bac:          { ko: '혈중 알코올', en: 'BAC' },
  clearHours:   { ko: '분해 시간',   en: 'Time to clear' },
  caffeineMg:   { ko: '카페인(mg)',  en: 'Caffeine (mg)' },
  hoursLater:   { ko: '경과 시간',   en: 'Hours later' },
  remainMg:     { ko: '남은 양',     en: 'Remaining' },
};

export const BODY_UNITS: Record<string, Term> = {
  kg:      { ko: 'kg',     en: 'kg' },
  kcal:    { ko: 'kcal',   en: 'kcal' },
  bpm:     { ko: 'bpm',    en: 'bpm' },
  mmHg:    { ko: 'mmHg',   en: 'mmHg' },
  mg:      { ko: 'mg',     en: 'mg' },
  m2:      { ko: '㎡',     en: 'm²' },
  minPerKm:{ ko: '분/km',  en: 'min/km' },
  hour:    { ko: '시간',   en: 'h' },
  week:    { ko: '주',     en: 'wk' },
  mgdlU:   { ko: 'mg/dL',  en: 'mg/dL' },
  mmolU:   { ko: 'mmol/L', en: 'mmol/L' },
  step:    { ko: '걸음',   en: 'steps' },
  minute:  { ko: '분',     en: 'min' },
};
