/**
 * 비율 섹션에서 더 쓰는 용어(3언어).
 *
 * terms.ts의 CORE_TERMS는 세 섹션이 함께 쓰는 것만 둔다. 비율 100종으로 늘리며
 * 생긴 용어는 여기 모아 둔다 — 한 파일이 삼백 줄을 넘으면 무엇이 어디 쓰이는지
 * 안 보인다.
 */
import type { Term } from './terms.ts';

export const RATE_TERMS: Record<string, Term> = {
  /* 할인·가격 */
  freeCount: { ko: '무료 개수', en: 'Free items' },
  payCount: { ko: '사는 개수', en: 'Items paid for' },
  effDiscount: { ko: '실질 할인율', en: 'Real discount' },
  unitPrice: { ko: '개당 가격', en: 'Price each' },
  costPerUse: { ko: '1회당 비용', en: 'Cost per use' },
  costPerMonth: { ko: '한 달당 비용', en: 'Cost a month' },
  costPerDay: { ko: '하루당 비용', en: 'Cost a day' },
  saveAmt: { ko: '절약액', en: 'Saved' },
  shipFee: { ko: '배송비', en: 'Shipping' },
  freeShipMin: { ko: '무료배송 기준', en: 'Free-shipping threshold' },
  addBuy: { ko: '더 담을 금액', en: 'Add to basket' },
  annualFee: { ko: '연회비', en: 'Annual fee' },
  memberPrice: { ko: '회원가', en: 'Member price' },
  breakEvenCount: { ko: '본전 되는 횟수', en: 'Break-even uses' },
  baseRate: { ko: '기준 환율', en: 'Mid-market rate' },
  appliedRate: { ko: '적용 환율', en: 'Rate you got' },
  spread: { ko: '환전 스프레드', en: 'Spread' },
  buyPrice: { ko: '구매가', en: 'Purchase price' },
  depreciation: { ko: '연 감가율', en: 'Yearly depreciation' },
  nowValue: { ko: '현재 가치', en: 'Value now' },
  minMargin: { ko: '지킬 이익률', en: 'Margin floor' },
  maxDiscount: { ko: '최대 할인율', en: 'Discount ceiling' },

  /* 세금·정산 */
  taxRate: { ko: '세율', en: 'Tax rate' },
  taxFreeRate: { ko: '비과세 수익률', en: 'Tax-free rate' },
  equivYield: { ko: '등가 과세 수익률', en: 'Equivalent taxable rate' },
  serviceRate: { ko: '서비스료', en: 'Service charge' },
  feeRateA: { ko: '수수료 A', en: 'First fee' },
  feeRateB: { ko: '수수료 B', en: 'Second fee' },
  totalDays: { ko: '전체 일수', en: 'Days in term' },
  usedDays: { ko: '쓴 일수', en: 'Days used' },
  refundAmt: { ko: '환불액', en: 'Refund' },
  goodsPrice: { ko: '물품 가격', en: 'Item price' },
  dutyRate: { ko: '관세율', en: 'Duty rate' },
  landedCost: { ko: '총 수입 비용', en: 'Landed cost' },
  dutyFreeLimit: { ko: '면세 한도', en: 'Duty-free allowance' },
  taxableAmt: { ko: '과세 대상액', en: 'Taxable amount' },
  workHours: { ko: '월 근무시간', en: 'Hours a month' },
  hourlyNet: { ko: '세후 시급', en: 'Take-home hourly' },

  /* 비율·증감 */
  outerPct: { ko: '바깥 비율', en: 'Outer share' },
  innerPct: { ko: '안쪽 비율', en: 'Inner share' },
  netPercent: { ko: '전체 대비', en: 'Of the whole' },
  changeA: { ko: '1차 변화율', en: 'First change' },
  changeB: { ko: '2차 변화율', en: 'Second change' },
  trueVal: { ko: '참값', en: 'True value' },
  measured: { ko: '측정값', en: 'Measured value' },
  errorPct: { ko: '오차율', en: 'Error' },
  startVal: { ko: '시작 값', en: 'Starting value' },
  endVal: { ko: '목표 값', en: 'Ending value' },
  neededRate: { ko: '필요 연 성장률', en: 'Growth needed' },
  rankNo: { ko: '내 순위', en: 'Your rank' },
  totalPeople: { ko: '전체 인원', en: 'Total people' },
  topPercent: { ko: '상위 비율', en: 'Top percentage' },
  ratioC: { ko: 'C', en: 'C' },
  shareC: { ko: 'C의 몫', en: "C's share" },
  permille: { ko: '천분율(‰)', en: 'Per mille (‰)' },
  workers: { ko: '사람 수', en: 'Workers' },
  daysNeeded: { ko: '걸리는 일수', en: 'Days needed' },
  usedAmt: { ko: '쓴 양', en: 'Used' },
  remainPct: { ko: '남은 비율', en: 'Left' },
  relDiff: { ko: '상대 차이', en: 'Relative gap' },
  indexVal: { ko: '지수', en: 'Index' },

  /* 금융·이자 */
  goalAmount: { ko: '목표 금액', en: 'Goal amount' },
  neededMonthly: { ko: '필요 월 납입', en: 'Monthly needed' },
  monthsNeeded: { ko: '걸리는 개월', en: 'Months needed' },
  futureAmt: { ko: '미래 금액', en: 'Future amount' },
  presentAmt: { ko: '현재 가치', en: 'Present value' },
  discountRate: { ko: '할인율(연)', en: 'Discount rate' },
  affordPay: { ko: '월 상환 여력', en: 'Payment you can manage' },
  maxLoan: { ko: '빌릴 수 있는 금액', en: 'Borrowing limit' },
  prepayAmt: { ko: '중도상환액', en: 'Extra payment' },
  savedInterest: { ko: '아끼는 이자', en: 'Interest saved' },
  days: { ko: '일수', en: 'Days' },
  dailyInterest: { ko: '하루 이자', en: 'Interest a day' },
  firstPrincipal: { ko: '첫 달 원금', en: 'Principal in month 1' },
  firstInterest: { ko: '첫 달 이자', en: 'Interest in month 1' },
  installMonths: { ko: '할부 개월', en: 'Instalments' },
  installFee: { ko: '할부 수수료율', en: 'Instalment fee' },
  apr: { ko: '실질 연이율', en: 'Effective APR' },
  futurePrice: { ko: '미래 가격', en: 'Price later' },
  buyPriceA: { ko: '1차 매수가', en: 'First buy price' },
  buyQtyA: { ko: '1차 수량', en: 'First quantity' },
  buyPriceB: { ko: '2차 매수가', en: 'Second buy price' },
  buyQtyB: { ko: '2차 수량', en: 'Second quantity' },
  avgPrice: { ko: '평균 단가', en: 'Average price' },
  totalQty: { ko: '총 수량', en: 'Total quantity' },
  feeRate: { ko: '왕복 수수료', en: 'Round-trip fee' },
  needReturn: { ko: '본전 수익률', en: 'Return to break even' },
  monthlySpend: { ko: '월 생활비', en: 'Monthly spend' },
  fundMonths: { ko: '버틸 개월', en: 'Months of cover' },
  fundAmount: { ko: '필요 비상금', en: 'Fund needed' },
  savedSoFar: { ko: '지금 모은 금액', en: 'Saved so far' },
  faceValue: { ko: '액면 금액', en: 'Face value' },
  couponRate: { ko: '표면 금리', en: 'Coupon rate' },
  currentYield: { ko: '현재 수익률', en: 'Current yield' },

  /* 농도·배합 */
  origAbv: { ko: '원래 도수', en: 'Starting strength' },
  targetAbv: { ko: '목표 도수', en: 'Target strength' },
  waterAddMl: { ko: '넣을 물(ml)', en: 'Water to add (mL)' },
  syrupPart: { ko: '시럽 몫', en: 'Syrup parts' },
  waterPart: { ko: '물 몫', en: 'Water parts' },
  syrupMl: { ko: '시럽(ml)', en: 'Syrup (mL)' },
  amountA: { ko: 'A의 양', en: 'Amount of A' },
  amountB: { ko: 'B의 양', en: 'Amount of B' },
  evapMl: { ko: '졸일 물', en: 'Water to boil off' },
  stockPct: { ko: '원액 농도', en: 'Stock strength' },
  targetPpm: { ko: '목표 ppm', en: 'Target ppm' },
  stockNeedMl: { ko: '필요 원액', en: 'Stock needed' },
  mainMl: { ko: '주제(ml)', en: 'Base (mL)' },
  hardenerMl: { ko: '경화제(ml)', en: 'Hardener (mL)' },

  /* 점수·달성 */
  currentAvg: { ko: '현재 평균', en: 'Average so far' },
  targetAvg: { ko: '목표 평균', en: 'Average wanted' },
  examsDone: { ko: '치른 과목 수', en: 'Tests taken' },
  examsLeft: { ko: '남은 과목 수', en: 'Tests left' },
  neededScore: { ko: '받아야 할 점수', en: 'Score needed' },
  midScore: { ko: '중간 점수', en: 'Midterm score' },
  finalScoreV: { ko: '기말 점수', en: 'Final score' },
  hwScore: { ko: '과제 점수', en: 'Coursework score' },
  midWeight: { ko: '중간 비중', en: 'Midterm weight' },
  finalWeight: { ko: '기말 비중', en: 'Final weight' },
  weightedScore: { ko: '가중 총점', en: 'Weighted total' },
  passScore: { ko: '합격선', en: 'Pass mark' },
  gapScore: { ko: '남은 점수', en: 'Points short' },
  daysLeft: { ko: '남은 일수', en: 'Days left' },
  perDay: { ko: '하루에 할 양', en: 'Per day' },
};

export const RATE_UNITS: Record<string, Term> = {
  piece: { ko: '개', en: '' },
  day: { ko: '일', en: 'd' },
  hour: { ko: '시간', en: 'h' },
  point: { ko: '점', en: 'pt' },
  permille: { ko: '‰', en: '‰' },
};
