/**
 * 공식 도구 화면의 열 언어 문구 — 비율·몸 수치·도형이 함께 쓴다.
 *
 * 섹션 이름과 소개만 섹션별로 다르고 나머지 라벨("계산식", "결과" 같은 것들)은
 * 전부 같다. 섹션마다 사전을 복사하면 세 벌이 서로 어긋나기 시작하므로
 * 공통 문구는 여기 한 벌만 둔다.
 */
import type { FormulaLang, Lang } from './terms.ts';
import { sectionHasLang, type SectionConfig } from './section.ts';
import {
  ALL_LOCALES10, alternateLanguagesFor, localeLabel, localePrefix, localeTag,
  type AnyLocale10,
} from '../locales.ts';

export const FORMULA_UI = {
  ko: {
    home: '홈',
    inputs: '값 입력',
    result: '결과',
    formula: '계산식',
    interpret: '해석',
    related: '함께 쓰는 계산',
    reset: '기본값으로',
    copy: '결과 복사',
    copied: '✅ 복사했습니다',
    categoryAll: '전체',
    rangeAny: '제한 없음',
    andUp: '이상',
    andBelow: '이하',
    faqHow: (t: string) => `${t}는 어떻게 계산하나요?`,
    faqExample: '예를 들어 계산해 주세요.',
    faqCaution: '주의할 점이 있나요?',
    exampleLead: (input: string, out: string) => `${input}일 때 ${out}입니다.`,
    faqInputs: '어떤 값을 넣어야 하나요?',
    faqInputsLead: (list: string) => `${list}을 넣습니다. 값을 고치면 결과가 바로 다시 계산되고, 빈칸은 0으로 봅니다.`,
    faqAnother: '값을 바꾸면 결과가 어떻게 달라지나요?',
    faqAnotherLead: (pivot: string, a: string, b: string) => `${pivot}만 바꿔 보면 ${a}, ${b}로 달라집니다. 아래 표에 다섯 단계로 정리해 두었습니다.`,
    faqRounding: '결과는 어디까지 반올림하나요?',
    faqRoundingLead: '금액은 1원 단위, 비율은 소수점 한 자리, 그 밖의 값은 소수점 두 자리까지 보여 줍니다. 화면에 보이는 값은 반올림한 것이고 계산은 반올림 전 값으로 이어집니다.',
    articleInputs: '무엇을 넣나요',
    articleSteps: '계산 과정',
    articleTable: '값에 따른 결과',
    articleOutputs: '결과 항목의 뜻',
    articleGlossary: '용어 정리',
    articleCaution: '자주 틀리는 곳',
    articleAbout: '이 계산은 어디에 쓰나요',
    colInput: '입력 항목',
    colDefault: '기본값',
    colRange: '넣을 수 있는 범위',
    colOutput: '결과 항목',
    colValue: '기본값일 때',
    colMeaning: '뜻',
    stepFormula: '공식',
    stepSubstitute: '기본값 대입',
    stepAnswer: '답',
    tableLead: (pivot: string) => `다른 값은 그대로 두고 ${pivot}만 바꿨을 때의 결과입니다.`,
  },
  en: {
    home: 'Home',
    inputs: 'Your numbers',
    result: 'Result',
    formula: 'Formula',
    interpret: 'What it means',
    related: 'Related calculators',
    reset: 'Reset to defaults',
    copy: 'Copy result',
    copied: '✅ Copied',
    categoryAll: 'All',
    rangeAny: 'No limit',
    andUp: 'and up',
    andBelow: 'and below',
    faqHow: (t: string) => `How is ${t} calculated?`,
    faqExample: 'Can you walk through an example?',
    faqCaution: 'Anything to watch out for?',
    exampleLead: (input: string, out: string) => `With ${input}, the answer is ${out}.`,
    faqInputs: 'What do I need to enter?',
    faqInputsLead: (list: string) => `Enter ${list}. The result recalculates as you type, and an empty box counts as zero.`,
    faqAnother: 'How much does the answer move if I change a number?',
    faqAnotherLead: (pivot: string, a: string, b: string) => `Changing only ${pivot} moves the answer to ${a} and ${b}. The table below lays out five steps.`,
    faqRounding: 'How are the numbers rounded?',
    faqRoundingLead: 'Money is shown to the nearest whole unit, percentages to one decimal place and everything else to two. What you see is rounded; the calculation itself carries the unrounded value forward.',
    articleInputs: 'What to enter',
    articleSteps: 'Step by step',
    articleTable: 'Quick reference table',
    articleOutputs: 'What each result means',
    articleGlossary: 'Glossary',
    articleCaution: 'Common mistakes',
    articleAbout: 'When you would use this',
    colInput: 'Input',
    colDefault: 'Default',
    colRange: 'Accepted range',
    colOutput: 'Result',
    colValue: 'At default values',
    colMeaning: 'Meaning',
    stepFormula: 'Formula',
    stepSubstitute: 'With the default numbers',
    stepAnswer: 'Answer',
    tableLead: (pivot: string) => `Results when only ${pivot} changes and everything else stays put.`,
  },
  es: {
    home: 'Inicio',
    inputs: 'Tus números',
    result: 'Resultado',
    formula: 'Fórmula',
    interpret: 'Qué significa',
    related: 'Calculadoras relacionadas',
    reset: 'Volver a los valores por defecto',
    copy: 'Copiar el resultado',
    copied: '✅ Copiado',
    categoryAll: 'Todo',
    rangeAny: 'Sin límite',
    andUp: 'o más',
    andBelow: 'o menos',
    faqHow: (t: string) => `¿Cómo se calcula ${t}?`,
    faqExample: '¿Me lo explicas con un ejemplo?',
    faqCaution: '¿Hay algo que vigilar?',
    exampleLead: (input: string, out: string) => `Con ${input}, el resultado es ${out}.`,
    faqInputs: '¿Qué tengo que escribir?',
    faqInputsLead: (list: string) => `Escribe ${list}. El resultado se recalcula mientras escribes y una casilla vacía cuenta como cero.`,
    faqAnother: '¿Cuánto se mueve el resultado si cambio un número?',
    faqAnotherLead: (pivot: string, a: string, b: string) => `Cambiando solo ${pivot}, el resultado pasa a ${a} y ${b}. La tabla de abajo lo recorre en cinco pasos.`,
    faqRounding: '¿Cómo se redondean los números?',
    faqRoundingLead: 'El dinero se muestra a la unidad, los porcentajes con un decimal y lo demás con dos. Lo que ves está redondeado; el cálculo sigue con el valor sin redondear.',
    articleInputs: 'Qué escribir',
    articleSteps: 'Paso a paso',
    articleTable: 'Tabla de referencia',
    articleOutputs: 'Qué significa cada resultado',
    articleGlossary: 'Glosario',
    articleCaution: 'Errores frecuentes',
    articleAbout: 'Cuándo se usa esto',
    colInput: 'Dato',
    colDefault: 'Por defecto',
    colRange: 'Rango admitido',
    colOutput: 'Resultado',
    colValue: 'Con los valores por defecto',
    colMeaning: 'Significado',
    stepFormula: 'Fórmula',
    stepSubstitute: 'Con los valores por defecto',
    stepAnswer: 'Resultado',
    tableLead: (pivot: string) => `Resultados cuando solo cambia ${pivot} y lo demás se queda igual.`,
  },
  'pt-br': {
    home: 'Início',
    inputs: 'Seus números',
    result: 'Resultado',
    formula: 'Fórmula',
    interpret: 'O que isso quer dizer',
    related: 'Calculadoras relacionadas',
    reset: 'Voltar aos valores padrão',
    copy: 'Copiar o resultado',
    copied: '✅ Copiado',
    categoryAll: 'Tudo',
    rangeAny: 'Sem limite',
    andUp: 'ou mais',
    andBelow: 'ou menos',
    faqHow: (t: string) => `Como se calcula ${t}?`,
    faqExample: 'Pode mostrar com um exemplo?',
    faqCaution: 'Tem algo para ficar de olho?',
    exampleLead: (input: string, out: string) => `Com ${input}, o resultado é ${out}.`,
    faqInputs: 'O que preciso digitar?',
    faqInputsLead: (list: string) => `Digite ${list}. O resultado recalcula enquanto você digita, e campo vazio conta como zero.`,
    faqAnother: 'O quanto o resultado muda se eu mexer num número?',
    faqAnotherLead: (pivot: string, a: string, b: string) => `Mudando só ${pivot}, o resultado vai para ${a} e ${b}. A tabela abaixo mostra cinco passos.`,
    faqRounding: 'Como os números são arredondados?',
    faqRoundingLead: 'Dinheiro aparece na unidade inteira, porcentagens com uma casa decimal e o resto com duas. O que você vê está arredondado; a conta segue com o valor cheio.',
    articleInputs: 'O que digitar',
    articleSteps: 'Passo a passo',
    articleTable: 'Tabela de referência',
    articleOutputs: 'O que cada resultado significa',
    articleGlossary: 'Glossário',
    articleCaution: 'Erros comuns',
    articleAbout: 'Quando isso é usado',
    colInput: 'Campo',
    colDefault: 'Padrão',
    colRange: 'Faixa aceita',
    colOutput: 'Resultado',
    colValue: 'Nos valores padrão',
    colMeaning: 'Significado',
    stepFormula: 'Fórmula',
    stepSubstitute: 'Com os valores padrão',
    stepAnswer: 'Resultado',
    tableLead: (pivot: string) => `Resultados quando só ${pivot} muda e o resto fica parado.`,
  },
  ja: {
    home: 'ホーム',
    inputs: '値の入力',
    result: '結果',
    formula: '計算式',
    interpret: '読み方',
    related: '一緒に使う計算',
    reset: '初期値に戻す',
    copy: '結果をコピー',
    copied: '✅ コピーしました',
    categoryAll: 'すべて',
    rangeAny: '制限なし',
    andUp: '以上',
    andBelow: '以下',
    faqHow: (t: string) => `${t}はどう計算しますか？`,
    faqExample: '例で計算してみせてください。',
    faqCaution: '気をつけることはありますか？',
    exampleLead: (input: string, out: string) => `${input}のとき、${out}です。`,
    faqInputs: 'どの値を入れますか？',
    faqInputsLead: (list: string) => `${list}を入れます。値を直せばすぐ計算し直し、空欄は0として扱います。`,
    faqAnother: '値を変えると結果はどう動きますか？',
    faqAnotherLead: (pivot: string, a: string, b: string) => `${pivot}だけ動かすと${a}、${b}に変わります。下の表に五段階でまとめてあります。`,
    faqRounding: '結果はどこまで四捨五入しますか？',
    faqRoundingLead: '金額は1単位、割合は小数第1位、それ以外は小数第2位まで表示します。画面の値は丸めたもので、計算は丸める前の値で続きます。',
    articleInputs: '何を入れるか',
    articleSteps: '計算の手順',
    articleTable: '値ごとの結果',
    articleOutputs: '結果の項目の意味',
    articleGlossary: '用語',
    articleCaution: 'よくある間違い',
    articleAbout: 'どんなときに使うか',
    colInput: '入力項目',
    colDefault: '初期値',
    colRange: '入れられる範囲',
    colOutput: '結果の項目',
    colValue: '初期値のとき',
    colMeaning: '意味',
    stepFormula: '公式',
    stepSubstitute: '初期値を代入',
    stepAnswer: '答え',
    tableLead: (pivot: string) => `ほかの値はそのままに、${pivot}だけを変えたときの結果です。`,
  },
  de: {
    home: 'Start',
    inputs: 'Deine Zahlen',
    result: 'Ergebnis',
    formula: 'Formel',
    interpret: 'Was das heißt',
    related: 'Passende Rechner',
    reset: 'Auf Standardwerte zurücksetzen',
    copy: 'Ergebnis kopieren',
    copied: '✅ Kopiert',
    categoryAll: 'Alle',
    rangeAny: 'Ohne Grenze',
    andUp: 'und mehr',
    andBelow: 'und weniger',
    faqHow: (t: string) => `Wie wird ${t} berechnet?`,
    faqExample: 'Kannst du das an einem Beispiel zeigen?',
    faqCaution: 'Worauf muss ich achten?',
    exampleLead: (input: string, out: string) => `Bei ${input} lautet die Antwort ${out}.`,
    faqInputs: 'Was muss ich eingeben?',
    faqInputsLead: (list: string) => `Trag ${list} ein. Das Ergebnis rechnet beim Tippen mit, und ein leeres Feld zählt als null.`,
    faqAnother: 'Wie stark bewegt sich das Ergebnis, wenn ich eine Zahl ändere?',
    faqAnotherLead: (pivot: string, a: string, b: string) => `Änderst du nur ${pivot}, wandert das Ergebnis auf ${a} und ${b}. Die Tabelle unten zeigt fünf Stufen.`,
    faqRounding: 'Wie wird gerundet?',
    faqRoundingLead: 'Geldbeträge auf die ganze Einheit, Prozentwerte auf eine Nachkommastelle, alles andere auf zwei. Angezeigt wird gerundet; gerechnet wird mit dem ungerundeten Wert weiter.',
    articleInputs: 'Was du einträgst',
    articleSteps: 'Schritt für Schritt',
    articleTable: 'Ergebnisse im Überblick',
    articleOutputs: 'Was jedes Ergebnis bedeutet',
    articleGlossary: 'Begriffe',
    articleCaution: 'Häufige Fehler',
    articleAbout: 'Wofür du das brauchst',
    colInput: 'Eingabe',
    colDefault: 'Standard',
    colRange: 'Zulässiger Bereich',
    colOutput: 'Ergebnis',
    colValue: 'Bei Standardwerten',
    colMeaning: 'Bedeutung',
    stepFormula: 'Formel',
    stepSubstitute: 'Mit den Standardwerten',
    stepAnswer: 'Antwort',
    tableLead: (pivot: string) => `Ergebnisse, wenn sich nur ${pivot} ändert und alles andere bleibt.`,
  },
  fr: {
    home: 'Accueil',
    inputs: 'Tes valeurs',
    result: 'Résultat',
    formula: 'Formule',
    interpret: 'Ce que ça veut dire',
    related: 'Calculatrices associées',
    reset: 'Revenir aux valeurs par défaut',
    copy: 'Copier le résultat',
    copied: '✅ Copié',
    categoryAll: 'Tout',
    rangeAny: 'Sans limite',
    andUp: 'et plus',
    andBelow: 'et moins',
    faqHow: (t: string) => `Comment calcule-t-on ${t} ?`,
    faqExample: 'Tu peux montrer un exemple ?',
    faqCaution: 'Y a-t-il un piège ?',
    exampleLead: (input: string, out: string) => `Avec ${input}, la réponse est ${out}.`,
    faqInputs: 'Que dois-je saisir ?',
    faqInputsLead: (list: string) => `Saisis ${list}. Le résultat se recalcule à mesure que tu tapes, et une case vide compte pour zéro.`,
    faqAnother: 'De combien bouge le résultat si je change une valeur ?',
    faqAnotherLead: (pivot: string, a: string, b: string) => `En ne changeant que ${pivot}, le résultat passe à ${a} puis ${b}. Le tableau ci-dessous détaille cinq paliers.`,
    faqRounding: 'Comment les nombres sont-ils arrondis ?',
    faqRoundingLead: 'L’argent est affiché à l’unité, les pourcentages à une décimale et le reste à deux. Ce que tu vois est arrondi ; le calcul, lui, continue avec la valeur non arrondie.',
    articleInputs: 'Ce qu’il faut saisir',
    articleSteps: 'Étape par étape',
    articleTable: 'Tableau de référence',
    articleOutputs: 'Ce que veut dire chaque résultat',
    articleGlossary: 'Lexique',
    articleCaution: 'Erreurs fréquentes',
    articleAbout: 'Quand s’en servir',
    colInput: 'Donnée',
    colDefault: 'Par défaut',
    colRange: 'Plage acceptée',
    colOutput: 'Résultat',
    colValue: 'Aux valeurs par défaut',
    colMeaning: 'Signification',
    stepFormula: 'Formule',
    stepSubstitute: 'Avec les valeurs par défaut',
    stepAnswer: 'Réponse',
    tableLead: (pivot: string) => `Résultats quand seul ${pivot} change et que le reste ne bouge pas.`,
  },
  hi: {
    home: 'होम',
    inputs: 'आपके अंक',
    result: 'परिणाम',
    formula: 'सूत्र',
    interpret: 'इसका मतलब',
    related: 'साथ काम आने वाले कैलकुलेटर',
    reset: 'डिफ़ॉल्ट पर लौटें',
    copy: 'परिणाम कॉपी करें',
    copied: '✅ कॉपी हो गया',
    categoryAll: 'सब',
    rangeAny: 'कोई सीमा नहीं',
    andUp: 'या ज़्यादा',
    andBelow: 'या कम',
    faqHow: (t: string) => `${t} कैसे निकाला जाता है?`,
    faqExample: 'एक उदाहरण से समझाइए।',
    faqCaution: 'किस बात का ध्यान रखें?',
    exampleLead: (input: string, out: string) => `${input} पर उत्तर ${out} है।`,
    faqInputs: 'क्या-क्या लिखना है?',
    faqInputsLead: (list: string) => `${list} लिखें। लिखते ही गणना दोबारा हो जाती है, और ख़ाली खाना शून्य माना जाता है।`,
    faqAnother: 'कोई अंक बदलूँ तो परिणाम कितना हिलता है?',
    faqAnotherLead: (pivot: string, a: string, b: string) => `सिर्फ़ ${pivot} बदलने पर परिणाम ${a} और ${b} हो जाता है। नीचे की सारणी में पाँच चरण दिए हैं।`,
    faqRounding: 'अंक कहाँ तक गोल किए जाते हैं?',
    faqRoundingLead: 'रक़म पूरी इकाई तक, प्रतिशत एक दशमलव तक और बाक़ी दो दशमलव तक दिखाए जाते हैं। दिखने वाला अंक गोल किया हुआ है; गणना बिना गोल किए मान से आगे बढ़ती है।',
    articleInputs: 'क्या लिखना है',
    articleSteps: 'चरण दर चरण',
    articleTable: 'मान के हिसाब से परिणाम',
    articleOutputs: 'हर परिणाम का मतलब',
    articleGlossary: 'शब्दावली',
    articleCaution: 'आम ग़लतियाँ',
    articleAbout: 'यह कहाँ काम आता है',
    colInput: 'इनपुट',
    colDefault: 'डिफ़ॉल्ट',
    colRange: 'स्वीकार्य दायरा',
    colOutput: 'परिणाम',
    colValue: 'डिफ़ॉल्ट मान पर',
    colMeaning: 'अर्थ',
    stepFormula: 'सूत्र',
    stepSubstitute: 'डिफ़ॉल्ट मान रखने पर',
    stepAnswer: 'उत्तर',
    tableLead: (pivot: string) => `बाक़ी सब वैसा ही रखकर सिर्फ़ ${pivot} बदलने पर के परिणाम।`,
  },
  'zh-hans': {
    home: '首页',
    inputs: '填入数值',
    result: '结果',
    formula: '算式',
    interpret: '怎么读',
    related: '一起用的计算',
    reset: '回到默认值',
    copy: '复制结果',
    copied: '✅ 已复制',
    categoryAll: '全部',
    rangeAny: '不限',
    andUp: '以上',
    andBelow: '以下',
    faqHow: (t: string) => `${t}怎么算？`,
    faqExample: '举个例子算一遍。',
    faqCaution: '有什么要注意的吗？',
    exampleLead: (input: string, out: string) => `${input}时，是${out}。`,
    faqInputs: '要填哪些值？',
    faqInputsLead: (list: string) => `填${list}。改了值就立刻重算，空着的按0算。`,
    faqAnother: '改了值，结果会怎么动？',
    faqAnotherLead: (pivot: string, a: string, b: string) => `只动${pivot}的话，会变成${a}、${b}。下表分五档列了出来。`,
    faqRounding: '结果四舍五入到哪一位？',
    faqRoundingLead: '金额到个位，比例到小数点后一位，其余到小数点后两位。屏幕上是四舍五入过的，往下算用的还是没舍入的值。',
    articleInputs: '要填什么',
    articleSteps: '算的步骤',
    articleTable: '值不同，结果不同',
    articleOutputs: '结果各项的意思',
    articleGlossary: '术语',
    articleCaution: '常错的地方',
    articleAbout: '什么时候用得上',
    colInput: '输入项',
    colDefault: '默认值',
    colRange: '能填的范围',
    colOutput: '结果项',
    colValue: '默认值时',
    colMeaning: '意思',
    stepFormula: '公式',
    stepSubstitute: '代入默认值',
    stepAnswer: '答案',
    tableLead: (pivot: string) => `其他值不动，只改${pivot}时的结果。`,
  },
  'zh-hant': {
    home: '首頁',
    inputs: '填入數值',
    result: '結果',
    formula: '算式',
    interpret: '怎麼讀',
    related: '一起用的計算',
    reset: '回到預設值',
    copy: '複製結果',
    copied: '✅ 已複製',
    categoryAll: '全部',
    rangeAny: '不限',
    andUp: '以上',
    andBelow: '以下',
    faqHow: (t: string) => `${t}怎麼算？`,
    faqExample: '舉個例子算一遍。',
    faqCaution: '有什麼要注意的嗎？',
    exampleLead: (input: string, out: string) => `${input}時，是${out}。`,
    faqInputs: '要填哪些值？',
    faqInputsLead: (list: string) => `填${list}。改了值就立刻重算，空著的按0算。`,
    faqAnother: '改了值，結果會怎麼動？',
    faqAnotherLead: (pivot: string, a: string, b: string) => `只動${pivot}的話，會變成${a}、${b}。下表分五檔列了出來。`,
    faqRounding: '結果四捨五入到哪一位？',
    faqRoundingLead: '金額到個位，比例到小數點後一位，其餘到小數點後兩位。螢幕上是四捨五入過的，往下算用的還是沒捨入的值。',
    articleInputs: '要填什麼',
    articleSteps: '算的步驟',
    articleTable: '值不同，結果不同',
    articleOutputs: '結果各項的意思',
    articleGlossary: '術語',
    articleCaution: '常錯的地方',
    articleAbout: '什麼時候用得上',
    colInput: '輸入項',
    colDefault: '預設值',
    colRange: '能填的範圍',
    colOutput: '結果項',
    colValue: '預設值時',
    colMeaning: '意思',
    stepFormula: '公式',
    stepSubstitute: '代入預設值',
    stepAnswer: '答案',
    tableLead: (pivot: string) => `其他值不動，只改${pivot}時的結果。`,
  },
} as const;

/**
 * 두 언어만 있는 섹션(나라 정보·사자성어)의 언어 전환 링크.
 *
 * 이 두 섹션은 아직 ko·en뿐이라 목록이 고정이다. 여덟 언어로 넓히면 아래
 * formulaLangs()처럼 레지스트리에서 만들면 된다.
 */
export const FORMULA_LANGS: { lang: Lang; label: string; prefix: string }[] = [
  { lang: 'ko', label: '한국어', prefix: '' },
  { lang: 'en', label: 'EN', prefix: '/en' },
];

/**
 * 이 섹션이 실제로 나가는 언어.
 *
 * 섹션마다 번역된 언어가 다르다. 없는 언어를 링크하면 404이므로 섹션 설정을
 * 보고 있는 것만 낸다. 지금 보고 있는 언어도 포함한다 — 언어 선택 버튼이
 * "지금 이 언어"를 표시해야 하기 때문이다.
 *
 * 거르는 기준은 ALL_LOCALES(여덟)가 아니라 ALL_LOCALES10이다. 여덟짜리로 거르면
 * 중국어를 다 옮겨 놓고도 전환 목록에 안 떠서, 주소를 직접 치지 않는 한 아무도
 * 그 페이지에 닿지 못한다. 실제로 그 상태였다.
 */
export function formulaLocales(section: SectionConfig): AnyLocale10[] {
  return ALL_LOCALES10.filter(l => sectionHasLang(section, l));
}

/**
 * 언어 전환 링크(옛 방식).
 *
 * 지금은 components/LangPicker.tsx가 국기와 원어 이름을 곁들여 그린다.
 * 이 함수는 아직 그쪽으로 안 옮긴 자리를 위해 남겨 둔다.
 */
export function formulaLangs(section: SectionConfig, lang: FormulaLang) {
  return formulaLocales(section)
    .filter(l => l !== lang)
    .map(l => ({ lang: l, label: localeLabel(l), tag: localeTag(l), prefix: localePrefix(l) }));
}

/** hreflang 묶음 — 그 섹션이 실제로 있는 언어만 담는다 */
export function sectionAlternates(section: string, slug?: string, langs?: FormulaLang[]) {
  const path = slug ? `/${section}/${slug}` : `/${section}`;
  return alternateLanguagesFor(path, langs ?? ['ko', 'en']);
}

/** 1,200,000처럼 세 자리마다 끊는다. 세 언어 모두 쉼표를 쓴다 */
export const groupNum = (n: number, digits: number): string => {
  if (!Number.isFinite(n)) return '—';
  return new Intl.NumberFormat('en-US', { maximumFractionDigits: digits }).format(n);
};
