/**
 * 새 스냅테스트의 도구별 문구 — 제목·설명·안내와 항목 이름.
 *
 * 결과 문장은 여기 없다. 그건 측정값에서 만든다(lib/snap/copy.ts의 VOCAB).
 * 여기 적는 것은 **측정으로 만들 수 없는 것**뿐이다.
 *
 * 항목 이름(METRIC)은 도구를 가로질러 함께 쓴다 — '기울기'는 증명사진과
 * 고개 각도가 같이 쓰고, '눈 뜬 정도'는 증명사진과 눈 검사가 같이 쓴다.
 */
import type { L10 } from './copy.ts';

export const NEW_SNAP_SLUGS = [
  // 랜드마크만 보는 다섯
  'id-photo', 'head-pose', 'real-smile', 'eye-open', 'framing',
  // 픽셀까지 보는 다섯
  'lighting', 'sharpness', 'white-balance', 'distance', 'mirror',
  // 비율을 보는 다섯과 픽셀을 보는 둘 (2026-08-07)
  'face-thirds', 'eye-spacing', 'face-shape', 'brows', 'lips',
  'contrast', 'backdrop',
] as const;
export type NewSnapSlug = typeof NEW_SNAP_SLUGS[number];

export interface ToolText {
  title: string;
  desc: string;
  lead: string;
  privacy: string;
}

/** 항목 이름 — 도구가 공유한다 */
export type MetricKey =
  | 'faceSize' | 'centered' | 'eyeLine' | 'level' | 'eyesOpen'
  | 'roll' | 'yaw' | 'pitch'
  | 'mouth' | 'eyeSmile'
  | 'leftEye' | 'rightEye' | 'evenness'
  | 'headroom' | 'thirds' | 'size'
  | 'thirdsUpper' | 'thirdsMiddle' | 'thirdsLower' | 'thirdsBalance'
  | 'eyeGap' | 'eyeEven' | 'eyeSpan'
  | 'shapeRatio' | 'jawWidth' | 'browWidth'
  | 'browLevel' | 'browGap' | 'browLift'
  | 'lipRatio' | 'lipWidth' | 'lipEven'
  | 'contrastRange' | 'contrastPop' | 'backEven' | 'backSeparation'
  | 'sideLight' | 'topLight' | 'backlit' | 'exposure'
  | 'focus' | 'temp' | 'tint'
  | 'shotDistance' | 'faceFill' | 'perspective'
  | 'axisBalance';

export interface SnapTextPack {
  tools: Record<NewSnapSlug, ToolText>;
  metric: Record<MetricKey, string>;
}

export const TOOL_TEXT: L10<SnapTextPack> = {
  ko: {
    tools: {
      'id-photo': { title: '증명사진 규격 검사', desc: '여권·증명사진 규격에 맞는지 다섯 가지로 확인', lead: '얼굴 크기·위치·눈높이·수평·눈 뜸을 실제로 재서 규격과 견줍니다', privacy: '여권 사진 규격 중 숫자로 확인할 수 있는 다섯 가지만 봅니다. 배경·표정·그림자 규정은 숫자로 잴 수 없어 여기서 다루지 않으므로, 이 검사를 통과해도 접수처에서 반려될 수 있습니다.' },
      'head-pose': { title: '고개 각도 측정', desc: '사진 속 고개가 얼마나 기울고 돌아갔는지', lead: '두 눈과 코·턱의 자리로 기울기·좌우 돌림·끄덕임을 잽니다', privacy: '기울기는 두 눈을 잇는 선의 각도라 도(°)로 정확히 나옵니다. 좌우 돌림과 끄덕임은 사진 한 장에 깊이 정보가 없어 각도가 아니라 치우침으로만 냅니다.' },
      'real-smile': { title: '진짜 웃음 지수', desc: '입만 웃는지, 눈까지 웃는지', lead: '입꼬리와 눈이 함께 움직였는지를 재서 뒤센 미소인지 봅니다', privacy: '진짜 즐거울 때는 눈둘레근이 함께 움직여 눈이 좁아진다고 알려져 있습니다(뒤센 미소). 여기서는 입이 웃을 때 눈이 얼마나 좁아졌는지만 재며, 감정을 판정하지 않습니다.' },
      'eye-open': { title: '눈 뜬 정도 측정', desc: '눈 감긴 사진인지, 좌우가 고른지', lead: '눈의 세로·가로 비(EAR)로 얼마나 떴는지 잽니다', privacy: '감은 눈과 뜬 눈을 가르는 흔한 방법인 EAR로 잽니다. 눈 크기가 작은 것과 눈을 감은 것은 다르며, 이 값은 눈 모양이 아니라 여는 정도를 봅니다.' },
      framing: { title: '인물 구도 분석', desc: '삼분할·머리 위 여백으로 보는 구도', lead: '얼굴이 화면 어디에 얼마나 크게 놓였는지를 잽니다', privacy: '삼분할선과 정중앙을 모두 정석으로 칩니다. 인물 사진에서 가운데 구도는 흔하고 틀린 것이 아니므로, 삼분할만 옳다고 말하지 않습니다.' },
      'lighting': { title: '조명 방향 분석', desc: '빛이 어디서 오는지, 역광인지', lead: '얼굴의 좌우·위아래 밝기와 배경 밝기를 재서 빛의 방향을 짚습니다', privacy: '밝기는 사진에서 실제로 잰 값입니다. 다만 얼굴에 드리운 그림자와 원래 피부색을 구분하지는 못하므로, 한쪽이 어둡게 나와도 조명 탓이 아닐 수 있습니다.' },
      'sharpness': { title: '사진 선명도 검사', desc: '흔들렸는지, 초점이 맞았는지', lead: '얼굴 영역의 이웃 픽셀 차이로 또렷함을 잽니다', privacy: '얼굴 안쪽만 잽니다. 배경을 흐리게 찍은 인물 사진에서 전체를 재면 흔들렸다고 나오는데, 정작 얼굴은 또렷한 좋은 사진이기 때문입니다.' },
      'white-balance': { title: '화이트밸런스 검사', desc: '사진 색이 어느 쪽으로 치우쳤는지', lead: '화면 전체 색 평균으로 색온도와 색조의 치우침을 잽니다', privacy: '화면 평균이 회색이어야 한다고 보고 잽니다(회색세계 가정). 노을이나 단풍처럼 한 색이 실제로 많은 사진은 치우쳤다고 나오는데, 그건 이 가정의 한계이지 사진이 잘못된 것이 아닙니다.' },
      'distance': { title: '촬영 거리 어림', desc: '얼마나 가까이서 찍었고 얼굴이 얼마나 왜곡됐는지', lead: '얼굴 너비가 화면에서 차지하는 몫과 렌즈 화각으로 거리를 어림합니다', privacy: '사진에 렌즈 화각이 적혀 있지 않고 머리 너비도 사람마다 달라, 이것은 측정이 아니라 어림입니다. 스마트폰 주카메라(약 70도)와 성인 머리 너비 145mm를 가정합니다.' },
      'mirror': { title: '좌우 합성 얼굴', desc: '왼쪽만·오른쪽만으로 만든 두 얼굴', lead: '콧대를 축으로 왼쪽 반쪽과 오른쪽 반쪽을 각각 거울처럼 붙여 봅니다', privacy: '재는 것이 아니라 실제로 이미지를 뒤집어 붙인 것입니다. 정면이 아닌 사진에서는 두 얼굴이 크게 달라지는데, 그건 얼굴이 비대칭이어서가 아니라 고개가 돌아가 있어서입니다.' },
      'face-thirds': { title: "얼굴 삼등분 검사", desc: "이마·코·턱 세 칸의 비율", lead: "눈썹 윗선·코 밑·턱 끝을 짚어 세 칸의 높이를 잽니다", privacy: "이마 높이는 잴 수 없습니다 — 얼굴 점 예순여덟 개에는 머리카락 경계가 없기 때문입니다. 그래서 위 칸은 가운데 칸과 같다고 두고 어림합니다. 셋이 고르다는 기준은 오래된 화법 관습이지 아름다움의 기준이 아닙니다." },
      'eye-spacing': { title: "눈 간격 검사", desc: "두 눈 사이가 눈 하나 너비인지", lead: "두 눈 사이 거리를 한쪽 눈 너비로 나눠 잽니다", privacy: "얼굴 너비를 다섯 등분했을 때 눈 하나가 한 칸을 차지한다는 어림이 널리 쓰입니다. 즉 두 눈 사이가 눈 하나 너비와 같을 때 1이 됩니다. 널리 쓰이는 어림일 뿐 아름다움의 기준이 아닙니다." },
      'face-shape': { title: "얼굴형 판별", desc: "계란형·둥근형·각진형·긴 얼굴·하트형", lead: "세로가로비와 턱·이마 너비 세 값으로 가릅니다", privacy: "사람의 얼굴은 경계에 걸치는 경우가 많아, 이름 하나만 주면 왜 그런지 알 수 없습니다. 그래서 가른 근거가 된 세 값을 함께 보여 줍니다. 사진의 각도에 따라 결과가 달라지므로 정면 사진에서 보세요." },
      'brows': { title: "눈썹 균형 검사", desc: "좌우 높이와 눈썹 사이 간격", lead: "눈썹의 좌우 높이 차이를 얼굴 크기로 나눠 잽니다", privacy: "픽셀 그대로 재면 가까이서 찍은 사진일수록 나쁘게 나오므로 얼굴 크기로 나눕니다. 눈썹은 표정에 따라 실제로 움직이니, 힘을 뺀 얼굴에서 보는 것이 맞습니다." },
      'lips': { title: "입술 비율 검사", desc: "윗입술과 아랫입술의 두께 비", lead: "입술 바깥선과 안쪽선 사이를 재서 위아래 두께를 구합니다", privacy: "얼굴 점에 입술 안쪽 여덟 점이 없으면 두께를 잴 수 없습니다. 그럴 때는 모른다고 말하고 너비만 보여 줍니다 — 없는 점을 바깥 점으로 대신하면 \"윗입술이 없다\"는 뜻의 숫자가 그럴듯하게 나오기 때문입니다." },
      'contrast': { title: "사진 대비 검사", desc: "밋밋한지, 한쪽이 탔는지", lead: "얼굴 안 네 구역의 밝기 폭과 배경과의 차이를 잽니다", privacy: "대비는 클수록 좋은 것이 아닙니다. 폭이 너무 작으면 밋밋하고 너무 크면 한쪽이 날아간 것이라, 가운데가 가장 좋습니다. 조명 검사가 \"빛이 어느 쪽에서 오는가\"라면 이것은 \"얼마나 또렷한가\"입니다." },
      'backdrop': { title: "배경 정리도 검사", desc: "증명사진에 쓸 만큼 배경이 깔끔한지", lead: "배경의 밝기 표준편차와 얼굴과의 밝기 차이를 잽니다", privacy: "배경이 고르다는 것은 밝기가 한결같다는 뜻입니다. 무늬나 물건이 있으면 표준편차가 커집니다. 색은 보지 않으므로, 흰 배경인지 파란 배경인지는 이 검사가 알려 주지 못합니다." },
    },
    metric: {
      thirdsUpper: "위 칸",
      thirdsMiddle: "가운데 칸",
      thirdsLower: "아래 칸",
      thirdsBalance: "세 칸 고름",
      eyeGap: "눈 사이 비율",
      eyeEven: "두 눈 크기 고름",
      eyeSpan: "눈이 차지하는 폭",
      shapeRatio: "세로 대 가로",
      jawWidth: "턱 너비",
      browWidth: "이마 너비",
      browLevel: "좌우 높이 고름",
      browGap: "눈썹 사이",
      browLift: "눈썹 높이",
      lipRatio: "위아래 두께 비",
      lipWidth: "입 너비",
      lipEven: "입꼬리 고름",
      contrastRange: "얼굴 안 밝기 폭",
      contrastPop: "배경과의 차",
      backEven: "배경 고름",
      backSeparation: "인물 분리",
      sideLight: '좌우 밝기 차', topLight: '위아래 밝기 차', backlit: '역광', exposure: '노출', focus: '초점', temp: '색온도', tint: '색조', shotDistance: '어림 거리', faceFill: '얼굴이 차지하는 몫', perspective: '원근 왜곡', axisBalance: '좌우 폭 균형',
      faceSize: '얼굴 크기', centered: '좌우 가운데', eyeLine: '눈높이', level: '수평', eyesOpen: '눈 뜸',
      roll: '기울기', yaw: '좌우 돌림', pitch: '끄덕임',
      mouth: '입이 웃는 정도', eyeSmile: '눈이 웃는 정도',
      leftEye: '왼쪽 눈', rightEye: '오른쪽 눈', evenness: '좌우 고름',
      headroom: '머리 위 여백', thirds: '삼분할', size: '얼굴이 차지하는 몫',
    },
  },
  en: {
    tools: {
      'id-photo': { title: 'ID Photo Check', desc: 'Five checks against passport photo rules', lead: 'Face size, position, eye line, tilt and open eyes, measured and compared to the spec', privacy: 'Only the five parts of the passport spec that can be measured as numbers. Background, expression and shadow rules cannot be measured, so passing here does not guarantee acceptance.' },
      'head-pose': { title: 'Head Angle', desc: 'How much the head is tilted and turned', lead: 'Tilt, turn and nod measured from the eyes, nose and chin', privacy: 'Tilt comes from the angle of the line between the eyes, so it is exact in degrees. Turn and nod have no depth information in a single photo, so they are given as a lean, not an angle.' },
      'real-smile': { title: 'Real Smile Score', desc: 'Is it only the mouth, or the eyes too?', lead: 'Measures whether the corners of the mouth and the eyes moved together', privacy: 'A genuine smile is widely described as also narrowing the eyes (a Duchenne smile). This measures only how much the eyes narrow while the mouth smiles — it does not judge how you feel.' },
      'eye-open': { title: 'Eye Openness', desc: 'Blinked photo, and are both eyes even?', lead: 'Measured with the eye aspect ratio (EAR)', privacy: 'EAR is a common way to tell a shut eye from an open one. Small eyes and closed eyes are not the same thing — this reads how far the eyes are opened, not their shape.' },
      framing: { title: 'Portrait Framing', desc: 'Thirds and headroom', lead: 'Where the face sits in the frame, and how much of it fills', privacy: 'Both the thirds lines and dead centre count as correct. Centred portraits are common and not a mistake, so this does not treat the rule of thirds as the only right answer.' },
      'lighting': { title: 'Lighting Direction', desc: 'Where the light comes from, and is it backlit?', lead: 'Reads the light direction from the brightness across the face and behind it', privacy: 'The brightness is measured from your photo. It cannot separate a shadow from your natural skin tone, so a darker side is not always the light.' },
      'sharpness': { title: 'Photo Sharpness', desc: 'Shaken, or in focus?', lead: 'Measures crispness from neighbouring-pixel differences inside the face', privacy: 'Only the face is measured. On a portrait with a deliberately blurred background, measuring the whole frame would call a perfectly sharp face blurry.' },
      'white-balance': { title: 'White Balance', desc: 'Which way the colour leans', lead: 'Reads colour temperature and tint from the average colour of the frame', privacy: 'This assumes the average of a frame should be grey (the grey-world assumption). A sunset or autumn leaves will read as leaning — that is the limit of the assumption, not a fault in the photo.' },
      'distance': { title: 'Shooting Distance', desc: 'How close the camera was, and how much the face is stretched', lead: 'Estimates the distance from how much of the frame the face fills and the lens angle', privacy: 'The lens angle is not stored in the photo and head width varies, so this is an estimate, not a measurement. It assumes a phone main camera (about 70 degrees) and a 145 mm head.' },
      'mirror': { title: 'Mirror Faces', desc: 'Two faces: left half doubled, right half doubled', lead: 'Mirrors each half of your face across the bridge of the nose', privacy: 'Nothing is scored here — the image really is flipped and joined. In a photo taken off-centre the two faces differ a lot, and that is the head being turned, not an asymmetric face.' },
      'face-thirds': { title: "Face Thirds", desc: "How the forehead, nose and chin sections compare", lead: "Measures the three sections from the brow line, the base of the nose and the chin", privacy: "Forehead height cannot be measured — the sixty-eight face points contain no hairline. So the upper third is estimated as equal to the middle one. \"Even thirds\" is an old drawing convention, not a standard of beauty." },
      'eye-spacing': { title: "Eye Spacing", desc: "Whether the gap between the eyes equals one eye width", lead: "Divides the distance between the eyes by the width of one eye", privacy: "A common rule of thumb splits the face into five widths with one eye filling each. That means the gap equals one eye width when the value is 1. It is a rule of thumb, not a standard of beauty." },
      'face-shape': { title: "Face Shape", desc: "Oval, round, square, long or heart", lead: "Decided from the height-to-width ratio and the jaw and forehead widths", privacy: "Real faces often sit on the border between two shapes, and a name alone tells you nothing about why. So the three values behind the call are shown too. The result shifts with the angle of the photo, so use a straight-on shot." },
      'brows': { title: "Brow Balance", desc: "Left-right height and the gap between the brows", lead: "Divides the left-right height difference by the size of the face", privacy: "Measured in raw pixels, a closer photo always scores worse, so the difference is divided by face size. Brows genuinely move with expression, so judge them on a relaxed face." },
      'lips': { title: "Lip Proportions", desc: "How the upper and lower lip thicknesses compare", lead: "Takes the thickness from the gap between the outer and inner lip lines", privacy: "If the face points do not include the eight inner lip points, thickness cannot be measured. In that case it says so and shows only the width — substituting the outer points would produce a plausible-looking number meaning \"there is no upper lip\"." },
      'contrast': { title: "Photo Contrast", desc: "Whether it is flat or blown out on one side", lead: "Measures the brightness range across four regions of the face and the gap to the background", privacy: "More contrast is not better. Too small a range looks flat and too large means one side is blown out, so the middle is best. Where the lighting check asks which direction the light comes from, this one asks how crisp the photo is." },
      'backdrop': { title: "Backdrop Check", desc: "Whether the background is clean enough for an ID photo", lead: "Measures the standard deviation of background brightness and its gap from the face", privacy: "An even background means the brightness barely varies. Patterns or objects push the standard deviation up. Colour is not examined, so this check cannot tell you whether the background is white or blue." },
    },
    metric: {
      thirdsUpper: "Upper third",
      thirdsMiddle: "Middle third",
      thirdsLower: "Lower third",
      thirdsBalance: "Balance of the three",
      eyeGap: "Gap between eyes",
      eyeEven: "Eyes matched",
      eyeSpan: "Eye span",
      shapeRatio: "Height to width",
      jawWidth: "Jaw width",
      browWidth: "Forehead width",
      browLevel: "Brows level",
      browGap: "Gap between brows",
      browLift: "Brow height",
      lipRatio: "Upper to lower",
      lipWidth: "Mouth width",
      lipEven: "Corners level",
      contrastRange: "Range within the face",
      contrastPop: "Against the background",
      backEven: "Background evenness",
      backSeparation: "Subject separation",
      sideLight: 'Side difference', topLight: 'Top–bottom difference', backlit: 'Backlight', exposure: 'Exposure', focus: 'Focus', temp: 'Temperature', tint: 'Tint', shotDistance: 'Estimated distance', faceFill: 'Face fills', perspective: 'Perspective stretch', axisBalance: 'Half-width balance',
      faceSize: 'Face size', centered: 'Centred', eyeLine: 'Eye line', level: 'Level', eyesOpen: 'Eyes open',
      roll: 'Tilt', yaw: 'Turn', pitch: 'Nod',
      mouth: 'Mouth smiling', eyeSmile: 'Eyes smiling',
      leftEye: 'Left eye', rightEye: 'Right eye', evenness: 'Both even',
      headroom: 'Headroom', thirds: 'Thirds', size: 'Face fills',
    },
  },
  es: {
    tools: {
      'id-photo': { title: 'Foto de carnet', desc: 'Cinco comprobaciones frente a las normas de pasaporte', lead: 'Tamaño, posición, línea de ojos, inclinación y ojos abiertos, medidos y comparados con la norma', privacy: 'Solo las cinco partes de la norma que pueden medirse como números. El fondo, la expresión y las sombras no se pueden medir, así que pasar aquí no garantiza la aceptación.' },
      'head-pose': { title: 'Ángulo de la cabeza', desc: 'Cuánto está inclinada y girada', lead: 'Inclinación, giro y cabeceo medidos desde ojos, nariz y mentón', privacy: 'La inclinación sale del ángulo de la línea entre los ojos, así que es exacta en grados. El giro y el cabeceo no tienen profundidad en una sola foto, por eso se dan como desviación y no como ángulo.' },
      'real-smile': { title: 'Sonrisa real', desc: '¿Solo la boca, o también los ojos?', lead: 'Mide si las comisuras y los ojos se movieron juntos', privacy: 'Se suele decir que la sonrisa genuina también estrecha los ojos (sonrisa de Duchenne). Aquí solo se mide cuánto se estrechan mientras la boca sonríe; no se juzga lo que sientes.' },
      'eye-open': { title: 'Apertura de ojos', desc: '¿Salió con los ojos cerrados? ¿Están parejos?', lead: 'Medido con la relación de aspecto del ojo (EAR)', privacy: 'El EAR es una forma habitual de distinguir un ojo cerrado de uno abierto. Ojos pequeños y ojos cerrados no son lo mismo: esto lee cuánto se abren, no su forma.' },
      framing: { title: 'Encuadre del retrato', desc: 'Tercios y aire sobre la cabeza', lead: 'Dónde queda la cara en el encuadre y cuánto ocupa', privacy: 'Tanto las líneas de tercios como el centro exacto cuentan como correctos. El retrato centrado es común y no es un error.' },
      'lighting': { title: 'Dirección de la luz', desc: 'De dónde viene la luz, ¿hay contraluz?', lead: 'Lee la dirección de la luz por el brillo de la cara y del fondo', privacy: 'El brillo se mide en tu foto. No puede separar una sombra de tu tono de piel, así que un lado oscuro no siempre es la luz.' },
      'sharpness': { title: 'Nitidez de la foto', desc: '¿Movida o enfocada?', lead: 'Mide la nitidez por la diferencia entre píxeles vecinos dentro de la cara', privacy: 'Solo se mide la cara. En un retrato con fondo desenfocado a propósito, medir todo el cuadro llamaría movida a una cara perfectamente nítida.' },
      'white-balance': { title: 'Balance de blancos', desc: 'Hacia dónde se inclina el color', lead: 'Lee la temperatura y el matiz desde el color medio del cuadro', privacy: 'Supone que la media del cuadro debería ser gris (hipótesis del mundo gris). Un atardecer saldrá inclinado: es el límite de la hipótesis, no un fallo de la foto.' },
      'distance': { title: 'Distancia de disparo', desc: 'Qué tan cerca estaba la cámara y cuánto se estira la cara', lead: 'Estima la distancia por lo que ocupa la cara y el ángulo del objetivo', privacy: 'El ángulo del objetivo no está en la foto y el ancho de cabeza varía, así que es una estimación. Supone cámara principal de móvil (unos 70 grados) y cabeza de 145 mm.' },
      'mirror': { title: 'Caras espejo', desc: 'Dos caras: mitad izquierda y mitad derecha duplicadas', lead: 'Refleja cada mitad de la cara sobre el puente de la nariz', privacy: 'Aquí no se puntúa nada: la imagen se voltea y se une de verdad. En una foto de perfil las dos caras difieren mucho, y eso es la cabeza girada, no una cara asimétrica.' },
      'face-thirds': { title: "Tercios del rostro", desc: "Cómo se comparan frente, nariz y mentón", lead: "Mide las tres secciones desde la línea de las cejas, la base de la nariz y el mentón", privacy: "La altura de la frente no se puede medir: los sesenta y ocho puntos faciales no incluyen el nacimiento del pelo. Por eso el tercio superior se estima igual al medio. \"Tercios iguales\" es una vieja convención de dibujo, no un canon de belleza." },
      'eye-spacing': { title: "Separación de los ojos", desc: "Si el hueco entre los ojos equivale a un ojo", lead: "Divide la distancia entre los ojos por la anchura de un ojo", privacy: "Una regla común divide la cara en cinco anchuras, cada una ocupada por un ojo. Así, el hueco equivale a un ojo cuando el valor es 1. Es una regla práctica, no un canon de belleza." },
      'face-shape': { title: "Forma del rostro", desc: "Ovalado, redondo, cuadrado, alargado o de corazón", lead: "Se decide por la relación alto-ancho y las anchuras de mandíbula y frente", privacy: "Las caras reales suelen quedar en el límite entre dos formas, y un nombre por sí solo no dice por qué. Por eso se muestran también los tres valores en que se basa. El resultado cambia con el ángulo de la foto, así que usa una toma frontal." },
      'brows': { title: "Equilibrio de las cejas", desc: "Altura izquierda-derecha y separación entre cejas", lead: "Divide la diferencia de altura izquierda-derecha por el tamaño de la cara", privacy: "Medida en píxeles, una foto más cercana siempre puntúa peor, así que la diferencia se divide por el tamaño de la cara. Las cejas se mueven de verdad con la expresión, así que júzgalas con la cara relajada." },
      'lips': { title: "Proporción de los labios", desc: "Cómo se comparan los grosores del labio superior e inferior", lead: "Toma el grosor del hueco entre las líneas externa e interna del labio", privacy: "Si los puntos faciales no incluyen los ocho puntos internos del labio, el grosor no se puede medir. En ese caso lo dice y muestra solo la anchura: sustituirlos por los externos daría un número plausible que significa \"no hay labio superior\"." },
      'contrast': { title: "Contraste de la foto", desc: "Si está plana o quemada por un lado", lead: "Mide el rango de brillo en cuatro zonas de la cara y la diferencia con el fondo", privacy: "Más contraste no es mejor. Un rango demasiado pequeño se ve plano y uno demasiado grande significa que un lado está quemado, así que lo mejor está en medio. Si el test de luz pregunta de dónde viene la luz, este pregunta qué tan nítida es la foto." },
      'backdrop': { title: "Comprobación del fondo", desc: "Si el fondo está lo bastante limpio para una foto de carné", lead: "Mide la desviación típica del brillo del fondo y su diferencia con la cara", privacy: "Un fondo uniforme significa que el brillo apenas varía. Los estampados u objetos elevan la desviación típica. No se examina el color, así que esta prueba no puede decirte si el fondo es blanco o azul." },
    },
    metric: {
      thirdsUpper: "Tercio superior",
      thirdsMiddle: "Tercio medio",
      thirdsLower: "Tercio inferior",
      thirdsBalance: "Equilibrio de los tres",
      eyeGap: "Separación de los ojos",
      eyeEven: "Ojos igualados",
      eyeSpan: "Anchura de los ojos",
      shapeRatio: "Alto respecto al ancho",
      jawWidth: "Anchura de la mandíbula",
      browWidth: "Anchura de la frente",
      browLevel: "Cejas niveladas",
      browGap: "Separación de las cejas",
      browLift: "Altura de las cejas",
      lipRatio: "Superior respecto al inferior",
      lipWidth: "Anchura de la boca",
      lipEven: "Comisuras niveladas",
      contrastRange: "Rango dentro de la cara",
      contrastPop: "Frente al fondo",
      backEven: "Uniformidad del fondo",
      backSeparation: "Separación del sujeto",
      sideLight: 'Diferencia lateral', topLight: 'Diferencia arriba-abajo', backlit: 'Contraluz', exposure: 'Exposición', focus: 'Enfoque', temp: 'Temperatura', tint: 'Matiz', shotDistance: 'Distancia estimada', faceFill: 'La cara ocupa', perspective: 'Estiramiento', axisBalance: 'Equilibrio de mitades',
      faceSize: 'Tamaño de la cara', centered: 'Centrado', eyeLine: 'Línea de ojos', level: 'Nivelado', eyesOpen: 'Ojos abiertos',
      roll: 'Inclinación', yaw: 'Giro', pitch: 'Cabeceo',
      mouth: 'Boca sonriendo', eyeSmile: 'Ojos sonriendo',
      leftEye: 'Ojo izquierdo', rightEye: 'Ojo derecho', evenness: 'Ambos parejos',
      headroom: 'Aire arriba', thirds: 'Tercios', size: 'La cara ocupa',
    },
  },
  'pt-br': {
    tools: {
      'id-photo': { title: 'Foto 3x4', desc: 'Cinco conferências frente às regras de passaporte', lead: 'Tamanho, posição, linha dos olhos, inclinação e olhos abertos, medidos e comparados à norma', privacy: 'Só as cinco partes da norma que dá para medir como número. Fundo, expressão e sombra não são mensuráveis, então passar aqui não garante aceitação.' },
      'head-pose': { title: 'Ângulo da cabeça', desc: 'O quanto está inclinada e virada', lead: 'Inclinação, giro e aceno medidos pelos olhos, nariz e queixo', privacy: 'A inclinação vem do ângulo da linha entre os olhos, então é exata em graus. Giro e aceno não têm profundidade numa foto só, por isso saem como desvio, não como ângulo.' },
      'real-smile': { title: 'Sorriso de verdade', desc: 'Só a boca, ou os olhos também?', lead: 'Mede se os cantos da boca e os olhos se moveram juntos', privacy: 'Costuma-se dizer que o sorriso genuíno também estreita os olhos (sorriso de Duchenne). Aqui se mede apenas o quanto eles estreitam enquanto a boca sorri; não se julga o que você sente.' },
      'eye-open': { title: 'Abertura dos olhos', desc: 'Saiu de olho fechado? Os dois estão iguais?', lead: 'Medido pela razão de aspecto do olho (EAR)', privacy: 'O EAR é um jeito comum de separar olho fechado de olho aberto. Olho pequeno e olho fechado não são a mesma coisa: isto lê o quanto abrem, não o formato.' },
      framing: { title: 'Enquadramento', desc: 'Terços e espaço acima da cabeça', lead: 'Onde o rosto fica no quadro e o quanto ele ocupa', privacy: 'Tanto as linhas dos terços quanto o centro exato contam como certos. Retrato centralizado é comum e não é erro.' },
      'lighting': { title: 'Direção da luz', desc: 'De onde vem a luz, tem contraluz?', lead: 'Lê a direção da luz pelo brilho do rosto e do fundo', privacy: 'O brilho é medido na sua foto. Não dá para separar uma sombra do seu tom de pele, então um lado escuro nem sempre é a luz.' },
      'sharpness': { title: 'Nitidez da foto', desc: 'Tremida ou em foco?', lead: 'Mede a nitidez pela diferença entre pixels vizinhos dentro do rosto', privacy: 'Só o rosto é medido. Num retrato com fundo desfocado de propósito, medir o quadro inteiro chamaria de tremido um rosto perfeitamente nítido.' },
      'white-balance': { title: 'Balanço de branco', desc: 'Para que lado a cor pende', lead: 'Lê a temperatura e o matiz pela cor média do quadro', privacy: 'Supõe que a média do quadro deveria ser cinza (hipótese do mundo cinza). Um pôr do sol vai sair pendendo: é o limite da hipótese, não um defeito da foto.' },
      'distance': { title: 'Distância do clique', desc: 'O quão perto a câmera estava e o quanto o rosto estica', lead: 'Estima a distância pelo quanto o rosto ocupa e pelo ângulo da lente', privacy: 'O ângulo da lente não está na foto e a largura da cabeça varia, então isto é uma estimativa. Supõe câmera principal de celular (uns 70 graus) e cabeça de 145 mm.' },
      'mirror': { title: 'Rostos espelhados', desc: 'Dois rostos: metade esquerda e metade direita duplicadas', lead: 'Espelha cada metade do rosto sobre o dorso do nariz', privacy: 'Aqui nada é pontuado: a imagem é realmente virada e unida. Numa foto de lado os dois rostos ficam bem diferentes, e isso é a cabeça virada, não um rosto assimétrico.' },
      'face-thirds': { title: "Terços do rosto", desc: "Como se comparam testa, nariz e queixo", lead: "Mede as três seções a partir da linha das sobrancelhas, da base do nariz e do queixo", privacy: "A altura da testa não pode ser medida: os sessenta e oito pontos faciais não incluem a linha do cabelo. Por isso o terço superior é estimado igual ao do meio. \"Terços iguais\" é uma velha convenção de desenho, não um padrão de beleza." },
      'eye-spacing': { title: "Distância entre os olhos", desc: "Se o vão entre os olhos equivale a um olho", lead: "Divide a distância entre os olhos pela largura de um olho", privacy: "Uma regra comum divide o rosto em cinco larguras, cada uma ocupada por um olho. Assim, o vão equivale a um olho quando o valor é 1. É uma regra prática, não um padrão de beleza." },
      'face-shape': { title: "Formato do rosto", desc: "Oval, redondo, quadrado, alongado ou coração", lead: "Definido pela relação altura-largura e pelas larguras do maxilar e da testa", privacy: "Rostos reais costumam ficar no limite entre dois formatos, e só o nome não diz por quê. Por isso os três valores que embasam a decisão também aparecem. O resultado muda com o ângulo da foto, então use uma tomada frontal." },
      'brows': { title: "Equilíbrio das sobrancelhas", desc: "Altura esquerda-direita e o vão entre elas", lead: "Divide a diferença de altura esquerda-direita pelo tamanho do rosto", privacy: "Medida em pixels, uma foto mais próxima sempre pontua pior, então a diferença é dividida pelo tamanho do rosto. As sobrancelhas realmente se mexem com a expressão, então avalie com o rosto relaxado." },
      'lips': { title: "Proporção dos lábios", desc: "Como se comparam as espessuras do lábio superior e inferior", lead: "Tira a espessura do vão entre as linhas externa e interna do lábio", privacy: "Se os pontos faciais não incluem os oito pontos internos do lábio, a espessura não pode ser medida. Nesse caso ele avisa e mostra só a largura: substituir pelos externos daria um número plausível que significa \"não há lábio superior\"." },
      'contrast': { title: "Contraste da foto", desc: "Se está chapada ou estourada de um lado", lead: "Mede a faixa de brilho em quatro regiões do rosto e a diferença para o fundo", privacy: "Mais contraste não é melhor. Uma faixa pequena demais fica chapada e uma grande demais significa que um lado estourou, então o melhor está no meio. Se o teste de luz pergunta de onde vem a luz, este pergunta o quanto a foto é nítida." },
      'backdrop': { title: "Verificação do fundo", desc: "Se o fundo está limpo o bastante para foto de documento", lead: "Mede o desvio padrão do brilho do fundo e a diferença dele para o rosto", privacy: "Um fundo uniforme significa que o brilho quase não varia. Estampas ou objetos aumentam o desvio padrão. A cor não é examinada, então esta verificação não diz se o fundo é branco ou azul." },
    },
    metric: {
      thirdsUpper: "Terço superior",
      thirdsMiddle: "Terço médio",
      thirdsLower: "Terço inferior",
      thirdsBalance: "Equilíbrio dos três",
      eyeGap: "Distância entre os olhos",
      eyeEven: "Olhos iguais",
      eyeSpan: "Largura dos olhos",
      shapeRatio: "Altura sobre largura",
      jawWidth: "Largura do maxilar",
      browWidth: "Largura da testa",
      browLevel: "Sobrancelhas niveladas",
      browGap: "Distância entre sobrancelhas",
      browLift: "Altura das sobrancelhas",
      lipRatio: "Superior sobre inferior",
      lipWidth: "Largura da boca",
      lipEven: "Cantos nivelados",
      contrastRange: "Faixa dentro do rosto",
      contrastPop: "Contra o fundo",
      backEven: "Uniformidade do fundo",
      backSeparation: "Separação do sujeito",
      sideLight: 'Diferença lateral', topLight: 'Diferença cima-baixo', backlit: 'Contraluz', exposure: 'Exposição', focus: 'Foco', temp: 'Temperatura', tint: 'Matiz', shotDistance: 'Distância estimada', faceFill: 'O rosto ocupa', perspective: 'Esticamento', axisBalance: 'Equilíbrio das metades',
      faceSize: 'Tamanho do rosto', centered: 'Centralizado', eyeLine: 'Linha dos olhos', level: 'Nivelado', eyesOpen: 'Olhos abertos',
      roll: 'Inclinação', yaw: 'Giro', pitch: 'Aceno',
      mouth: 'Boca sorrindo', eyeSmile: 'Olhos sorrindo',
      leftEye: 'Olho esquerdo', rightEye: 'Olho direito', evenness: 'Os dois iguais',
      headroom: 'Espaço acima', thirds: 'Terços', size: 'O rosto ocupa',
    },
  },
  ja: {
    tools: {
      'id-photo': { title: '証明写真チェック', desc: 'パスポート写真の規格を5項目で確認', lead: '顔の大きさ・位置・目の高さ・傾き・目の開きを実測して規格と比べます', privacy: 'パスポート規格のうち数値で測れる5項目だけを見ます。背景・表情・影の規定は数値化できないため扱っておらず、ここを通っても窓口で差し戻されることがあります。' },
      'head-pose': { title: '顔の角度測定', desc: '写真の顔がどれだけ傾き、向いているか', lead: '両目と鼻・あごの位置から傾き・左右の向き・うなずきを測ります', privacy: '傾きは両目を結ぶ線の角度なので度で正確に出ます。左右の向きとうなずきは一枚の写真に奥行きがないため、角度ではなく偏りとして出します。' },
      'real-smile': { title: '本物の笑顔指数', desc: '口だけか、目まで笑っているか', lead: '口角と目が一緒に動いたかを測り、デュシェンヌ・スマイルかを見ます', privacy: '心からの笑いでは眼輪筋も動いて目が細くなるとされます（デュシェンヌ・スマイル）。ここでは口が笑うときに目がどれだけ細くなったかだけを測り、感情の判定はしません。' },
      'eye-open': { title: '目の開き測定', desc: '目つむり写真か、左右はそろっているか', lead: '目の縦横比（EAR）でどれだけ開いているかを測ります', privacy: '閉じた目と開いた目を見分けるのに広く使われるEARで測ります。目が小さいことと目を閉じていることは別で、この値は形ではなく開き具合を見ます。' },
      framing: { title: '人物の構図分析', desc: '三分割と頭上の余白で見る構図', lead: '顔が画面のどこに、どれくらいの大きさで置かれているかを測ります', privacy: '三分割線と中央のどちらも正解として扱います。人物写真で中央構図はよくあるもので、間違いではありません。' },
      'lighting': { title: '照明の向き分析', desc: '光がどこから来ているか、逆光か', lead: '顔の左右・上下の明るさと背景の明るさから光の向きを読みます', privacy: '明るさは写真から実際に測った値です。ただし影と地肌の色は区別できないので、片側が暗く出ても照明のせいとは限りません。' },
      'sharpness': { title: '写真のシャープさ検査', desc: 'ぶれているか、ピントは合っているか', lead: '顔の範囲で隣り合う画素の差から鮮明さを測ります', privacy: '顔の内側だけを測ります。背景をぼかした人物写真で全体を測ると、顔は鮮明なのに「ぶれている」と出てしまうからです。' },
      'white-balance': { title: 'ホワイトバランス検査', desc: '写真の色がどちらに寄っているか', lead: '画面全体の平均色から色温度と色かぶりの偏りを測ります', privacy: '画面の平均は灰色になるはず、という前提で測ります。夕焼けのように実際に一色が多い写真は偏りと出ますが、それは前提の限界であって写真の欠点ではありません。' },
      'distance': { title: '撮影距離の目安', desc: 'どれくらい近くで撮ったか、顔がどれだけ歪んでいるか', lead: '顔の幅が画面に占める割合とレンズの画角から距離を見積もります', privacy: '画角は写真に記録されておらず頭幅にも個人差があるため、これは測定ではなく目安です。スマホの主カメラ（約70度）と成人の頭幅145mmを仮定しています。' },
      'mirror': { title: '左右合成の顔', desc: '左半分だけ・右半分だけで作った二つの顔', lead: '鼻すじを軸に、左右それぞれの半分を鏡のように合わせます', privacy: 'ここでは点数をつけません。実際に画像を反転して貼り合わせています。正面でない写真では二つの顔が大きく違いますが、それは顔が非対称なのではなく顔が向いているからです。' },
      'face-thirds': { title: "顔の三分割", desc: "額・鼻・あごの三段の比率", lead: "眉の上・鼻の下・あご先を取って三段の高さを測ります", privacy: "額の高さは測れません — 顔の68点には生え際がないからです。そのため上の段は中の段と同じと見て概算します。「三段が等しい」は古い画法の慣習であって、美の基準ではありません。" },
      'eye-spacing': { title: "目の間隔検査", desc: "両目の間が目一つ分かどうか", lead: "両目の間の距離を片目の幅で割って測ります", privacy: "顔の幅を5等分すると目一つがちょうど1区画を占める、という目安が広く使われます。つまり両目の間が目一つ分のとき1になります。あくまで目安であり、美の基準ではありません。" },
      'face-shape': { title: "顔型判定", desc: "卵形・丸顔・エラ張り・面長・ハート形", lead: "縦横比とあご・額の幅の3つの値で分けます", privacy: "実際の顔は2つの型の境目にあることが多く、名前だけでは理由が分かりません。そこで判定の根拠になった3つの値も一緒に出します。写真の角度で結果が変わるので、正面の写真で見てください。" },
      'brows': { title: "眉の均衡検査", desc: "左右の高さと眉間の広さ", lead: "眉の左右の高さの差を顔の大きさで割って測ります", privacy: "ピクセルのまま測ると近くで撮った写真ほど悪く出るので、顔の大きさで割ります。眉は表情で実際に動くので、力を抜いた顔で見るのが正しいです。" },
      'lips': { title: "唇の比率検査", desc: "上唇と下唇の厚みの比", lead: "唇の外側の線と内側の線の間を測って上下の厚みを出します", privacy: "顔の点に唇の内側8点がないと厚みは測れません。そのときは分からないと言って幅だけ出します — ない点を外側の点で代わりにすると、「上唇がない」という意味の数字がもっともらしく出るからです。" },
      'contrast': { title: "写真のコントラスト検査", desc: "眠いか、片側が飛んでいるか", lead: "顔の中の4区域の明暗の幅と背景との差を測ります", privacy: "コントラストは大きいほど良いものではありません。幅が小さすぎると眠く、大きすぎると片側が飛んでいるので、真ん中がいちばん良いのです。照明検査が「光がどちらから来るか」なら、これは「どれだけくっきりしているか」です。" },
      'backdrop': { title: "背景の整い検査", desc: "証明写真に使えるほど背景がきれいか", lead: "背景の明るさの標準偏差と顔との明るさの差を測ります", privacy: "背景が均一とは明るさがほとんど変わらないということです。柄や物があると標準偏差が大きくなります。色は見ないので、白い背景か青い背景かはこの検査では分かりません。" },
    },
    metric: {
      thirdsUpper: "上の段",
      thirdsMiddle: "中の段",
      thirdsLower: "下の段",
      thirdsBalance: "三段の均衡",
      eyeGap: "目の間隔",
      eyeEven: "両目のそろい",
      eyeSpan: "目の幅",
      shapeRatio: "縦横比",
      jawWidth: "あごの幅",
      browWidth: "額の幅",
      browLevel: "左右の高さ",
      browGap: "眉間",
      browLift: "眉の高さ",
      lipRatio: "上下の厚み比",
      lipWidth: "口の幅",
      lipEven: "口角のそろい",
      contrastRange: "顔の中の明暗差",
      contrastPop: "背景との差",
      backEven: "背景の均一さ",
      backSeparation: "人物の分離",
      sideLight: '左右の明るさ差', topLight: '上下の明るさ差', backlit: '逆光', exposure: '露出', focus: 'ピント', temp: '色温度', tint: '色かぶり', shotDistance: '推定距離', faceFill: '顔の占める割合', perspective: '遠近の歪み', axisBalance: '左右の幅バランス',
      faceSize: '顔の大きさ', centered: '左右の中央', eyeLine: '目の高さ', level: '水平', eyesOpen: '目の開き',
      roll: '傾き', yaw: '左右の向き', pitch: 'うなずき',
      mouth: '口の笑い', eyeSmile: '目の笑い',
      leftEye: '左目', rightEye: '右目', evenness: '左右のそろい',
      headroom: '頭上の余白', thirds: '三分割', size: '顔の占める割合',
    },
  },
  de: {
    tools: {
      'id-photo': { title: 'Passbild-Check', desc: 'Fünf Prüfungen gegen die Passbild-Vorgaben', lead: 'Größe, Position, Augenlinie, Neigung und offene Augen — gemessen und mit der Vorgabe verglichen', privacy: 'Nur die fünf Punkte der Vorgabe, die sich als Zahl messen lassen. Hintergrund, Mimik und Schatten sind nicht messbar, ein Bestehen hier ist also keine Zusage der Behörde.' },
      'head-pose': { title: 'Kopfwinkel', desc: 'Wie stark der Kopf geneigt und gedreht ist', lead: 'Neigung, Drehung und Nicken, gemessen an Augen, Nase und Kinn', privacy: 'Die Neigung ergibt sich aus dem Winkel der Linie zwischen den Augen und ist daher in Grad exakt. Drehung und Nicken haben in einem einzelnen Foto keine Tiefe und werden deshalb als Abweichung angegeben, nicht als Winkel.' },
      'real-smile': { title: 'Echtes Lächeln', desc: 'Nur der Mund oder auch die Augen?', lead: 'Misst, ob Mundwinkel und Augen sich zusammen bewegt haben', privacy: 'Einem echten Lächeln wird nachgesagt, dass sich dabei auch die Augen verengen (Duchenne-Lächeln). Gemessen wird nur, wie stark sich die Augen verengen, während der Mund lächelt — dein Gefühl wird nicht beurteilt.' },
      'eye-open': { title: 'Augenöffnung', desc: 'Augen zu erwischt? Sind beide gleich?', lead: 'Gemessen über das Seitenverhältnis des Auges (EAR)', privacy: 'EAR ist ein gängiges Maß, um geschlossene von offenen Augen zu unterscheiden. Kleine Augen und geschlossene Augen sind nicht dasselbe — gemessen wird die Öffnung, nicht die Form.' },
      framing: { title: 'Bildaufbau', desc: 'Drittel und Kopffreiheit', lead: 'Wo das Gesicht im Bild sitzt und wie viel es füllt', privacy: 'Sowohl die Drittellinien als auch die genaue Mitte gelten als richtig. Mittige Porträts sind üblich und kein Fehler.' },
      'lighting': { title: 'Lichtrichtung', desc: 'Woher das Licht kommt, und ist es Gegenlicht?', lead: 'Liest die Lichtrichtung aus der Helligkeit im Gesicht und dahinter', privacy: 'Die Helligkeit ist an deinem Foto gemessen. Ein Schatten lässt sich nicht von deinem Hautton trennen, eine dunklere Seite ist also nicht immer das Licht.' },
      'sharpness': { title: 'Bildschärfe', desc: 'Verwackelt oder scharf?', lead: 'Misst die Schärfe aus den Unterschieden benachbarter Pixel im Gesicht', privacy: 'Gemessen wird nur das Gesicht. Bei einem Porträt mit absichtlich unscharfem Hintergrund würde die Messung über das ganze Bild ein gestochen scharfes Gesicht als verwackelt melden.' },
      'white-balance': { title: 'Weißabgleich', desc: 'Wohin die Farbe kippt', lead: 'Liest Farbtemperatur und Farbstich aus der Durchschnittsfarbe des Bildes', privacy: 'Es wird angenommen, dass der Bilddurchschnitt grau sein sollte. Ein Sonnenuntergang gilt dann als gekippt — das ist die Grenze der Annahme, kein Fehler im Foto.' },
      'distance': { title: 'Aufnahmeabstand', desc: 'Wie nah die Kamera war und wie stark das Gesicht verzerrt ist', lead: 'Schätzt den Abstand daraus, wie viel Bildbreite das Gesicht füllt, und aus dem Bildwinkel', privacy: 'Der Bildwinkel steht nicht im Foto und die Kopfbreite ist verschieden — das ist eine Schätzung, keine Messung. Angenommen werden Handy-Hauptkamera (etwa 70 Grad) und 145 mm Kopfbreite.' },
      'mirror': { title: 'Spiegelgesichter', desc: 'Zwei Gesichter: linke und rechte Hälfte verdoppelt', lead: 'Spiegelt jede Gesichtshälfte am Nasenrücken', privacy: 'Hier wird nichts bewertet — das Bild wird wirklich gespiegelt und zusammengesetzt. Bei einem schrägen Foto unterscheiden sich die beiden stark, und das ist der gedrehte Kopf, kein unsymmetrisches Gesicht.' },
      'face-thirds': { title: "Gesichtsdrittel", desc: "Wie sich Stirn-, Nasen- und Kinnabschnitt vergleichen", lead: "Misst die drei Abschnitte ab Brauenlinie, Nasenbasis und Kinn", privacy: "Die Stirnhöhe lässt sich nicht messen — die achtundsechzig Gesichtspunkte enthalten keinen Haaransatz. Daher wird das obere Drittel als gleich dem mittleren geschätzt. „Gleiche Drittel\" ist eine alte Zeichenkonvention, kein Schönheitsmaßstab." },
      'eye-spacing': { title: "Augenabstand", desc: "Ob der Abstand zwischen den Augen einer Augenbreite entspricht", lead: "Teilt den Abstand zwischen den Augen durch die Breite eines Auges", privacy: "Eine verbreitete Faustregel teilt das Gesicht in fünf Breiten, jede von einem Auge gefüllt. Der Abstand entspricht also einer Augenbreite, wenn der Wert 1 ist. Eine Faustregel, kein Schönheitsmaßstab." },
      'face-shape': { title: "Gesichtsform", desc: "Oval, rund, eckig, lang oder herzförmig", lead: "Bestimmt aus dem Höhen-Breiten-Verhältnis sowie Kiefer- und Stirnbreite", privacy: "Echte Gesichter liegen oft an der Grenze zwischen zwei Formen, und ein Name allein sagt nichts über das Warum. Deshalb werden auch die drei Werte gezeigt, auf denen die Zuordnung beruht. Das Ergebnis hängt vom Aufnahmewinkel ab — nimm ein frontales Foto." },
      'brows': { title: "Brauenbalance", desc: "Höhe links-rechts und der Abstand zwischen den Brauen", lead: "Teilt den Höhenunterschied links-rechts durch die Gesichtsgröße", privacy: "In reinen Pixeln gemessen schneidet ein näheres Foto immer schlechter ab, deshalb wird durch die Gesichtsgröße geteilt. Brauen bewegen sich tatsächlich mit dem Ausdruck — beurteile sie an einem entspannten Gesicht." },
      'lips': { title: "Lippenverhältnis", desc: "Wie sich Ober- und Unterlippendicke vergleichen", lead: "Nimmt die Dicke aus dem Abstand zwischen äußerer und innerer Lippenlinie", privacy: "Fehlen in den Gesichtspunkten die acht inneren Lippenpunkte, lässt sich die Dicke nicht messen. Dann wird das gesagt und nur die Breite gezeigt — die äußeren Punkte einzusetzen ergäbe eine plausible Zahl mit der Bedeutung „es gibt keine Oberlippe\"." },
      'contrast': { title: "Foto-Kontrast", desc: "Ob es flau ist oder auf einer Seite ausgefressen", lead: "Misst die Helligkeitsspanne über vier Gesichtsbereiche und den Abstand zum Hintergrund", privacy: "Mehr Kontrast ist nicht besser. Eine zu kleine Spanne wirkt flau, eine zu große heißt, eine Seite ist ausgefressen — die Mitte ist am besten. Während der Lichttest fragt, woher das Licht kommt, fragt dieser, wie knackig das Foto ist." },
      'backdrop': { title: "Hintergrund-Check", desc: "Ob der Hintergrund sauber genug für ein Ausweisfoto ist", lead: "Misst die Standardabweichung der Hintergrundhelligkeit und deren Abstand zum Gesicht", privacy: "Ein gleichmäßiger Hintergrund heißt, dass die Helligkeit kaum schwankt. Muster oder Gegenstände treiben die Standardabweichung hoch. Farbe wird nicht geprüft — ob der Hintergrund weiß oder blau ist, sagt dieser Test nicht." },
    },
    metric: {
      thirdsUpper: "Oberes Drittel",
      thirdsMiddle: "Mittleres Drittel",
      thirdsLower: "Unteres Drittel",
      thirdsBalance: "Ausgewogenheit der drei",
      eyeGap: "Augenabstand",
      eyeEven: "Augen gleich",
      eyeSpan: "Augenbreite",
      shapeRatio: "Höhe zu Breite",
      jawWidth: "Kieferbreite",
      browWidth: "Stirnbreite",
      browLevel: "Brauen auf gleicher Höhe",
      browGap: "Abstand zwischen den Brauen",
      browLift: "Brauenhöhe",
      lipRatio: "Oben zu unten",
      lipWidth: "Mundbreite",
      lipEven: "Mundwinkel auf gleicher Höhe",
      contrastRange: "Spanne im Gesicht",
      contrastPop: "Gegenüber dem Hintergrund",
      backEven: "Gleichmäßigkeit des Hintergrunds",
      backSeparation: "Trennung vom Hintergrund",
      sideLight: 'Seitenunterschied', topLight: 'Oben-unten-Unterschied', backlit: 'Gegenlicht', exposure: 'Belichtung', focus: 'Schärfe', temp: 'Temperatur', tint: 'Farbstich', shotDistance: 'Geschätzter Abstand', faceFill: 'Gesicht füllt', perspective: 'Perspektivische Dehnung', axisBalance: 'Hälften im Gleichgewicht',
      faceSize: 'Gesichtsgröße', centered: 'Mittig', eyeLine: 'Augenlinie', level: 'Waagerecht', eyesOpen: 'Augen offen',
      roll: 'Neigung', yaw: 'Drehung', pitch: 'Nicken',
      mouth: 'Mund lächelt', eyeSmile: 'Augen lächeln',
      leftEye: 'Linkes Auge', rightEye: 'Rechtes Auge', evenness: 'Beide gleich',
      headroom: 'Kopffreiheit', thirds: 'Drittel', size: 'Gesicht füllt',
    },
  },
  fr: {
    tools: {
      'id-photo': { title: "Photo d'identité", desc: 'Cinq contrôles face aux règles du passeport', lead: "Taille, position, ligne des yeux, inclinaison et yeux ouverts, mesurés et comparés à la norme", privacy: "Seuls les cinq points de la norme qui se mesurent en chiffres. Le fond, l'expression et les ombres ne sont pas mesurables : réussir ici ne garantit pas l'acceptation au guichet." },
      'head-pose': { title: 'Angle de la tête', desc: "À quel point la tête penche et tourne", lead: 'Inclinaison, rotation et hochement mesurés sur les yeux, le nez et le menton', privacy: "L'inclinaison vient de l'angle de la ligne entre les yeux : elle est exacte en degrés. La rotation et le hochement n'ont pas de profondeur sur une seule photo, ils sont donc donnés comme un écart et non comme un angle." },
      'real-smile': { title: 'Vrai sourire', desc: 'La bouche seule, ou aussi les yeux ?', lead: 'Mesure si les coins de la bouche et les yeux ont bougé ensemble', privacy: "On dit d'un sourire sincère qu'il plisse aussi les yeux (sourire de Duchenne). Ici on mesure seulement de combien les yeux se plissent pendant que la bouche sourit ; votre ressenti n'est pas jugé." },
      'eye-open': { title: 'Ouverture des yeux', desc: 'Photo les yeux fermés ? Les deux sont-ils égaux ?', lead: "Mesuré par le rapport d'aspect de l'œil (EAR)", privacy: "L'EAR est une façon courante de distinguer un œil fermé d'un œil ouvert. Petits yeux et yeux fermés ne sont pas la même chose : on lit l'ouverture, pas la forme." },
      framing: { title: 'Cadrage du portrait', desc: 'Tiers et espace au-dessus de la tête', lead: 'Où se place le visage dans le cadre et quelle place il occupe', privacy: "Les lignes de tiers et le centre exact comptent tous deux comme justes. Le portrait centré est courant et n'est pas une erreur." },
      'lighting': { title: 'Direction de la lumière', desc: 'D’où vient la lumière, y a-t-il un contre-jour ?', lead: 'Lit la direction de la lumière d’après la luminosité du visage et du fond', privacy: 'La luminosité est mesurée sur votre photo. Une ombre ne se distingue pas de votre carnation : un côté sombre n’est pas toujours la lumière.' },
      'sharpness': { title: 'Netteté de la photo', desc: 'Bougée ou nette ?', lead: 'Mesure la netteté par la différence entre pixels voisins dans le visage', privacy: 'Seul le visage est mesuré. Sur un portrait au fond volontairement flou, mesurer toute l’image déclarerait bougé un visage parfaitement net.' },
      'white-balance': { title: 'Balance des blancs', desc: 'De quel côté penche la couleur', lead: 'Lit la température et la teinte à partir de la couleur moyenne de l’image', privacy: 'On suppose que la moyenne de l’image devrait être grise. Un coucher de soleil ressortira penché : c’est la limite de l’hypothèse, pas un défaut de la photo.' },
      'distance': { title: 'Distance de prise de vue', desc: 'À quelle distance et combien le visage est étiré', lead: 'Estime la distance d’après la place du visage dans le cadre et l’angle de l’objectif', privacy: 'L’angle n’est pas enregistré dans la photo et la largeur de tête varie : c’est une estimation, pas une mesure. On suppose un appareil principal de téléphone (environ 70 degrés) et une tête de 145 mm.' },
      'mirror': { title: 'Visages miroir', desc: 'Deux visages : moitié gauche et moitié droite doublées', lead: 'Reflète chaque moitié du visage sur l’arête du nez', privacy: 'Rien n’est noté ici — l’image est vraiment retournée et recollée. Sur une photo de trois quarts les deux visages diffèrent beaucoup : c’est la tête tournée, pas un visage asymétrique.' },
      'face-thirds': { title: "Tiers du visage", desc: "Comparaison du front, du nez et du menton", lead: "Mesure les trois sections à partir de la ligne des sourcils, de la base du nez et du menton", privacy: "La hauteur du front ne peut pas être mesurée : les soixante-huit points du visage ne comportent pas la racine des cheveux. Le tiers supérieur est donc estimé égal au tiers médian. « Tiers égaux » est une vieille convention de dessin, pas un canon de beauté." },
      'eye-spacing': { title: "Écart entre les yeux", desc: "Si l’espace entre les yeux vaut une largeur d’œil", lead: "Divise la distance entre les yeux par la largeur d’un œil", privacy: "Une règle courante découpe le visage en cinq largeurs, chacune occupée par un œil. L’espace vaut donc une largeur d’œil quand la valeur est 1. C’est une règle empirique, pas un canon de beauté." },
      'face-shape': { title: "Forme du visage", desc: "Ovale, rond, carré, allongé ou en cœur", lead: "Déterminée par le rapport hauteur-largeur et les largeurs de mâchoire et de front", privacy: "Les vrais visages se trouvent souvent à la frontière entre deux formes, et un nom seul ne dit rien du pourquoi. Les trois valeurs qui fondent le verdict sont donc affichées aussi. Le résultat change avec l’angle de la photo : utilisez une prise de face." },
      'brows': { title: "Équilibre des sourcils", desc: "Hauteur gauche-droite et écart entre les sourcils", lead: "Divise l’écart de hauteur gauche-droite par la taille du visage", privacy: "Mesurée en pixels bruts, une photo plus proche est toujours moins bien notée : l’écart est donc divisé par la taille du visage. Les sourcils bougent réellement avec l’expression — jugez-les sur un visage détendu." },
      'lips': { title: "Proportions des lèvres", desc: "Comparaison des épaisseurs de la lèvre supérieure et inférieure", lead: "Prend l’épaisseur dans l’écart entre les lignes externe et interne de la lèvre", privacy: "Si les points du visage n’incluent pas les huit points internes de la lèvre, l’épaisseur ne peut pas être mesurée. On le dit alors et seule la largeur est montrée : substituer les points externes donnerait un nombre plausible signifiant « il n’y a pas de lèvre supérieure »." },
      'contrast': { title: "Contraste de la photo", desc: "Si elle est plate ou brûlée d’un côté", lead: "Mesure l’amplitude de luminosité sur quatre zones du visage et l’écart au fond", privacy: "Plus de contraste n’est pas mieux. Une amplitude trop faible paraît plate et une trop forte signifie qu’un côté est brûlé : le milieu est le meilleur. Là où le test d’éclairage demande d’où vient la lumière, celui-ci demande à quel point la photo est nette." },
      'backdrop': { title: "Contrôle du fond", desc: "Si le fond est assez net pour une photo d’identité", lead: "Mesure l’écart-type de la luminosité du fond et son écart au visage", privacy: "Un fond uniforme signifie que la luminosité varie à peine. Les motifs ou objets font grimper l’écart-type. La couleur n’est pas examinée : ce contrôle ne dit pas si le fond est blanc ou bleu." },
    },
    metric: {
      thirdsUpper: "Tiers supérieur",
      thirdsMiddle: "Tiers médian",
      thirdsLower: "Tiers inférieur",
      thirdsBalance: "Équilibre des trois",
      eyeGap: "Écart entre les yeux",
      eyeEven: "Yeux appariés",
      eyeSpan: "Largeur des yeux",
      shapeRatio: "Hauteur sur largeur",
      jawWidth: "Largeur de la mâchoire",
      browWidth: "Largeur du front",
      browLevel: "Sourcils au même niveau",
      browGap: "Écart entre les sourcils",
      browLift: "Hauteur des sourcils",
      lipRatio: "Supérieure sur inférieure",
      lipWidth: "Largeur de la bouche",
      lipEven: "Coins au même niveau",
      contrastRange: "Amplitude dans le visage",
      contrastPop: "Par rapport au fond",
      backEven: "Uniformité du fond",
      backSeparation: "Détachement du sujet",
      sideLight: 'Écart gauche-droite', topLight: 'Écart haut-bas', backlit: 'Contre-jour', exposure: 'Exposition', focus: 'Mise au point', temp: 'Température', tint: 'Teinte', shotDistance: 'Distance estimée', faceFill: 'Le visage occupe', perspective: 'Étirement', axisBalance: 'Équilibre des moitiés',
      faceSize: 'Taille du visage', centered: 'Centré', eyeLine: 'Ligne des yeux', level: 'Horizontal', eyesOpen: 'Yeux ouverts',
      roll: 'Inclinaison', yaw: 'Rotation', pitch: 'Hochement',
      mouth: 'Bouche qui sourit', eyeSmile: 'Yeux qui sourient',
      leftEye: 'Œil gauche', rightEye: 'Œil droit', evenness: 'Les deux égaux',
      headroom: 'Espace au-dessus', thirds: 'Tiers', size: 'Le visage occupe',
    },
  },
  hi: {
    tools: {
      'id-photo': { title: 'पासपोर्ट फ़ोटो जाँच', desc: 'पासपोर्ट फ़ोटो नियमों के विरुद्ध पाँच जाँच', lead: 'चेहरे का आकार, स्थिति, आँख की रेखा, झुकाव और खुली आँखें नापकर मानक से मिलाई जाती हैं', privacy: 'मानक के केवल वे पाँच हिस्से देखे जाते हैं जो संख्या में नापे जा सकते हैं। पृष्ठभूमि, भाव और छाया के नियम नापे नहीं जा सकते, इसलिए यहाँ पास होना स्वीकृति की गारंटी नहीं है।' },
      'head-pose': { title: 'सिर का कोण', desc: 'सिर कितना झुका और घूमा हुआ है', lead: 'आँखों, नाक और ठुड्डी से झुकाव, घुमाव और सिर हिलाव नापा जाता है', privacy: 'झुकाव दोनों आँखों को जोड़ने वाली रेखा के कोण से आता है, इसलिए वह डिग्री में सटीक है। एक तस्वीर में गहराई नहीं होती, इसलिए घुमाव और हिलाव कोण नहीं बल्कि झुकाव के रूप में दिए जाते हैं।' },
      'real-smile': { title: 'असली मुस्कान', desc: 'सिर्फ़ होंठ, या आँखें भी?', lead: 'नापता है कि होंठों के कोने और आँखें साथ हिलीं या नहीं', privacy: 'कहा जाता है कि सच्ची मुस्कान में आँखें भी सिकुड़ती हैं (डचेन मुस्कान)। यहाँ केवल यह नापा जाता है कि होंठ मुस्कुराते समय आँखें कितनी सिकुड़ीं — आपकी भावना का आकलन नहीं होता।' },
      'eye-open': { title: 'आँख खुलने की माप', desc: 'आँख बंद वाली तस्वीर? दोनों बराबर हैं?', lead: 'आँख के अनुपात (EAR) से नापा जाता है', privacy: 'बंद और खुली आँख में फ़र्क़ करने का आम तरीक़ा EAR है। छोटी आँखें और बंद आँखें एक बात नहीं — यह खुलने की मात्रा पढ़ता है, आकार नहीं।' },
      framing: { title: 'फ़्रेमिंग विश्लेषण', desc: 'तिहाई और सिर के ऊपर की जगह', lead: 'चेहरा फ़्रेम में कहाँ और कितना बड़ा है', privacy: 'तिहाई रेखाएँ और ठीक बीच — दोनों सही माने जाते हैं। बीच में रखा पोर्ट्रेट आम है और ग़लत नहीं।' },
      'lighting': { title: 'रोशनी की दिशा', desc: 'रोशनी कहाँ से आ रही है, बैकलाइट है क्या?', lead: 'चेहरे और पृष्ठभूमि की चमक से रोशनी की दिशा पढ़ी जाती है', privacy: 'चमक आपकी तस्वीर से नापी गई है। छाया और आपकी त्वचा के रंग में फ़र्क़ नहीं किया जा सकता, इसलिए एक तरफ़ अँधेरा हमेशा रोशनी की वजह से नहीं होता।' },
      'sharpness': { title: 'तस्वीर की तीक्ष्णता', desc: 'हिली हुई है या फ़ोकस में?', lead: 'चेहरे के भीतर पड़ोसी पिक्सल के अंतर से तीक्ष्णता नापी जाती है', privacy: 'सिर्फ़ चेहरा नापा जाता है। जान-बूझकर धुँधली पृष्ठभूमि वाले पोर्ट्रेट में पूरा फ़्रेम नापने पर बिलकुल साफ़ चेहरा भी हिला हुआ बताया जाता।' },
      'white-balance': { title: 'व्हाइट बैलेंस जाँच', desc: 'रंग किस ओर झुका है', lead: 'पूरे फ़्रेम के औसत रंग से रंग-ताप और रंगत का झुकाव नापा जाता है', privacy: 'मान लिया जाता है कि फ़्रेम का औसत धूसर होना चाहिए। सूर्यास्त झुका हुआ दिखेगा — यह धारणा की सीमा है, तस्वीर की ख़ामी नहीं।' },
      'distance': { title: 'खींचने की दूरी का अनुमान', desc: 'कैमरा कितना पास था और चेहरा कितना खिंचा है', lead: 'चेहरा फ़्रेम में कितना भरता है और लेंस के कोण से दूरी का अनुमान', privacy: 'लेंस का कोण तस्वीर में दर्ज नहीं होता और सिर की चौड़ाई अलग-अलग होती है, इसलिए यह नाप नहीं अनुमान है। फ़ोन का मुख्य कैमरा (क़रीब 70 डिग्री) और 145 मिमी सिर मान लिया गया है।' },
      'mirror': { title: 'दर्पण चेहरे', desc: 'दो चेहरे: बायाँ आधा और दायाँ आधा दुगुना', lead: 'नाक की हड्डी को धुरी मानकर चेहरे के हर आधे हिस्से को दर्पण की तरह जोड़ा जाता है', privacy: 'यहाँ कुछ आँका नहीं जाता — तस्वीर सचमुच पलटकर जोड़ी जाती है। तिरछी तस्वीर में दोनों चेहरे बहुत अलग दिखेंगे, वह सिर के मुड़े होने से है, चेहरे के असमान होने से नहीं।' },
      'face-thirds': { title: "चेहरे के तीन भाग", desc: "माथा, नाक और ठोड़ी के भागों की तुलना", lead: "भौंह रेखा, नाक के आधार और ठोड़ी से तीनों भागों की ऊँचाई मापता है", privacy: "माथे की ऊँचाई नहीं मापी जा सकती — चेहरे के अड़सठ बिंदुओं में बालों की रेखा नहीं होती। इसलिए ऊपरी भाग को मध्य भाग के बराबर मानकर अनुमान लगाया जाता है। \"बराबर तीन भाग\" चित्रकला की पुरानी परंपरा है, सुंदरता का मानक नहीं।" },
      'eye-spacing': { title: "आँखों का अंतर", desc: "क्या दोनों आँखों के बीच एक आँख की चौड़ाई है", lead: "दोनों आँखों के बीच की दूरी को एक आँख की चौड़ाई से भाग देता है", privacy: "एक प्रचलित नियम चेहरे को पाँच चौड़ाइयों में बाँटता है, हर एक में एक आँख। यानी मान 1 होने पर अंतर एक आँख की चौड़ाई के बराबर है। यह एक व्यावहारिक नियम है, सुंदरता का मानक नहीं।" },
      'face-shape': { title: "चेहरे का आकार", desc: "अंडाकार, गोल, चौकोर, लंबा या दिल जैसा", lead: "ऊँचाई-चौड़ाई अनुपात तथा जबड़े और माथे की चौड़ाई से तय होता है", privacy: "असली चेहरे अक्सर दो आकारों की सीमा पर होते हैं, और अकेला नाम यह नहीं बताता कि क्यों। इसलिए निर्णय के आधार वाले तीनों मान भी दिखाए जाते हैं। परिणाम फ़ोटो के कोण से बदलता है, इसलिए सामने से ली गई फ़ोटो लें।" },
      'brows': { title: "भौंहों का संतुलन", desc: "बाएँ-दाएँ ऊँचाई और भौंहों के बीच का अंतर", lead: "बाएँ-दाएँ ऊँचाई के अंतर को चेहरे के आकार से भाग देता है", privacy: "सीधे पिक्सेल में मापें तो पास से ली गई फ़ोटो हमेशा ख़राब आती है, इसलिए अंतर को चेहरे के आकार से भाग दिया जाता है। भौंहें भाव के साथ सचमुच हिलती हैं, इसलिए शांत चेहरे पर आँकें।" },
      'lips': { title: "होंठों का अनुपात", desc: "ऊपरी और निचले होंठ की मोटाई की तुलना", lead: "होंठ की बाहरी और भीतरी रेखा के बीच से मोटाई लेता है", privacy: "यदि चेहरे के बिंदुओं में होंठ के आठ भीतरी बिंदु न हों तो मोटाई नहीं मापी जा सकती। ऐसे में यह बता दिया जाता है और केवल चौड़ाई दिखाई जाती है — बाहरी बिंदुओं को बदले में रखने पर \"ऊपरी होंठ है ही नहीं\" अर्थ वाला विश्वसनीय दिखने वाला अंक निकलता।" },
      'contrast': { title: "फ़ोटो कंट्रास्ट जाँच", desc: "सपाट है या एक ओर जल गई है", lead: "चेहरे के चार क्षेत्रों में चमक की परास और पृष्ठभूमि से अंतर मापता है", privacy: "ज़्यादा कंट्रास्ट बेहतर नहीं होता। परास बहुत छोटी हो तो सपाट लगता है और बहुत बड़ी हो तो एक ओर जल गई है — इसलिए बीच सबसे अच्छा है। जहाँ प्रकाश जाँच पूछती है कि रोशनी किस ओर से आ रही है, वहाँ यह पूछती है कि फ़ोटो कितनी स्पष्ट है।" },
      'backdrop': { title: "पृष्ठभूमि जाँच", desc: "क्या पृष्ठभूमि पहचान-पत्र फ़ोटो के लिए पर्याप्त साफ़ है", lead: "पृष्ठभूमि की चमक का मानक विचलन और चेहरे से उसका अंतर मापता है", privacy: "एकसमान पृष्ठभूमि का अर्थ है कि चमक लगभग नहीं बदलती। नमूने या वस्तुएँ मानक विचलन बढ़ा देती हैं। रंग नहीं जाँचा जाता, इसलिए यह जाँच नहीं बता सकती कि पृष्ठभूमि सफ़ेद है या नीली।" },
    },
    metric: {
      thirdsUpper: "ऊपरी तिहाई",
      thirdsMiddle: "मध्य तिहाई",
      thirdsLower: "निचली तिहाई",
      thirdsBalance: "तीनों का संतुलन",
      eyeGap: "आँखों के बीच का अंतर",
      eyeEven: "आँखें समान",
      eyeSpan: "आँखों की चौड़ाई",
      shapeRatio: "ऊँचाई बनाम चौड़ाई",
      jawWidth: "जबड़े की चौड़ाई",
      browWidth: "माथे की चौड़ाई",
      browLevel: "भौंहें समतल",
      browGap: "भौंहों के बीच",
      browLift: "भौंह की ऊँचाई",
      lipRatio: "ऊपर-नीचे अनुपात",
      lipWidth: "मुँह की चौड़ाई",
      lipEven: "कोने समतल",
      contrastRange: "चेहरे के भीतर परास",
      contrastPop: "पृष्ठभूमि से अंतर",
      backEven: "पृष्ठभूमि की एकरूपता",
      backSeparation: "विषय का पृथक्करण",
      sideLight: 'बाएँ-दाएँ अंतर', topLight: 'ऊपर-नीचे अंतर', backlit: 'बैकलाइट', exposure: 'एक्सपोज़र', focus: 'फ़ोकस', temp: 'रंग-ताप', tint: 'रंगत', shotDistance: 'अनुमानित दूरी', faceFill: 'चेहरा घेरता है', perspective: 'परिप्रेक्ष्य खिंचाव', axisBalance: 'आधे हिस्सों का संतुलन',
      faceSize: 'चेहरे का आकार', centered: 'बीच में', eyeLine: 'आँख की रेखा', level: 'समतल', eyesOpen: 'आँखें खुली',
      roll: 'झुकाव', yaw: 'घुमाव', pitch: 'सिर हिलाव',
      mouth: 'होंठ मुस्कुराते', eyeSmile: 'आँखें मुस्कुरातीं',
      leftEye: 'बाईं आँख', rightEye: 'दाईं आँख', evenness: 'दोनों बराबर',
      headroom: 'ऊपर की जगह', thirds: 'तिहाई', size: 'चेहरा घेरता है',
    },
  },
  'zh-hans': {
    tools: {
      'id-photo': { title: '证件照规格检查', desc: '按护照照片规定做五项核对', lead: '实测脸部大小、位置、眼睛高度、倾斜和睁眼程度，再和规格比对', privacy: '只看护照规格中能用数字量的五项。背景、表情和阴影的规定无法量化，因此这里通过并不代表窗口一定受理。' },
      'head-pose': { title: '头部角度测量', desc: '照片里头歪了多少、转了多少', lead: '用双眼与鼻、下巴的位置量出倾斜、左右转动和点头', privacy: '倾斜由两眼连线的角度得出，所以能精确到度。单张照片没有深度信息，左右转动和点头只能给出偏移量而不是角度。' },
      'real-smile': { title: '真笑指数', desc: '只是嘴在笑，还是眼睛也在笑？', lead: '测量嘴角和眼睛是否一起动了，看是不是杜氏微笑', privacy: '一般认为发自内心的笑会让眼轮匝肌一起动、眼睛变窄（杜氏微笑）。这里只测量嘴笑时眼睛收窄了多少，不判断你的情绪。' },
      'eye-open': { title: '睁眼程度测量', desc: '是不是闭眼照？两边是否一致？', lead: '用眼睛长宽比（EAR）量出睁开的程度', privacy: '用来区分闭眼和睁眼的常用方法是 EAR。眼睛小和闭着眼不是一回事，这个数值看的是睁开程度而不是形状。' },
      framing: { title: '人像构图分析', desc: '三分法和头顶留白', lead: '测量脸在画面中的位置和占比', privacy: '三分线和正中都算标准。人像照片里居中构图很常见，并不是错的。' },
      'lighting': { title: '光线方向分析', desc: '光从哪边来，是不是逆光', lead: '用脸部左右、上下的亮度和背景亮度判断光的方向', privacy: '亮度是从照片上实际测得的。不过阴影和肤色本身无法区分，所以一侧偏暗不一定是光造成的。' },
      'sharpness': { title: '照片清晰度检查', desc: '是糊了还是对上焦了', lead: '用脸部范围内相邻像素的差异衡量清晰度', privacy: '只测脸部。人像照片常故意虚化背景，如果整幅一起测，脸明明很清晰也会被判成糊了。' },
      'white-balance': { title: '白平衡检查', desc: '照片颜色偏向哪一边', lead: '用整幅画面的平均颜色测色温和色调的偏移', privacy: '这里假定整幅画面的平均应当是灰色。晚霞或红叶这类本来就偏色的照片会被判为偏色，那是假设的局限，不是照片的问题。' },
      'distance': { title: '拍摄距离估算', desc: '拍得多近，脸被拉伸了多少', lead: '用脸部占画面的比例和镜头视角估算距离', privacy: '照片里没有记录视角，头宽也因人而异，所以这是估算而不是测量。假定手机主摄（约 70 度）和成人头宽 145 毫米。' },
      'mirror': { title: '左右合成脸', desc: '两张脸：只用左半边、只用右半边', lead: '以鼻梁为轴，把左右各半张脸像照镜子一样拼起来', privacy: '这里不打分——图片是真的翻转拼接的。不是正面的照片里两张脸差别会很大，那是头转过去了，不是脸不对称。' },
      'face-thirds': { title: "三庭检查", desc: "额、鼻、颏三段的比例", lead: "取眉上线、鼻底与下巴尖，量出三段的高度", privacy: "额头高度无法测量——面部六十八个点里没有发际线。所以上庭按与中庭相等来估算。「三庭均等」是古老的画法惯例，不是审美标准。" },
      'eye-spacing': { title: "双眼间距检查", desc: "两眼之间是否为一只眼的宽度", lead: "用两眼之间的距离除以一只眼的宽度", privacy: "常见的经验法则把脸横向分成五等分，每一份正好是一只眼。也就是说，值为 1 时两眼之间恰好一眼宽。这只是经验法则，不是审美标准。" },
      'face-shape': { title: "脸型判定", desc: "鹅蛋、圆、方、长或心形", lead: "由长宽比以及下颌、额头的宽度三个值判定", privacy: "真实的脸常常卡在两种脸型之间，只给一个名字看不出理由。所以判定所依据的三个数值也一并显示。结果会随拍摄角度变化，请用正面照片。" },
      'brows': { title: "眉毛平衡检查", desc: "左右高度与眉间距", lead: "把左右眉毛的高度差除以脸的大小", privacy: "直接按像素量，拍得越近分数越差，所以要除以脸的大小。眉毛会随表情真的移动，所以要用放松的表情来看。" },
      'lips': { title: "唇形比例检查", desc: "上唇与下唇厚度的比值", lead: "量唇部外轮廓线与内轮廓线之间的距离得出上下厚度", privacy: "如果面部点里没有唇内侧的八个点，就量不出厚度。这时会直说量不到，只显示宽度——用外侧点代替会得出一个看起来合理、含义却是「没有上唇」的数字。" },
      'contrast': { title: "照片对比度检查", desc: "是发闷还是一侧过曝", lead: "量出面部四个区域的明暗跨度以及与背景的差值", privacy: "对比度并非越大越好。跨度太小显得发闷，太大则说明一侧已经过曝，所以中间最合适。如果说光线检查问的是「光从哪边来」，这一项问的就是「照片有多通透」。" },
      'backdrop': { title: "背景整洁度检查", desc: "背景是否干净到可以拍证件照", lead: "量出背景亮度的标准差以及它与面部的亮度差", privacy: "背景均匀是指亮度几乎不变。有花纹或物体会让标准差变大。不检查颜色，所以这项检查无法告诉你背景是白色还是蓝色。" },
    },
    metric: {
      thirdsUpper: "上庭",
      thirdsMiddle: "中庭",
      thirdsLower: "下庭",
      thirdsBalance: "三庭均衡",
      eyeGap: "双眼间距比",
      eyeEven: "双眼对称",
      eyeSpan: "双眼跨度",
      shapeRatio: "长宽比",
      jawWidth: "下颌宽度",
      browWidth: "额头宽度",
      browLevel: "眉毛高度对称",
      browGap: "眉间距",
      browLift: "眉毛高度",
      lipRatio: "上下唇厚度比",
      lipWidth: "嘴巴宽度",
      lipEven: "嘴角对称",
      contrastRange: "面部明暗跨度",
      contrastPop: "与背景的差",
      backEven: "背景均匀度",
      backSeparation: "人物分离度",
      sideLight: '左右亮度差', topLight: '上下亮度差', backlit: '逆光', exposure: '曝光', focus: '对焦', temp: '色温', tint: '色调', shotDistance: '估算距离', faceFill: '脸部占比', perspective: '透视拉伸', axisBalance: '左右宽度平衡',
      faceSize: '脸部大小', centered: '左右居中', eyeLine: '眼睛高度', level: '水平', eyesOpen: '睁眼',
      roll: '倾斜', yaw: '左右转动', pitch: '点头',
      mouth: '嘴在笑', eyeSmile: '眼在笑',
      leftEye: '左眼', rightEye: '右眼', evenness: '左右一致',
      headroom: '头顶留白', thirds: '三分法', size: '脸部占比',
    },
  },
  'zh-hant': {
    tools: {
      'id-photo': { title: '證件照規格檢查', desc: '依護照照片規定做五項核對', lead: '實測臉部大小、位置、眼睛高度、傾斜與睜眼程度，再與規格比對', privacy: '只看護照規格中能用數字量的五項。背景、表情與陰影的規定無法量化，因此這裡通過並不代表櫃檯一定受理。' },
      'head-pose': { title: '頭部角度測量', desc: '照片裡頭歪了多少、轉了多少', lead: '用雙眼與鼻、下巴的位置量出傾斜、左右轉動與點頭', privacy: '傾斜由兩眼連線的角度得出，所以能精確到度。單張照片沒有深度資訊，左右轉動與點頭只能給出偏移量而不是角度。' },
      'real-smile': { title: '真笑指數', desc: '只是嘴在笑，還是眼睛也在笑？', lead: '量測嘴角與眼睛是否一起動了，看是不是杜氏微笑', privacy: '一般認為發自內心的笑會讓眼輪匝肌一起動、眼睛變窄（杜氏微笑）。這裡只量測嘴笑時眼睛收窄了多少，不判斷你的情緒。' },
      'eye-open': { title: '睜眼程度測量', desc: '是不是閉眼照？兩邊是否一致？', lead: '用眼睛長寬比（EAR）量出睜開的程度', privacy: '用來分辨閉眼與睜眼的常用方法是 EAR。眼睛小和閉著眼不是一回事，這個數值看的是睜開程度而不是形狀。' },
      framing: { title: '人像構圖分析', desc: '三分法與頭頂留白', lead: '量測臉在畫面中的位置與占比', privacy: '三分線與正中都算標準。人像照片裡置中構圖很常見，並不是錯的。' },
      'lighting': { title: '光線方向分析', desc: '光從哪邊來，是不是逆光', lead: '用臉部左右、上下的亮度與背景亮度判斷光的方向', privacy: '亮度是從照片上實際量得的。不過陰影與膚色本身無法區分，所以一側偏暗不一定是光造成的。' },
      'sharpness': { title: '照片清晰度檢查', desc: '是糊了還是對到焦了', lead: '用臉部範圍內相鄰像素的差異衡量清晰度', privacy: '只量臉部。人像照片常刻意虛化背景，若整幅一起量，臉明明很清晰也會被判成糊了。' },
      'white-balance': { title: '白平衡檢查', desc: '照片顏色偏向哪一邊', lead: '用整幅畫面的平均顏色量色溫與色調的偏移', privacy: '這裡假定整幅畫面的平均應該是灰色。晚霞或紅葉這類本來就偏色的照片會被判為偏色，那是假設的侷限，不是照片的問題。' },
      'distance': { title: '拍攝距離估算', desc: '拍得多近，臉被拉伸了多少', lead: '用臉部占畫面的比例與鏡頭視角估算距離', privacy: '照片裡沒有記錄視角，頭寬也因人而異，所以這是估算而不是量測。假定手機主鏡頭（約 70 度）與成人頭寬 145 公釐。' },
      'mirror': { title: '左右合成臉', desc: '兩張臉：只用左半邊、只用右半邊', lead: '以鼻樑為軸，把左右各半張臉像照鏡子一樣拼起來', privacy: '這裡不打分——圖片是真的翻轉拼接的。不是正面的照片裡兩張臉差別會很大，那是頭轉過去了，不是臉不對稱。' },
      'face-thirds': { title: "三庭檢查", desc: "額、鼻、頦三段的比例", lead: "取眉上線、鼻底與下巴尖，量出三段的高度", privacy: "額頭高度無法測量——面部六十八個點裡沒有髮際線。所以上庭按與中庭相等來估算。「三庭均等」是古老的畫法慣例，不是審美標準。" },
      'eye-spacing': { title: "雙眼間距檢查", desc: "兩眼之間是否為一隻眼的寬度", lead: "用兩眼之間的距離除以一隻眼的寬度", privacy: "常見的經驗法則把臉橫向分成五等分，每一份正好是一隻眼。也就是說，值為 1 時兩眼之間恰好一眼寬。這只是經驗法則，不是審美標準。" },
      'face-shape': { title: "臉型判定", desc: "鵝蛋、圓、方、長或心形", lead: "由長寬比以及下顎、額頭的寬度三個值判定", privacy: "真實的臉常常卡在兩種臉型之間，只給一個名字看不出理由。所以判定所依據的三個數值也一併顯示。結果會隨拍攝角度變化，請用正面照片。" },
      'brows': { title: "眉毛平衡檢查", desc: "左右高度與眉間距", lead: "把左右眉毛的高度差除以臉的大小", privacy: "直接按像素量，拍得越近分數越差，所以要除以臉的大小。眉毛會隨表情真的移動，所以要用放鬆的表情來看。" },
      'lips': { title: "唇形比例檢查", desc: "上唇與下唇厚度的比值", lead: "量唇部外輪廓線與內輪廓線之間的距離得出上下厚度", privacy: "如果面部點裡沒有唇內側的八個點，就量不出厚度。這時會直說量不到，只顯示寬度——用外側點代替會得出一個看起來合理、含義卻是「沒有上唇」的數字。" },
      'contrast': { title: "照片對比度檢查", desc: "是發悶還是一側過曝", lead: "量出面部四個區域的明暗跨度以及與背景的差值", privacy: "對比度並非越大越好。跨度太小顯得發悶，太大則說明一側已經過曝，所以中間最合適。如果說光線檢查問的是「光從哪邊來」，這一項問的就是「照片有多通透」。" },
      'backdrop': { title: "背景整潔度檢查", desc: "背景是否乾淨到可以拍證件照", lead: "量出背景亮度的標準差以及它與面部的亮度差", privacy: "背景均勻是指亮度幾乎不變。有花紋或物體會讓標準差變大。不檢查顏色，所以這項檢查無法告訴你背景是白色還是藍色。" },
    },
    metric: {
      thirdsUpper: "上庭",
      thirdsMiddle: "中庭",
      thirdsLower: "下庭",
      thirdsBalance: "三庭均衡",
      eyeGap: "雙眼間距比",
      eyeEven: "雙眼對稱",
      eyeSpan: "雙眼跨度",
      shapeRatio: "長寬比",
      jawWidth: "下顎寬度",
      browWidth: "額頭寬度",
      browLevel: "眉毛高度對稱",
      browGap: "眉間距",
      browLift: "眉毛高度",
      lipRatio: "上下唇厚度比",
      lipWidth: "嘴巴寬度",
      lipEven: "嘴角對稱",
      contrastRange: "面部明暗跨度",
      contrastPop: "與背景的差",
      backEven: "背景均勻度",
      backSeparation: "人物分離度",
      sideLight: '左右亮度差', topLight: '上下亮度差', backlit: '逆光', exposure: '曝光', focus: '對焦', temp: '色溫', tint: '色調', shotDistance: '估算距離', faceFill: '臉部占比', perspective: '透視拉伸', axisBalance: '左右寬度平衡',
      faceSize: '臉部大小', centered: '左右置中', eyeLine: '眼睛高度', level: '水平', eyesOpen: '睜眼',
      roll: '傾斜', yaw: '左右轉動', pitch: '點頭',
      mouth: '嘴在笑', eyeSmile: '眼在笑',
      leftEye: '左眼', rightEye: '右眼', evenness: '左右一致',
      headroom: '頭頂留白', thirds: '三分法', size: '臉部占比',
    },
  },
};
