/**
 * 태그 140개의 한 줄 설명 — 열 언어.
 *
 * 태그 이름은 옮기지 않는다. <div>는 어디서나 <div>이고, 속성 이름도 표준이 정한
 * 영어라 그대로 둔다. 옮기는 것은 "이 태그가 무엇을 하는가" 한 문장뿐이다.
 *
 * 열 칸을 배열로 적는다 — 항목마다 열쇠 이름을 여덟 번 쓰면 파일이 세 배가 되고,
 * 빠진 칸도 오히려 눈에 안 띈다. 순서는 ko·en·es·pt·ja·de·fr·hi·zh·tw.
 */
export type Ten = [string, string, string, string, string, string, string, string, string, string];

/** 배열 자리 순서 — ko·en·es·pt·ja·de·fr·hi */
const LANG_ORDER = ['ko', 'en', 'es', 'pt', 'ja', 'de', 'fr', 'hi', 'zh', 'tw'] as const;

/** 태그 이름과 언어로 한 줄 설명을 꺼낸다 */
export function tagDesc(name: string, lang: string): string {
  const row = TAG_DESC[name];
  if (!row) return '';
  const i = LANG_ORDER.indexOf(lang as (typeof LANG_ORDER)[number]);
  return row[i >= 0 ? i : 1];
}

export const TAG_DESC: Record<string, Ten> = {
  /* ───────── 문서 뼈대 ───────── */
  html: ['문서 전체를 감싸는 뿌리 태그입니다. lang 속성으로 문서의 언어를 알립니다.', 'The root element wrapping the whole document; its lang attribute declares the language.', 'El elemento raíz que envuelve todo el documento; su atributo lang declara el idioma.', 'O elemento raiz que envolve todo o documento; o atributo lang declara o idioma.', '文書全体を包む根の要素です。lang属性で文書の言語を伝えます。', 'Das Wurzelelement um das ganze Dokument; sein lang-Attribut nennt die Sprache.', "L'élément racine qui enveloppe tout le document ; son attribut lang déclare la langue.", 'पूरे दस्तावेज़ को घेरने वाला मूल तत्व; इसका lang विशेषण भाषा बताता है।', '整份文件的最外层，语言就写在它的 lang 属性上。', '整份文件的最外層，語言就寫在它的 lang 屬性上。'],
  head: ['화면에 그리지 않는 문서 정보를 담습니다. 제목·메타·스타일이 여기 들어갑니다.', 'Holds information about the document that is not rendered — title, meta, styles.', 'Contiene información del documento que no se muestra: título, meta, estilos.', 'Guarda informações do documento que não aparecem: título, meta, estilos.', '画面に表示しない文書情報を入れます。タイトル・メタ・スタイルがここに入ります。', 'Enthält nicht dargestellte Dokumentinformationen — Titel, Meta, Styles.', "Contient les informations du document non affichées : titre, méta, styles.", 'दस्तावेज़ की वह जानकारी रखता है जो दिखती नहीं — शीर्षक, मेटा, स्टाइल।', '放不显示在页面上的信息 —— 标题、样式、元数据都在这儿。', '放不顯示在頁面上的資訊 —— 標題、樣式、中繼資料都在這兒。'],
  body: ['화면에 보이는 내용 전부가 이 안에 들어갑니다.', 'Everything the reader actually sees goes inside this element.', 'Todo lo que el lector ve realmente va dentro de este elemento.', 'Tudo o que o leitor realmente vê fica dentro deste elemento.', '画面に見える内容はすべてこの中に入ります。', 'Alles, was der Leser tatsächlich sieht, steht in diesem Element.', "Tout ce que le lecteur voit réellement se trouve dans cet élément.", 'पाठक को जो कुछ दिखता है, वह सब इसी के भीतर आता है।', '实际显示出来的内容全部装在这里。', '實際顯示出來的內容全部裝在這裡。'],
  title: ['브라우저 탭과 검색 결과에 나오는 문서 제목입니다.', 'The document title shown in the browser tab and in search results.', 'El título del documento que aparece en la pestaña y en los resultados de búsqueda.', 'O título do documento exibido na aba e nos resultados de busca.', 'ブラウザーのタブや検索結果に出る文書のタイトルです。', 'Der Dokumenttitel, der im Browser-Tab und in Suchergebnissen erscheint.', "Le titre du document affiché dans l'onglet et dans les résultats de recherche.", 'ब्राउज़र टैब और खोज परिणामों में दिखने वाला दस्तावेज़ शीर्षक।', '浏览器标签页和搜索结果上显示的标题。', '瀏覽器分頁和搜尋結果上顯示的標題。'],
  base: ['문서 안 상대 주소의 기준이 되는 주소를 정합니다.', 'Sets the base URL that all relative links in the document resolve against.', 'Define la URL base contra la que se resuelven los enlaces relativos.', 'Define a URL base usada para resolver os links relativos do documento.', '文書内の相対アドレスの基準となるURLを決めます。', 'Legt die Basis-URL fest, gegen die relative Links aufgelöst werden.', "Définit l'URL de base à laquelle se rapportent les liens relatifs.", 'दस्तावेज़ के सापेक्ष लिंक जिस आधार URL से हल होते हैं, वह तय करता है।', '给页内所有相对链接定一个共同的起点。', '給頁內所有相對連結定一個共同的起點。'],

  /* ───────── 구획 ───────── */
  header: ['한 구획의 머리말입니다. 제목이나 로고, 안내가 들어갑니다.', 'The introductory part of a section — a heading, a logo, navigation.', 'La parte introductoria de una sección: un título, un logotipo, navegación.', 'A parte introdutória de uma seção: título, logotipo, navegação.', '一つの区画の冒頭部分です。見出しやロゴ、案内が入ります。', 'Der einleitende Teil eines Abschnitts — Überschrift, Logo, Navigation.', "La partie introductive d'une section : titre, logo, navigation.", 'किसी खंड का प्रारंभिक भाग — शीर्षक, लोगो, नेविगेशन।', '一段内容开头的部分 —— 标题、导航之类。一页里可以有好几个。', '一段內容開頭的部分 —— 標題、導覽之類。一頁裡可以有好幾個。'],
  nav: ['주요 이동 링크 묶음입니다. 모든 링크 묶음이 아니라 길잡이만 감쌉니다.', 'A block of major navigation links — not every set of links, just the wayfinding ones.', 'Un bloque de enlaces de navegación principales; no cualquier grupo de enlaces.', 'Um bloco de links de navegação principais, não qualquer grupo de links.', '主要な移動リンクのまとまりです。すべてのリンク群ではなく道案内だけを包みます。', 'Ein Block wichtiger Navigationslinks — nicht jede Linkgruppe, nur die zur Orientierung.', "Un bloc de liens de navigation principaux, pas n'importe quel groupe de liens.", 'मुख्य नेविगेशन लिंक का समूह — हर लिंक-समूह नहीं, सिर्फ़ राह दिखाने वाले।', '主要的导航链接区。读屏工具靠它跳转。', '主要的導覽連結區。螢幕閱讀器靠它跳轉。'],
  main: ['그 문서의 본론입니다. 한 문서에 하나만 두고, 머리말과 꼬리말은 뺍니다.', 'The main content of the document — one per page, excluding header and footer.', 'El contenido principal del documento: uno por página, sin cabecera ni pie.', 'O conteúdo principal do documento: um por página, sem cabeçalho nem rodapé.', 'その文書の本題です。1ページに一つだけ置き、ヘッダーとフッターは含めません。', 'Der Hauptinhalt des Dokuments — einmal pro Seite, ohne Kopf- und Fußbereich.', "Le contenu principal du document : un seul par page, hors en-tête et pied de page.", 'दस्तावेज़ की मुख्य सामग्री — हर पन्ने पर एक, हेडर और फुटर के बिना।', '这一页的主要内容，一页只能有一个。', '這一頁的主要內容，一頁只能有一個。'],
  section: ['제목을 가진 하나의 주제 묶음입니다. 뜻 없는 상자로 쓰면 안 됩니다.', 'A thematic grouping that has a heading — not a generic box.', 'Una agrupación temática con su encabezado, no una caja genérica.', 'Um agrupamento temático com título, não uma caixa genérica.', '見出しを持つ一つの主題のまとまりです。意味のない箱として使ってはいけません。', 'Eine thematische Gruppe mit Überschrift — kein beliebiger Container.', "Un regroupement thématique doté d'un titre, pas une boîte générique.", 'शीर्षक वाला विषयगत समूह — कोई सामान्य डिब्बा नहीं।', '有主题的一段内容，通常配一个标题。', '有主題的一段內容，通常配一個標題。'],
  article: ['그 자체로 떼어 놓아도 뜻이 통하는 글입니다. 기사·게시물·댓글이 그렇습니다.', 'A piece that still makes sense on its own — an article, a post, a comment.', 'Una pieza que se sostiene por sí sola: un artículo, una publicación, un comentario.', 'Um conteúdo que faz sentido sozinho: artigo, postagem, comentário.', 'それだけ切り離しても意味が通る内容です。記事・投稿・コメントなどです。', 'Ein Inhalt, der für sich allein Sinn ergibt — Artikel, Beitrag, Kommentar.', "Un contenu qui garde son sens isolément : article, publication, commentaire.", 'ऐसी सामग्री जो अकेले भी अर्थपूर्ण रहे — लेख, पोस्ट, टिप्पणी।', '拿出去单独看也说得通的一块内容，比如一篇文章。', '拿出去單獨看也說得通的一塊內容，比如一篇文章。'],
  aside: ['본문 옆에 곁들이는 내용입니다. 빼도 본문이 그대로 읽힙니다.', 'Content beside the main flow — remove it and the main text still reads fine.', 'Contenido al margen del flujo principal: si se quita, el texto sigue leyéndose.', 'Conteúdo à margem do fluxo principal: se sair, o texto continua fazendo sentido.', '本文の脇に添える内容です。取り除いても本文はそのまま読めます。', 'Inhalt neben dem Haupttext — ohne ihn liest sich der Text unverändert.', "Contenu en marge du flux principal : sans lui, le texte se lit toujours.", 'मुख्य पाठ के किनारे की सामग्री — हटा दें तो भी मूल पाठ पढ़ा जाता है।', '和正文相关但不是主线的旁支内容。', '和正文相關但不是主線的旁支內容。'],
  footer: ['한 구획의 꼬리말입니다. 저작권, 연락처, 관련 링크가 들어갑니다.', 'The closing part of a section — copyright, contact details, related links.', 'La parte final de una sección: copyright, contacto, enlaces relacionados.', 'A parte final de uma seção: copyright, contato, links relacionados.', '一つの区画の末尾です。著作権表示や連絡先、関連リンクが入ります。', 'Der abschließende Teil eines Abschnitts — Copyright, Kontakt, verwandte Links.', "La partie finale d'une section : copyright, contact, liens connexes.", 'किसी खंड का अंतिम भाग — कॉपीराइट, संपर्क, संबंधित लिंक।', '一段内容结尾的部分 —— 版权、联系方式之类。', '一段內容結尾的部分 —— 版權、聯絡方式之類。'],
  div: ['아무 뜻이 없는 상자입니다. 다른 태그로 표현할 수 없을 때만 씁니다.', 'A box with no meaning of its own — reach for it only when no other element fits.', 'Una caja sin significado propio: úsala solo cuando ningún otro elemento encaje.', 'Uma caixa sem significado próprio: use só quando nenhum outro elemento serve.', '意味を持たない箱です。ほかのタグで表せないときだけ使います。', 'Ein Container ohne eigene Bedeutung — nur wenn kein anderes Element passt.', "Une boîte sans signification propre : à n'utiliser que si aucun autre élément ne convient.", 'बिना अर्थ का डिब्बा — तभी इस्तेमाल करें जब कोई और तत्व फ़िट न बैठे।', '没有语义的块级盒子。找不到合适的标签时才用它。', '沒有語意的區塊盒子。找不到合適的標籤時才用它。'],
  h1: ['그 문서에서 가장 큰 제목입니다. 한 문서에 하나가 원칙입니다.', 'The top-level heading of the page — one per document as a rule.', 'El encabezado de nivel superior de la página: como regla, uno por documento.', 'O título de nível mais alto da página: como regra, um por documento.', 'その文書でいちばん大きな見出しです。1文書に一つが原則です。', 'Die oberste Überschrift der Seite — in der Regel eine pro Dokument.', "Le titre de plus haut niveau de la page : en principe un seul par document.", 'पन्ने का सर्वोच्च शीर्षक — नियमतः हर दस्तावेज़ में एक।', '这一页最高一级的标题，通常只写一个。', '這一頁最高一級的標題，通常只寫一個。'],
  h2: ['h1 아래 단계의 제목입니다. 큰 갈래를 나눌 때 씁니다.', 'A heading one level below h1, used to divide the page into major parts.', 'Un encabezado un nivel por debajo de h1, para dividir la página en partes.', 'Um título um nível abaixo de h1, para dividir a página em partes.', 'h1の一つ下の見出しです。大きな区分けに使います。', 'Eine Überschrift eine Ebene unter h1, für die großen Abschnitte.', "Un titre d'un niveau sous h1, pour découper la page en grandes parties.", 'h1 से एक स्तर नीचे का शीर्षक — पन्ने को बड़े हिस्सों में बाँटने के लिए।', '第二级标题，用来切分大的段落。', '第二級標題，用來切分大的段落。'],
  h3: ['h2 안을 다시 나누는 제목입니다.', 'A heading that subdivides what sits under an h2.', 'Un encabezado que subdivide lo que hay bajo un h2.', 'Um título que subdivide o que está sob um h2.', 'h2の中をさらに分ける見出しです。', 'Eine Überschrift, die einen h2-Abschnitt weiter unterteilt.', "Un titre qui subdivise ce qui se trouve sous un h2.", 'h2 के भीतर के हिस्से को और बाँटने वाला शीर्षक।', '第三级标题，切分 h2 底下的内容。', '第三級標題，切分 h2 底下的內容。'],
  h4: ['네 번째 단계 제목입니다. 여기까지 내려가면 구조를 다시 볼 때입니다.', 'A fourth-level heading — needing this deep a nest often means the structure wants rethinking.', 'Un encabezado de cuarto nivel: llegar tan hondo suele indicar que conviene repensar la estructura.', 'Um título de quarto nível: chegar tão fundo costuma indicar que a estrutura merece revisão.', '四段目の見出しです。ここまで下がるなら構造を見直す頃合いです。', 'Eine Überschrift vierter Ebene — so tief verschachtelt lohnt ein Blick auf die Struktur.', "Un titre de quatrième niveau : descendre si bas invite à revoir la structure.", 'चौथे स्तर का शीर्षक — इतनी गहराई अक्सर संरचना पर पुनर्विचार का संकेत है।', '第四级标题，用在 h3 之下。', '第四級標題，用在 h3 之下。'],
  h5: ['다섯 번째 단계 제목입니다. 실제로 쓰이는 일은 드뭅니다.', 'A fifth-level heading — rarely needed in practice.', 'Un encabezado de quinto nivel: rara vez hace falta.', 'Um título de quinto nível: raramente necessário.', '五段目の見出しです。実際に使われることはまれです。', 'Eine Überschrift fünfter Ebene — in der Praxis selten nötig.', "Un titre de cinquième niveau : rarement utile en pratique.", 'पाँचवें स्तर का शीर्षक — व्यवहार में शायद ही ज़रूरत पड़ती है।', '第五级标题，实际上很少会用到。', '第五級標題，實際上很少會用到。'],
  h6: ['여섯 번째이자 가장 작은 제목입니다.', 'The sixth and smallest heading level.', 'El sexto y más pequeño nivel de encabezado.', 'O sexto e menor nível de título.', '六段目でいちばん小さい見出しです。', 'Die sechste und kleinste Überschriftenebene.', "Le sixième et plus petit niveau de titre.", 'छठा और सबसे छोटा शीर्षक स्तर।', '最低一级的标题，很少需要用到。', '最低一級的標題，很少需要用到。'],
  hgroup: ['제목과 그에 딸린 부제를 한 덩어리로 묶습니다.', 'Groups a heading together with the subheading that belongs to it.', 'Agrupa un encabezado con el subtítulo que le acompaña.', 'Agrupa um título com o subtítulo que o acompanha.', '見出しとそれに付く副題を一つのまとまりにします。', 'Fasst eine Überschrift mit ihrer Unterzeile zusammen.', "Regroupe un titre et le sous-titre qui l'accompagne.", 'शीर्षक और उसके उपशीर्षक को एक साथ बाँधता है।', '把标题和它的副标题捆在一起。', '把標題和它的副標題綁在一起。'],
  address: ['그 글이나 문서의 연락처를 표시합니다. 일반 주소를 적는 곳이 아닙니다.', 'Marks contact details for the article or document — not for any postal address.', 'Marca los datos de contacto del artículo o documento, no cualquier dirección postal.', 'Marca os dados de contato do artigo ou documento, não qualquer endereço postal.', 'その文章や文書の連絡先を示します。一般の住所を書く場所ではありません。', 'Kennzeichnet Kontaktangaben zum Artikel oder Dokument — nicht jede Postanschrift.', "Indique les coordonnées de l'article ou du document, pas une adresse postale quelconque.", 'लेख या दस्तावेज़ के संपर्क विवरण — कोई भी डाक पता नहीं।', '这段内容的联系方式。不是用来写普通地址的。', '這段內容的聯絡方式。不是用來寫普通地址的。'],
  search: ['검색을 위한 입력 묶음임을 알립니다. 비교적 최근에 표준이 된 태그입니다.', 'Marks a group of controls used for searching — a relatively recent addition to the standard.', 'Marca un grupo de controles de búsqueda; es una incorporación reciente al estándar.', 'Marca um grupo de controles de busca; é uma adição recente ao padrão.', '検索のための入力のまとまりであることを示します。比較的新しく標準になった要素です。', 'Kennzeichnet eine Gruppe von Suchsteuerelementen — erst seit Kurzem im Standard.', "Signale un groupe de contrôles de recherche : un ajout récent à la norme.", 'खोज के लिए बने नियंत्रणों का समूह दर्शाता है — मानक में अपेक्षाकृत नया।', '包住搜索框那一块的容器。', '包住搜尋框那一塊的容器。'],

  /* ───────── 글 ───────── */
  p: ['한 문단입니다. 닫는 태그를 빼도 브라우저가 알아서 닫습니다.', 'A paragraph. Browsers close it for you if you leave the closing tag out.', 'Un párrafo. El navegador lo cierra por ti si omites la etiqueta de cierre.', 'Um parágrafo. O navegador o fecha sozinho se você omitir a tag final.', '一つの段落です。閉じタグを省いてもブラウザーが閉じてくれます。', 'Ein Absatz. Browser schließen ihn automatisch, wenn das End-Tag fehlt.', "Un paragraphe. Le navigateur le ferme tout seul si la balise fermante manque.", 'एक अनुच्छेद। बंद टैग छोड़ देने पर ब्राउज़र स्वयं बंद कर देता है।', '一个段落。段与段之间浏览器会自动留空。', '一個段落。段與段之間瀏覽器會自動留空。'],
  br: ['줄바꿈 하나입니다. 문단 간격을 벌리는 용도로 쓰면 안 됩니다.', 'A single line break — not a tool for adding space between paragraphs.', 'Un salto de línea; no sirve para separar párrafos.', 'Uma quebra de linha; não serve para espaçar parágrafos.', '改行一つです。段落の間隔を空ける目的で使ってはいけません。', 'Ein einzelner Zeilenumbruch — kein Mittel für Abstand zwischen Absätzen.', "Un simple retour à la ligne, pas un moyen d'espacer les paragraphes.", 'एक पंक्ति विराम — अनुच्छेदों के बीच जगह बनाने का साधन नहीं।', '强制换行。段落之间不该用它来留空。', '強制換行。段落之間不該用它來留空。'],
  hr: ['주제가 바뀌는 자리를 나타냅니다. 단순한 가로줄 장식이 아닙니다.', 'Marks a shift in topic — it is not merely a decorative horizontal line.', 'Marca un cambio de tema; no es una simple línea decorativa.', 'Marca uma mudança de assunto; não é apenas uma linha decorativa.', '話題が変わる位置を表します。単なる横線の飾りではありません。', 'Markiert einen Themenwechsel — keine bloße Zierlinie.', "Marque un changement de sujet, ce n'est pas une simple ligne décorative.", 'विषय बदलने का संकेत — यह महज़ सजावटी रेखा नहीं है।', '话题转换的分隔。以前只是一条横线，现在有了语义。', '話題轉換的分隔。以前只是一條橫線，現在有了語意。'],
  pre: ['적은 그대로 보여 줍니다. 공백과 줄바꿈이 살아 있습니다.', 'Shows text exactly as written — spaces and line breaks are preserved.', 'Muestra el texto tal cual: se conservan espacios y saltos de línea.', 'Mostra o texto como escrito: espaços e quebras de linha são preservados.', '書いたそのままを表示します。空白と改行が保たれます。', 'Zeigt Text genau wie geschrieben — Leerzeichen und Umbrüche bleiben erhalten.', "Affiche le texte tel quel : espaces et retours à la ligne sont conservés.", 'पाठ जैसा लिखा है वैसा दिखाता है — स्पेस और लाइन ब्रेक बने रहते हैं।', '原样保留空格和换行，代码块常配 code 一起用。', '原樣保留空格和換行，程式碼區塊常配 code 一起用。'],
  blockquote: ['다른 곳에서 가져온 긴 인용입니다. cite 속성에 출처 주소를 적습니다.', 'A long quotation from elsewhere; put the source URL in the cite attribute.', 'Una cita larga de otra fuente; la URL de origen va en el atributo cite.', 'Uma citação longa de outra fonte; a URL de origem vai no atributo cite.', 'ほかから引いた長い引用です。cite属性に出典のURLを書きます。', 'Ein längeres Zitat von anderswo; die Quell-URL steht im cite-Attribut.', "Une longue citation venue d'ailleurs ; l'URL de la source va dans l'attribut cite.", 'कहीं और से लिया गया लंबा उद्धरण; स्रोत URL cite विशेषण में लिखें।', '整段的引用。出处写在 cite 属性里。', '整段的引用。出處寫在 cite 屬性裡。'],
  figure: ['본문에서 참조하는 그림이나 코드 묶음입니다. 옮겨도 뜻이 유지됩니다.', 'A self-contained figure or code block referenced from the text; it can be moved without loss.', 'Una figura o bloque de código autocontenido al que remite el texto; puede moverse sin perder sentido.', 'Uma figura ou bloco de código autocontido citado no texto; pode ser movido sem perda.', '本文から参照する図やコードのまとまりです。位置を移しても意味が保たれます。', 'Eine in sich geschlossene Abbildung oder Codeblock, auf die der Text verweist; verschiebbar ohne Sinnverlust.', "Une figure ou un bloc de code autonome référencé depuis le texte ; déplaçable sans perte.", 'पाठ से संदर्भित स्वतंत्र चित्र या कोड-खंड; हटाकर रखने पर भी अर्थ बना रहता है।', '图片、图表这类可以独立看的插入内容。', '圖片、圖表這類可以獨立看的插入內容。'],
  figcaption: ['figure에 붙는 설명입니다. figure 안에서 처음이나 마지막에 둡니다.', 'The caption for a figure, placed as the first or last child inside it.', 'El pie de una figura, como primer o último hijo dentro de figure.', 'A legenda de uma figura, como primeiro ou último filho dentro de figure.', 'figureに付く説明です。figureの中の先頭か末尾に置きます。', 'Die Beschriftung einer Abbildung, als erstes oder letztes Kind darin.', "La légende d'une figure, placée en premier ou en dernier dans figure.", 'figure की व्याख्या — उसके भीतर पहले या अंतिम बच्चे के रूप में।', 'figure 的说明文字。', 'figure 的說明文字。'],

  /* ───────── 문장 안 표시 ───────── */
  a: ['다른 곳으로 가는 링크입니다. href가 없으면 링크가 아닌 자리표시가 됩니다.', 'A link to somewhere else; without href it is a placeholder rather than a link.', 'Un enlace a otro lugar; sin href es un marcador, no un enlace.', 'Um link para outro lugar; sem href é apenas um marcador, não um link.', 'ほかへ移動するリンクです。hrefがなければリンクではなく仮の印になります。', 'Ein Link woandershin; ohne href ist es ein Platzhalter, kein Link.', "Un lien vers ailleurs ; sans href, c'est un espace réservé, pas un lien.", 'कहीं और ले जाने वाला लिंक; href न हो तो यह लिंक नहीं, महज़ स्थानधारक है।', '通往别处的链接。没有 href 就只是个占位，算不上链接。', '通往別處的連結。沒有 href 就只是個占位，算不上連結。'],
  span: ['문장 안에서 아무 뜻 없이 감싸는 상자입니다. 색이나 글꼴을 따로 줄 때 씁니다.', 'An inline box with no meaning, used to style part of a line differently.', 'Una caja en línea sin significado, para dar estilo a parte de un texto.', 'Uma caixa em linha sem significado, para estilizar parte de um texto.', '文中を意味なく包む箱です。色や書体だけ変えたいときに使います。', 'Ein Inline-Container ohne Bedeutung, um Teile einer Zeile anders zu gestalten.', "Une boîte en ligne sans signification, pour styler une partie de texte.", 'पंक्ति के भीतर बिना अर्थ का डिब्बा — किसी हिस्से को अलग रूप देने के लिए।', '行内的无义盒子，用来给一句话里的某段单独设样式。', '行內的無義盒子，用來給一句話裡的某段單獨設樣式。'],
  strong: ['중요하다는 뜻입니다. 굵게 보이는 것은 결과일 뿐입니다.', 'Marks text as important; looking bold is a side effect, not the point.', 'Marca el texto como importante; verse en negrita es un efecto, no el objetivo.', 'Marca o texto como importante; ficar em negrito é efeito, não o objetivo.', '重要であるという意味です。太く見えるのは結果にすぎません。', 'Kennzeichnet Wichtiges; die fette Darstellung ist nur die Folge.', "Indique une information importante ; l'affichage en gras n'est qu'un effet.", 'महत्वपूर्ण होने का अर्थ देता है; मोटा दिखना केवल परिणाम है।', '表示重要。看起来变粗只是附带结果，不是目的。', '表示重要。看起來變粗只是附帶結果，不是目的。'],
  em: ['말할 때 힘주어 읽는 부분입니다. 기울임은 그 표현일 뿐입니다.', 'The part you would stress when reading aloud; italics are just how that is shown.', 'La parte que enfatizarías al leer en voz alta; la cursiva es solo su forma visual.', 'A parte que você enfatizaria ao ler em voz alta; o itálico é só a aparência.', '声に出すとき力を入れて読む部分です。斜体はその表れにすぎません。', 'Der Teil, den man beim Vorlesen betonen würde; kursiv ist nur die Darstellung.', "La partie que l'on accentuerait à voix haute ; l'italique n'est que son rendu.", 'वह हिस्सा जिसे पढ़ते समय ज़ोर देंगे; तिरछापन उसकी प्रस्तुति भर है।', '表示强调。读屏工具会把语气读出来。', '表示強調。螢幕閱讀器會把語氣讀出來。'],
  b: ['뜻의 강조 없이 눈에 띄게만 합니다. 중요하다면 strong을 씁니다.', 'Draws attention without implying importance — use strong when it matters.', 'Llama la atención sin implicar importancia; usa strong si de verdad importa.', 'Chama atenção sem implicar importância; use strong quando importar.', '意味の強調なしに目立たせるだけです。重要ならstrongを使います。', 'Hebt hervor, ohne Wichtigkeit auszudrücken — dafür gibt es strong.', "Attire l'œil sans marquer d'importance ; pour cela, utilisez strong.", 'बिना महत्व जताए ध्यान खींचता है — महत्व हो तो strong लें।', '只是想让它粗一点，不带任何轻重之分。', '只是想讓它粗一點，不帶任何輕重之分。'],
  i: ['다른 결의 말임을 나타냅니다. 외래어나 학명, 생각 속 말에 씁니다.', 'Text in a different voice — foreign words, scientific names, inner thoughts.', 'Texto en otro registro: extranjerismos, nombres científicos, pensamientos.', 'Texto em outro registro: estrangeirismos, nomes científicos, pensamentos.', '調子の違う言葉を表します。外来語や学名、心の中の言葉に使います。', 'Text in anderem Tonfall — Fremdwörter, wissenschaftliche Namen, Gedanken.', "Un texte d'un autre registre : mots étrangers, noms scientifiques, pensées.", 'भिन्न स्वर का पाठ — विदेशी शब्द, वैज्ञानिक नाम, मन की बात।', '换一种语气的文字 —— 术语、外来词、想法。', '換一種語氣的文字 —— 術語、外來語、想法。'],
  u: ['맞춤법 오류처럼 별도 표시가 필요한 부분에 밑줄을 긋습니다.', 'Underlines text that needs a non-textual annotation, such as a spelling error.', 'Subraya texto que requiere una anotación no textual, como un error ortográfico.', 'Sublinha texto que precisa de anotação não textual, como um erro ortográfico.', '綴りの誤りなど、別途印が必要な部分に下線を引きます。', 'Unterstreicht Text, der eine nicht-textliche Anmerkung braucht, etwa Rechtschreibfehler.', "Souligne un texte nécessitant une annotation non textuelle, comme une faute d'orthographe.", 'ऐसा पाठ रेखांकित करता है जिसे ग़ैर-पाठ्य टिप्पणी चाहिए, जैसे वर्तनी की त्रुटि।', '标出非文字性的注记，比如拼写错误。别拿它当链接用。', '標出非文字性的註記，比如拼字錯誤。別拿它當連結用。'],
  s: ['이제는 맞지 않는 내용에 취소선을 긋습니다. 삭제 이력에는 del을 씁니다.', 'Strikes through content that is no longer accurate; for edit history use del.', 'Tacha contenido que ya no es correcto; para el historial de ediciones usa del.', 'Risca conteúdo que já não é correto; para histórico de edições use del.', 'もう正しくない内容に取り消し線を引きます。編集履歴にはdelを使います。', 'Streicht nicht mehr Zutreffendes durch; für Änderungsverlauf nimmt man del.', "Barre un contenu devenu inexact ; pour l'historique des modifications, utilisez del.", 'अब सही न रही सामग्री पर काट देता है; संपादन इतिहास के लिए del लें।', '已经不再准确的内容。删掉的内容要用 del。', '已經不再正確的內容。刪掉的內容要用 del。'],
  mark: ['찾아보는 사람에게 중요한 부분을 형광펜처럼 표시합니다.', 'Highlights the part that matters to the reader, like a marker pen.', 'Resalta la parte relevante para quien lee, como un rotulador.', 'Realça a parte relevante para quem lê, como um marca-texto.', '読む人にとって重要な部分を蛍光ペンのように示します。', 'Hebt hervor, was für den Lesenden zählt — wie ein Textmarker.', "Surligne ce qui compte pour le lecteur, comme un marqueur.", 'पाठक के लिए महत्वपूर्ण हिस्से को हाइलाइटर की तरह चिह्नित करता है।', '像荧光笔一样标出和当下相关的部分。', '像螢光筆一樣標出和當下相關的部分。'],
  small: ['면책 조항이나 저작권처럼 곁들이는 작은 글씨입니다.', 'Side comments in small print — disclaimers, copyright lines.', 'Letra pequeña al margen: descargos de responsabilidad, líneas de copyright.', 'Letra miúda ao lado: isenções de responsabilidade, linhas de copyright.', '免責事項や著作権表示のような添え書きです。', 'Kleingedrucktes am Rand — Haftungsausschlüsse, Copyright-Zeilen.', "Les mentions en petits caractères : avertissements, lignes de copyright.", 'किनारे की छोटी लिखावट — अस्वीकरण, कॉपीराइट पंक्तियाँ।', '免责声明、版权这类附带的小字。', '免責聲明、版權這類附帶的小字。'],
  sub: ['아래 첨자입니다. H₂O의 2처럼 씁니다.', 'Subscript text, as in the 2 of H₂O.', 'Texto en subíndice, como el 2 de H₂O.', 'Texto em subscrito, como o 2 de H₂O.', '下付き文字です。H₂Oの2のように使います。', 'Tiefgestellter Text, wie die 2 in H₂O.', "Texte en indice, comme le 2 de H₂O.", 'निचला अंक — जैसे H₂O का 2।', '下标。化学式的 H₂O 就靠它。', '下標。化學式的 H₂O 就靠它。'],
  sup: ['위 첨자입니다. 제곱이나 각주 번호에 씁니다.', 'Superscript text, used for powers and footnote markers.', 'Texto en superíndice, para potencias y llamadas de nota.', 'Texto em sobrescrito, para potências e chamadas de nota.', '上付き文字です。累乗や脚注番号に使います。', 'Hochgestellter Text, für Potenzen und Fußnotenzeichen.', "Texte en exposant, pour les puissances et les appels de note.", 'ऊपरी अंक — घात और पादटिप्पणी संकेतों के लिए।', '上标。平方和脚注号码用它。', '上標。平方和註腳號碼用它。'],
  code: ['코드 한 조각입니다. 대개 고정폭 글꼴로 보입니다.', 'A fragment of code, usually shown in a monospace font.', 'Un fragmento de código, normalmente en tipografía monoespaciada.', 'Um trecho de código, normalmente em fonte monoespaçada.', 'コードの断片です。ふつう等幅フォントで表示されます。', 'Ein Codefragment, meist in dicktengleicher Schrift dargestellt.', "Un fragment de code, généralement affiché en police à chasse fixe.", 'कोड का एक अंश — आमतौर पर मोनोस्पेस फ़ॉन्ट में।', '一小段代码或者变量名。', '一小段程式碼或者變數名。'],
  kbd: ['사용자가 누르는 키를 나타냅니다. Ctrl이나 Enter처럼 씁니다.', 'Represents a key the user presses, such as Ctrl or Enter.', 'Representa una tecla que pulsa el usuario, como Ctrl o Enter.', 'Representa uma tecla que o usuário aperta, como Ctrl ou Enter.', '利用者が押すキーを表します。CtrlやEnterのように使います。', 'Steht für eine Taste, die man drückt, etwa Strg oder Enter.', "Représente une touche pressée par l'utilisateur, comme Ctrl ou Entrée.", 'उपयोगकर्ता द्वारा दबाई जाने वाली कुंजी — जैसे Ctrl या Enter।', '要用户按下的那个按键，比如 Ctrl。', '要使用者按下的那個按鍵，比如 Ctrl。'],
  samp: ['프로그램이 내놓은 출력입니다.', 'Output produced by a program.', 'La salida producida por un programa.', 'A saída produzida por um programa.', 'プログラムが出した出力です。', 'Von einem Programm erzeugte Ausgabe.', "La sortie produite par un programme.", 'किसी प्रोग्राम द्वारा दिया गया आउटपुट।', '程序吐出来的输出内容。', '程式吐出來的輸出內容。'],
  var: ['수식이나 코드 안의 변수 이름입니다.', 'The name of a variable in a formula or in code.', 'El nombre de una variable en una fórmula o en código.', 'O nome de uma variável numa fórmula ou em código.', '数式やコード中の変数名です。', 'Der Name einer Variablen in einer Formel oder im Code.', "Le nom d'une variable dans une formule ou du code.", 'सूत्र या कोड में किसी चर का नाम।', '数学式或程序里的一个变量名。', '數學式或程式裡的一個變數名。'],
  q: ['문장 안에 들어가는 짧은 인용입니다. 따옴표는 브라우저가 붙입니다.', 'A short inline quotation; the browser adds the quotation marks.', 'Una cita corta en línea; el navegador añade las comillas.', 'Uma citação curta em linha; o navegador acrescenta as aspas.', '文中に入る短い引用です。引用符はブラウザーが付けます。', 'Ein kurzes Zitat im Fließtext; die Anführungszeichen setzt der Browser.', "Une courte citation en ligne ; le navigateur ajoute les guillemets.", 'पंक्ति के भीतर छोटा उद्धरण; उद्धरण चिह्न ब्राउज़र लगाता है।', '短短的行内引用。引号由浏览器按语言自动加。', '短短的行內引用。引號由瀏覽器按語言自動加。'],
  cite: ['작품의 제목을 나타냅니다. 사람 이름에는 쓰지 않습니다.', 'Names the title of a work — not the name of a person.', 'Indica el título de una obra, no el nombre de una persona.', 'Indica o título de uma obra, não o nome de uma pessoa.', '作品の題名を表します。人の名前には使いません。', 'Nennt den Titel eines Werks — nicht den Namen einer Person.', "Désigne le titre d'une œuvre, pas le nom d'une personne.", 'किसी कृति का शीर्षक बताता है — व्यक्ति का नाम नहीं।', '作品的名字 —— 书名、片名之类。', '作品的名字 —— 書名、片名之類。'],
  abbr: ['줄임말입니다. title 속성에 원래 말을 적어 둡니다.', 'An abbreviation; put the expansion in the title attribute.', 'Una abreviatura; escribe el desarrollo en el atributo title.', 'Uma abreviatura; coloque a forma completa no atributo title.', '略語です。title属性に元の語を書いておきます。', 'Eine Abkürzung; die Auflösung steht im title-Attribut.', "Une abréviation ; la forme développée va dans l'attribut title.", 'संक्षिप्त रूप; पूरा रूप title विशेषण में लिखें।', '缩写。全称写在 title 属性里。', '縮寫。全稱寫在 title 屬性裡。'],
  time: ['날짜나 시각입니다. datetime 속성에 기계가 읽을 꼴로 적습니다.', 'A date or time; the datetime attribute carries the machine-readable form.', 'Una fecha u hora; el atributo datetime lleva la forma legible por máquina.', 'Uma data ou hora; o atributo datetime traz a forma legível por máquina.', '日付や時刻です。datetime属性に機械が読める形式で書きます。', 'Ein Datum oder eine Uhrzeit; das datetime-Attribut trägt die maschinenlesbare Form.', "Une date ou une heure ; l'attribut datetime porte la forme lisible par machine.", 'तिथि या समय; मशीन-पठनीय रूप datetime विशेषण में रहता है।', '机器能读的日期或时间，写在 datetime 属性里。', '機器能讀的日期或時間，寫在 datetime 屬性裡。'],
  data: ['화면에 보이는 값 옆에 기계가 읽을 값을 함께 답니다.', 'Attaches a machine-readable value alongside the human-readable one.', 'Añade un valor legible por máquina junto al que ve la persona.', 'Anexa um valor legível por máquina ao lado do valor visível.', '画面に見える値の横に、機械が読む値を添えます。', 'Hängt an den lesbaren Wert einen maschinenlesbaren an.', "Associe une valeur lisible par machine à la valeur affichée.", 'दिखने वाले मान के साथ मशीन-पठनीय मान जोड़ता है।', '给一段文字配上机器能读的值。', '給一段文字配上機器能讀的值。'],
  dfn: ['그 자리에서 처음 정의되는 낱말을 나타냅니다.', 'Marks the term being defined at that point in the text.', 'Marca el término que se está definiendo en ese punto.', 'Marca o termo que está sendo definido naquele ponto.', 'その場で初めて定義される語を表します。', 'Kennzeichnet den Begriff, der an dieser Stelle definiert wird.', "Marque le terme défini à cet endroit du texte.", 'उस स्थान पर परिभाषित हो रहे शब्द को चिह्नित करता है।', '这个术语第一次下定义的地方。', '這個術語第一次下定義的地方。'],
  bdi: ['글자 방향이 다른 글이 주변을 흔들지 않게 가둡니다.', 'Isolates text whose direction might otherwise disturb the surrounding line.', 'Aísla texto cuya dirección podría alterar la línea que lo rodea.', 'Isola texto cuja direção poderia bagunçar a linha ao redor.', '文字の向きが違う文が周囲を乱さないよう囲い込みます。', 'Isoliert Text, dessen Leserichtung sonst die Umgebung stören würde.', "Isole un texte dont le sens d'écriture perturberait la ligne autour.", 'ऐसा पाठ अलग रखता है जिसकी दिशा आसपास की पंक्ति बिगाड़ सकती है।', '把一段文字的书写方向和周围隔开。用户名常需要。', '把一段文字的書寫方向和周圍隔開。使用者名稱常需要。'],
  bdo: ['글자 방향을 강제로 뒤집습니다. dir 속성이 반드시 필요합니다.', 'Forces the text direction; the dir attribute is required.', 'Fuerza la dirección del texto; el atributo dir es obligatorio.', 'Força a direção do texto; o atributo dir é obrigatório.', '文字の向きを強制的に変えます。dir属性が必須です。', 'Erzwingt die Schreibrichtung; das dir-Attribut ist Pflicht.', "Force le sens d'écriture ; l'attribut dir est obligatoire.", 'पाठ की दिशा ज़बरन बदलता है; dir विशेषण अनिवार्य है।', '强行指定这一段的书写方向。', '強行指定這一段的書寫方向。'],
  ruby: ['한자 위에 읽는 법을 다는 표기입니다. rt와 함께 씁니다.', 'Ruby annotation — pronunciation shown above characters, used with rt.', 'Anotación ruby: la lectura sobre los caracteres, se usa con rt.', 'Anotação ruby: a leitura acima dos caracteres, usada com rt.', '漢字の上に読み方を添える表記です。rtと一緒に使います。', 'Ruby-Anmerkung — die Lesung über den Zeichen, zusammen mit rt.', "Annotation ruby : la prononciation au-dessus des caractères, avec rt.", 'रूबी टिप्पणी — अक्षरों के ऊपर उच्चारण, rt के साथ।', '汉字上方标注读音的注音结构。', '漢字上方標註讀音的注音結構。'],
  rt: ['ruby 안에서 실제 읽는 법이 들어가는 자리입니다.', 'Inside ruby, this holds the pronunciation itself.', 'Dentro de ruby, contiene la lectura misma.', 'Dentro de ruby, contém a leitura em si.', 'rubyの中で実際の読み方が入る場所です。', 'Innerhalb von ruby steht hier die Lesung selbst.', "Dans ruby, contient la prononciation elle-même.", 'ruby के भीतर उच्चारण स्वयं यहाँ आता है।', '注音里实际的读音文字。', '注音裡實際的讀音文字。'],
  rp: ['ruby를 못 그리는 브라우저에서 대신 보여 줄 괄호입니다.', 'Fallback brackets shown by browsers that cannot render ruby.', 'Paréntesis de reserva para navegadores que no saben mostrar ruby.', 'Parênteses de reserva para navegadores que não exibem ruby.', 'rubyを描けないブラウザーで代わりに見せる括弧です。', 'Ersatzklammern für Browser, die Ruby nicht darstellen können.', "Parenthèses de repli pour les navigateurs qui ne gèrent pas ruby.", 'उन ब्राउज़रों के लिए वैकल्पिक कोष्ठक जो ruby नहीं दिखा पाते।', '给不支持注音的浏览器留的括号。', '給不支援注音的瀏覽器留的括號。'],
  wbr: ['여기서 줄이 바뀌어도 좋다고 알려 줍니다. 긴 주소에 씁니다.', 'Suggests a place where a line may break — handy inside long URLs.', 'Sugiere un punto donde puede romperse la línea; útil en URLs largas.', 'Sugere um ponto onde a linha pode quebrar; útil em URLs longas.', 'ここで改行してもよいと知らせます。長いURLに使います。', 'Schlägt eine Stelle für einen Zeilenumbruch vor — nützlich in langen URLs.', "Indique un endroit où la ligne peut se couper ; utile dans les longues URL.", 'बताता है कि यहाँ पंक्ति टूट सकती है — लंबे URL में उपयोगी।', '长字符串里允许换行的位置。', '長字串裡允許換行的位置。'],
  ins: ['나중에 더해진 부분입니다. 문서의 수정 이력을 남길 때 씁니다.', 'Content added later — used when a document keeps its edit history visible.', 'Contenido añadido después: se usa cuando el documento muestra su historial.', 'Conteúdo acrescentado depois: usado quando o documento mostra o histórico.', 'あとから加えられた部分です。文書の修正履歴を残すときに使います。', 'Später hinzugefügter Inhalt — wenn ein Dokument seinen Änderungsverlauf zeigt.', "Contenu ajouté ensuite : utile quand un document garde son historique visible.", 'बाद में जोड़ी गई सामग्री — जब दस्तावेज़ संपादन इतिहास दिखाता है।', '后来加进去的内容，默认带下划线。', '後來加進去的內容，預設帶底線。'],
  del: ['지워진 부분입니다. ins와 짝을 이뤄 수정 이력을 보여 줍니다.', 'Content that was removed; pairs with ins to show an edit history.', 'Contenido eliminado; forma pareja con ins para mostrar el historial.', 'Conteúdo removido; forma par com ins para mostrar o histórico.', '削除された部分です。insと対にして修正履歴を見せます。', 'Entfernter Inhalt; bildet mit ins den Änderungsverlauf ab.', "Contenu supprimé ; s'associe à ins pour montrer l'historique.", 'हटाई गई सामग्री; ins के साथ मिलकर संपादन इतिहास दिखाती है।', '被删掉的内容，默认带删除线。', '被刪掉的內容，預設帶刪除線。'],

  /* ───────── 목록 ───────── */
  ul: ['순서가 없는 목록입니다. 항목을 바꿔 놓아도 뜻이 그대로입니다.', 'An unordered list — reordering the items changes nothing.', 'Una lista sin orden: cambiar el orden no altera el sentido.', 'Uma lista sem ordem: trocar a ordem não muda o sentido.', '順序のない一覧です。項目を入れ替えても意味は変わりません。', 'Eine ungeordnete Liste — Umsortieren ändert nichts am Sinn.', "Une liste non ordonnée : changer l'ordre ne change rien.", 'बिना क्रम की सूची — क्रम बदलने से अर्थ नहीं बदलता।', '先后顺序无所谓的列表，前面画圆点。', '先後順序無所謂的清單，前面畫圓點。'],
  ol: ['순서가 있는 목록입니다. start로 시작 번호를, reversed로 거꾸로 셀 수 있습니다.', 'An ordered list; start sets the first number and reversed counts backwards.', 'Una lista ordenada; start fija el primer número y reversed cuenta al revés.', 'Uma lista ordenada; start define o primeiro número e reversed conta ao contrário.', '順序のある一覧です。startで開始番号を、reversedで逆順にできます。', 'Eine geordnete Liste; start setzt die Anfangszahl, reversed zählt rückwärts.', "Une liste ordonnée ; start fixe le premier numéro et reversed compte à rebours.", 'क्रमित सूची; start पहली संख्या तय करता है और reversed उल्टा गिनता है।', '顺序有意义的列表，会自动编号。', '順序有意義的清單，會自動編號。'],
  li: ['목록 안의 한 항목입니다. ul이나 ol 안에서만 씁니다.', 'One item in a list; it belongs inside a ul or an ol.', 'Un elemento de la lista; va dentro de un ul o un ol.', 'Um item da lista; fica dentro de um ul ou ol.', '一覧の中の一項目です。ulかolの中でのみ使います。', 'Ein Listenpunkt; gehört in ein ul oder ol.', "Un élément de liste ; il se place dans un ul ou un ol.", 'सूची का एक आइटम; ul या ol के भीतर ही आता है।', '列表里的一项，装在 ul 或 ol 中。', '清單裡的一項，裝在 ul 或 ol 中。'],
  dl: ['용어와 뜻을 짝지어 늘어놓는 목록입니다.', 'A list that pairs terms with their descriptions.', 'Una lista que empareja términos con sus descripciones.', 'Uma lista que emparelha termos com suas descrições.', '用語と説明を組にして並べる一覧です。', 'Eine Liste, die Begriffe mit ihren Beschreibungen paart.', "Une liste appariant des termes et leurs descriptions.", 'शब्दों और उनके विवरण को जोड़ने वाली सूची।', '名词和解释成对出现的列表。', '名詞和解釋成對出現的清單。'],
  dt: ['dl 안에서 설명될 용어 쪽입니다.', 'Inside a dl, this is the term being described.', 'Dentro de un dl, es el término que se describe.', 'Dentro de um dl, é o termo descrito.', 'dlの中で説明される用語のほうです。', 'In einer dl steht hier der beschriebene Begriff.', "Dans un dl, c'est le terme décrit.", 'dl के भीतर वर्णित किया जा रहा शब्द।', '被解释的那个词条，dd 紧跟在它后面。', '被解釋的那個詞條，dd 緊跟在它後面。'],
  dd: ['dt에 붙는 설명 쪽입니다. 한 용어에 여러 개를 달 수 있습니다.', 'The description that follows a dt; one term may have several.', 'La descripción que sigue a un dt; un término puede tener varias.', 'A descrição que segue um dt; um termo pode ter várias.', 'dtに付く説明のほうです。一つの用語に複数付けられます。', 'Die Beschreibung nach einem dt; ein Begriff kann mehrere haben.', "La description qui suit un dt ; un terme peut en avoir plusieurs.", 'dt के बाद आने वाला विवरण; एक शब्द के कई हो सकते हैं।', '对上面那个名词的解释。', '對上面那個名詞的解釋。'],
  menu: ['명령이나 도구를 늘어놓는 목록입니다. 지금은 ul과 같게 다뤄집니다.', 'A list of commands or tools; today it behaves the same as ul.', 'Una lista de comandos o herramientas; hoy se comporta igual que ul.', 'Uma lista de comandos ou ferramentas; hoje se comporta como ul.', '命令や道具を並べる一覧です。現在はulと同じ扱いです。', 'Eine Liste von Befehlen oder Werkzeugen; verhält sich heute wie ul.', "Une liste de commandes ou d'outils ; se comporte aujourd'hui comme ul.", 'आदेशों या औज़ारों की सूची; आज यह ul जैसा ही व्यवहार करता है।', '一组命令按钮的列表，浏览器当成 ul 处理。', '一組命令按鈕的清單，瀏覽器當成 ul 處理。'],

  /* ───────── 표 ───────── */
  table: ['가로세로로 짜인 자료를 담습니다. 화면 배치 용도로는 쓰지 않습니다.', 'Holds data arranged in rows and columns — not a layout tool.', 'Contiene datos en filas y columnas; no es una herramienta de maquetación.', 'Contém dados em linhas e colunas; não é ferramenta de layout.', '縦横に並ぶデータを入れます。画面の配置目的では使いません。', 'Enthält Daten in Zeilen und Spalten — kein Layout-Werkzeug.', "Contient des données en lignes et colonnes ; ce n'est pas un outil de mise en page.", 'पंक्तियों और स्तंभों में सजा डेटा रखता है — यह लेआउट का साधन नहीं।', '行列构成的数据表。别拿它排版面。', '列欄構成的資料表。別拿它排版面。'],
  thead: ['표의 머리 줄 묶음입니다. 인쇄할 때 쪽마다 되풀이됩니다.', 'The header rows of a table; they repeat on each printed page.', 'Las filas de encabezado de la tabla; se repiten en cada página impresa.', 'As linhas de cabeçalho da tabela; repetem-se em cada página impressa.', '表の見出し行のまとまりです。印刷時にページごとに繰り返されます。', 'Die Kopfzeilen einer Tabelle; sie wiederholen sich auf jeder Druckseite.', "Les lignes d'en-tête du tableau ; elles se répètent à chaque page imprimée.", 'तालिका की शीर्ष पंक्तियाँ; छपाई में हर पन्ने पर दोहराई जाती हैं।', '表格最上面的表头那几行。', '表格最上面的表頭那幾列。'],
  tbody: ['표의 본문 줄 묶음입니다. 적지 않아도 브라우저가 만들어 넣습니다.', 'The body rows of a table; browsers insert one even if you do not write it.', 'Las filas del cuerpo; el navegador lo añade aunque no lo escribas.', 'As linhas do corpo; o navegador o insere mesmo se você não escrever.', '表の本体行のまとまりです。書かなくてもブラウザーが補います。', 'Die Datenzeilen einer Tabelle; Browser ergänzen sie auch ungeschrieben.', "Les lignes de corps du tableau ; le navigateur l'ajoute même sans l'écrire.", 'तालिका की मुख्य पंक्तियाँ; न लिखने पर भी ब्राउज़र जोड़ देता है।', '表格正文里装数据的那些行。', '表格正文裡裝資料的那些列。'],
  tfoot: ['표의 맨 아래 요약 줄입니다. 합계를 넣을 때 씁니다.', 'The summary rows at the bottom of a table, such as totals.', 'Las filas de resumen al pie de la tabla, como los totales.', 'As linhas de resumo no rodapé da tabela, como os totais.', '表の最下部の要約行です。合計を入れるときに使います。', 'Die Zusammenfassungszeilen am Tabellenende, etwa Summen.', "Les lignes de synthèse en bas du tableau, comme les totaux.", 'तालिका के नीचे की सारांश पंक्तियाँ, जैसे योग।', '表格底部的合计那几行。', '表格底部的合計那幾列。'],
  tr: ['표의 한 줄입니다. 안에 th나 td가 들어갑니다.', 'One row of a table, containing th or td cells.', 'Una fila de la tabla, con celdas th o td dentro.', 'Uma linha da tabela, com células th ou td dentro.', '表の一行です。中にthやtdが入ります。', 'Eine Tabellenzeile, die th- oder td-Zellen enthält.', "Une ligne du tableau, contenant des cellules th ou td.", 'तालिका की एक पंक्ति, जिसमें th या td कोशिकाएँ होती हैं।', '表格里横着的一行，里面装 th 或 td。', '表格裡橫著的一列，裡面裝 th 或 td。'],
  th: ['머리 칸입니다. scope로 그 칸이 행을 설명하는지 열을 설명하는지 밝힙니다.', 'A header cell; scope tells whether it labels a row or a column.', 'Una celda de encabezado; scope indica si describe una fila o una columna.', 'Uma célula de cabeçalho; scope indica se descreve uma linha ou coluna.', '見出しのセルです。scopeでその見出しが行か列かを示します。', 'Eine Kopfzelle; scope sagt, ob sie eine Zeile oder Spalte benennt.', "Une cellule d'en-tête ; scope indique si elle décrit une ligne ou une colonne.", 'शीर्ष कोशिका; scope बताता है कि यह पंक्ति की है या स्तंभ की।', '表头格。scope 属性告诉读屏工具它管哪一片。', '表頭格。scope 屬性告訴螢幕閱讀器它管哪一片。'],
  td: ['자료가 들어가는 칸입니다. colspan과 rowspan으로 칸을 합칩니다.', 'A data cell; colspan and rowspan merge it across columns or rows.', 'Una celda de datos; colspan y rowspan la fusionan por columnas o filas.', 'Uma célula de dados; colspan e rowspan a mesclam por colunas ou linhas.', 'データが入るセルです。colspanとrowspanでセルを結合します。', 'Eine Datenzelle; colspan und rowspan verbinden sie über Spalten oder Zeilen.', "Une cellule de données ; colspan et rowspan la fusionnent en largeur ou en hauteur.", 'डेटा कोशिका; colspan और rowspan इसे स्तंभों या पंक्तियों में मिलाते हैं।', '表格里装普通数据的一格。', '表格裡裝普通資料的一格。'],
  caption: ['표 전체의 제목입니다. table 안 맨 앞에 둡니다.', 'The title of the whole table, placed as its first child.', 'El título de toda la tabla, colocado como su primer hijo.', 'O título de toda a tabela, como seu primeiro filho.', '表全体の題名です。tableの中の先頭に置きます。', 'Der Titel der gesamten Tabelle, als erstes Kind darin.', "Le titre du tableau entier, placé en premier enfant.", 'पूरी तालिका का शीर्षक — table का पहला बच्चा।', '整张表格的标题，写在 table 的最前面。', '整張表格的標題，寫在 table 的最前面。'],
  colgroup: ['열 여러 개를 한 묶음으로 다룹니다. 열 단위 스타일에 씁니다.', 'Treats several columns as a group, handy for column-wide styling.', 'Trata varias columnas como grupo, útil para estilos por columna.', 'Trata várias colunas como grupo, útil para estilos por coluna.', '列をまとめて扱います。列単位のスタイル指定に使います。', 'Fasst mehrere Spalten zusammen, praktisch für spaltenweite Gestaltung.', "Traite plusieurs colonnes en groupe, pratique pour styler par colonne.", 'कई स्तंभों को समूह मानता है — स्तंभ-स्तरीय स्टाइल के लिए उपयोगी।', '把若干列捆成一组，好一起设样式。', '把若干欄綁成一組，好一起設樣式。'],
  col: ['colgroup 안에서 열 하나(또는 span만큼)를 가리킵니다.', 'Inside colgroup, points at one column — or as many as span says.', 'Dentro de colgroup, señala una columna, o tantas como diga span.', 'Dentro de colgroup, aponta uma coluna, ou quantas span disser.', 'colgroupの中で列一つ(またはspanの数だけ)を指します。', 'Verweist innerhalb von colgroup auf eine Spalte — oder so viele wie span sagt.', "Dans colgroup, désigne une colonne, ou autant que l'indique span.", 'colgroup के भीतर एक स्तंभ को इंगित करता है — या span जितने।', '单独指定某一竖列的样式。', '單獨指定某一直欄的樣式。'],

  /* ───────── 입력 ───────── */
  form: ['입력을 모아 보내는 묶음입니다. action에 보낼 곳, method에 방식을 적습니다.', 'Groups inputs for submission; action is where it goes, method how it is sent.', 'Agrupa entradas para enviarlas; action indica adónde y method cómo.', 'Agrupa entradas para envio; action diz para onde e method como.', '入力をまとめて送る単位です。actionに送り先、methodに方式を書きます。', 'Bündelt Eingaben zum Absenden; action nennt das Ziel, method die Art.', "Regroupe des saisies à envoyer ; action indique où et method comment.", 'भेजने के लिए इनपुट का समूह; action गंतव्य और method तरीक़ा बताता है।', '把输入的内容打包送出去的表单。', '把輸入的內容打包送出去的表單。'],
  input: ['한 칸의 입력입니다. type 하나로 글·숫자·날짜·색·파일이 모두 됩니다.', 'A single input control; the type attribute turns it into text, number, date, colour or file.', 'Un control de entrada; el atributo type lo convierte en texto, número, fecha, color o archivo.', 'Um controle de entrada; o atributo type o torna texto, número, data, cor ou arquivo.', '一つの入力欄です。type一つで文字・数値・日付・色・ファイルになります。', 'Ein einzelnes Eingabefeld; type macht daraus Text, Zahl, Datum, Farbe oder Datei.', "Un champ de saisie ; l'attribut type en fait du texte, un nombre, une date, une couleur ou un fichier.", 'एक इनपुट नियंत्रण; type विशेषण इसे टेक्स्ट, संख्या, तिथि, रंग या फ़ाइल बनाता है।', '输入的格子。type 一变，它的样子和行为就完全不同。', '輸入的格子。type 一變，它的樣子和行為就完全不同。'],
  textarea: ['여러 줄을 받는 입력 칸입니다. 기본값은 태그 사이에 적습니다.', 'A multi-line text box; its default text goes between the tags.', 'Un cuadro de texto multilínea; el texto inicial va entre las etiquetas.', 'Uma caixa de texto de várias linhas; o texto inicial fica entre as tags.', '複数行を受け取る入力欄です。初期値はタグの間に書きます。', 'Ein mehrzeiliges Textfeld; der Vorgabetext steht zwischen den Tags.', "Une zone de texte multiligne ; le texte par défaut se place entre les balises.", 'बहु-पंक्ति टेक्स्ट बॉक्स; डिफ़ॉल्ट पाठ टैग के बीच लिखा जाता है।', '可以换行的多行文字输入框。', '可以換行的多行文字輸入框。'],
  button: ['누르는 단추입니다. form 안에서 type을 안 적으면 제출 단추가 됩니다.', 'A clickable button; inside a form, omitting type makes it a submit button.', 'Un botón; dentro de un formulario, omitir type lo convierte en botón de envío.', 'Um botão; dentro de um formulário, omitir type o torna botão de envio.', '押すボタンです。form内でtypeを省くと送信ボタンになります。', 'Ein Knopf; ohne type wird er im Formular zum Absende-Knopf.', "Un bouton ; dans un formulaire, sans type il devient bouton d'envoi.", 'दबाने वाला बटन; फ़ॉर्म में type न देने पर यह सबमिट बटन बन जाता है।', '可以按的按钮。表单里默认是提交。', '可以按的按鈕。表單裡預設是送出。'],
  select: ['여러 값 중 하나를 고르는 목록입니다. multiple을 주면 여러 개도 됩니다.', 'A drop-down for choosing one value — add multiple to allow several.', 'Un desplegable para elegir un valor; con multiple se pueden elegir varios.', 'Um menu para escolher um valor; com multiple dá para escolher vários.', '複数の値から一つを選ぶ一覧です。multipleを付ければ複数選べます。', 'Eine Auswahlliste für einen Wert; mit multiple sind mehrere möglich.', "Une liste déroulante pour choisir une valeur ; avec multiple, on en choisit plusieurs.", 'एक मान चुनने की सूची; multiple देने पर कई भी चुने जा सकते हैं।', '点开会掉下来的下拉选单。', '點開會掉下來的下拉選單。'],
  option: ['select 안의 선택지 하나입니다.', 'One choice inside a select.', 'Una opción dentro de un select.', 'Uma opção dentro de um select.', 'selectの中の選択肢一つです。', 'Eine Auswahlmöglichkeit in einem select.', "Un choix au sein d'un select.", 'select के भीतर एक विकल्प।', '下拉选单里可选的一项。', '下拉選單裡可選的一項。'],
  optgroup: ['선택지를 갈래로 묶어 보여 줍니다.', 'Groups options under a labelled heading.', 'Agrupa opciones bajo un encabezado con etiqueta.', 'Agrupa opções sob um rótulo.', '選択肢を分類ごとにまとめて見せます。', 'Gruppiert Optionen unter einer Beschriftung.', "Regroupe des options sous un intitulé.", 'विकल्पों को नामित समूह में बाँटता है।', '把下拉选单里的选项分成几组。', '把下拉選單裡的選項分成幾組。'],
  label: ['입력 칸에 붙는 이름표입니다. for로 이으면 글자를 눌러도 칸이 선택됩니다.', 'A label for an input; linked with for, clicking the text focuses the field.', 'Una etiqueta para un campo; con for, hacer clic en el texto activa el campo.', 'Um rótulo para um campo; com for, clicar no texto foca o campo.', '入力欄に付く名札です。forでつなぐと文字を押しても欄が選ばれます。', 'Eine Beschriftung für ein Eingabefeld; mit for aktiviert ein Klick auf den Text das Feld.', "Une étiquette de champ ; reliée par for, cliquer le texte active le champ.", 'इनपुट का लेबल; for से जोड़ने पर पाठ पर क्लिक करने से फ़ील्ड चुन जाता है।', '输入框的说明文字。点它就等于点那个输入框。', '輸入框的說明文字。點它就等於點那個輸入框。'],
  fieldset: ['관련된 입력들을 테두리로 묶습니다. disabled로 한꺼번에 잠급니다.', 'Boxes related controls together; disabled switches them all off at once.', 'Agrupa controles relacionados; disabled los desactiva todos a la vez.', 'Agrupa controles relacionados; disabled desativa todos de uma vez.', '関連する入力を枠でまとめます。disabledで一度に無効にできます。', 'Fasst zusammengehörige Felder ein; disabled sperrt alle auf einmal.', "Encadre des champs liés ; disabled les désactive tous d'un coup.", 'संबंधित नियंत्रणों को घेरता है; disabled सबको एक साथ बंद कर देता है।', '把相关的几个输入框圈成一组。', '把相關的幾個輸入框圈成一組。'],
  legend: ['fieldset의 제목입니다. 묶음 안 첫 자리에 둡니다.', 'The caption for a fieldset, placed as its first child.', 'El título de un fieldset, como su primer hijo.', 'O título de um fieldset, como seu primeiro filho.', 'fieldsetの題名です。まとまりの先頭に置きます。', 'Die Beschriftung eines fieldset, als erstes Kind.', "Le titre d'un fieldset, placé en premier enfant.", 'fieldset का शीर्षक — उसका पहला बच्चा।', 'fieldset 那一组输入框的标题。', 'fieldset 那一組輸入框的標題。'],
  datalist: ['입력 칸에 뜨는 추천 목록입니다. 다른 값도 그대로 칠 수 있습니다.', 'Suggestions offered to an input; the user may still type anything else.', 'Sugerencias para un campo; el usuario puede escribir otra cosa igualmente.', 'Sugestões para um campo; o usuário ainda pode digitar outra coisa.', '入力欄に出る候補一覧です。ほかの値もそのまま入力できます。', 'Vorschläge für ein Eingabefeld; man darf trotzdem etwas anderes eintippen.', "Des suggestions pour un champ ; l'utilisateur peut toujours saisir autre chose.", 'इनपुट के लिए सुझाव; उपयोगकर्ता कुछ और भी टाइप कर सकता है।', '给输入框配的候选词，但仍可自由输入。', '給輸入框配的候選詞，但仍可自由輸入。'],
  output: ['계산 결과를 담는 자리입니다. 어떤 입력에서 나왔는지 for로 밝힙니다.', 'Holds the result of a calculation; for names the inputs it came from.', 'Contiene el resultado de un cálculo; for indica de qué campos proviene.', 'Contém o resultado de um cálculo; for indica de quais campos veio.', '計算結果を入れる場所です。どの入力から出たかをforで示します。', 'Enthält ein Rechenergebnis; for nennt die zugrunde liegenden Felder.', "Contient le résultat d'un calcul ; for nomme les champs d'origine.", 'गणना का परिणाम रखता है; for बताता है कि यह किन फ़ील्ड से आया।', '用来显示算出来的结果。', '用來顯示算出來的結果。'],
  progress: ['일이 얼마나 진행됐는지 보여 주는 막대입니다.', 'A bar showing how far a task has got.', 'Una barra que muestra cuánto ha avanzado una tarea.', 'Uma barra que mostra o quanto uma tarefa avançou.', '作業がどこまで進んだかを示すバーです。', 'Ein Balken, der den Fortschritt einer Aufgabe zeigt.', "Une barre indiquant l'avancement d'une tâche.", 'दिखाता है कि कोई काम कितना बढ़ा — प्रगति पट्टी।', '进度条，表示做完了多少。', '進度條，表示做完了多少。'],
  meter: ['정해진 범위 안의 값을 눈금으로 보여 줍니다. 진행률에는 쓰지 않습니다.', 'Shows a value within a known range — not for progress.', 'Muestra un valor dentro de un rango conocido; no sirve para el progreso.', 'Mostra um valor dentro de um intervalo conhecido; não serve para progresso.', '決まった範囲の中の値を目盛りで示します。進行率には使いません。', 'Zeigt einen Wert in einem bekannten Bereich — nicht für Fortschritt.', "Affiche une valeur dans une plage connue ; pas pour l'avancement.", 'ज्ञात परिसर में कोई मान दिखाता है — प्रगति के लिए नहीं।', '在已知范围里的一个量，比如磁盘用量。', '在已知範圍裡的一個量，比如磁碟用量。'],

  /* ───────── 그림·소리·영상 ───────── */
  img: ['그림 한 장입니다. alt에 그림이 전하는 내용을 반드시 적습니다.', 'A single image; alt must carry what the image conveys.', 'Una imagen; alt debe transmitir lo que la imagen comunica.', 'Uma imagem; alt deve transmitir o que a imagem comunica.', '画像一枚です。altに画像が伝える内容を必ず書きます。', 'Ein Bild; alt muss wiedergeben, was das Bild vermittelt.', "Une image ; alt doit porter ce que l'image transmet.", 'एक चित्र; alt में वह लिखें जो चित्र बताता है।', '插入图片。alt 属性用来说明它画了什么。', '插入圖片。alt 屬性用來說明它畫了什麼。'],
  picture: ['화면 크기나 형식에 따라 다른 그림을 고르게 합니다.', 'Lets the browser pick a different image by screen size or format.', 'Permite elegir otra imagen según el tamaño de pantalla o el formato.', 'Permite escolher outra imagem conforme o tamanho da tela ou o formato.', '画面の大きさや形式に応じて別の画像を選ばせます。', 'Lässt den Browser je nach Bildschirm oder Format ein anderes Bild wählen.', "Laisse le navigateur choisir une autre image selon l'écran ou le format.", 'स्क्रीन आकार या फ़ॉर्मैट के अनुसार अलग चित्र चुनने देता है।', '按屏幕条件在几张图里挑一张。', '按螢幕條件在幾張圖裡挑一張。'],
  source: ['picture·video·audio 안에서 고를 수 있는 후보 하나입니다.', 'One candidate file inside picture, video or audio.', 'Un archivo candidato dentro de picture, video o audio.', 'Um arquivo candidato dentro de picture, video ou audio.', 'picture・video・audioの中で選べる候補の一つです。', 'Eine Kandidatendatei innerhalb von picture, video oder audio.', "Un fichier candidat dans picture, video ou audio.", 'picture, video या audio के भीतर एक विकल्प फ़ाइल।', '给 picture、video、audio 提供备选的来源。', '給 picture、video、audio 提供備選的來源。'],
  video: ['영상을 재생합니다. autoplay는 muted와 함께여야 대개 동작합니다.', 'Plays video; autoplay generally only works together with muted.', 'Reproduce vídeo; autoplay suele funcionar solo junto con muted.', 'Reproduz vídeo; autoplay geralmente só funciona junto com muted.', '動画を再生します。autoplayはmutedと一緒でないとたいてい動きません。', 'Spielt Video ab; autoplay funktioniert meist nur zusammen mit muted.', "Lit une vidéo ; autoplay ne fonctionne en général qu'avec muted.", 'वीडियो चलाता है; autoplay आमतौर पर muted के साथ ही काम करता है।', '把视频嵌进页面，自带播放控件。', '把影片嵌進頁面，自帶播放控制項。'],
  audio: ['소리를 재생합니다. controls를 주지 않으면 화면에 아무것도 안 보입니다.', 'Plays sound; without controls nothing appears on screen.', 'Reproduce sonido; sin controls no se ve nada en pantalla.', 'Reproduz som; sem controls nada aparece na tela.', '音を再生します。controlsを付けないと画面には何も出ません。', 'Spielt Ton ab; ohne controls ist nichts zu sehen.', "Lit du son ; sans controls, rien n'apparaît à l'écran.", 'ध्वनि चलाता है; controls न हो तो स्क्रीन पर कुछ नहीं दिखता।', '把声音嵌进页面，自带播放控件。', '把聲音嵌進頁面，自帶播放控制項。'],
  track: ['영상에 자막이나 설명을 붙입니다. WebVTT 파일을 가리킵니다.', 'Adds captions or descriptions to media, pointing at a WebVTT file.', 'Añade subtítulos o descripciones al medio, apuntando a un archivo WebVTT.', 'Adiciona legendas ou descrições à mídia, apontando para um arquivo WebVTT.', '動画に字幕や説明を付けます。WebVTTファイルを指します。', 'Fügt Untertitel oder Beschreibungen hinzu und verweist auf eine WebVTT-Datei.', "Ajoute sous-titres ou descriptions, en pointant un fichier WebVTT.", 'मीडिया में उपशीर्षक या विवरण जोड़ता है — WebVTT फ़ाइल की ओर संकेत।', '给影音配的字幕或说明轨。', '給影音配的字幕或說明軌。'],
  canvas: ['스크립트로 그림을 그리는 빈 화면입니다. 그린 것은 글자로 남지 않습니다.', 'A blank surface drawn on by script; what you draw is not text.', 'Una superficie en blanco para dibujar con script; lo dibujado no es texto.', 'Uma superfície em branco para desenhar via script; o traçado não é texto.', 'スクリプトで描く空の画面です。描いたものは文字として残りません。', 'Eine leere Fläche, auf der Skript zeichnet; das Gezeichnete ist kein Text.', "Une surface vierge dessinée par script ; le tracé n'est pas du texte.", 'स्क्रिप्ट से चित्र बनाने का खाली पटल; बनाया गया पाठ नहीं होता।', '用脚本一笔一笔画出来的画布。', '用腳本一筆一筆畫出來的畫布。'],
  svg: ['크기를 키워도 깨지지 않는 벡터 그림을 문서 안에 직접 그립니다.', 'Draws vector graphics inline; they stay sharp at any size.', 'Dibuja gráficos vectoriales en línea; se mantienen nítidos a cualquier tamaño.', 'Desenha gráficos vetoriais em linha; ficam nítidos em qualquer tamanho.', '拡大しても崩れないベクター画像を文書内に直接描きます。', 'Zeichnet Vektorgrafik direkt im Dokument; sie bleibt in jeder Größe scharf.', "Dessine du vectoriel dans le document ; net à toutes les tailles.", 'दस्तावेज़ में सीधे वेक्टर चित्र बनाता है; हर आकार पर साफ़ रहता है।', '直接写在页面里的矢量图，放大也不糊。', '直接寫在頁面裡的向量圖，放大也不糊。'],
  map: ['그림 위에 누를 수 있는 영역을 얹습니다. area와 함께 씁니다.', 'Overlays clickable regions on an image, used together with area.', 'Superpone regiones pulsables sobre una imagen; se usa con area.', 'Sobrepõe regiões clicáveis a uma imagem; usa-se com area.', '画像の上に押せる領域を重ねます。areaと一緒に使います。', 'Legt anklickbare Bereiche über ein Bild, gemeinsam mit area.', "Superpose des zones cliquables sur une image, avec area.", 'चित्र पर क्लिक करने योग्य क्षेत्र लगाता है — area के साथ।', '给图片划出可点击区域的地图。', '給圖片劃出可點擊區域的地圖。'],
  area: ['map 안의 누를 수 있는 한 조각입니다. 모양과 좌표로 범위를 정합니다.', 'One clickable region inside a map, defined by shape and coordinates.', 'Una región pulsable dentro de un map, definida por forma y coordenadas.', 'Uma região clicável dentro de um map, definida por forma e coordenadas.', 'mapの中の押せる一区画です。形と座標で範囲を決めます。', 'Ein anklickbarer Bereich in einer map, über Form und Koordinaten definiert.', "Une zone cliquable d'un map, définie par une forme et des coordonnées.", 'map के भीतर एक क्लिक-योग्य क्षेत्र — आकार और निर्देशांक से तय।', '图片地图里的一块可点击区域。', '圖片地圖裡的一塊可點擊區域。'],

  /* ───────── 끼워넣기 ───────── */
  iframe: ['다른 문서를 창처럼 끼워 넣습니다. title로 그 창이 무엇인지 알립니다.', 'Embeds another document as a window; title says what that window is.', 'Incrusta otro documento como una ventana; title dice qué contiene.', 'Incorpora outro documento como janela; title diz o que ela contém.', 'ほかの文書を窓のように埋め込みます。titleでその窓が何かを伝えます。', 'Bettet ein anderes Dokument als Fenster ein; title nennt dessen Inhalt.', "Intègre un autre document comme une fenêtre ; title en indique le contenu.", 'दूसरे दस्तावेज़ को खिड़की की तरह जोड़ता है; title बताता है वह क्या है।', '在页面里嵌进另一个页面。', '在頁面裡嵌進另一個頁面。'],
  embed: ['외부 플러그인 내용을 끼워 넣습니다. 요즘은 거의 쓰지 않습니다.', 'Embeds external plugin content; rarely used nowadays.', 'Incrusta contenido de complementos externos; hoy apenas se usa.', 'Incorpora conteúdo de plugins externos; hoje quase não se usa.', '外部プラグインの内容を埋め込みます。近ごろはほとんど使いません。', 'Bindet externe Plugin-Inhalte ein; heute kaum noch gebräuchlich.', "Intègre du contenu de plugin externe ; rarement utilisé aujourd'hui.", 'बाहरी प्लगइन सामग्री जोड़ता है; आजकल शायद ही इस्तेमाल होता है।', '嵌入外部插件的内容。如今基本不用了。', '嵌入外部外掛的內容。如今基本不用了。'],
  object: ['외부 자원을 끼워 넣습니다. 안에 대체 내용을 적어 둘 수 있습니다.', 'Embeds an external resource, with fallback content allowed inside.', 'Incrusta un recurso externo, con contenido alternativo dentro.', 'Incorpora um recurso externo, com conteúdo alternativo dentro.', '外部の資源を埋め込みます。中に代替の内容を書けます。', 'Bindet eine externe Ressource ein; im Inneren ist Ersatzinhalt möglich.', "Intègre une ressource externe, avec un contenu de repli à l'intérieur.", 'बाहरी संसाधन जोड़ता है; भीतर वैकल्पिक सामग्री रखी जा सकती है।', '嵌入外部资源，比 embed 更通用。', '嵌入外部資源，比 embed 更通用。'],
  portal: ['다른 페이지를 미리 보여 주고 그대로 넘어가게 하려던 실험 태그입니다.', 'An experimental element for previewing another page and navigating into it.', 'Un elemento experimental para previsualizar otra página y navegar a ella.', 'Um elemento experimental para pré-visualizar outra página e navegar até ela.', 'ほかのページを先に見せてそのまま遷移させる実験的な要素です。', 'Ein experimentelles Element, das eine andere Seite vorzeigt und dorthin führt.', "Un élément expérimental pour prévisualiser une autre page et y naviguer.", 'दूसरे पन्ने की झलक दिखाकर वहीं ले जाने वाला प्रयोगात्मक तत्व।', '可以预览再跳过去的嵌入方式，一直没被广泛采用。', '可以預覽再跳過去的嵌入方式，一直沒被廣泛採用。'],

  /* ───────── 스크립트·스타일 ───────── */
  script: ['자바스크립트를 싣거나 적습니다. defer를 주면 문서를 다 읽은 뒤 실행합니다.', 'Loads or contains JavaScript; defer runs it after the document is parsed.', 'Carga o contiene JavaScript; defer lo ejecuta tras analizar el documento.', 'Carrega ou contém JavaScript; defer executa após analisar o documento.', 'JavaScriptを読み込むか書きます。deferを付けると文書を読み終えてから実行します。', 'Lädt oder enthält JavaScript; defer führt es nach dem Parsen aus.', "Charge ou contient du JavaScript ; defer l'exécute après l'analyse du document.", 'जावास्क्रिप्ट लोड करता या रखता है; defer इसे दस्तावेज़ पढ़े जाने के बाद चलाता है।', '放 JavaScript，或者指向一个脚本文件。', '放 JavaScript，或者指向一個腳本檔案。'],
  noscript: ['스크립트가 꺼져 있을 때만 보이는 내용입니다.', 'Content shown only when scripting is unavailable.', 'Contenido visible solo cuando el script está desactivado.', 'Conteúdo exibido apenas quando o script está desativado.', 'スクリプトが無効なときだけ表示される内容です。', 'Inhalt, der nur ohne aktives Skript erscheint.', "Contenu affiché seulement si le script est désactivé.", 'सामग्री जो केवल तब दिखती है जब स्क्रिप्ट बंद हो।', '在不跑脚本的环境里显示的替代内容。', '在不跑腳本的環境裡顯示的替代內容。'],
  style: ['문서 안에 직접 적는 CSS입니다. head 안에 두는 것이 보통입니다.', 'CSS written directly in the document, usually inside head.', 'CSS escrito directamente en el documento, normalmente dentro de head.', 'CSS escrito diretamente no documento, normalmente dentro de head.', '文書内に直接書くCSSです。ふつうheadの中に置きます。', 'Direkt im Dokument notiertes CSS, üblicherweise im head.', "Du CSS écrit directement dans le document, en principe dans head.", 'दस्तावेज़ में सीधे लिखा CSS — आमतौर पर head के भीतर।', '直接写在页面里的 CSS。', '直接寫在頁面裡的 CSS。'],
  template: ['지금은 그리지 않고 스크립트로 복제해 쓰는 조각입니다.', 'A fragment that is not rendered now but cloned later by script.', 'Un fragmento que no se muestra ahora y se clona luego por script.', 'Um fragmento que não é exibido agora e depois é clonado por script.', '今は描画せず、あとでスクリプトが複製して使う断片です。', 'Ein Fragment, das jetzt nicht dargestellt, später per Skript geklont wird.', "Un fragment non rendu, cloné plus tard par script.", 'ऐसा अंश जो अभी नहीं दिखता, बाद में स्क्रिप्ट से नकल होता है।', '先不渲染的一段结构，交给脚本以后再用。', '先不算繪的一段結構，交給腳本以後再用。'],
  slot: ['웹 컴포넌트 안에서 바깥 내용이 들어올 자리를 비워 둡니다.', 'Reserves a place inside a web component for content from outside.', 'Reserva un lugar dentro de un componente web para contenido externo.', 'Reserva um lugar dentro de um componente web para conteúdo externo.', 'ウェブコンポーネント内で外の内容が入る場所を空けます。', 'Hält in einer Web-Komponente Platz für Inhalt von außen frei.', "Réserve dans un composant web une place pour du contenu extérieur.", 'वेब कंपोनेंट में बाहरी सामग्री के लिए जगह रखता है।', 'Web 组件里预留给外部内容的位置。', 'Web 元件裡預留給外部內容的位置。'],

  /* ───────── 문서 정보 ───────── */
  meta: ['문서에 관한 정보를 적습니다. charset·설명·뷰포트가 여기 들어갑니다.', 'Carries information about the document — charset, description, viewport.', 'Aporta información sobre el documento: charset, descripción, viewport.', 'Traz informações sobre o documento: charset, descrição, viewport.', '文書に関する情報を書きます。charsetや説明、viewportがここに入ります。', 'Trägt Angaben über das Dokument — charset, Beschreibung, Viewport.', "Porte des informations sur le document : charset, description, viewport.", 'दस्तावेज़ के बारे में जानकारी — charset, विवरण, viewport।', '页面的元数据 —— 描述、视口设定、编码。', '頁面的中繼資料 —— 描述、視區設定、編碼。'],
  link: ['다른 자원과 문서를 잇습니다. 스타일시트와 파비콘, 대체 언어를 가리킵니다.', 'Connects the document to another resource — stylesheets, favicons, alternate languages.', 'Conecta el documento con otro recurso: hojas de estilo, favicons, idiomas alternos.', 'Liga o documento a outro recurso: folhas de estilo, favicons, idiomas alternativos.', 'ほかの資源と文書をつなぎます。スタイルシートやファビコン、別言語を指します。', 'Verbindet das Dokument mit anderen Ressourcen — Stylesheets, Favicons, Sprachvarianten.', "Relie le document à d'autres ressources : feuilles de style, favicons, langues.", 'दस्तावेज़ को अन्य संसाधनों से जोड़ता है — स्टाइलशीट, फ़ेविकॉन, वैकल्पिक भाषाएँ।', '挂上外部资源，最常见的是样式表。', '掛上外部資源，最常見的是樣式表。'],

  /* ───────── 눌러서 여닫기 ───────── */
  details: ['접었다 펴는 상자입니다. 자바스크립트 없이 동작합니다.', 'A box that folds open and shut, working without any JavaScript.', 'Una caja que se pliega y despliega, sin necesidad de JavaScript.', 'Uma caixa que abre e fecha, sem precisar de JavaScript.', '折りたたんで開く箱です。JavaScriptなしで動きます。', 'Ein auf- und zuklappbarer Kasten — ganz ohne JavaScript.', "Une boîte qui se replie et se déplie, sans JavaScript.", 'खुलने-बंद होने वाला डिब्बा — बिना जावास्क्रिप्ट के काम करता है।', '可以折叠展开的一块内容。', '可以摺疊展開的一塊內容。'],
  summary: ['details가 접혀 있을 때 보이는 제목 줄입니다.', 'The line shown while a details box is closed.', 'La línea visible mientras la caja details está cerrada.', 'A linha visível enquanto a caixa details está fechada.', 'detailsが閉じているときに見える見出し行です。', 'Die Zeile, die bei geschlossenem details sichtbar ist.', "La ligne visible quand la boîte details est fermée.", 'details बंद रहने पर दिखने वाली पंक्ति।', '折叠块上那行一直看得见的标题。', '摺疊區塊上那行一直看得見的標題。'],
  dialog: ['대화 상자입니다. showModal로 열면 뒤쪽 조작이 막힙니다.', 'A dialog box; opened with showModal it blocks interaction behind it.', 'Un cuadro de diálogo; abierto con showModal bloquea lo que hay detrás.', 'Uma caixa de diálogo; aberta com showModal bloqueia o que está atrás.', 'ダイアログです。showModalで開くと背後の操作が止まります。', 'Ein Dialogfenster; mit showModal geöffnet sperrt es den Hintergrund.', "Une boîte de dialogue ; ouverte via showModal, elle bloque l'arrière-plan.", 'संवाद बॉक्स; showModal से खोलने पर पीछे की क्रियाएँ रुक जाती हैं।', '对话框。加 modal 会挡住后面的内容。', '對話框。加 modal 會擋住後面的內容。'],

  /* ───────── 더 쓰지 않는 것 ───────── */
  center: ['가운데 정렬을 위한 옛 태그입니다. 지금은 CSS로 합니다.', 'The old way to centre content; CSS does this now.', 'La forma antigua de centrar; hoy se hace con CSS.', 'A forma antiga de centralizar; hoje se faz com CSS.', '中央揃えのための古いタグです。今はCSSで行います。', 'Der alte Weg zum Zentrieren; heute macht das CSS.', "L'ancienne façon de centrer ; aujourd'hui, c'est le rôle du CSS.", 'बीच में लाने का पुराना तरीक़ा; अब यह CSS करता है।', '居中排版的旧标签。现在用 CSS 的 text-align。', '置中排版的舊標籤。現在用 CSS 的 text-align。'],
  font: ['글꼴과 크기, 색을 직접 지정하던 옛 태그입니다.', 'The old tag for setting typeface, size and colour directly.', 'La etiqueta antigua para fijar tipografía, tamaño y color.', 'A tag antiga para definir fonte, tamanho e cor diretamente.', '書体や大きさ、色を直接指定していた古いタグです。', 'Das alte Tag, um Schrift, Größe und Farbe direkt zu setzen.', "L'ancienne balise pour fixer police, taille et couleur.", 'फ़ॉन्ट, आकार और रंग सीधे तय करने वाला पुराना टैग।', '设定字体颜色大小的旧标签，已被 CSS 取代。', '設定字型顏色大小的舊標籤，已被 CSS 取代。'],
  marquee: ['글자를 흘러가게 하던 옛 태그입니다. 지금은 CSS 애니메이션을 씁니다.', 'The old scrolling-text tag; CSS animation replaces it.', 'La antigua etiqueta de texto en marcha; la sustituye la animación CSS.', 'A antiga tag de texto rolante; a animação CSS a substitui.', '文字を流していた古いタグです。今はCSSアニメーションを使います。', 'Das alte Lauftext-Tag; CSS-Animation ersetzt es.', "L'ancienne balise de texte défilant ; l'animation CSS la remplace.", 'चलते पाठ का पुराना टैग; अब CSS एनिमेशन इसका स्थान लेता है।', '让文字滚动的旧标签。别再用了。', '讓文字捲動的舊標籤。別再用了。'],
  blink: ['글자를 깜빡이게 하던 태그입니다. 어떤 브라우저도 더는 지원하지 않습니다.', 'Made text blink; no browser supports it any more.', 'Hacía parpadear el texto; ningún navegador lo admite ya.', 'Fazia o texto piscar; nenhum navegador ainda o suporta.', '文字を点滅させたタグです。どのブラウザーももう対応しません。', 'Ließ Text blinken; kein Browser unterstützt es mehr.', "Faisait clignoter le texte ; plus aucun navigateur ne le gère.", 'पाठ को टिमटिमाता था; अब कोई ब्राउज़र इसे नहीं मानता।', '让文字闪烁的旧标签，浏览器早就不理它了。', '讓文字閃爍的舊標籤，瀏覽器早就不理它了。'],
  big: ['글자를 한 단계 크게 하던 옛 태그입니다.', 'The old tag for one step larger text.', 'La etiqueta antigua para agrandar el texto un paso.', 'A tag antiga para aumentar o texto um passo.', '文字を一段大きくしていた古いタグです。', 'Das alte Tag für eine Stufe größeren Text.', "L'ancienne balise pour agrandir le texte d'un cran.", 'पाठ को एक स्तर बड़ा करने वाला पुराना टैग।', '把字调大一号的旧标签。', '把字調大一號的舊標籤。'],
  strike: ['취소선을 긋던 옛 태그입니다. 지금은 s나 del을 씁니다.', 'The old strike-through tag; use s or del instead.', 'La antigua etiqueta de tachado; hoy se usan s o del.', 'A antiga tag de riscado; hoje usam-se s ou del.', '取り消し線を引いていた古いタグです。今はsやdelを使います。', 'Das alte Durchstreichungs-Tag; heute nimmt man s oder del.', "L'ancienne balise de texte barré ; on utilise s ou del.", 'काटने वाला पुराना टैग; अब s या del का प्रयोग करें।', '画删除线的旧标签，现在用 del 或 s。', '畫刪除線的舊標籤，現在用 del 或 s。'],
  tt: ['고정폭 글꼴로 보여 주던 옛 태그입니다. 지금은 code를 씁니다.', 'The old monospace tag; code replaces it.', 'La antigua etiqueta monoespaciada; la sustituye code.', 'A antiga tag monoespaçada; code a substitui.', '等幅フォントで見せていた古いタグです。今はcodeを使います。', 'Das alte Tag für dicktengleiche Schrift; code ersetzt es.', "L'ancienne balise à chasse fixe ; code la remplace.", 'मोनोस्पेस दिखाने वाला पुराना टैग; अब code का प्रयोग करें।', '等宽字体的旧标签，现在用 code 或 CSS。', '等寬字型的舊標籤，現在用 code 或 CSS。'],
  frame: ['화면을 나눠 여러 문서를 띄우던 옛 방식의 한 칸입니다.', 'One pane of the old way of splitting the window between documents.', 'Un panel del antiguo método de dividir la ventana entre documentos.', 'Um painel do antigo método de dividir a janela entre documentos.', '画面を分けて複数の文書を表示していた古い方式の一枠です。', 'Ein Feld der alten Methode, das Fenster auf Dokumente aufzuteilen.', "Un volet de l'ancienne méthode de découpage de la fenêtre.", 'खिड़की को दस्तावेज़ों में बाँटने के पुराने तरीक़े का एक खाना।', '旧式框架集里的一格，早已废弃。', '舊式框架集裡的一格，早已廢棄。'],
  frameset: ['frame들을 배치하던 옛 태그입니다. body를 대신했습니다.', 'The old container that laid out frames in place of body.', 'El antiguo contenedor que colocaba frames en lugar de body.', 'O antigo contêiner que dispunha frames no lugar de body.', 'frameを配置していた古いタグです。bodyの代わりでした。', 'Der alte Container, der Frames anstelle von body anordnete.', "L'ancien conteneur disposant les frames à la place de body.", 'frame सजाने वाला पुराना कंटेनर — body की जगह लेता था।', '把窗口切成几格的旧方式，已被 iframe 取代。', '把視窗切成幾格的舊方式，已被 iframe 取代。'],
  acronym: ['두문자어를 나타내던 옛 태그입니다. 지금은 abbr 하나로 씁니다.', 'The old tag for acronyms; abbr covers this now.', 'La antigua etiqueta de siglas; hoy basta con abbr.', 'A antiga tag de siglas; hoje basta abbr.', '頭字語を表していた古いタグです。今はabbrに一本化されています。', 'Das alte Tag für Akronyme; heute genügt abbr.', "L'ancienne balise des acronymes ; abbr la remplace.", 'संक्षेपाक्षरों का पुराना टैग; अब abbr ही पर्याप्त है।', '首字母缩写的旧标签，现在统一用 abbr。', '首字母縮寫的舊標籤，現在統一用 abbr。'],
  applet: ['자바 애플릿을 띄우던 옛 태그입니다. 실행 환경 자체가 사라졌습니다.', 'The old tag for Java applets; the runtime itself is gone.', 'La antigua etiqueta de applets de Java; el entorno ya no existe.', 'A antiga tag de applets Java; o ambiente já não existe.', 'Javaアプレットを表示していた古いタグです。実行環境自体がなくなりました。', 'Das alte Tag für Java-Applets; die Laufzeitumgebung existiert nicht mehr.', "L'ancienne balise des applets Java ; l'environnement a disparu.", 'जावा एप्लेट का पुराना टैग; अब वह वातावरण ही नहीं रहा।', '嵌入 Java 小程序的旧标签，已经废弃。', '嵌入 Java 小程式的舊標籤，已經廢棄。'],
  dir: ['파일 목록을 표시하던 옛 태그입니다. ul이 그 자리를 대신합니다.', 'The old directory-listing tag; ul took its place.', 'La antigua etiqueta de listado de directorios; ul ocupó su lugar.', 'A antiga tag de listagem de diretórios; ul tomou seu lugar.', 'ファイル一覧を表示していた古いタグです。ulがその役を引き継ぎました。', 'Das alte Tag für Verzeichnislisten; ul hat es ersetzt.', "L'ancienne balise de liste de répertoires ; ul l'a remplacée.", 'फ़ाइल-सूची का पुराना टैग; ul ने उसकी जगह ली।', '目录列表的旧标签，现在用 ul。', '目錄清單的舊標籤，現在用 ul。'],
  math: ['수식을 적는 MathML의 뿌리 요소입니다. HTML 안에 그대로 쓸 수 있습니다.', 'The MathML root element for formulas; it can be written directly inside HTML.', 'El elemento raíz de MathML para fórmulas; se escribe directamente dentro de HTML.', 'O elemento raiz do MathML para fórmulas; escreve-se direto dentro do HTML.', '数式を書くMathMLの根の要素です。HTMLの中にそのまま書けます。', 'Das MathML-Wurzelelement für Formeln; es steht direkt im HTML.', 'L\'élément racine MathML pour les formules ; il s\'écrit directement dans le HTML.', 'सूत्रों के लिए MathML का मूल तत्व; इसे सीधे HTML के भीतर लिखा जा सकता है।', '写数学公式的 MathML 根元素，可以直接写在 HTML 里面。', '寫數學公式的 MathML 根元素，可以直接寫在 HTML 裡面。'],
  nobr: ['줄을 바꾸지 말라는 뜻이었습니다. 표준에 든 적이 없고 지금은 CSS로 합니다.', 'Meant to stop line breaking; it never entered the standard and CSS does this now.', 'Servía para impedir el salto de línea; nunca fue estándar y hoy se hace con CSS.', 'Servia para impedir a quebra de linha; nunca foi padrão e hoje se faz com CSS.', '改行しないという意味でした。標準に入ったことはなく、今はCSSで行います。', 'Sollte Zeilenumbrüche verhindern; war nie Standard, heute macht das CSS.', 'Servait à empêcher les retours à la ligne ; jamais normalisé, on utilise CSS.', 'पंक्ति न तोड़ने के लिए था; यह कभी मानक नहीं बना और अब यह काम CSS करता है।', '本来表示不要换行。它从未进入标准，现在改用 CSS 来做。', '本來表示不要換行。它從未進入標準，現在改用 CSS 來做。'],
  noframes: ['틀을 못 그리는 브라우저에 보여 줄 내용이었습니다. 틀과 함께 사라졌습니다.', 'Held the fallback shown when a browser could not draw frames; gone with frames.', 'Contenía lo que se mostraba si el navegador no dibujaba marcos; desapareció con ellos.', 'Continha o que se mostrava quando o navegador não desenhava quadros; sumiu com eles.', '枠を描けない閲覧ソフトに見せる内容でした。枠と一緒に使われなくなりました。', 'Enthielt den Ersatzinhalt, wenn ein Browser keine Frames darstellen konnte.', 'Contenait le contenu de secours si le navigateur ne gérait pas les cadres.', 'उन ब्राउज़रों के लिए वैकल्पिक सामग्री रखता था जो फ़्रेम नहीं बना पाते थे।', '用来放浏览器画不出框架时的替代内容，随框架一起被淘汰。', '用來放瀏覽器畫不出框架時的替代內容，隨框架一起被淘汰。'],
  noembed: ['끼워넣기를 못 하는 브라우저에 보여 줄 내용이었습니다.', 'Held the fallback shown when a browser could not handle an embedded object.', 'Contenía lo que se mostraba si el navegador no podía incrustar un objeto.', 'Continha o que se mostrava quando o navegador não conseguia incorporar um objeto.', '埋め込みができない閲覧ソフトに見せる内容でした。今は使いません。', 'Enthielt den Ersatzinhalt, wenn ein Browser ein eingebettetes Objekt nicht konnte.', 'Contenait le contenu de secours si le navigateur ne gérait pas l\'objet embarqué.', 'उन ब्राउज़रों के लिए वैकल्पिक सामग्री रखता था जो वस्तु जड़ नहीं सकते थे।', '用来放浏览器无法嵌入对象时的替代内容，现在已经不用。', '用來放瀏覽器無法嵌入物件時的替代內容，現在已經不用。'],
  plaintext: ['이 뒤로는 전부 날글로 읽으라는 뜻이었습니다. 닫는 꼴이 없어 되돌릴 수 없습니다.', 'Told the browser to read everything after it as plain text; it can never be closed.', 'Indicaba leer todo lo siguiente como texto plano; no se puede cerrar nunca.', 'Mandava ler tudo o que vem depois como texto puro; não há como fechar.', 'この後をすべて生の文字として読めという意味でした。閉じられないので戻せません。', 'Wies den Browser an, alles Folgende als reinen Text zu lesen; nicht schließbar.', 'Indiquait de lire tout ce qui suit comme du texte brut ; impossible à refermer.', 'इसके बाद सब कुछ सादे पाठ के रूप में पढ़ने को कहता था; इसे बंद नहीं किया जा सकता।', '表示后面的内容全部当纯文本读。它没有闭合形式，无法再切回来。', '表示後面的內容全部當純文字讀。它沒有閉合形式，無法再切回來。'],
  xmp: ['글을 적힌 그대로 보여 주던 태그입니다. pre가 그 자리를 이어받았습니다.', 'Showed text exactly as written; pre took over this job long ago.', 'Mostraba el texto tal cual estaba escrito; pre ocupó su lugar hace mucho.', 'Mostrava o texto exatamente como escrito; pre assumiu esse papel há muito.', '書いたそのままの形で文字を見せる札でした。今はpreがその役目を担います。', 'Zeigte Text genau wie geschrieben; pre hat diese Aufgabe übernommen.', 'Affichait le texte tel quel ; pre a repris ce rôle depuis longtemps.', 'पाठ को जैसा लिखा था वैसा ही दिखाता था; अब यह काम pre करता है।', '把文字原样照搬显示出来，这个位置早就由 pre 接手了。', '把文字原樣照搬顯示出來，這個位置早就由 pre 接手了。'],
  listing: ['옛 브라우저가 코드를 줄 맞춰 보여 주던 태그입니다.', 'An early tag that showed code with its line breaks kept; replaced by pre.', 'Una etiqueta antigua que mostraba código conservando los saltos; hoy es pre.', 'Uma etiqueta antiga que mostrava código mantendo as quebras; hoje é pre.', '古い閲覧ソフトが行を揃えて番付を見せていた札です。今はpreを使います。', 'Ein frühes Tag, das Code mit erhaltenen Zeilenumbrüchen zeigte; heute pre.', 'Une balise ancienne qui affichait du code en conservant les retours ; remplacée par pre.', 'पुराना टैग जो कोड को पंक्ति-विराम सहित दिखाता था; अब इसकी जगह pre है।', '早期浏览器用来按行显示代码的标签，如今由 pre 取代。', '早期瀏覽器用來按行顯示程式碼的標籤，如今由 pre 取代。'],
  basefont: ['문서 전체의 기본 글꼴을 정하던 태그입니다. 지금은 CSS로 합니다.', 'Set the default font for the whole document; CSS does this now.', 'Fijaba la fuente por defecto de todo el documento; hoy lo hace CSS.', 'Fixava a fonte padrão de todo o documento; hoje é o CSS que faz isso.', '文書全体の既定の書体を決める札でした。今はCSSで行います。', 'Legte die Standardschrift des ganzen Dokuments fest; heute macht das CSS.', 'Définissait la police par défaut du document ; CSS s\'en charge aujourd\'hui.', 'पूरे दस्तावेज़ का डिफ़ॉल्ट फ़ॉन्ट तय करता था; अब यह काम CSS करता है।', '用来设定整份文档的默认字体，现在改由 CSS 负责。', '用來設定整份文件的預設字型，現在改由 CSS 負責。'],
  keygen: ['열쇠 쌍을 만들어 보내던 입력이었습니다. 브라우저에서 모두 걷어냈습니다.', 'An input that generated a key pair; every browser has removed it.', 'Una entrada que generaba un par de claves; todos los navegadores la quitaron.', 'Uma entrada que gerava um par de chaves; todos os navegadores a removeram.', '鍵の組を作って送る入力欄でした。どの閲覧ソフトも取り除きました。', 'Ein Eingabefeld, das ein Schlüsselpaar erzeugte; alle Browser haben es entfernt.', 'Un champ qui générait une paire de clés ; tous les navigateurs l\'ont retiré.', 'एक इनपुट जो कुंजी-युग्म बनाता था; सभी ब्राउज़रों ने इसे हटा दिया।', '曾用来生成密钥对的输入控件，各家浏览器都已经移除。', '曾用來產生金鑰對的輸入控制項，各家瀏覽器都已經移除。'],
  spacer: ['빈자리를 만들던 넷스케이프 전용 태그입니다. 표준이 된 적이 없습니다.', 'A Netscape-only tag for inserting blank space; it never became standard.', 'Una etiqueta solo de Netscape para dejar espacio; nunca fue estándar.', 'Uma etiqueta só do Netscape para deixar espaço; nunca virou padrão.', '余白を作るネットスケープ専用の札でした。標準になったことはありません。', 'Ein reines Netscape-Tag für Leerraum; es wurde nie Standard.', 'Une balise propre à Netscape pour insérer un espace ; jamais normalisée.', 'ख़ाली जगह बनाने के लिए सिर्फ़ नेटस्केप का टैग; यह कभी मानक नहीं बना।', '网景专用的留白标签，从来没有成为标准。', '網景專用的留白標籤，從來沒有成為標準。'],
  isindex: ['검색 칸 하나를 만들던 태그입니다. form과 input이 대신하게 됐습니다.', 'Created a single search box; form and input replaced it.', 'Creaba una única caja de búsqueda; form e input la sustituyeron.', 'Criava uma única caixa de busca; form e input a substituíram.', '検索欄を一つ作る札でした。formとinputが代わりを務めます。', 'Erzeugte ein einzelnes Suchfeld; form und input haben es ersetzt.', 'Créait un unique champ de recherche ; form et input l\'ont remplacé.', 'एक अकेला खोज-बक्सा बनाता था; form और input ने इसकी जगह ले ली।', '用来生成一个搜索框，后来由 form 和 input 取代。', '用來產生一個搜尋框，後來由 form 和 input 取代。'],
  param: ['object에 넘길 값을 적던 태그입니다. object가 밀려나며 함께 빠졌습니다.', 'Passed a value into an object element; it faded out along with object.', 'Pasaba un valor al elemento object; desapareció junto con él.', 'Passava um valor ao elemento object; saiu de cena junto com ele.', 'objectに渡す値を書く札でした。objectが使われなくなり一緒に外れました。', 'Übergab einen Wert an ein object-Element; verschwand zusammen mit object.', 'Transmettait une valeur à un élément object ; disparu avec lui.', 'object तत्व को मान देता था; object के साथ ही यह भी चलन से बाहर हो गया।', '用来给 object 传值的标签，随着 object 淡出而一起被去掉。', '用來給 object 傳值的標籤，隨著 object 淡出而一起被去掉。'],
  rb: ['루비를 달 밑글자를 감싸던 태그입니다. 지금은 감싸지 않고 그냥 적습니다.', 'Wrapped the base text that ruby annotates; today the base is written bare.', 'Envolvía el texto base al que se anota ruby; hoy se escribe sin envolver.', 'Envolvia o texto base anotado pelo ruby; hoje escreve-se sem envolver.', 'ルビを振る親文字を包む札でした。今は包まずにそのまま書きます。', 'Umschloss den Basistext einer Ruby-Anmerkung; heute steht er unverpackt.', 'Entourait le texte de base annoté par ruby ; aujourd\'hui on l\'écrit sans balise.', 'रूबी जिस मूल पाठ पर लगती है उसे लपेटता था; अब मूल पाठ बिना लपेटे लिखा जाता है।', '用来包住注音所标注的本文，现在本文直接写、不再包起来。', '用來包住注音所標註的本文，現在本文直接寫、不再包起來。'],
  rtc: ['루비 설명을 한 겹 더 묶던 태그입니다. 두 겹 루비에만 쓰였습니다.', 'Grouped a second layer of ruby annotation; only used for double-sided ruby.', 'Agrupaba una segunda capa de anotación ruby; solo para ruby de dos niveles.', 'Agrupava uma segunda camada de anotação ruby; só para ruby de dois níveis.', 'ルビの説明をもう一段まとめる札でした。二重ルビにだけ使われました。', 'Fasste eine zweite Ebene der Ruby-Anmerkung zusammen; nur bei doppelter Ruby.', 'Regroupait une deuxième couche d\'annotation ruby ; réservé au ruby double.', 'रूबी टिप्पणी की दूसरी परत को समूह में बाँधता था; सिर्फ़ दोहरी रूबी में काम आता था।', '把注音说明再多包一层，只有双层注音才会用到。', '把注音說明再多包一層，只有雙層注音才會用到。'],
};
