/**
 * 한국어 공유 카드 — 경로에서 카드로 가는 대응표.
 *
 * 전에는 app 곳곳의 opengraph-image.tsx 1,799장이 이 일을 했다. 파일 규약이라
 * 편했지만 장마다 라우트 엔트리가 하나씩 생겨서, 컴파일 비용의 다섯 분의 넷을
 * 그것들이 썼다(카드를 치우면 컴파일이 4.3분에서 99초로 줄었다). 2코어 8GB
 * 빌드 컨테이너가 그 무게로 죽었다.
 *
 * 그래서 카드는 그대로 두고 **엔트리만** 접었다. 1,799개 라우트가 언어마다
 * 모듈 하나씩, 모두 열 개가 됐다. 그리는 것은 app/og/[...slug]/route.tsx 하나다.
 *
 * 키는 언어 접두사를 뺀 라우트다 — ''는 첫 화면, 'color/name'은 /color/name.
 * 낱장은 자기 섹션 카드를 쓴다(전에 파일 규약이 물려주던 것과 같다).
 * 그 물려주기는 lib/og-cards/index.ts의 cardFor가 한다.
 */
import type { ReactElement } from 'react';
import { newSnapCard } from '@/lib/snap/card';

import { hubCard as altitudeHub } from '@/lib/altitude/route';
import { hubCard as airHub } from '@/lib/air/route';
import { hubCard as ampereHub } from '@/lib/ampere/route';
import { hubCard as flightHub } from '@/lib/flight/route';
import { hubCard as raidHub } from '@/lib/raid/route';
import { hubCard as heredityHub } from '@/lib/heredity/route';
import { hubCard as exposureHub } from '@/lib/exposure/route';
import { hubCard as bloodHub } from '@/lib/blood/route';
import { hubCard as braHub } from '@/lib/bra/route';
import { hubCard as wineHub } from '@/lib/wine/route';
import { hubCard as bedHub } from '@/lib/bed/route';
import { hubCard as quakeHub } from '@/lib/quake/route';
import { hubCard as microwaveHub } from '@/lib/microwave/route';
import { hubCard as golfHub } from '@/lib/golf/route';
import { hubCard as powerbankHub } from '@/lib/powerbank/route';
import { hubCard as lumberHub } from '@/lib/lumber/route';
import { hubCard as tatamiHub } from '@/lib/tatami/route';
import { hubCard as cableHub } from '@/lib/cable/route';
import { hubCard as gengoHub } from '@/lib/gengo/route';
import { hubCard as bignumHub } from '@/lib/bignum/route';
import { hubCard as viewingHub } from '@/lib/viewing/route';
import { hubCard as passwordHub } from '@/lib/password/route';
import { hubCard as petfoodHub } from '@/lib/petfood/route';
import { hubCard as sizeHub } from '@/lib/size/route';
import { hubCard as uvHub } from '@/lib/uv/route';
import { hubCard as hikeHub } from '@/lib/hike/route';
import { hubCard as insulHub } from '@/lib/insul/route';
import { hubCard as asciiHub } from '@/lib/ascii/route';
import { hubCard as bandwidthHub } from '@/lib/bandwidth/route';
import { hubCard as batteryHub } from '@/lib/battery/route';
import { BODY_SECTION } from '@/lib/body-section';
import { hubCard as chessHub } from '@/lib/chess/route';
import { hubCard as chmodHub } from '@/lib/chmod/route';
import { hubCard as cidrHub } from '@/lib/cidr/route';
import { hubCard as codeHub } from '@/lib/code/route';
import { COUNTRY_SECTION, COUNTRY_UI } from '@/lib/country-ui';
import { hubCard as cssHub } from '@/lib/css/route';
import { hubCard as cubeHub } from '@/lib/cube/route';
import { hubCard as dartsHub } from '@/lib/darts/route';
import { hubCard as deviceHub } from '@/lib/device/route';
import { hubCard as dewHub } from '@/lib/dew/route';
import { hubCard as diceHub } from '@/lib/dice/route';
import { hubCard as drillHub } from '@/lib/drill/route';
import { hubCard as elementHub } from '@/lib/element/route';
import { hubCard as extHub } from '@/lib/ext/route';
import { hubCard as fractionHub } from '@/lib/fraction/route';
import { hubCard as fretHub } from '@/lib/fret/route';
import { GEO_SECTION } from '@/lib/geo-section';
import { hubCard as glyphHub } from '@/lib/glyph/route';
import { hubCard as gravityHub } from '@/lib/gravity/route';
import { HANJA_SECTION, HANJA_UI } from '@/lib/hanja-ui';
import { hubCard as htmlHub } from '@/lib/html/route';
import { hubCard as httpHub } from '@/lib/http/route';
import { hubCard as imgsizeHub } from '@/lib/imgsize/route';
import { hubCard as keycodeHub } from '@/lib/keycode/route';
import { hubCard as lensHub } from '@/lib/lens/route';
import { hubCard as lumenHub } from '@/lib/lumen/route';
import { hubCard as metroHub } from '@/lib/metro/route';
import { hubCard as musicHub } from '@/lib/music/route';
import { hubCard as numberHub } from '@/lib/number/route';
import { intlOg } from '@/lib/og-intl';
import { ogCard } from '@/lib/og-template';
import { hubCard as paceHub } from '@/lib/pace/route';
import { hubCard as paperHub } from '@/lib/paper/route';
import { hubCard as pokerHub } from '@/lib/poker/route';
import { hubCard as portHub } from '@/lib/port/route';
import { RATE_SECTION } from '@/lib/rate-section';
import { hubCard as regexHub } from '@/lib/regex/route';
import { hubCard as remHub } from '@/lib/rem/route';
import { hubCard as resistorHub } from '@/lib/resistor/route';
import { hubCard as romanHub } from '@/lib/roman/route';
import { hubCard as screwHub } from '@/lib/screw/route';
import { hubCard as soundHub } from '@/lib/sound/route';
import { hubCard as sqrtHub } from '@/lib/sqrt/route';
import { hubCard as stopHub } from '@/lib/stop/route';
import { hubCard as tarotHub } from '@/lib/tarot/route';
import { hubCard as timesHub } from '@/lib/times/route';
import { hubCard as tireHub } from '@/lib/tire/route';
import { hubCard as torqueHub } from '@/lib/torque/route';
import { hubCard as wifiHub } from '@/lib/wifi/route';
import { hubCard as windchillHub } from '@/lib/windchill/route';
import { hubCard as wireHub } from '@/lib/wire/route';
import { hubCard as yearHub } from '@/lib/year/route';

export const CARDS: Record<string, () => ReactElement> = {
  'snap/lighting': () => newSnapCard('ko', 'lighting'),
  'snap/sharpness': () => newSnapCard('ko', 'sharpness'),
  'snap/white-balance': () => newSnapCard('ko', 'white-balance'),
  'snap/distance': () => newSnapCard('ko', 'distance'),
  'snap/mirror': () => newSnapCard('ko', 'mirror'),
  'snap/id-photo': () => newSnapCard('ko', 'id-photo'),
  'snap/head-pose': () => newSnapCard('ko', 'head-pose'),
  'snap/real-smile': () => newSnapCard('ko', 'real-smile'),
  'snap/eye-open': () => newSnapCard('ko', 'eye-open'),
  'snap/framing': () => newSnapCard('ko', 'framing'),
  '': () => ogCard({
    icon: '🧰',
    eyebrow: 'vixutil',
    title: '일상 도구 모음',
    desc: '계산기 · 운세 · 심리테스트 · 퀴즈 · 생성기 · 체크리스트',
    from: '#2563eb',
    to: '#7c3aed',
  }),
  'air': () => airHub('ko'),
  'altitude': () => altitudeHub('ko'),
  'ampere': () => ampereHub('ko'),
  'bed': () => bedHub('ko'),
  'blood': () => bloodHub('ko'),
  'exposure': () => exposureHub('ko'),
  'heredity': () => heredityHub('ko'),
  'raid': () => raidHub('ko'),
  'flight': () => flightHub('ko'),
  'bra': () => braHub('ko'),
  'password': () => passwordHub('ko'),
  'cable': () => cableHub('ko'),
  'lumber': () => lumberHub('ko'),
  'tatami': () => tatamiHub('ko'),
  'bignum': () => bignumHub('ko'),
  'gengo': () => gengoHub('ko'),
  'golf': () => golfHub('ko'),
  'viewing': () => viewingHub('ko'),
  'wine': () => wineHub('ko'),
  'petfood': () => petfoodHub('ko'),
  'size': () => sizeHub('ko'),
  'uv': () => uvHub('ko'),
  'hike': () => hikeHub('ko'),
  'insul': () => insulHub('ko'),
  'ascii': () => asciiHub('ko'),
  'bandwidth': () => bandwidthHub('ko'),
  'battery': () => batteryHub('ko'),
  'body': () => {
    const meta = BODY_SECTION.meta['ko'];
    return ogCard({
      icon: '🩺',
      eyebrow: meta.section,
      title: meta.hubTitle,
      desc: meta.hubLead,
      from: BODY_SECTION.ogFrom,
      to: BODY_SECTION.ogTo,
    });
  },
  'calculator': () => ogCard({
    icon: '🧮',
    eyebrow: 'Calculator',
    title: '실생활 계산기',
    desc: '세금 · 금융 · 대출 · 부동산 · 건강 등 85개+ 계산기',
    from: '#1d4ed8',
    to: '#3b82f6',
  }),
  'calculator/en': () => intlOg('calculator/en'),
  'calculator/ja': () => intlOg('calculator/ja'),
  'checklist': () => ogCard({
    icon: '✅',
    eyebrow: 'Checklist',
    title: '상황별 체크리스트',
    desc: '이사 · 취업 · 여행 · 건강 등 70개+ 체크리스트',
    from: '#0ea5e9',
    to: '#0891b2',
  }),
  'chmod': () => chmodHub('ko'),
  'cidr': () => cidrHub('ko'),
  'code': () => codeHub('ko'),
  'color': () => ogCard({
    icon: '🎨',
    eyebrow: 'Color Tools',
    title: '색상 도구',
    desc: '팔레트·대비 검사·그라디언트를 브라우저에서',
    from: '#8b5cf6',
    to: '#d946ef',
  }),
  'color/colorblind': () => ogCard({
    icon: '👓',
    eyebrow: 'CVD Sim',
    title: '색맹 시뮬레이터',
    desc: '색각 이상이 있는 눈에 어떻게 보이는지',
    from: '#f59e0b',
    to: '#f43f5e',
  }),
  'color/contrast': () => ogCard({
    icon: '👁️',
    eyebrow: 'Contrast',
    title: '명도 대비 검사',
    desc: '글자가 읽히는지 WCAG 기준으로 확인',
    from: '#10b981',
    to: '#0d9488',
  }),
  'color/gradient': () => ogCard({
    icon: '🌈',
    eyebrow: 'Gradient',
    title: '그라디언트 만들기',
    desc: '두세 색으로 CSS 그라디언트 생성',
    from: '#d946ef',
    to: '#0ea5e9',
  }),
  'color/mixer': () => ogCard({
    icon: '🧪',
    eyebrow: 'Mixer',
    title: '색 섞기',
    desc: '두 색 사이의 중간색을 만들기',
    from: '#14b8a6',
    to: '#0284c7',
  }),
  'color/name': () => ogCard({
    icon: '🏷️',
    eyebrow: 'Color Name',
    title: '색 이름 찾기',
    desc: '이 색과 가장 가까운 이름은 무엇인가',
    from: '#84cc16',
    to: '#059669',
  }),
  'color/palette': () => ogCard({
    icon: '🎨',
    eyebrow: 'Palette',
    title: '팔레트 생성기',
    desc: '기준 색에 어울리는 색을 규칙대로 뽑기',
    from: '#8b5cf6',
    to: '#d946ef',
  }),
  'color/random': () => ogCard({
    icon: '🎲',
    eyebrow: 'Random',
    title: '랜덤 색 뽑기',
    desc: '마음에 드는 색은 잠그고 다시 뽑기',
    from: '#f43f5e',
    to: '#f97316',
  }),
  'color/shades': () => ogCard({
    icon: '🪜',
    eyebrow: 'Shades',
    title: '명도 단계 생성',
    desc: '색 하나로 50~900 단계 만들기',
    from: '#6366f1',
    to: '#7c3aed',
  }),
  'color/shadow': () => ogCard({
    icon: '🌫️',
    eyebrow: 'Shadow',
    title: '그림자 만들기',
    desc: 'box-shadow를 눈으로 보며 조절',
    from: '#475569',
    to: '#4338ca',
  }),
  'color/temperature': () => ogCard({
    icon: '🔥',
    eyebrow: 'Kelvin',
    title: '색온도 변환',
    desc: '켈빈(K) 값을 실제 색으로 보기',
    from: '#f97316',
    to: '#0891b2',
  }),
  'convert': () => ogCard({
    icon: '🔄',
    eyebrow: 'Unit Converter',
    title: '단위 변환',
    desc: '길이·무게·부피·넓이·온도까지 50가지 변환',
    from: '#3b82f6',
    to: '#4f46e5',
  }),
  'country': () => {
    const ui = COUNTRY_UI['ko'];
    return ogCard({
      icon: '🧭',
      eyebrow: ui.section,
      title: ui.hubTitle,
      desc: ui.hubLead,
      from: COUNTRY_SECTION.ogFrom,
      to: COUNTRY_SECTION.ogTo,
    });
  },
  'crypto': () => ogCard({
    icon: '🪙',
    eyebrow: 'Crypto Tools',
    title: 'Crypto Trading Tools',
    desc: 'Volatility & TP/SL from Binance market data',
    from: '#f59e0b',
    to: '#ea580c',
  }),
  'crypto/atr-tpsl': () => ogCard({
    icon: '📊',
    eyebrow: 'Crypto · ATR',
    title: 'ATR TP/SL Calculator',
    desc: 'Volatility-based take-profit & stop-loss',
    from: '#f59e0b',
    to: '#ea580c',
  }),
  'crypto/signals': () => ogCard({
    icon: '📈',
    eyebrow: 'Crypto · Signals',
    title: 'Crypto Signal Board',
    desc: 'Multi-strategy entry / TP / SL for all coins',
    from: '#f59e0b',
    to: '#ea580c',
  }),
  'css': () => cssHub('ko'),
  'darts': () => dartsHub('ko'),
  'device': () => ogCard({
    icon: '🧰',
    eyebrow: 'Device Check',
    title: '기기 점검',
    desc: '키보드·마우스·마이크·웹캠·모니터 온라인 테스트',
    from: '#0ea5e9',
    to: '#4f46e5',
  }),
  'device/gamepad': () => ogCard({
    icon: '🎮',
    eyebrow: 'Gamepad Test',
    title: '게임패드 테스트',
    desc: '버튼·아날로그 스틱·트리거 입력 확인',
    from: '#6366f1',
    to: '#06b6d4',
  }),
  'device/info': () => ogCard({
    icon: '🧾',
    eyebrow: 'Device Info',
    title: '내 기기 정보',
    desc: '해상도·브라우저·OS·코어 수 한눈에 보기',
    from: '#14b8a6',
    to: '#0284c7',
  }),
  'device/keyboard': () => ogCard({
    icon: '⌨️',
    eyebrow: 'Keyboard Test',
    title: '키보드 테스트',
    desc: '안 눌리는 키·동시입력(N키 롤오버) 확인',
    from: '#0ea5e9',
    to: '#4f46e5',
  }),
  'device/mic': () => ogCard({
    icon: '🎤',
    eyebrow: 'Mic Test',
    title: '마이크 테스트',
    desc: '입력 볼륨 실시간 확인 + 녹음해서 들어보기',
    from: '#f43f5e',
    to: '#f97316',
  }),
  'device/monitor': () => ogCard({
    icon: '🖥️',
    eyebrow: 'Monitor Test',
    title: '모니터 불량화소 테스트',
    desc: '단색 전체화면으로 죽은 픽셀·얼룩 찾기',
    from: '#475569',
    to: '#4338ca',
  }),
  'device/mouse': () => ogCard({
    icon: '🖱️',
    eyebrow: 'Mouse Test',
    title: '마우스 클릭 테스트',
    desc: '좌·우·휠 클릭과 채터링(더블클릭 오작동) 검사',
    from: '#8b5cf6',
    to: '#d946ef',
  }),
  'device/refresh-rate': () => ogCard({
    icon: '⚡',
    eyebrow: 'Refresh Rate',
    title: '모니터 주사율 테스트',
    desc: '내 화면이 실제 몇 Hz로 도는지 측정',
    from: '#f59e0b',
    to: '#f43f5e',
  }),
  'device/screen': () => deviceHub('ko'),
  'device/speaker': () => ogCard({
    icon: '🔊',
    eyebrow: 'Speaker Test',
    title: '스피커·이어폰 테스트',
    desc: '좌우 채널 분리와 들리는 주파수 대역 확인',
    from: '#10b981',
    to: '#0d9488',
  }),
  'device/touch': () => ogCard({
    icon: '👆',
    eyebrow: 'Touch Test',
    title: '터치스크린 테스트',
    desc: '멀티터치 인식 개수와 안 먹는 영역 확인',
    from: '#ec4899',
    to: '#7c3aed',
  }),
  'device/webcam': () => ogCard({
    icon: '📷',
    eyebrow: 'Webcam Test',
    title: '웹캠 테스트',
    desc: '화면·해상도·프레임레이트 확인 및 스냅샷',
    from: '#06b6d4',
    to: '#2563eb',
  }),
  'dew': () => dewHub('ko'),
  'drill': () => drillHub('ko'),
  'element': () => elementHub('ko'),
  'ext': () => extHub('ko'),
  'food': () => ogCard({
    icon: '🍳',
    eyebrow: 'Cooking Tools',
    title: '계량·요리',
    desc: '컵을 그램으로, 레시피 배율, 오븐 온도까지',
    from: '#f59e0b',
    to: '#dc2626',
  }),
  'food/baking-pan': () => ogCard({
    icon: '🎂',
    eyebrow: 'Pan Size',
    title: '베이킹 팬 환산',
    desc: '틀 크기가 다를 때 반죽량 조절',
    from: '#ec4899',
    to: '#c026d3',
  }),
  'food/coffee': () => ogCard({
    icon: '☕',
    eyebrow: 'Coffee',
    title: '커피 비율',
    desc: '원두와 물의 황금비율',
    from: '#b45309',
    to: '#9a3412',
  }),
  'food/measure': () => ogCard({
    icon: '🥄',
    eyebrow: 'Measure',
    title: '계량 변환',
    desc: '컵·큰술을 그램으로 (재료별로 다릅니다)',
    from: '#f59e0b',
    to: '#ea580c',
  }),
  'food/oven': () => ogCard({
    icon: '🔥',
    eyebrow: 'Oven Temp',
    title: '오븐 온도 변환',
    desc: '화씨·가스마크·에어프라이어 환산',
    from: '#f97316',
    to: '#dc2626',
  }),
  'food/pasta': () => ogCard({
    icon: '🍝',
    eyebrow: 'Pasta',
    title: '파스타 물·소금',
    desc: '면 200g에 물과 소금은 얼마나',
    from: '#eab308',
    to: '#d97706',
  }),
  'food/recipe-scale': () => ogCard({
    icon: '📖',
    eyebrow: 'Scale',
    title: '레시피 배율',
    desc: '2인분 레시피를 원하는 인분으로',
    from: '#f43f5e',
    to: '#db2777',
  }),
  'food/rice': () => ogCard({
    icon: '🍚',
    eyebrow: 'Rice',
    title: '밥물 계산',
    desc: '쌀 몇 컵에 물은 얼마나',
    from: '#84cc16',
    to: '#059669',
  }),
  'food/salt': () => ogCard({
    icon: '🧂',
    eyebrow: 'Brine',
    title: '소금물 염도',
    desc: '김장·장아찌용 소금물 만들기',
    from: '#0ea5e9',
    to: '#0891b2',
  }),
  'food/steak': () => ogCard({
    icon: '🥩',
    eyebrow: 'Steak',
    title: '고기 굽기 온도',
    desc: '미디엄 레어는 중심 몇 도인가',
    from: '#ef4444',
    to: '#be123c',
  }),
  'food/storage': () => ogCard({
    icon: '🧊',
    eyebrow: 'Storage',
    title: '식품 보관 기간',
    desc: '냉장·냉동 며칠까지 괜찮을까',
    from: '#06b6d4',
    to: '#1d4ed8',
  }),
  'fortune': () => ogCard({
    icon: '🔮',
    eyebrow: 'Fortune',
    title: '오늘의 무료 운세',
    desc: '사주 · 타로 · 별자리 · 띠 · 꿈해몽 · MBTI 운세',
    from: '#7c3aed',
    to: '#db2777',
  }),
  'fortune/animal': () => ogCard({
    icon: '🐉',
    eyebrow: 'Animal Sign',
    title: '띠 운세',
    desc: '쥐·소·범 등 12띠별 오늘의 운세',
    from: '#f43f5e',
    to: '#db2777',
  }),
  'fortune/biorhythm': () => ogCard({
    icon: '📈',
    eyebrow: '바이오리듬',
    title: '바이오리듬 계산기',
    desc: '신체·감성·지성 리듬 그래프',
    from: '#10b981',
    to: '#0d9488',
  }),
  'fortune/birth-stone': () => intlOg('fortune/birth-stone/ko'),
  'fortune/blood-match': () => ogCard({
    icon: '🩸',
    eyebrow: '혈액형 궁합',
    title: '혈액형 궁합',
    desc: '두 사람의 혈액형으로 보는 궁합',
    from: '#f43f5e',
    to: '#ea580c',
  }),
  'fortune/blood-type': () => ogCard({
    icon: '🩸',
    eyebrow: '혈액형',
    title: '혈액형 운세',
    desc: 'A·B·O·AB형 오늘의 운세',
    from: '#f43f5e',
    to: '#dc2626',
  }),
  'fortune/card': () => tarotHub('ko'),
  'fortune/daily': () => ogCard({
    icon: '🔮',
    eyebrow: '오늘의 종합운세',
    title: '오늘의 종합운세',
    desc: '생년월일로 보는 오늘의 운세',
    from: '#7c3aed',
    to: '#db2777',
  }),
  'fortune/daily-tarot': () => intlOg('fortune/daily-tarot/ko'),
  'fortune/dream': () => ogCard({
    icon: '🌙',
    eyebrow: 'Dream',
    title: '꿈 해몽',
    desc: '돼지·뱀·불 등 78가지 꿈의 의미 분석',
    from: '#334155',
    to: '#3730a3',
  }),
  'fortune/lucky-lotto': () => intlOg('fortune/lucky-lotto/ko'),
  'fortune/mbti': () => ogCard({
    icon: '🧠',
    eyebrow: 'MBTI',
    title: 'MBTI 운세',
    desc: '16가지 성격 유형별 오늘의 운세',
    from: '#0ea5e9',
    to: '#2563eb',
  }),
  'fortune/mbti-match': () => ogCard({
    icon: '🧠',
    eyebrow: 'MBTI 궁합',
    title: 'MBTI 궁합',
    desc: '두 사람의 MBTI로 보는 궁합',
    from: '#8b5cf6',
    to: '#4f46e5',
  }),
  'fortune/name-match': () => ogCard({
    icon: '💕',
    eyebrow: '이름 궁합',
    title: '이름 궁합',
    desc: '두 사람 이름 획수로 보는 궁합',
    from: '#ec4899',
    to: '#e11d48',
  }),
  'fortune/saju': () => ogCard({
    icon: '🔯',
    eyebrow: 'Saju',
    title: '사주 분석',
    desc: '생년월일로 사주 4주 분석 + 오행 균형',
    from: '#6366f1',
    to: '#6d28d9',
  }),
  'fortune/star-match': () => ogCard({
    icon: '⭐',
    eyebrow: '별자리 궁합',
    title: '별자리 궁합',
    desc: '12별자리 원소로 보는 두 사람의 궁합',
    from: '#8b5cf6',
    to: '#c026d3',
  }),
  'fortune/tarot': () => ogCard({
    icon: '🃏',
    eyebrow: 'Tarot',
    title: '타로 카드',
    desc: '78장 풀덱에서 카드 뽑기',
    from: '#f59e0b',
    to: '#ea580c',
  }),
  'fortune/tarot-yesno': () => intlOg('fortune/tarot-yesno/ko'),
  'fortune/today-color': () => intlOg('fortune/today-color/ko'),
  'fortune/zodiac': () => ogCard({
    icon: '⭐',
    eyebrow: 'Zodiac',
    title: '별자리 운세',
    desc: '12개 별자리로 오늘의 운세 확인',
    from: '#8b5cf6',
    to: '#7e22ce',
  }),
  'fortune/zodiac-match': () => ogCard({
    icon: '🐲',
    eyebrow: '띠 궁합',
    title: '띠 궁합',
    desc: '십이지로 보는 두 사람의 궁합',
    from: '#f43f5e',
    to: '#db2777',
  }),
  'fraction': () => fractionHub('ko'),
  'fret': () => fretHub('ko'),
  'game': () => ogCard({
    icon: '🕹️',
    eyebrow: 'Brain Games',
    title: '두뇌 게임',
    desc: '반응속도·클릭속도·기억력을 1분 만에 재는 게임',
    from: '#10b981',
    to: '#4f46e5',
  }),
  'game/aim': () => ogCard({
    icon: '🎯',
    eyebrow: 'Aim',
    title: '표적 클릭 게임',
    desc: '30초 동안 과녁을 몇 개나 맞히나',
    from: '#f43f5e',
    to: '#f97316',
  }),
  'game/chess': () => chessHub('ko'),
  'game/color-blind': () => ogCard({
    icon: '🎨',
    eyebrow: 'Color',
    title: '색 구분 테스트',
    desc: '미세하게 다른 색 하나를 찾아내기',
    from: '#d946ef',
    to: '#7c3aed',
  }),
  'game/cps': () => ogCard({
    icon: '🖱️',
    eyebrow: 'Click Speed',
    title: '클릭 속도 테스트',
    desc: '10초 동안 몇 번이나 클릭할 수 있나',
    from: '#0ea5e9',
    to: '#4f46e5',
  }),
  'game/cube': () => cubeHub('ko'),
  'game/hearing': () => ogCard({
    icon: '👂',
    eyebrow: 'Hearing',
    title: '가청 주파수 테스트',
    desc: '몇 Hz까지 들리는지 확인',
    from: '#06b6d4',
    to: '#2563eb',
  }),
  'game/math': () => ogCard({
    icon: '➕',
    eyebrow: 'Mental Math',
    title: '암산 대결',
    desc: '30초 동안 몇 문제나 푸나',
    from: '#10b981',
    to: '#65a30d',
  }),
  'game/memory': () => ogCard({
    icon: '🧠',
    eyebrow: 'Memory',
    title: '순서 기억 게임',
    desc: '색이 켜지는 순서를 따라 누르기',
    from: '#f59e0b',
    to: '#f43f5e',
  }),
  'game/number-memory': () => ogCard({
    icon: '🔢',
    eyebrow: 'Numbers',
    title: '숫자 암기 테스트',
    desc: '점점 길어지는 숫자를 외워서 입력',
    from: '#6366f1',
    to: '#7c3aed',
  }),
  'game/poker': () => pokerHub('ko'),
  'game/reaction': () => ogCard({
    icon: '⚡',
    eyebrow: 'Reaction',
    title: '반응속도 테스트',
    desc: '초록불이 켜지면 얼마나 빨리 누르나',
    from: '#10b981',
    to: '#0d9488',
  }),
  'game/sequence': () => ogCard({
    icon: '🔲',
    eyebrow: 'Pattern',
    title: '패턴 기억 게임',
    desc: '격자에 켜진 칸의 위치를 기억하기',
    from: '#475569',
    to: '#4338ca',
  }),
  'game/typing': () => ogCard({
    icon: '⌨️',
    eyebrow: 'Typing',
    title: '타자 연습',
    desc: '한글 문장을 쳐서 타수와 정확도 측정',
    from: '#8b5cf6',
    to: '#d946ef',
  }),
  'generator': () => ogCard({
    icon: '⚙️',
    eyebrow: 'Generator',
    title: '생성기 모음',
    desc: '닉네임 · 비밀번호 · 추천 · 명언 등 100개+ 생성기',
    from: '#10b981',
    to: '#0d9488',
  }),
  'geometry': () => {
    const meta = GEO_SECTION.meta['ko'];
    return ogCard({
      icon: '📐',
      eyebrow: meta.section,
      title: meta.hubTitle,
      desc: meta.hubLead,
      from: GEO_SECTION.ogFrom,
      to: GEO_SECTION.ogTo,
    });
  },
  'gravity': () => gravityHub('ko'),
  'hanja': () => {
    const ui = HANJA_UI['ko'];
    return ogCard({
      icon: '📖',
      eyebrow: ui.section,
      title: ui.hubTitle,
      desc: ui.hubLead,
      from: HANJA_SECTION.ogFrom,
      to: HANJA_SECTION.ogTo,
    });
  },
  'html': () => htmlHub('ko'),
  'http': () => httpHub('ko'),
  'image': () => ogCard({
    icon: '🖼️',
    eyebrow: 'Image Tools',
    title: '이미지 도구',
    desc: '용량 줄이기·크기 조절·자르기·모자이크를 브라우저에서',
    from: '#8b5cf6',
    to: '#0ea5e9',
  }),
  'image/compress': () => ogCard({
    icon: '🗜️',
    eyebrow: 'Compress',
    title: '이미지 용량 줄이기',
    desc: '화질을 조절해 사진 파일 크기를 줄입니다',
    from: '#8b5cf6',
    to: '#4f46e5',
  }),
  'image/convert': () => ogCard({
    icon: '🔄',
    eyebrow: 'Convert',
    title: '이미지 포맷 변환',
    desc: 'JPG·PNG·WebP 사이에서 형식을 바꿉니다',
    from: '#10b981',
    to: '#0d9488',
  }),
  'image/crop': () => ogCard({
    icon: '✂️',
    eyebrow: 'Crop',
    title: '이미지 자르기',
    desc: '필요한 부분만 잘라냅니다',
    from: '#f43f5e',
    to: '#f97316',
  }),
  'image/merge': () => ogCard({
    icon: '🧩',
    eyebrow: 'Merge',
    title: '사진 이어붙이기',
    desc: '여러 장을 한 장으로 세로·가로 연결합니다',
    from: '#d946ef',
    to: '#0ea5e9',
  }),
  'image/mosaic': () => ogCard({
    icon: '🔳',
    eyebrow: 'Mosaic',
    title: '모자이크 가리기',
    desc: '얼굴·주소 등 가리고 싶은 곳을 문질러 지웁니다',
    from: '#475569',
    to: '#6d28d9',
  }),
  'image/palette': () => ogCard({
    icon: '🎨',
    eyebrow: 'Palette',
    title: '이미지 색상 추출',
    desc: '사진에서 많이 쓰인 색을 뽑아 HEX로 보여줍니다',
    from: '#ec4899',
    to: '#7c3aed',
  }),
  'image/resize': () => ogCard({
    icon: '📐',
    eyebrow: 'Resize',
    title: '이미지 크기 조절',
    desc: '가로·세로 픽셀을 원하는 크기로 바꿉니다',
    from: '#0ea5e9',
    to: '#0891b2',
  }),
  'image/rotate': () => ogCard({
    icon: '🔃',
    eyebrow: 'Rotate',
    title: '이미지 회전·반전',
    desc: '돌아간 사진을 바로 세우고 좌우를 뒤집습니다',
    from: '#f59e0b',
    to: '#f43f5e',
  }),
  'image/size': () => imgsizeHub('ko'),
  'keycode': () => keycodeHub('ko'),
  'lumen': () => lumenHub('ko'),
  'microwave': () => microwaveHub('ko'),
  'metro': () => metroHub('ko'),
  'music': () => musicHub('ko'),
  'number': () => numberHub('ko'),
  'pace': () => paceHub('ko'),
  'paper': () => paperHub('ko'),
  'powerbank': () => powerbankHub('ko'),
  'quake': () => quakeHub('ko'),
  'port': () => portHub('ko'),
  'quiz': () => ogCard({
    icon: '🏆',
    eyebrow: 'Quiz',
    title: '지식 퀴즈',
    desc: '한국사 · IT · 상식 · K-POP 등 100개+ 퀴즈',
    from: '#f59e0b',
    to: '#ea580c',
  }),
  'random': () => intlOg('random/ko'),
  'random/dice': () => diceHub('ko'),
  'rate': () => {
    const meta = RATE_SECTION.meta['ko'];
    return ogCard({
      icon: '📐',
      eyebrow: meta.section,
      title: meta.hubTitle,
      desc: meta.hubLead,
      from: RATE_SECTION.ogFrom,
      to: RATE_SECTION.ogTo,
    });
  },
  'rem': () => remHub('ko'),
  'resistor': () => resistorHub('ko'),
  'roman': () => romanHub('ko'),
  'screw': () => screwHub('ko'),
  'snap': () => ogCard({
    icon: '📸',
    eyebrow: 'Snap Test',
    title: '스냅테스트',
    desc: '사진 한 장으로 즐기는 참여형 테스트 모음',
    from: '#d946ef',
    to: '#0ea5e9',
  }),
  'snap/animal-face': () => ogCard({
    icon: '🐾',
    eyebrow: 'Animal Face',
    title: '동물상 테스트',
    desc: '사진 한 장으로 보는 나의 동물상',
    from: '#f97316',
    to: '#db2777',
  }),
  'snap/couple-match': () => ogCard({
    icon: '💑',
    eyebrow: 'Couple Match',
    title: '커플 관상 궁합',
    desc: '사진 두 장으로 보는 우리 커플 관상 궁합',
    from: '#f43f5e',
    to: '#db2777',
  }),
  'snap/expression': () => ogCard({
    icon: '🎭',
    eyebrow: 'Expression',
    title: '표정 감정 분석',
    desc: 'AI로 보는 사진 속 표정의 7가지 감정',
    from: '#ec4899',
    to: '#7c3aed',
  }),
  'snap/face-reading': () => ogCard({
    icon: '🪞',
    eyebrow: 'Face Reading',
    title: '관상 테스트',
    desc: '사진 한 장으로 보는 재미있는 관상 분석',
    from: '#0d9488',
    to: '#0369a1',
  }),
  'snap/face-symmetry': () => ogCard({
    icon: '⚖️',
    eyebrow: 'Face Symmetry',
    title: '얼굴 대칭 분석',
    desc: '사진 한 장으로 보는 좌우 밸런스 지수',
    from: '#6366f1',
    to: '#06b6d4',
  }),
  'snap/first-impression': () => intlOg('snap/first-impression/ko'),
  'snap/golden-ratio': () => ogCard({
    icon: '📐',
    eyebrow: 'Golden Ratio',
    title: '얼굴 황금비율 테스트',
    desc: '사진 한 장으로 보는 이목구비 황금비 점수',
    from: '#f59e0b',
    to: '#ea580c',
  }),
  'snap/handwriting': () => ogCard({
    icon: '✍️',
    eyebrow: 'Handwriting',
    title: '손글씨 심리 테스트',
    desc: '손글씨 사진 한 장으로 보는 기울기·필압 분석',
    from: '#475569',
    to: '#4338ca',
  }),
  'snap/lens': () => lensHub('ko'),
  'snap/personal-color': () => ogCard({
    icon: '🎨',
    eyebrow: 'Personal Color',
    title: '퍼스널컬러 진단',
    desc: '사진 한 장으로 보는 웜톤·쿨톤 컬러 진단',
    from: '#fb923c',
    to: '#6366f1',
  }),
  'snap/photo-mood': () => ogCard({
    icon: '🎞️',
    eyebrow: 'Photo Mood',
    title: '사진 감성 분석',
    desc: '아무 사진이나 올려서 보는 내 감성 타입',
    from: '#d946ef',
    to: '#0ea5e9',
  }),
  'snap/smile-score': () => ogCard({
    icon: '😊',
    eyebrow: 'Smile Score',
    title: '미소 지수 측정',
    desc: '사진 한 장으로 보는 내 미소 지수',
    from: '#fbbf24',
    to: '#f43f5e',
  }),
  'sound': () => ogCard({
    icon: '🔊',
    eyebrow: 'Sound Tools',
    title: '소리 도구',
    desc: '메트로놈·튜너·백색소음을 브라우저가 직접 만듭니다',
    from: '#6366f1',
    to: '#0ea5e9',
  }),
  'sound/binaural': () => ogCard({
    icon: '🧘',
    eyebrow: 'Binaural',
    title: '바이노럴 비트',
    desc: '좌우에 다른 주파수를 넣어 만드는 맥놀이',
    from: '#14b8a6',
    to: '#4f46e5',
  }),
  'sound/bpm-tap': () => ogCard({
    icon: '👏',
    eyebrow: 'Tap BPM',
    title: 'BPM 측정',
    desc: '박자에 맞춰 두드리면 템포를 알려줍니다',
    from: '#f59e0b',
    to: '#f43f5e',
  }),
  'sound/decibel': () => ogCard({
    icon: '📢',
    eyebrow: 'Decibel',
    title: '소음 측정',
    desc: '주변이 얼마나 시끄러운지 재기',
    from: '#f43f5e',
    to: '#f97316',
  }),
  'sound/hz': () => soundHub('ko'),
  'sound/metronome': () => ogCard({
    icon: '🎵',
    eyebrow: 'Metronome',
    title: '메트로놈',
    desc: '박자를 정확히 짚어 주는 연습 도구',
    from: '#6366f1',
    to: '#7c3aed',
  }),
  'sound/mosquito': () => ogCard({
    icon: '🦟',
    eyebrow: 'Mosquito',
    title: '모기 소리',
    desc: '나이가 들면 안 들리는 고주파',
    from: '#84cc16',
    to: '#059669',
  }),
  'sound/noise': () => ogCard({
    icon: '🌊',
    eyebrow: 'White Noise',
    title: '백색소음',
    desc: '집중·수면을 돕는 잡음 만들기',
    from: '#0ea5e9',
    to: '#0891b2',
  }),
  'sound/pitch': () => ogCard({
    icon: '👂',
    eyebrow: 'Ear Training',
    title: '음정 듣기 훈련',
    desc: '들려주는 두 음의 관계 맞히기',
    from: '#8b5cf6',
    to: '#d946ef',
  }),
  'sound/recorder': () => ogCard({
    icon: '🎙️',
    eyebrow: 'Recorder',
    title: '음성 녹음기',
    desc: '녹음해서 듣고 파일로 저장',
    from: '#d946ef',
    to: '#7c3aed',
  }),
  'sound/tone': () => ogCard({
    icon: '〰️',
    eyebrow: 'Tone Gen',
    title: '주파수 생성기',
    desc: '원하는 높이의 소리를 직접 만들기',
    from: '#475569',
    to: '#0284c7',
  }),
  'sound/tuner': () => ogCard({
    icon: '🎸',
    eyebrow: 'Tuner',
    title: '악기 튜너',
    desc: '마이크로 소리를 듣고 음정을 알려줍니다',
    from: '#10b981',
    to: '#0d9488',
  }),
  'sqrt': () => sqrtHub('ko'),
  'stop': () => stopHub('ko'),
  'test': () => ogCard({
    icon: '🧭',
    eyebrow: 'Personality Test',
    title: '심리 테스트',
    desc: 'MBTI · 연애 · 성향 · 밈 테스트 등 170개+',
    from: '#7c3aed',
    to: '#db2777',
  }),
  'text': () => ogCard({
    icon: '✍️',
    eyebrow: 'Text Tools',
    title: '텍스트 도구',
    desc: '한영타 변환·영문 이름·특수문자·글자수를 한 곳에서',
    from: '#3b82f6',
    to: '#d946ef',
  }),
  'text/amount': () => ogCard({
    icon: '🧾',
    eyebrow: 'Amount',
    title: '한글 금액 변환',
    desc: '숫자를 계약서용 한글 금액으로',
    from: '#f59e0b',
    to: '#ea580c',
  }),
  'text/case': () => ogCard({
    icon: '🔠',
    eyebrow: 'Letter Case',
    title: '대소문자 변환',
    desc: '영문을 원하는 표기 방식으로 바꿉니다',
    from: '#475569',
    to: '#4338ca',
  }),
  'text/char': () => glyphHub('ko'),
  'text/clean': () => ogCard({
    icon: '🧼',
    eyebrow: 'Clean Up',
    title: '텍스트 정리',
    desc: '복사해 온 글의 이상한 공백·줄바꿈 정리',
    from: '#0ea5e9',
    to: '#0891b2',
  }),
  'text/dedupe': () => ogCard({
    icon: '🧹',
    eyebrow: 'Dedupe',
    title: '중복 줄 제거·정렬',
    desc: '목록에서 겹치는 줄을 지우고 정렬합니다',
    from: '#f43f5e',
    to: '#db2777',
  }),
  'text/emoticon': () => ogCard({
    icon: '🙂',
    eyebrow: 'Kaomoji',
    title: '이모티콘 모음',
    desc: '(╯°□°）╯ 같은 문자 이모티콘 복사',
    from: '#f97316',
    to: '#f43f5e',
  }),
  'text/hanyoung': () => ogCard({
    icon: '⌨️',
    eyebrow: 'Ko/En Keys',
    title: '한영타 변환기',
    desc: '한/영 안 바꾸고 친 글자를 되돌립니다',
    from: '#3b82f6',
    to: '#4f46e5',
  }),
  'text/initial': () => ogCard({
    icon: '🔤',
    eyebrow: 'Initials',
    title: '초성 변환기',
    desc: '문장을 초성만 남겨 퀴즈로 만듭니다',
    from: '#8b5cf6',
    to: '#d946ef',
  }),
  'text/lorem': () => ogCard({
    icon: '📄',
    eyebrow: 'Lorem',
    title: '더미 텍스트 생성',
    desc: '레이아웃 채울 한글·영문 예시 문장',
    from: '#64748b',
    to: '#0284c7',
  }),
  'text/manuscript': () => ogCard({
    icon: '📝',
    eyebrow: 'Count',
    title: '원고지·자소서 글자수',
    desc: '원고지 매수와 자소서 기준 글자수 계산',
    from: '#6366f1',
    to: '#7c3aed',
  }),
  'text/regex': () => regexHub('ko'),
  'text/replace': () => ogCard({
    icon: '🔍',
    eyebrow: 'Replace',
    title: '찾아 바꾸기',
    desc: '긴 글에서 특정 단어를 한 번에 치환',
    from: '#14b8a6',
    to: '#059669',
  }),
  'text/romanize': () => ogCard({
    icon: '🛂',
    eyebrow: 'Romanize',
    title: '영문 이름 변환',
    desc: '여권·명함에 쓸 이름의 로마자 표기',
    from: '#10b981',
    to: '#0d9488',
  }),
  'text/special-char': () => ogCard({
    icon: '✨',
    eyebrow: 'Symbols',
    title: '특수문자 모음',
    desc: '화살표·도형·기호를 눌러서 복사',
    from: '#d946ef',
    to: '#7c3aed',
  }),
  'time': () => ogCard({
    icon: '⏰',
    eyebrow: 'Time Tools',
    title: '시간 도구',
    desc: '타이머·스톱워치·세계시계·날짜 계산을 한 곳에서',
    from: '#0ea5e9',
    to: '#f43f5e',
  }),
  'time/alarm': () => ogCard({
    icon: '⏰',
    eyebrow: 'Alarm',
    title: '알람',
    desc: '정한 시각에 소리로 깨우기',
    from: '#f59e0b',
    to: '#ea580c',
  }),
  'time/date-add': () => ogCard({
    icon: '➕',
    eyebrow: 'Date Math',
    title: '날짜 더하기·빼기',
    desc: '이 날짜에서 며칠·몇 달 뒤는 언제',
    from: '#8b5cf6',
    to: '#d946ef',
  }),
  'time/lived': () => ogCard({
    icon: '🎂',
    eyebrow: 'Lived Time',
    title: '살아온 시간',
    desc: '태어나서 지금까지 몇 초인지',
    from: '#ec4899',
    to: '#e11d48',
  }),
  'time/pomodoro': () => ogCard({
    icon: '🍅',
    eyebrow: 'Pomodoro',
    title: '뽀모도로 타이머',
    desc: '25분 집중 · 5분 휴식 반복',
    from: '#ef4444',
    to: '#e11d48',
  }),
  'time/stopwatch': () => ogCard({
    icon: '⏱️',
    eyebrow: 'Stopwatch',
    title: '스톱워치',
    desc: '흐른 시간을 재고 구간마다 기록',
    from: '#0ea5e9',
    to: '#4f46e5',
  }),
  'time/timer': () => ogCard({
    icon: '⏲️',
    eyebrow: 'Timer',
    title: '타이머',
    desc: '시간을 정해두고 끝나면 소리로 알림',
    from: '#f43f5e',
    to: '#f97316',
  }),
  'time/timezone': () => ogCard({
    icon: '🕰️',
    eyebrow: 'Time Zones',
    title: '시차 계산',
    desc: '해외 회의 시간을 서로의 시각으로',
    from: '#6366f1',
    to: '#7c3aed',
  }),
  'time/weeknumber': () => ogCard({
    icon: '🗓️',
    eyebrow: 'Week No.',
    title: '주차·분기 확인',
    desc: '오늘이 몇 주차이고 몇 분기인지',
    from: '#475569',
    to: '#4338ca',
  }),
  'time/workdays': () => ogCard({
    icon: '📆',
    eyebrow: 'Workdays',
    title: '근무일 계산',
    desc: '주말 빼고 며칠인지 세기',
    from: '#10b981',
    to: '#0d9488',
  }),
  'time/worldclock': () => ogCard({
    icon: '🌍',
    eyebrow: 'World Clock',
    title: '세계 시계',
    desc: '주요 도시의 지금 시각을 한눈에',
    from: '#06b6d4',
    to: '#2563eb',
  }),
  'times': () => timesHub('ko'),
  'tire': () => tireHub('ko'),
  'torque': () => torqueHub('ko'),
  'wifi': () => wifiHub('ko'),
  'windchill': () => windchillHub('ko'),
  'wire': () => wireHub('ko'),
  'year': () => yearHub('ko'),
};
