/** 나라 정보 - 오세아니아·아프리카 둘째 묶음 (12) */
import type { Country } from './types.ts';

export const AFRICA2: Country[] = [
  {
    slug: 'fiji', code: 'FJ', icon: '🇫🇯', region: '오세아니아·아프리카',
    utc: 12, tz: 'Pacific/Fiji', dst: false, dial: '+679', volt: '240V', hz: '50Hz', plug: 'I',
    drive: 'left', currencyCode: 'FJD', tld: '.fj',
    ko: { name: '피지', capital: '수바', languages: '피지어, 영어, 힌디어', currency: '피지달러',
      intro: '남태평양에 330개가 넘는 섬이 흩어져 있고 그 가운데 100여 개에 사람이 삽니다. 날짜변경선 가까이 있어 세계에서 새해를 이른 편으로 맞는 나라입니다.',
      tip: '국제선은 난디에 내리지만 수도는 수바입니다. 리조트가 몰린 마마누차·야사와 제도는 난디에서 배로 갑니다.',
      visa: '관광 목적 4개월 무비자로 알려져 있습니다. 출국 항공권과 숙소 정보를 확인하는 경우가 있습니다.', emergency: '911' },
    en: { name: 'Fiji', capital: 'Suva', languages: 'Fijian, English, Hindi', currency: 'Fijian dollar',
      intro: 'Over 330 islands scatter across the South Pacific, about a hundred of them inhabited. Sitting near the date line, Fiji is among the first countries to see the new year.',
      tip: 'International flights land at Nadi while the capital is Suva. The resort-heavy Mamanuca and Yasawa groups are reached by boat from Nadi.',
      visa: 'Four months visa-free has applied for tourism; an onward ticket and accommodation details are sometimes checked.', emergency: '911' },
    zh: { name: '斐济', capital: '苏瓦', languages: '斐济语、英语、印地语', currency: '斐济元',
      intro: '南太平洋上散布着330多座岛屿，其中约一百座有人居住。因靠近日界线，是世界上较早迎来新年的国家之一。',
      tip: '国际航班降落在楠迪，而首都是苏瓦。度假村集中的玛玛努卡与亚萨瓦群岛需从楠迪乘船前往。',
      visa: '旅游目的曾可免签停留四个月，有时会查验离境机票与住宿信息。', emergency: '911' },
  },
  {
    slug: 'papua-new-guinea', code: 'PG', icon: '🇵🇬', region: '오세아니아·아프리카',
    utc: 10, tz: 'Pacific/Port_Moresby', dst: false, dial: '+675', volt: '240V', hz: '50Hz', plug: 'I',
    drive: 'left', currencyCode: 'PGK', tld: '.pg',
    ko: { name: '파푸아뉴기니', capital: '포트모르즈비', languages: '영어, 톡피신, 히리모투', currency: '키나',
      intro: '뉴기니섬 동쪽 절반을 차지하며 사용되는 언어가 800개를 넘어 세계에서 언어가 가장 많은 나라입니다. 내륙은 험한 산지라 항공편이 주 교통수단입니다.',
      tip: '도로망이 끊겨 있어 도시 간 이동을 국내선으로 합니다. 일정을 항공 스케줄에 맞춰 짜야 합니다.',
      visa: '도착비자 또는 사전 비자가 필요합니다. 치안 상황이 지역별로 다르므로 여행경보를 확인하세요.', emergency: '000 경찰 · 111 구급' },
    en: { name: 'Papua New Guinea', capital: 'Port Moresby', languages: 'English, Tok Pisin, Hiri Motu', currency: 'Kina',
      intro: 'Occupying the eastern half of New Guinea, it has over 800 living languages — more than any other country. The rugged interior means air travel does most of the work.',
      tip: 'The road network is fragmented, so intercity travel goes by domestic flight. Build the itinerary around the air schedule.',
      visa: 'A visa on arrival or in advance is required. Security varies sharply by region, so check travel advisories.', emergency: '000 police · 111 ambulance' },
    zh: { name: '巴布亚新几内亚', capital: '莫尔斯比港', languages: '英语、托克皮辛语、希里莫图语', currency: '基那',
      intro: '占据新几内亚岛东半部，现存语言超过800种，为世界之最。内陆山势险峻，航空是主要交通方式。',
      tip: '公路网不连贯，城市间往来依靠国内航班，行程需按航班时刻安排。',
      visa: '需办落地签或提前签证。各地治安差异较大，请查看旅行警示。', emergency: '000 警察 · 111 急救' },
  },
  {
    slug: 'kenya', code: 'KE', icon: '🇰🇪', region: '오세아니아·아프리카',
    utc: 3, tz: 'Africa/Nairobi', dst: false, dial: '+254', volt: '240V', hz: '50Hz', plug: 'G',
    drive: 'left', currencyCode: 'KES', tld: '.ke',
    ko: { name: '케냐', capital: '나이로비', languages: '스와힐리어, 영어', currency: '실링',
      intro: '적도가 국토를 가로지르고 마사이마라에서 세렝게티로 이어지는 초식동물의 대이동이 유명합니다. 나이로비 국립공원은 수도 도심에 붙어 있습니다.',
      tip: '대이동은 7월에서 10월에 마사이마라를 지납니다. 사파리 일정은 이 시기를 기준으로 잡으세요.',
      visa: '전자여행허가(eTA)를 미리 받아야 합니다. 승인에 시간이 걸리므로 출발 며칠 전에 신청하세요.', emergency: '999 또는 112' },
    en: { name: 'Kenya', capital: 'Nairobi', languages: 'Swahili, English', currency: 'Shilling',
      intro: 'The equator runs through the country, and the great migration from the Masai Mara into the Serengeti is its best-known spectacle. Nairobi National Park adjoins the capital itself.',
      tip: 'The migration passes through the Masai Mara from July to October — plan safari dates around that window.',
      visa: 'An electronic travel authorisation (eTA) must be obtained in advance; approval takes time, so apply days ahead.', emergency: '999 or 112' },
    zh: { name: '肯尼亚', capital: '内罗毕', languages: '斯瓦希里语、英语', currency: '先令',
      intro: '赤道横贯国土，从马赛马拉延伸到塞伦盖蒂的动物大迁徙最为著名。内罗毕国家公园就紧邻首都市区。',
      tip: '大迁徙在7月至10月经过马赛马拉，狩猎观光行程应以此为准安排。',
      visa: '需提前申请电子旅行许可(eTA)，审批需要时间，请提前数日办理。', emergency: '999 或 112' },
  },
  {
    slug: 'tanzania', code: 'TZ', icon: '🇹🇿', region: '오세아니아·아프리카',
    utc: 3, tz: 'Africa/Dar_es_Salaam', dst: false, dial: '+255', volt: '230V', hz: '50Hz', plug: 'D, G',
    drive: 'left', currencyCode: 'TZS', tld: '.tz',
    ko: { name: '탄자니아', capital: '도도마', languages: '스와힐리어, 영어', currency: '실링',
      intro: '아프리카 최고봉 킬리만자로(5,895m)와 세렝게티, 잔지바르 섬이 모두 이 나라에 있습니다. 법정 수도는 도도마이지만 상업 중심은 다르에스살람입니다.',
      tip: '킬리만자로는 기술 장비 없이 오를 수 있지만 고도 적응 때문에 최소 6일 코스를 권합니다. 짧은 코스는 성공률이 크게 떨어집니다.',
      visa: '사전 비자 또는 도착비자가 필요합니다. 잔지바르 입도 시 별도 보험 가입을 요구하는 제도가 있습니다.', emergency: '112' },
    en: { name: 'Tanzania', capital: 'Dodoma', languages: 'Swahili, English', currency: 'Shilling',
      intro: 'Kilimanjaro at 5,895 m — Africa’s highest point — plus the Serengeti and Zanzibar all lie within this one country. Dodoma is the legal capital while Dar es Salaam remains the commercial hub.',
      tip: 'Kilimanjaro needs no technical gear, but acclimatisation argues for a route of at least six days; success rates fall sharply on shorter ones.',
      visa: 'A visa in advance or on arrival is required, and Zanzibar has required separate travel insurance on entry.', emergency: '112' },
    zh: { name: '坦桑尼亚', capital: '多多马', languages: '斯瓦希里语、英语', currency: '先令',
      intro: '非洲最高峰乞力马扎罗（5,895米）、塞伦盖蒂与桑给巴尔岛都在这个国家。法定首都为多多马，商业中心仍是达累斯萨拉姆。',
      tip: '攀登乞力马扎罗无需技术装备，但为适应高度建议选择六天以上路线，短线成功率明显下降。',
      visa: '需提前签证或落地签。进入桑给巴尔曾要求单独购买旅行保险。', emergency: '112' },
  },
  {
    slug: 'ethiopia', code: 'ET', icon: '🇪🇹', region: '오세아니아·아프리카',
    utc: 3, tz: 'Africa/Addis_Ababa', dst: false, dial: '+251', volt: '220V', hz: '50Hz', plug: 'C, F, L',
    drive: 'right', currencyCode: 'ETB', tld: '.et',
    ko: { name: '에티오피아', capital: '아디스아바바', languages: '암하라어, 영어', currency: '비르',
      intro: '아프리카에서 유럽 식민 지배를 받지 않은 나라로 고유 문자(게에즈)와 고유 달력을 씁니다. 커피의 원산지로 알려져 있습니다.',
      tip: '자체 달력이 그레고리력보다 7~8년 느리고 하루를 해 뜰 때부터 세는 시간 표기도 씁니다. 예약 시각은 어느 기준인지 확인하세요.',
      visa: '온라인 비자(e-Visa)를 미리 받을 수 있습니다. 지역별 정세 차이가 크므로 여행경보를 확인하세요.', emergency: '991 경찰 · 907 구급' },
    en: { name: 'Ethiopia', capital: 'Addis Ababa', languages: 'Amharic, English', currency: 'Birr',
      intro: 'The one African country never colonised by a European power, with its own Geʽez script and its own calendar. It is also the birthplace of coffee.',
      tip: 'The local calendar runs seven to eight years behind the Gregorian one, and clock time is often counted from sunrise. Confirm which system a booking uses.',
      visa: 'An online e-Visa is available in advance. Conditions differ sharply by region, so check travel advisories.', emergency: '991 police · 907 ambulance' },
    zh: { name: '埃塞俄比亚', capital: '亚的斯亚贝巴', languages: '阿姆哈拉语、英语', currency: '比尔',
      intro: '非洲唯一未被欧洲殖民的国家，拥有自己的吉兹字母与独立历法，同时也是咖啡的原产地。',
      tip: '当地历法比公历晚七到八年，且常从日出开始计时。预约时间请确认采用哪一套标准。',
      visa: '可提前申请在线电子签证。各地区局势差异较大，请查看旅行警示。', emergency: '991 警察 · 907 急救' },
  },
  {
    slug: 'nigeria', code: 'NG', icon: '🇳🇬', region: '오세아니아·아프리카',
    utc: 1, tz: 'Africa/Lagos', dst: false, dial: '+234', volt: '240V', hz: '50Hz', plug: 'D, G',
    drive: 'right', currencyCode: 'NGN', tld: '.ng',
    ko: { name: '나이지리아', capital: '아부자', languages: '영어, 하우사어, 요루바어, 이보어', currency: '나이라',
      intro: '아프리카에서 인구가 가장 많은 나라이고 라고스는 대륙 최대 도시권입니다. 500개가 넘는 언어가 쓰이며 공용어는 영어입니다.',
      tip: '수도는 아부자이지만 경제 중심은 라고스입니다. 두 도시는 성격이 아주 달라 목적에 따라 도착 공항을 정해야 합니다.',
      visa: '사전 비자가 필요합니다. 지역별 치안 차이가 크므로 출발 전 여행경보를 확인하세요.', emergency: '112' },
    en: { name: 'Nigeria', capital: 'Abuja', languages: 'English, Hausa, Yoruba, Igbo', currency: 'Naira',
      intro: 'Africa’s most populous country, with Lagos as the continent’s largest urban area. More than 500 languages are spoken and English is the official one.',
      tip: 'Abuja is the capital but Lagos is the economic centre, and the two feel very different — choose your arrival airport by purpose.',
      visa: 'A visa is required in advance. Security varies widely by region, so check advisories before travelling.', emergency: '112' },
    zh: { name: '尼日利亚', capital: '阿布贾', languages: '英语、豪萨语、约鲁巴语、伊博语', currency: '奈拉',
      intro: '非洲人口最多的国家，拉各斯是非洲最大的都市圈。境内使用500多种语言，官方语言为英语。',
      tip: '首都是阿布贾，经济中心却是拉各斯，两座城市气质迥异，应按目的选择抵达机场。',
      visa: '需提前办理签证。各地治安差异很大，出发前请查看旅行警示。', emergency: '112' },
  },
  {
    slug: 'ghana', code: 'GH', icon: '🇬🇭', region: '오세아니아·아프리카',
    utc: 0, tz: 'Africa/Accra', dst: false, dial: '+233', volt: '230V', hz: '50Hz', plug: 'D, G',
    drive: 'right', currencyCode: 'GHS', tld: '.gh',
    ko: { name: '가나', capital: '아크라', languages: '영어', currency: '세디',
      intro: '경도 0도인 본초자오선이 지나고 적도에도 가까워 지구 좌표의 원점에 가장 가까운 육지 가운데 하나입니다. 서머타임이 없어 연중 UTC와 같습니다.',
      tip: '해안에 남아 있는 유럽 요새들이 세계유산으로 지정돼 있습니다. 노예무역의 역사를 다루는 곳이라 방문 전 배경을 알고 가면 좋습니다.',
      visa: '사전 비자가 필요합니다. 황열병 예방접종 증명서를 요구하는 경우가 있으니 함께 준비하세요.', emergency: '191 경찰 · 193 구급' },
    en: { name: 'Ghana', capital: 'Accra', languages: 'English', currency: 'Cedi',
      intro: 'The prime meridian passes through Ghana and the equator is not far off, putting it among the closest land to the origin of the coordinate system. With no daylight saving it stays on UTC year round.',
      tip: 'The European forts along the coast are World Heritage sites dealing with the history of the slave trade — read up before you visit.',
      visa: 'A visa is required in advance, and proof of yellow fever vaccination is often requested, so arrange both.', emergency: '191 police · 193 ambulance' },
    zh: { name: '加纳', capital: '阿克拉', languages: '英语', currency: '塞地',
      intro: '本初子午线穿过加纳，且距赤道不远，是最接近坐标原点的陆地之一。该国不实行夏令时，全年与UTC同刻。',
      tip: '沿海遗留的欧洲城堡已列入世界遗产，涉及奴隶贸易的历史，参访前先了解背景更好。',
      visa: '需提前办理签证，常被要求出示黄热病疫苗证明，请一并准备。', emergency: '191 警察 · 193 急救' },
  },
  {
    slug: 'tunisia', code: 'TN', icon: '🇹🇳', region: '오세아니아·아프리카',
    utc: 1, tz: 'Africa/Tunis', dst: false, dial: '+216', volt: '230V', hz: '50Hz', plug: 'C, E',
    drive: 'right', currencyCode: 'TND', tld: '.tn',
    ko: { name: '튀니지', capital: '튀니스', languages: '아랍어, 프랑스어', currency: '디나르',
      intro: '아프리카 대륙의 최북단이 이 나라에 있고 시칠리아까지 140km 거리입니다. 고대 카르타고 유적과 사하라 사막이 한 나라에 있습니다.',
      tip: '영화 촬영지로 쓰인 사하라 마을들은 남부에 있어 튀니스에서 하루 이상 걸립니다. 국내선이나 장거리 이동을 미리 잡으세요.',
      visa: '관광 목적 90일 무비자로 알려져 있습니다. 조건이 개정될 수 있으므로 출발 전 확인하세요.', emergency: '197 경찰 · 190 구급' },
    en: { name: 'Tunisia', capital: 'Tunis', languages: 'Arabic, French', currency: 'Dinar',
      intro: 'Africa’s northernmost point lies here, only 140 km from Sicily. Ancient Carthage and the Sahara sit inside the same country.',
      tip: 'The Saharan villages used as film locations are in the south, over a day from Tunis — book internal flights or long transfers ahead.',
      visa: 'Ninety days visa-free has applied for tourism, though terms can change — check before departure.', emergency: '197 police · 190 ambulance' },
    zh: { name: '突尼斯', capital: '突尼斯市', languages: '阿拉伯语、法语', currency: '第纳尔',
      intro: '非洲大陆最北端就在该国，距西西里仅140公里。古迦太基遗址与撒哈拉沙漠同处一国。',
      tip: '被用作电影取景地的撒哈拉村落位于南部，从突尼斯前往需一天以上，请提前安排国内航班或长途交通。',
      visa: '旅游目的曾可免签停留90天，条件可能调整，出发前请确认。', emergency: '197 警察 · 190 急救' },
  },
  {
    slug: 'algeria', code: 'DZ', icon: '🇩🇿', region: '오세아니아·아프리카',
    utc: 1, tz: 'Africa/Algiers', dst: false, dial: '+213', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'DZD', tld: '.dz',
    ko: { name: '알제리', capital: '알제', languages: '아랍어, 베르베르어, 프랑스어', currency: '디나르',
      intro: '아프리카에서 국토가 가장 넓고 그 대부분이 사하라 사막입니다. 인구는 지중해에 닿은 북쪽 좁은 띠에 몰려 있습니다.',
      tip: '사막 지역은 별도 허가와 현지 가이드가 필요한 구간이 많습니다. 개인 이동으로 계획하기 어렵습니다.',
      visa: '사전 비자가 필요하며 초청장이나 숙소 확정 서류를 요구합니다. 준비 기간을 넉넉히 두세요.', emergency: '17 경찰 · 14 구급' },
    en: { name: 'Algeria', capital: 'Algiers', languages: 'Arabic, Berber, French', currency: 'Dinar',
      intro: 'The largest country in Africa, most of it Sahara. The population is concentrated in a narrow northern belt along the Mediterranean.',
      tip: 'Many desert areas require permits and a local guide, which makes independent travel there hard to arrange.',
      visa: 'A visa is required in advance, usually with an invitation or confirmed accommodation — allow plenty of lead time.', emergency: '17 police · 14 ambulance' },
    zh: { name: '阿尔及利亚', capital: '阿尔及尔', languages: '阿拉伯语、柏柏尔语、法语', currency: '第纳尔',
      intro: '非洲面积最大的国家，其中大部分为撒哈拉沙漠。人口集中在濒临地中海的北部狭长地带。',
      tip: '许多沙漠地区需办许可并配当地导游，个人自由行难以安排。',
      visa: '需提前办理签证，通常要求邀请函或已确认的住宿证明，请预留充足时间。', emergency: '17 警察 · 14 急救' },
  },
  {
    slug: 'namibia', code: 'NA', icon: '🇳🇦', region: '오세아니아·아프리카',
    utc: 2, tz: 'Africa/Windhoek', dst: false, dial: '+264', volt: '220V', hz: '50Hz', plug: 'D, M',
    drive: 'left', currencyCode: 'NAD', tld: '.na',
    ko: { name: '나미비아', capital: '빈트후크', languages: '영어, 아프리칸스어, 독일어', currency: '나미비아달러',
      intro: '나미브 사막이 대서양과 맞닿아 세계에서 가장 오래된 사막으로 꼽힙니다. 소수스블레이의 붉은 모래언덕이 대표 풍경입니다.',
      tip: '2017년에 서머타임을 없애 연중 UTC+2를 씁니다. 자갈길이 많아 렌터카는 사륜구동과 예비 타이어를 챙기세요.',
      visa: '관광 목적 90일 무비자로 알려져 있으나 제도가 개정되고 있습니다. 출발 전 확인하세요.', emergency: '10111 경찰' },
    en: { name: 'Namibia', capital: 'Windhoek', languages: 'English, Afrikaans, German', currency: 'Namibian dollar',
      intro: 'The Namib meets the Atlantic and is reckoned the oldest desert on earth. The red dunes of Sossusvlei are its signature landscape.',
      tip: 'Daylight saving was abolished in 2017, so it is UTC+2 all year. Gravel roads are the norm — hire a four-wheel drive and carry a spare.',
      visa: 'Ninety days visa-free has applied for tourism, but the scheme is being revised — check before departure.', emergency: '10111 police' },
    zh: { name: '纳米比亚', capital: '温特和克', languages: '英语、南非荷兰语、德语', currency: '纳米比亚元',
      intro: '纳米布沙漠直抵大西洋，被认为是地球上最古老的沙漠。索苏斯弗莱的红色沙丘是标志性景观。',
      tip: '该国2017年取消夏令时，全年使用UTC+2。砂石路居多，租车请选四驱并备好备胎。',
      visa: '旅游目的曾可免签停留90天，但制度正在调整，出发前请确认。', emergency: '10111 警察' },
  },
  {
    slug: 'mauritius', code: 'MU', icon: '🇲🇺', region: '오세아니아·아프리카',
    utc: 4, tz: 'Indian/Mauritius', dst: false, dial: '+230', volt: '230V', hz: '50Hz', plug: 'C, G',
    drive: 'left', currencyCode: 'MUR', tld: '.mu',
    ko: { name: '모리셔스', capital: '포트루이스', languages: '영어, 프랑스어, 크리올어', currency: '루피',
      intro: '인도양의 화산섬으로 산호초가 섬 전체를 둘러싸 파도가 잔잔합니다. 도도새가 살았던 곳으로도 알려져 있습니다.',
      tip: '남반구라 계절이 반대이고 1월에서 3월은 사이클론 시기입니다. 5월에서 10월이 여행에 안정적입니다.',
      visa: '관광 목적 90일 무비자로 알려져 있습니다. 숙소와 왕복 항공권을 확인하는 경우가 있습니다.', emergency: '999 경찰 · 114 구급' },
    en: { name: 'Mauritius', capital: 'Port Louis', languages: 'English, French, Creole', currency: 'Rupee',
      intro: 'A volcanic island in the Indian Ocean, ringed by coral reef that keeps the water calm. It is also where the dodo once lived.',
      tip: 'Seasons are reversed and January to March is cyclone season. May to October is the more settled window.',
      visa: 'Ninety days visa-free has applied for tourism; accommodation and a return ticket are sometimes checked.', emergency: '999 police · 114 ambulance' },
    zh: { name: '毛里求斯', capital: '路易港', languages: '英语、法语、克里奥尔语', currency: '卢比',
      intro: '印度洋上的火山岛，四周环绕珊瑚礁，海面平静。这里也是渡渡鸟曾经的栖息地。',
      tip: '位于南半球，季节相反，1月至3月为气旋季。5月至10月出行更为稳定。',
      visa: '旅游目的曾可免签停留90天，有时会查验住宿与往返机票。', emergency: '999 警察 · 114 急救' },
  },
  {
    slug: 'madagascar', code: 'MG', icon: '🇲🇬', region: '오세아니아·아프리카',
    utc: 3, tz: 'Indian/Antananarivo', dst: false, dial: '+261', volt: '220V', hz: '50Hz', plug: 'C, D, E, J, K',
    drive: 'right', currencyCode: 'MGA', tld: '.mg',
    ko: { name: '마다가스카르', capital: '안타나나리보', languages: '말라가시어, 프랑스어', currency: '아리아리',
      intro: '세계에서 네 번째로 큰 섬이고 대륙에서 떨어진 지 오래돼 동식물의 90%가 이곳에만 있습니다. 여우원숭이와 바오밥 나무가 상징입니다.',
      tip: '도로 사정이 좋지 않아 지도상 300km가 하루 종일 걸릴 수 있습니다. 국내선을 섞어 짜는 편이 현실적입니다.',
      visa: '도착비자를 받을 수 있습니다. 조건과 수수료가 바뀌므로 출발 전 확인하세요.', emergency: '117 경찰 · 124 구급' },
    en: { name: 'Madagascar', capital: 'Antananarivo', languages: 'Malagasy, French', currency: 'Ariary',
      intro: 'The fourth-largest island on earth, separated from the mainland long enough that about 90% of its wildlife exists nowhere else. Lemurs and baobabs are its emblems.',
      tip: 'Roads are poor, so 300 km on the map can take a whole day. Mixing in domestic flights is the realistic approach.',
      visa: 'A visa on arrival is available, though terms and fees change — check before departure.', emergency: '117 police · 124 ambulance' },
    zh: { name: '马达加斯加', capital: '塔那那利佛', languages: '马尔加什语、法语', currency: '阿里亚里',
      intro: '世界第四大岛，与大陆分离久远，约90%的动植物为当地独有。狐猴与猴面包树是其象征。',
      tip: '道路状况不佳，地图上的300公里可能要走一整天，搭配国内航班更为现实。',
      visa: '可办落地签，但条件与费用会变动，出发前请确认。', emergency: '117 警察 · 124 急救' },
  },
];
