/** 나라 정보 - 미주 둘째 묶음 (8) */
import type { Country } from './types.ts';

export const AMERICAS2: Country[] = [
  {
    slug: 'colombia', code: 'CO', icon: '🇨🇴', region: '미주',
    utc: -5, tz: 'America/Bogota', dst: false, dial: '+57', volt: '110V', hz: '60Hz', plug: 'A, B',
    drive: 'right', currencyCode: 'COP', tld: '.co',
    ko: { name: '콜롬비아', capital: '보고타', languages: '스페인어', currency: '페소',
      intro: '카리브해와 태평양 양쪽에 해안을 가진 유일한 남미 국가입니다. 보고타는 해발 2,640m 고지대라 적도 근처인데도 연중 서늘합니다.',
      tip: '보고타에 도착하면 고도 때문에 첫날은 무리하지 않는 편이 좋습니다. 해안 도시 카르타헤나는 반대로 덥고 습합니다.',
      visa: '관광 목적 90일 무비자로 알려져 있습니다. 입국 시 왕복 항공권과 숙소 증빙을 요구할 수 있습니다.', emergency: '123' },
    en: { name: 'Colombia', capital: 'Bogotá', languages: 'Spanish', currency: 'Peso',
      intro: 'The only South American country with both Caribbean and Pacific coastlines. Bogotá sits at 2,640 m, which keeps it cool all year despite being near the equator.',
      tip: 'Take the first day gently in Bogotá — the altitude is real. Coastal Cartagena is the opposite: hot and humid.',
      visa: 'Ninety days visa-free has applied for tourism. Officers may ask for a return ticket and accommodation proof.', emergency: '123' },
    zh: { name: '哥伦比亚', capital: '波哥大', languages: '西班牙语', currency: '比索',
      intro: '南美唯一同时拥有加勒比海与太平洋海岸线的国家。波哥大海拔2,640米，虽近赤道却全年凉爽。',
      tip: '抵达波哥大首日不宜过度活动，高海拔影响明显。沿海的卡塔赫纳则相反，炎热潮湿。',
      visa: '旅游目的曾可免签停留90天。入境时可能被要求出示回程机票与住宿证明。', emergency: '123' },
  },
  {
    slug: 'cuba', code: 'CU', icon: '🇨🇺', region: '미주',
    utc: -5, tz: 'America/Havana', dst: true, dial: '+53', volt: '110V', hz: '60Hz', plug: 'A, B, C, L',
    drive: 'right', currencyCode: 'CUP', tld: '.cu',
    ko: { name: '쿠바', capital: '아바나', languages: '스페인어', currency: '페소',
      intro: '카리브해에서 가장 큰 섬으로 1950년대 미국 차량이 아직 굴러다닙니다. 아바나 구시가와 트리니다드가 유네스코 세계유산입니다.',
      tip: '해외 카드 결제와 인터넷이 제한적입니다. 현금을 넉넉히 준비하고 숙소 와이파이 사정을 미리 확인하세요.',
      visa: '관광카드(투어리스트 카드)가 필요합니다. 미국을 경유하는 경우 별도 절차가 생기므로 항공 일정과 함께 확인하세요.', emergency: '106 경찰 · 104 구급' },
    en: { name: 'Cuba', capital: 'Havana', languages: 'Spanish', currency: 'Peso',
      intro: 'The largest island in the Caribbean, where 1950s American cars are still on the road. Old Havana and Trinidad are both UNESCO World Heritage sites.',
      tip: 'Foreign card payments and internet access are limited. Bring enough cash and check what wifi your accommodation actually has.',
      visa: 'A tourist card is required, and routing through the United States adds separate steps — check it alongside your flights.', emergency: '106 police · 104 ambulance' },
    zh: { name: '古巴', capital: '哈瓦那', languages: '西班牙语', currency: '比索',
      intro: '加勒比海最大的岛，1950年代的美国老爷车仍在路上行驶。哈瓦那老城与特立尼达均为世界遗产。',
      tip: '境外银行卡支付与网络都受限。请备足现金，并提前确认住处的无线网络情况。',
      visa: '需要旅游卡。经由美国中转会有额外手续，请与航班行程一并确认。', emergency: '106 警察 · 104 急救' },
  },
  {
    slug: 'costa-rica', code: 'CR', icon: '🇨🇷', region: '미주',
    utc: -6, tz: 'America/Costa_Rica', dst: false, dial: '+506', volt: '120V', hz: '60Hz', plug: 'A, B',
    drive: 'right', currencyCode: 'CRC', tld: '.cr',
    ko: { name: '코스타리카', capital: '산호세', languages: '스페인어', currency: '콜론',
      intro: '국토 4분의 1을 국립공원과 보호구역으로 두어 지구 생물종의 5%가 여기 모여 있습니다. 1948년에 군대를 없앤 나라로도 알려져 있습니다.',
      tip: '태평양과 카리브해 양쪽 해안의 우기가 서로 다릅니다. 한쪽이 비 오는 시기에 다른 쪽은 맑은 경우가 많습니다.',
      visa: '관광 목적 90일 무비자로 알려져 있습니다. 출국 항공권을 확인하는 경우가 있습니다.', emergency: '911' },
    en: { name: 'Costa Rica', capital: 'San José', languages: 'Spanish', currency: 'Colón',
      intro: 'A quarter of the country is national park or reserve, and roughly 5% of all species on earth live inside it. It is also known for abolishing its army in 1948.',
      tip: 'The Pacific and Caribbean coasts have different rainy seasons. When one side is wet the other is often clear.',
      visa: 'Ninety days visa-free has applied for tourism, and an onward ticket is sometimes checked.', emergency: '911' },
    zh: { name: '哥斯达黎加', capital: '圣何塞', languages: '西班牙语', currency: '科朗',
      intro: '国土的四分之一为国家公园或保护区，地球上约5%的物种生活在这里。该国还以1948年废除军队而闻名。',
      tip: '太平洋沿岸与加勒比海沿岸的雨季不同，一侧下雨时另一侧往往晴朗。',
      visa: '旅游目的曾可免签停留90天，有时会查验离境机票。', emergency: '911' },
  },
  {
    slug: 'panama', code: 'PA', icon: '🇵🇦', region: '미주',
    utc: -5, tz: 'America/Panama', dst: false, dial: '+507', volt: '120V', hz: '60Hz', plug: 'A, B',
    drive: 'right', currencyCode: 'PAB', tld: '.pa',
    ko: { name: '파나마', capital: '파나마시티', languages: '스페인어', currency: '발보아(미국 달러 병용)',
      intro: '남북 아메리카를 잇는 좁은 지협에 있고 운하가 태평양과 대서양을 갈라 놓습니다. 지형이 휘어 있어 운하는 남북이 아니라 북서에서 남동으로 지납니다.',
      tip: '자국 통화 발보아와 미국 달러가 1:1로 함께 쓰입니다. 지폐는 달러만 유통되므로 달러를 준비하면 됩니다.',
      visa: '관광 목적 180일 무비자로 알려져 있습니다. 입국 시 재정 증빙과 출국 항공권을 확인할 수 있습니다.', emergency: '911' },
    en: { name: 'Panama', capital: 'Panama City', languages: 'Spanish', currency: 'Balboa (US dollar also used)',
      intro: 'On the narrow isthmus joining the Americas, with a canal cutting between the Pacific and Atlantic. Because the land curves, the canal runs north-west to south-east rather than north to south.',
      tip: 'The balboa is pegged one-to-one with the US dollar, and only dollar notes circulate, so dollars are all you need.',
      visa: 'A hundred and eighty days visa-free has applied for tourism; proof of funds and an onward ticket may be checked.', emergency: '911' },
    zh: { name: '巴拿马', capital: '巴拿马城', languages: '西班牙语', currency: '巴波亚（同时通行美元）',
      intro: '位于连接南北美洲的狭窄地峡上，运河沟通太平洋与大西洋。由于地形弯曲，运河实际是由西北向东南穿行，而非南北走向。',
      tip: '本国货币巴波亚与美元1:1并用，纸币只流通美元，因此备美元即可。',
      visa: '旅游目的曾可免签停留180天，入境时可能查验资金证明与离境机票。', emergency: '911' },
  },
  {
    slug: 'guatemala', code: 'GT', icon: '🇬🇹', region: '미주',
    utc: -6, tz: 'America/Guatemala', dst: false, dial: '+502', volt: '120V', hz: '60Hz', plug: 'A, B, G, I',
    drive: 'right', currencyCode: 'GTQ', tld: '.gt',
    ko: { name: '과테말라', capital: '과테말라시티', languages: '스페인어, 마야어군', currency: '케찰',
      intro: '마야 문명의 중심지였던 곳으로 정글에 파묻힌 티칼 유적이 대표적입니다. 화산 서른 개 남짓이 줄지어 있고 그중 몇은 지금도 활동합니다.',
      tip: '안티과와 아티틀란 호수는 해발이 높아 밤에 쌀쌀합니다. 열대라고만 생각하고 얇은 옷만 챙기면 곤란해집니다.',
      visa: '관광 목적 90일 무비자로 알려져 있습니다. 중미 4개국 협정으로 체류 기간이 합산되는 점을 유의하세요.', emergency: '110 경찰 · 122 소방' },
    en: { name: 'Guatemala', capital: 'Guatemala City', languages: 'Spanish, Mayan languages', currency: 'Quetzal',
      intro: 'A heartland of Maya civilisation, with the jungle-buried ruins of Tikal as its signature site. Some thirty volcanoes line the country and several remain active.',
      tip: 'Antigua and Lake Atitlán sit high enough to be chilly at night. Packing only for the tropics is a mistake here.',
      visa: 'Ninety days visa-free has applied for tourism. Note that the CA-4 agreement pools your allowance across four Central American countries.', emergency: '110 police · 122 fire' },
    zh: { name: '危地马拉', capital: '危地马拉城', languages: '西班牙语、玛雅语族', currency: '格查尔',
      intro: '曾是玛雅文明的核心地带，埋在丛林中的蒂卡尔遗址最具代表性。境内约有三十座火山成列分布，其中数座仍在活动。',
      tip: '安提瓜与阿蒂特兰湖海拔较高，夜间偏凉。若只按热带气候准备薄衣会很吃力。',
      visa: '旅游目的曾可免签停留90天。请注意中美四国协定会把停留天数合并计算。', emergency: '110 警察 · 122 消防' },
  },
  {
    slug: 'ecuador', code: 'EC', icon: '🇪🇨', region: '미주',
    utc: -5, tz: 'America/Guayaquil', dst: false, dial: '+593', volt: '120V', hz: '60Hz', plug: 'A, B',
    drive: 'right', currencyCode: 'USD', tld: '.ec',
    ko: { name: '에콰도르', capital: '키토', languages: '스페인어, 케추아어', currency: '미국 달러',
      intro: '나라 이름 자체가 스페인어로 적도라는 뜻입니다. 본토에서 1,000km 떨어진 갈라파고스 제도가 이 나라 영토입니다.',
      tip: '2000년부터 미국 달러를 공식 통화로 쓰므로 환전이 필요 없습니다. 다만 소액 동전은 현지에서 따로 발행합니다.',
      visa: '관광 목적 90일 무비자로 알려져 있습니다. 갈라파고스 입도에는 별도 입국 카드와 국립공원 입장료가 붙습니다.', emergency: '911' },
    en: { name: 'Ecuador', capital: 'Quito', languages: 'Spanish, Quechua', currency: 'US dollar',
      intro: 'The country’s name is simply Spanish for “equator”. The Galápagos Islands, a thousand kilometres offshore, belong to it.',
      tip: 'The US dollar has been the official currency since 2000, so no exchange is needed — though small coins are minted locally.',
      visa: 'Ninety days visa-free has applied for tourism. Entering the Galápagos adds a separate transit card and a national park fee.', emergency: '911' },
    zh: { name: '厄瓜多尔', capital: '基多', languages: '西班牙语、克丘亚语', currency: '美元',
      intro: '国名在西班牙语中就是“赤道”的意思。距本土一千公里的加拉帕戈斯群岛属于该国领土。',
      tip: '自2000年起以美元为法定货币，无需换汇，但小额硬币由本国另行发行。',
      visa: '旅游目的曾可免签停留90天。进入加拉帕戈斯需另办通行卡并缴纳国家公园门票。', emergency: '911' },
  },
  {
    slug: 'bolivia', code: 'BO', icon: '🇧🇴', region: '미주',
    utc: -4, tz: 'America/La_Paz', dst: false, dial: '+591', volt: '230V', hz: '50Hz', plug: 'A, C',
    drive: 'right', currencyCode: 'BOB', tld: '.bo',
    ko: { name: '볼리비아', capital: '수크레(법정)·라파스(행정)', languages: '스페인어, 케추아어, 아이마라어', currency: '볼리비아노',
      intro: '헌법상 수도는 수크레이고 정부는 라파스에 있습니다. 라파스의 엘알토 공항은 해발 4,000m가 넘어 세계에서 가장 높은 국제공항 가운데 하나입니다.',
      tip: '우유니 소금 사막의 거울 풍경은 우기인 12월에서 3월에만 나옵니다. 건기에는 갈라진 소금 바닥이 보입니다.',
      visa: '사전 비자 또는 도착비자가 필요할 수 있습니다. 고도 4,000m 지역이 많아 고산병 대비를 함께 준비하세요.', emergency: '110 경찰 · 118 구급' },
    en: { name: 'Bolivia', capital: 'Sucre (constitutional) · La Paz (seat of government)', languages: 'Spanish, Quechua, Aymara', currency: 'Boliviano',
      intro: 'Sucre is the constitutional capital while the government sits in La Paz. El Alto airport above La Paz, over 4,000 m up, is among the highest international airports anywhere.',
      tip: 'The mirror effect on the Uyuni salt flat only appears in the wet season, December to March. In the dry months you see cracked salt instead.',
      visa: 'A visa in advance or on arrival may be required. Much of the country sits above 4,000 m, so plan for altitude as well.', emergency: '110 police · 118 ambulance' },
    zh: { name: '玻利维亚', capital: '苏克雷（法定）·拉巴斯（政府所在）', languages: '西班牙语、克丘亚语、艾马拉语', currency: '玻利维亚诺',
      intro: '宪法首都是苏克雷，政府机构设在拉巴斯。拉巴斯上方的埃尔阿尔托机场海拔超过4,000米，是世界上最高的国际机场之一。',
      tip: '乌尤尼盐沼的镜面景观只出现在12月至次年3月的雨季，旱季看到的是龟裂的盐壳。',
      visa: '可能需要提前签证或落地签。境内多为海拔4,000米以上地区，请同时做好高原反应准备。', emergency: '110 警察 · 118 急救' },
  },
  {
    slug: 'uruguay', code: 'UY', icon: '🇺🇾', region: '미주',
    utc: -3, tz: 'America/Montevideo', dst: false, dial: '+598', volt: '220V', hz: '50Hz', plug: 'C, F, I, L',
    drive: 'right', currencyCode: 'UYU', tld: '.uy',
    ko: { name: '우루과이', capital: '몬테비데오', languages: '스페인어', currency: '페소',
      intro: '남미에서 두 번째로 작은 나라로 국토가 평평하고 목축지가 넓습니다. 2015년에 서머타임을 폐지해 연중 UTC−3을 씁니다.',
      tip: '남반구라 계절이 반대입니다. 해변 도시 푼타델에스테의 성수기는 12월에서 2월입니다.',
      visa: '관광 목적 90일 무비자로 알려져 있습니다. 아르헨티나·브라질과 함께 도는 일정이 많으므로 각국 조건을 따로 확인하세요.', emergency: '911' },
    en: { name: 'Uruguay', capital: 'Montevideo', languages: 'Spanish', currency: 'Peso',
      intro: 'The second-smallest country in South America, flat and given over largely to grazing. It dropped daylight saving in 2015 and stays on UTC−3 year round.',
      tip: 'Seasons run the other way in the southern hemisphere: high season on the beach at Punta del Este is December to February.',
      visa: 'Ninety days visa-free has applied for tourism. Trips often combine Argentina and Brazil, so check each country separately.', emergency: '911' },
    zh: { name: '乌拉圭', capital: '蒙特维的亚', languages: '西班牙语', currency: '比索',
      intro: '南美第二小的国家，地势平坦，以牧场为主。该国2015年取消夏令时，全年使用UTC−3。',
      tip: '位于南半球，季节相反。海滨城市埃斯特角的旺季为12月至次年2月。',
      visa: '旅游目的曾可免签停留90天。行程常与阿根廷、巴西串联，请分别确认各国条件。', emergency: '911' },
  },
];
