/** 나라 정보 - 미주 (7) */
import type { Country } from './types.ts';

export const AMERICAS: Country[] = [
  {
    slug: 'usa', code: 'US', icon: '🇺🇸', region: '미주',
    utc: -5, tz: 'America/New_York', dst: true, dial: '+1', volt: '120V', hz: '60Hz', plug: 'A, B',
    drive: 'right', currencyCode: 'USD', tld: '.us',     ko: { name: '미국', capital: '워싱턴 D.C.', languages: '영어', currency: '미국달러',
      intro: '본토에 시간대가 넷이라 동부(뉴욕)와 서부(로스앤젤레스)의 시각이 세 시간 차이 납니다. 표에 적은 UTC−5는 수도인 동부 기준입니다.',
      tip: '식당과 택시에서 팁이 사실상 필수이고 통상 15~20%입니다. 표시 가격에 세금이 빠져 있어 결제 금액이 더 큽니다.',
      visa: '비자면제프로그램으로 90일 체류가 가능하지만 ESTA를 미리 받아야 합니다. 승인에는 며칠이 걸릴 수 있습니다.', emergency: '911' },
    en: { name: 'United States', capital: 'Washington, D.C.', languages: 'English', currency: 'US dollar',
      intro: 'Four time zones across the mainland put New York three hours ahead of Los Angeles. The UTC−5 listed here is Eastern, where the capital sits.',
      tip: 'Tipping is effectively required in restaurants and taxis, normally 15–20%, and listed prices exclude sales tax.',
      visa: 'The Visa Waiver Program allows 90 days, but ESTA must be approved in advance — allow a few days.', emergency: '911' },
  },
  {
    slug: 'canada', code: 'CA', icon: '🇨🇦', region: '미주',
    utc: -5, tz: 'America/Toronto', dst: true, dial: '+1', volt: '120V', hz: '60Hz', plug: 'A, B',
    drive: 'right', currencyCode: 'CAD', tld: '.ca',     ko: { name: '캐나다', capital: '오타와', languages: '영어, 프랑스어', currency: '캐나다달러',
      intro: '국토가 넓어 시간대가 여섯 개입니다. 퀘벡주는 프랑스어가 주 언어라 표지와 안내가 프랑스어 우선인 곳이 많습니다.',
      tip: '전화 국가번호가 미국과 같은 +1입니다. 국제전화 요금 계산 시 미국과 같은 권역으로 묶이는 경우가 많습니다.',
      visa: '관광 목적 6개월 체류가 가능하지만 항공편 입국 시 eTA(전자여행허가)를 미리 받아야 합니다.', emergency: '911' },
    en: { name: 'Canada', capital: 'Ottawa', languages: 'English, French', currency: 'Canadian dollar',
      intro: 'Six time zones span the country. Quebec runs primarily in French, so signage and service often put French first.',
      tip: 'The dialling code is +1, shared with the US, and international call plans frequently treat the two as one zone.',
      visa: 'Up to six months for tourism, but arriving by air requires an approved eTA beforehand.', emergency: '911' },
  },
  {
    slug: 'mexico', code: 'MX', icon: '🇲🇽', region: '미주',
    utc: -6, tz: 'America/Mexico_City', dst: false, dial: '+52', volt: '127V', hz: '60Hz', plug: 'A, B',
    drive: 'right', currencyCode: 'MXN', tld: '.mx',     ko: { name: '멕시코', capital: '멕시코시티', languages: '스페인어', currency: '멕시코페소',
      intro: '2022년에 전국 서머타임을 폐지해 대부분 지역이 일 년 내내 같은 시각을 씁니다. 멕시코시티는 해발 2,200m 고지라 도착 첫날은 무리하지 않는 편이 좋습니다.',
      tip: '수돗물은 마시지 않고 생수를 씁니다. 노점 음식은 회전이 빠른 곳을 고르는 것이 안전합니다.',
      visa: '관광 목적 180일 무비자. 입국 시 체류 목적과 숙소를 확인하는 경우가 있습니다.', emergency: '911' },
    en: { name: 'Mexico', capital: 'Mexico City', languages: 'Spanish', currency: 'Mexican peso',
      intro: 'Nationwide daylight saving was abolished in 2022, so most of the country keeps one clock year-round. Mexico City sits at 2,200 m, so take the first day easy.',
      tip: 'Drink bottled water rather than tap. With street food, pick stalls with fast turnover.',
      visa: '180 days visa-free for tourism. Officers sometimes ask about your purpose and accommodation.', emergency: '911' },
  },
  {
    slug: 'brazil', code: 'BR', icon: '🇧🇷', region: '미주',
    utc: -3, tz: 'America/Sao_Paulo', dst: false, dial: '+55', volt: '127V / 220V', hz: '60Hz', plug: 'C, N',
    drive: 'right', currencyCode: 'BRL', tld: '.br',     ko: { name: '브라질', capital: '브라질리아', languages: '포르투갈어', currency: '헤알',
      intro: '남미 유일의 포르투갈어권 나라이고 2019년에 서머타임을 폐지했습니다. 도시에 따라 전압이 127V와 220V로 갈려 숙소 표시를 확인해야 합니다.',
      tip: '플러그가 브라질 전용 N 타입입니다. 둥근 두 핀은 대개 들어가지만 접지 핀이 있는 기기는 어댑터가 필요합니다.',
      visa: '관광 목적 90일 무비자. 야간에 인적이 드문 길은 피하는 것이 좋습니다.', emergency: '190 경찰 · 192 구급' },
    en: { name: 'Brazil', capital: 'Brasília', languages: 'Portuguese', currency: 'Real',
      intro: 'South America’s only Portuguese-speaking country, and daylight saving ended in 2019. Voltage splits between 127 V and 220 V by city, so check what your accommodation uses.',
      tip: 'Sockets are the Brazilian type N. Round two-pin plugs usually fit, but anything with an earth pin needs an adapter.',
      visa: '90 days visa-free for tourism. Avoid empty streets after dark.', emergency: '190 police · 192 ambulance' },
  },
  {
    slug: 'argentina', code: 'AR', icon: '🇦🇷', region: '미주',
    utc: -3, tz: 'America/Argentina/Buenos_Aires', dst: false, dial: '+54', volt: '220V', hz: '50Hz', plug: 'C, I',
    drive: 'right', currencyCode: 'ARS', tld: '.ar',     ko: { name: '아르헨티나', capital: '부에노스아이레스', languages: '스페인어', currency: '아르헨티나페소',
      intro: '남반구라 계절이 한국과 반대입니다. 12~2월이 여름이고 파타고니아 트레킹도 이 시기에 집중됩니다.',
      tip: '물가 변동이 커서 현지 가격 정보가 금방 낡습니다. 환율과 결제 방식은 도착 직전에 다시 확인하세요.',
      visa: '관광 목적 90일 무비자. 플러그가 I 타입(비스듬한 두 핀)이라 어댑터가 필요합니다.', emergency: '911' },
    en: { name: 'Argentina', capital: 'Buenos Aires', languages: 'Spanish', currency: 'Argentine peso',
      intro: 'Southern hemisphere, so the seasons invert: December to February is summer, and Patagonian trekking concentrates in that window.',
      tip: 'Prices move fast, so local cost information goes stale quickly — recheck exchange rates and payment methods just before you go.',
      visa: '90 days visa-free for tourism. Sockets are type I with angled pins, so bring an adapter.', emergency: '911' },
  },
  {
    slug: 'peru', code: 'PE', icon: '🇵🇪', region: '미주',
    utc: -5, tz: 'America/Lima', dst: false, dial: '+51', volt: '220V', hz: '60Hz', plug: 'A, B, C',
    drive: 'right', currencyCode: 'PEN', tld: '.pe',     ko: { name: '페루', capital: '리마', languages: '스페인어, 케추아어', currency: '솔',
      intro: '마추픽추가 있는 쿠스코는 해발 3,400m로 고산증이 흔합니다. 리마에서 이틀 정도 머문 뒤 올라가는 일정이 안전합니다.',
      tip: '마추픽추는 입장 시간대와 인원이 제한돼 사전 예매가 필수입니다. 성수기에는 몇 주 전에 매진됩니다.',
      visa: '관광 목적 90일 무비자. 전압은 220V인데 플러그는 11자도 들어가는 곳이 많습니다.', emergency: '105 경찰 · 116 소방' },
    en: { name: 'Peru', capital: 'Lima', languages: 'Spanish, Quechua', currency: 'Sol',
      intro: 'Cusco, the base for Machu Picchu, sits at 3,400 m and altitude sickness is common. Spending a couple of days in Lima first is the safer plan.',
      tip: 'Machu Picchu caps visitors by time slot, so tickets must be booked ahead — peak season sells out weeks out.',
      visa: '90 days visa-free for tourism. Supply is 220 V, though many sockets also accept flat two-pin plugs.', emergency: '105 police · 116 fire' },
  },
  {
    slug: 'chile', code: 'CL', icon: '🇨🇱', region: '미주',
    utc: -4, tz: 'America/Santiago', dst: true, dial: '+56', volt: '220V', hz: '50Hz', plug: 'C, L',
    drive: 'right', currencyCode: 'CLP', tld: '.cl',     ko: { name: '칠레', capital: '산티아고', languages: '스페인어', currency: '칠레페소',
      intro: '남북으로 4,300km나 이어져 북쪽 아타카마 사막과 남쪽 파타고니아의 기후가 완전히 다릅니다. 남반구라 서머타임도 한국과 반대 시기에 적용됩니다.',
      tip: '아타카마 사막은 해발 2,400m 이상이라 밤이 매우 춥습니다. 별 관측 투어에는 두꺼운 옷이 필요합니다.',
      visa: '관광 목적 90일 무비자. 농축산물 반입 규제가 엄격해 반드시 신고해야 합니다.', emergency: '133 경찰 · 131 구급' },
    en: { name: 'Chile', capital: 'Santiago', languages: 'Spanish', currency: 'Chilean peso',
      intro: 'Stretching 4,300 km north to south, the Atacama Desert and Patagonia have nothing in common climatically. Being in the southern hemisphere, its daylight saving runs opposite to Korea’s.',
      tip: 'The Atacama sits above 2,400 m and nights get very cold — stargazing tours need serious layers.',
      visa: '90 days visa-free for tourism. Agricultural import rules are strict, so declare everything.', emergency: '133 police · 131 ambulance' },
  },
];
