/** 나라 정보 - 동아시아·동남아시아 앞부분 (8) */
import type { Country } from './types.ts';

export const EAST_ASIA: Country[] = [
  {
    slug: 'japan', code: 'JP', icon: '🇯🇵', region: '동아시아',
    utc: 9, tz: 'Asia/Tokyo', dst: false, dial: '+81', volt: '100V', hz: '50/60Hz', plug: 'A, B',
    drive: 'left', currencyCode: 'JPY', tld: '.jp',     ko: { name: '일본', capital: '도쿄', languages: '일본어', currency: '엔',
      intro: '한국에서 비행 두 시간 거리이고 시차가 없어 주말에도 다녀올 수 있는 나라입니다. 도쿄와 오사카를 잇는 신칸센, 지역마다 다른 온천과 향토 음식이 여행의 축입니다.',
      tip: '전압이 100V라 한국 220V 기기는 변압기가 필요할 수 있습니다. 플러그 모양은 11자 평판이라 흔한 여행용 어댑터로 됩니다.',
      visa: '관광 목적 90일 무비자. 입국 전 Visit Japan Web에 세관·입국 정보를 미리 등록하면 심사가 빠릅니다.', emergency: '110 경찰 · 119 소방' },
    en: { name: 'Japan', capital: 'Tokyo', languages: 'Japanese', currency: 'Yen',
      intro: 'Two hours from Seoul with no time difference, Japan works even for a weekend trip. The Shinkansen between Tokyo and Osaka, plus regional hot springs and local food, anchor most itineraries.',
      tip: 'Mains power is 100 V, so high-draw 220 V appliances may need a transformer. The flat two-pin plug fits most travel adapters.',
      visa: '90 days visa-free for tourism for Korean passports. Registering customs and immigration details on Visit Japan Web beforehand speeds up arrival.', emergency: '110 police · 119 fire' },
  },
  {
    slug: 'china', code: 'CN', icon: '🇨🇳', region: '동아시아',
    utc: 8, tz: 'Asia/Shanghai', dst: false, dial: '+86', volt: '220V', hz: '50Hz', plug: 'A, C, I',
    drive: 'right', currencyCode: 'CNY', tld: '.cn',     ko: { name: '중국', capital: '베이징', languages: '중국어(표준중국어)', currency: '위안',
      intro: '국토가 넓지만 시간대는 하나로 통일해 전국이 UTC+8을 씁니다. 한국보다 한 시간 느리고, 고속철도망이 촘촘해 도시 간 이동이 편합니다.',
      tip: '현금보다 알리페이·위챗페이가 기본입니다. 해외 카드 등록이 되지만 미리 앱을 설치하고 인증을 끝내 두는 편이 안전합니다.',
      visa: '무비자 입국이 가능한 기간이 있지만 정책 변동이 잦습니다. 출발 전 주중국대사관 공지를 반드시 확인하세요.', emergency: '110 경찰 · 120 구급' },
    en: { name: 'China', capital: 'Beijing', languages: 'Mandarin Chinese', currency: 'Yuan',
      intro: 'Despite its size China runs on a single time zone, UTC+8 — one hour behind Korea. A dense high-speed rail network makes intercity travel straightforward.',
      tip: 'Alipay and WeChat Pay matter more than cash. Foreign cards can be linked, but install and verify the apps before you fly.',
      visa: 'Visa-free entry has been available for Korean passports, but the policy changes often — check the embassy notice before departure.', emergency: '110 police · 120 ambulance' },
  },
  {
    slug: 'taiwan', code: 'TW', icon: '🇹🇼', region: '동아시아',
    utc: 8, tz: 'Asia/Taipei', dst: false, dial: '+886', volt: '110V', hz: '60Hz', plug: 'A, B',
    drive: 'right', currencyCode: 'TWD', tld: '.tw',     ko: { name: '대만', capital: '타이베이', languages: '중국어(대만 표준), 대만어', currency: '신대만달러',
      intro: '비행 두 시간 반, 시차 한 시간이라 짧은 일정에도 무리가 없습니다. 야시장과 우육면, 온천, 지우펀 같은 근교 코스가 잘 짜여 있습니다.',
      tip: '전압이 110V라 헤어드라이어 같은 발열 기기는 성능이 떨어질 수 있습니다. 지하철에서는 음식·음료 섭취가 금지돼 벌금이 붙습니다.',
      visa: '관광 목적 90일 무비자. 입국 시 왕복 항공권과 숙소 정보를 확인하는 경우가 있습니다.', emergency: '110 경찰 · 119 소방' },
    en: { name: 'Taiwan', capital: 'Taipei', languages: 'Mandarin, Taiwanese', currency: 'New Taiwan dollar',
      intro: 'Two and a half hours away with a one-hour time difference, Taiwan suits short trips. Night markets, beef noodle soup, hot springs and day trips like Jiufen make an easy itinerary.',
      tip: 'At 110 V, heating appliances such as hair dryers run weaker. Eating or drinking on the metro is fined.',
      visa: '90 days visa-free for tourism. Officers may ask to see a return ticket and accommodation details on arrival.', emergency: '110 police · 119 fire' },
  },
  {
    slug: 'hong-kong', code: 'HK', icon: '🇭🇰', region: '동아시아',
    utc: 8, tz: 'Asia/Hong_Kong', dst: false, dial: '+852', volt: '220V', hz: '50Hz', plug: 'G',
    drive: 'left', currencyCode: 'HKD', tld: '.hk',     ko: { name: '홍콩', capital: '(특별행정구)', languages: '광둥어, 영어, 중국어', currency: '홍콩달러',
      intro: '좁은 면적에 지하철과 트램, 페리가 촘촘히 얽혀 차 없이 다니기 좋은 도시입니다. 영국 통치의 흔적으로 좌측통행과 영국식 3구 플러그를 씁니다.',
      tip: '플러그가 영국식 G 타입이라 유럽용 어댑터로는 맞지 않습니다. 옥토퍼스 카드 하나로 교통과 편의점 결제가 모두 됩니다.',
      visa: '관광 목적 90일 무비자. 여권 유효기간이 체류 예정 기간보다 넉넉해야 합니다.', emergency: '999' },
    en: { name: 'Hong Kong', capital: '(Special Administrative Region)', languages: 'Cantonese, English, Chinese', currency: 'Hong Kong dollar',
      intro: 'A compact city where metro, trams and ferries interlock tightly enough that no car is needed. British rule left behind left-hand traffic and the three-pin British plug.',
      tip: 'The plug is British type G, so European adapters will not fit. One Octopus card covers transit and convenience stores alike.',
      visa: '90 days visa-free for tourism. Your passport must be valid comfortably beyond your planned stay.', emergency: '999' },
  },
  {
    slug: 'macau', code: 'MO', icon: '🇲🇴', region: '동아시아',
    utc: 8, tz: 'Asia/Macau', dst: false, dial: '+853', volt: '220V', hz: '50Hz', plug: 'D, G, M',
    drive: 'left', currencyCode: 'MOP', tld: '.mo',     ko: { name: '마카오', capital: '(특별행정구)', languages: '광둥어, 포르투갈어, 중국어', currency: '파타카',
      intro: '포르투갈 통치의 흔적이 도시 곳곳에 남아 성당과 광장이 중국식 거리와 붙어 있습니다. 홍콩에서 페리로 한 시간, 강주아오 대교로 버스도 다닙니다.',
      tip: '현지 통화는 파타카지만 홍콩달러가 거의 그대로 통용됩니다. 다만 거스름돈은 파타카로 돌아옵니다.',
      visa: '관광 목적 90일 무비자. 홍콩과 별도의 출입국 심사를 받습니다.', emergency: '999' },
    en: { name: 'Macau', capital: '(Special Administrative Region)', languages: 'Cantonese, Portuguese, Chinese', currency: 'Pataca',
      intro: 'Portuguese rule left churches and praças sitting directly against Chinese streets. It is an hour by ferry from Hong Kong, or by bus over the Hong Kong–Zhuhai–Macau Bridge.',
      tip: 'The local currency is the pataca, but Hong Kong dollars are accepted almost everywhere — expect change back in patacas.',
      visa: '90 days visa-free for tourism. Immigration is separate from Hong Kong’s.', emergency: '999' },
  },
  {
    slug: 'mongolia', code: 'MN', icon: '🇲🇳', region: '동아시아',
    utc: 8, tz: 'Asia/Ulaanbaatar', dst: false, dial: '+976', volt: '220V', hz: '50Hz', plug: 'C, E',
    drive: 'right', currencyCode: 'MNT', tld: '.mn',     ko: { name: '몽골', capital: '울란바토르', languages: '몽골어', currency: '투그릭',
      intro: '인구밀도가 세계에서 가장 낮은 나라로, 수도를 벗어나면 초원과 고비 사막이 이어집니다. 여행 성수기는 짧은 여름인 6~8월입니다.',
      tip: '일교차가 매우 큽니다. 여름에도 초원의 밤은 10도 아래로 떨어지니 겹쳐 입을 옷이 필요합니다.',
      visa: '관광 목적 90일 무비자. 초원 지역은 통신이 끊기는 곳이 많아 오프라인 지도를 미리 내려두세요.', emergency: '102 경찰 · 103 구급' },
    en: { name: 'Mongolia', capital: 'Ulaanbaatar', languages: 'Mongolian', currency: 'Tögrög',
      intro: 'The least densely populated country on earth: leave the capital and steppe gives way to the Gobi. The travel season is the short summer, June to August.',
      tip: 'The daily temperature swing is extreme — steppe nights drop below 10°C even in summer, so pack layers.',
      visa: '90 days visa-free for tourism. Coverage vanishes across much of the steppe, so download offline maps first.', emergency: '102 police · 103 ambulance' },
  },
  {
    slug: 'singapore', code: 'SG', icon: '🇸🇬', region: '동남아시아',
    utc: 8, tz: 'Asia/Singapore', dst: false, dial: '+65', volt: '230V', hz: '50Hz', plug: 'G',
    drive: 'left', currencyCode: 'SGD', tld: '.sg',     ko: { name: '싱가포르', capital: '싱가포르', languages: '영어, 중국어, 말레이어, 타밀어', currency: '싱가포르달러',
      intro: '도시 하나가 나라 전체인 곳으로, 적도 근처라 일 년 내내 낮과 밤 길이가 거의 같습니다. 영어가 행정 언어라 의사소통이 쉽습니다.',
      tip: '껌 판매, 대중교통 내 음식물, 지정 구역 밖 흡연에 실제로 벌금이 부과됩니다. 표지판을 눈여겨보세요.',
      visa: '관광 목적 90일 무비자. 입국 전 SG Arrival Card를 온라인으로 제출해야 합니다.', emergency: '999 경찰 · 995 구급' },
    en: { name: 'Singapore', capital: 'Singapore', languages: 'English, Chinese, Malay, Tamil', currency: 'Singapore dollar',
      intro: 'A single city that is also the whole country. Sitting near the equator, day and night stay nearly equal all year, and English as an administrative language makes it easy to navigate.',
      tip: 'Fines for selling gum, eating on public transport or smoking outside marked zones are actually enforced — read the signs.',
      visa: '90 days visa-free for tourism. You must file the SG Arrival Card online before entry.', emergency: '999 police · 995 ambulance' },
  },
  {
    slug: 'philippines', code: 'PH', icon: '🇵🇭', region: '동남아시아',
    utc: 8, tz: 'Asia/Manila', dst: false, dial: '+63', volt: '220V', hz: '60Hz', plug: 'A, B, C',
    drive: 'right', currencyCode: 'PHP', tld: '.ph',     ko: { name: '필리핀', capital: '마닐라', languages: '필리핀어(타갈로그), 영어', currency: '페소',
      intro: '7천 개가 넘는 섬으로 이루어져 있어 목적지에 따라 국내선 이동이 필수입니다. 세부와 보라카이는 휴양지, 마닐라는 관문 도시 성격이 강합니다.',
      tip: '주파수가 60Hz라 한국 기기와 잘 맞고 플러그도 11자가 통합니다. 대신 전압이 220V라 미국 기기는 주의가 필요합니다.',
      visa: '관광 목적 30일 무비자. 입국 시 왕복 항공권을 요구하는 경우가 많습니다.', emergency: '911' },
    en: { name: 'Philippines', capital: 'Manila', languages: 'Filipino (Tagalog), English', currency: 'Peso',
      intro: 'Made up of more than 7,000 islands, so domestic flights are usually part of the plan. Cebu and Boracay are resort destinations; Manila functions mainly as the gateway.',
      tip: 'At 60 Hz with flat two-pin sockets, Korean devices fit well — but the 220 V supply needs care with US-market appliances.',
      visa: '30 days visa-free for tourism. A return ticket is commonly requested at immigration.', emergency: '911' },
  },
];
