/** 나라 정보 - 서·남아시아 (6) */
import type { Country } from './types.ts';

export const WEST_ASIA: Country[] = [
  {
    slug: 'india', code: 'IN', icon: '🇮🇳', region: '서·남아시아',
    utc: 5.5, tz: 'Asia/Kolkata', dst: false, dial: '+91', volt: '230V', hz: '50Hz', plug: 'C, D, M',
    drive: 'left', currencyCode: 'INR', tld: '.in',     ko: { name: '인도', capital: '뉴델리', languages: '힌디어, 영어 외 다수', currency: '루피',
      intro: '표준시가 UTC+5:30으로 30분 단위이고, 넓은 국토를 하나의 시간대로 씁니다. 헌법이 인정하는 공용어가 22개나 됩니다.',
      tip: '플러그가 D·M 타입이라 한국 어댑터로는 맞지 않는 곳이 많습니다. 멀티 어댑터를 챙기세요.',
      visa: '전자비자를 미리 받아야 합니다. 무비자 입국은 되지 않습니다.', emergency: '112' },
    en: { name: 'India', capital: 'New Delhi', languages: 'Hindi, English and many more', currency: 'Rupee',
      intro: 'India runs on a half-hour offset, UTC+5:30, with one time zone across a very wide country. The constitution recognises 22 official languages.',
      tip: 'Type D and M sockets are common and Korean adapters often will not fit — bring a universal one.',
      visa: 'An e-visa must be obtained in advance; there is no visa-free entry.', emergency: '112' },
  },
  {
    slug: 'nepal', code: 'NP', icon: '🇳🇵', region: '서·남아시아',
    utc: 5.75, tz: 'Asia/Kathmandu', dst: false, dial: '+977', volt: '230V', hz: '50Hz', plug: 'C, D, M',
    drive: 'left', currencyCode: 'NPR', tld: '.np',     ko: { name: '네팔', capital: '카트만두', languages: '네팔어', currency: '네팔루피',
      intro: '표준시가 UTC+5:45로 15분 단위인 세계에서 드문 나라입니다. 히말라야 트레킹의 관문이고, 10~11월이 시야가 가장 맑습니다.',
      tip: '고산 지역 트레킹은 고도 적응 일정이 필수입니다. 하루 500m 이상 급하게 올리지 않는 것이 원칙입니다.',
      visa: '도착비자를 받을 수 있습니다. 입국 시 여권 사진과 수수료를 준비하세요.', emergency: '100 경찰 · 102 구급' },
    en: { name: 'Nepal', capital: 'Kathmandu', languages: 'Nepali', currency: 'Nepalese rupee',
      intro: 'One of the very few countries on a quarter-hour offset, UTC+5:45. It is the gateway to Himalayan trekking, with the clearest views in October and November.',
      tip: 'High-altitude treks need acclimatisation days built in — the rule of thumb is not to gain more than 500 m of sleeping altitude a day.',
      visa: 'Visa on arrival is available. Bring a passport photo and the fee.', emergency: '100 police · 102 ambulance' },
  },
  {
    slug: 'sri-lanka', code: 'LK', icon: '🇱🇰', region: '서·남아시아',
    utc: 5.5, tz: 'Asia/Colombo', dst: false, dial: '+94', volt: '230V', hz: '50Hz', plug: 'D, G, M',
    drive: 'left', currencyCode: 'LKR', tld: '.lk',     ko: { name: '스리랑카', capital: '스리자야와르데네푸라코테', languages: '싱할라어, 타밀어', currency: '스리랑카루피',
      intro: '행정 수도와 최대 도시(콜롬보)가 다릅니다. 섬 남서부와 북동부의 우기가 서로 어긋나 어느 계절에도 갈 만한 지역이 있습니다.',
      tip: '고산 지대 열차 구간(칸디~엘라)은 좌석이 빨리 팔립니다. 며칠 전 예약하는 편이 안전합니다.',
      visa: '전자여행허가(ETA)를 미리 받아야 합니다.', emergency: '119 경찰 · 110 구급' },
    en: { name: 'Sri Lanka', capital: 'Sri Jayawardenepura Kotte', languages: 'Sinhala, Tamil', currency: 'Sri Lankan rupee',
      intro: 'The administrative capital differs from the largest city, Colombo. Monsoons hit the south-west and north-east at opposite times, so some region is always in season.',
      tip: 'Seats on the hill-country train (Kandy to Ella) sell out fast — book several days ahead.',
      visa: 'An electronic travel authorisation (ETA) must be obtained in advance.', emergency: '119 police · 110 ambulance' },
  },
  {
    slug: 'uae', code: 'AE', icon: '🇦🇪', region: '서·남아시아',
    utc: 4, tz: 'Asia/Dubai', dst: false, dial: '+971', volt: '230V', hz: '50Hz', plug: 'C, D, G',
    drive: 'right', currencyCode: 'AED', tld: '.ae',     ko: { name: '아랍에미리트', capital: '아부다비', languages: '아라비아어, 영어', currency: '디르함',
      intro: '수도는 아부다비지만 여행자에게 익숙한 도시는 두바이입니다. 여름(6~9월)은 낮 기온이 45도를 넘어 실내 위주 일정이 됩니다.',
      tip: '금요일이 이슬람 예배일로 오전에는 문을 닫는 곳이 많습니다. 공공장소에서의 노출이 많은 옷차림은 피하는 편이 좋습니다.',
      visa: '관광 목적 90일 무비자. 유럽·아프리카 환승 거점으로도 많이 쓰입니다.', emergency: '999 경찰 · 998 구급' },
    en: { name: 'United Arab Emirates', capital: 'Abu Dhabi', languages: 'Arabic, English', currency: 'Dirham',
      intro: 'Abu Dhabi is the capital, but Dubai is the city most travellers know. Summer highs pass 45°C from June to September, pushing itineraries indoors.',
      tip: 'Friday is the day of prayer and many places close in the morning. Revealing clothing in public spaces is best avoided.',
      visa: '90 days visa-free for tourism. It is also a heavily used transit hub for Europe and Africa.', emergency: '999 police · 998 ambulance' },
  },
  {
    slug: 'turkey', code: 'TR', icon: '🇹🇷', region: '서·남아시아',
    utc: 3, tz: 'Europe/Istanbul', dst: false, dial: '+90', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'TRY', tld: '.tr',     ko: { name: '튀르키예', capital: '앙카라', languages: '튀르키예어', currency: '리라',
      intro: '아시아와 유럽에 걸쳐 있고, 2016년부터 서머타임을 폐지해 일 년 내내 UTC+3을 씁니다. 이스탄불이 최대 도시이고 수도는 앙카라입니다.',
      tip: '플러그가 유럽식 C·F 타입이라 한국 기기가 그대로 들어갑니다. 카파도키아 열기구는 바람에 따라 결항이 잦아 일정에 여유를 두세요.',
      visa: '관광 목적 90일 무비자(180일 중 90일). 여권 유효기간이 6개월 이상 남아야 합니다.', emergency: '112' },
    en: { name: 'Türkiye', capital: 'Ankara', languages: 'Turkish', currency: 'Lira',
      intro: 'Straddling Asia and Europe, Türkiye abolished daylight saving in 2016 and stays on UTC+3 year-round. Istanbul is the largest city; Ankara is the capital.',
      tip: 'European type C and F sockets take Korean plugs directly. Cappadocia balloon flights are cancelled often for wind — leave slack in the schedule.',
      visa: '90 days visa-free for tourism within any 180-day period. Passports should have at least six months of validity.', emergency: '112' },
  },
  {
    slug: 'uzbekistan', code: 'UZ', icon: '🇺🇿', region: '서·남아시아',
    utc: 5, tz: 'Asia/Tashkent', dst: false, dial: '+998', volt: '220V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'UZS', tld: '.uz',     ko: { name: '우즈베키스탄', capital: '타슈켄트', languages: '우즈베크어, 러시아어', currency: '숨',
      intro: '실크로드의 중심이던 사마르칸트와 부하라의 이슬람 건축이 여행의 핵심입니다. 봄과 가을이 다니기 좋고 여름은 매우 건조하고 뜨겁습니다.',
      tip: '고속철도로 타슈켄트~사마르칸트가 두 시간대입니다. 좌석이 빨리 나가 온라인 사전 예약이 낫습니다.',
      visa: '관광 목적 30일 무비자. 숙소에서 발급하는 체류 등록 서류를 보관해 두는 편이 좋습니다.', emergency: '102 경찰 · 103 구급' },
    en: { name: 'Uzbekistan', capital: 'Tashkent', languages: 'Uzbek, Russian', currency: 'Som',
      intro: 'The Islamic architecture of Samarkand and Bukhara, once Silk Road hubs, is the point of the trip. Spring and autumn are comfortable; summer is very dry and hot.',
      tip: 'High-speed rail links Tashkent and Samarkand in about two hours. Seats sell out, so book online in advance.',
      visa: '30 days visa-free for tourism. Keep the registration slips your accommodation issues.', emergency: '102 police · 103 ambulance' },
  },
];
