/** 나라 정보 - 동아시아·동남아시아 앞부분 (8) */
import type { Country } from './types.ts';

export const EAST_ASIA: Country[] = [
  {
    slug: 'japan', code: 'JP', icon: '🇯🇵', region: '동아시아',
    utc: 9, tz: 'Asia/Tokyo', dst: false, dial: '+81', volt: '100V', hz: '50/60Hz', plug: 'A, B',
    drive: 'left', currencyCode: 'JPY', tld: '.jp',     ko: { name: '일본', capital: '도쿄', languages: '일본어', currency: '엔',
      intro: '한국에서 비행 두 시간 거리이고 시차가 없어 주말에도 다녀올 수 있는 나라입니다. 도쿄와 오사카를 잇는 신칸센, 지역마다 다른 온천과 향토 음식이 여행의 축입니다.',
      tip: '전압이 100V라 한국 220V 기기는 변압기가 필요할 수 있습니다. 플러그 모양은 11자 평판이라 흔한 여행용 어댑터로 됩니다.',
      visa: '관광 목적 90일 무비자. 입국 전 Visit Japan Web에 세관·입국 정보를 미리 등록하면 심사가 빠릅니다.', emergency: '110 경찰 · 119 소방' },
    en: { name: 'Japan', capital: 'Tokyo', languages: 'Japanese', currency: 'Yen',
      intro: 'Two hours from Seoul with no time difference, Japan works even for a weekend trip. The Shinkansen between Tokyo and Osaka, plus regional hot springs and local food, anchor most itineraries.',
      tip: 'Mains power is 100 V, so high-draw 220 V appliances may need a transformer. The flat two-pin plug fits most travel adapters.',
      visa: '90 days visa-free for tourism for Korean passports. Registering customs and immigration details on Visit Japan Web beforehand speeds up arrival.', emergency: '110 police · 119 fire' },
    zh: { name: '日本', capital: '东京', languages: '日语', currency: '日元',
      intro: '从首尔飞两小时且没有时差，周末也能往返。东京与大阪之间的新干线，以及各地不同的温泉和乡土料理，构成大多数行程的主轴。',
      tip: '电压为100V，功率大的220V电器可能需要变压器。插头是两枚平行扁脚，普通旅行转换头即可。',
      visa: '韩国护照旅游可免签停留90天。出发前在Visit Japan Web登记海关与入境信息可加快通关。', emergency: '110 警察 · 119 消防' },
  },
  {
    slug: 'china', code: 'CN', icon: '🇨🇳', region: '동아시아',
    utc: 8, tz: 'Asia/Shanghai', dst: false, dial: '+86', volt: '220V', hz: '50Hz', plug: 'A, C, I',
    drive: 'right', currencyCode: 'CNY', tld: '.cn',     ko: { name: '중국', capital: '베이징', languages: '중국어(표준중국어)', currency: '위안',
      intro: '국토가 넓지만 시간대는 하나로 통일해 전국이 UTC+8을 씁니다. 한국보다 한 시간 느리고, 고속철도망이 촘촘해 도시 간 이동이 편합니다.',
      tip: '현금보다 알리페이·위챗페이가 기본입니다. 해외 카드 등록이 되지만 미리 앱을 설치하고 인증을 끝내 두는 편이 안전합니다.',
      visa: '무비자 입국이 가능한 기간이 있지만 정책 변동이 잦습니다. 출발 전 주중국대사관 공지를 반드시 확인하세요.', emergency: '110 경찰 · 120 구급' },
    en: { name: 'China', capital: 'Beijing', languages: 'Mandarin Chinese', currency: 'Yuan',
      intro: 'Despite its size China runs on a single time zone, UTC+8 — one hour behind Korea. A dense high-speed rail network makes intercity travel straightforward.',
      tip: 'Alipay and WeChat Pay matter more than cash. Foreign cards can be linked, but install and verify the apps before you fly.',
      visa: 'Visa-free entry has been available for Korean passports, but the policy changes often — check the embassy notice before departure.', emergency: '110 police · 120 ambulance' },
    zh: { name: '中国', capital: '北京', languages: '普通话', currency: '人民币',
      intro: '国土辽阔但全国统一使用UTC+8时区，比韩国晚一小时。高铁网络密集，城市间往来十分便利。',
      tip: '支付宝和微信支付比现金更重要。境外银行卡可以绑定，但请在出发前就装好并完成实名认证。',
      visa: '韩国护照曾可免签入境，但政策变动频繁 — 出发前请务必查看使馆公告。', emergency: '110 警察 · 120 急救' },
  },
  {
    slug: 'taiwan', code: 'TW', icon: '🇹🇼', region: '동아시아',
    utc: 8, tz: 'Asia/Taipei', dst: false, dial: '+886', volt: '110V', hz: '60Hz', plug: 'A, B',
    drive: 'right', currencyCode: 'TWD', tld: '.tw',     ko: { name: '대만', capital: '타이베이', languages: '중국어(대만 표준), 대만어', currency: '신대만달러',
      intro: '비행 두 시간 반, 시차 한 시간이라 짧은 일정에도 무리가 없습니다. 야시장과 우육면, 온천, 지우펀 같은 근교 코스가 잘 짜여 있습니다.',
      tip: '전압이 110V라 헤어드라이어 같은 발열 기기는 성능이 떨어질 수 있습니다. 지하철에서는 음식·음료 섭취가 금지돼 벌금이 붙습니다.',
      visa: '관광 목적 90일 무비자. 입국 시 왕복 항공권과 숙소 정보를 확인하는 경우가 있습니다.', emergency: '110 경찰 · 119 소방' },
    en: { name: 'Taiwan', capital: 'Taipei', languages: 'Mandarin, Taiwanese', currency: 'New Taiwan dollar',
      intro: 'Two and a half hours away with a one-hour time difference, Taiwan suits short trips. Night markets, beef noodle soup, hot springs and day trips like Jiufen make an easy itinerary.',
      tip: 'At 110 V, heating appliances such as hair dryers run weaker. Eating or drinking on the metro is fined.',
      visa: '90 days visa-free for tourism. Officers may ask to see a return ticket and accommodation details on arrival.', emergency: '110 police · 119 fire' },
    zh: { name: '台湾', capital: '台北', languages: '国语、台语', currency: '新台币',
      intro: '飞行两个半小时、时差一小时，短程行程也很轻松。夜市、牛肉面、温泉以及九份等近郊路线搭配得很成熟。',
      tip: '电压110V，吹风机等发热电器功率会偏弱。地铁内禁止饮食，违者罚款。',
      visa: '韩国护照旅游可免签停留90天。入境时可能会查验回程机票和住宿信息。', emergency: '110 警察 · 119 消防' },
  },
  {
    slug: 'hong-kong', code: 'HK', icon: '🇭🇰', region: '동아시아',
    utc: 8, tz: 'Asia/Hong_Kong', dst: false, dial: '+852', volt: '220V', hz: '50Hz', plug: 'G',
    drive: 'left', currencyCode: 'HKD', tld: '.hk',     ko: { name: '홍콩', capital: '(특별행정구)', languages: '광둥어, 영어, 중국어', currency: '홍콩달러',
      intro: '좁은 면적에 지하철과 트램, 페리가 촘촘히 얽혀 차 없이 다니기 좋은 도시입니다. 영국 통치의 흔적으로 좌측통행과 영국식 3구 플러그를 씁니다.',
      tip: '플러그가 영국식 G 타입이라 유럽용 어댑터로는 맞지 않습니다. 옥토퍼스 카드 하나로 교통과 편의점 결제가 모두 됩니다.',
      visa: '관광 목적 90일 무비자. 여권 유효기간이 체류 예정 기간보다 넉넉해야 합니다.', emergency: '999' },
    en: { name: 'Hong Kong', capital: '(Special Administrative Region)', languages: 'Cantonese, English, Chinese', currency: 'Hong Kong dollar',
      intro: 'A compact city where metro, trams and ferries interlock tightly enough that no car is needed. British rule left behind left-hand traffic and the three-pin British plug.',
      tip: 'The plug is British type G, so European adapters will not fit. One Octopus card covers transit and convenience stores alike.',
      visa: '90 days visa-free for tourism. Your passport must be valid comfortably beyond your planned stay.', emergency: '999' },
    zh: { name: '香港', capital: '(特别行政区)', languages: '粤语、英语、汉语', currency: '港元',
      intro: '面积不大，地铁、电车和渡轮交织密集，完全不需要开车。英治时期留下了左侧通行和英式三脚插头。',
      tip: '插头为英式G型，欧洲转换头无法使用。一张八达通即可搞定交通和便利店支付。',
      visa: '韩国护照旅游可免签停留90天。护照有效期需明显长于计划停留时间。', emergency: '999' },
  },
  {
    slug: 'macau', code: 'MO', icon: '🇲🇴', region: '동아시아',
    utc: 8, tz: 'Asia/Macau', dst: false, dial: '+853', volt: '220V', hz: '50Hz', plug: 'D, G, M',
    drive: 'left', currencyCode: 'MOP', tld: '.mo',     ko: { name: '마카오', capital: '(특별행정구)', languages: '광둥어, 포르투갈어, 중국어', currency: '파타카',
      intro: '포르투갈 통치의 흔적이 도시 곳곳에 남아 성당과 광장이 중국식 거리와 붙어 있습니다. 홍콩에서 페리로 한 시간, 강주아오 대교로 버스도 다닙니다.',
      tip: '현지 통화는 파타카지만 홍콩달러가 거의 그대로 통용됩니다. 다만 거스름돈은 파타카로 돌아옵니다.',
      visa: '관광 목적 90일 무비자. 홍콩과 별도의 출입국 심사를 받습니다.', emergency: '999' },
    en: { name: 'Macau', capital: '(Special Administrative Region)', languages: 'Cantonese, Portuguese, Chinese', currency: 'Pataca',
      intro: 'Portuguese rule left churches and praças sitting directly against Chinese streets. It is an hour by ferry from Hong Kong, or by bus over the Hong Kong–Zhuhai–Macau Bridge.',
      tip: 'The local currency is the pataca, but Hong Kong dollars are accepted almost everywhere — expect change back in patacas.',
      visa: '90 days visa-free for tourism. Immigration is separate from Hong Kong’s.', emergency: '999' },
    zh: { name: '澳门', capital: '(特别行政区)', languages: '粤语、葡语、汉语', currency: '澳门元',
      intro: '葡治时期的痕迹遍布城中，教堂和广场紧挨着华人街区。从香港乘渡轮约一小时，也可经港珠澳大桥坐巴士前往。',
      tip: '本地货币是澳门元，但港币几乎通用 — 只是找零会用澳门元。',
      visa: '韩国护照旅游可免签停留90天。出入境与香港分开办理。', emergency: '999' },
  },
  {
    slug: 'mongolia', code: 'MN', icon: '🇲🇳', region: '동아시아',
    utc: 8, tz: 'Asia/Ulaanbaatar', dst: false, dial: '+976', volt: '220V', hz: '50Hz', plug: 'C, E',
    drive: 'right', currencyCode: 'MNT', tld: '.mn',     ko: { name: '몽골', capital: '울란바토르', languages: '몽골어', currency: '투그릭',
      intro: '인구밀도가 세계에서 가장 낮은 나라로, 수도를 벗어나면 초원과 고비 사막이 이어집니다. 여행 성수기는 짧은 여름인 6~8월입니다.',
      tip: '일교차가 매우 큽니다. 여름에도 초원의 밤은 10도 아래로 떨어지니 겹쳐 입을 옷이 필요합니다.',
      visa: '관광 목적 90일 무비자. 초원 지역은 통신이 끊기는 곳이 많아 오프라인 지도를 미리 내려두세요.', emergency: '102 경찰 · 103 구급' },
    en: { name: 'Mongolia', capital: 'Ulaanbaatar', languages: 'Mongolian', currency: 'Tögrög',
      intro: 'The least densely populated country on earth: leave the capital and steppe gives way to the Gobi. The travel season is the short summer, June to August.',
      tip: 'The daily temperature swing is extreme — steppe nights drop below 10°C even in summer, so pack layers.',
      visa: '90 days visa-free for tourism. Coverage vanishes across much of the steppe, so download offline maps first.', emergency: '102 police · 103 ambulance' },
    zh: { name: '蒙古', capital: '乌兰巴托', languages: '蒙古语', currency: '图格里克',
      intro: '世界上人口密度最低的国家，出了首都便是草原与戈壁。旅游季集中在短暖的6至8月。',
      tip: '昼夜温差极大 — 即使夏天草原夜里也会降到10度以下，需要多层衣物。',
      visa: '韩国护照旅游可免签停留90天。草原大片区域没有信号，请提前下载离线地图。', emergency: '102 警察 · 103 急救' },
  },
  {
    slug: 'singapore', code: 'SG', icon: '🇸🇬', region: '동남아시아',
    utc: 8, tz: 'Asia/Singapore', dst: false, dial: '+65', volt: '230V', hz: '50Hz', plug: 'G',
    drive: 'left', currencyCode: 'SGD', tld: '.sg',     ko: { name: '싱가포르', capital: '싱가포르', languages: '영어, 중국어, 말레이어, 타밀어', currency: '싱가포르달러',
      intro: '도시 하나가 나라 전체인 곳으로, 적도 근처라 일 년 내내 낮과 밤 길이가 거의 같습니다. 영어가 행정 언어라 의사소통이 쉽습니다.',
      tip: '껌 판매, 대중교통 내 음식물, 지정 구역 밖 흡연에 실제로 벌금이 부과됩니다. 표지판을 눈여겨보세요.',
      visa: '관광 목적 90일 무비자. 입국 전 SG Arrival Card를 온라인으로 제출해야 합니다.', emergency: '999 경찰 · 995 구급' },
    en: { name: 'Singapore', capital: 'Singapore', languages: 'English, Chinese, Malay, Tamil', currency: 'Singapore dollar',
      intro: 'A single city that is also the whole country. Sitting near the equator, day and night stay nearly equal all year, and English as an administrative language makes it easy to navigate.',
      tip: 'Fines for selling gum, eating on public transport or smoking outside marked zones are actually enforced — read the signs.',
      visa: '90 days visa-free for tourism. You must file the SG Arrival Card online before entry.', emergency: '999 police · 995 ambulance' },
    zh: { name: '新加坡', capital: '新加坡', languages: '英语、华语、马来语、泰米尔语', currency: '新加坡元',
      intro: '一座城市就是整个国家。地处赤道附近，全年昼夜几乎等长；英语为行政语言，沟通十分方便。',
      tip: '售卖口香糖、在公共交通上进食、在非指定区域吸烟都会真的被罚款 — 请注意告示牌。',
      visa: '韩国护照旅游可免签停留90天。入境前须在线提交SG Arrival Card。', emergency: '999 警察 · 995 急救' },
  },
  {
    slug: 'philippines', code: 'PH', icon: '🇵🇭', region: '동남아시아',
    utc: 8, tz: 'Asia/Manila', dst: false, dial: '+63', volt: '220V', hz: '60Hz', plug: 'A, B, C',
    drive: 'right', currencyCode: 'PHP', tld: '.ph',     ko: { name: '필리핀', capital: '마닐라', languages: '필리핀어(타갈로그), 영어', currency: '페소',
      intro: '7천 개가 넘는 섬으로 이루어져 있어 목적지에 따라 국내선 이동이 필수입니다. 세부와 보라카이는 휴양지, 마닐라는 관문 도시 성격이 강합니다.',
      tip: '주파수가 60Hz라 한국 기기와 잘 맞고 플러그도 11자가 통합니다. 대신 전압이 220V라 미국 기기는 주의가 필요합니다.',
      visa: '관광 목적 30일 무비자. 입국 시 왕복 항공권을 요구하는 경우가 많습니다.', emergency: '911' },
    en: { name: 'Philippines', capital: 'Manila', languages: 'Filipino (Tagalog), English', currency: 'Peso',
      intro: 'Made up of more than 7,000 islands, so domestic flights are usually part of the plan. Cebu and Boracay are resort destinations; Manila functions mainly as the gateway.',
      tip: 'At 60 Hz with flat two-pin sockets, Korean devices fit well — but the 220 V supply needs care with US-market appliances.',
      visa: '30 days visa-free for tourism. A return ticket is commonly requested at immigration.', emergency: '911' },
    zh: { name: '菲律宾', capital: '马尼拉', languages: '菲律宾语(他加禄语)、英语', currency: '比索',
      intro: '由七千多个岛屿组成，因此国内航班通常是行程的一部分。宿务和长滩岛是度假地，马尼拉主要作为门户城市。',
      tip: '频率60Hz、插座为两枚扁脚，韩国电器很合用 — 但电压220V，美规电器需注意。',
      visa: '韩国护照旅游可免签停留30天。入境时常会要求出示回程机票。', emergency: '911' },
  },
];
