/** 나라 정보 - 동남아시아 (8) */
import type { Country } from './types.ts';

export const SOUTHEAST_ASIA: Country[] = [
  {
    slug: 'vietnam', code: 'VN', icon: '🇻🇳', region: '동남아시아',
    utc: 7, tz: 'Asia/Ho_Chi_Minh', dst: false, dial: '+84', volt: '220V', hz: '50Hz', plug: 'A, C, F',
    drive: 'right', currencyCode: 'VND', tld: '.vn',     ko: { name: '베트남', capital: '하노이', languages: '베트남어', currency: '동',
      intro: '남북으로 길어 같은 달에도 하노이는 서늘하고 호치민은 더울 수 있습니다. 한국보다 두 시간 느립니다.',
      tip: '지폐 단위가 커서 0을 세다 실수하기 쉽습니다. 1만 동과 10만 동은 색이 비슷해 특히 헷갈립니다.',
      visa: '관광 목적 45일 무비자. 체류 기간이 이를 넘으면 전자비자를 미리 받아야 합니다.', emergency: '113 경찰 · 115 구급' },
    en: { name: 'Vietnam', capital: 'Hanoi', languages: 'Vietnamese', currency: 'Dong',
      intro: 'Long from north to south, so Hanoi can be cool while Ho Chi Minh City is hot in the same month. It runs two hours behind Korea.',
      tip: 'The banknote denominations are large and easy to miscount — 10,000 and 100,000 dong look alike in colour.',
      visa: '45 days visa-free for tourism. Longer stays need an e-visa arranged in advance.', emergency: '113 police · 115 ambulance' },
  },
  {
    slug: 'thailand', code: 'TH', icon: '🇹🇭', region: '동남아시아',
    utc: 7, tz: 'Asia/Bangkok', dst: false, dial: '+66', volt: '220V', hz: '50Hz', plug: 'A, B, C',
    drive: 'left', currencyCode: 'THB', tld: '.th',     ko: { name: '태국', capital: '방콕', languages: '태국어', currency: '바트',
      intro: '건기(11~2월)와 우기(6~10월)가 뚜렷해 시기 선택이 여행 만족도를 크게 바꿉니다. 좌측통행이라 길을 건널 때 방향에 주의해야 합니다.',
      tip: '왕실에 대한 비하는 실제로 형사처벌 대상입니다. 사원에서는 어깨와 무릎을 가리는 옷차림이 요구됩니다.',
      visa: '관광 목적 90일 무비자. 입국 시 귀국 항공권 확인을 요구할 수 있습니다.', emergency: '191 경찰 · 1669 구급' },
    en: { name: 'Thailand', capital: 'Bangkok', languages: 'Thai', currency: 'Baht',
      intro: 'A sharp split between dry season (Nov–Feb) and monsoon (Jun–Oct) makes timing matter a lot. Traffic drives on the left, so check the other way when crossing.',
      tip: 'Insulting the monarchy is a criminal offence in practice. Temples require shoulders and knees covered.',
      visa: '90 days visa-free for tourism. Officers may ask to see an onward ticket.', emergency: '191 police · 1669 ambulance' },
  },
  {
    slug: 'malaysia', code: 'MY', icon: '🇲🇾', region: '동남아시아',
    utc: 8, tz: 'Asia/Kuala_Lumpur', dst: false, dial: '+60', volt: '240V', hz: '50Hz', plug: 'G',
    drive: 'left', currencyCode: 'MYR', tld: '.my',     ko: { name: '말레이시아', capital: '쿠알라룸푸르', languages: '말레이어, 영어, 중국어, 타밀어', currency: '링깃',
      intro: '말레이 반도와 보르네오섬으로 나뉘어 있어 코타키나발루는 국내선으로 두 시간 넘게 걸립니다. 이슬람 문화와 중국·인도계 문화가 함께 섞여 있습니다.',
      tip: '플러그가 영국식 G 타입입니다. 라마단 기간에는 낮 시간 식당 영업이 줄어드니 일정에 반영하세요.',
      visa: '관광 목적 90일 무비자. 입국 전 MDAC(디지털 입국 카드)를 온라인으로 제출해야 합니다.', emergency: '999' },
    en: { name: 'Malaysia', capital: 'Kuala Lumpur', languages: 'Malay, English, Chinese, Tamil', currency: 'Ringgit',
      intro: 'Split between the peninsula and Borneo, so Kota Kinabalu is more than two hours away by domestic flight. Malay, Chinese and Indian cultures sit side by side.',
      tip: 'Sockets are British type G. During Ramadan daytime restaurant hours shrink — plan around it.',
      visa: '90 days visa-free for tourism. The MDAC digital arrival card must be submitted online before entry.', emergency: '999' },
  },
  {
    slug: 'indonesia', code: 'ID', icon: '🇮🇩', region: '동남아시아',
    utc: 7, tz: 'Asia/Jakarta', dst: false, dial: '+62', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'left', currencyCode: 'IDR', tld: '.id',     ko: { name: '인도네시아', capital: '자카르타', languages: '인도네시아어', currency: '루피아',
      intro: '섬이 1만 7천 개가 넘고 시간대가 셋이라 자카르타(UTC+7)와 발리(UTC+8)의 시각이 다릅니다. 항공편 시간을 볼 때 현지 시간대를 꼭 확인하세요.',
      tip: '플러그가 유럽식 C·F 타입이라 한국 기기가 그대로 들어갑니다. 전압도 230V로 비슷합니다.',
      visa: '관광 목적 30일 무비자 또는 도착비자. 발리는 관광세를 별도로 납부해야 합니다.', emergency: '110 경찰 · 119 구급' },
    en: { name: 'Indonesia', capital: 'Jakarta', languages: 'Indonesian', currency: 'Rupiah',
      intro: 'More than 17,000 islands across three time zones, so Jakarta (UTC+7) and Bali (UTC+8) are not on the same clock. Always check which zone a flight time refers to.',
      tip: 'European type C and F sockets take Korean plugs directly, and 230 V is close enough to Korean voltage.',
      visa: '30 days visa-free or visa on arrival for tourism. Bali also charges a separate tourist levy.', emergency: '110 police · 119 ambulance' },
  },
  {
    slug: 'cambodia', code: 'KH', icon: '🇰🇭', region: '동남아시아',
    utc: 7, tz: 'Asia/Phnom_Penh', dst: false, dial: '+855', volt: '230V', hz: '50Hz', plug: 'A, C, G',
    drive: 'right', currencyCode: 'KHR', tld: '.kh',     ko: { name: '캄보디아', capital: '프놈펜', languages: '크메르어', currency: '리엘',
      intro: '앙코르와트가 있는 시엠레아프가 여행의 중심입니다. 유적 관람은 이른 아침이 덜 덥고 빛도 좋습니다.',
      tip: '미국 달러가 사실상 함께 통용되고 1달러 미만 거스름돈만 리엘로 받습니다. 낡거나 찢어진 달러 지폐는 거부될 수 있습니다.',
      visa: '전자비자 또는 도착비자가 필요합니다. 무비자 입국은 되지 않으니 미리 준비하세요.', emergency: '117 경찰 · 119 구급' },
    en: { name: 'Cambodia', capital: 'Phnom Penh', languages: 'Khmer', currency: 'Riel',
      intro: 'Siem Reap, home of Angkor Wat, anchors most trips. Early morning at the temples is cooler and the light is better.',
      tip: 'US dollars circulate alongside riel, with change under a dollar given in riel. Torn or worn dollar notes are often refused.',
      visa: 'An e-visa or visa on arrival is required — there is no visa-free entry, so arrange it in advance.', emergency: '117 police · 119 ambulance' },
  },
  {
    slug: 'laos', code: 'LA', icon: '🇱🇦', region: '동남아시아',
    utc: 7, tz: 'Asia/Vientiane', dst: false, dial: '+856', volt: '230V', hz: '50Hz', plug: 'A, B, C, E, F',
    drive: 'right', currencyCode: 'LAK', tld: '.la',     ko: { name: '라오스', capital: '비엔티안', languages: '라오어', currency: '킵',
      intro: '동남아에서 유일하게 바다가 없는 나라입니다. 루앙프라방의 사원과 방비엥의 강 풍경이 대표 코스이고, 중국까지 이어지는 고속철도가 이동을 크게 바꿨습니다.',
      tip: '플러그 형태가 여러 가지 섞여 있어 멀티 어댑터가 편합니다. 산악 도로 이동은 예상보다 시간이 걸립니다.',
      visa: '관광 목적 30일 무비자. 육로 국경으로 들어갈 때는 개방 시간을 미리 확인하세요.', emergency: '191 경찰 · 195 구급' },
    en: { name: 'Laos', capital: 'Vientiane', languages: 'Lao', currency: 'Kip',
      intro: 'The only landlocked country in Southeast Asia. Luang Prabang’s temples and the river scenery at Vang Vieng lead most itineraries, and the new railway to China has changed how people move.',
      tip: 'Several plug types are mixed in use, so a universal adapter helps. Mountain road journeys take longer than maps suggest.',
      visa: '30 days visa-free for tourism. If crossing by land, check the border post’s opening hours first.', emergency: '191 police · 195 ambulance' },
  },
  {
    slug: 'myanmar', code: 'MM', icon: '🇲🇲', region: '동남아시아',
    utc: 6.5, tz: 'Asia/Yangon', dst: false, dial: '+95', volt: '230V', hz: '50Hz', plug: 'C, D, F, G',
    drive: 'right', currencyCode: 'MMK', tld: '.mm',     ko: { name: '미얀마', capital: '네피도', languages: '미얀마어', currency: '짯',
      intro: '표준시가 UTC+6:30으로 30분 단위인 드문 나라입니다. 바간의 불탑 평원과 인레 호수가 대표적인 여행지입니다.',
      tip: '정세와 치안 상황에 따라 여행경보가 자주 바뀝니다. 출발 전 외교부 여행경보 단계를 반드시 확인하세요.',
      visa: '전자비자를 미리 받아야 합니다. 무비자 입국은 되지 않습니다.', emergency: '199 경찰 · 192 구급' },
    en: { name: 'Myanmar', capital: 'Naypyidaw', languages: 'Burmese', currency: 'Kyat',
      intro: 'One of the few countries on a half-hour offset, UTC+6:30. The pagoda plain at Bagan and Inle Lake are the best-known destinations.',
      tip: 'Travel advisories change often with the security situation — check your foreign ministry’s current advisory level before booking.',
      visa: 'An e-visa must be obtained in advance; there is no visa-free entry.', emergency: '199 police · 192 ambulance' },
  },
  {
    slug: 'brunei', code: 'BN', icon: '🇧🇳', region: '동남아시아',
    utc: 8, tz: 'Asia/Brunei', dst: false, dial: '+673', volt: '240V', hz: '50Hz', plug: 'G',
    drive: 'left', currencyCode: 'BND', tld: '.bn',     ko: { name: '브루나이', capital: '반다르스리브가완', languages: '말레이어, 영어', currency: '브루나이달러',
      intro: '보르네오섬 북부의 작은 산유국으로, 이슬람 율법이 엄격하게 적용됩니다. 수도의 모스크와 수상 마을이 주요 볼거리입니다.',
      tip: '술 판매가 금지돼 있습니다. 외국인은 소량 반입이 허용되지만 반드시 세관에 신고해야 합니다.',
      visa: '관광 목적 30일 무비자. 싱가포르달러가 1:1로 통용됩니다.', emergency: '993 경찰 · 991 구급' },
    en: { name: 'Brunei', capital: 'Bandar Seri Begawan', languages: 'Malay, English', currency: 'Brunei dollar',
      intro: 'A small oil state on northern Borneo where Islamic law is strictly applied. The capital’s mosques and its water village are the main sights.',
      tip: 'Alcohol sales are banned. Visitors may bring in a small allowance but must declare it at customs.',
      visa: '30 days visa-free for tourism. Singapore dollars circulate at par.', emergency: '993 police · 991 ambulance' },
  },
];
