/** 나라 정보 - 서·남아시아 둘째 묶음 (10) */
import type { Country } from './types.ts';

export const WEST_ASIA2: Country[] = [
  {
    slug: 'maldives', code: 'MV', icon: '🇲🇻', region: '서·남아시아',
    utc: 5, tz: 'Indian/Maldives', dst: false, dial: '+960', volt: '230V', hz: '50Hz', plug: 'D, G',
    drive: 'left', currencyCode: 'MVR', tld: '.mv',
    ko: { name: '몰디브', capital: '말레', languages: '디베히어, 영어', currency: '루피야',
      intro: '1,190개가 넘는 산호섬이 26개 환초로 흩어져 있고, 리조트 하나가 섬 하나를 쓰는 구조가 흔합니다. 수도 말레 공항에서 리조트까지 스피드보트나 수상비행기로 갈아타야 합니다.',
      tip: '수상비행기는 낮에만 뜨므로 오후 늦게 도착하는 항공편은 말레에서 1박이 생깁니다. 도착 시각을 먼저 정하고 항공권을 잡는 편이 낫습니다.',
      visa: '도착 시 30일 무료 관광비자를 받습니다. 출발 전 IMUGA 온라인 신고서를 미리 제출해 두면 입국이 빠릅니다.', emergency: '119 경찰 · 102 구급' },
    en: { name: 'Maldives', capital: 'Malé', languages: 'Dhivehi, English', currency: 'Rufiyaa',
      intro: 'More than 1,190 coral islands scatter across 26 atolls, and one resort to one island is the usual arrangement. From Malé airport you transfer to the resort by speedboat or seaplane.',
      tip: 'Seaplanes only fly in daylight, so a late arrival means an overnight stay in Malé. Fix your arrival time before booking the flight.',
      visa: 'A free 30-day tourist visa is issued on arrival. Filing the IMUGA declaration online beforehand speeds up entry.', emergency: '119 police · 102 ambulance' },
  },
  {
    slug: 'bangladesh', code: 'BD', icon: '🇧🇩', region: '서·남아시아',
    utc: 6, tz: 'Asia/Dhaka', dst: false, dial: '+880', volt: '220V', hz: '50Hz', plug: 'C, D, G, K',
    drive: 'left', currencyCode: 'BDT', tld: '.bd',
    ko: { name: '방글라데시', capital: '다카', languages: '벵골어, 영어', currency: '타카',
      intro: '갠지스강 삼각주에 자리해 국토 대부분이 평지이고 강이 교통의 축입니다. 세계에서 가장 인구 밀도가 높은 나라 가운데 하나로 다카의 릭샤 물결이 인상적입니다.',
      tip: '6월부터 9월까지 몬순으로 국토 상당 부분이 잠깁니다. 여행은 건기인 11월에서 2월이 훨씬 수월합니다.',
      visa: '사전 비자가 필요하며 도착비자도 조건부로 운영됩니다. 조건이 자주 바뀌므로 출발 전 대사관 공지를 확인하세요.', emergency: '999' },
    en: { name: 'Bangladesh', capital: 'Dhaka', languages: 'Bengali, English', currency: 'Taka',
      intro: 'Sitting on the Ganges delta, the country is almost entirely flat and rivers carry much of its traffic. It is among the most densely populated nations on earth, and Dhaka’s tide of rickshaws shows it.',
      tip: 'Monsoon floods large parts of the country from June to September. Travel is far easier in the dry season, November to February.',
      visa: 'A visa is required in advance, with visa-on-arrival available under conditions that change often — check the embassy before you fly.', emergency: '999' },
  },
  {
    slug: 'pakistan', code: 'PK', icon: '🇵🇰', region: '서·남아시아',
    utc: 5, tz: 'Asia/Karachi', dst: false, dial: '+92', volt: '230V', hz: '50Hz', plug: 'C, D',
    drive: 'left', currencyCode: 'PKR', tld: '.pk',
    ko: { name: '파키스탄', capital: '이슬라마바드', languages: '우르두어, 영어', currency: '루피',
      intro: '북부에 카라코람과 힌두쿠시가 겹쳐 8,000m급 봉우리 다섯 개가 몰려 있습니다. K2로 가는 길목인 훈자와 스카르두가 트레킹 여행의 중심입니다.',
      tip: '북부 산악 도로는 5월에서 10월에만 열립니다. 그 밖의 계절에는 카라코람 하이웨이 구간이 눈으로 막힙니다.',
      visa: '온라인 비자(e-Visa)를 미리 받아야 합니다. 산악 지역은 별도 허가가 필요한 구간이 있어 현지 여행사를 통하는 편이 안전합니다.', emergency: '15 경찰 · 1122 구급' },
    en: { name: 'Pakistan', capital: 'Islamabad', languages: 'Urdu, English', currency: 'Rupee',
      intro: 'In the north the Karakoram and Hindu Kush overlap, crowding five peaks above 8,000 m into one region. Hunza and Skardu, on the road towards K2, anchor most trekking trips.',
      tip: 'Mountain roads in the north open only from May to October; outside that window sections of the Karakoram Highway are closed by snow.',
      visa: 'An e-Visa must be obtained in advance. Some mountain areas need separate permits, so going through a local operator is safer.', emergency: '15 police · 1122 ambulance' },
  },
  {
    slug: 'bhutan', code: 'BT', icon: '🇧🇹', region: '서·남아시아',
    utc: 6, tz: 'Asia/Thimphu', dst: false, dial: '+975', volt: '230V', hz: '50Hz', plug: 'D, F, G',
    drive: 'left', currencyCode: 'BTN', tld: '.bt',
    ko: { name: '부탄', capital: '팀부', languages: '종카어, 영어', currency: '눌트룸',
      intro: '히말라야 동쪽 끝에 있는 작은 왕국으로 국토 60% 이상을 숲으로 유지하도록 헌법에 못 박아 두었습니다. 절벽에 붙은 탁상 사원(파로 탁상)이 대표적인 목적지입니다.',
      tip: '입국하면 하루 단위로 관광지속가능기금을 냅니다. 자유 배낭여행이 사실상 불가능해 일정과 예산을 미리 확정해야 합니다.',
      visa: '비자와 함께 하루 단위 관광세를 내야 하며, 승인된 현지 여행사를 통해 신청합니다. 금액과 조건이 개정되므로 최신 공고를 확인하세요.', emergency: '113 경찰 · 112 구급' },
    en: { name: 'Bhutan', capital: 'Thimphu', languages: 'Dzongkha, English', currency: 'Ngultrum',
      intro: 'A small kingdom at the eastern end of the Himalaya, Bhutan writes a minimum of 60% forest cover into its constitution. The cliffside Tiger’s Nest monastery near Paro is the signature destination.',
      tip: 'Visitors pay a Sustainable Development Fee for every night of their stay. Independent backpacking is effectively impossible, so fix the itinerary and budget first.',
      visa: 'A visa plus a nightly tourism levy are required, applied for through an approved local operator. Rates and conditions get revised, so check the current notice.', emergency: '113 police · 112 ambulance' },
  },
  {
    slug: 'kazakhstan', code: 'KZ', icon: '🇰🇿', region: '서·남아시아',
    utc: 5, tz: 'Asia/Almaty', dst: false, dial: '+7', volt: '220V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'KZT', tld: '.kz',
    ko: { name: '카자흐스탄', capital: '아스타나', languages: '카자흐어, 러시아어', currency: '텡게',
      intro: '세계에서 아홉 번째로 넓은 나라이면서 바다와 닿지 않는 내륙국 가운데 가장 큽니다. 2024년부터 전국이 UTC+5 하나로 통일돼 시차 계산이 단순해졌습니다.',
      tip: '아스타나의 겨울은 영하 30도까지 내려가 세계에서 가장 추운 수도로 꼽힙니다. 알마티는 훨씬 온화해 계절에 따라 목적지를 나누는 편이 좋습니다.',
      visa: '관광 목적 30일 무비자로 알려져 있으나 조건이 개정됩니다. 출발 전 최신 공지를 확인하세요.', emergency: '112' },
    en: { name: 'Kazakhstan', capital: 'Astana', languages: 'Kazakh, Russian', currency: 'Tenge',
      intro: 'The ninth-largest country on earth and the largest landlocked one. Since 2024 the whole country runs on a single time zone, UTC+5, which simplifies planning.',
      tip: 'Astana drops to −30 °C in winter and ranks among the coldest capitals anywhere. Almaty is far milder, so pick the city to suit the season.',
      visa: 'Thirty days visa-free for tourism has applied, but conditions are revised — confirm the current notice before departure.', emergency: '112' },
  },
  {
    slug: 'georgia', code: 'GE', icon: '🇬🇪', region: '서·남아시아',
    utc: 4, tz: 'Asia/Tbilisi', dst: false, dial: '+995', volt: '220V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'GEL', tld: '.ge',
    ko: { name: '조지아', capital: '트빌리시', languages: '조지아어', currency: '라리',
      intro: '캅카스 산맥 남쪽에 있어 유럽과 아시아 어느 쪽으로도 분류되는 나라입니다. 8,000년 된 항아리(크베브리) 와인 양조법이 유네스코에 등재돼 있습니다.',
      tip: '고유 문자인 조지아 문자를 써서 간판을 읽기 어렵습니다. 다만 관광지에서는 영어와 러시아어가 통하는 편입니다.',
      visa: '관광 목적으로 최대 1년까지 무비자 체류가 가능한 것으로 알려져 있습니다. 조건은 출발 전 확인하세요.', emergency: '112' },
    en: { name: 'Georgia', capital: 'Tbilisi', languages: 'Georgian', currency: 'Lari',
      intro: 'South of the Caucasus range, Georgia gets classified as European or Asian depending on who is counting. Its 8,000-year-old qvevri winemaking tradition is UNESCO-listed.',
      tip: 'The Georgian alphabet is unique, which makes signage hard to read, though English and Russian get you by in tourist areas.',
      visa: 'Visa-free stays of up to a year have applied for tourism. Confirm the conditions before travelling.', emergency: '112' },
  },
  {
    slug: 'israel', code: 'IL', icon: '🇮🇱', region: '서·남아시아',
    utc: 2, tz: 'Asia/Jerusalem', dst: true, dial: '+972', volt: '230V', hz: '50Hz', plug: 'C, H, M',
    drive: 'right', currencyCode: 'ILS', tld: '.il',
    ko: { name: '이스라엘', capital: '(예루살렘·논쟁 중)', languages: '히브리어, 아랍어', currency: '셰켈',
      intro: '지중해와 사해 사이 좁은 국토에 유대교·기독교·이슬람의 성지가 겹쳐 있습니다. 사해는 해수면보다 430m 낮아 지구에서 가장 낮은 육지입니다.',
      tip: '금요일 해가 지면서 토요일 저녁까지 안식일(샤바트)이라 대중교통과 상점이 멈춥니다. 주말 일정은 이 점을 먼저 넣고 짜야 합니다.',
      visa: '관광 목적 90일 무비자로 알려져 있습니다. 정세에 따라 입국 절차가 달라지므로 출발 전 외교부 안전 공지를 확인하세요.', emergency: '100 경찰 · 101 구급' },
    en: { name: 'Israel', capital: '(Jerusalem — disputed)', languages: 'Hebrew, Arabic', currency: 'Shekel',
      intro: 'Between the Mediterranean and the Dead Sea, holy sites of Judaism, Christianity and Islam overlap in a narrow strip of land. The Dead Sea shore, 430 m below sea level, is the lowest land on earth.',
      tip: 'Shabbat runs from Friday sunset to Saturday evening, and public transport and shops stop. Build weekend plans around it first.',
      visa: 'Ninety days visa-free has applied for tourism. Entry procedures shift with the security situation, so check your foreign ministry’s advisory.', emergency: '100 police · 101 ambulance' },
  },
  {
    slug: 'jordan', code: 'JO', icon: '🇯🇴', region: '서·남아시아',
    utc: 3, tz: 'Asia/Amman', dst: false, dial: '+962', volt: '230V', hz: '50Hz', plug: 'B, C, D, F, G, J',
    drive: 'right', currencyCode: 'JOD', tld: '.jo',
    ko: { name: '요르단', capital: '암만', languages: '아랍어', currency: '디나르',
      intro: '바위를 깎아 만든 고대 도시 페트라와 화성처럼 붉은 와디룸 사막이 대표 목적지입니다. 2022년부터 서머타임을 폐지하고 연중 UTC+3을 씁니다.',
      tip: '요르단 패스를 미리 사면 페트라 입장료와 관광비자 수수료가 함께 면제됩니다. 최소 3박 이상 체류가 조건입니다.',
      visa: '사전 비자 또는 요르단 패스가 필요합니다. 조건과 금액이 개정되므로 출발 전 확인하세요.', emergency: '911' },
    en: { name: 'Jordan', capital: 'Amman', languages: 'Arabic', currency: 'Dinar',
      intro: 'Petra, carved out of rock, and the Mars-red desert of Wadi Rum are the headline destinations. Jordan abolished daylight saving in 2022 and now stays on UTC+3 all year.',
      tip: 'Buying a Jordan Pass in advance covers Petra entry and waives the tourist visa fee, provided you stay at least three nights.',
      visa: 'A visa in advance or a Jordan Pass is required. Terms and fees get revised, so check before departure.', emergency: '911' },
  },
  {
    slug: 'qatar', code: 'QA', icon: '🇶🇦', region: '서·남아시아',
    utc: 3, tz: 'Asia/Qatar', dst: false, dial: '+974', volt: '240V', hz: '50Hz', plug: 'D, G',
    drive: 'right', currencyCode: 'QAR', tld: '.qa',
    ko: { name: '카타르', capital: '도하', languages: '아랍어, 영어', currency: '리얄',
      intro: '페르시아만으로 튀어나온 반도 국가로 국토가 경기도보다 조금 큽니다. 도하 하마드 공항이 환승 거점이라 스톱오버 여행지로 많이 쓰입니다.',
      tip: '여름 기온이 45도를 넘어 야외 활동이 어렵습니다. 11월에서 3월이 여행에 적당한 시기입니다.',
      visa: '관광 목적 30일 무비자로 알려져 있습니다. 환승 여객을 위한 별도 제도가 있으므로 항공사 안내도 함께 확인하세요.', emergency: '999' },
    en: { name: 'Qatar', capital: 'Doha', languages: 'Arabic, English', currency: 'Riyal',
      intro: 'A peninsula jutting into the Persian Gulf, Qatar is a small country with an outsized transit role — Hamad airport in Doha makes it a common stopover destination.',
      tip: 'Summer temperatures pass 45 °C and rule out most outdoor plans. November to March is the workable window.',
      visa: 'Thirty days visa-free has applied for tourism, and separate schemes exist for transit passengers — check with your airline too.', emergency: '999' },
  },
  {
    slug: 'saudi-arabia', code: 'SA', icon: '🇸🇦', region: '서·남아시아',
    utc: 3, tz: 'Asia/Riyadh', dst: false, dial: '+966', volt: '230V', hz: '60Hz', plug: 'G',
    drive: 'right', currencyCode: 'SAR', tld: '.sa',
    ko: { name: '사우디아라비아', capital: '리야드', languages: '아랍어', currency: '리얄',
      intro: '아라비아 반도의 대부분을 차지하며 2019년부터 관광 비자를 열었습니다. 나바테아 유적이 있는 알울라와 홍해 연안이 새 관광 축입니다.',
      tip: '주파수가 60Hz라 중동에서 드문 경우입니다. 220V·50Hz 전용 기기는 확인이 필요합니다.',
      visa: '온라인 관광비자(e-Visa)를 받을 수 있습니다. 메카·메디나 성지는 무슬림만 출입할 수 있습니다.', emergency: '911' },
    en: { name: 'Saudi Arabia', capital: 'Riyadh', languages: 'Arabic', currency: 'Riyal',
      intro: 'Covering most of the Arabian peninsula, Saudi Arabia opened to tourist visas in 2019. AlUla, with its Nabataean ruins, and the Red Sea coast are the new focus.',
      tip: 'Mains frequency is 60 Hz, unusual for the region, so check any appliance built strictly for 220 V at 50 Hz.',
      visa: 'An online tourist e-Visa is available. Mecca and Medina are open only to Muslims.', emergency: '911' },
  },
];
