/** 나라 정보 - 유럽 북·동·남부 (8) */
import type { Country } from './types.ts';

export const NORTH_EUROPE: Country[] = [
  {
    slug: 'czechia', code: 'CZ', icon: '🇨🇿', region: '유럽',
    utc: 1, tz: 'Europe/Prague', dst: true, dial: '+420', volt: '230V', hz: '50Hz', plug: 'C, E',
    drive: 'right', currencyCode: 'CZK', tld: '.cz',     ko: { name: '체코', capital: '프라하', languages: '체코어', currency: '코루나',
      intro: '유럽연합 회원국이지만 유로가 아니라 코루나를 씁니다. 프라하 구시가는 도보로 대부분 둘러볼 수 있는 크기입니다.',
      tip: '길거리 환전소의 환율 표시가 실제 적용 환율과 다른 경우가 있습니다. 은행이나 ATM을 쓰는 편이 안전합니다.',
      visa: '셰넨 협정에 따라 180일 중 90일 무비자. 유로를 받는 곳은 환율이 불리한 편입니다.', emergency: '112' },
    en: { name: 'Czechia', capital: 'Prague', languages: 'Czech', currency: 'Koruna',
      intro: 'An EU member that keeps its own koruna rather than the euro. Prague’s old town is compact enough to cover on foot.',
      tip: 'Street exchange booths sometimes post rates that differ from what they actually apply — banks or ATMs are safer.',
      visa: '90 days in any 180 under the Schengen rules. Places that accept euros tend to use poor rates.', emergency: '112' },
    zh: { name: '捷克', capital: '布拉格', languages: '捷克语', currency: '克朗',
      intro: '虽是欧盟成员国，但使用本国克朗而非欧元。布拉格老城范围紧凑，步行即可逛遍。',
      tip: '街边兑换点标示的汇率有时与实际结算不符 — 用银行或ATM更稳妥。',
      visa: '依申根规定，每180天可免签90天。接受欧元的场所汇率通常较差。', emergency: '112' },
  },
  {
    slug: 'portugal', code: 'PT', icon: '🇵🇹', region: '유럽',
    utc: 0, tz: 'Europe/Lisbon', dst: true, dial: '+351', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'EUR', tld: '.pt',     ko: { name: '포르투갈', capital: '리스본', languages: '포르투갈어', currency: '유로',
      intro: '유럽 본토 서쪽 끝이라 스페인과 붙어 있으면서도 시차가 한 시간 납니다. 리스본과 포르투가 여행의 두 축입니다.',
      tip: '스페인에서 국경을 넘으면 시계를 한 시간 되돌려야 합니다. 열차·버스 시각을 볼 때 특히 주의하세요.',
      visa: '셰넨 협정에 따라 180일 중 90일 무비자. 리스본 트램 28번은 소매치기 신고가 잦습니다.', emergency: '112' },
    en: { name: 'Portugal', capital: 'Lisbon', languages: 'Portuguese', currency: 'Euro',
      intro: 'The western edge of mainland Europe: it borders Spain yet sits an hour behind it. Lisbon and Porto are the two poles of most itineraries.',
      tip: 'Crossing from Spain means setting your watch back an hour — watch out when reading train and bus times.',
      visa: '90 days in any 180 under the Schengen rules. Lisbon’s tram 28 draws frequent pickpocket reports.', emergency: '112' },
    zh: { name: '葡萄牙', capital: '里斯本', languages: '葡萄牙语', currency: '欧元',
      intro: '欧洲大陆最西端，与西班牙相邻却相差一小时。里斯本和波尔图是行程的两大支点。',
      tip: '从西班牙跨境要把表往回调一小时 — 看火车和巴士时刻时尤需注意。',
      visa: '依申根规定，每180天可免签90天。里斯本28路电车扒窃报案较多。', emergency: '112' },
  },
  {
    slug: 'greece', code: 'GR', icon: '🇬🇷', region: '유럽',
    utc: 2, tz: 'Europe/Athens', dst: true, dial: '+30', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'EUR', tld: '.gr',     ko: { name: '그리스', capital: '아테네', languages: '그리스어', currency: '유로',
      intro: '아테네의 고대 유적과 산토리니·미코노스 같은 섬이 서로 다른 여행 성격을 갖습니다. 섬 이동은 페리가 기본이고 여름에는 좌석이 빨리 찹니다.',
      tip: '여름 한낮 유적 관람은 그늘이 거의 없어 힘듭니다. 아크로폴리스는 개장 직후나 늦은 오후가 낫습니다.',
      visa: '셰넨 협정에 따라 180일 중 90일 무비자. 페리는 기상에 따라 결항이 있어 일정에 여유가 필요합니다.', emergency: '112' },
    en: { name: 'Greece', capital: 'Athens', languages: 'Greek', currency: 'Euro',
      intro: 'Ancient Athens and islands like Santorini and Mykonos make for two different holidays. Ferries are the way between islands, and summer sailings fill up fast.',
      tip: 'Midday at the ruins in summer is punishing — there is almost no shade. Visit the Acropolis right at opening or late afternoon.',
      visa: '90 days in any 180 under the Schengen rules. Ferries get cancelled in bad weather, so keep slack in the plan.', emergency: '112' },
    zh: { name: '希腊', capital: '雅典', languages: '希腊语', currency: '欧元',
      intro: '雅典的古代遗址与圣托里尼、米科诺斯等海岛是两种不同的旅行。岛际交通主要靠渡轮，夏季船票很快售罄。',
      tip: '夏季正午看遗址非常难熬，几乎没有遮荫。参观雅典卫城最好在刚开门时或傍晚。',
      visa: '依申根规定，每180天可免签90天。渡轮遇恶劣天气会停航，行程需留余量。', emergency: '112' },
  },
  {
    slug: 'poland', code: 'PL', icon: '🇵🇱', region: '유럽',
    utc: 1, tz: 'Europe/Warsaw', dst: true, dial: '+48', volt: '230V', hz: '50Hz', plug: 'C, E',
    drive: 'right', currencyCode: 'PLN', tld: '.pl',     ko: { name: '폴란드', capital: '바르샤바', languages: '폴란드어', currency: '즈워티',
      intro: '유럽연합 회원국이지만 유로가 아니라 즈워티를 씁니다. 크라쿠프 구시가와 아우슈비츠 추모관이 대표적인 방문지입니다.',
      tip: '물가가 서유럽보다 낮아 같은 예산으로 더 오래 머물 수 있습니다. 아우슈비츠는 무료 입장이라도 사전 예약이 필요합니다.',
      visa: '셰넨 협정에 따라 180일 중 90일 무비자.', emergency: '112' },
    en: { name: 'Poland', capital: 'Warsaw', languages: 'Polish', currency: 'Złoty',
      intro: 'An EU member that uses the złoty rather than the euro. Kraków’s old town and the Auschwitz memorial are the best-known destinations.',
      tip: 'Prices sit below Western Europe, so a given budget stretches further. Auschwitz requires advance booking even for free entry.',
      visa: '90 days in any 180 under the Schengen rules.', emergency: '112' },
    zh: { name: '波兰', capital: '华沙', languages: '波兰语', currency: '兹罗提',
      intro: '欧盟成员国，但使用兹罗提而非欧元。克拉科夫老城与奥斯维辛纪念馆是最知名的目的地。',
      tip: '物价低于西欧，同样预算可以待更久。奥斯维辛即使免费入场也需提前预约。',
      visa: '依申根规定，每180天可免签90天。', emergency: '112' },
  },
  {
    slug: 'sweden', code: 'SE', icon: '🇸🇪', region: '유럽',
    utc: 1, tz: 'Europe/Stockholm', dst: true, dial: '+46', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'SEK', tld: '.se',     ko: { name: '스웨덴', capital: '스톡홀름', languages: '스웨덴어', currency: '스웨덴크로나',
      intro: '유럽연합 회원국이지만 유로가 아니라 크로나를 씁니다. 현금 사용이 극히 적어 카드나 모바일 결제 없이는 불편한 곳이 많습니다.',
      tip: '현금을 아예 받지 않는 가게와 박물관이 있습니다. 해외 결제가 되는 카드를 두 장 이상 준비하세요.',
      visa: '셰넨 협정에 따라 180일 중 90일 무비자. 겨울에는 오후 3시면 어두워집니다.', emergency: '112' },
    en: { name: 'Sweden', capital: 'Stockholm', languages: 'Swedish', currency: 'Swedish krona',
      intro: 'An EU member outside the eurozone, using the krona. Cash has almost disappeared, so getting by without a card or mobile payment is awkward.',
      tip: 'Some shops and museums refuse cash outright — bring at least two cards that work abroad.',
      visa: '90 days in any 180 under the Schengen rules. In winter it is dark by 3 pm.', emergency: '112' },
    zh: { name: '瑞典', capital: '斯德哥尔摩', languages: '瑞典语', currency: '瑞典克朗',
      intro: '欧盟成员国但不属欧元区，使用克朗。现金使用极少，没有银行卡或手机支付会很不方便。',
      tip: '有些商店和博物馆完全不收现金 — 请准备两张以上可境外使用的卡。',
      visa: '依申根规定，每180天可免签90天。冬季下午3点天就黑了。', emergency: '112' },
  },
  {
    slug: 'norway', code: 'NO', icon: '🇳🇴', region: '유럽',
    utc: 1, tz: 'Europe/Oslo', dst: true, dial: '+47', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'NOK', tld: '.no',     ko: { name: '노르웨이', capital: '오슬로', languages: '노르웨이어', currency: '노르웨이크로네',
      intro: '유럽연합 회원국이 아니지만 셰넨 협정에는 가입해 있습니다. 피오르와 오로라가 여행의 두 축이고 물가가 유럽에서 가장 높은 편입니다.',
      tip: '오로라는 9월부터 3월 사이, 트롬쇠처럼 위도가 높은 곳에서 볼 확률이 높습니다. 며칠 여유를 두는 편이 좋습니다.',
      visa: '셰넨 협정에 따라 180일 중 90일 무비자. 외식 물가가 높아 마트를 활용하면 예산이 크게 줄어듭니다.', emergency: '112 경찰 · 113 구급' },
    en: { name: 'Norway', capital: 'Oslo', languages: 'Norwegian', currency: 'Norwegian krone',
      intro: 'Not an EU member, but part of the Schengen Area. Fjords and the aurora are the two draws, and prices are among the highest in Europe.',
      tip: 'Aurora season runs September to March and odds improve at high latitudes like Tromsø — allow several nights.',
      visa: '90 days in any 180 under the Schengen rules. Eating out is expensive; supermarkets cut the budget sharply.', emergency: '112 police · 113 ambulance' },
    zh: { name: '挪威', capital: '奥斯陆', languages: '挪威语', currency: '挪威克朗',
      intro: '不是欧盟成员国，但属于申根区。峡湾与极光是两大看点，物价在欧洲属最高之列。',
      tip: '极光季为9月至次年3月，在特罗姆瑟等高纬度地区概率更高 — 建议多留几晚。',
      visa: '依申根规定，每180天可免签90天。外出就餐昂贵，多利用超市可大幅省钱。', emergency: '112 警察 · 113 急救' },
  },
  {
    slug: 'denmark', code: 'DK', icon: '🇩🇰', region: '유럽',
    utc: 1, tz: 'Europe/Copenhagen', dst: true, dial: '+45', volt: '230V', hz: '50Hz', plug: 'C, E, F, K',
    drive: 'right', currencyCode: 'DKK', tld: '.dk',     ko: { name: '덴마크', capital: '코펜하겐', languages: '덴마크어', currency: '덴마크크로네',
      intro: '유럽연합 회원국이지만 유로가 아니라 크로네를 씁니다. 코펜하겐은 자전거 통행 비중이 높아 도심 이동이 자전거로 빠릅니다.',
      tip: '플러그에 덴마크 전용 K 타입이 섞여 있습니다. 둥근 두 핀은 대개 들어가지만 접지가 필요한 기기는 확인이 필요합니다.',
      visa: '셰넨 협정에 따라 180일 중 90일 무비자. 스웨덴 말뫼까지 열차로 40분이면 갑니다.', emergency: '112' },
    en: { name: 'Denmark', capital: 'Copenhagen', languages: 'Danish', currency: 'Danish krone',
      intro: 'An EU member that keeps the krone rather than the euro. Copenhagen’s cycling share is high enough that a bike is the fastest way across the centre.',
      tip: 'The Danish type K socket is mixed in. Round two-pin plugs usually fit, but check anything that needs an earth connection.',
      visa: '90 days in any 180 under the Schengen rules. Malmö in Sweden is 40 minutes away by train.', emergency: '112' },
    zh: { name: '丹麦', capital: '哥本哈根', languages: '丹麦语', currency: '丹麦克朗',
      intro: '欧盟成员国，但保留克朗而非欧元。哥本哈根骑行比例很高，市中心用自行车反而最快。',
      tip: '插座混有丹麦专用K型。圆形两脚一般能插，但需要接地的电器要先确认。',
      visa: '依申根规定，每180天可免签90天。乘火车40分钟即可到瑞典马尔默。', emergency: '112' },
  },
  {
    slug: 'finland', code: 'FI', icon: '🇫🇮', region: '유럽',
    utc: 2, tz: 'Europe/Helsinki', dst: true, dial: '+358', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'EUR', tld: '.fi',     ko: { name: '핀란드', capital: '헬싱키', languages: '핀란드어, 스웨덴어', currency: '유로',
      intro: '북유럽에서 유로를 쓰는 유일한 나라입니다. 라플란드의 오로라와 사우나 문화가 대표적이고, 여름에는 밤에도 해가 지지 않는 백야가 있습니다.',
      tip: '겨울 라플란드는 영하 20도 아래로 내려갑니다. 방한화와 여러 겹 옷차림이 필수입니다.',
      visa: '셰넨 협정에 따라 180일 중 90일 무비자. 헬싱키에서 탈린(에스토니아)까지 페리로 두 시간입니다.', emergency: '112' },
    en: { name: 'Finland', capital: 'Helsinki', languages: 'Finnish, Swedish', currency: 'Euro',
      intro: 'The only Nordic country on the euro. Lapland’s aurora and sauna culture lead the list, and midsummer brings nights where the sun never sets.',
      tip: 'Lapland drops below −20°C in winter — insulated boots and proper layering are not optional.',
      visa: '90 days in any 180 under the Schengen rules. Tallinn in Estonia is a two-hour ferry from Helsinki.', emergency: '112' },
    zh: { name: '芬兰', capital: '赫尔辛基', languages: '芬兰语、瑞典语', currency: '欧元',
      intro: '北欧唯一使用欧元的国家。拉普兰的极光和桑拿文化最具代表性，仲夏时节还有太阳不落的白夜。',
      tip: '冬季拉普兰会降到零下20度以下 — 保暖靴和多层穿着是必需的。',
      visa: '依申根规定，每180天可免签90天。从赫尔辛基乘渡轮两小时可达爱沙尼亚塔林。', emergency: '112' },
  },
];
