/** 나라 정보 - 유럽 중부·동남부 (10) */
import type { Country } from './types.ts';

export const CENTRAL_EUROPE: Country[] = [
  {
    slug: 'belgium', code: 'BE', icon: '🇧🇪', region: '유럽',
    utc: 1, tz: 'Europe/Brussels', dst: true, dial: '+32', volt: '230V', hz: '50Hz', plug: 'C, E',
    drive: 'right', currencyCode: 'EUR', tld: '.be',
    ko: { name: '벨기에', capital: '브뤼셀', languages: '네덜란드어, 프랑스어, 독일어', currency: '유로',
      intro: '북부는 네덜란드어, 남부는 프랑스어를 써서 도시 이름이 두 가지로 불립니다. 브뤼셀에 유럽연합과 나토 본부가 있어 유럽의 행정 중심으로 통합니다.',
      tip: '플러그가 E 타입이라 구멍 옆에 핀이 하나 튀어나옵니다. C 타입 어댑터도 꽂히지만 접지가 안 되니 노트북은 확인하세요.',
      visa: '솅겐 협정 국가로 180일 중 90일 무비자입니다. ETIAS 사전 승인 제도가 도입 예정이므로 출발 전 확인하세요.', emergency: '112' },
    en: { name: 'Belgium', capital: 'Brussels', languages: 'Dutch, French, German', currency: 'Euro',
      intro: 'Dutch in the north and French in the south means many cities carry two names. Brussels hosts both the EU and NATO headquarters, making it Europe’s administrative centre.',
      tip: 'Sockets are type E, with a protruding earth pin. A type C adapter fits but gives no earth, so check anything with a metal chassis.',
      visa: 'A Schengen state: 90 days in any 180 visa-free. ETIAS pre-authorisation is being introduced, so check before travelling.', emergency: '112' },
    zh: { name: '比利时', capital: '布鲁塞尔', languages: '荷兰语、法语、德语', currency: '欧元',
      intro: '北部说荷兰语、南部说法语，许多城市因此有两个名字。布鲁塞尔同时设有欧盟与北约总部，被视为欧洲的行政中心。',
      tip: '插座为E型，孔旁有一根突出的接地针。C型转换头能插入但无接地，金属外壳的设备需注意。',
      visa: '申根国家，180天内可免签停留90天。ETIAS预先授权制度即将实施，出发前请确认。', emergency: '112' },
  },
  {
    slug: 'ireland', code: 'IE', icon: '🇮🇪', region: '유럽',
    utc: 0, tz: 'Europe/Dublin', dst: true, dial: '+353', volt: '230V', hz: '50Hz', plug: 'G',
    drive: 'left', currencyCode: 'EUR', tld: '.ie',
    ko: { name: '아일랜드', capital: '더블린', languages: '영어, 아일랜드어', currency: '유로',
      intro: '섬 북동쪽 북아일랜드는 영국 영토이고 나머지가 아일랜드 공화국입니다. 통화는 유로지만 통행은 영국처럼 좌측이고 플러그도 영국식 G 타입입니다.',
      tip: '북아일랜드로 넘어가면 통화가 파운드로 바뀝니다. 국경에 검문소가 없어 넘어간 것을 모르고 결제하다 당황하는 경우가 있습니다.',
      visa: '솅겐에 속하지 않아 별도 규정을 씁니다. 관광 목적 90일 무비자로 알려져 있으니 조건은 출발 전 확인하세요.', emergency: '112 또는 999' },
    en: { name: 'Ireland', capital: 'Dublin', languages: 'English, Irish', currency: 'Euro',
      intro: 'Northern Ireland in the island’s north-east belongs to the UK; the rest is the Republic. The currency is the euro, but traffic drives on the left and plugs are the British type G.',
      tip: 'Cross into Northern Ireland and the currency becomes sterling. There is no border post, so people often only notice at the till.',
      visa: 'Ireland is outside Schengen and applies its own rules. Ninety days visa-free has applied for tourism — confirm before travelling.', emergency: '112 or 999' },
    zh: { name: '爱尔兰', capital: '都柏林', languages: '英语、爱尔兰语', currency: '欧元',
      intro: '岛的东北部北爱尔兰属英国，其余为爱尔兰共和国。货币用欧元，但与英国一样靠左行驶，插头也是英式G型。',
      tip: '进入北爱尔兰后货币会变成英镑。边界没有检查站，很多人到付款时才发现已经越境。',
      visa: '爱尔兰不属申根区，另有规定。旅游目的曾可免签停留90天，出发前请确认条件。', emergency: '112 或 999' },
  },
  {
    slug: 'hungary', code: 'HU', icon: '🇭🇺', region: '유럽',
    utc: 1, tz: 'Europe/Budapest', dst: true, dial: '+36', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'HUF', tld: '.hu',
    ko: { name: '헝가리', capital: '부다페스트', languages: '헝가리어', currency: '포린트',
      intro: '도나우강이 부다페스트를 부다와 페스트로 갈라 놓습니다. 지하에 온천수가 흘러 도심에서 대형 목욕탕(세체니·겔레르트)에 들어갈 수 있습니다.',
      tip: '유럽연합이지만 유로를 쓰지 않고 포린트를 씁니다. 관광지에서 유로를 받더라도 환율이 불리한 경우가 많습니다.',
      visa: '솅겐 협정 국가로 180일 중 90일 무비자입니다. ETIAS 도입이 예정돼 있으므로 출발 전 확인하세요.', emergency: '112' },
    en: { name: 'Hungary', capital: 'Budapest', languages: 'Hungarian', currency: 'Forint',
      intro: 'The Danube splits Budapest into Buda and Pest. Thermal water runs beneath the city, which is why you can soak in grand baths like the Széchenyi and Gellért downtown.',
      tip: 'Hungary is in the EU but keeps the forint. Tourist spots may take euros, though usually at a poor rate.',
      visa: 'A Schengen state: 90 days in any 180 visa-free. ETIAS is being introduced, so check before travelling.', emergency: '112' },
    zh: { name: '匈牙利', capital: '布达佩斯', languages: '匈牙利语', currency: '福林',
      intro: '多瑙河把布达佩斯分成布达与佩斯两半。城下有温泉水流经，因此市区就有塞切尼、盖勒特等大型浴场。',
      tip: '虽属欧盟但不用欧元，而使用福林。旅游区即便收欧元，汇率通常也不划算。',
      visa: '申根国家，180天内可免签停留90天。ETIAS即将实施，出发前请确认。', emergency: '112' },
  },
  {
    slug: 'croatia', code: 'HR', icon: '🇭🇷', region: '유럽',
    utc: 1, tz: 'Europe/Zagreb', dst: true, dial: '+385', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'EUR', tld: '.hr',
    ko: { name: '크로아티아', capital: '자그레브', languages: '크로아티아어', currency: '유로',
      intro: '아드리아해를 따라 1,200개가 넘는 섬이 늘어서 있습니다. 2023년에 유로와 솅겐에 동시 가입해 통화와 국경 절차가 한꺼번에 바뀌었습니다.',
      tip: '해안선이 길어 도시 간 이동에 시간이 많이 듭니다. 자그레브에서 두브로브니크까지 육로로 여덟 시간이 넘습니다.',
      visa: '솅겐 협정 국가로 180일 중 90일 무비자입니다. ETIAS 도입이 예정돼 있으므로 출발 전 확인하세요.', emergency: '112' },
    en: { name: 'Croatia', capital: 'Zagreb', languages: 'Croatian', currency: 'Euro',
      intro: 'More than 1,200 islands line the Adriatic coast. Croatia joined both the euro and Schengen in 2023, changing currency and border procedure at once.',
      tip: 'The long coastline makes intercity travel slow — Zagreb to Dubrovnik is over eight hours by road.',
      visa: 'A Schengen state: 90 days in any 180 visa-free. ETIAS is being introduced, so check before travelling.', emergency: '112' },
    zh: { name: '克罗地亚', capital: '萨格勒布', languages: '克罗地亚语', currency: '欧元',
      intro: '亚得里亚海沿岸分布着1,200多座岛屿。该国于2023年同时加入欧元区与申根区，货币与边检手续一并改变。',
      tip: '海岸线狭长，城市间移动耗时较多。从萨格勒布到杜布罗夫尼克陆路超过八小时。',
      visa: '申根国家，180天内可免签停留90天。ETIAS即将实施，出发前请确认。', emergency: '112' },
  },
  {
    slug: 'slovenia', code: 'SI', icon: '🇸🇮', region: '유럽',
    utc: 1, tz: 'Europe/Ljubljana', dst: true, dial: '+386', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'EUR', tld: '.si',
    ko: { name: '슬로베니아', capital: '류블랴나', languages: '슬로베니아어', currency: '유로',
      intro: '알프스와 아드리아해, 카르스트 지형이 두 시간 거리 안에 모여 있습니다. 카르스트라는 지형 용어 자체가 이 나라 크라스 지역 이름에서 왔습니다.',
      tip: '고속도로를 쓰려면 비네트(통행 스티커)를 미리 사야 합니다. 없이 진입하면 과태료가 붙습니다.',
      visa: '솅겐 협정 국가로 180일 중 90일 무비자입니다. ETIAS 도입이 예정돼 있으므로 출발 전 확인하세요.', emergency: '112' },
    en: { name: 'Slovenia', capital: 'Ljubljana', languages: 'Slovene', currency: 'Euro',
      intro: 'The Alps, the Adriatic and karst country all sit within two hours of each other. The geological term “karst” itself comes from the Kras region here.',
      tip: 'Using the motorways requires a vignette bought in advance; entering without one brings a fine.',
      visa: 'A Schengen state: 90 days in any 180 visa-free. ETIAS is being introduced, so check before travelling.', emergency: '112' },
    zh: { name: '斯洛文尼亚', capital: '卢布尔雅那', languages: '斯洛文尼亚语', currency: '欧元',
      intro: '阿尔卑斯山、亚得里亚海与喀斯特地貌彼此相距不过两小时。地质学名词“喀斯特”正来自该国的克拉斯地区。',
      tip: '使用高速公路需提前购买通行贴（vignette），未购贴驶入会被罚款。',
      visa: '申根国家，180天内可免签停留90天。ETIAS即将实施，出发前请确认。', emergency: '112' },
  },
  {
    slug: 'slovakia', code: 'SK', icon: '🇸🇰', region: '유럽',
    utc: 1, tz: 'Europe/Bratislava', dst: true, dial: '+421', volt: '230V', hz: '50Hz', plug: 'C, E',
    drive: 'right', currencyCode: 'EUR', tld: '.sk',
    ko: { name: '슬로바키아', capital: '브라티슬라바', languages: '슬로바키아어', currency: '유로',
      intro: '1993년 체코와 갈라져 독립했고 수도 브라티슬라바가 오스트리아 국경에 붙어 있습니다. 빈에서 버스로 한 시간이면 닿습니다.',
      tip: '북부 타트라 산맥은 알프스보다 규모가 작지만 트레킹 코스가 잘 정비돼 있습니다. 겨울에는 스키장으로 바뀝니다.',
      visa: '솅겐 협정 국가로 180일 중 90일 무비자입니다. ETIAS 도입이 예정돼 있으므로 출발 전 확인하세요.', emergency: '112' },
    en: { name: 'Slovakia', capital: 'Bratislava', languages: 'Slovak', currency: 'Euro',
      intro: 'Independent from Czechia since 1993, with a capital that sits right on the Austrian border — an hour by bus from Vienna.',
      tip: 'The Tatra mountains in the north are smaller than the Alps but well served by trails, and turn into ski country in winter.',
      visa: 'A Schengen state: 90 days in any 180 visa-free. ETIAS is being introduced, so check before travelling.', emergency: '112' },
    zh: { name: '斯洛伐克', capital: '布拉迪斯拉发', languages: '斯洛伐克语', currency: '欧元',
      intro: '1993年与捷克分离独立，首都布拉迪斯拉发紧邻奥地利边界，从维也纳乘巴士一小时即可抵达。',
      tip: '北部的塔特拉山脉规模小于阿尔卑斯，但徒步路线完善，冬季则转为滑雪场。',
      visa: '申根国家，180天内可免签停留90天。ETIAS即将实施，出发前请确认。', emergency: '112' },
  },
  {
    slug: 'romania', code: 'RO', icon: '🇷🇴', region: '유럽',
    utc: 2, tz: 'Europe/Bucharest', dst: true, dial: '+40', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'RON', tld: '.ro',
    ko: { name: '루마니아', capital: '부쿠레슈티', languages: '루마니아어', currency: '레우',
      intro: '카르파티아 산맥이 국토를 감싸고 그 안쪽이 트란실바니아입니다. 브란 성이 드라큘라 이야기와 엮여 알려져 있습니다.',
      tip: '유럽연합이지만 통화는 레우입니다. 2025년에 솅겐 항공·해상 국경이 열려 육로 절차와 다를 수 있으니 경로별로 확인하세요.',
      visa: '솅겐 협정 국가로 180일 중 90일 무비자입니다. ETIAS 도입이 예정돼 있으므로 출발 전 확인하세요.', emergency: '112' },
    en: { name: 'Romania', capital: 'Bucharest', languages: 'Romanian', currency: 'Leu',
      intro: 'The Carpathians curve around the country, enclosing Transylvania. Bran Castle is the site most often tied to the Dracula story.',
      tip: 'Romania is in the EU but keeps the leu. Schengen air and sea borders opened in 2025 and may differ from land crossings, so check your route.',
      visa: 'A Schengen state: 90 days in any 180 visa-free. ETIAS is being introduced, so check before travelling.', emergency: '112' },
    zh: { name: '罗马尼亚', capital: '布加勒斯特', languages: '罗马尼亚语', currency: '列伊',
      intro: '喀尔巴阡山脉环抱国土，其内侧即为特兰西瓦尼亚。布兰城堡因与德拉库拉传说相连而知名。',
      tip: '虽属欧盟但货币为列伊。2025年申根空港与海港边界开放，与陆路手续可能不同，请按路线确认。',
      visa: '申根国家，180天内可免签停留90天。ETIAS即将实施，出发前请确认。', emergency: '112' },
  },
  {
    slug: 'bulgaria', code: 'BG', icon: '🇧🇬', region: '유럽',
    utc: 2, tz: 'Europe/Sofia', dst: true, dial: '+359', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'BGN', tld: '.bg',
    ko: { name: '불가리아', capital: '소피아', languages: '불가리아어', currency: '레프',
      intro: '키릴 문자가 이곳에서 만들어져 슬라브권으로 퍼졌습니다. 흑해 연안 해변과 릴라 수도원, 장미 계곡이 대표 목적지입니다.',
      tip: '고개를 끄덕이는 것이 부정, 좌우로 흔드는 것이 긍정인 관습이 남아 있습니다. 말로 확인하는 편이 안전합니다.',
      visa: '솅겐 협정 국가로 180일 중 90일 무비자입니다. ETIAS 도입이 예정돼 있으므로 출발 전 확인하세요.', emergency: '112' },
    en: { name: 'Bulgaria', capital: 'Sofia', languages: 'Bulgarian', currency: 'Lev',
      intro: 'The Cyrillic alphabet was devised here before spreading across the Slavic world. Black Sea beaches, Rila Monastery and the Valley of Roses draw most visitors.',
      tip: 'A nod can mean no and a shake can mean yes — the old convention persists in places, so confirm in words.',
      visa: 'A Schengen state: 90 days in any 180 visa-free. ETIAS is being introduced, so check before travelling.', emergency: '112' },
    zh: { name: '保加利亚', capital: '索非亚', languages: '保加利亚语', currency: '列弗',
      intro: '西里尔字母在此创制，随后传遍斯拉夫世界。黑海海滨、里拉修道院与玫瑰谷是主要目的地。',
      tip: '当地仍保留点头表示否定、摇头表示肯定的习惯，最好用言语再确认一次。',
      visa: '申根国家，180天内可免签停留90天。ETIAS即将实施，出发前请确认。', emergency: '112' },
  },
  {
    slug: 'serbia', code: 'RS', icon: '🇷🇸', region: '유럽',
    utc: 1, tz: 'Europe/Belgrade', dst: true, dial: '+381', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'RSD', tld: '.rs',
    ko: { name: '세르비아', capital: '베오그라드', languages: '세르비아어', currency: '디나르',
      intro: '도나우강과 사바강이 만나는 곳에 베오그라드가 있어 예부터 요새 도시였습니다. 유럽연합과 솅겐에 속하지 않아 국경 절차가 따로 있습니다.',
      tip: '키릴 문자와 라틴 문자를 함께 씁니다. 같은 지명이 두 문자로 적혀 있어 표지판이 달라 보일 수 있습니다.',
      visa: '관광 목적 90일 무비자로 알려져 있습니다. 솅겐 체류 일수와 별도로 계산되므로 유럽 일정 전체를 함께 보세요.', emergency: '112' },
    en: { name: 'Serbia', capital: 'Belgrade', languages: 'Serbian', currency: 'Dinar',
      intro: 'Belgrade stands where the Danube meets the Sava, which made it a fortress city for centuries. Serbia is outside the EU and Schengen, so borders are separate.',
      tip: 'Both Cyrillic and Latin scripts are in use, so the same place name can appear in two alphabets on different signs.',
      visa: 'Ninety days visa-free has applied for tourism. It counts separately from Schengen days, so plan the whole European trip together.', emergency: '112' },
    zh: { name: '塞尔维亚', capital: '贝尔格莱德', languages: '塞尔维亚语', currency: '第纳尔',
      intro: '贝尔格莱德位于多瑙河与萨瓦河交汇处，自古便是要塞城市。塞尔维亚不属欧盟与申根区，边检手续另计。',
      tip: '西里尔字母与拉丁字母并用，同一地名会以两种字母出现在不同标牌上。',
      visa: '旅游目的曾可免签停留90天。该天数与申根停留分别计算，请把整个欧洲行程一并规划。', emergency: '112' },
  },
  {
    slug: 'ukraine', code: 'UA', icon: '🇺🇦', region: '유럽',
    utc: 2, tz: 'Europe/Kyiv', dst: true, dial: '+380', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'UAH', tld: '.ua',
    ko: { name: '우크라이나', capital: '키이우', languages: '우크라이나어', currency: '흐리브냐',
      intro: '유럽에서 러시아를 빼면 국토가 가장 넓고 흑토 지대가 넓어 곡물 수출이 큽니다. 키이우의 성 소피아 대성당과 페체르스크 수도원이 세계유산입니다.',
      tip: '전쟁 상황에 따라 이동과 통신 사정이 크게 달라집니다. 여행을 계획하기 전에 외교부 여행경보 단계를 먼저 확인해야 합니다.',
      visa: '관광 목적 90일 무비자로 알려져 있으나 현재 정세로 실제 입국이 제한될 수 있습니다. 출발 전 반드시 최신 공지를 확인하세요.', emergency: '112' },
    en: { name: 'Ukraine', capital: 'Kyiv', languages: 'Ukrainian', currency: 'Hryvnia',
      intro: 'Excluding Russia, it is the largest country in Europe, and its black-earth belt makes it a major grain exporter. Kyiv’s Saint Sophia Cathedral and the Lavra are World Heritage sites.',
      tip: 'Movement and communications vary sharply with the war. Check your foreign ministry’s travel advisory before planning anything.',
      visa: 'Ninety days visa-free has applied for tourism, but entry may be restricted under current conditions — check the latest notice.', emergency: '112' },
    zh: { name: '乌克兰', capital: '基辅', languages: '乌克兰语', currency: '格里夫纳',
      intro: '除俄罗斯外为欧洲面积最大的国家，黑土带广阔，是重要的粮食出口国。基辅的圣索菲亚大教堂与洞窟修道院为世界遗产。',
      tip: '通行与通信状况会随战况大幅变化。规划旅行前应先查看本国外交部的旅行警示等级。',
      visa: '旅游目的曾可免签停留90天，但在当前局势下实际入境可能受限，出发前务必确认最新公告。', emergency: '112' },
  },
];
