/** 나라 정보 - 유럽 서부 (8) */
import type { Country } from './types.ts';

export const WEST_EUROPE: Country[] = [
  {
    slug: 'uk', code: 'GB', icon: '🇬🇧', region: '유럽',
    utc: 0, tz: 'Europe/London', dst: true, dial: '+44', volt: '230V', hz: '50Hz', plug: 'G',
    drive: 'left', currencyCode: 'GBP', tld: '.uk',     ko: { name: '영국', capital: '런던', languages: '영어', currency: '파운드',
      intro: '표준시의 기준이 된 그리니치가 있는 나라입니다. 3월 말부터 10월 말까지 서머타임을 적용해 한국과의 시차가 9시간에서 8시간으로 줄어듭니다.',
      tip: '플러그가 3구 G 타입으로 크고, 콘센트마다 개별 스위치가 달려 있습니다. 스위치를 켜지 않으면 전원이 들어오지 않습니다.',
      visa: '관광 목적 6개월 무비자이지만 전자여행허가(ETA)를 미리 받아야 합니다. 셰넨 협정과는 별개입니다.', emergency: '999 or 112' },
    en: { name: 'United Kingdom', capital: 'London', languages: 'English', currency: 'Pound sterling',
      intro: 'Home of Greenwich, the reference for standard time. Daylight saving runs from late March to late October, cutting the gap with Korea from nine hours to eight.',
      tip: 'The three-pin type G plug is bulky and each socket has its own switch — nothing powers on until you flip it.',
      visa: 'Six months visa-free for tourism, but an Electronic Travel Authorisation must be obtained first. The UK is outside the Schengen Area.', emergency: '999 or 112' },
    zh: { name: '英国', capital: '伦敦', languages: '英语', currency: '英镑',
      intro: '标准时间基准格林尼治所在的国家。3月底至10月底实行夏令时，与韩国的时差从9小时缩短为8小时。',
      tip: '三脚G型插头体积很大，且每个插座都有独立开关 — 不打开开关就不通电。',
      visa: '韩国护照旅游可免签停留6个月，但须提前申请电子旅行许可(ETA)。英国不属于申根区。', emergency: '999或112' },
  },
  {
    slug: 'france', code: 'FR', icon: '🇫🇷', region: '유럽',
    utc: 1, tz: 'Europe/Paris', dst: true, dial: '+33', volt: '230V', hz: '50Hz', plug: 'E',
    drive: 'right', currencyCode: 'EUR', tld: '.fr',     ko: { name: '프랑스', capital: '파리', languages: '프랑스어', currency: '유로',
      intro: '파리 외에도 남부 프로방스, 루아르 고성, 알프스가 각기 다른 여행 성격을 갖습니다. 고속철도 TGV로 대부분의 대도시가 세 시간 안에 연결됩니다.',
      tip: '박물관은 대개 월요일이나 화요일 중 하루를 휴관합니다. 파리 주요 미술관은 온라인 사전 예약이 사실상 필수입니다.',
      visa: '셰넨 협정에 따라 180일 중 90일 무비자. 소매치기가 많은 구간에서는 가방을 앞으로 두세요.', emergency: '112' },
    en: { name: 'France', capital: 'Paris', languages: 'French', currency: 'Euro',
      intro: 'Beyond Paris, Provence, the Loire châteaux and the Alps each offer a different kind of trip. TGV high-speed rail puts most major cities within three hours.',
      tip: 'Museums typically close one day a week, Monday or Tuesday. For the major Paris galleries, booking online ahead is effectively required.',
      visa: '90 days in any 180 under the Schengen rules. Keep bags in front of you on pickpocket-heavy routes.', emergency: '112' },
    zh: { name: '法国', capital: '巴黎', languages: '法语', currency: '欧元',
      intro: '除巴黎之外，南部普罗旺斯、卢瓦尔河谷城堡与阿尔卑斯各有不同的旅行气质。TGV高铁让大多数大城市都在三小时内。',
      tip: '博物馆通常每周休一天，周一或周二。巴黎主要美术馆基本必须提前网上预约。',
      visa: '依申根规定，每180天可免签90天。在扒手多的路段请把包背在身前。', emergency: '112' },
  },
  {
    slug: 'germany', code: 'DE', icon: '🇩🇪', region: '유럽',
    utc: 1, tz: 'Europe/Berlin', dst: true, dial: '+49', volt: '230V', hz: '50Hz', plug: 'F',
    drive: 'right', currencyCode: 'EUR', tld: '.de',     ko: { name: '독일', capital: '베를린', languages: '독일어', currency: '유로',
      intro: '연방제라 도시마다 성격이 크게 다릅니다. 베를린은 현대사, 뮌헨은 바이에른 문화, 라인강 일대는 성과 와인이 중심입니다.',
      tip: '일요일에는 대형 마트와 상점이 대부분 문을 닫습니다. 주말 장은 토요일에 미리 봐 두세요.',
      visa: '셰넨 협정에 따라 180일 중 90일 무비자. 현금만 받는 식당이 아직 적지 않습니다.', emergency: '110 경찰 · 112 구급' },
    en: { name: 'Germany', capital: 'Berlin', languages: 'German', currency: 'Euro',
      intro: 'A federal country whose cities differ sharply — Berlin for modern history, Munich for Bavarian culture, the Rhine for castles and wine.',
      tip: 'Supermarkets and most shops close on Sundays. Do your weekend shopping on Saturday.',
      visa: '90 days in any 180 under the Schengen rules. Cash-only restaurants are still fairly common.', emergency: '110 police · 112 ambulance' },
    zh: { name: '德国', capital: '柏林', languages: '德语', currency: '欧元',
      intro: '联邦制国家，各城市气质差异很大 — 柏林看现代史，慕尼黑看巴伐利亚文化，莱茵河沿线是城堡与葡萄酒。',
      tip: '周日超市和多数商店都关门。周末的采买请在周六完成。',
      visa: '依申根规定，每180天可免签90天。只收现金的餐馆仍然不少。', emergency: '110 警察 · 112 急救' },
  },
  {
    slug: 'italy', code: 'IT', icon: '🇮🇹', region: '유럽',
    utc: 1, tz: 'Europe/Rome', dst: true, dial: '+39', volt: '230V', hz: '50Hz', plug: 'F, L',
    drive: 'right', currencyCode: 'EUR', tld: '.it',     ko: { name: '이탈리아', capital: '로마', languages: '이탈리아어', currency: '유로',
      intro: '로마·피렌체·베네치아가 고속철도로 이어져 도시 이동이 쉽습니다. 남부는 여름이 매우 뜨거워 5~6월과 9~10월이 다니기 좋습니다.',
      tip: '플러그에 L 타입(세 핀 일렬)이 섞여 있어 어댑터가 안 맞는 숙소가 있습니다. 유럽용에 L 겸용을 챙기면 안전합니다.',
      visa: '셰넨 협정에 따라 180일 중 90일 무비자. 주요 도시 기차역 주변은 소매치기 신고가 많습니다.', emergency: '112' },
    en: { name: 'Italy', capital: 'Rome', languages: 'Italian', currency: 'Euro',
      intro: 'Rome, Florence and Venice are linked by high-speed rail, so hopping between them is easy. The south gets fiercely hot in summer, making May–June and September–October the better windows.',
      tip: 'Type L sockets (three pins in a row) turn up alongside type F, and some adapters will not fit — carry one that covers both.',
      visa: '90 days in any 180 under the Schengen rules. Pickpocketing is frequently reported around major stations.', emergency: '112' },
    zh: { name: '意大利', capital: '罗马', languages: '意大利语', currency: '欧元',
      intro: '罗马、佛罗伦萨和威尼斯由高铁相连，城市间往来方便。南部夏季酷热，5~6月和9~10月更适合出行。',
      tip: '除F型外还混有L型插座(三针一列)，部分转换头插不上 — 请带兼容两种的。',
      visa: '依申根规定，每180天可免签90天。主要火车站周边扒窃案件较多。', emergency: '112' },
  },
  {
    slug: 'spain', code: 'ES', icon: '🇪🇸', region: '유럽',
    utc: 1, tz: 'Europe/Madrid', dst: true, dial: '+34', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'EUR', tld: '.es',     ko: { name: '스페인', capital: '마드리드', languages: '스페인어, 카탈루냐어 등', currency: '유로',
      intro: '경도상으로는 영국과 비슷한데 중부유럽 시간대를 써서 해가 늦게 집니다. 여름 저녁 9시에도 밝아 저녁 식사가 늦습니다.',
      tip: '점심 후 시에스타로 오후에 문을 닫는 상점이 지역에 따라 있습니다. 식당 저녁 영업은 20시 이후에 시작하는 곳이 많습니다.',
      visa: '셰넨 협정에 따라 180일 중 90일 무비자. 바르셀로나 관광지 주변 소매치기에 주의하세요.', emergency: '112' },
    en: { name: 'Spain', capital: 'Madrid', languages: 'Spanish, Catalan and others', currency: 'Euro',
      intro: 'Spain sits at roughly British longitude but keeps Central European time, so the sun sets late — it is still bright at 9 pm in summer, which is why dinner is late.',
      tip: 'In some regions shops still close for a midday siesta, and many restaurants only start dinner service after 8 pm.',
      visa: '90 days in any 180 under the Schengen rules. Watch for pickpockets around Barcelona’s tourist sites.', emergency: '112' },
    zh: { name: '西班牙', capital: '马德里', languages: '西班牙语、加泰罗尼亚语等', currency: '欧元',
      intro: '经度与英国相近，却使用中欧时区，因此日落很晚 — 夏天晚上9点仍亮，晚餐也随之推迟。',
      tip: '部分地区商店仍有午后午休而关门，很多餐厅晚餐时段20点以后才开始。',
      visa: '依申根规定，每180天可免签90天。巴塞罗那景点周边请当心扒手。', emergency: '112' },
  },
  {
    slug: 'netherlands', code: 'NL', icon: '🇳🇱', region: '유럽',
    utc: 1, tz: 'Europe/Amsterdam', dst: true, dial: '+31', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'EUR', tld: '.nl',     ko: { name: '네덜란드', capital: '암스테르담', languages: '네덜란드어, 영어', currency: '유로',
      intro: '국토의 상당 부분이 해수면보다 낮아 운하와 제방이 도시 구조를 결정했습니다. 자전거가 주요 교통수단이라 전용 도로가 촘촘합니다.',
      tip: '자전거 도로에 서 있으면 위험합니다. 보행자 길과 자전거 길이 색으로 구분되니 반드시 확인하세요.',
      visa: '셰넨 협정에 따라 180일 중 90일 무비자. 대부분의 상점이 카드 결제만 받는 경우도 있습니다.', emergency: '112' },
    en: { name: 'Netherlands', capital: 'Amsterdam', languages: 'Dutch, English', currency: 'Euro',
      intro: 'Much of the country lies below sea level, and canals and dykes shaped the cities accordingly. Cycling is primary transport, with a dense network of dedicated lanes.',
      tip: 'Standing in a bike lane is genuinely dangerous — pavements and cycle paths are colour-coded, so check which you are on.',
      visa: '90 days in any 180 under the Schengen rules. Some shops accept cards only.', emergency: '112' },
    zh: { name: '荷兰', capital: '阿姆斯特丹', languages: '荷兰语、英语', currency: '欧元',
      intro: '大片国土低于海平面，运河与堤坝塑造了城市结构。自行车是主要交通工具，专用道网络密集。',
      tip: '站在自行车道上确实危险 — 人行道与自行车道以颜色区分，请务必确认。',
      visa: '依申根规定，每180天可免签90天。部分商店只接受刷卡。', emergency: '112' },
  },
  {
    slug: 'switzerland', code: 'CH', icon: '🇨🇭', region: '유럽',
    utc: 1, tz: 'Europe/Zurich', dst: true, dial: '+41', volt: '230V', hz: '50Hz', plug: 'C, J',
    drive: 'right', currencyCode: 'CHF', tld: '.ch',     ko: { name: '스위스', capital: '베른', languages: '독일어, 프랑스어, 이탈리아어, 로만슈어', currency: '스위스프랑',
      intro: '공용어가 네 개이고 지역마다 주로 쓰는 말이 다릅니다. 유로존이 아니라 프랑을 쓰지만 유로를 받는 곳도 있습니다.',
      tip: '플러그가 스위스 전용 J 타입입니다. 둥근 두 핀(C)은 들어가지만 세 핀 유럽 플러그는 맞지 않는 콘센트가 있습니다.',
      visa: '셰넨 협정에 따라 180일 중 90일 무비자. 산악 열차는 좌석 예약제인 구간이 있습니다.', emergency: '117 경찰 · 144 구급' },
    en: { name: 'Switzerland', capital: 'Bern', languages: 'German, French, Italian, Romansh', currency: 'Swiss franc',
      intro: 'Four official languages, with a different one dominant in each region. Switzerland is outside the eurozone and uses francs, though some places take euros.',
      tip: 'Sockets are the Swiss type J. Round two-pin (C) plugs fit, but some three-pin European plugs will not.',
      visa: '90 days in any 180 under the Schengen rules. Some mountain trains require seat reservations.', emergency: '117 police · 144 ambulance' },
    zh: { name: '瑞士', capital: '伯尔尼', languages: '德语、法语、意大利语、罗曼什语', currency: '瑞士法郎',
      intro: '有四种官方语言，各地区主用语言不同。瑞士不属欧元区，使用法郎，但部分场所也接受欧元。',
      tip: '插座为瑞士专用J型。圆形两脚(C型)可以插入，但部分三脚欧规插头插不上。',
      visa: '依申根规定，每180天可免签90天。部分山区列车需预订座位。', emergency: '117 警察 · 144 急救' },
  },
  {
    slug: 'austria', code: 'AT', icon: '🇦🇹', region: '유럽',
    utc: 1, tz: 'Europe/Vienna', dst: true, dial: '+43', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'EUR', tld: '.at',     ko: { name: '오스트리아', capital: '빈', languages: '독일어', currency: '유로',
      intro: '빈의 음악과 잘츠부르크·할슈타트의 알프스 풍경이 대표적입니다. 국토 대부분이 산지라 철도와 버스가 산 사이를 잇습니다.',
      tip: '카페에서는 자리에 앉으면 종업원이 주문을 받습니다. 물을 따로 주문하지 않으면 나오지 않는 곳이 많습니다.',
      visa: '셰넨 협정에 따라 180일 중 90일 무비자. 도시 간 이동은 ÖBB 철도 온라인 예약이 저렴합니다.', emergency: '133 경찰 · 144 구급' },
    en: { name: 'Austria', capital: 'Vienna', languages: 'German', currency: 'Euro',
      intro: 'Vienna’s music and the Alpine scenery of Salzburg and Hallstatt define most trips. The country is largely mountainous, with rail and bus threading between the ranges.',
      tip: 'In cafés you sit and wait for table service, and water usually only arrives if you order it.',
      visa: '90 days in any 180 under the Schengen rules. Booking ÖBB rail online is the cheaper way between cities.', emergency: '133 police · 144 ambulance' },
    zh: { name: '奥地利', capital: '维也纳', languages: '德语', currency: '欧元',
      intro: '维也纳的音乐与萨尔茨堡、哈尔施塔特的阿尔卑斯风光最具代表性。国土多山，铁路与巴士穿行于群山之间。',
      tip: '咖啡馆里落座后由服务员点单，不主动要水通常不会送上。',
      visa: '依申根规定，每180天可免签90天。城市间出行在ÖBB官网提前订票更便宜。', emergency: '133 警察 · 144 急救' },
  },
];
