/** 나라 정보 - 유럽 동부·발트·지중해 (10) */
import type { Country } from './types.ts';

export const EAST_EUROPE: Country[] = [
  {
    slug: 'russia', code: 'RU', icon: '🇷🇺', region: '유럽',
    utc: 3, tz: 'Europe/Moscow', dst: false, dial: '+7', volt: '220V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'RUB', tld: '.ru',
    ko: { name: '러시아', capital: '모스크바', languages: '러시아어', currency: '루블',
      intro: '세계에서 가장 넓은 나라로 시간대가 열한 개에 걸쳐 있습니다. 2014년에 서머타임을 없애 연중 같은 시각을 씁니다.',
      tip: '표에 적은 UTC+3은 모스크바 기준입니다. 블라디보스토크는 UTC+10이라 한국과 한 시간 차이밖에 나지 않습니다.',
      visa: '전자비자 등 제도가 정세에 따라 바뀌고 있습니다. 여행경보 단계와 항공편 사정을 함께 확인하세요.', emergency: '112' },
    en: { name: 'Russia', capital: 'Moscow', languages: 'Russian', currency: 'Rouble',
      intro: 'The largest country on earth, spanning eleven time zones. Russia abolished daylight saving in 2014 and keeps the same clock all year.',
      tip: 'The UTC+3 listed here is Moscow. Vladivostok runs on UTC+10, only an hour from Korean time.',
      visa: 'E-visa and other schemes shift with the political situation. Check travel advisories and flight availability together.', emergency: '112' },
  },
  {
    slug: 'estonia', code: 'EE', icon: '🇪🇪', region: '유럽',
    utc: 2, tz: 'Europe/Tallinn', dst: true, dial: '+372', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'EUR', tld: '.ee',
    ko: { name: '에스토니아', capital: '탈린', languages: '에스토니아어', currency: '유로',
      intro: '발트 3국 가운데 가장 북쪽에 있고 핀란드와 언어가 가깝습니다. 행정 절차를 거의 전부 온라인으로 옮긴 전자정부로 알려져 있습니다.',
      tip: '탈린에서 헬싱키까지 페리로 두 시간입니다. 두 도시를 묶어 도는 일정이 흔합니다.',
      visa: '솅겐 협정 국가로 180일 중 90일 무비자입니다. ETIAS 도입이 예정돼 있으므로 출발 전 확인하세요.', emergency: '112' },
    en: { name: 'Estonia', capital: 'Tallinn', languages: 'Estonian', currency: 'Euro',
      intro: 'The northernmost Baltic state, with a language close to Finnish. It is known for moving almost all government business online.',
      tip: 'Tallinn to Helsinki is a two-hour ferry, and pairing the two cities in one trip is common.',
      visa: 'A Schengen state: 90 days in any 180 visa-free. ETIAS is being introduced, so check before travelling.', emergency: '112' },
  },
  {
    slug: 'latvia', code: 'LV', icon: '🇱🇻', region: '유럽',
    utc: 2, tz: 'Europe/Riga', dst: true, dial: '+371', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'EUR', tld: '.lv',
    ko: { name: '라트비아', capital: '리가', languages: '라트비아어', currency: '유로',
      intro: '발트 3국의 가운데에 있고 리가 구시가가 세계유산입니다. 아르누보 건축이 유럽에서 가장 밀집한 도시로 꼽힙니다.',
      tip: '겨울에는 오후 4시면 어두워집니다. 실내 일정과 야외 일정을 낮 시간에 몰아 배치하는 편이 좋습니다.',
      visa: '솅겐 협정 국가로 180일 중 90일 무비자입니다. ETIAS 도입이 예정돼 있으므로 출발 전 확인하세요.', emergency: '112' },
    en: { name: 'Latvia', capital: 'Riga', languages: 'Latvian', currency: 'Euro',
      intro: 'The middle Baltic state, with Riga’s old town on the World Heritage list. The city holds one of the densest concentrations of Art Nouveau architecture in Europe.',
      tip: 'In winter it is dark by four in the afternoon. Pack the outdoor parts of a day into the daylight hours.',
      visa: 'A Schengen state: 90 days in any 180 visa-free. ETIAS is being introduced, so check before travelling.', emergency: '112' },
  },
  {
    slug: 'lithuania', code: 'LT', icon: '🇱🇹', region: '유럽',
    utc: 2, tz: 'Europe/Vilnius', dst: true, dial: '+370', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'EUR', tld: '.lt',
    ko: { name: '리투아니아', capital: '빌뉴스', languages: '리투아니아어', currency: '유로',
      intro: '발트 3국 가운데 가장 남쪽이고 셋 중 인구가 가장 많습니다. 리투아니아어는 현존하는 인도유럽어 가운데 고형을 많이 보존한 언어로 알려져 있습니다.',
      tip: '십자가 언덕과 쿠로니아 사구가 대표 목적지인데 둘 다 수도에서 멉니다. 렌터카나 장거리 버스를 미리 잡아 두세요.',
      visa: '솅겐 협정 국가로 180일 중 90일 무비자입니다. ETIAS 도입이 예정돼 있으므로 출발 전 확인하세요.', emergency: '112' },
    en: { name: 'Lithuania', capital: 'Vilnius', languages: 'Lithuanian', currency: 'Euro',
      intro: 'The southernmost and most populous of the Baltic states. Lithuanian is often cited as the living Indo-European language that preserves the most archaic features.',
      tip: 'The Hill of Crosses and the Curonian Spit are the signature sites, and both are far from the capital — book a car or long-distance bus ahead.',
      visa: 'A Schengen state: 90 days in any 180 visa-free. ETIAS is being introduced, so check before travelling.', emergency: '112' },
  },
  {
    slug: 'iceland', code: 'IS', icon: '🇮🇸', region: '유럽',
    utc: 0, tz: 'Atlantic/Reykjavik', dst: false, dial: '+354', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'ISK', tld: '.is',
    ko: { name: '아이슬란드', capital: '레이캬비크', languages: '아이슬란드어', currency: '크로나',
      intro: '북대서양 화산섬으로 지열로 난방과 발전을 거의 다 해결합니다. 서머타임을 쓰지 않아 연중 UTC와 같은 시각입니다.',
      tip: '여름에는 밤에도 밝고 겨울에는 낮이 네 시간대로 짧습니다. 오로라를 보려면 9월에서 3월에 가야 합니다.',
      visa: '솅겐 협정 국가로 180일 중 90일 무비자입니다. ETIAS 도입이 예정돼 있으므로 출발 전 확인하세요.', emergency: '112' },
    en: { name: 'Iceland', capital: 'Reykjavík', languages: 'Icelandic', currency: 'Króna',
      intro: 'A volcanic island in the North Atlantic that heats and powers itself almost entirely from geothermal sources. It keeps no daylight saving, so it stays on UTC year round.',
      tip: 'Summer nights barely darken while winter days run about four hours. Aurora season is September to March.',
      visa: 'A Schengen state: 90 days in any 180 visa-free. ETIAS is being introduced, so check before travelling.', emergency: '112' },
  },
  {
    slug: 'luxembourg', code: 'LU', icon: '🇱🇺', region: '유럽',
    utc: 1, tz: 'Europe/Luxembourg', dst: true, dial: '+352', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'EUR', tld: '.lu',
    ko: { name: '룩셈부르크', capital: '룩셈부르크', languages: '룩셈부르크어, 프랑스어, 독일어', currency: '유로',
      intro: '국토가 서울과 경기 일부를 합친 정도이고 인구도 적지만 유럽연합 기관 여러 곳이 들어와 있습니다. 2020년부터 전국 대중교통이 무료입니다.',
      tip: '기차·버스·트램 요금이 없어 교통비가 들지 않습니다. 다만 1등석과 국경을 넘는 구간은 요금이 붙습니다.',
      visa: '솅겐 협정 국가로 180일 중 90일 무비자입니다. ETIAS 도입이 예정돼 있으므로 출발 전 확인하세요.', emergency: '112' },
    en: { name: 'Luxembourg', capital: 'Luxembourg City', languages: 'Luxembourgish, French, German', currency: 'Euro',
      intro: 'Small in both area and population, yet home to several EU institutions. Since 2020 all public transport within the country has been free.',
      tip: 'Trains, buses and trams cost nothing, so transport is off the budget. First class and cross-border legs still charge.',
      visa: 'A Schengen state: 90 days in any 180 visa-free. ETIAS is being introduced, so check before travelling.', emergency: '112' },
  },
  {
    slug: 'malta', code: 'MT', icon: '🇲🇹', region: '유럽',
    utc: 1, tz: 'Europe/Malta', dst: true, dial: '+356', volt: '230V', hz: '50Hz', plug: 'G',
    drive: 'left', currencyCode: 'EUR', tld: '.mt',
    ko: { name: '몰타', capital: '발레타', languages: '몰타어, 영어', currency: '유로',
      intro: '시칠리아 남쪽 지중해에 있는 작은 섬나라로 유럽연합 회원국 가운데 가장 작습니다. 영국 통치의 영향으로 좌측통행과 영국식 G 플러그를 씁니다.',
      tip: '영어가 공용어라 의사소통이 쉽습니다. 여름에는 강수가 거의 없어 물이 귀하므로 숙소 사정을 확인하세요.',
      visa: '솅겐 협정 국가로 180일 중 90일 무비자입니다. ETIAS 도입이 예정돼 있으므로 출발 전 확인하세요.', emergency: '112' },
    en: { name: 'Malta', capital: 'Valletta', languages: 'Maltese, English', currency: 'Euro',
      intro: 'A small Mediterranean island nation south of Sicily and the smallest EU member state. British rule left it driving on the left with British type G plugs.',
      tip: 'English is an official language, which makes everything easier. Summer brings almost no rain and water is scarce, so check what your accommodation offers.',
      visa: 'A Schengen state: 90 days in any 180 visa-free. ETIAS is being introduced, so check before travelling.', emergency: '112' },
  },
  {
    slug: 'cyprus', code: 'CY', icon: '🇨🇾', region: '유럽',
    utc: 2, tz: 'Asia/Nicosia', dst: true, dial: '+357', volt: '230V', hz: '50Hz', plug: 'G',
    drive: 'left', currencyCode: 'EUR', tld: '.cy',
    ko: { name: '키프로스', capital: '니코시아', languages: '그리스어, 터키어', currency: '유로',
      intro: '지중해 동쪽 섬으로 수도 니코시아가 남북으로 갈려 있습니다. 유럽연합 회원국이지만 섬 북부는 실효 지배가 다릅니다.',
      tip: '남부와 북부를 오갈 때 검문소를 통과해야 하고 통화도 유로와 리라로 다릅니다. 렌터카는 보험 적용 범위를 확인하세요.',
      visa: '유럽연합 회원국이지만 솅겐에는 아직 완전히 편입되지 않았습니다. 조건이 다를 수 있으므로 출발 전 확인하세요.', emergency: '112' },
    en: { name: 'Cyprus', capital: 'Nicosia', languages: 'Greek, Turkish', currency: 'Euro',
      intro: 'An island in the eastern Mediterranean whose capital, Nicosia, is divided north from south. It is an EU member, but the north is under separate control.',
      tip: 'Crossing between south and north means passing a checkpoint, and the currencies differ — euro against lira. Check what your hire car insurance covers.',
      visa: 'Cyprus is an EU member but not yet fully in Schengen, so conditions can differ — check before travelling.', emergency: '112' },
  },
  {
    slug: 'albania', code: 'AL', icon: '🇦🇱', region: '유럽',
    utc: 1, tz: 'Europe/Tirane', dst: true, dial: '+355', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'ALL', tld: '.al',
    ko: { name: '알바니아', capital: '티라나', languages: '알바니아어', currency: '레크',
      intro: '아드리아해와 이오니아해를 따라 해변이 이어지고 물가가 유럽에서 낮은 편입니다. 오랜 폐쇄 정책이 끝난 뒤 관광이 빠르게 늘었습니다.',
      tip: '해안도로는 풍경이 좋지만 굽이가 많아 시간이 오래 걸립니다. 이동 시간을 지도상 거리보다 넉넉히 잡으세요.',
      visa: '관광 목적 90일 무비자로 알려져 있습니다. 솅겐 일수와 별도로 계산됩니다.', emergency: '112' },
    en: { name: 'Albania', capital: 'Tirana', languages: 'Albanian', currency: 'Lek',
      intro: 'Beaches run along both the Adriatic and Ionian coasts, and prices sit low by European standards. Tourism has grown quickly since the long years of isolation ended.',
      tip: 'The coast road is scenic but full of switchbacks, so allow far more time than the map distance suggests.',
      visa: 'Ninety days visa-free has applied for tourism, counted separately from Schengen days.', emergency: '112' },
  },
  {
    slug: 'bosnia-herzegovina', code: 'BA', icon: '🇧🇦', region: '유럽',
    utc: 1, tz: 'Europe/Sarajevo', dst: true, dial: '+387', volt: '230V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'BAM', tld: '.ba',
    ko: { name: '보스니아 헤르체고비나', capital: '사라예보', languages: '보스니아어, 크로아티아어, 세르비아어', currency: '전환 마르카',
      intro: '사라예보는 동서 문화가 겹쳐 이슬람 모스크와 정교회, 가톨릭 성당, 유대교 회당이 한 동네에 있습니다. 모스타르의 옛 다리가 세계유산입니다.',
      tip: '해안선이 20km밖에 안 되지만 네움에서 아드리아해에 닿습니다. 크로아티아를 지나다 이 구간에서 국경을 두 번 넘게 됩니다.',
      visa: '관광 목적 90일 무비자로 알려져 있습니다. 솅겐 일수와 별도로 계산됩니다.', emergency: '112' },
    en: { name: 'Bosnia and Herzegovina', capital: 'Sarajevo', languages: 'Bosnian, Croatian, Serbian', currency: 'Convertible mark',
      intro: 'Sarajevo layers East and West, with a mosque, an Orthodox church, a Catholic cathedral and a synagogue within a few streets. The old bridge at Mostar is World Heritage.',
      tip: 'The coastline is only about 20 km, reaching the Adriatic at Neum — driving through Croatia means crossing the border twice around it.',
      visa: 'Ninety days visa-free has applied for tourism, counted separately from Schengen days.', emergency: '112' },
  },
];
