/**
 * 나라 정보 — 뒤에 더한 열두 곳 (셋째 묶음).
 *
 * 전압·플러그·긴급전화는 위키백과의 해당 목록에서 확인해 넣었다. 기억으로 적으면
 * 반드시 몇 개가 틀리고, 틀린 긴급전화는 여행자를 실제로 위험하게 만든다.
 *
 * 목록 자체가 나라를 빠뜨리기도 한다. 처음에는 베네수엘라·잠비아·짐바브웨를
 * 넣으려 했는데 전기 표에서 그 세 나라를 확인하지 못했다. 확인 못 한 값을
 * 지어 넣는 대신 확인된 나라(니카라과·르완다·모나코)로 바꿨다.
 *
 * 표준시와 서머타임은 여기 적은 값을 검사가 IANA 자료와 대조한다. 파라과이는
 * 2024년에 서머타임을 없애고 UTC−3으로 고정했는데, 그런 변경이 있으면 검사가
 * 먼저 걸린다.
 */
import type { Country } from './types.ts';

export const EXTRA2_COUNTRIES: Country[] = [
  {
    slug: 'jamaica', code: 'JM', icon: '🇯🇲', region: '미주',
    utc: -5, tz: 'America/Jamaica', dst: false, dial: '+1876', volt: '110V', hz: '50Hz', plug: 'A, B',
    drive: 'left', currencyCode: 'JMD', tld: '.jm',
    ko: { name: '자메이카', capital: '킹스턴', languages: '영어(공용), 자메이카 파트와', currency: '자메이카 달러',
      intro: '카리브해에 있는 섬나라로, 레게 음악과 자메이카 파트와라는 고유한 말이 함께 자란 곳입니다. 북쪽 해안에 관광지가 몰려 있고 수도 킹스턴은 남쪽에 있습니다.',
      tip: '영국 식민지였던 흔적으로 차가 왼쪽으로 다닙니다. 전압이 110V인데 주파수는 50Hz라, 60Hz를 전제로 만든 기기는 그대로 쓰기 어렵습니다.',
      visa: '관광 목적 단기 체류는 무비자로 들어갑니다. 입국 카드를 온라인으로 미리 내면 심사가 빨라집니다.', emergency: '119 경찰 · 110 구급' },
    en: { name: 'Jamaica', capital: 'Kingston', languages: 'English (official), Jamaican Patois', currency: 'Jamaican dollar',
      intro: 'An island in the Caribbean where reggae and a language of its own, Jamaican Patois, grew up together. The resorts cluster along the north coast while Kingston, the capital, sits in the south.',
      tip: 'A legacy of British rule: traffic keeps to the left. Note that the supply is 110 V at 50 Hz, so appliances built for 60 Hz may not work as expected.',
      visa: 'Short tourist stays are visa-free for most visitors. Filing the immigration card online beforehand speeds up the queue.', emergency: '119 police · 110 ambulance' },
  },
  {
    slug: 'paraguay', code: 'PY', icon: '🇵🇾', region: '미주',
    utc: -3, tz: 'America/Asuncion', dst: false, dial: '+595', volt: '220V', hz: '50Hz', plug: 'A, B, C',
    drive: 'right', currencyCode: 'PYG', tld: '.py',
    ko: { name: '파라과이', capital: '아순시온', languages: '스페인어, 과라니어', currency: '과라니',
      intro: '남아메리카 한가운데 있는 내륙국으로, 스페인어와 원주민 말인 과라니어를 나란히 공용어로 씁니다. 남미에서 원주민 언어가 이만큼 널리 쓰이는 나라는 드뭅니다.',
      tip: '2024년에 서머타임을 없애고 UTC−3으로 고정했습니다. 오래된 여행 안내서의 시차 표는 한 시간씩 틀릴 수 있습니다.',
      visa: '관광 목적 단기 체류는 무비자입니다. 이과수 폭포는 국경 너머 아르헨티나·브라질 쪽으로 나눠져 있어 이동 계획을 미리 세우는 편이 좋습니다.', emergency: '911' },
    en: { name: 'Paraguay', capital: 'Asunción', languages: 'Spanish, Guaraní', currency: 'Guaraní',
      intro: 'A landlocked country in the middle of South America, with Spanish and the indigenous Guaraní side by side as official languages. Few countries on the continent use an indigenous language this widely.',
      tip: 'Paraguay dropped daylight saving in 2024 and now stays on UTC−3 year round. Older guidebooks may be an hour off.',
      visa: 'Short tourist stays are visa-free for most passports. The Iguazú falls straddle the borders with Argentina and Brazil, so plan the crossing in advance.', emergency: '911' },
  },
  {
    slug: 'el-salvador', code: 'SV', icon: '🇸🇻', region: '미주',
    utc: -6, tz: 'America/El_Salvador', dst: false, dial: '+503', volt: '115V', hz: '60Hz', plug: 'A, B',
    drive: 'right', currencyCode: 'USD', tld: '.sv',
    ko: { name: '엘살바도르', capital: '산살바도르', languages: '스페인어', currency: '미국 달러',
      intro: '중앙아메리카에서 가장 작은 나라이면서 인구 밀도는 가장 높습니다. 태평양 쪽 해안에 화산이 줄지어 있어 서핑과 등반을 함께 하러 오는 사람이 많습니다.',
      tip: '자국 통화 대신 미국 달러를 그대로 씁니다. 환전이 필요 없는 대신 잔돈이 귀해서 큰 지폐를 내면 거스름돈을 못 받는 일이 있습니다.',
      visa: '관광 목적 90일 무비자입니다. 중앙아메리카 4개국 협정(CA-4)이라 과테말라·온두라스·니카라과와 체류 기간을 함께 셉니다.', emergency: '911' },
    en: { name: 'El Salvador', capital: 'San Salvador', languages: 'Spanish', currency: 'US dollar',
      intro: 'The smallest country in Central America and the most densely populated. A line of volcanoes runs down the Pacific coast, which draws people who want to surf and climb on the same trip.',
      tip: 'The US dollar is the currency, so there is nothing to change — but small notes are scarce and paying with a large bill often means no change.',
      visa: 'Ninety days visa-free for tourism. Under the CA-4 agreement, that clock is shared with Guatemala, Honduras and Nicaragua.', emergency: '911' },
  },
  {
    slug: 'nicaragua', code: 'NI', icon: '🇳🇮', region: '미주',
    utc: -6, tz: 'America/Managua', dst: false, dial: '+505', volt: '120V', hz: '60Hz', plug: 'A, B',
    drive: 'right', currencyCode: 'NIO', tld: '.ni',
    ko: { name: '니카라과', capital: '마나과', languages: '스페인어', currency: '코르도바',
      intro: '중앙아메리카에서 면적이 가장 넓은 나라로, 안에 담수호가 두 개나 있습니다. 니카라과호 한가운데에는 화산 두 개가 솟은 오메테페 섬이 있습니다.',
      tip: '식민지 시절 도시 그라나다와 레온이 잘 남아 있고 둘 사이가 두 시간 거리입니다. 우기인 5월부터 10월 사이에는 오후에 소나기가 자주 옵니다.',
      visa: '관광 목적 90일 무비자이고 입국 시 소액의 관광카드 요금을 냅니다. CA-4 협정국이라 이웃 세 나라와 체류 기간을 함께 셉니다.', emergency: '118 경찰 · 128 구급' },
    en: { name: 'Nicaragua', capital: 'Managua', languages: 'Spanish', currency: 'Córdoba',
      intro: 'The largest country in Central America by area, with two freshwater lakes inside it. Ometepe, an island formed by two volcanoes, rises out of the middle of Lake Nicaragua.',
      tip: 'The colonial towns of Granada and León are both well preserved and about two hours apart. In the May-to-October wet season, afternoon downpours are routine.',
      visa: 'Ninety days visa-free for tourism, with a small tourist card fee on arrival. As a CA-4 country it shares that allowance with its three neighbours.', emergency: '118 police · 128 ambulance' },
  },
  {
    slug: 'senegal', code: 'SN', icon: '🇸🇳', region: '오세아니아·아프리카',
    utc: 0, tz: 'Africa/Dakar', dst: false, dial: '+221', volt: '230V', hz: '50Hz', plug: 'C, D, E, K',
    drive: 'right', currencyCode: 'XOF', tld: '.sn',
    ko: { name: '세네갈', capital: '다카르', languages: '프랑스어(공용), 월로프어', currency: '서아프리카 CFA 프랑',
      intro: '아프리카 대륙의 서쪽 끝에 있는 나라로, 수도 다카르가 대륙에서 가장 서쪽에 있는 큰 도시입니다. 공용어는 프랑스어지만 거리에서 실제로 오가는 말은 월로프어인 경우가 많습니다.',
      tip: '플러그가 C·D·E·K 네 종류나 섞여 있습니다. 만능 어댑터를 가져가는 편이 확실합니다.',
      visa: '관광 목적 90일 무비자입니다. 황열병 예방접종 증명서를 요구하는 경우가 있으니 출발 전에 확인하세요.', emergency: '17 경찰 · 18 소방' },
    en: { name: 'Senegal', capital: 'Dakar', languages: 'French (official), Wolof', currency: 'West African CFA franc',
      intro: 'At the western edge of the African continent, with Dakar as the westernmost major city on the mainland. French is the official language, but what you hear on the street is often Wolof.',
      tip: 'Four different socket types are in use — C, D, E and K. A universal adapter is the safe answer.',
      visa: 'Ninety days visa-free for tourism. Proof of yellow fever vaccination is sometimes requested, so check before you fly.', emergency: '17 police · 18 fire' },
  },
  {
    slug: 'ivory-coast', code: 'CI', icon: '🇨🇮', region: '오세아니아·아프리카',
    utc: 0, tz: 'Africa/Abidjan', dst: false, dial: '+225', volt: '230V', hz: '50Hz', plug: 'C, E',
    drive: 'right', currencyCode: 'XOF', tld: '.ci',
    ko: { name: '코트디부아르', capital: '야무수크로', languages: '프랑스어(공용)', currency: '서아프리카 CFA 프랑',
      intro: '서아프리카의 코코아 최대 생산국이고, 세계 코코아의 상당 부분이 이 나라에서 나옵니다. 법적 수도는 야무수크로이지만 정부 기관과 경제는 아비장에 몰려 있습니다.',
      tip: '나라 이름을 영어로 옮기지 않는 것이 원칙입니다. 정부가 1986년에 어느 언어에서든 Côte d’Ivoire로 부르도록 요청했습니다.',
      visa: '전자비자를 미리 받아 가는 방식이 일반적입니다. 황열병 예방접종 증명서가 입국 요건입니다.', emergency: '110 경찰 · 180 소방' },
    en: { name: 'Côte d’Ivoire', capital: 'Yamoussoukro', languages: 'French (official)', currency: 'West African CFA franc',
      intro: 'The world’s largest cocoa producer, supplying a substantial share of the global crop. Yamoussoukro is the official capital, but government and business are concentrated in Abidjan.',
      tip: 'The country’s name is deliberately left untranslated: since 1986 the government has asked that it be called Côte d’Ivoire in every language.',
      visa: 'An e-visa arranged in advance is the usual route, and proof of yellow fever vaccination is required to enter.', emergency: '110 police · 180 fire' },
  },
  {
    slug: 'cameroon', code: 'CM', icon: '🇨🇲', region: '오세아니아·아프리카',
    utc: 1, tz: 'Africa/Douala', dst: false, dial: '+237', volt: '220V', hz: '50Hz', plug: 'C, E',
    drive: 'right', currencyCode: 'XAF', tld: '.cm',
    ko: { name: '카메룬', capital: '야운데', languages: '프랑스어, 영어', currency: '중앙아프리카 CFA 프랑',
      intro: '사막부터 열대우림까지 아프리카의 여러 지형이 한 나라 안에 모여 있어 "작은 아프리카"라고 불립니다. 프랑스어와 영어를 함께 공용어로 쓰는 드문 나라이기도 합니다.',
      tip: '지역에 따라 통하는 언어가 갈립니다. 북서·남서 지역은 영어권이고 나머지는 프랑스어권이라, 가는 곳에 맞춰 준비하는 편이 좋습니다.',
      visa: '관광 비자를 미리 받아야 합니다. 황열병 예방접종 증명서가 입국 요건입니다.', emergency: '112' },
    en: { name: 'Cameroon', capital: 'Yaoundé', languages: 'French, English', currency: 'Central African CFA franc',
      intro: 'Often called “Africa in miniature” because desert, savannah, mountain and rainforest all sit inside one country. It is also one of the few states with both French and English as official languages.',
      tip: 'Which language works depends on where you are: the North-West and South-West regions are anglophone and the rest is francophone.',
      visa: 'A tourist visa must be obtained in advance, and proof of yellow fever vaccination is required on entry.', emergency: '112' },
  },
  {
    slug: 'rwanda', code: 'RW', icon: '🇷🇼', region: '오세아니아·아프리카',
    utc: 2, tz: 'Africa/Kigali', dst: false, dial: '+250', volt: '230V', hz: '50Hz', plug: 'C, E, G',
    drive: 'right', currencyCode: 'RWF', tld: '.rw',
    ko: { name: '르완다', capital: '키갈리', languages: '키냐르완다어, 영어, 프랑스어, 스와힐리어', currency: '르완다 프랑',
      intro: '언덕이 끝없이 이어져 "천 개 언덕의 나라"로 불립니다. 화산 국립공원의 산악고릴라 탐방이 이 나라를 찾는 큰 이유입니다.',
      tip: '비닐봉지 반입이 금지되어 있어 공항에서 압수합니다. 짐을 쌀 때 비닐 대신 천 주머니를 쓰세요.',
      visa: '도착 비자를 받거나 전자비자로 미리 받습니다. 아프리카 대륙 밖에서 오는 여행자도 대부분 받을 수 있습니다.', emergency: '112' },
    en: { name: 'Rwanda', capital: 'Kigali', languages: 'Kinyarwanda, English, French, Swahili', currency: 'Rwandan franc',
      intro: 'Known as the land of a thousand hills, and the terrain lives up to it. Tracking mountain gorillas in Volcanoes National Park is what brings most visitors.',
      tip: 'Plastic bags are banned and are confiscated at the airport. Pack with cloth bags instead.',
      visa: 'A visa on arrival or an e-visa arranged beforehand covers most nationalities, including travellers from outside Africa.', emergency: '112' },
  },
  {
    slug: 'iraq', code: 'IQ', icon: '🇮🇶', region: '서·남아시아',
    utc: 3, tz: 'Asia/Baghdad', dst: false, dial: '+964', volt: '230V', hz: '50Hz', plug: 'C, D, G',
    drive: 'right', currencyCode: 'IQD', tld: '.iq',
    ko: { name: '이라크', capital: '바그다드', languages: '아랍어, 쿠르드어', currency: '이라크 디나르',
      intro: '티그리스와 유프라테스 두 강 사이의 땅으로, 문자와 도시와 법이 처음 생긴 메소포타미아가 여기입니다. 아랍어와 쿠르드어를 함께 공용어로 씁니다.',
      tip: '북부 쿠르드 자치구는 비자와 안전 상황이 다른 지역과 따로 굴러갑니다. 어디로 가느냐에 따라 준비가 완전히 달라집니다.',
      visa: '지역에 따라 절차가 갈리고 상황이 자주 바뀝니다. 출발 전에 외교부 여행경보와 현지 공관 안내를 반드시 확인하세요.', emergency: '112 · 122 구급' },
    en: { name: 'Iraq', capital: 'Baghdad', languages: 'Arabic, Kurdish', currency: 'Iraqi dinar',
      intro: 'The land between the Tigris and the Euphrates — Mesopotamia, where writing, cities and written law first appeared. Arabic and Kurdish are both official.',
      tip: 'The Kurdistan Region in the north runs its own entry rules and has its own security picture, so preparation depends entirely on where you are headed.',
      visa: 'Procedures differ by region and change often. Check your foreign ministry’s advisory and the nearest mission before travelling.', emergency: '112 · 122 ambulance' },
  },
  {
    slug: 'lebanon', code: 'LB', icon: '🇱🇧', region: '서·남아시아',
    utc: 2, tz: 'Asia/Beirut', dst: true, dial: '+961', volt: '220V', hz: '50Hz', plug: 'A, B, C, D, G',
    drive: 'right', currencyCode: 'LBP', tld: '.lb',
    ko: { name: '레바논', capital: '베이루트', languages: '아랍어(공용), 프랑스어, 영어', currency: '레바논 파운드',
      intro: '지중해 동쪽 끝의 작은 나라로, 해안에서 산까지 한 시간이면 닿습니다. 겨울에는 아침에 스키를 타고 오후에 바다에 갈 수 있다는 말이 실제로 성립합니다.',
      tip: '플러그가 다섯 종류나 섞여 있고 정전이 잦아 숙소마다 발전기 사정이 다릅니다. 보조배터리를 넉넉히 챙기세요.',
      visa: '국적에 따라 도착 비자 또는 사전 비자입니다. 이스라엘 입국 흔적이 있는 여권은 입국이 거부됩니다.', emergency: '112 · 140 적십자' },
    en: { name: 'Lebanon', capital: 'Beirut', languages: 'Arabic (official), French, English', currency: 'Lebanese pound',
      intro: 'A small country at the eastern end of the Mediterranean where the coast and the mountains are an hour apart. In winter the claim that you can ski in the morning and swim in the afternoon actually holds.',
      tip: 'Five socket types are in circulation and power cuts are frequent, so generator arrangements vary by building. Bring plenty of battery capacity.',
      visa: 'Visa on arrival or in advance depending on nationality. Passports showing entry to Israel are refused.', emergency: '112 · 140 Red Cross' },
  },
  {
    slug: 'kyrgyzstan', code: 'KG', icon: '🇰🇬', region: '서·남아시아',
    utc: 6, tz: 'Asia/Bishkek', dst: false, dial: '+996', volt: '220V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'KGS', tld: '.kg',
    ko: { name: '키르기스스탄', capital: '비슈케크', languages: '키르기스어, 러시아어', currency: '솜',
      intro: '국토의 대부분이 해발 1,500m를 넘는 산악 국가입니다. 이식쿨 호수는 산으로 둘러싸인 큰 호수인데도 겨울에 얼지 않아 이름 자체가 "따뜻한 호수"라는 뜻입니다.',
      tip: '여름철 산간 지역에는 유목민의 이동식 천막 유르트에서 묵는 숙소가 많습니다. 밤에는 8월에도 영하로 떨어지니 침낭이 필요합니다.',
      visa: '관광 목적 60일 무비자입니다. 중국·타지키스탄 국경 지대는 별도 허가가 필요한 구간이 있습니다.', emergency: '112' },
    en: { name: 'Kyrgyzstan', capital: 'Bishkek', languages: 'Kyrgyz, Russian', currency: 'Som',
      intro: 'A mountain country where most of the land sits above 1,500 m. Lake Issyk-Kul, ringed by peaks, never freezes in winter — its name means “warm lake”.',
      tip: 'In summer much of the high-country lodging is in yurts, the nomads’ portable tents. Nights drop below freezing even in August, so bring a sleeping bag.',
      visa: 'Sixty days visa-free for tourism. Some border zones near China and Tajikistan need a separate permit.', emergency: '112' },
  },
  {
    slug: 'monaco', code: 'MC', icon: '🇲🇨', region: '유럽',
    utc: 1, tz: 'Europe/Monaco', dst: true, dial: '+377', volt: '230V', hz: '50Hz', plug: 'C, E',
    drive: 'right', currencyCode: 'EUR', tld: '.mc',
    ko: { name: '모나코', capital: '모나코', languages: '프랑스어(공용)', currency: '유로',
      intro: '바티칸 다음으로 작은 나라로, 넓이가 2제곱킬로미터 남짓입니다. 나라 전체가 도시 하나여서 수도의 이름도 나라 이름과 같습니다.',
      tip: '유럽연합 회원국이 아닌데도 유로를 쓰고 국경 검문이 없습니다. 프랑스 니스에서 기차로 20분이면 닿습니다.',
      visa: '솅겐 지역과 같은 규칙이 적용됩니다. 프랑스를 거쳐 들어가므로 솅겐 체류 일수에 함께 셉니다.', emergency: '17 경찰 · 18 소방' },
    en: { name: 'Monaco', capital: 'Monaco', languages: 'French (official)', currency: 'Euro',
      intro: 'The second-smallest country in the world after the Vatican, covering barely two square kilometres. The whole state is a single city, so the capital carries the same name.',
      tip: 'Monaco is not in the European Union yet uses the euro and has no border checks. It is twenty minutes by train from Nice.',
      visa: 'Schengen rules apply. Because you enter through France, the days count against your Schengen allowance.', emergency: '17 police · 18 fire' },
  },
];
