/** 나라 정보 - 오세아니아·아프리카 (5) */
import type { Country } from './types.ts';

export const OCEANIA_AFRICA: Country[] = [
  {
    slug: 'australia', code: 'AU', icon: '🇦🇺', region: '오세아니아·아프리카',
    utc: 10, tz: 'Australia/Sydney', dst: true, dial: '+61', volt: '230V', hz: '50Hz', plug: 'I',
    drive: 'left', currencyCode: 'AUD', tld: '.au',     ko: { name: '오스트레일리아', capital: '캔버라', languages: '영어', currency: '호주달러',
      intro: '남반구라 계절이 한국과 반대이고, 시간대가 셋에 서머타임을 주별로 달리 적용해 국내 이동 시 시각이 어긋납니다. 표의 UTC+10은 시드니 기준입니다.',
      tip: '플러그가 I 타입(비스듬한 세 핀)으로 한국 어댑터가 맞지 않습니다. 자외선이 매우 강해 흐린 날에도 자외선 차단이 필요합니다.',
      visa: '무비자 입국은 되지 않습니다. 관광은 ETA 또는 eVisitor를 미리 받아야 합니다.', emergency: '000' },
    en: { name: 'Australia', capital: 'Canberra', languages: 'English', currency: 'Australian dollar',
      intro: 'Southern hemisphere seasons, three time zones, and daylight saving applied differently by state — domestic hops can shift the clock. The UTC+10 listed here is Sydney.',
      tip: 'Type I sockets with angled pins mean Korean adapters will not fit. UV is intense enough that sun protection matters even on cloudy days.',
      visa: 'There is no visa-free entry — tourists need an ETA or eVisitor approved in advance.', emergency: '000' },
    zh: { name: '澳大利亚', capital: '堪培拉', languages: '英语', currency: '澳元',
      intro: '南半球季节与韩国相反，全国三个时区且各州夏令时不一，国内飞行常会改变时刻。表中UTC+10为悉尼时间。',
      tip: '插座为I型(三枚斜脚)，韩国转换头插不上。紫外线极强，即使阴天也需要防晒。',
      visa: '没有免签入境 — 旅游须提前获批ETA或eVisitor。', emergency: '000' },
  },
  {
    slug: 'new-zealand', code: 'NZ', icon: '🇳🇿', region: '오세아니아·아프리카',
    utc: 12, tz: 'Pacific/Auckland', dst: true, dial: '+64', volt: '230V', hz: '50Hz', plug: 'I',
    drive: 'left', currencyCode: 'NZD', tld: '.nz',     ko: { name: '뉴질랜드', capital: '웰링턴', languages: '영어, 마오리어', currency: '뉴질랜드달러',
      intro: '날짜변경선에 가까워 세계에서 새해를 가장 먼저 맞는 나라 중 하나입니다. 남섬의 산악 풍경과 북섬의 화산·온천이 서로 다른 여행을 만듭니다.',
      tip: '입국 시 식품과 흙 묻은 등산화에 대한 검역이 매우 엄격합니다. 신고하지 않으면 즉시 과태료가 부과됩니다.',
      visa: '무비자 입국은 되지 않습니다. 관광은 NZeTA를 미리 받아야 하고 관광세도 함께 납부합니다.', emergency: '111' },
    en: { name: 'New Zealand', capital: 'Wellington', languages: 'English, Māori', currency: 'New Zealand dollar',
      intro: 'Close to the date line, it is among the first countries into each new year. The South Island’s mountains and the North Island’s volcanoes and hot springs make two different trips.',
      tip: 'Biosecurity checks on food and muddy hiking boots are strict — failing to declare brings an instant fine.',
      visa: 'No visa-free entry: tourists need an approved NZeTA, which includes the visitor levy.', emergency: '111' },
    zh: { name: '新西兰', capital: '惠灵顿', languages: '英语、毛利语', currency: '新西兰元',
      intro: '靠近日界线，是全球最早迎接新年的国家之一。南岛的山地风光与北岛的火山温泉是两种不同的旅行。',
      tip: '入境对食品和沾泥登山鞋的生物安检非常严格 — 未申报会立即罚款。',
      visa: '没有免签入境：旅游须提前获批NZeTA，并同时缴纳旅游税。', emergency: '111' },
  },
  {
    slug: 'egypt', code: 'EG', icon: '🇪🇬', region: '오세아니아·아프리카',
    utc: 2, tz: 'Africa/Cairo', dst: true, dial: '+20', volt: '220V', hz: '50Hz', plug: 'C, F',
    drive: 'right', currencyCode: 'EGP', tld: '.eg',     ko: { name: '이집트', capital: '카이로', languages: '아라비아어', currency: '이집트파운드',
      intro: '기자의 피라미드와 룩소르 신전, 나일강 크루즈가 여행의 축입니다. 여름은 40도를 넘어 10~4월이 다니기 좋습니다.',
      tip: '유적지에서 사진 촬영에 별도 요금을 받는 곳이 있습니다. 안내인이 붙는 경우 사전에 금액을 정하는 편이 분쟁이 적습니다.',
      visa: '도착비자 또는 전자비자가 필요합니다. 무비자 입국은 되지 않습니다.', emergency: '122 경찰 · 123 구급' },
    en: { name: 'Egypt', capital: 'Cairo', languages: 'Arabic', currency: 'Egyptian pound',
      intro: 'The Giza pyramids, the temples at Luxor and a Nile cruise anchor most trips. Summer passes 40°C, so October to April is the comfortable window.',
      tip: 'Some sites charge separately for photography. If a guide attaches himself to you, agree the fee up front to avoid a dispute.',
      visa: 'A visa on arrival or e-visa is required; there is no visa-free entry.', emergency: '122 police · 123 ambulance' },
    zh: { name: '埃及', capital: '开罗', languages: '阿拉伯语', currency: '埃及镑',
      intro: '吉萨金字塔、卢克索神庙和尼罗河游船是行程主轴。夏季超过40度，10月至次年4月更适合出行。',
      tip: '部分遗址对拍照单独收费。若有导游主动跟随，请事先谈好价格以免纠纷。',
      visa: '需办理落地签或电子签证，没有免签入境。', emergency: '122 警察 · 123 急救' },
  },
  {
    slug: 'south-africa', code: 'ZA', icon: '🇿🇦', region: '오세아니아·아프리카',
    utc: 2, tz: 'Africa/Johannesburg', dst: false, dial: '+27', volt: '230V', hz: '50Hz', plug: 'D, M, N',
    drive: 'left', currencyCode: 'ZAR', tld: '.za',     ko: { name: '남아프리카공화국', capital: '프리토리아(행정)', languages: '영어, 아프리칸스어 외 다수', currency: '랜드',
      intro: '수도가 셋으로 나뉘어 행정은 프리토리아, 입법은 케이프타운, 사법은 블룸폰테인입니다. 공용어가 11개를 넘습니다.',
      tip: '플러그가 남아공 전용 M 타입(굵은 세 핀)이라 대부분의 여행용 어댑터가 맞지 않습니다. 현지에서 구하는 편이 확실합니다.',
      visa: '무비자 입국이 가능하지만 허용 기간과 조건이 바뀔 수 있습니다. 출발 전 대사관 공지를 확인하세요.', emergency: '10111 경찰 · 10177 구급' },
    en: { name: 'South Africa', capital: 'Pretoria (administrative)', languages: 'English, Afrikaans and others', currency: 'Rand',
      intro: 'Three capitals split the functions: Pretoria administers, Cape Town legislates, Bloemfontein judges. There are more than eleven official languages.',
      tip: 'The local type M plug has three thick pins that most travel adapters do not fit — buying one locally is the reliable option.',
      visa: 'Visa-free entry is available, but the permitted period and conditions can change — check the embassy notice before departure.', emergency: '10111 police · 10177 ambulance' },
    zh: { name: '南非', capital: '比勒陀利亚(行政)', languages: '英语、南非荷兰语等', currency: '兰特',
      intro: '三个首都分担职能：比勒陀利亚行政、开普敦立法、布隆方丹司法。官方语言超过十一种。',
      tip: '当地M型插头为三枚粗针，多数旅行转换头都插不上 — 在当地购买最稳妥。',
      visa: '可免签入境，但允许期限和条件可能变化 — 出发前请查看使馆公告。', emergency: '10111 警察 · 10177 急救' },
  },
  {
    slug: 'morocco', code: 'MA', icon: '🇲🇦', region: '오세아니아·아프리카',
    utc: 1, tz: 'Africa/Casablanca', dst: false, dial: '+212', volt: '220V', hz: '50Hz', plug: 'C, E',
    drive: 'right', currencyCode: 'MAD', tld: '.ma',     ko: { name: '모로코', capital: '라바트', languages: '아라비아어, 베르베르어, 프랑스어', currency: '디르함',
      intro: '2018년부터 연중 UTC+1을 쓰지만 라마단 기간에만 한 시간 되돌립니다. 마라케시의 메디나와 사하라 사막 투어가 대표 코스입니다.',
      tip: '메디나(구시가) 골목은 지도가 잘 통하지 않을 만큼 복잡합니다. 숙소 위치를 사진으로 남겨 두는 편이 좋습니다.',
      visa: '관광 목적 90일 무비자. 현지 통화는 국외 반출이 제한되니 남은 돈은 출국 전에 환전하세요.', emergency: '190 경찰 · 150 구급' },
    en: { name: 'Morocco', capital: 'Rabat', languages: 'Arabic, Berber, French', currency: 'Dirham',
      intro: 'Since 2018 the country stays on UTC+1 year-round, stepping back an hour only during Ramadan. Marrakesh’s medina and Sahara tours lead most itineraries.',
      tip: 'Medina alleys are tangled enough that maps struggle — photograph your accommodation’s location before setting out.',
      visa: '90 days visa-free for tourism. Taking dirhams out of the country is restricted, so change what is left before you fly.', emergency: '190 police · 150 ambulance' },
    zh: { name: '摩洛哥', capital: '拉巴特', languages: '阿拉伯语、柏柏尔语、法语', currency: '迪拉姆',
      intro: '自2018年起全年使用UTC+1，仅在斋月期间回调一小时。马拉喜什的老城与撒哈拉沙漠团是主要路线。',
      tip: '老城(麦地那)巷道错综复杂，地图常常不管用 — 出门前先拍下住宿位置。',
      visa: '韩国护照旅游可免签停留90天。当地货币限制携出，剩余现金请在离境前兑换。', emergency: '190 警察 · 150 急救' },
  },
];
